FRRouting/frr

bgpd/bgp_updgrp_adv.c
tests/topotests/bgp_max_med_on_startup/r1/bgpd.conf
tests/topotests/bgp_max_med_on_startup/r1/zebra.conf
tests/topotests/bgp_max_med_on_startup/r2/bgpd.conf
tests/topotests/bgp_max_med_on_startup/r2/zebra.conf
tests/topotests/bgp_max_med_on_startup/test_bgp_max_med_on_startup.py

Currently, if `bgp max-med on-startup` is configured, after BGP session is established for the first time, a timer for the specified time is started. When the timer is expired, an UPDATE message should be sent to reflect changes in the routes' MED value. The problem is that the routes are being suppressed because based on the attributes they look like they have not changed. However, in the case of max-med, the value is copied to the packet directly from `bgp->maxmed_value`, not from the attributes. Thus, changes in this case cannot be detected by comparing attributes.
With this fix, avoid route suppressing when the `max-med on-startup` timer expires and initiates an UPDATE.
Signed-off-by: Alexander Chernavin <achernavin@netgate.com>

bgpd: fix "bgp max-med on-startup"

---

lib/frrscript.c
lib/frrscript.h
lib/libfrr.c
ripd/ripd.c
ripngd/ripngd.c
staticd/static_main.c
zebra/main.c
zebra/zebra_evpn_mh.c

Some memory leaks on shutdown being fixed

General mayhem

---

.github/workflows/conflicts.yml

Just to quickly identify which PRs needs attention on rebasing.

github: Add `conflicts`/`no_conflicts` labels for PRs

---

snapcraft/snapcraft.yaml.in

It looks like frr gets built and published to snapcraft.io for a bunch of different architectures, but unfortunately on those other than x86, libssh.so doesn't get primed effectively, so on arm64, for instance, you end up with errors like 
`frr.bgpd[59989]: frr_init: loader error: dlopen(/snap/frr/x1/lib/frr/modules/bgpd_rpki.so): libssh.so.4: cannot open shared object file: No such file or directory` 
This tweak should make sure the .so file gets included on all architectures.

snapcraft: fix staging libssh on non-x86 arches

---

configure.ac
doc/user/isisd.rst
isisd/isis_cli.c
isisd/isis_lsp.c
isisd/isis_lsp.h
isisd/isis_nb.c
isisd/isis_nb.h
isisd/isis_nb_config.c
isisd/isisd.c
isisd/isisd.h
tests/topotests/isis_topo1/test_isis_topo1.py
yang/frr-isisd.yang

Adding support for set-overload on-startup.
YANG changes: Converted the existing overload leaf into a container to add a sub-config for set overload on startup.
Example CLI behavior:
```
unet> sh r1 vtysh
Hello, this is FRRouting (version 8.4-dev-my-manual-build).
r1# show running-config 
Building configuration...
!
frr version 8.4-dev-my-manual-build
hostname r1
...
router isis 1
exit
!
end
r1# conf
r1(config)#  router isis 1
r1(config-router)# set-overload-bit 
r1(config-router)# set-overload-bit 
<cr>        
on-startup  Set overload bit on startup
r1(config-router)# set-overload-bit on-startup 
(0-86400)  Set overload time in seconds
r1(config-router)# set-overload-bit …
```

isisd: Add support for set-overload on-startup

---

bgpd/bgp_vty.c
ldpd/ldp_vty_cmds.c
lib/command.c
lib/command.h
lib/command_graph.c
lib/command_graph.h
lib/command_match.c
lib/command_py.c
lib/grammar_sandbox.c
lib/log_vty.c
pimd/pim6_mld.c
pimd/pim_cmd.c
python/clippy/__init__.py
python/makefile.py
python/xrelfo.py
tools/permutations.c
vrrpd/vrrp_vty.c
vtysh/vtysh.c
zebra/zebra_fpm.c

- simplifying / detangling / removing unused `DEFUN` macros
- make `CMD_ATTR_*` a bitmask
- fix a bunch of b0rked CLI docstrings
- fix 2 b0rked CLI command definitions
- exclude vtysh from `frr.xref`
- use faster `ujson` for handling `.xref` files, if it's available
This is all prep work for replacing `vtysh/extract.pl` with extracting the commands from `frr.xref` instead.
NB: some of the python files related to this aren't black-formatted yet. I will do that *AFTER* the `frr.xref` changes (which are already in the oven, so I'd trample over my own changes.)

*: clean up various CLI-related bits

---

bgpd/bgp_mplsvpn.c

This PR adds a missing debug guard.

bgpd: Add missing debug guard in SRv6 L3VPN code

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_private.h
bgpd/bgp_evpn_vty.c
bgpd/bgp_routemap.c
bgpd/bgpd.h
doc/user/bgp.rst
lib/prefix.c
lib/prefix.h
lib/routemap.c

------------------------------------------------------------------------------
These patches add support a few different things with L3 Route-Targets.
- Add user configured import/export RTs and still retain auto configuration via new `route-target [import|export|both] auto` command
- Add multiple RTs via list format in the `route-target [import|export|both] RTLIST command`
- Add new WILDCARD import RT type specified via `route-target import *:101004` which allows you to import an L3 RT from any AS. This behaves very similarly to the auto RT and is implemented the same way as well by just setting the beginning port of the RT to 0.
- Add a `no` form of command to `advertise ipvX route-map MAP`
- Add support for filtering outbound Type5 and Type2 routes via a prefix list in a route-map of …

bgpd: EVPN D-VNI L3 RT Config Enhancements

---

ospfd/ospf_spf.c

Fix CID 1526337: (SIZEOF_MISMATCH)
Needs to pass the correct length to the function.

ospfd: pass the length of string to function

---

ospf6d/ospf6_gr_helper.c

Description:
Active GR count field is missing in json o/p
of 'show ipv6 ospf gr helper' command.
Issue: #12100

ospf6d: adding missing json fields

---

pimd/pim_zlookup.c

In the current code, if_lookup_by_index()
is called for un-initialized ifindex value.
This will break v4-over-v6 nexthop handling feature.
This issue is introduced after #11098 PR.

pimd: Fix v4-over-v6 nexthop handling

---

ospfclient/ospfclient.py
ospfd/ospf_opaque.h
tests/topotests/ospfapi/test_ospf_clientapi.py

This issue was first introduced in release 8.2 (8.1 passes zero len opaque LSAs)
Also improve related topotest

OSPF: allow for zero length opaque LSAs

---

lib/routemap.c
zebra/zebra_nhg.c

Couple of fixes:
a) linklist compare function does not need to check for null
b) print out the actual nexthop instead of just the ifindex( and having it fail if it is 0)

Debug nh fix

---

pimd/pim_cmd_common.c
pimd/pim_util.c
pimd/pim_util.h

pimd, pim6d: Don't configure link-local, Multicast, Unspecified address as RP
Problem:
frr(config)# do show ipv6 pim interface
Interface  State  Address                   PIM Nbrs  PIM DR  FHR  IfChannels
ens192     up     fe80::250:56ff:feb7:3619  0         local   0    1
Configure ens192 interface link-local address as RP.
frr(config)# ipv6 pim rp fe80::250:56ff:feb7:3619
No Path to RP address specified: fe80::250:56ff:feb7:3619
frr(config)# do show ipv6 pim rp-info
RP address                group/prefix-list  OIF      I am RP  Source  Group-Type
fe80::250:56ff:feb7:3619  ff00::/8           Unknown  yes      Static  ASM
Fix:
RP should not be link-local, multicast and unspecified address.
Fixes: #12095 

pimd, pim6d: Don't configure link-local, Multicast, Unspecified address as RP

---

doc/user/bgp.rst

I don't know how I missed that it was already defined. Let's just revert it.
This reverts commit 13111667513a0f91a8e875cdf12c940ea2b60b05.

Revert "doc: Add `neighbor PEER extended-optional-parameters` command"

---

bgpd/bgp_evpn_vty.c

Fix the vni_str NULL check for wildcard route-targets in evpn show run. This will never be NULL if we add 1 here. Though it should also never be NULL since ":" should always exist. Better to be safe than sorry.

bgpd: fix vni_str NULL check in evpn rt show run

---

tests/topotests/bgp_local_asn/bgp_local_asn_agg.json
tests/topotests/bgp_local_asn/bgp_local_asn_ecmp.json
tests/topotests/bgp_local_asn/bgp_local_asn_topo1.json
tests/topotests/bgp_local_asn/bgp_local_asn_topo2.json
tests/topotests/bgp_local_asn/bgp_local_asn_vrf_topo1.json
tests/topotests/bgp_local_asn/bgp_local_asn_vrf_topo2.json
tests/topotests/bgp_local_asn/test_bgp_local_asn_agg.py
tests/topotests/bgp_local_asn/test_bgp_local_asn_ecmp.py
tests/topotests/bgp_local_asn/test_bgp_local_asn_topo1.py
tests/topotests/bgp_local_asn/test_bgp_local_asn_topo2.py
tests/topotests/bgp_local_asn/test_bgp_local_asn_vrf_topo1.py
tests/topotests/bgp_local_asn/test_bgp_local_asn_vrf_topo2.py
tests/topotests/lib/bgp.py

When an Internet service provider (ISP) acquires a network 
that belongs to a different autonomous system (AS), there is 
no seamless method for moving the BGP peers of the acquired 
network to the AS of the acquiring ISP, in this case it can be 
useful to configure BGP-enabled devices in the new AS to 
use the former AS number in BGP updates. This former AS 
number is called a local AS.
Added tests and lib changes to verify BGP Local AS feature
and functionality.
Co-Auther: Vijayaguru Jayaram <vjayaram@vmware.com>

tests: Add bgp local asn test suite

---

lib/if.c
lib/if.h
lib/zclient.c
zebra/interface.c
zebra/zapi_msg.c

Daemons like isisd continue to use the previous after they are unset
from zebra.
For example,
>r0# sh run zebra
> (...)
> interface eth-rt1
>  link-params
>   enable
>   metric 100
>  exit-link-params
> r0# conf
> r0(config)# interface eth-rt1
> r0(config-if)#  link-params
> r0(config-link-params)#   no enable
After "no enable", "sh run zebra" displays no more link-params context.
The "no enable" causes the release of the "link_params" pointer within
the "interface" structure. The zebra function to update daemons with
a ZEBRA_INTERFACE_LINK_PARAMS zapi message is called but the function
returns without doing anything because the "link_params" pointer is
NULL.
"enable" means that the traffic engineering parameters are set. Daemons
consider "enable" is set when the "link_params" pointer is …

lib,zebra,ospf: link-params are not flushed after "no enable"

---

isisd/isis_te.c

Two fixes for mpls-te
If MPLS TE is enabled, the router encodes the local and remote interface
IP address in the "Extended Reachability" TLV.
> east-vm(config)# do show isis database detail east-vm.00-00
>  Extended Reachability: 0007.e901.3333.00 (Metric: 10)
>    Local Interface IP Address(es): 10.126.0.2
>    Remote Interface IP Address(es): 10.126.0.3
>    Maximum Bandwidth: 1.76258e+08 (Bytes/sec)
The remote interface is added when the circuit adjacency comes up after
setting MPLS TE. However, if MPLS TE is enabled after, the remote
address is not added. It happens after disabling and re-enabling the
MPLS TE.
> east-vm(config)# router isis 1
> east-vm(config-router)# no mpls on
> east-vm(config-router)# mpls on
> east-vm(config)# do show isis database detail east-vm.00-00
>  Extended …

isisd: fixes for mpls-te

---

bgpd/bgp_route.c
bgpd/bgp_route.h
tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post4.1.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post5.0.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post6.1.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv4.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv6-post4.1.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv6.ref
tests/topotests/all_protocol_startup/r1/show_bgp_ipv6_post6.1.ref

Column headers in BGP routes table are not aligned with data when RPKI status is available.  This was fixed to insert a space at the beginning of the header and at the beginning of lines that do not have RPKI status.
This fix requires that several testing templates be adjusted to match the new output.
Signed-off-by: Wayne Morrison <wmorrison@netgate.com>

bgpd: fixed misaligned columns in BGP routes table

---

ospfd/ospf_flood.c
ospfd/ospf_packet.c
tests/topotests/ospf_basic_functionality/test_ospf_p2mp.py

FRR implements a non-standard, but compatible approach for
sending update LSAs (it always send to 224.0.0.5) on P2MP
interfaces. This change makes it so acks are also sent to
224.0.0.5.
Since the acks are multicast, this allows an optimization
where we don't send back out the incoming P2MP interface
immediately allow time to rx multicast ack from neighbors
on the same net that rx'ed the original (multicast) update.

  ospf: optimization for FRR's P2MP mode

---

ospf6d/ospf6_area.c
ospf6d/ospf6_asbr.c

Problem:
Multiple memory leaks in ospf6.
260 ==6637== 32 bytes in 1 blocks are definitely lost in loss record 5 of 24
261 ==6637==    at 0x4C31FAC: calloc (vg_replace_malloc.c:762)
262 ==6637==    by 0x4E8A1BF: qcalloc (memory.c:111)
263 ==6637==    by 0x11EE27: ospf6_summary_add_aggr_route_and_blackhole (ospf6_asbr.c:2779)
264 ==6637==    by 0x11EEBA: ospf6_originate_new_aggr_lsa (ospf6_asbr.c:2811)
265 ==6637==    by 0x4E7C6A7: hash_clean (hash.c:325)
266 ==6637==    by 0x11FA93: ospf6_handle_external_aggr_update (ospf6_asbr.c:3164)
267 ==6637==    by 0x11FA93: ospf6_asbr_summary_process (ospf6_asbr.c:3386)
268 ==6637==    by 0x4EB739B: thread_call (thread.c:1692)
269 ==6637==    by 0x4E85B17: frr_run (libfrr.c:1068)
270 ==6637==    by 0x119535: main (ospf6_main.c:228)
356 ==6637== 240 …

ospf6d: Fix for memory leak issues in ospf6.

---

bgpd/bgp_route.c

When deciding whether to apply "neighbor soo" filtering towards a peer, we were only looking for SoO ecoms that use either AS or AS4 encoding. This makes sure we also check for IPv4 encoding, since we allow a user to configure that encoding style against the peer.
Config:
```
router bgp 1
network 100.64.0.2/32 route-map soo-foo
neighbor 192.168.122.12 soo 3.3.3.3:20
!
route-map soo-foo permit 10
set extcommunity soo 3.3.3.3:20
exit
```
Before:
```
ub20# show ip bgp neighbors 192.168.122.12 advertised-routes
BGP table version is 5, local router ID is 100.64.0.222, vrf id 0
Default local pref 100, local AS 1
Nexthop …
```

bgpd: Check for IP-format Site-of-Origin

---

bgpd/bgp_updgrp_packet.c

Given that the following topology, route server MUST not modify NEXT_HOP attribute because route server isn't in the actual routing path. This behavior is required to comply RFC7947:
RFC7947 says as follows:
> As the route server does not participate in the actual routing of
> traffic, the NEXT_HOP attribute MUST be passed unmodified to the route
> server clients, similar to the "third-party" next-hop
> feature described in Section 5.1.3. of [RFC4271].
However, current FRR is violating RFC7947 in some cases. If routers and route server established BGP peer over IPv6 connection and routers advertise ipv4-vpn routes through route server, route server will modify NEXT_HOP attribute in these advertisements.
This is because the condition to check whether NEXT_HOP attribute should be changed or …

bgpd: Fix the condition whether nexthop is changed

---

lib/zclient.c

The code was working but the coverity scan reported a failure.
Clarify the code to make the coverity scan happy.
Fixes: fe0a129687 ("lib,zebra: link-params are not flushed after no enable")

lib: fix coverity scan failure in zebra_interface_link_params_read()

---

pimd/pim_rp.c

Problem:
```
frr(config)# show ip pim rp-info
RP address group/prefix-list OIF I am RP Source Group-Type 109.0.0.3 224.0.0.0/4 ens192 no Static ASM
frr(config)# int ens192
frr(config-if)# no ip pim
frr(config) show ip pim rp-info
RP address group/prefix-list OIF I am RP Source Group-Type 109.0.0.3 224.0.0.0/4 ens192 no Static ASM
```
rp-info OIF is still having ens192 which is PIM disabled. Fixing this as part of this PR.
Issue: #12044

pimd, pim6d: Fix rp-info OIF having PIM disabled interface

---

bgpd/bgp_fsm.c

When waiting on a path to reach the peer, modify the debug/show output to give a better understanding to the operator about what they should be looking for.

bgpd: Clarify what NHT error message means

---

pimd/pim_nht.c
pimd/pim_tib.c

Fixing the coverity issues
Unchecked return value (CID 1519816) and 
Dereference before null check (CID 1519749)
Check commits for more details.

pimd: fixing some coverity issues

---

bgpd/bgp_io.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst

Add a default limit to the InQ for messages off the bgp peer socket. Make the limit configurable via cli.
Adding in this limit causes the messages to be retained in the tcp socket and allow for tcp back pressure and congestion control to kick in.
Before this change, we allow the InQ to grow indefinitely just taking messages off the socket and adding them to the fifo queue, never letting the kernel know we need to slow down. We were seeing under high loads of messages and large perf-heavy routemaps (regex matching) this queue would cause a memory spike and BGP would get OOM killed. Modifying this leaves the messages in the socket and distributes that load where it should be in the socket buffers on both send/recv while we handle the mesages.
Also, changes were made to allow the ringbuffer …

bgpd,doc: limit InQ buf to allow for back pressure

---

lib/if.h
tests/topotests/cspf_topo1/r1/zebra.conf
tests/topotests/cspf_topo1/r2/zebra.conf
tests/topotests/cspf_topo1/reference/sharp-ted.json
tests/topotests/cspf_topo1/test_cspf_topo1.py
tests/topotests/isis_te_topo1/r1/zebra.conf
tests/topotests/isis_te_topo1/r2/zebra.conf
tests/topotests/isis_te_topo1/reference/ted_step1.json
tests/topotests/isis_te_topo1/reference/ted_step2.json
tests/topotests/isis_te_topo1/reference/ted_step3.json
tests/topotests/isis_te_topo1/reference/ted_step4.json
tests/topotests/isis_te_topo1/reference/ted_step5.json
tests/topotests/isis_te_topo1/reference/ted_step6.json
tests/topotests/ospf_te_topo1/r1/zebra.conf
tests/topotests/ospf_te_topo1/r2/zebra.conf
tests/topotests/ospf_te_topo1/reference/ted_step1.json
tests/topotests/ospf_te_topo1/reference/ted_step2.json
tests/topotests/ospf_te_topo1/reference/ted_step3.json
tests/topotests/ospf_te_topo1/reference/ted_step4.json
tests/topotests/ospf_te_topo1/reference/ted_step5.json
tests/topotests/ospf_te_topo1/reference/ted_step6.json
tests/topotests/ospf_te_topo1/reference/ted_step7.json

When enabling the interface link-params, a default bandwidth is assigned to the Max, Reservable and Unreserved Bandwidth variables. If the bandwidth is set at in the interface context, this value is used. Otherwise, a default bandwidth value of 10 Gbps is set.
Revert the default value to 10 Mbps as it was intended in the initial commit. 10 Mbps is a low value so that the link will not be prioritized when computing the paths.

lib: fix the default TE bandwidth

---

doc/user/zebra.rst

The right default FPM server port is 2620
Signed-off-by: Spoorthi K <spk@redhat.com>

doc: Update with right default FPM server port

---

ospfd/ospf_flood.c

This looks like an original but - the recent P2MP optimization made it more obvious.

ospfd: fix bug where acks were not be generated to incoming P2P/P2MP peers

---

ospfd/ospf_lsa.c
ospfd/ospf_packet.c

ospfd: remove asster on zero length LSA - which is permitted by spec

---

bgpd/bgp_mplsvpn.c
bgpd/bgp_vty.c
bgpd/bgp_zebra.c
lib/srv6.c
lib/srv6.h

A programmer can use the `srv6_locator_chunk_free()` function to free the memory allocated for a `struct srv6_locator_chunk`.
The programmer invokes `srv6_locator_chunk_free()` by passing a single pointer to the `struct srv6_locator_chunk` to be freed. `srv6_locator_chunk_free()` uses `XFREE()` to free the memory. It is the responsibility of the programmer to set the
`struct srv6_locator_chunk` pointer to NULL after freeing memory with `srv6_locator_chunk_free()`.
This PR modifies the `srv6_locator_chunk_free()` function to take a double pointer instead of a single pointer. In this way, setting the `struct srv6_locator_chunk` pointer to NULL is no longer the programmer's responsibility but is the responsibility of
`srv6_locator_chunk_free()`. This prevents programmers from making mistakes …

bgpd: Enhance the `srv6_locator_chunk_free()` API by automatically setting the pointer to the freed memory to `NULL`

---

lib/srv6.c

This PR changes `seg6local_context2str()` to use `%pI6`/`%pI4` instead of `inet_ntop` to print the SRv6 seg6local context information.

lib: Use `%pI6`/`%pI4` to print SRv6 seg6local ctx

---

doc/user/ospfd.rst

"on-shutdown" and "on-startup" have the different timeout range.
Correct the timeout range for "on-shutdown" based on the current code:
```
(ospf)  max-metric router-lsa on-shutdown (5-100)
```

doc: fix ospf's max-metric command

---

ospfd/ospf_vty.c

Just add the missing running config for this command:
```
(ospf)  max-metric router-lsa administrative
```

ospfd: fix missing max-metric in show running config

---

bgpd/bgp_mplsvpn.c

This PR changes some debug prints to use `%pI6` instead of `inet_ntop` to print SRv6 SIDs.
Signed-off-by: Carmine Scarpitta [carmine.scarpitta@uniroma2.it](mailto:carmine.scarpitta@uniroma2.it)

bgpd: Use `%pI6` to print SRv6 SIDs

---

bgpd/bgp_packet.c

If a operator receives an invalid packet that is of insufficient size then it is possible for BGP to assert during reading of the packet instead of gracefully resetting the connection with the peer.

bgpd: Ensure that bgp open message stream has enough data to read

---

pimd/pim_mroute.c

While going through the code, I realised that 2674ba0ab012591edd30979ed57749d1df42ae65 commit
got overwritten by https://github.com/FRRouting/frr/pull/10661 PR probably while resolving conflicts.
Hence adding it back.

pimd: fix igmp source packet check

---

bgpd/bgp_fsm.c

Currently the bgp mib specifies two traps:
a) Into established state
b) transition backwards from a state
b) really is an interesting case.  It means transitioning from say established to starting over.  It can also mean when bgp is trying to connect and that fails and the state transitions backwards.
Now let's imagine 500 peers with tight timers (say a data center) and there is network trauma you have just created an inordinately large number of traps for each peer.
Let's limit FRR to changing from the old status as Established to something else.  This will greatly limit the trap but it will also be something end operators are actually interested in.
I actually had several operators say they had to write special code to ignore all the backward state transitions that they didn't care …

bgpd: Limit snmp trap for backwards state movement from established

---

bgpd/bgp_evpn_vty.c

~~Since it will never happen without ':' in `ecom_str`, change it into `assert()`. Otherwise, memleak on this `ecom_str` will occur in this case.~~
In the case of without ':' in `ecom_str`, memleak on this `ecom_str` will occur. Just free `ecom_str` for this case.

bgpd: avoid possible memleak

---

pimd/pim_igmp_mtrace.c

Saw this EC log:
```
PIM: [WX4HZ-FA72S][EC 100663307] pim_rp_find_match_group: BUG We should have found default group information
```
The root cause is group address of "0.0.0.0" is wrongly introduced into `pim_rp_find_match_group()`. So add a check to avoid it.

pimd: avoid one EC log

---

zebra/tc_netlink.c

In file included from /usr/include/net/ethernet.h:10,
from ./lib/prefix.h:26,
from zebra/tc_netlink.c:32:
/usr/include/netinet/if_ether.h:115:8: error: redefinition of 'struct ethhdr'
115 | struct ethhdr {
|        ^~~~~~
In file included from zebra/tc_netlink.c:28:
/usr/include/linux/if_ether.h:169:8: note: originally defined here
169 | struct ethhdr {
|        ^~~~~~

zebra: Reuse netinet/if_ether.h to avoid redefinition of struct ethhdr

---

ospfd/ospf_vty.c

Closes https://github.com/FRRouting/frr/issues/12273

ospfd: Get route-map name for default-information originate

---

bgpd/bgp_pbr.c

bgpd: fix "storing the address of local variable"

---

zebra/netconf_netlink.c

Fix the following build failure raised since version 8.4 and https://github.com/FRRouting/frr/commit/d53dc9bd8164ba40242e2013d382fb01eb0b96ed:
```
zebra/netconf_netlink.c: In function 'netlink_netconf_change': zebra/netconf_netlink.c:109:32: error: 'AF_MPLS' undeclared (first use in this function)
109 |         if (ncm->ncm_family == AF_MPLS)
|                                ^~~~~~~
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

zebra/netconf_netlink.c: fix build without AF_MPLS

---

tools/etc/frr/support_bundle_commands.conf

PIMv6 Support Bundle commands are added in support_bundle_commands.conf file.
This will help in debugging PIMv6 test Failures.
Issue: #12279 

tools: Add pim6d support bundle commands

---

bgpd/bgp_rpki.c

The code was this:
1)        match = bgp_table_subtree_lookup(rrp->bgp->rib[rrp->afi][rrp->safi],
&rrp->prefix);
2)        node = match;
while (node) {
if (bgp_dest_has_bgp_path_info_data(node)) {
revalidate_bgp_node(node, rrp->afi, rrp->safi);
}
3)               node = bgp_route_next_until(node, match);
}
if (match)
4)              bgp_dest_unlock_node(match);
At 1) match was locked and became +1
At 2) match and node are now equal
At 3) On first iteration, match is decremented( as that node points at it ) and the next item is locked, if it is found, and returned which becomes node
If 3 is run again because node is non-null then, current node is decremented and the next node found is incremented and returned which becomes node again.
So if we get to 4) match is unlocked again which is now …

bgpd: rpki was decrementing the node lock one time too many

---

bgpd/bgp_mac.c
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_rpki.c
bgpd/bgpd.c
bgpd/bgpd.h

issue #12264 points at several issues with RPKI.  Mainly that when changes are made rpki can take some extraordinary amount of time to converge.
This PR attempts to mitigate some of those issues by breaking up work done into a bunch of different events.  Additionally some code refactoring was done to improve FRR and finally an additional lock decrement was found by the re-arrangement that would not have been easily exposed ( but is also probably already causing crashes in the field )

Bgp rpki takes too long

---

pimd/pim_rpf.c

The unable to find a nexthop should not be a warning it should be a debug.  Switching over.

pimd: Convert zlog_warn to debug

---

ospfd/ospf_lsa.c

When using debug mode, the ei parameter may be NULL. In that case, do not display the log trace, otherwise a crash will happen.

ospfd: prevent from crashing when processing external lsa

---

zebra/zebra_evpn_mh.c

The API for configuring ES in zebra had a strict check for if_type "isBond" that prevented the ES config from being created before the interface.
Ticket: CM-29454
Signed-off-by: Anuradha Karuppiah <anuradhak@cumulusnetworks.com>

zebra: relax if_type check to allow early ES config creation

---

debian/frr.pam
redhat/frr.pam

https://github.com/FRRouting/frr/pull/11465 enabled account verification, but the pam config declares rootok as sufficient in authentication only and not in account verification, what causes warning in the log:
```
vtysh[3747]: pam_warn(frr:account): function=[pam_sm_acct_mgmt] flags=0 service=[frr] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[<unknown>]
```

pam: declare root as sufficient frr pam account

---

pimd/pim_iface.c
pimd/pim_nb_config.c
pimd/pim_nht.c
pimd/pim_nht.h
pimd/pim_rpf.c

Commit 1:
Handle IPV6 for "no ipv6 pim" code flow.
Commit 2:
When “no ip pim” command gets executed on source connected interface, then clear upstream RPF information.
Closes #10782
Closes #11931

pimd, pim6d: Update upstream IIF when pim disabled and enabled on an interface

---

zebra/dplane_fpm_nl.c

1) Fix a enum issue
2) Fix the reported bug in #12314

Dplane sorry

---

tools/frrcommon.sh.in

The backslash in `grep -q '^declare \-a'` is not needed and
causes `grep: warning: stray \ before -` warning in grep-3.8.

tools: remove backslash from declare check regex

---

pimd/pim_igmp_mtrace.c

Bring error handling up front and delay creating socket so that we don't think too much about closing the socket in error case.

pimd: delay creating the socket

---

bgpd/bgp_io.c

Add a debug guard for the inQ limit.

bgpd: debug guard inQ limit

---

isisd/isis_route.c

Fix the case area is NULL.
Fixes: acc0029779 ("isisd: fix potential access to NULL pointer in isis_route_update")

isisd: fix area NULL pointer in isis_route_update

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_mh.c
bgpd/bgp_evpn_private.h
bgpd/bgp_evpn_vty.c
bgpd/bgp_evpn_vty.h
bgpd/bgp_route.c
bgpd/bgp_route.h
doc/user/bgp.rst
lib/command.h
zebra/zebra_evpn.c
zebra/zebra_evpn_mac.c
zebra/zebra_evpn_mac.h
zebra/zebra_evpn_neigh.c
zebra/zebra_evpn_neigh.h
zebra/zebra_vty.c
zebra/zebra_vxlan.c
zebra/zebra_vxlan.h

Changes here are to address various issues seen in Extended Mac Mobility handling.
The brunt of the changes were reworking the BGP VNI table into two separate tables for type2 routes so that MAC and IP info can be deterministically determined. 
By separating the two we are able to run path selection across multiple MACs and IPs to more appropriately handle EMM events. A lot of code also changed around handling of various events now that these are in different tables.
Also, change zebra to always accept whatever it was handed by BGP for neigh/mac even if the seq is lower. During a mobility event is entirely possible to transition back to a lower seq number and we have to handle that. Zebra should not be making decisions on whether to install entries or not, that is a BGP decision and, with …

Rework of Various Handling in EVPN for Extended Mac Mobility

---

m4/ax_python.m4

Only the embed version includes necessary linker flags to link with libpython.
Signed-off-by: Alexander Kanavin <alex@linutronix.de>

m4/ax_python.m4: check for python-x.y-emded.pc, not python-x.y.pc

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/pim6d-service
snapcraft/snapcraft.yaml.in

snapcraft: Add pim6 daemon for PIM IPv6 to snap package

---

zebra/zebra_srte.c

This PR solves the following issue:
```
________________________________________________________________________________________________________
*** CID 1527358:  Memory - illegal accesses  (USE_AFTER_FREE)
/zebra/zebra_srte.c: 395 in zebra_srte_client_close_cleanup()
389             int sock = client->sock;
390             struct zebra_sr_policy *policy;
391     
392             if (!sock)
393                     return 0;
394     
>>>     CID 1527358:  Memory - illegal accesses  (USE_AFTER_FREE)
>>>     Passing freed pointer "policy" as an argument to "zebra_sr_policy_instance_head_RB_NEXT".
395             RB_FOREACH (policy, zebra_sr_policy_instance_head,
396                         &zebra_sr_policy_instances) {
397                     if (policy->sock == sock)
398 …
```

zebra: Fix use-after-free crash on srte cleanup

---

bgpd/bgp_zebra.c

LL address is assigned, but we get a warning, that it's not:
Interface: enp3s0 does not have a v6 LL address associated with it, waiting until one is created for it
```
donatas-pc# sh int enp3s0
Interface enp3s0 is up, line protocol is up
Link ups:       0    last: (never)
Link downs:     0    last: (never)
vrf: default
index 2 metric 0 mtu 1500 speed 100
flags: <UP,BROADCAST,RUNNING,MULTICAST>
v4 Multicast forwarding is on
v6 Multicast forwarding is on
Type: Ethernet
HWaddr: 18:c0:4d:96:fa:3f
inet 192.168.10.17/24
inet6 2a02:4780:abc:0:e776:6220:1e21:44b1/64
inet6 fe80::ca5d:fd0d:cd8:1bb7/64
```

bgpd: Warn user only if the LL is not seriously available

---

bgpd/bgp_vty.c
doc/user/bgp.rst

Previously BGP supported up to 255 SIDs.
The PR https://github.com/FRRouting/frr/pull/11981 extended the transposition computation algorithm in BGP to support more SIDs (up to 1048575 SIDs).
However, the BGP VTY command for allocating an SRv6 per-VRF SID (`sid vpn per-vrf export`) is still limited to 255 SIDs.
This PR extends the SID index in `sid vpn per-vrf export` VTY command to support up to 1048575 SIDs.
Signed-off-by: Carmine Scarpitta [carmine.scarpitta@uniroma2.it](mailto:carmine.scarpitta@uniroma2.it)

bgpd: Fix SRv6 SID index limit in the `sid vpn per-vrf export` VTY command

---

tests/topotests/isis_lfa_topo1/rt1/bfdd.conf
tests/topotests/isis_lfa_topo1/rt2/bfdd.conf
tests/topotests/isis_lfa_topo1/test_isis_lfa_topo1.py

isis_lfa_topo1 topotests regularly fails at step 24. The test expects that the BFD session between rt1 and rt2 comes down after shutting the link between rt1 and rt2.
Since the BFD is multihop, the BFD can get back through rt3.
Set the BFD type to single-hop.

tests: fix bfd in isis_lfa_topo1 step24

---

lib/lib_vty.c
vtysh/vtysh.c

Watchfrr really should receive notification about start/end read of configuration.  Let's fix that.

lib, vtysh: Allow watchfrr to receive start/end lines

---

tests/topotests/bfd_topo1/test_bfd_topo1.py
tests/topotests/bgp_features/test_bgp_features.py
tests/topotests/bgp_suppress_fib/test_bgp_suppress_fib.py
tests/topotests/bgp_tcp_mss/test_bgp_tcp_mss.py
tests/topotests/cspf_topo1/test_cspf_topo1.py
tests/topotests/isis_lfa_topo1/test_isis_lfa_topo1.py
tests/topotests/isis_tilfa_topo1/test_isis_tilfa_topo1.py

Ensure that the minimum time spent run and expecting is 5 seconds.  Heavy load is not a reason to fail a test.

tests: Expand minimum run_and_expect to 5 seconds

---

pimd/pim_join.c

pim6d, pimd: Discard (*,G) join/prune if WC bit is set but RPT bit is unset.
As per RFC 7761, Section 4.9.1
The RPT (or Rendezvous Point Tree) bit is a 1-bit value for use
with PIM Join/Prune messages (see Section 4.9.5.1). If the
WC bit is 1, the RPT bit MUST be 1.
ANVL conformance test case is trying to verify this and is failing because we are accepting the packet
and forwarding it towards RP.
Issue: #12354

pim6d, pimd: RFC conformance - Discard join/prune msg when WC bit is set but RPT bit is unset

---

pimd/pim_ifchannel.c
pimd/pim_register.c
pimd/pim_ssm.c
pimd/pim_upstream.c
pimd/pim_util.c

... the prefix length wasn't ignored as expected.  Both S and G are always /32.  But expecting "le 32" in prefix-list config is unexpected & counterintuitive.
---
it's already ignored in most other places.

pimd: consistently ignore prefix list mask len

---

zebra/zebra_script.c

There's a switch statement in the lua extension code that doesn't include all of the values of a dataplane enum - so it fails to build. Add those values in...

zebra: Replace TC definitions for dplane

---

bgpd/bgp_updgrp.c
bgpd/bgp_updgrp.h
bgpd/bgp_vty.c
doc/user/zebra.rst

Changes:
- JSON support for the update group command.
Test:
torc-11# show ip bgp vrf all ipv6 update-groups json
torc-11# show bgp vrf all update-groups json
```
torc-12# show bgp vrf all update-groups json
{
"default":{
"2":{
"groupCreateTime":{
"epoch":1669142445,
"epochString":"Tue Nov 22 18:40:45 2022\n"
},
"afi":"IPv6",
"safi":"unicast",
"outRouteMap":"MY_ORIGIN_ASPATH_ONLY",
"minRouteAdvInt":0,
"subGroup":[
{
"subGroupId":2,
"groupCreateTime":{
"epoch":1669142445,
"epochString":"Tue Nov 22 18:40:45 2022\n"
},
"statistics":{
"joinEvents":1,
"pruneEvents":0,
"mergeEvents":0,
"splitEvents":0,
"switchEvents":0,
"peerRefreshEvents":0,
"mergeCheckEvents":1
},
"coalesceTime":1150,
"version":6,
"packetQueueInfo":{
"qeueueLen":0,
"queuedTotal":0,
"queueHwmLen":0,
"totalEnqueued":0
}, …
```

bgpd: JSON support for show ip bgp vrf all update-group

---

lib/vrf.c

We must disable the vrf before we start terminating interfaces.
On termination, we free the 'zebra_if' struct from the interface ->info pointer. We rely on that for subsystems like vxlan for cleanup when shutting down.
'''
==497406== Invalid read of size 8
==497406==    at 0x47E70A: zebra_evpn_del (zebra_evpn.c:1103)
==497406==    by 0x47F004: zebra_evpn_cleanup_all (zebra_evpn.c:1363)
==497406==    by 0x4F2404: zebra_evpn_vxlan_cleanup_all (zebra_vxlan.c:1158)
==497406==    by 0x4917041: hash_iterate (hash.c:267)
==497406==    by 0x4F25E2: zebra_vxlan_cleanup_tables (zebra_vxlan.c:5676)
==497406==    by 0x4D52EC: zebra_vrf_disable (zebra_vrf.c:209)
==497406==    by 0x49A247F: vrf_disable (vrf.c:340)
==497406==    by 0x49A2521: vrf_delete (vrf.c:245)
==497406==    by 0x49A2E2B: …

lib: disable vrf before terminating interfaces

---

lib/libospf.h
ospfd/ospf_lsa.c

**Steps to reproduce:**
1. ANVL: Establish full adjacency with DUT for neighbor Rtr-0-A on DIface-0 with DUT as DR.
2. ANVL: Listen (for up to 2 * <RxmtInterval> seconds) on DIface-0.
3. DUT: Send <OSPF-LSU> packet.
4. ANVL: Verify that the received <OSPF-LSU> packet contains a Network- LSA for network N1 originated by DUT, and the LS Sequence Number is set to <InitialSequenceNumber>.
5. ANVL: Establish full adjacency with DUT for neighbor Rtr-0-B on DIface-0 with DUT as DR.
6. ANVL: Listen (for up to 2 * <RxmtInterval> seconds) on DIface-0.
7. DUT: Send <OSPF-LSU> packet.
8. ANVL: Verify that the received <OSPF-LSU> packet contains a new instance of the Network-LSA for network N1 originated by DUT, and the LS Sequence Number is set to (<InitialSequenceNumber> + 1).
Both the test cases …

ospfd: Fix RFC conformance test cases 25.19 and 27.6

---

tests/topotests/srv6_locator_custom_bits_length/test_srv6_locator.py
tests/topotests/srv6_locator_usid/r1/zebra.conf
tests/topotests/srv6_locator_usid/test_srv6_locator_usid.py
zebra/zebra_srv6_vty.c

The latest FRR's frr-reload.py is broken and we can't reload FRR gracefully with segment routing locator configuration (if we execute frr-reload.py, FRR will stop suddenly) because block-len and node-len introduced by https://github.com/FRRouting/frr/pull/11673 are something wrong.
The root cause of this issue is very simple. FRR will display the current configuration like this (the below is the result of "show running-configuration").
```
srv6
locators
locator default
prefix fd00:1:0:1::/64 block-len 40 node-len 24 func-bits 16
exit
!
exit
!
exit
!
exit
```
However, FRR doesn't accept segment routing locator parameters if we specify block-len and node-len earlier than func-bits.
```
HV101(config)# segment-routing
HV101(config-sr)# srv6
HV101(config-srv6)# locators …
```

bgpd: Fix the order of SRv6 locator parameters

---

bgpd/bgp_routemap.c

Crash when using for example:
```
route-map test permit 10
set ipv6 vpn next-hop 10.10.10.10
```
```
bgpd[30843]: libyang: Unsatisfied pattern - "1.1.1.1" does not conform to "((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[\p{N}\p{L}]+)?". (Schema location /frr-route-map:lib/route-map/entry/set-action/rmap-set-action/set-action/frr-bgp-route-map:ipv6-address/ipv6-address.)
bgpd[30843]: [JEA2K-29RPH][EC 100663345] nb_candidate_edit: lyd_new_path(/frr-route-map:lib/route-map[name='belekas']/entry[sequence='109']/set-action[action='frr-bgp-route-map:ipv6-vpn-address']/rmap-set-action/frr-bgp-route-map:ipv6-address) failed: 7
bgpd[30843]: [ZDEA9-V1X7W][EC …
```

bgpd: Fix crash for `set ipv4/ipv6 vpn next-hop` command

---

lib/vty.c
zebra/zebra_trace.h

1) do not log `ping ECHO` commands from watchfrr when `log commands` is turned on.
2) fix the lttng issue introduced recently

Echo exclusion

---

doc/user/setup.rst
tools/etc/frr/daemons
tools/frrcommon.sh.in

There might be use cases when this would make sense, for example running FRR in a container as a designated user.
Signed-off-by: Michal Ruprich <mruprich@redhat.com>
Closes https://github.com/FRRouting/frr/issues/12323

tools: Enable start of FRR for non-root user

---

zebra/interface.c

Closes https://github.com/FRRouting/frr/issues/12406

zebra: Use `mpls enable`, not `mpls` when generating a config

---

tests/topotests/isis_lfa_topo1/test_isis_lfa_topo1.py
tests/topotests/isis_tilfa_topo1/test_isis_tilfa_topo1.py
tests/topotests/lib/topotest.py
tests/topotests/ospf6_gr_topo1/test_ospf6_gr_topo1.py
tests/topotests/ospf6_topo2/test_ospf6_topo2.py
tests/topotests/ospf_gr_topo1/test_ospf_gr_topo1.py
tests/topotests/pim_basic/test_pim.py
tests/topotests/pim_basic_topo2/test_pim_basic_topo2.py
tests/topotests/srv6_locator/test_srv6_locator.py
tests/topotests/srv6_locator_custom_bits_length/test_srv6_locator.py

This is for run_and_expect_type and run_and_expect topotests method.
Some contributions unintentionally get merged with very low values, that leads to CI failures, let's guard this a bit.

tests: Fail tests immediately if they use too low wait/count values

---

ospf6d/ospf6_route.c
ospf6d/ospf6_route.h

Commit 8f359e1593c414322 removed a check that prevented the same route from being added twice. In certain topologies, that change resulted in the following infinite loop when adding an ASBR route:
```
ospf6_route_add
ospf6_top_brouter_hook_add
ospf6_abr_examin_brouter
ospf6_abr_examin_summary
ospf6_route_add
(repeat until stack overflow)
```
Revert the offending commit and update `ospf6_route_is_identical()` to not do comparison using `memcmp()`.
Closes https://github.com/FRRouting/frr/issues/10823

ospf6d: fix infinite loop when adding ASBR route

---

doc/user/zebra.rst
zebra/zebra_rnh.c
zebra/zebra_rnh.h
zebra/zebra_vty.c

show ip/ipv6 nht vrf <all | name> json support added.
**Commands enhanced with JSON:**
------------------------------------
show ip nht json
show ip nht <addr> json
show ipv6 nht json
show ipv6 nht <addr> json
show ip nht vrf <name> json
show ip nht vrf all json
show ipv6 nht vrf <name> json
show ipv6 nht vrf all json
show ip nht vrf default <addr> json
show ipv6 nht vrf default <addr> json
**Sample JSON output:**
-------------------------
tor-1# **show ip nht vrf default json**
```
{
"default":{
"nexthops":{
"27.0.0.5":{
"nhtConnected":false,
"clientList":[
{
"protocol":"bgp",
"socket":70,
"protocolFiltered":"none"
}
],
"gates":[
{
"ip":"fe80::202:ff:fe00:2b",
"interface":"uplink_1"
},
{
"ip":"fe80::202:ff:fe00:35",
"interface":"uplink_2"
}
],
"resolvedProtocol":"bgp"
},
"27.0.0.6":{ …
```

zebra: json support for show ip nht

---

ospfd/ospfd.c

Description:
As part of signal handler ospf_finish_final(),  lsas are originated
and added to refresh queues are not freed.
One such leak is :
==2869285== 432 (40 direct, 392 indirect) bytes in 1 blocks are definitely lost in loss record 159 of 221
==2869285==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2869285==    by 0x4910EC3: qcalloc (memory.c:116)
==2869285==    by 0x199024: ospf_refresher_register_lsa (ospf_lsa.c:4017)
==2869285==    by 0x199024: ospf_refresher_register_lsa (ospf_lsa.c:3979)
==2869285==    by 0x19A37F: ospf_network_lsa_install (ospf_lsa.c:2680)
==2869285==    by 0x19A37F: ospf_lsa_install (ospf_lsa.c:2941)
==2869285==    by 0x19C18F: ospf_network_lsa_update (ospf_lsa.c:1099)
==2869285==    by 0x1931ED: ism_change_state …

ospfd: Fixing a memleak.

---

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/r1/bgpd.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/r2/bgpd.conf

The `bgp_srv6l3vpn_to_bgp_vrf2` topotest tests the SRv6 IPv4 L3VPN functionality. It applies the appropriate configuration in `bgpd` and `zebra`, and then checks that the RIB is updated correctly.
The topotest expects to find the AS-Path in the RIB, which is only present if the `bgp send-extra-data zebra` option is enabled in the `bgpd` configuration.
When this topotest was created, the `bgp send-extra-data zebra` option was enabled by default and the topotest worked fine.
However, the PR https://github.com/FRRouting/frr/pull/10408 changed the default behavior of bgp. Now the `bgp send-extra-data zebra` option is unset by default, which always causes the topotest to fail (because AS-Path is missing in the RIB):
This PR fixes the `bgp_srv6l3vpn_to_bgp_vrf2` topotest by enabling the `bgp …

tests: Fix `bgp_srv6l3vpn_to_bgp_vrf2` topotest failures

---

lib/compiler.h
lib/prefix.h

Add some `pragma`s to handle errors that the C/C++ extension is not able to understand.
See [discussion](https://github.com/FRRouting/frr/discussions/12398) for more details.

lib: handle visual studio code C/C++ extension

---

configure.ac

Change configure.ac so that pim6d is enabled by default; a command-line option can disable it. There was a platform test for pimd - I duplicated that for pim6d too.

build: enable pim6d by default

---

zebra/zebra_srv6_vty.c

The `behavior usid` command is installed under the SRv6 Locator node in the zebra VTY. However, in the SRv6 config write function this command is wrongly put on the same line as the `prefix X:X::X:X/M` command. This causes a failure when an SRv6 uSID locator is configured in zebra and `frr-reload.py` is used to reload the FRR configuration.
This PR prepends a newline character to the `behavior usid` command in the SRv6 config write function. The output of `show running-config` before and after this PR is shown below.
Before:
```
Building configuration...
!
frr version 8.5-dev
!
srv6
locators
locator loc1
prefix fc00:0:1::/48 block-len 32 node-len 16    behavior usid
exit
!
exit
!
exit
!
exit
!
end
```
After:
```
Building configuration...
Current …
```

zebra: Fix missing newline character in the of SRv6 config write function

---

bgpd/bgp_mplsvpn.c
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/test_bgp_srv6l3vpn_to_bgp_vrf2.py
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py

The current SRv6 L3VPN topotests can't test reachability correctly. If we set expect_connected to True, check_ping will pass even if all ping packets are dropped. 
This PR fixes check_ping to check reachability correctly. This PR also updates misuse of sid_unregister in delete_vrf_tovpn_sid_per_{af,vrf} to pass bgp_srv6l3vpn_to_bgp_vrf.

bgpd, tests: Fix topotests for SRv6 L3VPN and misuse of sid_unregister

---

vtysh/vtysh_main.c

The rl_callback_handler_install function manual says this:
Set up the terminal for Readline I/O and display the initial expanded value of prompt. Save the value of lhandler to use as a handler function to call when a complete line of input has been entered. The handler function receives the text of the line as an argument. As with readline(), the handler function should free the line when it is finished with it.
Adding a free removes this memory leak that I am seeing with address sanitizer enabled;
SUMMARY: AddressSanitizer: 99 byte(s) leaked in 5 allocation(s).: 2022-12-05 07:50:57,231 INFO: topolog.r7: vtysh result:
Hello, this is FRRouting (version 8.5-dev).
r7# clear log cmdline-targets
r7# conf t
r7(config)# log file staticd.log debug …

vtysh: free memory given to us by readline

---

lib/if.c
zebra/if_netlink.c
zebra/interface.c
zebra/interface.h
zebra/irdp_interface.c
zebra/zapi_msg.c
zebra/zebra_gr.c
zebra/zebra_pbr.c
zebra/zebra_pbr.h
zebra/zserv.c
zebra/zserv.h

Add several MTYPEs for various objects and use those instead of MTYPE_TMP. This makes it easier to debug mem leaks, for example.

lib, zebra: Use real mtypes instead of MTYPE_TMP

---

doc/user/vrrp.rst
vrrpd/vrrp.c
vrrpd/vrrp.h
vrrpd/vrrp_northbound.c
vrrpd/vrrp_packet.c
vrrpd/vrrp_packet.h
vrrpd/vrrp_vty.c
vrrpd/vrrp_vty.h
yang/frr-vrrpd.yang

This commit adds a new option to control whether a VRRPv3 group accepts / computes its checksum with a prepended IPv4 pseudoheader. This should improve interoperability with other devices.
Signed-off-by: Siger Yang <siger.yang@outlook.com>
Due to text ambiguity, vendors have different explanations for IPv4 scenarios in [RFC 5798 #5.2.8](https://www.rfc-editor.org/rfc/rfc5798.html#section-5.2.8), so this PR should solve #9951.

vrrpd: add IPv4 pseudoheader option for VRRPv3

---

bgpd/bgp_fsm.c
bgpd/bgp_network.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

found 2 use after frees in bgp code.  See individual commits for explanations.

Bgp use after free

---

tools/frrcommon.sh.in

This reverts commit 2000ac4075bbe1a9557ee30286309d3ade72b3a7.
There were concerns that ensuring zebra stopped last led to problems with zebra's "-r" flag, so we'll revert that for the time being and reconsider this area.

tools: revert stop zebra daemon last

---

bgpd/bgp_evpn_vty.c

It is possible there is no ip address in type2 prefix, that leads to crash in `build_evpn_type2_prefix()`.

bgpd: fix null pointer dereference

---

bgpd/bgp_evpn_mh.c

The default vrf in bgp when created, ends up having the bgp->name as NULL.  This of course crashes the ilk of `json_object_string_add` when a NULL is passed in.
Go through all the places in bgp_evpn_mh.c and fix so that it doesn't crash.

bgpd: Prevent crash in evpn when using default vrf

---

doc/accords/README.md
doc/accords/frr-service-is-watchfrr
doc/accords/integrated-config-wins
doc/developer/workflow.rst

The idea here is to pass "non-code agreements" through the PR review mechanism, and have them visible in the git tree.
Two "example" (but real) accords are included, mostly to illustrate the idea.  Both of these should be non-controversial and have had some previous discussion in random places.

doc: introduce FRR community "accords"

---

bgpd/bgp_updgrp.c

bgpd: Don't always allocate json memory in non-json path

---

tests/topotests/ospf_gr_helper/ospf_gr_helper.json

With a dead interval of 40 seconds, each tests is waiting 40+ seconds for ospf convergence to occurr because the DR is re-elected

tests: ospf_gr_helper tests are slow

---

doc/user/bgp.rst
doc/user/evpn.rst
doc/user/index.rst
doc/user/subdir.am

The existing EVPN documentation in bgp.rst does not provide a holistic configuration, just examples of individual features, and doesn't give an operator any idea of what a compatible Linux netdev configuration might look like. This introduces evpn.rst which includes a sample frr.conf and corresponding Linux interface config (via iproute2) that an operator can use to setup a basic EVPN topology and model their interface manager's config from.
This initial version of evpn.rst shows Linux netdev config for traditional bridges (vlan_filtering=0) and traditional vxlan devices (single VNI). Later changes to this file will cover the use of VLAN-aware bridges (vlan_filtering=1), single VXLAN devices (multi VNI), and eventually bonds (for EVPN-MH).
Eventually the plan is to move the existing EVPN …

doc: add FRR/Linux configuration examples for EVPN

---

configure.ac
doc/developer/building-frr-for-freebsd13.rst
doc/developer/building.rst
doc/developer/subdir.am
m4/ax_lua.m4

- fix non-portable `sed` regex in Lua detection
- make pim6d Linux-only
- add FreeBSD 13 build docs

build: FreeBSD fixes

---

bgpd/bgp_nht.c
tests/topotests/bgp_unnumbered/r1/bgpd.conf
tests/topotests/bgp_unnumbered/r1/zebra.conf
tests/topotests/bgp_unnumbered/r2/bgpd.conf
tests/topotests/bgp_unnumbered/r2/zebra.conf
tests/topotests/bgp_unnumbered/test_bgp_unnumbered.py

In case of BGP unnumbered, BGP fails to free the nexthop node for peer if the interface is shutdown before
unconfiguring/deleting the BGP neighbor.
This is because, when the interface is shutdown,
peer's LL neighbor address will be cleared. Therefore, during neighbor deletion, since the peer's neighbor address is not available, BGP will skip freeing the nexthop node of this peer. This results in a stale nexthop node that points to a peer that's already
been freed.
Ticket: 3191547
Signed-off-by: Pooja Jagadeesh Doijode <pdoijode@nvidia.com>

bgpd: BGP fails to free the nexthop node

---

doc/user/ospfd.rst

The command of "show ip ospf" is incomplete. But "show ipv6 ospf" is fine.
Just complete it with actual parameters.

doc: fix an incomplete command for ospf

---

bgpd/bgp_vty.c

Some keys are only present in the JSON data of BGP neighbors are only present if the peer is, or has previously been established. While they are not present if the peer has never come up.
To keep the data structure aligned, the below keys are added also to the neighbors that BGP adjacency has never been established. And the values of the keys are all set to "Unknown"
"hostname":Unknown,
"nexthop":Unknown,
"nexthopGlobal":Unknown,
"nexthopLocal":Unknown,
"bgpConnection":Unknown,
Signed-off-by: Karl Quan <kquan@nvidia.com>

BGP neighbor JSON output always displays hostname, nexthop and related keys 

---

ospf6d/ospf6_nssa.c
tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa2.py

Problem:
Delay in ospfv3 route installation when area gets converted to regular from NSSA.
RCA:
when area gets converted from NSSA to normal the type-7(NSSA_LSAs) gets flushed from the area, as a result the external routes learnt from these type-7s gets removed. Once the area is moved to nomral the type 5 lsas needs to flooded through the area so that routes are re-learnt. however there is a delay in flooding of these routes until these routes are refreshed. Due to this there is delay installation of these routes.
Fix:
The Fix involves refreshing of the type 5 lsas once the area is changed from nssa to regular area.

ospf6d: ospf6 route installation when changed from nssa to regular area.

---

lib/link_state.c

The wrong size is allocated for struct ls_prefix memory.
Fix ls_prefix memory allocation.
Fixes: b0c0b43348 ("lib: Update Link State Database")

lib: fix ls_prefix memory allocation

---

zebra/debug.c
zebra/debug.h

Use the correct flags for debug zebra dataplane dpdk options - we were confusing 'debug dataplane' and 'debug dataplane dpdk' in several places.

zebra: fix flags used for debug dpdk

---

doc/developer/fpm.rst
zebra/dplane_fpm_nl.c
zebra/rt_netlink.c
zebra/rt_netlink.h
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_rib.c
zebra/zebra_router.c
zebra/zebra_router.h
zebra/zebra_vty.c

See the various commits.  But effectively modify the dplane_fpm_nl to receive a RTM_NEWROUTE netlink message to allow the underlying asic to signal to zebra if the route was successfully offloaded/Failed to offload or Trapped.  This message is read then converted to a context to pass up through the dplane to zebra for processing.

Add ability for dplane_fpm_nl to receive RTM_NEWROUTE netlink messages that signal route handling in the asic

---

bgpd/bgp_mplsvpn.c
tests/topotests/bgp_vrf_leaking_5549_routes/ce1/bgpd.conf
tests/topotests/bgp_vrf_leaking_5549_routes/ce1/zebra.conf
tests/topotests/bgp_vrf_leaking_5549_routes/pe1/bgpd.conf
tests/topotests/bgp_vrf_leaking_5549_routes/pe1/results/default_ipv4_vpn.json
tests/topotests/bgp_vrf_leaking_5549_routes/pe1/results/vrf10_ipv4_unicast.json
tests/topotests/bgp_vrf_leaking_5549_routes/pe1/results/vrf20_ipv4_unicast.json
tests/topotests/bgp_vrf_leaking_5549_routes/pe1/zebra.conf
tests/topotests/bgp_vrf_leaking_5549_routes/test_bgp_vrf_leaking.py

When we use vrf-to-vrf export, the nexthop has already not been overridden when the peer is BGP unnumberred. However, when we use normal export, the nexthop will be oberridden. This behavior will make some VPN routes invalid in VPN RIB.
This PR stops overriding nexthop even if we use normal export and will solve #12349.
Closes https://github.com/FRRouting/frr/issues/12349
Signed-off-by: Ryoga Saito <ryoga.saito@linecorp.com>

bgpd: Stop overriding nexthop in vpn_leak_from_vrf_update when the peer is BGP unnumberred

---

bgpd/bgp_evpn.c

ASAN reported the following memleak:
```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x4d4342 in calloc (/usr/lib/frr/bgpd+0x4d4342)
#1 0xbc3d68 in qcalloc /home/sharpd/frr8/lib/memory.c:116:27
#2 0xb869f7 in list_new /home/sharpd/frr8/lib/linklist.c:64:9
#3 0x5a38bc in bgp_evpn_remote_ip_hash_alloc /home/sharpd/frr8/bgpd/bgp_evpn.c:6789:24
#4 0xb358d3 in hash_get /home/sharpd/frr8/lib/hash.c:162:13
#5 0x593d39 in bgp_evpn_remote_ip_hash_add /home/sharpd/frr8/bgpd/bgp_evpn.c:6881:7
#6 0x59dbbd in install_evpn_route_entry_in_vni_common /home/sharpd/frr8/bgpd/bgp_evpn.c:3049:2
#7 0x59cfe0 in install_evpn_route_entry_in_vni_ip /home/sharpd/frr8/bgpd/bgp_evpn.c:3126:8
#8 0x59c6f0 in install_evpn_route_entry /home/sharpd/frr8/bgpd/bgp_evpn.c:3318:8
#9 0x59bb52 in …
```

bgpd: cleanup macip_path_list for remote macip

---

bgpd/bgp_attr.c

Currently, bgp_packet_mpattr_prefix_size (bgpd/bgp_attr.c:3978) always returns zero for Flowspec prefixes. This is because, for flowspec prefixes, the prefixlen attribute of the prefix struct is always set to 0, and the actual length in bytes is set inside the flowspec_prefix struct instead (see lib/prefix.h:293 and lib/prefix.h:178). Because of this, with a large number of flowspec NLRIs, bgpd ends up building update messages that exceed the maximum size and cause the peer to drop the connection (bgpd/bgp_updgrp_packet.c:L719). The proposed change allows the bgp_packet_mpattr_prefix_size to return correct result for flowspec prefixes.
Fixes #12529
Signed-off-by: Stephane Poignant <stephane.poignant@proton.ch>

bgpd: Add support for flowspec prefixes in bgp_packet_mpattr_prefix_size

---

bgpd/bgp_fsm.c
bgpd/bgp_fsm.h
bgpd/bgp_vty.c
lib/agentx.c
lib/smux.h
lib/srv6.c
lib/workqueue.c
lib/workqueue.h
ospf6d/ospf6_interface.c
ospf6d/ospf6_message.c
tests/lib/test_heavy_wq.c
tests/topotests/config_timing/test_config_timing.py
zebra/rt_netlink.c
zebra/zebra_mpls.c
zebra/zebra_rib.c

See individual commits, memory leaks to code cleanup to making topotests run faster

Some various stuff

---

lib/zlog_targets.c
staticd/static_zebra.c

When compiling with -fsanitize=thread.  I started getting this error:
staticd/static_zebra.c: In function ‘static_zebra_nht_get_prefix’: staticd/static_zebra.c:316:1: error: control reaches end of non-void function [-Werror=return-type]
316 | }
| ^
Just to make future efforts still work, let's just make the compiler happy.

lib, staticd: return values even after an assert

---

bgpd/bgp_addpath.c

I am seeing this output:
2022/12/16 09:16:00.206 BGP: [MNE5N-K0G4Z] Resetting peer (null) due to change in addpath config
Switch over to %pBP

bgpd: Print out useful information about peer

---

zebra/rtadv.c
zebra/rtadv.h

Currently when zebra receives a RA with optional types, note the optional types that we are ignoring.

zebra: Notice Optional Router Advertisement types that are not handled

---

zebra/main.c

Zebra has a shutdown setup where it asks the dplane to shutdown but can still be processing data.  This is especially true if something the dplane is listening on receives data that will be processed by the main dplane thread
from netlink.   When zebra_finalize is called it is possible that a bit
of data comes in before the zebra_dplane_shutdown() function is called
and the memory freed in ns_walk_func() causes the main dplane event
to crash when it cannot find the ns data anymore.
Reverse the order, stop the zebra dplane pthread and then free the memory associated with the namespaces.

zebra: Ensure memory is not freed that dplane depends on in shutdown

---

zebra/zebra_fpm_netlink.c

The wrong parameter is passed in `inet_ntop()` of `zfpm_log_route_info()` in old fpm module, so the display of gateway is always wrong. Just remove that extra ampersand.
Additionally, use "none" as gateway value for the case of no gateway.

zebra: fix wrong gateway for fpm debug

---

bgpd/bgp_attr.c

See individual commits but effectively we had a recent commit where flowspec wasn't being properly encoded because an if statement was hiding the flowspec safi being properly encoded because the code was using if statements.  Make it easier for future people to not have bugs when new encodings are needed.

Use switch statements without default for safi_t and afi_t enum's

---

pathd/path_pcep_config.c

Fix an SA warning about a possibly-uninited local.

pathd: fix SA warning in path_pcep_config

---

doc/user/ospfd.rst
ospfd/ospf_vty.c

show ip ospf border-routers json support added.
commands:
- show ip ospf vrf default border-routers json
- show ip ospf vrf all border-routers json
- show ip ospf border-routers json
Testing Done: Unit testing completed.
rut# show ip ospf vrf all border-routers json
```
{
"default":{
"vrfName":"default",
"vrfId":0,
"routers":{
"0.0.0.8":{
"routeType":"R ",
"cost":10,
"area":"0.0.0.1",
"routerType":"abr",
"nexthops":[
{
"ip":"12.0.0.2",
"via":"swp1"
}
]
},
"0.0.0.9":{
"routeType":"R ",
"cost":10,
"area":"0.0.0.1",
"routerType":"abr",
"nexthops":[
{
"ip":"12.0.1.2",
"via":"swp2"
}
]
}
}
}
}
```
rut#
rut# show ip ospf vrf all border-routers json
```
{
"default":{
"vrfName":"default",
"vrfId":0,
"routers":{
"0.0.0.15":{
"routeType":"R ",
"cost":30,
"area":"0.0.0.0",
"routerType":"abr", …
```

ospfd: json support for show ip ospf border-routers

---

ospfd/ospf_spf.c
ospfd/ospfd.c

Fixes #12500 .
Fix a memory leak that happens on OSPF instance removal.

ospfd: fix SPF table memory leak

---

bgpd/bgp_debug.c

Several functions had this pattern:
a) p = prefix_new
b) if (already_tracking)
return
b) needs to free the newly allocated prefix else it is leaked.

bgpd: When allocating prefix, free it when we are already tracking it

---

pimd/pim_oil.c

Fixing the below debug issue.
```
2022/12/14 04:28:17 PIM: [P4GDD-KHFYX] pim_channel_oil_del(pim_channel_oil_upstream_deref): Del oil for (225.1.1.1,*), Ref Count: 1 (Predecrement)
```

pimd: Fix (S,G) debug issue

---

bgpd/bgp_debug.c

Fixes static analyzer warnings introduced here:
https://github.com/FRRouting/frr/pull/12539#issuecomment-1359594833
Always initialize stack variables so static analyzer doesn't complain about garbage values.
NOTE: it is unlikely or impossible that it is not initialized because the DEFUN parameters are always validated and all the cases get a valid prefix.

bgpd: fix static analyzer warning

---

vtysh/vtysh_main.c

The code is double checking the VTYSH_HISTFILE env variable, additionally clang-15 when running SA over it doesn't fully understand the code pattern.  Reduce the double check to one check to reduce program run-time (ha!) and make SA happy.

vtysh: Remove double retrieve of env VTYSH_HISTFILE

---

bgpd/bgp_zebra.c

Take it into consideration for one debug log:
EVPN MAC-IP routes with a L3 NHG id, has no nexthops.
Not "delete", but "add".
Before:
```
Tx route delete VRF 21 192.168.30.253/32 metric 0 tag 0 count 0 nhg 72580649
```
After:
```
Tx route add VRF 21 192.168.30.253/32 metric 0 tag 0 count 0 nhg 72580649
```

bgpd: fix one wrong debug log for evpn

---

bgpd/bgp_zebra.c
tests/topotests/bgp_srv6l3vpn_route_leak/ce1/zebra.conf
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/bgpd.conf
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/default_ipv4_vpn.json
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/vrf10_ipv4_unicast.json
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/vrf20_ipv4.json
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/vrf20_ipv4_unicast.json
tests/topotests/bgp_srv6l3vpn_route_leak/pe1/zebra.conf
tests/topotests/bgp_srv6l3vpn_route_leak/test_bgp_srv6l3vpn_route_leak.py

Current bgpd can't announce SRv6 locally-generated routes to Zebra correctly because the MPLS label of locally-generated routes is not valid but sid_info->transposition_len is set to a non-zero value. This commit fixes such kinds of issues.
**pe1**
```
pe1# show bgp vrf vrf20 ipv4 unicast 
BGP table version is 1, local router ID is 192.0.2.1, vrf id 4
Default local pref 100, local AS 65001
*> 172.16.0.0/24    0.0.0.0@2<               0 …
```

bgpd: Fix announce SRv6 locally-generated routes to Zebra

---

bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
bgpd/bgp_route.h
doc/user/bgp.rst

Absolutely not possible to read the output and even distinguish the prefix we are looking for.
Before:
```
donatas-pc# show ip bgp detail
BGP table version is 12, local router ID is 192.168.10.17, vrf id 0
Default local pref 100, local AS 65002
65001
2a02:4780:abc::2 from 2a02:4780:abc::2 (200.200.200.202)
(fe80::a00:27ff:fe5e:d19e) (used)
Origin incomplete, metric 0, valid, external, multipath
Last update: Tue Dec 13 22:53:16 2022
65001 …
```

bgpd: Show the real prefix for `show bgp detail`

---

bgpd/bgp_nexthop.c
bgpd/bgp_route.c
bgpd/rfapi/bgp_rfapi_cfg.c

Shutdown of bgp results in both the bgp_path_info, bgp_dest and bgp_table's not being freed because
the bgp_path_info remains locked.
Effectively static routes are scheduled for deletion but bgp_process skips the work because the work queue sees that the bgp router is marked for deletion.  Effectively not doing any work and leaving data on the floor.
Modify the code when attempting to put into the work queue to notice and not do so but just unlock the path info.
This is effectively the same as what goes on for normal peering as that it checks for shutdown and just calls bgp_path_info_free too.
Closes https://github.com/FRRouting/frr/issues/12506

bgpd: static routes are leaked on shutdown

---

tests/topotests/bgp_unique_rid/bgp_unique_rid.json
tests/topotests/bgp_unique_rid/bgp_unique_rid_vrf.json
tests/topotests/bgp_unique_rid/test_bgp_unique_rid.py
tests/topotests/bgp_unique_rid/test_bgp_unique_rid_vrf.py
tests/topotests/lib/bgp.py

This is the automation for bgp unique router id, includes tests like configuring same or different router ids on different routers topology.

tests: adding bgp unique router id automation.

---

tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/vrf20_ipv4.json

Previously, routes leaked from one VRF to another VRF were associated with the original nexthop interface.
Commit 14aabc0 replaced the nexthop interface with the index of incoming VRF interface.
Due to this change, the `bgp_srv6l3vpn_route_leak` topotest always fails because it still expects the nexthop interface.
This commit fixes the expected interface name in the `bgp_srv6l3vpn_route_leak` topotest.

tests: Fix wrong interface name in `bgp_srv6l3vpn_route_leak` topotest

---

zebra/zebra_vty.c
zebra/zserv.c

Fix a couple of typos in zebra vty prompt and output text.

zebra: fix a couple of typos

---

ospfd/ospf_vty.c

Signed-off-by: Rei Shimizu <rshimizu@apache.org>
This PR enables to show ospfd database info using formatted json. As result, we can see such a result as following format.
```
R1# show ip ospf database json
{
"routerId":"1.1.1.1",
"areas":{
"0.0.0.0":{
"routerLinkStates":[
{
"lsId":"1.1.1.1",
"advertisedRouter":"1.1.1.1",
"lsaAge":460,
"sequenceNumber":"80000006",
"checksum":"95f4",
"numOfRouterLinks":3
},
...
}
```

ospfd: show ospf database info using formatted json

---

bgpd/bgp_route.c

The withdraw message and announcement message of a prefix are received continuously within 50ms, which may lead to abnormal aggregation route reference count.
step1:
local config aggregate route 111.0.0.0/24
receive route：111.0.0.1/32 111.0.0.02/32
ref_count:2
step2:
peer withdraw 111.0.0.1/32 and  network 111.0.0.1/32  in 50ms
receive route：111.0.0.1/32 111.0.0.02/32
ref_count:1
step3:
peer withdraw 111.0.0.1/32
receive route：111.0.0.02/32
ref_count:0
aggregate route will be withdrawn abnormally
Signed-off-by: liuze03 <liuze03@baidu.com>

bgpd: Fix aggregated routes are withdrawn abnormally.

---

lib/command.c

Before patch:
```
service cputime-warning 1000
service walltime-warning 2000
```
After patch:
```
service cputime-warning 1
service walltime-warning 2
```

lib: fix display cputime-warning and walltime-warning

---

bgpd/bgp_nexthop.c
bgpd/subdir.am
doc/user/bgp.rst

This PR contains 3 commits.
Commit 1 of this MR(bf85e4c5f1008a12faea6e52de01b910d2b20e2c) is a patch from @yar-fed 's PR: https://github.com/FRRouting/frr/pull/12171.
Commit 2 and commit 3 are changes on top of the changes present in #12171.
Changes in commit 2:
1. Updated "show bgp vrf <vrf-name> nexthop detail"
and "show bgp vrf <vrf-name> import-check-table
detail" show commands to display paths associated with
nexthop. "detail" option was previously unused.
2. Added 'ipv4' and 'ipv6' JSON object under top level JSON.
3. Removed the "nexthops" JSON object which was under the top
level JSON object
4. Renamed "ifname" to "interfaceName"
5. Renamed "gates" JSON obejct to "nexthops"
6. Changed "flags" JSON array to JSON object and changed the
flags from string to boolean
```
JSON output: …
```

Bgp nexthop json changes

---

zebra/zebra_vxlan.c

Missing json attributes added for show evpn json
Before:
```
tor-1# show evpn json
{
"advertiseGatewayMacip":"No",
"numVnis":26,
"numL2Vnis":21,
"numL3Vnis":5,
"isDuplicateAddrDetection":true,
"maxMoves":5,
"detectionTime":180,
"detectionFreezeTime":0,
"macHoldtime":1080,
"neighHoldtime":1080,
"startupDelay":180,
"startupDelayTimer":"--:--:--",
"uplinkConfigCount":0,
"uplinkActiveCount":0
}
tor-1#
```
After:
```
tor-1# show evpn json
{
"advertiseGatewayMacip":"No",
"advertiseSviMacip":"No",
"advertiseSviMac":"No",
"numVnis":26,
"numL2Vnis":21,
"numL3Vnis":5,
"isDuplicateAddrDetection":true,
"maxMoves":5,
"detectionTime":180,
"detectionFreezeTime":0,
"macHoldtime":1080,
"neighHoldtime":1080,
"startupDelay":180,
"startupDelayTimer":"--:--:--",
"uplinkConfigCount":0,
"uplinkActiveCount":0
} …
```

zebra: Add missing json attributes for show evpn

---

alpine/APKBUILD.in

As the title says, replace `isl` package with `isl-dev` package in Alpine Docker build. The Alpine upstream changed the package name, and it caused a build failure.

docker,alpine: Remove isl from dependencies

---

zebra/dplane_fpm_nl.c

When FRR receives a netlink message that it decides to stop parsing it returns a 0 ( instead of a -1 ).  Just make the dplane continue reading other data instead of aborting the read.

zebra: Continue fpm_read when we decide a netlink message is not needed

---

bgpd/bgp_evpn.c

When creating one interface "vxlan66" ( ip link add vxlan66 type vxlan ... ), which initially maintains down status, saw one unexpected EC log:
```
zebra[37906]: [ZAG0W-VSNSD] interface vxlan66 vrf default(0) index 35 becomes active.
zebra[37906]: [HPWGA-Y527W] IFLA_VXLAN_LINK missing from VXLAN IF message
...
zebra[37906]: [W6BZR-YZPAB] RTM_NEWLINK update for vxlan66(35) sl_type 0 master 0 flags 0x1002
zebra[37906]: [MR3ZF-ATDBY] Intf vxlan66(35) has gone DOWN
zebra[37906]: [T44X9-FFNVB] Intf vxlan66(35) L2-VNI 66 is DOWN
zebra[37906]: [KEGYY-K8XVV] Send EVPN_DEL 66 to bgp
zebra[37906]: [HPWGA-Y527W] IFLA_VXLAN_LINK missing from VXLAN IF message
bgpd[37911]: [TV0XP-3WR0A] Rx VNI del VRF default VNI 66 tenant-vrf default SVI ifindex 0
bgpd[37911]: [MDW89-YAXJG][EC 33554497] 0: VNI hash …
```

bgpd: remove one EC log

---

pimd/pim_ifchannel.c

pimd: Handling SGRPT prune received
```
Topology:
Receiver----R1----(ens192)R2(ens224)----R3----R4----Source
-----------------------------
```  
R1=LHR
R2=RP
R4=FHR
Problem:
1. Direct  connected link between R1 and R3 is down initially.
2. So traffic flow path is R4<->R3<->R2<->R1<->Receiver.
3. Mroutes are properly created on all the nodes.
4. Up the direct connected link between R1 and R3.
5. Traffic flows in both the paths.
R4<->R3<->R2<->R1<->Receiver
R4<->R3<->R1<->Receiver
6. Duplicate traffic received at the receiver.
Root Cause:
Initially when the direct connected link between R1 and R3 is
down, traffic flows via RP(R2). So in RP (S,G) installed with
IIF as ens224 and OIF as ens192 (reference = 2) with mask
PIM_OIF_FLAG_PROTO_STAR and PIM_OIF_FLAG_PROTO_PIM.
Now when the direct …

pimd, pim6d: Handling SGRPT prune received

---

doc/user/evpn.rst
zebra/zebra_evpn_mac.c
zebra/zebra_vty.c
zebra/zebra_vxlan.c
zebra/zebra_vxlan.h

A new show command "show evpn mac vni xx detail [json]" to display details of all the mac entries for the
requested VNI.
output of show evpn mac vni xx detail json:
```
{
"numMacs":18,
"macs":{
"00:02:00:00:00:0d":{
"type":"remote",
"remoteEs":"03:44:38:39:ff:ff:02:00:00:02",
"localSequence":0,
"remoteSequence":0,
"detectionCount":0,
"isDuplicate":false,
"syncNeighCount":0,
"neighbors":{
"active":[
"2001:fee1:0:9::d",
"fe80::202:ff:fe00:d"
],
"inactive":[
]
}
}
}
}
```
Also added remoteEs field in the JSON output of
"show evpn mac vni xx json".
output of show evpn mac vni xx json:
```
"00:02:00:00:00:0d":{
"type":"remote",
"remoteEs":"03:44:38:39:ff:ff:02:00:00:02",
"localSequence":0,
"remoteSequence":0,
"detectionCount":0,
"isDuplicate":false
}
```
Signed-off-by: Pooja Jagadeesh Doijode …

zebra: Evpn mac vni detail show command

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_evpn_vty.h
bgpd/bgp_route.c

Fix crash on "show bgp all" when BGP EVPN is set.
> #0  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007fdfe03cf53c in core_handler (signo=11, siginfo=0x7ffdebbffe30, context=0x7ffdebbffd00) at lib/sigevent.c:261
> #3  0x00000000004d4fec in bgp_attr_get_community (attr=0x41) at bgpd/bgp_attr.h:553
> #4  0x00000000004eee84 in bgp_show_table (vty=0x1a790d0, bgp=0x19d0a00, safi=SAFI_EVPN, table=0x19f6010, type=bgp_show_type_normal, output_arg=0x0, rd=0x0, is_last=1, output_cum=0x0,
>     total_cum=0x0, json_header_depth=0x7ffdebc00bf8, show_flags=4, rpki_target_state=RPKI_NOT_BEING_USED) at bgpd/bgp_route.c:11329
> #5  0x00000000004f7765 in bgp_show (vty=0x1a790d0, bgp=0x19d0a00, afi=AFI_L2VPN, safi=SAFI_EVPN, type=bgp_show_type_normal, …

bgpd: fix show bgp all with evpn

---

bgpd/bgp_route.c
doc/user/bgp.rst

Introduce a "detail" keyword for per-neighbor/per-afi-safi advertised-routes and received-routes show commands. Includes json support.

bgpd: add "detail" for advertised/received-routes

---

zebra/rt_netlink.c
zebra/zebra_dplane.c

Just remove redundant white spaces in debug information.
Before:
```
2023/01/11 05:04:48 ZEBRA: [W8V7C-6W4DS] init neigh ctx NEIGH_INSTALL: ifp vlan100, mac  9a:68:e9:73:74:88, ip 88.88.88.88
2023/01/11 05:04:48 ZEBRA: [NH6N7-54CD1] Tx RTM_NEWNEIGH family ipv4 IF vlan100(8) Neigh 88.88.88.88 MAC  9a:68:e9:73:74:88 flags 0x10 state 0x40 ext_flags 0x0
```
After:
```
2023/01/11 05:17:26 ZEBRA: [W8V7C-6W4DS] init neigh ctx NEIGH_INSTALL: ifp vlan100, mac 9a:68:e9:73:74:88, ip 88.88.88.88
2023/01/11 05:17:26 ZEBRA: [NH6N7-54CD1] Tx RTM_NEWNEIGH family ipv4 IF vlan100(8) Neigh 88.88.88.88 MAC 9a:68:e9:73:74:88 flags 0x10 state 0x40 ext_flags 0x0
```

zebra: cosmetic changes for debug

---

bfdd/control.c

Apply upper bound on incoming control messages, drop invalid messages. We had an issue reported about this, seems like something worth fixing?
Fixes: #10760

bfdd: validate incoming control message length

---

bgpd/bgp_vty.c
doc/user/bgp.rst

json support extended for show [ip] bgp vrfs <vrf-name> json
**Before:**
```
tor-2# show ip bgp vrfs default json
% JSON option not yet supported for specific VRF
tor-2#
tor-2# show bgp vrfs sym_1 json
% JSON option not yet supported for specific VRF
tor-2#
```
**After:**
```
tor-1# show ip bgp vrfs default json
{
"default":{
"type":"DFLT",
"vrfId":0,
"routerId":"27.0.0.7",
"numConfiguredPeers":2,
"numEstablishedPeers":2,
"l3vni":0,
"rmac":"00:00:00:00:00:00",
"interface":"unknown"
}
}
tor-1#
tor-1# show bgp vrfs sym_1 json
{
"sym_1":{
"type":"VRF",
"vrfId":21,
"routerId":"27.0.0.81",
"numConfiguredPeers":0,
"numEstablishedPeers":0,
"l3vni":8888,
"rmac":"44:38:39:ff:ff:25",
"interface":"vlan490_l3"
}
}
tor-1# show bgp vrfs test json
{
}
tor-1#
```
Ticket:#3314672
Issue:3314672
Testing: UT …

bgpd: show bgp vrfs per vrf level json support

---

bgpd/bgp_bfd.c
bgpd/bgp_vty.c

Related: https://github.com/FRRouting/frr/issues/12625

bgpd: Warn user about mixed order of commands executed

---

bgpd/bgpd.c

For vrf name in debug, use `bgp->name_pretty` instead of `bgp->name`.
Before:
```
2023/01/15 05:04:19 BGP: [P4GAZ-JHRM3] evpn vrf VRF default nh init
2023/01/15 05:04:19 BGP: [ZZKY3-FX5JH] bgp_get: Registering BGP instance (null) to zebra <-
2023/01/15 05:04:19 BGP: [TNK7N-FJF7K] Registering VRF 0
```
After:
```
2023/01/15 21:38:16 BGP: [P4GAZ-JHRM3] evpn vrf VRF default nh init
2023/01/15 21:38:16 BGP: [ZZKY3-FX5JH] bgp_get: Registering BGP instance VRF default to zebra <-
2023/01/15 21:38:16 BGP: [TNK7N-FJF7K] Registering VRF 0
```

bgpd: fix wrong vrf name for debug

---

tests/topotests/route_scale/scale_test_common.py

I'm seeing test failures after in micronet runs in CI after 7 seconds * 30 attempts at seeing if it succeeds. Let's see if another 60 seconds of attempts allows this to work properly.

tests: route_scale tests are failing on micronet

---

bgpd/bgp_keepalives.c
bgpd/bgp_keepalives.h

[New LWP 2524]
[New LWP 2539]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". Core was generated by `/opt/avi/bin/bgpd -f /run/frr/avi_ns3_bgpd.config -i /opt/avi/etc/avi_ns3_bgpd.'. Program terminated with signal SIGABRT, Aborted.
[Current thread is 1 (Thread 0x7f92ac8f1740 (LWP 2524))]
#0  0x00007f92acb3800b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f92acb17859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f92acb17729 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f92acb28fd6 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f92accf2164 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x000055b46be1ef63 in bgp_keepalives_wake () at …

bgpd: Fix crash during shutdown due to race condition

---

zebra/zebra_rib.c

After calling `rib_unlink` the variable `re` will point to `free()`d memory, so don't attempt to use it after this point.
Found by Coverity Scan (Coverity ID 1519784)
---
```c
static void rib_process(struct route_node *rn) {
/* ... */
RNODE_FOREACH_RE_SAFE (rn, re, next) {
/* ... */
if (CHECK_FLAG(re->status, ROUTE_ENTRY_CHANGED)) {
if (!nexthop_active_update(rn, re)) {
if (re->type == ZEBRA_ROUTE_TABLE) {
if (re != old_selected) {
/* ... */
rib_unlink(rn, re);
/* `re` now points to `free()`d memory */
} else
SET_FLAG(re->status,
ROUTE_ENTRY_REMOVED);
}
/* ... */
/* `re` is used after `free()` in `zsend_route_notify_owner` */
zsend_route_notify_owner(
rn, re, ZAPI_ROUTE_FAIL_INSTALL,
info->afi, info->safi);
continue;
}
} else {
/* ... */
}
/* ... */
}
```

zebra: fix use after free on RIB processing

---

bgpd/bgp_route.c
tests/topotests/bgp_vpnv4_gre/r1/bgpd.conf
tests/topotests/bgp_vpnv4_gre/r1/ipv4_routes.json

MPLS VPN networks can either peer with iBGP or eBGP. When calculating the distance to send to zebra, the imported prefix is never sent with distance information, even if the vty command is used under the ipv4 unicast address family:
router bgp 65505 vrf vrf1
distance bgp 26 27 28
[vpn config]
The observation is that the distance sent to zebra for an imported prefix is still 20:
[..]
VRF vrf1:
B>  192.168.0.0/24 [20/0] via 2.2.2.2 (vrf default) (recursive), label 20, weight 1, 00:00:12
*                          via 10.125.0.6, ntfp3 (vrf default), label implicit-null/20, weight 1, 00:00:12
The expectation is that the incoming prefix has to follow the distance that is configured, or the distance derived from the peer relationship established by the parent …

bgpd: imported vpn entries get appropriate distance

---

doc/user/evpn.rst
zebra/zebra_vty.c

cli & json support extended for show vrf vrf-id vni
commands:
- show vrf <vrf-name> vni
- show vrf all vni
- show vrf <vrf-name> vni json
- show vrf all vni json
Before:
```
tor-1# show vrf vni
VRF                                   VNI        VxLAN IF
L3-SVI               State Rmac
default                               100        None
None                 Down  None
sym_1                                 8888       vxlan99
vlan490_l3           Up    44:38:39:ff:ff:25
sym_2                                 8889       vxlan99
vlan491_l3           Up    44:38:39:ff:ff:25
sym_3                                 8890       vxlan99
vlan492_l3           Up    44:38:39:ff:ff:25
sym_4                                 8891       vxlan99
vlan493_l3           Up    44:38:39:ff:ff:25
sym_5 …
```

zebra: vrf-id support for show vrf vni json cmd

---

lib/zlog_5424.c

Changes:
- Convert `unsigned int` to `time_t` to satisfy time truncation warnings even though at this point we had already used the modulus operator.
- Avoid trying to access outside the bounds of the array
`months` array has a size of 13 elements, but the code inside the loop uses `i + 1` to peek on the next month.
Found by Coverity Scan (CID 1519752 and 1519769)

lib: fix gmtime_assafe potential issues

---

zebra/zebra_fpm_netlink.c

Don't attempt to encode the pointer address instead pass the pointer directly so the real contents can be accessed.
(`ri->pref_src` type is `union g_addr *`)
Found by Coverity Scan (CID 1482162)

zebra: fix fpm netlink encode out of bounds read

---

tests/topotests/pim_basic/test_pim.py
tests/topotests/zebra_netlink/test_zebra_netlink.py

Looks like under heavy load, the test is not giving enough time to come to steady state.  Do this:
a) send more udp packets and for longer
b) Increase time spent waiting

tests: pim_basic fails in micronet

---

bgpd/bgp_attr.c

In ipv6 vpn, when the global and the local ipv6 address are received, when re-transmitting the bgp ipv6 update, the nexthop attribute length must still be 48 bytes.

bgpd: fix vpnv6 nexthop encoding

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst

Limit the OutputQueue size ala what was done for the input Queue size.

Bgp outq limit

---

babeld/babel_main.c

babeld's `--terminal` option doesn't work because it replaces `stdin` with `/dev/null`. It seems to me this function can be removed as `frr_run` handles that in daemon mode.
Signed-off-by: Yuxiang Zhu <vfreex@gmail.com>

babeld: Fix --terminal option

---

ospfd/ospf_vty.c

When show ip ospf border-routers json (without vrf) specified, it leads to crash if there no border-routers information.
Fix:
Do not free json object if use_vrf flag (means vrf option is not passed) is not set.
Testing Done:
with fix:
```
l1# show ip ospf border-routers json
{
}
l1# show ip ospf vrf default border-routers json
{
}
```

ospfd: fix crash show ip ospf border-routers json

---

zebra/rt_netlink.c
zebra/rt_netlink.h
zebra/zebra_fpm_netlink.c

fpm:netlink format doesn't indicate the protocol information
in routes of BGP, OSPF and other protocols. Routes of those
protocols just indicate protocol as zebra.
The below route is actually BGP route but 'proto': 11
indicates that it is zebra.
{'attrs': [('RTA_DST', 'dummy'),
('RTA_PRIORITY', 0),
('RTA_GATEWAY', 'dummy'),
('RTA_OIF', 2)],
'dst_len': 32,
'family': 2,
'flags': 0,
'header': {'flags': 1025,
'length': 60,
'pid': 3160253895,
'sequence_number': 0,
'type': 24},
'proto': 11,
'scope': 0,
'src_len': 0,
'table': 254,
'tos': 0,
'type': 1}
with this change it is now seen with 'proto': 186
indicates that it is BGP.
{'attrs': [('RTA_DST', 'dummy'),
('RTA_PRIORITY', 0),
('RTA_GATEWAY', 'dummy'),
('RTA_OIF', 2)],
'dst_len': 32,
'family': 2,
'flags': 0,
'header': {'flags': 1025,
'length': …

zebra_fpm: Add support for other protocols in fpm:netlink

---

bgpd/bgp_evpn.c

Two changes for debug log -
1. Display empty VRF as "None".
2. Correct wrong "type-2" word for type-3 route.
Before:
```
2023/01/17 04:00:30 BGP: [Z5AV7-75RTE] VRF   vni 100 type-2 route evp [3]:[0]:[32]:[88.88.88.88] RMAC 00:00:00:00:00:00 nexthop 88.88.88.88 esi (null)
```
After:
```
2023/01/17 04:05:24 BGP: [M3X4Y-24DVB] VRF None vni 100 type-3 route evp [3]:[0]:[32]:[88.88.88.88] RMAC 00:00:00:00:00:00 nexthop 88.88.88.88 esi (null)
```

bgpd: cosmetic changes for debug

---

babeld/.gitignore
babeld/babel_interface.c
babeld/babeld.c
babeld/subdir.am

Some babeld commands doesn't have the corresponding negative commands defined, so those commands doesn't work with frr-reload.py (https://github.com/FRRouting/frr/pull/12611).
This PR adds those missing commands.
Signed-off-by: Yuxiang Zhu <vfreex@gmail.com>

babeld: Add missing `no` commands

---

bgpd/bgp_damp.c
eigrpd/eigrp_interface.c
isisd/isis_spf.c
ldpd/logmsg.c
lib/network.c
lib/network.h
ospf6d/ospf6_message.c
ospfd/ospf_interface.c
pimd/mtracebis_netlink.c
zebra/zebra_netns_id.c

Changes:
- Introduce new function for generating sequence numbers (clears up coverity scan warnings about time truncation)
- CIDs 1519812, 1519786, 1519783 and 1519772
- Replace PIM's tool mtracebis `time(NULL)` sequence seed with `getpid()`
- CID 1519828
- Increase `ldpd` log function variables storage for `time_t`
- CID 1519735
- Fix BGP dampening function prototype to avoid time truncation
- CID 1519802
- Fix IS-IS SPF show command time truncation
- CID 1519793
Please read individual commits for more information.

*: fix time truncation in many places

---

vtysh/subdir.am

The build failed if two conditions are met at the same time:
1. Configure with `--disable-dependency-tracking`
2. Set an indenpendent build directory
```
anlan@host:~/frr/build$ make
make: Entering directory '/home/anlan/frr/build'
true
/usr/bin/perl ../vtysh/daemons.pl zebra bgpd ripd ripngd ospfd ospf6d isisd fabricd nhrpd ldpd babeld eigrpd  pimd pim6d pbrd staticd bfdd vrrpd pathd > vtysh/vtysh_daemons.h
/bin/bash: line 1: vtysh/vtysh_daemons.h: No such file or directory
make: *** [Makefile:17644: vtysh/vtysh_daemons.h] Error 1
make: Leaving directory '/home/anlan/frr/build'
```
`~/frr/` is source directory, `~/frr/build/` is the specified build directory.
So, just create necessary directory - `vtysh/`.

vtysh: fix build failure for certain case

---

bgpd/bgp_evpn_vty.c

For BGP evpn route table detail JSON to use non pretty form of display.
Problem:
In scaled EVPN route table detail JSON dump occupies high resources (CPU + memory) of the system. 
In high scale EVPN route dump using pretty form
hogs CPU for a while which can trigger watchfrr
to kill bgpd.
Solution:
Avoid pretty JSON print for detail version dump

bgpd: evpn route detail json display non prett

---

tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vpn_routes.json
tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vpn_routes_unfiltered.json
tests/topotests/bgp_vpnv4_noretain/test_bgp_vpnv4_noretain.py

Fix the following issues:
- two tests are done in one function. Dispatch the tests in two functions to help the test debug.
- the first test passes even if a third prefix is not filtered. Match the exact to avoid false positive.
- the expected values contains variable like version. Do no check variable values.

topotests: fix bgp_vpnv4_noretain

---

zebra/zebra_dplane.c

Locking around the list of providers/plugins is not helpful - these only change at init time. Clear some SA warnings by removing the locking.

zebra: fix SA warning, don't lock plugin list

---

.github/workflows/freeze.yml

Mostly useful duging the freeze period to warn the maintainers from merging unwanted PRs.

github: Prevent merging (fail CI) if 'freeze' label exists for PR

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_mh.c
bgpd/bgp_flowspec.c
bgpd/bgp_mac.c
bgpd/bgp_route.c
bgpd/bgp_route.h

These two functions always return 0.  As such any and all tests against this make no sense.  Remove the return 0 to a void and follow the chain, logically, to remove all the dead code.

bgpd: bgp_update and bgp_withdraw never return failures

---

tests/topotests/lib/topotest.py

Fixes killRouterDaemons() function which occasionally deleted the wrong pidfile.
Nested loops with same loop variable caused wrong pidfile selection for deletion.
As a result, some processes would no longer be tracked and not deleted between
tests.

tests: Topotests fix for deleting wrong pidfile

---

zebra/zebra_rib.c

There existed the idea, from Volta, that a nexthop group would not have the same nexthops installed -vs- what FRR actually sent down.  The dplane would notify you.
With the addition of 06525c4f99d4dcafdf448565f7e11bd70993697d the code was put behind a bit of a wall controlled the usage of it.
The flag ROUTE_ENTRY_USE_FIB_NHG flag was being used to control which set was being sent up to concerned parties in nexthop tracking.  Put this flag behind the wall and do not necessarily set it when we receive a data plane notification about a route being installed or not.
Fixes: #12706

zebra: Send nht resolved entry up to concerned protocols in all cases

---

lib/subdir.am
tests/isisd/subdir.am
tests/lib/subdir.am
vtysh/subdir.am
yang/embedmodel.py

When running the build in a separate build directory, redirecting output into a file can error out if the directory does not exist yet.  Some places already had `mkdir -p` calls, but not all.
Make all occurences of this consistently use `@$(MKDIR_P)`.
(Extension of PR #12575 to catch more places.)

build: consistently mkdir -p output for redirect

---

tests/topotests/ospf_basic_functionality/test_ospf_lan.py
tests/topotests/ospf_gr_helper/test_ospf_gr_helper1.py
tests/topotests/ospf_gr_helper/test_ospf_gr_helper2.py
tests/topotests/ospf_gr_helper/test_ospf_gr_helper3.py

Calls were missing the () and caused the stop_topology() to be skipped

tests: Fix wrong tgen.stop_topology() calls which got skipped

---

bgpd/rfapi/rfapi_vty.h
lib/db.h
lib/libfrr.c
lib/zlog.h
tests/bgpd/test_peer_attr.c
tests/lib/test_nexthop_iter.c

cf. individual subjects/commits, just a bunch more format string attributes
also stripped a duplicate of `asprintfrr` from `tests/`

*: more format string fixing

---

doc/user/installation.rst
vtysh/vtysh.c

The shell access code has been hidden behind a configure option now for 5+ years.  Frankly I don't think FRR should be carrying such code that easily allows you to shoot yourself in the foot from a security perspective.  If someone really needs this they can carry this as a private patch.

vtysh: Remove shell access code

---

bgpd/bgp_packet.c

Before this patch, we always passed `struct attr` for NLRI_UPDATE, but if we have a situation with treat-as-withdraw (for example: malformed attribute, or using a command like `neighbor path-attribute treat-as-withdraw`) the route MUST be withdrawn form the BGP table.
Hence, we MUST pass attr as NULL, in this case we already have this check under NLRI_ATTR_ARG() macro, just reuse it properly.
In other words: if we handle the UPDATE as treat-as-withdraw, we SHOULD NOT reset the session with an error, but just withdraw the route.
This commit is the part of https://github.com/FRRouting/frr/pull/12728, but should be for 8.5 release, while #12728 - not.

bgpd: Set attr to NULL when passing NLRI_UPDATE with treat-as-withdraw

---

zebra/zebra_vxlan.c

The two commands ( `advertise-svi-ip` and `advertise-default-gw` ) can
be set in both `BGP_EVPN_NODE` and `BGP_EVPN_VNI_NODE`. So, when
configuring one of them, need to consider the configuration of the
other.  Configuring it under `BGP_EVPN_NODE`, it does check the other.
However, the conversion is wrong when configured under `BGP_EVPN_VNI_NODE`.
One example:
With the following steps, the evpn routes with `SVI` will be mistakenly
withdrawn.
```
anlan(config-router-af)# advertise-svi-ip
anlan(config-router-af)# vni 100
anlan(config-router-af-vni)# advertise-svi-ip
anlan(config-router-af-vni)# no advertise-svi-ip
```
This commit fixed the conversion under `BGP_EVPN_VNI_NODE` for the
two commands.
Remove redundant spaces for debug log. By the way, adjust one format problem.

zebra: fix wrong conversion for evpn advertising

---

bgpd/bgp_ecommunity.c

The function ecommunity_str2com_internal appears to want to handle the ecommunity_token_rt6 enum but skips over it.  Commit 9a659715dfcb6c0b1e3ef8004b6c9d14c55f2081 tried to add this but I really don't see how this is going to behave correctly.  Add the ecommunity_token_rt6 case to the switch statement so it is handled appropriately?

bgpd: ecommunity_token_rt6 is not handled

---

tests/topotests/bgp_evpn_vxlan_topo1/PE1/evpn.vni.json
tests/topotests/bgp_evpn_vxlan_topo1/PE2/evpn.vni.json
tests/topotests/bgp_evpn_vxlan_topo1/test_bgp_evpn_vxlan.py
zebra/zebra_evpn.c
zebra/zebra_vxlan.c

Few of the JSON fields in "show evpn vni detail" command is confusing and does not follow the naming convention used in EVPN deployments. Since this is the detail option, it is better to address it now.
```
primary# show evpn vni detail json
[
{
"vni":200,
"type":"L2",
"tenantVrf":"default",
"vxlanInterface":"vni200",
"vxlanIfindex":19,
"sviInterface":"br200",
"sviIfindex":18,
"vtepIp":"2.2.2.1",
"mcastGroup":"0.0.0.0",
"advertiseGatewayMacip":"No",
"advertiseSviMacip":"No",
"numMacs":0,
"numArpNd":0,
"numRemoteVteps":1,
"remoteVteps":[
{
"ip":"2.2.2.2",
"flood":"HER"
}
]
},
{
"vni":100,
"type":"L3",
"tenantVrf":"default",
"localVtepIp":"2.2.2.1",
"vxlanIntf":"vni100",
"sviIntf":"br100",
"state":"Up",
"sysMac":"aa:bb:cc:dd:ee:f1",
"routerMac":"aa:bb:cc:dd:ee:f1",
"vniFilter":"none", …
```

zebra: fix JSON fields for show evpn vni detail

---

bgpd/bgp_evpn_vty.c

```
anlan(config-router-af)# vni 33
anlan(config-router-af-vni)# route-target both 44:55
anlan(config-router-af-vni)# no route-target both 44:55
vtysh: error reading from bgpd: Resource temporarily unavailable (11)Warning: closing connection to bgpd because of an I/O error!
```
When `bgp_evpn_vni_rt_cmd` deals with "both" type, it wrongly created only one node ( should be two nodes ) for lists of both `vpn->import_rtl` and `vpn->export_rtl`.  At this time, the two lists are already wrong.
In `no route-target both RT`, it will free the single node from lists of both `vpn->import_rtl` and `vpn->export_rtl`.  After freed from `vpn->import_rtl`, it is "use-after-free" at the time of freeing it from `vpn->export_rtl`. It causes crash sometimes, or other unexpected behaviours.
This issue is …

bgpd: fix use-after-free crash for evpn

---

tests/topotests/bgp_vpnv4_noretain/test_bgp_vpnv4_noretain.py

Filter out keys in JSON output with "grep -v" does not work when JSON does not use the pretty format.
Use native python code to filter out keys.
Fixes: 6c13bd5744 ("topotests: fix bgp_vpnv4_noretain")

tests: do not use exclude grep

---

bgpd/bgp_route.c
doc/user/bgp.rst

Couple commits adding functionality (and docs) to advertised/received/bestpath-routes.
1 - introduce `detail` option for bestpath-routes
2 - introduce specific prefix lookups for advertised-routes/received-routes
I intentionally didn't add specific prefix lookups for bestpath-routes, because I felt like the intent behind "bestpath-routes" was to get a list of routes from the peer (the ones selected as best) rather than simply checking the details of one particular prefix.
However, I would be willing to spend the time to get this done if someone feels strongly that bestpath-routes should have a specific prefix match.

Improvements to advertised/received/bestpath-routes commands

---

pimd/pim6_mld.c

Currently "show ipv6 mld join json" o/p is
{
"default":{
"ens192":{
"ff02:2":{
"::":{
"state":"JOIN",
"created":"00:01:50.595",
"lastSeen":"00:00:38.403",
}
}
}
}
}
Here, I modified the o/p as below for better understanding. {
{
"default":{
"vrf":"default",
"ens192":{
"ff02::2":{
"*":{
"state":"JOIN",
"created":"00:00:42.766",
"lastSeen":"00:00:05.266"
}
}
}
}
}
Issue: #12755

pim6d: Modify "show ipv6 mld join json" o/p

---

vrrpd/vrrp.c

This is still causing crashes somehow.

vrrpd: give null when using null ifp to lookup vr

---

bgpd/bgp_routemap.c
doc/user/basic.rst
lib/routemap.c
lib/routemap.h
lib/subdir.am
ospfd/ospf_routemap.c
zebra/redistribute.c
zebra/zebra_routemap.c

See individual commits but end goal is to see stuff like this:
```eva(config)# ip import-table 33 route-map FAILURE
2023-02-13 09:38:11.332 [DEBG] zebra: [YY2TN-VKBG5] Importing routes from table 33
2023-02-13 09:38:11.332 [DEBG] zebra: [KC1TZ-DAY7N] route_match_ip_next_hop: Access-List Specified: 192.168.119.33 does not exist defaulting to NO_MATCH
2023-02-13 09:38:11.332 [DEBG] zebra: [KZK58-6T4Y6] No best match sequence for pfx: 1.2.3.4/32 in route-map: FAILURE, result: no match
2023-02-13 09:38:11.332 [DEBG] zebra: [H5AW4-JFYQC] Route-map: FAILURE, prefix: 1.2.3.4/32, result: deny
2023-02-13 09:38:11.332 [DEBG] zebra: [KC1TZ-DAY7N] route_match_ip_next_hop: Access-List Specified: 192.168.119.33 does not exist defaulting to NO_MATCH
2023-02-13 09:38:11.332 [DEBG] zebra: [KZK58-6T4Y6] No …
```

Routemap debugging

---

bgpd/bgp_routemap.c

The call for all_digit is unnecessary as that the local preference must be entered as a digit.  In other words you cannot get to this point without the string being all digits.  This check is unnecessary.

bgpd: Remove unnecessary all_digit() call

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_route.c
bgpd/bgp_route.h
tests/topotests/bgp_aigp/test_bgp_aigp.py
tests/topotests/bgp_community_alias/test_bgp-community-alias.py
tests/topotests/bgp_path_attribute_discard/test_bgp_path_attribute_discard.py
tests/topotests/bgp_path_attribute_treat_as_withdraw/test_bgp_path_attribute_treat_as_withdraw.py

"show bgp <afi> <safi> json detail" was incorrectly displaying header information from route_vty_out_detail_header() as an element of the "paths" array. This corrects the behavior for 'json detail' so that a route holds a dictionary with keys for "paths" and header info, which aligns with how we structure the output for a specific prefix, e.g. "show bgp <afi> <safi> <prefix> json".
Before:
```
ub20# show ip bgp json detail
{
"vrfId": 0,
"vrfName": "default",
"tableVersion": 3,
"routerId": "100.64.0.222",
"defaultLocPrf": 100,
"localAS": 1,
"routes": { "2.2.2.2/32": [
{                           <<<<<<<<<  should be outside the array
"prefix":"2.2.2.2/32",
"version":1,
"advertisedTo":{
"192.168.122.12":{
"hostname":"ub20-2"
}
}
},
{
"aspath":{
"string":"Local",
"segments":[
],
"length":0 …
```

bgpd: fix 'json detail' output structure

---

bgpd/bgp_routemap.c

Instead of hard coding so that if something ever changes it will break.  Let's use the #defines that FRR has included for us.

bgpd: Use actual defines to set values

---

ospfclient/ospfclient.py
ospfd/ospf_apiserver.c
ospfd/ospf_opaque.c
ospfd/ospf_route.c
tests/topotests/ospfapi/r1/ospfd.conf
tests/topotests/ospfapi/r1/zebra.conf
tests/topotests/ospfapi/r2/ospfd.conf
tests/topotests/ospfapi/r3/ospfd.conf
tests/topotests/ospfapi/r4/ospfd.conf
tests/topotests/ospfapi/r4/zebra.conf
tests/topotests/ospfapi/test_ospf_clientapi.py

- Add opaque data to the `detail json` show command output
- Bugfix with router reachability counts
- Bugfix with API reachability sorting order
- simplify ospfclient by removing implicit opaque type registration
- Add ability to enter API commands from over stdin
- Improve the topotest to adding a 4 router ring topology

ospfd client api bugfix and refinements

---

lib/log.h
ospfd/ospf_abr.c
ospfd/ospf_abr.h
ospfd/ospf_flood.c
ospfd/ospf_flood.h
ospfd/ospf_lsa.c
ospfd/ospf_lsa.h
ospfd/ospf_lsdb.c
ospfd/ospf_packet.c
ospfd/ospf_route.c
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h
tests/topotests/lib/ospf.py
tests/topotests/ospf_basic_functionality/ospf_flood_reduction.json
tests/topotests/ospf_basic_functionality/test_ospf_flood_reduction.py

As of now OSPF requires every LSA to be refreshed every 1800 seconds or else they will expire when they reach 
3600 seconds. This rfc proposes to overcome the LSA expiration by generalising the use of DoNotAge LSAs.
This technique will facilitate OSPF scaling by reducing OSPF traffic overhead in stable topologies.
This implementation handles CLIs, logic to flood DNA LSAs,  preventing LSAs from ageing,
generation and handling of Indication LSAs.
rfc link : https://datatracker.ietf.org/doc/html/rfc4136.
Below CLIs are added as part of this feature support.
Process/vrf level:
frr(config-router)# flood-reduction : Enables FR for all the areas.
frr(config-router)# no flood-reduction : Disables FR for all the areas.
Area level:
frr(config-router)# area [A.B.C.D$addr] flood-reduction : Enables …

ospfd: Support OSPF Refresh and Flooding Reduction RFC4136.

---

bgpd/bgpd.c

When leaving the BGP shutdown state we must restart the peer timers otherwise nothing will happen.

bgpd: Fix bgp no shutdown

---

bgpd/bgp_clist.c
bgpd/bgp_community.c
bgpd/bgp_community.h
bgpd/bgp_routemap.c
doc/user/bgp.rst
tests/topotests/bgp_communities_topo1/test_bgp_communities_topo2.py

Quite a few well-known communities from IANA's list do
not receive special treatment in Cisco IOS XR, and at least one
community on Cisco IOS XR's special treatment list, internet == 0:0,
is not formally a well-known community as it is not in [IANA-WKC] (it
is taken from the Reserved range [0x00000000-0x0000FFFF]).
https://datatracker.ietf.org/doc/html/rfc8642
This is Cisco-specific command which is causing lots of questions when it comes to debugging and/or configuring it properly, but overall, this behavior is very odd and it's not clear how it should be treated between different vendor implementations.
Let's deprecate it and let the operators use 0:0/0 communities as they want.

bgpd: Deprecate BGP `internet` community

---

doc/user/zebra.rst
zebra/rib.h
zebra/zapi_msg.c
zebra/zebra_rib.c
zebra/zebra_vty.c

a) Cleanup the cut-n-paste code that rib_match_ipv[4|6]_multicast
b) Cleanup doc and add `show ipv6 rpf X:X::X:X` as well as `show ipv6 rpf`

Rib match multicast

---

lib/prefix.c
lib/routemap.c

lib: skip route-map optimization if !AF_INET(6)
Currently we unconditionally send a prefix through the optimized
route-map codepath if the v4 and v6 LPM tables have been allocated and
optimization has not been disabled.
However prefixes from address-families that are not IPv4/IPv6 unicast
always fail the optimized route-map index lookup, because they occur on
an LPM tree that is IPv4 or IPv6 specific.
e.g.
Even if you have an empty permit route-map clause, Type-3 EVPN routes
are always denied:
```
--config
route-map soo-foo permit 10
--logs
2023/02/17 19:38:42 BGP: [KZK58-6T4Y6] No best match sequence for pfx: [3]:[0]:[32]:[2.2.2.2] in route-map: soo-foo, result: no match
2023/02/17 19:38:42 BGP: [H5AW4-JFYQC] Route-map: soo-foo, prefix: [3]:[0]:[32]:[2.2.2.2], result: deny
```
There is …

lib: skip route-map optimization if !AF_INET(6)

---

bgpd/bgp_attr.c
bgpd/bgpd.c
tests/topotests/bgp_confederation_astype/r1/bgpd.conf
tests/topotests/bgp_confederation_astype/r1/zebra.conf
tests/topotests/bgp_confederation_astype/r2/bgpd.conf
tests/topotests/bgp_confederation_astype/r2/zebra.conf
tests/topotests/bgp_confederation_astype/r3/bgpd.conf
tests/topotests/bgp_confederation_astype/r3/zebra.conf
tests/topotests/bgp_confederation_astype/test_bgp_confederation_astype.py

Closes https://github.com/FRRouting/frr/issues/12857

bgpd: Confederation fixes with remote-as external/internal

---

bgpd/bgp_rpki.c

Commit  6ccfd1030b42771cfb182e9e6ad53c5368d4b10e
did not properly handle asn parsing of the new
asn format.

bgpd: Fixup rpki and asn parsing

---

lib/routemap.c

Fixes missing debug guards for EVPN prefix conversion for optimized route-map lookup.

lib: add missing debug guards for route-map

---

bgpd/bgp_network.c

Sometimes bgp connections can be rejected for a variety of reasons.  Give a bit more context about what is going wrong so that the operator can make better decisions about their network.

bgpd: Give better debug message when configuration is being read in

---

pimd/pim_mroute.c

For incoming no-receiver SSM traffic, there isn't going to be a RP, much less a RPF.  We should install an MFC entry with empty oif regardless, so we don't get swamped with further notifications.
---
This is on top of #12878.
TBH while our behavior here for ASM can be argued to be correct, I'm not sure it's particularly useful — it results in the kernel spamming us with NOCACHE notifications if we have no RP config for the groups in question.

pimd: don't try to check RPF for incoming SSM data

---

pimd/pim_mroute.c

- the log message for input drops was incredibly useless, it grouped 3 different conditions that could cause drops to emit the one and same log message. That's incredibly unhelpful.
- log a warning and reinstall the MFC entry if we get a NOCACHE for something that we believe is already installed. We've seen this in production, though it's not quite clear what is causing MFC entries to be deleted. The warning hopefully helps tracking this down.
Flagging for backport since both of these are tracking-down-issues related and on the safe side.

pimd: bughunting improvements

---

bgpd/bgp_route.h

Before:
```
r1# sh ip bgp wide
BGP table version is 1, local router ID is 192.168.2.1, vrf id 0
Default local pref 100, local AS 65001
Network                                      Next Hop                                  Metric LocPrf Weight Path
*  172.16.255.254/32                            192.168.2.2                                    0             0 (65003) i
*>                                              192.168.1.2                                    0             0 (65002) i
Displayed  1 routes and …
```

bgpd: Align `show bgp ...` output with the header for wide option

---

bgpd/bgp_flowspec.c

According to the flowspec RFC 8955 a flowspec nlri is <length, <nlri data>> Specifying 0 as a length makes BGP get all warm on the inside.  Which in this case is not a good thing at all.  Prevent warmth, stay cold on the inside.
Reported-by: Iggy Frankovic <iggyfran@amazon.com>

bgpd: Flowspec overflow issue

---

bgpd/bgp_bmp.c
lib/prefix.c
lib/prefix.h

The l2vpn afi was not being properly displayed
when a show run was being issued.  Add a
afi2str_lower function and use it.
Fixes: #12867

lib, bgpd: bmp was not specifying l2vpn afi

---

doc/user/ospfd.rst
lib/vty.c
lib/vty.h
ospfd/ospf_vty.c

4 Commits:
commit 176900c12be977014b836c2db6b8b23cb297d18a:
ospfd: Fix "show ip ospf neighbor swp1 detail json" output
1. When OSPF unnumbered neighbor doesn't exist in any VRF,
OSPFD prints a bunch of empty JSON objects. Fixed it
by adding an outer JSON object with VRF information in it
2. Added "vrf" option to this command so that per VRF
unnumbered OSPF neighbor information can be retrieved
JSON output:
nl1# show ip ospf neighbor swp1 detail json
{
"default":{
},
"vrf1012":{
},
"vrf1013":{
},
"vrf1014":{
}
}
nl1# show ip ospf vrf vrf1012 neighbor swp4.2 detail json
{
"9.9.12.10":[
{
"ifaceAddress":"200.254.2.46",
"areaId":"0.0.0.0",
"ifaceName":"swp4.2",
"localIfaceAddress":"200.254.2.45",
"nbrPriority":1,
"nbrState":"Full",
"role":"DR",
"stateChangeCounter":6, …

ospfd: Added missing fields and option to query specific neighbor in VRF

---

lib/libfrr.c
lib/northbound.c
lib/northbound.h
lib/northbound_cli.c
lib/northbound_confd.c
lib/northbound_db.c
lib/northbound_grpc.cpp
lib/northbound_sysrepo.c
lib/vty.c

Pass context argument by value on initialization to be clear that the value is used/saved but not a pointer to the value. Previously the northbound code was incorrectly holding a pointer to stack allocated context structs.
However, the structure definition also had some musings (ifdef'd out code) and a comment that might be taken to imply that user data could follow the structure and thus be maintained by the code; it won't; so it can't; so get rid of the disabled misleading code/text from the structure definition.
The common use case worked b/c the transaction which cached the pointer was created and freed inside a single function
call (`nb_condidate_commit`) that executed below the stack allocation.
All other use cases (grpc, confd, sysrepo, and -- coming soon -- mgmtd) were bugs.

lib: fix init. use of nb_context to be by value not by reference

---

bgpd/bgp_attr.c

Just was blind when not seing it's already dup'ed above:
```	if (peer->sort == BGP_PEER_EBGP
&& (!CHECK_FLAG(peer->af_flags[afi][safi],
PEER_FLAG_AS_PATH_UNCHANGED)
|| attr->aspath->segments == NULL)
&& (!CHECK_FLAG(peer->af_flags[afi][safi],
PEER_FLAG_RSERVER_CLIENT))) {
aspath = aspath_dup(attr->aspath); <<<<<<<<<<<<<<<
```

bgpd: Avoid double aspath_dup() for confederation when remote-as != AS_SPECIFIED

---

lib/asn.c

In current code, some ASNUMs with redundant zero are legal, e.g. "1.01", "01.1", "1.001", "001.1", and more.  They should be forbidden.

lib: some ASNUMs should be forbidden

---

bgpd/bgpd.c

When allocating a new bit of memory free the old first.

bgpd: Prevent asn dot memory leak

---

pimd/pim6_mld.c

Fixing the issues mentioned in #11241
Closes https://github.com/FRRouting/frr/issues/11241

pim6d: Fix display issue in "show ipv6 mld interface" command

---

bgpd/bgp_updgrp_adv.c

After we call subgroup_announce_check(), we leave communities, large-communities that are modified by route-maps uninterned, and here we have a memory leak.
```
./bgp_large_community.test_bgp_large_community_topo_2/r1.bgpd.asan.2465323:Direct leak of 80 byte(s) in 2 object(s) allocated from:
./bgp_large_community.test_bgp_large_community_topo_2/r1.bgpd.asan.2465323-    #0 0x7f0858d90037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./bgp_large_community.test_bgp_large_community_topo_2/r1.bgpd.asan.2465323-    #1 0x7f08589b15b2 in qcalloc lib/memory.c:105
./bgp_large_community.test_bgp_large_community_topo_2/r1.bgpd.asan.2465323-    #2 0x561f5c4e08d2 in lcommunity_new bgpd/bgp_lcommunity.c:28
./bgp_large_community.test_bgp_large_community_topo_2/r1.bgpd …
```

bgpd: Intern attributes before putting into rib-out

---

tests/topotests/lib/ospf.py

tests/topotests/lib/ospf.py:2819: SyntaxWarning: "is not" with a literal. Did you mean "!="?
_age is not "get"
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

tests: Use inequality operator for strings

---

isisd/isis_lsp.c
isisd/isis_main.c
isisd/isisd.c
isisd/isisd.h

Before:
isisd generates its initial lsp before fully processing the written config. 
Ex: lsp_generate() is called in isis_instance_area_address_create(), before other configs that may affect the lsp are loaded in, like set-overload-bit.
After:
isisd generates its initial lsp as soon as the config is fully processed. This was done by utilizing the initialization config callbacks, modeled after bgp's use of start_config/end_config callbacks.

isisd: Delay lsp generation to after config processing is complete

---

pimd/pim_mroute.c

pimd, pim6d: Don't start KAT timer when traffic received on PIM disabled interface
Topology:
RP---FHR---Source
1. In FHR, Enable PIM and IGMP on source connected interface
2. Start multicast traffic. (s,g) mroute and upstream will be created as expected.
3. Disable PIM on source connected interface.
4. Disable IGMP on source connected interface.
5. Stop the traffic.
Mroute will never get timeout.
Root Cause:
In FHR, when PIMD receive multicast data packet on source connected interface which is IGMP enabled, but PIM not enabled. PIMD process the packet, install the
mroute and start the KAT timer.
Fix:
Don't process multicast data packet received on PIM disabled

pimd, pim6d: Don't start KAT timer when traffic received on PIM disabled interface

---

zebra/rt_netlink.c

Added Debugs For RFC 5549 Neighbor Creation
This commit is to add debug log as discussed in below link
https://github.com/FRRouting/frr/issues/5884
Added debug log in netlink_neigh_update(), log contains
ifindex, ifname, ip address and mac address
Output from zebra logs running in netns of frr after adding the fix
```
netlink_neigh_update:
RTM_DELNEIGH
ifname veth0 ifindex 5 addr ipv4 169.254.0.1 mac b2:99:a1:ac:d3:e5
netlink_neigh_update:
RTM_NEWNEIGH
ifname veth0 ifindex 5 addr ipv4 169.254.0.1 mac b2:99:a1:ac:d3:e5
```
Signed-off-by: Kavitha <kavirhene@gmail.com>

Fix for "Debugs For RFC 5549 Neighbor Creation #5884"

---

pimd/pim_cmd_common.c
pimd/pim_hello.c
pimd/pim_neighbor.c
pimd/pim_neighbor.h
pimd/pim_nht.c
pimd/pim_pim.c
pimd/pim_rpf.c
pimd/pim_upstream.c
pimd/pim_zebra.c
zebra/zapi_msg.c

1. Zebra should send ifindex  for nexthop type NEXTHOP_TYPE_IPV6.
2. pim6d should handle nexthop type NEXTHOP_TYPE_IPV6.
3. Fix RPF check,
For a  IPV4/IPV6 route, nexthop can be primary or secondary address.
Whereas PIM hello packet source IP is always primary address.
When there is a difference in the RPF address and PIM neighbour
address for the same interface. RPF check fails.
Fix: 
Check RPF address is either neighbour primary address  or one of the secondary address list.
Closes #11957
Closes #11526
Closes #12103

pimd, pim6d: Fix RPF check

---

pimd/pim_iface.c

If the pimreg device exists but it has not been set to the pim->pimreg pointer we can have a crash.  Just prevent the crash since it's some sort of startup / re-org the network issue.
(gdb) bt
0  0x00007f0485b035cb in raise () from /lib/x86_64-linux-gnu/libpthread.so.0 1  0x00007f0485c0fbec in core_handler (signo=6, siginfo=0x7ffdc0198030, context=<optimized out>) at lib/sigevent.c:264 2  <signal handler called>
3  0x00007f04859668eb in raise () from /lib/x86_64-linux-gnu/libc.so.6 4  0x00007f0485951535 in abort () from /lib/x86_64-linux-gnu/libc.so.6 5  0x00007f0485c3af76 in _zlog_assert_failed (xref=xref@entry=0x55692269b940 <_xref.23164>, extra=extra@entry=0x0) at lib/zlog.c:680 6  0x00005569226150d0 in pim_if_new (ifp=0x556922c82900, gm=gm@entry=false, pim=pim@entry=false, …

pimd: Prevent crash when pimreg already exists.

---

pimd/pim_rp.c

Topology:
FHR----Source
Problem:
When FHR receives multicast traffic, there is no RP configured, PIMD does NHT register for RP address 0.0.0.0 and group 224.0.0.0/4 PIM6D does NHT register for RP address 0::0 and group FF00::0/8
frr# show ip pim nexthop
Number of registered addresses: 1
Address         Interface        Nexthop
frr# show ipv6 pim nexthop
Number of registered addresses: 1
Address         Interface        Nexthop
Fix:
Don't track nexthop for RP 0.0.0.0 & 0::0.
frr# show ip pim nexthop
Number of registered addresses: 0
frr# show ipv6 pim nexthop
Number of registered addresses: 0
Closes #12104

pimd, pim6d: Don't track nexthop for RP 0.0.0.0 & 0::0

---

doc/user/isisd.rst
isisd/isis_circuit.c
isisd/isis_cli.c
isisd/isis_nb.c
isisd/isis_nb.h
isisd/isis_nb_config.c
isisd/isisd.c
isisd/isisd.h
tests/topotests/isis_advertise_high_metrics/r1/isisd.conf
tests/topotests/isis_advertise_high_metrics/r1/zebra.conf
tests/topotests/isis_advertise_high_metrics/r2/isisd.conf
tests/topotests/isis_advertise_high_metrics/r2/zebra.conf
tests/topotests/isis_advertise_high_metrics/r3/isisd.conf
tests/topotests/isis_advertise_high_metrics/r3/zebra.conf
tests/topotests/isis_advertise_high_metrics/r4/isisd.conf
tests/topotests/isis_advertise_high_metrics/r4/zebra.conf
tests/topotests/isis_advertise_high_metrics/test_isis_advertise_high_metrics.py
yang/frr-isisd.yang

Adding support for advertise-high-metrics.
YANG changes: Added leaf under ISIS area for advertise high metrics.
isisd CLI: Added output to "show isis summary" to indicate whether advertise high metrics is Enabled.
New CLI behavior:
```
r1# conf
r1(config)# router isis 1
r1(config-router)#
advertise-high-metrics  Advertise high metric value on all interfaces
area-password           Configure the authentication password for an area
...
r1(config-router)# advertise-high-metrics
r1(config-router)# end
r1# show isis summary
...
Area 1:
Net: 10.0000.0000.0000.0000.0000.0000.0000.0000.0000.00
TX counters per PDU type:
L2 IIH: 1
P2P IIH: 36
LSP RXMT: 0
RX counters per PDU type:
Advertise high metrics: Enabled
Level-2:
...
r1# conf
r1(config)# router isis 1
r1(config-router)# no …
```

isisd: Add support for advertise-high-metrics

---

ospf6d/ospf6_abr.c

RFC 5340, Section 4.8.3 says:
"Prefixes having the NU-bit set in their PrefixOptions field should
be ignored by the inter-area route calculation".
Fix a bug where, in addition to the NU-bit, ospf6d was also ignoring prefixes having the LA-bit set when computing inter-area routes. In practice, this fixes interoperability issues with vendors that set the LA-bit in loopback prefixes (among other cases).
While here, fix a copy-and-paste error where a log message wasn't showing accurate information about what happened.

ospf6d: fix processing of inter-area-prefix-LSAs with the LA-bit set

---

babeld/message.c

Replacing continue in loops to goto done so that index of packet buffer increases.
Closes https://github.com/FRRouting/frr/issues/11808

babeld: fix #11808 to avoid infinite loops

---

bgpd/bgp_label.c

Fixes a couple crashes associated with attempting to read beyond the end of the stream.
Reported-by: Iggy Frankovic <iggyfran@amazon.com>

bgpd: Fix use beyond end of stream of labeled unicast parsing

---

bgpd/bgp_attr.c
bgpd/bgp_evpn.c
bgpd/rfapi/vnc_import_bgp.c

some misc cleaning related withBGP attr structure

bgp attribute cleaning misc

---

zebra/zebra_mpls.c

The "show zebra mpls .. json" vty command may return empty information in case the MPLS database is empty or a given label entry is not available. When those errors occur, add the braces to return a valid json format.

zebra: add json support when "show zebra mpls" returns nothing

---

bgpd/bgp_updgrp.c

There are some missing values in the debug lines.  Let's add them in and help us understand.

bgpd: Add missing items to debug for update group hash key creation

---

bgpd/bgp_updgrp_adv.c

When an update group decides to not send a prefix
announcement because it has not changed, still increment the version number.  Why?  To allow for the situation where you have say 2 peers in 1 peer group and shortly after they come up a 3rd peer comes up.  It will be placed into a separate update group and could be
coalesced down, when it finishes updating all data to it.  Now imagine that a single prefix changes at this point in time as well.  Then first 2 peers may decide to not send the data, since nothing has changed. While the 3rd peer will and since the versions numbers never match they will never coalesce.  So when the decision is made to skip, update the version number as well.

bgpd: Increment version number even when no data is sent

---

pimd/pim_util.c

New correct behavior:
eva# conf
eva(config)# ip pim rp 192.168.1.224 224.0.0.0/24
No Path to RP address specified: 192.168.1.224
eva(config)# ip pim rp 224.1.2.3 224.0.0.0/24
% Bad RP address specified: 224.1.2.3
eva(config)#
Fixes: #12970

pimd: IN_MULTICAST needs host order

---

bgpd/bgp_fsm.c
bgpd/bgp_route.c
bgpd/bgp_zebra.c
bgpd/bgp_zebra.h
lib/log.c
lib/log.h
zebra/zebra_gr.c

The GR debug logs are doing all sorts of wonderful stuff but they were not actually displaying anything useful to the operator about what vrf we are operating in.

zebra: Make GR debug logs at least vrf aware

---

isisd/isis_pfpacket.c

This patch introduces a new BFP filter in `isis_pfpacket.c`, which in addition to IS-IS over LLC also permits IS-IS over Ethertype `0x00fe`. This makes IS-IS work over tunnels such as GRE.
Tested IS-IS over Ethernet, IS-IS over GRE and IS-IS over GENEVE (GENEVE requires upstreaming a kernel patch).
Resolves https://github.com/FRRouting/frr/issues/2330 (may need setting `isis network point-to-point`).

isisd: IS-IS over tunnel (GRE, GENEVE)

---

tools/frr-reload.py

Check for value present in list before removing
as in certain python3 ValueError traceback is observed.
```
Traceback (most recent call last):
File "/usr/lib/frr/frr-reload.py",
line 2278, in <module>
(lines_to_add, lines_to_del, restart_frr)
= compare_context_objects(newconf, running)
File "/usr/lib/frr/frr-reload.py",
line 1933, in compare_context_objects
lines_to_add, lines_to_del
File "/usr/lib/frr/frr-reload.py",
line 1549, in ignore_delete_re_add_lines
lines_to_del.remove((ctx_keys, line))
ValueError: list.remove(x): x not in list
```
Testing Done:
With fix perform frr-relaod on frr.conf config where earlier traceback was seen.

tools: frr-reload fix list value not present

---

lib/clippy.c

The old initialization/config API is deprecated in Python 3.11.  Make clippy use the new one added in 3.8 if it's that version or newer.
---
(fixes deprecation warnings when building with python 3.11 or newer)
with my luck this is probably gonna fail to build on odd python versions on the CI platforms…

lib: adapt clippy to Python 3.8+ init API

---

bgpd/bgp_fsm.c

gcc 12.2.0 complains `error: ‘%s’ directive argument is null`, even though all enum values are covered with a string.  Let's just go with a `???` default.
---
Honestly the warning is bogus, but broken build is broken build.
```
bgpd/bgp_fsm.c: In function ‘bgp_gr_update_all’:
./lib/zlog.h:109:34: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
109 |                 zlog_ref(&_xref, (msg), ##__VA_ARGS__);                        \
|                                  ^~~~~
./lib/zlog.h:116:26: note: in expansion of macro ‘_zlog_ecref’
116 | #define zlog_debug(...)  _zlog_ecref(0, LOG_DEBUG, __VA_ARGS__)
|                          ^~~~~~~~~~~
bgpd/bgp_fsm.c:2730:17: note: in expansion of macro ‘zlog_debug’
2730 |                 zlog_debug("[BGP_GR] global_old_gr_state :%s:", …
```

bgpd: fix NULL argument warning

---

bgpd/bgp_network.c

Log message is borked in a manner that makes it unusable: bgpd[52]: [VX6SM-8YE5W][EC 33554460] 2000:31:0:53::2: nexthop_set failed, resetting connection - intf 0x561eb9005a30
Let's print out the interface name instead.

bgpd: Use interface name instead of pointer value

---

bgpd/bgp_fsm.c

Imagine this scenario:
A peer has very large hold/keepalive timers of 600/200.  This peer is using the DataCenter default time.  As such the open will cause the t_holdtime to be negotiated to 600 seconds.  Now also imagine that both peers are in update-delay.  If we do not restart the timers and both peers are in Update Delay, we will continously reset the peer because the hold time will be hit( since the peer is not sending us any data ).

bgpd: Always restart timer from scratch in OpenConfirm/Established

---

lib/filter_cli.c
lib/filter_nb.c

Reading in prefix-lists is reading in the specified prefix list and validating that the prefix is unique 2 times.  This makes no sense.  Relax the requirement that a prefix list can limit this as well as completely remove this check.  Validation then just becomes
does this prefix-list specified actually make sense and that is taken care of by the the cli code.
Reading in prefix-lists was looking for duplicate prefixes 2 times instead of doing it just one time.  Let's just not do it at all.
By doing this change, The code changes from never
completing for a 27k long prefix-list to taking
just under 30 seconds, with 4 daemons processing
this data.

lib: Speedup prefix-list readin by a large factor

---

bgpd/bgp_evpn_mh.c

Crash:
(gdb) bt
0  0x00007fee27de15cb in raise () from /lib/x86_64-linux-gnu/libpthread.so.0 1  0x00007fee280ecd9c in core_handler (signo=11, siginfo=0x7ffe56001bb0, context=<optimized out>) at lib/sigevent.c:264 2  <signal handler called>
3  0x0000555e321c41b2 in prefix_rd2str (prd=0x10, buf=buf@entry=0x7ffe56002080 "27.0.0.R\340\373\062\062^U", size=size@entry=28) at bgpd/bgp_rd.c:168 4  0x0000555e321c431a in printfrr_prd (buf=0x7ffe560021a0, ea=<optimized out>, ptr=<optimized out>) at bgpd/bgp_rd.c:224 5  0x00007fee2812069b in vbprintfrr (cb_in=cb_in@entry=0x7ffe56002330, fmt0=fmt0@entry=0x555e3229a3ad " RD: %pRD\n", ap=ap@entry=0x7ffe560023d8) at lib/printf/vfprintf.c:564 6  0x00007fee28122ef7 in vasnprintfrr (mt=mt@entry=0x7fee281cb5e0 <MTYPE_VTY_OUT_BUF>, …

bgpd: Prevent Null pointer deref when outputting data

---

pimd/pim6_mld.c

When hitting gm_sg_update from the S,G expiry timer, t_sg_expire will already be cancelled.  But when arriving there from e.g. the MLD packet getting cleared out, it'll still be running.
Clear out the timer if we arrive with `has_expired == true`.
Fixes: #12441
---
cf. discussion in #13013

pimd: stop t_sg_expire in MLD NOINFO transition

---

ospfd/ospf_apiserver.c
ospfd/ospf_opaque.c

Clean up some memory leaks found in ospf_apiserver.c  Also a crash in the original implementation.

ospfd: Cleanup some memory leaks on shutdown in ospf_apiserver.c

---

pbrd/pbr_vty.c

upstream commit 67765a232d has incorect address family check which prevent from deleting src/dst config under pbr rule.
Testing Done:
**Config:**
```
pbr-map map6 seq 1
match src-ip 2000::200:100:100:0/96
match dst-ip 2000::100:100:100:0/96
set nexthop-group group3
```
**Before:**
```
torc-12(config)# pbr-map map6 seq 1
torc-12(config-pbr-map)# no match src-ip 2000::200:100:100:0/96 Cannot mismatch families within match src/dst
```
**After:**
```
torc-12(config)# pbr-map map6 seq 1
torc-12(config-pbr-map)# no match src-ip 2000::200:100:100:0/96
torc-12(config-pbr-map)#
```

pbrd:fix mismatching in match src-dst

---

nhrpd/nhrp_cache.c

When dropping an interface (e.g. at shutdown) while there are still valid cache entries, the reference held on the cache entries' peer pointers was leaking.
Fixes: #12505

nhrpd: drop peer references on freeing cache entry

---

lib/routemap.c

1. clear route-map command parsing had incorrect index to parse route-map name which corrected using DEFPY
tor-21# clear route-map counters SET_SRC_LO
tor-21#
**Before:**
```
TORC11# clear route-map counters
<cr>
WORD  route-map name
```
**After:**
```
TORC11# clear route-map counters
<cr>
RMAP_NAME  route-map name
my-as
```
tor-21# show route-map
ZEBRA:
route-map: ALLOW_LO Invoked: 0 Optimization: disabled Processed Change:
false
permit, sequence 10 **Invoked 0**
Match clauses:
interface lo
Set clauses:
Call clause:
Action:
Exit routemap

lib: fix clear route-map command

---

lib/bfd.c

When deleting a bfd peer during shutdown, let's ensure that any scheduled events are actually stopped.
==7759== Invalid read of size 4
==7759==    at 0x48BF700: _bfd_sess_valid (bfd.c:419)
==7759==    by 0x48BF700: _bfd_sess_send (bfd.c:470)
==7759==    by 0x492F79C: thread_call (thread.c:2008)
==7759==    by 0x48E9BD7: frr_run (libfrr.c:1223)
==7759==    by 0x1C739B: main (bgp_main.c:550)
==7759==  Address 0xfb687a4 is 4 bytes inside a block of size 272 free'd
==7759==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==7759==    by 0x48BFA5A: bfd_sess_free (bfd.c:535)
==7759==    by 0x2B7034: bgp_peer_remove_bfd (bgp_bfd.c:339)
==7759==    by 0x29FF8A: peer_free (bgpd.c:1160)
==7759==    by 0x29FF8A: peer_unlock_with_caller (bgpd.c:1192) …

lib: on bfd peer shutdown actually stop event

---

zebra/zebra_netns_notify.c

Issue:
When a netns is deleted, since zebra doesn’t receive interface down/delete notifications from kernel, it manually deletes the interface without removing the association between zebra_l3vni and the interface that is being deleted (i.e it deletes the interface without setting “zl3vni->vxlan_if” to NULL).
Later, during the deletion of netns, when zl3vni_rmac_uninstall() is called to uninstall the remote RMAC from the kernel, zebra ends up accessing stale “zl3vni->vxlan_if” pointer, which now points to freed memory. This was causing heap use-after-free.
Fix:
Before zebra starts deleting the interfaces when it receives netns delete notification, appropriate functions() are being called to remove the association between evpn structs and interface and set “zl3vni->vxlan_if” to NULL. This …

zebra: Fix for heap-use-after-free in EVPN

---

tests/topotests/static_routing_with_ebgp/test_static_routes_topo1_ebgp.py
tests/topotests/static_routing_with_ebgp/test_static_routes_topo2_ebgp.py
tests/topotests/static_routing_with_ebgp/test_static_routes_topo3_ebgp.py
tests/topotests/static_routing_with_ebgp/test_static_routes_topo4_ebgp.py
tests/topotests/static_routing_with_ibgp/test_static_routes_topo1_ibgp.py
tests/topotests/static_routing_with_ibgp/test_static_routes_topo2_ibgp.py
tests/topotests/static_routing_with_ibgp/test_static_routes_topo3_ibgp.py
tests/topotests/static_routing_with_ibgp/test_static_routes_topo4_ibgp.py

1. No Functionality Changes.
2. Updated the error messages.

tests: Enhance error msgs for static route automation.

---

zebra/zebra_vxlan.c

Added "isDetectionFreeze" into show evpn json output to identify **freeze** **permanent**. 
Before fix:-
```
tor-2(config)# router bgp 65561
tor-2(config-router)# address-family l2vpn evpn
<cr>
tor-2(config-router)# address-family l2vpn evpn
tor-2(config-router-af)# dup-addr-detection freeze permanent
tor-2(config-router-af)# do show evpn
L2 VNIs: 21
L3 VNIs: 5
Advertise gateway mac-ip: No
Advertise svi mac-ip: No
Advertise svi mac: No
Duplicate address detection: Enable
Detection max-moves 5, time 180
Detection freeze permanent
EVPN MH:
mac-holdtime: 1080s, neigh-holdtime: 1080s
startup-delay: 180s, start-delay-timer: --:--:--
uplink-cfg-cnt: 0, uplink-active-cnt: 0
tor-2(config-router-af)#
tor-2(config-router-af)# do show evpn json
{
"advertiseGatewayMacip":"No", …
```

zebra: add evpn isDetectionFreeze to json output

---

bgpd/bgp_routemap.c
doc/user/routemap.rst
yang/frr-bgp-route-map.yang

It's not allowed to install routes with zero distance, let's disallow this for route-maps as well.

bgpd: Do not allow setting `set distance` via route-maps to zero

---

mgmtd/mgmt_history.c

Close fd before returning to avoid leaks.

mgmtd: Fix fd leak.

---

pimd/pim_zebra.c

We have this valgrind trace:
==1125== Invalid read of size 4
==1125==    at 0x170A7D: pim_if_delete (pim_iface.c:203)
==1125==    by 0x170C01: pim_if_terminate (pim_iface.c:80)
==1125==    by 0x174F34: pim_instance_terminate (pim_instance.c:68)
==1125==    by 0x17535B: pim_vrf_terminate (pim_instance.c:260)
==1125==    by 0x1941CF: pim_terminate (pimd.c:161)
==1125==    by 0x1B476D: pim_sigint (pim_signals.c:44)
==1125==    by 0x4910C22: frr_sigevent_process (sigevent.c:133)
==1125==    by 0x49220A4: thread_fetch (thread.c:1777)
==1125==    by 0x48DC8E2: frr_run (libfrr.c:1222)
==1125==    by 0x15E12A: main (pim_main.c:176)
==1125==  Address 0x6274d28 is 1,192 bytes inside a block of size 1,752 free'd
==1125==    at 0x48369AB: free (in …

pimd: Fix use after free issue for ifp's moving vrfs

---

bgpd/bgp_open.c

It's not 4 bytes, it was assuming the same as Graceful-Restart tuples.
LLGR has more 3 bytes (Long-lived Stale Time).

bgpd: Check 7 bytes for Long-lived Graceful-Restart capability

---

ospfd/ospf_lsa.c

Problem:
Multiple memory leaks after pr12366
RCA:
ospf_lsa_unlock was not happening for the few of the LSAs in ospf_lsa_refresh_walker after pr12366 due to which
memory related to lsas was leaking.
Fix:
Moved the ospf_lsa_unlock outside if check.

ospfd: Fix for memory leak issue in ospf related to flood_reduction tests.

---

lib/defun_lex.l

Having a runaway string ala `DEFPY(… "something )` (note the missing closing ") was causing clippy to SEGV. Make this an actual (maybe even helpful) error report rather than a crash.

lib: improve clippy behavior with invalid input

---

configure.ac
tools/frr.in
tools/frrcommon.sh.in
tools/frrinit.sh.in

Before it was setting SDIR, which is /usr/lib/frr, but the vtysh binary is put under bindir (which is /usr/local by default). And running `/usr/lib/frr/frr reload` failed.

tools: Set correct directory of vtysh for frr-reload.py

---

pimd/pim6_cmd.c

While configuring global or non-multicast address
for ipv6 mld join command, displaying a custom error-message
"Invalid Multicast Address"
Closes #12822

pim6d: custom error-message for non-multicast groups

---

bgpd/bgp_route.c
bgpd/bgp_zebra.c
tests/topotests/bgp_suppress_fib/test_bgp_suppress_fib.py

The flag for telling BGP that a route is expected to be installed first before notifying a peer was always being set upon receipt of a path that could be accepted as bestpath.  This is not correct: imagine that you have a peer sending you a route and you have a network statement that covers the same route.  Irrelevant if the network statement would win the flag on the dest was being set in bgp_update.  Thus you could get into a situation where the network statement path wins but since the flag is set on the node, it will never be announced to a peer.
Let's just move the setting of the flag into bgp_zebra_announce and _withdraw.  In _announce set the flag to TRUE when suppress-fib is enabled.  In _withdraw just always unset the flag as that a withdrawal does not need to wait for rib …

bgpd: Ensure suppress-fib-pending works with network statements

---

lib/mgmt_be_client.c
lib/mgmt_fe_client.c
mgmtd/mgmt_be_adapter.c
mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_txn.c

See individual commits.  Remove unnecessary asserts *and* this is exactly why I hate cut-n-paste code.  I have to do this in 4+ spots since someone cargo-culted an assert instead of proper abstraction

Assert unneeded

---

bgpd/bgp_route.c

Log is printing this with this config:
2023-03-28 07:36:47.007 [DEBG] bgpd: [Q9J6Z-09HRR] 192.168.119.120 [Update:SEND] 1.2.3.33/32 is filtered by route-map '(null)'
Here's the config:
network 1.2.3.33/32
network 1.2.3.34/32
aggregate-address 1.2.3.0/24 summary-only
redistribute table 33 route-map foo
neighbor 192.168.119.120 route-map DENY in
neighbor 192.168.119.120 unsuppress-map UNSUPPRESS
ip prefix-list UNSUPPRESS seq 5 permit 1.2.3.4/32
ip prefix-list UNSUPPRESS seq 10 permit 1.2.3.5/32 ip prefix-list UNSUPPRESS seq 15 permit 1.2.3.6/32

bgpd: Fix debug output for route-map names when using a unsuppress-map

---

ospfd/ospf_interface.c

OSPF crash:
```
#0  0x00007f74dfd195cb in raise () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f74dffa7a9c in core_handler (signo=11, siginfo=0x7ffd70494b30, context=<optimized out>) at lib/sigevent.c:264
#2  <signal handler called>
#3  0x00005623aba3a2fb in ospf_vl_shutdown (vl_data=<optimized out>) at ospfd/ospf_interface.c:1054
#4  0x00005623aba3bf5b in ospf_vl_delete (ospf=ospf@entry=0x5623ac8fe6c0, vl_data=0x5623ac910e00) at ospfd/ospf_interface.c:1070
#5  0x00005623aba8cc1b in ospf_remove_vls_through_area (area=0x5623ac912250, ospf=0x5623ac8fe6c0) at ospfd/ospfd.c:1487
#6  ospf_finish_final (ospf=0x5623ac8fe6c0) at ospfd/ospfd.c:754
#7  ospf_deferred_shutdown_finish (ospf=0x5623ac8fe6c0) at ospfd/ospfd.c:597
#8  0x00005623aba8d5d0 in ospf_finish (ospf=<optimized out>) at …
```

ospfd: Fix for vitual-link crash in signal handler

---

bgpd/bgpd.c

Just realized it was a stupid copy/paste.

bgpd: Do not call bgp_soft_reconfig_in() twice in a row on policy change

---

isisd/isis_pdu.c
isisd/isisd.c
isisd/isisd.h

Adding a new drop counters section to "show isis summary".
In isis_handle_pdu(), I increment the drop counter for each PDU that isn't successfully processed. 
New output:
```
Drop counters per PDU type:
P2P IIH: X
L2 LSP: X
L2 CSNP: X
L2 PSNP: X
...
```
Before:
```
r1# show isis summary
vrf             : default
Process Id      : 972
System Id       : 0000.0000.0001
Up time         : 00:00:48 ago
Number of areas : 1
Area TE:
Net: 49.0000.0000.0000.0001.00
TX counters per PDU type:
P2P IIH: 36
L2 LSP: 8
L2 CSNP: 12
L2 PSNP: 11
RX counters per PDU type:
P2P IIH: 37
L2 LSP: 17
L2 CSNP: 12
L2 PSNP: 6
Advertise high metrics: Disabled
...
```
After:
```
r1# show isis summary
vrf             : default
Process Id      : 972
System Id       : 0000.0000.0001
Up time         : 00:00:19 ago
Number of …
```

isisd: Add PDU drop counter to "show isis summary"

---

doc/manpages/vtysh.rst
vtysh/vtysh.c
vtysh/vtysh.h
vtysh/vtysh_config.c
vtysh/vtysh_main.c

This is PR https://github.com/FRRouting/frr/pull/9621 . except it's been updated to fix the topotests as well as the merge conflicts.  I just did not want to figure out how to force push to a branch I don't own.
I don't really see any unresolved discussions, and this has been running internally for well over a year now as well as this brings down config file read in significantly.  Can we get this in?

Vtysh fork

---

tests/topotests/all_protocol_startup/r1/ospf6d.conf-pre-v4
tests/topotests/bfd_topo3/r5/bfdd.conf
tests/topotests/bfd_topo3/r6/bfdd.conf
tests/topotests/bgp_accept_own/ce1/bgpd.conf
tests/topotests/bgp_accept_own/ce2/bgpd.conf
tests/topotests/bgp_accept_own/pe1/bgpd.conf
tests/topotests/bgp_accept_own/rr1/bgpd.conf
tests/topotests/bgp_comm_list_match/r2/bgpd.conf
tests/topotests/bgp_confed1/r1/bgpd.conf
tests/topotests/bgp_confed1/r2/bgpd.conf
tests/topotests/bgp_confed1/r3/bgpd.conf
tests/topotests/bgp_confed1/r4/bgpd.conf
tests/topotests/bgp_dont_capability_negotiate/r1/bgpd.conf
tests/topotests/bgp_evpn_vxlan_svd_topo1/test_bgp_evpn_vxlan_svd.py
tests/topotests/bgp_evpn_vxlan_topo1/test_bgp_evpn_vxlan.py
tests/topotests/bgp_prefix_list_any/r2/bgpd.conf
tests/topotests/bgp_route_map_delay_timer/r1/bgpd.conf
tests/topotests/bgp_route_map_vpn_import/r1/bgpd.conf
tests/topotests/bgp_snmp_bgp4v2mib/r2/bgpd.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/r1/zebra.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/r2/zebra.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/r1/zebra.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/r2/bgpd.conf
tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/r2/zebra.conf
tests/topotests/bgp_suppress_fib/r2/bgpd.allowas_in.conf
tests/topotests/bgp_suppress_fib/r2/bgpd.conf
tests/topotests/bgp_vrf_md5_peering/r1/bgpd.conf
tests/topotests/isis_snmp/r5/ldpdconf
tests/topotests/ospf6_ecmp_inter_area/r1/ospf6d.conf
tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py

Tests are taking up too much space, turn off debug logging for normal runs.

tests: Turn off debug logging

---

bgpd/bgp_route.c
bgpd/bgp_zebra.c
doc/user/basic.rst
lib/prefix.c
lib/prefix.h

There are some specific edge-cases when is a need to run FRR and another FRR and/or another BGP implementation on the same box. Relaxing 127.0.0.0/8 for this case might be reasonable.
An example below peering via 127.0.0.0/8 between FRR and GoBGP:
```
% ss -ntlp | grep 179
LISTEN   0         4096              127.0.0.1:179              0.0.0.0:*
LISTEN   0         128               127.0.0.2:179              0.0.0.0:*
% grep 127.0.0.2 /etc/frr/daemons
bgpd_options="   -A 127.0.0.1 -l 127.0.0.2"
% grep local /etc/gobgp/config.toml
local-address-list = ["127.0.0.1"]
donatas-pc# sh ip bgp summary
IPv4 Unicast Summary (VRF default):
BGP router identifier 192.168.10.17, local AS number 65001 vrf-id 0
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 1, using 725 KiB of memory …
```

bgpd: Allow peering via 127.0.0.0/8

---

zebra/main.c

-What I did
Some threads will still get vrf,  when a new entry would created with insufficient data, and so it may crash.
-How I did it
Move vrf delete handle to zebra_finalize()
-How to verify it
Create vrf interfaces and reboot

zebra: move vrf deleting handle to zebra final state handle

---

bgpd/bgp_dump.c

This PR fixes [issue 13151](https://github.com/FRRouting/frr/issues/13151) where BGP messages larger than 8192 could be truncated in the dumped MRT files.
The fix is to use a larger buffer sized with BGP_MAX_PACKET_SIZE (65535) plus some overhead BGP_MAX_PACKET_SIZE_OVERFLOW (1024).

bgpd: increase buffer size used for dumping BGP to MRT files

---

bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgpd.c

Memory leaks are observed in the cleanup code. When “no router bgp" is executed, cleanup in that flow for aggregate-address command is not taken care.
fixes the below leak:
--
./bgp_local_asn_dot.test_bgp_local_asn_dot_agg/r3.bgpd.asan.3410444:Direct leak of 152 byte(s) in 1 object(s) allocated from:
./bgp_local_asn_dot.test_bgp_local_asn_dot_agg/r3.bgpd.asan.3410444-    #0 0x7f163e911037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./bgp_local_asn_dot.test_bgp_local_asn_dot_agg/r3.bgpd.asan.3410444-    #1 0x7f163e4b9259 in qcalloc lib/memory.c:105
./bgp_local_asn_dot.test_bgp_local_asn_dot_agg/r3.bgpd.asan.3410444-    #2 0x562bf42ebbd5 in bgp_aggregate_new bgpd/bgp_route.c:7239
./bgp_local_asn_dot.test_bgp_local_asn_dot_agg/r3.bgpd.asan.3410444- …

bgpd : memory leak fix for aggregate-address on cleanup

---

isisd/isis_te.c
sharpd/sharp_zebra.c

Subnets may be incorrectly created in the IS-IS Traffic Engineering Database (TED).
Indeed, to be usable, the subnets advertised by IS-IS peers must be  adjusted to avoid misinterpretation. For example, consider R1 which is connected to R2 with IP addresses 10.0.0.1/24 (R1) and 10.0.0.2/24 (R2). R1 and R2 will advertise the prefix 10.0.0.0/24. By leaving the subnet with the prefix 10.0.0.0/24 in the TED, it is not possible to determine whether 10.0.0.1 is attached to R1 or R2 or whether 10.0.0.3 exists.
So to avoid this, the subnet prefixes are adjusted with the IP addresses of the local interface. But IS-IS can start to advertise the subnet when not all adjacencies are up, especially when IPv4 and IPv6 are configured on the same interface. This results in an uncorrected prefix, e.g. …

isisd: Correction of subnets creation in the TED

---

pimd/pim_iface.c

After restarting pim6d, in some cases the ifindex is 0 for the interfaces,
so the vif index is also assigned as 0. This causes the interface name to be pim6reg.
Fix:
If the ifindex is 0 and the interface name is not "pimreg" or "pim6reg",
the function will return without assigning vifindex with an error message.
Issue: #12744

pim6d: Do not use interfaces with ifindex as 0

---

bgpd/bgp_vty.c

We use neighbor descriptions with len > 20 and usually no whitespaces.
But since 64541ffa8f33404e32336d1905b73f89a7d26610, `sh ip bgp summary` shows nothing because `last_space` == 0.
It'd be helpful trimming configured neighbor description instead of showing blank if its len > 20 and contains no whitespaces. Same stands if description len goes above 64 using wide mode.
Thanks for the help

bgpd: trim long neighbor description with no whitespace

---

bgpd/bgp_attr.c

BGP_PREFIX_SID_SRV6_L3_SERVICE attributes must not fully trust the length value specified in the nlri. Always ensure that the amount of data we need to read can be fullfilled.
Reported-by: Iggy Frankovic <iggyfran@amazon.com>
Closes https://github.com/FRRouting/frr/issues/13099

bgpd: Ensure stream received has enough data

---

zebra/main.c
zebra/rib.h
zebra/zebra_rib.c

two things:
On shutdown cleanup any events associated with the update walker. Also do not allow new events to be created.
Fixes this mem-leak:
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790:Direct leak of 8 byte(s) in 1 object(s) allocated from:
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790-    #0 0x7f0dd0b08037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790-    #1 0x7f0dd06c19f9 in qcalloc lib/memory.c:105
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790-    #2 0x55b42fb605bc in rib_update_ctx_init zebra/zebra_rib.c:4383
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790-    #3 0x55b42fb6088f in rib_update zebra/zebra_rib.c:4421
./msdp_topo1.test_msdp_topo1/r2.zebra.asan.1117790-    #4 …

zebra: Cleanup ctx leak on shutdown and turn off event

---

isisd/isis_snmp.c
zebra/dpdk/zebra_dplane_dpdk.c

Use the FRR provided array_size.

isisd, zebra: Use array_size instead of ARRAY_SIZE

---

bgpd/bgp_route.c

The json structure changes used for 'json detail' show commands are not very straightforward and might require code analysis to understand. This addscommentary to the flow to explain the change in structure.

bgpd: add comments for 'json detail' show cmd code

---

bgpd/bgp_ecommunity.c
tests/topotests/bgp_route_origin_parser/pe1/bgpd.conf
tests/topotests/bgp_route_origin_parser/test_bgp_route_origin_parser.py

The parser for extended communities was incorrectly disallowing an operator from configuring "Route Origin" extended communities (e.g. RD/RT/SoO) with a 4-byte value matching BGP_AS4_MAX (UINT32_MAX) and allowed the user to overflow UINT32_MAX:
```
TORC11(config-router-af)# neighbor uplink-1 soo 4294967296:65
TORC11(config-router-af)# do sh run | include soo
neighbor uplink-1 soo 0:65
TORC11(config-router-af)# neighbor uplink-1 soo 4294967295:65
% Malformed SoO extended community
TORC11(config-router-af)#
```
This updates the parser to read the value as a uint64_t so that we can do proper checks on the upper bounds (> BGP_AS4_MAX):
```
TORC11(config-router-af)# neighbor uplink-1 soo 4294967296:65
% Malformed SoO extended community
TORC11(config-router-af)# neighbor uplink-1 soo …
```

bgpd: fix ecommunity parsing for AS4

---

bgpd/bgp_bmp.c

according to the wireshark dissector the ports in the bmp peer-up messages are in the wrong byte order. 
for example, dissected port 179 of bgp is read as 0xb300 (base10 = 45824) instead of 0x00b3 (base10 = 179)
this PR adds a htons call to the port values put in the bmp message packet for the peer-up message in ordre to fix this byte order problem

bgpd: bmp fix peer-up ports byte order

---

lib/if_rmap.c

Currently the process of the `route-map` configuration for `per-vrf-rip` is wrong.
There are two problems:
1. `ctx->name` for `if_rmap_ctx`  is not initialized in `if_rmap_ctx_create()`.
2.  The global `if_rmap_ctx_list` is wrongly used for `per-vrf-rip`.
So, two changes for it:
1. Correctly initializes `ctx->name`.
2. Use specific `if_rmap_ctx` for `per-vrf-rip`, not global one.
Note, this related implementation for `route-map` is only for `ripd`.
Before:
```
anlan(config)# route rip vrf vrf1
anlan(config-router)# route-map aa in lan
anlan(config-router)# do show run
!
router rip
route-map aa in lan
exit
!
```
After:
```
anlan(config)# route rip vrf vrf1
anlan(config-router)# route-map aa in lan
anlan(config-router)# do show run
!
router rip vrf vrf1
route-map aa in lan
exit
!
```

ripd: Fix malformed route-map

---

ospfd/ospf_vty.c

ospf neighbor DR and BDR router-id wrongly displays with interface ip-address instead of router-id.
It is fixed to display the correct DR & BDR router-id  for JSON and CLI commands.
Commands:
```
show ip ospf vrf <vrf-name> neighbor detail json
show ip ospf vrf <vrf-name> neighbor detail
```
Before Fix:-
```
r1# show ip ospf vrf default neighbor  swp1 detail
Neighbor 0.0.0.17, interface address 11.0.0.1
In the area 0.0.0.0 via interface swp1 local interface IP 11.0.0.2
Neighbor priority is 1, State is Full, Role is DR, 6 state changes
Most recent state change statistics:
Progressive change 1d15h05m ago
DR is 11.0.0.1, BDR is 11.0.0.2 ======> DR and BDR shows the intef &
local intf ipaddress
Options 2 *|-|-|-|-|-|E|-
Dead timer due in 35.178s
Database Summary List 0
Link State Request List …
```

ospfd:display correct DR-BDR router-id in nbr cmd

---

tests/topotests/lib/common_config.py
tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm1.py
tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm2.py
tests/topotests/multicast_pim6_static_rp_topo1/test_multicast_pim6_static_rp1.py
tests/topotests/multicast_pim6_static_rp_topo1/test_multicast_pim6_static_rp2.py

For multicast pimv6 join and traffic, socat is
used, which was not cleaned up post tests executions, 
enhanced kill_socat() API to kill socat join and
traffic specific PIDs during teardown module.

tests: [topojson] multicast pimv6 socat cleanup

---

lib/zclient.c
zebra/rib.h
zebra/zebra_gr.c
zebra/zebra_rib.c
zebra/zserv.c
zebra/zserv.h

See individual commits but the high points:
a) Zebra was storing afi/safi data for GR but only acting on AFI/SAFI_UNICAST.  Remove the redundancy
b) Fix GR code to not accidently stop iterating when a node goes away
c) Fix GR code to process the AFI when it receives the notification that the afi is done
d) Fix GR code to run after anything in Meta-Q since we have a race condition

Improve and fix zebra GR

---

zebra/zebra_gr.c

Add a null check - should fix coverity CID 1537086.

zebra: null-check client pointer during GR processing

---

zebra/zebra_vxlan.c

"show evpn json" returns nothing when evpn is disabled.
Code has been fixed to return {} when evpn is disabled or no entry available.
Fix many of the places empty json when evpn is disabled.
Example:
Before Fix:-
```
cumulus@r2:mgmt:~$ sudo vtysh -c "show evpn json"
cumulus@r2:mgmt:~$
```
After Fix:-
```
cumulus@r1:mgmt:~$ sudo vtysh -c "show evpn json"
{
}
cumulus@r1:mgmt:~$
```
Signed-off-by: Sindhu Parvathi Gopinathan <sgopinathan@nvidia.com>

zebra:return empty dict in json when evpn is disabled

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn.h
bgpd/bgp_flowspec.c
bgpd/bgp_flowspec.h
bgpd/bgp_packet.c
bgpd/bgp_packet.h
tests/bgpd/test_mp_attr.c

See individual Commits, two categories:
a) Code cleanup to our standards
b) Prevent a NLRI_MPUPDATE that has a poorly formed bgp nlri( ie it doesn't exist ) from crashing flowspec.

Limit scope

---

isisd/isis_te.c
lib/link_state.c
lib/link_state.h
ospfd/ospf_te.c
pathd/path_ted.c
sharpd/sharp_vty.c

When passing a prefix into a function let's pass by address instead of pass by value.  Let's save our stack space.

*: Use a `struct prefix *p` instead of a `struct prefix` in functions

---

tests/topotests/all_protocol_startup/test_all_protocol_startup.py
tests/topotests/lib/micronet_compat.py
tests/topotests/lib/topogen.py
tests/topotests/lib/topotest.py
tests/topotests/zebra_rib/test_zebra_rib.py

tests: don't flush ipv6 addresses
tests: create 8 link, switch pairs, not 8 links on one switch
tests: initialize parent test namespace too

minor topotest cleanup

---

bgpd/bgp_evpn.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_vty.c

See individual commits but evpn_type5_test_topo1 is crashing regularly this should solve the issue

Evpn crashes and other ilk

---

bgpd/bgp_evpn_mh.c

`update_type1_routes_for_evi()` is called from L3VNI/L2VNI up event, if ESI is not UP at this point then
do not advertise EAD-ES Type-1 route.
Just like from multiple places EAD-ES route origination checks for its operational status.

bgpd: EVPN-MH ESI is not active suppress EAD-ES Type-1 route

---

lib/if_rmap.c

When cleaning `ripd`, it should free `ctx->name` of `struct if_rmap_ctx`, not `ctx` itself.  Otherwise, it will lead to memory leak.

ripd: Fix memory leak for ripd's route-map

---

doc/user/ospfd.rst
ospfd/ospf_network.c
ospfd/ospf_network.h
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Add configurable socket send and receive buffer sizes, configured at the instance level. The default buffer sizes are ... pretty big, especially for sending.

ospfd: support configuration of socket buffer sizes

---

doc/user/mgmtd.rst

Since mgmtd no longer supports the frr_startup.json, removing the documentation related to that. 
Proper documentation will be added when/if the frr_startup.json is ever supported.

mgmtd: remove the frr_startup.json related documentation.

---

zebra/zebra_dplane.c

During shutdown, the main pthread stops the dplane pthread before exiting. Don't try to clean up any events scheduled to the dplane pthread at that point - just let the thread exit and clean up. There was code that was trying to clean up an event in this path, and that looks to have opened a (narrow) race.
Fixes: #13187

zebra: fix race during shutdown

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/bgpd.h
doc/user/bgp.rst
tests/topotests/bgp_lu_explicitnull/r1/bgpd.conf
tests/topotests/bgp_lu_explicitnull/r1/zebra.conf
tests/topotests/bgp_lu_explicitnull/r2/bgpd.conf
tests/topotests/bgp_lu_explicitnull/r2/zebra.conf
tests/topotests/bgp_lu_explicitnull/test_bgp_lu_explicitnull.py

In BGP labeled unicast address-family, it is not possible to send explicit-null label values with redistributed or network declared prefixes.
A new CLI command is introduced:
> [no] bgp labeled-unicast explicit-null
When used, the explicit-null value for IPv4 ('0' value) or IPv6 ('2' value) will be used.
It is necessary to reconfigure the networks or the redistribution in order to inherit this new behaviour.

bgpd: add cli command to control explicit-null label usage

---

zebra/interface.c
zebra/interface.h

Add link_nsid to zebra interface, so that the <link_nsid, link_ifindex> pair can uniquely identify the link interface. And VLAN interface is not necessary in the same netns of its parent.

zebra: Add link_nsid to zebra interface

---

doc/user/ospfd.rst
ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_network.c
ospfd/ospf_network.h
ospfd/ospf_packet.c
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Modify ospfd to use a write socket per interface, instead of the current socket-per-instance. When multiple interfaces with different characteristics share a single socket (and its buffers), it's possible for slow or poor-performing destinations to block packets destined for other, better-performing destinations. With a socket per interface, fewer neighbors share fate.
This is enabled by default, on a per-instance basis. A new cli is available to revert to the original, socket - per - instance behavior if necessary.
I haven't added a specific test, since ... it's enabled all the time.

ospfd: write socket per interface

---

lib/mgmt_be_client.c
lib/mgmt_fe_client.c
mgmtd/mgmt_be_adapter.c
mgmtd/mgmt_be_server.c
mgmtd/mgmt_ds.c
mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_fe_server.c
mgmtd/mgmt_history.c
mgmtd/mgmt_history.h
mgmtd/mgmt_txn.c
mgmtd/mgmt_vty.c

Description:
The following list of coverity issues fixed as part of this PR.
1. CID 1536832:  Memory - corruptions  (OVERLAPPING_COPY)
/mgmtd/mgmt_history.c: 85 in mgmt_history_create_cmt_rec()
2. CID 1536831:  Error handling issues  (NEGATIVE_RETURNS)
/mgmtd/mgmt_be_server.c: 123 in mgmt_be_server_start()
3. CID 1536830:  Resource leaks  (RESOURCE_LEAK)
/mgmtd/mgmt_history.c: 146 in mgmt_history_read_cmt_record_index()
4. CID 1536829:  Error handling issues  (NEGATIVE_RETURNS)
/mgmtd/mgmt_fe_server.c: 123 in mgmt_fe_server_start()
5. CID 1536828:  Possible Control flow issues  (DEADCODE)
/mgmtd/mgmt_txn.c: 1859 in mgmt_txn_get_config()
6. CID 1536827:  Null pointer dereferences  (NULL_RETURNS)
/mgmtd/mgmt_ds.c: 526 in mgmt_ds_delete_data_nodes()
Signed-off-by: Rajesh Girada …

mgmtd: Fixing coverity issues and style warnings in the code

---

zebra/zebra_dplane.c

Issue:
After vlan flap, zebra was not marking the selected/best route as installed.
As a result, when a static route was configured with nexthop as directly connected interface's(vlan) IP, the static route was not being installed in the kernel since its nexthop was unresolved. The nexthop was marked unresolved because zebra failed to mark the best route as installed after interface flap.
This was happening because, in dplane_route_update_internal() if the old and new context type, and nexthop group id are the same, then zebra doesn't send down a route replace request to kernel. But, the installed (ROUTE_ENTRY_INSTALLED) flag is set when zebra receives a response from kernel. Since the request to kernel was being skipped for the route entry, installed flag was not being set
Fix:
In …

zebra: Mark connected route as installed after interface flap event

---

bgpd/rfapi/rfapi.c
bgpd/rfapi/rfapi_rib.c
bgpd/rfapi/rfapi_vty.c

More rfapi exit cleanups of memory allocation per #12478

bgpd: rfapi memleak fixes

---

zebra/zebra_rib.c

Free up the link list data structures as well as properly account for data sizes.

zebra: Actually free up memory associated with the mq list

---

ospf6d/ospf6_gr_helper.c
ospfd/ospf_vty.c
tests/topotests/lib/ospf.py
tests/topotests/ospf_gr_helper/test_ospf_gr_helper1.py

Fix json key 'supoort' -> 'support'; add 1-year deprecation notice; fix topotests to use corrected json key.

ospf,ospf6: fix json key typo supoort

---

bgpd/bgp_evpn.c

Replace the checking local path code in `update_evpn_type5_route_entry()` with generic function.

bgpd: Simplify the checking local path

---

pimd/pim_bsm.c

Topology Used:
Cisco---FRR4----FRR2
Initially PIM nbr is down between FRR4----FRR2 from FRR2 side Cisco is sending BSR packet to FRR4.
No shutdown the PIM neighbor on FRR2 towards FRR4. FRR2, receives BSR packet immediately as the new neighbor comes up. This BSR packet is having no-forward bit set. FRR2 is not able to process the BSR packet, and drop the BSR packet.
Root Cause:
When PIMD comes up, we start BSM timer for 60 seconds. Here, the value accept_nofwd_bsm is setting to false.
FRR2, when receives no-forward BSR packet, it is getting accept_nofwd_bsm value as false.
So, it drops, the no-forward BSM packet.
Fix:
Set accept_nofwd_bsm as false after first BSM packet received.

pimd: Process no-forward BSM packet

---

pimd/pim6_mld.c
pimd/pim6_mld.h
pimd/pim_nb_config.c

After doing "no ipv6 pim" and "ipv6 pim" on receiver interface in LHR, mroutes were not created.
When we enable pim after disabling it, we refresh the membership on interface. First we clear the membership on the interface, then we add it back. For PIMv6 we were only clearing it, membership was not added back. So mroutes were not created.
Now added code to fetch all the local membership information into PIM.
Fixes: #12005, #12820

pim6d: mroutes not created after disabling and enabling PIMv6.

---

doc/developer/zebra.rst
pimd/pim_nht.c

`ZEBRA_IMPORT_CHECK_UPDATE` has been gone for more than a year; remove some leftover dead references to it.

pimd, doc: remove dead import check references

---

doc/developer/logging.rst

fix the print iso macro documentation
Fixes: 7f9ab3b0bb ("lib: Add ISO System & Network format to printfrr")

doc: fix the print iso macro documentation

---

ospf6d/ospf6_spf.c
ospf6d/ospf6_spf.h

When ospf6 is started up and SPF is run depending on which route is
selected as the parent route we could miss adding a NH.   If one
possible parent route has two equal cost paths and the second possible
parent route has only one depending on which one is selected first
determines if we have have one or two NHs.
In the network below when creating a route 2001:db8:3:4::/64 in R2. When SPF is run there are two possible parent routes R3 and R4.
2001:db8:1:2  +-----+   2001:db8:2:5
+--------------+  2  +---------------+
|          ::2 |     | ::2           |
|              +-----+               |
|                                    |
::1|                                    |
+-----+                                  |::5
|  1  |2001:db8:1:3+-----+2001:db8:3:5+-----+2001:db8:5:6+-----+
| …

ospf6d: missing ECMP NHs in certain topologies

---

lib/zclient.c
lib/zclient.h

An L3VPN network can be configured on the main BGP instance, with an SRv6 SID. By declaring a network, a seg6local route is created but remains invalid.
The below BGP VPN configuration the default VRF has been used:
> router bgp 1
>  address-family ipv6 unicast
>   sid vpn export auto
>   rd vpn export 1:30
>   rt vpn both 77:77
>   import vpn
>   export vpn
>   network 2001:7::/64
>  exit-address-family
The below seg6local route has been added:
> # show ipv6 route
> [..]
> B   2001:db8:2:2:300::/128 [20/0] is directly connected, unknown inactive, seg6local End.DT6 table 254, seg6 ::, weight 1, 00:00:07
>
When creating the seg6local route, an interface is used as nexthop. The interface index is obtained from the vrf identifier. This is true when using VRF interfaces, but is wrong when …

lib: fix handle seg6local routes on default vrf

---

tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-3.py
tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-4.py

The tests are killing bgpd and then ending, the next test is checking for all daemons running and spewing warnings to stderr. Restart the daemons before ending the test (like other tests in this same module) to avoid this.

tests: restart bgpd to avoid warnings in follow on tests

---

tools/frr-reload.py

From commit `411d1a2`, `bgp_delete_nbr_remote_as_line()` is added to remove some specific bgp neighbors.  But, when reloading the following configuration, it will wrongly remove some good ones: `neighbor 66.66.66.6 remote-as internal`:
```
router bgp 66
bgp router-id 172.16.204.6
neighbor ANLAN peer-group
neighbor ANLAN remote-as internal
neighbor 66.66.66.6 remote-as internal <- LOST
neighbor 66.66.66.60 peer-group ANLAN
```
The reason is that "66.66.66.6" is included in "66.66.66.60" literally, then it is mistakenly thought to be a match.  Just fix it with excat match.
Additionally, the flag of `found_pg_cmd` is already there, but not used. Let this flag work.

tools: fix missing remote-as configuration when reload

---

zebra/zebra_evpn_mac.c

EVPN MH ES reduendant VTEPs need to install sync MAC as notify inactive and generate
ND:Proxy stamped extended community on Type-2 route.
Testing Done:
tor-11 originates type-2 MAC route:
```
tor-11# bridge -d fdb show | grep 00:65:00:00:00:01 
00:65:00:00:00:01 dev hostbond1 vlan 1000 notify master bridge static
```
tor-12 receives sync MAC route:
**Before fix:**
----------
```
tor-12:/# bridge -d fdb show | grep 00:65:00:00:00:01 
00:65:00:00:00:01 dev hostbond1 vlan 1000 notify master bridge static
```
**After fix:**  inactive is set to MAC entry
----------
```
tor-12:/#bridge -d fdb show | grep 00:65:00:00:00:01 
00:65:00:00:00:01 dev hostbond1 vlan 1000 notify inactive master bridge static
```
Notice the difference in `inactive` post notify on tor-12 with the fix.
Signed-off-by: Trey …

zebra: EVPN MH ES-peer Sync MAC installed as inactive

---

bgpd/bgp_updgrp.c

The `NULL` check for newly created groups (`updgroup` and `subgroup`) are unnecessary,  just remove them.

bgpd: Remove unnecessary check for groups

---

bgpd/bgp_evpn_mh.c

FRR "show bgp l2 evpn es <esi-id> json" output shows 'dfAlgorithm' same as 'dfPreference' value instead of algorithm.
Modified the code to set the correct DF algorithm value into 'dfAlgorithm' field.
```
torm-11# show bgp l2 evpn es
ES Flags: B - bypass, L local, R remote, I inconsistent VTEP Flags: E ESR/Type-4, A active nexthop
ESI                            Flags RD                    #VNIs
VTEPs
03:44:38:39:ff:ff:01:00:00:01  LR    27.0.0.15:15          10
27.0.0.16(EA),27.0.0.17(EA)
03:44:38:39:ff:ff:01:00:00:02  LR    27.0.0.15:16          10
27.0.0.16(EA),27.0.0.17(EA)
03:44:38:39:ff:ff:01:00:00:03  LR    27.0.0.15:17          10
27.0.0.16(EA),27.0.0.17(EA)
03:44:38:39:ff:ff:02:00:00:01  R     -                     10
27.0.0.18(A),27.0.0.19(A),27.0.0.20(A) …
```

bgpd: EVPN MH add correct value into dfAlgorithm json output

---

doc/user/index.rst

Include affinity-maps documentation into index under "basics".

doc: include affinity-maps into index

---

doc/user/routemap.rst
lib/routemap.c
lib/routemap.h
lib/routemap_cli.c
lib/routemap_northbound.c
ospfd/ospf_asbr.c
ospfd/ospf_asbr.h
ospfd/ospf_ase.c
ospfd/ospf_lsa.c
ospfd/ospf_routemap.c
ospfd/ospf_zebra.c
tests/topotests/ospf_metric_propagation/h1/frr.conf
tests/topotests/ospf_metric_propagation/h2/frr.conf
tests/topotests/ospf_metric_propagation/r1/frr.conf
tests/topotests/ospf_metric_propagation/r1/show_ip_route-1.json
tests/topotests/ospf_metric_propagation/r1/show_ip_route-2.json
tests/topotests/ospf_metric_propagation/r1/show_ip_route-3.json
tests/topotests/ospf_metric_propagation/r1/show_ip_route-4.json
tests/topotests/ospf_metric_propagation/r1/show_ip_route-5.json
tests/topotests/ospf_metric_propagation/r1/show_ip_route-6.json
tests/topotests/ospf_metric_propagation/r2/frr.conf
tests/topotests/ospf_metric_propagation/r3/frr.conf
tests/topotests/ospf_metric_propagation/r4/frr.conf
tests/topotests/ospf_metric_propagation/ra/frr.conf
tests/topotests/ospf_metric_propagation/rb/frr.conf
tests/topotests/ospf_metric_propagation/rc/frr.conf
tests/topotests/ospf_metric_propagation/test_ospf_metric_propagation.py
yang/frr-route-map.yang

When using route maps with external routes in OSPF as follows:
```
set metric +10
```
The current behavior is to use the default ospf metric as the base and then. and add to 10 to it.
The behavior isn't useful as-is and since a value 30 (20, the ospf default metric +10)  can be set
directly instead. the behavior is also not consistent with bgp for example where bgp does use the
rib metric in this case as the base. The current behavior also doesn't allow the metric to accumulate
when crossing different routing domains such as vrfs causing the metric to reset every time the
route enters a new vrf with a new ospf network.
This PR changes the behavior such so that the rib metric is as a base for external routes
when used with route maps set metric -/+
This PR also adds two new route map …

ospfd: use rib metric as the base for set metric +/-

---

bgpd/bgp_route.c

1. Consider a established L2VPN EVPN BGP peer with soft-reconfiguartion inbound configured
2. When the interface of this directly connected BGP peer is shutdown, bgp_soft_reconfig_table_update() is called, which memsets the evpn buffer and calls bgp_update() with received attributes stored in ain table(ain->attr). In bgp_update(), evpn_overlay attribute in ain->attr (which is an interned attr) was modified by doing a memcpy
3. Above action causes 2 attributes in the attrhash (which were previously different) to match!
4. Later during fsm change event of the peer, bgp_adj_in_remove() is called to clean up the ain->attr. But, because 2 attrs in attrhash match, it causes BGP to assert in bgp_attr_unintern()
BGP Crash decode:
```
#0  0x00007f623b39f5cb in raise () from …
```

bgpd: Fix for ain->attr corruption during path update

---

bgpd/bgp_lcommunity.c

If you have a very large number of large communities whose string length happened to be greater than BUFSIZ FRR's bgpd would crash.  This is because bgpd would write beyond the end of the string.
Originally the code auto-calculated the string size appropriately but commit ed0e57e3f079352714c3a3a8a5b0dddf4aadfe1d modified the string length to be a hard coded BUFSIZ.  When a route-map like this is added:
route-map LARGE-OUT permit 10
set large-community 4635:0:0 4635:1:906 4635:1:2906 4635:1:4515 4635:1:4594 4635:1:4641 4635:1:4760 4635:1:7979 4635:1:9253 4635:1:9293 4635:1:9304 4635:1:9908 4635:1:13335 4635:1:16265 4635:1:17924 4635:1:18013 4635:1:20940 4635:1:22822 4635:1:24429 4635:1:24482 4635:1:32590 4635:1:32934 4635:1:36692 4635:1:38008 4635:1:38819 4635:1:41378 4635:1:45753 …

bgpd: Fix lcom->str string length to correctly cover aliases

---

bgpd/bgp_lcommunity.c

If you have a very large number of large communities whose string length happened to be greater than BUFSIZ FRR's bgpd would crash.  This is because bgpd would write beyond the end of the string.
Originally the code auto-calculated the string size appropriately but commit ed0e57e3f079352714c3a3a8a5b0dddf4aadfe1d modified the string length to be a hard coded BUFSIZ.  When a route-map like this is added:
route-map LARGE-OUT permit 10
set large-community 4635:0:0 4635:1:906 4635:1:2906 4635:1:4515 4635:1:4594 4635:1:4641 4635:1:4760 4635:1:7979 4635:1:9253 4635:1:9293 4635:1:9304 4635:1:9908 4635:1:13335 4635:1:16265 4635:1:17924 4635:1:18013 4635:1:20940 4635:1:22822 4635:1:24429 4635:1:24482 4635:1:32590 4635:1:32934 4635:1:36692 4635:1:38008 4635:1:38819 4635:1:41378 4635:1:45753 …

bgpd: [8.5] Fix lcom->str string length to correctly cover aliases

---

ripd/rip_peer.c
tests/topotests/rip_topo1/r1/rip_status.ref
tests/topotests/rip_topo1/r2/rip_status.ref
tests/topotests/rip_topo1/r3/rip_status.ref

Before:
```
Routing Protocol is "rip"
Sending updates every 5 seconds with +/-50%, next due in 0 seconds
Timeout after 15 seconds, garbage collect after 10 seconds
Outgoing update filter list for all interface is not set
Incoming update filter list for all interface is not set
Default redistribution metric is 1
Redistributing:
Default version control: send version 2, receive any version
Interface        Send  Recv   Key-chain
r1-eth0          2     1 2
Routing for Networks:
192.168.1.0/24
Routing Information Sources:
Gateway          BadPackets BadRoutes  Distance Last Update
192.168.1.2              0         0       120   00:00:05
192.168.1.3              0         0       120   00:00:04
Distance: (default is 120)
```
After:
```
Routing Protocol is "rip"
Sending updates every 5 seconds …
```

ripd: Align show ip rip status output for sources

---

pimd/pim6_mld.c
pimd/pim_zebra.c

Coverity shows a path where the pim instance may
be null.  In this code path if we have no pim
vrf there is nothing to do anyway so just return

pimd: Fix possible null of pim instance

---

pimd/pim6_mld.c

Coverity is "finding" some loops with untrusted boundaries and null pointer dereferences. They're all false positives, but try to make the code a bit more digestible to SA.
Anything left flagged after this is just gonna get marked as false positive :disappointed:

pimd: address some static analysis complaints

---

babeld/message.c

Ignore all other bits(except U) in Hello TLVs, according to   #@RFC8966

babeld: ignore nonzero flag bits in Hello TLVs

---

lib/typesafe.c
lib/typesafe.h
tests/lib/test_typelist.h

Coverity sent me on a chase to understand my own code, so the first commit here is just additional breadcrumbs to understand how `tabshift` works.
However, while looking over the constraints regarding `tabshift`, I noticed the typesafe hash `_member()` is actually missing a check and will crash if used on an empty hash table. Oops.
(We have no code using `_member` on a hash, it's only used on an RB tree in lib/cspf.c.)

lib: typesafe shenanigans

---

zebra/zebra_evpn_mac.c

In EVPN, duplicate detected local MAC is deleted from dplane/kernel, trigger BGP to re sync remote MAC to zebra. 
If MAC is detected duplicate and froze in Zebra then BGP won't be aware of the local learnt event, BGP has remotely learnt entry. Upon deletion of local MAC event, BGP to resync remote MAC so it can install properly in dplane/kernel.
Commit 1:
```
zebra: evpn handle del event for dup detected mac
Upon receiving local mobility event for MAC + NEIGH,
both are detected as duplicate upon hitting DAD threshold.
Duplicated detected ( Frozen) MAC + NEIGH are not known to bgpd.
If locally learnt MAC + NEIGH are deleted in kernel,
the MAC is marked as AUTO after sending delete event     to bgpd.
Bgpd only re-installs best route for MAC_IP route (NEIGH)
but not for MAC event.
This puts …
```

zebra: EVPN handle duplicate detected local mac delete event

---

tests/topotests/conftest.py
tests/topotests/lib/micronet_compat.py
tests/topotests/munet/config.py

Also, acutally remove the local ConfigOptionProxy
import munet 0.13.2 - fixed ConfigOptionsProxy bug

fix missed passing pytestconfig arg.

---

lib/subdir.am

This was missed somewhere along the line, causing ripd to not start:
```
2023/04/24 16:44:01 RIP: libyang: Data model "frr-if-rmap" not found in local searchdirs.
2023/04/24 16:44:01 RIP: libyang: Loading "frr-if-rmap" module failed.
2023/04/24 16:44:01 RIP: libyang: Parsing module "frr-ripd" failed.
2023/04/24 16:44:01 RIP: libyang: Data model "frr-ripd" not found in local searchdirs.
2023/04/24 16:44:01 RIP: libyang: Loading "frr-ripd" module failed.
2023/04/24 16:44:01 RIP: [XAR87-H157X][EC 100663321] yang_module_load: failed to load data model: frr-ripd
```

build: fix frr-if-rmap.yang model embedding

---

nhrpd/nhrp_nhs.c

Free NHRP peers associated with an interface when NHS is deleted on shutdown

nhrpd: Fix nhrpd memory leak

---

bgpd/bgp_route.c

The command `show bgp ipv4 uni neigh A.B.C.D received-routes detail` was not displaying anything.
Fix the code to display the received routes from the ones that have been filtered.  In this case we need to fudge up a bgp_dest and a bgp_path_info to make it work.
Old output:
janelle.pinkbelly.org# show bgp ipv4 uni neighbors 192.168.119.224 received-routes detail BGP table version is 1711405, local router ID is 192.168.44.1, vrf id 0 Default local pref 100, local AS 64539
Total number of prefixes 3 (3 filtered)
janelle.pinkbelly.org#
New output:
janelle.pinkbelly.org# show bgp ipv4 uni neighbors 192.168.119.224 received-routes detail BGP table version is 0, local router ID is 192.168.44.1, vrf id 0 Default local pref 100, local AS 64539
BGP routing table entry for 1.2.3.0/24, version 0 …

bgpd: Fix `received-routes detail`

---

bgpd/bgp_nexthop.c

The following BGP configuration does not show that the resolved next-hop to 192.0.2.1 has a defined interface.
> router bgp 65500
>  bgp router-id 192.0.2.2
>  neighbor 192.0.2.1 remote-as 65500
>  neighbor 192.0.2.1 update-source loop1
>  neighbor 192.168.0.1 remote-as 65500
>  !
>  address-family ipv4 unicast
>   network 192.0.2.2/32
>   no neighbor 192.168.0.1 activate
>  exit-address-family
>  !
>  address-family ipv4 labeled-unicast
>   neighbor 192.168.0.1 activate
>  exit-address-family
>  !
>  address-family ipv4 vpn
>   neighbor 192.0.2.1 activate
>  exit-address-family
The 'show bgp nexthop' dump does not output the interface whereas the zebra rnh has the information.
> dut-vm# show bgp nexthop
> [..]
> Current BGP nexthop cache:
>  192.0.2.1 valid [IGP metric 0], #paths 1, peer …

bgpd: keep interface index on bgp nexthop tracking

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/bgpd.h
doc/user/bgp.rst

Until now, the bgp local paths were using the default null label defined. It was not possible to select the null label for the ipv4 or the ipv6 address families.
This commit addresses this issues by adding two extra-parameters to the BGP labeled-unicast command.

bgpd: configure explicit-null for local paths per address family

---

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/r2/bgpd.conf

The `bgp_srv6l3vpn_to_bgp_vrf3` topotest locally fails all the time.
```
>       assert result is None, "Failed"
E       AssertionError: Failed
E       assert Generated JSON diff error report:
E         
E         > $->192.168.1.0/24: d2 has the following element at index 0 which is not present in d1: 
E         
E         	{
E         	    "prefix": "192.168.1.0/24",
[...]
E         	> $->192.168.1.0/24[0]: d2 has key 'asPath' which is not present in d1
[...]
bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py:140: AssertionError
```
The reason CI doesn't catch the error is that this topotest is skipped on older kernels that don't support the SRv6 feature under test.
The `bgp_srv6l3vpn_to_bgp_vrf3` topotest verifies the SRv6 L3VPN functionality. It applies the appropriate …

tests: Fix `bgp_srv6l3vpn_to_bgp_vrf3` topotest

---

zebra/zebra_evpn_mh.c

FRR "show evpn es 'esi-id' json" output dont have the 'df' flag.
Modified the code to add the 'df' flag into json output.
Before Fix:
```
torm-11# show evpn es 03:44:38:39:ff:ff:01:00:00:01 json
{
"esi":"03:44:38:39:ff:ff:01:00:00:01",
"accessPort":"hostbond1",
"flags":[
"local",
"remote",
"readyForBgp",
"bridgePort",
"operUp",
"nexthopGroupActive"
====================> df is missing
],
"vniCount":10,
"macCount":13,
"dfPreference":50000,
"nexthopGroup":536870913,
"vteps":[
{
"vtep":"27.0.0.16",
"dfAlgorithm":"preference",
"dfPreference":32767,
"nexthopId":268435460
},
{
"vtep":"27.0.0.17",
"dfAlgorithm":"preference",
"dfPreference":32767,
"nexthopId":268435461
}
]
}
torm-11#
```
After Fix:-
```
torm-11# show evpn es 03:44:38:39:ff:ff:01:00:00:01 json
{ …
```

zebra:add df flag into evpn esi json output

---

bgpd/bgp_flowspec_util.c

If an error is detected in an NLRI, immediately return an error, when there is a risk of buffer overflow.

bgpd: add some flowspec sanity returns

---

tests/topotests/bgp_bfd_down_cease_notification/r1/bgpd.conf
tests/topotests/bgp_bfd_down_cease_notification/r2/bgpd.conf
tests/topotests/bgp_bfd_down_cease_notification/test_bgp_bfd_down_cease_notification.py

If r1 becomes the "server" (= local port 179), then it initiates the connection after sending BGP Notification (BFD Down) and r2 resets the last error code.
Telling r1 do not connect to r2, fixes the issue.
Tested with `pytest -s -n 48` at least 20 times - no failures.
Closes https://github.com/FRRouting/frr/issues/13384

tests: Do not try establishing a connection from r1 to r2

---

pimd/pim_mroute.c

`setsockopt()` should be only called once with `MRT_TABLE`, otherwise it will fail.
It only affects "pim instance" with one VRF.
Skip it in the "disable" case.

pimd: Fix wrong setsockopt() call

---

tests/topotests/ospf_basic_functionality/ospf_lan.json
tests/topotests/ospf_basic_functionality/test_ospf_lan.py

the ospf_basic_functionality/test_ospf_lan.py script is setting up a lan env that will have 4 ospf routers on it and shutting/no shutting interfaces with various priorities to see that ospf is properly choosing roles.  I am consistently seeing the ospf_basic_functionality/test_ospf_lan.py script failing where it is saying a neighbor is not in the correct state.
Upon examination of the logs we are seeing this:
2023/04/24 09:16:42 OSPF: [M7Q4P-46WDR] vty[7]@(config)# interface r0-s1-eth0  <----- This is where we no shut the interface
2023/04/24 09:16:47 OSPF: [M7Q4P-46WDR] vty[7]@> enable
2023/04/24 09:16:47 OSPF: [M7Q4P-46WDR] vty[7]@# show ip ospf neighbor all json
2023/04/24 09:16:53 OSPF: [QH9AB-Y4XMZ][EC 100663314] STARVATION: task ospf_ism_event (556af08a5b4c) ran for 6038ms (cpu time …

tests: Increase the dead interval to be longer for neighbor testing

---

babeld/message.c
babeld/message.h
babeld/util.h

According to rfc8966
https://www.rfc-editor.org/rfc/rfc8966#name-compatibility-with-previous
https://datatracker.ietf.org/doc/html/draft-ietf-babel-source-specific-07#section-4.4
1. when type is MESSAGE_REQUEST, babel should be able to handle sub_tlvs
2. a wildcard request with a source prefix MUST be ignored

babeld: add parse_request_subtlv into parse_packet

---

zebra/zebra_rnh.c

Srv6 routes which configure encap method, may not have seg6local instructions. Generally speaking, seg6local attributes that are not specified should not be dumped.
Before:
> B>* 10.200.0.0/24 [20/0] via fd00:125::2, ntfp2 (vrf default), label 16, seg6local unspec unknown(seg6local_context2str), seg6 2001:db8:1:1:1::, weight 1, 0\
0:00:17
After:
> B>* 10.200.0.0/24 [20/0] via fd00:125::2, ntfp2 (vrf default), label 16, seg6 2001:db8:1:1:1::, weight 1, 00:00:17

zebra: display seg6local only when specified

---

isisd/isis_lsp.c
isisd/isis_spf.c
lib/flex_algo.c
lib/flex_algo.h

A particular flex-algo algorithm may remain in disabled state after
configuring it if its flex-algo definition is being spread in the area.
It happens sometimes that, in isis_sr_flex_algo_topo1 topotest, r3
flex-algo 203 is disabled on test8. It depends on the following
sequence on r3:
1. a LSP containing the flex-algo 203 definition is received from
either r1 or r2 (or both).
2. the local LSP is rebuilt by lsp_build() because of the flex-algo 203
configuration
3. isis_run_spf() recomputes the algo 203 SPF tree
A 1. 2. 3. sequence results in a working test whereas 2. 1. 3. is not
working. The second case issue is because of an inconsistent flex-algo
definition state between the following:
- in lsp_build(), isis_flex_algo_elected_supported_local_fad() returns
false because no flex-algo …

isisd: fix a flex algo race condition and a minor fix

---

zebra/if_netlink.c
zebra/interface.c

1. No any configuration in FRR, and `ip link add vrf1 type vrf ...`.                                                                    
Currently, everything is ok.                                                     
2.  `ip link del vrf1`.                                                          
`zebra` will wrongly/redundantly notify clients to add "vrf1" as a normal        
interface after correct deletion of "vrf1".                                      
```                                                                              
ZEBRA: [KMXEB-K771Y] netlink_parse_info: netlink-listen (NS 0) type RTM_DELLINK(17), len=588, seq=0, pid=0
ZEBRA: [TDJW2-B9KJW] RTM_DELLINK for vrf1(93) <- Wrongly as normal interface, not vrf 
ZEBRA: [WEEJX-M4HA0] interface vrf1 vrf vrf1(93) index 93 …
```

zebra: Fix missing VRF flag

---

ripd/ripd.c

According to RFC2453 3.6, the tag of a RIP-1 entry should be zero
https://datatracker.ietf.org/doc/html/rfc2453#section-3.6

ripd: add non-zero check for RIPv1 reserved field

---

pimd/pim_neighbor.c
pimd/pim_oil.c
pimd/pim_oil.h

When the router is non dr for an interface, it installs mroute to drop the packets from directly connected source. This was done to avoid packets coming to cpu as nocache hit. Later when it gets change from non-DR to DR, these entries are not cleared. So the packets are still dropped. This causes register packets not getting generated. So cleaning up the mroute entries and channel oil without upstream reference which was created to drop.
Issue: #12306

pimd: PIM not sending register packets after changing from non DR to DR

---

pimd/pim_oil.c

An old fix that used THREAD_OFF was pushed in, should have used EVENT_OFF instead.

pimd: Fix old commit that got in

---

pimd/pim6_mld.c

Replace the noisy CPP_NOTICE lines in pimd with TODO comments.

pimd: replace CPP_NOTICE lines with TODO comments

---

ospfd/ospf_vty.c

FRR has a memory leak in the case when int X does not exist and a memory leak when int X does exist.  Fix these

ospfd: Fix memory leaks w/ `show ip ospf int X json` commands

---

lib/command.c
lib/vty.c
lib/vty.h

When the user specifies `--command-log-always` in CLI arguments then also log commands executed from loading the config file.

lib: log commands read from config file

---

ldpd/lde_lib.c

ldpd: changes for code maintainability

---

bgpd/bgp_ecommunity.c

Setting
> bgp extcommunity-list standard EXT seq 5 permit nt 192.168.1.3:0
results in:
> bgp extcommunity-list standard EXT seq 5 permit NT:192.168.1.3
Fix the display

bgpd: fix show running of nt extcommunity

---

lib/nexthop.c
lib/nexthop.h
zebra/redistribute.c
zebra/zebra_nhg.c
zebra/zebra_nhg.h

1.  zebra: re-install nhg on interface up
```
Intermittently zebra and kernel are out of sync when interface flaps and the add's/dels are in same processing
queue and zebra assumes no change in nexthop. Hence we need to bring in a reinstall to kernel of the nexthops and routes to sync their states.
Upon interface flap kernel would have deleted NHGs associated to a interface (the one flapped), zebra retains NHGs for 3 mins even though upper layer protocol removes the nexthops (associated NHG).  As part of interface address add , re-add singleton NHGs associated to interface. 
```
2    zebra:re-install dependent nhgs on interface up
```
Upon interface up associated singleton NHG's  dependent NHGs needs to be reinstalled as
kernel would have deleted if there is no route referencing it.
``` …

zebra: re-install NHG on interface up

---

bgpd/bgp_route.c
doc/user/bgp.rst

The following are the changes made to the show cmds involving "detail" keyword
```
- Before this fix, there was only `show bgp <ipv4|ipv6> flowspec detail` command. 
After the fix, we support `show bgp <ipv4|ipv6> <unicast|multicast|vpn|labeled-unicast|flowspec> detail`.
- Before this fix, there was only support for `sh bgp vrf <vrf_name|all> <ipv4|ipv6> flowspec detail` command.
After the fix, we support `sh bgp vrf <vrf name|all> <ipv4|ipv6> <unicast|multicast|vpn|labeled-unicast|flowspec> detail`.
- Before this fix, `show bgp vrf all detail` only displays vrf default entries and does not iterate all vrfs.
After the fix, we iterate all vrfs including the default vrf.
```
Adding support to show cmds like  show bgp vrf all detail, show bgp <afi> <safi> detail & show bgp <vrf> <afi> <safi> …

bgpd: Fixing the show bgp <vrf> <afi> <safi> detail command

---

zebra/zebra_rib.c

There are two issues being addressed:
a) The ZEBRA_ON_RIB_PROCESS_HOOK_CALL script point was creating a fs pointer per dplane ctx in
rib_process_dplane_results().
b) The fs pointer was not being deleted and directly leaked.
For (a) Move the creation of the fs to outside
the do while loop.
For (b) At function end ensure that the pointer
is actually deleted.

zebra: Reduce creation and fix memory leak of frrscripting pointers

---

tests/topotests/bgp_distance_change/bgp_admin_dist_vrf.json

Loopback interfaces which were not used in scripts have been removed.
Signed-off-by: nguggarigoud [nguggarigoud@vmware.com](mailto:nguggarigoud@vmware.com)

tests: removing un used loopback interface from bgp admin dist.

---

ospfd/ospf_abr.c

The new create ```range``` attribute is send to add to ```ranges```, but not use if the prefix already exist in the ```ranges```. The stack trace below show a leak due to creation of new ```range```:
```
Direct leak of 56 byte(s) in 2 object(s) allocated from:
#0 0x7fa31eae3a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7fa31e68fae8 in qcalloc ../lib/memory.c:105
#2 0x55efd93e38ae in ospf_area_range_new ../ospfd/ospf_abr.c:43
#3 0x55efd93e47aa in ospf_area_range_set ../ospfd/ospf_abr.c:193
#4 0x55efd936f3e9 in ospf_area_range ../ospfd/ospf_vty.c:628
#5 0x7fa31e5d88d2 in cmd_execute_command_real ../lib/command.c:988
#6 0x7fa31e5d8f28 in cmd_execute_command_strict ../lib/command.c:1099
#7 0x7fa31e5d9acd in command_config_read_one_line …
```

[WIP] ospfd: opsf_abr.c memory leak fix, free unused range

---

ospfd/ospf_interface.c
ospfd/ospf_lsa.c

When setting an loopback's cost, set the value to 0, unless the operator has assigned a value for the loopback's cost.
RFC states:
If the state of the interface is Loopback, add a Type 3 link (stub network) as long as this is not an interface to an unnumbered point-to-point network. The Link ID should be set to the IP interface address, the Link Data set to the mask 0xffffffff (indicating a host route), and the cost set to 0.
FRR is going to allow this to be overridden if the operator specifically sets a value too.
Fixes: #13472

ospfd: Respect loopback's cost that is set and set loopback costs to 0

---

ospfd/ospf_apiserver.c
ospfd/ospf_opaque.c
ospfd/ospf_packet.c
tests/topotests/ospfapi/test_ospf_clientapi.py

1. Fix OSPF opaque LSA processing to preserve the stale opaque
LSAs in the Link State Database for 60 seconds consistent with
what is done for other LSA types.
2. Add a topotest that tests for cases where ospfd is restarted
and a stale OSPF opaque LSA exists in the OSPF routing domain
both when the LSA is purged and when the LSA is reoriginagted
with a more recent instance.

ospfd: OSPF opaque LSA stale processing fix and topotests.

---

ospfd/ospf_ti_lfa.c

This PR resolves a memory leak detected by ASan by freeing the P spaces.
```
./ospf_tilfa_topo1.test_ospf_tilfa_topo1/rt1.ospfd.asan.1698739:Direct leak of 320 byte(s) in 4 object(s) allocated from:
./ospf_tilfa_topo1.test_ospf_tilfa_topo1/rt1.ospfd.asan.1698739-    #0 0x7f78e0d25037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./ospf_tilfa_topo1.test_ospf_tilfa_topo1/rt1.ospfd.asan.1698739-    #1 0x7f78e08cb1ee in qcalloc lib/memory.c:105
./ospf_tilfa_topo1.test_ospf_tilfa_topo1/rt1.ospfd.asan.1698739-    #2 0x5586ead59567 in ospf_ti_lfa_generate_p_space ospfd/ospf_ti_lfa.c:778
./ospf_tilfa_topo1.test_ospf_tilfa_topo1/rt1.ospfd.asan.1698739-    #3 0x5586ead5a1e9 in ospf_ti_lfa_generate_p_spaces ospfd/ospf_ti_lfa.c:918 …
```

ospfd: Fix  ospf_ti_lfa memory leak

---

.clang-format

Add an AlignConsecutiveMacros config for clang-format. Instead of un-aligning a list of macros, like flags bits:
```
-#define ZEBRA_NHT_CONNECTED           0x1
-#define ZEBRA_NHT_DELETED             0x2
+#define ZEBRA_NHT_CONNECTED 0x1
+#define ZEBRA_NHT_DELETED 0x2
#define ZEBRA_NHT_RESOLVE_VIA_DEFAULT 0x4
```
this will allow a little more readable format:
```
-#define ZEBRA_NHT_CONNECTED           0x1
-#define ZEBRA_NHT_DELETED             0x2
+#define ZEBRA_NHT_CONNECTED          0x1
+#define ZEBRA_NHT_DELETED            0x2
#define ZEBRA_NHT_RESOLVE_VIA_DEFAULT 0x4
```
It's still not really great, but it won't make false-reports that we ignore any more frequent, and it will make the output for folks who blindly apply the clang-format diff better for the rest of us.

tools: config clang-format to allow aligned macros

---

zebra/zebra_dplane.c

The prov->dp_out_queued counter was never being decremented when a ctx was pulled off of the list.  Let's change it to accurately reflect real life.
Broken:
janelle.pinkbelly.org# show zebra dplane providers detailed Zebra dataplane providers:
Kernel (1): in: 330872, q: 0, q_max: 100, out: 330872, q: 330872, q_max: 330872 janelle.pinkbelly.org#
Fixed:
sharpd@janelle:/tmp/topotests$ vtysh -c "show zebra dplane providers detailed" Zebra dataplane providers:
Kernel (1): in: 221495, q: 0, q_max: 100, out: 221495, q: 0, q_max: 100 sharpd@janelle:/tmp/topotests$

zebra: Fix dp_out_queued counter to actually reflect real life

---

tests/topotests/bgp_features/test_bgp_features.py

don't grep the tail of a log file after running a previous test, there could be (and have been) other items added to the log in between.
add before and after count of shutdown messages to very the actual message shows up as the test intended, and keep the search for the shutdown message.

tests: improve bgp test determinism

---

pimd/pim_iface.c

Some interfaces are special, they have the same `ifindex` with pimreg.

pimd: Use macro for pimreg interface

---

.clang-format

This reverts commit 25314d5d878bbcc5ff63ebe76db9b2143b3e04ab.
This causes errors on clang-formatter for versions <= 10.
```
% git clang-format bgpd
YAML:14:25: error: invalid boolean
AlignConsecutiveMacros: AcrossComments
^~~~~~~~~~~~~~
error: `clang-format -lines=11624:11624 -lines=11802:11802 bgpd/bgp_vty.c` failed
```

Revert "tools: config clang-format to allow aligned macros"

---

doc/developer/building-frr-for-ubuntu2204.rst
doc/developer/topotests.rst
lib/libfrr.c
tests/topotests/all_protocol_startup/test_all_protocol_startup.py
tests/topotests/conftest.py
tests/topotests/lib/topotest.py

This restores the ability to catch memory free/cleanup errors on exit *without* running valgrind.  This used to work and was broken sometime in the last year or so by multiple changes.
This also includes minor doc changes and an ubuntu 22.04 doc

Don't disable redirected files when running in daemon mode.  Also add topotest flag to report memory allocations on exit logged to stderr

---

bgpd/bgp_vty.c
bgpd/bgpd.h
tests/topotests/evpn_pim_1/spine/bgp.summ.json

Closes https://github.com/FRRouting/frr/issues/13525

bgpd: Show the real table version for a decent peer subgroup

---

tests/topotests/bgp_vpnv6_per_nexthop_label/r1/bgp_ipv6_routes_vrf1.json
tests/topotests/bgp_vpnv6_per_nexthop_label/r1/bgpd.conf
tests/topotests/bgp_vpnv6_per_nexthop_label/r11/bgpd.conf
tests/topotests/bgp_vpnv6_per_nexthop_label/r13/bgpd.conf
tests/topotests/bgp_vpnv6_per_nexthop_label/test_bgp_vpnv6_per_nexthop_label.py

When moving a prefix from one device to one another, it seems the test does not wait for the BGP RIB to be updated, and considers the additional testing as not good.
Before checking for BGP update in r2, ensure that r1 has correctly received the new BGP update.
Fixes: 37a02a8dcb0d ("topotests: add bgp_vpnv6 test allocation")

topotests: fix bgp_vpnv6_per_nexthop, syncing with bgp rib

---

doc/developer/topotests.rst

- tshark and valgrind are required but only if you enable those features during test runs.

doc: document optionally required packages

---

tests/topotests/bgp_auth/test_bgp_auth1.py
tests/topotests/bgp_auth/test_bgp_auth2.py
tests/topotests/bgp_auth/test_bgp_auth3.py
tests/topotests/bgp_auth/test_bgp_auth4.py
tests/topotests/lib/topotest.py
tests/topotests/pytest.ini

- Restore default of looking for a daemon config underneath the router directory if no config file was specified.
- Recent change for adding unified config support had a logic bug, fix

tests: fix implicit config file and recently added logic error

---

lib/plist.c
tests/topotests/bgp_prefix_list_topo1/prefix_modify.json
tests/topotests/bgp_prefix_list_topo1/test_prefix_modify.py

Problem statement:
Step-1:
pl1 - 10.10.10.10/24 with deny sequence 1
Step-2:
pl1 - 10.10.10.10/24 with permit sequence 2
Step-3:
pl1 - 20.20.20.20/24 with permit sequence 1
Now we end up deleting permit sequence 2,
which might blackhole the traffic.
RCA:
Whenever we have multiple prefix lists,
having same prefix and different subnet range,
delete or replace of prefix list
would result in delete of entry in route-map
prefix table.
Fix:
We will skip deleting prefix list entry
from routemap prefix table, if we have
the multiple prefix lists having same prefix.

lib : fix duplicate prefix list delete

---

zebra/zebra_ptm.c

When FRR is built with the option `--disable-bfdd`, the build process fails with the following error:
```
zebra/zebra_ptm.c: In function ‘zebra_ptm_init’:
zebra/zebra_ptm.c:119:35: error: ‘FRR_PTM_NAME’ undeclared (first use in this function)
119 |  snprintf(buf, sizeof(buf), "%s", FRR_PTM_NAME);
|                                   ^~~~~~~~~~~~
zebra/zebra_ptm.c:119:35: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:10520: zebra/zebra_ptm.o] Error 1
```
The reason is that `FRR_PTM_NAME` is defined in `version.h` which is not imported.
This PR adds the missing import.

zebra: Fix build error when FRR is built with the `--disable-bfdd` option

---

.gitignore
configure.ac
doc/user/installation.rst

`ccls` needs information from FRR build configuration to work, so allow creation of a custom ccls config during autoconf.
Paraphrasing the doc entry: ccls is a very powerful tool that allows dev environments to provide sophisticated IDE functionality, e.g., semantically aware jumps and code refactoring...

doc: configure: add configure option to generate .ccls file

---

tests/topotests/munet/cli.py

This is happening sometimes for stuff like `r1 shi cat ...`.

tests: Ignore utf-8 decoding errors

---

bgpd/bgp_route.c
bgpd/rfapi/rfapi_import.c

This can lead into some garbage outputs, that can't be decoded in utf-8 or so.
This was catched when testing 76b246aa1f779e17ce6845c6ab0c292497b0008f.

bgpd: Initialize pfx_buf to zeros before using in bgp_path_info_cmp()

---

tests/topotests/bgp_remove_private_as/test_bgp_remove_private_as.py

From running the test:
bgp_remove_private_as/test_bgp_remove_private_as.py::test_bgp_remove_private_as
/home/sharpd/.local/lib/python3.10/site-packages/_pytest/python.py:198: PytestReturnNotNoneWarning: Expected None, but bgp_remove_private_as/test_bgp_remove_private_as.py::test_bgp_remove_private_as returned True, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

tests: pytest does not like return True from a test

---

bgpd/bgp_attr.c
bgpd/bgp_route.c

1. In ebgp+ ibgp deployment aggregate summary-only route selected path should always be locally originated
summary route. When aggregate route summary-only config is removed.
The selected path is iBGP peer as its lower cost upon reconfiguring aggregate route summary-only,
the locally originated is not selected due to always choosing first path attribute and bailing out as no change in route update.
Testing Done:
Config:
```
TORC11(config-router)#router bgp
TORC11(config-router)# address-family ipv4 unicast
TORC11(config-router-af)# aggregate-address 184.123.0.0/16 summary-only
TORC11(config-router-af)# no aggregate-address 184.123.0.0/16 summary-only
TORC11(config-router-af)# aggregate-address 184.123.0.0/16 summary-only
```
Before fix:
```
*> 184.123.0.0/16   ::(TORC11)               0 …
```

 bgpd: aggregate route best path select and other fixes

---

bfdd/bfd_packet.c

With this configuration:
```
bfd
peer 33:33::66 local-address 33:33::88 vrf vrf8 interface enp1s0
exit
!
exit
```
The bfd session can't be established with error:
```
bfdd[18663]: [YA0Q5-C0BPV] control-packet: wrong vrfid. [mhop:no peer:33:33::66 local:33:33::88 port:2 vrf:61]
```
The vrf check should use the carefully adjusted `vrfid`, which is based on globally/reliable interface.  We can't believe the `bvrf->vrf->vrf_id` because the `/proc/sys/net/ipv4/udp_l3mdev_accept` maybe is set "1" in VRF-lite backend even with security drawback.
Just correct the vrf check.

bfdd: Fix malformed session with vrf

---

lib/printf/glue.c
tests/topotests/bgp_default_originate/test_bgp_default_originate_2links.py
tests/topotests/lib/bgp.py
tests/topotests/lib/common_config.py
tests/topotests/lib/ospf.py
tests/topotests/lib/topojson.py
zebra/zebra_dplane.c

1) Tests that look for second changes in time but complete in under a second will fail
2) Tests should not stop the entire run of the topotests if an error is found on configuring a single test
3) Do not free a hash until we are done
4) Do not test for ctx being null when it cannot be
5) va_end must be called

Grab bag of fixes from upgrading system

---

ripd/rip_cli.c

```
==13211==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000af158 at pc 0x55d48c5f1e38 bp 0x7fffd8a713d0 sp 0x7fffd8a713c0 READ of size 8 at 0x6020000af158 thread T0
#0 0x55d48c5f1e37 in rip_allow_ecmp ripd/rip_cli.c:98
#1 0x7f2ec125aa0f in cmd_execute_command_real lib/command.c:990
#2 0x7f2ec125ae90 in cmd_execute_command lib/command.c:1049
#3 0x7f2ec125b406 in cmd_execute lib/command.c:1217
#4 0x7f2ec137ca36 in vty_command lib/vty.c:551
#5 0x7f2ec137ce52 in vty_execute lib/vty.c:1314
#6 0x7f2ec1384f9e in vtysh_read lib/vty.c:2223
#7 0x7f2ec137041b in event_call lib/event.c:1995
#8 0x7f2ec12b54bf in frr_run lib/libfrr.c:1204
#9 0x55d48c5f0f32 in main ripd/rip_main.c:171
#10 0x7f2ec0ad9c86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
#11 0x55d48c5f1349 …
```

ripd: Use argv_find to avoid buffer overflow when parsing allow-ecmp args

---

bfdd/bfdd.c
lib/grammar_sandbox.c
lib/mgmt_be_client.c
mgmtd/mgmt_memory.c
zebra/zebra_ptm.c

See individual commits but make the 'show memory` command work so that we are not clipping the table.

memory desciprtion shortening

---

vtysh/vtysh_user.c

Code was was written where the pam error message put out was the result from a previous call to the pam modules instead of the current call to the pam module.

vtysh: Give actual pam error messages

---

bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_updgrp_adv.c

Reuse subgroup_process_announce_selected(). It does the same as we do here duplicating the logic.

bgpd: Refactor subgroup_announce_table() to reuse an existing helpers

---

mgmtd/subdir.am
ripd/subdir.am

- mgmtd wasn't embedding `frr-staticd.yang` & `frr-bfdd.yang` (dependency), the Makefile-fu was a bit off
- ripd needs `frr-bfdd.yang` since the RIP model depends on it

build: fix missing YANG model embedding

---

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py

The usage of run_and_expect doesn't work if the function being called as the run part asserts.

tests: Actually loop if ping fails

---

bgpd/bgp_attr.c

When the remote peer is neither EBGP nor confed, aspath is the shadow copy of attr->aspath in bgp_packet_attribute(). Striping AS4_PATH should not be done on the aspath directly, since that would lead to bgpd core dump when unintern the attr.

bgpd: fix bgpd core when unintern attr

---

ospf6d/ospf6_gr.c
ospf6d/ospf6_gr.h
ospfd/ospf_gr.c
ospfd/ospf_gr.h

Change timestamp parameter from int to time_t to avoid truncation.
Found by Coverity Scan (CID 1563226 and 1563222)

ospfd, ospf6d: fix time_t truncation

---

pimd/pim_nb_config.c

Problem:
Execute the below commands, pim6d core happens.
interface ens193
ip address 69.0.0.2/24
ipv6 address 8000::1/120
ipv6 mld
ipv6 pim
We see crash only if the interface is not configured in kernel, and we are executing PIMV6/MLD commands.
RootCause:
Interface ens193 is not configured in kernel. So, it will have ifindex = 0 and mroute_vif_index = -1.
Currently, we don't enable MLD on an interface if
mroute_vif_index < 0. So, pim_ifp->MLD = NULL.
In the API pim_if_membership_refresh(), we are accessing pim_ifp->MLD NULL pointer which leads to crash.
Fix:
Added NULL check before accessing pim_ifp->MLD pointer in the API pim_if_membership_refresh().
Fixes #13385

pim6d: Fix crash in ipv6 pim command

---

ospf6d/ospf6_interface.c

Commit 76249532faad ("ospf6d: Handle Premature Aging of LSAs") added a duplicate call to `OSPF6_INTRA_PREFIX_LSA_EXECUTE_TRANSIT()`, when the interface state changes to "Down".
Fixes: #1738

ospf6d: Prevent redundant LSA generation before interface goes down

---

lib/command.c

When issue vtysh command with ?, the initial buf size for the element is 16. Then it would loop through each element in the cmd output vector. If the required size for printing out the next element is larger than the current buf size, realloc the buf memory by doubling the current buf size regardless of the actual size that's needed. This would cause vtysh core when the doubled size is not enough for the next element.

lib: fix vtysh core when handling questionmark

---

bgpd/bgp_nht.c

Cosmetic change for the debug messages, mainly on the parentheses.
Before:
```
[ZJYCS-KQYD6] VRF vrf-debug(140): Rcvd NH update 50.50.50.0/24(0)0) - metric 300/300 #nhops 2/1 flags Valid Reg Static Static Exact
[VZJVD-D7GXM] parse nexthop update(50.50.50.0/24(0)(VRF vrf-debug)): bnc info not found for nexthop cache
[NSWTE-81HEK] parse nexthop update(50.50.201.0/31(0)(VRF vrf-debug)): bnc info not found for import check
```
After:
```
[ZJYCS-KQYD6] VRF vrf-debug(140): Rcvd NH update 50.50.50.0/24(0)(0) - metric 300/300 #nhops 2/1 flags Valid Reg Static Static Exact
[VZJVD-D7GXM] parse nexthop update 50.50.50.0/24(0)(VRF vrf-debug): bnc info not found for nexthop cache
[NSWTE-81HEK] parse nexthop update 50.50.201.0/31(0)(VRF vrf-debug): bnc info not found for import check
```

bgpd: Fix typo in debug message

---

mgmtd/mgmt_txn.c

There is no way that xpath can ever be anything but NULL in the failure path with the goto's.  Let's just remove the goto's and return immediately.

mgmtd: xpath is already NULL in the failure path

---

tests/topotests/mgmt_startup/test_bigconf.py
tests/topotests/mgmt_startup/test_late_bigconf.py

The tests are failing due to heavily loaded system and insufficient time for large configs to be handled.  Increasing the time allows the tests to complete locally for me under heavy load.

tests: new mgmt_startup tests are failing due to insufficient time

---

bgpd/bgp_fsm.c

When a state machine transition fails, bgpd would output data about what happened, but not necessarily give the reason why.  Add that data to the output.

bgpd: Give more data when state machine fails to change state

---

lib/mgmt_fe_client.c
lib/mgmt_fe_client.h
lib/vty.c

Remove an obfuscating abstraction layer whose existence was entirely based on using a uintptr_t rather than a pointer to an declared-only struct.
As the code is no longer using a global FE "client context", and instead create client objects, rename the structure and it's uses to reflect this.

lib: mgmtd: remove obfuscating abstraction layer and other cleanup

---

isisd/isis_spf.c
tests/topotests/isis_sr_flex_algo_topo1/test_isis_sr_flex_algo_topo1.py

Fix issue https://github.com/FRRouting/frr/issues/13640
A configured flex-algo algorithm may remain in disabled state after its
definition is advertised on the area.
It happens sometimes that, in isis_sr_flex_algo_topo1 topotest step 4 or
8, flex-algo 203 is disabled. It depends on the following sequence:
1. Flex-algo 203 is configured on a remote router to be re-advertised.
2. A LSP is received on the local router and contains the algo 203
definition.
3. The local router re-builds its own LSP with lsp_build().
4. local router isis_run_spf() recomputes the algo 203 SPF tree.
A 1. 2. 3. 4. sequence results in a working test. The reception of the
remote LSP (2.) does not trigger the built of the local LSP. If for
some reasons, the sequence is 1. 3. 4. 2. 4., isis_run_spf() will not
knows …

isisd: fix wrongly disabled flex-algorithm

---

zebra/rib.h
zebra/zapi_msg.c

When using a context to send route notifications to upper level protocols, the code was using a locking function to get the route node.  There is no need for this to be locked as such FRR should free it up.

zebra: Unlock the route node when sending route notifications

---

tests/topotests/conftest.py
tests/topotests/lib/micronet_compat.py
tests/topotests/lib/topogen.py
tests/topotests/lib/topolog.py
tests/topotests/lib/topotest.py

- test module level exec.log no longer truncated to last test case output
- keep separate exec logs for each pytest worker when running in distributed mode
- cleanup the log names, and make sure they are present in all exec logs
- add per test case exec logs

tests: fix some broken logging

---

mgmtd/mgmt_history.h

I believe coverity can't tell the length of the return value from strftime based on the format string (like we can), so it allows `n` to be larger than it could be which then allows `sz - n` to be negative which is size_t positive and very large so it thinks an overrun is possible.
CID#1563211

mgmtd: assert an assertion for coverity

---

tools/frr-reload.py

There might be a time element(s) from temporary list are removed more than once
which leads to valueError in certain python3 version.
commit-id 1543f58b5 did not handle valueError properly. 
This caused regression where prefix-list config leads to delete followed by add.
The new fix should just pass the exception as
value removal from list_to_add or list_to_del
is best effort.
This allows prefix-list config has no change
then removes the lines from lines_to_del and
lines_to_add properly.
Testing:
Configure prefix-list in frr.conf and perform
multiple frr-reload. After first reload operation subsequent ones should not result in delete
followed by add of the prefix-list but rather no-op operation.
(Pdb) lines_to_add
[(('ip prefix-list FOO permit 10.2.1.0/24',), None)] (Pdb) lines_to_del …

tools: fix list value remove in frr-reload

---

pimd/pim_igmpv3.c
pimd/pim_tib.c

Setup:
Receiver---LHR---RP
Problem:
In LHR, ipv6 pim state remains after MLD prune received.
Root Cause:
When LHR receives join, it creates (*,G) channel oil with oil_ref_count = 2. The channel_oil is used by gm_sg sg->oil and upstream->channel_oil.
When LHR receives prune, currently upstream->channel_oil is deleted and gm_sg sg->oil still present. Due to this channel_oil is still present with oil_ref_count = 1
Fix:
When LHR receives prune, upstream->channel_oil and pim_sg sg->oil needs to be deleted.
Issue: https://github.com/FRRouting/frr/issues/11249

pim6d: Clear channel_oil on prune

---

bgpd/bgp_flowspec.c

This commit addresses a memory leak issue in the BGP Flowspec NLRI parsing function.
Previously when processing NLRI, dynamically allocated memory to `temp` was not being freed, leading to a memory leak.
The commit introduces the necessary code (XFREE) to properly free the temp memory after processing Flowspec NLRI.
```
./bgp_flowspec.test_bgp_flowspec_topo/r1.bgpd.asan.687689:Direct leak of 56 byte(s) in 2 object(s) allocated from:
./bgp_flowspec.test_bgp_flowspec_topo/r1.bgpd.asan.687689-    #0 0x7fc9872b5037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./bgp_flowspec.test_bgp_flowspec_topo/r1.bgpd.asan.687689-    #1 0x7fc986e5b1ee in qcalloc lib/memory.c:105 …
```

bgpd: Free temp memory

---

pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_nb_config.c

1. Move pim_if_membership_clear api from pimd/pim_nb_config.c to pimd/pim_iface.c
2. Rename pim_cmd_interface_delete to pim_pim_interface_delete and move the api to pimd/pim_iface.c
3. Move the mld/igmp deletion common code to api pim_gm_interface_delete Code for IPv6 deletion(gm_ifp_teardown) for MLD was missing in this flow. Making the code common fixes this too.

pimd, pim6d: re-arrange some code and pimv6 deletion flow fix

---

bfdd/bfdd_nb.c
bfdd/bfdd_nb.h
bfdd/bfdd_nb_config.c

Fixes warning logs:
```
2023/05/29 20:11:50 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2023/05/29 20:11:50 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
```

bfdd: remove redundant nb destroy callbacks

---

bgpd/bgp_route.c
bgpd/bgp_updgrp.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst
tests/topotests/bgp_default_originate_timer/r1/bgpd.conf
tests/topotests/bgp_default_originate_timer/r1/zebra.conf
tests/topotests/bgp_default_originate_timer/r2/bgpd.conf
tests/topotests/bgp_default_originate_timer/r2/zebra.conf
tests/topotests/bgp_default_originate_timer/r3/bgpd.conf
tests/topotests/bgp_default_originate_timer/r3/zebra.conf
tests/topotests/bgp_default_originate_timer/test_bgp_default_originate_timer.py

As seen in the flame graph, subgroup_default_originate() works full-time. More details in https://github.com/FRRouting/frr/commit/f1f142c7c45ad078710eb5dd0a917d9ef38e1ee8.

bgpd: Add an ability to control default-originate route-map timer

---

bgpd/bgp_nexthop.c
bgpd/bgp_nexthop.h
bgpd/bgp_nht.c

In BGP, when an interface up event is detected or triggered, the BNC that have a next-hop that matches the interface are not evaluated.
Check if the nexthop interface information matches the interface that received the event. In that case, call the path evaluation attached to the BNC context.

bgpd: upon if up event, evaluate bnc with matching nexthop

---

zebra/main.c

When shutting down the main pthread was first closing the sockets associated with the dplane pthread and then telling it to shutdown the pthread at a later point in time.  This caused the dplane to crash because the nl data has been freed already.  Change the shutdown order to stop the dplane pthread *and* then close the sockets.

zebra: Prevent crash because nl is NULL on shutdown

---

bfdd/bfd.h

https://github.com/FRRouting/frr/blob/ff82184faebac4f7de68018c54f0f55da2ebcf37/bfdd/bfd_packet.c#L848-L852
BFD_GETVER: since the version of bad packet is represented by 3 bits in B[0], BFD_VERMASK should be 0x07, instead of 0x03.
https://github.com/FRRouting/frr/blob/ff82184faebac4f7de68018c54f0f55da2ebcf37/bfdd/bfd.h#L82-L84
Fixes https://github.com/FRRouting/frr/issues/13673

bfd:fix version bits check

---

tests/topotests/bgp_suppress_fib/test_bgp_suppress_fib.py

Test was attempting to test the 60.0.0.0 route but was querying 10.0.0.3 and ignoring the result.  Let's fix it.

tests: Fix missing assert for test case in bgp_suppress_fib

---

bgpd/bgp_network.c
tests/topotests/bgp_flowspec/test_bgp_flowspec_topo.py

Add a bit of code to allow the bgp_flowspec topotest to gather data when something goes wrong.

tests: The bgp_flowspec frequently fails try to gather more data

---

ospfd/ospf_interface.c

interface link update event needs to be handle properly in ospf interface cache.
Example:
When vrf (interface) is created its default type would be set to BROADCAST because ifp->status
is not set to VRF. Subsequent link event sets ifp->status to vrf,
ospf interface update need to compare current type to new default type which would be VRF (OSPF_IFTYPE_LOOPBACK). Since ospf type param was created in first add event, ifp vrf link event didn't update ospf type param which leads to treat vrf as non loopback interface.
**Testing Done:**
Running config suppose to bypass rendering default network broadcast for loopback/vrf types.
Before fix:
vrf vrf1
vni 4001
exit-vrf
!
interface vrf1
ip ospf network broadcast
exit
After fix: (interface vrf1 is not displayed).
vrf vrf1
vni 4001
exit-vrf

ospfd: fix interface param type update

---

pbrd/pbr_zebra.c
zebra/rule_netlink.c

In pbrd, don't encode a rule without a table. There are cases where the zapi encoding was incorrect because the 4-octet table id was missing. In zebra, mask off the ECN bits in the TOS byte when encoding an iprule to match netlink's expectation.
Fixes: #13550

pbrd, zebra: fix zapi and netlink rule encoding

---

lib/mgmt_be_client.c

Rather than exist in some questionable state, make unexpected error handling more robust by simply cycling the connection.

lib: mgmtd: make error handling more robust

---

lib/mgmt_be_client.c
lib/mgmt_be_client.h
lib/mgmt_fe_client.c
lib/mgmt_fe_client.h
lib/mgmt_msg.c
lib/vty.c
lib/vty.h
mgmtd/mgmt_ds.c
mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_history.c

Only the last commit is new as this PR also contains PR #13763 
- log names of datastores not numbers
- improve logging for mgmt_msg_read
- Rather than use a bool, instead store the const string name of the pending command being run that has postponed the CLI. This adds some nice information to the logging when enabled.

mgmtd: improvements in logging and commentary

---

doc/developer/workflow.rst

Updated Coverity documentation based on recommendations from Donald Sharpe. This workflow worked for me on Ubuntu 22.04. I the used restview open source tool to view the changes in Chrome.

doc: Update Coverity workflow in developer documentation.

---

doc/developer/topotests.rst

The code block doesn't work because blank line is missing. So, just make it work.

doc: Fix one syntax error for code block

---

pimd/pim6_cmd.c

Max response time in the code is being used as decisecond but the user input is taken in millisecond. 
Also yang expects the field to be in decisecond.
The below condition in yang is failing due to the mismatch in units.
```
units deciseconds;
must ". <= ../query-interval * 10";
```
Issue: #11892

pim6d: Correcting the help string

---

bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_updgrp_adv.c

BGP cannot decide to disseminate the safi based upon the bgp suppress-fib command.  Modify the code to look at the safi for the decision to communicate to a peer the particular node.
Ticket: #3402926

bgpd: some safi's do not mix with bgp suppress-fib

---

vrrpd/vrrp_vty.c

'Priority' attribute is missing in "show vrrp interface <intf> json" output. Whereas it is there in non-json output.
It has been added now in show vrrp interface json output.
Before Fix:
```
vrrp1# show vrrp interface swp5.101 json
[
{
"vrid":2,
"version":3,
"autoconfigured":false,
"shutdown":false,
"preemptMode":true,
"acceptMode":true,
"interface":"swp5.101",
"advertisementInterval":1000,
"v4":{
"interface":"vrrp4-11-2",
"vmac":"00:00:5e:00:01:02",
"primaryAddress":"50.0.0.2",
"status":"Master",
"effectivePriority":110,
"masterAdverInterval":1000,
"skewTime":570,
"masterDownInterval":3570,
"stats":{
"adverTx":248456,
"adverRx":1,
"garpTx":1,
"transitions":2
},
"addresses":[
"50.0.0.1"
]
},
"v6":{
"interface":"vrrp6-11-2",
"vmac":"00:00:5e:00:02:02", …
```

vrrpd: add priority field into interface json

---

zebra/interface.c
zebra/interface.h

We have both interface-level configuration to enable mpls, and runtime mpls status. They need to be distinct - we're getting some side-effects right now because we only have one variable.

zebra: clarify interface-level mpls config

---

bgpd/bgp_evpn.c
bgpd/bgp_route.c
bgpd/bgp_table.h

Consider the scenario of anycast gateways with one ES group in evpn multihoming, the remote ( not ES group ) has already learn everything about that ES group.
When removing one of ES peers, `show evpn rmac vni all` kept no change sometimes, it means the rmac of the removed peer is still there. This error display depends on which member of peers is to be removed.
The root cause is that the best path selection for Type-2/5 routes maybe keep no change and the best path is not to the removed peer, so `bgpd` wrongly doesn't tell `zebra` to remove ( withdraw ) the Type-2/5 routes owned by the removed peer. Finally, the rmac display from `zebra` kept no change.
So, force the deletion.
----
It is updated, please check commit log.

bgpd: Fix missing deletion of evpn routes

---

ospf6d/ospf6_auth_trailer.c

According to RFC 7166, the sequence number should be treated as an unsigned 64-bit value, although it is stored as two 32-bit values.
When incrementing it, the code caused the lower-order 32-bit value to skip from 0xFFFFFFFE to 0. As a side effect, an error was never produced if the full 64-bit sequence number wrapped.
Fixes: #13805

ospf6d: Increment sequence number correctly in Authentication Trailer

---

ripd/ripd.c
ripngd/ripngd.c

Revert a couple of faulty commits.
To reproduce in ripd:
```
frr# conf t
frr(config)# vrf vrf1
frr(config-vrf)# exit
frr(config)# router rip vrf vrf1
frr(config-router)# exit
frr(config)# no vrf vrf1
frr(config)# no router rip vrf vrf1
vtysh: error reading from ripd: Resource temporarily unavailable (11)Warning: closing connection to ripd because of an I/O error!
frr(config)#
```
Same thing with ripngd.

fix crashes in rip and ripng

---

vrrpd/vrrp.c

CID1519841: check return value and set error

vrrp: check return value for turning off multicast for v6

---

.clang-format

We modify the following from Linux Style:
AlignEscapedNewlines: Left -> Right
AlignTrailingComments: false -> true
AlignConsecutiveMacros: false -> true
ForEachMacros (replace linux with ours)
Don't break a string into multi-string-fragments
PenaltyBreakString: 10 -> 200
And allow going past the ColumnLimit some to keep function arguments aligned with the open parenthesis.
PenaltyBreakBeforeFirstCallParameter: 30 -> 200

tools: import latest linux clang-format config w/ FRR mods

---

lib/command.c
lib/mgmt.proto
lib/mgmt_fe_client.c
lib/mgmt_fe_client.h
lib/mgmt_msg.c
lib/mgmt_msg.h
lib/northbound_cli.c
lib/vty.c
lib/vty.h
mgmtd/mgmt_be_adapter.c
mgmtd/mgmt_be_adapter.h
mgmtd/mgmt_ds.c
mgmtd/mgmt_ds.h
mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_history.c
mgmtd/mgmt_txn.c
mgmtd/mgmt_txn.h
tests/lib/test_grpc.cpp
vtysh/vtysh.c
vtysh/vtysh_config.c

CLEANUP WRITE LOCKS
Move away from things like "lock if not locked" type code.
New KISS requirements API user must always lock the datastores.
- SET CFG:
not implicit commit - requires user has locked candidate DS and they
must unlock after
implicit commit - requires user has locked candidate and running DS
both locks will be unlocked on reply to the SETCFG
- COMMIT CFG:
requires user has locked candidate and running DS and they must unlock
after
NO READ LOCKS:
Run get-config operation from a snapshot of tree, eliminating need for read locks.
- For get-config operation instead of trying to maintain read and write locking, we take a snapshot of the config and run the operation off that. This allowed us to remove read locking from mgmtd.
- Also use short-circuit path for CLI (frontend) …

mgmt lock simplification

---

doc/developer/workflow.rst

Previous commit contained typo repeated in two places where "scan-file" was
used instead of "scan-build". I discovered this error when following my own
instructions.

doc: Fix typo in previous Coverity workflow doc commit.

---

zebra/if_netlink.c
zebra/interface.c
zebra/interface.h

It is never actually used in the code.
Closes #13532.

zebra: remove ZEBRA_IF_BOND_SLAVE interface type

---

pimd/pim_register.c
pimd/pim_upstream.c

Problem:
When ipv6 pim configuration is removed from the IIF on FHR node, if we wait for RST timer to expire and then add the ipv6 pim configuration on the IIF again, it is seen that pimreg is not getting added due to which null register wont be sent, the register flag state also remains NO_INFO forever instead of RegPrune. The reason for this is, when RST timer expires and IIF is unknown for the (S,G) upstream, the FHR state is not reset due to which when the RP becomes reachable, upstream state changes from NotJoined to Join but the register suppress timer could not be started since we see there is no change in FHR state.
Fix:
When the Register Timer expires and the reg state is set to PIM_REG_NOINFO,reset the FHR flag, so that when the RP becomes reachable can be because of config …

pim, pim6d: pimreg interface is not getting added in a certain scenario

---

isisd/isis_main.c

Log an error when the config-end callback is not received for 10 minutes.

isisd: Log error when config-end timeout occurs.

---

lib/link_state.c
lib/log.c
lib/zclient.c
lib/zclient.h
sharpd/sharp_vty.c
sharpd/sharp_zebra.c
sharpd/sharp_zebra.h
zebra/zapi_msg.c
zebra/zebra_opaque.c

This PR adds support for notifications from zebra when daemons register and unregister for opaque message types. Clients can use these notifications to rendezvous with servers - something that's difficult currently. A client can register for notifications; zebra will notify registered clients when a server first registers for an opaque message type, and when (if) the last server un-registers.

lib, zebra, sharpd: add notifications for ZAPI opaque message registration events

---

ospfd/ospf_main.c
ospfd/ospf_packet.c
ospfd/ospfd.c
ospfd/ospfd.h

Added configuration callbacks to prevent ospfd from sending hellos during config load. 
Tried similar change in ospf6d but it resulted in topotest failures - more investigation needed. 
Closes https://github.com/FRRouting/frr/issues/13542

ospfd: Add config callbacks and suppress hello during config load.

---

ospf6d/ospf6_main.c
ospf6d/ospf6_message.c
ospf6d/ospf6d.c
ospf6d/ospf6d.h
ospf6d/subdir.am

Add config-callbacks to ospf6d to suppress sending hellos during config load. Also, add "debug ospf6 event". 
Tested with ospf6 and ospfv3 topo tests.

ospf6d: Add config callbacks to suppress hellos during config load.

---

bgpd/bgp_attr.c
bgpd/bgp_attr.h
bgpd/bgp_ecommunity.c
bgpd/bgp_ecommunity.h
bgpd/bgp_nht.c
bgpd/bgp_routemap.c
bgpd/bgp_routemap_nb.c
bgpd/bgp_routemap_nb.h
bgpd/bgp_routemap_nb_config.c
bgpd/bgp_zebra.c
doc/user/bgp.rst
lib/routemap.h
lib/routemap_cli.c
tests/topotests/bgp_color_extcommunities/r1/bgpd.conf
tests/topotests/bgp_color_extcommunities/r1/zebra.conf
tests/topotests/bgp_color_extcommunities/r2/bgpd.conf
tests/topotests/bgp_color_extcommunities/r2/zebra.conf
tests/topotests/bgp_color_extcommunities/test_bgp_color_extcommunities.py
yang/frr-bgp-route-map.yang

bgpd,lib,yang: add colored extended communities support
add support of color extended community, conforming to RFC 9012.
This extended community will be added to the existing one, RT,SOO
and Node Target. The configuration will be made through the
route-map service.
find above a configuration example:
bgp router-id 192.168.1.1
no bgp network import-check
neighbor 192.168.1.2 remote-as external
neighbor 192.168.1.3 remote-as external
neighbor 192.168.1.4 remote-as external
network 10.10.10.10/24 route-map rmap
!
route-map rmap permit 10
set extcommunity color 55555 200
exit

bgpd,lib,yang: add colored extended communities support

---

babeld/message.c

According to RFC8966:
AE cannot be 0 when type = 7(Next Hop) or 10(Seqno Request).
https://www.rfc-editor.org/rfc/rfc8966.html#name-tlv-format
Closes https://github.com/FRRouting/frr/issues/13671

babeld: add AE!=0 check when type is 7 or 10.

---

zebra/zebra_vxlan.c

EVPN RMAC (Router MAC) nexthop list compare function needs to return all values so
the list element can be compared and added/deleted properly.
Testing Done:
Originate EVPN Type-5 route with PIP IP and MAC as remote nexthops.
Change the PIP IP address which triggers nexthop change.
Before fix:
When PIP IP changes RMAC is deleted from remote VTEPs.
```
TORS1# show evpn next-hops vni 4001 | include 00:02:00:00:00:2d
27.0.0.11       00:02:00:00:00:2d
TORS1# show evpn rmac vni 4001 | include 00:02:00:00:00:2d 
00:02:00:00:00:2d 27.0.0.11
```
----- Remote VTEP change nexthop IP to 172.16.16.16 -----
```
TORS1# show evpn next-hops vni 4001 | include 00:02:00:00:00:2d
172.16.16.16    00:02:00:00:00:2d
TORS1# show evpn rmac vni 4001 | include 00:02:00:00:00:2d
TORS1#
```
After fix:
RMAC is …

zebra: fix evpn rmac nh list cmp function

---

bgpd/bgpd.c

bgpd: Check for NULL before assigning a peer from the group

---

zebra/zebra_opaque.c

Seems a bit fussy of coverity, but ... don't NULL a variable unnecessarily.

zebra: clean up coverity warning in opaque api

---

staticd/static_bfd.c

```
vrf BELLA
ip route 1.1.1.1/32 192.168.1.1 bfd profile test
exit-vrf
```
Before patch:
```
BFD Peers:
peer 192.168.1.1 vrf default
```
After patch:
```
BFD Peers:
peer 192.168.1.1 vrf BELLA
```

staticd: Fix bfd for static route in VRF

---

isisd/isis_zebra.c
ospfd/ospf_zebra.c

Opaque zapi messages carry the sender's zclient tuple now, daemons shouldn't try to parse those bits directly. This should fix the recent report of zapi parsing errors after some recent opaque message changes.

isisd, ospfd: fix opaque zapi source parsing

---

bgpd/bgp_mplsvpn.c

Bgp coverity fix

---

doc/developer/building.rst
doc/developer/subdir.am

Add Ubuntu 22.04 build instructions to list.
Sort list into alphabetic order.

doc: Add Ubuntu 22.04 to list of builds

---

pbrd/pbr_vty.c

Crash with empty `ip-protocol`:
```
anlan(config-pbr-map)# match ip-protocol
vtysh: error reading from pbrd: Resource temporarily unavailable (11)Warning: closing connection to pbrd because of an I/O error!
```
So, prohibit empty value for `ip-protocol`.

pbrd: fix crash with match command

---

.clang-format
lib/darr.c
lib/darr.h
lib/mgmt.proto
lib/mgmt_be_client.c
lib/mgmt_fe_client.c
lib/mgmt_fe_client.h
lib/subdir.am
lib/vty.c
lib/vty.h
mgmtd/mgmt_be_adapter.c
mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_fe_adapter.h
mgmtd/mgmt_txn.c
mgmtd/mgmt_txn.h
mgmtd/mgmt_vty.c
tests/lib/subdir.am
tests/lib/test_darr.c

- rename a variable abbrev to avoid possible misreading
- remove unimplemented message types
- consolidate 2 getmsg types to 1 removing copy/paste code.
- move from static array to dynamic for xpath registries

Changes for inclusive language and other cleanup

---

bgpd/bgp_routemap.c
doc/user/bgp.rst
tests/topotests/bgp_set_aspath_replace/r1/bgpd.conf
tests/topotests/bgp_set_aspath_replace/test_bgp_set_aspath_replace.py

There is no route-map set action to replace any ASN, or a part of an ASN, with a configured ASN.
The current commit adds a new command to use a configured ASN as replacement, instead of using the local as number.
> set as-path replace any 65500
Update the 'bgp_set_aspath_replace' test.

bgpd: add 'set as-path replace' with a configured ASN

---

bgpd/bgp_routemap.c

fix to avoid "Excessive docstring" message
sharpd@eva ~/frr (tests_need_to_be_stricter)> sudo /usr/lib/frr/bgpd --log stdout --log-level debug --daemon
2023/06/30 09:47:25 BGP: [K2CCG-5Y7ZJ] Excessive docstring while parsing 'no set as-path replace [<any|ASNUM>]
[<ASNUM>$configured_asn]'
2023/06/30 09:47:25.361807 BGP: [K2CCG-5Y7ZJ] Excessive docstring while parsing 'no set as-path replace [<any|ASNUM>] [<ASNUM>$configured_asn]'
2023/06/30 09:47:25 BGP: [W7ENN-K2SVA] ----------
2023/06/30 09:47:25.361839 BGP: [W7ENN-K2SVA] ---------- 2023/06/30 09:47:25 BGP: [WCW75-6TZPF] Define the configured AS number 2023/06/30 09:47:25.361842 BGP: [WCW75-6TZPF] Define the configured AS number
2023/06/30 09:47:25 BGP: [W7ENN-K2SVA] ----------
2023/06/30 09:47:25.361844 BGP: [W7ENN-K2SVA] ---------- …

bgpd: fix no set as_path replace command

---

ospfd/ospf_ldp_sync.c
ospfd/ospf_vty.c

There were a couple of cli paths that NULL-checked in the vtysh output path, but not in the json path.

ospfd: check for NULLs in ldp-igp sync json code

---

ospf6d/ospf6_message.c

I'm seeing crashes in ospf6_write on the `assert(node)`.  The only sequence of events that I see that could possibly cause this to happen is this:
a) Someone has scheduled a outgoing write to the ospf6->t_write and placed item(s) on the ospf6->oi_write_q
b) A decision is made in ospf6_send_lsupdate() to send an immediate packet via a event_execute(..., ospf6_write,....). c) ospf6_write is called and the oi_write_q is cleaned out. d) the t_write event is now popped and the oi_write_q is empty and FRR asserts on the `assert(node)` <crash>
When event_execute is called for ospf6_write, just cancel the t_write event.  If ospf6_write has more data to send at the end of the function it will reschedule itself.  I've only seen this crash one time and am unable to reliably reproduce this at all. …

ospf6d: Stop crash in ospf6_write

---

ospf6d/ospf6_message.c
ospf6d/ospf6_neighbor.c
ospf6d/ospf6_neighbor.h

The loading_done event needs a event pointer to prevent use after free's.  Testing found this:
ERROR: AddressSanitizer: heap-use-after-free on address 0x613000035130 at pc 0x55ad42d54e5f bp 0x7ffff1e942a0 sp 0x7ffff1e94290
READ of size 1 at 0x613000035130 thread T0
#0 0x55ad42d54e5e in loading_done ospf6d/ospf6_neighbor.c:447
#1 0x55ad42ed7be4 in event_call lib/event.c:1995
#2 0x55ad42e1df75 in frr_run lib/libfrr.c:1213
#3 0x55ad42cf332e in main ospf6d/ospf6_main.c:250
#4 0x7f5798133c86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
#5 0x55ad42cf2b19 in _start (/usr/lib/frr/ospf6d+0x248b19)
0x613000035130 is located 48 bytes inside of 384-byte region [0x613000035100,0x613000035280)
freed by thread T0 here:
#0 0x7f57998d77a8 in __interceptor_free …

ospf6d: Fix crash because neighbor structure was freed

---

ospf6d/ospf6_message.c
ospf6d/ospf6_neighbor.c
ospf6d/ospf6_neighbor.h

Manual backports of https://github.com/FRRouting/frr/pull/13908, https://github.com/FRRouting/frr/pull/13911.

ospf6d: Crash backports

---

bgpd/bgp_evpn_vty.c
ospfd/ospf_vty.c

When not using json, do not allocate json memory.
Closes https://github.com/FRRouting/frr/issues/13919

ospfd: Ensure `show ip ospf interface` json code is guarded

---

lib/routemap.c

There were a couple of places where it was possible a route-map was applied( and DENIED ) but the count for the number of times the application happen was not incremented.

lib: Add two places we were not counting route-map applied

---

ospf6d/ospf6_gr.c
ospf6d/ospf6_lsdb.c

The function ospf6_router_lsa_contains_adj(), ospf6_gr_check_adjs() and ospf6_find_interf_prefix_lsa() iterate through LSDB and lock each LSA. During testing, it was discovered that the lock count did not reach zero upon termination. The stack trace below indicates the leak. To resolve this issue, it was found that unlocking the LSA before returning from the functions solves the problem. This suggests that there was a missing unlock that caused the lock count to remain nonzero.
```
================================================================= ==22565==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 400 byte(s) in 2 object(s) allocated from:
#0 0x7fa744ccea37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7fa744867562 in qcalloc …
```

ospf6d: unlock lsa

---

pimd/pim_cmd_common.c

**Problem:**
The cli "show ipv6 pim state" is not displaying when outgoing interface list is empty.
This is fixed now.
**Before Fix:**
`frr# show ipv6 pim state json`
`{`
` "ffaa::5":{`
` "1100::10":{`
` "ens224":{`
`    },`
`  "installed":1,`
`  "isRpt":false,`
` "refCount":1,`
`  "oilListSize":0,`
`"oilRescan":0,`
`"lastUsed":0,`
` "packetCount":40,`
`"byteCount":3080,`
`  "wrongInterface":1`
`}`
`}`
`}
`frr# show ipv6 pim state`
`Codes: J -> Pim Join, I -> MLD Report, S -> Source, * -> Inherited from (*,G), V -> VxLAN, M -> Muted`
`Active  Source  Group  RPT  IIF  OIL`
**After fix:**
Case 1:
- "show ipv6 pim state" output with 1 oil.
`frr# show ipv6 pim state`
`Codes: J -> Pim Join, I -> MLD Report, S -> Source, * -> Inherited from (*,G), V -> VxLAN, M -> Muted`
`Active  Source …

pim6d: "show ipv6 pim state" not displaying when OIL is empty

---

bgpd/bgp_mplsvpn.c
bgpd/bgp_mplsvpn.h
bgpd/bgpd.c

The bgp vpn policy had some attribute not free when the function bgp_free was called leading to memory leak as shown below.
```
./bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.bgpd.asan.603251:Direct leak of 592 byte(s) in 2 object(s) allocated from:
./bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.bgpd.asan.603251-    #0 0x7f4b7ae92037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.bgpd.asan.603251-    #1 0x7f4b7aa96e38 in qcalloc lib/memory.c:105
./bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.bgpd.asan.603251-    #2 0x7f4b7aa9bec9 in srv6_locator_chunk_alloc lib/srv6.c:135
./bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.bgpd.asan.603251-    #3 …
```

bgpd: free bgp vpn policy

---

babeld/babeld.c
bgpd/bgp_zebra.c
bgpd/bgpd.c
bgpd/rfapi/vnc_zebra.c
eigrpd/eigrp_northbound.c
eigrpd/eigrp_zebra.c
isisd/isisd.c
lib/vrf.c
lib/vrf.h
lib/zclient.c
ospf6d/ospf6_top.c
ospf6d/ospf6_zebra.c
ospf6d/ospf6_zebra.h
ospfd/ospf_flood.c
ospfd/ospf_zebra.c
ospfd/ospfd.c
zebra/redistribute.c
zebra/zapi_msg.c
zebra/zserv.c

When running all daemons with config for most of them, FRR has sharpd@janelle:~/frr$ vtysh -c "show debug hashtable"  | grep "VRF BIT HASH" | wc -l 3570
3570 hashes for bitmaps associated with the vrf.  This is a very large number of hashes.  Let's do two things:
a) Reduce the created size of the actually created hashes to 2 instead of 32.
b) Delay generation of the hash *until* a set operation happens. As that no hash directly implies a unset value if/when checked.
This reduces the number of hashes to 61 in my setup for normal operation.

*: Rearrange vrf_bitmap_X api to reduce memory footprint

---

zebra/zebra_rib.c

When using asic_offload with an asynchronous notification the rib_route_match_ctx function is testing for distance and tag being correct against the re.  This is no longer necessary.
Normal route notification for static routes is this(well really all routes): a) zebra dplane generates a ctx to send to the dplane for route install b) dplane installs it in the kernel
c) if the dplane_fpm_nl.c module is being used it installs it. d) The context's success code is set to it worked and passes the context back up to zebra for processing.
e) Zebra master receives this and checks the distance and tag are correct for static routes and accepts the route and marks it installed.
If the operator is using a wait for install mechansim where the dplane is asynchronously sending the result back up at a …

zebra: Static routes async notification do not need this test

---

bgpd/bgp_mplsvpn.c

`bmnc->nh` was not properly freed, leading to a memory leak. The commit adds a check to ensure that the `bmnc->nh` member variable is freed if it exists.
```
Address Sanitizer Error detected in bgp_vpnv4_asbr.test_bgp_vpnv4_asbr/r2.asan.bgpd.6382
==6382==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 720 byte(s) in 5 object(s) allocated from:
#0 0x7f6a80d02d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x55c9afd7c81c in qcalloc lib/memory.c:105
#2 0x55c9afd9166b in nexthop_new lib/nexthop.c:358
#3 0x55c9afd93aaa in nexthop_dup lib/nexthop.c:843
#4 0x55c9afad39bb in …
```

bgpd: Free nexthop in bgp_mplsvpn_nh_label_bind_free

---

pimd/pim6_mld.c

Problem:
ANVL Conformance test case 7.31 failed because DUT after receiving MLD Done msg and a query message with lower adddress, DUT did not keep on sending the group specific queries since it moved to non-querier state.
As per RFC 2710 s4 p7, DUT is supposed to keep sending the group specific queries until either it receives the membership report or there is no response even after last member query is sent.
Fix:
Whenever group specific queries are sent out we are checking if the self node is querier, if not it does not sends this query out. This check is preventing the continuation of the last queries which must be sent out although the self node is not the querier. Hence removing the check from the api gm_trigger_specific_query and adding in the caller to make sure this event is only …

pim6d: MLD conformance querier-non-querier transition fix

---

tests/topotests/zebra_rib/r1/v4_route_1_vrf_before.json
tests/topotests/zebra_rib/test_zebra_rib.py
zebra/zebra_nhg.c

Two commits:
1. zebra: Remove unnecessary condition check for kernel routes
There are relaxed nexthop requirements for kernel routes because we
trust kernel routes.
Two minor changes for kernel routes:
1. `if_is_up()` is one of the necessary conditions for `if_is_operative()`.
Here, we can remove this unnecessary check for clarity.
2. Since `nexthop_active()` doesn't distinguish whether it is kernel route,
modified the corresponding comment in it.
2. zebra: fix wrong nexthop check for kernel routes
When changing one interface's vrf, the kernel routes are wrongly kept
in old vrf.  Finally, the forwarding table in that old vrf can't forward
traffic correctly for those residual entries.
Follow these steps to make this problem happen:
( Firstly, "x1" interface of default vrf is with address …

zebra: fix wrong nexthop check for kernel routes

---

zebra/dplane_fpm_nl.c
zebra/if_netlink.c
zebra/if_netlink.h
zebra/interface.c
zebra/kernel_netlink.c
zebra/kernel_socket.c
zebra/rt.h
zebra/rt_netlink.c
zebra/rt_netlink.h
zebra/rule_netlink.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_l2.c
zebra/zebra_l2.h
zebra/zebra_mpls.c
zebra/zebra_mpls_openbsd.c
zebra/zebra_nhg.c
zebra/zebra_ns.c
zebra/zebra_ns.h
zebra/zebra_rib.c
zebra/zebra_router.c
zebra/zebra_router.h
zebra/zebra_script.c
zebra/zebra_vrf.c
zebra/zebra_vrf.h

see individual commits, but effectively move LINK and ADDR kernel events to the dplane.

move interface ( LINK and ADDR ) events to the dplane

---

bgpd/bgp_evpn_vty.c

The `bgp_vrf->vrf_prd_pretty` string was not properly freed, leading to a memory leak. This commit resolves the memory leak by freeing the memory allocated for `bgp_vrf->vrf_prd_pretty` before returning from the function.
```
Address Sanitizer Error detected in evpn_type5_test_topo1.test_evpn_type5_topo1/e1.asan.bgpd.17689
==17689==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 15 byte(s) in 1 object(s) allocated from:
#0 0x7fdd94fc0538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
#1 0x55e28d9c4c6c in qstrdup lib/memory.c:117
#2 0x55e28d6c0d27 in evpn_configure_vrf_rd …
```

bgpd: Fix memory leak

---

zebra/dplane_fpm_nl.c
zebra/zebra_dplane.c

This PR fixes #13754.
In `dplane_fpm_nl`, `fpm_read` allocates a dplane route context and calls `netlink_route_change_read_unicast_internal` to populate the dplane context with the received route. When `netlink_route_change_read_unicast_internal` fails to process the route information, we call `dplane_ctx_fini` to free the dplane context. However, this causes a crash because `dplane_ctx_fini` attempts to access the `intf_extra_list` which is not initialized.
To solve this issue, we need to initialize the `intf_extra_list` properly after allocating the dplane route context.
Signed-off-by: Carmine Scarpitta [carmine.scarpitta.94@gmail.com](mailto:carmine.scarpitta.94@gmail.com)

zebra: Fix crash when `dplane_fpm_nl` fails to process received routes

---

tests/.gitignore

This file is generated after `make check`.

tests: Ignore test_darr for git

---

pimd/pim_cmd_common.c

The cli "show ip pim nexthop json" gives the unicast RPF information. 
However it doesn't give PIM enable status on the nexthop interface.
Added pimEnabled field in this clis,
this will tell if PIM is enabled or not on the nexthop interface.
Example:
frr# show ip pim nexthop
Number of registered addresses: 1
Address    Interface  Nexthop
108.0.0.2  ens224     108.0.0.2
frr# show ip pim nexthop json
{
"108.0.0.2":{
"address":"108.0.0.2",
"nexthops":[
{
"interface":"ens224",
"pimEnabled":true,
"nexthop":"108.0.0.2"
}
]
}
}
frr# configure terminal
frr(config)# int ens224
frr(config-if)# no ip pim
frr(config-if)# end
frr# show ip pim nexthop json
{
"108.0.0.2":{
"address":"108.0.0.2",
"nexthops":[
{
"interface":"ens224",
"pimEnabled":false,
"nexthop":"108.0.0.2"
}
]
}
}
Closes #13441

pimd, pim6d: Added pimEnabled field in "show ip pim nexthop json" cli

---

bgpd/bgp_zebra.c
bgpd/bgp_zebra.h

bgp_zebra_tm_connect calls bgp_zebra_get_table_range which just used the global zclient.  Which of course still had us exposing the global zclient to read and drop important data from zebra.  This fixes commit 787c61e03c760ffdb422bfc44c72d83fb451e0c8

bgpd: Fix table manager to use the synchronous client

---

zebra/redistribute.c

zebra: adjust one debug info                                                                                                                                                 
Adjust one debug info, separate the ip address from it. Just like it is processed
in `redistribute_update()`.                                                         
Before:                                                                             
```                                                                                 
34:1375.75.75.75/32: Redist del: re 0x55c1112067e0 (0:static), new re 0x55c1112de7c0 (0:static)
```                                                                                 
After:                                                                              
``` …
```

zebra: adjust one debug info

---

isisd/isis_misc.c

No gmtime() allowed, not thread-safe, use gmtime_r().

isisd: replace gmtime with gmtime_r

---

tests/topotests/bgp_features/test_bgp_features.py

The changes allow the test to correctly pass in case the connection between two peers is be established in less than 0.5 seconds after the delayopen timer expires.
This fixes false negatives occurring during tests run on performant platforms (i.e. https://ci1.netdef.org/browse/FRR-PULLREQ2-TOPO3DEB10AMD64-12668/test/case/109021523)

tests: fix BGP delayopen timer expiration test

---

bgpd/bgp_attr.c

The total number of octets of the Sub-TLV Value field. The Sub-TLV Length field contains 1 octet if the Sub-TLV Type field contains a value in the range from 0-127. The Sub-TLV Length field contains two octets if the Sub-TLV Type field contains a value in the range from 128-255.

bgpd: Get 1 or 2 octets for Sub-TLV length (Tunnel Encap attr)

---

zebra/interface.c

The mpls configuration does not work when an interface is created after having applied the frr configuration. The below scenario illustrates:
> root@dut:~# modprobe mpls
> root@dut:~# zebra &
> [..]
> dut(config)# interface ifacenotcreated
> dut(config-if)# mpls enable
> dut(config-if)# Ctrl-D
> root@dut:~# ip li show ifacenotcreated
> Device "ifacenotcreated" does not exist.
> root@dut:~# ip li add ifacenotcreated type dummy
> 0
Fix this by forcing the mpls flag when the interface is detected.
> root@dut:~# cat /proc/sys/net/mpls/conf/ifacenotcreated/input
> 1

zebra: fix mpls config on ifaces created post frr

---

bgpd/bgp_fsm.c
bgpd/bgp_open.c
bgpd/bgp_open.h
bgpd/bgp_packet.c
bgpd/bgp_route.c
bgpd/bgp_updgrp.c
bgpd/bgp_updgrp.h
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

https://www.rfc-editor.org/rfc/rfc8810.html
Not relevant anymore. Use RFC'd version of ORF.

bgpd: Deprecate Prestandard Outbound Route Filtering capability

---

ospfd/ospf_lsa.c

In the function ```ospf_lsa_translated_nssa_new``` the newly created lsa is lock however, the return lsa from ```ospf_lsa_new``` already has a lock. Therefore removing the addition lock resolve the leak below.
```
ospf_basic_functionality.test_ospf_nssa#r3.asan.ospfd.5456
================================================================= ==5456==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 640 byte(s) in 5 object(s) allocated from:
#0 0x7f294f354a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7f294eeed562 in qcalloc ../lib/memory.c:105
#2 0x561a16004f60 in ospf_lsa_new ../ospfd/ospf_lsa.c:186
#3 0x561a160051a1 in ospf_lsa_new_and_data ../ospfd/ospf_lsa.c:205
#4 0x561a1600f21d in ospf_exnl_lsa_prepare_and_flood …
```

ospfd: fix lsa leak

---

doc/user/ospfd.rst
lib/libospf.h
ospfd/ospf_flood.c
ospfd/ospf_gr.c
ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_opaque.c
ospfd/ospf_packet.c
ospfd/ospf_vty.c
tests/topotests/ospfapi/test_ospf_clientapi.py

Add support for "[no] ip ospf capbility opaque" at the interface level with the default being capability opaque enabled. The command "no ip ospf capability opaque" will disable opaque LSA database exchange and flooding on the interface. A change in configuration will result in the interface being flapped to update our options for neighbors but no attempt will be made to purge existing LSAs as in dense topologies, these may received by neighbors through different interfaces.
Topotests are added to test both the configuration and the LSA opaque flooding suppression.

ospfd: Configurable interface-level 'capability opaque' support

---

bgpd/bgp_route.c

Fixes #13982. Currently the function `bgp_table_stats_single` leaks memory because the `json_object` won't get freed in the if condition. I moved the allocation after the if and Valgrind does not report a memory leak anymore.

bgpd: Fix memory leak by moving allocation of json object

---

mgmtd/mgmt_fe_adapter.c
mgmtd/mgmt_txn.c

mgmtd: adjust one unnecessary bool convert
It is unnecessary to do the bool calculation for expression

mgmtd: adjust one unnecessary bool convert

---

ospf6d/ospf6_flood.c
ospf6d/ospf6_gr.c
ospf6d/ospf6_gr_helper.c
ospf6d/ospf6_lsa.c
ospf6d/ospf6_lsa.h
ospf6d/ospf6_lsdb.c
ospf6d/ospf6_lsdb.h
ospf6d/ospf6_message.c
ospf6d/ospf6_neighbor.c
tests/ospf6d/test_lsdb.c

Make the ospf6_lsa_unlock take the same parameters that the ospf_lsa_unlock does to make it consistent and to also ensure that no-one can make the mistake of getting the pointer cleared up.

ospf6d: Convert ospf6_lsa_unlock to a better api

---

pimd/pim_ifchannel.c

Consider LHR in `SSM` case, and its `oif` goes from up to down. As the `oif` changes down, the `channel_oil` is still wrongly reserved with `PIM_OIF_FLAG_PROTO_STAR` protocol.
The mechanism of adding `STAR` protocol for <S,G> entry without `oif` is introduced by commit `2164ed5`/`71056a6`, which should be only used for ASM.
PR #13699 wants to clean this `STAR` protocol after the `oif` becomes up again. That case is for SSM, as the `oif` changes down, the `channel_oil` should be removed, so the fix of that PR is wrong.
In `pim_ifchannel_delete()` we should check the `ch->parent` before that mechanism of adding `STAR` protocol. If `ch->parent` is NULL, we should skip that mechanism with SSM.
Fixes #13696

pimd: Fix wrong protocol for SSM

---

bgpd/bgp_vty.c

Closes https://github.com/FRRouting/frr/issues/13988

bgpd: Free temporary memory after using argv_concat()

---

lib/routemap_northbound.c
tests/topotests/bgp_route_map_on_match_next/r1/bgpd.conf
tests/topotests/bgp_route_map_on_match_next/r1/zebra.conf
tests/topotests/bgp_route_map_on_match_next/r2/bgpd.conf
tests/topotests/bgp_route_map_on_match_next/r2/zebra.conf
tests/topotests/bgp_route_map_on_match_next/test_bgp_route_map_on_match_next.py

Currently, "on-match (next|goto)" only works if already present in a route-map entry when the route-map is applied to the routes. However, if the command is added to an existing route-map entry, the route-map is not reapplied to the routes in order to accommodate the changes. And service restart is needed. The problem is that setting the command doesn't signal about the change to the listener (i.e. to a routing daemon).
With this fix, signal to the listener about addition of "on-match (next|goto)" to a route-map entry.
-----
In order to reproduce this problem, you should add `on-match` to an existing route-map entry and see if there will be any effect of this on the routes.
For example:
1. R1 and R2 has a BGP session established
2. R2 receives a prefix from R1
3. R2 creates the following …

lib: fix on-match when added to existing route-map entry

---

bgpd/bgp_nht.c
zebra/interface.c

- zebra: Fix wrong vrf change procedure
Currently the vrf change procedure for the deleted interface is after its deletion, it causes problem for upper daemons.
Here is the problem of `bgp`:
After deletion of one **irrelevant** interface in the same vrf, its `ifindex` is set to 0. And then, the vrf change procedure will send "ZEBRA_INTERFACE_DOWN" to `bgpd`.
Normally, `bgp_nht_ifp_table_handle()` should igore this message for no correlation. However, it wrongly matched `ifindex` of 0, and removed the related routes for the down `bnc`.
Adjust the location of the vrf change procedure to fix this issue.
- bgpd: Add an assert for nht procedure
`bnc->ifindex` should not be with 0 ( IFINDEX_INTERNAL ), so add an
assert to make it safe.

zebra: Fix wrong vrf change procedure

---

lib/mgmt_fe_client.c
lib/mgmt_fe_client.h
lib/vty.c
lib/vty.h
mgmtd/mgmt_fe_adapter.c
tests/topotests/mgmt_config/r1/frr.conf
tests/topotests/mgmt_config/test_regression.py
vtysh/vtysh.c
vtysh/vtysh_config.c

vtysh: track and fix file-lock use in the workaround from 2004
There's a workaround in the code from a bug from back in 2004, it ends
and re-enters config mode anytime an `exit` is done from a level below
the top-level config node (e.g., from a `router isis` node). We need to
re-enter config mode with or without a lock according to how we actually
entered it to begin with.
fixes #13920
lib: mgmtd: only clear pending for the in-progress command
The lock/unlocks are being done short-circuit so they are never pending;
however, the handling of the unlock notification was always resuming the command
if pending was set. In all cases pending is set for another command. For example
implicit commit locks then when notified its done unlocks which was clearing the
set-config pending flag and …

fix double lock bug and cmd resume early bugs

---

bgpd/bgpd.c

When running bgp_always_compare_med, I am frequently seeing a crash After running with valgrind I am seeing this and a invalid write immediately after this as well.
==311743== Invalid read of size 2
==311743==    at 0x4992421: route_map_counter_decrement (routemap.c:3308)
==311743==    by 0x35664D: peer_route_map_unset (bgpd.c:7259)
==311743==    by 0x306546: peer_route_map_unset_vty (bgp_vty.c:8037)
==311743==    by 0x3066AC: no_neighbor_route_map (bgp_vty.c:8081)
==311743==    by 0x49078DE: cmd_execute_command_real (command.c:990)
==311743==    by 0x4907A63: cmd_execute_command (command.c:1050)
==311743==    by 0x490801F: cmd_execute (command.c:1217)
==311743==    by 0x49C5535: vty_command (vty.c:551)
==311743==    by 0x49C7459: vty_execute (vty.c:1314)
==311743==    by 0x49C97D1: …

bgpd: Prevent use after free

---

tests/lib/test_grpc.cpp

was trying to build test_grpc.cpp for validating some grpc operations and found that it was not compiling in the latest master, on ubuntu 22.04 .
```
Compilation Error:
CCLD     tests/lib/cli/test_commands
/usr/bin/ld: lib/.libs/libfrr.a(libfrr.o):/root/frr/frr-vanilla/lib/libfrr.c:37: multiple definition of `_hook_frr_late_init'; tests/lib/test_grpc-test_grpc.o:(.data.rel.local+0x0): first defined here
/usr/bin/ld: lib/.libs/libfrr.a(libfrr.o):/root/frr/frr-vanilla/lib/libfrr.c:41: multiple definition of `_hook_frr_fini'; tests/lib/test_grpc-test_grpc.o:(.data.rel.local+0x20): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:8929: tests/lib/test_grpc] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory …
```

test_grpc.cpp Fix Compilation Error and RuntimePath for finding grpc.so

---

bgpd/bgp_route.c

When switching `router bgp`, `no router bgp` and doing redistributions, we should ignore this action, otherwise memory leak happens:
```
Indirect leak of 400 byte(s) in 2 object(s) allocated from:
0 0x7f81b36b3a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
1 0x7f81b327bd2e in qcalloc lib/memory.c:105
2 0x55f301d28628 in bgp_node_create bgpd/bgp_table.c:92
3 0x7f81b3309d0b in route_node_new lib/table.c:52
4 0x7f81b3309d0b in route_node_set lib/table.c:61
5 0x7f81b330be0a in route_node_get lib/table.c:319
6 0x55f301ce89df in bgp_redistribute_add bgpd/bgp_route.c:8907
7 0x55f301dac182 in zebra_read_route bgpd/bgp_zebra.c:593
8 0x7f81b334dcd7 in zclient_read lib/zclient.c:4179
9 0x7f81b331d702 in event_call lib/event.c:1995
10 0x7f81b325d597 in frr_run …
```

bgpd: Do not try to redistribute routes if we are shutting down

---

zebra/table_manager.c
zebra/zapi_msg.c
zebra/zebra_mpls.c
zebra/zebra_mpls_vty.c
zebra/zebra_pw.c
zebra/zebra_vty.c
zebra/zebra_vxlan.c

Though default vrf must be non-NULL, there are some places to use unnecessary
check or assert. Let them unify the form - remove the redundant things.

zebra: remove unnecessary check for default vrf

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_vty.c

problem:
In CLI config codeflow there are memory leaks in failure scenario
Fix:
Code changes are done to free ecommunity

bgpd: fix bgp evpn cli memory leaks.

---

tools/frr-reload.py

When reloading the following config:
```
router ospf6
area 0 range 2001:db8::/32 advertise
exit
!
interface eth0
ipv6 ospf6 area 0
exit
```
frr-reload.py doesn't execute "exit" commands. Because of that, it tries
to execute "interface eth0" inside the "router ospf6" context and fails.
To always execute all commands from the correct context, frr-reload.py
should properly exit from every entered node.
Fixes https://github.com/FRRouting/frr/issues/10132

tools: always append "exit" in frr-reload.py

---

bgpd/bgp_nht.c

Assuming field 'ifindex_ipv6_ll' is not equal to field 'ifindex', then nhop_found is just a garbage, let's avoid that.

bgpd: Initialize bgp_nht_ifp_table_handle() bools

---

bgpd/bgp_aspath.c
bgpd/bgp_aspath.h
bgpd/bgp_filter.c
bgpd/bgp_filter.h
bgpd/bgp_routemap.c
doc/user/bgp.rst
tests/topotests/bgp_set_aspath_exclude/test_bgp_set_aspath_exclude.py

A route-map applied on incoming BGP updates is not able
to exclude the unwanted as segments, based on an AS path
access-list.
The below configuration illustrates the case:
neighbor 192.168.1.2 route-map rule_2 in
bgp as-path access-list RULE permit ^65
route-map rule_2 permit 10
set as-path exclude as-path-access-list RULE
```
BGP routing table entry for 10.10.10.10/32, version 13
Paths: (1 available, best https://github.com/FRRouting/frr/pull/1, table default)
Advertised to non peer-group peers:
192.168.10.65
65000 1 2 3 123
192.168.10.65 from 192.168.10.65 (10.10.10.11)
Origin IGP, metric 0, valid, external, best (First path received)
Last update: Mon Apr 25 10:39:50 2022
```
After:
```
do show ip bgp 10.10.10.10/32
BGP …
```

bgpd: add set as-path exclude acl-list command

---

pimd/pim_instance.c

`pim_if_create_pimreg()` need use the `mroute_socket`, so adjust the order. First call `pim_mroute_socket_enable()`, then call `pim_if_create_pimreg()`.

pimd: Fix wrong creating order for pimreg

---

zebra/zebra_evpn_neigh.c

When the MAC address of the neighbor changes, a possible crash issue may occur.
In the zebra_evpn_local_neigh_update function, the value of old_zmac (n->mac) will be updated to the new MAC address when the neighbor's MAC address changes. The pointer to the memory that this pointer points to may be released in the zebra_evpn_local_neigh_deref_mac function. This will cause old_zmac to become a dangling pointer. Accessing this dangling pointer in the zebra_evpn_ip_inherit_dad_from_mac function below will cause the zebra process to crash.
To fix this issue, the ZEBRA_MAC_DUPLICATE flag should be retrieved before old_zmac is released and used in the zebra_evpn_ip_inherit_dad_from_mac function.

zebra:fix a zebra crash issue caused by mac change

---

tests/topotests/lib/pim.py

When JoinState is not passed to API it is expected to be in Joined state, 
there was a minor bug in API, where it was printing JoinState as None, 
which is default value in API. Updated value to print Joined when 
verification fails.

tests: Update join state in verify_upstream_iif API

---

zebra/zebra_vxlan.c

When route_next return node, it has lock the node. if return or break loop, should unlock node.Otherwise, memory leaks when the node is deleted.

zebra:unlock node after route_next

---

bgpd/bgp_zebra.c
doc/user/pbr.rst
lib/pbr.h
pbrd/pbr_map.c
pbrd/pbr_map.h
pbrd/pbr_vty.c
pbrd/pbr_zebra.c
tests/topotests/pbr_topo1/test_pbr_topo1.py
zebra/zapi_msg.c
zebra/zebra_dplane.c
zebra/zebra_pbr.c

Supersedes PRs #13514, #9705 
by agreement between joshuawerner@mitre.org and paulz@labn.net 
NB: existing PR can not be transferred to new person
Add VTY and initial Zebra support for VLAN filters. 
match ip-protocol (was only tcp|udp, now any value in /etc/protocols)
match pcp (0-7)
match vlan (1-4094)
match vlan (tagged|untagged|untagged-or-zero)
Since the kernel PBR facilities do not provide any way of matching on VLAN fields, another provider will be required (e.g. netfilter). This PR includes changes from previous PRs 9705 by Eli Baum and 13514 by Josh Werner.
Update plan for this PR:
1. Label with no-merge; verify CI passes; fix if needed
2. reorganize/squash commits for clarity; remove no-merge
3. code review
Related future PRs planned:
a. 2/3 common ZAPI PBR encode/decode
b. 3/3 …

pbrd: 1/3: add vty support for vlan filtering and send to zebra

---

pimd/pim6_mld.c
pimd/pim6_mld.h

While running MLD conformance test 9.2 core is getting generated.
Test setps:
1. ANVL: Listen (for upto <GeneralQueryRecvWaitTime> seconds) on <AIface-0>.
2. DUT: Send MLD General Query Message.
3. ANVL: Send MLD Report Message to <DIface-0> containing: • IPv6 Source Address field set to link-local IPv6 Address of HOST-1 • IPv6 Destination Address field set to <McastAddrGroup> • MLD Multicast Address field set to <McastAddrGroup>.
4. ANVL: Wait for <ProcessTime> seconds for DUT to process and add <Mcas- tAddrGroup> to its Multicast Address list.
5. ANVL: Send MLD General Query Message to <DIface-0> containing: • IPv6 Source Address field set to link-local IPv6 Address of RTR-1 which is numerically less than the link-local IPv6 unicast address of <DIface-0> • IPv6 Destination Address field …

pim6d: Fixing core while running MLD conformance test.

---

lib/prefix.c
lib/prefix.h

Reported Warning:
Compare member by member to check object equality
RCA:
struct evpn_addr contains padding
Authored-by: Kantesh Mundaragi <kmundaragi@vmware.com>

bgpd: Fix coverity for EVPN

---

doc/user/ospfd.rst
lib/libospf.h
ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_lsa.c
ospfd/ospf_route.c
ospfd/ospf_vty.c
tests/topotests/ospf_prefix_suppression/r1/frr.conf
tests/topotests/ospf_prefix_suppression/r2/frr.conf
tests/topotests/ospf_prefix_suppression/r3/frr.conf
tests/topotests/ospf_prefix_suppression/test_ospf_prefix_suppression.py

Implement OSPF prefix-suppression as specified RFC 6860:
1. Implement interface level configuration of prefix-suppression including interface address configuration.
2. Suppression advertisement of stub links in router-LSAs with prefix-suppression enabled. 
3. Advertisement of a host-mask in the network-LSA for interfaces with prefix-suppression enabled. 
4. Implement new topotest which includes all the OSPF interface types.

ospfd: Implement OSPF prefix-suppression as specified in RFC 6860

---

doc/user/bfd.rst

Fixes #13933 .
`label` command is already gone ( https://github.com/FRRouting/frr/commit/3e4e7405ff2d9373c4e43550fa37c43fd06504d5 ) and now we are going to remove all label references.
---
Further explanation: `label` feature still exists for the control socket, however with new northbound the control socket should be deprecated in favor of gRPC/other yang tools.

doc: remove BFD label command references

---

bgpd/bgp_advertise.c
bgpd/bgp_advertise.h
bgpd/bgp_fsm.c
bgpd/bgp_io.c
bgpd/bgp_updgrp.c
bgpd/bgp_updgrp.h
bgpd/bgpd.c
bgpd/bgpd.h
bgpd/rfapi/rfapi.c
bgpd/rfapi/vnc_zebra.c

See individual Commits, but we were seeing issues at scale with bgp taking up too much memory when you have something like 4k peers.  More commits to probably come.

Remove unused memory allocations associated with bgp

---

zebra/zebra_vty.c
zebra/zebra_vxlan.c

1) zebra:non pretty json output for evpn route
Currently, json output of evpn route command are no pretty format.
This is an extremely expensive operation at high VNI scale
EVPN json non-pretty command support added:
```
show evpn mac vni <vni-id> detail json
show evpn vni detail json
```
Currently, json output of show ip route command are no pretty format.
This is an extremely expensive operation at high scale (with high number of routes with many paths).
2) Zebra json non-pretty command support added:
```
show ip route json
```

zebra: non pretty json format for rib and evpn operational commands

---

bgpd/bgp_route.c

Currently, json output of show BGP commands are no pretty format.
This is an extremely expensive operation for huge scale (lots of routes with lots of paths).
BGP json non-pretty commands support added:
```
show bgp neighbors <nbr-id> advertised-routes json
show bgp neighbors <nbr-id> received-routes json
show bgp neighbors <nbr-id> advertised-routes detail json
show bgp neighbors <nbr-id> received-routes detail json
```

bgpd: non pretty json output for neighbor routes

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

The last_reset_cause is a plain old BGP_MAX_PACKET_SIZE buffer that is really enlarging the peer data structure.  Let's just copy the stream that failed and only allocate how ever much the packet size actually was.  While it's likely that we have a reset reason, the packet typically is not going to be 65k in size.  Let's save space.

bgpd: The last_reset_cause in the peer structure is too large

---

lib/nexthop.c
zebra/zebra_rib.c

Two changes for debug:
1. Add a field to indicate its vrf for nexthop.  When the interface changes vrf, we can't easily know the vrf of this nexthop according to current log.
2. Add a field to indicate operation type.  We can't know whether to add or remove route according to current log.
Before:
```
zebra_nhg_increment_ref: nhe 0x555623eb82c0 (76[if 6]) 0 => 1
zebra_interface_nhg_reinstall install nhe 75[77.75.1.75 if 6] nh type 3 flags 0x1
Route 77.75.1.0/24(8) queued for processing into sub-queue Early Route Processing
Route 77.75.1.0/24(8) queued for processing into sub-queue Early Route Processing
```
After:
```
zebra_nhg_increment_ref: nhe 0x555623eb82c0 (76[if 6 vrfid 9]) 0 => 1
zebra_interface_nhg_reinstall install nhe 75[77.75.1.75 if 6 vrfid 8] nh type 3 flags 0x1
Route …
```

zebra: add several fields for debug

---

zebra/zebra_nhg.c

PR#13413 introduces reinstall mechanism, but there is problem with the route leak scenario.
With route leak configuration: ( `x1` and `x2` are binded to `vrf1` )
```
vrf vrf2
ip route 75.75.75.75/32 77.75.1.75 nexthop-vrf vrf1
ip route 75.75.75.75/32 77.75.2.75 nexthop-vrf vrf1
exit-vrf
```
Firstly, all are ok.  But after `x1` is set down and up ( The interval between the down and up operations should be less than 180 seconds. ) , `x1` is lost from the nexthop group:
```
anlan# ip nexthop
id 121 group 122/123 proto zebra
id 122 via 77.75.1.75 dev x1 scope link proto zebra
id 123 via 77.75.2.75 dev x2 scope link proto zebra
anlan# ip route show table 2
75.75.75.75 nhid 121 proto 196 metric 20
nexthop via 77.75.1.75 dev x1 weight 1
nexthop via 77.75.2.75 dev x2 weight 1
anlan# ip link set …
```

zebra: fix nhg out of sync between zebra and kernel

---

tests/lib/test_nexthop_iter.c

GCC/clang warns about using `strncpy` in such a way that it does not copy the null byte of a string; as implemented it was fine, but to fix the warning, just use `strlcat` which was purpose made for the task being accomplished here.
Fixes #6817

tests: fix strncpy warning

---

pbrd/pbr_vty.c

Should address this issue:
```
*** CID 1566396:  Null pointer dereferences  (FORWARD_NULL)
/pbrd/pbr_vty_clippy.c: 163 in pbr_map_match_vlan_tag()
157     #if 0 /* anything that can fail? */
158             if (_failcnt)
159                     return CMD_WARNING;
160     #endif
161     #endif
162
>>>     CID 1566396:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "tag_type" to "pbr_map_match_vlan_tag_magic",
which dereferences it.
163             return pbr_map_match_vlan_tag_magic(self, vty, argc, argv,
no, tag_type);
164     }
```

pbrd: fix coverity issue in pbr_map_match_vlan_tag

---

ospfd/ospf_asbr.c
ospfd/ospf_asbr.h
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Currently, when redistribution of routes was configured, external LSAs were already advertised to peers, and then default-metric is changed, external LSAs refresh will not occur. In other words, the peers will not receive the refreshed external LSAs with the new metric.
With this fix, changing default-metric will cause external LSAs to be refreshed and flooded.
There is a similar task to refresh external LSAs when NSSA settings are changed. And there is a function that accomplishes it - `ospf_schedule_asbr_nssa_redist_update()`. Since the function does the general work of refreshing external LSAs and is not specific to NSSA settings, the idea is to give it a more general name and call it when default-metric changes in order to fix the problem.

ospfd: fix default-metric change if external LSAs already sent

---

lib/zclient.c
pbrd/pbr_zebra.c

Fix a couple of style warnings introduced by recent PR 14050.

lib,pbrd: clean up style issues

---

lib/elf_py.c

David rightly pointed out that having a test for fd > 0 would technically not be right, but not wrong for this portion of the code since we know that we would never get a fd = 0 in this section. In any event let's make coverity happy and move on with our life.

lib: Fix elf_py.c for coverity

---

bfdd/bfd_packet.c
bfdd/bfdd_vty.c

Add parameters to the "show bfd peers json" command to display interface and type of BFD session.
Add BFD debug flag around log.
Signed-off-by:Lynne Morrison <lynne.morrison@ibm.com>

bfdd: add additional parameters to json command

---

tools/frr-reload.py

This PR fixes a problem in `frr-reload.py` that causes it to fail to remove key chains from the configuration.
How To Reproduce
---
1. Configure a key chain with a key:
```
key chain test
key 123
key-string test
exit
exit
```
2. Load a configuration without the key chain and `frr-reload` will try this:
```
frr-reload.py --test /tmp/1
Lines To Delete
===============
no key chain test
key chain test
no key 123
exit
frr-reload.py --reload /tmp/1                
"key chain test --  no key 123 -- exit" we failed to remove this command
Can't find key 123
```

tools: fix key chain reload removal

---

bgpd/bgp_clist.c
bgpd/bgp_clist.h
bgpd/bgp_routemap.c
bgpd/bgp_routemap_nb_config.c
doc/user/routemap.rst
lib/command.h
lib/routemap.h
lib/routemap_cli.c
tests/topotests/bgp_extcomm_list_delete/r1/bgpd.conf
tests/topotests/bgp_extcomm_list_delete/r1/zebra.conf
tests/topotests/bgp_extcomm_list_delete/r2/bgpd.conf
tests/topotests/bgp_extcomm_list_delete/r2/zebra.conf
tests/topotests/bgp_extcomm_list_delete/test_bgp_extcomm-list_delete.py
yang/frr-bgp-route-map.yang

Add a **"set extended-comm-list <EXTCOMM_LIST_NAME> delete"** command to **strip** BGP extended communities.

bgp: add set BGP extended community for deletion command

---

zebra/zebra_nhg.c

When frr.service is going down(restart or stop), zebra core can be seen.
Sequence of events leading to crash:
Increments of nhe refcnt:
- Upper level creates a new nhe(say NHE1) —> nhe->refcnt=1
- Two RE’s (Say RE1 & RE2) associate with NHE1 —> nhe->refcnt = 3
Decrements of nhe refcnt:
- BGP sends a zapi msg to zebra to delete NHG. —> nhe->refcnt = 2
- RE1 is queued for delete in META-Q
- As zebra is dissociating with its clients, zebra_nhg_score_proto() is invoked -> nhe->refcnt=1
- RE2 is no more associated with the NHE1 —>nhe->refcnt=0 & hence NHE IS FREED
- Now RE1 is dequeued from META-Q for processing the re delete. —> At this point re->nhe is pointing to freed pointer. CRASH CRASH!!!!
Fix:
- When upper client sends a zapi msg to delete nhg(zread_nhg_del), we mark nhe->flags as …

zebra: fix nhe refcnt when frr service goes down

---

ospfd/ospf_vty.c

Currently, when changing ABR type on a working router from shortcut/standard to cisco/ibm or vice versa, that will lead to LSA Type 1 update, SPF recalculation, and OSPF RIB update. However, when changing ABR type from standard to shortcut or vice versa, OSPF RIB update will not occur. In other words, changing ABR type between standard and shortcut will not result in inter-area routes addition/deletion.
The problem is that changing ABR type between standard and shortcut doesn't cause ABR/ASBR internal flags to update. And if the flags are unchanged, `ospf_check_abr_status()` will not initiate SPF recalculation.
With this fix, when ABR type is changed between standard and shortcut, the command initiates SPF recalculation.

ospfd: fix changing ABR type between standard and shortcut

---

bgpd/bgp_attr.c

Problem:
Few of the Update message error handling methods in RFC 4271 are updated with RFC 7606.
According to the RFC 7606, the error handling for the core attributes
has been relaxed to follow 'treat-as-withdraw' approach than session resets.
However, BGP session resets on encountering any malformed core attribute.
RCA:
On encountering any attribute error for core attributes in update message, the error handling is set to 'treat as withdraw' and further parsing of the remaining attributes is skipped. But the stream pointer is not being correctly adjusted to point to the next NLRI field skipping the rest of the attributes. This leads to incorrect parsing of the NLRI field, which causes BGP session to reset.
Fix:
The stream pointer offset is rightly adjusted to point to the NLRI field …

bgpd: Fix for session reset issue caused by malformed core attributes  in update message

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
tests/topotests/bgp_dynamic_capability/r1/bgpd.conf
tests/topotests/bgp_dynamic_capability/r1/zebra.conf
tests/topotests/bgp_dynamic_capability/r2/bgpd.conf
tests/topotests/bgp_dynamic_capability/r2/zebra.conf
tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_software_version.py

This is the first PR of the series to be handled with upcoming PRs for dynamic capability. We have to cover all of the supported or at least crucial ones (graceful restart, addpath) dynamically.

bgpd: Handle software version capability dynamicaly

---

staticd/static_vty.c

When displaying the configuration, the order of nexthop-vrf is wrong, because the default VRF is not displayed, but still compared as the word "default". Therefore it is placed in the middle of the list instead of always being the first one.
Before the fix:
```
ip route 1.1.1.0/24 2.2.2.2 nexthop-vrf ccc
ip route 1.1.1.0/24 2.2.2.2
ip route 1.1.1.0/24 2.2.2.2 nexthop-vrf eee
```
After the fix:
```
ip route 1.1.1.0/24 2.2.2.2
ip route 1.1.1.0/24 2.2.2.2 nexthop-vrf ccc
ip route 1.1.1.0/24 2.2.2.2 nexthop-vrf eee
```

staticd: fix comparison of nexthop-vrf

---

tests/topotests/bgp_addpath_best_selected/r5/bgpd.conf
tests/topotests/bgp_addpath_best_selected/r6/bgpd.conf
tests/topotests/bgp_evpn_vxlan_macvrf_soo_topo1/PE1/bgpd.conf
tests/topotests/bgp_evpn_vxlan_svd_topo1/PE1/bgpd.conf
tests/topotests/bgp_evpn_vxlan_topo1/PE1/bgpd.conf

BGP: [SHWNK-NWT5S][EC 100663304] No such command on config line 2:  timers 3 10

tests: Use a correct syntax for defining keepalive/hold timers

---

bgpd/bgp_main.c
bgpd/bgp_packet.c
bgpd/bgp_zebra.c
bgpd/bgpd.h
doc/user/bgp.rst
doc/user/zebra.rst
lib/zclient.c
lib/zclient.h
zebra/main.c
zebra/zapi_msg.c
zebra/zebra_router.c
zebra/zebra_router.h
zebra/zebra_vty.c

Allow zebra operators to specify if the dataplane can accept a v6 route with v4 nexthops embedded in the v6 nexthop.  Allow this to pass up to interested parties (well bgp at the moment ) and then have bgp make decisions about using the v6 address family when there are no v6 addresses on the interface based upon zebra having the ability to actually install the v6 nexthop with the embedded v4 address in it.  Finally allow bgp to allow this behavior when not using zebra at all.

V6 v4 nexthops

---

zebra/zebra_dplane.c
zebra/zebra_dplane.h

Changes the PBR-specific dataplane context to use the lib/pbr.h common PBR structures instead of replicating all of the match/action fields individually. Adds an accessor to get the entire structure. This change will enable the dataplane module interface to stay up-to-date with any PBR field changes without the need to add more per-field accessors.

zebra: zebra_dplane.[ch]: use pbr common struct in ctx

---

vtysh/vtysh_config.c

vtysh is not supposed to show empty interface node in running config, however the corresponding check is broken and empty nodes are shown.
P.S. This is broken for 2 years already (since my 4b639f996759eef388c42ca657a520de693ac6fc), so maybe it's better to remove the check completely and keep the current behavior instead of restoring the old one. Looking for comments from the community.

vtysh: fix checking empty interface node

---

bgpd/bgp_evpn_vty.c

The usage of bgp_vrf does not need to be tested
at this point since it's already been derefed in all paths to this point.

bgpd: bgp_vrf is already deref'ed in all paths

---

ospfd/ospf_ti_lfa.c

Coverity is complaining that listnode can return a NULL value and thus FRR could derefence the returned value. Since this is not crashing we know that this is not happening in the wild.  Let's make this an assert or check that it is legal to use the value.

ospfd: Ensure listnode returns are usable

---

bgpd/bgp_aspath.c
bgpd/bgp_aspath.h
bgpd/bgp_routemap.c
doc/user/bgp.rst
tests/topotests/bgp_set_aspath_replace/test_bgp_set_aspath_replace.py

A route-map applied on incoming BGP updates is not able
to replace an unwanted as segments by another one.
unwanted as segment are based on an AS path access-list.
The below configuration illustrates the case:
neighbor 192.168.1.2 route-map rule_2 in
bgp as-path access-list RULE permit ^65
route-map rule_2 permit 10
set as-path replace as-path-access-list RULE 6000
```
BGP routing table entry for 10.10.10.10/32, version 13
Paths: (1 available, best https://github.com/FRRouting/frr/pull/1, table default)
Advertised to non peer-group peers:
192.168.10.65
65000 1 2 3 123
192.168.10.65 from 192.168.10.65 (10.10.10.11)
Origin IGP, metric 0, valid, external, best (First path received)
```
After:
```
do show ip bgp 10.10.10.10/32 …
```

  bgpd: add set as-path replace acl-list command 

---

lib/bitfield.h

Use FRR mem api instead of raw realloc() in bitfield module.

libs: use XREALLOC in bitfield lib module

---

bgpd/bgp_labelpool.c

Fix some weird indentation in the bgp labelpool module; indentation/space changes only.

bgpd: fix whitespace/indent in bgp_labelpool module

---

bgpd/bgp_evpn.c

Found some code where bgp was not unlocking the dest and rd_dest when walking the tree attempting to
find something to install.

bgpd: evpn code was not properly unlocking rd_dest

---

zebra/zebra_fpm_netlink.c

For now, when zebra send msg to fpm client, it doesn't handle duplicated nexthops especially, which means if zebra has a route with NUM1 recursive nexthops, each resolved to the same NUM2 connected nexthops, it will send to fpm client a route with NUM1*NUM2 nexthops. But actually there are only NUM2 useful nexthops, the left NUM1*NUM2-NUM2 nexthops are all  duplicated nexthops. By the way, zebra has duplicated nexthop remove logic when sending msg to kernel.
Add duplicated nexthop remove logic to zebra when sending msg to fpm client.

zebra: remove duplicated nexthops when sending fpm msg

---

zebra/redistribute.c
zebra/zebra_nhg.c
zebra/zebra_routemap.c
zebra/zebra_routemap.h

The `struct nh_rmap_obj` in zebra being used for routemaps was copying lots of individual fields.  Let's just cut to the chase and store and use the re instead.
Found a couple of bugs:
a) import table was using the vrf of the route -vs- the vrf of the nexthop and as such a import table with a cross vrf nexthop would never be imported.
b) metric was being ignored and as such in some cases zebra would never match on a metric if we passed it in to use.  Let's just allow zebra to match on the metric.
This also sets up a future changes to allow other match requirements against the re( see the routemap work that ali-baba is doing to not install into the kernel.  This should be foundational for their work.

Zebra routemap cleanup

---

doc/developer/workflow.rst

See the documentation update, but system() calls and it's ilk block the processing of SIGINT and they are not properly handled as a result leading to shutdown issues where one or more daemons never stop.
See aa530b627de8d1d8c11e4455f3e97a8c2e045281 as an example of system call usage removed from the system.

doc: Prohibit usage of `system()` calls in FRR

---

bgpd/bgp_attr.c

Below two cases of update message error handling have been fixed as part of this commit in conformance to RFC7606.
Issue 1:
As per RFC7606 section 4,
when the total attribute length value is in conflict with the enclosed attribute length, treat-as-withdraw approach must be followed. However, notification is being sent out for this case currently, that leads to session reset.
Fix:
The handling has been updated to conform to treat-as-withdraw approach only for EBGP case. For IBGP, since we are not following treat-as-withdraw approach for any of the error handling cases, the existing behavior is retained for the IBGP.
Issue2:
As per RFC7606 section 3g,
g.  If the MP_REACH_NLRI attribute or the MP_UNREACH_NLRI [RFC4760]
attribute appears more than once in the UPDATE message, then a …

bgpd: Few fixes for Update message error handling of malformed attribute

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
eigrpd/eigrp_hello.c
eigrpd/eigrp_update.c
lib/bfd.c
lib/event.c
lib/frrevent.h
lib/wheel.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_intra.h
ospf6d/ospf6_lsa.c
ospf6d/ospf6_lsdb.c
ospf6d/ospf6_message.c
ospf6d/ospf6_nssa.c
ospfd/ospf_ism.h
ospfd/ospf_lsa.c
ospfd/ospf_nsm.h
pimd/pim6_mld.c
tests/lib/test_segv.c
zebra/zebra_gr.c

This is a proposal to include an event ptr-to-ptr in the event_execute() api call, like the various schedule api calls. This would allow the execute() api to cancel an existing scheduled task if that task is being executed inline. If there's agreement that this is a reasonable change, I'll continue implementing the 'cancel' code (and add a test).
At this point, I'm not proposing examining all of the code paths that use 'execute' - other than to add the argument and compile. I'd like to make the lib change first, and then over time we can review the various daemons' use of the apis and decide what changes to make.

* : include event ptr in event_execute api

---

pimd/pim_msg.c
pimd/pim_nht.c
pimd/pim_upstream.c
pimd/pim_vxlan.c
pimd/pim_vxlan.h
tests/topotests/bgp_evpn_mh/leaf1/evpn.conf
tests/topotests/bgp_evpn_mh/leaf1/pim.conf
tests/topotests/bgp_evpn_mh/leaf1/zebra.conf
tests/topotests/bgp_evpn_mh/leaf2/evpn.conf
tests/topotests/bgp_evpn_mh/leaf2/pim.conf
tests/topotests/bgp_evpn_mh/leaf2/zebra.conf
tests/topotests/bgp_evpn_mh/spine1/evpn.conf
tests/topotests/bgp_evpn_mh/spine1/zebra.conf
tests/topotests/bgp_evpn_mh/spine2/evpn.conf
tests/topotests/bgp_evpn_mh/spine2/pim.conf
tests/topotests/bgp_evpn_mh/spine2/zebra.conf
tests/topotests/bgp_evpn_mh/test_evpn_mh.py
tests/topotests/bgp_evpn_mh/torm11/pim.conf
tests/topotests/bgp_evpn_mh/torm12/pim.conf
tests/topotests/bgp_evpn_mh/torm21/pim.conf
tests/topotests/bgp_evpn_mh/torm22/pim.conf

1)  Make the bgp_evpn_mh test a 3 level clos to more realistically see flows setup
2) Prevent a S,G RPT prune being sent in some cases when a pim vxlan S,G is being used
3) Send immediate Null Registers when pim vxlan is being setup when routing for the RP becomes available if after vxlan S,G creation.
4) Intentionally rescan oil when RPF fails at S,G creation time.  Else it never gets rescanned and 
5) Add some more debugs

Do not look into pim's eyes, pim gets mad

---

bgpd/bgp_route.c

Should address this issue:
** CID 1566843:  Uninitialized variables  (UNINIT) /bgpd/bgp_route.c: 6754 in bgp_static_set()
6748                            bgp_static->backdoor = backdoor;
6749                            bgp_static->valid = 0;
6750                            bgp_static->igpmetric = 0;
6751                            bgp_static->igpnexthop.s_addr = INADDR_ANY;
6752                            bgp_static->label_index = label_index;
6753                            bgp_static->label = label;
>>>     CID 1566843:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value prd.
6754                            bgp_static->prd = prd;
6755
6756                            if (rmap) {
6757                                    XFREE(MTYPE_ROUTE_MAP_NAME,
6758 …

bgpd: fix coverity issue in bgpd

---

zebra/interface.c

This commit addresses a memory leak issue detected by ASan associated with the member lists (mbr_zifs) of bond interfaces.
Previously, the member lists were not properly deleted during interface deletion, leading to memory leaks.
A call to list_delete() is made when interface is deleted.
```
./bgp_evpn_mh.test_evpn_mh/torm12.zebra.asan.662047:Direct leak of 80 byte(s) in 2 object(s) allocated from:
./bgp_evpn_mh.test_evpn_mh/torm12.zebra.asan.662047-    #0 0x7fe7a5b9d037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
./bgp_evpn_mh.test_evpn_mh/torm12.zebra.asan.662047-    https://github.com/FRRouting/frr/pull/1 0x7fe7a57431ee in qcalloc lib/memory.c:105
./bgp_evpn_mh.test_evpn_mh/torm12.zebra.asan.662047- …
```

zebra: Delete the 'mbr_zifs' list in the if_zebra_delete_hook function 

---

bgpd/bgp_vty.c

Before the patch:
```
donatas-laptop(config-router)# bgp confederation
identifier  AS number in plain  <1-4294967295> or dotted <0-65535>.<0-65535> format
peers       Peer ASs in BGP confederation
```

bgpd: Fix CLI descriptions for `bgp confederation identifier`

---

lib/thread.c
vtysh/vtysh_config.c

Manual backport, replacing https://github.com/FRRouting/frr/pull/14209.

lib: Allow unsetting walltime-warning and cpu-warning

---

lib/command_match.c

Closes https://github.com/FRRouting/frr/issues/14200

lib: Lower precedence for ASNUM_TKN when using together with IPV4/IPV6_TKN

---

bgpd/bgp_nht.c

Problem:
On GR helper, paths learnt from an interface based peer were linked
to bnc with ifindex=0. During restart of GR peer, BGP (unnumbered)
session (with GR restarter peer) goes down on GR helper but the routes
are retained. Later, when BGP receives an interface up event, it
will process all the paths associated with BNC whose ifindex matches the
ifindex of the interface for which UP event is received. However, paths
associated with bnc that has ifindex=0 were not being reinstalled since
ifindex=0 doesn't match ifindex of any interfaces. This results in
BGP routes not being reinstalled in zebra and kernel.
Fix:
For paths learnt from an interface based peer, set the
ifindex to peer's interface ifindex so that correct
peer based nexthop can be found and linked to the path. …

bgpd: Set ifindex to find the correct nexthop

---

bgpd/bgp_routemap.c

Properly free the dynamically allocated memory held by `str` after its use. The change also maintains the return value of `nb_cli_apply_changes` by using `ret` variable.
```
Address Sanitizer Error detected in bgp_set_aspath_replace.test_bgp_set_aspath_replace/r1.asan.bgpd.11586
==11586==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 92 byte(s) in 3 object(s) allocated from:
#0 0x7f4e2951db40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x7f4e28f19ea2 in qmalloc lib/memory.c:100
#2 0x7f4e28edbb08 in frrstr_join lib/frrstr.c:89
#3 0x7f4e28e9a601 in argv_concat …
```

bgpd: Free memory in set_aspath_replace_access_list

---

zebra/if_netlink.c
zebra/interface.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_l2.c

Upon some internal testing some crashes were found.  This fixes the several crashes and normalizes the code to be closer in it's execution pre and post changes to use the data plane.

zebra: Fix crashes in interface change

---

bgpd/bgp_routemap.c

Properly free the dynamically allocated memory held by `str` after its use. The change also maintains the return value of `nb_cli_apply_changes` by using `ret` variable.
```
Direct leak of 55 byte(s) in 2 object(s) allocated from:
#0 0x7f16f285f867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0x7f16f23fda11 in qmalloc ../lib/memory.c:100
#2 0x7f16f23a01a0 in frrstr_join ../lib/frrstr.c:89
#3 0x7f16f23418c7 in argv_concat ../lib/command.c:183
#4 0x55aba24731f2 in set_aspath_exclude_access_list_magic ../bgpd/bgp_routemap.c:6327
#5 0x55aba2455cf4 in set_aspath_exclude_access_list bgpd/bgp_routemap_clippy.c:836
#6 0x7f16f2345d61 in cmd_execute_command_real ../lib/command.c:993
#7 0x7f16f23460ee in cmd_execute_command …
```

bgpd: Free memory in set_aspath_exclude_access_list

---

ospfd/ospf_ti_lfa.c

In scenarios where no backup paths are available, ensure proper memory management by deleting `q_space->vertex_list`. This prevents memory leaks.
```
Direct leak of 80 byte(s) in 2 object(s) allocated from:
#0 0x7fcf8c70aa37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7fcf8c2a8a45 in qcalloc ../lib/memory.c:105
#2 0x7fcf8c27d0cc in list_new ../lib/linklist.c:49
#3 0x55d6e8385e35 in ospf_spf_init ../ospfd/ospf_spf.c:540
#4 0x55d6e838c30d in ospf_spf_calculate ../ospfd/ospf_spf.c:1736
#5 0x55d6e83933cf in ospf_ti_lfa_generate_q_spaces ../ospfd/ospf_ti_lfa.c:673
#6 0x55d6e8394214 in ospf_ti_lfa_generate_p_space ../ospfd/ospf_ti_lfa.c:812
#7 0x55d6e8394c63 in ospf_ti_lfa_generate_p_spaces ../ospfd/ospf_ti_lfa.c:923 …
```

ospfd: Delete `q_space->vertex_list` on No Backup Path

---

pbrd/pbr_map.c
pbrd/pbr_map.h
pbrd/pbr_vty.c

This commit ensures that sequence data and associated structures are correctly deleted to prevent memory leaks
```
Direct leak of 432 byte(s) in 1 object(s) allocated from:
#0 0x7f911ebaba37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7f911e749a4e in qcalloc ../lib/memory.c:105
#2 0x564fd444b2d3 in pbrms_get ../pbrd/pbr_map.c:527
#3 0x564fd443a82d in pbr_map ../pbrd/pbr_vty.c:90
#4 0x7f911e691d61 in cmd_execute_command_real ../lib/command.c:993
#5 0x7f911e6920ee in cmd_execute_command ../lib/command.c:1052
#6 0x7f911e692dc0 in cmd_execute ../lib/command.c:1218
#7 0x7f911e843197 in vty_command ../lib/vty.c:591
#8 0x7f911e84807c in vty_execute ../lib/vty.c:1354
#9 0x7f911e84e47a in vtysh_read ../lib/vty.c:2362
#10 …
```

pbrd: Correct Handling of Sequence Deletion

---

tests/topotests/static_simple/test_static_simple.py

Under heavy system load we can see that the static_simple test is giving up too early in this micronet run:
8-17 15:00:27,105 DEBUG: topo: Waiting for [0.1]s as initial delay 2023-08-17 15:00:27,206 DEBUG: r1: cmd_status("/bin/bash -c 'ip -4 route show'") 2023-08-17 15:00:28,209 DEBUG: r1:
stdout: 101.0.0.0/24 dev r1-eth0 proto kernel scope link src 101.0.0.1
2023-08-17 15:00:28,209 DEBUG: topo: checking kernel routing table: 101.0.0.0/24 dev r1-eth0 proto kernel scope link src 101.0.0.1
2023-08-17 15:00:28,210  INFO: topo: Function raised exception: Failed to find
'10.0.0.0/8(?: nhid [0-9]+)? via 101.0.0.2 dev r1-eth0 proto (static|196) metric 20'
in
'101.0.0.0/24 dev r1-eth0 proto kernel scope link src 101.0.0.1
'
assert None
+  where None = <function search at …

tests: static_simple gives up after 3 seconds

---

bgpd/bgp_packet.c

Reported-by: Iggy Frankovic iggyfran@amazon.com

bgpd: Don't read the first byte of ORF header if we are ahead of stream

---

lib/cspf.c

This commit ensures proper cleanup by clearing the `algo->pdst` pointer if it points to a path that is being deleted. It addresses memory leaks by freeing memory held by `algo->pdst` that might not have been released during the cleanup of processed paths.
```
Direct leak of 96 byte(s) in 1 object(s) allocated from:
#0 0x7fbffcec9a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7fbffca67a81 in qcalloc ../lib/memory.c:105
#2 0x7fbffc9d1a54 in cpath_new ../lib/cspf.c:44
#3 0x7fbffc9d2829 in cspf_init ../lib/cspf.c:256
#4 0x7fbffc9d295d in cspf_init_v4 ../lib/cspf.c:287
#5 0x5601dcd34d3f in show_sharp_cspf_magic ../sharpd/sharp_vty.c:1262
#6 0x5601dcd2c2be in show_sharp_cspf sharpd/sharp_vty_clippy.c:1869
#7 …
```

lib: Clear Computed Path Pointer to Destination on Clean

---

zebra/rib.h
zebra/zebra_rib.c

Bug is reporoduced in case of switching interfaces betwean VRFs.
ospf6d is enabled and configured in each VRF.
'dest' can be removed from the route node in the time when the same
route node waiting processing in another sub-queue.
A route node must only be in one sub-queue at a time.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140662163115136) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140662163115136) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140662163115136, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fee76753476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fee767397f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fee76a420fd in _zlog_assert_failed () from …

zebra: fix assert in process_subq_route

---

debian/not-installed

Without this, the Debian package build fails because dplane_sample_plugin.so gets compiled but not installed.

debian: Don't install sample dplane plugin

---

bgpd/bgp_attr.c

Found when fuzzing:
```
==3470861==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xffff77801ef7 at pc 0xaaaaba7b3dbc bp 0xffffcff0e760 sp 0xffffcff0df50
READ of size 2 at 0xffff77801ef7 thread T0
0 0xaaaaba7b3db8 in __asan_memcpy (/home/ubuntu/frr_8_5_2/frr_8_5_2_fuzz_clang/bgpd/bgpd+0x363db8) (BuildId: cc710a2356e31c7f4e4a17595b54de82145a6e21)
1 0xaaaaba81a8ac in ptr_get_be16 /home/ubuntu/frr_8_5_2/frr_8_5_2_fuzz_clang/./lib/stream.h:399:2
2 0xaaaaba819f2c in bgp_attr_aigp_valid /home/ubuntu/frr_8_5_2/frr_8_5_2_fuzz_clang/bgpd/bgp_attr.c:504:3
3 0xaaaaba808c20 in bgp_attr_aigp /home/ubuntu/frr_8_5_2/frr_8_5_2_fuzz_clang/bgpd/bgp_attr.c:3275:7
4 0xaaaaba7ff4e0 in bgp_attr_parse /home/ubuntu/frr_8_5_2/frr_8_5_2_fuzz_clang/bgpd/bgp_attr.c:3678:10
```

bgpd: Make sure we have enough data to read two bytes when validating AIGP

---

bgpd/bgp_packet.c

```
3  0x00007f423aa42476 in __GI_raise (sig=sig@entry=11) at ../sysdeps/posix/raise.c:26
4  0x00007f423aef9740 in core_handler (signo=11, siginfo=0x7fffc414deb0, context=<optimized out>) at lib/sigevent.c:246
5  <signal handler called>
6  0x0000564dea2fc71e in route_set_aspath_prepend (rule=0x564debd66d50, prefix=0x7fffc414ea30, object=0x7fffc414e400)
at bgpd/bgp_routemap.c:2258
7  0x00007f423aeec7e0 in route_map_apply_ext (map=<optimized out>, prefix=prefix@entry=0x7fffc414ea30,
match_object=match_object@entry=0x7fffc414e400, set_object=set_object@entry=0x7fffc414e400, pref=pref@entry=0x0) at lib/routemap.c:2690
8  0x0000564dea2d277e in bgp_input_modifier (peer=peer@entry=0x7f4238f59010, p=p@entry=0x7fffc414ea30, attr=attr@entry=0x7fffc414e770,
afi=afi@entry=AFI_IP, …
```

bgpd: Do not process NLRIs if the attribute length is zero

---

configure.ac

Bug report:
```
root@adf01781b1eb:~/persist/frr-build/tests/topotests# /usr/lib/frr/zebra -M fpm
frr_init: loader error: dlopen(/usr/lib/frr/modules/zebra_fpm.so): /usr/lib/frr/modules/zebra_fpm.so: undefined symbol: zfpm_protobuf_encode_route
frr_init: loader error: dlopen(/usr/lib/frr/modules/fpm.so): /usr/lib/frr/modules/fpm.so: cannot open shared object file: No such file or directory
frr_init: loader error: dlopen(fpm): fpm: cannot open shared object file: No such file or directory
```
Bug trigger condition ( CI have this set ): 
```
./configure --enable-protobuf=no --enable-fpm=yes
/usr/lib/frr/zebra -M fpm
```
Explain:
Macro `HAVE_PROTOBUF` and compile condition variable `HAVE_PROTOBUF`  in `configure.ac ` is not consistent. 
When configure `disable-protobuf`, compile condition …

configure.ac: fix protobuf config

---

bgpd/bgp_route.c

Shouldn't validate the label after 'decode_label'. If we validate the label after 'decode_label', even the 'MPLS_INVALID_LABEL' will be valid then.

bgpd: fix bug in a place about label validation

---

doc/manpages/frr-zebra.rst
doc/user/zebra.rst
zebra/kernel_socket.c
zebra/main.c
zebra/redistribute.c
zebra/rib.h
zebra/rt_netlink.c
zebra/zebra_rib.c
zebra/zebra_vrf.c

Adds a `-R`/`--routing-table` flag to set the main kernel routing table used by zebra.

zebra: Make main routing table (RT_TABLE_MAIN) configurable

---

lib/link_state.c

Previously when updating vertices, edges and subnets, when no update was required due to existing value matching the new one, memory associated with the new object was not being freed leading to memory leaks. This commit fixes memory leak by freeing memory associated with new object when update is unnecessary.
```
Direct leak of 312 byte(s) in 3 object(s) allocated from:
#0 0x7faf3afbfa37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7faf3ab5dbcf in qcalloc ../lib/memory.c:105
#2 0x7faf3ab42e00 in ls_parse_prefix ../lib/link_state.c:1323
#3 0x7faf3ab43c87 in ls_parse_msg ../lib/link_state.c:1373
#4 0x7faf3ab476a5 in ls_stream2ted ../lib/link_state.c:1885
#5 0x564e045046aa in sharp_opaque_handler …
```

lib: Fix memory leaks in LS Update Functions

---

bgpd/bgp_packet.c

It was missed to handle UNSET Role capability using dynamic capabilities.
Also move length check before actually handling Role capability.

bgpd: Handle Role capability via dynamic capabilities for SET/UNSET properly

---

bgpd/bgp_attr.c

Before this path we used session reset method, which is discouraged by rfc7606.
Handle this as rfc requires.
Closes https://github.com/FRRouting/frr/issues/14289

bgpd: Use treat-as-withdraw for tunnel encapsulation attribute

---

bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

```
donatas-pc(config-router)# timers bgp 8 12
% keepalive value 8 is larger than 1/3 of the holdtime, setting to 4
donatas-pc(config-router)# do sh run | include timers bgp
timers bgp 4 12
donatas-pc(config-router)#
```
Closes https://github.com/FRRouting/frr/issues/14287

bgpd: Add a warning for the operator that keepalive was changed

---

bgpd/bgp_bmp.c
bgpd/bgp_evpn.c
bgpd/bgp_evpn_mh.c
bgpd/bgp_evpn_private.h
bgpd/bgp_evpn_vty.c
bgpd/bgp_fsm.c
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_table.c
bgpd/bgp_table.h
bgpd/bgp_zebra.c
bgpd/bgpd.h
lib/table.c
tests/bgpd/test_mpath.c

This is based on @donaldsharp 's work.
The current code base is the struct bgp_node data structure. 
The problem with this is that it creates a bunch of extra data per route_node. 
The table structure generates ‘holder’ nodes that are never going to receive bgp routes, 
and now the memory of those nodes is allocated as if they are a full bgp_node. 
After splitting up the **bgp_node** into **bgp_dest** and **route_node**, 
the memory of ‘holder’ node which does not have any bgp data will not be 
allocated the bgp_node for but the route_node, and the effect of memory 
usage reduction is achieved.
The memory usage of BGP node will be reduced from 200B to 96 B.
The total memory usage optimization of this part is ~16.00%.
Signed-off-by: Yuqing …

bgpd: Convert from struct bgp_node to struct bgp_dest

---

bgpd/bgp_fsm.c

It was noticed that occassionally peering failed in a testbed upon investigation it was found that the peer was not in the peer hash and we saw these failure messages:
Aug 25 21:31:15 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: %NOTIFICATION: sent to neighbor 2001:cafe:1ead:4::4 4/0 (Hold Timer Expired) 0 bytes
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 100663299] Can't get remote address and port: Transport endpoint is not connected
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 100663299] %bgp_getsockname() failed for  peer 2001:cafe:1ead:4::4 fd 27 (from_peer fd -1)
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 33554464] %Neighbor failed in xfer_conn
root@doca-hbn-service-bf3-s06-1-ipmi:/var/log/hbn/frr# vtysh -c 'show bgp …

bgpd: Add peers back to peer hash when peer_xfer_conn fails

---

ospfd/ospfd.c

Consider this config:
router ospf
redistribute kernel
Then you issue:
no router ospf
ospf will crash with a use after free.
The problem is that the event's associated with the ospf pointer were shut off then the ospf_external_delete was called which rescheduled the event.  Let's just move event deletion to the end of the no router ospf.

ospfd: Prevent use after free( and crash of ospf ) when no router ospf

---

bgpd/bgp_vty.c
bgpd/bgp_zebra.c
bgpd/bgp_zebra.h

When the BGP 'redistribute table' command is used for a given route table, and BGP configuration is flushed and rebuilt, the redistribution does not work.
Actually, when flushing the BGP configuration, the BGP redistribute entries are flushed only when the redistribute is not related to table identifier.
Fix this by adding some code to flush all the redistribute table instances.
Fixes: 7c8ff89e9346 ("Multi-Instance OSPF  Summary")

bgpd: fix redistribute table command after bgp restarts

---

bgpd/bgp_fsm.c

peer is NULL, but we pass it to hash_get().
This reverts commit 6f8c927b03c454aa309b84cefccc4faa31e0c03f.

Revert "bgpd: Add peers back to peer hash when peer_xfer_conn fails"

---

bgpd/bgp_route.c

Fix up the output to not display a (NULL) output for the bgp name

bgpd: When using `show bgp peerhash` don't display (NULL)

---

bgpd/bgp_route.c

The command "show bgp all rpki notfound" includes not only RPKI notfound routes but also RPKI valid and invalid routes in its results.
Fix the code to display only RPKI notfound routes.
Old output:
```
frr# show bgp all rpki notfound
For address family: IPv4 Unicast
BGP table version is 0, local router ID is 10.0.0.1, vrf id 0
Default local pref 100, local AS 64512
N   x.x.x.0/18       a.a.a.a                       100      0 64513 i
V …
```

bgpd: Fix `show bgp all rpki notfound`

---

lib/if.h
lib/zclient.c
zebra/if_netlink.c
zebra/interface.c
zebra/zapi_msg.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h

Add a txqlen attribute to the common interface struct. This captures the value in zebra, add it to the existing 'show' output, and distributes it through the interface lib module's zapi messaging.

lib,zebra: add tx queuelen to interface struct

---

tools/gcc-plugins/Makefile
tools/gcc-plugins/frr-format.c
tools/gcc-plugins/gcc-common.h

As usual, new GCC version, new small random changes in the API.

tools/gcc-plugins: fix for GCC 13

---

bgpd/bgp_nht.c
tests/topotests/bgp_blackhole_community/r4/bgpd.conf
tests/topotests/bgp_blackhole_community/test_bgp_blackhole_community.py
tests/topotests/bgp_vpn_5549_route_map/test_bgp_vpn_5549_route_map.py

For v4 nexthops, ifindex was being set. Modified the check to set ifindex only for v6 nexthops. Also modified the check to set ifindex only if the v6 nexthop matches peer's LL address.
UT:
Test 1:
```
Without AFI == IPv6 check:
=========================
mlx-3700-19# show bgp nexthop 
Current BGP nexthop cache:
27.0.0.15 invalid, #paths 32
Last update: Thu Aug 17 18:05:30 2023----> invalid IPv4 NH was created 
27.0.0.16 invalid, #paths 31
Last update: Thu Aug 17 18:05:30 2023
36.0.0.13 invalid, #paths 72
Last update: Thu Aug 17 18:05:30 2023
27.0.0.15 invalid, #paths 32
Last update: Thu Aug 17 18:05:30 2023
27.0.0.16 invalid, #paths 31
Last update: Thu Aug 17 18:05:30 2023
36.0.0.13 invalid, #paths 72
Last update: Thu Aug 17 18:05:30 2023
27.0.0.15 invalid, #paths 32
Last update: Thu Aug …
```

bgpd: set ifindex only for v6 nexthops and nexthops that match peer's LL

---

zebra/rib.h
zebra/zebra_nhg.c
zebra/zebra_rib.c

During replace of a NHE from upper proto in zebra_nhg_proto_add(),
- rib_handle_nhg_replace() is invoked with old NHE where we walk all RNs/REs & replace the re->nhe whose address points to old NHE.
- In this walk, if prev re->nhe refcnt is decremented to 0, we free up the memory which the old NHE is pointing to. Later in zebra_nhg_proto_add(), we end up accessing this freed memory and crash.
**Logs:**
```
1380766 2023/08/16 22:34:11.994671 ZEBRA: [WDEB1-93HCZ] zebra_nhg_decrement_ref: nhe 0x56091d890840 (70312519[2756/2762/2810]) 2 => 1 
1380773 2023/08/16 22:34:11.994678 ZEBRA: [WDEB1-93HCZ] zebra_nhg_decrement_ref: nhe 0x56091d890840 (70312519[2756/2762/2810]) 1 => 0 
1380777 2023/08/16 22:34:11.994844 ZEBRA: [JE46R-G2NEE] zebra_nhg_release: nhe 0x56091d890840 …
```

zebra: Fix zebra crash when replacing NHE during shutdown

---

configure.ac

The `-disable-rr-semantics` or `--enable-rr-senamtics` configure option is never used.  Let's just remove it.

*: Remove unused configure option

---

zebra/tc_netlink.c

If the kernel sends us bad data then the kind_str
will be NULL and a later strcmp operation will
cause a crash.
As a note: If the kernel is not sending us properly formated netlink messages then we got bigger problems than zebra crashing.  But at least let's prevent zebra from crashing.
Reported-by: Iggy Frankovic <iggyfran@amazon.com>

zebra: Prevent Null pointer deref

---

bgpd/bgp_routemap.c

Close https://github.com/FRRouting/frr/issues/14359

bgpd: Fix `no set as-path prepend` command for BGP

---

lib/event.c
lib/frrevent.h

... by converting the hash table to a typesafe hash.
Honestly I was just looking around for things to convert to the typesafe hash table code, but then I noticed that cpu_record_clear() deletes items from inside the hash_iterate() callback :(

lib: fix delete during hash_iterate() in event_*

---

ospfd/ospf_main.c

Crash found in the fuzzer is because the ospf pointer looked up for the default vrf instance returns NULL, which immediately crashes.  Normal OSPF code, to even get here, requires a default instance of ospf.  As such the fuzzing code violated a tenant of the main ospf code.  Let's just fix the ospf fuzzing code to create a default vrf and then associate the ospf code with it.

FUZZER: Certain types of fuzzing requires a default ospf instance

---

doc/user/zebra.rst
zebra/dplane_fpm_nl.c
zebra/rt_netlink.c
zebra/rt_netlink.h

Implement route replace semantics for FPM in order to avoid data traffic drops in data planes using this interface.
Examples:
- Route `10.254.254.100/32` update **without route replace** example (3 messages total, small data interruption between `RTM_DELROUTE` and `RTM_NEWROUTE`):
```
nlmsghdr [len=52 type=(24) NEWROUTE flags=(0x0501) {REQUEST,DUMP,(ROOT|REPLACE|CAPPED),(ATOMIC|CREATE)} seq=0 pid=3801105067]
rtmsg [family=(2) AF_INET dstlen=32 srclen=0 tos=0 table=254 protocol=(196) UNKNOWN scope=(0) UNIVERSE type=(1) UNICAST flags=0x0000 {}]
rta [len=8 (payload=4) type=(1) DST]                                                                                                                             
10.254.254.100                                                              
rta [len=8 …
```

zebra: support route replace semantic in FPM

---

isisd/isis_flex_algo.c
lib/typesafe.h

This reverts commit 72eae2c3cb771b7010f3f07b6c638e9ae078bbdf.
`frr_each_const(X, ...)` is not needed since it is the same as `frr_each(X_const, ...)`.
The fact that it wasn't properly set up for clang-format, and that then work-arounded with "clang-format off" is all the more reason to not do this.

Revert "lib: add a frr_each_const macro"

---

pbrd/pbr_map.c

This commit frees dynamically allocated memory associated with `pbrms->nhgrp_name` and `pbrms->dst` which were causing memory leaks.
```
==107458==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
#0 0x7f87d644ca37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7f87d5feaa37 in qcalloc ../lib/memory.c:105
#2 0x7f87d6054ffd in prefix_new ../lib/prefix.c:1180
#3 0x55722f3c2885 in pbr_map_match_dst_magic ../pbrd/pbr_vty.c:302
#4 0x55722f3b5c24 in pbr_map_match_dst pbrd/pbr_vty_clippy.c:228
#5 0x7f87d5f32d61 in cmd_execute_command_real ../lib/command.c:993
#6 0x7f87d5f330ee in cmd_execute_command …
```

pbrd: Free Memory in pbr_map_delete

---

bgpd/bgp_attr.c
bgpd/bgpd.c
bgpd/bgpd.h

allow 255 in path attr  discard/withdraw cmds
https://www.rfc-editor.org/rfc/rfc2042.html
says: 255 reserved for development
In FRR, 255 is kinda used too BGP_ATTR_VNC, even more we allow setting 255 in CLI.

bgpd: BGP_ATTR_MAX can be 255, allow using it for path attr

---

tests/topotests/bgp_snmp_mplsl3vpn/ce1/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/ce2/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/ce3/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/ce4/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/r1/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/r2/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/r3/snmpd.conf
tests/topotests/bgp_snmp_mplsl3vpn/r4/snmpd.conf
tests/topotests/isis_snmp/r1/snmpd.conf
tests/topotests/isis_snmp/r2/snmpd.conf
tests/topotests/isis_snmp/r3/snmpd.conf
tests/topotests/isis_snmp/r4/snmpd.conf
tests/topotests/isis_snmp/r5/snmpd.conf
tests/topotests/ldp_snmp/r1/snmpd.conf
tests/topotests/ldp_snmp/r2/snmpd.conf
tests/topotests/simple_snmp_test/r1/snmpd.conf

the snmp tests are using zebra.conf to setup the
address that they are binding to and immediately
after that they are starting snmpd.  If snmpd
starts up *before* zebra has installed the address the bind on the address will fail.  Causing the entire test to fail.  Modify the snmpd.conf for all our
snmp tests to bind to all addresses.  Things still work and we no longer have an issue.

tests: snmp tests sometimes fail with `Unable to bind`

---

bgpd/bgp_mplsvpn.h
tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vrf_all_routes_init.json
tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vrf_all_routes_plus_r1_vrf1.json
tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vrf_all_routes_plus_r2_vrf2.json
tests/topotests/bgp_vpnv4_noretain/r1/ipv4_vrf_all_routes_plus_r2_vrf3.json
tests/topotests/bgp_vpnv4_noretain/test_bgp_vpnv4_noretain.py

The BGP "no retain" VPN option avoids storing VPN prefixes that are not
imported in the incoming BGP table (aka. Adj RIB in). When a VPN import
policy is changed, BGP does a soft clear so that a prefix refresh is
requested from the peers. However, the import from local VPN prefixes
is never requested.
Fix this issue by requesting a local import refresh.

bgpd: fix import from a local VRF with no bgp retain

---

doc/user/zebra.rst
tests/topotests/all_protocol_startup/r1/ip_nht.ref
tests/topotests/all_protocol_startup/r1/ipv6_nht.ref
tests/topotests/bgp_features/r1/zebra.conf
zebra/zebra_vrf.c
zebra/zebra_vrf.h
zebra/zebra_vty.c

As discussed in the Slack, turning `nht resolve-via-default` for a traditional profile by default.

zebra: Turn on `nht resolve-via-default` by default for traditional profile

---

bgpd/bgp_fsm.c

Not sure why this is needed, because it's reset on bgp_connect_success(), when the session is UP.
When the session is reset, it clears those variables, and we are not able to see what remote address was before, etc.
hostLocal, hostRemote reports Unknown for `show bgp neighbor json`.

bgpd: Keep remote/local socket unions on BGP start event

---

bgpd/bgp_vty.c

The 'redistribute table' command can be used by configuration on any non default BGP instance, but this command does not work for multiple reasons:
- The route entries configured on a given table are always configured from the default vrf. This constraint prevents from redistributing a prefix from the default vrf to an other non default bgp instance.
- The importation of route entries requires 'ip import-table' on vrfs and this command is not available
Fix this by preventing from configuring this kind of redistribution on non default bgp instances.

bgpd: fix forbiding 'redistribute table' usage on non default instances

---

tools/frrcommon.sh.in

When calling daemon_stop() with --quiet and e.g. the pidfile is empty, it won't return early since while "$fail" is set, "$2" is "--quiet", so the if condition isn't met and it will continue executing, resulting in error messages in the log:
```
Sep 14 14:48:33 localhost watchfrr[2085]: [YFT0P-5Q5YX] Forked background command [pid 2086]: /usr/lib/frr/watchfrr.sh restart all
Sep 14 14:48:33 localhost frrinit.sh[2075]: /usr/lib/frr/frrcommon.sh: line 216: kill: `': not a pid or valid job spec
Sep 14 14:48:33 localhost frrinit.sh[2075]: /usr/lib/frr/frrcommon.sh: line 216: kill: `': not a pid or valid job spec
Sep 14 14:48:33 localhost frrinit.sh[2075]: /usr/lib/frr/frrcommon.sh: line 216: kill: `': not a pid or valid job spec
```
Fix this by moving the --quiet check into the block to …

tools: make --quiet actually suppress output

---

pimd/pim_mroute.c
pimd/pim_oil.c
pimd/pim_zlookup.c

When debugging and outputting the oil_parent() let's just convert it to a string that is useful for people trying to debug pim

pimd: Display oil_parent as a string name of the interface

---

ospf6d/ospf6_intra.c

GCC 13.2.0 complains:
```
ospf6d/ospf6_intra.c:139:25: error: ‘json_arr’ may be used uninitialized [-Werror=maybe-uninitialized]
ospf6d/ospf6_intra.c:485:20: error: ‘json_arr’ may be used uninitialized [-Werror=maybe-uninitialized]
```

ospf6d: fix uninitialized warnings

---

isisd/isis_tlvs.c
isisd/isis_zebra.c

Fix a bunch of coverity issues.
```
*** CID 1568129:  Null pointer dereferences  (REVERSE_INULL)
/isisd/isis_tlvs.c: 2813 in unpack_item_srv6_end_sid()
2807                    sid->subsubtlvs = NULL;
2808            }
2809
2810            append_item(&subtlvs->srv6_end_sids, (struct isis_item *)sid);
2811            return 0;
2812     out:
>>>     CID 1568129:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "sid" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
2813            if (sid)
2814                    free_item_srv6_end_sid((struct isis_item *)sid);
2815            return 1;
2816     }
2817
2818     /* Functions related to TLVs 1 Area Addresses */
```
---
```
*** CID 1568132:  Null pointer dereferences …
```

isisd: Fix a bunch of coverity issues in IS-IS

---

lib/compiler.h

Typesafe hash tables do this:
```
assume((tabshift) >= 2 && (tabshift) <= 33);
(val) >> (33 - (tabshift));
```
Sadly, Coverity currently ignores assume() and says:
> [...] right shifting by more than 31 bits has undefined behavior.
> The shift amount, "33 - h->hh.tabshift", is 33.
Let's see if Coverity understands this can't happen...

lib: another attempt at Coverity false positives

---

pimd/pim_nb_config.c
yang/frr-pim.yang

The YANG specification currently designates a uint8 data type for the hello interval, despite the CLI documentation (ip pim hello (1-65535) [(1-65535)]) indicating a maximum value of 65535.
To address this inconsistency, updating the data type to uint16 allowing for a maximum value for hello intervals.
Closes #14286

pimd,pim6d: Resolving the YANG datatype Inconsistency for PIM Hello Interval

---

pimd/pim_cmd_common.c
pimd/pim_mroute.c
pimd/pim_oil.c
pimd/pim_oil.h
pimd/pim_static.c
pimd/pim_upstream.c
pimd/pim_zlookup.c

Use oil_incoming_vif instead of oil_parent.  I had to go look this up as that I failed to remember that the linux kernel calls this parent for some bizarre reason.

pimd: Use a better name for oil_parent

---

lib/typesafe.h

The previous change to assume() did address the coverity warning about one direction of the shift in HASH_KEY, let's constrain the other in HASH_SIZE as well.
To be fair, the hash table *will* break at 1G entries, but at that point we have other problems RAM-wise.  (Could bump the thing to 64-bit, but then we need better item hash functions too on every single user.)
---
this should *finally* get rid of all hash table related coverity warnings

lib: constrain hash table "tabshift" both ways

---

bgpd/bgp_evpn.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
bgpd/bgp_route.h

couple bgp coverity issues

---

bgpd/bgp_btoa.c
bgpd/bgp_labelpool.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_nexthop.c
bgpd/bgp_route.c
bgpd/bgp_updgrp.c
bgpd/bgpd.h
pathd/path_pcep_debug.c
tests/bgpd/test_mpath.c

ctime() is a no-no - use ctime_r() instead.

bgpd, pathd: replace ctime() with ctime_r()

---

doc/developer/index.rst
doc/developer/northbound/_sidebar.rst
doc/developer/northbound/advanced-topics.rst
doc/developer/northbound/architecture.rst
doc/developer/northbound/demos.rst
doc/developer/northbound/links.rst
doc/developer/northbound/northbound.rst
doc/developer/northbound/operational-data-rpcs-and-notifications.rst
doc/developer/northbound/plugins-sysrepo.rst
doc/developer/northbound/ppr-basic-test-topology.rst
doc/developer/northbound/ppr-mpls-basic-test-topology.rst
doc/developer/northbound/retrofitting-configuration-commands.rst
doc/developer/northbound/transactional-cli.rst
doc/developer/northbound/yang-module-translator.rst
doc/developer/northbound/yang-tools.rst
doc/developer/subdir.am

Adds the Northbound API docs from [here](https://github.com/opensourcerouting/frr/wiki/Architecture).
This is a simple pandoc conversion of the docs, makefile update, and an small edit to make sure they show up in the toctree. I plan to come back and clean these up more, but this patch is years overdue.
Todo:
* Fix the heading levels to be correct
* Download all the images from postimg, put them in tree and fix the image references
* Remove the manual TOC blocks
* Probably other fixes

doc: add northbound api arch docs

---

bgpd/bgp_zebra.c
doc/user/static.rst
include/linux/seg6.h
lib/nexthop.c
lib/nexthop.h
lib/srv6.h
lib/zclient.c
lib/zclient.h
sharpd/sharp_vty.c
staticd/static_nb.c
staticd/static_nb.h
staticd/static_nb_config.c
staticd/static_routes.h
staticd/static_vty.c
staticd/static_zebra.c
tests/topotests/srv6_static_route/expected_srv6_route.json
tests/topotests/srv6_static_route/r1/setup.sh
tests/topotests/srv6_static_route/r1/staticd.conf
tests/topotests/srv6_static_route/r1/zebra.conf
tests/topotests/srv6_static_route/test_srv6_route.py
yang/frr-nexthop.yang
zebra/rt_netlink.c
zebra/zapi_msg.c
zebra/zebra_nb.c
zebra/zebra_nb.h
zebra/zebra_nb_state.c
zebra/zebra_nhg.c
zebra/zebra_rnh.c

From now it is possible to specify a route using an SRv6 with multiple segs SIDs (on Linux it one may know it as seg6 route).
With this command staticd will request a seg6 route with multiple segs via ZEBRA_ROUTE_ADD ZAPI.
format:
```
ipv6 route X:X::X:X <X:X::X:X|nexthop> segments U:U::U:U/Y:Y::Y:Y/Z:Z::Z:Z
````
config:
```
router(config)# ipv6 route  2005::1/64 ens3 segments 2001:db8:aaaa::7/2002::2/2003::3/2004::4
```
show:
```
router# show ipv6 route
[..]
S>* 2005::/64 [1/0] is directly connected, ens3, seg6 2001:db8:aaaa::7,2002::2,2003::3,2004::4, weight 1, 00:00:06
```
Signed-off-by: Dmytro Shytyi <dmytro.shytyi@6wind.com>

 bgpd,doc,lib,sharpd,staticd,yang,zebra: SRv6 multiple segs SIDs

---

bgpd/bgp_aspath.c

CID 1566378 (#1-4 of 4): Use after free (USE_AFTER_FREE)76.
use_after_free: Using freed pointer cur_seg.
now the prev_seg pointer is set with always existaing values.
Link: https://scan7.scan.coverity.com/reports.htm#v39104/p13747/fileInstanceId=146858993&defectInstanceId=18968273&mergedDefectId=1566378&fileStart=1376&fileEnd=1625
Fixes: 4685db418e3a861205a28f975afeb9869f674337 (bgpd: add set as-path exclude acl-list command)

bgpd: fix coverity issue on aspath_filter_exclude_acl

---

isisd/isis_zebra.c

After the ISIS daemon is launched, the configuration of an srv6 locator in zebra triggers a crash:
> #4  0x00007f1f0ea980f3 in core_handler (signo=11, siginfo=0x7ffdb750de70, context=0x7ffdb750dd40)
>     at /build/make-pkg/output/_packages/cp-routing/src/lib/sigevent.c:262
> #5  <signal handler called>
> #6  0x00005651a05783ef in isis_zebra_process_srv6_locator_add (cmd=117, zclient=0x5651a21d9bd0, length=25, vrf_id=0)
>     at /build/make-pkg/output/_packages/cp-routing/src/isisd/isis_zebra.c:1258
> #7  0x00007f1f0ead5ac9 in zclient_read (thread=0x7ffdb750e750) at /build/make-pkg/output/_packages/cp-routing/src/lib/zclient.c:4246
> #8  0x00007f1f0eab19d4 in thread_call (thread=0x7ffdb750e750) at /build/make-pkg/output/_packages/cp-routing/src/lib/thread.c:1825
> #9  0x00007f1f0ea4862e …

isisd: fix crash when configuring srv6 locator without isis instance

---

zebra/zebra_snmp.c

The value is not being treated correctly, make it so.

zebra: Fix longstanding snmp coverity issue

---

bgpd/bgp_snmp_bgp4.c
ospfd/ospf_snmp.c

Coverity reports some uses of 'oid *' as if they were 'char *'; try to correct that.

bgpd, ospfd: fix some dicey pointer arith in snmp modules

---

bgpd/bgp_updgrp.c
bgpd/bgpd.h

Don't return a local - caller needs to pass in a buffer.
This should fix recent coverity CID 1568217.

bgpd: fix return of local from ctime_r

---

tests/topotests/lib/bgp.py
tests/topotests/multicast_mld_join_topo1/test_multicast_mld_local_join.py
tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm1.py
tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm2.py
tests/topotests/multicast_pim_uplink_topo1/test_multicast_pim_uplink_topo1.py
tests/topotests/multicast_pim_uplink_topo2/test_multicast_pim_uplink_topo2.py
tests/topotests/multicast_pim_uplink_topo3/test_multicast_pim_uplink_topo3.py

tests: Adding BGP convergence verification before starting PIM tests
Issue: For the tests where BGP is used for PIM tests,
sometimes BGP neighbors are not up before doing any PIM
operation, that is causing some tests failures.
https://github.com/FRRouting/frr/issues/14441
Fix: Added BGP convergence for all tests where BGP is used to make
sure all BGP neigbhors
Issue: https://github.com/FRRouting/frr/issues/14057
Fix: Added some sleep to make sure prune is received before
RP is changed.

tests: Adding BGP convergence verification before starting PIM tests

---

pimd/pim_ssmpingd.c

The socket has been closed in `ssmpingd_setsockopt()` in the wrong cases, so remove the redundant closing socket from outer layer.

pimd: remove redundant closing socket

---

bgpd/bgp_advertise.c

When BGP is sending updates to peers on a neighbor up event it was noticed that the bgp updates being sent were in reverse order being sent to the first peer.
Imagine r1 -- r2 -- r3.  r1 and r2 are ebgp peers and r2 and r3 are ebgp peers.  r1's interface to r2 is currently shutdown.  Prior to this fix the send order would look like this:
r1 -> r2 send of routes to r2 and then they would be installed in order received:
10.0.0.12 nhid 39 via 192.168.8.2 dev leaf2-eth5 proto bgp metric 20 10.0.0.11 nhid 39 via 192.168.8.2 dev leaf2-eth5 proto bgp metric 20 10.0.0.10 nhid 39 via 192.168.8.2 dev leaf2-eth5 proto bgp metric 20 10.0.0.9 nhid 39 via 192.168.8.2 dev leaf2-eth5 proto bgp metric 20 10.0.0.8 nhid 39 via 192.168.8.2 dev leaf2-eth5 proto bgp metric 20 10.0.0.7 nhid 39 via 192.168.8.2 …

bgpd: Ensure send order is 100% consistent

---

tests/topotests/bgp_srv6l3vpn_sid/test_bgp_srv6l3vpn_sid.py

Fix the following warning:
```
tests/topotests/bgp_srv6l3vpn_sid/test_bgp_srv6l3vpn_sid.py:42
/media/SharedUTM/workspace/frr/tests/topotests/bgp_srv6l3vpn_sid/test_bgp_srv6l3vpn_sid.py:42: DeprecationWarning: invalid escape sequence '\ '
```
In test_bgp_srv6l3vpn_sid.py we have a comment containing some '\\' characters. Python mistakenly tries to interpret such '\\' characters as escape sequences, which leads to the above warning.
Let's tell Python to treat the comment as a raw string, so that it simply treats backslashes as literal characters rather than escape sequences.

tests: Fix DeprecationWarning in SRv6 L3VPN topotest

---

isisd/isis_zebra.c

When `isis_zebra_process_srv6_locator_chunk()` returns prematurely due to an error, do not forget to free memory allocated by `srv6_locator_chunk_alloc()`.

isisd: Fix memory leaks when IS-IS fails to process an SRv6 locator chunk

---

lib/vty.c

Coverity is complaining that vty->state could be VTY_PASSFD here.  It can't, it really shouldn't, and if it actually is then something went seriously wrong somewhere earlier so assert()ing out is the best thing to do.

lib: assert for VTY_PASSFD expectations
