FRRouting/frr

ospfd/ospf_asbr.c
Fixes a memory leak in ospfd where the external aggregator was not released after its associated route node is deleted.
```
Address Sanitizer Error detected in ospf_basic_functionality.test_ospf_asbr_summary_topo1/r0.asan.ospfd.31502
==31502==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 200 byte(s) in 5 object(s) allocated from:
#0 0x7fdb30665d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7fdb300620da in qcalloc lib/memory.c:105
#2 0x55e53c2da5fa in ospf_external_aggregator_new ospfd/ospf_asbr.c:396
#3 0x55e53c2dead3 in ospf_asbr_external_aggregator_set …
```
=> ospfd: Fix External Aggregator Leak

bgpd/bgp_debug.c, bgpd/bgp_vty.c
following crash occurs:
at ./nptl/pthread_kill.c:44
at ./nptl/pthread_kill.c:78
at ./nptl/pthread_kill.c:89
context=0x7ffd06d3d300)
at /build/make-pkg/output/_packages/cp-routing/src/lib/sigevent.c:246
length=0x7ffd06d3da88, exact=1, var_len=0x7ffd06d3da90, write_method=<optimized out>)
at /build/make-pkg/output/_packages/cp-routing/src/bgpd/bgp_snmp_bgp4v2.c:364
vp=vp@entry=0x7f7c88b584c0 <bgpv2_variables>, vp_len=vp_len@entry=102,
ename=ename@entry=0x7f7c88b58440 <bgpv2_trap_oid>, enamelen=enamelen@entry=8,
name=name@entry=0x7f7c88b58480 <bgpv2_oid>, namelen=namelen@entry=7,
iname=0x7ffd06d3e7b0, index_len=1, trapobj=0x7f7c88b53b80 <bgpv2TrapBackListv6>,
trapobjlen=6, sptrap=2 '\002')
at /build/make-pkg/output/_packages/cp-routing/src/lib/agentx.c:382
vp_len=vp_len@entry=102, …
=> bgpd: fix crash in *bgpv2PeerErrorsTable"

doc/developer/workflow.rst
Align to the release rules:
Releases are scheduled in a 4-month cycle on the first Tuesday each March/July/November.
=> doc: Fix release dates in workflow

lib/command.c, lib/vty.c, vtysh/vtysh.c
```
vty: fix configure terminal argument descriptions
"terminal" and "file-lock" description are mixed up.
```
```
vty: fix working in file-lock mode
When the configuration node is entered in file-lock mode, candidate
and running datastores are locked. Any configuration change is followed
by an implicit commit which leads to a crash of mgmtd, because double
lock is prohibited by an assert. When working in file-lock mode, we
shouldn't do implicit commits which is disabled by allowing pending
configuration changes.
```
```
vtysh: fix entering configuration node in file-lock mode
When the config node is entered in file-lock mode, we should actually
remember it to correctly apply the workaround in `vtysh_exit`.
Otherwise, the file-lock mode is dropped once we exit any node one level
below the …
```
=> Fixes for `file-lock` mode of configuration node

doc/developer/building-frr-for-ubuntu2204.rst, doc/developer/checkpatch.rst, doc/developer/cli.rst, doc/developer/cspf.rst, doc/developer/index.rst, doc/developer/ospf.rst, doc/developer/topotests.rst, doc/developer/workflow.rst
* Whitespace & syntax errors
* Grammar errors
* checkpatch and CSPF docs were not included in index and thus unreachable except by search, fix it
=> fix various developer doc issues

doc/developer/.readthedocs.yaml, doc/user/.readthedocs.yaml
As of Sep 25 2023, RTD projects require config files to build. This patch is necessary for docs to continue to build.
=> doc: add .readthedocs.yaml configs

mgmtd/mgmt_vty.c
When the command is called without specifying the datastore, it crashes.
=> mgmtd: fix crash on "show mgmtd datastore-contents"

bgpd/bgp_network.c
When we accept a connection, we try to set TTL for the socket, but the socket is not yet created and we are trying to set it on the wrong socket fd.
```
[Event] connection from 127.0.0.1 fd 25, active peer status 3 fd -1
can't set sockopt IP_TTL 255 to socket -1
bgp_set_socket_ttl: Can't set TxTTL on peer (rtrid 0.0.0.0) socket, err = 9
Unable to set min/max TTL on peer 127.0.0.1, Continuing
```
=> bgpd: Set the TTL for the correct socket

doc/user/zebra.rst, zebra/label_manager.c, zebra/subdir.am
In zebra/label_manager.c the releasing of the label chunk is done by disowning the chunk to the system. The presence of this system label chunk will cause label assignment to fail for this use case example:
label chunk ospf: 300-320
label chunk system: 510-520
label chunk isis: 1200-1300
Then we try to allocate the chunk 500-530, we get this error:
"Allocation of mpls label chunk [500/530] failed"
The error is raised when the below condition is true:
/* if chunk is used, cannot honor request */
if (lmc->proto != NO_PROTO)
return NULL;
Delete the label chunk instead of disowning it when the label releasing is done.
Signed-off-by: Farid MIHOUB <farid.mihoub@6wind.com>
=> zebra: delete label chunk upon release

lib/darr.c
I believe coverity is complaining that the current code does not handle the realloc fail case, in which case the original pointer is not freed, but NULL is returned. The code assert()s it's not failed but that is not strong enough it needs to abort which XREALLOC does and is a better integration into FRR-inrfa anyway.
=> lib: use XREALLOC over realloc avoid coverity warning

lib/plist.c
Fixes #14392 .
This PR reverts #13369 fix in favor of a optimized lookup function that uses the trie instead of the linked list to find duplicated prefix.
=> lib: fix route map duplicated prefix removal evaluation

staticd/static_vty.c
XSTRDUP and then calling strsep mangles the
pointer returned by XSTRDUP.  Keep a copy
of the orig and when we are done, free that instead.
=> staticd: Memory leak of string in staticd

pimd/pim_msdp.c, pimd/pim_msdp_packet.c
The current implementation sends MSDP Source Active (SA) messages with incorrect RP for the local multicast sources. They indicate the local address used to establish the connection to the MSDP peer as the RP. The correct is to indicate the RP that has been configured via the command "ip pim rp A.B.C.D A.B.C.D/M".
This pull request changes the MSDP SA messages so they indicate the correct RP for local multicast sources.
=> pimd: Indicating the configured PIM Rendezvous Point (RP) in the MSDP SA message

isisd/isis_nb.c, isisd/isis_nb.h, isisd/isis_nb_config.c
Fixes startup warnings:
```
ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-isisd:isis/instance/segment-routing-srv6/msd/node-msd/max-segs-left'
ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-isisd:isis/instance/segment-routing-srv6/msd/node-msd/max-end-pop'
ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-isisd:isis/instance/segment-routing-srv6/msd/node-msd/max-h-encaps'
ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-isisd:isis/instance/segment-routing-srv6/msd/node-msd/max-end-d'
```
=> isisd: remove redundant northbound destroy callbacks

zebra/zapi_msg.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h
The iprule/pbr rule object has a vrf id, and zebra uses that internally, but the vrf id isn't returned to clients who install rules and are waiting for results. Include the vrf_id sent by the client in the zapi result notification message; update the existing clients so they decode the id.
=> lib,*: add vrf id to pbr rule results zapi message

zebra/redistribute.c
`ng` was not properly freed, leading to a memory leak. The commit calls `nexthop_group_delete` to free memory associated with `ng`.
```
Address Sanitizer Error detected in isis_topo1.test_isis_topo1/r5.asan.zebra.24308
==24308==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 32 byte(s) in 1 object(s) allocated from:
#0 0x7f4f47b43d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7f4f4753c0a8 in qcalloc lib/memory.c:105
#2 0x7f4f47559526 in nexthop_group_new lib/nexthop_group.c:270
#3 0x562ded6a39d4 in zebra_add_import_table_entry zebra/redistribute.c:681
#4 …
```
=> zebra: Free nexthop_group

bgpd/bgp_aspath.c
They are already initialized via assegment_new().
=> bgpd: Drop redundant assignment for aspath segment type and length

pimd/pim_iface.c
`pimregX` of specific vrf can be deleted from kernel after this vrf                                                                                                          
is deleted.  However, then `pimdregX` will never come back to                    
kernel after adding it ( the same vrf ) back.  That is to say, it exists            
only in daemon, but not in kernel.                                               
The root cause is this `pimregX` is not really deleted for its special              
usage, and `pim_if_create_pimreg()` wants reusing it.                            
I have tried 4 solutions:                                                        
1. Remove the `configured` flag of `pimregX`, allow its deletion.                
A few timers still use `pimregX` after its …
=> pimd: Fix missing pimreg interface

bgpd/bgp_advertise.c, bgpd/bgp_advertise.h, bgpd/bgp_updgrp_adv.c
BGP is storing outgoing updates in a couple of different fifo's.  This is to ensure proper packet packing of all bgp_dests that happen to use the same attribute.
How it's all put together currently:  On initial update BGP walks through all the bgp_dest's in a table.  For each path being sent a bgp_advertise is created.  This bgp_advertise is placed in fifo order on the bgp_synchronize->update queue. The bgp_advertise has a pointer to the bgp_advertise_attr which is associated iwth the actual attribute that is being sent to it's peer.  In turn this bgp_advertise is placed in a fifo off of the bgp_advertise_attr structure.  As such as we have paths that share an attribute, the path/dest is placed on the bgp_syncrhonize->update fifo as well as being placed on the fifo associated with the …
=> bgpd: Convert the bgp_advertise_attr->adv to a fifo

lib/event.c, vtysh/vtysh_main.c
Running ping/traceroute/etc. (any kind of commands that use execute_command() suffer with this kind of warnings.
Related: https://github.com/FRRouting/frr/issues/14412
=> lib: Suppress HOB/STARVATION warnings when running in vtysh

eigrpd/eigrp_interface.c
Trying to delete an interface during the test `test_eigrp_topo1.py` triggers a crash.
```
2023/10/10 19:12:25.299840 EIGRP: [T6888-VVP0Y] Zebra: Interface[r1-eth0] state change to down.
2023/10/10 19:12:25.301524 EIGRP: [ZNQW6-A3MDH] Zebra: interface delete r1-eth0 index 2 flags 1002 metric 0 mtu 1500
2023/10/10 19:12:25.301529 EIGRP: lib/memory.c:73: mt_count_free(): assertion (mt->n_alloc) failed
EIGRP: Received signal 6 at 1696954345 (si_addr 0x840006315b, PC 0x7f246ad7200b); aborting...
EIGRP: zlog_signal+0x1b1                  7f246b04004b     7ffff0df59b0 /usr/lib//frr/libfrr.so.0 (mapped at 0x7f246af74000)
EIGRP: core_handler+0xfc                  7f246b08fc33     7ffff0df5ae0 /usr/lib//frr/libfrr.so.0 (mapped at 0x7f246af74000)
EIGRP: funlockfile+0x60 …
```
=> eigrp: use correct memory pool on interface deletion

mgmtd/mgmt.h
This is clashing with PIMv6 (2622).
=> mgmtd: Change MGMTD_VTY_PORT to 2623

nhrpd/nhrp_cache.c, nhrpd/nhrp_main.c, nhrpd/nhrp_peer.c
- Addressed memory leak by removing `&c->peer_notifier` from the notifier list on termination. Retaining it caused the notifier list to stay active, preventing the deletion of `c->cur.peer` thereby causing a memory leak.
- Reordered termination steps to call `vrf_terminate` before `nhrp_vc_terminate`, preventing a heap-use-after-free issue when `nhrp_vc_notify_del` is invoked in `nhrp_peer_check_delete`.
- Added an if statement to avoid passing NULL as hash to `hash_release`, which leads to a SIGSEGV.
```
Address Sanitizer Error detected in nhrp_topo.test_nhrp_topo/r1.asan.nhrpd.20265
==20265==ERROR: …
```
=> nhrpd: Fix nhrp_peer leak

bgpd/bgp_mplsvpn.c
bgp_orig is never NULL in the code path, and coverity is angry on this.
Let's remove this test at all.
Coverity 1566808
=> bgpd: Remove redundant check for bgp against NULL

zebra/kernel_netlink.c
Add the RTM_xxxCHAIN netlink message codes to the callback that may see them; this prevents zebra from logging errors about the unknown message types. We ignore these (for now).
Fixes: #14575
=> zebra: add xxxCHAIN netlink messages to handler, ignore

lib/mgmt_msg.c, lib/mgmt_msg.h, mgmtd/mgmt.c, mgmtd/mgmt_vty.c
When short circuiting is requested the caller can count on that being the connection type they get.
=> lib: msg: make short-circuit connections guaranteed

bgpd/bgp_mplsvpn.c
The shallow copy of attr wasn't freed when there was no valid label for the moment and the function return therefore creating leaks. The leak below are solved by flushing the shallow copy of attr.
```Address Sanitizer Error detected in bgp_vpnv6_per_nexthop_label.test_bgp_vpnv6_per_nexthop_label/r1.asan.bgpd.13409 ================================================================= ==13409==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 280 byte(s) in 7 object(s) allocated from:
#0 0x7f62cd0c9d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7f62ccac21c3 in qcalloc lib/memory.c:105
#2 0x5623b8810dc8 in ecommunity_dup bgpd/bgp_ecommunity.c:252
#3 0x5623b88be8eb in vpn_leak_from_vrf_update bgpd/bgp_mplsvpn.c:1628
#4 0x5623b88c13b3 in …
```
=> bgpd: ecommunity_dup memory leak fix

zebra/label_manager.c, zebra/label_manager.h
When the label manager is unable to provide a label chunk to a routing service, an error message is displayed:
> Oct 11 11:47:27 vsr zebra[163745]: [YMY6E-K9JYD][EC 4043309085] Unable to assign Label Chunk [60;60] to bgp instance 0
There is missing information on the range that was requested. Add this information in the log message.
> Oct 11 11:47:27 vsr zebra[163745]: [YMY6E-K9JYD][EC 4043309085] Unable to assign Label Chunk [60;60] to bgp instance 0
=> zebra: add label chunk range in log when label manager request fails

ospf6d/ospf6_asbr.c
When redistributing a local route, ensure the forwarding address field of AS-External LSAs is only set when the associated nexthop interface is OSPF-enabled. This is necessary because the OSPF RFC requires that the AS-External LSA forwarding address should be resolvable using an intra-area or inter-area path.
Fixes #14462.
=> ospf6d: fix setting of the forwarding address in AS-External LSAs

ldpd/init.c
Clarify the fatal error message recorded when an error situation happens.  Disambiguating the default case from the TLV_TYPE_DYNAMIC_CAP case.
=> ldpd: Clarify error situation for different problems

tests/topotests/bgp_evpn_route_map_match/c1/frr.conf, tests/topotests/bgp_evpn_route_map_match/c2/frr.conf, tests/topotests/bgp_evpn_route_map_match/r1/frr.conf, tests/topotests/bgp_evpn_route_map_match/r2/frr.conf, tests/topotests/bgp_evpn_route_map_match/test_bgp_evpn_route_map_match.py
Related: https://github.com/FRRouting/frr/issues/14419
=> tests: Check if evpn route-map match by route type works

pimd/pim_register.c
Syscall param sendmsg(msg.msg_iov[0]) points to uninitialised byte(s) at 0x4975157: sendmsg (sendmsg.c:28)
==2263111==    by 0x1413BE: pim_msg_send_frame (pim_pim.c:629)
==2263111==    by 0x1413BE: pim_msg_send (pim_pim.c:743)
==2263111==    by 0x1425DC: pim_register_send (pim_register.c:332)
==2263111==    by 0x1427EE: pim_null_register_send (pim_register.c:443)
==2263111==    by 0x14D228: pim_upstream_register_stop_timer (pim_upstream.c:1608)
==2263111==    by 0x48CE6DF: thread_call (thread.c:1693)
==2263111==    by 0x4899EFF: frr_run (libfrr.c:1068)
==2263111==    by 0x11D035: main (pim6_main.c:190)
==2263111==  Address 0x1ffeffdcb1 is on thread 1's stack
==2263111==  in frame #2, created by pim_register_send (pim_register.c:273)
==2263111==  Uninitialised value …
=> pim6d: valgrind issue fixes

doc/user/bgp.rst
With the deprecation of the global "bgp enforce-first-as" command back in https://github.com/FRRouting/frr/pull/2259 the newly introduced option to enable that setting on a specific peer was not documented. This commit adds the necessary documentation and states the command's default.
=> doc: add "enforce-first-as" to BGP documentation

watchfrr/watchfrr.c
When testing GR features, it is desired to kill bgp (or really any daemon )and not immediately have bgp start up again. Modify the code to not attempt to restart the daemon by hand to let us developers work when the `watchfrr ignore XXX` command is issued.
Testing:
watchfrr ignore bgpd
kill -9 bgpd
start bgp by `/usr/lib/frr/watchfrr.sh start bgpd` at some point in time in the future
leaf-1# show watchfrr
watchfrr global phase: Idle
Restart Command: "/usr/lib/frr/watchfrr.sh restart %s"
Start Command: "/usr/lib/frr/watchfrr.sh start %s"
Stop Command: "/usr/lib/frr/watchfrr.sh stop %s"
Min Restart Interval: 60
Max Restart Interval: 600
Restart Timeout: 90
zebra                Up
bgpd                 Up/Ignoring Timeout
staticd              Up
leaf-1#
=> watchfrr: Extend ignore option to daemon being killed

lib/northbound.c
This was true when we had only a CLI for configuration. Now mgmtd has a public frontend interface that can be used by external applications, and they can send invalid requests that lead to errors.
This is still true for CLI though, so the same comment still stays in `nb_cli_apply_changes_internal`.
=> lib: remove incorrect comment from northbound

bgpd/bgp_conditional_adv.c, tests/topotests/bgp_conditional_advertisement_static_route/r1/frr.conf, tests/topotests/bgp_conditional_advertisement_static_route/r2/frr.conf, tests/topotests/bgp_conditional_advertisement_static_route/r3/frr.conf, tests/topotests/bgp_conditional_advertisement_static_route/test_bgp_conditional_advertisement_static_route.py
Closes https://github.com/FRRouting/frr/issues/14598
=> bgpd: Do not suppress conditional advertisement updates if triggered

doc/developer/topotests.rst, tests/topotests/conftest.py, tests/topotests/lib/topotest.py
When specified `--gdb-use-emacs` will launch the daemon with gdb inside a running emacs server using `emacsclient --eval` commands.
=> tests: add --gdb-use-emacs option

zebra/debug_nl.c
Print the ifname with netlink LINK debug output (pretty useful to see...)
=> zebra: debug ifname in netlink link debugs

bgpd/bgp_snmp.c, bgpd/bgp_snmp.h, bgpd/bgp_snmp_bgp4.c, bgpd/bgp_snmp_bgp4.h, bgpd/bgp_snmp_bgp4v2.c, bgpd/bgp_snmp_bgp4v2.h, bgpd/bgp_vty.c, bgpd/bgpd.h, bgpd/subdir.am, doc/user/snmptrap.rst, tests/topotests/bgp_snmp_bgp4v2mib/r2/snmpd.conf, tests/topotests/bgp_snmp_bgp4v2mib/r2/snmptrapd.conf, tests/topotests/bgp_snmp_bgp4v2mib/test_bgp_snmp_bgp4v2mib.py, tests/topotests/lib/snmptest.py, tests/topotests/lib/topogen.py, tests/topotests/lib/topotest.py
this pull request add the support of traps for bgp4-mibv2. It is
conformant to draft-ietf-idr-bgp4-mibv2-11.
bgp4V2EstablishedNotification and bgp4V2BackwardTransitionNotification.
since the MIB bgp4-mibv2 notification are  redundant with MIB RFC4273
we added a  2 commands for avoiding conflicts.
bgp snmp traps rfc4273<enable|disable>
bgp snmp traps bgp4-mibv2<enable|disable>
=> bgpd: add support of traps for bgp4-mibv2 

tests/topotests/all_protocol_startup/test_all_protocol_startup.py, zebra/zebra_nhg.c
Zebra currently does a shortest prefix match for
resolving nexthops for a prefix.  This is typically an ok thing to do but fails in several specific scenarios. If a nexthop matches to a route that is not usable, nexthop resolution just gives up and refuses to use that particular route.  For example if zebra currently has a covering prefix say a 10.0.0.0/8.  And about the same time it receives a 10.1.0.0/16 ( a more specific than the /8 ) and another route A, who's nexthop is 10.1.1.1.  Imagine the 10.1.0.0/16 is processed enough to know we want to install it and the prefix is sent to the dataplane for installation( it is queued ) and then route A is processed, nexthop resolution will fail and the route A will be left in limbo as uninstallable.
Let's modify the nexthop resolution code in …
=> zebra: Allow longer prefix matches for nexthops

lib/mgmt.proto, lib/mgmt_be_client.c, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_txn.c, mgmtd/mgmt_txn.h
The config is always applied fully, all batches are included. There's no
need to pass a list of applied batches as it always contains all of
them.
=> mgmtd, lib: remove batch ids from cfg apply reply 

doc/user/pbr.rst, pbrd/pbr_vty.c
'detail' and 'josn' keyword is given as an optional parameter for cli arguments. Hence 'detail' keyword was consider as a pbr 'name' for "show pbr map detail json" command.
Before Fix:
```
cumulus#
cumulus# show pbr map detail json
[
]
cumulus#
```
After Fix:
```
cumulus# show pbr map detail json
[
{
"name":"MAP1",
"valid":false,
"policies":[
{
"id":1,
"sequenceNumber":10,
"ruleNumber":309,
"vrfUnchanged":false,
"installed":false,
"installedReason":"Invalid Src or Dst",
"vrfName":"default"
}
]
}
]
cumulus#
```
=> pbrd: fix show pbr map detail json

ospf6d/ospf6_interface.c, tests/topotests/bgp_vpn_5549_route_map/test_bgp_vpn_5549_route_map.py, tests/topotests/ospf6_gr_topo1/rt1/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt2/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt3/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt4/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt5/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt6/show_ipv6_route.json, tests/topotests/ospf6_gr_topo1/rt7/show_ipv6_route.json, tests/topotests/ospf6_loopback_cost/r1/frr.conf, tests/topotests/ospf6_loopback_cost/r2/frr.conf, tests/topotests/ospf6_loopback_cost/test_ospf6_loopback_cost.py
Closes https://github.com/FRRouting/frr/issues/14632
=> ospf6d: Set loopback interface cost to 0

zebra/interface.c
Display ptmStatus in correct order in show interface json output.
=> zebra: display ptmStatus order in interface json

lib/vty.c, lib/vty.h, ospfd/ospf_vty.c, pimd/pim_cmd.c, zebra/zebra_vxlan.c
This is addressing remaining places returning
empty dict, earlier PR-13214 addressed few places.
Code has been changed to return {} for all the evpn clis when evpn is disabled or no entry available.
```
cumulus@r2:mgmt:~$ sudo vtysh -c "show evpn json"
cumulus@r2:mgmt:~$
```
After Fix:-
```
cumulus@r1:mgmt:~$ sudo vtysh -c "show evpn json"
{
}
cumulus@r1:mgmt:~$
```
=> zebra:returns empty dict when evpn is disabled II

ospf6d/ospf6_top.c, ospfd/ospf_vty.c
```
r1# sh ipv6 ospf6 summary-address
VRF Name: default
aggregation delay interval :5(in seconds)
```
Just hit this random and looks ugly, let's fix it.
=> ospfd, ospf6d: Fix spacing nit for `show ... summary-address` command

doc/developer/topotests.rst, tests/topotests/lib/topotest.py
Allows you to run daemons under valgrind integrated with gdb. When daemons are run with the ``--gdb-daemons/--gdb-routers`` options they will be wired up to valgrind using vgdb (valgrind tool) so gdb will stop when valgrind errors are encountered.
=> tests: add gdb integration with valgrind

lib/mgmt_msg.c
- Free the outbound stream on destroy.
=> lib: mgmt_msg: fix a valgrind memleak

zebra/rt_netlink.c
Currently in the single nexthop case w/ evpn sending down via the FPM the encap type is not being set
for the nexthop.
This looks like the result of some code reorg for the nexthop happened but the fpm failed to be accounted for. Let's just move the encap type encoding to where it will happen.
=> zebra: Add encap type when building packet for FPM

doc/developer/northbound/demos.rst, doc/developer/northbound/ppr-basic-test-topology.rst, doc/developer/northbound/retrofitting-configuration-commands.rst, doc/developer/northbound/yang-tools.rst, doc/developer/topotests.rst
A few fixups to clean up some dev doc warnings, in the northbound files especially.
=> docs: clean up some developer doc warnings

pathd/path_pcep_cli.c
Yet another pcep **no commands** to add:
- **no pcep**: delete all the pcep configuration
- **no msd**: decofigure the pcc msd node
=> Add missing pcep no commands

pimd/pim_upstream.c
In the scenario on an intermediate router where a *,G join has been received and a S,G stream is being sent through that router on the *,G stream, there exists a situation when the *,G in has been pruned but the stream is still being received on on incoming interface towards
the RP for the *,G.   In this situation PIM will see the S,G stream
initially as a NOCACHE from the dataplane, PIM will then do a RPF
for the S and notice that it is supposed to be coming in on adifferent
interface.  In this case PIM the original PIM code would create
a blackhole mroute towards the RPF of the *,G( the interface the
stream is being received on ).  The original reason for this is that
if there is a scenario where this particular S1,G stream is sending
at basically line rate, and there also happens to be …
=> pimd: Ensure upstream points at the correct rpf

tools/frr-reload.py
Fix frr-reload script to only render 'no description' rather than 'no description blah'
Testing:
```
route-map TEST permit 140
description rule for PFIX_IPV6_7
match ipv6 address prefix-list PFIX_IPV6_7
exit
!
end
torc-11# confi t
torc-11(config)# route-map TEST permit 140
torc-11(config-route-map)# no description rule for PFIX_IPV6_7 % Unknown command: no description rule for PFIX_IPV6_7
torc-11(config-route-map)# no description rule
% There is no matched command.
torc-11(config-route-map)# no description
<cr>
torc-11(config-route-map)# no description
torc-11(config-route-map)#
```
Using frr-reload failure log:
```
2023-10-31 00:30:31,972  INFO: Failed to execute route-map TEST permit 140  no description rule for PFIX_IPV6_7 exit 2023-10-31 00:30:31,972 ERROR: "route-map TEST permit 140 …
```
=> tools: fix frr-reload route-map desc cmd

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_packet.c
Found when fuzzing, in the normal case, such packets can't exist at all.
=> bgpd: A couple more bgpd crash fixes for malformed packets 

babeld/babel_main.c, bfdd/ptm_adapter.c, bgpd/bgp_zebra.c, eigrpd/eigrp_interface.c, isisd/isis_circuit.c, ldpd/ldp_zebra.c, lib/if.c, lib/if.h, nhrpd/nhrp_main.c, ospf6d/ospf6_interface.c, ospfd/ospf_interface.c, pbrd/pbr_main.c, pimd/pim_iface.c, ripd/rip_interface.c, ripngd/ripng_interface.c, sharpd/sharp_zebra.c, staticd/static_zebra.c, vrrpd/vrrp_zebra.c, zebra/interface.c
...so that multiple functions can be subscribed.
The create/destroy hooks are renamed to real/unreal because that's what they *actually* signal.
---
Pulled out of a pile of other work.
=> lib: convert `if_zapi_callbacks` into actual hooks

pathd/path_pcep.h, pathd/path_pcep_cli.c
Rework "debug pathd pcep [...]" command to support the following configurations:
- configure one debugging log type at a time.
- deconfigure one debugging log type at a time.
- configure all debugging logs in one shot.
- deconfigure all debugging logs in one shot.
=> pathd: rework debug pathd pcep command

lib/buffer.h, lib/if.h, lib/workqueue.c, lib/workqueue.h, tests/lib/test_heavy_wq.c, zebra/zebra_script.c
See individual patches for discussion
=> Workqueue cleanup

isisd/isis_srv6.c, isisd/isis_srv6.h
`isis_srv6_area_init` should not use `yang_get_default_*` functions for fabricd.
Fixes: https://github.com/FRRouting/frr/issues/14722
=> isisd: Fix crash when enabling OpenFabric on an interface

bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c, bgpd/bgpd.h
Reverts FRRouting/frr#14648
This PR was marked as `Do Not Merge`  Reverting as that it is not ready
=> Revert "bgpd: combine import_check_table and nexthop_check_table"

zebra/main.c, zebra/rib.h, zebra/rt_netlink.c, zebra/zebra_router.h, zebra/zebra_vty.c
1) add to `show zebra` the v6_rr_semantics flag
2) Move v6_rr_semantics to zrouter
Long term we need to figure out how to figure this out so we don't need to carry this anymore.  v6_rr_semantics is fixed in latest kernels as far as I can tell now
=> V6 rr semantics zrouter

zebra/redistribute.c, zebra/zebra_neigh.c, zebra/zebra_neigh.h
Without this patch, static ARP entries remain active even if the interface is down, but the kernel already removed them.
Closes https://github.com/FRRouting/frr/issues/14652
=> zebra: Remove static ARP entries on interface down events

mgmtd/mgmt_txn.c
When validating the config, we shouldn't also validate state.
=> mgmtd: fix local validation

lib/northbound.c, lib/northbound.h, mgmtd/mgmt_ds.c, mgmtd/mgmt_txn.c
The code doesn't work at all. It tries to use libyang operation metadata in a regular (not diff) data tree, and regular data trees don't provide this data. Also, for destroy operations, it searches for nodes in the running config, which may not have the deleted nodes if we're not using implicit commits.
@pushpasis @choppsv1 I'm adding a `do not merge` label in case I am missing something. Please, take a look before I remove the label.
=> mgmt: delete candidate scratch buffer

bgpd/bgp_zebra.c
Add guard for `zlog_debug` when bgpd is not connected to zebra or zebra does not know the bgp instance.
=> bgpd: Add missing guard for `zlog_debug`

bgpd/bgp_snmp_bgp4v2.c
I recieve the following error with GCC 9.4.0:
```
In file included from /usr/include/string.h:495,
from ./lib/zebra.h:23,
from bgpd/bgp_snmp_bgp4v2.c:7:
In function ‘memset’,
inlined from ‘bgp4v2PathAttrLookup’ at bgpd/bgp_snmp_bgp4v2.c:605:3,
inlined from ‘bgp4v2PathAttrTable’ at bgpd/bgp_snmp_bgp4v2.c:747:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:10: error: ‘__builtin_memset’ offset [9, 20] from the object at ‘paddr’ is out of the bounds of referenced subobject ‘_v4_addr’ with type ‘struct in_addr’ at offset 4 [-Werror=array-bounds]
71 |   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> bgpd: fix build error

lib/northbound.c
mgmtd frees all non-NULL change->value variables at the end of every commit. We shouldn't assign change->value with data returned by libyang to prevent freeing of library-allocated memory.
=> lib: fix possible freeing of libyang data

lib/command.h, lib/mgmt_be_client.c, lib/mgmt_fe_client.c, mgmtd/mgmt_vty.c, tools/valgrind.supp, vtysh/vtysh_config.c
- Cannot have 2 cmd_node's with same .node number. Install the mgmtd client library debug nodes (client frontend and client backend) using new unique node numbers. Fixes memleaks.
- Fix "debug mgmt client backend" to generate correct config (and not for frontend).
- Also suppress some normal external lib reachable valgrind memleaks, this allows a clean valgrind run with memleak type "all"
=> lib: mgmtd: fix debug cli commands and memleaks

lib/darr.c, lib/darr.h
Was using XREALLOC() and then free(). instant "memleaks".
=> lib: darr needs to use memory.h for both alloc and free

lib/mgmt_be_client.c, lib/northbound.c, lib/northbound.h, lib/northbound_cli.c, lib/vty.c, lib/vty.h, mgmtd/mgmt_txn.c, mgmtd/mgmt_vty.c
`nb_cli_apply_changes` can be called with base xpath which should be prepended to xpaths of every change in a transaction. This base xpath is respected by regular northbound CLI but not by mgmtd. This commit fixes the problem.
=> lib, mgmtd: respect base xpath in mgmtd

bgpd/bgp_label.c, bgpd/bgp_mpath.c, bgpd/bgp_updgrp_adv.c, bgpd/bgp_zebra.c
Let's use the natural data structure in bgp for the prefix display instead of a bunch of places where we call a translator function. The %pBD does this and actually ensures data is correct. Also fix a few spots in bgp_zebra.c where the cast to a NULL pointer causes the catcher functionality to not work and fix the resulting crash that resulted.
=> bgpd: Used %pBD instead of %pRN

bgpd/bgp_snmp_bgp4v2.c
CID 1570969 Overrun
/bgpd/bgp_snmp_bgp4v2.c: 534 in bgp4v2PathAttrLookup() /bgpd/bgp_snmp_bgp4v2.c: 575 in bgp4v2PathAttrLookup() /bgpd/bgp_snmp_bgp4v2.c: 514 in bgp4v2PathAttrLookup()
>>>     CID 1570969:    (OVERRUN)
>>>     Overrunning array "bgp->rib" of 4 64-byte elements at element index 4 (byte offset 319) using index "afi" (which evaluates to 4).
=> bgpd: fix coverity issue in bgp_snmp_bgp4v2.c

bgpd/bgp_bmp.c, bgpd/bgp_bmp.h, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_trace.h, doc/developer/bmp.rst, doc/developer/subdir.am, doc/user/bmp.rst, tests/topotests/bgp_bmp/test_bgp_bmp.py, tests/topotests/lib/bmp_collector/bmp.py
BMP Loc-Rib Monitoring (RFC9069) Implementation
implementation uses a new secondary queue structure specific to loc-rib monitoring
Currently done : 
- Loc-Rib Monitoring (config `bmp monitor afi safi loc-rib`)
- Loc-Rib Syncing
- set Peer-Flag to 3 for Loc-Rib Monitoring Messages
- set Peer-Distinguisher for Loc-Rib Monitoring Messages
- Loc-Rib EOR messages
- added VRF/Table Name TLV util function (not added to Peer Up/Down messages yet)
- added `bgp_rib_uptime` field to `bgp_path_info_extra` for use in Loc-RIB RM Timestamps
- documentation
=> bgpd: BMP Loc-Rib Monitoring (RFC9069) Implementation

isisd/isis_pdu.c, tests/topotests/isis_lsp_bits_topo1/rt6/step1/show_yang_interface_isis_adjacencies.ref
I added a new variable to calculate the required level of neighborhood,
as well as checking if the interfaces are in the same area,
in accordance with cisco
Signed-off-by: Sososhas <1248756005hfh@gmail.com>
=> isisd:change ngh lvl when int circuit type setted

zebra/if_netlink.c
this feature is to support teamd driver when configing ethernet segment's id and sys_mac via vtysh/zebra.
there are 2 approaches to support lacp protocol.
1st:  linux bonding driver via tool (ifenslave_2.13~deb11u1_all.deb) via ip link cli command.
2nd: via teamd driver by nlmsg
https://github.com/jpirko/libteam/blob/master/libteam/libteam.c#L477
example for nlmsg from bonding driver:
https://cpp.hotexamples.com/examples/-/-/rtnl_link_add/cpp-rtnl_link_add-function-examples.html
comparison between bonding driver and teamd driver:
https://github.com/jpirko/libteam/wiki/Bonding-vs.-Team-features
hence, support teamd driver as what bonding driver does. we should add teamd nlmsg as bond type so that we are able to config associated es data.
=> zebra: supports to listen teamd nlmsg as bond type

lib/sockopt.c
For some series of calls in FREEBSD setting the SO_RCVBUF size will always fail under freebsd.  This is no bueno since the setsockopt_so_recvbuf call goes into an infinite loop.
(gdb) bt
0  setsockopt () at setsockopt.S:4
1  0x0000000083065870 in setsockopt_so_recvbuf (sock=15, size=0) at lib/sockopt.c:26
2  0x00000000002bd200 in ospf_ifp_sock_init (ifp=<optimized out>, ifp@entry=0x8d1dd500) at ospfd/ospf_network.c:290
3  0x00000000002ad1e0 in ospf_if_new (ospf=0x8eefc000, ifp=0x8d1dd500, p=0x8eecf1c0) at ospfd/ospf_interface.c:276
4  0x0000000000304ee0 in add_ospf_interface (co=0x8eecbe10, area=0x8d192100) at ospfd/ospfd.c:1115
5  0x00000000003050fc in ospf_network_run_interface (ospf=0x8eefc000, ifp=0x8d1dd500, p=0x80ff63f8, given_area=0x8d192100)
at ospfd/ospfd.c:1460
6 …
=> lib: Prevent infinite loop in ospf

zebra/zebra_rnh.c
Fix memory leaks by allocating `json_segs` conditionally on `nexthop->nh_srv6->seg6_segs`. The previous code allocated memory even when not in use or attached to the JSON tree.
```
Direct leak of 3240 byte(s) in 45 object(s) allocated from:
#0 0x7f6e84a35d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7f6e83de9e6f in json_object_new_array (/lib/x86_64-linux-gnu/libjson-c.so.3+0x3e6f)
#2 0x564dcab5c1a6 in vty_show_ip_route zebra/zebra_vty.c:705
#3 0x564dcab5cc71 in do_show_route_helper zebra/zebra_vty.c:955
#4 0x564dcab5d418 in do_show_ip_route zebra/zebra_vty.c:1039
#5 0x564dcab63ee5 in show_route_magic zebra/zebra_vty.c:1878
#6 0x564dcab63ee5 in show_route zebra/zebra_vty_clippy.c:659
#7 0x7f6e843b6fb1 in …
```
=> zebra: Refactor memory allocation in zebra_rnh.c

babeld/babel_interface.c
Release memory allocated for the IPv4 address during the interface reset. The addition of `free(babel_ifp->ipv4)` ensures proper cleanup, preventing potential memory leaks.
```
Address Sanitizer Error detected in babel_topo1.test_babel_topo1/r2.asan.babeld.18864
==18864==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 2 object(s) allocated from:
#0 0x7f3f4531bb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x55c1806cb28d in babel_interface_address_add babeld/babel_interface.c:112
#2 0x7f3f44de9e29 in zclient_read lib/zclient.c:4425
#3 0x7f3f44db9dfa in …
```
=> babeld: Free IPv4 Memory in interface_reset

sharpd/sharp_main.c, sharpd/sharp_nht.c, sharpd/sharp_nht.h
Implement a callback function for memory cleanup of sharp_nh_tracker. Specifically, set `sharp_nh_tracker_free` as the deletion function for the `sg.nhs` list. This ensures proper cleanup of resources when elements are removed.
```
Address Sanitizer Error detected in zebra_nht_resolution.test_verify_nh_resolution/r1.asan.sharpd.32320
==32320==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 64 byte(s) in 1 object(s) allocated from:
#0 0x7f4ee812ad28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7f4ee7b291cc in qcalloc lib/memory.c:105
#2 0x5582be672011 in …
```
=> sharpd: Set Callback Function for Memory Cleanup

lib/northbound.c, lib/yang.c
Currently, the YANG data tree validation stops on the first error that is found. As an operator has to fix all the validation errors before the config can be commited, it's useful to let them know about all the errors at once.
=> Print all errors when validating NB configuration

pimd/pim6_main.c
Mentioning few of the leaks here:
=3843268== 6 bytes in 3 blocks are still reachable in loss record 1 of 29
==3843268==    at 0x483C855: malloc (vg_replace_malloc.c:381)
==3843268==    by 0x489ED0E: qmalloc (memory.c:106)
==3843268==    by 0x48DE8DB: redist_add_instance (zclient.c:125)
==3843268==    by 0x48DF561: zclient_init (zclient.c:647)
==3843268==    by 0x14FFA3: pim_zebra_init (pim_zebra.c:527)
==3843268==    by 0x11D021: main (pim6_main.c:178)
==3843268==
==3843268== 24 bytes in 1 blocks are still reachable in loss record 2 of 29
==3843268==    at 0x484147B: calloc (vg_replace_malloc.c:1328)
==3843268==    by 0x489EE03: qcalloc (memory.c:111)
==3843268==    by 0x4878DDE: buffer_new (buffer.c:72)
==3843268==    by 0x48DE7BF: zclient_new (zclient.c:75) …
=> pim6d: Fix memory leaks

babeld/babel_interface.c
Ensure proper memory cleanup by freeing the `babel_ifp->ipv4` when babel interface is deleted. This prevents memory leaks.
```
Address Sanitizer Error detected in all_protocol_startup.test_all_protocol_startup/r1.asan.babeld.4141
==4141==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 40 byte(s) in 10 object(s) allocated from:
#0 0x7f1cde6a9b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x562b8eff328d in babel_interface_address_add babeld/babel_interface.c:112
#2 0x7f1cde1772cb in zclient_read lib/zclient.c:4425
#3 0x7f1cde14729c in event_call lib/event.c:1980
#4 …
```
=> babeld: Free IPv4 Memory in babel_interface_free

lib/mgmt.proto, lib/mgmt_be_client.c, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_be_adapter.h, mgmtd/mgmt_txn.c, mgmtd/mgmt_txn.h
Batch IDs are only used to verify that all messages were received and processed by a backend. It's not necessary to do that as we use reliable stream transport - messages can't be dropped or received out of order.
This commit also fixes possible race condition that can happen if one backend process messages slower than other backends.
=> mgmtd, lib: remove batch ids from all messages

ospf6d/ospf6_neighbor.c
GCC is complaining prev_cost may be used uninitialized.  It really can't, but let's get rid of the warning.
=> ospf6d: fix uninitialized value warning in p2xp

lib/northbound.c
LYD_VALIDATE_MULTI_ERROR was added in libyang 2.1.36.  The currently enforced minimum of libyang is 2.0.0.  Stick an #ifdef around it.
---
Fixes #14800
=> lib: use LYD_VALIDATE_MULTI_ERROR only if available

isisd/isis_adjacency.h, isisd/isis_route.c
These were added in e38e0df01ad3 but never used anywhere.  Also the code grabs any random /32 or /128 that is directly connected to the adjacent router, which may not even be an address of that router itself.
=> isisd: remove unused router_address fields

bgpd/bgp_bmp.c, bgpd/bgp_trace.h
=> bgpd: Fix frrtrace arguments for bmp_eor tracing

vtysh/vtysh.c
The flag should be cleared to make sure it's not reused the next time we enter the config node.
=> vtysh: clean vtysh_file_locked when exiting config node

zebra/rt_netlink.c
The fpm code path in building a ecmp route for evpn has a bug that caused it to not add the encap attribute to the netlink message.  See #f0f7b285b99dbd971400d33feea007232c0bd4a9 for the single path case being fixed.
=> zebra: Fix fpm multipath encap addition

ospfd/ospf_vty.c
Small fix for the command "show ip ospf vrf NAME graceful-restart helper detail". FRR did not show information by vrf's name.
**Error description**: If i have ``` router ospf vrf red```, vtysh's command ```show ip ospf vrf red graceful-restart helper``` will not show anything. But command ```show ip ospf vrf all graceful-restart helper``` will work normally. This fix fixes the display of information by vrf's name.
=> ospfd:fix show_ip_ospf_gr_helper

bgpd/bgp_aspath.c
The function aspath_remove_private_asns was using an aspath to perform some operation and didn't free it after usage leading to the leak below.
```*********************************************************************************** Address Sanitizer Error detected in bgp_remove_private_as_route_map.test_bgp_remove_private_as_route_map/r2.asan.bgpd.27074
================================================================= ==27074==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 80 byte(s) in 2 object(s) allocated from:
#0 0x7fd0a4b95d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7fd0a45932ff in qcalloc lib/memory.c:105
#2 0x562b630b44cc in aspath_dup bgpd/bgp_aspath.c:689
#3 0x562b62f48498 in route_set_aspath_prepend bgpd/bgp_routemap.c:2283
#4 …
```
=> bgpd:aspath leak fix

bgpd/bgp_nht.c, bgpd/bgp_nht.h, bgpd/bgp_zebra.c, lib/zclient.c, lib/zclient.h, ospf6d/ospf6_zebra.c, ospfd/ospf_zebra.c, pbrd/pbr_zebra.c, pimd/pim_nht.c, pimd/pim_nht.h, pimd/pim_zebra.c, sharpd/sharp_zebra.c, staticd/static_zebra.c
All users of `ZEBRA_NEXTHOP_UPDATE` check the VRF and then call into `zapi_nexthop_update_decode` before further processing.  Move this into common code in lib/.
`zapi_nexthop_update_decode` is private at the end of this chain of commits.
---
This is prep work for further NHT refactoring & cleanup. There should be no visible/functional changes from this series of commits.
=> *: move common NHT update decoding bits into lib/

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_packet.c
commit a0c4ec2f52b299d45a77b0fcb29452329d22dce1 (HEAD -> backport_itis, donald/backport_itis)
Author: Donatas Abraitis <donatas@opensourcerouting.org>
Date:   Sun Oct 29 22:44:45 2023 +0200
bgpd: Ignore handling NLRIs if we received MP_UNREACH_NLRI
and 
commit 01f232c227e566fec924472eb61cd6489a6e1d2b
Author: Donatas Abraitis <donatas@opensourcerouting.org>
Date:   Fri Oct 27 11:56:45 2023 +0300
bgpd: Treat EOR as withdrawn to avoid unwanted handling of malformed attrs
are missing from 8.5
=> Backport a couple of fixes to 8.5

zebra/zebra_dplane.c
Fix a crash because a use-after-free.
> =================================================================
> ==1249835==ERROR: AddressSanitizer: heap-use-after-free on address 0x604000074210 at pc 0x7fa1b42a652c bp 0x7ffc477a2aa0 sp 0x7ffc477a2a98
> READ of size 8 at 0x604000074210 thread T0
>     #0 0x7fa1b42a652b in list_delete_all_node git/frr/lib/linklist.c:299:20
>     #1 0x7fa1b42a683f in list_delete git/frr/lib/linklist.c:312:2
>     #2 0x5ee515 in dplane_ctx_free_internal git/frr/zebra/zebra_dplane.c:858:4
>     #3 0x5ee59c in dplane_ctx_free git/frr/zebra/zebra_dplane.c:884:2
>     #4 0x5ee544 in dplane_ctx_fini git/frr/zebra/zebra_dplane.c:905:2
>     #5 0x7045c0 in rib_process_dplane_results git/frr/zebra/zebra_rib.c:4928:4
>     #6 0x7fa1b4434fb2 in event_call …
=> zebra: fix dplane_ctx_iptable use-after-free

mgmtd/mgmt_txn.c
At this stage, we should send a SET_CFG reply, not COMMIT_CFG reply. Commit request is not yet initialized.
=> mgmtd: fix reply when running ds is not locked

doc/developer/building-frr-for-freebsd14.rst, doc/developer/building.rst
The changes add build instructions for FRRouting on FreeBSD 14 to the developer documentation.
Tested on FreeBSD 14.0-RELEASE.
=> doc: Add build instructions for FreeBSD 14

bgpd/bgp_zebra.c, bgpd/rfapi/vnc_zebra.c, eigrpd/eigrp_zebra.c, isisd/isis_zebra.c, ldpd/lde.c, lib/zclient.c, lib/zclient.h, ospfd/ospf_zebra.c, pathd/path_zebra.c, pbrd/pbr_zebra.c, pimd/pim_zlookup.c, sharpd/sharp_zebra.c, staticd/static_zebra.c, zebra/zapi_msg.c
- remove `receive_notify`, use `ZEBRA_ROUTE_NOTIFY_REQUEST` instead
- add a common predefined `zclient_options_sync`
- make the options `const`
- add an `auxiliary` option that prevents `lib/` message handlers from being called
- note this only affects VNC since that was the only place that opens a second zclient that is _NOT_ also `synchronous`
=> *: clean up `zclient` options

doc/developer/building-docker.rst, docker/ubuntu20-ci/README.md, docker/ubuntu22-ci/README.md
Fix typos in docs.
Also sync doc/developer/building-docker.rst with docker/ubuntu20-ci/README.md and docker/ubuntu22-ci/README.md
=> docker: fix typos in docs for ubuntu20-ci and ubuntu22-ci

bgpd/bgp_ecommunity.c, bgpd/bgp_ecommunity.h, bgpd/bgp_mplsvpn.c, bgpd/bgp_mplsvpn.h, bgpd/bgp_routemap.c, bgpd/bgp_routemap_nb_config.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_vpnv4_asbr/test_bgp_vpnv4_asbr.py, tests/topotests/bgp_vpnv4_ebgp/r1/bgpd.conf, tests/topotests/bgp_vpnv4_ebgp/test_bgp_vpnv4_ebgp.py, tests/topotests/lib/bgpcheck.py
This pull request introduces a few fixes related to route-map and l3vpn usage.
This pull request also proposes to facilitate the L3VPN prefixes exportation by not solely relying on the 'rt vpn export ' command. That is to say that a route-map usage can also be used.
=> L3VPN exportation by using 'route-map vpn export' command instead of 'rt vpn export' command

doc/user/zebra.rst, lib/routemap.c, vtysh/vtysh.c
Fixes #13515 .
This PR moves the `show route-map` daemon output aggregation to `vtysh` so we can properly format the JSON output. It also removes a `zebra` lingering documentation that duplicates the one found in `route-map` docs.
=> lib: fix show route map JSON display

tools/frr-reload.py
Fix frr-reload script to only render 'no description' rather than 'no description blah'
Testing Done:
Before:
```
2023-11-29 02:38:55,758  INFO: Failed to execute interface hostbond_1 no description hostbond_1_to_host exit
2023-11-29 02:38:55,758 ERROR: "interface hostbond_1 --  no description hostbond_1_to_host -- exit" we failed to remove this command 2023-11-29 02:38:55,758 ERROR: % Unknown command:  no description hostbond_1_to_host
```
After fix it removes the description under interface.
=> tools: fix frr-reload interface desc cmd

ospfd/ospf_interface.c, ospfd/ospf_interface.h, ospfd/ospf_nsm.c, ospfd/ospf_opaque.c, ospfd/ospf_opaque.h, tests/topotests/ospfapi/test_ospf_clientapi.py
1. When an OSPF interface is deleted, remove the references in link-local LSA. Delete the LSA from the LSDB so that the callback has accessibily to the interface prior to deletion.
2. Fix a double free for the opaque function table data structure.
3. Assure that the opaque per-type information and opaque function table structures are removed at the same time since they have back pointers to one another.
4. Add a topotest variation for the link-local opaque LSA crash.
=> ospfd: Fix OSPF link-local opaque LSA crash and opaque memory corruption

bgpd/bgp_route.c
Fix bgp_best_selection heap-use-after-free
> ==2521540==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000032810 at pc 0x000000716f45 bp 0x7ffedc6229d0 sp 0x7ffedc6229c8
> READ of size 8 at 0x60d000032810 thread T0
>     #0 0x716f44 in bgp_best_selection /home/lscalber/git/frr/bgpd/bgp_route.c:2834:5
>     #1 0x71a05e in bgp_process_main_one /home/lscalber/git/frr/bgpd/bgp_route.c:3344:2
>     #2 0x71c265 in bgp_process_wq /home/lscalber/git/frr/bgpd/bgp_route.c:3622:3
>     #3 0x7fe630a6669c in work_queue_run /home/lscalber/git/frr/lib/workqueue.c:282:10
>     #4 0x7fe630a294e2 in event_call /home/lscalber/git/frr/lib/event.c:1974:2
>     #5 0x7fe630898f3f in frr_run /home/lscalber/git/frr/lib/libfrr.c:1214:3
>     #6 0x4f4ace in main …
=> bgpd: fix bgp_best_selection heap-use-after-free

doc/developer/scripting.rst, lib/frrlua.c, lib/frrlua.h, lib/frrscript.c, lib/frrscript.h, tests/lib/test_frrlua.c, tests/lib/test_frrscript.c
- Add noop decoder, this replaces my `const void*` noop decoder
- Rename and create decoders for int, int*, long long, long long *
- Fix bgp_routemap.c cast (it was casting from int* to long long*, changed it to int*)
---
So we have encoders and decoders. Encoders encode types from C -> Lua, decoders the other way. But decoders doesn't work for all types.
Breaking it down, we have three types:
1. non cost qualified pointer types (e.g. int*)
2. const qualified pointer types (e.g. const int *)
3. everything else, lets call these value types (e.g. int)
We want to be able to encode all three types, but we can really only decode non const qualified pointer types. The other two types, we want them to noop. e.g. I have integer values I encode into frrscript, but I don't want to/can decode these …
=> Refactor decoder for Lua hook system

doc/user/pathd.rst, pathd/path_pcep_cli.c
The below running-configuration has extra spaces before the pce port configuration:
> segment-routing
>  traffic-engineering
>   pce test
>    address ip 192.0.2.2   port 1234
>
Fix this by keeping only one space.
>    address ip 192.0.2.2 port 1234
Fixes: efba0985fcdd ("pathd: Add optional support for PCEP to pathd")
=> pathd: fix space before pcep port in running-config

lib/command.h, lib/northbound.c, mgmtd/mgmt_main.c, mgmtd/mgmt_vty.c, staticd/static_nb.c, staticd/static_vrf.c, staticd/static_vty.c, staticd/static_vty.h
When a daemon becomes mgmtd-converted, mgmtd starts processing its vty configuration commands. It makes sense to output the configuration from mgmtd as well, so that everything related to vty config is handled in one place.
=> Output configuration of mgmtd-converted daemons from mgmtd

zebra/zebra_router.c, zebra/zebra_tc.c, zebra/zebra_tc.h
Configure hash table cleanup with specific free functions for `zrouter.filter_hash`, `zrouter.qdisc_hash`, and `zrouter.class_hash`. This ensures proper memory cleanup, addressing memory leaks.
```
Address Sanitizer Error detected in tc_basic.test_tc_basic/r1.asan.zebra.15495
==15495==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 176 byte(s) in 1 object(s) allocated from:
#0 0x7fd5660ffd28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7fd565afe238 in qcalloc lib/memory.c:105
#2 0x5564521c6c9e in tc_filter_alloc_intern zebra/zebra_tc.c:389
#3 0x7fd565ac49e8 in …
```
=> zebra: Set Free Functions for Traffic Control Hash Tables

bgpd/bgpd.c
Release memory associated with `bgp->confed_peers` in the `bgp_free` function to ensure proper cleanup. This fix prevents memory leaks related to `confed_peers`.
```
Address Sanitizer Error detected in bgp_confederation_astype.test_bgp_confederation_astype/r2.asan.bgpd.15045
==15045==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f5666787b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x7f56661867c7 in qrealloc lib/memory.c:112
#2 0x55a3b4736a40 in bgp_confederation_peers_add bgpd/bgpd.c:681
#3 0x55a3b46b3363 in …
```
=> bgpd: Free Memory for confed_peers in bgp_free

bgpd/bgp_mplsvpn.c, bgpd/bgp_vty.c, bgpd/bgp_zebra.c, bgpd/bgpd.c, bgpd/bgpd.h, lib/srv6.c, lib/srv6.h
Implement proper memory cleanup for SRv6 functions and locator chunks to prevent potential memory leaks. The list callback deletion functions have been set.
```
Address Sanitizer Error detected in bgp_srv6l3vpn_to_bgp_vrf.test_bgp_srv6l3vpn_to_bgp_vrf/r2.asan.bgpd.4180
==4180==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 544 byte(s) in 2 object(s) allocated from:
#0 0x7f8d176a0d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7f8d1709f238 in qcalloc lib/memory.c:105
#2 0x55d5dba6ee75 in sid_register bgpd/bgp_mplsvpn.c:591
#3 0x55d5dba6ee75 in alloc_new_sid …
```
=> bgpd: Free Memory for SRv6 Functions and Locator Chunks

bgpd/bgp_evpn.c, bgpd/bgp_evpn.h, bgpd/bgp_evpn_mh.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_trace.h, tools/frr_babeltrace.py
When exporting bgp vrf instance unicast route into
EVPN as type-5, check for suppressed ones and do not
export them.
Config:
```
router bgp 660000 vrf vrf1
bgp router-id 144.1.1.2
no bgp network import-check
neighbor 144.1.1.1 remote-as external
!
aggregate-address 50.1.0.0/16 summary-only
redistribute connected
!
address-family l2vpn evpn
advertise ipv4 unicast
exit
```
v4 suppressed route: (5 suppressed routes not exported to evpn)
```
tor1# vtysh -c "show bgp vrf vrf1 ipv4 unicast" | grep "50.1"
*> 50.1.0.0/16      0.0.0.0(bordertor-11)
s> 50.1.1.212/32    6.0.0.30(leaf-11)<
s> 50.1.1.222/32    6.0.0.31(leaf-11)<
s> 50.1.110.0/24    0.0.0.0(bordertor-11)
s> 50.1.210.214/32  6.0.0.30(leaf-11)<
s> 50.1.220.224/32 …
```
=> bgpd: aggr summary-only suppressed export to evpn

pathd/path_pcep_cli.c
The following message appears after starting pathd:
> root@ubuntu2204:~# vtysh
> 2023/10/31 05:59:10 [K2CCG-5Y7ZJ] Excessive docstring while parsing 'msd (1-32)'
> 2023/10/31 05:59:10 [W7ENN-K2SVA] ----------
> 2023/10/31 05:59:10 [WCW75-6TZPF] PCC maximum SID depth value
> 2023/10/31 05:59:10 [W7ENN-K2SVA] ----------
Remove the excessive doc string in the pcep msd command.
Fixes: d6d2527448ef ("pathd: fix 'no msd' command not possible under pcc node")
=> pathd: fix excessive doc string on pcep msd command

docker/ubi8-minimal/Dockerfile
FRR's RPM package requires protobuf-c to be installed on the runtime system, otherwise it will refuse to be installed.
=> docker/ubi8-minimal: add protobuf-c runtime dep

bgpd/bgp_evpn.c
(pi=pi@entry=0x55e86ec1a5a0, evp=evp@entry=0x7fff4edc2160)
at bgpd/bgp_evpn.c:3623
3623    bgpd/bgp_evpn.c: No such file or directory.
(gdb) info locals
bgp_evpn = 0x0
macvrf_soo = <optimized out>
ret = false
__func__ = <optimized out>
```
#3  bgp_evpn_route_matches_macvrf_soo (pi=pi@entry=0x55e86ec1a5a0, evp=evp@entry=0x7fff4edc2160)
at bgpd/bgp_evpn.c:3623
#4  0x000055e86cb7598b in bgp_evpn_install_uninstall_table (bgp=bgp@entry=0x55e86e9cd010, afi=afi@entry=AFI_L2VPN,
safi=safi@entry=SAFI_EVPN, p=p@entry=0x0, pi=pi@entry=0x55e86ec1a5a0, import=import@entry=1, in_vrf_rt=true,
in_vni_rt=true) at bgpd/bgp_evpn.c:4200
#5  0x000055e86cb79b4b in install_uninstall_evpn_route (import=1, pi=pi@entry=0x55e86ec1a5a0, p=p@entry=0x0,
safi=safi@entry=SAFI_EVPN, afi=afi@entry=AFI_L2VPN, …
```
=> bgpd: check bgp evpn instance presence in soo

isisd/isis_lsp.c
If "no hostname dynamic" command is used, this fix correctly displays the LSP ID.
=> isisd: Fix dislaying LSP ID

lib/nexthop_group.c, lib/nexthop_group.h
No need to declare 'nexthop_group_nexthop_num_no_recurse()' as external.
Fixes: 98cda54a9543 ("zebra: Add recursive functionality to NHE's")
=> lib: fix nexthop_group_nexthop_num_no_recurse() is static

ospfd/ospf_ri.c, ospfd/ospfd.c
=> ospfd: fix deferred shutdown handling

pbrd/pbr_vty.c, tests/topotests/pbr_topo1/r1/pbr-map.json
Post fix:
```
tor-2# show pbr map json
[
{
"name":"global-vrf-PBR-map",
"valid":true,
"policies":[
{
"id":1,
"sequenceNumber":10,
"ruleNumber":309,
"vrfUnchanged":false,
"installed":true,   <<<< now display correct value
"installedReason":"Valid",
"vrfName":"sym_1",
"matchSrc":"10.1.200.0\/24",
"matchDst":"10.6.200.0\/24"
}
]
}
```
=> pbrd: fix map seq installed flag in json

sharpd/sharp_nht.c, sharpd/sharp_zebra.c
When no nexthops are in a nexthop group, two successive events are sent: NHG_DEL and NHG_ADD, but only the NHG_DEL one is necessary. Fixes this by returning in the nhg_add() function.
Fixes: 82beaf6ae520 ("sharpd: fix deleting nhid when suppressing nexthop from nh group")
=> sharpd: fix deleting nhid when suppressing nexthop from nh group

zebra/zebra_rib.c
If there happens to be a entry in the zebra rib
that has a lower admin distance then a newly received re, zebra would not notify the upper level protocol about this happening.  Imagine a case where there
is a connected route for say a /32 and bgp receives a route from a peer that is the same route as the
connected.  Since BGP has no network statement and perceives the route as being `good` bgp will install the route into zebra.  Zebra will look at the new
bgp re and correctly identify that the re is not
something that it will use and do nothing.  This
change notices this and sends up a BETTER_ADMIN_WON route notification.
=> zebra: Fix non-notification of better admin won

zebra/rib.h, zebra/zapi_msg.c, zebra/zebra_rib.c
The NHG_DEL operation is done directly from ZAPI call, whereas the NHG_ADD operation is done in the rib_nhg meta queue.
This may be problematic when ADD is followed by DEL. Imagine a scenarion with two protocol NHIDs. <NH1> depends of <NH2> and <NH3>. The deletion of <NH3> at the protocol level will trigger 2 messages to ZEBRA: NHG_ADD(<NH1>) and NHG_DEL(<NH3>).
Those operations are properly enqueued in ZAPI, but in the end, the NHG_DEL is executed first. This causes NHG_ADD to unlink an already freed NHG.
Fix this by consistently enqueuing NHG_DEL and NHG_ADD operations.
=> zebra: enqueue NHG_DEL in rib_nhg meta queue

docker/ubuntu-ci/Dockerfile
kmod is needed in order to get modprobe
=> docker: fix /sbin/modprobe missing

ospfd/ospf_ext.c
Segment Router Identifier (SID) could be an index (4 bytes) within a range (SRGB or SRLB) or an MPLS label (3 bytes). Thus, before calling check_size macro to verify SID TLVs size, it is mandatory to determine the SID type to avoid wrong assert.
=> ospfd: Correct SID check size

zebra/rib.h, zebra/rt_netlink.c, zebra/zebra_rib.c
The route entry created when using a ctx to pass route entry data backup to the master pthread in zebra is being leaked.  Prevent this from happening.
=> zebra: The dplane_fpm_nl return path leaks memory

lib/mgmt_be_client.c, lib/mgmt_fe_client.c, staticd/static_main.c
Rename global client pointer variables and make the linkage static.
=> lib: fix the ASAN OneDefinitionRule violation.

lib/netns_linux.c, zebra/label_manager.c, zebra/label_manager.h, zebra/main.c, zebra/zebra_pw.c, zebra/zebra_pw.h, zebra/zebra_vrf.c
See individual commit messages, but there are some more memory cleanups on shutdown
=> Zebra delete memory problems

bgpd/bgp_vty.c, tests/topotests/all_protocol_startup/r1/show_bgp_ipv6_summary.ref, tests/topotests/all_protocol_startup/r1/show_ip_bgp_summary.ref
The vrf name was not being displayed in this output. New output:
eva# show bgp vrf all ipv4 uni summ
BGP router identifier 0.0.0.0, local AS number 99 VRF RED vrf-id 14 BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 1, using 20 KiB of memory
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
192.168.119.1   4          0         0         0        0    0    0    never       Active        0 N/A
Total number of neighbors 1
BGP router identifier 0.0.0.0, local AS number 99 VRF GREEN vrf-id 15 BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 1, using 20 KiB of memory
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
192.168.119.1   4          0         0 …
=> bgpd: Have `show bgp vrf all ipv4 uni summ` display vrf NAME

tools/frr-reload.py
Ensure to change description for index 0 from the list.
Testing Done:
After fix:
```
start with three interfaces description delete in lines_to_del: (Pdb) lines_to_del
[(('interface swp1',), "description swp1 -> sp1's swp1"), (('interface swp2',), "description swp2 -> sp2's swp 1"), (('interface swp3',), "description swp3 -> sp3's swp1")]
After first iteration swp1:
(Pdb) index
0
(Pdb) lines_to_del
[(('interface swp1',), 'description'), (('interface swp2',), "description swp2 -> sp2's swp1"), (('interface swp 1s2',), "description swp3 -> sp3's swp1")]
After second iteration swp2:
(Pdb) lines_to_del
[(('interface swp1',), 'description'), (('interface swp2',), 'description'), (('interface swp3',), "description swp3 -> sp3's swp1")]
After third iteration swp3 fix
(Pdb) lines_to_del …
```
=> tools: fix frr-reload multiple no description cmds

doc/user/ospfd.rst, ospfd/ospf_vty.c
1. fix ip ospf dead-interval minimal hello-multiplier param range (2-20) accroding to OSPFv2 doc(ospfd.rst)
2. add param range of graceful-restart helper supported-grace-time in OSPFv2 doc(ospfd.rst)
3. check other cmds' param range
=> ospfd: fix some ospf cmds' param range

ospfd/ospf_te.c, tests/topotests/ospf_te_topo1/r1/ospfd.conf, tests/topotests/ospf_te_topo1/r1/zebra.conf, tests/topotests/ospf_te_topo1/r2/ospfd.conf, tests/topotests/ospf_te_topo1/r2/zebra.conf, tests/topotests/ospf_te_topo1/r3/ospfd.conf, tests/topotests/ospf_te_topo1/r3/zebra.conf, tests/topotests/ospf_te_topo1/r4/ospfd.conf, tests/topotests/ospf_te_topo1/r4/zebra.conf, tests/topotests/ospf_te_topo1/test_ospf_te_topo1.py
Traffic Engineering Database (TED) is fulfill from the various LSA advertised and received by the router. To remove information on the TED, 2 mechanisms are used: i) parse TE Opaque LSA when there are flushed and ii) compare the list of prefixes advertised in the Router LSA with the list of corresponding edges and subnets contained in the TED. However, this second mechanism assumes that the Router LSA is unique and contains all prefixes of the advertised router. But, this is wrong. Prefixes could be advertised with several Router LSA. This conduct to remove edge and subnet in the TED while it should be maintained. The result is a faulty test with ospf_sr_te_topo1 topotest when server is heavy loaded.
This simple patch removed deletion of edges and subnets when parsing the Router LSA and …
=> ospfd: Correct LSA parser which fulfill the TED

zebra/dplane_fpm_nl.c
An operator is reporting that the dplane_fpm_nl connection has started to accumulate contexts.  One such path that could cause this is that the obuf used is full and stays full.  This would imply that what ever is on the receiving end has gotten wedged and is not reading from the stream of data being sent it's way. If after 15 seconds of no response, let's declare the connection dead and reset it.
=> zebra: Prevent possible wedged fpm write

tests/topotests/ospf_suppress_fa/r1/initial.json, tests/topotests/ospf_suppress_fa/r1/neighbor.json, tests/topotests/ospf_suppress_fa/r1/post.json, tests/topotests/ospf_suppress_fa/test_ospf_suppress_fa.py
The test_ospf_suppres_fa.py script is using straight up sleeps before testing that the next step worked properly. On a unloaded test system this will work 100% of the time on a loaded test system this will have random failures. Convert the test to use run_and_expect and give each section of the test 30 seconds to get to the next state appropriately instead of 10.
=> tests: ospf_suppress_fa sleeps, convert to run_and_expect

bgpd/bgp_route.c, tests/topotests/bgp_default_route/r1/bgpd.conf, tests/topotests/bgp_default_route/r1/zebra.conf, tests/topotests/bgp_default_route/test_bgp_default-originate.py
Prevent "default-originate" from withdrawing non-default routes like 0.0.0.0/1 by checking prefix length.
=> bgpd: "default-originate" shouldn't withdraw non-default routes

ospfd/ospf_apiserver.c, ospfd/ospf_opaque.c
1. Fix ospf opaque LSA function table memory leak.
2. Remove incorrect one-to-one association of OSPF opaque LS info-per-type to function table (since there many be many).
3. Fix a problem with opaque AS external LSA cleanup that was exposed by the above change. 
4. Also fix memory leak in ospf_opaque_type9_lsa_if_cleanup().
=> ospfd: Fix opaque functab memory leak and opaque AS External LSA cleanup problems

lib/keychain.c
This is a bit of a bummer that this slipped through for so long.
=> lib: Keychain.c was using free

tests/topotests/bgp_evpn_overlay_index_gateway/test_bgp_evpn_overlay_index_gateway.py, tests/topotests/bgp_flowspec/test_bgp_flowspec_topo.py, tests/topotests/conftest.py, tests/topotests/lib/snmptest.py, tools/etc/frr/support_bundle_commands.conf
1) Auto generate a support bundle on test failure
2) snmp tests were generating python warnings
3) support bundles were missing some bgp vpnv4 data, add it in
=> Generate support bundle on test failure

zebra/interface.c, zebra/interface.h
=> zebra: Drop ipv6_address_configured() function

doc/developer/.readthedocs.yaml
There's a graph in cli.rst that needs graphviz to be built.
=> doc: add graphiz dependency for dev docs

bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_zebra.c, zebra/zebra_vxlan.c
Add nexthop fied when import/unimport evpn route in vrf, print bgp vrf instance name which contains "VRF" keyword.
Include pathcount which is list of paths linked to nexthop.
add and delete l3vni to keep symmetric "L3VNI" keyword as used in other debug statements.
Testing Done:
```
2023/12/27 05:10:03.339616 BGP: [HPE1G-3H7F2] ... new pi VRF vrf2 dest 0x55663e8372c0 (l 2) pi 0x55663e8374d0 (l 1, f 0x4010) nh 6.0.0.1
2023/12/27 05:58:56.650116 BGP: [MC0JJ-7ZYQB] ... delete pi VRF vrf2 dest 0x55663e885110 (l 5) pi 0x55663e8851e0 (l 1, f 0x4098) nh 6.0.0.1
2023/12/27 05:10:03.339581 BGP: [P4TBX-3W31N] evpn VRF vrf2 nh 6.0.0.1 rmac 00:02:00:00:00:04 add to zebra
2023/12/27 06:13:12.685906 BGP: [SWSCZ-2Z6M4] evpn vrf VRF vrf1 nh 6.0.0.1 del to zebra
2023/12/27 05:10:03.339603 BGP: …
```
=> bgpd: revamp evpn debugs nexthop and l3vni

bgpd/bgp_evpn.c, bgpd/bgp_trace.h
Two commits:
1) bgpd: lttng tp add ethtag to macip zebra send
Testing Done:
2023-09-08T17:33:03.731 frr_bgp:evpn_mac_ip_zsend {'action': 'add',
'vni': 1003, 'eth_tag': 968006412, 'mac': '00:02:00:00:00:40', 'ip': '',
'vtep': '27.0.0.16', 'esi': '00:00:00:00:00:00:00:00:00:00'}
2) bgpd: fix coverity warnings about evpn vpn variable
A few paths could see a vpn variable with a NULL value;
check and protect those paths.
Signed-off-by: Mark Stapp <mstapp@nvidia.com>
=> bgpd: lttng tp add ethtag to macip zebra send

lib/northbound_oper.c
Heard back from libyang folks that this is not something they consider part of the API and/or are going to guarantee. So we cannot count on it. Expect keys at any location on the child sibling list.
https://github.com/CESNET/libyang/discussions/1396#discussioncomment-7991855
=> lib: don't count on scheme key nodes being first children

configure.ac, doc/developer/building-frr-for-archlinux.rst, doc/developer/building-frr-for-ubuntu1404.rst, doc/developer/building-frr-for-ubuntu1604.rst, doc/developer/building-frr-for-ubuntu1804.rst, doc/developer/building-frr-for-ubuntu2004.rst, doc/developer/building-frr-for-ubuntu2204.rst, doc/developer/building-libyang.rst, docker/ubuntu-ci/Dockerfile
- recommend using libyang 2.1.128 but accept 2.0.0 for now.
- update ubuntu building doc to add GRPC section
- update ubuntu reference docker builds to match grpc doc change
=> build: protobuf is required so update building docs

.github/workflows/freeze.yml
This prevents us from merging PRs marked as 'do not merge'.
=> github: Mark the build as failed if 'do not merge' label is set

isisd/isis_spf.c
Fix the following heap-use-after-free
> ==82961==ERROR: AddressSanitizer: heap-use-after-free on address 0x6020001e4750 at pc 0x55a8cc7f63ac bp 0x7ffd6948e340 sp 0x7ffd6948e330
> READ of size 8 at 0x6020001e4750 thread T0
>     #0 0x55a8cc7f63ab in isis_route_node_cleanup isisd/isis_route.c:335
>     #1 0x7ff25ec617c1 in route_node_free lib/table.c:75
>     #2 0x7ff25ec619fc in route_table_free lib/table.c:111
>     #3 0x7ff25ec61661 in route_table_finish lib/table.c:46
>     #4 0x55a8cc800d83 in _isis_spftree_del isisd/isis_spf.c:397
>     #5 0x55a8cc800e45 in isis_spftree_clear isisd/isis_spf.c:414
>     #6 0x55a8cc80bd9a in isis_run_spf isisd/isis_spf.c:2020
>     #7 0x55a8cc80c370 in isis_run_spf_with_protection isisd/isis_spf.c:2076
>     #8 0x55a8cc80cf52 in isis_run_spf_cb …
=> isisd: fix _isis_spftree_del heap-use-after-free

lib/zclient.c, lib/zclient.h
zebra_interface_vrf_update_read is orphan. Remove it.
Fixes: b580c52698 ("*: remove ZEBRA_INTERFACE_VRF_UPDATE")
=> lib: remove zebra_interface_vrf_update_read()

bgpd/bgp_ecommunity.c
Fix the following heap-buffer-overflow:
> ==3901635==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020003a5940 at pc 0x56260067bb48 bp 0x7ffe8a4f3840 sp 0x7ffe8a4f3838
> READ of size 4 at 0x6020003a5940 thread T0
>     #0 0x56260067bb47 in ecommunity_fill_pbr_action bgpd/bgp_ecommunity.c:1587
>     #1 0x5626007a246e in bgp_pbr_build_and_validate_entry bgpd/bgp_pbr.c:939
>     #2 0x5626007b25e6 in bgp_pbr_update_entry bgpd/bgp_pbr.c:2933
>     #3 0x562600909d18 in bgp_zebra_announce bgpd/bgp_zebra.c:1351
>     #4 0x5626007d5efd in bgp_process_main_one bgpd/bgp_route.c:3528
>     #5 0x5626007d6b43 in bgp_process_wq bgpd/bgp_route.c:3641
>     #6 0x7f450f34c2cc in work_queue_run lib/workqueue.c:266
>     #7 0x7f450f327a27 in event_call lib/event.c:1970
>     #8 0x7f450f21a637 …
=> bgpd: fix ecommunity_fill_pbr_action heap-buffer-overflow

zebra/zebra_dplane.c
Fix the following coverity issue:
```
*** CID 1575079:  Null pointer dereferences  (REVERSE_INULL) /zebra/zebra_dplane.c: 5950 in dplane_srv6_encap_srcaddr_set()
5944     	if (ret == AOK)
5945     		result = ZEBRA_DPLANE_REQUEST_QUEUED;
5946     	else {
5947     		atomic_fetch_add_explicit(&zdplane_info
5948     						   .dg_srv6_encap_srcaddr_set_errors,
5949     					  1, memory_order_relaxed);
CID 1575079:  Null pointer dereferences  (REVERSE_INULL)
Null-checking "ctx" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
5950     		if (ctx)
5951     			dplane_ctx_free(&ctx);
5952     	}
5953     	return result;
5954     }
5955
```
Remove the pointer check for `ctx`. At this point in the function it has to be non null since we deref'ed …
=> zebra: Fix coverity issue in `dplane_srv6_encap_srcaddr_set`

bfdd/bfd_packet.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_import.h, isisd/isis_tlvs.c, lib/command.c, lib/frrsendmmsg.h, lib/imsg-buffer.c, lib/log.c, lib/privs.c, lib/pullwr.c, lib/subdir.am, lib/vrf.c, lib/zebra.h, lib/zlog.c, lib/zlog_5424.c, lib/zlog_live.c, nhrpd/linux.c, ospf6d/ospf6_auth_trailer.c, ospfd/ospf_auth.c, pimd/pim6_mld.c, pimd/pim_cmd_common.c, pimd/pim_mroute.c, ripd/ripd.c, sharpd/sharp_logpump.c, vtysh/vtysh.c, zebra/if_ioctl.c, zebra/ioctl.c, zebra/rtadv.c, zebra/zebra_mpls_openbsd.c
Zebra.h has become a bit of a dumping ground for system headers.  Let's make a single pass through zebra.h and properly locate stuff where it belongs.  Especially for includes that are only used by 1-2 files.
Initial results of compile time on my machine actually surprised me.
I run a make -j32
Before timings:
```
Executed in   13.12 secs    fish           external
usr time  208.02 secs  360.00 micros  208.02 secs
sys time   68.33 secs  179.00 micros   68.33 secs
```
After Timings:
```
Executed in   10.92 secs    fish           external
usr time  158.24 secs  328.00 micros  158.24 secs
sys time   50.81 secs  162.00 micros   50.81 secs
```
=> Lib zebra h cleanup

redhat/frr.spec.in
Fixes for:
```python
checking for protoc-c... no
configure: error: in `/builddir/build/BUILD/frr-frr-9.1':
configure: error: protobuf requested but protoc-c not found.  Install protobuf-c.
```
And rpmlint warnings:
```python
warning: line 208: It's not recommended to have unversioned Obsoletes: Obsoletes:          gated mrt zebra frr-sysvinit
warning: bogus date in %changelog: Thu Oct 09 2023 Donatas Abraitis <donatas@opensourcerouting.org> - 9.1
line 208: It's not recommended to have unversioned Obsoletes: Obsoletes:          gated mrt zebra frr-sysvinit
bogus date in %changelog: Thu Oct 09 2023 Donatas Abraitis <donatas@opensourcerouting.org> - 9.1
```
=> redhat: rpm spec: added protobuf-c to deps & fix bogus changelog date

lib/event.c
The thread system has been renamed, let's use the proper terminology now in the show commands.  Also realign output a tiny bit for stuff that was missing.
=> lib: Use event name instead of thread

bgpd/bgp_labelpool.c
There are several problems with the bgp_sync_label_manager function:
a) It is possible that a request in the lp->requests fifo will be unable to be filled at this point in time and the lf will be leaked and not ever fullfilled.
b) The bgp_sync_label_manager runs one time a second irrelevant if there is work to do or not.
To fix (a) just add the request back to the requests fifo and set the timer to pop in the future.
To fix (b) just every time something is put into
the request pool start a timer to run in 1 second
and do not restart it if all the work is done.
=> bgpd: bgp_sync_label_manager failure case

bgpd/bgp_fsm.c
This reverts commit 7bf3c2fb195f34382e1bf00ed2c91310a1dc9f86. Commit reverted as it introduces a memoery leak during the tests
=> Revert "bgpd: On shutdown do not create a workqueue for the self peer"

configure.ac, doc/developer/building-frr-for-centos6.rst, doc/developer/building-frr-for-opensuse.rst, doc/developer/building-frr-for-ubuntu2204.rst
Update building docs to reflect this as well.
=> build: require libyang 2.1.128

zebra/main.c
This reverts commit 71f7ecb571cd8a87c97ae952db1f1fafa7ef627a.
=> Revert "zebra: Cleanup zrouter.stale_client_list on shutdown"

doc/developer/process-architecture.rst, doc/user/basic.rst, lib/event.c, tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py, tests/topotests/isis_topo1/test_isis_topo1.py, tools/etc/frr/support_bundle_commands.conf, vtysh/vtysh.c
Deprecate `show thread ...` commands later, and add them as aliases.
=> vtysh: Add `show event ...` commands

bgpd/bgp_updgrp_adv.c
Closes https://github.com/FRRouting/frr/issues/15113
=> bgpd: Fix memory leak for default-originate with route-map

bgpd/bgp_zebra.c, lib/zclient.h, sharpd/sharp_zebra.c
This rework permits to decorrelate the ZAPI nexthop build from the ZAPI route build.
The new function bgp_zebra_announce_parse_nexthop() will later be used to update the nexthop groups
=> Zebra nexthop rework

bgpd/bgp_debug.c, bgpd/bgp_debug.h, bgpd/bgp_packet.c, doc/user/bgp.rst
When filtering with `debug bgp updates in x.x.x.x prefix-list plist`, we want to filter out unnecessary messages like:
```
127.0.0.1(Unknown) rcvd UPDATE wlen 0 attrlen 20 alen 5
```
Such a line as above will be repeated for all the paths received and it's useless without knowing the prefix (because NLRIs are not parsed yet).
But want to see only relevant ones:
```
127.0.0.1(Unknown) rcvd UPDATE w/ attr: nexthop 127.0.0.1, origin i, path 65002
127.0.0.1(Unknown) rcvd 10.255.255.1/32 IPv4 unicast
```
With `debug bgp updates detail` we can combine this to something like:
```
127.0.0.1(Unknown) rcvd UPDATE w/ attr: nexthop 127.0.0.1, origin i, path 65002
127.0.0.1(Unknown) rcvd UPDATE wlen 0 attrlen 20 alen 5
127.0.0.1(Unknown) rcvd 10.255.255.1/32 IPv4 unicast
```
=> bgpd: Add `debug bgp updates detail` command

configure.ac, lib/darr.h, lib/mgmt_msg.c, lib/northbound.c, lib/northbound.h, lib/northbound_oper.c, lib/vty.c, lib/yang.c, lib/yang.h, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_txn.c, mgmtd/mgmt_txn.h, tests/topotests/mgmt_oper/test_querying.py, tests/topotests/mgmt_oper/test_scale.py
Allow user to specify full YANG compatible XPath 1.0 functionality. This allows
for trimming results of generic queries using functions and other non-key
predicates from XPath 1.0
=> Implement full XPath 1.0 functionality

lib/northbound_oper.c, tests/topotests/mgmt_oper/test_simple.py
Fix memleak when a key-ed query was done for which the key didn't exist.
=> lib: fix oper-state memleak

bgpd/bgp_packet.c, bgpd/bgp_snmp_bgp4v2.c, ospf6d/ospf6_neighbor.c, pimd/pim_upstream.c, zebra/redistribute.c
Ran Clang SA locally found some issues.  Clean some of them up.  See individual commits
=> Sa problems local

mgmtd/mgmt_txn.c
When determining the interested backend clients for a configuration change, don't consider disconnected clients. This fixes a crash in `mgmt_txn_send_be_txn_create` when trying to send data to a non-existing adapter.
=> mgmtd: don't try to send config to disconnected clients

doc/developer/mgmtd-dev.rst, lib/northbound.c, lib/northbound.h, mgmtd/mgmt_main.c, staticd/static_vty.c
Setting this variable to true makes NB ignore only configuration-related callbacks. CLI-related callbacks are still loaded and executed, so rename the variable to make it clearer.
=> lib, mgmtd: rename ignore_cbs to ignore_cfg_cbs

doc/developer/northbound/retrofitting-configuration-commands.rst, lib/mgmt.proto, lib/mgmt_be_client.c, lib/northbound.c, lib/northbound.h, lib/northbound_cli.h, lib/northbound_confd.c, lib/northbound_sysrepo.c, lib/vty.c, mgmtd/mgmt_txn.c, mgmtd/mgmt_vty.c, tools/gen_northbound_callbacks.c
Currently, we basically support two types of configuration edit operations:
- `merge`: modify existing data or create if it doesn't exist (NB_OP_CREATE/NB_OP_MODIFY, both do the same thing)
- `remove`: delete data if it exists, ignore otherwise (NB_OP_DESTROY)
To be able to integrate with NETCONF/RESTCONF servers, this PR adds three more operation types:
- `create`: create new data, fail if it already exists (new NB_OP_CREATE_EXCL operation)
- `delete`: delete data, fail if it doesn't exist (new NB_OP_DELETE operation)
- `replace`: replace config with a new one, create if it doesn't exist (new NB_OP_REPLACE operation)
Important note:
`DELETE_DATA` operation in mgmtd frontend API now fails if the data already exists. To have the old behavior, one should use new `REMOVE_DATA` operation. …
=> Add more northbound operation types

lib/darr.h, lib/yang.c, mgmtd/mgmt_fe_adapter.c
** CID 1575504:  Insecure data handling  (TAINTED_SCALAR) (maybe)
** CID 1575505:  Integer handling issues  (CONSTANT_EXPRESSION_RESULT)
** CID 1575506:  Integer handling issues  (CONSTANT_EXPRESSION_RESULT)
** CID 1575507:  Null pointer dereferences  (REVERSE_INULL)
=> lib: fix coverity issues

pimd/pim_join.c, pimd/pim_rp.c, pimd/pim_rpf.c, pimd/pim_vxlan.c, pimd/pim_vxlan.h
One fix to pim vxlan behavior and several debug changes to make debugging easier on the eyes.
The pim vxlan behavior change is to be more persistent about sending the Null Register on startup.   Effectively one thing that was noticed during internal testing is that the null register is sometimes not received on the RP.  Just sending one at startup time ( when all the other routers/switches are starting up too ) leave you with a situation where the next Null register is 60 seconds out.  PIM VXlan wants to build the SPT tree as fast as possible.  So let's facilitate this.
=> Pim vxlan issues

bgpd/bgp_network.c
In an EBGP multihop configuration with dynamic neighbors, the TTL configured is not being updated for the socket.
Issue:
Assume the following topology:
Host (Dynamic peer to spine - 192.168.1.100) - Leaf - Spine (192.168.1.1)
When the host establishes a BGP multihop session to the spine, the connection uses the MAXTTL value instead of the configured TTL (in this case, 2). This issue is only observed with dynamic peers.
Logs: look at the TTL is still MAXTTL, instead of “2” configured.
18:13:18.872395 48:b0:2d:0c:58:0b > 48:b0:2d:66:64:6b, ethertype IPv4 (0x0800), length 85: (tos 0xc0, ttl 255, id 32078, offset 0, flags [DF], proto TCP (6), length 71)
192.168.1.100.179 > 192.168.1.1.40967: Flags [P.], cksum 0xfe89 (correct), seq 28406:28425, ack 28424, win 255, options [nop,nop,TS val …
=> bgpd: Set correct TTL for the dynamic neighbor peers

bgpd/bgp_damp.h
=> bgpd: Drop dampening `tmax` variable from struct

lib/northbound_oper.c
** CID 1575595:  Null pointer dereferences  (REVERSE_INULL)
=> lib: fix coverity issue

buildtest.sh
- Replace `make` with the 'MAKE' variable to support `gmake` on BSD systems.
- Reorder `mktemp` options for the FreeBSD implementation
=> build: make buildtest.sh BSD compatible

pimd/pim_msg.c, pimd/pim_zebra.c
1) Refactor a function in pim_msg.c to make it better indented
2) Fix some debugs in pim that now show the vrf name instead of the id.
=> Some code realignment in pim

mgmtd/mgmt_main.c
We don't really need full VRF infrastructure in mgmtd. We only need to register vty commands.
=> mgmtd: remove full vrf initialization

lib/if.c, yang/frr-interface.yang
Technically changing a leaf from uint16 to uint32 is a NBC change; however, increasing this to uint32 should not break anyone in reality.
=> yang: lib: interface MTUs can be larger than uint16

tests/topotests/bgp_evpn_mh/test_evpn_mh.py
Getting this error:
2024-01-17 19:05:20,688 WARNING: torm11: Router(torm11): proc failed: rc 255 pid 2436134
args: /usr/bin/nsenter --mount=/proc/2435168/ns/mnt --net=/proc/2435168/ns/net --uts=/proc/2435168/ns/uts -F /bin/bash -c /sbin/bridge vlan add vid 1000 dev bridge
stdout: RTNETLINK answers: Operation not supported
stderr: *empty*
As I understand it the correct thing to do here is pass in: bridge vlan add vid 1000 dev bridge self
=> tests: Fix test_evpn_mh.py to correctly call bridge program

doc/user/basic.rst, lib/.gitignore, lib/log_vty.c, lib/subdir.am, vtysh/.gitignore, vtysh/subdir.am, vtysh/vtysh.c
Add a config that specifies per-daemon log file names. The new clis are like this:
log daemon <name> file <file> [<level>]
no log daemon <name> file [file [level]]
We've talked about wanting to do this to support transition to a single integrated config, so this is sort of a "what do we think about this" PR.
Move the handy generated list of daemon names from vtysh/ to lib/, edit the gitignore files to match.
=> lib,vtysh: add per-daemon log file config

zebra/zebra_nhg.h
The NEXTHOP_GROUP_FPM #define conflicts with
NEXTHOP_GROUP_KEEP_AROUND.  Not ideal let's fix
this.
=> zebra: Fix NEXTHOP_GROUP_FPM define value

doc/user/pathd.rst, pathd/path_pcep_cli.c, pceplib/pcep_session_logic_counters.c, pceplib/pcep_utils_counters.c, pceplib/pcep_utils_counters.h, pceplib/test/pcep_utils_counters_test.c
Add support to dump sr-te pcep session in json output.
````
ubuntu2204# show sr-te pcep session 
PCE q
PCE IP 192.0.2.40 port 4189
PCC IP 192.0.2.10 port 4189
PCC MSD 10
Session Status UP
Precedence 10, best candidate
Confidence normal
Timer: KeepAlive config 30, pce-negotiated 70
Timer: DeadTimer config 120, pce-negotiated 120
Timer: PcRequest 30
Timer: SessionTimeout Interval 30
Timer: Delegation Timeout 10
No TCP MD5 Auth
PCE SR Version draft07
Next PcReq ID 5
Next PLSP  ID 2
Connected for 171 seconds, since 2023-10-28 09:36:44 UTC
PCC Capabilities: [PCC Initiated LSPs] [Stateful PCE] [SR TE PST]
PCE Capabilities: [Stateful PCE] [SR TE PST]
PCEP Message Statistics
Sent   Rcvd
Message Open:     2      1
Message KeepAlive:     1      6
Message PcReq:     4      0
Message PcRep:     0 …
```
=> Dump PCEP session in json format

bgpd/bgp_routemap_nb_config.c
Add missing break. Currently, lib_route_map_entry_match_destroy is called on every commit stage, but it should run only on APPLY.
=> bgpd: fix route-map match probability deconfiguration callback

bgpd/bgp_rpki.c
Fix 16 RPKI coverity scanner issues 1575911 to 1575926
=> bgpd: fix RPKI coverity scanner issues

mgmtd/mgmt_txn.c
The log doesn't provide any valuable information, so removing it instead of adding a check.
=> mgmtd: remove unguarded debug log

lib/if.h, tests/topotests/zebra_multiple_connected/test_zebra_multiple_connected.py, zebra/connected.c, zebra/if_netlink.c, zebra/interface.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h
It breaks NetworkManager because NM automatically sets this flag.
=> Revert `noprefixroute` stuff

lib/if.h, tests/topotests/zebra_multiple_connected/test_zebra_multiple_connected.py, zebra/connected.c, zebra/if_netlink.c, zebra/interface.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h
It breaks NetworkManager because NM automatically sets this flag.
=> Revert noprefixroute stuff

sharpd/sharp_zebra.c
New commits had an assignment instead of a comparison option.  Coverity wisely found it.
=> sharpd: Fix coverity issues

pceplib/test/pcep_utils_counters_test.c
The following compilation error happens, with pcep test files.
> In file included from pceplib/test/pcep_utils_counters_test.c:31:
> pceplib/test/pcep_utils_counters_test.c: In function 'test_create_subgroup_counter':
> pceplib/test/pcep_utils_counters_test.c:127:25: error: too few arguments to function 'create_subgroup_counter'
>   127 |         CU_ASSERT_FALSE(create_subgroup_counter(subgroup, counter_id + 1,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> In file included from pceplib/test/pcep_utils_counters_test.c:33:
> ./pceplib/pcep_utils_counters.h:163:6: note: declared here
>   163 | bool create_subgroup_counter(struct counters_subgroup *subgroup,
>       |      ^~~~~~~~~~~~~~~~~~~~~~~
> Makefile:10948: recipe for target …
=> pceplib: fix compilation error

bgpd/bgp_route.c, doc/user/bgp.rst
=> bgpd: Use single whitespace when displaying show bgp summary

eigrpd/eigrp_cli.c, isisd/isis_cli.c, lib/northbound.c, lib/northbound.h, lib/northbound_confd.c, lib/northbound_sysrepo.c, pimd/pim_cmd_common.c, ripd/rip_cli.c, ripngd/ripng_cli.c, vrrpd/vrrp_vty.c, zebra/interface.c
Currently, when editing a leaf-list, `nb_candidate_edit` expects to receive its xpath without a predicate and the value in a separate argument, and then creates the full xpath. This hack is complicated, because it depends on the operation and on the caller being a backend or not. Instead, let's require to always include the predicate in a leaf-list xpath. Update all the usages in the code accordingly.
=> lib: remove leaf-list xpath hack from northbound

lib/zclient.c, lib/zclient.h, nhrpd/linux.c, nhrpd/netlink.h, nhrpd/nhrp_interface.c, nhrpd/nhrp_route.c, nhrpd/nhrpd.h, tests/topotests/nhrp_topo/test_nhrp_topo.py, zebra/interface.c, zebra/interface.h, zebra/zapi_msg.c
Unset the IFF_NOARP interface flag using a ZAPI message. It removes the dependency to if.h headers.
=> nhrpd: unset noarp flag using a zapi message

bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgpd.h
Use enum instead of int, and make the compiler happy when using -format-overflow.
Without this patch, it does not compile e.g. on Debian12.
=> bgpd: Fix format overflow for graceful-restart debug logs

bgpd/bgp_rpki.c, pceplib/pcep_socket_comm_mock.c, pceplib/test/pcep_msg_messages_test.c, pceplib/test/pcep_msg_object_error_types_test.c, pceplib/test/pcep_msg_objects_test.c, pceplib/test/pcep_msg_tlvs_test.c, pceplib/test/pcep_msg_tools_test.c, pceplib/test/pcep_pcc_api_test.c, pceplib/test/pcep_utils_counters_test.c
a) pceplib was not building for testing unless you have the `libcunit1`  package installed.
b) bgp_rpki needed to have the correct print formatter.
Just some stuff preventing usage of `--enable-werror` for builds.
=> Compile issue fixups

pbrd/pbr_nht.c
Issue:
Previously, the PBR common was updated for every rule update or deletion
example:
let say we have three rule 11, 12, 13 and if we are removing rule 12. in the current code we are making the entire map "valid" to false.
pbr-map MAP1 seq 11
match src-ip 90.1.1.2/32
set nexthop 20.1.1.2 swp1
pbr-map MAP1 seq 12
match src-ip 90.1.1.3/32
set nexthop 20.1.1.2 swp1
pbr-map MAP1 seq 13
match src-ip 90.1.1.4/32
set nexthop 20.1.1.2 swp1
no pbr-map MAP1 seq 12 ==> turns whole map valid to false.
r1(config)# end
r1# show pbr map
pbr-map MAP1 valid: no
Seq: 11 rule: 310
Installed: yes Reason: Valid
SRC IP Match: 90.1.1.2/32
nexthop 20.1.1.2 swp1
Installed: yes Tableid: 10002
Seq: 13 rule: 312
Installed: yes Reason: Valid
SRC IP Match: 90.1.1.4/32
nexthop 20.1.1.2 swp1
Installed: yes Tableid: …
=> pbrd: Fix PBR handling for last rule deletion

bgpd/bgp_updgrp.c, bgpd/bgpd.h
Approaching the limits of uint32.
=> bgpd: Increase peer's struct cap from uint32 to uint64

sharpd/sharp_vty.c, sharpd/sharp_zebra.c, sharpd/sharp_zebra.h
Wanted to do some testing of redistribute without having to restart sharpd over and over.  Added ability to turn off the `sharp watch redistribute XX` functionality.
=> sharpd: Add ability to turn off watching of redistribution

bgpd/bgp_route.c
Comparing pointers is not the appropriate way to know if the label values are the same or not. Perform a memcmp call instead is better.
Fixes: 8ba710505735 ("bgpd: fix valgrind flagged errors")
=> bgpd: fix mpls label pointer comparison

configure.ac, debian/frr.install, doc/user/installation.rst, redhat/frr.spec.in, snapcraft/snapcraft.yaml.in
IRDP client (rdisc) was deleted from iputils more than 2 years ago. It's time to drop IRDP, but first let's stop building and including it in the packages by default to see if anyone will be complaining.
=> zebra, build: disable irdp by default

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_mplsvpn.c, bgpd/bgp_nht.c, tests/topotests/bgp_l3vpn_to_bgp_vrf/customize.py, tests/topotests/bgp_l3vpn_to_bgp_vrf/r1/bgpd.conf, tests/topotests/bgp_l3vpn_to_bgp_vrf/r1/zebra.conf, tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py, tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_down.py
If 'bgp network import-check' is defined on the source BGP session,
prefixes that are defined with the network command cannot be leaked to
the other VRFs BGP table even if they are present in the origin VRF RIB.
Always validate the nexthop of BGP static routes (i.e. defined with the
network statement) if 'network import-check' is defined on the source
BGP session and the prefix is present in source RIB.
=> bgpd: fix VRF leaking with 'network import-check'

lib/bitfield.h
Realloc doesn't init - ensure a newly-allocated word is inited.
=> lib: init new bitfield word after realloc

bgpd/bgp_attr.h, bgpd/bgp_damp.h, bgpd/bgp_route.h, bgpd/bgpd.h
Some low-hanging fruits to optimize the memory, especially for attr, nlri data structures. Looks like we can safe ~100Mb of memory easily for 2 BGP full tables.
=> bgpd: Some memory optimizations

debian/frr.pam, redhat/frr.pam
With a current pam_rootok.so, it works only with `root` account. If the user is under `frrvty`, `frr` group, it gets the error:
```
% groups | grep -o -E "frrvty|frr"
frrvty
frr
% vtysh -c 'end'
vtysh_pam: Failed in account validation: Permission denied(6)
```
Checking the logs:
```
vtysh[23930]: pam_rootok(frr:account): root check failed
```
Let's require a valid user, instead of the root user only.
=> packaging: Require account validation with pam_unix.so if PAM enabled

bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_routemap.c, tests/topotests/bgp_aggregate_address_route_map/test_bgp_aggregate-address_route-map.py
Closes https://github.com/FRRouting/frr/issues/15241
=> bgpd: Reinstall aggregated routes if using route-maps and it was changed

doc/user/basic.rst, tools/gen_northbound_callbacks.c, vtysh/vtysh.c
Add the cli_show (config write) callback when emitting the create or modify callback in the northbound template. These are pretty necessary, and if they're not in the template, they have to be hand-crafted. Also unhide the "show configuration running" cli that interrogates the NB: this is pretty darn useful when doing NB work, and it's hard to use if it's hidden.
The CI checkpatch script complains because I've added the bare copyright line to the auto-gen nb template file.
=> tools, vtysh: add the cli write callback, unhide an NB show command

doc/developer/northbound/retrofitting-configuration-commands.rst
pointed out by a user in slack
=> doc: fix misformatted list in nbapi docs

bgpd/bgp_advertise.c
Seen by code review.
In bgp_adj_in_set(), attr has not yet been interned. adj->attr is always different from attr. adj->attr is always uninterned and interned even if attr and adj->attr are identical.
Fix the comparison.
=> bgpd: fix attr comparaison bgp_adj_in_set

lib/mgmt_be_client.c, lib/mgmt_be_client.h, lib/mgmt_fe_client.c, lib/mgmt_fe_client.h, lib/vty.c, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_ds.c, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_txn.c
The old code using `ALL_CAP_MACROS` draws too much attention away from the actual functional code. Use localized names that are still noticeably different don't demand you stare at them instead of the actual functional code.
=> lowercase and localize debug/err macros

babeld/babeld.h, bfdd/bfdd.c, bgpd/bgpd.h, eigrpd/eigrp_const.h, fpm/fpm.h, isisd/isis_main.c, ldpd/ldpd.c, lib/libfrr.c, lib/libfrr.h, lib/zebra.h, mgmtd/mgmt.h, nhrpd/nhrpd.h, ospf6d/ospf6_main.c, ospfd/ospf_api.h, ospfd/ospfd.h, pathd/path_main.c, pbrd/pbr_main.c, pimd/pimd.h, ripd/ripd.h, ripngd/ripngd.h, sharpd/sharp_main.c, staticd/static_main.c, vrrpd/vrrp_main.c, zebra/dplane_fpm_nl.c, zebra/zserv.h
Create a single registry of default port values that daemons are using. Most of these are vty ports, but there are some others for features like ospfapi and zebra FPM. Currently, the various values are scattered through the code.
=> *: create a single registry of daemons' default port values

lib/event.c
It's unlikely that an operator will ever set a fd
limit of over 100k.  Let's warn the operator that
things are in a bit of a wonky state.
Fixes: #15280
=> lib: Warn operator when fd limit is set too large

lib/vrf.c
Remove operational data check from CLI command. It never works in mgmtd and it is not needed in backend daemons because it's done in `lib_vrf_destroy` callback.
=> lib: fix "no vrf" command

zebra/zebra_rib.c
Fix this:
*********************************************************************************** Address Sanitizer Error detected in zebra_opaque.test_zebra_opaque/r3.asan.zebra.11099
================================================================= ==11099==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 66 byte(s) in 1 object(s) allocated from:
#0 0x7f527fc06b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x7f527f5e852b in qmalloc lib/memory.c:100
#2 0x56418d20832d in zread_route_add zebra/zapi_msg.c:2125
#3 0x56418d215d08 in zserv_handle_commands zebra/zapi_msg.c:4011
#4 0x56418d32ab5b in zserv_process_messages zebra/zserv.c:520
#5 0x7f527f6938d3 in event_call lib/event.c:2003
#6 0x7f527f5cb692 in frr_run lib/libfrr.c:1218
#7 0x56418d1c3336 in …
=> zebra: Fix opaque memory leak in rare situation

bgpd/bgp_rpki.c, lib/frr_pthread.c, lib/frr_pthread.h, lib/frrcu.c, lib/frrcu.h
Fix the following crash when logging from rpki_create_socket():
> #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f6e21723798 in core_handler (signo=6, siginfo=0x7f6e1e502ef0, context=0x7f6e1e502dc0) at lib/sigevent.c:248
> #3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #4  0x00007f6e2144e537 in __GI_abort () at abort.c:79
> #5  0x00007f6e2176348e in _zlog_assert_failed (xref=0x7f6e2180c920 <_xref.16>, extra=0x0) at lib/zlog.c:670
> #6  0x00007f6e216b1eda in rcu_read_lock () at lib/frrcu.c:294
> #7  0x00007f6e21762da8 in vzlog_notls (xref=0x0, prio=2, fmt=0x7f6e217afe50 "%s:%d: %s(): assertion (%s) failed", ap=0x7f6e1e504248) at lib/zlog.c:425
> #8  0x00007f6e217632fb in vzlogx (xref=0x0, …
=> bgpd,lib: fix logging from rpki_create_socket()

bgpd/bgp_rpki.c, lib/frr_pthread.c
See individual commits.
1) Ensure the non-controlled startup moves the rcu data structure creation to the earliest point possible.  Else calls into things like event_master_create will likely cause a crash
2) Ensure that the rpki pthreads only call the non-controlled startup one time.
=> Rcu bites the bitey thing

doc/user/bgp.rst, doc/user/mgmtd.rst, doc/user/zebra.rst
The rule is to document only positive versions of commands.
=> doc: remove [no] from commands

lib/if.c, lib/if.h, lib/routing_nb.c, lib/routing_nb.h, lib/vrf.c, lib/vrf.h, mgmtd/mgmt_main.c
Only --vrfwnetns works right now, because -n was missing from short ops. Also add the missing help.
=> mgmtd: fix missing -n flag and help

mgmtd/mgmt_main.c
mgmtd reads config files on its own, it doesn't need libfrr to do that. The code is already skipped, because mgmtd uses `di->read_in` thread for config reading and libfrr doesn't reschedule the thread, so this commit just removes the dead code.
=> mgmtd: disable lib code for config reading

lib/if.c, lib/if.h, lib/routing_nb.c, lib/routing_nb.h, lib/vrf.c, lib/vrf.h, mgmtd/mgmt_main.c
mgmtd is supposed to only register CLI callbacks. If configuration callbacks are registered, they are getting called on startup when mgmtd reads config files, and they can use infrastructure that is not initialized on mgmtd, or allocate some memory that is never freed.
=> lib, mgmtd: don't register NB config callbacks in mgmtd

lib/yang.c, mgmtd/subdir.am
Fixes the following warnings:
```
MGMTD: [HG1WF-2N96F] YANG model "ietf-yang-metadata@*" "*@*"not embedded, trying external file
MGMTD: [HG1WF-2N96F] YANG model "frr-zebra-route-map@*" "*@*"not embedded, trying external file
```
=> lib, mgmtd: fix missing embedded modules

zebra/rib.h
The `struct route_entry` had items that were almost never used at the front of the data structure resulting in items that would be loaded first into memory that were never used.  Let's reorg a tiny bit and put all the frequently used items in the first cache line.  I'm sure people will notice .000000001 speedup
new layout:
sharpd@eva /w/h/s/frr1 (reorg_route_entry)> /home/sharpd/pahole/build/pahole --reorganize --show_reorg_steps -C route_entry zebra/.libs/zebra struct route_entry {
struct re_list_item        next;                 /*     0     8 */
struct nhg_hash_entry *    nhe;                  /*     8     8 */
uint32_t                   nhe_id;               /*    16     4 */
uint32_t                   nhe_installed_id;     /*    20     4 */
int                        type; …
=> zebra: Reorg `struct route_entry` to have important bits first

doc/developer/rcu.rst
Not necessarily the correct place for this but there is no other place and it needs to be called out and I would rather have some documentation in place.  Long term I would like to add a bunch of frr_pthread documentation but at this point in time it's not there.  We can
re-arrange when that happens.
=> doc: Add some documentation around a new pthread call

doc/user/bgp.rst
There was a question in regards to how the update-source choose the ip address for the source when using the `update-source` command in BGP.  Upon looking at the code, I was a but surprised, so I decided to document this behavior.
=> doc: Document `update-source <IFNAME>` command better

bgpd/rfapi/rfapi_vty.c
98efa5bc6b ("bgpd: bgp_path_info_extra memory optimization") has removed SID info from the extra structure.
Do not test for extra presence.
Fixes: 98efa5bc6b ("bgpd: bgp_path_info_extra memory optimization")
=> bgpd: fix displaying srv6 sid

bgpd/bgp_route.c
No need to init new_attr. It is not used until it is overridden.
> new_attr = *attr;
=> bgpd: remove dead label code in bgp_update

mgmtd/subdir.am
Fix duplicate definition of frr_affinity_map_cli_info in libfrr.so.0 and libmgmt_be_nb.so.0
> =================================================================
> ==3860488==ERROR: AddressSanitizer: odr-violation (0x7f12c98c4d20):
>   [1] size=296 'frr_affinity_map_cli_info' lib/affinitymap_cli.c:77:35
>   [2] size=296 'frr_affinity_map_cli_info' lib/affinitymap_cli.c:77:35
> These globals were registered at these points:
>   [1]:
>     #0 0x7f12c9a36f40 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
>     #1 0x7f12c9585b7d in _sub_I_00099_1 (/lib/libfrr.so.0+0x185b7d)
>     #2 0x7f12ca437fe1 in call_init elf/dl-init.c:72
>
>   [2]:
>     #0 0x7f12c9a36f40 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
>     #1 …
=> lib: fix affinity map duplicate

lib/vty.h, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_txn.c, vtysh/vtysh.c, vtysh/vtysh_config.c
Fixes https://github.com/FRRouting/frr/issues/15262
Probably fixes https://github.com/FRRouting/frr/issues/15267
=> Fix conflict in mgmtd on startup

nhrpd/netlink_arp.c
when neighbor is added (due to routing) at the same as NHRP is adding the neighbor entry, NHRP ends up using the null lladdr vs the address learned via NHRP.
=> nhrp: fix race condition in  null lladdr from zebra

lib/sockopt.c
Closes https://github.com/FRRouting/frr/issues/15321
=> bgpd: Do not show TCP MSS if the socket is broken

bgpd/bgp_route.c, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h
When a BGP flowspec peering stops, the BGP RIB entries for IPv6 flowspec entries are removed, but not the ZEBRA RIB IPv6 entries.
Actually, when calling bgp_zebra_withdraw() function call, only the AFI_IP parameter is passed to the bgp_pbr_update_entry() function in charge of the Flowspec add/delete in zebra. Fix this by passing the AFI parameter to the bgp_zebra_withdraw() function.
Note that using topotest does not show up the problem as the flowspec driver code is not present. Without that, routes are not installed, and can not be uninstalled.
Fixes: 529efa234655 ("bgpd: allow flowspec entries to be announced to zebra")
Link: https://github.com/FRRouting/frr/pull/2025
=> bgpd: fix flushing ipv6 flowspec entries when peering stops

tools/frr-reload.py
This is a combined backport PR with all later fixes in `master` to `stable/9.0`.
Closes #15299
=> frr-reload: backport fixes from master for stable/9.0

bgpd/bgp_mplsvpn.c, tests/topotests/bgp_srv6l3vpn_route_leak/pe1/results/vrf20_ipv4.json, tests/topotests/bgp_vrf_route_leak_basic/r1/bgpd.conf, tests/topotests/bgp_vrf_route_leak_basic/r1/zebra.conf, tests/topotests/bgp_vrf_route_leak_basic/setup_vrfs, tests/topotests/bgp_vrf_route_leak_basic/test_bgp-vrf-route-leak-basic.py, tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-ray.txt
The interface of routes leaked from another VRF is incorrect in the following cases:
1. the route originates from the "network" statement, the nexthop interface is unknown
`> B   192.0.2.0/24 [20/0] is directly connected, unknown (vrf r1-cust1) inactive, weight 1, 00:03:40`
2. the route originates from "redistribute connected", the nexthop interface is the interface from the source VRF, which is unknown in the destination VRF.
`> B>* 172.16.29.0/24 [20/0] is directly connected, r1-eth4 (vrf r1-cust1), weight 1, 00:00:02`
The expected output is:
```
> B>* 192.0.2.0/24 [20/0] is directly connected, r1-cust1 (vrf r1-cust1) inactive, weight 1, 00:03:40
> B>* 172.16.29.0/24 [20/0] is directly connected, r1-cust1 (vrf r1-cust1), weight 1, 00:00:02
```
=> bgpd: fix interface of routes leaked from another VRF

ospfd/ospf_ri.c
frr-reload.py will walk through all config contexts and prepend no to the CLI command. This requires that the vtysh shell code accepts a full command.
To Reproduce
```
vtysh -c "conf t" -c "router ospf" -c "router-info area"
vtysh -c "conf t" -c "router ospf" -c "no router-info area" % Unknown command: no router-info area
vtysh -c "conf t" -c "router ospf" -c "no router-info"
```
Closes #15335
Backport to `stable/9.0` and `stable/9.1`
=> ospfd: add support for "no router-info [<area|as>] command"

ospfd/ospf_sr.c
This fixes the initial implementation of commit 7743f2f8c00 ("OSPFd: Update Segment Routing PR following review") where it wsa not possible to remove the "segment-routing node-msd" CLI nodes via vtysh once segment-routing got disabled.
Closes #14910
Should be backported to `stable/9.0` and `stable/9.1`
=> ospfd: can not delete "segment-routing node-msd" when SR if off

tools/frr-reload.py
This is a combined backport PR with all later fixes in master to stable/9.1.
Closes https://github.com/FRRouting/frr/issues/15299
Related to 
* https://github.com/FRRouting/frr/pull/15323
=> frr-reload: backport fixes from master for stable/9.1

pimd/pim_mroute.c, pimd/pim_upstream.c, pimd/pim_upstream.h
Topology:
```
TOR11 (FHR) --- LEAF-11---SPINE1 (RP)MSDP SPINE-2(RP)MSDP --- LEAF-12 -- TOR12 (LHR)
|         |                    |				|       |
|         -----------------------------------------------------(ECMP)   |
|         |		                                |               |
-----------------------------------------------------------------------(ECMP)
```
Issue:
In some triggers, S,G upstream is preserved even with the PP timer expiry, resulting
in S,G with NULL OILS. This could be because we create a dummy S,G upstream and
dummy channel_oif for *,G, where RPF is UNKNOWN. As a result, PIM+VXLAN traffic is never
forwarded downstream to LHR.
Fix:
when the S,G stream is running, Determine if a reevaluation of the outgoing interface
list (OIL) is required. S,G upstream should then …
=> pimd: re-evaluated S,G OILs upon RP changes and empty SG upstream oils

doc/developer/mgmtd-dev.rst
While checking the code, we can notice that they are already converted.
Suggested-by: Igor Ryzhov <iryzhov@nfware.com>
=> mgmtd: ripng, libs fully converted

qpb/qpb.h
In `qpb.h` we have a bunch of functions that make use of `union g_addr`. `union g_addr` is defined in `nexthop.h`, which actually is NOT included in `qpb.h`.
Let's add the missing `#include nexthop.h`.
=> qpb: Add missing `#include nexthop.h`

bgpd/bgpd.c
Include gtsm_hops (minttl) field when copying peer structure, so that a new connection could set a proper value.
=> bgpd: fix minttl copying during peer reset

bgpd/bgp_zebra.c, tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py
bgpd: fix route recursion on leaked routes
Leaked recursive routes are not resolved.
```
VRF r1-cust1:
B>  5.1.0.0/24 [200/98] via 99.0.0.1 (recursive), weight 1, 00:00:08
*                       via 192.168.1.2, r1-eth4, weight 1, 00:00:08
B>* 99.0.0.1/32 [200/0] via 192.168.1.2, r1-eth4, weight 1, 00:00:08
VRF r1-cust4:
B   5.1.0.0/24 [20/98] via 99.0.0.1 (vrf r1-cust1) inactive, weight 1, 00:00:08
B>* 99.0.0.1/32 [20/0] via 192.168.1.2, r1-eth4 (vrf r1-cust1), weight 1, 00:00:08
```
When announcing the routes to zebra, use the peer of the ultimate bgp
path info instead of the one of the first parent path info to determine
whether the route is recursive.
The result is:
```
VRF r1-cust4:
B>  5.1.0.0/24 [20/98] via 99.0.0.1 (vrf r1-cust1) (recursive), weight 1, 00:00:02
* …
```
=> bgpd: fix route recursion on leaked routes

mgmtd/mgmt_be_adapter.c
Backend "subscribe" API allows daemons to dynamically register xpaths they are interested in. Such xpaths are not stored in hardcoded config/oper xpath arrays so this function fails to understand that a backend daemon is interested in them. Fix by using dynamic xpath maps instead which store both hardcoded and dynamic xpaths.
=> mgmtd: fix be_is_client_interested

ospfd/ospf_ext.c, ospfd/ospf_opaque.c, ospfd/ospf_ri.c, ospfd/ospf_te.c, tests/topotests/ospfapi/test_ospf_clientapi.py
When dumping OSPF database with json output, this PR add decoder for the various TLVs and sub-TLVs instead of dumping bulk of data. Supported Opaque LSA are:
- Traffic Engineering (Type 1)
- Router Information (Type 4) including PCE and Segment Routing information
- Inter-domain Link (Type 6)
- Extended Prefix (Type 7)
- Extended Link (Type 8)
=> ospfd: Add Opaque LSA decoder for json output

lib/event.c
There exists cases where just honoring the FD_LIMIT size as given to us by the operating system makes no sense. Let's just make a switch to allow for this for things like vtysh and ospfclient which will never have 1k files open at any given time.
Fixes: #15315
=> lib, ospfclient, vtysh: Allow for a minimum fd poll size

tests/topotests/bgp_snmp_bgp4v2mib/test_bgp_snmp_bgp4v2mib.py, tests/topotests/lib/snmptest.py
Fixes failures on the SNMP parsing in the traps on `bgp_snmp_bgp4v2mib` topotest. The original code skipped every 2nd request which will cause intermittent failures based on timing and how many SNMP traps are produced.
=> topotests: fix snmptrap log OID parsing

configure.ac, doc/user/installation.rst, vtysh/vtysh.c
This code has been deprecated for over a year and frankly needs to be removed from the system.
=> vtysh: Remove deprecated shell_access code

zebra/interface.c, zebra/interface.h, zebra/redistribute.c, zebra/zebra_nhg.c, zebra/zebra_nhg.h, zebra/zebra_vty.c
See individual commits but this is a bunch of code cleanup.
=> Nhg stuffs

bgpd/bgp_rpki.c, ospfd/ospf_te.c
=> More sa failures

tests/topotests/ospf_suppress_fa/r2/ospfd.conf
Set static router-id for OSPF, because otherwise it depends on timing of router-id updates received from zebra and may differ between test runs.
Fixes #15261
=> tests: fix ospf_suppress_fa timing issue

fpm/fpm.proto, fpm/fpm_pb.h
This PR extends the FPM protobuf implementation to support sending SRv6 SIDs through FPM using Protobuf as the message format.
=> fpm: Add support for SRv6 to FPM protobuf

ospfd/ospf_ldp_sync.c
LDP-Sync is automatically enabled on interfaces when turned on in
router ospf context.   The user can remove ldp-sync from running
on an interface, by issuing a "no ip ospd mpls ldp-sync" command.
To remove all ldp-sync interface commands the user must delete
ldp-sync at the router level.  The code was not correctly removing
the config.   This PR fixes that issue.   Now the extra cli
ldp-sync interface commands are removed when ldp-sync is disabled.
=> ospfd: fix cli shown in running config when turning off ldp-sync

lib/base64.c, lib/base64.h
Remove adding of line feeds when encondig. We're using these functions only for encoding binary data for storing in YANG data tree.
According to RFC 7950, section 9.8.2:
```
9.8.2.  Lexical Representation
Binary values are encoded with the base64 encoding scheme (see
Section 4 in [RFC4648]).
```
According to mentioned RFC 4648, section 3.1:
```
Implementations MUST NOT add line feeds to base-encoded data unless
the specification referring to this document explicitly directs base
encoders to add line feeds after a specific number of characters.
```
Therefore, line feeds must not be added to the encoded data.
=> lib: fix base64 encoding

lib/affinitymap_northbound.c, lib/northbound.c
```
lib: add missing priority for affinity map callbacks
Other objects depend on affinity-maps being created before them by using
leafref with require-instance true. Set the priority to ensure that.
```
```
lib: fix order of northbound callbacks
When ordering the NB callbacks according to their priorities, if the
operation is "destroy" we should reverse the order, to destroy the
dependants before the dependencies.
This fixes the crash, that can be reproduced with the following steps:
frr# conf term file-lock
frr(config)# affinity-map map bit-position 10
frr(config)# interface test
frr(config-if)# link-params
frr(config-link-params)# affinity map
frr(config-link-params)# exit
frr(config-if)# exit
frr(config)# mgmt commit apply
frr(config)# no affinity-map map
frr(config)# interface test …
```
=> Fix order of NB callbacks (and a crash)

tests/topotests/bgp_evpn_vxlan_svd_topo1/PE1/evpn.vni.json, tests/topotests/bgp_evpn_vxlan_svd_topo1/PE2/evpn.vni.json, zebra/zebra_evpn.c, zebra/zebra_vxlan.c
Both zebra_evpn.c and zebra_vxlan.c have items that were deprecated a year ago.  Let's remove them.
=> zebra: Remove deprecated items

doc/user/isisd.rst, isisd/isis_spf.c, isisd/isis_sr.c
Add the ability to display all the flexible-algorithms at the same time in the following commands:
- show isis route algorithm
- show isis topology algorithm
- show isis segment-routing node algorithm
It is currently only possible to show only one given algorithm X
- show isis route algorithm X
- show isis topology algorithm X
- show isis segment-routing node algorithm X
=> isisd: display all the algorithms at the same time

tests/topotests/bgp_evpn_mh/test_evpn_mh.py
This test is failing locally for me 100% of the time since zebra was converted to mgmtd usage.  The failed command is:
torm11# show evpn mac vni 1000 mac 00:00:00:00:00:11 json {
"00:00:00:00:00:11":{
"type":"auto",
"uptime":"00:02:01",
"localSequence":0,
"remoteSequence":0,
"detectionCount":0,
"isDuplicate":false,
"syncNeighCount":0,
"neighbors":{
"active":[
],
"inactive":[
"45.0.0.11"
]
}
}
}
The test is expecting an esi as a key in the output.  Re-arranging the startup of the tor's before the hosts fixes the issue.
=> tests: bgp_evpn_mh timing issue fix

bgpd/bgp_attr.h, bgpd/bgp_mpath.c, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_snmp_bgp4v2.c, bgpd/bgp_zebra.c
Move mp_nexthop_prefer_global boolean attribute to nh_flags. It does not currently save memory because of the packing.
After the change:
```
$ pahole /usr/lib/frr/bgpd | grep -A100 'struct attr {' | grep -B100 -m1 '}'
struct attr {
struct aspath *            aspath;               /*     0     8 */
struct community *         community;            /*     8     8 */
long unsigned int          refcnt;               /*    16     8 */
_uint64_t                  flag;                 /*    24     8 */
struct in_addr             nexthop;              /*    32     4 */
uint32_t                   med;                  /*    36     4 */
uint32_t                   local_pref;           /*    40     4 */
ifindex_t                  nh_ifindex;           /*    44     4 */
uint8_t …
```
=> bgpd: move mp_nexthop_prefer_global boolean attribute to nh_flags

lib/mgmt_fe_client.c, lib/mgmt_fe_client.h
Notifications are sent by mgmtd for each session of a client, so they should be processed once per each session.
Also, add session_id parameter to an async_notification callback as all other callbacks have this parameter.
=> lib: fix processing of notifications on mgmt fe client

lib/northbound.c
By calling `ly_log_options` with `LY_LOSTORE`, the current code effectively disables libyang logging and never enables it back. The call is done to get the current logging options, but we don't really need that. When looking for a schema node, we don't want neither to log nor to store the error, so simply set the temporary options to 0.
=> lib: fix setting temporary log options for libyang

bgpd/bgp_aspath.h, bgpd/bgp_filter.c, bgpd/bgp_filter.h, bgpd/bgp_routemap.c, tests/topotests/bgp_set_aspath_exclude/test_bgp_set_aspath_exclude.py
neighbor 192.168.1.2 remote-as external
neighbor 192.168.1.2 timers 3 10
neighbor 192.168.1.2 route-map r2 in
!
ip prefix-list p1 seq 5 permit 172.16.255.31/32
!
route-map r2 permit 10
match ip address prefix-list p1
set as-path exclude 65003
route-map r2 permit 20
set as-path exclude all
!
we make the following commands
bgp as-path access-list FIRST permit ^65
bgp as-path access-list SECOND permit 2
route-map r2 permit 6
set as-path exclude as-path-access-list SECOND
and then
no bgp as-path access-list SECOND permit 2
clear bgp *
we have the following crash in bgp
Stack trace of thread 536083:
#0  0x00007f87f8aacfe1 raise (libpthread.so.0 + 0x12fe1)
https://github.com/FRRouting/frr/pull/1 …
=> bgpd: fix no bgp as-path access-list issue 

zebra/zebra_evpn.c
=> zebra: changes for code maintainability

lib/filter.c, lib/filter.h, lib/filter_nb.c
```
lib: fix access-list entry update
When an access-list entry is updated, current NB code calls notification
hooks for each updated field. It means that when multiple fields of an
entry are changed in a single commit, the hooks are run with an interim
state of an access-list instead of a final one. To fix the issue, we
should call the hooks once, after all fields of an entry are updated.
```
```
lib: fix prefix-list entry update
When a prefix-list entry is updated, current NB code calls the
replacement code multiple times, once per each updated field. It means
that when multiple fields of an entry are changed in a single commit,
the replacement is done with an interim state of a prefix-list instead
of a final one. To fix the issue, we should call the replacement code
once, after all …
```
=> lib: fix access/prefix-list entry update

bgpd/bgp_addpath.h, bgpd/bgp_fsm.c, bgpd/bgp_open.c, bgpd/bgp_open.h, bgpd/bgp_packet.c, bgpd/bgp_updgrp.c, bgpd/bgp_updgrp_adv.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_addpath_paths_limit/r1/frr.conf, tests/topotests/bgp_addpath_paths_limit/r2/frr.conf, tests/topotests/bgp_addpath_paths_limit/r3/frr.conf, tests/topotests/bgp_addpath_paths_limit/r4/frr.conf, tests/topotests/bgp_addpath_paths_limit/r5/frr.conf, tests/topotests/bgp_addpath_paths_limit/r6/frr.conf, tests/topotests/bgp_addpath_paths_limit/r7/frr.conf, tests/topotests/bgp_addpath_paths_limit/test_bgp_addpath_paths_limit.py
Capability: https://datatracker.ietf.org/doc/html/draft-abraitis-idr-addpath-paths-limit
Capability assigned by IANA: https://www.iana.org/assignments/capability-codes/capability-codes.xhtml
=> bgpd: Implement Paths-Limit capability

ospfd/ospf_te.c
Iggy Frankovic discovered an ospfd crash when perfomring fuzzing of OSPF LSA packets. The crash occurs in ospf_te_parse_te() function when attemping to create corresponding egde from TE Link parameters. If there is no local address, an edge is created but without any attributes. During parsing, the function try to access to this attribute fields which has not been created causing an ospfd crash.
The patch simply check if the te parser has found a valid local address. If not found, we stop the parser which avoid the crash.
=> ospfd: Solved crash in OSPF TE parsing

lib/routemap.c
Replacing https://github.com/FRRouting/frr/pull/15414
=> lib: Do not convert EVPN prefixes into IPv4/IPv6 if not needed

zebra/zebra_vxlan.c
A macvlan interface can have its underlying link-interface in another
namespace (aka. netns). However, by default, zebra does not know the
interface from the other namespaces. It results in a crash the pointer
to the link interface is NULL.
> 6  0x0000559d77a329d3 in zebra_vxlan_macvlan_up (ifp=0x559d798b8e00) at /root/frr/zebra/zebra_vxlan.c:4676
> 4676		link_zif = link_ifp->info;
> (gdb) list
> 4671		struct interface *link_ifp, *link_if;
> 4672
> 4673		zif = ifp->info;
> 4674		assert(zif);
> 4675		link_ifp = zif->link;
> 4676		link_zif = link_ifp->info;
> 4677		assert(link_zif);
> 4678
> (gdb) p zif->link
> $2 = (struct interface *) 0x0
> (gdb) p zif->link_ifindex
> $3 = 15
Fix the crash by returning when the macvlan link-interface is in another
namespace. No need to go further because …
=> zebra: fix crash when macvlan link-interface is in another netns

bgpd/bgp_ecommunity.c
The following command results in a wrong route-target display:
> # show running-config
> [..]
> route-map rmap permit 1
>  set extcommunity rt 1.45:55
> exit
> router bgp 65500
> neighbor 1.1.1.1 remote-as 65500
> address-family ipv4 unicast
>  neighbor 1.1.1.1 route-map rmap in
>
Observed output:
> # show bgp ipv4 3.3.3.3/32
> [..]
>     Extended Community: RT:1.0.0.45:55
>
The decoding of the passed cli string assumes this is an IP address, whereas it is an AS number in dotted format. Consequently, the vty output will use the ip address encoding.
Count the number of dots in the extended community format. If a single dot number is detected, the AS format is passed, and used by the vty output.
Expected output:
>
> # show bgp ipv4 3.3.3.3/32
> [..]
>    Extended Community: RT:65581:55
>
=> bgpd: fix route-target display with as dotted format

bgpd/bgp_bmp.c
"show run" displays BMP monitor AFI in upper case.
> bmp targets bmp1
>  bmp monitor IPv4 unicast loc-rib
Display it in lower case.
> bmp targets bmp1
>  bmp monitor ipv4 unicast loc-rib
=> bmp: fix vty_out for monitor afi loc-rib

configure.ac
Fix a small typo nit in the configure script.
=> tools: fix typo in configure script

bgpd/bgp_updgrp_packet.c, tests/topotests/bgp_6vpe_ebgp_topo1/h1/zebra.conf, tests/topotests/bgp_6vpe_ebgp_topo1/h2/zebra.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/bgp_summary.json, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/bgp_vrf_ipv6.json, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/bgpd.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/ipv6_routes_vrf.json, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/isisd.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe1/zebra.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe2/bgp_summary.json, tests/topotests/bgp_6vpe_ebgp_topo1/pe2/bgp_vrf_ipv6.json, tests/topotests/bgp_6vpe_ebgp_topo1/pe2/bgpd.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe2/isisd.conf, tests/topotests/bgp_6vpe_ebgp_topo1/pe2/zebra.conf, tests/topotests/bgp_6vpe_ebgp_topo1/test_bgp_6vpe_ebgp_topo1.py
6vPE enables the announcement of IPv6 VPN prefixes through an IPv4 BGP
session. In this scenario, the next hop addresses for these prefixes are
represented in an IPv4-mapped IPv6 format, noted as ::ffff:[IPv4]. This
format indicates to the peer that it should route these IPv6 addresses
using information from the IPv4 nexthop. For example:
> Path Attribute - MP_REACH_NLRI
> [...]
>     Address family identifier (AFI): IPv6 (2)
>     Subsequent address family identifier (SAFI): Labeled VPN Unicast (128)
>     Next hop:  RD=0:0 IPv6=::ffff:192.0.2.5 RD=0:0 Link-local=fe80::501d:42ff:feef:b021
>     Number of Subnetwork points of attachment (SNPA): 0
This rule is set out in RFC4798:
> The IPv4 address of the egress 6PE router MUST be encoded as an
> IPv4-mapped IPv6 address in the BGP Next …
=> bgpd: fix 6vpe nexthop

tools/frr-reload.py
bgp neighbor config can have multiple lines, if neighbor is deleted via frr-reload, no neighbor remote-as <> wipes out the neighbor, subsequent neighbor associated config deletion would throw generic error.
Frr-reload needs to move neighbor remote-as line to end and allow all other config lines to be removed.
Testing Done:
config:
```
neighbor swp3 interface remote-as external
neighbor swp3 bfd 3 300 300
neighbor swp3 password leaf11-spine
```
```
INFO: Executed "router bgp 65101  no neighbor swp3 interface remote-as external"
INFO: Failed to execute router bgp 65101  no neighbor swp3 bfd 3 300 300
INFO: Failed to execute router bgp 65101  no neighbor swp3 bfd 3 300
INFO: Failed to execute router bgp 65101  no neighbor swp3 bfd 3
INFO: Failed to execute router bgp 65101  no neighbor swp3 …
```
=> tools: fix frr-reload for nbr deletion

tests/topotests/ospf_single_switch/r1_frr.conf, tests/topotests/ospf_single_switch/r2_frr.conf, tests/topotests/ospf_single_switch/r3_frr.conf, tests/topotests/ospf_single_switch/r4_frr.conf, tests/topotests/ospf_single_switch/r5_frr.conf, tests/topotests/ospf_single_switch/r6_frr.conf, tests/topotests/ospf_single_switch/r7_frr.conf, tests/topotests/ospf_single_switch/r8_frr.conf, tests/topotests/ospf_single_switch/test_ospf_single_switch.py
A large set of routers are connected to the same switch. Each router shares a single network. All shared networks must be reachable from all routers.
=> tests: multiple OSPF routers connected to a single switch

mgmtd/mgmt_vty.c
`./configure [...] --disable-ripngd` 
could lead to:
```
mgmtd/mgmt_vty.c:614:5: warning: "HAVE_RIPNGD" is not defined, evaluates to 0 [-Wundef]
614 | #if HAVE_RIPNGD
|     ^~~~~~~~~~~
```
=> fix warning if ripngd disabled

lib/darr.c
If the initial darr capacity is not enough for the output, the `ap` is reused multiple times, which is wrong, because it may be altered by `vsnprintf`. Make a copy of `ap` each time instead of reusing.
=> lib: fix __darr_in_vsprintf

configure.ac, debian/control, debian/frr-test-tools.install, debian/not-installed, doc/developer/checkpatch.rst, doc/user/installation.rst, doc/user/zebra.rst, redhat/frr.spec.in, tests/topotests/fpm_testing_topo1/r1/fpm_counters.json, tests/topotests/fpm_testing_topo1/r1/routes_summ.json, tests/topotests/fpm_testing_topo1/r1/routes_summ_removed.json, tests/topotests/fpm_testing_topo1/r1/zebra.conf, tests/topotests/fpm_testing_topo1/test_fpm_topo1.py, tests/topotests/lib/topogen.py, tests/topotests/lib/topotest.py, tests/topotests/pytest.ini, tools/checkpatch.pl, zebra/.gitignore, zebra/dplane_fpm_nl.c, zebra/fpm_listener.c, zebra/subdir.am
Add the ability to test the fpm module dplane_fpm_nl.c. 
This includes a new daemon that needs to be added to the system from:
git@github.com:donaldsharp/fpm-stub.git
=> Add ability to test dplane_fpm_nl.c file

zebra/dplane_fpm_nl.c
Found by coverity.  Let's just lock the writeable
amount to see if it is possible.  It's ok because
we want to know if we have room *now*.  If another pthread runs it will only remove data from fnc->obuf and make more room.  So this is ok.
=> zebra: fnc->obuf could be accessed without a lock

ospfd/ospf_asbr.c
When an AS-external-route is deleted on our system and later added again with a new metric, then the ospfd would first send a LS-update to remove the old route and later another LS-update to add the route with the new metric again.
But when this metric-change happens with no time inbetween the ospfd recognizes this as the same route and does not send any LS-update. With the change made here, the ospfd will interpret this route as a different route, when the metric has changed.
=> ospfd: Send update for route with new metric

tests/topotests/bgp_peer_type_multipath_relax/test_bgp_peer-type_multipath-relax.py
Apparently test_bgp_peer_type_multipath_relax.py does no really need to run a `setup_vrfs` script.  Looking at the other configuration for this test there are no vrf's in the frr configuration.  So let's remove it
=> tests: test invokes a script which does not exist

lib/vty.c
Make errors look the same way as in regular non-mgmtd vty. We don't need to show information about some internal request names.
Before:
```
ERROR: SET_CONFIG request failed, Error: YANG error(s):
Path: Data location "/frr-affinity-map:lib/affinity-maps/affinity-map[name='a']".
Error: Unique data leaf(s) "value" not satisfied in "/frr-affinity-map:lib/affinity-maps/affinity-map[name='b']" and "/frr-affinity-map:lib/affinity-maps/affinity-map[name='a']".
```
After:
```
YANG error(s):
Path: Data location "/frr-affinity-map:lib/affinity-maps/affinity-map[name='b']".
Error: Unique data leaf(s) "value" not satisfied in "/frr-affinity-map:lib/affinity-maps/affinity-map[name='a']" and "/frr-affinity-map:lib/affinity-maps/affinity-map[name='b']".
```
=> vty: change output of errors from mgmtd

bgpd/bgp_nht.c
In make_prefix, the code checks to see if the pi->attr is non-NULL.  Since (A) we cannot have a path_info without an attribute and (B) all paths leading up to the test in make_prefix already have pi->attr deref'ed and the code is not crashing we know this is safe to remove.
=> bgpd: pi->attr is deref'ed in all paths leading up to test

lib/northbound.c
When a node is top-level, we shouldn't stop the whole processing, we should just skip this single node.
=> lib: fix apply_finish callback in northbound

configure.ac, pimd/pim_mroute.h
FRR needs to properly include the FreeBSD headers for compilation on FreeBSD.  I have setup v6 as well
but I have not even tested it.  Since I know
that the form is the same I think this is ok
at the moment.  This is a step forward.
Because of this change *clearly* no-one is even
using pim on FreeBSD.  <look at the MRT_XXX values to prove to yourself>.  In any event this is a step in the direction of getting that working again.
=> pimd: Cleanup inclusion of headers

bgpd/bgp_packet.c, bgpd/bgp_vty.c, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_addpath.py, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_fqdn.py, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_graceful_restart.py, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_orf.py, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_software_version.py
When using dynamic capabilities, do not forget to unset advertised capabilities.
Otherwise, it's kept as advertised.
=> bgpd: Unset advertised capabilities if capability is disabled

bgpd/bgp_open.c, bgpd/bgp_vty.c, bgpd/bgpd.c
If `bgp default software-version-capability` is enabled, allow unsetting this for a single neighbor also.
=> bgpd: Fix `no` form for `neighbor X capability software-version`

doc/developer/logging.rst, lib/printf/README, lib/printf/printflocal.h, lib/printf/vfprintf.c, tests/lib/test_printfrr.c
ISO C23 has new printf specifiers for `intXX_t` and cousins, most relevant for us `%w64d` for `int64_t` and `%w64u` for `uint64_t`. `w64` is a length modifier like `l` for long, `h` for `short`, and `hh` for `char`. It works in combination with `%d`/`%u`/`%x`/etc.
This picks up the `lib/printf` changes for this (straight from FreeBSD), adds a quick test and updates related docs.
The `w64` modifier is **NOT** ready for use yet since neither the compilers on older distros nor the `frr-format` plugin support type checking for it yet. If it's added to `frr-format`, it will become usable together with the `FMT_NSTD` macro¹. Unfortunately the `frr-format` plugin, being derived from GCC's internal code, is some rather impressive spaghetti and resyncing it with the upstream GCC changes for `w64` …
=> lib/printf: pick up ISO C23 / N2680 from FreeBSD

lib/yang.c
When actions and notification are defined as descendants of other nodes, they are not getting initialized, because the iterator skips them. Fix the iterator to include them when traversing the schema.
=> lib: fix initialization of northbound nodes

zebra/zserv.c
Currently, the way zebra works is it creates pthread per client (BGP is of interest in this case) and this thread loops itself in zserv_read() to check for any incoming data. If there is one, then it reads, validates and adds it in the ibuf_fifo signalling the main thread to process the message. The main thread when it gets a change, processes the message, and invokes the function pointer registered in the header command. (Ex: zserv_handlers).
Finally, if all of this was successful, this task reschedules itself and loops in zserv_read() again
However, if there are already items on the ibuf FIFO, that means zebra is slow in processing. And with the current mechanism if Zebra main is busy, the ibuf FIFO keeps growing holding up the memory.
Show memory zebra:(Example: 15k streams  hoarding …
=> zebra: backpressure - Zebra push back on Buffer/Stream creation

lib/affinitymap.c, lib/mgmt_msg_native.c, lib/netns_other.c, lib/northbound_sysrepo.c, zebra/main.c
=> Lib mtype cleanup

zebra/zebra_gr.c, zebra/zserv.c, zebra/zserv.h
Recent commit: 6b2554b94a
Exposed, via Address Sanitation, that memory was being leaked.  Unfortunately the CI system did not catch this.
Two pieces of memory were being lost: The zserv client data structure as well as anything on the client->gr_info_queue. Clean these up.
=> zebra: Cleanup leaked memory on shutdown from GR code

eigrpd/eigrp_main.c, mgmtd/mgmt_testc.c, ospf6d/ospf6_main.c
I noticed that ospf6d always had a linked list memory leak. Tracking it down shows that frr_fini() shuts down the memory system and prints out memory not cleaned up.  eigrpd, mgmtd and ospf6d all called cleanup functions after frr_fini leaving memory leaked that was not really leaked.
=> eigrpd, mgmtd, ospf6d: frr_fini is last

bgpd/bgp_conditional_adv.c, bgpd/bgp_route.c, bgpd/bgp_updgrp.h, bgpd/bgp_updgrp_adv.c
see individual commits
a) Allows unsuppress-maps to be part of the filtering system that would allow outgoing data to a peer.
b) Fix memory leak associated with late decision not to send data to peer in bgp
=> Bgp filter fun

bgpd/bgp_aspath.c, bgpd/bgp_attr.c, bgpd/bgp_ecommunity.c, bgpd/bgp_ecommunity.h, bgpd/bgp_updgrp.c
See the commit but when dumping the attributes that have been interned it is still impossible to tell them apart.  Add some more discriminating data.  There will be more in the future.
=> bgpd: Add some missing data to `show bgp attribute-info`

lib/sigevent.c
When a memory operation (malloc/free/... ) causes a crash and the call to core_handler causes another crash then instead of actually writing a core dump the alarm is hit and the daemon in trouble will not cause a core dump. Modify the shutdown code to just try to dump the buffers and leave instead of cleaning up after itself.
Back Trace:
(gdb) bt
0  0x00007f17082ec056 in __lll_lock_wait_private () from /lib/x86_64-linux-gnu/libc.so.6 1  0x00007f17082fc8bd in ?? () from /lib/x86_64-linux-gnu/libc.so.6 2  0x00007f17082fee8f in free () from /lib/x86_64-linux-gnu/libc.so.6 3  0x00007f170866c2ea in qfree (mt=<optimized out>, ptr=<optimized out>) at lib/memory.c:141 4  0x00007f17086c156a in zlog_tls_free (arg=0x55584f816fb0) at lib/zlog.c:390 5  zlog_tls_buffer_fini () at lib/zlog.c:346
6 …
=> lib: Prevent crash then another crash from happening

bgpd/bgp_route.c, bgpd/bgp_updgrp.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/bgp_sender_as_path_loop_detection/test_bgp_sender-as-path-loop-detection.py
currently:
when as-path-loop-detection is set on a peer-group.
members of the peer-group are not using that functionnality.
analysis:
the as-path-loop-detection, is not using the peer's flags
related framework.
fix:
use the peer's flag framework for as-path-loop-detection.
=> bgpd: make as-path-loop-detection conform to the framework 

lib/vrf.c, lib/vrf.h, zebra/main.c
Restore the order of execution in zebra's main thread:
vrf_terminate();
zebra_dplane_finish();
zebra_dplane_shutdown();
changed in commit 3b0e17067ee1ed09318ddb3314ad341959813d85.
vrf_terminate() enqueues routes for deletion in dplane thread.
zebra_dplane_shutdown() effectively forces dplane thread
to immediately cease and join (leaving unprocessed routes), while
zebra_dplane_finish() has a condition that prevents
zebra_dplane_shutdown() from running until all routes queued for dplane thread have been deleted.
Closes https://github.com/FRRouting/frr/issues/14062
Closes https://github.com/FRRouting/frr/issues/14178
=> zebra: fix route deletion during zebra shutdown

lib/libfrr.c
We're not calling any other termination functions to free allocated memory when daemonizing except these two. There's no reason for such an exception, and because of these calls we have the following libyang warnings every time FRR is started:
```
MGMTD: libyang: String "15" not freed from the dictionary, refcount 2
MGMTD: libyang: String "200" not freed from the dictionary, refcount 2
MGMTD: libyang: String "mrib-then-urib" not freed from the dictionary, refcount 2
MGMTD: libyang: String "1000" not freed from the dictionary, refcount 2
MGMTD: libyang: String "10" not freed from the dictionary, refcount 2
MGMTD: libyang: String "5" not freed from the dictionary, refcount 2
```
Remove these calls to get rid of the unnecessary warnings.
=> lib: remove nb/yang memory cleanup when daemonizing

bgpd/bgp_table.c, doc/developer/logging.rst
When building FRR with `--enable-dev-build`.  Add a bit of code to include the pointer value as part of the output. Helps with tracking down issues and let's us see more data when using the dev build option.
New output:
2024/03/08 19:48:56 BGP: [V0J1J-W5RHA] 11.0.20.1/32(0x5759ddf8d7c0) for 11.0.20.1/32
=> bgpd: When using dev build add pointer information to %pBD

ospfd/ospf_packet.c
With this fix, OSPF LS Updates sent in response to OSPF LS Requests during the DB Exchange process will be sent as unicasts. Unless the timing of multiple database exchanges coincides, there is little chance that the LSAs in the LS Update are required by OSPF routers other than the one which elicited the LS Update. 
While RFC 2328 is somewhat ambiguous on this point, FRR OSPFv3 (ospf6d) already does it correctly - see ospf6_lsupdate_send_neighbor(struct event *thread). Also, if there is any doubt, one can refer to the C++ code at ospf.org (John Moy's seminal OSPF reference implementation).
=> ospfd: Send LS Updates in response to LS Request as unicast.

bgpd/bgp_updgrp.c, bgpd/bgp_updgrp.h
Not used anymore. There is triggered merge check, not periodic.
=> bgpd: Drop periodic merge check functions

doc/developer/topotests.rst, lib/compiler.h, tests/lib/subdir.am, tests/topotests/grpc_basic/test_basic_grpc.py
lib: don't define a `fallthrough` in c++ to avoid conflict with protobuf c++
check: add link libs required by some versions of grpc++ or it's dependent linked libs
tests: don't fail the test due to known at exit memleaks
Closes: https://github.com/FRRouting/frr/issues/15475
=> grpc: fix grpc for various failures

zebra/zebra_vxlan.c
Whenever a link up change was detected on a macvlan device where the linked device wasn't visible in the namespace zebra was running in, the linked zebra interface was NULL. This was already handled in the event of a link down, but was ommitted from the upside. Added the same null check to the up-side.
Relates to https://github.com/FRRouting/frr/issues/13523
=> zebra: Fix crash on macvlan link down/up

ospfd/ospf_ase.c, ospfd/ospf_interface.c
OSPF intra/inter area routes were previously marked to assure they are re-installed after a fast link flap in the commit:
commit effee18744ad3e1777614f58350d74fb718d3211
Author: Donald Sharp <sharpd@nvidia.com>
Date:   Mon May 24 13:45:29 2021 -0400
ospfd: Fix quick interface down up event handling in ospf
This commit extends this fix to OSPF AS External routes as well.
=> ospfd: Assure OSPF AS External routes are installed after link flap

bgpd/bgp_main.c, bgpd/bgp_route.c, bgpd/bgp_table.h, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, bgpd/bgpd.c, bgpd/bgpd.h, lib/zclient.c
1. Modify the bgp master to hold a type safe list for bgp_dests that need to be passed to zebra.
2. Since installing/withdrawing routes into zebra is going to be changed around to be dest based in a list,
- Retrieve the afi/safi to use based upon the dest's afi/safi instead of passing it in.
- Prefix is known by the dest. Remove this arg as well
3. BGP is now keeping a list of dests with the dest having a pointer to the bgp_path_info that it will be working on.
1.  When bgp receives a prefix, process it, add the bgp_dest of the prefix into the new Fifo list if not present, update the flags (Ex: earlier if the prefix was advertised and now it is a withdrawn), increment the ref_count and DO NOT advertise the install/withdraw  to zebra yet.
2. Schedule an event to wake up to invoke the new …
=> backpressure bgp zebra client

bgpd/bgp_open.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst
Dynamic capability provides more value without resetting the sessions for some important other capabilities to exchange, like: graceful-restart, addpath, orf, fqdn, etc.
Since we support it already, enable it by default.
=> bgpd: Enable BGP dynamic capability by default for datacenter profile

bgpd/bgp_advertise.c, bgpd/bgp_advertise.h, bgpd/bgp_updgrp_adv.c
This is a backport to stable/9.0 of #14554 ; the mergify backport had merge conflicts, so I've closed that version in favor of this one.
=> bgpd: Convert the bgp_advertise_attr->adv to a fifo (backport #14554)

bgpd/bgp_mplsvpn.c
The asan memory leak has been detected:
> Direct leak of 16 byte(s) in 1 object(s) allocated from:
>     #0 0x7f9066dadd28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
>     #1 0x7f9066779b5d in qcalloc lib/memory.c:105
>     #2 0x556d6ca527c2 in vpn_leak_zebra_vrf_sid_update_per_af bgpd/bgp_mplsvpn.c:389
>     #3 0x556d6ca530e1 in vpn_leak_zebra_vrf_sid_update bgpd/bgp_mplsvpn.c:451
>     #4 0x556d6ca64b3b in vpn_leak_postchange bgpd/bgp_mplsvpn.h:311
>     #5 0x556d6ca64b3b in vpn_leak_postchange_all bgpd/bgp_mplsvpn.c:3751
>     #6 0x556d6cb9f116 in bgp_zebra_process_srv6_locator_chunk bgpd/bgp_zebra.c:3337
>     #7 0x7f906685a6b6 in zclient_read lib/zclient.c:4490
>     #8 0x7f9066826a32 in event_call lib/event.c:2011
>     #9 0x7f906675c444 in frr_run …
=> bgpd: fix srv6 memory leak detection

zebra/zebra_vty.c
Similarly to issue mentioned here: https://github.com/FRRouting/frr/issues/15277, the 'show ip route vrf all json' command doesn't work as expected, because it doesn't return a valid json object.
Command 'show ip route vrf <vrf_name> json' returns a valid json object, however for multiple vrfs the output looks like this:
{//vrf1 routes}{//vrf2 routes}{//vrf3 routes}
After the fix we get:
{"vrf1":{//vrf1 routes},"vrf2:{//vrf2 routes},"vrf3":{//vrf3 routes}}
Which is a valid json object, that can be parsed effectively using built-in modules. That makes a big difference for anyone that wants to take the json outputs for multiple vrfs and make use of them. The rest of the commands remain unaffected and behave the same.
=> vtysh, zebra: fix malformed json output for multiple vrfs in command 'show ip route vrf all json'

zebra/interface.c
Null-check the vxlan-vni array info coming into zebra from the dataplane.
Fixes: #15564
=> zebra: don't deref vxlan-vni array

tests/topotests/bgp_peer_group/r1/bgpd.conf, tests/topotests/bgp_peer_group/r1/zebra.conf, tests/topotests/bgp_peer_group/r2/bgpd.conf, tests/topotests/bgp_peer_group/r2/zebra.conf, tests/topotests/bgp_peer_group/test_bgp_peer-group.py
This topotest covers the PR-15574's coverage where a change is not to delete neighbors when the associated peer-group's remote-as is removed.
Testing:
```
test_bgp_peer-group.py::test_bgp_peer_group
---------------------------------------------------------------------------- live log call ----------------------------------------------------------------------------- 2024-03-29 18:12:22,608 INFO: r1: checking if daemons are running 2024-03-29 18:12:22,802 INFO: r2: checking if daemons are running 2024-03-29 18:12:22,911 INFO: r3: checking if daemons are running 2024-03-29 18:12:23,015 INFO: topo: Remove bgp peer-group PG1 remote-as neighbor should be retained 2024-03-29 18:12:25,605 INFO: topo: Re-add bgp peer-group PG1 remote-as neighbor should be established …
```
=> tests: add topotest for PG remote-as add del

bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c
The nexthop tracking never displays the prefix that has been used in ZEBRA to resolve its nexthop. This information will be useful if some decision has to be taken regarding any loops, that is to say if for instance a BGP prefix is resolved over a prefix in ZEBRA that is exactly the same.
Store the value in bgp nexthop context, and display it.
=> bgpd: add resolved_prefix visibility on nht

bgpd/bgp_route.c, bgpd/bgp_zebra.c
See 2nd commit for the real meat.
Effectively w/ suppress-fib-pending a withdrawal will not be sent to a peer if BGP is already in the process of waiting for a previous route install for the same route.
ie suppose you have 2 way ecmp w/ bgp-suppress-fib-pending.  peer 1 withdraws, bgp marks the route for FIB_INSTALLING and does not send an update.  Then if peer 2 withdraws it's route before zebra gives notice, when attempting to send the route via group_announce_route it sees the FIB_INSTALLING flag and does not send the withdrawal.
Closes: https://github.com/FRRouting/frr/issues/15626
=> Suppress fib funny business

tests/topotests/lib/topotest.py
In topotest, a given interface has only the ignore routes bit turned on for IPv6 only, whereas topotest is expected to turn it on for all address families.
> # show interface
> Interface r2-r3-eth2 is up, line protocol is up
> [..]
>  flags: <UP,BROADCAST,RUNNING,MULTICAST>
>  Ignore all v6 routes with linkdown
>  Type: Ethernet
>  [..]
This is because the only the 'default' ipv6 ignore sysctl is set to
1. Use the /proc/sys/net/conf/<family>/default/ignore_routes_with_linkdown flag instead, to have same behaviour for ipv4 and ipv6.
Fixes: 4958158787ce ("tests: micronet: update infra")
=> topotests: fix ignore routes with linkdown

isisd/isis_adjacency.c, isisd/isis_lfa.c, isisd/isis_sr.c, isisd/isis_sr.h, isisd/isis_zebra.c
The ISIS_SR_LAN_BACKUP should be renamed to ISIS_SR_ADJ_BACKUP.
Fixes: 26f6acafc369 ("isisd: add support for segment routing")
=> isisd: fix mispelling with ISIS_SR_LAN_BACKUP

zebra/zebra_mpls.c
Use `CHECK_FLAG()` for readability.
This PR is only cosmetic change, no functional change.
=> zebra: cosmetic change for one flag

tests/topotests/bfd_topo3/test_bfd_topo3.py
Increase the wait time in a bfd topotest; it's failing frequently in the CI runs, but the config etc seems ok.
=> tests: increase topotest wait time for bfd convergence

lib/srv6.c
Add SRv6 Binding SID END.B6.Encaps nh6 str to lib. It is used to display nh6 when one uses 'show ipv6 route'.
=> lib: add srv6 bsid to seg6local_context2str

doc/user/isisd.rst
Correct a few commands for isis based on code, just complete the missing `[vrf <NAME|all>]`.
=> doc: correct a few commands for isis

doc/user/ospf6d.rst, doc/user/ospf_fundamentals.rst, doc/user/ospfd.rst, lib/libospf.h, ospfd/ospf_flood.c, ospfd/ospf_interface.c, ospfd/ospf_interface.h, ospfd/ospf_ism.c, ospfd/ospf_neighbor.c, ospfd/ospf_nsm.c, ospfd/ospf_packet.c, ospfd/ospf_vty.c, ospfd/ospfd.c, tests/topotests/ospf_p2mp/r1/frr-p2mp-non-broadcast.conf, tests/topotests/ospf_p2mp/r1/frr-p2mp.conf, tests/topotests/ospf_p2mp/r2/frr-p2mp-non-broadcast.conf, tests/topotests/ospf_p2mp/r2/frr-p2mp.conf, tests/topotests/ospf_p2mp/r3/frr-p2mp-non-broadcast.conf, tests/topotests/ospf_p2mp/r3/frr-p2mp.conf, tests/topotests/ospf_p2mp/r4/frr-p2mp-non-broadcast.conf, tests/topotests/ospf_p2mp/r4/frr-p2mp.conf, tests/topotests/ospf_p2mp/test_ospf_p2mp_broadcast.py, tests/topotests/ospf_p2mp/test_ospf_p2mp_non_broadcast.py
This extends non-broadcast support to point-to-multipoint networks. Neighbors will be explicitly configured and polled in lieu of multicast dicovery. Toptotests and documentation updates are included.
The AllOSPFRouters (224.0.0.5) is still joined for non-broadcast networks since it is joined for NBMA networks. It seems this could be removed but it should done be in a separate commit.
=> ospfd: Implement non-broadcast support for point-to-multipoint networks

zebra/zebra_mpls.c, zebra/zebra_mpls.h, zebra/zebra_mpls_vty.c
Add a parameter for `zebra_mpls_fec_for_label()`, as before if it is `NULL`, otherwise exclude what this parameter represents.
Before:
```
anlan(config)# mpls label bind 1.1.1.2/32 88
anlan(config)# mpls label bind 1.1.1.2/32 88
% Label already bound to a FEC
anlan(config)# mpls label bind 1.1.1.3/32 88
% Label already bound to a FEC
```
After:
```
anlan(config)# mpls label bind 1.1.1.2/32 88
anlan(config)# mpls label bind 1.1.1.2/32 88
anlan(config)# mpls label bind 1.1.1.3/32 88
% Label already bound to a FEC
```
The immediate effect is that  `systemctl reload frr` will fail with adding this command line without this commit.
=> zebra: fix wrong check for mpls label

bgpd/bgp_evpn.c, bgpd/bgp_evpn.h, bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_mh.h, bgpd/bgp_route.c, bgpd/bgp_table.h, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, bgpd/bgpd.h
Current changes deals with EVPN routes installation to zebra.
In evpn_route_select_install() we invoke evpn_zebra_install/uninstall which sends zclient_send_message().
This is a continuation of code changes (similar to ccfe452763d16c432fa81fd20e805bec819b345e) but to handle evpn part of the code.
Ticket: #3390099
Related MRs:
Backpressure server code changes: https://github.com/FRRouting/frr/pull/15411 (Merged)
Backpressure Non EVPN client(BGP) code changes : https://github.com/FRRouting/frr/pull/15524 (Merged)
=> bgpd : backpressure - Handle BGP-Zebra(EPVN) Install evt Creation

pimd/pim_iface.c
Add break for loop, `pimreg` interface should be with one master.
=> pimd: Set pimreg interface with one master

tests/topotests/lib/common_config.py, zebra/rtadv.c
1) Ensure that generate_support_bundles doesn't crash the run
2) Cleanup a sendmsg call that sent down uninited data.
=> Zebra rtadv use without init

bgpd/bgp_vty.c
The 'show bgp neighbors' output appends additional lines after GR mode
helpers.
> # show bgp neighbors
> [..]
>     End-of-RIB received: IPv4 VPN
>     Local GR Mode: Helper*
>
>     Remote GR Mode: Helper
>
>     R bit: True
>
Fix this by not appending the extra line feed.
> # show bgp neighbors
> [..]
>     End-of-RIB received: IPv4 VPN
>     Local GR Mode: Helper*
>     Remote GR Mode: Helper
>     R bit: True
Fixes: 0e4e879b4084 ("bgpd: fix silly format string SNAFU")
=> bgpd: fix 'show bgp neighbors' output

pimd/pim_cmd.c
command 'show ip pim mlag summary json' should display 'mlagConnUp', 'mlagPeerConnUp', and 'mlagPeerZebraUp' when the connection is down.
Fix:
Added 'json_object_boolean_false_add()' for these objects.
=> pimd:  pim mlag summary should display the down connection status.

tools/indent.py
Python subprocess communication now operates on bytes, not strings.
=> tools/indent.py: fix encoded byte stream handling

bfdd/bfd.h, bfdd/bfd_packet.c
According to RFC 5880:
Multipoint (M)
This bit is reserved for future point-to-multipoint extensions to BFD. It MUST be zero on both transmit and receipt.
=> bfdd: Add check for flag Multipoint (M)

bgpd/bgp_evpn.c
=> Evpn zebra interactions

bgpd/bgp_attr.h
When receiving a BGP update that includes a colored extended community, the nexthop is tracked in the bgp nexthop tracking context, but the color is never recorded.
Actually, the srte color is set only when the SRTE_COLOR attribute is set, and this is an internal flag that is only set when a local route-map sets the sr-te-color parameter.
Fix this by removing that condition.
Fixes: 442e2edcfaef ("bgpd: add functions related to srte_color management")
=> bgpd: fix register NHT with appropriate colored ext. community

bgpd/bgp_route.c
This is happening when configuring with `--disable-bgp-vnc`:
```
./bgpd/bgp_route.c:3342:23: error: unused variable ‘p’ [-Werror=unused-variable]
3342 |  const struct prefix *p = bgp_dest_get_prefix(dest);
```
=> bgpd: fix compile error

bgpd/bgp_fsm.c, bgpd/bgp_network.c
On non established TCP sessions, the remote/local address/port information is not available.
However, for outgoing TCP connections, this is possible.
Lets do it.
=> BGP TCP non established : get port and ip

bgpd/bgp_zebra.c
Fix dereferencing NULL ptr making coverity happy.
Ticket :#3390099
=> zebra: backpressure - Fix Null ptr access (Coverity Issue)

zebra/zebra_nb_config.c
The encoded DNSSL length is not set so the value is missing from RA packet.
Fixes #15740.
=> zebra: fix encoded DNSSL length

bgpd/bgp_damp.c, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_private.h, bgpd/bgp_label.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_vty.c, bgpd/bgp_zebra.c, bgpd/bgpd.c, bgpd/rfapi/rfapi.c, tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post4.1.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post5.0.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv4-post6.1.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv4.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv6-post4.1.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv6.ref, tests/topotests/all_protocol_startup/r1/show_bgp_ipv6_post6.1.ref, tests/topotests/bgp_evpn_mh/leaf1/evpn.conf, tests/topotests/bgp_evpn_mh/leaf2/evpn.conf, tests/topotests/bgp_evpn_mh/spine1/evpn.conf, tests/topotests/bgp_evpn_mh/spine2/evpn.conf, tests/topotests/bgp_evpn_mh/torm11/evpn.conf, tests/topotests/bgp_evpn_mh/torm12/evpn.conf, tests/topotests/bgp_evpn_mh/torm21/evpn.conf, tests/topotests/bgp_evpn_mh/torm22/evpn.conf, tests/topotests/ospf_basic_functionality/test_ospf_rte_calc.py
See individual commits.  But setup for best path reordering.  Code cleanup etc.
=> bgp_process work

zebra/rt_netlink.c
When configuring a SID list by vtysh, the segment list obtained in iproute2 is the exact opposite:
>
>vtysh:
>ipv6 route 2005::/64 eth0 segments 2001:db8:aaaa::7/2002::2/2003::3/2004::4
>
>root@r1:/# ip -6 route
>2005::/64 nhid 6  encap seg6 mode encap segs 4 [ 2004::4 2003::3 2002::2 2001:db8:aaaa::7 ] dev dummy0 proto 196 metric 20 pref medium
>
Fix this by keeping the same vtysh config and swap the segment's order of the list in the rt_netlink.c
>
>root@r1:/# ip -6 route
>2005::/64 nhid 6  encap seg6 mode encap segs 4 [ 2001:db8:aaaa::7 2002::2 2003::3 2004::4 ] dev dummy0 proto 196 metric 20 pref medium
>
Fixes: f20cf14 ("bgpd,lib,sharpd,zebra: srv6 introduce multiple segs/SIDs in nexthop")
=> zebra: fix static srv6 segment-list sid order

bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_updgrp_adv.c, bgpd/bgp_vpn.c, doc/user/bgp.rst
The usage of the `bgp bestpath med missing-as-worst` command was being accepted and applied during bestpath, but during output of the routes affected by this it would not give any indication that this was happening or what med value was being used.
Fixes: #15718
=> bgpd: Fix display when using `missing-as-worst`

bgpd/bgp_vty.c
Not documented, and it's just an alias.
=> bgpd: Drop `bgp_network_import_check_exact_cmd` command

vtysh/vtysh.c
Closes https://github.com/FRRouting/frr/issues/15754
=> vtysh: Check if bgpd is enabled before installing vtysh commands for RPKI

tools/frr-reload.py
if frr.conf file contains 'interface x vrf <name> config it causes protocol (like ospf) neighbor session flap, as replayed via frr-reload deletes interface base config line ('interface x') from running config and readds with 'interface x vrf <name>' line from frr.conf.
This deletion and re-addition of lines leads to neighborship flaps.
This issue is by product of (PR-10411 | https://github.com/FRRouting/frr/pull/10411) (commit id: 788a036fdb)
where running config for interface config no loger displays associated vrf line.
Testing:
frr.conf:
```
interface swp1.2 vrf vrf1012
ip ospf network point-to-point
```
running-config:
```
interface swp1.2
ip ospf network point-to-point
exit
```
Before fix:
frr-reload logs:
```
2024-04-09 00:28:31,096  INFO: Executed "interface swp1.2  no ip ospf …
```
=> tools: frr-reload strip interface vrf ctx line

isisd/isis_pdu.c
The hold time filled in the hello packets of a P2P link is calculated based on the level 1 configuration, while the hello timer is based on the level 2 configuration. If the hello interval times in level 1 and level 2 configurations are inconsistent, it may lead to neighbor establishment failure.
=> isisd: The hold time of hello packets on a P2P link does not match the sending interval.

bgpd/bgp_debug.c, bgpd/bgp_debug.h
The debug command was removed in 17e9298e47 ("bgpd: Remove 'debug bgp allow-martian'")
Cleanup all references to the debug command.
=> bgpd: cleanup references to debug bgp allow-martians

lib/keychain_nb.c
Operational data should not be used on validation stage. Move the usage to apply stage only.
Fixes #15707.
=> lib: fix keychain NB crash

ospfd/ospf_vty.c
1. Fixed the syntax of the 'no maximum-paths' command to allow the parameter (1-64) to be present. Since the corresponding 'set' command is 'maximum-paths (1-64)', its 'unset' command should also allow the parameter (1-64) to be either present or absent, aligning it with the same command in `bgp_vty.c` and `ospf6_top.c`.
2. Fixed the syntax of the 'no write-multiplier' command for the same reasons as above.
=> ospfd: fix 'no maximum-paths' 'no write-multiplier'  commands

bgpd/bgp_rpki.c, doc/user/rpki.rst
RFC-7607 specifically calls out the allowed usage
of AS 0 to signal that the a particular address is not in use and should be guarded against.  Add
the ability to specify this special AS in the rpki commands.
eva# show rpki  as-number 0
RPKI/RTR prefix table
Prefix                                   Prefix Length  Origin-AS
2.57.180.0                                  22 -  24   0
2.58.144.0                                  22 -  22   0
2.59.116.0                                  24 -  24   0
4.42.228.0                                  22 -  22   0
5.57.80.0                                   22 -  22   0
<snip>
2a13:df87:b400::                            38 -  38   0
2a13:df84::                                 32 -  32   0
2630::                                      16 -  16   0
Number of …
=> bgpd: Allow specification of AS 0 for rpki commands

lib/command.c, lib/vrf.c, zebra/zebra_cli.c
If a command is not marked as `YANG`-converted, the current command batching buffer is flushed before executing the command. We shouldn't flush the buffer when executing an `exit` command. It should only be flushed if the next command is not `YANG`-converted, which is checked by the command itself, not the previous `exit`.
Fixes #15706.
=> lib, zebra: fix exit commands

vtysh/vtysh.c
Fixes https://github.com/FRRouting/frr/issues/15795
=> vtysh: Fix `show route-map` command when calling via `do`

yang/frr-zebra.yang, zebra/zebra_nb_state.c
This was caught by the grpc_basic test which was receiving an invalid error result, which was returned b/c inside zebra the libyang code was flagging the value as invalid for a derived zebra interface type.
=> yang: add missing `zif-gre` zebra interface type

bfdd/bfd.h, tests/topotests/bfd_bgp_cbit_topo3/r1/bgp_ipv6_routes_down.json, tests/topotests/bfd_bgp_cbit_topo3/r1/ipv6_routes.json, tests/topotests/bfd_bgp_cbit_topo3/test_bfd_bgp_cbit_topo3.py
The macro should check C bit, not F bit.
=> bfdd: fix BFD_GETCBIT

lib/mgmt_fe_client.c, lib/mgmt_fe_client.h, lib/mgmt_msg_native.c, lib/mgmt_msg_native.h, lib/northbound.c, lib/northbound.h, lib/northbound_oper.c, lib/vty.c, lib/vty.h, lib/yang.c, lib/yang.h, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_fe_adapter.h, mgmtd/mgmt_txn.c, mgmtd/mgmt_txn.h, mgmtd/mgmt_vty.c, tests/topotests/mgmt_tests/test_yang_mgmt.py
This operation basically implements support for RESTCONF operations. It receives an xpath and a data tree in JSON/XML format, instead of a list of (xpath, value) tuples as required by the current protobuf interface.
=> mgmtd: add support for native 'edit' operation

lib/plist.c, vtysh/vtysh.c, vtysh/vtysh.h
Json output is not valid for 'show ip prefix-list ... json' commands, because it goes through each running daemon and for each one it calls 'vty_show_prefix_list' creating a new json object. To aggreagate the output and create a valid json that can be parsed, the commands were moved to vtysh, similarly to this PR: https://github.com/FRRouting/frr/pull/14856
This solves: https://github.com/FRRouting/frr/issues/15277
Before:
```
{
"ZEBRA":{
"DEFAULT":{
"addressFamily":"IPv4",
"entries":[
{
"sequenceNumber":10,
"type":"permit",
"prefix":"0.0.0.0/0"
}
]
}
}
}
{
"OSPF":{
"DEFAULT":{
"addressFamily":"IPv4",
"entries":[
{
"sequenceNumber":10,
"type":"permit",
"prefix":"0.0.0.0/0"
}
]
}
}
}
{
"BGP":{
"DEFAULT":{
"addressFamily":"IPv4",
"entries":[
{
"sequenceNumber":10,
"type":"permit", …
```
=> vtysh, lib: fix 'show ip[v6] prefix-list ... json' JSON display by moving it to vtysh to fix formatting issue

bgpd/bgp_mplsvpn.c, bgpd/bgp_mplsvpn.h, bgpd/bgp_vty.c
Today, with the following bgp instance configured, the local VRF label is allocated even if it is not used.
> router bgp 65500 vrf vrf1
>  address-family ipv4 unicast
>   label vpn export allocation-mode per-nexthop
>   label vpn export auto
>   rd vpn export 444:1
>   rt vpn both 52:100
>   export vpn
>   import vpn
The 'show mpls table' indicates that the 16 label value is allocated, but never used in the exported prefixes.
> r1# show mpls table
>  Inbound Label  Type  Nexthop         Outbound Label
>  -----------------------------------------------------
>  16             BGP   vrf1            -
>  17             BGP   192.168.255.13  -
>  18             BGP   192.0.2.12      -
>  19             BGP   192.0.2.11      -
Fix this by only allocating new label values when really used. …
=> bgpd: do allocate vrf label only when necessary

bgpd/bgp_bfd.c
Before this patch after command
`no neighbor <A.B.C.D|X:X::X:X|WORD> bfd profile [BFDPROF]`
has always been created bfd-config for neighbor.
=> bgpd: fix disable bfd profile for neighbors.

isisd/isis_srv6.c, isisd/isis_srv6.h
The define has inheritated from a wrong naming in sr-mpls. Fix this by renaming ISIS_SRV6_LAN_BACKUP to ISIS_SRV6_ADJ_BACKUP.
Fixes: 2566656a6f50 ("isisd: Add data structure for SRv6 Adjacency SIDs")
=> isisd: fix renaming backup define for ENDX SID

lib/nexthop.c, lib/nexthop.h, zebra/zebra_nhg.c
In zebra_interface_nhg_reinstall zebra is checking that the nhg is a singleton and not a blackhole nhg.  This was originally done with checking that the nexthop is a NEXTHOP_TYPE_IFINDEX, NEXTHOP_TYPE_IPV4_IFINDEX and NEXTHOP_TYPE_IPV6_IFINDEX.  This was excluding NEXTHOP_TYPE_IPV4 and NEXTHOP_TYPE_IPV6.  These were both possible to be received and maintained from the upper level protocol for when a route is being recursively resolved. If we have gotten to this point in zebra_interface_nhg_reinstall the nexthop group has already been installed at least once and we *know* that it is actually a valid nexthop.  What the test is really trying to do is ensure that we are not reinstalling a blackhole nexthop group( Which is not possible to even be here by the way, but safety first! ).  So let's …
=> lib, zebra: Check for not being a blackhole route

lib/frr_pthread.c, lib/frr_pthread.h
Add a new condition var and mutex to serialize pthread startup. The order in which the parent and a new child run is not deterministic. With this change, when a new pthread is started it will wait very early on for the parent pthread to permit it to run. This ensures that that the ordering between parent and child is predictable.
Fixes: #15699
=> lib: serialize pthread startup

tests/topotests/conftest.py, tests/topotests/munet/__main__.py, tests/topotests/munet/args.py, tests/topotests/munet/base.py, tests/topotests/munet/mucmd.py, tests/topotests/munet/munet-schema.json, tests/topotests/munet/mutest/__main__.py, tests/topotests/munet/mutest/userapi.py, tests/topotests/munet/native.py, tests/topotests/munet/parser.py, tests/topotests/munet/testing/fixtures.py, tests/topotests/munet/testing/hooks.py
- improve coverage functionality
- update munet to latest release (0.14.0), brings in a a bugfix for running on older kernels with missing functionality (pidfd_open), as well as new generic gcov coverage support that we would like to leverage. remaining changes are in areas not currently utilized by topotest (e.g., mutest, and qemu/vm).
=> Improve coverage functionality

lib/stream.c
An extension of commit-8d8f12ba8e5cd11c189b8475b05539fa8415ccb9
Removing ifdef DEV_BUILD in stream_fifo_push as well to make the 'sh zebra client' display the current I/O fifo along with max fifo items.
TICKET :#3390099
=> zebra: Actually display I/O buffer sizes (part-2)

bgpd/bgp_route.c
Route-distinguisher is not printed properly in show run:
>  address-family ipv6 vpn
>   network ff01::/64 rd (null) label 7
>   network ff01::/64 rd (null) label 8
https://github.com/FRRouting/frr/commit/ad151f66aabaf29a16254eee3eea36a4d4ff674f ("bgpd: Refactor bgp_static_set/bgp_static_set_safi") merged
bgp_static_set_safi into bgp_static_set but inadvertently omitted the
handling of prd_pretty.
Copy the pretty RD string if available.
> address-family ipv6 vpn
>  network ff01::/64 rd 75:5 label 7
>  network ff01::/64 rd 85:5 label 8
=> bgpd: fix show run of network route-distinguisher

doc/user/ospfd.rst, ospfd/ospf_interface.c, ospfd/ospf_interface.h, ospfd/ospf_packet.c, ospfd/ospf_vty.c, ospfd/ospf_zebra.c, tests/topotests/ospf_p2mp/test_ospf_p2mp_broadcast.py
This commit adds the capabiity to filter OSPF neighbors using a prefix-list with rules matching the neighbor's IP source address. Configuration, filtering, immediate neighbor pruning, topo-tests, and documentation are included. The command is:
ip ospf neighbor-filter <prefix-list> [A.B.C.D]
=> ospfd: Add prefix-list filtering of OSPF neighbors on OSPF interface

bgpd/bgp_vty.h, lib/command.h, vtysh/vtysh.c
Stop including a bgp header file from vtysh (ouch); move a couple of cli string defines to a library header.
=> lib,bgpd,vtysh: move bgp vty defines to lib

lib/subdir.am, mgmtd/subdir.am
ietf-key-chain depends on ietf-netconf-acm, and lib/ code sets up the former, so ietf-netconf-acm needs to be embedded in the libfrr too.
=> yang: ietf-netconf-acm needs to be in libfrr

lib/libfrr.c
I can't see them but apparently this causes compiler warnings.
---
```
lib/libfrr.c:734:66: error: ‘%s’ directive output may be truncated writing up to 15 bytes into a region of size between 1 and 511
```
Double checked that SQLite3 is enabled (it is) and running quite recent GCC (13.2.0) but still not seeing this. Might be something they changed on the GCC side and it only shows on GCC 11 or 12? Either way just make the string larger.
Since I can't see it — @donaldsharp can you confirm this fixes it?
=> lib: fix SQLite dbfile path length

bgpd/bgp_advertise.c, bgpd/bgp_bmp.c, bgpd/bgp_bmp.h, bgpd/bgp_route.c, bgpd/bgpd.h, doc/user/bmp.rst
Add support for BMP stats option 7 and 8.
Add vty command to disable sending experimental stats numbers.
=> Bmp improvements about statistics

sharpd/sharp_vty.c, zebra/rt_netlink.c
Add the support for adding DX6 behavior into netlink layer of zebra. Add the necessary test in sharpd.
> ubuntu2204# sharp install seg6local-routes 1:1::1:2 nexthop-seg6local loop1 End_DX6 4:4::4:6 1
> ubuntu2204# do show ipv6 route
> [..]
> D>* 1:1::1:2/128 [150/0] is directly connected, loop1, seg6local End.DX6 nh6 4:4::4:6, weight 1, 00:00:03
=> zebra, sharpd: add srv6 End.DX6 support

doc/developer/building-libyang.rst, doc/developer/cross-compiling.rst, doc/developer/northbound/plugins-sysrepo.rst, doc/developer/static-linking.rst
Since cmake 3.21, we should use `--install-prefix`
see https://cmake.org/cmake/help/latest/manual/cmake.1.html
=> cmake install prefix

doc/user/ospfd.rst, ospfd/ospf_apiserver.c, ospfd/ospf_apiserver.h, ospfd/ospf_main.c
This commit include OSPFAPI Server options to:
1. Limit the OSPFAPI server connections to local (i.e., loopback) connections.
2. Allow different OSPFAPI server TCP ports to be specified for different OSPF instances in /etc/services.
=> ospfd: OSPFAPI Server options to limit to local connections and per-instance TCP

pimd/pim_cmd_common.c
pimd crashs while unconfigure of rp ka timer as we are trying to access a yand dnode(suppress timer) which does not exist at the moment.
User just configured rp keepalive timer and not suppress timer, the yang dnode would not be present. Instead of directly accessing yang_dnode_get_unit16, first check the yang node exist using the xpath.
Ticket: #3874971
Testing:
Before:
------
tor-11(config)# no ip pim rp keep-alive-timer 3000 vtysh: error reading from pimd: Success (0)Warning: closing connection to pimd because of an I/O error!
Broadcast message from root@tor-11 (somewhere) (Mon Apr 22 17:29:12 2024):
cumulus-core: Running cl-support for core files "pimd.25467.1713806952.core"
After:
-----
tor-11(config)# no ip pim rp keep-alive-timer 3000 tor-11(config)#
=> pimd: fix crash unconfiguring rp keepalive timer

lib/zclient.c
Right where the zapi route flags are defined, there's a comment asking that the flag-dumper-function also be updated... and yet...
Also apply clang-format's preferences, so next person won't have to.
=> lib: add ZEBRA_FLAG_OUTOFSYNC to dump_flags function

bgpd/bgp_ecommunity.c
Fixed the Coverity scanner issue 1586018:
** CID 1586018: Control flow issues (DEADCODE) /bgpd/bgp_ecommunity.c: 1402 in ecommunity_ecom2str()
=> bgpd: fix the dead code

tools/frr-reload.py
If frr.conf has bgp as-path access-list clause without sequence number then upon performing frr-rleoad, the running config clause with sequence number will always be deleted and the new ones without sequence will be re-added.
This could lead to blackhole until the config gets reapplied.
Testing:
```
frr.conf:
bgp as-path access-list important_internet_bgp_as_numbers permit _16509_
Running config:
bgp as-path access-list important_internet_bgp_as_numbers seq 5 permit _16509_
!
Before fix
Upon frr-reload it deletes and readd line as without seq
2024-04-26 03:16:45,772  INFO: Executed "no bgp as-path access-list important_internet_bgp_as_numbers seq 5 permit _16509_"
'bgp as-path access-list important_internet_bgp_as_numbers permit _16509_\n'
After fix:
no form is not executed and no delta …
```
=> tools: Handle seq num for BGP as-path in frr-reload.py

bgpd/bgp_vty.c
Description:
-----
Deleting a peer group also deletes its associated BGP listen range. This behaviour is undesired as it could cause unintended configuration changes.
Fix :
-----
-Do not allow peer group deletion until they are no longer associated with any listen range. 
-Check the count of listen ranges attached to the group. If any listen ranges are found, returns a configuration warning, preventing the deletion.
=> bgpd : Prevent deletion of BGP peer groups associated to listen range

ospf6d/ospf6_interface.c, ospf6d/ospf6_neighbor.c
clang-format doesn't understand `DEFUN` and formats it rather ugly. Standard approach was to skip these in clang-format, which hasn't happened here sadly.
=> ospf6d: fix DEFUN formatting wrecked by clang

tools/etc/iproute2/rt_protos.d/frr.conf
With SRv6 traffic engineering, some ipv6 routes will be installed by the Pathd daemon.
Populate the iproute2 aliasing table with pathd.
=> tools: add iproute2 alias for pathd daemon

bgpd/bgpd.c
Description :
------
Dynamic neighbors exceeding the listen limit were rejected without appropriate logging. Previously, only rejection logs were generated, leaving users unaware of when the limit being reached.
Fix :
------
Adding a log message for when the listen limit is reached.
Signed-off-by: Pooja Rathore <rathorepo@vmware.com>
=> bgpd : Ensure logging for dynamic neighbor listen limit reached

isisd/isis_te.c, isisd/isis_te.h, lib/link_state.c, lib/link_state.h
Add SRv6  information to link state database.
This information is now reachable from each side (IS-IS, or Pathd).
=> Link state srv6 capas

yang/frr-isisd.yang
When the ISIS instance does not exist, this check causes the default value of the ISIS instance's metric to become narrow. 
The following two scenarios present issues: 
1) When the ISIS metric configuration under the interface exceeds 63, we are unable to delete the ISIS instance.
2) When the ISIS instance is not created, we are unable to modify an ISIS metric that exceeds 63.
=> isisd: When the ISIS instance does not exist, the default metric will not be wide.

bgpd/bgp_fsm.c
The return value of bgp_getsockname() should always be checked.
=> bgpd: fix covery ID 1585206

zebra/fpm_listener.c, zebra/kernel_netlink.c
As part of the kernel netlink functionality, it is possible that a bit of nested attributes can be
passed up.  This attribute has a type value which
is stored in the lower 8 bits and in the upper 8
bits are a couple control flags that can be used.
FRR can parse this data and then just throw away
the value unless we mask off the upper 8 bits.
Let's ensure that it can be properly parsed.
=> zebra: Ensure proper decoding of netlink message

lib/compiler.h, lib/memory.h
Sections use a different syntax for Mach-O executables.
The `frr` package has a host build step in OpenWRT, which can be cross-compiled on macOS. This commit fixes errors while building OpenWRT on macOS host.
Fixes:
``` bash
make package/feeds/packages/frr/host/{clean,compile} -j 1 V=s
…
lib/command_graph.c:16:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma DEFINE_MTYPE_STATIC(LIB, CMD_TOKENS, "Command Tokens"); ^
./lib/memory.h:139:2: note: expanded from macro 'DEFINE_MTYPE_STATIC'
DEFINE_MTYPE_ATTR(group, name, static, desc)                           \
^
./lib/memory.h:109:26: note: expanded from macro 'DEFINE_MTYPE_ATTR'
__attribute__((section(".data.mtypes"))) = { {                 \ …
```
=> lib: fix build error on MacOS

pathd/path_main.c, pathd/path_zebra.c
Remove blocking "sleep" calls from the pathd code that initializes and connects the synchronous zapi session used for, sigh, label-manager. Be prepared to retry on a timer.
Also clean up a typo in a log message.
Fixes: #15847
=> pathd: retry label-manager connection asynchronously

ospf6d/ospf6_interface.c, ospf6d/ospf6_neighbor.c
changes to the interface type weren't correctly handled in updating the connected routes
- changing the interface type wasn't reoriginating connected routes to begin with, meaning stale routes could be left over
- the type check was looking at state rather than iftype, but state can be "down"
also a `no` form was missing for the interface type CLI command
This may or may not fix CI ospf6 ptmp test issues, either way it's fixing a bunch of issues.
=> ospf6d: fix interface type vs. connected routes updates

lib/resolver.c
The c-ares api has deprecated ares_process() and ares_gethostbyname() and it causes a build failure on Fedora 40.
This PR replaces the deprecated functions with their replacements.
=> fix use of deprecated c-ares api

zebra/if_netlink.c
With the commit `605df8d4`, all real things are moved into dplane. So the operations mentioned in this comment have nothing to do with this function `netlink_link_change()`.
Just remove that confusing and useless comment.
=> zebra: clean up one comment

tests/topotests/mgmt_oper/oper.py, tests/topotests/mgmt_oper/test_oper.py, tests/topotests/mgmt_oper/test_scale.py
Use proper retry loop to wait for state to converge, not some arbitrary delay.
fixes #15878
=> tests: remove reliance on time.sleep

configure.ac
Other parts of the system can change (e.g. libc-ares), making things deprecated, and then our build fails for no reason inside FRR.  This shouldn't be an error.
---
I'm gonna say this is the correct thing to do even after the libc-ares fix (#15837)for the deprecated bits is merged.
=> build: exclude deprecated decls from -Werror

zebra/zebra_evpn_mh.c, zebra/zebra_evpn_mh.h, zebra/zebra_l2.c, zebra/zebra_vxlan_if.c
Upon bridge flap, the associated SVD case, VLAN membership is not updated correctly.
When SVI comes up, the VNI could not associate with it as bridge VLAN membership was not updated.
Testing:
Before fix:
-----------
```
tor-1:#ifdown br_l3vni ; sleep 1 ; ifup br_l3vni
tor-1:# vtysh -c 'show evpn vni 8888'
VNI: 8888
Type: L3
Tenant VRF: sym_1
Vlan: 490
Bridge: br_l3vni
Local Vtep Ip: 27.0.0.9
Vxlan-Intf: vxlan99
SVI-If: None    <<<<<< SVI not found
State: Down     <<<<<< status remained in down BGP is not informed
VNI Filter: none
System MAC: None
Router MAC: None
L2 VNIs: 1800 1801 1900 1901
```
After fix:
----------
```
tor-1:# ifdown br_l3vni; sleep 1; ifup br_l3vni
tor-1:# vtysh
Hello, this is FRRouting (version 8.4.3).
tor-1# show evpn vni …
```
=> zebra: bridge flap handle vlan membership update

isisd/isis_adjacency.c, isisd/isisd.c
Before:
```
anlan# show isis neighbor
Area xx:
System Id           Interface   L  State        Holdtime SNPA
0023.0000.0000      enp1s0      2  Down          Expiring2c53.4a30.0820
```
After:
```
anlan# show isis neighbor
Area xx:
System Id           Interface   L  State         Holdtime SNPA
0023.0000.0000      enp1s0      2  Down          Expiring 2c53.4a30.0820
```
The `-` display format caused by no hello packet in `isis_adj_print_vty()` is same as that of above "Expiring".
=> isisd: adjust the format of display command

bgpd/bgp_zebra.c
When BGP receives a `SRV6_LOCATOR_DEL` from zebra, it invokes `bgp_zebra_process_srv6_locator_delete` to process the message.
`bgp_zebra_process_srv6_locator_delete` obtains a pointer to the default BGP instance and then dereferences this pointer.
If the default BGP instance is not ready / not configured yet, this pointer this pointer is `NULL` and dereferencing it causes BGP to crash.
This commit fix the issue by adding a a check to verify if the pointer is `NULL` and returning early if it is.
=> bgpd: Fix crash when deleting the SRv6 locator

bgpd/bgp_vty.c
When a bgp neighbor graceful-restart config mode change is applied, after accepting the config if it does not take effect instead of throwing vtysh error code,
return the success to vtysh and warn the user.
The debug log is already present at critical code point where GR failure is seen during config apply.
Testing Done:
```
root@tor-1:# vtysh -c 'config t' -c 'router bgp 65564 vrf VRF2' -c 'neighbor 20.1.1.1 graceful-restart'
As part of configuring graceful-restart, capability send to zebra failed root@tor-1:# echo $?
0
```
=> bgpd: [GR] fix mode change vtysh return code

lib/northbound_oper.c, tools/gcc-plugins/frr-format.c
The gcc plugin was already warning about printfrr'ing `time_t`, but `struct timeval` uses `suseconds_t`.
- fix the one place where this matters in lib/NB code
- add `__suseconds_t`/`__suseconds64_t` to things that the GCC plugin will warn about
(The GCC plugin is executed on one of the Debian 12 build VMs in CI, i.e. this will cause CI failures there in the future. [In addition to 32bit builds where it fails if the OS has moved to 64-bit time_t, which is Ubuntu 24.04+ / Debian 13+.])
+ Just noticed that the print in the NB code is also misleading - it prints microseconds but the format was %lus, i.e. it prints "99999s", u being the printf specifier of course. I think someone got confused there.
---
part of fixing #15881
=> lib, gcc-plugin: fix 64-bit time_t prints

configure.ac
It'll generally exist but be empty on systems that don't need it. (Some 32bit platforms now need it due to 64bit time_t, and the platform may not have 64bit atomic ops.)
---
part of fixing #15881
=> build: link libatomic if available

ospfd/ospf_vty.c
Fix the bug where ip_ospf_dead-interval_minimal_hello-multiplier did not reset hello timer.
The command ip_ospf_dead-interval_minimal_hello-multiplier sets the OSPF dead interval to 1 second and the hello interval to 1/arg seconds to accelerate OSPF convergence. Once this command is set, the hello timer should immediately reset and send a new hello packet to inform its neighbors, similar to what the ip ospf hello-interval command does.
=> ospfd: fix the bug where ip_ospf_dead-interval_minimal_hello-multiplier did not reset hello timer

bgpd/bgp_attr.c, tests/topotests/bgp_path_attribute_discard/peer1/exabgp.cfg, tests/topotests/bgp_path_attribute_discard/r1/bgpd.conf, tests/topotests/bgp_path_attribute_discard/r1/frr.conf, tests/topotests/bgp_path_attribute_discard/r1/zebra.conf, tests/topotests/bgp_path_attribute_discard/r2/frr.conf, tests/topotests/bgp_path_attribute_discard/test_bgp_path_attribute_discard.py
Closes https://github.com/FRRouting/frr/discussions/15884
=> bgpd: Ignore validating the attribute flags if path-attribute is configured

bgpd/bgp_routemap.c
If entering `no set as-path prepend 1 2 3`, it's warned as unknown command.
Now fixed, and the following combinations work fine:
```
no set as-path prepend
no set as-path prepend last-as
no set as-path prepend last-as 1
no set as-path prepend 1
no set as-path prepend 1 2
```
Fixes: https://github.com/FRRouting/frr/issues/15912
=> bgpd: Fix `no set as-path prepend ASNUM...`

isisd/isis_spf.c
The unconfigured flexible algorithm should not be displayed.
Before: (Here only 128 is configured)
```
anlan# show isis topology algorithm
Area A: Algorithm 128
Area A:Area A:Area A:Area A:Area A:Area A:Area A:Area A:Area A:Area ...
......
anlan#
```
After:
```
anlan# show isis topology algorithm
Area A: Algorithm 128
anlan#
```
=> isisd: fix the display topology command

lib/if.c
Using the same address with a different prefix length is not supported. If we configure two identical addresses with different netmasks 192.168.1.1/30 and then 192.168.1.1/29. Zebra sends '192.168.1.1' with a prefix length of 29. However, the function 'zebra_interface_address_read()' reads '192.168.1.1/30' because the prefix length is not checked.
Using 'same_prefix()' is more convenient.
=> if: fix same connected address

isisd/isis_spf.c, isisd/isis_te.c, isisd/isisd.c
The `vrf_name` is always non-NULL in `isisd` code, so remove the unnecesary check to make it clear.
=> isisd: remove unnecessary checkings for vrf  

ospf6d/ospf6_abr.h, ospf6d/ospf6_asbr.c, ospf6d/ospf6_asbr.h, ospf6d/ospf6_route.h, ospf6d/ospf6_zebra.c
When ospf6d originates an AS-external route that has been read from a kernel routing table, then the metric of that route was ignored until now. In my case all of these routes were announced with metric 1 in LS-updates.
Now the metric of the kernel route is added to whatever metric ospf6d already computed originally.
=> ospf6d: Fix metric when sending AS-external LSAs

isisd/isis_lsp.c, isisd/isisd.c
The current json display lost a lot of LSPs, added them.
Fixed the json format for two commands:
"show isis database detail json"
"show isis database json"
Before: ( There should be 3 LSPs )
```
anlan# show isis database json
{
"areas":[
{
"area":{
"name":"A"
},
"levels":[
{
},
{
"id":2,
"lsp":{
"id":"0023.0000.0001.00-00",
"own":"*"
},
"pdu-len":86,
"seq-number":"0x000001ab",
"chksum":"0x3fdc",
"holdtime":1177,
"att-p-ol":"0/0/0",
"count":3
}
]
}
]
}
anlan# show isis database detail json
{
"areas":[
{
"area":{
"name":"A"
},
"levels":[
{
},
{
"id":2,
"lsp":{
"id":"0023.0000.0001.00-00",
"own":"*"
},
"pdu-len":54,
"seq-number":"0x000001aa",
"chksum":"0xc3d8",
"holdtime":1135,
"att-p-ol":"0/0/0",
"protocols-supported":{
"0":"IPv4"
},
"area-addr":"47",
"te-router-id":"73.73.73.73", …
```
=> isisd: fix json display for database command

configure.ac
GCC only errors out on unrecognized _positive_ `-Wsomething` flags, negative ones it ignores... but then prints a "note" about whenever an unrelated(!) warning/error occurs.  This is both annoying and confusing, since we now get a lot of:
```
cc1: note: unrecognized command-line option ‘-Wno-microsoft-anon-tag’ may have been intended to silence earlier diagnostics
```
Fix by checking for the positive flag in `AC_C_FLAG` instead, which will error out, and therefore `-Wno-microsoft-anon-tag` won't be added for GCC.  (It only exists on clang.)
=> build: get rid of "unrecognized … anon-tag"

bgpd/bgp_bmp.c
this PR renames bmp tlv types to include the name of the message they are used in for better clarity
this is also related to [draft bmp peer up](https://datatracker.ietf.org/doc/draft-ietf-grow-bmp-peer-up/) which splits the [BMP Initiation and Peer Up Information TLVs](https://www.iana.org/assignments/bmp-parameters/bmp-parameters.xhtml#initiation-peer-up-tlvs) IANA registry in two: peer up/down TLVs and initiation TLVs.
they need a router implementation to get the draft to become rfc, maybe FRR can be it?
=> bgpd: bmp rename tlv types

lib/frr_zmq.c
Didn't catch this one when adding the warning/error (with -Werror) for missing this.  Neither the CI nor I build with ZeroMQ enabled :(.
---
fixes:
```
lib/libfrrzmq.la: warning: binary has no FRRouting.XREF note
lib/libfrrzmq.la-   one of FRR_MODULE_SETUP, FRR_DAEMON_INFO or XREF_SETUP must be used
```
=> lib: stick `XREF_SETUP` into libfrrzmq

zebra/zebra_vxlan.c
In the context of SVD (Single VxLAN Device) for L3VNI, the remote VTEP's nexthop is programmed neighbor entry against SVD along with neighbor entry against SVI.
However, when L3VNI is removed or the VRF is disabled, all SVI based remote nexthop neighbors are uninstalled and deleted. The SVD based neigh entries remains in Zebra and the Kernel. Subsequently, when reconfiguring L3VNI and relearning the same nexthop, the neighbor entry is not programmed is because it is not removed from Zebra SVD neighbor hash table, leading to the failure to reprogram the entry.
With this fix, the SVD nexthop neigh entry is uninstalled and deleted from Zebra and Kernel.
Testing:
```
borderleaf:# ip neigh show 2.2.2.2
2.2.2.2 dev vlan2560_l3 lladdr 00:01:00:00:1d:09 extern_learn NOARP proto zebra 
2.2.2.2 dev …
```
=> zebra: fix EVPN svd based remote nh neigh del

.clang-format
This makes clang-format not wreck all our hand-formatted DEFUN/DEFPY statements.  We apparently missed this option when we originally looked at setting up the .clang-format control file...
---
_how did we not see this option earlier, this is such a continuous (even if small) nuisance_
=> build: make clang-format ignore DEFUN/DEFPY

bgpd/bgpd.c
Fix a couple of memory leaks spotted by Address Sanitizer:
```
==970960==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 592 byte(s) in 2 object(s) allocated from:
#0 0xfeb98b28a4b4 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
https://github.com/FRRouting/frr/pull/1 0xfeb98ae572f8 in qcalloc lib/memory.c:105
https://github.com/FRRouting/frr/issues/2 0xfeb98ae76138 in srv6_locator_chunk_alloc lib/srv6.c:138
https://github.com/FRRouting/frr/issues/3 0xb7f3c8508fa0 in ensure_vrf_tovpn_sid_per_vrf bgpd/bgp_mplsvpn.c:831
https://github.com/FRRouting/frr/issues/4 0xb7f3c8509494 in ensure_vrf_tovpn_sid bgpd/bgp_mplsvpn.c:866
https://github.com/FRRouting/frr/pull/5 0xb7f3c85028a8 in …
```
=> bgpd: Fix SRv6 memory leaks spotted by Address Sanitizer

tests/topotests/key_sendaccept/test_keychain.py
Also update to use a newer hashing function while we are here.
fixes #15923
=> tests: fix mis-spelled `cryptographic-algorithm` keyword in test

zebra/debug_nl.c
Add a few more RTA_ attribute names to the netlink debug output (the output from zebra's "debug zebra kernel msgdump xxx")
=> zebra: add some more netlink RTA_ strings

grpc/frrgrpc_pb.c, grpc/subdir.am, mlag/mlag_pb.c, mlag/subdir.am
This really should be all of them.
---
The two pceplib ones won't in fact trigger the warning because they're `noinst_LTLIBRARIES`, and those are not scanned for xrefs. `mlag_pb` and `frrgrpc_pb` do trigger the warning.
=> build: throw in a few more `XREF_SETUP`

zebra/fpm_listener.c, zebra/rt_netlink.c
a) Modify fpm_listener to understand vxlan vni's and the encoding associated with that
b) Modify fpm_listener to allow a `-v` option that dumps the netlink message received
c) Cleanup code a bit in rt_netlink.c to allow for a bit smoother sailing
d) In the ecmp case where evpn vxlan vni's are available, ensure that the netlink encoding
is correct and matches the `-M fpm` output when using `-M dplane_fpm_nl`
=> Parse attr problems

isisd/isis_tlvs.c
Don't allocate subtlvs container if there's nothing to add to it. If the container is allocated, the "sub-TLVs presence" bit is set in the TLVs even if there's no actual sub-TLVs, what violates the RFC.
Fixes #14514.
=> isisd: fix ip/ipv6 reachability tlvs

bgpd/bgp_nht.c
When the SR-TE service is off, colored BGP routes are not selected if it is recursively resolved over routes that are colored only.
Actually, a BGP nexthop context includes the color attribute; when an update from ZEBRA is received, there is no color, and the colored BGP nexthop contexts are parsed, only if there is a non colored BGP nexthop context. The actual setup shows this may not be the case every time.
Fix this by parsing all the colored BGP nexthop contexts.
Fixes: b8210849b8ac ("bgpd: Make bgp ready to remove distinction between 2 nh tracking types")
=> bgpd: fix colored nexthops resolution

bgpd/bgp_bmp.c
Unconfiguring the send-experimental stats in BMP has no effect on the current behavior.
Fixes this by swapping the configuration boolean.
Fixes: 7ba991cf963f ("bgpd: add 'bmp stat send-experimental' command")
=> bgpd: fixes bmp stats send-experimental configuration

lib/filter.c, tests/topotests/nb_config/test_nb_config.py, vtysh/vtysh.c, vtysh/vtysh.h
Similarly to recently fixed 'show ip[v6] prefix-list ...' - PR#15750, json output is not valid for 'show ip[v6] access-list ... json' commands, as it goes through all the running daemons and for each one it calls 'filter_show' creating a new json object. To aggreagate the output and create a valid json that can later be parsed, the commands were moved to vtysh and formatted accordingly
Before and after for json objects the same as here: [PR#15750](https://github.com/FRRouting/frr/pull/15750)
=> lib, vtysh: fix 'show ip[v6] access-list ... json' formatting

.gitignore, lib/atomlist.h, lib/typerb.h, lib/typesafe.h, python/tsexpand.py
This can be used to get less cryptic error/warnings from GCC when dealing with something typesafe container related.
---
as requested by @mjstapp :wink:
=> python: add tool to expand typesafe definitions

bgpd/bgp_nht.c
On a multihomed setup with colored bgp updates, when the primary PE goes offline, only a small subset of colored bgp routes are not switching to the secondary pe.
When a switchover happens, due to a remote IP becoming unreachable, some nexthop tracking down notifications are sent, but those messages are completely ignored for colored bgp updates.
The original code has been thought for enabling the SR-TE service, when IP reachability is ok, but not when services goes offline.
Fix this by extending the down notification mechanism for colored routes too.
Fixes: 545aeef1d13e ("bgpd: extend the NHT code to understand SR-TE colors")
=> bgpd: fix colored routes not installed after a switchover

zebra/rt_netlink.c, zebra/zebra_rnh.c, zebra/zebra_rnh.h, zebra/zebra_vty.c
Include the prefix source address when set by a route-map in show output for routes, in various formats.
Add some debugs when encoding netlink route messages with a source address.
=> zebra: include route source set by route-map in show output

lib/nexthop.c, lib/nexthop.h, zebra/zebra_rnh.c
The nexthop display functions should be moved in a common place, ready to be available for whatever daemon wants to use it.
Adding to this, display SR-TE color in all cases.
=> Nexthop display rework

bgpd/bgp_fsm.c
bgp_llgr topotest sometimes fails at step 8:
> topo: STEP 8: 'Check if we can see 172.16.1.2/32 after R4 (dynamic peer) was killed'
R4 neighbor is deleted on R2 because it fails to re-connect:
> 14:33:40.128048 BGP: [HKWM3-ZC5QP] 192.168.3.1 fd -1 went from Established to Clearing
> 14:33:40.128154 BGP: [MJ1TJ-HEE3V] 192.168.3.1(r4) graceful restart timer expired
> 14:33:40.128158 BGP: [ZTA2J-YRKGY] 192.168.3.1(r4) graceful restart stalepath timer stopped
> 14:33:40.128162 BGP: [H917J-25EWN] 192.168.3.1(r4) Long-lived stale timer (IPv4 Unicast) started for 20 sec
> 14:33:40.128168 BGP: [H5X66-NXP9S] 192.168.3.1(r4) Long-lived set stale community (LLGR_STALE) for: 172.16.1.2/32
> 14:33:40.128220 BGP: [H5X66-NXP9S] 192.168.3.1(r4) Long-lived set stale community (LLGR_STALE) for: …
=> bgpd: fix dynamic peer graceful restart race condition

tests/lib/subdir.am
`make check` should run w/o installing FRR first. Thus we need to embed the yang modules otherwise mgmtd unit-test fails.
=> tests: embed YANG in mgmtd unit-test bin

zebra/dpdk/zebra_dplane_dpdk.c, zebra/dpdk/zebra_dplane_dpdk.h
Hi,
This is my first try to fix Zebra against DPDK >= 22.11 API. Starting from this version DPDK had some changes:
> External users may still register their driver using the associated driver headers (see enable_driver_sdk meson option). **The rte_driver and rte_device objects are now opaque and must be manipulated through added accessors**.
There are few issues still:
1. To enable the DPDK we need to compile FRRouting with `--enable-dp-dpdk=yes`
2. usr/lib/*/frr/modules/zebra_dplane_dpdk.so is missing from debian/frr.install . For testing purpose I've created a script that adds this option and missing lib in the corresponding files.
3. Zebra is still crashing when I don't have any interfaces attached to DPDK. Keeps #15910 opened until we figured out the issue.
Partial solves #15910 .
=> zebra: Update Zebra DPDK >=22.11 API

zebra/fpm_listener.c
The header should be changed with the loop.
=> zebra: fix wrong fpm packet header

zebra/zebra_mpls.c, zebra/zebra_mpls_vty.c
Configured with "mpls label bind 1.1.1.1/32 explicit-null", the running configuration is:
```
!
mpls label bind 1.1.1.1/32 IPv4 Explicit Null
!
```
After this commit, the running configuration is:
```
!
mpls label bind 1.1.1.1/32 explicit-null
!
```
And add the support for the "no" form:
```
anlan(config)# mpls label bind 1.1.1.1/32 explicit-null
anlan(config)# no mpls label bind  1.1.1.1/32 explicit-null
```
=> zebra: fix mpls command

bgpd/bgp_route.c, bgpd/bgp_zebra.c
As part of backpressure changes, there is a bug where immediate withdraw is to be sent for evpn imported type-5 prefix to clear the nh neigh and RMAC entry.
Fixing this by sending withdraw immediately to keep it inline with the code today
Ticket: #3905571
=> bgpd: backpressure - Fix to withdraw evpn type-5 routes immediately

bgpd/bgp_evpn.c, bgpd/bgpd.c
In case when bgp_evpn_free or bgp_delete is called and the announce_list has few items where vpn/bgp does not match, we add the item back to the list. Because of this the list count is always > 0 thereby hogging CPU or infinite loop.
Ticket: #3905624
=> bgpd: backpressure - Fix to avoid CPU hog

bgpd/bgp_main.c, eigrpd/eigrp_main.c, isisd/isis_main.c, ldpd/ldpd.c, lib/agentx.c, lib/libagentx.c, lib/libagentx.h, lib/smux.h, lib/subdir.am, ospf6d/ospf6_main.c, ospfd/ospf_main.c, python/xref2vtysh.py, ripd/rip_main.c, zebra/main.c
If you had a situation where an operator turned on ospfd with snmp but not ospf6d and agentx was configured then you get into a situation where ospf6d would complain that the config for agentx did not exist.  Let's modify the code to allow this situation to happen.
Fixes: #15896
=> *: Modify agentx to be allowed to be called

zebra/zebra_routemap.c
Currently zebra does not deny the routes if `ip protocol <proto> route-map FOO`
commmand is configured with reference to an undefined route-map (FOO in this case).
However, on FRR restart, in zebra_route_map_check() routes get denied if route-map name is available but the route-map is not defined. This change was introduced in fd303a4ba14c762550db972317e1e88528768005.
Fix:
When `ip protocol <proto> route-map FOO` CLI is configured with reference to an undefined route-map FOO, let the processing in ip_protocol_rm_add() and ip_protocol_rm_del() go through so that zebra can deny the routes instead of simply returning. This will result in consistent behavior.
Testing Done:
Before fix:
```
spine-1# configure
spine-1(config)# ip protocol bgp route-map rmap7
root@spine-1:mgmt:/var/home/cumulus# …
```
=> zebra: Deny the routes if ip protocol CLI refers to an undefined rmap

isisd/isis_spf.c
Trying to build a new topotest based on the attached commit but the following head-after-free error is raised.
```
==2334217==ERROR: AddressSanitizer: heap-use-after-free on address 0x61000001d0a0 at pc 0x563828c8de6f bp 0x7fffbdaee560 sp 0x7fffbdaee558
READ of size 1 at 0x61000001d0a0 thread T0
#0 0x563828c8de6e in prefix_sid_cmp isisd/isis_spf.c:187
#1 0x7f84b8204f71 in hash_get lib/hash.c:142
#2 0x7f84b82055ec in hash_lookup lib/hash.c:184
#3 0x563828c8e185 in isis_spf_prefix_sid_lookup isisd/isis_spf.c:209
#4 0x563828c90642 in isis_spf_add2tent isisd/isis_spf.c:598
#5 0x563828c91cd0 in process_N isisd/isis_spf.c:824
#6 0x563828c93852 in isis_spf_process_lsp isisd/isis_spf.c:1041
#7 0x563828c98dde in isis_spf_loop isisd/isis_spf.c:1821
#8 0x563828c998de in isis_run_spf …
```
=> isisd: fix heap-after-free with prefix sid

bgpd/bgp_mplsvpn.c, tests/topotests/bgp_vrf_route_leak_basic/test_bgp-vrf-route-leak-basic.py, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-ray.txt
Leaked route from the l3VRF are installed with the loopback as the nexthop interface instead of the real interface.
> B>* 10.0.0.0/30 [20/0] is directly connected, lo (vrf default), weight 1, 00:21:01
Routing of packet from a L3VRF to the default L3VRF destined to a leak prefix fails because of the default routing rules on Linux.
> 0:      from all lookup local
> 1000:   from all lookup [l3mdev-table]
> 32766:  from all lookup main
> 32767:  from all lookup default
When the packet is received in the loopback interface, the local rules are checked without match, then the l3mdev-table says to route to the loopback. A routing loop occurs (TTL is decreasing).
> 12:26:27.928748 ens37 In  IP (tos 0x0, ttl 64, id 26402, offset 0, flags [DF], proto ICMP (1), length 84)
>     10.0.0.2 > 10.0.1.2: …
=> bgpd: fix route leaking from the default l3vrf

bgpd/bgp_clist.c, bgpd/bgp_clist.h, bgpd/bgp_vty.c
bgpd: Return success if lcomm/comm/extcomm name or entry is not found
Problem:
Currently bgp prints `Can't find community-list` and returns CMD_WARNING_CONFIG_FAILED
error if name or an entry for community, large-community and ext-community is not found. This
causes frr-reload to fail.
Fix:
Return success if community, large-community and ext-community name or
an entry is not found.
Ticket:#3900813
Testing Done:
Before fix:
```
root@tor-4:mgmt:/var/home/cumulus# cat /etc/frr/frr.conf
<SNIP>
bgp large-community-list standard lc22 seq 10 permit 4200857911:011:01 4200857911:011:011555
no bgp large-community-list standard lc22 seq 10 permit 4200857911:011:01
<SNIP>
root@tor-4:mgmt:/var/home/cumulus# systemctl reload frr
Job for frr.service failed.
See "systemctl status frr.service" and …
```
=> bgpd: Return success if lcomm/comm/extcomm name or entry is not found

doc/user/ospfd.rst, ospfd/ospf_vty.c
Add the specific instance id for one ospf command, more in commit log.
=> ospfd: add instance id for one command

ospf6d/ospf6_abr.c, ospf6d/ospf6_asbr.c, ospf6d/ospf6_gr.c, ospf6d/ospf6_intra.c, ospf6d/ospf6_lsa.c, ospf6d/ospf6_lsa.h, ospf6d/ospf6_lsdb.c, ospf6d/ospf6_message.c, ospf6d/ospf6_nssa.c, ospf6d/ospf6_snmp.c, ospf6d/ospf6_spf.c
This PR proposes the removal of OSPF6_LSA_HEADER_END, OSPF6_LSA_SIZE and OSPF6_LSA_END macros. It replaces those macros with inline functions that enables better type checking and reduces the number of unchecked type casts. No functional change is intended.
=> Cleanup some OSPF6_LSA_ macros

include/linux/compiler_types.h, include/linux/if.h, include/linux/libc-compat.h, include/subdir.am, lib/if.c, tests/topotests/all_protocol_startup/r1/show_ip_ospf_interface.ref, tests/topotests/nhrp_topo/test_nhrp_topo.py, tests/topotests/ospf_basic_functionality/test_ospf_single_area.py, zebra/fpm_listener.c
In Linux, a network driver can set the interface flags IFF_UP and IFF_RUNNING although the IFF_LOWER_UP flag is down, which means the interface is ready but the carrier is down:
> These values contain interface state:
>
> ifinfomsg::if_flags & IFF_UP:
>  Interface is admin up
> ifinfomsg::if_flags & IFF_RUNNING:
>  Interface is in RFC2863 operational state UP or UNKNOWN. This is for
>  backward compatibility, routing daemons, dhcp clients can use this
>  flag to determine whether they should use the interface.
> ifinfomsg::if_flags & IFF_LOWER_UP:
>  Driver has signaled netif_carrier_on()
However, FRR considers an interface is operational as soon it is up (IFF_UP) and running (IFF_RUNNING), disregarding the IFF_LOWER_UP flag. This can lead to a scenario where FRR starts adding routes …
=> lib: take into account the Linux IFF_LOWER_UP flag

ospfd/ospf_te.c
https://github.com/FRRouting/frr/pull/15674
=> ospfd: Solved crash in RI parsing with OSPF TE (backport #15674)

ospf6d/ospf6_abr.c, ospf6d/ospf6_route.h
When a router route already exists in the area border routers table as an ABR and it solely changes its ABR or ASBR status, the change was missed and border route is not updated. This fixes the comparison for the router_bits in the ospf6_path structure.
This fixes issue https://github.com/FRRouting/frr/issues/16053 although the actual problem is not the computing router (r2) and not the OSPFv3 redistribution (r3).
Fixes: https://github.com/FRRouting/frr/issues/16053
=> ospf6d: OSPFv3 route change comparision fixed for ASBR-only change

yang/frr-bgp-route-map.yang, yang/frr-ospf-route-map.yang, yang/frr-ospf6-route-map.yang
Using absolute xpath is not optimal for finding the target node. As the route map configuration grows, the yang validation will take more time to complete. Relative paths are much faster.
Tested with a config file that contains ~3k route map config lines.
-before: 
time cat conf | vtysh
configure
log syslog errors
router bgp 65000
!
route-map RM:BGP:VPNV4:PEER:VRR9:IN10001 permit 101
match community CL:HCC:PATH_PRIO1_EAST1
set local-preference 15200
!
... (route-map RM:BGP:VPNV4:PEER:VRR9:IN10001 permit 102-1181)
route-map RM:BGP:VPNV4:PEER:VRR9:IN10001 permit 1182
match community CL:HCC:PATH_PRIO1_EAST1082
set local-preference 16281
!
real    13m51.500s
user    0m0.522s
sys     0m4.854s
-after: 
time cat conf | vtysh
...
real    0m48.390s
user    0m0.384s
sys     0m1.245s
=> yang: use relative path instead of absolute one for route-map

tests/topotests/zebra_seg6_route/r1/routes_setup.json, tests/topotests/zebra_seg6_route/test_zebra_seg6_route.py
Locally this test would occassionally fail for me
because the connected route the sharp route being
installed has not fully come up yet due to heavy
load and start up slowness.  Add a bit of code
to look for the problem and make sure it doesn't
happen.
=> tests: Fix zebra_seg6_route

nhrpd/nhrp_main.c, tests/topotests/nhrp_redundancy/r1/nhrp_cache.json, tests/topotests/nhrp_redundancy/r1/nhrp_route.json, tests/topotests/nhrp_redundancy/r1/nhrpd.conf, tests/topotests/nhrp_redundancy/r1/zebra.conf, tests/topotests/nhrp_redundancy/r2/nhrp_cache.json, tests/topotests/nhrp_redundancy/r2/nhrp_route.json, tests/topotests/nhrp_redundancy/r2/nhrpd.conf, tests/topotests/nhrp_redundancy/r2/zebra.conf, tests/topotests/nhrp_redundancy/r3/nhrp_cache.json, tests/topotests/nhrp_redundancy/r3/nhrp_route.json, tests/topotests/nhrp_redundancy/r3/nhrpd.conf, tests/topotests/nhrp_redundancy/r3/zebra.conf, tests/topotests/nhrp_redundancy/r4/nhrp_cache.json, tests/topotests/nhrp_redundancy/r4/nhrp_route.json, tests/topotests/nhrp_redundancy/r4/nhrp_route_shortcut.json, tests/topotests/nhrp_redundancy/r4/nhrpd.conf, tests/topotests/nhrp_redundancy/r4/zebra.conf, tests/topotests/nhrp_redundancy/r5/nhrp_cache.json, tests/topotests/nhrp_redundancy/r5/nhrp_route.json, tests/topotests/nhrp_redundancy/r5/nhrpd.conf, tests/topotests/nhrp_redundancy/r5/zebra.conf, tests/topotests/nhrp_redundancy/r6/zebra.conf, tests/topotests/nhrp_redundancy/r7/zebra.conf, tests/topotests/nhrp_redundancy/test_nhrp_redundancy.dot, tests/topotests/nhrp_redundancy/test_nhrp_redundancy.py
When nhrpd is shutdown via nhrp_request_stop() the shutdown sequence was not handling the case where there are active shortcut routes installed. The zebra client and shortcut rib were being cleaned up before vrf_terminate() had an opportunity to delete the active routes.
[core.txt](https://github.com/FRRouting/frr/files/15152268/core.txt)
=> nhrpd: fixes core dump on shutdown

lib/atomlist.h
`lib/typesafe.h` was supposed to be outside the `_TYPESAFE_EXPAND_MACROS` guard, so that including `lib/atomlist.h` grabs all the typesafe container macros.
(No effect on normal build, as `_TYPESAFE_EXPAND_MACROS` is never defined there.)
---
blech. off by one line error in the `#ifndef`.
=> lib: make `python/ts_expand.py` actually work

pimd/pim_igmpv3.c
Fixes: #15630
There is no reason to call `igmp_anysource_forward_stop()`  inside a call to 
`igmp_get_source_by_addr()`. The decision to start/stop forwarding is already handled correctly 
by pim outside `igmp_get_source_by_addr()`. That call was left there from the days pim was
initially imported in.
The problem was happening because `igmp_find_source_by_addr()` would fail to find the group/source  combo when 
mixing `(*, G)` and `(S, G)`, so a new entry is correctly created, but `igmp_anysource_forward_stop(group)` always stops (and eventually frees) `(*, G)` , but leaving a bad state because the new entry for `(S, G)` shouldn't have caused `(*, G)` to go away.
Tested the fix with multiple receivers on the same interface with several  ssm and any source senders and receivers with …
=> pimd: fix crash when mixing ssm/any-source joins

ospf6d/ospf6_gr_helper.c
When parsing a osf6 grace lsa field and we receive an unknown tlv type, ospf6d was not incrementing the pointer to get beyond the tlv.  Leaving a situation where ospf6d would parse the packet incorrectly.
=> ospf6d: Prevent heap-buffer-overflow with unknown type

nhrpd/nhrp_main.c
This fixes a merge conflict encountered when backporting  #15879
=> nhrpd: core dump on shutdown (backport #15879)

pimd/pim_mroute.c
When the kernel is not compiled with mroute vrf's enabled it will fail the call to initialize the vrf.  As such let's recognize this specific error code and output a specific warning to the operator to help them figure this problem out.
=> pimd: Give a clearer warning when the kernel is not compiled right

bgpd/bgp_network.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst
The default DSCP used for BGP connections is CS6. The DSCP value is not part of the TCP header.
When setting the IP_TOS or IPV6_TCLASS socket options, the argument is not the 6-bit DSCP value, but an 8-bit value for the former IPv4 Type of Service field or IPv6 Traffic Class field, respectively.
Fixes: #11152
=> bgpd: Adjust terminology related to DSCP

.github/workflows/conflicts.yml
This change will stop this action from running on forked repos. Previously whenever one pushed a change to one's development branch the action would "run but skip" which still generated an email notifications and thus was very annoying. :)
The "pull_request" event-id by default runs on event types of [ opened, reopened, synchronize ] which I believe is the original intention.
=> ci: only run conflict check on pull-requests

isisd/isis_spf.c, tests/isisd/test_isis_spf.refout
The IPv4 directly connected route prefix exists in both the root LSP and the root's neighbor LSP:
1. When generating vertices for directly connected route prefixes with a metric of 0 based on the root LSP, the `isis_spf_preload_tent_ip_reach_cb` function only generates vertices of type `VTYPE_IPREACH_INTERNAL `without distinguishing between `area->oldmetric` and `area->newmetric`.
2. When generating vertices for the directly connected route prefix based on the neighbor LSP, the `isis_spf_process_lsp` function will generate vertices of type `VTYPE_IPREACH_INTERNAL` and `VTYPE_IPREACH_TE` based on `area->oldmetric` and `area->newmetric`, where the vertex metric is the sum of the metric from the root IS to the neighbor IS and from the neighbor IS to the root IS, respectively.
If …
=> isisd: When the metric-type is configured as "wide", the IS-IS generates incorrect metric values for IPv4 directly connected routes.

zebra/zebra_netns_notify.c
Fixes:
``` C
zebra/zebra_netns_notify.c: In function 'zebra_ns_ready_read':
zebra/zebra_netns_notify.c:266:40: error: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
266 |         if (strmatch(VRF_DEFAULT_NAME, basename(netnspath))) {
|                                        ^~~~~~~~
```
Fixed by including `libgen.h`, then since `basename` may modify its parameter, allocate a copy on the stack, using `strdupa`, and pass the temporary string to `basename`.
According to the man page for basename:
> With `glibc`, one gets the POSIX version of `basename()` when `<libgen.h>` is included, and the GNU version otherwise.
> The POSIX version of `basename` may modify the contents of path, so we should to pass a copy when calling this function.
Please let me know if any …
=> zebra: fix compilation with GCC14

bgpd/bgpd.c
Configuration:
```
vtysh <<EOF
configure
vrf vrf100
vni 10100
exit-vrf
router bgp 50
address-family l2vpn evpn
advertise-all-vni
exit
router bgp 100 vrf vrf100
exit
EOF
```
TL;DR; When we configure `advertise-all-vni` (in this case), a new BGP instance is created with the name vrf100, and ASN 50. Next, when we create `router bgp 100 vrf vrf100`, we look for the BGP instance with the same name and we found it, but ASNs are different 50 vs. 100.
Every such a new auto created instance is flagged with BGP_VRF_AUTO.
After the fix:
```
router bgp 50
!
address-family l2vpn evpn
advertise-all-vni
exit
!
router bgp 100 vrf vrf100
exit
!
end
donatas.net(config)# router bgp 51
BGP is already running; AS is 50
donatas.net(config)# router bgp 50 …
```
=> bgpd: Ignore auto created VRF BGP instances

nhrpd/nhrp_main.c, nhrpd/nhrp_shortcut.c
nhrp_shortcut_terminate() previously was just freeing the associated AFI shortcut RIBs and not addressing existing shortcut cache entries. This cause a use after free issue in vrf_terminate() later in the terminate sequence
NHRP: Received signal 7 at 1717516286 (si_addr 0x1955d, PC 0x7098786912c0); aborting...
NHRP: zlog_signal+0xf5                   709878ad1255     7fff3d992eb0 /usr/lib/frr/libfrr.so.0 (mapped at 0x709878a00000)
NHRP: core_handler+0xb5                  709878b0db85     7fff3d992ff0 /usr/lib/frr/libfrr.so.0 (mapped at 0x709878a00000)
NHRP: __sigaction+0x50                   709878642520     7fff3d993140 /lib/x86_64-linux-gnu/libc.so.6 (mapped at 0x709878600000)
NHRP:     ---- signal ----
NHRP: __lll_lock_wait_private+0x90       7098786912c0     7fff3d9936d8 …
=> nhrpd: cleans up shortcut cache entries on termination

zebra/zebra_srv6_vty.c
The 'show running-config' does not display the ipv6 source address when a locator is not configured. Fix this by systematically displaying the ipv6 source address.
Fixes: 6a0956169b31 ("zebra: Add encap source address to SRv6 config write function")
=> zebra: display srv6 encapsulation source-address when configured

isisd/isis_lsp.c, isisd/isis_tlvs.c, isisd/isisd.c, tests/topotests/isis_topo1/test_isis_topo1.py
Fixes for show isis database [detail] json
- Clean JSON format.
- Display multiple values into array. They were mixed together in the same dict.
=> isisd: fix show isis database [detail] json

docker/debian/Dockerfile
1. **Environment Setup**:
- 1: "Docker desktop running on Apple silicon M3"
2. **Reproduce Issue**:
- Download Files On: "[Navigate to the directory containing the Dockerfile](https://github.com/FRRouting/frr/tree/master/docker/debian)."
- Run Command: "`docker build -t frr-debian:latest .`"
- Run Command: "`docker run -itd --privileged --name frr frr-debian:latest`"
3. **Expected Behavior**:
Just Run as stated on document 
4. **Actual Behavior**:
-Output: "`docker logs -f frr`"
"`[FATAL tini (7)] exec /usr/lib/frr/docker-start failed: Permission denied`"
Chmod fixes this issue.
-
=> docker: fix chmod issues when running container for debian

bgpd/bgp_evpn_mh.c, lib/ipaddr.h, lib/prefix.c, lib/prefix.h, lib/stream.c, lib/stream.h, tests/lib/test_printfrr.c, zebra/zebra_evpn_mh.c, zebra/zebra_vxlan.c
This changeset introduces changes in lib for prefix_sg (and associated downstream consumers in bgpd/zebra)
- src address in prefix_sg is now v6 aware (struct ipaddr)
- %pSG4 now prints a v6 src address
- Places where zebra uses prefix_sg src address are now V6 aware
- ES_VTEP_LIST_STR_SZ can now support a v6 VTEP address
- This has impacts in bgpd and zebra as uint8_t is not enough for printing (size_t changes)
This is a part of the upstreaming process for #5885.
=> lib, bgpd, tests, zebra: prefix_sg changes for V6 VTEP

lib/vty.c, lib/vty.h, tests/topotests/bgp_vrf_route_leak_basic/test_bgp-vrf-route-leak-basic.py, zebra/zebra_vty.c
The command show ip[v6] route [vrf (all|XX)] json may cause an out-of-memory error when attempting to display large route tables.
Currently, JSON objects are created for every prefix and stored in a table JSON object. Once all the prefixes are collected, the table JSON is dumped, and all associated JSON objects are freed. Since commit 0e2fc3d67f, table JSON objects for each VRF are stored in a root JSON object. Similarly, the root JSON is dumped, and all related JSON objects are freed.
When the route tables are large, this process allocates a significant amount of memory for all the JSON objects containing the prefixes. In some cases, this leads to a crash of the protocol daemon due to insufficient memory on the machine.
To address this, instead of storing all the prefix JSON objects in …
=> zebra: fix Out Of Memory issue when displaying large route tables in JSON

ospf6d/ospf6_flood.c
Description:
OSPF6 GR HELPER router should  consider as TOPOCHANGE when it receives lsas with max age and should exit from Helper. But, it is not exiting from helper because this max age lsa is considered as duplicated lsa since the sender uses same seq number for max age lsa from the previous lsa update. Currently, topo change is not considered for duplicated lsas. So removed the duplicated check when validating TOPOCHNAGE.
=> ospf6d: Handling Topo Change in GR-HELPER mode for max-age lsas

doc/user/installation.rst
The [documentation](https://docs.frrouting.org/en/stable-8.0/installation.html#python-dependency-documentation-and-tests) says that Python is used only for docs, tests, and building process. But at the same time, [FRR uses the Python script](https://docs.frrouting.org/en/stable-8.0/frr-reload.html) for the "[frr reload](https://docs.frrouting.org/en/latest/setup.html#reloading)" operation.
Therefore, I propose to add this point to the documentation.
Related discussion: https://github.com/FRRouting/frr/discussions/16073
=> doc: Add reloading script into Python dependency section

lib/zclient.c
When switching from nexthop to zapi_nexthop, the srte color is copied. Do the same in reverse.
Fixes: 31f937fb43f4 ("lib, zebra: Add SR-TE policy infrastructure to zebra")
=> lib: fix copy srte_color from zapi_nexthop structure

lib/darr.h, lib/mgmt_msg_native.c, lib/mgmt_msg_native.h, lib/yang.c, mgmtd/mgmt_fe_adapter.c, tests/lib/test_darr.c, tests/topotests/lib/fe_client.py, tests/topotests/mgmt_notif/test_notif.py
- Add new notification select message for front-end clients
- Add new native session-req and session-reply replacements for front-end protobuf messages
- Extend fe_client to support new native notify select and session-req messages
- Add topotest
- Add string array encoding/decode to native messages
=> mgmtd: add notification selection to front-end API 

yang/frr-isisd.yang
Before:
```
anlan(config)# route isis ix
anlan(config-router)# metric-style transition
...
anlan(config-if)# isis metric 200
Error description: YANG error(s):
Path: Data location "/frr-interface:lib/interface[name='x']/frr-isisd:isis/metric/level-1".
Error: Must condition ". < 64 or /frr-isisd:isis/instance[area-tag = current()/../../area-tag]/metric-style = 'wide' or not(/frr-isisd:isis/instance[area-tag = current()/../../area-tag]/metric-style)" not satisfied.
Path: Data location "/frr-interface:lib/interface[name='x']/frr-isisd:isis/metric/level-2".
Error: Must condition ". < 64 or /frr-isisd:isis/instance[area-tag = current()/../../area-tag]/metric-style = 'wide' or not(/frr-isisd:isis/instance[area-tag = …
```
=> yang: fix wrong check for isis metric style

zebra/dplane_fpm_nl.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h
Instead of keeping a counter that is independent
of the queue's data structure.  Just use the queue's built-in counter.  Ensure that it's pthread safe by keeping it wrapped inside the mutex for adding/deleting to the queue.
=> zebra: Use built in data structure counter

doc/user/nhrpd.rst, nhrpd/nhrp_interface.c, nhrpd/nhrp_nhs.c, nhrpd/nhrp_packet.c, nhrpd/nhrp_peer.c, nhrpd/nhrp_shortcut.c, nhrpd/nhrp_vty.c, nhrpd/nhrpd.h, nhrpd/subdir.am, tests/topotests/nhrp_topo/r1/nhrpd.conf, tests/topotests/nhrp_topo/r2/nhrpd.conf, tests/topotests/nhrp_topo/test_nhrp_topo.py
This PR takes over work done on https://github.com/FRRouting/frr/pull/14788 with agreement from @volodymyrhuti .
In addition to the work in 14788 I have addressed 4 issues I found while testing interop between Cisco and FRR:
1) FRR would accept messages from a spoke without authentication configured when FRR NHRP had auth configured.
2) The error indication was not being sent in network byte order
3) The debug print in nhrp_connection_authorized was not correctly printing the received password
4) The addresses portion of the mandatory part of the error indication was invalid on the wire (confirmed in wireshark)
=> nhrpd: add cisco-authentication password support

bgpd/bgp_mpath.c, bgpd/bgp_route.c, tests/topotests/bgp_duplicate_nexthop/r1/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r1/isisd.conf, tests/topotests/bgp_duplicate_nexthop/r1/zebra.conf, tests/topotests/bgp_duplicate_nexthop/r3/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r3/isisd.conf, tests/topotests/bgp_duplicate_nexthop/r3/zebra.conf, tests/topotests/bgp_duplicate_nexthop/r4/isisd.conf, tests/topotests/bgp_duplicate_nexthop/r4/zebra.conf, tests/topotests/bgp_duplicate_nexthop/r5/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r5/isisd.conf, tests/topotests/bgp_duplicate_nexthop/r5/zebra.conf, tests/topotests/bgp_duplicate_nexthop/r6/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r6/isisd.conf, tests/topotests/bgp_duplicate_nexthop/r6/zebra.conf, tests/topotests/bgp_duplicate_nexthop/test_bgp_duplicate_nexthop.py, tests/topotests/lib/common_check.py, tests/topotests/lib/topotest.py
Under a setup where two BGP prefixes are available from multiple sources, if one of the two prefixes is recursive over the other BGP prefix, then it will not be considered as multipath. The below output shows the two prefixes 192.0.2.24/32 and 192.0.2.21/32. The 192.0.2.[5,6,8] are the known IP addresses visible from the IGP.
> # show bgp ipv4 192.0.2.24/32
> *>i 192.0.2.24/32    192.0.2.21               0    100      0 i
> * i                  192.0.2.21               0    100      0 i
> * i                  192.0.2.21               0    100      0 i
> # show bgp ipv4 192.0.2.21/32
>  *>i 192.0.2.21/32    192.0.2.5                0    100      0 i
>  *=i                  192.0.2.6                0    100      0 i
>  *=i                  192.0.2.8                0    100      0 i
The bgp …
=> bgpd: fix do not skip paths with same nexthop

isisd/isis_events.c
1. Router A is configured with "is-type level-1-2", while Router B is configured with "is-type level-1". Only level 1 neighbor entries are present on Router A.
2. After configuring Router B with "is-type level-2-only", both level 1 and level 2 neighbor entries exist on Router A. The state of these entries is UP, and the level 1 neighbor entry is currently aging.
3. Before the level 1 neighbor entry on Router A ages out, configuring Router B with "is-type level-1", both level 1 and level 2 neighbor entries exist on Router A. The level 2 neighbor entry is UP and will age out normally. However, the level 1 neighbor entry remains in the Initializing state, preventing the establishment of level 1 neighbor adjacency between Router A and Router B.
When the adjacency type of the link is switched …
=> isisd: After the router switches IS-IS type several times, the neighbor adjacency cannot be established.

lib/termtable.c, lib/termtable.h
The following table is not compliant with caml format when displayed in json:
>                 ttable_add_row(
>                         tt,
>                         "Vertex|Type|Metric|Next-Hop|Interface|Parent");
>
>                 ttable_json(tt, "ssdsss");
output observed:
> [..]
>        {
>          "Vertex":"r1",
>          "Type":"",
>          "Metric":0,
>          "Next-Hop":"",
>          "Interface":"",
>          "Parent":""
>        }
output expected:
> [..]
>        {
>          "vertex":"r1",
>          "type":"",
>          "metric":0,
>          "nextHop":"",
>          "interface":"",
>          "parent":""
>        }
Override the ttable_json() function with a new function which has an extra paramter: this parameter will redefine the initial row value for json:
> …
=> lib: add json API to dump and override row naming convention

bgpd/bgp_zebra.c
Use the name for when putting out debugs in bgp_zebra.c. Additionally add an evpn flag for announce_route_actual.
=> bgpd: Convert over to using vrf name instead of id

zebra/zebra_dplane.c
When removing a large number of routes, the linux kernel can take the cpu for an extended amount of time, leaving a situation where FRR detects a starvation event.
r1# sharp install routes 10.0.0.0 nexthop 192.168.44.33 1000000 repeat 10 2024-06-14 12:55:49.365 [NTFY] sharpd: [M7Q4P-46WDR] vty[5]@# sharp install routes 10.0.0.0 nexthop 192.168.44.33 1000000 repeat 10 2024-06-14 12:55:49.365 [DEBG] sharpd: [YP4TQ-01TYK] Inserting 1000000 routes 2024-06-14 12:55:57.256 [DEBG] sharpd: [TPHKD-3NYSB] Installed All Items 7.890085 2024-06-14 12:55:57.256 [DEBG] sharpd: [YJ486-NX5R1] Removing 1000000 routes 2024-06-14 12:56:07.802 [WARN] zebra: [QH9AB-Y4XMZ][EC 100663314] STARVATION: task dplane_thread_loop (634377bc8f9e) ran for 7078ms (cpu time 220ms) 2024-06-14 12:56:25.039 [DEBG] sharpd: …
=> zebra: Prevent starvation in dplane_thread_loop

bgpd/bgp_zebra.c
In scaled EVPN + ipv4/ipv6 uni route sync to zebra, some of the ipv4/ipv6 routes skipped re installation
due to incorrect local variable's stale value.
Once the local variable value reset in each loop iteration all skipped routes synced to zebra properly.
Signed-off-by: Rajasekar Raja <rajasekarr@nvidia.com>
=> bgpd: backpressure - fix evpn route sync to zebra

bgpd/bgp_evpn.c, bgpd/bgp_evpn.h, bgpd/bgpd.c
When a vrf is deleted from the kernel, before its removed from the FRR config, zebra gets to delete the the vrf and assiciated state.
It does so by sending a request to delete the l3 vni associated with the vrf followed by a request to delete the vrf itself.
```
2023/10/06 06:22:18 ZEBRA: [JAESH-BABB8] Send L3_VNI_DEL 1001 VRF testVRF1001 to bgp
2023/10/06 06:22:18 ZEBRA: [XC3P3-1DG4D] MESSAGE: ZEBRA_VRF_DELETE testVRF1001
```
The zebra client communication is asynchronous and about 1/5 cases the bgp client process them in a different order.
```
2023/10/06 06:22:18 BGP: [VP18N-HB5R6] VRF testVRF1001(766) is to be deleted.
2023/10/06 06:22:18 BGP: [RH4KQ-X3CYT] VRF testVRF1001(766) is to be disabled.
2023/10/06 06:22:18 BGP: [X8ZE0-9TS5H] VRF disable testVRF1001 id 766
2023/10/06 06:22:18 …
```
=> bgpd: fixed failing to remove VRF if there is a stale l3vni

bgpd/bgp_zebra.c
The backup_nexthop entry list has been populated by mistake, and should not. Fix this by reverting the introduced behavior.
Fixes: 237ebf8d4503 ("bgpd: rework bgp_zebra_announce() function, separate nexthop handling")
=> bgpd: fix do not use api.backup_nexthop in ZAPI message

zebra/interface.c
In case of EVPN MH bond, a member port going in protodown state due to external reason (one case being linkflap), 
frr updates the state correctly but upon manually clearing external reason trigger FRR to reinstate protodown without any reason code.
Fix is to ensure if the protodown reason was external and new state is to have protodown 'off' then do no reinstate protodown.
Testing:
```
switch:#ip link show swp1
4: swp1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 9216 qdisc
pfifo_fast master bond1 state DOWN mode DEFAULT group default qlen
1000
link/ether 1c:34:da:2c:aa:68 brd ff:ff:ff:ff:ff:ff protodown on
protodown_reason <linkflap>
switch:#ip link set swp1 protodown off protodown_reason linkflap off 
switch:#ip link show swp1
4: swp1: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu …
```
=> zebra: fix evpn mh bond member proto reinstall

pimd/pim6_main.c, pimd/pim_addr.h, pimd/pim_bsm.c, pimd/pim_main.c, pimd/pim_nht.c, pimd/pim_nht.h, pimd/pim_pim.c, pimd/pim_rp.c, tools/checkpatch.pl
Preparations for C-RP/C-BSR:
- make clang-format not wreck the YANG module lists
- print a debug if we're RP ourselves (helpful when debugging C-RP)
- allow sending unicast PIM packets that are routed normally by the kernel (C-RP advertisements)
- pre-plumb in the NHT infrastructure for BSRs to track C-RPs
---
#15969 rebase & reopen (the old PR has CI stuck in some weird state)
=> pimd: Candidate RP/BSR preparation

bgpd/bgp_vty.c, bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/16238
=> bgpd: Set last reset reason to admin shutdown if it was manually

bgpd/bgp_aspath.c, bgpd/bgp_aspath.h, bgpd/bgp_filter.c, bgpd/bgp_filter.h, bgpd/bgp_routemap.c, tests/topotests/bgp_set_aspath_exclude/r1/bgpd.conf, tests/topotests/bgp_set_aspath_exclude/r3/zebra.conf, tests/topotests/bgp_set_aspath_exclude/test_bgp_set_aspath_exclude.py
bgpd: fix "bgp as-pah access-list" with "set aspath exclude" set/unset issues
whith the following config
neighbor 192.168.1.2 remote-as external
neighbor 192.168.1.2 timers 3 10
!
neighbor 192.168.1.2 route-map r2 in
exit
!
bgp as-path access-list FIRST seq 5 permit ^65
bgp as-path access-list SECOND seq 5 permit 2$
!
route-map r2 permit 6
match ip address prefix-list p2
set as-path exclude as-path-access-list SECOND
exit
!
route-map r2 permit 10
match ip address prefix-list p1
set as-path exclude 65003
exit
!
route-map r2 permit 20
match ip address prefix-list p3
set as-path exclude all
exit
making some
no bgp as-path access-list SECOND permit 2$
bgp as-path access-list SECOND permit 3$
clear bgp …
=>  bgpd: fix "bgp as-pah access-list" with "set aspath exclude" set/unset issue

isisd/isis_tlvs.c
- Fix a crash when doing "show isis database detail json" in isis_srv6_topo1 topotest.
- Rename a variable that was incorrectly named, leading to confusion and causing the crash bug
- fix a JSON key
Fixes: 2e670cd779 ("isisd: fix display of srv6 subsubtlvs")
Fixes: 648a158802 ("isisd: Add SRv6 End.X SID to Sub-TLV format func")
=> isisd: fix crash in display srv6 sid structure in json

isisd/isis_tlvs.c
Fix crash when displaying ASLAs (Application Specific Link-Attributes) with JSON
(cherry picked from commit 1c397942a46999a850ada62ea015a658373150c6)
=> isisd: fix crash when displaying asla in json

zebra/zebra_nb_rpcs.c
clear evpn dup-addr cli returns error-msg for below conditions,
- If evpn is not enabled &
- If there is no VNI exists.
supported command:
```
clear evpn dup-addr vni <vni-id>
```
Testing:
```
bharat# clear evpn dup-addr vni 20
Error description: % EVPN not enabled
bharat# clear evpn dup-addr vni 20
Error description: % VNI 20 does not exist
```
=> zebra: clear evpn dup-addr return error-msg when there is no vni

zebra/zebra_srv6.c
Fix CID 1594013, 1594014, 1594015, 1594016.
=> zebra: Fix coverity issues

isisd/isis_spf.c, isisd/isis_spf.h, tests/isisd/test_isis_spf.c, tests/isisd/test_isis_spf.refout, tests/topotests/isis_topo1/r1/r1_topology.json, tests/topotests/isis_topo1/r2/r2_topology.json, tests/topotests/isis_topo1/r3/r3_topology.json, tests/topotests/isis_topo1/r4/r4_topology.json, tests/topotests/isis_topo1/r5/r5_topology.json, tests/topotests/isis_topo1/test_isis_topo1.py, tests/topotests/isis_topo1_vrf/r1/r1_topology.json, tests/topotests/isis_topo1_vrf/r2/r2_topology.json, tests/topotests/isis_topo1_vrf/r3/r3_topology.json, tests/topotests/isis_topo1_vrf/r4/r4_topology.json, tests/topotests/isis_topo1_vrf/r5/r5_topology.json, tests/topotests/isis_topo1_vrf/test_isis_topo1_vrf.py
Add json support for 'show isis route' , paths part.
=> Isis show route paths json

bgpd/bgp_fsm.c
Under heavy system load with many peers in passive mode and a large number of routes, bgpd can enter an infinite loop. This occurs while processing timeout BGP_OPEN messages, which prevents it from accepting new connections. The following log entries illustrate the issue:
>bgpd[6151]: [VX6SM-8YE5W][EC 33554460] 3.3.2.224: nexthop_set failed, resetting connection - intf 0x0
>bgpd[6151]: [P790V-THJKS][EC 100663299] bgp_open_receive: bgp_getsockname() failed for peer: 3.3.2.224
>bgpd[6151]: [HTQD2-0R1WR][EC 33554451] bgp_process_packet: BGP OPEN receipt failed for peer: 3.3.2.224
... repeating
The issue occurs when bgpd handles a massive number of routes in the RIB while receiving numerous BGP_OPEN packets. If bgpd is overloaded, it fails to process these packets promptly, leading the remote …
=> bgpd: avoid clearing routes for peers that were never established

pimd/pim_rp.c
The `!rp_info ||` check got added during a cleanup pass.  Unfortunately the braces/and/or combination is not correct :(
(for `rp_info == NULL && source != INADDR_ANY`)
Fixes: b194536 ("pimd: Various buffer overflow reads and crashes")
=> pimd: fix misplaced braces/logic error in pim_rp_set_upstream_addr

doc/developer/conf.py, doc/user/conf.py
Style checking is complaining about these, rightly so. Reformat.
=> doc: reformat Sphinx conf.py files

doc/user/about.rst, doc/user/basics.rst, doc/user/bfd.rst, doc/user/index.rst, doc/user/installation.rst, doc/user/introduction.rst, doc/user/protocols.rst, doc/user/subdir.am
The current TOC organization is not really following Sphinx best practices and is resulting in a jumble of articles showing up in the sidebar.
Result of these changes is viewable here: https://qlyoung.net/frr-docs/
Compare to: https://docs.frrouting.org/en/latest/
This change primarily organizes existing articles into three major sections:
* Introduction
- Contains system requirements, architecture & design, installation, basic setup
* Basics
- Covers basic commands, concepts, and some random things that don't fit elsewhere
* Protocols
- Contains all protocol documentation, and other miscellaneous daemon docs such as those on Zebra, watchfrr, mgmtd, etc.
The appendix has been left as is, but the TOC now has a caption which has the effect of adding a section separator in the nav sidebar. …
=> doc: improve table-of-contents organization

doc/user/conf.py
Multiple daemons have the same CLI commands defined, but the current directive used to document CLI commands only takes the command definition string. Since CLI command objects can be cross-referenced using the :clicmd: directive, and are placed in the index, each object needs to be unique.
To accomplish this, add a custom directive. This directive extends the directive class used by sphinx's add_object_type to add a :daemon: option. By specifying this option where needed, the object name becomes "(<daemon>) <definition>", disambiguating it.
tl;dr
```
.. clicmd:: foo bar
:daemon: zebra
<later>
.. clicmd:: foo bar
:daemon: bgpd
```
Fixes `WARNING: duplicate clicmd description of foo bar, other instance in bgpd` type warnings; once all of these are resolved, there should be zero doc build …
=> doc: add ability to disambiguate clicmds

bgpd/bgp_evpn.c
Fix for a bug, where FRR fails to install route received for an unknown but later-created VRF - detailed description can be found here:
https://github.com/FRRouting/frr/issues/13708
This is our internal bug fix we introduced that fixed this issue for us shortly after submitting the issue report.
=> bgpd: Ignore routes from evpn if VRF is unknown

bgpd/bgp_route.c, tests/topotests/bgp_confed1/r2/bgpd.conf
Closes https://github.com/FRRouting/frr/issues/16304
=> bgpd: Ignore RFC8212 for BGP Confederations

ripd/ripd.c
Start the sequence at zero to make md5 authentication compatible with bird
=> ripd/ripd.c - rip_auth_md5 : Change the start value of sequence 1 to 0

isisd/isis_adjacency.c
When receiving a hello packet, if the neighbor state transitions directly from a non-ISIS_ADJ_UP state (such as ISIS_ADJ_INITIALIZING) to ISIS_ADJ_DOWN state, the neighbor entry cannot be deleted. If the neighbor is removed or the neighbor's System ID changes, it may result in memory leakage in the neighbor entry.
Test Scenario:
LAN link between Router A and Router B is established. Router A does not configure neighbor authentication, while Router B is configured with neighbor authentication. When the neighbor entry on Router B ages out, the neighbor state on Router A transitions to INIT. If Router B is then removed, the neighbor state on Router A transitions to DOWN and persists.
=> isisd: Fix memory leaks when the transition of neighbor state from non-UP to DOWN

debian/control, debian/copyright, debian/frr-grpc.install, debian/rules, doc/developer/packaging-debian.rst, doc/developer/packaging-redhat.rst, redhat/frr.spec.in
Adding Debian and RedHat packages with GRPC support built.
The GRPC part will be built as an extra submodule.
By default (at this time), the building of the GRPC is disabled unless specifically requested
To enable it, use `pkg.frr.grpc` as documented in `doc/developer/packaging-debian.rst`
=> Add option to build pkg with grpc support

isisd/isis_lfa.c
When a neighbor connection is disconnected, it may trigger LSP re-generation as a timer task, but this process may be delayed. As a result, the list of neighbors in `area->adjacency_list` may be inconsistent with the neighbors in `lsp->tlvs->oldstyle_reach/extended_reach`. For example, the `area->adjacency_list` may lack certain neighbors even though they are present in the LSP. When computing SPF, the call to `isis_spf_build_adj_list()` generates the `spftree->sadj_list`, which reflects the real neighbors in the `area->adjacency_list`. However, in the case of LAN links, `spftree->sadj_list` may include additional pseudo neighbors. The pre-loading of tents through the call to `isis_spf_preload_tent()` involves two steps:
1. `isis_spf_process_lsp()` is called to generate real neighbor …
=> isisd: fix crash when obtaining the next hop to calculate LFA on LAN links

bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgp_main.c, bgpd/bgp_open.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/bgp_vty.h, bgpd/bgp_zebra.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, lib/libfrr.c, lib/libfrr.h, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-4.py, tests/topotests/bgp_gr_notification/test_bgp_gr_notification.py, tests/topotests/lib/bgp.py, zebra/main.c, zebra/rib.h, zebra/zapi_msg.c, zebra/zebra_gr.c, zebra/zebra_rib.c, zebra/zebra_router.c, zebra/zebra_router.h, zebra/zebra_vty.c, zebra/zserv.c, zebra/zserv.h
Commit 1:
Add support for a BGP-wide setting for graceful restart modes and
parameters. This setting will apply to all BGP peers across all BGP
instances, but per-neighbor configuration can override it.
Per-instance configuration is disallowed if the BGP-wide setting
is in effect.
Commit2:
Streamline the BGP graceful-restart configuration at the global and
peer level some more. Similar to many other neighbor capability
parameters like MP and ENHE, reset the session immediately upon a
change to the configuration. This will be more aligned with the
transactional UI model also and will not require a separate 'clear'
command to be executed.
Note: Peer-group graceful-restart configuration is not yet supported.
Commit3:
bgpd: Refine restarter operation - R-bit & F-bit
Introduce BGP-wide flags …
=> Implement BGP-wide configuration for graceful restart

ldpd/neighbor.c
In linux networking stack, the received mpls packets will be processed by the host *twice*, one as mpls packet, the other as ip packet, so its ttl decreased 1.
So, we need release the `IP_MINTTL` value if gtsm is enabled, it is for the mpls packets of neighbor session caused by the command: `label local advertise explicit-null`.
This change makes the gtsm mechanism a bit deviation.
Fix  #8313
=> ldpd: fix wrong gtsm count

yang/frr-route-map.yang
=> yang: Corrected typo at yang file

sharpd/sharp_zebra.c
The ZAPI_MESSAGE_NEXTHOP flag is systematically set, even if the route message does not include any nexthops. Limit the usage of this value only when nexthops are present.
Fixes: 8a71d93d85a6 ("sharpd: Add Super Happy Advanced Routing Protocol")
=> sharpd: fix set ZAPI_MESSAGE_NEXTHOP in nhg only when nexthops used

isisd/isis_nb_config.c, isisd/isisd.c
When there are multiple areas on the same router, the following two scenarios exist:
1. When clearing the net in one of the areas, the system ID is unconditionally cleared, even if the net does not include the current system ID.
2. When deleting one of the areas, even if the net under the area includes the current system ID, the system ID still remains.
=> isisd: When operating multiple areas, the system ID behaves abnormally.

lib/libospf.h, ospfd/ospf_flood.c, ospfd/ospf_flood.h, ospfd/ospf_interface.c, ospfd/ospf_interface.h, ospfd/ospf_ism.c, ospfd/ospf_packet.c, ospfd/ospf_packet.h
1. On P2MP interfaces, direct ack would include the same LSA multiple times multiple packets are processed before the OSPF interfae direct LSA acknowledgment event is processed. Now duplicates LSA in the same event are suppressed.
2. On non-broadcast interfaces, direct acks for multiple neighbors would be unicast to the same neighbor due to the multiple OSPF LS Update packets being process prior to the OSPF interface direct ack event. Now, separate direct acks are unicast to the neighbors requiring them.
3. The interface delayed acknowledgment timer runs would run continously (every second as long as the interace is up). Now, the timer is set when delayed acknowledgments are queued and all queued delayed acknowledges are sent when it fires.
4. For non-broadcast interface delayed …
=> ospfd: Fix several problems with direct and delayed acknowledgments 

lib/frrcu.h, lib/seqlock.c, tests/lib/test_atomlist.c, tests/lib/test_seqlock.c
First go around and fix a bunch of mixups in test_seqlock, then make TSAN understand that the world is not on fire.
Fixes: #16244 (hopefully)
=> lib, tests: fix some b0rked tests, then fix TSAN warnings

isisd/isis_adjacency.c, isisd/isis_lsp.c, tests/topotests/isis_topo1/test_isis_topo1.py
1. The `lsp_update_data()` function will check for the presence of the `ISIS_TLV_DYNAMIC_HOSTNAME `in the LSP, and then call `isis_dynhn_insert()` to add a hostname entry corresponding to the LSP ID. However, when the `ISIS_TLV_DYNAMIC_HOSTNAME `is not present in the LSP, the hostname entry corresponding to the LSP ID should also be deleted.
2. The command “show isis neighbor” invokes `isis_adj_name()` to display the System ID or hostname, but it does not check the `area->dynhostname` flag.
=> isisd: The neighbor entry still displays the deleted hostname of the neighbor.

tests/topotests/bgp_duplicate_nexthop/test_bgp_duplicate_nexthop.py, tests/topotests/bgp_peer_type_multipath_relax/r1/prefix1-eBGP-confed.json, tests/topotests/bgp_peer_type_multipath_relax/r1/prefix1-eBGP-iBGP.json, tests/topotests/lib/common_check.py, zebra/zebra_dplane.c, zebra/zebra_rib.c
For route updates:
- add duplicate flag wherever needed
- remove the fib flag when duplicate is present
=> Duplicate fib proposal

ripd/ripd.c, ripngd/ripngd.c, tests/topotests/rip_topo1/r1/show_ip_rip.ref, tests/topotests/rip_topo1/r2/show_ip_rip.ref, tests/topotests/rip_topo1/r3/show_ip_rip.ref, tests/topotests/ripng_topo1/r1/show_ipv6_ripng.ref, tests/topotests/ripng_topo1/r2/show_ipv6_ripng.ref, tests/topotests/ripng_topo1/r3/show_ipv6_ripng.ref
Both rip and ripng can import routes from other protocols, e.g. ISIS. But their header doesn't list the description for these abbreviations.
Let `show ip rip` (and `show ipv6 ripng`) uses the common header.
Before:
```
Codes: R - RIP, C - connected, S - Static, O - OSPF, B - BGP
Sub-codes:
(n) - normal, (s) - static, (d) - default, (r) - redistribute,
(i) - interface
```
After:
```
Codes: K - kernel route, C - connected, L - local, S - static,
R - RIP, O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
f - OpenFabric, t - Table-Direct,
Sub-codes:
(n) - normal, (s) - static, (d) - default, (r) - redistribute,
(i) - interface
```
=> ripd/ripngd: use common header for display command

lib/hash.h, lib/linklist.h, lib/openbsd-queue.h, lib/openbsd-tree.h
Put some verbiage in place to warn people that we
are actively discouraging new development that uses an older data structure.
=> lib: Discourage usage of deprecated data structures

tests/topotests/ospf_metric_propagation/r1/frr.conf, tests/topotests/ospf_metric_propagation/r1/show_ip_route-1.json, tests/topotests/ospf_metric_propagation/r1/show_ip_route-2.json, tests/topotests/ospf_metric_propagation/r1/show_ip_route-3.json, tests/topotests/ospf_metric_propagation/r1/show_ip_route-4.json, tests/topotests/ospf_metric_propagation/r1/show_ip_route-5.json, tests/topotests/ospf_metric_propagation/r1/show_ip_route-6.json, tests/topotests/ospf_metric_propagation/r2/frr.conf, tests/topotests/ospf_metric_propagation/r3/frr.conf, tests/topotests/ospf_metric_propagation/r4/frr.conf, tests/topotests/ospf_metric_propagation/ra/frr.conf, tests/topotests/ospf_metric_propagation/rb/frr.conf, tests/topotests/ospf_metric_propagation/rc/frr.conf, tests/topotests/ospf_metric_propagation/test_ospf_metric_propagation.py
This tests started failing more frequently on Debian ARM recently. Could be just a slow convergence issue, so I'm giving it extra time to converge. I may need to do the same with other test cases in the file, but will wait and see the result of changing this one only.
=> tests: tweak timers to avoid frequent failures on slow CI hardware

zebra/interface.c
During internal testing, when the following sequence is followed, two non default vrfs end up pointing to the same table-id
- Initially vrf201 has table id 1002
- ip link add dev vrf202 type vrf table 1002
- ip link set dev vrf202 up
- ip link set dev <intrerface> master vrf202
This will ideally lead to zebra exit since this is a misconfiguration as expected.
However if we perform a restart frr.service at this point, we end up having two vrfs pointing to same table-id and bad things can happen.
root@mlx-3700-20:mgmt:/var/log/frr# sudo vtysh -c "sh vrf" vrf mgmt id 37 table 1001
vrf vrf201 id 46 table 1002
vrf vrf202 id 59 table 1002 >>>>
Fix: in all cases of misconfiguration, exit zebra as expected.
Ticket :#3970414
=> zebra: Fix to avoid two Vrfs with same table ids

staticd/static_zebra.c
Use `vtysh` with this input file:
```
ip route A nh1
ip route A nh2
ip route B nh1
ip route B nh2
```
When running "ip route B" with "nh1" and "nh2", the procedure maybe is: 
1) Create the two nexthops: "nh1" and "nh2".
2) Register "nh1" with `static_zebra_nht_register()`, then the states of both
"nh1" and "nht2" are set to "STATIC_SENT_TO_ZEBRA".
3) Register "nh2" with `static_zebra_nht_register()`, then only the routes with
nexthop of "STATIC_START" will be sent to zebra.
So, send the routes with the nexthop of "STATIC_SENT_TO_ZEBRA" to zebra.
=> staticd: fix missing static routes

isisd/isis_spf.c
1. When the root IS regenerates an LSP, it calls `lsp_build() -> lsp_clear_data()` to free the TLV memory of the first fragment and all other fragments. If the number of fragments in the regenerated LSP decreases or if no fragmentation is needed, the extra LSP fragments are not immediately deleted. Instead,` lsp_seqno_update() -> lsp_purge()` is called to set the remaining time to zero and start aging, while also notifying other IS nodes to age these fragments. `lsp_purge()` usually does not reset `lsp->hdr.seqno` to zero because the LSP might recover during the aging process.
2. When other IS nodes receive an LSP, they always call `process_lsp() -> isis_unpack_tlvs()` to allocate TLV memory for the LSP. This does not differentiate whether the received LSP has a remaining lifetime of …
=> isisd: fix crash when calculating the neighbor spanning tree based on the fragmented LSP

bgpd/bgp_vty.c, tests/topotests/bgp_vrf_different_asn/r1/frr.conf, tests/topotests/bgp_vrf_different_asn/test_bgp_vrf_different_asn.py
Closes https://github.com/FRRouting/frr/issues/16355
=> bgpd: Mark VRF instance as auto created if import vrf is configured for this instance

bgpd/bgp_evpn.c, bgpd/bgpd.c
Author: Rajasekar Raja <rajasekarr@nvidia.com>
Date:   Wed Jul 10 20:17:14 2024 -0700
bgpd: backpressure - Improve debuggability
Improve debuggability in backpressure code.
Ticket :#3980988
Signed-off-by: Rajasekar Raja <rajasekarr@nvidia.com>
Author: Rajasekar Raja <rajasekarr@nvidia.com>
Date:   Wed Jul 10 16:46:29 2024 -0700
bgpd: backpressure - fix to properly remove dest for bgp under deletion
In case of imported routes (L3vni/vrf leaks), when a bgp instance is
being deleted, the peer->bgp comparision with the incoming bgp to remove
the dest from the pending fifo is wrong. This can lead to the fifo
having stale entries resulting in crash.
Two changes are done here.
- Instead of pop/push items in list if the struct bgp doesnt match,
simply iterate the list and remove the expected …
=> bgpd: backpressure - fix to properly remove dest for bgp under deletion

lib/libfrr.h, ospfd/ospf_main.c
In the "2x2 matrix" of these, I accidentally edited "row-wise" when I should've edited "column-wise"...  *sigh*
Reported-by: @rbfnet
Fixes: #16349
Fixes: 110945ba0d2 ("ospfd: fix GR state location")
=> ospfd: fix state location mixup

bfdd/bfd.c, bfdd/bfd.h, bfdd/bfd_packet.c
=> bfdd: changes for code maintainability

doc/user/pim.rst, doc/user/pimv6.rst, lib/command.h, pimd/pim6_cmd.c, pimd/pim_addr.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_instance.c, pimd/pim_msdp.c, pimd/pim_msdp.h, pimd/pim_nb.h, pimd/pim_rp.c, pimd/pim_rp.h, pimd/pim_vty.c, tools/frr-reload.py, vtysh/vtysh.c, vtysh/vtysh_config.c
Added new 'router pim[6] [vrf NAME]' config node.
Moved all existing global/vrf PIM configs to the new subnode and the existing configuration was set to be hidden and deprecated.
Both versions of the configuration still work together for the time being until they can be safely removed.
PIM now always writes out configuration in the "router pim" syntax so ,in order to support frr-reload, the JSON based configuration in the PIM topotests also needs to generate configuration in the same syntax.
Config file style tests are left in the global pim configuration syntax for now as a test of backwards compatibility.
Fixes #16196
=> Router pim config

nhrpd/nhrp_vty.c
Freeing auth-token does not set nifp->auth_token to NULL. Explicitly set auth_token to NULL when deleting auth config in order for write config logic to succeed.
Fix bug #16359
=> nhrpd: Fixes auth config change bug

tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
These failing tests are hard to track down. Added numbering to each assert to easily tell where the test fails.
=> tests: OSPFv3 hello tests investigation, make assert output unique

configure.ac
Configure is displaying the run state directory but not the local state directory.
> FRRouting configuration
> ------------------------------
> state file directory    : /usr/var/run/frr
> config file directory   : /etc/frr
Display the local state directory as well.
> local state file dir    : /usr/var/lib/frr
> run state file dir      : /usr/var/run/frr
> config file directory   : /etc/frr
=> build: display local state dir configuration

nhrpd/nhrp_peer.c
The nhrp_peer_forward() routine was not explicitly handling the Authentication Extension in the switch statement and instead fell through to the default case which checked whether this was an unhandled Compulsory extension and errored out, never forwarding the Resolution Request.
Closes #16371
=> nhrpd: Fixes auth no redirect bug

yang/frr-eigrpd.yang
=> yang: Corrected range in yang file

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/test_bgp_srv6l3vpn_to_bgp_vrf2.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py
Fix a bunch of warnings observed when running the `bgp_srv6l3vpn_to_bgp_vrf*` topotests.
```
/media/workspace/frr/tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r1/setup.sh: No such file or directory
/media/workspace/frr/tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r2/setup.sh: No such file or directory
/media/workspace/frr/tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/ce1/setup.sh: No such file or directory
/media/workspace/frr/tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/ce2/setup.sh: No such file or directory
...
```
=> tests: Fix topotest warnings

tests/topotests/bgp_evpn_rt5/r1/bgpd.conf, tests/topotests/bgp_evpn_rt5/r1/zebra.conf, tests/topotests/bgp_evpn_rt5/r2/bgpd.conf, tests/topotests/bgp_evpn_rt5/r2/zebra.conf, tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py, zebra/zebra_vxlan.c
In L3 BGP-EVPN, if there are both IPv4 and IPv6 routes in the VPN, zebra maintains two instances of `struct zebra_neigh` object: one with IPv4 address of the nexthop, and another with IPv6 address that is an IPv4 mapped to IPv6, but only one intance of `struct zebra_mac` object, that contains a list of nexthop addresses that use this mac.
The code in `zebra_vxlan` module uses the fact that the list is empty as the indication that the `zebra_mac` object is unused, and needs to be dropped. However, preexisting code used nexthop address converted to IPv4 notation for the element of this list. As a result, when two `zebra_neigh` objects, one IPv4 and one IPv6-mapped-IPv4 were linked to the `zebra_mac` object, only one element was added to the list. Consequently, when one of the two …
=> zebra: evpn: not coerce VTEP IP to IPv4 in nh_list

lib/vty.c, mgmtd/mgmt_txn.c
Additionally, print `errmsg_if_any` in successful debug messages if non-NULL.
fixes #16386 #16043
=> lib: move non-error from __log_err to __dbg

pimd/pim_nb_config.c
Fix the following crash when pim options are (un)configured on an non-existent interface.
> r1(config)# int fgljdsf
> r1(config-if)# no ip pim unicast-bsm
> vtysh: error reading from pimd: Connection reset by peer (104)Warning: closing connection to pimd because of an I/O error!
> #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f70c8f32249 in core_handler (signo=11, siginfo=0x7fffff88e4f0, context=0x7fffff88e3c0) at lib/sigevent.c:258
> #3  0x0000556cfdd9b16d in lib_interface_pim_address_family_unicast_bsm_modify (args=0x7fffff88f130) at pimd/pim_nb_config.c:1910
> #4  0x00007f70c8efdcb5 in nb_callback_modify (context=0x556d00032b60, nb_node=0x556cffeeb9b0, event=NB_EV_APPLY, dnode=0x556d00031670, resource=0x556d00032b48, …
=> pimd: fix crash on non-existent interface

bgpd/bgp_evpn.c, bgpd/bgpd.c
Coverity complains there is a use after free (1598495 and 1598496) At this point, most likely dest->refcount cannot go 1 and free up the dest, but there might be some code path where this can happen.
Fixing this with a simple order change (no harm fix).
Ticket :#4001204
=> bgpd: backpressure - Avoid use after free

tests/topotests/isis_tilfa_topo1/rt5/step10/show_ip_route.ref, zebra/zebra_nhg.c, zebra/zebra_vty.c
Current code when a link is set down is to just mark the nexthop group as not properly setup.  Leaving situations where when an interface goes down and show output is entered we see incorrect state.  This is true for anything that would be checking those flags at that point in time.
Modify the interface down nexthop group code to notice the nexthops appropriately ( and I mean set the appropriate flags ) and to allow a `show ip route` command to actually display what is going on with the nexthops.
eva# show ip route 1.0.0.0
Routing entry for 1.0.0.0/32
Known via "sharp", distance 150, metric 0, best
Last update 00:00:06 ago
* 192.168.44.33, via dummy1, weight 1
* 192.168.45.33, via dummy2, weight 1
sharpd@eva:~/frr1$ sudo ip link set dummy2 down
eva# show ip route 1.0.0.0
Routing entry for …
=> zebra: Properly note that a nhg's nexthop has gone down

ospfd/ospf_ldp_sync.c, tests/topotests/ldp_sync_ospf_topo1/r2/show_ospf_ldp_sync.ref, tests/topotests/ldp_sync_ospf_topo1/r2/show_ospf_ldp_sync_r1_eth1_shutdown.ref, tests/topotests/ldp_sync_ospf_topo1/r2/show_ospf_ldp_sync_r2_eth1_shutdown.ref, tests/topotests/ldp_sync_ospf_topo1/r3/show_ospf_ldp_sync.ref, tests/topotests/ldp_sync_ospf_topo1/r3/show_ospf_ldp_sync_r1_eth1_shutdown.ref, tests/topotests/ldp_sync_ospf_topo1/r3/show_ospf_ldp_sync_r2_eth1_shutdown.ref
When enabling "mpls ldp-sync" under "router ospf" ospfd configures SET_FLAG(ldp_sync_info->flags, LDP_SYNC_FLAG_IF_CONFIG) so internally knowing that the ldp-sync feature is enabled. However the flag is not cleared when turning of the feature using "nompls ldp-sync"!
Closes #16375
Please backup this to stable/10.0 and stable/9.1
=> ospfd: fix internal ldp-sync state flags when feature is disabled

bgpd/bgp_mplsvpn.c, bgpd/bgp_zebra.c
VRF-label association drops when the VRF loopback goes down, however, it does not return once the interface is enabled again.
Logs show that when VRF loopback goes down, a label drop message is sent to zebra and immediately resent label installation to zebra: 2024/07/16 13:26:29 BGP: [RVJ1J-J2T22] ifp down r1-cust1 vrf id 7 2024/07/16 13:26:29 BGP: [WA2QY-06STJ] vpn_leak_zebra_vrf_label_withdraw: deleting label for vrf VRF r1-cust1 (id=7) 2024/07/16 13:26:30 BGP: [S82AC-6YAC8] vpn_leak_zebra_vrf_label_update: vrf VRF r1-cust1: afi IPv4: setting label 80 for vrf id 7
Since the interface is down, the netlink message is not send to kernel. Once the interface comes back, zebra ignore the installation assuming the label is already seen.
To fix this, add a check for the interface status before …
=> bgpd: fix label lost when vrf loopback comes back

zebra/zebra_dplane.c
The nexthop updates counter value was never displayed. Add it.
> # show zebra dplane
> Zebra dataplane:
> Route updates:            7673010
> Route update errors:      0
> Nexthop updates:          1100
> Nexthop update errors:    0
> [..]
=> zebra: add nexthop counter to 'show zebra dplane' command

yang/ietf/frr-deviations-ietf-routing.yang
Added missed prefix to the frr-deviations-ietf-routing yang file
Below warning is seen at frr-deviations-ietf-routing.yang file while applying pyang.
**"warning: "ietf-rip" looks like a prefix but is not defined"**
Corrected warning by including the module
=> yang: Added missed prefix to the frr-deviations-ietf-routing yang file

lib/libfrr.c, lib/libfrr.h, lib/vty.c
Correct FRR startup counts on a daemon's vty socket to be open when the parent process exits. The parent process waits for `frr_check_detach()` to be called by the child before exiting. The problem is when the `FRR_MANUAL_VTY_START` flag is set the vty socket was not opened but `frr_check_detach()` was called anyway.
Instead add a bool option for `frr_check_detach()` to be called when the socket is opened with `frr_vty_serv_start()`, and do so when "manually" calling said function (i.e., when FRR_MANUAL_VTY_START is set).
The `FRR_MANUAL_VTY_START` flag is only set by mgmtd. The reason we wait to open the vty socket is so that mgmtd can parse the various daemon specific config files it has taken over, after the event loop has started, but before we receive any possible new config from …
=> lib: mgmtd: fix too early daemon detach of mgmtd

isisd/isis_misc.c, isisd/isisd.c, isisd/isisd.h, tests/isisd/test_isis_spf.c
The command "show isis topology" calls `print_sys_hostname()` to display the system ID or hostname, but it does not check the `area->dynhostname` flag.
=> isisd: Even after configuring "no hostname dynamic", the topology still displays the hostname.

doc/developer/conf.py, doc/manpages/conf.py, doc/user/conf.py, python/firstheader.py, python/makefile.py
When using a regex (or anything that uses `\?` escapes) in python, raw strings (`r"content"`) should be used so python doesn't consume the escapes itself.  Otherwise we get either broken behavior and/or `SyntaxWarning: invalid escape sequence '\['`
=> build: fix a few python string escape warnings

bgpd/bgp_evpn.c, bgpd/bgp_zebra.c
The return value of evpn_route_select_install is ignored in all cases except during vni route table install/uninstall and based on the returned value, an error is logged. Fixing this.
Also, log error for evpn in case route install to zebra fails.
Ticket :#3992392
No functionality issue here. Just making sure we don't have dead code and log error
=> bgpd: backpressure - fix ret value and log err for evpn

isisd/isis_nb_config.c, isisd/isis_te.c, isisd/isis_te.h, lib/flex_algo.c, lib/flex_algo.h
When an color affinity is set on an interface before configuring the flex-algorithm, the ASLA (Application Specific Link-Attribute) sub-TLV is not build. Flex-algo fails to build the paths when a affinity constraint is required because of the lacking of information contained in ASLA. There are no problems when the configuration order is reversed. For example:
> affinity-map red bit-position 1
>
> interface eth2
>  link-params
>   affinity red
>
> router isis 1
>  mpls-te on
>  flex-algo 129
>   dataplane sr-mpls
>   advertise-definition
>   affinity include-any green
In isis_link_params_update_asla(), the ASLA sub-TLV is not build when the list of flex-algos is empty.
Update ASLA when the first flex-algorithm is configured.
Fixes: 893882ee20 ("isisd: add isis flex-algo configuration …
=> isisd: fix building flex-algo asla at init

isisd/isis_lsp.c, isisd/isis_lsp.h, isisd/isis_te.c, isisd/isis_te.h, lib/link_state.c, lib/link_state.h
According to draft-ietf-lsr-isis-srv6-extensions draft, the End SID should be available in link state prefix information. Add the SID information in the link state prefix.
I have however a problem. how to test it .. I tried , but without success:
Observed
```
r3# show isis database  detail r3.00-00
Area TE:
IS-IS Level-2 link-state database:
LSP ID                  PduLen  SeqNumber   Chksum  Holdtime  ATT/P/OL
r3.00-00             *    628   0x0000000a  0xf151     326    0/0/0
[..]
MT Reachability: 0000.0000.0002.00 (Metric: 10) ipv6-unicast
Admin Group: 0x00000020
Bit positions: 5
Local Interface IPv6 Address(es): 2001:db8:3::3:3
Remote Interface IPv6 Address(es): 2001:db8:3::3:2
[..]
Adjacency-SID: 15001, Weight: 0, Flags: F:1 B:0, V:1, L:1, S:0, P:0
SRv6 End.X SID: fc00:0:3:1::, …
```
=> isis, lib: add isis srv6 end sid to ls_prefix

tests/topotests/bgp_duplicate_nexthop/r1/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r3/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r5/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/r6/bgpd.conf, tests/topotests/bgp_duplicate_nexthop/test_bgp_duplicate_nexthop.py, tests/topotests/bgp_vpnv4_per_nexthop_label/test_bgp_vpnv4_per_nexthop_label.py, tests/topotests/bgp_vpnv6_per_nexthop_label/test_bgp_vpnv6_per_nexthop_label.py
See individual commits.  These should help get the vtysh changes in.
=> Test fixes

tests/topotests/lib/bgprib.py
Timing changes in vtysh (PR 16427) affected test results. This change adds retries and timeout to test functions in tests/topotests/lib/bgprib.py (with default values and additional parameters allowing callers to override).
=> tests: topotests/lib: add wait to RequireVpnRoutes, RequireUnicastRoutes

nhrpd/nhrp_peer.c
When an NHRP server was forwarding a message, it was copying all extensions from the originally received packet. The authentication extension must be regenerated hop by hop per RFC2332. The copied auth extension had an incorrect length. This fix checks for the auth extension when copying extensions and omits the original packet auth and instead regenerates a new auth extension.
Fix bug #16466
=> nhrpd: fixes duplicate auth extension

zebra/zebra_rib.c
It is possible that right before an upper level protocol dies or is killed routes would be installed into zebra.  These routes could be on the Meta-Q for early route-processing.  Leaving us with a situation where the client is removed, and all it's routes that are in the rib at that time, and then after that the MetaQ is run and the routes are reprocessed leaving routes from an upper level daemon post daemon going away from zebra's perspective.  These routes will be abandoned.
=> zebra: Fix removal of routes on MetaQ when client goes down

babeld/babel_interface.c
babel: Added null check after retrieving babel_ifp
Asserting the further instructions when the babel interface pointer is NULL
=> babel: Added null check after retrieving babel_ifp

doc/developer/topotests.rst
Add some hints for developers about how to reproduce failure conditions in the test.
=> doc: Add some topotest documentation about how to reproduce failures

bgpd/bgp_attr.c
```
0 0xb50b9f898028 in __sanitizer_print_stack_trace (/home/ubuntu/frr-public/frr_public_private-libfuzzer/bgpd/.libs/bgpd+0x368028) (BuildId: 3292703ed7958b20076550c967f879db8dc27ca7)
1 0xb50b9f7ed8e4 in fuzzer::PrintStackTrace() (/home/ubuntu/frr-public/frr_public_private-libfuzzer/bgpd/.libs/bgpd+0x2bd8e4) (BuildId: 3292703ed7958b20076550c967f879db8dc27ca7)
2 0xb50b9f7d4d9c in fuzzer::Fuzzer::CrashCallback() (/home/ubuntu/frr-public/frr_public_private-libfuzzer/bgpd/.libs/bgpd+0x2a4d9c) (BuildId: 3292703ed7958b20076550c967f879db8dc27ca7)
3 0xe0d12d7469cc  (linux-vdso.so.1+0x9cc) (BuildId: 1a77697e9d723fe22246cfd7641b140c427b7e11)
4 0xe0d12c88f1fc in __pthread_kill_implementation nptl/pthread_kill.c:43:17
5 0xe0d12c84a678 in gsignal signal/../sysdeps/posix/raise.c:26:13
6 …
```
=> bgpd: Check the actual remaining stream length before taking TLV value

bgpd/bgp_fsm.c, bgpd/bgpd.c, bgpd/bgpd.h
It might cause this use-after-free:
```
==6523==ERROR: AddressSanitizer: heap-use-after-free on address 0x60300058d720 at pc 0x55f3ab62ab1f bp 0x7ffe5b95a0d0 sp 0x7ffe5b95a0c8
READ of size 8 at 0x60300058d720 thread T0
#0 0x55f3ab62ab1e in bgp_gr_update_mode_of_all_peers bgpd/bgp_fsm.c:2729
#1 0x55f3ab62ab1e in bgp_gr_update_all bgpd/bgp_fsm.c:2779
#2 0x55f3ab73557e in bgp_inst_gr_config_vty bgpd/bgp_vty.c:3037
#3 0x55f3ab74db69 in bgp_graceful_restart bgpd/bgp_vty.c:3130
#4 0x7fc5539a9584 in cmd_execute_command_real lib/command.c:1002
#5 0x7fc5539a98a3 in cmd_execute_command lib/command.c:1061
#6 0x7fc5539a9dcf in cmd_execute lib/command.c:1227
#7 0x7fc553ae493f in vty_command lib/vty.c:616
#8 0x7fc553ae4e92 in vty_execute lib/vty.c:1379
#9 0x7fc553aedd34 in vtysh_read lib/vty.c:2374
#10 …
```
=> bgpd: Use bgp_session_reset_safe() for GR update all peers

tests/topotests/mgmt_rpc/test_rpc.py
Vtysh has been improved to startup very quickly this exposed a race in this test, where the `clear ip rip...` command ran before the test client that handles it had finished connecting to mgmtd. Add a retried check for the test client being connected before issuing the `clear ip rip ...` test command.
=> tests: wait for test client to connect before running test

lib/distribute.c
The destroy callback must be executed only once on APPLY stage.
Fixes #16528
=> lib: fix crash on distribute-list delete

ripd/rip_cli.c, ripd/rip_nb.c
CLI show callbacks should be defined in frr_ripd_cli_info instead of frr_ripd_info, because only the former is loaded by mgmtd and only its callbacks are getting called for config output.
Fixes #16527
=> ripd: fix show run output for distribute-list

lib/nexthop.c, lib/srv6.c, lib/srv6.h
Some srv6 behaviors have a context attached that is visible if no json is requested:
> # show ipv6 route
> [..]
> B>* 2001:db8:1:1:100::/128 [20/0] is directly connected, vrf10, seg6local End.DT6 table 10, weight 1, 00:00:14
> B>* 2001:db8:1:1:200::/128 [20/0] is directly connected, vrf20, seg6local End.DT6 table 20, weight 1, 00:00:14
>
The json does not dump this attribute:
> # show ipv6 route 2001:db8:1:1:100::/128 json
> [..]
>      "nexthops":[
>        {
>          "flags":3,
>          "fib":true,
>          "directlyConnected":true,
>          "interfaceIndex":6,
>          "interfaceName":"vrf10",
>          "active":true,
>          "weight":1,
>          "seg6local":{
>            "action":"End.DT6"
>          },
>        }
>
Add the json support for this.
>      "nexthops":[
> …
=> lib: add seg6localContext json attribute in nexthop information

lib/yang.c
There will be a LYD_NEW_PATH_OUTPUT undeclared error if using the latest libyang V3.x version.  It was reported in #16287 before.
I fixed the error to support that. And it's compatible with old version.
> lib/yang.c: In function ‘yang_dnode_rpc_output_add’:
lib/yang.c:674:7: error: ‘LYD_NEW_PATH_OUTPUT’ undeclared (first use in this function); did you mean ‘LYD_NEW_VAL_OUTPUT’?
674 | LYD_NEW_PATH_OUTPUT | LYD_NEW_PATH_UPDATE, NULL);
| ^~~~~~~~~~~~~~~~~~~
| LYD_NEW_VAL_OUTPUT
lib/yang.c:674:7: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:10793: lib/yang.lo] Error 1
make[1]: Leaving directory '/opt/frr'
make: *** [Makefile:6576: all] Error 2
=> Fix LYD_NEW_PATH_OUTPUT issue to support libyang v3.x

mgmtd/mgmt_ds.c
When mgmt reads configuration from file, it shouldn't add implicit state data to the candidate datastore. Configuration datastores like candidate should never store state, otherwise they fail validation.
Fixes #15814
=> mgmtd: don't add implicit state data when reading config from file

lib/distribute.c
When a whole distribute-list is deleted (can be done only using API), all its children must be cleaned up manually.
Fixes #16538
=> lib: fix distribute-list deletion

lib/event.c, lib/libfrr.c, lib/libfrr.h
vtysh will print out the `stupidly large FD limit` upon every run of the program if the ulimit is set stupidly large.  Prevent this from being displayed for vtysh.
Fixes: #16516
=> lib: Don't print warning if not a daemon

zebra/zebra_nhg.c
The function zebra_nhg_hash_equal is only used
as a hash function for storage of NHG's and retrieval. If you have say two nhg's:
31 (25/26)
32 (25/26)
This function would return them as being equal.  Which of course leads to the problem when you attempt to hash_release 32 but release 31 from the hash.  Then later when you attempt to do hash comparisons 32 has actually been freed leaving to use after free situations and shit goes down hill fast.
This hash is only used as part of the hash comparison function for nexthop group storage.  Since this is so let's always return the 31/32 nhg's are not equal at all.
We possibly have a different problem where we are creating 31 and 32 ( when 31 should have just been used instead of 32 ) but we need to prevent any type of hash release problem at …
=> zebra: Ensure non-equal id's are not same nhg's

bgpd/bgp_mplsvpn_snmp.c, bgpd/bgp_snmp.c, bgpd/bgpd.h, doc/user/snmptrap.rst
Add a trap command to disable or enable the traps defined by the RFC4382.
=> bgpd: add bgp snmp traps rfc4382 command

mgmtd/.gitignore
This program, mgmtd_testc, is built with the
--enable-mgmtd-test-be-client configure option
but it is not .gitignore'd.  Let's fix that
=> mgmtd: Add to .gitignore for mgmtd_testc program

isisd/isis_adjacency.c, isisd/isis_adjacency.h, isisd/isis_pdu.c
The adj_process_threeway() api may call the adj_state_change() api, which may delete the adj struct being examined. Change the signature so that callers pass a ptr-to-ptr so that they will see that deletion.
Hoping that this will fix the recent asan report:
Fixes #16543
=> isisd: fix memory handling in isis_adj_process_threeway()

bgpd/bgp_nht.c, bgpd/bgp_updgrp_packet.c, tests/topotests/bgp_nexthop_mp_ipv4_6/r2/bgp_ipv6_step2.json, tests/topotests/bgp_nexthop_mp_ipv4_6/r3/bgp_ipv6_step2.json
fixes for ipv4 mapped ipv6 address. See individual commit logs
=> bgpd: fixes for ipv4 mapped ipv6 address

doc/developer/topotests.rst, tests/topotests/lib/topotest.py
E.g.:
```
for _, (rname, router) in enumerate(router_list.items(), 1):
router.load_frr_config(os.path.join(CWD, "{}/frr.conf".format(rname)))
```
=> doc: Document on how to start specific daemons with unified config in topotests

lib/agentx.c
The events list is storing a `struct event *` allocated as a MTYPE_TMP pointer, on shutdown ensure that it is properly free'd up.
=> lib: Fix memory leak in snmp on shutdown

pathd/pathd.c
Just some code to cleanup the shutdown memory leaks that are in pathd.
=> pathd: Cleanup shutdown memory leaks

doc/user/pim.rst
FIx a few style issues and expanded descriptions in the PIM user docs.
=> doc: Fix up pim user docs.

doc/developer/topotests.rst, doc/developer/workflow.rst
In order to run the XXXX Sanitizers over the code as a developer modern linux distro's require a specific sysctl.  Let's document that so that people are aware of it.
=> doc: Add doc to show sysctl setting for Sanitizers

bgpd/bgp_vty.c
Fixes: https://github.com/FRRouting/frr/issues/16577
=> bgpd: Avoid use-after-free when doing `no router bgp` with auto created instances

bgpd/bgp_vty.c
json_peers is allocated in the above if statement block for json but is not freed in this code path.  Noticed by running Address Sanitizer.
=> bgpd: Free up non-freed json memory on function return

tests/topotests/all_protocol_startup/test_all_protocol_startup.py
The all_protocol_startup topotest needs to allow for some delay between configuring nexthop-groups and their installation. Add some wait periods in a couple of nhg test cases.
This should (may) fix several of the failures in this test suite that we've seen recently.
=> tests: add retries to nhg tests in all_proto_startup

bgpd/bgp_route.c
A crash happens when executing the following command:
> ubuntu2204hwe# conf
> ubuntu2204hwe(config)# router bgp 65500
> ubuntu2204hwe(config-router)#  !
> ubuntu2204hwe(config-router)#  address-family ipv4 unicast
> ubuntu2204hwe(config-router-af)#   sid vpn export auto
> ubuntu2204hwe(config-router-af)#  exit-address-family
> ubuntu2204hwe(config-router)#  !
> ubuntu2204hwe(config-router)#  address-family ipv4 vpn
> ubuntu2204hwe(config-router-af)#   network 4.4.4.4/32 rd 55:55 label 556
> ubuntu2204hwe(config-router-af)#   network 5.5.5.5/32 rd 662:33 label 232
> ubuntu2204hwe(config-router-af)#  exit-address-family
> ubuntu2204hwe(config-router)# exit
> ubuntu2204hwe(config)# !
> ubuntu2204hwe(config)# no router bgp
The crash analysis indicates a memory item has been freed.
> #6 …
=> bgpd: fix memory type for static->prd_pretty

tests/topotests/route_scale/scale_test_common.py
Upstream CI is frequently running into a situation where the routes are not being installed.  These routes
start at the beginning and suddenly in the middle
they start working properly.
D   1.0.15.183/32 [150/0] via 192.168.0.1, r1-eth0 inactive, weight 1, 00:10:17
via 192.168.1.1, r1-eth1 inactive, weight 1, 00:10:17
D   1.0.15.184/32 [150/0] via 192.168.0.1, r1-eth0 inactive, weight 1, 00:10:17
via 192.168.1.1, r1-eth1 inactive, weight 1, 00:10:17
D   1.0.15.185/32 [150/0] via 192.168.0.1, r1-eth0 inactive, weight 1, 00:10:17
via 192.168.1.1, r1-eth1 inactive, weight 1, 00:10:17
D>* 1.0.15.186/32 [150/0] via 192.168.0.1, r1-eth0, weight 1, 00:10:17
*                       via 192.168.1.1, r1-eth1, weight 1, 00:10:17
D>* 1.0.15.187/32 [150/0] via 192.168.0.1, r1-eth0, weight 1, 00:10:17 …
=> tests: Fix route_scale startup issues

pimd/pim_iface.c
`gm_join_new()` will return NULL in the case of running out of socket/file resources.  Just add the check for it.
=> pimd: fix missing checking the return value for igmp command

ospfd/ospf_packet.c, ospfd/ospf_vty.c
Fix SA warnings in ospf_packet.c and ospf_vty.c. The former was
introduced by commit ed480148844259b7e9e30ed92489cdf44085457e.
Signed-off-by: Acee <aceelindem@gmail.com>
=>  ospfd: Fix SA warnings in ospf_packet.c and ospf_vty.c

lib/srv6.h, zebra/zebra_srv6_vty.c
Fixes the following compilation warnings:
```
error	15-Aug-2024 13:54:10	In file included from lib/bfd.c:16:
error	15-Aug-2024 13:54:10	In file included from ./lib/zclient.h:22:
error	15-Aug-2024 13:54:10	In file included from ./lib/nexthop.h:14:
error	15-Aug-2024 13:54:10	./lib/srv6.h:338:3: warning: Value stored to 'len' is never read [deadcode.DeadStores]
error	15-Aug-2024 13:54:10	                len += snprintf(str + len, size - len, " USP");
error	15-Aug-2024 13:54:10	                ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error	15-Aug-2024 13:54:10	./lib/srv6.h:343:3: warning: Value stored to 'len' is never read [deadcode.DeadStores]
error	15-Aug-2024 13:54:10	                len += snprintfrr(str + len, size - len, " nh6 %pI6", &ctx->nh6);
error	15-Aug-2024 13:54:10 …
```
=> lib, zebra: Fix a couple compilation warnings

lib/mgmt_be_client.c, mgmtd/mgmt_fe_adapter.c
Also an empty (thus non-replace) notify selectors message shouldn't clear the selectors, it should just do nothing.
=> mgmtd: fix a couple compilation warnings.

bgpd/bgp_attr.c, bgpd/bgp_route.c, ospfd/ospf_asbr.c, yang/ietf/ietf-bgp-types.yang, zebra/zebra_gr.c
=> Spelling in master 2

zebra/if_ioctl.c, zebra/if_sysctl.c, zebra/kernel_socket.c
Commit 605df8d44 zebra: Use zebra dplane for RTM link and addr broke loading of kernel routes at startup for configurations without netlink.
It rearranged the startup sequence in zebra_ns_enable() to pass via zebra_ns_startup_continue(), triggered through zebra_dplane_startup_stage() calls. However, it neglected to make these calls in the non-netlink code path. As a result zebra failed to load kernel routes at startup on platforms such as FreeBSD.
Insert these calls so we run through all of the expected startup stages.
=> zebra: fix loading kernel routes without netlink

bgpd/bgp_rpki.c
When 'no rpki' is requested and the rtrlib RPKI object was freed, bgpd is crashing.
RPKI is configured in VRF red.
> ip l set red down
> ip l del red
> printf 'conf\n vrf red\n no rpki' | vtysh
> Core was generated by `/usr/bin/bgpd -A 127.0.0.1 -M snmp -M rpki -M bmp'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:44
> 44	./nptl/pthread_kill.c: No such file or directory.
> [Current thread is 1 (Thread 0x7fb401f419c0 (LWP 190226))]
> (gdb) bt
> #0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:44
> #1  __pthread_kill_internal (signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:78
> #2 …
=> bgpd: fix crash at no rpki

doc/developer/conf.py, doc/user/conf.py
Read The Docs made some changes that require us to add some configuration in our build config files.
Read more:
https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> doc: update sphinx configs for RTD changes

bgpd/bgp_snmp_bgp4v2.c, tests/topotests/bgp_snmp_bgp4v2_notification/r2/bgpd.conf, tests/topotests/bgp_snmp_bgp4v2_notification/r2/snmpd.conf, tests/topotests/bgp_snmp_bgp4v2_notification/r2/zebra.conf, tests/topotests/bgp_snmp_bgp4v2_notification/rr/bgpd.conf, tests/topotests/bgp_snmp_bgp4v2_notification/rr/zebra.conf, tests/topotests/bgp_snmp_bgp4v2_notification/test_bgp_snmp_bgp4v2_notification.py
bgp crash on rt2 spotted when 2 commands
launched consequently:
```
T0: rr, config -> router bgp 65004 -> neighbor 192.168.12.2 password
8888
T1: rt2, snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.4.1.7336.4.2.1
T2: rt2 bgp crashed.
```
[EDIT1] -> reduce the configs as @ton31337 requested
config rt2-bgp:
---------------
```
!
debug bgp updates
!
router bgp 65002
no bgp network import-check
no bgp default ipv4-unicast
neighbor 192.168.12.4 remote-as external
neighbor 192.168.12.4 timers 1 3
neighbor 192.168.12.4 timers connect 1
!
neighbor 192.168.12.4 activate
neighbor 192.168.12.4 addpath-tx-all-paths
!
agentx
!
```
config rt2-snmpd:
```
agentAddress 127.0.0.1,[::1]
group public_group v1 public
group public_group …
```
=> bgpd: fix, do not access peer->notify.data when it is null

bgpd/bgp_rpki.c
When 'no rpki' is requested and the rtrlib RPKI object was freed, bgpd is crashing.
RPKI is configured in VRF red.
> ip l set red down
> ip l del red
> printf 'conf\n vrf red\n no rpki' | vtysh
> Core was generated by `/usr/bin/bgpd -A 127.0.0.1 -M snmp -M rpki -M bmp'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:44
> 44	./nptl/pthread_kill.c: No such file or directory.
> [Current thread is 1 (Thread 0x7fb401f419c0 (LWP 190226))]
> (gdb) bt
> #0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:44
> #1  __pthread_kill_internal (signo=11, threadid=140411103615424) at ./nptl/pthread_kill.c:78
> #2 …
=> bgpd: fix crash at no rpki (backport 9.1 and lower)

tests/topotests/lib/grpc-query.py
Don't print the sys.path when running grpc-query.py. Doing so was causing tests to fail.
=> tests: dont print sys.path when running grpc-query.py

tests/topotests/munet/mutini.py, tests/topotests/munet/native.py
Changes:
- mutini: handle possible missed zombie cleanup leading to test hangs
- mutini: also we avoid logging in the signal handler which was causing an exception.
=> tests: update munet to 0.14.10

babeld/kernel.c, babeld/route.c
=> Babel metric

zebra/zebra_netns_notify.c
musl only provides POSIX version of basename and it has also removed providing it via string.h header [1] which now results in compile errors with newer compilers e.g. clang-18
[1] https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7
=> Mimic GNU basename() API for non-glibc library e.g. musl

nhrpd/nhrp_route.c
The remote spoke always sends a 32 prefix length to a shortcut request. In the example, the remote spoke as the IP address 192.168.2.1/24.
spoke1# sh ip nhrp shortcut
Type     Prefix                   Via                      Identity
dynamic  192.168.2.1/32           10.255.255.2
Do not deal with local routes in nhrpd. Now:
spoke1# sh ip nhrp shortcut
Type     Prefix                   Via                      Identity
dynamic  192.168.2.0/24           10.255.255.2
Fixes: d4aa24ba7d ("*: Introduce Local Host Routes to FRR")
=> nhrpd: fix sending /32 shortcut

lib/nexthop.c, lib/nexthop.h, zebra/zebra_nhg.c
Currently FRR when it has two nexthop groups:
A
nexthop 1 weight 5
nexthop 2 weight 6
nexthop 3 weight 7
B
nexthop 1 weight 3
nexthop 2 weight 4
nexthop 3 weight 5
We end up with 5 singleton nexthops and two groups:
ID: 181818168 (sharp)
RefCnt: 1
Uptime: 00:04:52
VRF: default
Valid, Installed
Depends: (69) (70) (71)
via 192.168.119.1, enp13s0 (vrf default), weight 182
via 192.168.119.2, enp13s0 (vrf default), weight 218
via 192.168.119.3, enp13s0 (vrf default), weight 255
ID: 181818169 (sharp)
RefCnt: 1
Uptime: 00:02:08
VRF: default
Valid, Installed
Depends: (71) (127) (128)
via 192.168.119.1, enp13s0 (vrf default), weight 127
via 192.168.119.2, enp13s0 (vrf default), weight 170
via 192.168.119.3, enp13s0 (vrf default), weight 255
id 69 via 192.168.119.1 dev enp13s0 scope link proto 194 …
=> Reduce the number of Singleton objects when using weight for NHG's

bgpd/bgp_route.c
Some json attributes are missing for L3NHG values.
> PE1# show bgp vrf all detail
> [..]
> Instance vrf-purple:
> BGP table version is 1, local router ID is 27.3.0.85, vrf id 7
> Default local pref 100, local AS 65000
> BGP routing table entry for fe80::4620:ff:feff:ff01/128, version 1
> Paths: (1 available, best #1, vrf vrf-purple)
>   Not advertised to any peer
>   Imported from 10.30.30.30:5:[2]:[0]:[48]:[44:20:00:ff:ff:01]:[128]:[fe80::4620:ff:feff:ff01], VNI 4000  Local
>     ::ffff:a1e:1e1e (metric 20) from 10.30.30.30 (10.30.30.30) announce-nh-self
>       Origin IGP, localpref 100, valid, internal, best (First path received)
>       Extended Community: RT:65000:4000 ET:8
>       Last update: Thu Aug 22 18:23:38 2024
>
> Displayed 1 routes and 1 total paths
> PE1# show bgp vrf all …
=> bgpd: add json support for BGP L3NHG values

pimd/pim_zebra.c
ifp->info is not always set in PIM. So add a guard here to stop it from crashing when addresses are added to a non-PIM enabled interface and PIM zebra debugging is enabled.
=> pimd: Fix crash in pimd

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_evpn.c, bgpd/bgp_route.c
When parsing EVPN NLRIs, and an error occurred, do no forget to free the memory.
=> bgpd: Free epvn_overlay memory on error

tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_transit_router_topo3.py
Current code adds a new vlan interface, sets up ospf and pim on it and immediately starts shoving data down the pipes. This of course has the fun thing where the IGP and pim do not always come up in a nice neat manner and the test is looking for state from a nice neat come up, even though pim is `working` correctly it is not correct for what the test wants.
Modify the code to ensure that ospf is up and has propagated the route where it is needed as well as that pim neighbors have properly come up, then initiate the multicast streams and igmp reports.
=> tests: Allow convergence before adding multicast routes

zebra/zebra_nhg.c
Treat TYPE_IPV6 and TYPE_IPV6_IFINDEX nexthops the same way when processing v4 (RFC 5549) routes. TYPE_IPV6 nexthops were being treated as if the prefix was v6: that causes the zebra 'ip protocol' routemap to fail to match and prevents use of the routemap to set a v4 source address when installing the route. That in turn prevents locally-sourced traffic to the v4 prefix from working correctly.
=> zebra: be consistent about v6 nexthops for v4 routes

isisd/isis_te.c
Fix crash when flex-algo is configured and mpls-te is disabled.
> interface eth0
>  ip router isis 1
> !
> router isis 1
>  flex-algo 129
>   dataplane sr-mpls
>   advertise-definition
> #0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140486233631168) at ./nptl/pthread_kill.c:44
> #1  __pthread_kill_internal (signo=11, threadid=140486233631168) at ./nptl/pthread_kill.c:78
> #2  __GI___pthread_kill (threadid=140486233631168, signo=signo@entry=11) at ./nptl/pthread_kill.c:89
> #3  0x00007fc5802e9476 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
> #4  0x00007fc58076021f in core_handler (signo=11, siginfo=0x7ffd38d42470, context=0x7ffd38d42340) at lib/sigevent.c:248
> #5  <signal handler called>
> #6  0x000055c527f798c9 in isis_link_params_update_asla …
=> isisd: fix crash at flex-algo without mpls-te

bgpd/bgp_bmp.c, bgpd/bgp_evpn.c, bgpd/bgp_label.c, bgpd/bgp_mac.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_routemap.c, bgpd/bgp_rpki.c, bgpd/bgp_updgrp_packet.c, bgpd/bgp_zebra.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c, bgpd/rfapi/vnc_import_bgp.c
Fix static-analyser warnings with BGP labels:
> $ scan-build make -j12
> bgpd/bgp_updgrp_packet.c:819:10: warning: Access to field 'extra' results in a dereference of a null pointer (loaded from variable 'path') [core.NullDereference]
>                                                 ? &path->extra->labels->label[0]
>                                                    ^~~~~~~~~
=> bgpd: fix labels static-analyser

bgpd/bgp_bmp.c, bgpd/bgp_evpn.c, bgpd/bgp_label.c, bgpd/bgp_mac.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_routemap.c, bgpd/bgp_rpki.c, bgpd/bgp_updgrp_packet.c, bgpd/bgp_zebra.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c, bgpd/rfapi/vnc_import_bgp.c
Fix static-analyser warnings with BGP labels:
> $ scan-build make -j12
> bgpd/bgp_updgrp_packet.c:819:10: warning: Access to field 'extra' results in a dereference of a null pointer (loaded from variable 'path') [core.NullDereference]
>                                                 ? &path->extra->labels->label[0]
>                                                    ^~~~~~~~~
=> bgpd: fix labels static-analyser (backport #16655)

mgmtd/mgmt_be_adapter.c
Build is complaining:
build	27-Aug-2024 05:46:38	mgmtd/mgmt_be_adapter.c: In function ‘mgmt_register_client_xpath’: build	27-Aug-2024 05:46:38	mgmtd/mgmt_be_adapter.c:274:27: warning: ‘maps’ may be used uninitialized [-Wmaybe-uninitialized]
build	27-Aug-2024 05:46:38	  274 |         map = darr_append(*maps);
build	27-Aug-2024 05:46:38	      |                           ^
build	27-Aug-2024 05:46:38	mgmtd/mgmt_be_adapter.c:250:36: note: ‘maps’ was declared here
build	27-Aug-2024 05:46:38	  250 |         struct mgmt_be_xpath_map **maps, *map;
build	27-Aug-2024 05:46:38	      |                                    ^~~~
Let's make the compiler happy, even though there is no problem.
=> mgmtd: Ensure map is NULL

tests/topotests/zebra_multiple_connected/r1/ip_route_connected.json, tests/topotests/zebra_multiple_connected/r1/ip_route_kernel.json, tests/topotests/zebra_multiple_connected/test_zebra_multiple_connected.py, zebra/interface.c, zebra/rib.h, zebra/rt_netlink.c, zebra/zebra_rib.c
Allow kernel routes to be read in when they are created in linux.  Additionally treat the connected routes as connected.  This fixes one of the issues seen with NOPREFIXROUTE
=> Local connected

doc/developer/topotests.rst
The nhrp tests skip tests that do not have iptables installed. As such we have ended up with a situation where the nrhp test is now failing locally for me because I have iptables installed and if the CI system had iptables installed it would have detected the problem as well.
Let's document that iptables is needed to do testing.
=> doc: Update topotest doc to include iptables is needed

lib/vty.c, lib/vty.h, vtysh/vtysh.c, vtysh/vtysh.h
The output buffer vty->obuf is a linked list where each element is of 4KB.
Currently, when a huge sh command  like <show ip route json> is executed on a large scale, all the vty_outs are processed and the entire data is accumulated.
After the entire vty execution, vtysh_flush proceeses and puts this data in the socket (131KB at a time).
Problem here is the memory spike for such heavy duty show commands.
The fix here is to chunkify the output on VTY shell by flushing it intermediately for every 128 KB of output accumulated and free the memory allocated for the buffer data.
This way, we achieve ~25-30% reduction in the memory spike.
Fixes: #16498
Note: This is a continuation of MR #16498
=> lib: Memory spike reduction for sh cmds at scale

tests/topotests/bgp_default_originate/test_bgp_default_originate_topo1_3.py
This test was killing bgp on r1 and r2
and then immediately testing that the
default route transitioned.  Unfortunately
the test was written that under load the
system might be in a bad state.  Let's
modify the code to check for a bgp version
change and then that the bgp state has
come back up
=> tests: Fix bgp_default_originate_topo1_3

zebra/zebra_vty.c
Move the prefix lookup/comparison to outside the re loop and into the rn loop, since that is where the code should actually be.
=> zebra: Move prefix lookup to outside re loop

tests/topotests/bgp_suppress_fib/test_bgp_suppress_fib.py
Giving only 5 seconds to pass bgp data to peers on a heavily loaded system is a recipe for not having fun.  Add more time.
=> tests: Ensure bgp suppress fib has a chance to transmit data to peer

tests/topotests/ospf_netns_vrf/test_ospf_netns_vrf.py
Test fails:
test_func = partial(
topotest.router_json_cmp,
router,
"show ip ospf vrf {0}-ospf-cust1 json".format(rname),
expected,
)
_, diff = topotest.run_and_expect(test_func, None, count=10, wait=0.5)
assertmsg = '"{}" JSON output mismatches'.format(rname)
>           assert diff is None, assertmsg
E           AssertionError: "r1" JSON output mismatches
E           assert Generated JSON diff error report:
E
E             > $->r1-ospf-cust1->areas->0.0.0.0->nbrFullAdjacentCounter: output has element with value '1' but in expected it has value '2'
/home/sharpd/frr2/tests/topotests/ospf_netns_vrf/test_ospf_netns_vrf.py:239: AssertionError
Support bundle has this data:
r1# show ip ospf vrf all neighbor
% 2024/08/28 14:55:54.763
VRF Name: r1-ospf-cust1
Neighbor ID     Pri State           Up …
=> tests: ospf_netns_vrf should give more time for coming up

doc/developer/workflow.rst
Related: 
https://github.com/FRRouting/frr/pull/16635
https://github.com/FRRouting/frr/pull/16587
=> doc: Document the git revert flow

zebra/zebra_rib.c
There is a code path that could theoretically get you to a point where the ng->nexthop is a NULL value.
Let's just make sure the SA system believes that
cannot happen anymore.
=> zebra: Convince SA that the ng will always be valid

zebra/zebra_nhg.c, zebra/zebra_vty.c
=> Blackhole and afi

doc/user/zebra.rst, zebra/zebra_dplane.c, zebra/zebra_nhg.c, zebra/zebra_nhg.h, zebra/zebra_rib.c, zebra/zebra_vty.c
When creating these three types of routes, we are also implicitly creating a nexthop group that matches these routes.  If these routes already exist in the kernel using the old style of nexthops there is no need to immediately install these nexthops.  Make it so that they initially will `pretend` install and then when it is really needed install them.
=> No connected/local/kernel nexthops at first

bgpd/bgp_bmp.c, isisd/isis_mt.c, isisd/isis_spf.c, isisd/isis_sr.c, isisd/isis_srv6.c, lib/hash.c, lib/memory.c, lib/memory.h, lib/northbound_cli.c, lib/termtable.c, lib/termtable.h, pathd/path_cli.c, pimd/pim6_mld.c, pimd/pim_cmd_common.c, pimd/pim_rp.c, tests/lib/test_ttable.c, vrrpd/vrrp_vty.c, zebra/dplane_fpm_nl.c, zebra/zebra_mpls.c, zebra/zebra_vty.c
see individual commits but clean up some MTYPE_XXX stuff that needs to be better
=> Memory type stuff

bgpd/bgp_route.c
show bgp vrf afi unicast statistics json output is not return in json format for non exists vrf.
Fix:
Json output is formatted for non exists vrf cases.
Command supported:
```
show bgp vrf <VRFNAME> ipv4/ipv6 unicast statistics json
show bgp vrf <VRFNAME> l2vpn evpn statistics json
```
Before Fix:
```
leaf11#
leaf11# show bgp vrf test ipv4 unicast statistics json
View/Vrf test is unknown
leaf11#
leaf11# show bgp vrf test ipv6 unicast statistics json
View/Vrf test is unknown
leaf11#
leaf11# show bgp vrf default1 l2vpn evpn statistics json
View/Vrf default1 is unknown
leaf11#
```
After Fix:
```
leaf11#
leaf11# show bgp vrf test ipv4 unicast statistics json
{
"warning":"View/Vrf is unknown"
}
leaf11#
leaf11#
leaf11# show bgp vrf test ipv6 unicast statistics json
{
"warning":"View/Vrf is …
```
=> bgpd: fix proper json format for unicast statistics for non exists vrf

bgpd/bgp_evpn_vty.c, bgpd/bgp_route.c, bgpd/bgp_route.h
evpn has a concept of `local` tables where the evpn routes are actually converted into underlying routes/neighbor table entries( or vice versa ).  Then this local route is propagated to the global evpn l2vpn table and sent to the peers.  Certain show commands in evpn look
operate on the local table but make the output look like the data has not been sent to the peer.  This is confusing for the operator.  Modify the code
such that local tables get a `Local BGP table not advertised` in the place where the code talks about whom has received the data or not.
Example:
torm11# show bgp l2vpn evpn route vni 1000 mac 8a:a1:cc:73:a3:ac ip 45.0.0.5 BGP routing table entry for [2]:[0]:[48]:[8a:a1:cc:73:a3:ac]:[32]:[45.0.0.5] Paths: (2 available, best #2)
Local BGP table not advertised
Route …
=> bgpd: Ensure evpn local table display shows route send status

isisd/isis_te.c
If the link-params are set when the circuit not yet up, the link-params are never updated.
isis_link_params_update() is called from isis_circuit_up() but returns immediately because circuit->state != C_STATE_UP. circuit->state is updated in isis_csm_state_change after isis_circuit_up().
> struct isis_circuit *isis_csm_state_change(enum isis_circuit_event event,
> 					   struct isis_circuit *circuit,
> 					   void *arg)
> {
> [...]
> 			if (isis_circuit_up(circuit) != ISIS_OK) {
> 				isis_circuit_deconfigure(circuit, area);
> 				break;
> 			}
> 			circuit->state = C_STATE_UP;
> 			isis_event_circuit_state_change(circuit, circuit->area,
> 							1);
Do not return isis_link_params_update() if circuit->state != C_STATE_UP.
Fixes: 0fdd8b2b11 ("isisd: update link params after circuit is …
=> isisd: fix update link params after circuit is up

isisd/isis_cli.c, isisd/isis_nb.c, isisd/isis_nb.h
Add missing `exit` statement to `show running-config` output.
```
router isis ISIS_CORE
net 49.0001.0000.0000.0004.00
lsp-mtu 1300
topology ipv6-unicast
log-adjacency-changes
segment-routing srv6
locator ISIS_LOC
exit   <<<<<<<<<<<<<<<<<<<<<<<<
exit
```
Fixes https://github.com/FRRouting/frr/issues/16694
=> isisd: Add missing `exit` statement to `show running-config` output

bgpd/bgp_mplsvpn.c
The "if_is_vrf" check is unnecessary because it’s already handled by "if_get_vrf_loopback". Additionally, it ignores the default loopback and could introduce potential bugs.
Fixes: 8b81f32e9787 ("bgpd: fix label lost when vrf loopback comes back")
=> bgpd: remove redundant loopback check in label update

tests/topotests/bgp_l3vpn_to_bgp_vrf/test_bgp_l3vpn_to_bgp_vrf.py
Tests may fail because of limited memory on 32bit system
=> tests: Skip bgp_l3vpn vrf tests on 32bit systems

zebra/dplane_fpm_nl.c, zebra/rib.h, zebra/zebra_dplane.c, zebra/zebra_rib.c
=> Zebra fpm backpressure

ospfd/ospf_flood.c
Resolve a couple of SA warnings by asserting that pointers are valid.
=> ospfd: add assert to resolve SA warning

bgpd/bgp_fsm.c
Code was scanning a table then identifying a prefix that needed to be modified then calling code that
reran bestpath on the entire table again.
If you had multiple items that needed processing
you would end up scanning and setting the entire
table to be scanned multiple times.  No bueno.
a) We do not need to reprocess items that are not
being modified.
b) We do not need to walk the entire table multiple times, we have the data that is needed already.
Modify the code to just call bgp_process on the
interesting nodes.
=> bgpd: Reduce # of iterations when doing llgr

tests/topotests/lib/common_config.py, tests/topotests/mgmt_oper/oper.py
tests: optionally pass `seconds_left` to retrying functions
This allows retrying functions to possibly change their logging level
for diagnostics.
In order to maintain backward compatibility with this longstanding
function we catch the specific exception of it not being handled by the
retrying function and call again w/o the argument.
=> improve @retry decorator

lib/northbound_oper.c
Also, cleanup some unreachable code in `nb_op_sib_next()`.
=> lib: fix clang SA warnings

doc/developer/topotests.rst, tests/topotests/pytest.ini
Update the topotest doc to the latest pytest* pkg versions known to work together
=> tests: add asyncio default config param to quiet warning

isisd/isis_nb_config.c
The following causes a isisd crash.
> router # cat config
> affinity-map green bit-position 0
> router isis 1
>  flex-algo 129
>   affinity exclude-any green
> router # vtysh -f config
> router #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
> https://github.com/FRRouting/frr/pull/1  0x00007f650cd32756 in core_handler (signo=6, siginfo=0x7ffc56f93070, context=0x7ffc56f92f40) at lib/sigevent.c:258
> https://github.com/FRRouting/frr/issues/2  <signal handler called>
> https://github.com/FRRouting/frr/issues/3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> https://github.com/FRRouting/frr/issues/4  0x00007f650c91c537 in __GI_abort () at abort.c:79
> https://github.com/FRRouting/frr/pull/5  0x00007f650cd007c9 in nb_running_get_entry_worker …
=> isisd: fix crash at flex-algo affinity setting
