FRRouting/frr

- nhrpd/nhrp_vty.c
For compatibility with frr-reload, a command
"no tunnel protection [vici profile PROFILE [fallback-profile FALLBACK]]" was added.
This fix closes https://github.com/FRRouting/frr/issues/16628
> nhrpd: Added a command "no tunnel protection vici profile PROFILE"

- isisd/isis_tlvs.c
- isisd/isis_tlvs.h
isisd is crashing when reading a ASLA sub-TLV with Application Identifier Bit Mask length greater than 1 octet.
Set a limit of 8 bytes in accordance with RFC9479 and check that the received value does not exceed the limit.
Link: https://www.rfc-editor.org/rfc/rfc9479.html#name-application-identifier-bit-
Fixes: 5749ac83a8 ("isisd: add ASLA support")
> isisd: fix crash when reading asla

- doc/developer/bgpd.rst
- doc/developer/mgmtd-dev.rst
- doc/developer/northbound/yang-tools.rst
- doc/developer/topotests.rst
- doc/developer/workflow.rst
Add some text about using git forks in the FRR workflow. Fix a few doc warnings in the dev docs too.
> doc: add some text about using git forks

- bgpd/bgp_routemap.c
Fix a crash when modifying a route-map with set as-path exclude without as-path-access-list:
> router(config)# route-map routemaptest deny 1
> router(config-route-map)# set as-path exclude 33 34 35
> router(config-route-map)# set as-path exclude as-path-access-list test
> #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007fb3959327de in core_handler (signo=11, siginfo=0x7ffd122da530, context=0x7ffd122da400) at lib/sigevent.c:258
> #3  0x000055ab2762a1bd in as_list_list_del (h=0x55ab27897680 <as_exclude_list_orphan>, item=0x55ab28204e20) at ./bgpd/bgp_aspath.h:77
> #4  0x000055ab2762d1a8 in as_exclude_remove_orphan (ase=0x55ab28204e20) at bgpd/bgp_aspath.c:1574
> #5  0x000055ab27550538 in route_aspath_exclude_free …
> bgpd: fix as-path exclude modify crash

- zebra/redistribute.c
- zebra/zapi_msg.c
- zebra/zebra_rib.c
- zebra/zserv.c
Trying to debug some cross vrf stuff in zebra and frankly it's hard to grep the file for the routes you are interested in.  Let's clean this up some and get a bit better information for us developers
> zebra: Add more vrf name to debugs

- isisd/isis_nb_state.c
Level 2 adjacency list is not supposed to be always set.
> #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f9f0353274f in core_handler (signo=6, siginfo=0x7ffe95260770, context=0x7ffe95260640) at lib/sigevent.c:258
> #3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #4  0x00007f9f0324e537 in __GI_abort () at abort.c:79
> #5  0x00007f9f035744ea in _zlog_assert_failed (xref=0x7f9f0362c6c0 <_xref.15>, extra=0x0) at lib/zlog.c:789
> #6  0x00007f9f034d25ee in listnode_head (list=0x0) at lib/linklist.c:316
> #7  0x000055cd65aaa481 in lib_interface_state_isis_adjacencies_adjacency_get_next (args=0x7ffe95261730) at isisd/isis_nb_state.c:101
> #8  0x00007f9f034feadd in nb_callback_get_next …
> tests: fix isis_lsp_bits_topo1 race condition

- ospfd/ospf_flood.c
When "ip ospf network point-to-multipoint delayed-reflooding" is configured, LSAs received on an OSPF P2MP network are not reflooded. Since LSA reflooding would normally serve as an implied LSA acknowledgment, an explicit OSPF ack should be sent to avoid retransmission by the neighbor which orginally flooded the LSA on the P2MP network.
> ospfd: An OSPF Ack should be sent when P2MP reflooding is delayed

- bgpd/bgp_ecommunity.c
> bgpd: changes for code maintainability

- tests/topotests/conftest.py
- tests/topotests/munet/cli.py
- tests/topotests/munet/native.py
- tests/topotests/munet/testing/util.py
- fix spawning shells/vtysh on error in xdist mode
- munet 0.14.14
- Another improvement for remote CLI in xdist mode
- munet 0.14.13
- Improve remote CLI operation [improves xdist mode]
- munet 0.14.12
- Fix --stdout and --stderr munet CLI args
- Adds retry_sleep (i.e., interval) parameter to native @retry decorator
> improvements for xdist mode

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Include SID structure information when installing/removing an SRv6 SID in/from the forwarding plane.
> bgpd, lib: Include SID structure in seg6local nexthop

- bgpd/bgp_route.c
- bgpd/bgp_route.h
a) Allow bgp_process to push a item to the front of the list
b) Remove a redundant check
> Bgp give some ordering increases

- bgpd/bgp_route.c
Add counters for redistributed routes, and local aggregates to the output of "show ip bgp statistics".
> bgpd: add counters for redistributed and aggregated routes

- bgpd/bgp_packet.c
- bgpd/bgp_updgrp.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- tests/topotests/bgp_dual_as/r1/frr.conf
- tests/topotests/bgp_dual_as/r2/frr.conf
- tests/topotests/bgp_dual_as/test_bgp_dual_as.py
Closes https://github.com/FRRouting/frr/issues/13928
> bgpd: Implement BGP dual-as feature

- bgpd/bgp_script.h
Use forward references instead of including the main bgpd.h header in the bgp scripting header: because of the way the lua scripting infra builds, changes to bgpd.h were affecting other modules.
> bgpd: remove bgpd.h from bgp script header

- tests/topotests/lib/common_config.py
- tests/topotests/lib/topotest.py
Apparently logger.warn is being deprecated.  So let's switch over to logger.warning.  Clearly it's better
> tests: use logger.warning not logger.warn

- ospfd/ospf_sr.c
When parsing the SR-Algorithm TLV in the OSPF Router Information Opaque LSA, assure that not more than the maximum number of supported algorithms are copied from the TLV.
> ospfd: Fix heap corruption vulnerability when parsing SR-Algorithm TLV

- bgpd/bgp_ecommunity.h
- bgpd/bgp_evpn.c
- bgpd/bgp_pbr.c
The type of the val field in ecommunity_val is used inconsistently in a number of places. It should be defined as uint8_t.
> bgpd: define val in ecommunity_val as uint8_t

- zebra/kernel_netlink.c
- zebra/kernel_netlink.h
This function is never used.  So let's remove it.
> zebra: Remove nl_addraw_l

- bgpd/bgp_fsm.c
- bgpd/bgp_network.c
- bgpd/bgp_network.h
The below log message is often seen when peering with BGP peers. This message has been displayed by introducing a recent fix that exposes the IP/port information when available.
Fix this by separating the peer->su_[local/remote] contexts used for display, and for handling the peer session operational.
Two new attributes are appended to the peer structure: su_remote_display and su_local_display. Those fields are only used for display the network information (in vty and in snmp).
Fixes: 78ce63952a99 ("bgpd: fix addressing information of non established outgoing sessions")
> bgpd: fix 'nexthop_set failed' error message often displayed

- lib/libfrr.c
We've faced with a regression after we moved from frr 8.5 to a newer versions (9.0, 9.1, 10.0, 10.1).
In our automation we start frr from python code using subprocess like this:
```python
subprocess.run(
["/usr/lib/frr/frrinit.sh", "start"],
stdout=subprocess.PIPE,
stderr=subprocess.PIPE,
)
```
This call hangs in `poll()` for stdout FD indefinitely and `frrinit.sh` hangs in zombie state unless we kill `subprocess.run()` call.
If we remove stdout capturing from `subprocess.run()` call (make associated to stdout FD a tty FD), things go well and process terminates correctly with no hangs and zombies.
This commit fixes this situation where stdout of a process started in a daemon mode was attached to a calling process regardless of presence `--log` option.
If this patch is acceptable, it's …
> lib: Attach stdout to child only if --log=stdout and stdout FD is a tty

- bgpd/bgp_zebra.c
- tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/zebra-vrf-default.txt
- tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/zebra-vrf-neno.txt
- tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-default.txt
- tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-ray.txt
Fix the misplaced arguments "bhtype" and "api.distance" in bgp_redistribute_add().
> bgpd: fix misplaced arguments in bgp_redistribute_add()

- zebra/zebra_nhg.c
zebra_nhg_install_kernel takes a route type.  We don't know it at that particular spot but we should not be passing in `true`.  Let's use ZEBRA_ROUTE_MAX to indicate we do not know, so that the correct thing is done.
> zebra: Pass in ZEBRA_ROUTE_MAX instead of true

- tests/topotests/dump_of_bgp/r1/frr.conf
- tests/topotests/dump_of_bgp/r2/frr.conf
- tests/topotests/dump_of_bgp/test_dump_of_bgp.py
None of the bgp dump code was even tested.  Add a bit of basic stuff that it at least generates a dump file. This can be extended at a future time.
> tests: Add a very basic `dump bgp PATH..` topotest

- tests/topotests/srv6_encap_src_addr/r1/zebra.conf
- tests/topotests/srv6_sid_manager/rt1/bgpd.conf
- tests/topotests/srv6_sid_manager/rt6/bgpd.conf
`log monitor XX` command is deprecated and does nothing. Let's remove it.
> tests: Remove `log monitor XX ` from topotests

- ospfd/ospfd.c
When 'ip ospf neighbor-filter <filter-name>' is configured in the startup configuration, it is in the running configuration but not applied on the interface.
> ospfd: Interface 'ip ospf neighbor-filter' startup config not applied.

- isisd/isis_spf.c
When creating SPF neighbors and calling spf_adj_list_parse_tlv(), the F_ISIS_SPF_ADJ_METRIC_INFINITY flag is only set to a local variable flags and not set to the SPF neighbor sadj->flags. Additionally, the pseudo node metric pseudo_metric is also not reflected in the F_ISIS_SPF_ADJ_METRIC_INFINITY flag, the metric should be checked using sadj->metric.
> isisd: Fix infinity flag not being set successfully

- zebra/if_netlink.c
- zebra/zebra_evpn.c
Must unlock if we break during iteration over any lib/table tree; the per-ns if_table tree needs some cleanup.
> zebra: unlock if_table route_nodes

- yang/frr-bgp-route-map.yang
f1ea52bee9 ("yang: use relative path instead of absolute one for route-map") has introduced a route-map optimization but some paths were not changed.
Use relative path instead absolute one everywhere.
> yang: use relative path for route-map

- bgpd/bgpd.c
Don't need to cancel scheduled events twice in a row - just once: could be expensive.
> bgpd: cancel events once in peer_free()

- tests/topotests/forwarding_on_off/r1/frr.conf
- tests/topotests/forwarding_on_off/r2/frr.conf
- tests/topotests/forwarding_on_off/r3/frr.conf
- tests/topotests/forwarding_on_off/test_forwarding_on_off.py
There are no tests that ensured that turning off then on v4 and v6 forwarding actually worked.  This does so. This was found via looking at the code coverage.
> tests: Add v4/v6 forwarding off/on

- bgpd/bgp_route.c
This is another potential fix for #16198
* First we modify the original `(from == bgp->peer_self || peer->sort == BGP_PEER_EBGP)` to an `&&` operator.
* Then we create a second case for a remote_peer and check `IN6_IS_ADDR_LINKLOCAL(&attr->mp_nexthop_local)` (e.g. link-local nh is actually included by remote peer.
In [rfc2545 section 3](https://datatracker.ietf.org/doc/html/rfc2545#section-3) we have:
> The link-local address shall be included in the Next Hop field if and
> only if the BGP speaker shares a common subnet with the entity
> identified by the global IPv6 address carried in the Network Address
> of Next Hop field and the peer the route is being advertised to.
> In all other cases a BGP speaker shall advertise to its peer in the
> Network Address field only the global IPv6 …
> bgpd - Exclude case for remote prefix w/o link-local #16198

- ospf6d/ospf6_abr.c
- ospf6d/ospf6_abr.h
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_asbr.h
- ospf6d/ospf6_flood.c
- ospf6d/ospf6_gr.c
- ospf6d/ospf6_gr.h
- ospf6d/ospf6_gr_helper.c
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_intra.c
- ospf6d/ospf6_intra.h
- ospf6d/ospf6_lsa.c
- ospf6d/ospf6_lsa.h
- ospf6d/ospf6_lsdb.c
- ospf6d/ospf6_message.c
- ospf6d/ospf6_neighbor.c
- ospf6d/ospf6_nssa.c
- ospf6d/ospf6_proto.h
- ospf6d/ospf6_spf.c
- ospf6d/ospf6_tlv.h
- ospf6d/ospf6_top.c
- ospf6d/ospf6_zebra.c
- ospf6d/ospf6d.c
- ospf6d/subdir.am
- tests/ospf6d/test_lsdb.c
This PR contains what I hope would be the less controversial bits of the Work In Progress on PR #16532.
It refactors the ospf6d implementation in order to
* enable future use of the existing TLV handling when E-LSAs are added
* cleanup some pointer casts and pointer arithmetic to improve readability
> OSPF6: Refactor to prepare for E-LSA handling

- ospfd/ospf_vty.c
OSPFD The issue occurs when the new value set using the timers throttle spf command is larger than the previous one. In this case, the holdTimeMultiplier does not reset to 1 and remains greater than 1, leading to an incorrect min_holdtime.
> ospfd: reset spf_hold_multiplier when current SPF delay state is changed

- ospfd/ospf_vty.c
1. Fixed the syntax of `no ip ospf dead-interval minimal hello-multiplier` to allow the parameter(2-20) to either present or absent, aligning with `no ip ospf dead-interval` command. 
2. Fixed the syntax of 'no ospf abr-type'  same as above
> ospfd: fix snytax of some no commands

- tests/topotests/bgp_dual_as/r2/frr.conf
- tests/topotests/bgp_dual_as/test_bgp_dual_as.py
This should fix current random failures in CI.
> tests: Simplify BGP dual-as topotest

- tests/topotests/zebra_rib/test_zebra_rib.py
Range is wrong. We want values 1 and 2 but we only test 1.
> >>> for i in range(1, 2):
> ...     print(i)
> ...
> 1
Fixes: abd2a1ff3f ("tests: Test some basic kernel <-> zebra interactions")
> tests: fix zebra_rib range

- isisd/isis_sr.c
Before adding an NHLFE entry, zebra calls `nhlfe_nexthop_active_ipv4()/nhlfe_nexthop_active_ipv6()` to check if there is a corresponding directly connected route for the next hop prefix of the NHLFE. If such a route exists, it directly overwrites the output interface of the NHLFE's next hop with the output interface of the directly connected route. If the output interface of the directly connected route is different from the output interface of the NHLFE's next hop, deleting the NHLFE entry later will fail because `nhlfe_nhop_match()` cannot find the same next hop address and output interface, leading to an NHLFE entry leak.
Of course, the above situation generally does not occur, but ISIS adjacency labels can cause issues.
Establishing neighbors in ISIS only requires the existence of the …
> isisd: Fix NHLFE entry memory leaks

- nhrpd/nhrp_shortcut.c
- nhrpd/nhrpd.h
In the event that a resolution request is sent and and resolution reply is never received, resolution requests will continue to be sent until either the newly created shortcut has been purged or a resolution reply is finally received.
NHRPD_DEFAULT_PURGE_TIME and NHRPD_PURGE_EXPIRE are values that were previously hardcoded and  moved into macros for the sake of readability.
> nhrpd: Implement retrying resolution request

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_cmd_common.c
- pimd/pim_cmd_common.h
- pimd/pim_iface.c
- pimd/pim_iface.h
- pimd/pim_igmp.c
- pimd/pim_igmp.h
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- pimd/pim_tib.c
- pimd/pim_tib.h
- pimd/pim_vty.c
- tests/topotests/lib/pim.py
- tests/topotests/pim_basic_igmp_proxy/r1/frr.conf
- tests/topotests/pim_basic_igmp_proxy/r2/frr.conf
- tests/topotests/pim_basic_igmp_proxy/r3/frr.conf
- tests/topotests/pim_basic_igmp_proxy/rp/frr.conf
- tests/topotests/pim_basic_igmp_proxy/test_pim_igmp_proxy.py
- yang/frr-gmp.yang
This PR adds the ability to proxy igmp joins received on downstream interfaces to one or more upstream interfaces
> Add igmp proxy support

- bgpd/bgp_vty.c
Recent commit 4d0e7a49cf8d4311a485281fa50bbff6ee8ca6cc brought in changes that moved a check for ret up
in the code, caused some code to be left around
and be effectively dead since it would never be called.
> bgpd: Remove dead code from recent commit

- zebra/zebra_snmp.c
Was playing with snmp and noticed some issues with zebra's implementation of it.
a) snmp walk was wrong.  Whomever wrote this found a new and interesting way to make something simple hard.  Further work should be done to optimize this, just putting this back into working order since I broke it in 2019
b) Who would think to walk the individual bytes of a struct to set them to 0 in a loop when memset is available?
c) Metrics are not being reported at all.  Let's return them
d) Some missing proto translations.  The values are weird so we don't get everything.
> zebra snmp fixes

- bgpd/bgp_evpn_vty.c
Current Issue:
paths key is not there for 'show bgp l2vpn evpn route rd <rd-id> mac <mac> json' uses evpn prefix as key for each path.
Replace the evpn prefix with "paths".
This aligned with overall EVPN RIB json output like 'show bgp l2vpn evpn route json'
'show bgp l2vpn evpn route rd <> type 2 json'
Testing:
Before fix:
```
leaf22# show bgp l2vpn evpn route rd 6.0.0.17:2 mac 00:02:00:00:00:12 json {
"prefix":"[2]:[0]:[48]:[00:02:00:00:00:12]",
"prefixLen":352,
"rd":"6.0.0.17:2",
"routeType":2,
"ethTag":0,
"macLen":48,
"mac":"00:02:00:00:00:12",
"advertisedTo":{
"220.20.0.33":{
"hostname":"spine21"
},
"220.21.0.33":{
"hostname":"spine22"
}
},
"[2]:[0]:[48]:[00:02:00:00:00:12]":[ <=====  Prefix info instead of "paths" key
[
{
"vni":"101101",
"aspath":{
"string":"65202 65024", …
```
> bgpd: EVPN fix per rd specific type-2 json output

- .clang-format
A bunch of recent discussion has gone on about this.  Let's see if we are actually interested in making a change.
> *: Modify clang-format column limit to 100

- pimd/pim_autorp.c
- pimd/pim_cmd.c
- pimd/pim_cmd_common.c
- tests/topotests/pim_autorp/test_pim_autorp.py
Expands the autorp topotest to include the "announce" cli commands and fixes cli bugs uncovered during this development
> pimd: enhance topotest of autorp, fix autorp cli bug

- pimd/pim6_mld.c
- pimd/pim_nb_config.c
Two small fixes in PIM:
- Remove unreacheable code
- Fix some badly formated northbound output
> pimd: miscellaneous fixes

- lib/elf_py.c
Fix the following compiler warning:
```
lib/elf_py.c: In function _elffile_load_:
lib/elf_py.c:1310:34: warning: _calloc_ sizes specified with _sizeof_ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
1310 |         w->sects = calloc(sizeof(PyObject *), w->ehdr->e_shnum);
|                                  ^~~~~~~~
lib/elf_py.c:1310:34: note: earlier argument should specify number of elements, later size of each element
```
> lib: fix calloc warning on recent compiler

- tools/frr-reload.py
Without checking interfaces, the other interfaces' changes will be wrongly lost.
Running config:
```
interface A
ip pim
ip pim use-source 11.0.0.1
exit
!
interface B
ip pim
ip pim use-source 22.0.0.1
exit
!
```
Reload the new config:
```
interface A
exit
!
interface B
ip pim
exit
```
Before:
```
2024-09-29 10:08:27,686  INFO: Executed "interface A  no ip pim exit"
```
After:
```
2024-09-29 10:05:01,356  INFO: Executed "interface A  no ip pim exit"
2024-09-29 10:05:01,376  INFO: Executed "interface B  no ip pim use-source 22.0.0.1 exit"
```
> tools: fix missing check interfaces for reloading pim

- lib/nexthop_group.c
- lib/nexthop_group.h
It's possible to specify via the cli and configure how many nexthops that are allowed on the system.  If you happen to have > 255 then things are about to get interesting otherwise.
Let's allow up to 65k nexthops (ha!)
> lib: nexthop code should use uint16_t for nexthop counting

- bgpd/bgpd.c
Fix printfrr_bp for non initialized peers. For example:
> Sep 26 17:56:44 r1 bgpd[26295]: [GJPH1-W8PZV] Resetting peer (null)(Unknown) due to change in addpath config
Is now:
> Oct 02 14:00:59 r1 bgpd[12795]: [MNE5N-K0G4Z] Resetting peer 2.2.2.2 due to change in addpath config
> bgpd: fix printfrr_bp for non initialized peers

- zebra/dplane_fpm_nl.c
`fpm_enqueue_rmac_table` expects an `fpm_rmac_arg *` as its argument.
The issue can be reproduced by dropping the TCP session using:
```
ss -K dst 127.0.0.1 dport = 2620
```
I've seen that you have `tests` folder but I'm new to the frr codebase, if you give me small guidelines I can add a test for my PR.
> zebra: Fix crash during reconnect

- tools/frr-reload.py
The issue is we can't remove all pim configurations including some special configurations (e.g., `no ip pim bsm`) for one interface.
For one pim-disable interface, all such pim depdendent options (including `ip pim ` and `no ip pim `) should be completely removed.
Also append `no ip multicast` for the same purpose, it is no use at present, but for future use.
The running config:
```
interface A
ip pim
no ip pim bsm
exit
```
Reload the new config:
```
interface A
exit
```
Before:
```
2024-10-05 20:52:33,467  INFO: Executed "interface A  no ip pim exit"
2024-10-05 20:52:33,482  INFO: Executed "interface A  ip pim bsm exit"
```
And the pim configurations in running configuration are not removed after reloading:
```
interface A
ip pim <- Wrong
exit
```
After:
```
2024-10-05 20:56:27,489 …
```
> tools: fix some special commands for reloading pim

- lib/grammar_sandbox_main.c
- lib/libfrr.c
- lib/libfrr.h
- lib/northbound.c
- lib/northbound.h
- lib/yang.c
- lib/yang.h
- lib/yang_translator.c
- mgmtd/mgmt.c
- mgmtd/mgmt_main.c
- tests/bgpd/test_peer_attr.c
- tests/helpers/c/main.c
- tests/isisd/test_isis_spf.c
- tests/lib/cli/common_cli.c
- tests/lib/cli/test_commands.c
- tests/lib/northbound/test_oper_data.c
- tests/lib/test_grpc.cpp
- tools/gen_northbound_callbacks.c
- tools/gen_yang_deviations.c
Mgmtd makes use of libyang's internal ietf-yang-library module to add support for said module to FRR management. Previously, ietf-yang-library was loading this module explicitly; however, that required that libyang's `ietf-yang-library.yang` module definition file be co-located with FRR's so that it (and ietf-datastore.yang) would be found when searched for by libyang. This isn't always the case depending on how the user compiles and installs libyang so mgmtd was failing to run in these cases.
Instead of doing it that way we simply tell libyang to load it's internal version of ietf-yang-library when we initialize the libyang context.
This required adding a boolean to a couple of the init functions which is why so many files are touched (although all the changes are minimal).
> lib: add flag to have libyang load internal ietf-yang-library module

- isisd/isis_nb_config.c
```
anlan# show run
!
interface eth0
ip router isis A
exit
!
router isis A
metric-style narrow <- NOT wide
exit
!
end
anlan (config)# int eth0
anlan (config-if)# no isis topology ipv6-unicast
Error description: Multi topology IS-IS can only be used with wide metrics
```
The MT commands are mainly controlled by the binded area, not by interface. Currently if there is any MT configuration in the area, `metric-style` must be with the `wide` mode, this requirement is sufficient.  So, the unnecessary/wrong check for MT in the interface should be removed.
> isisd: fix wrong check for MT commands

- vrrpd/vrrp_packet.c
Assign the return of `CMSG_NXTHDR` so we can really iterate over the ancillary data.
> vrrpd: iterate over all ancillary messages

- isisd/isis_lfa.c
When there are pseudo-nodes on the device, during TI-LFA calculation of PQ space, even if this IS vertex is not originally a P/Q node, it might be calculated as a P/Q node due to the presence of pseudo-nodes, causing this IS vertex to become a P/Q node.
> TI-LFA incorrectly included pseudo-nodes when calculating PQ space.

- bgpd/bgp_route.c
- tests/topotests/bgp_received_routes_with_soft_inbound/r1/frr.conf
- tests/topotests/bgp_received_routes_with_soft_inbound/r2/frr.conf
- tests/topotests/bgp_received_routes_with_soft_inbound/test_bgp_received_routes_with_soft_inbound.py
Closes https://github.com/FRRouting/frr/issues/16943
> bgpd: Show unmodified version of received-routes per neighbor

- zebra/zebra_pw.c
- zebra/zebra_pw.h
- zebra/zebra_rib.c
slight cleanup of where code was and also a small change to not automatically retry the installation of a pseudowire if it's reachability is down.
> Pw cleanup

- bgpd/bgp_addpath.c
- bgpd/bgp_addpath.h
- bgpd/bgp_nexthop.h
- bgpd/bgp_nht.c
- pimd/pim_nht.c
- pimd/pim_nht.h
- zebra/rt_netlink.c
- zebra/zapi_msg.c
- zebra/zebra_dplane.c
- zebra/zebra_dplane.h
- zebra/zebra_nhg.c
- zebra/zebra_nhg.h
Currently FRR is limiting the nexthop count to a uint8_t not a uint16_t.  This leads to issues when the nexthop count is 256 which results in the count to overflow to 0 causing problems in the code.
> zebra: Allow dplane to pass larger number of nexthops down to dataplane

- zebra/zebra_pw.c
Recent PR #17009 introduced a crash in pw handing
for deletion.  Let's fix that problem.
Fixes: #17041
> zebra: Fix crash in pw code

- bfdd/bfdd_cli.c
- doc/user/bfd.rst
- yang/frr-bfdd.yang
The minimum and maximum values for BFD timers and multiplier settings have been updated to align with RFC 5880 requirements.
Since the values inputted via VTY are in milliseconds, the maximum permissible value on the VTY interface is 4,294,967 milliseconds.
For the multiplier setting, the minimum value is now restricted to be greater than zero, as zero is not allowed.
The minimum transmit interval has been set to 10 milliseconds to ensure reliable service performance.
> bfdd, yang: change bfd timer and multiplier values

- doc/user/vrrp.rst
This week I have learnt more about VRRP and IPv6 than I can care to elaborate on 😂 
Essentially we are running our FRR routers inside VMs, and those VMs have network interfaces placed in a bridge on the host (in this case, Proxmox). VRRP on IPv4 had no issues, but I was having incredibly strange behaviour with IPv6 and the VMs randomly no longer receiving the VRRP announcements.
Given it took almost 3 days of debugging, thought it would be worthwhile adding to the (already brilliant) docs on this, in case anyone else hits the same issue in the future.
> Adds note about VRRP issues inside a VM with underlying bridge networking

- isisd/isis_lsp.c
When LSP fragments age, isis_dynhn_remove() is also called to remove the corresponding dyhn_cache entries.
> isisd: Lsp fragments will delete the corresponding dyn_cache entry.

- bgpd/bgp_vty.c
- doc/user/bgp.rst
This command did not allow the operator to display neighbor information related to graceful-restart when used inside of a vrf.
> bgpd: Allow specification of vrf in show bgp neighbor graceful-restart

- bgpd/bgp_route.c
- tests/topotests/bgp_nexthop_ipv6/exabgp.env
- tests/topotests/bgp_nexthop_ipv6/r1/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/r1/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/r1/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r1/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/r2/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/r2/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/r2/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r2/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/r3/exabgp.cfg
- tests/topotests/bgp_nexthop_ipv6/r4/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/r4/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/r4/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r4/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/r5/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/r5/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/r5/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r5/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/r6/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/r6/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/r6/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r6/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/rr/bgpd.conf
- tests/topotests/bgp_nexthop_ipv6/rr/show_bgp_ipv6_step1.json
- tests/topotests/bgp_nexthop_ipv6/rr/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/rr/show_bgp_ipv6_summary.json
- tests/topotests/bgp_nexthop_ipv6/rr/zebra.conf
- tests/topotests/bgp_nexthop_ipv6/test_bgp_nexthop_ipv6_topo1.py
https://github.com/FRRouting/frr/pull/16219 attempted to solve https://github.com/FRRouting/frr/issues/16198 issue but removed ipv6 link-local nexthop in situation it was legitimate. For example, when an ipv4-mapped IPv6 address is present in global IPv6 nexthop, the link-local is also useful if the peer does not understand the ipv4-mapped IPv6 address format.
Revert https://github.com/FRRouting/frr/pull/16219 and apply fixes to the "ipv6 nexthop-local unchanged" behavior. When the parameter is present:
- don't insert a link-local when the origin peer does not send any link-local
- reset the link-local of the origin peer to the local router link-local when the origin and destination peer does not share the same network  
Add a topotest to check the ipv6 nexthops in various situations …
> bgpd: fix ipv6 nexthop-local unchanged

- bgpd/bgp_routemap.c
- lib/routemap_cli.c
Closes https://github.com/FRRouting/frr/issues/17055
> bgpd: Move some non BGP-specific route-map functions to lib

- zebra/interface.c
The `flags` field is removed recently, so add back it for debug.
> zebra: add back one field for debug

- fpm/fpm.h
- zebra/dplane_fpm_nl.c
The fpm_nl_process function was getting the count
of the total number of ctx's processed.  This leads to after having processed 1 context to always signal the dataplane that there is work to do.  Change the code to only notify the dplane worker when a context was actually added to the outgoing context queue.
> zebra: Only notify dplane work pthread when needed

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn.h
- bgpd/bgp_evpn_mh.c
- bgpd/bgp_evpn_mh.h
In symmetric routing, when local ESI is down,
the MH peer learnt local mac-ip
prefix is installed into teannt vrf (given l3vni).
When ESI is back up and associated to evi/vni then remove the local synced mac-ip imported routes from the tenant vrf as local neigh/arp is present.
Testing:
peer advertised mac-ip route:
```
*> [2]:[0]:[48]:[aa:aa:aa:00:00:01]:[32]:[45.0.0.51] RD 27.0.0.4:9
27.0.0.4 (spine-1)
0 64435 65016 i
ESI:03:44:38:39:ff:ff:01:00:00:01
RT:65016:1000 RT:65016:4000 ET:8 Rmac:44:38:39:ff:ff:16
``` 
When local ESI is flapped
```
torm-11:# ip neigh show 45.0.0.51
45.0.0.51 dev vlan1000 lladdr aa:aa:aa:00:00:01 REACHABLE proto zebra
```
Before fix:
(The imported route remained in tenant-vrf)
```
torm-11:# ip route show vrf vrf1 45.0.0.51
45.0.0.51 nhid 257 proto bgp metric 20 …
```
> bgpd: fix evpn mh esi down

- bgpd/bgp_bmp.c
- bgpd/bgp_bmp.h
- bgpd/bgp_packet.c
- bgpd/bgp_packet.h
- bgpd/bgpd.c
- bgpd/bgpd.h
- tests/topotests/bgp_bmp/test_bgp_bmp.py
- tests/topotests/bgp_bmp_vrf/r1/bgpd.conf
- tests/topotests/bgp_bmp_vrf/r1/zebra.conf
- tests/topotests/bgp_bmp_vrf/r2/bgpd.conf
- tests/topotests/bgp_bmp_vrf/r2/zebra.conf
- tests/topotests/bgp_bmp_vrf/test_bgp_bmp_vrf.py
- tests/topotests/lib/bmp_collector/bmp.py
added bmp bgp peer for vrfs
added peer up vrf in bmp peer up state
added vrf state in bmpbgp
added safe bmp_peer_sendall : bmp_peer_sendall_safe
changed bgp_open_send to call new bgp_open_make
bgp_open_make creates a bgp open packet, now used in bmp for peer up vrf
added hook and call to bgp instance state
vrf peer state is recomputed when interfaces (including vrf itf) go up / down
and when it gets created or removed
Link: https://github.com/mxyns/frr/commit/e48ba380700d53124131f4e4419f646c05b40c86
Signed-off-by: Maxence Younsi <mx.yns@outlook.fr>
> bgpd: bmp loc-rib peer up/down for vrfs

- zebra/dpdk/zebra_dplane_dpdk.c
- zebra/dplane_fpm_nl.c
- zebra/if_netlink.c
- zebra/kernel_netlink.c
- zebra/kernel_socket.c
- zebra/zebra_dplane.c
- zebra/zebra_dplane.h
- zebra/zebra_l2.h
- zebra/zebra_rib.c
- zebra/zebra_script.c
- zebra/zebra_vxlan.c
- zebra/zebra_vxlan.h
**Commit-2 : zebra: vlan to dplane Offload from main**
```
Trigger: Zebra core seen when we convert l2vni to l3vni and back
BackTrace:
/usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(_zlog_assert_failed+0xe9) [0x7f4af96989d9]
/usr/lib/frr/zebra(zebra_vxlan_if_vni_up+0x250) [0x5561022ae030]
/usr/lib/frr/zebra(netlink_vlan_change+0x2f4) [0x5561021fd354]
/usr/lib/frr/zebra(netlink_parse_info+0xff) [0x55610220d37f]
/usr/lib/frr/zebra(+0xc264a) [0x55610220d64a]
/usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(thread_call+0x7d) [0x7f4af967e96d]
/usr/lib/x86_64-linux-gnu/frr/libfrr.so.0(frr_run+0xe8) [0x7f4af9637588]
/usr/lib/frr/zebra(main+0x402) [0x5561021f4d32]
/lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f4af932624a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f4af9326305] …
```
> zebra: vlan to dplane

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_route.c
- tests/topotests/bgp_aigp/r1/ospfd.conf
- tests/topotests/bgp_aigp/r2/bgpd.conf
- tests/topotests/bgp_aigp/r2/ospfd.conf
- tests/topotests/bgp_aigp/r3/bgpd.conf
- tests/topotests/bgp_aigp/r3/ospfd.conf
- tests/topotests/bgp_aigp/r4/bgpd.conf
- tests/topotests/bgp_aigp/r4/ospfd.conf
- tests/topotests/bgp_aigp/r5/bgpd.conf
- tests/topotests/bgp_aigp/r5/ospfd.conf
- tests/topotests/bgp_aigp/r6/bgpd.conf
- tests/topotests/bgp_aigp/r6/ospfd.conf
- tests/topotests/bgp_aigp/test_bgp_aigp.py
The nexthop metric should be added to AIGP when calculating the
bestpath in bgp_path_info_cmp().
> bgpd: fix route selection with AIGP

- lib/command.h
Related: https://github.com/FRRouting/frr/issues/17052
> lib: Apply and generate route-map commands earlier before any other protocol

- isisd/isis_vty_fabricd.c
Closes https://github.com/FRRouting/frr/issues/17075
> isisd: Remove circuit state check for openfabric

- ospfd/ospf_vty.c
When we use the `no area X.X.X.X range A.B.C.D/M` command, if the area no longer has an interface to which it belongs, then the area should be deleted from the LSDB. This processing logic is consistent with instructions such as `no network area` and `no area authentication`.
CLOSES https://github.com/FRRouting/frr/issues/17079 https://github.com/FRRouting/frr/issues/17080
> ospfd: fix the bug that the empty area was not free after no_area_range was executed

- bgpd/bgp_bmp.c
Fix bmp coverity issue 1600779. peer->su_local cannot be NULL.
Fixes: 035304c25a ("bgpd: bmp loc-rib peer up/down for vrfs")
> bgpd: fix bmp coverity issue 1600779

- tools/gcc-plugins/frr-format.c
Need to have arrays as a stop condition in this type normalization function, like pointers and function pointers.  Actual arrays as argument types are extremely rare to see because C has this array-decay-to-pointer thing, but it can happen.
---
Fixes the ICE/GCC crash in #12346
> tools/gcc-plugins: don't crash on array parameters

- bgpd/bgp_route.c
- tests/topotests/bgp_nexthop_ipv6/r4/show_bgp_ipv6_step2.json
- tests/topotests/bgp_nexthop_ipv6/r5/show_bgp_ipv6_step2.json
Depends on https://github.com/FRRouting/frr/pull/17071 merge
```
AS 65000  | AS 65001
|
RR  |
|  |
R1 --- | --- R2
|
```
When r1 peer is an iBGP route reflector client of rr and r2 peer is a
eBGP neighbor of rr, and all three routers shares the same network, r2
receives announcements coming from r1 with a IPv6 link-local nexthop
from rr. This is incorrect as r2 should send traffic to r1 without
involving rr.
Do not send an IPv6 link-local nexthop if the originating peer is a
route-reflector client.
Link: https://github.com/FRRouting/frr/pull/16219#issuecomment-2397425505
Link: https://github.com/FRRouting/frr/pull/17037#discussion_r1792529683
> bgpd, tests: don't send local nexthop from rr client

- zebra/connected.c
There exists a series of events where a kernel route is learned first( that happens to be exactly what a connected route should be ) and FRR ends up with both a kernel route and a connected route, leaving us in a very strange spot.  This code change just mirrors the existing code of if there is a connected route drop the kernel route.  Here we just do the reverse, if we have a kernel route already and a connected should be created, remove the kernel and keep the connected.
> zebra: Prevent a kernel route from being there when a connected should

- zebra/zebra_rib.c
I got asked today what was going on in the rnh code.  I had to take time off of what I was doing and rewrap my head around this code, since it's been a long time. As that this question may come up again in the future I am trying to document this better so that someone coming behind us will be able to read this and get a better idea of what the algorithm is attempting
to do.
> zebra: Attempt to explain the rnh tracking code better

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_route.c
- bgpd/bgp_routemap.c
- bgpd/bgp_updgrp_adv.c
- bgpd/rfapi/rfapi.c
- bgpd/rfapi/vnc_export_bgp.c
- doc/user/routemap.rst
- lib/routemap_cli.c
- lib/routemap_northbound.c
- tests/topotests/bgp_aigp/r1/bgpd.conf
- tests/topotests/bgp_aigp/r1/zebra.conf
- tests/topotests/bgp_aigp/r8/bgpd.conf
- tests/topotests/bgp_aigp/r8/zebra.conf
- tests/topotests/bgp_aigp/test_bgp_aigp.py
- tests/topotests/bgp_set_metric_igp/r1/frr.conf
- tests/topotests/bgp_set_metric_igp/r2/frr.conf
- tests/topotests/bgp_set_metric_igp/r3/frr.conf
- tests/topotests/bgp_set_metric_igp/r4/frr.conf
- tests/topotests/bgp_set_metric_igp/r5/frr.conf
- tests/topotests/bgp_set_metric_igp/test_bgp_set_metric_igp.py
- yang/frr-route-map.yang
Related: https://github.com/FRRouting/frr/issues/17031
> bgpd: Derive and set MED from IGP or AIGP

- zebra/zebra_rnh.c
Move route_unlock_node() after rnh_list_del().
> zebra: unlock node only after operation in zebra_free_rnh()

- bgpd/bgp_attr.h
- bgpd/bgp_route.c
- bgpd/bgp_routemap.c
- tests/topotests/bgp_aigp/r4/bgpd.conf
- tests/topotests/bgp_aigp/r6/zebra.conf
- tests/topotests/bgp_aigp/test_bgp_aigp.py
Fix several issues in sourcing AIGP attribute:
1) AIGP should not be set as default for a redistributed route or a
static network. It should be set by config instead.
2) AIGP sourced by "set aigp-metric igp-metric" in a route-map does
not set the correct value for a redistributed route.
3) When redistribute a connected route like loopback, the AGIP (with
value 0) is sourced by "set aigp-metric igp-metric", but the
attribute is not propagated as the attribute flag is not set.
> bgpd: fix several issues in sourcing AIGP attribute

- ospfd/ospf_vty.c
This is the fix of https://github.com/FRRouting/frr/issues/17039
1. no area range cost NUM, NUM can be omitted
2. no area shortcut MODE, MODE can be default, that is no area shortcut default
Closes https://github.com/FRRouting/frr/issues/17039
> ospfd: fix some ospf commands

- ospfd/ospfd.c
In the processing of nssa, if the number of areas that need to be translated is greater than 0, then abr will be regarded as asbr, and it will be marked (0x3) in the flag of router lsa. When a certain area is set from nssa to a normal area, the areas that need to be translated may be reduced. The asbr should be re-interpreted as abr when the translated area is 0.
CLOSES https://github.com/FRRouting/frr/issues/17105
> ospfd: update ospf_asbr_status when using no_area_nssa command

- lib/event.c
The frrevent system is spitting out this message in bgpd: 20:40:15 mem1-roc-f2-b1-r5-t2-d4 bgpd[13166]: [XETTR-D5MR0][EC 100663316] Attempting to process an I/O event but for fd: 214(8) no thread to handle this!
This is because as each io event is processed, it is possible that a .events is set to 0.  This can leave a situation where we ask ppoll to handle anything that happens on a fd with a .events of 0, in this situation ppoll can return POLLERR, which indicates that something bad has happened on the fd.
Let's cleanup the pfds after io events are handled that can be cleaned up.
> lib: Correctly handle ppoll pfds.events == 0

- tests/topotests/lib/topotest.py
In the cases where `sysctl_assure()` or `sysctl_atleast()` catch an error, the previous declaration of the local variable `logger` masks the global variable also called `logger` and prevents the error from being gracefully handled. Instead, the local logger is referenced before assignment which throws an unhandled error. The name of the local logger is changed to avoid this unintended behavior.
> tests: logger masked in topotest.py

- bgpd/bgp_routemap.c
- doc/user/routemap.rst
The value of 0 is accepted from peers, and can also be set by the route-map "set aigp-metric igp-metric". For consistency, it should be allowed in "set aigp-metric <value>" as well.
> bgpd: allow value 0 in aigp-metric setting

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_bmp.c
- bgpd/bgp_route.c
- bgpd/bgp_updgrp_packet.c
- tests/topotests/bgp_aigp_rr/r1/bgpd.conf
- tests/topotests/bgp_aigp_rr/r1/ospfd.conf
- tests/topotests/bgp_aigp_rr/r1/zebra.conf
- tests/topotests/bgp_aigp_rr/r2/bgpd.conf
- tests/topotests/bgp_aigp_rr/r2/ospfd.conf
- tests/topotests/bgp_aigp_rr/r2/zebra.conf
- tests/topotests/bgp_aigp_rr/r3/bgpd.conf
- tests/topotests/bgp_aigp_rr/r3/ospfd.conf
- tests/topotests/bgp_aigp_rr/r3/zebra.conf
- tests/topotests/bgp_aigp_rr/r4/bgpd.conf
- tests/topotests/bgp_aigp_rr/r4/ospfd.conf
- tests/topotests/bgp_aigp_rr/r4/zebra.conf
- tests/topotests/bgp_aigp_rr/test_bgp_aigp_rr.py
Currently the AIGP is always incremented when a route with the
attribute is advertised. That is incorrect when the nexthop is
unchanged, as is commonly the case in route reflection.
Adjust the AIGP for propagation only when the nexthop is set
to ourselves.
> bgpd: fix AIGP calculation in route advertisement

- zebra/kernel_netlink.c
After moved to dataplane, the NEWLINK/DELLINK procedure should be also removed.
> zebra: drop NEWLINK event handling in the main thread

- ospfd/ospf_vty.c
When we use the no area X.X.X.X range A.B.C.D/M command, if the area no longer has an interface to which it belongs, then the area should be deleted from the LSDB. This processing logic is consistent with instructions such as no network area and no area authentication.
> ospfd:fix the bug that the empty area was not free after no area range command was executed

- zebra/zebra_rnh.c
- zebra/zebra_vty.c
For some reasons the Linux kernel associates the ipv6 blackhole of non default table the lo interface.
> root@r1# ip -6 route show table 100
> root@r1# ip -6 route add unreachable default metric 4278198272 table 100
> root@r1# ip -6 route show table 100
> unreachable default dev lo metric 4278198272 pref medium
As a consequence, the VRF default that owns the lo interface is shown as the nexthop VRF:
> r1# show ipv6 route table 20
> Table 20:
> K>* ::/0 [255/8192] unreachable (ICMP unreachable) (vrf default), 00:18:12
Do not display the nexthop VRF of a blackhole. It does not make sense for a blackhole and it was not displayed in the past.
> zebra: fix showing nexthop vrf for ipv6 blackhole

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 10.1
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 10.1)

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 10.0
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 10.0)

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 9.1
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 9.1)

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 9.0
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 9.0)

- bgpd/bgp_label.c
- bgpd/bgp_mplsvpn.c
Fixes for valgrind issues in https://github.com/FRRouting/frr/issues/17144
Closes https://github.com/FRRouting/frr/issues/17144
> bgpd: fix uninitialized bgp_labels

- bgpd/bgp_mplsvpn.c
Fix uninitialized labels that cause multiple valgrind issues.
> ==3729602== Use of uninitialised value of size 8
> ==3729602==    at 0x492B493: hash_get (hash.c:140)
> ==3729602==    by 0x2629D2: bgp_labels_intern (bgp_label.c:98)
> ==3729602==    by 0x2E6C92: bgp_adj_out_set_subgroup (bgp_updgrp_adv.c:622)
> ==3729602==    by 0x2A6810: subgroup_process_announce_selected (bgp_route.c:3340)
> ==3729602==    by 0x2E5FF6: group_announce_route_walkcb (bgp_updgrp_adv.c:260)
> ==3729602==    by 0x2E3E28: update_group_walkcb (bgp_updgrp.c:1759)
> ==3729602==    by 0x492B9A0: hash_walk (hash.c:270)
> ==3729602==    by 0x2E498C: update_group_af_walk (bgp_updgrp.c:2090)
> ==3729602==    by 0x2E7C0D: group_announce_route (bgp_updgrp_adv.c:1119)
> ==3729602==    by 0x2A796E: bgp_process_main_one …
> bgpd: fix uninitialized labels (backport 10.0)

- pimd/pim_autorp.c
Just because there is currently no path to the RP doesn't mean it failed to add.
> pimd: PIM autorp no path RP fix

- bgpd/bgp_aspath.c
- bgpd/bgp_aspath.h
- bgpd/bgp_fsm.c
- bgpd/bgp_fsm.h
- bgpd/bgp_packet.c
- bgpd/bgp_route.c
- bgpd/bgpd.h
- zebra/kernel_netlink.c
> Optimizations and problem fixing for large scale ecmp from bgp

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 8.5
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 8.5)

- tests/topotests/lib/bmp_collector/bmp.py
- tests/topotests/lib/bmp_collector/bmpserver
- tests/topotests/lib/topogen.py
> tests: add bmpserver logging

- bgpd/bgp_route.c
- doc/user/bgp.rst
- tests/topotests/bgp_aigp_rr/r1/bgpd.conf
- tests/topotests/bgp_aigp_rr/r2/bgpd.conf
- tests/topotests/bgp_aigp_rr/test_bgp_aigp_rr.py
For consistency between RIB and BGP, the aigp comparison should be made after the local route check in bgp bestpath selection.
As a reference, that's exactly what Cisco IOS does:
https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/119001-configure-aigp-00.html
> bgpd: compare aigp after local route check in bgp_path_info_cmp()

- bgpd/bgp_nht.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/ipv6.rst
Introduce a command to completely disable sending IPv6 router advertisement messages on an interface. Before, there were cases where it could be enabled by other daemons, namely bgpd and vrrpd. Particularly, it happens when BGP extended-nexthop capability is used: bgpd tells zebra to enable RA in this case, though it wasn't intended.
Fixes #7738.
> bgpd: add bgp ipv6-auto-ra command

- bgpd/bgp_route.c
Fix the display of the local label in show bgp.
> r1# show bgp ipv4 labeled-unicast 172.16.2.2/32
> BGP routing table entry for 172.16.2.2/32, version 2
> Local label: 16 <---- MISSING
> Paths: (1 available, best #1, table default, vrf (null))
>   Advertised to non peer-group peers:
>  192.168.1.2
>  65501
>    192.168.1.2 from 192.168.1.2 (172.16.2.2)
>      Origin IGP, metric 0, valid, external, best (First path received)
>      Remote label: 3
>      Last update: Fri Oct 25 17:55:45 2024
Fixes: 67f67ba481 ("bgpd: Drop label_ntop/label_pton functions")
> bgpd: fix display of local label in show bgp

- lib/frrscript.c
- lib/frrscript.h
- zebra/zebra_vty.c
After the change:
```
$ grep on-rib-process /etc/frr/frr.conf
zebra on-rib-process script script4
$ systemctl restart frr
$ vtysh -c 'show run' | grep on-rib-process
zebra on-rib-process script script4
```
> lib, zebra: Keep `zebra on-rib-process script` in frr.conf (backport #17160)

- python/xref2vtysh.py
I simply missed that `node->cmd_vector` is needed for `find` and `list` to work correctly.
---
Fixes: #17043
Fixes: 4bc41193e810 ("vtysh, lib: preprocess CLI graphs")
> vtysh: fix `find` and `list` commands

- doc/user/zebra.rst
- zebra/debug.c
- zebra/debug.h
- zebra/zebra_srv6.c
Add a specific debug command to handle srv6 troubleshooting. Move the srv6 traces that initially were under 'debug zebra packet' debug.
> zebra: add 'debug zebra srv6' command

- ospfd/ospf_vty.c
Fix syntax of some no commands:
1. `no area virtual link A.B.C.D hello-interval <NUM>`, `<NUM>` can be omitted.
2. `no area nssa default-information-originate metric <NUM>`, `<NUM>` can be omitted.
3. `no area nssa range cost <NUM>`, `<NUM>` can be omitted.
4. `no area default cost <NUM>`, `<NUM>` can be omitted.
5. `no ospf write-multiplier <NUM>`, `<NUM>` can be omitted.
6. `no default-information originate metric <NUM>`, `<NUM>` can be omitted.
7.  `no distance <NUM>`, `<NUM>` can be omitted.
> ospfd:fix syntax of some ospf no commands

- bgpd/bgp_bmp.c
An extra blank line is added in show running-config with BMP:
> ubuntu2204hwe(config)# router bgp 65500
> ubuntu2204hwe(config-router)# bmp targets tgt
> ubuntu2204hwe(config-bgp-bmp)# bmp monitor ipv4 unicast pre-policy
> ubuntu2204hwe(config-bgp-bmp)# bmp listener 192.0.2.100 port 44
> ubuntu2204hwe(config-bgp-bmp)# do show running-config
>
> router bgp 65500
> [..]
>  bmp targets tgt
>   bmp monitor ipv4 unicast pre-policy
>                                       <-- blank line
>   bmp listener 192.0.2.100 port 44
>  exit
Remove the blank line.
Fixes: ed18356f1f2d ("bgpd/bmp: BMP implementation")
> bgpd: fix blank line in running-config with bmp listener cmd

- bgpd/bgp_snmp_bgp4v2.c
we have
(gdb) p *path->attr->aspath
$1 = {refcnt = 3, segments = 0x0, json = 0x0, str = 0x55723d0b7470 "", str_len = 0, asnotation = ASNOTATION_PLAIN}
It looks like this aspath is empty, resulting in a size 0 and NULL pointer for path->attr->aspath->segments which leads to the SIGSEGV
fixe: return 0 when segments is null.
> bgpd:  fix crash when polling bgp4v2PathAttrTable

- bgpd/bgp_mplsvpn.c
- lib/srv6.h
Manual backport of https://github.com/FRRouting/frr/pull/16835 for FRR 8.4
> bgpd, lib: Include SID structure in seg6local nexthop (backport for 8.4)

- bgpd/bgp_mplsvpn.c
- tests/topotests/bgp_vpnv4_per_nexthop_label/test_bgp_vpnv4_per_nexthop_label.py
- tests/topotests/bgp_vpnv6_per_nexthop_label/test_bgp_vpnv6_per_nexthop_label.py
When a prefix is imported using the "network" command under a vrf, which
is a connected prefix, and in the context of label allocation per
nexthop:
..
>router bgp 1 vrf vrf1
> address-family ipv4 unicast
>  redistribute static
>  network 172.16.0.1/32  <--- connected network
>  network 192.168.106.0/29
>  label vpn export auto
>  label vpn export allocation-mode per-nexthop
..
We encounter an MPLS entry where the nexthop is the prefix itself:
> 18             BGP   172.16.0.1     -
Actually, when using the "network" command, a bnc context is used, but
it is filled by using the prefix itself instead of the nexthop for other
BGP updates. Consequently, when picking up the original nexthop for
label allocation, the function behaves incorrectly. Instead ensure that
the nexthop type of …
> bgpd: fix prefix same as nexthop in label per nexthop

- isisd/isisd.c
- tests/topotests/isis_topo1/test_isis_topo1.py
Modify the implementation by referring to the "show isis vrf all interface json" command, mainly by adding vrfs nodes in the JSON.
> isisd: The command "'show isis vrf all summary json" has no output.

- bgpd/bgp_nht.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/ipv6.rst
Introduce a command to stop bgpd from enabling IPv6 router advertisement messages sending on interfaces.
---
(manual backport of #16354)
> (8.4 backport) bgpd: add `bgp ipv6-auto-ra` command

- bgpd/bgp_nht.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/ipv6.rst
Introduce a command to stop bgpd from enabling IPv6 router advertisement messages sending on interfaces.
---
(manual backport of #16354)
> (9.1 backport) bgpd: add `bgp ipv6-auto-ra` command

- bgpd/bgp_nht.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/ipv6.rst
Introduce a command to stop bgpd from enabling IPv6 router advertisement messages sending on interfaces.
---
(manual backport of #16354)
> (10.0 backport) bgpd: add `bgp ipv6-auto-ra` command

- bgpd/bgp_nht.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/ipv6.rst
Introduce a command to stop bgpd from enabling IPv6 router advertisement messages sending on interfaces.
---
manual backport of #16354
> (10.1 backport) bgpd: add `bgp ipv6-auto-ra` command

- bgpd/bgp_attr.c
- bgpd/bgp_route.c
- bgpd/bgpd.h
a) Make attribute hash faster?  convert jhash_1word to jhash_3words so we make less calls
b) Extend `show bgp attribute-info` to dump more data
c) Gather some data around how many times path_info_cmp is called and how many times we double enqueue and defer enqueuing.
> Bgp musings

- doc/developer/conf.py
- doc/user/conf.py
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/frrouting/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 529, in eval_config_file
exec(code, namespace)  # NoQA: S102
^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/frrouting/checkouts/latest/doc/user/conf.py", line 77, in <module>
html_context["READTHEDOCS"] = True
^^^^^^^^^^^^
NameError: name 'html_context' is not defined
> doc: Create html_context before setting READTHEDOCS

- tests/topotests/conftest.py
In the case that that hard limit of `RLIMIT_CORE` cannot be increased (e.g. in this case can't be changed to `RLIM_INFINITY`), `setrlimit` will throw an unhandled `ValueError` that prematurely ends pytest. This commit catches the error, and then attempts to maximize the soft limit while respecting the hard limit value that it can't exceed.
> tests: respect RLIMIT_CORE hard limit

- doc/user/zebra.rst
- tests/topotests/zebra_rib/r1/frr-import.conf
- tests/topotests/zebra_rib/r1/import_init_mrib_table.json
- tests/topotests/zebra_rib/r1/import_init_table.json
- tests/topotests/zebra_rib/r1/import_mrib_table_2.json
- tests/topotests/zebra_rib/r1/import_mrib_table_3.json
- tests/topotests/zebra_rib/r1/import_mrib_table_4.json
- tests/topotests/zebra_rib/r1/import_table_2.json
- tests/topotests/zebra_rib/r1/import_table_3.json
- tests/topotests/zebra_rib/r1/import_table_4.json
- tests/topotests/zebra_rib/test_zebra_import.py
- zebra/redistribute.c
- zebra/redistribute.h
- zebra/zebra_rib.c
- zebra/zebra_routemap.c
- zebra/zebra_routemap.h
- zebra/zebra_vty.c
Added a mrib flag to the `import-table ...` command to allow importing into the main MRIB table. Piped through specifying the safi in the import code rather than assuming/hardcoding the unicast safi.
> Add support to import alternate URIB tables into the main MRIB

- bgpd/bgp_packet.c
- bgpd/bgp_route.c
- bgpd/bgpd.h
Just a bunch of stuff to try to make bgp_update() more efficient.  It's the long poll in processing each bgp_path_info from a peer.  The more peers and routes you ahve the more time is spent in bgp_update().  These don't really provide a huge improvement, but it's incremental and I don't think anythng was done that is going to cause problems for understanding or maintainability
> Bgp update optimizations

- ospfd/ospfd.c
This reverts commit 71aa5ab7f6f166065e3b869e3c33ba5b7a57fccb.
This commit was causing frequent master ci run failures.  Author has not responded and since I do not know which of the two problems we have here is better, I would rather go with the known original problem
> Revert "ospfd: update ospf_asbr_status when using no_area_nssa command"

- lib/wheel.c
- lib/wheel.h
With commit:
60a3efec2458d9a1531f8204d0e4a91729d3fc00
The ability for the wheel code to display the name of what wheel was actually being run was removed from the system. Since we can no longer do this and it's been 4 years since it's been in, let's just remove this bit of dead code.
> lib: Remove wheel name it is no longer used

- doc/user/ospfd.rst
- lib/libospf.h
- ospfd/ospf_lsa.c
- ospfd/ospf_lsa.h
- ospfd/ospf_opaque.c
- ospfd/ospf_vty.c
The configured OSPF refresh interval was not being used for opaque LSA (it always used the constant). Also, modified the timers lsa min-arrival command to have a maximum of 5000 msecs as well as providing a path for backward command compatibility.
Added missing user documentation for both timers lsa min-arrival and timers throttle lsa all.
> ospfd: Fix opaque LSA refresh interval and modify LSA cmds.

- zebra/zebra_srv6.c
`ZEBRA_DEBUG_SRV6` is not the correct macro to evaluate if SRv6 debug is enabled or not.
The correct macro is `IS_ZEBRA_DEBUG_SRV6`.
Fix this by replacing `ZEBRA_DEBUG_SRV6` with `IS_ZEBRA_DEBUG_SRV6`.
> zebra: Fix incorrect debug macros

- zebra/main.c
- zebra/zebra_ns.c
- zebra/zebra_router.h
Recent commits have moved zebra's nexthop group cache entries to be figured out after the dplane has started up. As such this leaves us with a situation where the cache entries startup time *can* be/is greater than the startup time for the purposes of graceful restart.  Just notice that we are in startup mode and do the right thing.
> zebra: On startup actually allow for nhe's to be early

- nhrpd/nhrp_peer.c
- nhrpd/nhrp_protocol.h
- nhrpd/nhrp_vty.c
- tests/topotests/nhrp_topo/r1/nhrp_shortcut_present.json
- tests/topotests/nhrp_topo/r1/zebra.conf
- tests/topotests/nhrp_topo/r2/nhrp4_cache.json
- tests/topotests/nhrp_topo/r2/nhrp_route4.json
- tests/topotests/nhrp_topo/r2/zebra.conf
- tests/topotests/nhrp_topo/r4/nhrp4_cache.json
- tests/topotests/nhrp_topo/r4/nhrp_route4.json
- tests/topotests/nhrp_topo/r4/nhrpd.conf
- tests/topotests/nhrp_topo/r4/zebra.conf
- tests/topotests/nhrp_topo/test_nhrp_topo.py
Modified nhrp_topo topotest to test for newly added resolution request retry feature
Modified nhrp_connection_authorized() function so that debugging messages don't read into NHRP authentication extension as if it were a null-terminated string - which can lead to  printing of non ASCII-compliant bytes.
Moved CISCO_PASS_LENGTH_LEN from nhrp_vty.c to nhrp_protocol.h for easier access  to the macro in other files
> nhrpd: fix passphrase handling, add topotest for resolution request

- zebra/table_manager.h
- zebra/zebra_vrf.c
- zebra/zebra_vty.c
Currently when doing a `show ip route table XXXX`, zebra is displaying the current default vrf as the vrf we are in.  We are displaying a table not a vrf.  This is only true if you are not using namespace based vrf's, so modify the output to display accordingly.
> zebra: Don't display the vrf if not using namespace based vrfs

- tests/topotests/zebra_multiple_connected/r1/ip_route_kernel_blackhole.json
- tests/topotests/zebra_multiple_connected/test_zebra_multiple_connected.py
- zebra/zebra_rib.c
The `rib_update_handle_kernel_route_down_possibility()` didn't consider the kernel routes ( blackhole )  without interface.  When some other interfaces are down, these kernel routes will be wrongly removed.
> zebra: fix missing kernel routes

- ospfd/ospf_lsa.c
Under certain timing conditions, the current logic asserts in ospf_lsa_refresh_delay(). While this isn't readily reproducible, the only explanation is that the conversion from struct timeval to milliseconds is 0 due to rounding off the microseconds.
> ospfd: Fix assert in LSA refresh interval setting

- ospf6d/ospf6_intra.c
Fix defect flagged by Coverity:
```
*** CID 1599957:  Null pointer dereferences  (REVERSE_INULL) /ospf6d/ospf6_intra.c: 581 in ospf6_link_lsa_get_prefix_str()
575                                                int buflen, int pos)
576     {
577             struct ospf6_link_lsa *link_lsa = lsa_after_header(lsa->header);
578             struct ospf6_prefix *prefix = nth_prefix(lsa->header, pos);
579             struct in6_addr in6 = { 0 };
580
>>>     CID 1599957:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "lsa" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
581             if (!lsa || !prefix || !buf || buflen < (1 + INET6_ADDRSTRLEN))
582                     return NULL;
583
584             /* position zero is …
```
> ospf6d: remove redundant null ptr check in ospf6_link_lsa_get_prefix_str() - CID 1599957

- ospf6d/ospf6_intra.c
Fix defect flagged by Coverity:
```
*** CID 1599962:  Null pointer dereferences  (REVERSE_INULL) /ospf6d/ospf6_intra.c: 775 in ospf6_intra_prefix_lsa_get_prefix_str()
769     {
770             struct ospf6_prefix *prefix = nth_prefix(lsa->header, pos);
771             struct in6_addr in6 = { 0 };
772             char tbuf[16];
773
774             /* ensure buflen >= INET6_ADDRSTRLEN + '/128\0' */
>>>     CID 1599962:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "lsa" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
775             if (!lsa || !prefix || !buf || buflen < (5 + INET6_ADDRSTRLEN))
776                     return NULL;
777
778             memcpy(&in6, OSPF6_PREFIX_BODY(prefix),
779 …
```
> ospf6d: remove redundant null ptr check

- doc/user/routemap.rst
- lib/routemap.c
- lib/routemap.h
- tests/topotests/all_protocol_startup/r1/show_route_map.ref
- tests/topotests/all_protocol_startup/test_all_protocol_startup.py
- tests/topotests/zebra_rib/r1/sharp_rmap.ref
- tests/topotests/zebra_rib/r1/static_rmap.ref
- tests/topotests/zebra_rib/test_zebra_rib.py
Add some ability to the `show route-map` command to track how much time was spent in each section and total time for the route-map
> lib: Add ability to track time in individual routemaps

- bgpd/bgp_ecommunity.c
- bgpd/bgp_ecommunity.h
- doc/user/bgp.rst
- tests/topotests/bgp_color_extcommunities/r1/bgpd.conf
- tests/topotests/bgp_color_extcommunities/test_bgp_color_extcommunities.py
- yang/frr-bgp-route-map.yang
Add support of color extended community color-only types, RFC 9256.
The type only support 00 01 10.
configuration example:
!
frr version 10.3-dev-my-manual-build
hostname router3
!
route-map color permit 1
set extcommunity color 10:100 01:200 00:300
exit
!
vrf Vrf1
exit-vrf
!
interface lo
ipv6 address 3::3/128
exit
!
router bgp 3
bgp router-id 3.3.3.3
bgp log-neighbor-changes
no bgp default ipv4-unicast
bgp bestpath as-path multipath-relax
timers bgp 10 30
neighbor 100.13.13.1 remote-as 1
neighbor 100.13.13.1 advertisement-interval 0
neighbor 100.23.23.2 remote-as 2
neighbor 100.23.23.2 advertisement-interval 0
neighbor 1000:3000::1 remote-as 1
neighbor 1000:3000::1 ebgp-multihop
neighbor 1000:3000::1 update-source 1000:3000::3
neighbor …
> bgpd:support of color extended community color-only types

- bgpd/bgp_vty.c
- bgpd/bgpd.c
- tests/topotests/bgp_tcp_mss/r1/bgpd.conf
- tests/topotests/bgp_tcp_mss/r1/zebra.conf
- tests/topotests/bgp_tcp_mss/r2/bgpd.conf
- tests/topotests/bgp_tcp_mss/r2/zebra.conf
- tests/topotests/bgp_tcp_mss/test_bgp_tcp_mss.py
support tcp-mss for neighbor group
> bgpd:support tcp-mss for neighbor group

- bgpd/bgp_route.c
- tests/topotests/bgp_route_map_match_source_protocol/test_bgp_route_map_match_source_protocol.py
A redistribute cmd can have a route-map attached to it and adding the match source-protocol to that route-map means BGP to filter which protocol routes to accept among the bunch of routes zebra is sending.
Fixing this since this wasnt implemented earlier.
Ticket :#4119692
> bgpd: Fix for match source-protocol in route-map for redistribute cmd

- bgpd/bgp_route.c
A redistribute cmd can have a route-map attached to it and adding the match source-protocol to that route-map means BGP to filter which protocol routes to accept among the bunch of routes zebra is sending.
Fixing this since this wasnt implemented earlier.
Ticket :#4119692
Signed-off-by: Rajasekar Raja <rajasekarr@nvidia.com>
(cherry picked from commit 68358c0f928eafe50c9e73b0cb6a443c03f2a33f)
> bgpd: Fix for match source-protocol in route-map for redistribute cmd (backport)

- bgpd/bgp_bfd.c
- bgpd/bgp_fsm.c
- bgpd/bgpd.c
- tests/topotests/bgp_bfd_session/r1/frr.conf
- tests/topotests/bgp_bfd_session/test_bgp_bfd_session.py
Closes https://github.com/FRRouting/frr/issues/17396
Closes https://github.com/FRRouting/frr/issues/17408
> BGP BFD session things

- tests/topotests/bgp_vpnv4_asbr/test_bgp_vpnv4_asbr.py
Clarify bgp_vpnv4_asbr. Cosmetic change.
> tests: clarify bgp_vpnv4_asbr

- isisd/isis_route.h
- lib/if.c
- lib/if.h
- zebra/if_netlink.c
- zebra/interface.c
- zebra/interface.h
- zebra/zebra_evpn.c
- zebra/zebra_evpn.h
- zebra/zebra_ns.c
- zebra/zebra_ns.h
- zebra/zebra_vxlan.c
Replace the "lib/table" based per-NS collection of interfaces with a dedicated rbtree. Convert all the code that uses the if_table directly to use new iterator apis.
> zebra, lib: use internal rbtree for per-NS tree of ifps

- debian/control
Configure fails without libprotobuf-dev package. protobuf-compiler package recommends libprotobuf-dev, but this is a soft-dependency, so it needs to be added explicitly.
Also correct tabs/spaces issues introduced by the original patch.
> debian: Add missing libprotobuf-dev to grpc profile

- bgpd/bgp_route.c
Closes https://github.com/FRRouting/frr/issues/17421
> bgpd: Show neighbor advertised paths including addpath

- zebra/zebra_evpn.c
Guard a debug in the evpn code.
> zebra: fix unguarded debug in evpn code

- bgpd/bgp_ecommunity.c
Previous work to separate out 'color' ecomm parsing made a test unreachable; coverity SA reported it.
> bgpd: Fix color extended community parsing

- zebra/zebra_evpn.c
- zebra/zebra_vxlan.c
> Zebra debug assert

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn.h
In cases such as 'no advertise-all-vni' and L2 VNI DELETE, we need to pop all the VPN routes present in the bgp_zebra_announce FIFO yet to be processed regardless of VNI is configured or not.
NOTE: NO need to pop the VPN routes in two cases
1) In free_vni_entry
- Called by bgp_free()->bgp_evpn_cleanup().
- Since bgp_delete is called before bgp_free and we pop all the dest pertaining to bgp under delete. 2) evpn_delete_vni() when user configures "no vni" since the withdraw of all routes happen in normal cycle.
Fixes: a07df6f7548f6bd1b92acbb7a10c3823de33fe5f
("bgpd : backpressure - Handle BGP-Zebra(EPVN) Install evt Creation")
Ticket :#4163611
> bgpd : backpressure - Fix to pop items off zebra_announce FIFO for few EVPN triggers

- doc/user/pimv6.rst
- pimd/pim6_cmd.c
- pimd/pim6_cmd.h
- pimd/pim6_mld.c
- pimd/pim_ifchannel.c
- pimd/pim_instance.c
- pimd/pim_instance.h
- pimd/pim_join.c
- pimd/pim_mroute.c
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- pimd/pim_rp.c
- pimd/pim_rp.h
- pimd/pim_tib.c
- pimd/pim_vty.c
- tests/topotests/pim_embedded_rp/r1/frr.conf
- tests/topotests/pim_embedded_rp/r2/frr.conf
- tests/topotests/pim_embedded_rp/r3/frr.conf
- tests/topotests/pim_embedded_rp/test_pim_embedded_rp.py
- yang/frr-pim-rp.yang
Implement embedded RP support and configuration commands.
Embedded RP is disabled by default and can be globally enabled with the command `embedded-rp`. It supports the following options:
- Embedded RP maximum limit
- Embedded RP group filtering
For more information please read the [RFC 3956](https://www.rfc-editor.org/rfc/rfc3956).
---
To do list before merge:
> pim6d: support embedded-rp

- bgpd/bgp_route.c
- tests/topotests/bgp_invalid_nexthop/exabgp.env
- tests/topotests/bgp_invalid_nexthop/peer1/exabgp.cfg
- tests/topotests/bgp_invalid_nexthop/r1/frr.conf
- tests/topotests/bgp_invalid_nexthop/test_bgp_invalid_nexthop.py
Closes https://github.com/FRRouting/frr/issues/17308
> bgpd: Validate both nexthop information (NEXTHOP and NLRI)

- doc/accords/frr-name-use
This attempts to establish a little bit of clarifying restrictions around the FRRouting "identifiers", mostly as a reaction to FRRouting now functioning almost like a "seal of approval" in some cases.
---
We discussed this a few weeks ago on Slack (and I forgot I wanted to post this); there was rough agreement but the devil is probably in the details.
> accords: guidelines/terms for FRRouting trademarks

- debian/rules
- redhat/frr.spec.in
Closes https://github.com/FRRouting/frr/issues/17365
> packaging: Use PCRE2 for .deb/.rpm builds

- pimd/pim_rp.c
Fix Coverity Scan CID 1601875: use the return value to tell user about the availability of a next hop to the learned RP (needs debug enabled).
> pim6d: fix coverity scan warning

- bgpd/bgp_route.c
If we receive an IPv6 prefix e.g.: 2001:db8:100::/64 with nextop: 0.0.0.0, and mp_nexthop: fc00::2, we should not treat this with an invalid nexthop because of 0.0.0.0. We MUST check for MP_REACH attribute also and decide later if we have at least one a valid nexthop.
(cherry picked from commit a0d2734e879f78fbef5f1815429de331b9940c73)
> bgpd: Validate both nexthop information (NEXTHOP and NLRI) (backport)

- isisd/isis_tlvs.c
When the segment-routing ipv6 is configured, the SPF algoritm shows S-SPF is used:
> rt1# show isis segment-routing srv6 node
> Area 1:
>  IS-IS L1 SRv6-Nodes:
>
> System ID       Algorithm  SRH Max SL  SRH Max End Pop  SRH Max H.encaps  SRH Max End D
> -----------------------------------------------------------------------------------------
> 0000.0000.0001  S-SPF        3           3                2                 5
Actually, the segment-routing ipv6 algo capabilities displayed from router_capability_tlv. Display the segment-routing ipv6 algo capabilities from locator_tlv
Initialize sub tlv "algorithm" in the "locator" tlv with SR_ALGORITHM_SPF value.
> rt1# show isis segment-routing srv6 node
> Area 1:
>  IS-IS L1 SRv6-Nodes:
>
> System ID       Algorithm  SRH Max SL  SRH Max End Pop …
> isisd: properly display srv6 algorithm

- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_msdp_socket.c
Two small MSDP improvements:
- Reduce MSDP data structure size
- Constify function
> pimd: two small improvements

- ospfd/ospf_asbr.c
- ospfd/ospf_asbr.h
- ospfd/ospf_lsa.c
- ospfd/ospf_vty.c
- ospfd/ospf_zebra.c
- ospfd/ospf_zebra.h
- tests/topotests/ospf_multi_instance/r1/frr.conf
- tests/topotests/ospf_multi_instance/r2/frr.conf
- tests/topotests/ospf_multi_instance/r3/frr.conf
- tests/topotests/ospf_multi_instance/test_ospf_multi_instance.py
When originating a default AS-External LSA in one OSPF instance, it wasn't working if the criteria route was installed by another OSPF instance. This required more flexible processing of the OSPF external route information.
> ospfd: OSPF multi-instance default origination fixes

- tools/etc/frr/support_bundle_commands.conf
I've been slowly adding to my local support bundle generation but have failed to upload it.  Let's get this in so that other people can take advantage of this as well.
> Support bundle isis

- tests/topotests/ospf_instance_redistribute/test_ospf_instance_redistribute.py
Upon high load the ospf_instance_redistribute test can attempt to install routes with sharpd before the connected routes have fully baked themselves into zebra.  Since sharpd intentionally has no retry mechanism we need to ensure that the test is waiting a small bit.
> tests: Ensure connected routes are installed before continuing

- tools/etc/frr/support_bundle_commands.conf
Add more data gathering for pim and pim6 support bundles
> tools: Add pim show commands to support bundle

- bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/17485
> bgpd: Do not reset peers on suppress-fib toggling

- lib/nexthop.c
- lib/nexthop.h
- zebra/zebra_mpls.c
In zebra_mpls.c it has a usage of MTYPE_NH_LABEL which is defined in both lib/nexthop.c and zebra/zebra_mpls.c.  The usage in zebra_mpls.c is a realloc.  This leads to a crash:
(gdb) bt
0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=126487246404032) at ./nptl/pthread_kill.c:44 1  __pthread_kill_internal (signo=6, threadid=126487246404032) at ./nptl/pthread_kill.c:78 2  __GI___pthread_kill (threadid=126487246404032, signo=signo@entry=6) at ./nptl/pthread_kill.c:89 3  0x0000730a1b442476 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26 4  0x0000730a1b94fb18 in core_handler (signo=6, siginfo=0x7ffeed1e07b0, context=0x7ffeed1e0680) at lib/sigevent.c:268 5  <signal handler called>
6  __pthread_kill_implementation (no_tid=0, signo=6, threadid=126487246404032) at …
> lib, zebra: Do not have duplicate memory type problems

- tools/frr-reload.py
Add missing keywords `segment-routing srv6` and `node-msd` in  frr-reload.
Fix the errors below:
```
[58564|mgmtd] sending configuration
[58565|zebra] sending configuration,
line 10: % Unknown command[52]:  node-msd
[58573|isisd] sending configuration
[58565|zebra] Configuration file[/etc/frr/frr.conf] processing failure: 2
```
```
[58564|mgmtd] sending configuration
[58565|zebra] sending configuration,
line 14: % Unknown command[52]:  max-segs-left 3
line 18: % Unknown command[52]:  max-end-pop 3
line 22: % Unknown command[52]:  max-h-encaps 2
line 26: % Unknown command[52]:  max-end-d 5
[58573|isisd] sending configuration
[58565|zebra] Configuration file[/etc/frr/frr.conf] processing failure: 2
```
> tools: Add missing keywords in frr-reload

- ospfd/ospf_sr.c
When OSPFd starts, there is 2 possible scenarios for Segment Routing: 1/ Routes associated to Prefixes are not yet available i.e. Segment Routing LSA are received before LSA Type 1. In this case, the function ospf_sr_nhlfe_update() is triggered when a new SPF is launch. Thus, neighbors and output label are always synchronise with the routing table. 2/ Routes are already available i.e. LSA Type 1 are received before Segment Routing LSA, in particular the Router Information which contains the SRGB. During nhlfe computation, perfixes are leave with incomplete configuration, in particular, the SR nexthop is set to NULL. If this scenario is handle through the function update_out_nhlfe (triggered when SRGB is received or modified from a neighbor node), the output label is not correctly …
> ospfd: Correct invalid SR-MPLS output label

- tools/frr-reload.py
Consider the following scenario.
You start from the configuration below:
```
!
srv6
encapsulation
source-address fc00:0:1::1
!
!
!
```
Then you change the source address:
```
r1# configure
r1(config)# segment-routing
r1(config-sr)# srv6
r1(config-srv6)# encapsulation
r1(config-srv6-encap) source-address 1::1
```
And finally, reload the configuration
`python3 frr-reload.py --reload /etc/frr/frr.conf`
frr-reload returns the error below:
```
Failed to execute segment-routing  srv6   no source-address 1::1  exit exit
"segment-routing --  srv6 --   no source-address 1::1 --  exit -- exit" we failed to remove this command
% Unknown command:   no source-address 1::1
[79975|mgmtd] sending configuration
line 3: % Unknown command[76]:   source-address fc00:0:1::1
[79975|mgmtd] …
```
> tools: Add missing keyword `encapsulation` in frr-reload

- bgpd/bgp_route.c
The json display of the version attribute is originally an integer. It has changed, most probably mistakenly.
> {
>   "vrfId": 7,
>   "vrfName": "vrf1",
>   "tableVersion": 3,
>   "routerId": "192.0.2.1",
>   "defaultLocPrf": 100,
>   "localAS": 65500,
>   "routes": {
>     "172.31.0.1/32": {
>       "prefix": "172.31.0.1/32",
>       "version": "1",		<--- int or string ??
Let us fix it, by using the integer display instead.
Fixes: f9f2d188e398 ("bgpd: fix 'json detail' output structure")
> bgpd: fix version attribute is an int, not a string

- zebra/dplane_fpm_nl.c
During zebra shutdown, the main pthread in fpm_nl_finish_early() and the FPM pthread can deadlock if the FPM pthread is in fpm_reconnect(). Each pthread tries to use event_cancel_async() to cancel tasks that may be scheduled for the other pthread - this leads to deadlock as neither thread can progress.
This adds an atomic boolean that's managed as each pthread enters and leaves the cleanup code in question, preventing the two threads from running into the deadlock.
> zebra: avoid a race during FPM dplane plugin shutdown

- bfdd/bfd.c
- bfdd/bfd.h
Fixes #16594.
Lets avoid a performance penalty in forwarding when not using the BFD echo feature. The echo socket uses raw packet capturing along with a BPF filter which causes performance issues.
> bfdd: disable echo socket when not using it

- isisd/isis_circuit.c
- isisd/isis_pdu.c
- tests/topotests/isis_topo1/test_isis_topo1.py
Test Scenario:
RouterA and RouterB are in the same routing domain and have configured a P2P link. RouterA is configured with "is-type level-1" while RouterB is configured with "is-type level-1-2". They establish a level-1 UP neighborship. In this scenario, we expect that when RouterB's configuration is switched to "is-type level-2-only", the neighborship status on both RouterA and RouterB would be non-UP. However, RouterB still shows the neighbor as UP.
Upon receiving a P2P Hello packet, the function `process_p2p_hello()` is invoked. According to the ISO/IEC 10589 protocol specification, section 8.2.5.2 a) and tables 5 and 7, if the `iih->circ_type` of the neighbor's hello packet does not match one's own `circuit->is_type`, we may choose to take no action. When establishing a neighborship …
> isisd: When the ISIS types of the routers do not match on a P2P link, the neighbor status remains UP

- tools/frr_babeltrace.py
- zebra/rt_netlink.c
- zebra/zebra_vxlan.c
- zebra/zebra_vxlan_if.c
The issue is when bridge flap lead to failure of Type-2/Type-3 route installation.
Upon VxLAN device flap, the associated vlan-vni mapping is processed
before the VxLAN device up netlink notification.
Fix:
When VLAN-VNI mapping is updated, do not set the L2VNI up event
if the associated VXLAN device is not up. This may result in bgp
synced remote routes to skip installing in Zebra and onwards (Kernel).
> zebra: fix EVPN check vxlan oper up in vlan mapping

- bgpd/bgp_flowspec_vty.c
There is an extra space in the 'Displayed' line of show bgp command, that should not be present.
Fix this by being consistent with the output of the other address families.
Fixes: ("a1baf9e84f71") bgpd: Use single whitespace when displaying show bgp summary
> bgpd: fix use single whitespace when displaying flowspec entries

- bgpd/bgp_fsm.c
- bgpd/bgp_network.c
- bgpd/bgp_network.h
- bgpd/bgp_nexthop.c
- bgpd/bgp_packet.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
I have started another round of converting the `struct peer` doppelganger away and found some more functions that should properly be connection oriented.  Move them over.  I also made some code changes to make the coding pattern in bgp to be a bit better.
> More found connection conversion issues

- doc/user/bgp.rst
Fix: doc build issues
Introduces these new doc build issues:
```
/home/sharpd/frr4/doc/user/bgp.rst:2942: WARNING: Unexpected indentation.
/home/sharpd/frr4/doc/user/bgp.rst:2943: WARNING: Block quote ends without a blank line; unexpected unindent.
```
> doc:Fix bgp doc warning

- bgpd/bgp_nht.c
When receiving an SRv6 BGP update, the nexthop tracking is used to find out the reachability of the BGP update.
> # show bgp ipv6 vpn fd00:200::/64
> Paths: (1 available, best #1)
> [..]
>     4:4::4:4 from 4:4::4:4 (4.4.4.4)
>       Origin incomplete, metric 0, localpref 100, valid, internal, best (First path received)
>       Extended Community: RT:52:100
>       Remote label: 16
>       Remote SID: 2001:db8:f4::
>       Last update: Mon Mar 11 11:50:04 2024
The IPv6 address used is the "Remote SID". Actually, this value is incomplete. Remote SID stands for the attribute value received in BGP, while the label value determines a complement of SRv6 SID value. The transposition technique authorises that in BGP, and in the above case, the incoming BGP update has used the transposition …
> bgpd: fix use real SID in BGP nexthop tracking

- docker/ubuntu-ci/Dockerfile
This PR adds the ability to override the UID of the FRR user with the additional docker argument `--build-arg=UID=$(id -u)`.
When using docker containers to develop FRR, it is much easier to manage copying files in and out of the container if the UID of the FRR user is also the same as the user that created the container.
For reference, I use the following commands to create my local development container:
```
docker build -t $(whoami)-$(basename `/bin/pwd`)-frr-ubuntu20:latest --build-arg=UBUNTU_VERSION=20.04 --build-arg=UID=$(id -u) -f docker/ubuntu20-ci/Dockerfile .
docker run --init -it --privileged --name $(whoami)-$(basename `/bin/pwd`)-frr-ubuntu20 -v /lib/modules:/lib/modules -v `/bin/pwd`:/home/frr/frr $(whoami)-$(basename `/bin/pwd`)-frr-ubuntu20:latest bash
docker start …
```
> Docker: Add the ability to override the FRR UID during docker creation

- nhrpd/nhrp_vty.c
> nhrpd: fix show ip nhrp output

- bgpd/bgpd.c
- tests/topotests/bgp_peer_group/r1/frr.conf
- tests/topotests/bgp_peer_group/r4/frr.conf
- tests/topotests/bgp_peer_group/test_bgp_peer-group.py
Closes https://github.com/FRRouting/frr/issues/17541
> bgpd: Fix remote-as with peer-group

- zebra/main.c
- zebra/zserv.c
- zebra/zserv.h
It sounds from #16747 as if it's possible for zebra to get privs wrong when it sets up its zapi server socket when running in privs-per-process mode. The current zserv code opens and starts listening on that server socket pretty late during startup, since zebra needs to be ready to do what clients start asking it to do.
This PR separates zebra's ZAPI server socket handling into two phases: an early phase that opens the socket, and a later phase that starts listening for client connections. The early 'open' phase is called quite early, before other zebra subsystems are started. The 'start' phase is still called later on.
> zebra: separate zebra ZAPI server open and accept

- pimd/pimd.c
Reset access-lists in pimd on terminate
> pimd: Fix access-list memory leak in pimd

- lib/bfd.c
Currently if you have this sequence of events:
a) BGP starts
b) BGP reads cli that has bfd configuration
c) BGP attempts to install bfd configuration but fails because zebra is not connected to yet
d) BGP connects to zebra
e) BGP receives resend bfd code from bfdd
f) BGP was not sending down the unsent data to bfd, never causing the bfd session to be established.
So effectively bfd was attempting to install but failed and then when it was asked to replay everything it decided that the bfd information for a particular peer was actually installed and does not need to be resent.  Modify the code such that the bfd code now tracks failed installation and allows the resend of data to bfdd.
> lib: Fix session re-establishment

- lib/sockopt.c
- lib/sockopt.h
- lib/vty.c
- lib/vty.h
- vtysh/vtysh.c
See individual commits, but this should fix the freebsd issue being seen on not being able to connect via vtysh.
> Fix bsd sockopt problem

- lib/routemap.c
- lib/routemap.h
This would give maybe more information on what's going (`Route-map: (null) ...`) on with https://github.com/FRRouting/frr/issues/17552.
> lib: Print the reason why the route-map and/or the index parsing is done

- pimd/pim_vty.c
> pimd: igmp proxy joins should not be written as part of config

- pimd/pim_autorp.c
If the socket associated with the auto-rp fails to initialize then the memory for the auto-rp is just dropped on the floor.  Additionally any type of attempt at using the feature will just cause pimd to crash, when the pointer is derefed.  Since it is derefed all over the place without checking.
Clearly if you cannot bind/use the socket let's allow continuation.
Fixes: #17540
> pimd: Prevent crash of pim when auto-rp's socket is not initialized

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- tests/topotests/msdp_topo1/test_msdp_topo1.py
- yang/frr-pim.yang
Allow user to temporarily shutdown MSDP sessions without removing any configuration.
> pimd: implement MSDP shutdown command

- bgpd/bgp_vty.c
The below command is not successfull on an existing as dot peer
> no neighbor 10.0.0.2 remote-as 1.1
> % Create the peer-group or interface first
Handle the case where the remote-as argument can be an ASNUM.
Fixes: 8079a4138d61 ("lib, bgp: add initial support for asdot format")
> bgpd: fix unconfigure asdot neighbor

- bgpd/bgp_vty.c
The below command is not successfull on an existing as dot peer
> no neighbor 10.0.0.2 remote-as 1.1
> % Create the peer-group or interface first
Handle the case where the remote-as argument can be an ASNUM.
Fixes: 8079a4138d61 ("lib, bgp: add initial support for asdot format")
> bgpd: fix unconfigure asdot neighbor (backport)

- bgpd/bgp_bmp.c
- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/test_bgp_bmp_1.py
- tests/topotests/bgp_bmp/test_bgp_bmp_2.py
At startup, there is no peer up message for loc-rib instance peer. Instead, a global peer up message with address 0.0.0.0 is sent.
Such message is wrong, violates the RFC and should be dropped by a strict collector. Actually, the peer type message sent is wrong, and should be set to LOC-RIB peer type.
Fix this by changing the peer type of peer up message to either loc-rib or global instance peer type.
Fixes: 035304c25a38 ("bgpd: bmp loc-rib peer up/down for vrfs")
> bgpd: fix peer up message for loc-rib not sent

- bgpd/bgp_route.c
This would give maybe more information on what's going (`Route-map: (null) ...`) on with https://github.com/FRRouting/frr/issues/17552.
> bgpd: Show which route-map is used when the prefix is filtered by route-map

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- tests/topotests/msdp_topo1/test_msdp_topo1.py
- yang/frr-pim.yang
MSDP feature to help limit the amount of SAs a peer can learn. This is useful to keep the amount of SAs to a certain amount or to handle misconfigured peers.
> pimd: MSDP per peer SA limit

- bgpd/bgp_zebra.c
Although trigger unknown, based on the backtrace in one of the internal testing, we do see some delete in the Intf where we can have the peer ifp pointer null and we try to dereference it while trying to install the route leading to a crash
Skip updating the ifindex in such cases and since the nexthop is not properly updated, BGP skips sending it to zebra.
BackTrace:
```
0  0x00007faef05e7ebc in ?? () from /lib/x86_64-linux-gnu/libc.so.6 1  0x00007faef0598fb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6 2  0x00007faef09900dc in core_handler (signo=11, siginfo=0x7ffdde8cb4b0, context=<optimized out>) at lib/sigevent.c:274 3  <signal handler called>
4  0x00005560aad4b7d8 in update_ipv6nh_for_route_install (api_nh=0x7ffdde8cbe94, is_evpn=false, best_pi=0x5560b21187d0, pi=0x5560b21187d0, …
```
> bgpd: Fix bgp core with a possible Intf delete

- bgpd/bgp_zebra.c
Although trigger unknown, based on the backtrace in one of the internal testing, we do see some delete in the Intf where we can have the peer ifp pointer null and we try to dereference it while trying to install the route leading to a crash
Skip updating the ifindex in such cases and since the nexthop is not properly updated, BGP skips sending it to zebra.
BackTrace:
0  0x00007faef05e7ebc in ?? () from /lib/x86_64-linux-gnu/libc.so.6 1  0x00007faef0598fb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6 2  0x00007faef09900dc in core_handler (signo=11, siginfo=0x7ffdde8cb4b0, context=<optimized out>) at lib/sigevent.c:274 3  <signal handler called>
4  0x00005560aad4b7d8 in update_ipv6nh_for_route_install (api_nh=0x7ffdde8cbe94, is_evpn=false, best_pi=0x5560b21187d0, pi=0x5560b21187d0, …
> bgpd: Fix bgp core with a possible Intf delete (backport)

- bgpd/bgp_bmp.c
- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/bmp1vrf/bmp-update-loc-rib-step1.json
- tests/topotests/bgp_bmp/bmp1vrf/bmp-update-post-policy-step1.json
- tests/topotests/bgp_bmp/bmp1vrf/bmp-update-pre-policy-step1.json
- tests/topotests/bgp_bmp/bmp1vrf/bmp-withdraw-loc-rib-step1.json
- tests/topotests/bgp_bmp/bmp1vrf/bmp-withdraw-post-policy-step1.json
- tests/topotests/bgp_bmp/bmp1vrf/bmp-withdraw-pre-policy-step1.json
- tests/topotests/bgp_bmp/r1vrf/frr.conf
- tests/topotests/bgp_bmp/test_bgp_bmp_2.py
Today, only global instance per peer header messages are used.
This set of commits makes possible to send per peer header on a VRF instance, and send RD instance messages instead with its proper peer distinguisher value.
> BMP Peer Distinguisher support

- pimd/pim_instance.c
- pimd/pim_instance.h
- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_nb_config.c
- pimd/pim_register.c
- pimd/pim_rp.c
- pimd/pim_upstream.c
- pimd/pim_upstream.h
- pimd/pim_vty.c
Move all MSDP code possible to its own files and guard MSDP code from being compiled in PIMv6.
> pimd: clean up MSDP code

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_msdp_packet.c
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- tests/topotests/msdp_topo3/r1/frr.conf
- tests/topotests/msdp_topo3/r2/frr.conf
- tests/topotests/msdp_topo3/test_msdp_topo3.py
- yang/frr-pim.yang
Add new MSDP knob to let user override the SA RP: `msdp originator-id A.B.C.D`. With this configuration MSDP will not use the configured RP for the group, but the manual address provided by originator-id (usually the RP interface address).
> pimd: MSDP originador ID configuration

- bgpd/bgp_fsm.c
- bgpd/bgp_route.c
If we have this construct:
for (pi = bgp_dest_get_bgp_path_info(dest); pi; pi = pi->next) {
...
bgp_process();
}
This can induce an infinite loop.  This happens because bgp_process will move the unsorted items to the top of the list for handling, as such it is necessary to hold the next pointer to the side to actually look at each possible bgp_path_info.
> bgpd: When calling bgp_process, prevent infinite loop

- pimd/pim6_mld.c
- pimd/pim_tib.c
Fix crash on `clear ipv6 mroute` when using embedded RP.
Explanation: revert change to decrement reference count on embedded RP for channel_oil and always update the MLD group oil pointer.
> pim6d: fix crash on clear ipv6 mroute

- pimd/pim_bsm.c
- pimd/pim_nb_config.c
- pimd/pim_rp.c
- pimd/pim_util.c
- pimd/pim_util.h
Fix Coverity Scan CID 1602463: make it impossible for the function to fail.
Hardcode the multicast prefix generation instead of calling [`str2prefix()`](https://github.com/FRRouting/frr/blob/master/lib/prefix.c#L618) which caused unnecessary memory allocations and returned error values.
> pimd,pim6d: optimize multicast prefix generation and fix coverity scan defect

- zebra/zserv.c
When debugging a crash I noticed that sometimes we talked about a zclient connection in relation to the fd associated with it and sometimes we did not.  Let's just always give the data associated with the fd.  It will make it a bit easier for me to follow the transitions.
> zebra: Give a bit more data about zclient connection on errors

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn.h
- bgpd/bgp_evpn_private.h
- bgpd/bgp_main.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgp_zebra.h
- bgpd/bgpd.c
- bgpd/bgpd.h
- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_chaos_topo1.py
- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py
The following are cases where it is the reverse i.e. BGP is very busy processing the first ZAPI message from zebra due to which the buffer grows huge in zebra and memory spikes up.  Below are few triggers as example 
Interface Up/Down events 
- a bulk of L2VNIs are flapped i.e. flap of br_default interface (or) 
- a bulk of L3VNIs are flapped i.e. flap of br_l3vni interface  
Anytime BGP gets a L2 VNI ADD (or) L3 VNI ADD/DEL from zebra,
- Walking the entire global routing table per L2VNI is very expensive.
- The next read (say of another VNI ADD) from the socket does not proceed unless this walk is complete.
So for triggers where a bulk of L2VNI's/L3VNIs are flapped, this results in huge output buffer FIFO growth spiking up the memory in zebra since bgp is slow/busy processing the first …
> EVPN L2VNI/L3VNI Optimize inline Global walk for remote route installations

- tests/topotests/zebra_multiple_connected/r1/ip_route_kernel_interface_down.json
- tests/topotests/zebra_multiple_connected/r1/ip_route_kernel_interface_up.json
- tests/topotests/zebra_multiple_connected/test_zebra_multiple_connected.py
- zebra/interface.c
- zebra/zebra_nhg.c
- zebra/zebra_rib.c
The kernel routes are wronlgy active even the nexthop interface is linkdown.                                                                                                 
Use `ip link set dev <interface> down` on the other box to set the box's                                                                                                     
nexthop interface linkdown. The kernel routes will be kept as `linkdown`,                                                                                                    
but are still with active nexthop in `zebra`.                                                                                                                                
Add three changes for kernel routes in this commit: …
> zebra: fix wrong nexthop status for kernel routes

- lib/plist.c
Closes https://github.com/FRRouting/frr/issues/17612
> lib: Take ge/le into consideration when checking the prefix with the prefix-list

- bgpd/bgp_route.c
If you have a bestpath list that looks something like this:
<local evpn mac route>
<learned from peer out swp60>
<learned from peer out swp57>
And a network event happens that causes the peer out swp60 to not be in an established state, yet we still have the path_info for the destination for swp60, bestpath
will currently end up with this order:
<learned from peer out swp60>
<local evpn mac route>
<learned from peer out swp57>
This causes the local evpn mac route to be deleted in zebra( Wrong! ).
This is happening because swp60 is skipped in bestpath calculation and not considered to be a path yet it stays at the front of the list.
Modify bestpath calculation such that when pulling the unsorted_list together to pull path info's into that list when they are also not in a established state.
> bgpd: Fix evpn bestpath calculation when path is not established

- include/linux/if_packet.h
- isisd/isis_pfpacket.c
When I use the ip link add command on two Ubuntu systems to create an eth1.100 VLAN sub-interface and enable the ISIS protocol on the interface, I find that the sub-interface can not only establish an ISIS neighbor with the eth1.100 port of another Ubuntu, but also establish an ISIS neighbor with the eth1 port.
```
ip link add link eth1 name eth1.100 type vlan 100
```
R1 configuration:
```
interface eth1
ip route isis 1
interface eth1.100
ip route isis 1
router isis 1
net 49.0000.0000.0001.00
```
R2 configuration:
```
interface eth1.100
ip route isis 1
router isis 1
net 49.0000.0000.0001.00
```
R1 show isis neighbor
```
SystemID     Interface      L     State
R2                  eth1           2       UP
R2                  eth1.100    2       UP …
```
> vlan-subif isis neigbor

- bgpd/bgp_table.h
Remove a printfrr registration for pRN from bgpd.
> bgpd: remove unneeded printfrr reg for pRN

- bgpd/bgp_fsm.c
- bgpd/bgp_vty.c
- bgpd/bgpd.h
- tests/topotests/bgp_minimum_holdtime/test_bgp_minimum_holdtime.py
120 seconds (default) is a bit of something like "are you from the past?". Let's see if we can have a lower value with some backoff...
> bgpd: Connect retry timer backoff

- bgpd/bgp_rpki.c
- bgpd/bgpd.c
- bgpd/bgpd.h
Closes https://github.com/FRRouting/frr/issues/17533
> bgpd: Validate only affected RPKI prefixes instead of a full RIB

- bgpd/bgp_route.c
Add missing json attribute to BGP path.
Fixes: 82c298be7354 ("bgpd: Show RPKI short state in `show bgp <afi> <safi>`")
> bgpd: add rpki json attributes to bgp path

- bgpd/bgp_vty.c
A memory leak happens when reconfiguring an already configured route distinguisher on an L3VPN BGP instance. Fix this by freeing the previous route distinguisher.
> bgpd: fix memory leak when reconfiguring a route distinguisher

- lib/darr.c
- lib/darr.h
- lib/mgmt_msg_native.h
- fix issue with nested macros
- use frr sprintf
> Fix 2 darr (dynamic-array) bugs

- babeld/babeld.c
When deactivating babel no router babel and later re-enabling it router babel the previous configuration is still in place.
Steps to reproduce:
- Enable babel
- Configure babel
- Disable babel with "no router babel"
- Verify config
Expected correct behavior: No config present
> babel: Clean babel config on babel daemon stop

- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_table.h
- bgpd/bgpd.c
- bgpd/bgpd.h
This commit introduces meta queue to the BGP process_queue which is helpful in having a priority of lists where some routes can be processed earlier than 'other' routes. This is similar to how meta queue is present in zebra.
After Fix:
---------
For testing, note that all 100.x routes are marked as Early routes which got enqueued and dequeued first before Other routes in every batch of updates. Also, the items are dequeued in FIFO order.
switch# cat /var/log/frr/bgpd.log | grep sub-queue 2024/12/06 19:19:42.788014 BGP: [V64FH-G6883] 88.0.0.9/32 queued into sub-queue Other Route 2024/12/06 19:19:42.856127 BGP: [V64FH-G6883] 100.90.9.186/32 queued into sub-queue Early Route 2024/12/06 19:19:42.856138 BGP: [V64FH-G6883] 100.90.9.187/32 queued into sub-queue Early Route 2024/12/06 …
> bgpd: add meta queue in bgp

- lib/northbound_cli.c
- lib/northbound_cli.h
- lib/vty.h
Issue: When the incoming config has say 30K entries of a prefix-lists, current implementation is to schedule the configs to be batched and only after batching the entire config, the processing of the configs take place. As part of batching this config, we perform string concatenation to save all the configs in the buffer which over time results in taking longer time.
Ex: Imagine each line of config is 50 chars. With a delimiter of ‘- ‘ we end up adding 52 chars to buffer for each command i.e. 52*30000 = 156K of chars. Strlcat is an expensive operation and every time we strlcat, we have to traverse at end of string to append new char.
Because of this, we end up adding extra 6-8 secs for accepting the config.
Fix: The idea here is to bring back something similar to the backoff count …
> lib: Fix to optimize the time taken while batching huge configs

- mgmtd/mgmt_be_adapter.c
Compile error with `--disable-ripd`:
```
mgmtd/mgmt_be_adapter.c:86:5: error: "HAVE_RIPD" is not defined, evaluates to 0 [-Werror=undef]
86 | #if HAVE_RIPD
|     ^~~~~~~~~
```
I have searched the code, there is only three places need to be fixed.
> mgmtd: fix compile error

- zebra/zebra_srv6_vty.c
`srv6_locator_alloc` can never fail. Let's remove the tests for allocation failure.
> zebra: Remove tests for `srv6_locator_alloc` failure

- bgpd/bgp_mplsvpn.c
- bgpd/bgp_mplsvpn.h
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- tests/topotests/bgp_vpnv4_ebgp_vpn_auto/r1/frr.conf
- tests/topotests/bgp_vpnv4_ebgp_vpn_auto/r2/frr.conf
- tests/topotests/bgp_vpnv4_ebgp_vpn_auto/r3/frr.conf
- tests/topotests/bgp_vpnv4_ebgp_vpn_auto/test_bgp_vpnv4_vpn_auto.py
**What is the problem ?**
When we remove the BGP VPN session which had been configured using ( label vpn export auto ), corresponding label is not getting freed up in the label pool structures.
**What is the Impact ?**
In higher scale deployment, more we remove sessions and rollback or add new session, earlier assigned labels wont get freed up leading to label pool expansion
**What is the fix ?**
Fix to release the corresponding label pool using _bgp_lp_release_ in _bgp_delete_  flow and verifying the same using topotest
> BGP Labelpool : Releasing the label in labelpool when VPN session gets removed

- tests/topotests/srv6_static_route/test_srv6_route.py
`srv6_static_route` is a pure staticd topotest. It does not have any dependency on bgpd and sharpd.
Let's fix the pytestmark to include only staticd.
> tests: Fix markers in `srv6_static_route` topotest

- tools/frr-reload.py
When reloading the following configuration:
```
srv6
formats
format usid-f3216
wide-local-id-block explicit start 100
exit
!
format uncompressed-f4024
exit
!
exit
!
exit
!
exit
```
frr-reload.py does not properly enter the `formats` context. Because of this, it fails with an unknown command error when applying new or updating format configuration.
> tools: Add missing formats keyword to segment-routing in frr-reload

- bgpd/bgp_route.c
- tests/topotests/bgp_rpki_topo1/r2/bgp_rpki_valid.json
- tests/topotests/bgp_rpki_topo1/test_bgp_rpki_topo1.py
Display rpki_curr_state in the output and provide a topotest to theck the json field:
```
"version": 2,
"rpkiValidationState": "valid",
"bestpath": {
"overall": true,
"selectionReason": "First path received"
},
```
> bgpd: add rpki current state

- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgpd.c
When stopping and restarting BGP daemon part of the configuration remains. It should be cleared.
Particulary those are address-family parametes, like: distance, ead-es-frag, disable-ead-evi-rx, disable-ead-evi-tx.
> bgpd: Clean address-family config on daemon restart

- staticd/static_nht.c
For one static_path, only need to call static_zebra_route_add once.
> staticd: Reduce the frequency of adding routes

- zebra/zebra_evpn_mac.c
If Duplicate Address Detection action is freeze
(permanent or definite time means not warn only mode) then locally duplicate detected MAC delete notification is not require to inform,
instead ask BGP to sync previous remote MAC entry. In freeze case local MAC event is not known to BGP, instead BGP is pointing to remote VTEP for the MAC.
Signed-off-by: Karthikeya Venkat Muppalla <kmuppalla@nvidia.com>
> zebra:check DAD freeze action before notifying bgp

- babeld/babel_interface.c
When deactivating babel no router babel and later re-enabling it router babel the previous configuration is still in place.
Steps to reproduce:
Enable babel
Configure babel
Disable babel with "no router babel"
Verify config
Expected correct behavior: No config present
> babel: Clean babel related config on daemon stop

- tools/frr-reload.py
When reloading the following configuration:
```
vrf red
rpki
rpki cache tcp 172.65.0.2 8282 preference 1
exit
exit-vrf
```
frr-reload.py does not properly enter the `rpki` context within a `vrf`. Because of this, it fails to apply RPKI configurations.
> tools: Add missing rpki keyword to vrf in frr-reload

- bgpd/bgp_fsm.c
Closes https://github.com/FRRouting/frr/issues/17751
> bgpd: Do not try to uninstall BFD session if the peer is not established (backport)

- tools/frr-reload.py
When reloading the following configuration:
```
srv6
formats
format usid-f3216
wide-local-id-block explicit start 100
exit
!
format uncompressed-f4024
exit
!
exit
!
exit
!
exit
```
frr-reload.py does not properly enter the `formats` context. Because of this, it fails with an unknown command error when applying new or updating format configuration.
> tools: Add missing formats keyword to segment-routing in frr-reload (backport)

- zebra/dpdk/zebra_dplane_dpdk.c
Fixing compilation error in a switch statement case
Fixes :aa4786642c9a65c282d0fd5247a35b0f14fa1c3c
> zebra: fix dpdk compilation error

- bgpd/bgpd.c
Fix a bug in peer_allowas_in_set() so that the config takes effect for peer-group members.
> bgpd: fix a bug in peer_allowas_in_set()

- bgpd/bgp_evpn_vty.c
- bgpd/bgp_nexthop.c
- bgpd/bgp_route.c
- bgpd/bgp_vty.c
- doc/user/bgp.rst
- tests/topotests/bgp_gr_notification/test_bgp_gr_notification.py
This PR includes multiple commits that optimize the show json output for various BGP show commands in scaled setup.
> bgpd: show json output changes to optimize various show commands

- lib/route_types.txt
- tests/topotests/bgp_suppress_fib/test_bgp_suppress_fib.py
- zebra/zebra_nb_config.c
- zebra/zebra_routemap.c
"ip/ipv6 protocol any route-map <route map>" cli is setting wrong route type (ZEBRA_ROUTE_MAX), It should set route type ZEBRA_ROUTE_ALL.
After executing the above CLI, routes are not scheduled for processing with routemap. 
Reason: CLI set route-type=ZEBRA_ROUTE_MAX but Zebra checks ZEBRA_ROUTE_ALL in rib_update_route_node(). 
FRR restart solves the issue, and filter works as expected, because restart route install flow is different and its checks are proper.
After this code change all the api's are in synced, and right FLAG is used.
CLI, rib_update_route_node() , zebra_route_map_check ()
Ticket: #4101560
> zebra: Fix ip protocol route-map issue.

- ospfd/ospf_vty.c
The users would know the failure of some case for the two commands, just return the error ```CMD_WARNING_CONFIG_FAILED```.
> ospfd: fix wrong check for two commands

- bgpd/bgp_bmp.c
- bgpd/bgp_io.c
- bgpd/bgp_nht.c
- bgpd/bgp_nht.h
- bgpd/bgp_trace.h
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/test_bgp_bmp_2.py
- tests/topotests/lib/bmp_collector/bgp/update/rd.py
Update BMP per peer header messages according to the various configuration changes:
- router-id
- route distinguisher
- vrf interface flapping
it replaces https://github.com/FRRouting/frr/pull/17373
> BMP handling of BGP configuration changes

- lib/if.c
- lib/northbound.c
- lib/northbound.h
- lib/northbound_oper.c
- tests/lib/northbound/test_oper_data.c
- tests/lib/northbound/test_oper_data.refout
- tools/gen_northbound_callbacks.c
- yang/frr-test-module.yang
Current get_elem callback allocates and initializes a `struct yang_data` which is an xpath and value, then immediately uses this to create a libyang `struct lyd_node` and free's the `yang_data`.
Add a new get callback that simply creates the libyang `struct lyd_node` directly avoiding xpath creations and allocations.
> Add new oper state get callback

- lib/northbound_oper.c
- tests/lib/northbound/test_oper_data.in
- tests/lib/northbound/test_oper_data.refout
For keyless list `foo` make this work: `show /foos/foo[1]`
> fix xpath query on keyless list with positional predicate

- tests/topotests/ospf6_ecmp_inter_area/r1/show_ipv6_routes_ospf6-1.json
- tests/topotests/ospf6_ecmp_inter_area/r1/show_ipv6_routes_ospf6-2.json
- tests/topotests/ospf6_ecmp_inter_area/r1/show_ipv6_routes_ospf6-3.json
- tests/topotests/ospf6_ecmp_inter_area/r7/ospf6d.conf
- tests/topotests/ospf6_ecmp_inter_area/r8/ospf6d.conf
- tests/topotests/ospf6_ecmp_inter_area/test_ospf6_ecmp_inter_area.py
Replaces/supersedes #16811. Addresses all review comments.
Compare JSON routes to check for success instead of counting nexthops. Also fix bad interface shutdown config.
Note that like #16811, this does not fix intermittent test case failures. These are actual ospf6d errors, not test case bugs. See https://github.com/FRRouting/frr/issues/16197 for details, in particular comments starting at https://github.com/FRRouting/frr/issues/16197#issuecomment-2293383832
> tests: cleanup ospf6 ecmp inter area

- lib/privs.c
Don't over-allocate syscaps in zcaps2sys(): This is just a single struct (pset_t) with a count and a pointer to an array of capabilities, not an array. So only allocate a single pset_t, not num copies of it.
The allocation size of syscaps->caps then needs to be based on the number of Linux capabilities (count), but that is already handled properly a few lines below.
Note that this fix is mostly cosmetic and for correctness. There was no potential for memory corruption, because num is guaranteed to be nonzero. So at least the one required pset_t was always allocated (but potentially much more).
> lib: Fix privs syscaps (pset_t) allocation

- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_routemap.c
Currently when re-evaluating an aggregate route, the full attribute of
the aggregate route is not compared with the existing one in the BGP
table. That can result in unnecessary churns (un-install and then
install) of the aggregate route when a more specific route is added or
deleted, or when the route-map for the aggregate changes. The churn
would impact route installation and route advertisement.
The fix is to apply the route-map for the aggregate first and then
compare the attribute.
> bgpd: apply route-map for aggregate before attribute comparison

- bgpd/bgp_route.c
Potential memory leak with as-set and matching-MED-only config.
> bgpd: fix memory leak in bgp_aggregate_install()

- bgpd/bgp_vty.c
- bgpd/bgp_vty.h
- bgpd/bgpd.c
`frrbot` was intentionally skipped because we already prefer such formatting.
> bgpd: Fix showing default `timers bgp x y`

- bgpd/bgp_attr.h
Use igpmetric from bgp_path_info in bgp_igp_metric_total() to be consistent with all other cases, e.g., as in bgp_path_info_cmp().
> bgpd: use igpmetric in bgp_aigp_metric_total()

- tests/topotests/munet/base.py
- tests/topotests/munet/munet-schema.json
- tests/topotests/munet/mutest/userapi.py
- tests/topotests/munet/native.py
- tests/topotests/munet/testing/util.py
- add readline and waitline functions for use with popen objects
- other non-topotest (munet native) run changes
- vm/qemu support booting cloud images (rocky, ubuntu, debian)
- native topology init commands
> tests: update munet to 0.15.3

- zebra/zebra_nhg.c
In some cases, the old_re nhe and the newnhe is same and there is no point in comparing them both since they are the same. Skip comparing in such cases.
Ex:
```
9404 2025/01/09 23:49:27.489020 ZEBRA: [W4Z4R-NTSMD] zebra_nhg_rib_find_nhe: => nhe 0x555f611d30c0 (44[38/39/45])
9405 2025/01/09 23:49:27.489021 ZEBRA: [ZH3FQ-TE9NV] zebra_nhg_rib_compare_old_nhe: 0.0.0.0/0 new id: 44 old id: 44
9406 2025/01/09 23:49:27.489021 ZEBRA: [YB8HE-Z86GN] zebra_nhg_rib_compare_old_nhe: 0.0.0.0/0 NEW 0x555f611d30c0 (44[38/39/45])
9407 2025/01/09 23:49:27.489023 ZEBRA: [ZSB1Z-XM2V3] 0.0.0.0/0: NH 20.1.1.9[0] vrf default(0) wgt 1, with flags
9408 2025/01/09 23:49:27.489024 ZEBRA: [ZSB1Z-XM2V3] 0.0.0.0/0: NH 30.1.2.9[0] vrf default(0) wgt 1, with flags
9409 2025/01/09 23:49:27.489025 ZEBRA: [ZSB1Z-XM2V3] …
```
> zebra: Optimize invoking nhg compare func

- tools/frr-reload.py
When a bgp neighbor removed from associated to peer-group, the neighbor is fully deleted, subsequent deletion of any configuration related to the neighbor leads to failure in frr-reload.
Handle any 'no neighbor ...' part of lines_to_del list
Testing:
Below first line would delete the neighbor swp1.10, the existing code before the change handles to remove config starts with 'neighbor swp1.10 ...' but not
'no neighbor swp1.10 ...'.
(Pdb) (lines_to_del)
(('router bgp 100',), 'neighbor swp1.10 interface peer-group dpeergrp_2'),
(('router bgp 100',), 'neighbor swp1.10 advertisement-interval 1'),
(('router bgp 100',), 'neighbor swp1.10 timers 3 9'),
(('router bgp 100',), 'neighbor swp1.10 timers connect 1'),
(('router bgp 100',), 'no neighbor swp1.10 capability dynamic'),
**Before fix:**
``` …
```
> tools: fix frr-reload for nbr deletion of no form cmds

- bgpd/bgp_route.c
- bgpd/bgp_route.h
Remove the unused safi field in bgp_aggregate structure.
> bgpd: remove unused safi in bgp_aggregate structure

- bgpd/bgp_route.c
Currently when an aggregate-address is configured, the existing entry is always removed regardless whether any change is involved. This would create unnecessary churn of the aggregate route when the same config is applied for the aggregate address.
The fix is to check for duplicate aggregate-address config.
> bgpd: fix churn of aggregate routes from duplicate config

- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_routemap.c
> bgpd: Aggregate backports

- ospfd/ospf_asbr.c
```
(config-router)# no summary-address 9.9.9.0/24
(config-router)# no summary-address 9.9.9.0/24
(config-router)# no summary-address 9.9.9.0/24
(config-router)# no summary-address 9.9.9.0/24
(config-router)# no summary-address 9.9.9.0/24
2025/01/09 09:30:10 OSPF: [S5BD4-3G5QX] ospf_external_aggr_timer: Start Aggregator delay timer 5(in seconds).
2025/01/09 09:30:11 OSPF: [S5BD4-3G5QX] ospf_external_aggr_timer: Start Aggregator delay timer 5(in seconds).
2025/01/09 09:30:11 OSPF: [S5BD4-3G5QX] ospf_external_aggr_timer: Start Aggregator delay timer 5(in seconds).
2025/01/09 09:30:11 OSPF: [S5BD4-3G5QX] ospf_external_aggr_timer: Start Aggregator delay timer 5(in seconds).
2025/01/09 09:30:12 OSPF: [S5BD4-3G5QX] ospf_external_aggr_timer: Start Aggregator delay timer 5(in seconds).
```
Since …
> ospfd: avoid the redundant timers

- bgpd/bgp_mplsvpn.c
- bgpd/bgp_mplsvpn.h
- bgpd/bgp_route.c
- tests/topotests/bgp_vpnv4_import_allowas_in_between_vrf/r1/frr.conf
- tests/topotests/bgp_vpnv4_import_allowas_in_between_vrf/r2/frr.conf
- tests/topotests/bgp_vpnv4_import_allowas_in_between_vrf/test_bgp_vpnv4_import_allowas_in_between_vrf.py
Closes https://github.com/FRRouting/frr/issues/17797
> bgpd: Respect allowas-in value from the source VRF's peer

- zebra/dplane_fpm_nl.c
- zebra/rt_netlink.c
- zebra/rt_netlink.h
- zebra/zebra_dplane.c
- zebra/zebra_dplane.h
- zebra/zebra_rib.c
- zebra/zebra_vrf.c
- zebra/zebra_vrf.h
The current FPM dataplane plugin uses some zebra netlink message encode and decode apis. That seems to have been done to avoid duplication - but there are races present because FPM uses its own pthread, the netlink code touches zebra internal datastructures, and that is not thread-safe. This PR attempts to re-work the netlink apis so that they become safe for FPM use.
> zebra: avoid race between FPM pthread and zebra main pthread in netlink encode/decode

- bgpd/bgp_mplsvpn.c
- bgpd/bgp_route.c
- bgpd/rfapi/rfapi.c
Route aggregation should be checked after a route is added, and not before. This is for code flow and consistency.
> bgpd: move bgp_aggregate_increment() after bgp_path_info_add()

- tests/topotests/msdp_topo3/r1/frr.conf
- tests/topotests/msdp_topo3/r2/frr.conf
- tests/topotests/msdp_topo3/test_msdp_topo3.py
Decrease the protocol timers, wait for peers to connect (and test it) then finally wait a bit more for SAs to be propagated.
> topotests: improve test reliability

- zebra/zebra_nhg.c
If you have this series of events:
a) Decision to install a NHG is made in zebra, enqueue to DPLANE b) Changes to NHG are made and we remove it in the master pthread
Since this NHG is not marked as installed it is not removed
but the NHG data structure is deleted
c) DPLANE installs the NHG
In the end the NHG stays installed but ZEBRA has lost track of it.
Modify the removal code to check to see if the NHG is queued. There are 2 cases:
a) NHG is kept around for a bit before being deleted.  In this case just see that the NHG is Queued and keep it around too.
b) NHG is not kept around and we are just removing it.  In this case check to see if it is queued and send another deletion event.
> zebra: Uninstall NHG in some situations

- lib/northbound.c
The previous use of `lyd_new_path()` returns the first node created, rather than the xpath target node. The code is lucky in the sense that it is normally only creating a single node rather than a branch. Fix this to use `lyd_new_path2()` which returns the target node to actually implement the semantics expected by callers of `dnode_create()` (i.e., returning the newly created target node).
> lib: fix dnode_create to use correct libyang function.

- tools/gen_northbound_callbacks.c
When support for new style `get()` was added inadvertently stopped generating other callbacks and prototypes. Fix this.
> tools: fix regression in gen_northbound_callback tool

- bgpd/bgp_route.c
- tests/topotests/bgp_ipv6_rtadv/r1/bgp_ipv4_routes.json
- tests/topotests/bgp_ipv6_rtadv/r1/bgp_ipv6_routes.json
- tests/topotests/bgp_ipv6_rtadv/test_bgp_ipv6_rtadv.py
> Bgp unnumbered interface json

- tools/frr-reload.py
- When reloading the configuration in FRR, the `frr-reload.py` script does not allow removing an entire interface context in one step. Instead, it attempts to delete each configuration line individually under the interface context.
- This line-by-line deletion can cause issues when the interface is already removed from the system.
**Specific Issue:**
- If an interface has been removed from the system, trying to delete specific configurations (such as IP addresses) under that interface context fails.
- For example, if an IP address was configured on an interface that no longer exists, trying to remove that IP address will result in an error because the interface itself is not present.
**Impact of the Issue:**
- This behavior leads to errors during the configuration reload process, making …
> tools: fix reload interface deletion

- bgpd/bgp_zebra.c
Issue:
During FRR restart, we fail to add some of the local interface's MAC to the 'bgp mac hash'. Not having local MAC in the hash table can cause lookup issues while receiving EVPN RT-2.
Currently, we have code to add local MAC(bgp_mac_add_mac_entry) while handling interface add/up events in BGP(bgp_ifp_up/bgp_ifp_create). But the code 'bgp_mac_add_mac_entry' in bgp_ifp_create is not getting invoked as it is placed under a specific check(vrf->bgp link check).
Fix:
We can skip this check 'vrf->bgp link existence' as the tenant VRF might not have BGP instance but still we want to cache the tenant VRF local MACs. So keeping this check in bgp_ifp_create inline with bgp_ifp_up.
Ticket: #4204154
> bgpd: Fix for local interface MAC cache issue in 'bgp mac hash' table

- doc/developer/packaging-redhat.rst
- redhat/frr.spec.in
fix generation of rpms for RHEL/Rocky8. default behavior is not changed by addition of new rpmbuild (command line) options.
> Fix Rocky 8 RPMs, add options to build without rpki and docs (default is to include)

- lib/northbound_notif.c
The code doesn't push more than one group (currently) so wouldn't hit the bug yet, nice catch by coverity.
> lib: fix coverity use after free issue: CID 1620101

- bgpd/bgp_bmp.c
With recent BMP code, on a standard BMP config, the peer up and peer down messages related to a BGP peer are sent twice, whereas they should be send only once.
Fix this by better controlling the condition.
Fixes: f8a693311145 ("bgpd: bmp, handle imported bgp instances for peer up/down events")
> bgpd: fix do not send twice peer up/down messages

- bgpd/bgp_evpn_mh.c
- bgpd/bgp_route.c
- bgpd/bgp_route.h
EVPN imported routes AF is not AF_EVPN, in that case the path info extra with EVPN is nver created.
In order to create evpn info under path extra, define new api which does not specifically check for AF_EVPN afi type.
> bgpd: fix evpn path info get api

- bgpd/bgp_bfd.c
- tests/topotests/bgp_bfd_session/r1/frr.conf
- tests/topotests/bgp_bfd_session/test_bgp_bfd_session.py
Fix BFD session not created when the peer is in update-group with the update-source option.
> bgpd: fix bfd with update-source in peer-group

- zebra/zebra_vty.c
Return error if IPv6 address or prefix is passed as an argument to "show ip route" command.
UT:
------
Before fix:
```
r1# 
r1# show ipv6 route 200.0.20.1/32
% Unknown command: show ipv6 route 200.0.20.1/32
r1# 
r1# show ip route 2::3/128 ===> v4  CMD accepts v6 prefix
Routing entry for 2::3/128
Known via "bgp", distance 20, metric 0, best
Last update 00:02:30 ago
* fe80::5493:4ff:fe30:55fd, via r1-r2-eth0, weight 1
r1# show ip route 2::3 ===> v4  CMD accepts v6 address
Routing entry for 2::3/128
Known via "bgp", distance 20, metric 0, best
Last update 00:15:16 ago
* fe80::5493:4ff:fe30:55fd, via r1-r2-eth0, weight 1
r1# show ip route 2::
r1# show ip route 2:
% Unknown command: show ip route 2:
r1# 
```
After fix:
```
r1# show ip route 2::3/128
% Cannot specify IPv6 address or prefix with …
```
> zebra: Return error if v6 prefix is passed to show ip route

- redhat/frr.spec.in
Version requirement from a BuildRequire get dropped and don't get reflected in Require's for the package. Specify it both ways for Libyang as we require >= 2.1.128
This makes sure that we force an upgrade from older libyang for FRR to work
> redhat: Specify minimum libyang version requirement

- isisd/isis_tlvs.h
The application specific defines from rfc8919 were defined twice in the isis tlv headers. Remove the second one.
Fixes: 5749ac83a8ad ("isisd: add ASLA support")
> isisd: fix duplicate rfc8919 defines

- bgpd/bgp_route.c
- tests/topotests/bgp_aggregate_address_topo1/r1/bgp_192_168_0_1.json
- tests/topotests/bgp_aggregate_address_topo1/test_bgp_aggregate_address_topo1.py
There is an inconsistency between the vty output and its json output: there is a missing information about the suppressed information. Fix this by adding and testing a new json attribute.
> Bgp suppressed attribute

- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- lib/zclient.c
- lib/zclient.h
- tests/topotests/bgp_table_direct_topo1/r1/frr.conf
- tests/topotests/bgp_table_direct_topo1/r2/frr.conf
- tests/topotests/bgp_table_direct_topo1/r3/frr.conf
- tests/topotests/bgp_table_direct_topo1/test_bgp_table_direct_topo1.py
- zebra/redistribute.c
- zebra/zapi_msg.c
- zebra/zapi_msg.h
This PR implements the mechanism in `lib` and `zebra` to differentiate `table-direct` from different protocol VRF instances.
> bgpd,lib,zebra: permit table-direct on VRFs

- bgpd/bgp_fsm.c
- bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/17868
> bgpd: last reset SNAFU

- bgpd/bgp_nht.c
Currently when a directly connected peer is going down BGP gets a call back for nexthop tracking in addition the interface down events.  On the interface down
event BGP goes through and sets up a per peer Q that holds all the bgp path info's associated with that peer and then it goes and processes this in the future.  In the meantime zebra is also at work and sends a nexthop removal event to BGP as well.  This triggers a complete walk of all path info's associated with the bnc( which happens to be all the path info's already scheduled for removal here shortly).  This evaluate paths
is not an inexpensive operation in addition the work for handling this is already being done via the
peer down queue.  Let's optimize the bnc handling
of evaluate paths and check to see if the peer is
still up …
> bgpd: Optimize evaluate paths for a peer going down

- tests/topotests/isis_srv6_topo1/test_isis_srv6_topo1.py
Fix a ping test that should never pass.
> Isis srv6 topo1 ping

- ospfd/ospf_zebra.c
- tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_transit_router_topo3.py
- tests/topotests/ospf_prune_next_hop/r1/frr.conf
- tests/topotests/ospf_prune_next_hop/r2/frr.conf
- tests/topotests/ospf_prune_next_hop/r3/frr.conf
- tests/topotests/ospf_prune_next_hop/r4/frr.conf
- tests/topotests/ospf_prune_next_hop/r5/frr.conf
- tests/topotests/ospf_prune_next_hop/r6/frr.conf
- tests/topotests/ospf_prune_next_hop/r7/frr.conf
- tests/topotests/ospf_prune_next_hop/r8/frr.conf
- tests/topotests/ospf_prune_next_hop/test_ospf_prune_next_hop.py
ospfd: Prune duplicate next-hops when installing into zebra
Duplicate next-hops are maintained for OSPF inter-area and AS
external routes in the OSPF routing table as long as they
correspond to LSAs for different adverting routers. The
intra-area route computation will not result in duplicate
next-hops.
tests: OSPF topotest for next-hop pruning
OSPF topotest to test OSPF next-hop pruning on installation
into zebra routing table.
Signed-off-by: Acee Lindem <acee@lindem.com>
> ospfd: Prune duplicate next-hop when installing into zebra route table. 

- bgpd/bgp_zebra.c
- tests/topotests/bgp_table_map/r1/frr.conf
- tests/topotests/bgp_table_map/r2/frr.conf
- tests/topotests/bgp_table_map/test_bgp_table_map.py
Schedule zebra to withdraw routes filtered out by a table-map.
> bgpd: fix table-map option

- tools/frr-reload.py
In ebgp-multihop, there is a difference in reload behavior when TTL is unspecified (meaning default 255) and when 255 is explicitly specified. For example, when reloading with 'neighbor <neighbor> ebgp-multihop 255' in the config, the following difference is created. This commit fixes that.
Lines To Delete
===============
no neighbor 10.0.0.4 ebgp-multihop
exit
Lines To Add
============
neighbor 10.0.0.4 ebgp-multihop 255
exit
The commit 767aaa3a8048 is not sufficient and frr-reload needs to be fixed to handle both unspecified and specified cases.
----
```
cat <<EOF > /etc/frr/frr.conf
bgp router-id 10.0.0.1
neighbor 10.0.0.4 remote-as 65002
neighbor 10.0.0.4 ebgp-multihop 255
exit
!
end
EOF
systemctl start frr
./tools/frr-reload.py …
```
> tools: Fix frr-reload for ebgp-multihop TTL reconfiguration.

- tests/topotests/v6_nexthop_group_recursive_resolution/r1/frr.conf
- tests/topotests/v6_nexthop_group_recursive_resolution/test_v6_nexthop_group_recursive_resolution.py
- zebra/zebra_nhg.c
Ensure that the nhg hash comparison function includes all nexthops, including recursive-resolving nexthops.
We discovered that the hash key computation does include the full recursion list, but this "equals" function did not, and that can lead to errors...
> zebra: include resolving nexthops in nhg hash

- pimd/pim_autorp.c
- pimd/pim_cmd_common.c
Don't leave the socket open if we are not enabled for discovery or announcements.
Properly disable autorp discovery by setting false rather than nb destroy.
> pimd: Close AutoRP socket when not needed

- isisd/isis_tlvs.c
The show isis database detail command dumps invalid srv6 information:
>  SRv6 Locator: fc00:0:6::/64 (Metric: 0) ipv6-unicast
>    Sub-TLVs:
>      SRv6 End SID Endpoint Behavior: unknown, SID value: fc00:0:6:0:1::
>
>  MT Reachability: 0123.6452.1973.03 (Metric: 10) ipv6-unicast
>    Local Interface IPv6 Address(es): 192::4:3
>    SRv6 Lan End.X SID: fc00:0:3:0:43::, Algorithm: SPF, Weight: 0, Endpoint Behavior: End.DX6, Flags: B:0, S:0, P:0 Neighbor-ID: 0123.6452.1975
>        SRv6 SID Structure Locator Block length: 40, Locator Node length: 24, Function length: 16, Argument length: 0,
The behavior codepoint should use the IANA definitions to display the correct value. Fix this by calling the appropriate convert function.
> isisd: fix erroneous srv6 information in database

- bgpd/bgp_route.c
When you have suppress-fib-pending turned on it is possible to end up in a situation where the prefix is not withdrawn from downstream peers.
Here is the timing that I believe is happening:
a) have 2 paths to a peer.
b) receive a withdrawal from 1 path, set BGP_NODE_FIB_INSTALL_PENDING
and send the route install to zebra.
c) receive a withdrawal from the other path.
d) At this point we have a dest->flags set BGP_NODE_FIB_INSTALL_PENDING
old_select the path_info going away, new_select is NULL
e) A bit further down we call group_announce_route() which calls
the code to see if we should advertise the path.  It sees the
BGP_NODE_FIB_INSTALL_PENDING flag and says, nope.
f) the route is sent to zebra to withdraw, which unsets the
BGP_NODE_FIB_INSTALL_PENDING.
g) This function winds up and …
> bgpd: With suppress-fib-pending ensure withdrawal is sent

- bgpd/bgp_vty.c
Just to make it simpler for compiling with a different default value. No change to its default value.
> bgpd: add config default for "route-reflector allow-outbound-policy"

- tests/topotests/static_srv6_sids/expected_srv6_sids.json
- tests/topotests/static_srv6_sids/r1/frr.conf
- zebra/zebra_srv6.c
The SRv6 SID Manager does not allow allocating an SRv6 End/uN function even though it is already supported by staticd.
> Fix SRv6 SID Manager

- bgpd/bgp_main.c
Closes https://github.com/FRRouting/frr/issues/17903
> bgpd: Do not ignore auto generated VRF instances when deleting

- staticd/static_zebra.c
When staticd receives a `ZAPI_SRV6_SID_RELEASED` notification from SRv6 SID Manager, it tries to unset the validity flag of `sid`. But since the `sid` variable is NULL, we get a NULL pointer dereference.
```
==13815==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000060 (pc 0xc14b813d9eac bp 0xffffcb135a40 sp 0xffffcb135a40 T0)
==13815==The signal is caused by a READ memory access.
==13815==Hint: address points to the zero page.
#0 0xc14b813d9eac in static_zebra_srv6_sid_notify staticd/static_zebra.c:1172
#1 0xe44e7aa2c194 in zclient_read lib/zclient.c:4746
#2 0xe44e7a9b69d8 in event_call lib/event.c:1984
#3 0xe44e7a85ac28 in frr_run lib/libfrr.c:1246
#4 0xc14b813ccf98 in main staticd/static_main.c:193
#5 …
```
> staticd: Fix NULL pointer dereference when receiving `ZAPI_SRV6_SID_RELEASED` notification

- pimd/pim_autorp.c
- pimd/pim_cmd_common.c
Don't leave the socket open if we are not enabled for discovery or announcements.
Signed-off-by: Nathan Bahr <nbahr@atcorp.com>
(cherry picked from commit 5d102a0a7014e9c526381bacc398a9b06a64ca24)
> pimd: Close AutoRP socket when not needed (backport #17934)

- lib/privs.c
When called without caps/privs, just return from "change_caps" instead of exiting - it's possible that a process may not need privs, but a lib (for example) may use the api.
> libs: return from change_caps if no caps

- staticd/static_vty.c
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_1.json
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_2.json
- tests/topotests/static_srv6_sids/test_static_srv6_sids.py
When a user wants to delete a specific SRv6 SID, he executes the `no sid X:X::X:X/M` command.
However, by mistake, in addition to deleting the SID requested by the user, this command also removes all other SIDs.
This happens because `no sid X:X::X:X/M` triggers a destroy operation on the wrong xpath `frr-staticd:staticd/segment-routing/srv6`.
This commit fixes the issue by replacing the wrong xpath `frr-staticd:staticd/segment-routing/srv6` with the correct xpath `frr-staticd:staticd/segment-routing/srv6/static-sids/sid[sid='%s']`.
This ensures that the `no sid X:X::X:X/M` command only deletes the SID that was requested by the user.
> staticd: Fix wrong xpath in `no sid X:X::X:X/M`

- bgpd/bgp_vty.c
Just to make it simpler for compiling with a different default value. No change to its default value.
> bgpd: add config default for "bgp bestpath aigp"

- bfdd/bfd.c
- bfdd/bfd.h
- bfdd/bfd_packet.c
- bfdd/bfdd_cli.c
- bfdd/bfdd_nb.c
- bfdd/bfdd_nb.h
- bfdd/bfdd_nb_config.c
- bfdd/bfdd_nb_state.c
- bfdd/bfdd_vty.c
- bfdd/event.c
- bfdd/ptm_adapter.c
- doc/developer/sbfd.rst
- doc/developer/subdir.am
- doc/user/sbfd.rst
- doc/user/subdir.am
- lib/bfd.c
- lib/bfd.h
- tests/topotests/sbfd_topo1/r1/frr.conf
- tests/topotests/sbfd_topo1/r2/frr.conf
- tests/topotests/sbfd_topo1/sbfd_topo1.dot
- tests/topotests/sbfd_topo1/test_sbfd_topo1.py
- vtysh/vtysh.c
- yang/frr-bfdd.yang
implementing the SBFD feature (RFC7880, RFC7881) in FRR. 
**What is the motivation for this PR?**
The PhoenixWing project aims to implement SRv6 features into the SONiC community. In PhoenixWing traffic engineering case, we use  SBFD to protect SRv6 TE paths.
**How did you do it?**
SBFD HLD in SoNiC community: https://github.com/sonic-net/SONiC/pull/1766
use SBFD to protect TE path, two types of configs are supported:
1) SBFD echo mode, which mainly used in Our SRv6 TE case. Only need to config at local side: 
configure terminal->
bfd -> 
peer X::X bfd-mode sbfd-echo bfd-name name local-address X::X encap-type SRv6 encap-data X::X source-ipv6 X::X
2) SBFD initiator and reflector mode, Need to config at local side and remote side:
2.1) local config:
configure terminal->
bfd -> 
peer X::X …
> implement SBFD

- lib/event.c
- lib/frrevent.h
Freeing any item here means freeing someone's `event->hist`, leaving a dangling pointer there.  Which will immediately be written to because we're executing in a CLI function under the `vty_read` event, whose `event->hist` is then updated.
Deallocating `event->hist` anywhere other than shutting down the whole event loop is a bad idea to begin with, just zero out the stats instead.
Fixes: FRRouting/frr#16419
> lib: fix use after free in `clear event cpu`

- zebra/zebra_vxlan.c
Upon zebra shutdown hash_clean_and_free is called where user free function is passed,
The free function should not call hash_release which lead to double free of hash bucket.
Fix:
The fix is to avoid calling hash_release from
free function if its called from hash_clean_and_free path.
```
10 0x00007f0422b7df1f in free () from /lib/x86_64-linux-gnu/libc.so.6 11 0x00007f0422edd779 in qfree (mt=0x7f0423047ca0 <MTYPE_HASH_BUCKET>,
ptr=0x55fc8bc81980) at ../lib/memory.c:130
12 0x00007f0422eb97e2 in hash_clean (hash=0x55fc8b979a60,
free_func=0x55fc8a529478 <svd_nh_del_terminate>) at
../lib/hash.c:290
13 0x00007f0422eb98a1 in hash_clean_and_free (hash=0x55fc8a675920
<svd_nh_table>, free_func=0x55fc8a529478 <svd_nh_del_terminate>) at
../lib/hash.c:305
14 0x000055fc8a5323a5 in zebra_vxlan_terminate …
```
> zebra: fix evpn svd hash avoid double free

- bgpd/bgp_vty.c
For auto configured value RD value comes as NULL,
switching back to original change will ensure to cover for both auto and user configured RD value in JSON.
```
tor-11# show bgp vrf blue ipv4 unicast route-leak json {
"vrf":"blue",
"afiSafi":"ipv4Unicast",
"importFromVrfs":[
"purple"
],
"importRts":"10.10.3.11:6",
"exportToVrfs":[
"purple"
],
"routeDistinguisher":"(null)", <<<<<
"exportRts":"10.10.3.11:10"
}
```
> bgpd: fix route-distinguisher in vrf leak json cmd

- bgpd/bgp_evpn_mh.c
When peering with an EVPN device from other vendor, FRR acting as route reflector is not able to read nor transmit the label value.
Actually, EVPN AD routes completely ignore the label value in the code, whereas in some functionalities like evpn-vpws, it is authorised to carry and propagate label value.
Fix this by handling the label value.
> bgpd: fix add label support to EVPN AD routes

- isisd/isis_cli.c
- yang/frr-isisd.yang
isisd: The command fast-reroute lfa tiebreaker [downstream | lowest-backup-metric | node-protecting] index (1-255) [level-1 | level-2] will overwrite configurations with the same index but different types. This is because the index is set as the key in frr-isisd.yang. However, the lfa_tiebreaker_cmp function uses a tuple (index, type) as the key. Therefore, the yang file should be modified to stay in sync with the business logic.
Test Scenario:
On RouterA, first configure fast-reroute lfa tiebreaker downstream index 100 level-1, then configure fast-reroute lfa tiebreaker lowest-backup-metric index 100 level-1, and check the configuration:
!
router isis 10
fast-reroute lfa tiebreaker lowest-backup-metric index 100 level-1
exit
!
Signed-off-by: baozhen-H3C <bao.zhen@h3c.com>
> isisd: 'tiebreaker' command line funtionality is inconsistent with its implementation

- bgpd/bgp_fsm.c
- bgpd/bgp_network.c
- bgpd/bgpd.h
If we have IPv6-only network and no IPv4 addresses at all, then by default 0.0.0.0 is created which is treated as malformed according to RFC 6286.
(cherry picked from commit 739f2b566a8217acce84d4c21aaf033314f535bb)
> bgpd: Do not start BGP session if BGP identifier is not set (backport)

- bgpd/bgp_route.c
Memory is being leaked when processing the eoiu marker. BGP is creating a dummy dest to contain the data but it was never freed.  As well as the eoiu info was
not being freed either.
> bgpd: Fix up memory leak in processing eoiu marker

- zebra/rt_netlink.c
see commits but just a couple memory leaks address sanitizer finds
> Nexthop leak

- bgpd/bgp_evpn_mh.c
- bgpd/bgp_fsm.c
- bgpd/bgp_network.c
- bgpd/bgpd.c
- bgpd/bgpd.h
=> Reverted https://github.com/FRRouting/frr/pull/18016/commits/daa68852a2a78acf103e8ae1127953b2870c6772 because it was merged with failed status.
> bgpd: Recent failed backports for 10.1

- bgpd/bgp_pbr.c
- fpm/fpm_pb.h
- lib/nexthop.c
- lib/nexthop.h
- lib/zclient.c
- pbrd/pbr_nht.c
- pbrd/pbr_vty.c
- zebra/zebra_routemap.c
Core change: We were hashing 4 bytes of the address.  Even for IPv6 addresses. Oops.
Related changes:
* went through all initializations and assignments of `gate` `src` and `rmap_src` to check that we're not feeding garbage into the 12 unused bytes and hash that
* it should be noted that this was already the behavior before 2019 - all 16 bytes were unconditionally fed into the hash. This PR goes back to that behavior, but it is possible we might have accumulated places where we get junk data into the 12 padding bytes. Hence the cleanup patches in this PR.
* `rmap_src` use is just… wrong… this does a best-effort fixup but it's only a bandaid.
* since the original change with the 4 bytes was done to "speed up things" I've gone and refactored `nexthop_hash` as a whole. It just feeds a …
> lib: actually hash all 16 bytes of IPv6 addresses, not just 4

- bgpd/bgp_fsm.c
- ospfd/ospf_api.c
- zebra/zebra_dplane.c
- zebra/zserv.c
- zebra/zserv.h
see individual commits, fixing some coverity issues
> Coverity 2024 new hotness

- isisd/isis_circuit.c
- isisd/isis_events.c
Address sanitizer was telling us that linked lists were being leaked.  No need to do so.
> isisd: Do not leak a linked list in the circuit

- pimd/pim_ifchannel.c
- pimd/pim_upstream.c
Issue:
When there is no traffic for a group, the LHR and RP take the default KAT+Join timer expiry of a maximum of 480 seconds to clear the S,G . However, in the FHR, we update the state from JOINED to NOT Joined, downstream state from PPto NOINFO.  This restarts the ET timer, causing S,G on FHR to take more than 10 minutes to age out.
In other words,
Consider a case where (S,G) is in Join state. When the traffic stops and the KAT (210) expires,
the Join expiry timer restarts. At this time, if we receive a prune, the expectation is to set
PPT to 0 (RFC 4601 sec 4.5.2).
When the PPT expires, we move to the noinfo state and restart the expiry timer one more time. We remove the
(S,G) entry only after ~10 minutes when there is no active traffic.
Summary:
KAT Join ET 210 + PP ET 210 + NOINFO …
> pimd: Fix for FHR mroute taking longer to age out

- pimd/pim_nb_config.c
In case interface address is learnt during configuration, make sure to run DR election when configuring PIM/PIM passive on interface (if not run).
This is a fix for some intermittent failure in msdp_topo3.
> pimd: fix DR election race on startup

- bgpd/rfapi/rfapi_import.c
Something changed in the bgpd termination sequence, leading to rfapi objects not being freed via their usual timed expiration pathway. This change frees rfapi peer BPIs immediately instead of expiring via timer when bgp is terminating.
> bgpd: rfapi: fix mem leak when killed

- bgpd/bgp_main.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
Revert recent accidental merges (failed).
=> frrbot can be ignored, it does not understand `Reapply` commit prefix.
> Stabilize 10.1 branch

- lib/zlog_5424.c
I tried to configure logging to systemd's journald using the method described in the [documentation](https://docs.frrouting.org/en/latest/basic.html#clicmd-log-stdout-LEVEL): Simply `log stdout` in `frr.conf`. But besides log messages from frrinit.sh and watchfrr, I saw no log messages from the actual routing daemons.
Debugging this revealed that FRR correctly notices that stdout is connected to journald (sd_stdout_is_journal==true), causing log_vty_init() to call zlog_5424_init() and zlog_5424_apply_dst(). But by the time zlog_5424_apply_dst() gets called, zt_stdout_journald.prio_min still is ZLOG_DISABLED, causing it to skip the call to zlog_5424_open(). And when frr.conf gets read later on, my `log stdout` statement sets .prio_min to LOG_DEBUG and causes a call to …
> Fix journald logging via "log stdout"

- bgpd/bgp_mplsvpn.c
- tests/topotests/bgp_bmp/test_bgp_bmp_1.py
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/frr.conf
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/show_bgp_ipv4_vpn_add_zita.json
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/show_bgp_ipv4_vpn_del_donna_prefix.json
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/show_bgp_ipv4_vpn_eva_down.json
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/show_bgp_ipv4_vpn_init.json
- tests/topotests/bgp_vpnv4_route_leak_basic/r1/show_bgp_ipv4_vpn_zita_up.json
- tests/topotests/bgp_vpnv4_route_leak_basic/test_bgp_vpnv4_route_leak_basic.py
- tests/topotests/bgp_vrf_route_leak_basic/test_bgp-vrf-route-leak-basic.py
Fix for the validity and the presence of prefixes in the BGP VPN table.
See individial commit logs
> bgpd: fix for the validity and the presence of prefixes in the BGP VPN table.

- bgpd/bgp_evpn_vty.c
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- doc/user/bgp.rst
=> intentionally ignoring `Verify Source` check.
> bgpd: Show internal data for BGP routes

- isisd/isis_nb.c
- isisd/isis_nb_config.c
Our infrastructure was complaining about this:
2025/02/05 19:38:42 ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'modify' callback for '/frr-isisd:isis/instance/fast-reroute/level-1/lfa/tiebreaker/type'
2025/02/05 19:38:42 ISIS: [ZKB8W-3S2Q4][EC 100663330] unneeded 'modify' callback for '/frr-isisd:isis/instance/fast-reroute/level-2/lfa/tiebreaker/type'
Seems we don't need it.  Let's just remove it.
> isisd: Remove unneeded modify functions

- lib/frr_pthread.c
- lib/frrcu.c
- lib/sigevent.h
You can have the prettiest crash handler on the planet, if you go and mask SIGSEGV on a thread before it segfaults… YOU GET NOTHING, YOU LOSE, GOOD DAY SIR.
(The process just up and hard exits.)
…let's see which of our CI systems don't recognize which of the signals I listed in here…
> lib: crash handlers must be allowed on threads

- nhrpd/netlink_arp.c
Sometimes, NHRP receives L2 information on a cache entry with the 0.0.0.0 IP address. NHRP considers it as valid and updates the binding with the new IP address.
> Feb 09 20:09:54 aws-sin-vpn01 nhrpd[2695]: [QQ0NK-1H449] Netlink: new-neigh 10.2.114.238 dev dmvpn1 lladdr 162.251.180.10 nud 0x2 cache used 0 type 4
> Feb 09 20:10:35 aws-sin-vpn01 nhrpd[2695]: [QQ0NK-1H449] Netlink: new-neigh 10.2.114.238 dev dmvpn1 lladdr 162.251.180.10 nud 0x4 cache used 1 type 4
> Feb 09 20:10:48 aws-sin-vpn01 nhrpd[2695]: [QQ0NK-1H449] Netlink: del-neigh 10.2.114.238 dev dmvpn1 lladdr 162.251.180.10 nud 0x4 cache used 1 type 4
> Feb 09 20:10:49 aws-sin-vpn01 nhrpd[2695]: [QQ0NK-1H449] Netlink: who-has 10.2.114.238 dev dmvpn1 lladdr (unspec) nud 0x1 cache used 1 type 4
> Feb 09 20:10:49 aws-sin-vpn01 …
> nhrpd: fix dont consider incomplete L2 entry

- zebra/fpm_listener.c
Currently when the fpm_listener attempts to read say X bytes it may only get Y( which is less than X ).  In this case we should assume that the dplane_fpm_nl code is just being slow, as that we know it is possible for it to send a partial fpm message.  Let's just loosen the constraints a bit and allow data to flow.
> zebra: Allow fpm_listener to continue to try to read

- bfdd/event.c
- lib/event.c
- lib/frrevent.h
Refactor the "timer getting executed too late" warning:
- warning threshold is now adjustable
- check is performed when event actually executes, rather than when it's thrown on ready list (makes more sense really)
- ignore_late_timer replaced with threshold = 0
- system load averages printed in log message
- warning ratelimited to once per 10s rather than once per poll()
+ use it for BFD TX timers (sets the threshold to half TX interval)
+ freebie `thread` → `event` in user-visible formatting
Among other things this is intended to distinguish BFD failures in CI due to high system load. Doesn't fix the issue but at least makes clear what is going on.
Example warning now looks like this:
```
2025/02/11 11:54:31 ZEBRA: [ZXB3P-3AVT0][EC 100663315] CPU starvation: {(event *)0x7ffd081b2600 …
```
> lib (+bfd): improve late timer warnings

- bgpd/bgp_evpn_mh.c
The following static analysis can be seen :
```
> *** CID 1636504:    (ARRAY_VS_SINGLETON)
> /bgpd/bgp_evpn_mh.c: 1241 in bgp_evpn_type1_route_process()
> 1235            build_evpn_type1_prefix(&p, eth_tag, &esi, vtep_ip);
> 1236            /* Process the route. */
> 1237            if (attr) {
> 1238                    bgp_update(peer, (struct prefix *)&p, addpath_id, attr, afi, safi, ZEBRA_ROUTE_BGP,
> 1239                               BGP_ROUTE_NORMAL, &prd, &label, num_labels, 0, NULL);
> 1240            } else {
> >>>     CID 1636504:    (ARRAY_VS_SINGLETON)
> >>>     Passing "&label" to function "bgp_withdraw" which uses it as an array. This might corrupt or misinterpret adjacent memory locations.
> 1241                    bgp_withdraw(peer, (struct prefix *)&p, addpath_id, afi, …
```
> Cid 1636504

- tests/helpers/c/prng.c
- tests/isisd/test_isis_lspdb.c
- tests/lib/test_nexthop_iter.c
* order of arguments was swapped; not consistent with [`calloc` signature](https://man7.org/linux/man-pages/man3/calloc.3p.html)
* therefore producing [`-Wcalloc-transposed-args`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) during compilation.
> tests: clear `-Wcalloc-transposed-args` warnings

- bfdd/bfd.c
It's unlikely that this would ever get a 0 fd to use but let's just let the code assume it is ok.
> bfdd: 0 is a valid fd.

- yang/frr-pim-rp.yang
Reordered the revision statements in reverse chronological order
According to the YANG specification, the revision statements should be ordered with the most recent revision first
> yang: Reorder the revision statements

- bgpd/bgp_route.c
In bgp_show_table_rd(), the is_last argument is determined using the expression "next == NULL" to check if the RD table is the last one. This helps ensure proper JSON formatting.
However, if next is not NULL but is no longer associated with a BGP table, the JSON output becomes malformed.
Updates the condition to also verify the existence of the next bgp_dest table.
Fixes: 1ae44dfcba ("bgpd: unify 'show bgp' with RD with normal unicast bgp show")
> bgpd: fix incorrect JSON in bgp_show_table_rd

- doc/user/pim.rst
- doc/user/pimv6.rst
- pimd/pim6_cmd.c
- pimd/pim6_mld.c
- pimd/pim6_mld.h
- pimd/pim_cmd.c
- pimd/pim_iface.c
- pimd/pim_iface.h
- pimd/pim_igmp.c
- pimd/pim_igmpv3.c
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- pimd/pim_vty.c
- tests/topotests/lib/mcast-tester.py
- tests/topotests/multicast_features/r1/frr.conf
- tests/topotests/multicast_features/r2/frr.conf
- tests/topotests/multicast_features/r3/frr.conf
- tests/topotests/multicast_features/test_multicast_features.py
- yang/frr-gmp.yang
This PR adds support for IGMP and MLD groups / source limiting.
Example 1:
```
interface eth0
ip igmp
ip igmp max-groups 10
exit
```
Will cause PIM to learn at most 10 groups, new groups will be ignored.
Example 2:
```
interface eth1
ipv6 mld
ipv6 mld max-sources 10
exit
```
Will cause PIM to learn at most 10 sources per groups, new sources will be ignored.
> pimd,pim6d: implement GMP group / source limits

- doc/user/ospfd.rst
- ospfd/ospf_apiserver.c
- ospfd/ospf_dump.c
- ospfd/ospf_dump.h
- ospfd/ospf_lsa.c
- ospfd/ospf_lsa.h
- ospfd/ospf_lsdb.c
- ospfd/ospf_lsdb.h
- ospfd/ospf_opaque.c
- ospfd/ospf_te.c
Replace the LSDB callbacks with LSA update and delete hooks using the
the FRR hook mechanism. Remove redundant callbacks by placing the LSA
update and delete hooks in a single place so that deletes don't need
to be handled by the update hook. Simplify existing OSPF TE and OSPF
API Server callbacks now that there is no ambiguity or redundancy.
Also cleanup the debugging by separating out opaque-lsa debugging
from the overloaded event debugging.
> ospfd: Replace LSDB callbacks with LSA Update/Delete hooks.

- bgpd/bgp_label.c
- bgpd/bgp_labelpool.c
- bgpd/bgp_labelpool.h
- bgpd/bgp_mplsvpn.c
The bgp labelpool code is grabbing the vpn policy data structure. This vpn_policy has a pointer to the bgp data structure.  If a item placed on the bgp label pool workqueue happens to sit there for the microsecond or so and the operator issues a `no router bgp...` command that corresponds to the vpn_policy bgp pointer, when the workqueue is run it will crash because the bgp pointer is now freed and something else owns it.
Modify the labelpool code to store the vrf id associated with the request on the workqueue.  When you wake up if the vrf id still has a bgp pointer allow the request to continue, else drop it.
> bgpd: Fix crash in bgp_labelpool

- lib/srv6.c
The seg6local route dumped by 'show ipv6 route' makes think that the USP flavor is supported, whereas it is not the case. This information is a context information, and for End, the context information should be empty.
> # show ipv6 route
> [..]
> I>* fc00:0:4::/128 [115/0] is directly connected, sr0, seg6local End USP, weight 1, 00:49:01
Fix this by suppressing the USP information from the output.
Fixes: e496b4203055 ("bgpd: prefix-sid srv6 l3vpn service tlv")
> lib: fix false context information for SRv6 route

- lib/nexthop.c
- lib/srv6.c
- lib/srv6.h
- staticd/static_zebra.c
- tests/topotests/static_srv6_sids/expected_srv6_sids.json
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_1.json
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_2.json
The SRv6 support in staticd (PR #16894) does not set the correct SID parameters (block length, node length, function length).
This PR fixes the issue and computes the correct parameters.
The bug was reported by SONiC testing.
> staticd: Fix SRv6 SID installation and deletion

- bgpd/bgpd.c
When a BGP instance with a manually assigned VPN label is deleted, the label is not released from the Zebra label registry. As a result, reapplying a configuration with the same manual label leads to VPN prefix export failures.
For example, with the following configuration:
> router bgp 65000 vrf BLUE
>  address-family ipv4 unicast
>   label vpn export <int>
Release zebra label registry on unconfiguration.
Fixes: d162d5f6f5 ("bgpd: fix hardset l3vpn label available in mpls pool")
> bgpd: release manual vpn label on instance deletion

- tools/frrcommon.sh.in
Our startup scripts allow the passing of a cli command to all daemons started.  Recently -w was added to handle namespaces better, but watchfrr was not included.  This caused people using startup scripts to be a bit unhappy. Let's get them rolling by adding a quick and dirty ignoring of that flag to watchfrr.
Fixes: #18107
> watchfrr: Allow -w option to be ignored

- bgpd/bgp_packet.c
We are very very rarely seeing this crash:
0 0x7f36ba48e389 in prefix_list_apply_ext lib/plist.c:789
1 0x55eff3fa4126 in subgroup_announce_check bgpd/bgp_route.c:2334
2 0x55eff3fa858e in subgroup_process_announce_selected bgpd/bgp_route.c:3440
3 0x55eff4016488 in subgroup_announce_table bgpd/bgp_updgrp_adv.c:808
4 0x55eff401664e in subgroup_announce_route bgpd/bgp_updgrp_adv.c:861
5 0x55eff40111df in peer_af_announce_route bgpd/bgp_updgrp.c:2223
6 0x55eff3f884cb in bgp_announce_route_timer_expired bgpd/bgp_route.c:5892
7 0x7f36ba4ec239 in event_call lib/event.c:2019
8 0x7f36ba41a22a in frr_run lib/libfrr.c:1295
9 0x55eff3e668b7 in main bgpd/bgp_main.c:557
10 0x7f36b9e2d249 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
11 0x7f36b9e2d304 in __libc_start_main_impl …
> bgpd: When removing the prefix list drop the pointer

- lib/srv6.c
Manual backport of #18023 for FRR 10.0
> lib: fix false context information for SRv6 route (backport #18023 for 10.0) 

- lib/srv6.c
Manual backport of https://github.com/FRRouting/frr/pull/18023 for FRR 10.1
> lib: fix false context information for SRv6 route (backport #18023 for 10.1)

- sharpd/sharp_vty.c
This adds 2 commands, one that should just straight up SEGV, another that should trip an ASAN warning for an use-after-free.
---
This is for 2nd order testing, i.e. testing how the tests handle crashes and ASAN reports. Not used yet (it's easier to first add this into master and then muck around with CI components.)
Code 'hidden' from static analysis for obvious reasons.
> sharpd: add `crashme` commands

- isisd/isis_srv6.c
- isisd/isis_srv6.h
- isisd/isis_zebra.c
When SRv6 is enabled and an SRv6 locator is specified in the IS-IS configuration, IS-IS may attempt to request SRv6 locator information from zebra before the connection is fully established. If this occurs, the request fails with the following error:
```
2025/02/14 21:41:20 ISIS: [HR66R-TWQYD][EC 100663302] srv6_manager_get_locator: invalid zclient socket
````
As a result, IS-IS is unable to obtain the locator information, preventing SRv6 from working.
This PR fixes the issue by ensuring IS-IS requests SRv6 locator information once the connection with zebra is successfully established.
> isisd: Request SRv6 locator after zebra connection

- bgpd/bgp_evpn_vty.c
evpn route-targets are decoded in  ... multiple places; at least two places don't decode the AS4 form correctly.
> bgpd: fix vty output of evpn route-target AS4

- lib/keychain_nb.c
- lib/northbound.c
- lib/northbound.h
Previously the code was only calling the child destroy callbacks if the target deleted node was a non-presence container. We now add a flag to the callback structure to instruct northbound to perform the rescursive delete.
- Fix wrong relative path lookup in keychain destroy callback
> lib: nb: call child destroy CBs when YANG container is deleted

- doc/user/basic.rst
- lib/prefix.c
- zebra/zebra_rib.c
Changes allow ipv4 class E addresses in the 240.0.0.0/4 range to be displayed and used as connected routes in zebra by default.
Reason for changes are cloud providers (with customers still using obsolete ipv4 protocol, i.e. Azure, AWS) running out of ip space and abusing class E for addressing instances (announced via BGP) over tunneling connections back to customers on premise infrastructure.
Kernel routing table:
```
root@frr:~# ip route
default via 192.168.1.1 dev enp10s0 
192.168.1.0/24 dev enp10s0 proto kernel scope link src 192.168.1.111
192.168.122.0/24 dev enp9s0 proto kernel scope link src 192.168.122.253
240.12.12.0/24 dev enp1s0 proto kernel scope link src 240.12.12.12 <---
240.80.45.0/24 dev enp1s0 proto kernel scope link src 240.80.45.1 <---
```
Without patch:
```
frr# show …
```
> Use ipv4 class E addresses (240.0.0.0/4) as connected routes by default

- doc/user/ripd.rst
The previous version incorrectly spelled the command as `ip split-horizon`. The correct command is `ip rip split-horizon`, as indicated in the code at line 675 of rip_cli.c.
> doc: correct `ip rip split-horizon` command in the documentation

- staticd/static_routes.c
Problem:
After networking restart, staticd unregistered the nexthop but failed to register the nexthop again, which caused the nexthop to remain inactive in zebra for static route.
Fix:
Call to static_zebra_nht_register() from static_install_path() was removed in 3c05d53bf8defc36acdfe6e78064e068d60c649f. Adding it back so that staticd can register the nexthop for static routes.
Testing:
After networking restart trigger on h1:
Before fix:
```
h1# show ipv6 route vrf vrf1012
Codes: K - kernel route, C - connected, L - local, S - static,
R - RIPng, O - OSPFv3, I - IS-IS, B - BGP, N - NHRP,
T - Table, A - Babel, D - SHARP, F - PBR, f - OpenFabric,
t - Table-Direct, Z - FRR,
VRF vrf1012:
S …
```
> staticd: Failed to register nexthop after networking restart

- zebra/zebra_cli.c
Closes https://github.com/FRRouting/frr/issues/17952
> zebra: Do not flush an existing vni configuration trying to remove wrong vni

- doc/user/pim.rst
- doc/user/pimv6.rst
- pimd/pim6_cmd.c
- pimd/pim_cmd.c
- pimd/pim_iface.c
- pimd/pim_iface.h
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- pimd/pim_pim.c
- pimd/pim_vty.c
- tests/topotests/multicast_features/r1/frr.conf
- tests/topotests/multicast_features/test_multicast_features.py
- yang/frr-pim.yang
This is a new PIM feature to filter undesired PIM neighbors from establishing sessions.
> pimd: filter neighbors by address

- tests/topotests/ospf_sr_te_topo1/rt1/ospfd.conf
- tests/topotests/ospf_sr_te_topo1/rt2/ospfd.conf
- tests/topotests/ospf_sr_te_topo1/rt4/ospfd.conf
- tests/topotests/ospf_sr_te_topo1/rt5/ospfd.conf
- tests/topotests/ospf_sr_te_topo1/rt6/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt1/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt2/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt3/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt4/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt5/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt6/ospfd.conf
- tests/topotests/ospf_tilfa_topo1/rt1/ospfd.conf
- tests/topotests/ospf_tilfa_topo1/rt2/ospfd.conf
- tests/topotests/ospf_tilfa_topo1/rt3/ospfd.conf
- tests/topotests/ospf_tilfa_topo1/rt4/ospfd.conf
- tests/topotests/ospf_tilfa_topo1/rt5/ospfd.conf
- tests/topotests/pim_acl/r1/ospfd.conf
Several tests have warnings about the passive
command and how to use it.  Let's address this.
> tests: Remove warning about passive command

- bgpd/bgp_packet.c
I was pointed at yet another crash in the orf code.  I think it stems from basicaly the same problem as the last one.  Let's just make sure that the orf_plist is handled appropriately.
> bgpd: Fix another crash in orf

- pimd/pim_register.c
Topology:
A single router is acting as the First Hop Router (FHR), Last Hop Router (LHR), and RP.
RC and Issue:
When an upstream S,G is in join state, it sends a register message to the RP. If the RP has the receiver, it sends a register stop message and switches to the shortest path. When the register stop message is processed, it removes pimreg, moves to prune, and starts the reg stop timer.
When the reg stop timer expires, PIM changes S,G state to Join Pending and sends out a NULL register message to RP. RP receives it and fails to send Reg stop because SPT is not set at that point.
The problem is when the register stop timer pops and state is in Join Pending. According to https://www.rfc-editor.org/rfc/rfc4601#section-4.4.1, we need to put back the pimreg reg tunnel into the S,G …
> pimd: Fix for data packet loss when FHR is LHR and RP

- ospf6d/ospf6d.h
- ripngd/ripng_interface.c
- zebra/rtadv.c
Headers include this stuff now.  No need for it
in our code base.
> *: Remove unneeded IPV6_JOIN|LEAVE_GROUP

- bgpd/bgp_route.c
As part of the upstream master commit (f3575f61c7 bgpd: Sort the bgp_path_inf) the snippet of the code for dmed check condition left out, which leads to an issue of selecting incorrect bestpath.
As an example:
During the bestpath selection local route looses to another path due to dmed condition being hit.
The snippet of the logs:
```
2025/02/20 03:06:20.131441 BGP: [JW7VP-K1YVV] [2]:[0]:[48]:[00:92:00:00:00:10](VRF default): Comparing path 27.0.0.7 flags Valid  with path Static announcement flags Selected Valid Attr Changed Unsorted 
2025/02/20 03:06:20.131445 BGP: [SYTDR-QV6X9] [2]:[0]:[48]:[00:92:00:00:00:10]: path 27.0.0.7 loses to path Static announcement as ES 03:44:38:39:ff:ff:02:00:00:01 is same and local 
2025/02/20 03:06:20.131452 BGP: [JW7VP-K1YVV] …
```
> bgpd: remove dmed check not required in bestpath selection

- tests/topotests/zebra_operational_data/r1/frr.conf
- tests/topotests/zebra_operational_data/test_zebra_operational.py
- yang/frr-zebra.yang
- zebra/zebra_nb.c
- zebra/zebra_nb.h
- zebra/zebra_nb_state.c
The multipath number specified is not available through the yang data and is not retrievable.  Make it so. At this point in time do not allow this to be set from yang.  Perhaps in the future.
> zebra: Add operational retrieval of Multipath Number

- pimd/pim_autorp.c
- pimd/pim_autorp.h
- pimd/pim_instance.c
- pimd/pim_mroute.c
Bind the autorp socket to the vrf device.
Also fixed mroute socket to use vrf_bind instead of directly setting the socket option.
> pim: Fix vrf binding of autorp and mroute socket

- ospfd/ospf_lsa.c
- ospfd/ospf_lsa.h
- zebra/zebra_dplane.c
> Drop unused code

- pimd/pim_autorp.c
- pimd/pim_iface.c
- tests/topotests/pim_autorp/test_pim_autorp.py
Group joining got broken when moving the autorp socket to open/close as needed. This fixes it so autorp group joining is properly handled as part of opening the socket.
This is a manual backport of pull request https://github.com/FRRouting/frr/pull/18225 done by [Mergify](https://mergify.com/).
> pim: Fix autorp group joins (backport #18225)

- ripd/rip_cli.c
`no ip rip split-horizon poisoned-reverse` command will undo poisoned-reverse and set default behavior which is split-horizon. Currently, this command inadvertently disables split-horizon, which is inappropriate.
By contrast, `no ip rip split-horizon` will undo interface's split-horizon behavior.
> ripd: fix no ip rip split-horizon poisoned-reverse command

- staticd/static_zebra.c
With recent commit:
c1adc8f1d6795124df022a36388df173d217a34e staticd has started to crash aproximately 1/10 of the tine in the static_vrf topotest
(gdb) bt
0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140400982256064) at ./nptl/pthread_kill.c:44 1  __pthread_kill_internal (signo=6, threadid=140400982256064) at ./nptl/pthread_kill.c:78 2  __GI___pthread_kill (threadid=140400982256064, signo=signo@entry=6) at ./nptl/pthread_kill.c:89 3  0x00007fb1a6442476 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26 4  0x00007fb1a6950823 in core_handler (signo=6, siginfo=0x7ffd6d832ff0, context=0x7ffd6d832ec0) at lib/sigevent.c:268 5  <signal handler called>
6  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140400982256064) at ./nptl/pthread_kill.c:44 7 …
> staticd: Fix crash because registering unknown vrf

- doc/user/static.rst
- lib/srv6.h
- staticd/static_nb.c
- staticd/static_nb.h
- staticd/static_nb_config.c
- staticd/static_vty.c
- staticd/static_zebra.c
- tests/topotests/static_srv6_sids/expected_srv6_sids.json
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_1.json
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_delete_2.json
- tests/topotests/static_srv6_sids/r1/frr.conf
- yang/frr-staticd.yang
- zebra/zebra_srv6.c
The SRv6 support in staticd was introduced in PR #16894. The currently supported behaviors are uN, uDT4, uDT6, uDT46.
This PR extends the SRv6 uSID support in staticd to add support for the uA behavior.
> staticd: Add support for SRv6 uA behavior

- doc/manpages/frr-fabricd.rst
- doc/user/fabricd.rst
- isisd/isis_circuit.c
- isisd/isis_main.c
- isisd/isisd.c
- isisd/isisd.h
- lib/if.h
- zebra/if_netlink.c
- zebra/interface.c
- zebra/interface.h
- zebra/zebra_nb_state.c
Add interface status flag for interfaces of type "dummy" [0]. Add fabricd option to treat dummy interfaces as loopback interfaces.
This is a (kind of) continuation of  #10679.
This patch enables dummy-interfaces to be used as router-id interfaces in openfabric networks. This allows us to have multiple openfabric routers with different router-id's on a single node when using a ip unnumbered setup (interfaces without ip's configured). Previously we were limited by only having a single loopback interface, meaning only a single openfabric router was possible.
[0]: https://github.com/torvalds/linux/blob/master/drivers/net/dummy.c
> fabricd: add option to treat dummy interfaces as loopback interfaces

- lib/northbound.c
- lib/northbound.h
- lib/northbound_notif.c
- lib/northbound_oper.c
- lib/yang.c
- lib/yang.h
- tests/lib/northbound/test_oper_data.c
- tests/lib/northbound/test_oper_data.refout
- tests/lib/northbound/test_oper_exists.c
- tests/lib/northbound/test_oper_exists.in
- tests/lib/northbound/test_oper_exists.py
- tests/lib/northbound/test_oper_exists.refout
- tests/lib/subdir.am
- yang/frr-test-module.yang
Fix bug with list data queries. The capacity of the xpath string was not guaranteed to be sufficient to hold all the key predicates and so would truncate. Calculate the required space and guarantee that it is available. This is an easy to hit bug.
This also fixes a bug with specific (position specified) queries on keyless
lists. If the `get_next` callback is using the parent entry it will probably
crash as the code is passing the list_entry as both parent and child in the
specific lookup case.
There may currently be no code that uses the parent entry if the child entry is
non-NULL, though.
> support pre-built oper state in libyang tree

- tests/topotests/lib/bgp.py
Missing comma between the key-value pairs
Input dictionary is a missing comma between the key-value pairs
Ex:
"default_originate":{
"neighbor":"R2",
"add_type":"lo"  <----- 
"route_map":"rm"
},
> tests: Fixed input dict at create_router_bgp

- ospf6d/ospf6_intra.c
This PR fixes FRR issue https://github.com/FRRouting/frr/issues/18040. The OSPFv3 route is locked during the ABR calculation since there are scenarios under which it is freed. The OSPFv3 ABR computation is sub-optimal and this PR doesn't attempt to rework it.
> ospf6d: Fix use after free of router in OSPFv3 ABR route calculation.

- staticd/static_nb_config.c
When running valgrind, the following error is observed.
```
==2474568== Memcheck, a memory error detector
==2474568== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2474568== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2474568== Command: /usr/lib/frr/staticd --command-log-always --log file:staticd.log --log-level debug -d
==2474568== Parent PID: 2474525
==2474568==
==2474568== Conditional jump or move depends on uninitialised value(s)
==2474568==    at 0x490B32A: inet_ntop (ntop.c:105)
==2474568==    by 0x49AB9CB: printfrr_i6 (prefix.c:1614)
==2474568==    by 0x4A24B19: printfrr_extp (glue.c:220)
==2474568==    by 0x4A2286E: vbprintfrr (vfprintf.c:626)
==2474568==    by 0x4A12AE2: zlog_msg_text (zlog.c:838)
==2474568==    by 0x4A11B83: vzlog_tls …
```
> staticd: Do not log uninitialized `nexthop` variable

- lib/zclient.c
ldpd has this crash:
(gdb) bt
0  __pthread_kill_implementation (no_tid=0, signo=11, threadid=140329211443648) at ./nptl/pthread_kill.c:44 1  __pthread_kill_internal (signo=11, threadid=140329211443648) at ./nptl/pthread_kill.c:78 2  __GI___pthread_kill (threadid=140329211443648, signo=signo@entry=11) at ./nptl/pthread_kill.c:89 3  0x00007fa0f0642476 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26 4  0x00007fa0f0b51944 in core_handler (signo=11, siginfo=0x7fff562810b0, context=0x7fff56280f80) at lib/sigevent.c:268 5  <signal handler called>
6  0x00007fa0f0b9534d in lm_get_label_chunk (zclient=0x0, keep=0 '\000', base=0, chunk_size=64, start=0x7fff56281bdc, end=0x7fff56281be0) at lib/zclient.c:3667 7  0x0000564e0d1c011e in lde_get_label_chunk () at ldpd/lde.c:2211 8 …
> lib: Prevent crash in getting label chunk

- mgmtd/mgmt_txn.c
ci is picking up this use after free on occasion:
ERROR: AddressSanitizer: attempting to call malloc_usable_size() for pointer which is not owned: 0x6030001d94a0
0 0x7fab994b7f04 in __interceptor_malloc_usable_size ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:119
1 0x7fab994264f6 in __sanitizer::BufferedStackTrace::Unwind(unsigned long, unsigned long, void*, bool, unsigned int) ../../../../src/libsanitizer/sanitizer_common/sanitizer_stacktrace.h:131
2 0x7fab994264f6 in __asan::asan_malloc_usable_size(void const*, unsigned long, unsigned long) ../../../../src/libsanitizer/asan/asan_allocator.cpp:1058
3 0x7fab99039bcf in mt_count_free lib/memory.c:78
4 0x7fab99039bcf in qfree lib/memory.c:130
5 0x7fab98ff971a in hash_clean lib/hash.c:290
6 0x56110cdb0e7f in mgmt_txn_hash_destroy …
> mgmtd: Prevent use after free

- bgpd/bgp_clist.c
- bgpd/bgp_clist.h
- bgpd/bgp_ecommunity.c
- bgpd/bgp_ecommunity.h
- bgpd/bgp_routemap.c
- bgpd/bgp_routemap_nb.c
- bgpd/bgp_routemap_nb.h
- bgpd/bgp_routemap_nb_config.c
- doc/user/bgp.rst
- lib/routemap.h
- lib/routemap_cli.c
- tests/topotests/bgp_ecomm_list_match/r1/frr.conf
- tests/topotests/bgp_ecomm_list_match/r2/frr.conf
- tests/topotests/bgp_ecomm_list_match/r3/frr.conf
- tests/topotests/bgp_ecomm_list_match/test_bgp_ecomm_list_match.py
- yang/frr-bgp-route-map.yang
Add extensions in route-map for handling extended community-list in match operations:
- add the exact-match and the any options
- add the extcommunity-limit count
> Bgp ecommlist count

- pimd/pim_igmpv3.c
When the IGMP group source limit is reached the function `igmp_get_source_by_addr` won't return a `struct gm_source` so we must test for that condition before attempting to access its fields.
Fixes coverity scan issue 1637406.
> pimd: fix null memory access on IGMP source limit

- tools/frr-reload.py
```
[...]
srv6
static-sids
sid fcbb:bbbb:1::/48 locator MAIN behavior uN
sid fcbb:bbbb:1:fe10::/64 locator MAIN behavior uDT4 vrf Vrf10
sid fcbb:bbbb:1:fe20::/64 locator MAIN behavior uDT6 vrf Vrf20
sid fcbb:bbbb:1:fe30::/64 locator MAIN behavior uDT46 vrf Vrf30
sid fcbb:bbbb:1:fe40::/64 locator MAIN behavior uA interface sr0 nexthop 2001::2
[...]
```
When the user has a configuration like the one above and runs the command `frr-reload.py --reload`, the following error occurs:
```
[1129654|mgmtd] sending configuration
line 17: % Unknown command[76]:   sid fcbb:bbbb:1::/48 locator MAIN behavior uN
line 23: % Unknown command[76]:   sid fcbb:bbbb:1:fe10::/64 locator MAIN behavior uDT4 vrf Vrf10
line 29: % Unknown command[76]:   sid fcbb:bbbb:1:fe20::/64 locator MAIN behavior …
```
> tools: Fix `frr-reload.py` error related to `static-sids`

- bgpd/bgp_aspath.c
- bgpd/bgp_aspath.h
- bgpd/bgp_route.c
- doc/user/bgp.rst
- tests/topotests/bgp_reject_as_sets/r2/bgpd.conf
- tests/topotests/bgp_reject_as_sets/r2/zebra.conf
- tests/topotests/bgp_reject_as_sets/r4/bgpd.conf
- tests/topotests/bgp_reject_as_sets/r4/zebra.conf
- tests/topotests/bgp_reject_as_sets/test_bgp_reject_as_sets.py
=> updates according to https://datatracker.ietf.org/doc/html/draft-ietf-idr-deprecate-as-set-confed-set-16
> bgpd: Do not advertise aggregate routes to contributing ASes

- yang/frr-zebra.yang
- zebra/zebra_nb.c
- zebra/zebra_nb.h
- zebra/zebra_nb_state.c
allow retrieval of forwarding state
> Allow retrieval of v4/v6 forwarding state via NB

- bfdd/bfd.c
- bfdd/bfd.h
- bfdd/bfdd_cli.c
- bfdd/bfdd_nb.c
- bfdd/bfdd_nb.h
- bfdd/bfdd_nb_config.c
- bfdd/bfdd_vty.c
- bfdd/dplane.c
- doc/user/bfd.rst
- tests/topotests/bfd_topo1/r1/bfdd.conf
- tests/topotests/bfd_topo1/r2/bfdd.conf
- yang/frr-bfdd.yang
This PR includes changes to:
bfdd: Add feature support for "log-session-changes" command and operational state via frr-bfd.yang model and northbound API.
yang:  Add log-session-changes leaf to session-common in frr-bfdd.yang model.
tests: Add "log-session-changes" to a couple configs. 
doc: Add "log-session-changes" command to BFD user documentation.
> bfdd: Add "log-session-changes" command to BFD configuration and operational state via YANG Northbound API. 

- lib/vrf.c
This value in the yang tree was returning NULL for when the state of the vrf was not active.  It should return a false.
Before:
eva# show mgmt get-data /frr-vrf:lib/vrf[name="vrf1"] {
"frr-vrf:lib": {
"vrf": [
{
"name": "vrf1",
"state": {
"id": 4294967295
}
eva# show mgmt get-data /frr-vrf:lib/vrf[name="BLUE"] {
"frr-vrf:lib": {
"vrf": [
{
"name": "BLUE",
"state": {
"id": 68,
"active": true
},
After:
eva# show mgmt get-data /frr-vrf:lib/vrf[name="vrf1"] {
"frr-vrf:lib": {
"vrf": [
{
"name": "vrf1",
"state": {
"id": 4294967295,
"active": false
}
eva# show mgmt get-data /frr-vrf:lib/vrf[name="BLUE"] {
"frr-vrf:lib": {
"vrf": [
{
"name": "BLUE",
"state": {
"id": 68,
"active": true
},
> lib: Correct handling of /frr-vrf:lib/vrf/state/active

- bgpd/bgp_fsm.c
- bgpd/bgp_keepalives.c
- bgpd/bgp_network.c
- bgpd/bgp_packet.c
- bgpd/bgp_packet.h
- bgpd/bgpd.c
- bgpd/bgpd.h
See individual commits.  But the gist of these commits is to further cleanup usages of the connection instead of the peer.  Additionally clean up bgp_accept to have a better naming convention.
> More connection cleanup

- doc/user/subdir.am
Automake generates [default targets](https://www.gnu.org/software/automake/manual/automake.html#Texinfo) for `info`, `html`, `pdf` and corresponding `install-info` and `install-html` targets to install the artifacts generated by those rules. Prior to this change we are overriding those targets which results in automake warnings:
```
lib/subdir.am:545: warning: user target '.l.c' defined here ...
Makefile.am:178:   'lib/subdir.am' included from here
/nix/store/kwhvl2c4m4dfv91pamx4xxp7np0r1xwq-automake-1.16.5/share/automake-1.16/am/lex.am: ... overrides Automake target '.l.c' defined here
configure.ac: installing 'm4/ac/ylwrap'
lib/subdir.am:547: warning: user target '.y.c' defined here ...
Makefile.am:178:   'lib/subdir.am' included from here …
```
> doc: don't override automake builtin targets

- lib/libfrr.c
The --command-log-always was not being listed as a valid option for when the operator issues a <daemon> --help command line.
> lib: Document --command-log-always in help

- bgpd/bgp_route.c
Coverity rightly points out that the worse pointer cannot be null in this section of code.  Fix it.
> bgpd: Fix dead code in bgp_route.c #1637664

- lib/bitfield.h
use memcpy in bf_copy() instead of copy word by word in for loop
> lib: use memcpy in bf_copy

- tests/topotests/lib/topotest.py
Topotests startup by starting mgmtd/zebra/staticd then everything else.  Unfortunately the problem is that under heavy system load other daemons can get ahead of zebra( and probably mgmtd too ) and attempt to connect to zebra before it is ready.  If this happens there tests can and are thrown off because some daemons don't have great recovery mechanisms for reconnection to zebra.  
Modify the tests so that mgmtd and zebra are actually ensured that they are up and ready before continuing on with the other daemons.
> Topotest startup order

- tests/topotests/lib/bmp_collector/bmpserver.py
Fixed NameError at bmpserver.py
except socket.error as sock_err:
timestamp_print(f"Socket error: {e}")  <---- NameError
> tests: Fixed NameError at bmpserver.py

- lib/zclient.c
- lib/zclient.h
- tests/topotests/zebra_rib/r1/import_mrib_table_2.json
- tests/topotests/zebra_rib/r1/import_mrib_table_3.json
- tests/topotests/zebra_rib/r1/import_mrib_table_4.json
- tests/topotests/zebra_rib/r1/import_table_2.json
- tests/topotests/zebra_rib/r1/import_table_3.json
- tests/topotests/zebra_rib/r1/import_table_4.json
- tests/topotests/zebra_rib/r1/v4_route_table_1_no_vrf.json
- tests/topotests/zebra_rib/r1/v4_route_table_1_no_vrf.txt
- tests/topotests/zebra_rib/r1/v4_route_table_1_vrf_red.json
- tests/topotests/zebra_rib/r1/v4_route_table_1_vrf_red.txt
- tests/topotests/zebra_rib/test_zebra_rib.py
- zebra/zebra_nhg.c
- zebra/zebra_nhg.h
- zebra/zebra_rib.c
- zebra/zebra_vrf.c
- zebra/zebra_vrf.h
Fix a heap-after-free that causes zebra to crash even without address-sanitizer. To reproduce:
> echo "100 my_table" | tee -a /etc/iproute2/rt_tables
> ip route add blackhole default table 100
> ip route show table 100
> ip l add red type vrf table 100
> ip l del red
> ip route del blackhole default table 100
> ==2866266==ERROR: AddressSanitizer: heap-use-after-free on address 0x606000154f54 at pc 0x7fa32474b83f bp 0x7ffe94f67d90 sp 0x7ffe94f67d88
> READ of size 1 at 0x606000154f54 thread T0
>     #0 0x7fa32474b83e in rn_hash_node_const_find lib/table.c:28
>     #1 0x7fa32474bab1 in rn_hash_node_find lib/table.c:28
>     #2 0x7fa32474d783 in route_node_get lib/table.c:283
>     #3 0x7fa3247328dd in srcdest_rnode_get lib/srcdest_table.c:231
>     #4 0x55b0e4fa8da4 in rib_find_rn_from_ctx …
> zebra: fix table heap-after-free crash

- zebra/zebra_neigh.c
Issue:
Not freeing the neighbor n  within the same function can lead to
memory leak.
zebra_neigh_del_all() -> zebra_neigh_del() re lookup and free
Fix: not accessing n after its freed.
Directly free the neighbor entry (n) when its interface index matches
ifp->ifindex.
This fixes:
ERROR: AddressSanitizer: heap-use-after-free on address 0x6070001052e8 at pc 0x7f6bf7d09ddb bp 0x7ffd3366a000 sp 0x7ffd33669ff0 READ of size 8 at 0x6070001052e8 thread T0
#0 0x7f6bf7d09dda in _rb_next lib/openbsd-tree.c:455
#1 0x55f95a307261 in zebra_neigh_rb_head_RB_NEXT zebra/zebra_neigh.h:34
#2 0x55f95a3082e9 in zebra_neigh_del_all zebra/zebra_neigh.c:162
#3 0x55f95a121ee7 in zebra_interface_down_update zebra/redistribute.c:571
#4 0x55f95a0f819d in if_down zebra/interface.c:1017
#5 0x55f95a0fe168 in …
> zebra: Fix neigh delete causing heap-use-after-free error

- staticd/static_routes.c
- staticd/static_routes.h
- staticd/static_zebra.c
CI tests are showing cases where staticd is connecting to zebra after config is read in and the nexthops are never being registered w/ zebra:
2025/03/11 15:39:44 STATIC: [T83RR-8SM5G] staticd 10.4-dev starting: vty@2616
2025/03/11 15:39:45 STATIC: [GH3PB-C7X4Y] Static Route to 13.13.13.13/32 not installed currently because dependent config not fully available
2025/03/11 15:39:45 STATIC: [RHJK1-M5FAR] static_zebra_nht_register: Failure to send nexthop 1.1.1.2/32 for 11.11.11.11/32 to zebra
2025/03/11 15:39:45 STATIC: [M7Q4P-46WDR] vty[14]@> enable
Zebra shows connection time as:
2025/03/11 15:39:45.933343 ZEBRA: [V98V0-MTWPF] client 5 says hello and bids fair to announce only static routes vrf=0
As a result staticd never installs the route because it has no nexthop tracking to say that the …
> staticd: Install known nexthops upon connection with zebra

- doc/developer/topotests.rst
- tests/topotests/lib/topogen.py
- tests/topotests/lib/topotest.py
Backport some missing topotest infrastructure changes so that the v6_nexthop_group_recursive_resolution test can properly run on this branch.
> Backport missing frr config to 10.1

- tests/topotests/bgp_comm_list_match/test_bgp_comm_list_match.py
- tests/topotests/bgp_ecomm_list_match/test_bgp_ecomm_list_match.py
Add some more testing for when the community limit and extcommunity limit commands over the route-map are set to 0.
> Add Testing for community and Extended community match limit zero

- bgpd/bgp_route.c
The command `show bgp <afi> <safi>` has this output:
r1# show bgp ipv4 uni 10.0.0.0
BGP routing table entry for 10.0.0.0/32, version 1 Paths: (1 available, best #1, table default)
Advertised to non peer-group peers:
r1-eth0 r1-eth1 r1-eth2 r1-eth3
....
It specifically states `Advertised to non peer-group peers:` yet the code is not filtering those out.
> bgpd: Show bgp <afi> <safi> shouldn't display peers in groups

- isisd/isisd.h
Resolve conflict between F_ISIS_UNIT_TEST and ISIS_OPT_DUMMY_AS_LOOPBACK (introduced in #18242) which were both using the same bit value (0x01). This collision caused unit test mode to be unintentionally enabled when DUMMY_AS_LOOPBACK was set.
> isisd: fix bit flag collision in options field

- lib/darr.h
- lib/northbound_oper.c
- tests/lib/test_darr.c
lib: make sure we update the darr_strlen from pruned string.
This fixes a bug when handling of queries which include list nodes in
the xpath.
> Fix bug with oper-state queries including list node

- ospf6d/ospf6_area.c
- ospf6d/ospf6_area.h
- ospf6d/ospf6_interface.c
ospf6d: Disable and delete OSPFv3 areas that no longer have interfaces or configuration.
This fix will delete an OSPFv3 area when all the interfaces and
configuration (ranges, NSSA ranges, stub area, NSSA area, filter-list,
import-list and export-list) have been removed. The changes provides
a general solution to https://github.com/FRRouting/frr/issues/18324.
Signed-off-by: Acee Lindem <acee@lindem.com>
> ospf6d: Disable and delete OSPFv3 areas that no longer have interfaces or configuration.

- bgpd/bgp_packet.c
The call into bgp_open_capability can return that it wrote more than BGP_OPEN_NON_EXT_OPT_LEN bytes, in that case the open part needs to be written again with ext_opt_params set to true to allow extended parameters to be written thus keeping the len < 255 bytes.  The code to do this was first creating a new stream and then copying into it the stream, trying to call bgp_open_capability() and if it succeeded recopying the tmp stream back onto the original.
Let's change this around such that we save the current spot in the stream of where we are writing and if the change does not work reset the pointer and try again with the correct parameter.  This removes the stream and multiple copies and eventual free of the temporary stream.
> bgpd: Remove unnecessary stream_new/stream_copies in bgp_open_make

- bgpd/bgp_route.c
BT:
```
3  <signal handler called>
4  0x00005616837546fc in bgp_static_update (bgp=bgp@entry=0x5616865eac50, p=0x561686639e40,
bgp_static=0x561686639f50, afi=afi@entry=AFI_IP6, safi=safi@entry=SAFI_UNICAST) at ../bgpd/bgp_route.c:7232
5  0x0000561683754ad0 in bgp_static_add (bgp=0x5616865eac50) at ../bgpd/bgp_table.h:413
6  0x0000561683785e2e in no_bgp_network_import_check (self=<optimized out>, vty=0x5616865e04c0,
argc=<optimized out>, argv=<optimized out>) at ../bgpd/bgp_vty.c:4609
7  0x00007fdbcc294820 in cmd_execute_command_real (vline=vline@entry=0x561686663000,
```
The program encountered a SEG FAULT when attempting to access pi->extra->vrfleak->bgp_orig because pi->extra->vrfleak was NULL.
```
(gdb) p pi->extra->vrfleak
$1 = (struct bgp_path_info_extra_vrfleak *) 0x0
(gdb) p …
```
> bgpd: Fixed crash upon bgp network import-check command

- configure.ac
- tests/lib/cli/test_cli.refout.in
- tests/lib/northbound/test_oper_exists.c
- fix `make check` when user overrides --log-timestamp-precision in configure
- fix a compile warning
> 2 unit-test fixes

- bgpd/bgpd.c
- tests/topotests/bgp_vpn_5549_route_map/test_bgp_vpn_5549_route_map.py
- zebra/interface.c
- zebra/interface.h
- zebra/rtadv.c
If bgpd instance is removed, then the rtadv is not disabled.
Like it was done when a peer is unconfigured,
do the same at BGP unconfiguration: unregister rtadv before deleting a peer.
Add a rtadv json fields. Create a topotest to check that newly added json fields are present.
> bgpd, zebra, tests: disable rtadv when bgp instance unconfiguration.

- vrrpd/vrrp_vty.c
Make the VRRP version information always visible in the running configuration output, regardless of whether it's the default value (version 3) or not.
**_Problem_**
When using frr-reload.py to apply configuration changes, VRRP instances were being unnecessarily reinitialized even when no actual configuration changes were made. This occurred because:
The cli_show_vrrp function in vrrpd/vrrp_vty.c does not display the VRRP version in the show running-config output when it's the default value (version 3).
Configuration files often explicitly specify vrrp X version 3 even though it's the default.
When frr-reload.py compares the explicit configuration with the running configuration, it detects a difference and generates commands to remove and recreate the VRRP instance.
For example： 
original …
> fix(vrrp): display vrrp version by default

- doc/developer/lists.rst
The typesafe documentation needs a bit of warning about how they can cause problems on conversion.
> doc: Modify typesafe documentation

- ripngd/ripng_main.c
ripngd:     Access List                   :      1 *         56
ripngd:     Access List Str               :      1 *          3
ripngd:     Access Filter                 :      1 *        112
ripngd:     Prefix List                   :      1 *         88
ripngd:     Prefix List Str               :      1 *          3
ripngd:     Prefix List Entry             :      1 *        136
ripngd:     Prefix List Trie Table        :      4 *       4096
This is now fixed.
> ripngd: Access and Prefix lists are being leaked on shutdown

- redhat/frr.spec.in
Revert the broken change and added the correct changes
The change allows to build the RPMs without RPKI and/or without docs.
Default is building with them and is strongly suggested. The dependencies
for the RPKI (the librtr packages) is only there for build time and if the 
rpki sub-packages are installed.
Building without docs allows the build without the sphinx installed, but
this does not change any runtime dependencies (sphinx is only needed
for build), it only saves some disk space in the main frr rpm package
> RedHat: Fixing for PR17793 - Allow RPM build without docs and/or rpki

- lib/routing_nb_config.c
When creating a control plane protocol through NB, create the vrf if needed instead of only looking up and asserting if it doesn't exist yet.
Fixes #18429.
> lib: Create VRF if needed

- bgpd/bgpd.c
Since https://github.com/FRRouting/frr/commit/4d0e7a49cf8d4311a485281fa50bbff6ee8ca6cc ("bgpd: VRF-Lite fix default BGP delete"), upon deletion
of the default instance, it is marked as hidden and the "deletion
in progress" flag is set. When the instance is restored, some routes
are not installed due to the presence of this flag.
> bgpd: fix "delete in progress" flag on default instance

- tests/topotests/lib/topotest.py
See individual commits, but allow for zebra to be up and individual daemons to be attached to the daemon before a unified config is read in.
> Fix topotest to wait for zebra connection

- bgpd/bgp_route.c
The two memory leaks:
==387155== 744 (48 direct, 696 indirect) bytes in 1 blocks are definitely lost in loss record 222 of 262
==387155==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==387155==    by 0x4C1B982: json_object_new_object (in /usr/lib/x86_64-linux-gnu/libjson-c.so.5.1.0)
==387155==    by 0x2E4146: peer_adj_routes (bgp_route.c:15245)
==387155==    by 0x2E4F1A: show_ip_bgp_instance_neighbor_advertised_route_magic (bgp_route.c:15549)
==387155==    by 0x2B982B: show_ip_bgp_instance_neighbor_advertised_route (bgp_route_clippy.c:722)
==387155==    by 0x4915E6F: cmd_execute_command_real (command.c:1003)
==387155==    by 0x4915FE8: cmd_execute_command (command.c:1062)
==387155==    by 0x4916598: cmd_execute (command.c:1228)
==387155==    by …
> bgpd: Fix leaked memory when showing some bgp routes

- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
This is a topotest for issues like #10298 and #12391, where L3-VNI RMACs were lost due to queueing issues.
After getting my way around topotests this is now the upstreamed version of a test we do internally for every FRR version before using it.
A second path is added between R1 and R2 in the `bgp_evpn_rt5` topology, convergence is checked. Both paths are flapped alternately, checking for convergence and presence of the RMAC afterwards. Reverting #12524 (fix for #12391) breaks this test, as expected.
> topotests: Add EVPN RT5 multipath flap test

- pimd/pim_msdp.c
- pimd/pim_msdp_packet.c
According to RFC 3618 section 10.2
If a member R of a mesh-group M receives a SA message from an MSDP peer that is also a member of mesh-group M, R accepts the SA message and forwards it to all of its peers that are not part of mesh-group M.  R MUST NOT forward the SA message to other members of mesh-group M.
https://datatracker.ietf.org/doc/html/rfc3618#section-10.2
With the changes in this commit, if the SA message is received from a peer that is the part of same mesh group, the RPF check will be skipped and the SA will be processed. The SA message will be forwarded to only those peer that do not belong to the mesh-group of the originator SA packet
> pimd: Skip RPF check for SA message from mesh group peer

- lib/elf_py.c
This PR addresses a set of fixes related to static errors in lib, zebra, pbrd, isisd, bgpd.
Each commit provides a description of the error that was present before and is attempted to be corrected.
> lib: fix static analysis error

- tests/topotests/bgp_bmp/r1/frr.conf
- tests/topotests/bgp_bmp/r2/frr.conf
- tests/topotests/bgp_bmp/r3/frr.conf
Currently the tests appear to do this:
a) Start the neighbors
b) Start the bmp server connection
c) Look for the neighbors up
d) Look for the neighbor up messages in the bmp log
This is not great from a testing perspective in that even though we started a) first it may not happen
until after b) happens.  Or even worse if it is
partially up ( 1 of the 2 peers ) then the dump
will have the neighbor connecting after parts
of the table.  This doesn't work too well because
the SEQ number is something that is kept and compared to to make sure only new data is being looked at.
Let's modify the startup configuration to start
the bmp server first and then have a delayopen
on the bgp neighbor statements so that the bmp
peering can come up first.
> tests: Change up start order of bmp tests

- bgpd/bgp_route.c
- bgpd/bgp_routemap.c
- tests/topotests/bgp_evpn_route_map_set/c1/frr.conf
- tests/topotests/bgp_evpn_route_map_set/r1/frr.conf
- tests/topotests/bgp_evpn_route_map_set/r2/frr.conf
- tests/topotests/bgp_evpn_route_map_set/test_bgp_evpn_route_map_set.py
The `route_set_evpn_gateway_ip` function copies `gw_ip->ip.addr` in the route's gateway ip. In a nutshell, this skips the `ipa_type` field, writing the actual IP in the IP type. This later rightfully trips asserts about unknown IP types.
The following route-map...
```
route-map test permit 10
set evpn gateway-ip ipv4 1.1.1.1
```
...will make the following gateway IP in the route:
```
(gdb) p/x a1->evpn_overlay->gw_ip
$11 = {ipa_type = 0x1010101, ip = {addr = 0x0, addrbytes = {
0x0 <repeats 16 times>}, _v4_addr = {s_addr = 0x0}, _v6_addr = {
__in6_u = {__u6_addr8 = {0x0 <repeats 16 times>}, __u6_addr16 = {0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, __u6_addr32 = {0x0, 0x0, 0x0,
0x0}}}}}
```
We do indeed see the IP Address in the `ipa_type` field.
Fix by starting the memcpy at the root of …
> bgpd: fix `set evpn gateway-ip ipv[46]` route-map

- tests/topotests/high_ecmp/r1/frr.conf
- tests/topotests/high_ecmp/r2/frr.conf
The high_ecmp test was creating 2 update groups, where 513 of the neighbors are in 1 and the remaining is in another.  They should just all be in 1 update group. Modify the test creation such that interfaces r1-eth514 and r2-eth514 have v4 and v6 addresses.
> tests: high_ecmp creates 2 update groups

- staticd/static_nb_config.c
- tests/topotests/static_srv6_sids/expected_srv6_sids_sid_modify.json
- tests/topotests/static_srv6_sids/r1/setup.sh
- tests/topotests/static_srv6_sids/test_static_srv6_sids.py
When the user modifies an SRv6 SID and then removes all SIDs, staticd crashes:
```
2025/03/23 08:37:22.691860 STATIC: lib/memory.c:74: mt_count_free(): assertion (mt->n_alloc) failed
STATIC: Received signal 6 at 1742715442 (si_addr 0x8200007cf0); aborting...
STATIC: zlog_signal+0x390                  fcc704a844b8     ffffd7450390 /usr/lib/frr/libfrr.so.0 (mapped at 0xfcc704800000)
STATIC: core_handler+0x1f8                 fcc704b79990     ffffd7450590 /usr/lib/frr/libfrr.so.0 (mapped at 0xfcc704800000)
STATIC:     ---- signal ----
STATIC: ?                                  fcc705c008f8     ffffd74507a0 linux-vdso.so.1 (mapped at 0xfcc705c00000)
STATIC: pthread_key_delete+0x1a0           fcc70458f1f0     ffffd7451a00 /lib/aarch64-linux-gnu/libc.so.6 (mapped at 0xfcc704510000)
STATIC: …
```
> staticd: Fix a crash that occurs when modifying an SRv6 SID

- babeld/message.c
https://www.rfc-editor.org/rfc/rfc8966#name-route-request:
A Request TLV with AE set to 0 and Plen not set to 0 MUST be ignored.
> babeld: Missing Validation for AE=0 and Plen!=0

- bgpd/bgp_fsm.c
Commit:  cc9f21da2218d95567eff1501482ce58e6600f54
Modified the bgp_fsm code to dissallow the extension of the hold time when the system is under extremely heavy load.  This was a attempt to remove the return code but it was too aggressive and messed up this bit of code.
Put the behavior back that was introduced in:
d0874d195d0127009a7d9c06920c52c95319eff9
> bgpd: Fix holdtime not working properly when busy

- babeld/message.c
https://www.rfc-editor.org/rfc/rfc8966#section-4.6.8:
AE SHOULD be 1 (IPv4) or 3 (link-local IPv6), and MUST NOT be 0
> babeld: add check incorrect AE value for NH TLV.

- isisd/isis_circuit.c
- isisd/isis_circuit.h
- isisd/isis_vty_fabricd.c
When working with the ISIS protocol, I noticed the same issue occurring as previously addressed in #9092  The root cause is: "Sending a Hello message before restarting the hello timer to avoid session flaps in case of larger hello interval configurations."
> isisd:IS-IS hello packets not sent with configured hello timer

- babeld/message.c
[RFC 8966](https://www.rfc-editor.org/rfc/rfc8966#section-4.6.11-4.12):
Hop Count The maximum number of times that this TLV may be forwarded, plus 1. This MUST NOT be 0.
> babeld: Hop Count must not be 0.

- babeld/babel_interface.c
Same issue occurring as previously addressed in https://github.com/FRRouting/frr/pull/9092. The root cause is: "Sending a Hello message before restarting the hello timer to avoid session flaps in case of larger hello interval configurations."
> babeld: fix hello packets not sent with configured hello timer

- tests/topotests/ripng_aggregate_address/r2/frr.conf
- tests/topotests/ripng_aggregate_address/r3/frr.conf
- tests/topotests/ripng_aggregate_address/test_ripng_aggregate_address.py
Looking at gcov and noticed that ripngd does not
test any aggregate address addition/deletion
to ensure that it works.
> tests: Add ripng aggregate address testing

- bgpd/bgp_packet.c
- tests/topotests/bgp_gr_notification/r1/bgpd.conf
- tests/topotests/bgp_gr_notification/r2/bgpd.conf
- tests/topotests/bgp_gr_notification/test_bgp_gr_notification.py
Closes https://github.com/FRRouting/frr/issues/18238
> bgpd: Retain the routes if we do a clear with N-bit set for Graceful-Restart

- lib/routemap.c
This command:
route-map FOOBAR permit 10
set ipv6 next-hop prefer-global
set community 5060:12345 additive
!
When you issue a `show route-map ...` command displays this:
route-map: FOOBAR Invoked: 0 (0 milliseconds total) Optimization: enabled Processed Change: false
permit, sequence 5 Invoked 0 (0 milliseconds total)
Match clauses:
Set clauses:
ipv6 next-hop prefer-global (null)
community 5060:12345 additive
Call clause:
Action:
Exit routemap
Modify the code so that it no longer displays the NULL when there is nothing to display.
> lib: `show route-map` should not print (null)

- tests/topotests/lib/lutil.py
> tests: Irrelevant code in lutil.py

- doc/user/frr-reload.rst
- tools/frr-reload.py
Adding option --logfile to specify a different logfile instead of the default /var/log/frr/frr-reload.log
This solves the issue with multiple FRR instances running in different network namespaces to use different
logfiles
> tools: Add option to frr-reload to specify alternate logfile

- babeld/message.c
Missing next hop initialization:
The implementation does not initialize the next hop parser state from the source address at packet start, as required by RFC 8966 section 4.5 (https://www.rfc-editor.org/rfc/rfc8966#name-parser-state-and-encoding-o):
> for each address family (IPv4 or IPv6), the current next hop: this is the source address of the enclosing packet for the matching address family at the start of a packet
> babeld: Add next hop initialization

- yang/frr-eigrpd.yang
Currently EIGRP has built in yang code that expects only 1 ASN used per vrf.  Let's just limit the operator from putting themselves in a bad position by allowing something like this:
router eigrp 33
....
!
router eigrp 99
...
!
no router eigrp 99 would crash because of assumptions made in the yang processing.
Let's just hard code that assumption into the EIGRP yang at the moment such that it will not allow you to enter a `router eigrp 99` instance at all.
This is purely a software limitation to prevent the code from violating it's current assumptions.  I do not see much need to support this at this point in time so I fixed the problem this way instead of having to possibly touch a bunch of code.
> yang: Limit eigrp to just 1 instance per vrf

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn_mh.c
- bgpd/bgp_mplsvpn.c
- bgpd/bgp_route.c
- bgpd/rfapi/rfapi.c
Only call attrhash_cmp when necessary.
> bgpd: optimize attrhash_cmp calls

- bgpd/bgp_mac.c
Issue:
"Processing EVPN MAC interface change on peer" log message is printed even when the peer didnt have EVPN address family.
Fix:
Process only if the peer is in EVPN address family
Ticket: #17890
> bgpd: Skip EVPN MAC processing for non-EVPN peers

- bgpd/bgpd.c
- bgpd/rfapi/rfapi.c
- bgpd/rfapi/rfapi_backend.h
- bgpd/rfapi/rfapi_import.c
- bgpd/rfapi/rfapi_import.h
- bgpd/rfapi/rfapi_rib.c
- bgpd/rfapi/rfapi_rib.h
- tests/topotests/bgp_rfapi_basic_sanity/r3/bgpd.conf
- tests/topotests/bgp_rfapi_basic_sanity/scripts/cleanup_all.py
- tests/topotests/bgp_rfapi_basic_sanity_config2/r3/bgpd.conf
Original RFAPI code relied on the frr timer system to remember
various allocations that were supposed to be freed at future times
rather than manage a parallel database. However, if bgpd is terminated
before the times expire, those pending allocations are marked as
memory leaks, even though they wouldn't be leaks under normal operation.
This change adds some hash tables to track these outstanding
allocations that are associated with pending timers, and uses
those tables to free the allocations when bgpd exits.
> bgpd: rfapi: track outstanding rib and import timers, free mem at exit

- tests/topotests/bgp_gr_notification/test_bgp_gr_notification.py
`"` was accidentally added, and random tests failures happening.
Fixes: a4f61b78dd382c438ff4fec2fda7450ecc890edf ("tests: Check if routes are marked as stale and retained with N-bit for GR")
> tests: Fix typo when configuring delayopen timer

- babeld/message.c
The RFC https://www.rfc-editor.org/rfc/rfc8966#name-seqno-requests states:
>  if the node has one or more feasible routes towards the requested
prefix with a next hop that is not the requesting node, then the
node MUST forward the request to the next hop of one such route;
Modify route selection to check feasibility first, then fall back to non-feasible routes as per SHOULD requirement.
> babeld: Request forwarding does not prioritize feasible routes

- babeld/babeld.c
A router-id MUST NOT consist of either all binary zeroes (0000000000000000 hexadecimal) or all binary ones (FFFFFFFFFFFFFFFF hexadecimal).
> babeld: Add a check to prevent all-ones case

- babeld/message.c
The known_ae() function accepts AE values up to 4, but the RFC only defines AE values 0-3.
> babel: fix incorrect check in known_ae()

- pimd/pim_iface.c
The gm_join_list has a setup where it attempts to only create the list upon need and deletes it when the list is empty.  On interface shutdown it was calling the function to empty the list but it was not empty so the list was being left at the end.  Just add a bit of code to really clean up the list in the shutdown case.
Direct leak of 40 byte(s) in 1 object(s) allocated from:
0 0x7f84850b83b7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
1 0x7f8484c391c4 in qcalloc lib/memory.c:106
2 0x7f8484c1ad36 in list_new lib/linklist.c:49
3 0x55d982827252 in pim_if_gm_join_add pimd/pim_iface.c:1354
4 0x55d982852b59 in lib_interface_gmp_address_family_join_group_create pimd/pim_nb_config.c:4499
5 0x7f8484c6a5d3 in nb_callback_create lib/northbound.c:1512
6 …
> pimd: Fix memory leak on shutdown

- nhrpd/nhrp_peer.c
According to [RFC 2332, Section 5.1], if an NHS receives a packet that it would normally forward and the hop count is zero, it must send an error indication back to the source and drop the packet.
> nhrpd: Add Hop Count Validation Before Forwarding in nhrp_peer_recv()

- bgpd/bgpd.c
This commit fixes two types of problems:
a) Avoidance of cleaning up memory when a instance is hidden, thus causing it never to be freed on shutdown
b) In some instances bgp_create is called 2 times
for some code.  We are double allocating memory
and dropping it on the second allocation.
> bgpd: On shutdown free up memory leak found by topotest

- mgmtd/mgmt_ds.c
- mgmtd/mgmt_ds.h
- mgmtd/mgmt_fe_adapter.c
- mgmtd/mgmt_txn.c
Say you have 2 mgmtd frontend sessions (2 vtysh's) the first one is long
running and is actively changing the global candidate datastore (DS),
the second one starts and exits, this code would then copy running
back over the candidate, blowing away any changes made by the first
session.
(the long running session could technically be any user)
Instead we need to trust the various cleanup code that already exits.
For example in the commit_cfg_reply on success candidate is copied to
running, and on failure *for implicit commit* running is copied back to
candidate clearing the change. This leaves the non-implicit
configuration changes in this case we actually want candidate to keep
it's changes in transactional cases, in the other case of pending commit
during a file read the code restores …
> mgmtd: remove bogus "hedge" code which corrupted active candidate DS

- zebra/irdp_packet.c
My compiler is complaining about irdp_sock
being a shadow variable.
> zebra: Fix shadow warning in irdp_packet.c

- bgpd/bgp_route.c
Indirect leak of 56 byte(s) in 1 object(s) allocated from:
0 0x7fdaf6cb83b7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
1 0x7fdaf683a480 in qcalloc lib/memory.c:106
2 0x7fdaf68dd706 in route_table_init_with_delegate lib/table.c:38
3 0x5649b22c05b0 in bgp_table_init bgpd/bgp_table.c:139
4 0x5649b2273da0 in bgp_static_set bgpd/bgp_route.c:7779
5 0x5649b21eba58 in vpnv4_network bgpd/bgp_mplsvpn.c:3244
6 0x7fdaf67b6d61 in cmd_execute_command_real lib/command.c:1003
7 0x7fdaf67b7080 in cmd_execute_command lib/command.c:1062
8 0x7fdaf67b75ac in cmd_execute lib/command.c:1228
9 0x7fdaf68ffb20 in vty_command lib/vty.c:626
10 0x7fdaf6900073 in vty_execute lib/vty.c:1389
11 0x7fdaf6903e24 in vtysh_read lib/vty.c:2408
12 0x7fdaf68f0222 in event_call …
> bgpd: On shutdown free up table for static routes

- bfdd/bfd.c
According to RFC 5880 Section 6.3, once the remote peer reflects back the local discriminator, the receiver MUST demultiplex subsequent BFD packets based solely on the Your Discriminator field. The source IP or interface MUST NOT be used in demultiplexing once the session is established.
The current implementation incorrectly verifies the source address in
`bfd_find_disc()` even after the discriminator is known, which violates
the spec and can prevent valid packets from matching established sessions
(e.g., if the source IP or interface changes).
This patch removes the peer address check from `bfd_find_disc()`, ensuring
compliance with the RFC and supporting demultiplexing using only the Your
Discriminator field after session establishment.
> bfdd: Fix demultiplexing to rely solely on Your Discriminator 

- babeld/message.c
parse_request_subtlv accesses type using fixed offset instead of the current position.
> babeld: fix incorrect type assignment in parse_request_subtlv

- babeld/message.c
1. If the metric is infinite and AE is 0, Plen and Omitted MUST both be 0
2. Use INFINITY to replace 0xFFFF
3. Ignore unkown ae
4. If the metric field if 0xFFFF, a retraction happens So it is acceptable for no router_id when metric is 0xFFFF while ae is not 0.
> babeld: Add input validation for update TLV.

- bgpd/bgp_mplsvpn.c
Until now, BGP srv6 usid instructions were not really used. Add the support for this.
> bgpd: add usid behavior for bgp srv6 instructions

- bgpd/bgp_vty.c
The 'acceptedPrefixCounter' is available in 'show bgp neighbor json', but there is no equivalent when using the non json output. Add it.
> # show bgp neighbor
> [..]
>  Community attribute sent to this neighbor(all)
>  0 accepted prefixes, 1 sent prefixes
Fixes: 856ca177c4bb ("Added json formating support to show-...-neighbors-... bgp commands.")
> bgpd: fix add prefix sent in 'show bgp neighbor'

- babeld/message.c
according to RFC 8966: 
https://www.rfc-editor.org/rfc/rfc8966.html#name-padn
[PadN](https://www.rfc-editor.org/rfc/rfc8966.html#name-padn-2)
PadN TLV: MBZ must be zero
PadN SubTLV: MBZ must be zero
according to RFC 8966: 
[Acknowledgment Request](https://www.rfc-editor.org/rfc/rfc8966.html#name-acknowledgment-request)
[IHU](https://www.rfc-editor.org/rfc/rfc8966.html#name-ihu)
[Router-Id](https://www.rfc-editor.org/rfc/rfc8966.html#name-router-id-2)
[Next Hop](https://www.rfc-editor.org/rfc/rfc8966.html#name-next-hop)
[Seqno Request](https://www.rfc-editor.org/rfc/rfc8966.html#name-seqno-request)
'Reserved' field should be sent as 0
> babeld: Add MBZ and Reserved field checking

- tools/frr-reload.py
Current code implementation does not have a "no" form of handling for the following commands under segment-routing srv6
- no formats
- no locators
- no prefix <> under locator XYZ
Fix the handling of segment-routing srv6 locators and formats commands
- Ignore "no formats" and "no locators" command
- replace "no prefix" under locator XYZ as "no locator XYZ" as prefix is a mandatory property of locator
> tools: fix reload script for SRv6 locators and formats

- tests/topotests/lib/common_config.py
Shadowing the built-in function
Ex:
def set_seq_id(obj_type, router, **id <---**,  obj_name):
...
...
seq_id = int(seq_id) + int(id)  
def __exit__(self, **type <---**, value, traceback):
self.cleanup()
> tests: Shadowing the built-in function

- zebra/zapi_msg.c
- zebra/zebra_pbr.c
- zebra/zebra_pbr.h
We are obviously doing deleting on wrong object.
> Direct leak of 40 byte(s) in 1 object(s) allocated from:
>     #0 0x7fcf718b4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
>     #1 0x7fcf7126f8dd in qcalloc lib/memory.c:105
>     #2 0x7fcf7124401a in list_new lib/linklist.c:49
>     #3 0x55771621d86d in pbr_iptable_alloc_intern zebra/zebra_pbr.c:1015
>     #4 0x7fcf71217d79 in hash_get lib/hash.c:147
>     #5 0x55771621dad3 in zebra_pbr_add_iptable zebra/zebra_pbr.c:1030
>     #6 0x55771614d00c in zread_iptable zebra/zapi_msg.c:4131
>     #7 0x55771614e586 in zserv_handle_commands zebra/zapi_msg.c:4424
>     #8 0x5577162dae2c in zserv_process_messages zebra/zserv.c:521
>     #9 0x7fcf7137798e in event_call lib/event.c:2011
>     #10 …
> zebra: fix pbr_iptable memory leak

- zebra/fpm_listener.c
The fpm_listener currently has no ability to store the list of prefixes that it has received.  Modify the code to store the prefixes in a typesafe RB Tree.  Additionally modify the code such that when a SIGUSR1 is received to dump the routes out.  If the operator specifies a -z <filename> then write the routes to that file.  It will overwrite the last version of the file written.
> zebra: Add ability to dump routes received from fpm_listener

- doc/user/static.rst
- staticd/static_vty.c
- staticd/static_zebra.c
- tests/topotests/static_simple/test_static_simple.py
Routing v4 over an v6 nexthop is already well supported within zebra (and FRR). This adds support to staticd, allowing an IPv6 nexthop to be provided to ip route statements. For this the commands are extended and the address family is parsed from the parameter.
When receiving nht updates from zebra, both AFIs are checked because prefixes could exist in both. Additionally when route_node is known, family of prefix is used instead of nexthop.
see https://datatracker.ietf.org/doc/draft-chroboczek-intarea-v4-via-v6/
> Add v4-via-v6 nexthop support to staticd

- bgpd/bgp_packet.c
- lib/resolver.c
Clean up a couple of clang compiler warnings (this was clang 18)
> lib,bgpd: clean up clang warnings

- lib/northbound.c
- lib/northbound.h
- lib/northbound_oper.c
The existing iteration callback only allows for a daemon to return a
pointer to objects that must already exist and must continue to exists
indefinitely.
To allow the daemon to return allocated iterator objects and for locking
it's container structures we need a callback to tell the daemon when FRR
is done using the returned value, so the daemon can free it (or unlock
etc)
That's what list_entry_done() is for.
> lib: nb: add list_entry_done() callback to free resources

- bfdd/bfd.c
RFC 5880 6.8.16, need to set LocalDiag when transitioning to AdminDown state.
> bfdd: Set bfd.LocalDiag when transitioning to AdminDown

- tests/.gitignore
- tests/lib/northbound/test_oper_data.c
Use little-endian integer in a libyang api that seems to expect that. This might fix the recently-reported issue with debian packaging pre-reqs.
Also update the unit-tests' .gitignore to include a test binary.
Fixes: #18660
> tests: Fix northbound endian use in a unit-test

- isisd/isis_zebra.c
Seen with isis_srv6_topo1 topotest.
> ==178793==ERROR: LeakSanitizer: detected memory leaks
>
> Direct leak of 56 byte(s) in 1 object(s) allocated from:
>     #0 0x7f3f63cb4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
>     #1 0x7f3f6366f8dd in qcalloc lib/memory.c:105
>     #2 0x561b810c62b7 in isis_srv6_sid_alloc isisd/isis_srv6.c:243
>     #3 0x561b8111f944 in isis_zebra_srv6_sid_notify isisd/isis_zebra.c:1534
>     #4 0x7f3f637df9d7 in zclient_read lib/zclient.c:4845
>     #5 0x7f3f637779b2 in event_call lib/event.c:2011
>     #6 0x7f3f63642ff1 in frr_run lib/libfrr.c:1216
>     #7 0x561b81018bf2 in main isisd/isis_main.c:360
>     #8 0x7f3f63029d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
Fixes: 0af0f4616d ("isisd: …
> isisd: fix srv6_sid memory leak

- zebra/dplane_fpm_nl.c
- zebra/zebra_dplane.c
- zebra/zebra_dplane.h
Make code changes in fpm_read to create a list of ctx and send it to zebra for processing rather than sending individual ctx
> zebra: change fpm_read to batch the messages

- zebra/rib.h
- zebra/zebra_rib.c
- zebra/zebra_vty.c
Display below info from metaq and sub queues
1. Current queue size
2. Max/Highwater size
3. Total number of events received fo so far
```
r1# sh zebra metaq
MetaQ Summary
Current Size    : 0
Max Size        : 9
Total           : 20
|------------------------------------------------------------------|
| SubQ                             | Current  | Max Size  | Total  |
|----------------------------------+----------+-----------+--------|
| NHG Objects                      | 0        | 0         | 0      |
|----------------------------------+----------+-----------+--------|
| EVPN/VxLan Objects               | 0        | 0         | 0      |
|----------------------------------+----------+-----------+--------|
| Early Route Processing           | 0        | 8         | 11     | …
```
> zebra: show command to display metaq info

- bgpd/bgpd.c
```
bgpd/bgpd.c:8975:5: error: "ENABLE_BGP_VNC" is not defined, evaluates to 0 [-Werror=undef]
8975 | #if ENABLE_BGP_VNC
```
Fixes: FRRouting#18546
Fixes: 1629c05924fe9 ("bgpd: rfapi: track outstanding rib and import timers, free mem at exit")
Cc: @gpziemba
> bgpd: fix misused rfapi conditional

- pimd/pim_autorp.c
- pimd/pim_iface.c
- pimd/pim_nb_config.c
Previously, the autorp socket would get created and bind if needed by autorp configuration.
This update limits it further to also require pim enabled interfaces in the vrf before the socket is created and bind.
So now the socket will automatically close if there are no pim enabled interfaces left, or if autorp is turned off. It will automatically turn on if autorp is turned on and there are pim enabled interfaces in the vrf.
> pimd: Only create and bind the autorp socket when really needed

- bfdd/bfd.c
- bgpd/bgp_bmp.c
- lib/command_parse.y
- pimd/pim_autorp.c
- pimd/pim_bsm.c
- pimd/pim_bsr_rpdb.c
Clean up a variety of clang-18 warnings so that we can build with newer clangs.
> lib,pimd,bgpd,bfdd: Fix clang 18 warnings

- bgpd/bgpd.c
backporting this to 10.2, since the regression was introduced there, but the commit doesn't apply since there has been some refactoring done in bgpd.c in the meanwhile.
> bgpd: Treat the peer as not active due to BFD down only if established (backport #18562)

- zebra/main.c
The rib_sweep_route function when not doing graceful restart does not attempt to save the event on the
t_rib_sweep pointer for shutdown.  Prevent any
weird shenanigans by allowing shutdown to clean
up the rib_sweep_route event.
> zebra: Save event pointer for rib sweeping

- bgpd/bgp_route.c
- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
- zebra/zebra_evpn_mac.h
- zebra/zebra_evpn_mh.c
- zebra/zebra_rib.c
- zebra/zebra_vxlan.c
Today bgpd sends down withdraw and install to zebra when a EVPN prefix route is updated. There was no mechanism in zebra to track such changes and references to prefixes on EVPN nexthops.
The commits implement the respective tracking in zebra and stops sending withdraws for updates from bgpd.
> Update EVPN prefix routes properly instead of withdraw/install

- bgpd/bgpd.h
Found by the static analyzer Svace (ISP RAS): DEREF_AFTER_FREE - Pointer '&bgp->vrf_id' is dereferenced after the referenced memory was deallocated by passing as 1st parameter to function 'bgp_unlock'.
> bgpd: Fix deref after free in bgp_vrf_unlink

- bgpd/bgp_attr.c
- bgpd/bgp_ecommunity.c
- bgpd/bgp_ecommunity.h
- bgpd/bgp_evpn.c
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
According to draft-ietf-bess-evpn-ipvpn-interworking-13 §5.2 [1], strip
the following extended communities for VRF routes imported from EVPN.
- BGP Encapsulation extended communities.
- Route Target extended communities.
- All the extended communities of type EVPN.
[1] https://datatracker.ietf.org/doc/html/draft-ietf-bess-evpn-ipvpn-interworking-13#section-5.2-3.4.1
> bgpd: Clean extended communities for VRF routes imported from EVPN

- doc/user/zebra.rst
- isisd/isis_srv6.c
- isisd/isis_zebra.c
- zebra/zebra_srv6_vty.c
Add a CLI to display the information regarding SRv6 local SID(s) allocated from a given locator.
Usage examples:
```
router# show segment-routing srv6 sid
SID                Behavior    Context                Daemon/Instance
-----------------  ----------  ---------------------  -----------------
fc00:0:1::         uN          -                      isis(0)
fc00:0:1:fe00::    uDT6        VRF 'vrf10'            bgp(0)
fc00:0:1:fe01::    uDT6        VRF 'vrf20'            bgp(0)
fc00:0:1:e000::    uA          Interface 'eth-sw1'    isis(0)
fc00:0:1:e001::    uA          Interface 'eth-sw1'    isis(0)
```
> zebra: Add CLI to display SRv6 SIDs allocated

- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
- zebra/zebra_vxlan.c
Because zebra does not support IPv6 VTEPs, zl3vni_remote_rmac_add can get IPv4 **and** IPv4-mapped IPv6 addresses, this is also true for zl3vni_remote_rmac_del (which calls l3vni_rmac_nh_list_nh_delete).
However when receiving a del for the first address added, the rmac is removed.
This adds the IP address to the list in all cases (it's a nodup list, no duplicates will be added) but only installs it to the Kernel when the VTEP IP changes.
In addition testing is added to the evpn topotest, removing the IPv4 routes as well, which causes the test to fail without applying the changes from this PR.
The fix should probably be backported as well.
see: https://github.com/FRRouting/frr/issues/18371, https://github.com/FRRouting/frr/issues/16340
Also https://github.com/FRRouting/frr/pull/16341 …
> zebra: add vtep_ip to rmac nh_list in all cases

- doc/manpages/vtysh.rst
- doc/user/vtysh.rst
Modified section about environment variable VTYSH_PAGER in manpage about vtysh to reflect the default configuration for this env as described inside the FRR User Docs (https://docs.frrouting.org/en/latest/vtysh.html#envvar-VTYSH_PAGER)
> doc: state correct default behaviour of VTYSH_PAGER env if unset (vtysh manpage)

- pimd/pim_instance.c
- pimd/pim_vxlan.c
- pimd/pim_vxlan_instance.h
During vrf delete, the vxlan_info.work_list
linked list was deleted which is a global list
containing the SGs for all the VRFs.
If two vrfs are configured, vrf a and vrf b and
both has SGs assocaited with them which are
inserted in the vxlan_info.work_list. Now if
vrf a is deleted, it deletes the work_list also.
Due to this when any SG add or del comes for vrf b it tries to access the work_list and crashes.
Fix
Delete the vxlan_info.work_list only when all the
VRFs are terminated and unset the vxlan_info.flags so if new add cmd comes it re-allocates the work_list.
> pimd: Fix for crash during networking restart

- zebra/zebra_nhg.c
- zebra/zebra_nhg.h
- zebra/zebra_vty.c
When displaying `show nexthop-group rib` the afi
displayed for Nexthop Groups ( not singletons ) is `bad-value` which while true to the specific of
the AFI it's not necessarily what we want to display to the end operator.  Add a wrapper function for
nhg's to do the right thing.
> zebra: Display nhg's afi as `No Afi`

- zebra/zserv.c
Problem:
Zebra crashed while going down. This happened because zebra was trying to process a new client accept request after closing ZAPI's listener socket zsock and setting it to -1.
Fix:
Cancel all the new client accept requests before closing ZAPI's listener socket in signal handler. Inorder to achieve this, a new list has been created to store all the accept events. Before closing ZAPI's listener socket, zebra will go over this list of accept events and cancel it.
crash bt:
```
#0  0x00007f0e81ce1eec in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f0e81c92fb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f0e821002ec in core_handler (signo=6, siginfo=0x7ffed863d170, context=<optimized out>) at ../lib/sigevent.c:261
#3  <signal handler called>
#4 …
```
> zebra: Cancel new client accept events after zsock is closed

- bgpd/bgp_addpath.c
- bgpd/bgp_route.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- bgpd/rfapi/rfapi_import.c
- isisd/isis_adjacency.c
- isisd/isis_pdu_counter.c
- isisd/isisd.c
- ldpd/lde_lib.c
- lib/command_graph.c
- lib/command_match.c
- lib/ipaddr.h
- lib/northbound.c
- lib/prefix.c
- pathd/path_cli.c
- pathd/path_pcep_config.c
- pathd/path_pcep_controller.c
- pathd/path_pcep_debug.c
- pathd/path_pcep_pcc.c
- pathd/pathd.c
- ripd/rip_nb_state.c
- zebra/router-id.c
If you have undefined behavior compilation checking gcc starts to complain about a bunch of places that do not have return's.  When most of them actually do and we have the assert's to prove it.  I'm just doing this to make the compiler happy for me, so I can continue to do work.
> *: Allow returns to work with --enable-undefined-behavior

- doc/user/ldpd.rst
- docker/ubuntu-ci/Dockerfile
- ldpd/interface.c
- ldpd/ldp_vty.h
- ldpd/ldp_vty_cmds.c
- ldpd/ldp_vty_conf.c
- ldpd/ldpd.c
- ldpd/ldpd.h
- ldpd/neighbor.c
- tests/topotests/ldp_establish_hello_topo1/r1/ldpd.conf
- tests/topotests/ldp_establish_hello_topo1/r1/zebra.conf
- tests/topotests/ldp_establish_hello_topo1/r2/ldpd.conf
- tests/topotests/ldp_establish_hello_topo1/r2/zebra.conf
- tests/topotests/ldp_establish_hello_topo1/r3/ldpd.conf
- tests/topotests/ldp_establish_hello_topo1/r3/zebra.conf
- tests/topotests/ldp_establish_hello_topo1/test_establish_hello_topo1.dot
- tests/topotests/ldp_establish_hello_topo1/test_establish_hello_topo1.py
Currently the LDPD services on TCP session establishment sends additional UDP multicast hello message. Overall, it should speed up label acknowledge.
On the big LAN with a lot of LDPD services(100+) that may reconnect it would lead to a HUGE traffic in the network, when we would lost any performance. So, this PR propose an option to disable "additional hello" during the TCP establishment.
Added option "disable-establish-hello" that disables sending additional LDP hello multicast messages during TCP session establishment. This option enables per interface: "(config-ldp-af-if)"
Usage example:
```
VyOS# configure
VyOS(config)# mpls ldp
VyOS(config-ldp)# address-family ipv4
VyOS(config-ldp-af)# interface eth0
VyOS(config-ldp-af-if)# disable-establish-hello
VyOS(config-ldp-af-if)# end
VyOS# …
```
> ldpd: Option for disabled LDP hello message during TCP

- doc/user/sharp.rst
- sharpd/sharp_vty.c
- zebra/rt_netlink.c
Add to sharp VTY extensions to add srv6 route installation:
- add support for microSID instruction
- add support for End.B6.Encap instruction
> Add sharp support for seg6local routes with uSID flavor

- bgpd/bgp_route.c
- tests/topotests/bgp_addpath_paths_limit/test_bgp_addpath_paths_limit.py
bgpd: add total path count for bgp net in json output
Currently only vty output shows total path count for a
BGP net. This fix add that information in josn output too.
sh bgp ipv4 unicast 172.16.16.254/32 json 
{
"prefix":"172.16.16.254/32",
"version":4,
"advertisedTo":{
"192.168.1.2":{
"hostname":"r2"
}
},
"pathCount":2,<<<<<<<new key value added
"paths":[
{
"aspath":{
"string":"65002 65005",
"segments":[
{
"type":"as-sequence",
"list":[
65002,
65005
]
}
],
"length":2
},
"origin":"incomplete",
"valid":true,
"version":4,
"multipath":true,
"bestpath":{
"overall":true,
"selectionReason":"Older Path"
},
"addpathRxId":6,
"addpathTxId":0,
"addpathTxIdAll":0,
"addpathTxIdBestPerAS":0,
"addpathTxIdBestSelected":0,
"lastUpdate":{
"epoch":1746080990,
"string":"Thu May  1 06:29:50 2025"
}, …
> add total path count for bgp net in json output

- ospf6d/ospf6_zebra.c
- ospf6d/ospf6_zebra.h
- ospfd/ospf_zebra.c
- ospfd/ospf_zebra.h
The ospf6_distance_set and ospf6_distance_unset functions were introduced in 2014 and they were effectively dead code on that day.  Let's just remove this code.
> ospf6d: Remove dead code

- tests/topotests/zebra_recursive_nhg_installed/r1/frr.conf
- tests/topotests/zebra_recursive_nhg_installed/test_zebra_recursive_nhg_installed.py
- zebra/rib.h
- zebra/zebra_dplane.c
- zebra/zebra_rib.c
See individual commits.
a) Add a test to show that nhe_installed_id is useful and accurately tracks the actually installed nexthop group id.
b) Move where nhe_installed_id is set
c) Document rib.h a bit better since I couldn't remember wtf was going on.
> Move where nhe_installed_id is set in zebra

- staticd/static_srv6.c
- staticd/static_srv6.h
- staticd/static_zebra.c
On a heavily loaded system, it may take some time to establish a connection between staticd and SRv6 SID Manager.
As a result, staticd might try to allocate SIDs in SID Manager before the connection is fully established, leading to a failure.
This issue is reflected in the log with the following error message:
```
2025/03/04 15:24:01 STATIC: [HR66R-TWQYD][EC 100663302] srv6_manager_get_locator: invalid zclient socket
```
In this scenario, SIDs are still kept in the staticd configuration, but not allocated and not installed in the RIB.
This commit fixes the issue by forcing staticd to retry to allocate the SIDs once the connection with SID Manager is successfully established.
> staticd: Fix an issue where SRv6 SIDs may not be allocated on heavily loaded systems

- lib/command_graph.h
- lib/command_parse.y
- lib/command_py.c
- lib/subdir.am
- python/xref2vtysh.py
The docstring warning for too short/long docstrings was getting printed from the C code as a zlog_warn, but the Python code was entirely unaware of that and as such build just continued...
(This doesn't work for `DEFUN_NOSH`, because this is in the code path for vtysh commands... but 99% is better than 0%.)
> build: fail on docstring problems

- bgpd/bgp_mpath.c
- doc/user/bgp.rst
> Fix spelling error in bgp as well as clean up bgp documentation

- docker/alpine/Dockerfile
- docker/centos-7/Dockerfile
- docker/centos-8/Dockerfile
- docker/ubi8-minimal/Dockerfile
- docker/ubuntu-ci/Dockerfile
Our topotests are assuming that there is 128 way ecmp at the moment Let's just build with 256
> docker: Build with 256 way ecmp

- doc/user/zebra.rst
- tests/topotests/all_protocol_startup/r1/ip_nht.ref
- tests/topotests/all_protocol_startup/r1/pbrd.conf
- tests/topotests/all_protocol_startup/test_all_protocol_startup.py
- zebra/zebra_vty.c
Prior to this change a `show ip route table X A.B.C.D/M longer-prefix` command was the only command accepted.  Additionally it would not dump data about the nexthops or nexthop groups.  With PBR this useful data to have.
New ability:
r1# show ip route table 10000 0.0.0.0/0
Routing entry for 0.0.0.0/0
Known via "pbr", distance 200, metric 0, best
Last update 00:00:16 ago
192.168.3.7 (recursive), weight 1
*   192.168.1.1, via r1-eth0, weight 1
*   192.168.1.2, via r1-eth0, weight 1
*   192.168.1.3, via r1-eth0, weight 1
192.168.4.1 (recursive), weight 1
*   192.168.2.1, via r1-eth1, weight 1
192.168.1.1, via r1-eth0 (duplicate nexthop removed), weight 1
192.168.1.2, via r1-eth0 (duplicate nexthop removed), weight 1
> zebra: Allow `show ip route table X A.B.C.D/M` to work

- lib/darr.c
- lib/darr.h
- lib/mgmt_be_client.c
- lib/mgmt_be_client.h
- lib/mgmt_msg_native.h
- lib/northbound.h
- lib/northbound_notif.c
- mgmtd/mgmt_be_adapter.c
- mgmtd/mgmt_fe_adapter.c
- mgmtd/mgmt_testc.c
- mgmtd/mgmt_txn.c
- mgmtd/mgmt_txn.h
- tests/topotests/lib/fe_client.py
- tests/topotests/mgmt_notif/test_ds_notify.py
- tests/topotests/mgmt_notif/test_notif.py
To allow for correct syncing using notifications a client needs an initial dump of the state before receiving notifications without missing any notifications after this initial dump. Implement this initial state dump using the notification code to support this functionality.
Also, Add notify_format field to the session creation message. When sending notification messages back to front-end, convert data to the format the session requested when it was created.
> Add initial state dump on frontend datastore notify subscribe

- tests/topotests/bgp_local_asn/test_bgp_local_asn_topo1.py
- tests/topotests/bgp_local_asn_dot/test_bgp_local_asn_dot_topo1.py
- vtysh/vtysh.c
- vtysh/vtysh_config.c
In some instances the return codes from failed configuration is not gathered up to report to the operator.
> Gather vtysh return codes up to report to operator

- lib/nexthop.c
- lib/nexthop.h
- tests/topotests/zebra_nhg_check/r1/frr.conf
- tests/topotests/zebra_nhg_check/r2/frr.conf
- tests/topotests/zebra_nhg_check/test_zebra_nhg.py
- zebra/zebra_nhg.c
- zebra/zebra_rib.c
- zebra/zebra_vty.c
Currently if there are multiple interfaces going down it is possible to have a ships in the night situation with trying to reuse a nhg.
Imagine that you have a route w/ 4 way ecmp
nexthop A interface a
nexthop B interface b
nexthop C interface c
nexthop D interface d
Suppose interface a goes down, zebra receives this data marks singleton nexthop A down and then recurses up the tree to the 4 way ecmp and sets nexthop A as inactive. Zebra then will notify the upper level protocol.
The upper level protocol will refigure the route and send it down with 3 way ecmp.  At the same time if interface b goes down and zebra handles that interface down event before the new route installation, then when
zebra_nhg_rib_compare_old_nhe is called it will not match the old and new ones up as that the old …
> zebra: Allow nhg's to be reused when multiple interfaces are going amuck

- lib/darr.c
- lib/darr.h
- lib/mgmt_msg_native.h
- lib/northbound.h
- lib/northbound_notif.c
- lib/northbound_oper.c
- lib/yang_wrappers.c
- mgmtd/mgmt_be_adapter.c
- mgmtd/mgmt_be_adapter.h
- mgmtd/mgmt_ds.c
- mgmtd/mgmt_fe_adapter.c
- mgmtd/mgmt_testc.c
- mgmtd/mgmt_txn.c
- tools/checkpatch.pl
Replace all incorrect uses of `__` as prefix for identifier as this is reserved for the C implementation.
> Replace use of `__` as identifier prefix

- python/xrelfo.py
Fedora 42 has some new GCC/ld combination that has negative offsets from the .note.FRR to the xref pointers.  (This is completely fine, those offsets are supposed to be signed.)  Clippy decoded them as unsigned, resulting in off-by-2^64 offset values (which Python cheerfully processes, due to its builtin "large integer" support... in C code it would've just wrapped in an uint64_t and made no difference...)
Read the values as signed like they should be.
> lib/clippy: pointer offsets are signed

- bgpd/bgp_bmp.c
The RFC9069 stipulates in chapter 5.2 that send and received OPEN message should be the same. The AS number and the BGP identifier should be the same.
Link: https://datatracker.ietf.org/doc/html/rfc9069#section-5.2
Fixes: a3ef2fc62b3a ("bgpd: fix loc-rib open message should use router-id")
> bgpd: fix second router-id of loc-rib peer-up message set to 0.0.0.0

- bgpd/bgp_mplsvpn.c
We use `BGP_VRF_TOVPN_SID_AUTO` to indicate auto-mode for tovpn sid in per_vrf case,
and use `BGP_VPN_POLICY_TOVPN_SID_AUTO` in per_af.
Hence, in delete_vrf_tovpn_sid_per_vrf, we should use the former.
Let's fix it.
> bgpd: Fix flag issue in delete_vrf_tovpn_sid_per_vrf

- zebra/zserv.c
It's possible for the main pthread to try to use a zclient that has failed/closed. Add some guards to try to prevent some obvious paths where that might occur.
> zebra: guard against use of zapi client data during close

- docker/ubuntu-ci/Dockerfile
- tests/topotests/lib/fe_client.py
Also fix fe_client.py test script to include munet path prior to importing from munet.
This will enable running of tests that count on fe_client.py working (e.g., mgmt_notif).
> docker: install correct python protobuf in ubuntu docker images

- tests/topotests/bgp_evpn_rt5/r1/bgp_l2vpn_evpn_routes.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_l2vpn_evpn_routes_all.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_101_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_101_ipv4_routes_detail_import.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_101_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_101_ipv6_routes_detail_import.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_102_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_102_ipv4_routes_detail_import.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_102_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r1/bgp_vrf_102_ipv6_routes_detail_import.json
- tests/topotests/bgp_evpn_rt5/r1/frr.conf
- tests/topotests/bgp_evpn_rt5/r2/bgp_l2vpn_evpn_routes.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_101_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_101_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_102_ipv4_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/bgp_vrf_102_ipv6_routes_detail.json
- tests/topotests/bgp_evpn_rt5/r2/frr.conf
- tests/topotests/bgp_evpn_rt5/rr/frr.conf
- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
ec06de8403 ("zebra: use nexthop instead of route vrf_id for EVPN") fixed the reflection of EVPN RT5 routes.
Add route-reflector into bgp_evpn_rt5 topology.
Fixes: https://github.com/FRRouting/frr/issues/18371
> tests: bgp_evpn_rt5 add route-reflector

- bgpd/bgp_damp.c
- bgpd/bgp_evpn.c
- bgpd/bgp_evpn_mh.c
- bgpd/bgp_mplsvpn.c
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/rfapi/rfapi.c
This function does not actually delete the path info.  Let's call it what it really does, which is just mark it for deletion in the future.
> bgpd: Rename bgp_path_info_delete to bgp_path_info_mark_for_delete

- isisd/isis_tlvs.c
- lib/yang_wrappers.c
Clean up few more gcc-15 warnings: init locals in isisd module, replace variadic-ish macros in yang_wrappers.c with simple-minded macros.
Fixes: #18793
> isid, lib: Fix gcc 15 warnings

- bgpd/bgp_route.c
- tests/topotests/bgp_bestpath_reason/r1/frr.conf
- tests/topotests/bgp_bestpath_reason/r2/frr.conf
- tests/topotests/bgp_bestpath_reason/r3/frr.conf
- tests/topotests/bgp_bestpath_reason/r4/frr.conf
- tests/topotests/bgp_bestpath_reason/test_bgp_bestpath_reason.py
The best path reason was being incorrectly set in some cases.  Let's fix that.  Also write a test to show that it is fixed.
> Fix bestpath reason being incorrectly set in some cases

- doc/developer/topotests.rst
I did not check for all distro, but on Ubuntu 24.04, we are missing:
`IANA-STORAGE-MEDIA-TYPE-MIB`
Fix test:
```
bgp_snmp_mplsl3vpn/test_bgp_snmp_mplsvpn.py::test_r1_mplsvpn_scalars -
/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf
Cannot find module (IANA-STORAGE-MEDIA-TYPE-MIB): At line 19 in /usr/share/snmp/mib...
```
```
bgp_snmp_mplsl3vpn/test_bgp_snmp_mplsvpn.py::test_r1_mplsvpn_scalars_interface
/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf
Cannot find module (IANA-STORAGE-MEDIA-TYPE-MIB): At line 19 in /usr/share/snmp/mib...
```
> doc: topotest add missing media type MIB

- tests/topotests/zebra_operational_data/test_zebra_operational.py
- yang/frr-zebra.yang
- zebra/zebra_nb.c
- zebra/zebra_nb_config.c
- zebra/zebra_nb_state.c
- zebra/zebra_vty.c
a) Move max-multicast to a state value
b) Convert `ip forwarding` to yang
c) Convert `ipv6 forwarding` to yang
I am doing something wrong with this conversion, in that I am not seeing the config values reflected in yang when I ask for it.  I do not know what I am missing or doing wrong and would like some help figuring it out.  When I issue:
`show mgmt get-data /frr-zebra:zebra with-defaults all`
`show mgmt get-data /frr-zebra:zebra with-config`
`show mgmt get-data /frr-zebra:zebra only-config` 
I do not see the ip|ipv6 forwarding yang show up there.  
When I issue the
`show mgmt get-config /frr-zebra:zebra` I only see the default values as defined in yang
I do know that yang-conversion is being accepted by the system as that I can toggle forwarding on/off. 
I also see this problem with …
> Ipforwarding modify

- doc/user/sharp.rst
- isisd/isis_zebra.c
- lib/nexthop.c
- lib/srv6.c
- lib/srv6.h
- sharpd/sharp_vty.c
- tests/topotests/isis_srv6_topo1/rt1/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt1/zebra.conf
- tests/topotests/isis_srv6_topo1/rt2/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt2/zebra.conf
- tests/topotests/isis_srv6_topo1/rt3/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt3/zebra.conf
- tests/topotests/isis_srv6_topo1/rt4/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt4/zebra.conf
- tests/topotests/isis_srv6_topo1/rt5/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt5/zebra.conf
- tests/topotests/isis_srv6_topo1/rt6/step1/show_ipv6_route.ref
- tests/topotests/isis_srv6_topo1/rt6/zebra.conf
- zebra/zebra_srv6_vty.c
Add FRRouting support for PSP flavor to End behavior.
Unfortunately, kernel does not have PSP flavor for other behaviors.
So lets just support End for now.
> End psp flavor

- bgpd/bgp_vty.c
- bgpd/bgpd.c
This PR addresses two issues:
1. Fix views removal with the command `no router bgp ASN view WORD`
This commit broke the ability to unconfigure BGP views: https://github.com/FRRouting/frr/commit/4d0e7a49cf8d4311a485281fa50bbff6ee8ca6cc
2. Fix BGP main socket removal when removing BGP views
When two or more views are configured and one of them is removed the main socket is closed causing BGP to no longer accept new connections (see commit description for more information)
> bgpd: fix view deletion and main socket deletion

- tests/topotests/srv6_locator_custom_bits_length/expected_locators8.json
- tests/topotests/srv6_locator_custom_bits_length/test_srv6_locator_custom_bits_length.py
- zebra/zebra_srv6_vty.c
Zebra: Allow configuring node-len 0
Currently the node-len for a locator can only be configured between the range 16-64. However, as per the RFC draft
https://datatracker.ietf.org/doc/html/draft-ietf-spring-srv6-srh-compression-23#name-recommended-installation-of
```
The SID 2001:db8:b1:f123:: bound to the End.X behavior for its local IGP adjacency 123 with the NEXT-CSID flavor is instantiated from LIB with
Locator-Block length (LBL) = 48 (Locator-Block value 0x20010db800b1),
Locator-Node length (LNL) = 0,
Function length (FL) = 16 (Function value 0xf123), and
Argument length (AL) = 64.
```
End.X should be able to handle 0 node length.
Fixing this by allowing the user to configure the node-len 0-64. Also distinguishing the not configured node-len and node-len 0 configuration.
> SRv6: Allow configuring node-len 0

- bgpd/bgp_vty.c
- tests/topotests/bgp_peer_group/test_bgp_peer-group.py
Currently, peergroup_filter_check() does not check whether exist-map or non-exist-map is configured along with advertise-map. This check is missing only when the peer is part of peergroup and having the exist/non-exist-map. So the 'show run' does not show the configured exist/non-exist-map as expected.
This new check is needed because, unlike other filter type the adv-map can have exist/non-exist-map additionally and we don't store this in the filter_override but store only the adv-map. So, a specific check is required to account the exist/non-exist-map while printing the adv-map config. Fixing the same by adding a check.
> bgpd: fix to show exist/non-exist-map in 'show run' properly

- lib/command.h
- vtysh/vtysh_config.c
- zebra/zebra_cli.c
- zebra/zebra_vty.c
Need to put the CLI handler in the file linked into mgmtd, also use NB yang CLI write function for config generation.
> zebra: finish moving `ip[v6] forwarding` to NB/mgmtd

- doc/user/pim.rst
- doc/user/pimv6.rst
- pimd/pim6_cmd.c
- pimd/pim6_mld.c
- pimd/pim_cmd.c
- pimd/pim_iface.h
- pimd/pim_igmp.c
- pimd/pim_nb.c
- pimd/pim_nb.h
- pimd/pim_nb_config.c
- pimd/pim_vty.c
- tests/topotests/lib/packet/igmp/igmp.py
- tests/topotests/lib/packet/igmp/igmp_v1.py
- tests/topotests/lib/packet/igmp/igmp_v2.py
- tests/topotests/lib/packet/igmp/igmp_v3.py
- tests/topotests/lib/packet/mld/mld.py
- tests/topotests/lib/packet/mld/mld_v1.py
- tests/topotests/lib/packet/mld/mld_v2.py
- tests/topotests/multicast_features/test_multicast_features.py
- yang/frr-gmp.yang
Implementation of the configuration require-router-alert for IGMP/MLD.
Until now there were two distinct behaviors between IGMP and MLD:
1. IGMP always **accepted** reports even with no router-alert
2. MLD always **rejected** reports without router-alert
This PR introduces a knob called "require-router-alert", which is disabled by default (meaning IGMP and MLD will accept all reports even without router alert) , that when it is enabled it will make PIM only accept IGMP/MLD reports with the router-alert option.
> pimd,pim6d: require router alert configuration

- tests/topotests/high_ecmp/test_high_ecmp_unnumbered.py
- zebra/interface.c
- zebra/rtadv.c
- zebra/rtadv.h
zebra: V6 RA not sent anymore after interface up-down-up
Issue:
Once interface is shutdown, the interface is removed from
wheel timer. Now when the interface is up again, current code
won't add the interface to wheel timer again, so it won't send RA
anymore for that interface
Fix:
Moved wheel_add for interface inside rtadv_start_interface_events
This is more common function which gets triggered for both
RA enable and interface up event
Also on any kind of interface activation event, we try to send
RA as soon as possible. This is to satisfy requirement where
quick RA is needed, especially for some convergence, dependent on
RA.
Testing:
Did ineterface up to down to up
Added debug log for RA, checked it is getting advertised preodically
after when up at up state
show bgp summary for 512 bgp …
> zebra: V6 RA not sent anymore after interface up-down-up

- redhat/frr.spec.in
Newer glibc on RedHat 9 fail with _FORTIFY_SOURCE on the frr replacement of the inet_ntop. Fixes https://github.com/FRRouting/frr/issues/18575
> redhat: Add Workaround for inet_ntop replacement which breaks rpms

- bgpd/bgp_vty.c
- lib/nexthop.c
- lib/srv6.h
- staticd/static_vty.c
When configuring an srv6 route with encap option, the displayed option in running config differs:
> ubuntu2404(config)# ipv6 route 5::6/128 loop0 segments 1::1 encap-behavior H_Encaps_Red
> ubuntu2404(config)# do show ipv6 route
> [..]
> S>* 5::6/128 [1/0] is directly connected, loop0, seg6 1::1, encap behavior H.Encaps.Red, weight 1, 00:00:02
> ubuntu2404(config)# do show running-config
> [..]
> ipv6 route 5::6/128 loop0 segments 1::1 encap-behavior H.Encaps.Red
Modify output in running-config wherever the encap-behavior is used. Use _ instead.
Fixes: 5323ad0d1fec ("staticd: Add SRv6 encap behavior in show running-config")
Fixes: dbd77b184f1a ("bgpd: add encap red support to L3VPN seg6 routes")
> staticd, bgp: fix srv6 encap-value displayed with _ instead of .

- bgpd/bgpd.h
Proof reading. All the flags are ULL.
> bgpd: fix PEER_FLAG_CONFIG_DAMPENING to be ULL

- yang/frr-staticd.yang
Fix pyang errors or warnings in frr-staticd.yang
frr-staticd.yang:31: warning: imported module "ietf-srv6-types" not used
frr-staticd.yang:70: error: RFC 8407: 4.8: statement "revision" must have a "reference" substatement
frr-staticd.yang:81: error: RFC 8407: 4.14: statement "grouping" must have a "description" substatement
frr-staticd.yang:82: error: RFC 8407: 4.14: statement "list" must have a "description" substatement
frr-staticd.yang:110: error: keyword "description" not in canonical order, expected "type" (see RFC 7950, Section 14)
frr-staticd.yang:111: error: keyword "type" not in canonical order (see RFC 7950, Section 14)
frr-staticd.yang:165: error: RFC 8407: 4.14: statement "augment" must have a "description" substatement
frr-staticd.yang:201: error: keyword "must" not in …
> yang: Fix pyang errors in frr-staticd.yang

- configure.ac
- lib/zebra.h
- zebra/ioctl.c
This one is removing a whole bunch of dead checks/defines. The last one (`stropts.h`) is speculative in that I'm just going to throw it into CI and see if it passes. The file apparently exists on old Linux (≤2019) but it shouldn't be doing anything. The other ones are just bogus/ancient/…
> build: the war against `config.h` continues, 1 of ∞

- bgpd/bgp_bmp.c
- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/bmp2import/bmp-update-loc-rib-step1.json
- tests/topotests/bgp_bmp/bmp2import/bmp-update-post-policy-step1.json
- tests/topotests/bgp_bmp/bmp2import/bmp-update-pre-policy-step1.json
- tests/topotests/bgp_bmp/test_bgp_bmp_3.py
- tests/topotests/lib/bmp_collector/bmpserver.py
When BMP client connects to a BMP collector, the RIB entries from an imported VRF are not sent to that collector. After reconnecting the BMP client, only the RIB entries of the default VRF where BMP is configured are sent.
> 2025/05/19 14:33:11.863970 BGP: [KXFT6-AKP4X] bmp[192.0.2.10:1789] connection established
> 2025/05/19 14:33:11.864027 BGP: [Y3NW5-Y5P0A] bmp[192.0.2.10:1789] IPv4 unicast sending table (BGP VRF default)
> 2025/05/19 14:33:11.864059 BGP: [MC9C8-MQZT1] bmp[192.0.2.10:1789] IPv4 unicast table completed (EoR) (BGP VRF default)
> 2025/05/19 14:33:11.864066 BGP: [Y3NW5-Y5P0A] bmp[192.0.2.10:1789] IPv6 unicast sending table (BGP VRF default)
> 2025/05/19 14:33:11.864076 BGP: [MC9C8-MQZT1] bmp[192.0.2.10:1789] IPv6 unicast table completed (EoR) (BGP VRF default)
The BGP …
> bgpd: fix import all adj-rib-in and loc-rib after bmp connects

- isisd/isis_dlpi.c
- lib/northbound_oper.c
- pimd/pim_autorp.h
`BIG_ENDIAN` is a number define, not a "is it defined?" define.  It's actually 4321.  And `LITTLE_ENDIAN` is 1234, and then `BYTE_ORDER` is one of them.  (Or `PDP_ENDIAN`, which is 3412.)  This unfortunately means that `BIG_ENDIAN` is always defined, so this code was taking the big-endian path even on little endian machines.
---
Plus 2 non-bugfix endian-related cleanups for consistency. (The `isisd` one is unused by way of being Solaris specific, the `pimd` one is just using nonstandard macro names.)
> lib: fix mis-done endian check

- configure.ac
- eigrpd/eigrp_packet.c
- ldpd/packet.c
- lib/prefix.h
- lib/sockopt.c
- lib/sockunion.c
- lib/zebra.h
- ospf6d/ospf6_interface.c
- ospfd/ospf_packet.c
- pceplib/pcep.h
- zebra/if_sysctl.c
- zebra/interface.h
- zebra/ioctl.c
- zebra/ipforward_sysctl.c
- zebra/rtread_sysctl.c
- zebra/table_manager.h
Another stack of `config.h` related cleanups.
On the TODO list of things needed for using our headers without `config.h` (#18807):
- `HAVE_CLOCK_THREAD_CPUTIME_ID` needs to go (because it changes the layout of `struct event`)
- easy, because it's set on all of our supported platforms. It's only missing on Apple, which is a pandora's box for another day…
- `HAVE_SECTION_SYMS` might affect things
- easy again, because it's set on all of our supported platforms. This one was for Solaris primarily (and Apple is screwed regardless, being a non-ELF platform)
- `HAVE_MALLOC_USABLE_SIZE` & `HAVE_MALLOC_SIZE` need something, because they affect the layout of `struct mtype`
- `MULTIPATH_NUM` will just need to be exported in the `.pc` file, i.e. it'll have `-DMULTIPATH_NUM=1234`
- needs …
> build: the war on `config.h` is a war of attrition, 2 of ∞

- bfdd/bfd.c
According to: https://www.rfc-editor.org/rfc/rfc5880.html#section-6.8.3
If bfd.DesiredMinTxInterval is increased and bfd.SessionState is Up, the actual transmission interval used MUST NOT change until the Poll Sequence described above has terminated.
> bfdd:  Only apply increased transmission interval after Poll Sequence

- bfdd/bfd_packet.c
RFC 5880 6.8.7:  A system MUST NOT transmit BFD Control packets if bfd.RemoteDiscr is zero and the system is taking the Passive role.
> bfdd: Check for passive mode with zero discriminator

- nhrpd/nhrp_interface.c
Contemporary kernels automatically add link-local IPv6 addresses on GRE interfaces. This patch makes `nhrpd` ignore such and other non-host addresses when selecting the best protocol address, instead of discarding such an address after the selection.
> nhrpd: ignore non-host addresses on NHRP interfaces

- staticd/static_zebra.c
Ensure we check sid->locator before deref'ing it; this was coverity SA 1643169
> staticd: fix deref of NULL pointer in srv6 code

- doc/developer/frr-release-procedure.rst
Add a few lines to the FRR release process outline as a reminder to check the dataplane API version number. Hopefully PRs that make dplane API changes will also update the version number in the code, but it's worth a check at release time.
> doc: add a note about dplane API version to the release docs

- zebra/zebra_dplane.c
Bump the minor dplane api version for the 10.4 release.
> zebra: bump the dplane api version for FRR 10.4

- lib/lib_vty.c
- lib/mgmt.proto
- lib/mgmt_fe_client.c
- lib/mgmt_fe_client.h
- lib/northbound_cli.c
- lib/vty.c
- lib/vty.h
- mgmtd/mgmt_fe_adapter.c
- mgmtd/mgmt_fe_adapter.h
- mgmtd/mgmt_txn.c
- mgmtd/mgmt_txn.h
- mgmtd/mgmt_vty.c
- tests/topotests/config_timing/r1/frr.conf
- tests/topotests/config_timing/r1/staticd.conf
- tests/topotests/config_timing/test_config_timing.py
- tests/topotests/mgmt_config/r1/mgmtd.conf
- tests/topotests/mgmt_debug_flags/test_debug.py
- tests/topotests/mgmt_tests/test_yang_mgmt.py
mgmtd: eliminate use of SETCFG_REQ message.
Since external clients are going to use the native EDIT message, there's no reason to force the CLI to use the old protobuf "set config" message to send config changes to itself (from vty code to message handling), just do it directly.
Things get a "little" faster too:
```
config_timing topotest before:
topo: added 10000 ipv4 static routes under 10.0.0.0/8 in 11.185793s (limit: 0s)
topo: added 10000 ipv4 static routes under 11.0.0.0/8 in 13.454671s (limit: 33.557379s)
topo: added 10000 ipv4 static routes under 10.0.0.0/8 in 9.397964s (limit: 33.557379s)
topo: removed 5000 ipv4 static routes under 10.0.0.0/8 in 4.867958s (limit: 33.557379s)
topo: added 10000 ipv4 static routes under 10.0.0.0/8 in 12.056481s (limit: 33.557379s)
topo: removed 10000 …
```
> mgmtd simplify frontend CLI config path

- configure.ac
For extra confusion, unwind.h is also provided by the various libunwind implementations, but it provides a different API.  And in some cases, they ship unwind.h but not libunwind.h, and then this check incorrectly detects as positive...
This is a separate commit because it should probably be backported. (A larger rework of the backtrace configure option is following.)
> build: check for libunwind.h, not unwind.h

- buildtest.sh
- configure.ac
- doc/developer/building-frr-for-centos6.rst
- doc/developer/building-frr-for-centos7.rst
- doc/developer/building-frr-for-centos8.rst
- doc/developer/include-compile.rst
- doc/developer/topotests.rst
- doc/user/installation.rst
- doc/user/snmp.rst
- docker/ubi8-minimal/Dockerfile
- docker/ubuntu-ci/Dockerfile
- redhat/frr.spec.in
- snapcraft/snapcraft.yaml.in
- zebra/rtadv.c
- zebra/rtadv.h
- zebra/zebra_cli.c
- zebra/zebra_nb.c
- zebra/zebra_nb.h
- zebra/zebra_nb_config.c
- includes #18912 (DO NOT MERGE before #18912 is merged, so that one can be backported without the other ones here)
- rework `--enable-backtrace` option to have explicit `--enable-backtrace=libunwind` option
- simplify SNMP checks (use `pkg-config` if available, remove multi-variant SMUX leftovers)
- remove `--disable-rtadv` option (why did we even have this?)
Adding `do not merge` tag until #18912 is merged (can be removed after #18912 is in — I can't separate that commit out from this PR because it would immediately conflict on the libunwind change.)
If you want to have a laugh, read the commit text on the SNMP change :grin:
> build: `autoconf` cleanup pass

- tools/checkpatch.pl
This reverts commit 010fb27df1ebb4176c270caa09ca4a8469c197a8.
This commit has broken the run of checkpatch.pl that checkpatch.sh does.
> Revert "tools: ignore spaces only in macro empty line."

- bgpd/bgp_nexthop.c
- bgpd/bgp_nexthop.h
- bgpd/bgp_route.c
- tests/topotests/bgp_l3vpn_to_bgp_direct/scripts/check_routes.py
Accepting a host route from a BGP peer for a local address would result in inconsistency between BGP and RIB/FIB.
> bgpd: do not accept a host route that matches a local address

- tools/checkpatch.pl
clang-format uses all spaces for blank lines in a macro (i.e., all whitespace with a backslash escape at the end of line), so modify checkpatch.pl for now to not require tabs for these lines. There is a clang-format issue open for fixing this, but it has been open a while: llvm/llvm-project#56081
> tools: ignore spaces only in macro empty line.

- redhat/frr.spec.in
Changes to make FRR RPM build to work on RedHat 10
- We used rpmversion as the major version variable. This is now a reserved system variable in the rpm package system with RPM shipped on RedHat 10. Rename it to frrmajorversion
- RedHat 10 doesn't have the pathfix.py for the shebang fix in pythonv - need to use py3_shebang_fix macro instead
> redhat: make FRR RPM build to work on RedHat 10

- bgpd/bgpd.c
An incoming BGP prefix encapsulated in LOC-RIB BMP message, encodes AS-Paths information in AS2B. This is not what the RFC9069, ch.5.4.1:
> Loc-RIB Route Monitoring messages MUST use a 4-byte ASN encoding as
> indicated in the Peer Up sent OPEN message (Section 5.2) capability.
Set the appropriate flags in the peer_self structure, to encode AS information for loc-rib in AS4B format.
> bgpd: use AS4B format for BGP loc-rib messages.

- zebra/dplane_fpm_nl.c
- zebra/zebra_rib.c
When using `no fpm use-nexthop-group` and we have 512 way ecmp and ipv6 routes 8k buffer is not enough to actually encode the route to the dplane.  Add code to stop this problem from happening.  Add code to let the ctx carry the failure back up to zebra.  Add code to let zebra set the flags appropriately.
@mjstapp @pbrisset  you two should put your heads together and make sure you are happy with this change.  If so I would recommend that someone port the dplane_fpm_nl.c code changes over to the sonic dplane module.
> Fix up dplane handling of some edge cases

- zebra/zebra_srv6_vty.c
In `show running-config`, normally we don't show parameters that are set to the default value.
However, currently the `block-len` and `node-len` parameters of an SRv6 locator do not follow this rule, and are shown even when they are set to the default values.
The following example shows the issue:
```
router# configure
router(config)# segment-routing
router(config-sr)# srv6
router(config-srv6)# locators
router(config-locators)# locator MAIN
router(config-locator)# prefix fcbb:bb01:1::/48
router# show running-config
[...]
srv6
locators
locator MAIN
prefix fcbb:bb01:1::/48 block-len 24 node-len 24
[...]
```
This PR fixes the issue by hiding the `block-len` and `node-len` parameters when they are set to default.
> zebra: Do not show SRv6 locator params when they are set to default

- bgpd/bgpd.c
When a BGP instance is about to be destroyed, we call delete_vrf_tovpn_sid_per_vrf() to release SRv6 SIDs.
This function checks that there are no BGP_VRF_TOVPN_SID_* flags set for this BGP instance. If there are, then it assumes that this BGP instance is still using SRv6, and returns early without releasing the SIDs.
This PR makes sure the BGP_VRF_TOVPN_SID_EXPLICIT flag is unset before calling delete_vrf_tovpn_sid_per_vrf(), so that the delete_vrf_tovpn_sid_per_vrf() can do its job and release the SIDs.
> bgpd: Unset TOVPN_SID_EXPLICIT flag to ensure BGP can release SRv6 SIDs

- lib/mgmt_msg_native.h
- lib/northbound_oper.c
The return value is the same, but it requires less smarts to know this if the code is more explicit. Should make coverity happy.
fixes CID:1644144, CID:1644150, CID:1644159
> lib: fix coverity "free address-of" issues

- configure.ac
- lib/mgmt_be_client.c
- mgmtd/mgmt_fe_adapter.c
- mgmtd/mgmt_fe_adapter.h
- mgmtd/mgmt_txn.c
- mgmtd/mgmt_txn.h
This didn't end up being needed. It requires embedding daemon specific semantic validation functions inside mgmtd. This would require another yang info structure mapping xpaths to the daemon specific validation.
In reality we do little of this type of validation, and there's almost no overlap between daemons (i.e., multiple daemons aren't doing the same validation) so we don't save on processing here to just do it once in the daemon vs once in mgmtd.
> mgmtd: remove unfinished and unneeded yang-validate code

- staticd/static_srv6.c
- tests/topotests/static_srv6_sids/expected_srv6_sids_interface_down.json
- tests/topotests/static_srv6_sids/test_static_srv6_sids.py
Static daemons in the current code does not remove/add SRv6 sids configured with behavior uA on an interface when it receives the interface events.
Fixing this.
```
Initial state:
ip -6 -d route  | grep End.X
unicast fcbb:bbbb:fe5::/48 nhid 16  encap seg6local action End.X nh6 fe80::c0f9:81ff:fe68:6455 dev r1-eth1 proto 196 scope global metric 20 pref medium vtysh -c "sh ipv6 route" | grep seg6
S>* fcbb:bbbb:fe5::/48 [1/0] is directly connected, r1-eth1, seg6local uA nh6 fe80::c0f9:81ff:fe68:6455, weight 1, 00:00:20
ip link set down r1-eth1
vtysh -c "sh ipv6 route" | grep seg6
S>  fcbb:bbbb:fe5::/48 [1/0] is directly connected, r1-eth1 inactive, seg6local uA nh6 fe80::c0f9:81ff:fe68:6455, weight 1, 00:00:28 ip -6 -d route  | grep End.X
ip link set up r1-eth1
vtysh -c "sh ipv6 route" | …
```
> static: [SRv6] Fixing uninstall and reinstall uA Sids upon Intf flaps

- zebra/zebra_vty.c
The duplicate nexthop is not displayed with proper alignment.
```
mlx-4700-44# show nexthop-group rib 580
ID: 580 (zebra)
RefCnt: 1
Uptime: 01:39:06
VRF: default
Valid, Installed
Depends: (530) (564) (579)
via 20.1.1.9 (vrf default) (recursive), weight 1
via 20.1.1.2, swp1s0 (vrf default), weight 1
via 30.1.2.9 (vrf default) (recursive), weight 1
via 30.1.1.2, br_default.60 (vrf default), weight 1
via 30.1.1.6, vlan70 (vrf default), weight 1
via 30.1.1.10, bond1 (vrf default), weight 1
via 20.1.1.2, swp1s0 (vrf default), weight 1 <<<<<<<<
```
With fix:
```
mlx-4700-44# show nexthop-group rib 580
ID: 580 (zebra)
RefCnt: 1
Uptime: 01:39:06
VRF: default
Valid, Installed
Depends: (530) (564) (579)
via 20.1.1.9 (vrf default) (recursive), weight 1
via 20.1.1.2, swp1s0 (vrf default), weight 1 …
```
> zebra: fix nexthop rib out for duplicate nhg

- zebra/zebra_evpn_neigh.c
- Fix issue where mh_peer_sync flag was missing on EVPN MH neighbor entries after networking service restart. Earlier the hold timer for the ES_PEER_ACTIVE flag was unconditionally started when a sync neighbor was deleted. which removes the sync flag.
- Added more debugs
Ticket: #
Signed-off-by: Rajesh Varatharaj <rvaratharaj@nvidia.com>
> zebra: Start EVPN neighbor hold timer only when interface is operative

- lib/srte.h
- pathd/path_pcep_pcc.c
- pathd/pathd.c
Test code:
```
int compare(uint32_t x, uint32_t y) {
return x - y;
}
void print_compare(uint32_t x, uint32_t y) {
int ret = compare(x, y);
if (ret < 0) {
printf("%u < %u\n", x, y);
} else if (ret > 0) {
printf("%u > %u\n", x, y);
} else {
printf("%u = %u\n", x, y);
}
}
int main(void) {
uint32_t a = 2;
uint32_t b = 0x80000001u;
uint32_t c = 0xffffffffu;
print_compare(a, b);
print_compare(b, c);
print_compare(c, a);
uint32_t x = 7;
uint32_t y = 0x80000007u;
print_compare(x, y);
print_compare(y, x);
return 0;
}
```
Output:
```
2 < 2147483649
2147483649 < 4294967295
4294967295 < 2
```
> pathd: fix compare function overflow

- zebra/zebra_router.c
RB tree for router table is not initializes and can have garbage values leading to crashes when zebra boots.
```
==52257== Invalid read of size 4
==52257==    at 0x24A683: zebra_router_table_entry_compare (zebra_router.c:46)
==52257==    by 0x24A683: zebra_router_table_head_RB_COMPARE (zebra_router.c:38)
==52257==    by 0x494859F: _rb_find (openbsd-tree.c:415)
==52257==    by 0x24AA44: zebra_router_table_head_RB_FIND (zebra_router.h:39)
==52257==    by 0x24AA44: zebra_router_get_table (zebra_router.c:131)
==52257==    by 0x268AB8: zebra_vrf_table_create (zebra_vrf.c:432)
==52257==    by 0x268AB8: zebra_vrf_enable (zebra_vrf.c:140)
==52257==    by 0x4977036: vrf_enable (vrf.c:286)
==52257==    by 0x4977036: vrf_enable (vrf.c:275)
==52257==    by 0x497797D: vrf_init (vrf.c:554)
==52257== …
```
> zebra: Initialize RB tree for router tables

- bgpd/bgp_route.c
Currently there is a dest flag `BGP_NODE_SOFT_RECONFIG` that when set completely stops processing of the path, because it is assumed that when running through all of those adjacency in's that the node will be reprocessed.
Imagine this series of events:
a) route-map change that causes a soft-adjacency run to be triggered for the dest.
b) Schedule all dests associated with the adjacency in's to be processed in the future
c) Some other event that causes a need for processing of that node.  This can be, but is not limited to:
1) NHT change and we need to reprocess the node
2) Receive a update for a dest that does not have soft
adjacency turned on( but some other path_info for the
node does.
d) Current best path processing sees that the node has a SOFT_RECONFIG flag on it, this stops …
> bgpd: Soft-reconfig should not completely stall bestpath processing

- zebra/zebra_evpn_neigh.c
Fix Coverity CID 1644475 - null pointer dereference when n->zevpn is null in zebra_evpn_sync_neigh_static_chg().
Added defensive null checks following existing patterns in the codebase:
- Guard call to zebra_evpn_sync_neigh_static_chg() with n->zevpn check
- Use ternary operator for safe VNI access in debug logs
The fix prevents crashes when neighbor entries have null zevpn pointers while preserving existing functionality.
Ticket:
Signed-off-by: Rajesh Varatharaj <rvaratharaj@nvidia.com>
> zebra: fix null pointer dereference in zebra_evpn_sync_neigh_del

- zebra/main.c
- zebra/zebra_nhg.c
- zebra/zebra_nhg.h
- zebra/zebra_router.c
Fixing stale NHG issue in kernel.
**Issue1:**
1. zebra creates an nhe and sets 'initial delay' flag for the nexthop received along with kernel/connected route and this routes is a v6 route.
2. Later zebra receives intf_address event for the interface that belongs to the same nhe created above. but this is v4 event. Then zebra iterates through the nhe set linked to this interface and eventually it will end up installing this nhe in kernel
So, we install the NHG in kernel for connected/kernel routes and that looks to be deviating from the expected behaviour. All this happens when we receive interface event, we attempt a reinstall for all the NHGs associated with that intf. But if the 'initial delay' is already set for an NHG, we can skip that.
Fixing the same.
**Issue2:**
During FRR restart …
> zebra: fix stale NHG in kernel

- doc/user/index.rst
The quagga site is dead; remove the link from our docs.
Fixes FRRouting/frr-www#83
> doc: remove dead link to quagga website

- tests/topotests/lib/topogen.py
use --version flag to obtain exabgp version
> tests: exabgp drops `-v` flag in 4.2.25, use `--version``

- bgpd/bgp_bmp.c
- bgpd/bgpd.c
- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/test_bgp_bmp_3.py
- tests/topotests/lib/bmp_collector/bgp/open/__init__.py
- tests/topotests/lib/bmp_collector/bmp.py
2 Fixes related to how BGP open messages are forged for LOC-RIB notification messages.
Actually all fields are set to 0, but this is not what is usually expected.
Use the settings of the current BGP instance for AS value and router-id.
> Bmp locrib bgp open message

- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- tests/topotests/bgp_listen_l3vrf/r1/frr.conf
- tests/topotests/bgp_listen_l3vrf/r3/frr.conf
- tests/topotests/bgp_listen_l3vrf/test_bgp_listen_l3vrf.py
Currently bgpd open a listening port for every existing bgp instance.
This leads to have open port (identified as a security leak) for l3vrf without neigbhors.
Now only default VRF is opening is BGP port at starting
other VRF wait for neigbhor creation or listening-range command
> bgpd: avoid BGP port opening for VRF instances

- bgpd/bgp_route.c
Just adjust display format for `show bgp ipv6 unicast`, add two white spaces.
Before:
```
*>i 3001::/64        fe80::2e53:4aff:fe30:820
0    100      0 i
```
After:
```
*>i 3001::/64        fe80::2e53:4aff:fe30:820
0    100      0 i
```
> bgpd: adjust display format

- lib/vty.c
- lib/vty.h
This reverts the `vtysh_flush()` part of #16672 since it is just plain not permissible to do that. There's a cascaded partial revert of #17571, but that was only a minor adjustment and it remains intact in the general sense.
A better/correct fix would be to do something like engineering a `vtysh_try_flush()` function; but I'd prefer to not do that on stable versions, so here's a revert to get back to functionally correct before we take another go at the memory spike problem.
cf.  #19040 for related discussion (this revert should make that PR unnecessary)
> lib: revert addition of vtysh_flush() call in vty_out()

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn_mh.c
- bgpd/bgp_evpn_mh.h
Mac only EVPN type-2 routes should not be advertised with the MPLS
Label2 (L3VNI).
Only mac-ipv4 and mac-ipv6-global routes should be advertised with the
second label. This check is already performed for attaching the Extended
community such as RMAC and L3VNI RTs. The same check applies to the
second label as well.
> L3VNI should not be attached to Mac only type-2 routes

- tests/topotests/bgp_bmp/bgpbmp.py
- tests/topotests/bgp_bmp/test_bgp_bmp_1.py
- tests/topotests/bgp_bmp/test_bgp_bmp_2.py
- tests/topotests/bgp_bmp/test_bgp_bmp_3.py
The bgp_bmp tests have a global SEQ number that was being shared across all tests running at the same time.  As such if one of the 3 tests was running at the same time as the other 2, you could end up in a situation where the SEQ number from one test would affect a different test, thus causing it to get out of sync and fail the test.
I saw this when I added log output to display the starting sequence number and in the failing tests, the sequence number that was being started with was 87.  This fixes the issue by creating a sequence context that needs to be passed in for each function that bgpbmp.py supports.
> tests: Fix bgp_bmp tests

- tests/topotests/bgp_tcp_ip_transparent/test_bgp_tcp_ip_transparent.py
- tests/topotests/example_munet/test_munet.py
- tests/topotests/isis_topo1/test_isis_topo1.py
- tests/topotests/lib/bgp.py
- tests/topotests/lib/ospf.py
- tests/topotests/log_config/basic.py
- tests/topotests/mgmt_debug_flags/test_debug.py
- tests/topotests/mgmt_rpc/test_rpc.py
- tests/topotests/mgmt_startup/util.py
- tests/topotests/nhrp_topo/test_nhrp_topo.py
- tests/topotests/send_log/test_send_log.py
- tests/topotests/static_vrf/test_static_vrf.py
- tests/topotests/zebra_received_nhe_kept/test_zebra_received_nhe_kept.py
Test is showing this on failure in the logs:
2025-07-09 11:28:15,614  INFO: topo: Function raised exception: "AssertionError("Failed to find \n  '192.0.2.130'\n   in \n  '198.51.100.1 nhid 25 via 192.0.2.2 dev r1-eth0 proto 196 metric 20 \n  '\nassert '192.0.2.130' in '198.51.100.1 nhid 25 via 192.0.2.2 dev r1-eth0 proto 196 metric 20 \\n'")"
2025-07-09 11:28:15,614  INFO: topo: Retry timeout of 1s reached
2025-07-09 11:28:15,615  INFO: topo: Spawn collection of support bundle for r1
2025-07-09 11:28:15,615 DEBUG: r1: cmd_status("/bin/bash -c 'mkdir -p /tmp/topotests/static_vrf.test_static_vrf/worker-logs/gw4/r1/support_bundles/test_static_vrf'")
2025-07-09 11:28:15,618 DEBUG: r1: popen("/usr/lib/frr/generate_support_bundle.py --log-dir=/tmp/topotests/static_vrf.test_static_vrf/worker-logs …
> tests: Increase timeout for any test that uses the @retry mechanism

- bgpd/bgp_vty.c
Remove a duplicated GR timer value from a show command - looks like we had two of the same value?
> bgpd: remove duplicated gr timer value

- bgpd/bgpd.c
Issue:
The vtysh running-config will incorrectly show
bgp neighbor local-as value as (null) with this config sequence -
1.configure bgp peer-group p1 with local-as as1
2.configure bgp neighbor n1, assign peer-group pg1 to it.
3.set local-as of neighbor n1 to as1
RC:
peer->change_local_as_pretty(having string value of local-as) is not set for bgp neighbor,
when new configured local-as value is same as its current local-as value.
This will skip setting peer->change_local_as_pretty,
when neighbor that inherited local-as from peer-group is configured with same local-as as its peer-group.
Fix:
1.Set peer->change_local_as_pretty to the input as_string value,
if both values dont match.
2.prevent peer->change_local_as_pretty memleak in bgp peer when local-as is changed
in its associated …
>     bgpd: fix "neighbor <n> local-as (null)" in running-config

- lib/libfrr.c
- lib/libfrr.h
- zebra/interface.c
- zebra/ioctl.c
- zebra/kernel_netlink.c
- zebra/kernel_socket.c
- zebra/rtadv.c
- zebra/zebra_nhg.c
- zebra/zebra_ns.c
- zebra/zebra_srte.c
I'm seeing cases of tests failing in the CI system where zebra just is not running and there are no
dumps of the backtrace.  In the past it's not
uncommon for exit to be called when zebra just
dissapears.  Let's see if we get a bit more data
in this case when it happens if we initiate a buffer flush.
> zebra: Ensure on exit that log buffers are flushed

- ospf6d/ospf6_route.c
- tests/topotests/lib/ospf.py
- tests/topotests/ospf6_gr_topo1/rt1/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt2/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt3/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt4/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt5/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt6/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/rt7/show_ipv6_ospf_route.json
- tests/topotests/ospf6_gr_topo1/test_ospf6_gr_topo1.py
- tests/topotests/ospf6_point_to_multipoint/test_ospf6_point_to_multipoint.py
- tests/topotests/ospf6_topo1/test_ospf6_topo1.py
- tests/topotests/ospf6_topo1_vrf/test_ospf6_topo1_vrf.py
- tests/topotests/ospf6_topo2/test_ospf6_topo2.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp_lan.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa2.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_routemaps.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_rte_calc.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
See individual commits but the problem boils down to the fact that the ospf6 `show ipv6 ospf6 route json` output is wrong and needs to be adjusted to an array.  This of course results in a decent number of test changes in order for the tests to continue to work.
> Ospf6 json output fix

- bgpd/bgp_open.c
- lib/plist.c
- ospf6d/ospf6_neighbor.c
- ospf6d/ospf6_route.c
- ospf6d/ospf6_spf.c
- zebra/zebra_evpn_mac.c
- zebra/zebra_evpn_neigh.c
- zebra/zebra_routemap.c
- zebra/zebra_vxlan.c
Cleanup some allocated json objects in several components; generally ensuring that objects are freed in error cases.
Fixes #19151
> lib,bgpd,ospf6d,zebra: Free json objects in error paths

- tests/topotests/isis_srv6_topo1/test_isis_srv6_topo1.py
I'm getting some ping failures locally due to busy system. Let's give 20 pings and allow more than a little failure as long as something goes through.
> tests: Modify isis_srv6_topo1 to allow some ping failures

- bgpd/bgp_route.c
Reset the boolean used in counting filtered routes - looks like if it was ever set "true", it stayed set.
> bgpd: fix filtered_routes_count

- lib/vty.c
- lib/vty.h
Send incremental results periodically, instead of buffering large vty output streams. 
This restores a version of the work done in commits from these two earlier PRs:
#16672  lib: Memory spike reduction for sh cmds at scale
9112fb367b1ae0168b4e7a81f41c2ca621979199
#17571  lib,vtysh: Use backoff setsockopt option for freebsd
959dbe27cde21ab212f6566b30865b2da418b4d2
That work was reverted by #19109  because error-handling during the incremental output flush, if the remote vtysh exited e.g., would lead to an application crash. This version tries to recognize that an error has occurred, but defer closing the application's vty object until after the application callback has completed and the vty is no longer being used.
> lib: incremental vty output, restored

- zebra/zebra_vxlan.c
Recent changes in how prefix_sg is created causes coverity to complain about uninitialized data.
> zebra: Make coverity happy with prefix_sg declaration

- bgpd/bgp_route.c
Found by the static analyzer Svace (ISP RAS): DEREF_AFTER_FREE. 
Pointer '&bn->flags' is dereferenced at bgp_route.c:9813 after the referenced memory was deallocated at bgp_table.c:91 by passing as 1st parameter to function 'bgp_dest_unlock_node' at bgp_route.c:9812.
I suggest moving the memory release 2 lines lower.
> bgpd: fix DEREF_AFTER_FREE in bgp_route

- tests/topotests/pim_embedded_rp/test_pim_embedded_rp.py
Two changes in Embedded RP topology test:
- When testing the learned embedded RP limit ensure that the groups are learned in a particular order so we always pick the correct filtered group
- Increase the amount of wait time for multicast state convergence.
> topotests: improve embedded RP test reliability

- vtysh/vtysh.c
Fix the "dryrun" boolean used when applying config from a file with "copy FILE running-config". The boolean was mis-set.
> vtysh: copy config from file should actually apply

- lib/nexthop.c
- lib/nexthop.h
- tests/topotests/two_layer_wucmp/README.md
- tests/topotests/two_layer_wucmp/leaf1/frr.conf
- tests/topotests/two_layer_wucmp/leaf2/frr.conf
- tests/topotests/two_layer_wucmp/spine1/frr.conf
- tests/topotests/two_layer_wucmp/spine2/frr.conf
- tests/topotests/two_layer_wucmp/test_two_layer_wuecmp.py
- zebra/zebra_nhg.c
With W-ECMP, when an interface goes down, we mark the singleton nexthop as INACTIVE. We then process the dependents (NHG groups containing this singleton nexthop) and attempt to mark them as INACTIVE as well.
During this process, we compare all singleton nexthops in the nexthop group with the singleton nexthop that went down using nexthop_same() in zebra_nhg_set_valid().
However, there's a weight mismatch issue:
- The standalone singleton nexthop has weight = 1
- The same singleton nexthop when part of an NHG has weight = 255 This weight mismatch causes nexthop_same() to return FALSE, preventing proper matching.
Testing:
```
Before fix:
ID: 76 (zebra)
RefCnt: 20
Uptime: 00:00:59
VRF: default
Valid, Installed
Interface Index: 46
via 22.64.0.18, swp43 (vrf default), weight 1          <<<< …
```
> lib, zebra: mark singleton nexthops inactive/active on link state changes for wecmp

- tests/topotests/ospf_topo1/test_ospf_topo1.py
The addition of kernel routes are immediately checked after routes have been accepted locally.  This test has no check to give the routes time to be installed from ospf->zebra->kernel. Modify the test to do so.
> tests: Modify ospf_topo1 to use run and expect for kernel routes

- eigrpd/eigrp_hello.c
Improve validation for hello packets and their TLVs; check for too-short and well as too-long values; don't process zero-length TLVs.
Fixes #19250
> eigrp: validate hello packets and tlvs better

- bgpd/bgp_trace.h
In the bgpd module, the `TP_ARGS` macro was causing a compilation error due to an incorrect argument type for `bgp`. This commit updates the macro to use `struct bgp *` instead of `bgp`, resolving the issue.
No issue related.
> bgpd : Fix compilation error in bgpd module: Update TP_ARGS for bgp

- bgpd/bgp_vty.c
- doc/user/bgp.rst
This PR has below changes
* Add new json CLI “show ip bgp l2vpn evpn update-groups json”
* Add command to display EVPN type-5 per-prefix
* Fixed selectionDeferralTimer JSON field as it was displaying stalepath timer value instead of select_defer_time
> bgpd: CLI Changes

- bgpd/bgp_vty.c
Fixed selectionDeferralTimer JSON field which was displaying stalepath timer value instead of select_defer_time.
Issue:3803619
> bgpd: [GR] fixed selectionDeferralTimer to display select_defer_time val

- tests/topotests/munet/base.py
When failing to mount the sysfs, give it up
to 30 seconds for failure to perculate.  Additionally let's gather the dmesg to see what it is telling us in the failure case.
> tests: Allow for longer period of sysfs retry

- bgpd/bgp_packet.c
- doc/user/bgp.rst
- tests/topotests/bgp_dual_as/r1/frr.conf
- tests/topotests/bgp_dual_as/r2/frr.conf
See individual commits.  But the tl;dr -> the bgp_dual_as test is sometimes failing because of how the test was setup.  Let's change the test to negate this from happening in the future.  Add some additional debugs to bgp and add some verbiage to the documentation to help operators from getting into this situation.
> Bgp dual as fixes

- tests/topotests/bgp_evpn_vxlan_topo1/test_bgp_evpn_vxlan.py
This test is doing this:
ping XXXX
<ensuring that the local neighbor address has shown up>
Unfortunately it has absolutely no run_and_expect and as such under heavy load the appropriate processing needed to handle this in zebra will not always happen before the test starts checking for it.
Modify the code to check for the mac address for up to 30 seconds.
> tests: Fix bgp_evpn_vxlan_topo1 in one case

- bgpd/bgp_vty.c
The following error happens:
> red1(config)# router bgp 500 vrf RED_B
> red1(config-router)#  address-family ipv4 unicast
> red1(config-router-af)# import vrf default
> red1(config-router-af)# import vpn
> red1(config-router-af)# import vrf afz
> % error: Please unconfigure vpn to vrf commands before using import vrf commands
Do not use the import|export vpn command while vrf command is used.
> bgpd: fix do not use import|export vpn when import vrf command used

- configure.ac
Abseil [0] sets a hard lower-limit on the C++ version [1]. As we also hard-code the version here, we should relax it and just use the highest version the installed compiler supports.
The previous code breaks Debian Trixie, where the abseil package needs C++14 (and g++ supports it), but we set C++11 as the standard.
[0]: https://github.com/abseil/abseil-cpp
[1]: https://github.com/abseil/abseil-cpp/blob/483951bb49b4ca91510b94884ee2436d79c74bef/absl/base/policy_checks.h#L81
> build: remove C++ version restriction for grpc build

- bgpd/bgp_route.c
This reverts commit e11791f475be03f1e5bbacac8368fece717e51ca.
This commit is causing double free. Hence reverting it.
Details:
This commit is causing double free of lecomm, ecomm, comm and aspath attributes for aggregate route with as-set, leading to BGP crash. Hence reverting it.
Problem:
When BGP route aggregation is configured with as-set and a non-existent route-map (example config below) following events occur:
1. BGP runs the route-map for aggregate route and returns RMAP_DENYMATCH in bgp_attr_aggregate_intern() since rmap `test` doesn't exist
2. bgp_attr_aggregate_intern() cleans up memory allocated for all the attributes and returns NULL to bgp_aggregate_install()
3. In bgp_aggregate_install() ,this commit introduced code to free aspath, lcomm, ecomm and comm attributes if attr is …
> Revert "bgpd: Free dup'ed attributes for aggregate routes with route-maps"

- doc/user/isisd.rst
Fix missing indentation in the SRv6 configuration example within the IS-IS documentation.
**Before:**
```
hostname HOSTNAME
password PASSWORD
log file /var/log/isisd.log
!
!
interface eth0
ipv6 router isis FOO
ip router isis FOO
isis hello-interval 5
!
interface eth1
ip router isis FOO
!
!
router isis FOO
net 49.0001.1111.1111.1111.00
metric-style wide
segment-routing srv6
locator loc1
!
line vty
```
**After:**
```
hostname HOSTNAME
password PASSWORD
log file /var/log/isisd.log
!
!
interface eth0
ipv6 router isis FOO
ip router isis FOO
isis hello-interval 5
!
interface eth1
ip router isis FOO
!
!
router isis FOO
net 49.0001.1111.1111.1111.00
metric-style wide
segment-routing srv6
locator loc1
!
line vty
```
> doc: Fix SRv6 configuration example in IS-IS documentation

- staticd/static_srv6.c
When an interface status changes from UP to DOWN or vice versa, staticd receives a notification and installs or uninstalls all SIDs that depend on that interface.
A typo is present in the debug log message.
This commit fixes the typo as shown in the examples below.
**Before:**
```
r1# ip link set sr0 down
r1# ip link set sr0 up
r1# cat mgmtd.log
...
2025/08/13 09:51:56.094801 STATIC: [P9961-ZG7PV] static_ifp_srv6_sids_update: Interface disabled disabled. sr0 SIDs that depend on the interface
2025/08/13 09:51:57.638533 STATIC: [P9961-ZG7PV] static_ifp_srv6_sids_update: Interface enabled Removing. sr0 SIDs that depend on the interface
...
```
**After:**
```
r1# ip link set sr0 down
r1# ip link set sr0 up
r1# cat mgmtd.log
...
2025/08/13 10:19:34.357281 STATIC: [X9BAH-9VKGQ] …
```
> staticd: Fix typo in SRv6 SIDs debug logs for interface UP/DOWN events

- zebra/zebra_srv6_vty.c
Explicitly print 'exit' at the end of srv6 encapsulation node configuration. This ensures consistency with other VTY nodes and prevents issues similar to those fixed in https://github.com/FRRouting/frr/pull/9331.
```
srv6
encapsulation
source-address fcbb:bbbb:1::1
exit                <<<<<<<<<< Add this "exit" statement
locators
locator MAIN
prefix fcbb:bbbb::/48
format usid-f3216
exit
...
```
> zebra: Explicitly print "exit" at the end of srv6 encap node config

- zebra/rt_netlink.c
Guard a debug in the rt netlink code.
> zebra: Add missing debug guard in rt netlink code

- pimd/pim_bsm.c
- pimd/pim_instance.c
BSM doesn't work with vrf.
`vrf_bind()` should be called in `vrf_master.vrf_enable_hook()`, must not in `vrf_master.vrf_new_hook()` which is in vrf-disabled status.
So move `vrf_bind()` into `pim_vrf_enable()` for BSM socket.
> pimd: fix wrong bsm case with vrf

- pimd/pim_upstream.c
- pimd/pim_vty.c
With the configuration:
```
router pim6
register-suppress-time 50000
```
Then:
```
anlan(config-pim6)# rp keep-alive-timer 12
anlan(config-pim6)# no rp keep-alive-timer 12
anlan(config-pim6)# do show run
!
router pim6
register-suppress-time 50000
rp keep-alive-timer 65535 <-
exit
!
```
Since `pim->rp_keep_alive_time` can't exceed 65535, these places should consider the special conversion:
1) show running config
2) set/unset "register-suppress-time" commands
> pimd/pim6d: fix wrong running config

- doc/developer/topotests.rst
Tests are starting to need to be compiled with a decent amount of ecmp turned on.  Let's document this.
> doc: Show proper amount of ecmp needed for tests now

- zebra/interface.c
Add to the `show int XXX` command whether or not
BGP has configured RA for the interface or not.
> zebra: Add to `show int ..` if BGP configed RA or not

- bgpd/bgp_label.c
- tests/topotests/bgp_lu_topo1/test_bgp_lu.py
See individual commits for important bits/bobs
the test changes are because the test is just wrong, the upstream test failures are happening because the test is doing a clear then immediately checking end result.  If the clear hasn't happened the end result is going to be what is actually there.  So modify the tests to make sure the clear happens ( when you do this the test always fails for me )
> Labelpool changes

- lib/log_cli.c
- lib/log_nb.c
- lib/log_vty.c
- lib/log_vty.h
- mgmtd/mgmt_be_adapter.c
- yang/frr-logging.yang
This was being handled by vty to each daemon, but the correct way this should be handled now is with YANG RPCs, so move to that.
> lib: move `clear log cmdline-targets` to YANG RPC

- bgpd/bgp_label.c
- bgpd/bgp_labelpool.c
- bgpd/bgp_labelpool.h
- bgpd/bgp_mplsvpn.c
The bgp labelpool manager used a ... scary "void *" based api that accepted several different structs as arguments. Use typed apis for the various structs that can release labels; move the generic release code to a private common helper.
> bgpd: clean up lp_release api

- tests/topotests/grpc_basic/test_basic_grpc.py
A few new backends have been added + a "frr-logging" json object.
> tests: fix grpc_basic tests

- tests/topotests/bgp_listen_l3vrf/test_bgp_listen_l3vrf.py
The grep in the check_port_179_open was matching against incorrect data for the ss output:
2025-08-28 14:33:10,037  INFO: topo: <re.Match object; span=(33, 40), match='0.0.0.0'>
2025-08-28 14:33:11,042 DEBUG: r1: cmd_status("/bin/bash -c 'ss -tuplen | grep :179 '") 2025-08-28 14:33:11,434 DEBUG: r1:
stdout: tcp   LISTEN 0      3            0.0.0.0:2616      0.0.0.0:*    users...
2025-08-28 14:33:11,434  INFO: topo: tcp   LISTEN 0      3            0.0.0.0:2616      0.0.0.0:*    users:(("staticd",pid=1331068,fd=11)) uid:126 ino:1793738408 sk:102b cgroup:/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-16849abe-4367-40b4-9b10-7c8146fb9591.scope <->
tcp   LISTEN 0      3            0.0.0.0:2623      0.0.0.0:* …
> tests: Actually look for port 179

- bgpd/bgpd.c
- tests/topotests/bgp_remote_as_ra_validation/r1/frr.conf
- tests/topotests/bgp_remote_as_ra_validation/test_bgp_remote_as_ra_validation.py
When a peer group's remote-as configuration is removed and then re-added, BGP unnumbered peers in that group were not getting their Router Advertisement (RA) re-initiated.
The issue was in peer_group_remote_as() function which handles adding remote-as to peer groups. While peer_group_remote_as_delete() properly terminates RA for BGP unnumbered peers, the add function was missing the corresponding RA re-initiation logic.
Fix adds RA re-initiation for all BGP unnumbered peers with extended next-hop capability when remote-as is configured on the peer group.
Ticket :#4597330
> bgpd: Fix RA not re-initiated when remote-as is re-added to peer group

- doc/developer/building-frr-for-debian13.rst
- doc/developer/building.rst
- doc/developer/subdir.am
Add build instructions in the developer docs for debian 13 (trixie). Copied them over from debian 12 and changed a few things:
* Updated the gRPC packages
* Updated libyang instructions (libyang is now packaged in debian)
* Add `mkdir /etc/frr` and `mkdir /var/log/frr` before installing config files
* Add the installation of systemd service file and enable + start commands
All the rest is still relevant, including the missing shared library error.
> docs: add build instructions for debian 13

- ospf6d/ospf6_spf.c
crash occurs in fields
core 1:
result_table=0x5e7c57a1ba80, oa=0x5e7c57a1b810)
at /build/make-pkg/output/_packages/cp-routing/src/ospf6d/ospf6_spf.c:502
at /build/make-pkg/output/_packages/cp-routing/src/ospf6d/ospf6_spf.c:638
core 2:
at /build/make-pkg/output/_packages/cp-routing/src/ospf6d/ospf6_spf.c:386
result_table=0x5727e5e99200, oa=0x5727e5eae1d0)
at /build/make-pkg/output/_packages/cp-routing/src/ospf6d/ospf6_spf.c:502
at /build/make-pkg/output/_packages/cp-routing/src/ospf6d/ospf6_spf.c:638
core analysis exhibits v->lsa is use while the memory had been freed or more reallocated to another type structure.
proposed fix, protect v->lsa by ospf6_lsa_lock/unlock use.
> ospf6d: protect LSA in vertex

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn.h
- bgpd/bgp_main.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgp_zebra.h
- bgpd/bgpd.c
- bgpd/bgpd.h
- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_chaos_topo1.py
- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py
There is an issue in this L3vni optimization design. With the current
optimization, we have two issues.
1) Overwriting the states (ADD/Withdraw) leading to inconsistencies
between Zebra and BGP.
2) Post processing handling in the delete
- When BGP receives a L3VNI add
* Pre-processes (update RDs, tunnel ip etc..)
* Schedule the remote route processing for global walk
* No post processing
- However, in case of L3VNI del
* No pre-processing
* Schedules the remote route processing for global walk
* Post-processing: handle the delete/memset portion of code
Imagine the below situation
T0: L3VNI Up in zebra
T1: L3VNI added in BGP via Zebra
T2: BGP imports type-5 route in the tenant VRF for this L3VNI based on
import RTs
T3: VRF routes runs best path and programmed in zebra
T4: Before Zebra gets …
> Revert l3vni optimization

- bgpd/bgp_fsm.c
- bgpd/bgp_packet.c
- bgpd/bgp_packet.h
- bgpd/bgpd.h
Treating the first keepalive message as an "implicit" EOR was a temporary hack before the EOR for GR was defined more than 20 years ago. The logic can cause GR to be prematurely terminated, and should have been removed a long time ago.
> bgpd: remove the implicit EOR (keepalive message) for GR

- doc/developer/cli.rst
Moving this dev doc change out of the ipv6 VTEP PR; it's really general and unrelated to that feature
> doc: Add example for "Ran out of docstring"

- debian/rules
- doc/developer/packaging-debian.rst
To debug hard to reproduce memory corruptions, it may be useful to have "production" build of FRR compiled with enabled address sanitizer. However this should not be the default. Use `DEB_BUILD_PROFILES` feature to optionally enable sanitizer at package build time. With such profile, debian package will be built with configure option "--enable-address-sanitizer".
> Debian build: introduce profile "pkg.frr.asan"

- zebra/connected.c
- zebra/debug_nl.c
- zebra/dplane_fpm_nl.c
- zebra/main.c
- zebra/rt_netlink.c
- zebra/zapi_msg.c
- zebra/zebra_fpm_netlink.c
- zebra/zebra_fpm_protobuf.c
- zebra/zebra_mpls_openbsd.c
- zebra/zebra_nb_state.c
- zebra/zebra_nhg.c
- zebra/zebra_rib.c
- zebra/zebra_router.c
- zebra/zebra_router.h
- zebra/zebra_vty.c
Currently it is up to the operator to fully specify zrouter values via command line or compile time options.  It is desirable to allow a copy of FRR to dynamically figure some of these out at run time. Let's provide a hook for that too happen.
> zebra: Allow for NOS to initialize some zrouter values

- bgpd/bgp_route.c
The pointer 'evpn' in bgp_update() can be stale after creating/ interning attrs into attr_new; use the value from the new attr object.
Turning on debug bgp updates with asan on exposed this as a use-after-free.
> bgpd: don't use stale 'evpn' pointer in bgp_update()

- bgpd/bgp_vty.c
The reason being shown is simply wrong.
> bgpd: fix last-reset-reason in bgp_show_failed_summary()

- bgpd/bgp_fsm.c
Just like the "established" or "dropped" counters for a peer, the last_reset field should not be copied in peer_xfer_conn().
> bgpd: remove the last_reset copying in peer_xfer_conn()

- lib/mgmt_be_client.c
- mgmtd/mgmt_testc.c
- tests/topotests/mgmt_notif/test_ds_notify.py
Previously attaching a notify handler to a covering container that was non-presence would not be noticed due to an apparent optimization in the nb_node parent chain which skips over NP container nodes in branches. Use the libyang parent pointer chain to avoid this problem.
Update test client so topotest tests this bug and fix.
> Allow notify callback on non-presence container

- bgpd/bgp_bmp.c
- bgpd/bgp_bmp.h
The current implementation has this cycle:
a) As path_info comes in, bmp_process is called, this generates an item on a hash.  This typesafe hash was automatically growing as more path info's were received.
b) This generation of items on the hash eventually causes pullwr_run to happen, which pulls items off the hash, encodes them and sends them to a peer.  This causes the hash to automatically shrink.
Now imagine a scenario where you have a large number of paths being brought in upon initial startup.  Run time starts to be dominated by the hash_grow and hash_shrink functions because it involves reallocs and memory manipulation:
+   99.17%     0.00%  bgpd     bgpd               [.] _start
+   99.17%     0.00%  bgpd     libc.so.6          [.] __libc_start_main
+   99.17%     0.00%  bgpd …
> bgpd: Convert bmp path_info tracking from hash to rbtree

- bgpd/bgp_bmp.c
The code calls XFREE on bbpeer->open_tx twice.
There is no need to do it twice.
> bgpd: Remove unnecessary code in bgp_bmp.c

- bgpd/bgp_fsm.c
- bgpd/bgpd.h
It should more generic, and for both ipv4 or ipv6.
> bgpd: fix the description for PEER_DOWN_NBR_ADDR

- bgpd/bgp_bfd.c
- bgpd/bgp_fsm.c
- bgpd/bgp_network.c
- bgpd/bgp_packet.c
- bgpd/bgp_vty.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
The function peer_set_last_reset() is introduced to facilitate additional features, such as checking for peer status and duplicate setting and even possible recording of a series of reset causes.
> bgpd: use a function to set the peer reset cause

- bgpd/bgp_evpn_vty.c
If BGP has been created with a vni, but there has
been no reason to create the bgp vrf associated with the vni, prevent a crash with the show run.
If you have this config:
router bgp 65000
timers bgp 3 9
bgp router-id 10.10.10.10
no bgp default ipv4-unicast
neighbor 10.30.30.30 remote-as 65000
neighbor 10.30.30.30 update-source lo
neighbor 10.30.30.30 timers 3 10
!
address-family l2vpn evpn
neighbor 10.30.30.30 activate
advertise-all-vni
advertise-svi-ip
vni 101
rd 10.10.10.10:101
route-target import 65000:101
route-target export 65000:101
exit-vni
advertise-svi-ip
And if there is no reason to yet create the bgp vrf associated with the vni and you issue a show run,
bgp will crash.  This is because the vpn->bgp_vrf
pointer is NULL and it is dereferenced.  If you examine the bgp_evpn code, …
> bgpd: Do not crash with only vni configed.

- bgpd/bgp_vty.c
BGP has a command to allocate a SID for a specific address family:
```
router bgp ASN vrf VRFNAME
address-family <ipv4|ipv6> unicast
sid vpn export <auto | explicit X:X::X:X>
!
!
```
We use two `vpn_policy` flags to indicate the allocation mode:
- `BGP_VPN_POLICY_TOVPN_SID_AUTO` is set when the SID is allocated in auto mode.
- `BGP_VPN_POLICY_TOVPN_SID_EXPLICIT` is set when the SID is allocated in explicit mode.
The BGP Vty code has a check to prevent configuring both auto and explicit modes at the same time:
- If a user tries to allocate a SID in auto mode for an address family and the `BGP_VPN_POLICY_TOVPN_SID_EXPLICIT` flag is already set, it indicates that the SID has been already allocated in explicit mode, and the configuration should be rejected.
- If a user tries to allocate a SID …
> bgpd: Fix incorrect flag checks for SRv6 SID allocation

- bgpd/bgp_mplsvpn.c
- bgpd/bgp_vty.c
- bgpd/bgpd.h
If the router-id is learned after a bgp vrf has
already received a specified rd, it will auto-derive a value and override the specified on the command line.
Do not let this happen.
> bgpd: Do not override a specified rd

- bgpd/bgp_fsm.c
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_zebra.c
- bgpd/bgpd.h
- tests/topotests/bgp_gr_fib_suppress/__init__.py
- tests/topotests/bgp_gr_fib_suppress/r1/frr.conf
- tests/topotests/bgp_gr_fib_suppress/r2/frr.conf
- tests/topotests/bgp_gr_fib_suppress/r3/frr.conf
- tests/topotests/bgp_gr_fib_suppress/test_bgp_gr_fib_suppress.py
Currently during GR, EOR is sent to neighbor prematurely for wfi enabled case. below fix has be implemented.
keep a counter to track the routes installed in FIB.Increamnet
counter when bgp send route install to zebra, decreamnet counter when
fib install ack to received from zebra in bgp.when this count reaches
zero and route deferred count is 0 ad gr route syn pending is set, then
do further processing of sending EOR and zebra gr update complete.
This will send EOR as soon as last route fib install ack is received.
Testing:
before:
2020:2025/08/19 21:23:53.786402 BGP: [ZP3RE-J4Q8C] send End-of-RIB for IPv4 Unicast to swp1s1.3 2021:2025/08/19 21:23:53.786412 BGP: [ZP3RE-J4Q8C] send End-of-RIB for IPv6 Unicast to swp1s0.3 2022:2025/08/19 21:23:53.786415 BGP: [ZP3RE-J4Q8C] send End-of-RIB …
> bgpd:send EOR during GR only when fib install comeplete for wfi enabled

- bgpd/bgp_fsm.c
- bgpd/bgp_route.c
- bgpd/bgpd.c
- bgpd/bgpd.h
This hash is really connection oriented instead of peer oriented.  Let's change it over to be connection based.
Long term the end goal is to get rid of the doppelganger.  This is addtional work towards this
> bgpd: Convert the bgp->peerhash to a connectionhash

- zebra/kernel_socket.c
This broadcast of 0.0.0.0 is being treated as
the dest_same as false.  When creating the
ifc on freebsd the ifc is created with no
broadcast values and as such when a deletion
event happens the ifc is not found and the
event is ignored.  Modify the code to
treat a broadcast address of 0 as a dest_same = true.
This allows for the deletion of the local and connected routes.
sharpd@robot:~/frr $ sudo ifconfig lo0 inet 216.92.216.57 netmask 255.255.255.0 add sharpd@robot:~/frr $ sudo vtysh -c "show ip route" % Can't open configuration file /usr/local/etc/frr/vtysh.conf due to 'No such file or directory'. Configuration file[/usr/local/etc/frr/frr.conf] processing failure: 11 2025/10/01 18:29:59 [H0DHT-S9KF2][EC 100663299] setsockopt_so_recvbuf: fd 3: SO_RCVBUF set to 1048576 (requested …
> zebra: freebsd is sending a broadcast of 0.0.0.0

- bgpd/bgp_route.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
Ensure the clearing info object iteration correctly accounts for the "outer"/RD table and "inner" table nature of the VPN
SAFIs. Depending on the number of prefixes and number of RDs, the existing iteration logic could move past an RD value before completely removing all associated prefixes.
Also improve some debugs, especially in the paths where the bgp dest object is an RD - the generic bgp dest output format handler doesn't understand RDs.
Fixes: #19605
> bgpd: Fix bgp peer clearing logic

- zebra/zebra_gr.c
Recent commit 4ab7f0a1c6987fd2bc7eac1501824c63dec3fcee added a frrtrace point which does not exist and this breaks compilation when lttng is enabled.
> zebra : Fix compilation when lttng is enabled

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/notification_check.py
There are a series of tests that use the `notification_check.py` script to test that neighbors have come up.  Unfortunately it is failing if any notification messages come in.  A `Cease/Collision` notification is a normal part of bgp operation and should not be used to fail the test as that it is completely normal for both sides to connect at the same time, especially in a testing environment.
We can see this in our daily runs:
* test_notification_check (https://ci1.netdef.org/browse/FRR-FRR-9012)
* test_notification_check (https://ci1.netdef.org/browse/FRR-FRR-9018)
* test_notification_check (https://ci1.netdef.org/browse/FRR-FRR-9019)
All three of these show the same problem.  Let's just make the message something that doesn't fail the test.
> tests: Allow a Collision notification to not fail the test

- tests/topotests/ospf_topo2/r1/frr.conf
- tests/topotests/ospf_topo2/r2/frr.conf
- tests/topotests/ospf_topo2/r3/frr.conf
- tests/topotests/ospf_topo2/r4/frr.conf
The current code for this test uses the `dead-interval minimal..` command.  This causes the hello timer to be `1/<minimal value>` in seconds.  So with 4 each hello is sent out every 1/4 second. In our ci system a heavily loaded system may not even get to a 1 second dead timer and cause the daemon to time out the peering.  This is not really conducive to a testing setup that is under load.  Change the test to not do this and to give much more lenient timers.
> tests: ospf_topo2 allow dead interval to be a bit longer

- ldpd/lde_lib.c
Consider the ldp neighbor with both link and targeted adjs at the same time. After the directed interface of the two boxes are removed from ldp by command line, the route via the directed interface is wrongly with label.
The reason is its targeted adj may have other path to the neighbor, so the neighbor relation between them was maintained and it did label mapping procedure for all nexthops without checking ldp interface.
> ldpd: fix wrong label mapping procedure

- doc/developer/building-frr-for-freebsd14.rst
These two packages are not available on freebsd14 when I try to install them:
sharpd@robot:~/frr $ sudo pkg install py32-sphinx
Updating FreeBSD-ports repository catalogue...
FreeBSD-ports repository is up to date.
Updating FreeBSD-ports-kmods repository catalogue... FreeBSD-ports-kmods repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py32-sphinx' have been found in the repositories sharpd@robot:~/frr $ sudo pkg install py39-pytest
Updating FreeBSD-ports repository catalogue...
FreeBSD-ports repository is up to date.
Updating FreeBSD-ports-kmods repository catalogue... FreeBSD-ports-kmods repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py39-pytest' have been found in the …
> doc: Fixup building freebsd14 doc

- bgpd/bgp_routemap.c
- lib/vrf.c
- ripngd/ripngd.c
Ran clang 19 SA on *BSD and it found some stuff that needed to be cleaned up.
> Clang 19 on bsd sa issues

- tests/topotests/msdp_topo1/test_msdp_topo1.py
If you change the test to limit at 3, 5, 6, 7 it never fails. Additionally the test can fail because the msdp SA announcements have not been received yet.  Modify the code base to actually look for the 4 limit being hit.
> tests: msdp_topo1 not properly detecting SA limit being hit

- ospfd/ospf_spf.c
- ospfd/ospf_spf.h
- ospfd/ospf_ti_lfa.c
Upon examining this Indirect leak:
Indirect leak of 160 byte(s) in 4 object(s) allocated from:
#0 0x7fe4f40b83b7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
#1 0x7fe4f3c24c1d in qcalloc lib/memory.c:111
#2 0x7fe4f3c03441 in list_new lib/linklist.c:49
#3 0x564c81d076f9 in ospf_spf_vertex_copy ospfd/ospf_spf.c:335
#4 0x564c81d0bff2 in ospf_spf_copy ospfd/ospf_spf.c:378
#5 0x564c81d158e8 in ospf_ti_lfa_generate_p_space ospfd/ospf_ti_lfa.c:787
#6 0x564c81d162f5 in ospf_ti_lfa_generate_p_spaces ospfd/ospf_ti_lfa.c:923
#7 0x564c81d16532 in ospf_ti_lfa_compute ospfd/ospf_ti_lfa.c:1101
#8 0x564c81d0e942 in ospf_spf_calculate_area ospfd/ospf_spf.c:1811
#9 0x564c81d0eaa6 in ospf_spf_calculate_areas ospfd/ospf_spf.c:1840
#10 0x564c81d0eda2 in …
> ospfd: On cleanup, actually free vertexes

- eigrpd/eigrp_dump.c
- eigrpd/eigrp_packet.c
- ospfd/ospf_packet.c
- pimd/pim_igmp.c
- pimd/pim_igmp_mtrace.c
- pimd/pim_mroute.c
- pimd/pim_pim.c
FreeBSD is complaining:
warning: taking address of packed member 'ip_src' of class or structure 'ip' may result in an unaligned pointer value [-Waddress-of-packed-member]
Let's fix this so the problem goes away and the compilation is clean.
> eigrpd, ospfd, pimd: Fix usage of packed member unaligned

- configure.ac
Enable the compiler warning for format-extra-args; seems benign, but it does seem to work...
> build: add warning for extra format args

- lib/nexthop_group.c
- lib/nexthop_group.h
- tests/topotests/bgp_duplicate_nexthop/test_bgp_duplicate_nexthop.py
- tests/topotests/bgp_redistribute_table/test_bgp_redistribute_table.py
- zebra/zebra_vty.c
Add a JSON field showing count of nexthops installed in kernel FIB. Useful for debugging duplicate nexthop scenarios.
> lib, zebra: Add fib installed NH count in json show cmd
