vtysh/extract.pl.in

vtysh: add `logical-router ...` to extract.pl ignore list

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
ospfd/ospf_dump.c
zebra/zebra_vty.c

bgpd, ospfd, zebra: remove duplicate cli installs

---

lib/if.h

lib: make interface metric a uint32_t

---

.gitignore
configure.ac
m4/ax_prog_perl_modules.m4

build: check if the LibXML perl module is available

---

lib/Makefile.am
lib/imsg.c
lib/json.c
lib/json.h
lib/prefix.h
lib/thread.c
lib/thread.h
lib/wheel.c
lib/wheel.h
lib/zebra.h
zebra/if_netlink.c
zebra/kernel_netlink.c
zebra/kernel_netlink.h
zebra/rt_netlink.c
zebra/zebra_fpm.c
zebra/zebra_fpm_netlink.c
zebra/zebra_rib.c
zebra/zebra_static.c
zebra/zebra_static.h
zebra/zebra_vty.c
zebra/zserv.c
zebra/zserv.h

This is a bunch of library changes that I've pulled out of the PIM-SM-MSDP build.  
It's a grab bag of stuff, the one important thing is the commit to allow json to work across different versions.
I decided to pull it out because I do not forsee the PIM-SM-MSDP code getting in soon, because enough has changed in the intervening 2 weeks it needs some serious rebasing and now that regressions are running better they have exposed some issues that I need to fix.

Library changes

---

lib/vty.c

Fixes a couple off-by-ones introduced in previous commit.

lib: additional patch for 496e83a

---

bgpd/bgp_damp.c
bgpd/bgp_vty.c
bgpd/rfapi/rfapi_import.c
cumulus/start-stop-daemon.c
isisd/isis_bpf.c
lib/wheel.h
zebra/if_ioctl.c
zebra/kernel_socket.c
zebra/zebra_fpm.c
zebra/zserv.c

This Pull Request has a bunch of minor build warnings kicked out I noticed when looking at the *bsd logs on Martin's CI system. 
Additionally I added in the timer_wheel documentation that @louberger and @eqvinox asked for.  It was just a convenient place to put it.

Various Build Warnings Fixage

---

bgpd/bgp_main.c
isisd/isis_main.c
ldpd/control.c
ldpd/ldp_vty_exec.c
ldpd/ldpd.c
ldpd/ldpd.h
ldpd/ldpe.c
ldpd/ldpe.h
lib/privs.c
lib/sockopt.c
lib/sockopt.h
lib/vty.c
ospf6d/ospf6_main.c
ospfd/ospf_main.c
pimd/pim_main.c
ripd/rip_main.c
ripngd/ripng_main.c
vtysh/vtysh.c
vtysh/vtysh.h
vtysh/vtysh_main.c
vtysh/vtysh_user.c
zebra/main.c

Updated version of the required changes to support Snap Packages.

Snapcraft base changes

---

pimd/pim_cmd.c

Some minor pim cleanup found while rerunning vtysh

Pim fixups

---

configure.ac

bump rev to 2.1-dev	
point to https://github.com/freerangerouting/frr/issues

master: bump rev and change issues pointer

---

lib/memory.c
tests/common-cli.c

catch race conditions that seem to result in dup frees as they happen...

lib: assert on duplicate free (count)

---

README

1) Modify that PIM-SM/MSDP is now included
2) Add pointers to where people can talk to us

*: Update README

---

bgpd/rfapi/rfapi.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_import_bgp.c

Fix 3 minor RFAPI/VNC fixes found in regression testing

2.0: misc vnc/rfapi fixes

---

.gitignore
bgpd/bgp_bfd.c
bgpd/bgp_vty.c
bgpd/bgpd.c
cumulus/etc/iproute2/rt_protos.d/frr.conf
debian/frr.dirs
tools/frr
tools/frr-reload.py
zebra/kernel_netlink.c
zebra/rt_netlink.c
zebra/rt_netlink.h
zebra/zebra_ptm.c
zebra/zebra_vty.c

Various bug fixes we've done since mid-dec.

Various Updates

---

bgpd/rfapi/rfapi_import.c

fixes issue reported by @pguibert6WIND

2.0: bgp rfapi: fix resolution / lookup failure when using MPLS TT

---

bgpd/rfapi/bgp_rfapi_cfg.c
bgpd/rfapi/rfapi.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_import_bgp.c

Fix 3 minor RFAPI/VNC fixes found in regression testing
Fix add vrf command parsing
Enable nexthop vrf-policy for controller use case and automated testing

Master: misc vnc/rfapi and VRF

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/rfapi/vnc_import_bgp.c

bgpd rfapi: fix TT handling broken on Sat Jan 28 18:57:28 2017 -0500
bgpd: cleanup/restore show ip|ipv6 bgp and show bgp ipv4 summary relted
bgpd: get rid of 'unknown' in show safi (broken in earlier merge)

2.0: Fix a couple of merge related and rfapi/show vpn issues 

---

vtysh/vtysh.h
vtysh/vtysh_main.c

vtysh: Quagga.conf -> Frr.conf

---

bgpd/bgp_route.c

bgpd: fix array oob for `show ip bgp`

---

lib/vty.h
tools/frr-reload.py
vtysh/vtysh.c
vtysh/vtysh_main.c

Cleanup Quagga.conf -> Frr.conf

*: Found some instances of Quagga.conf

---

lib/command.c
lib/csv.c
lib/grammar_sandbox.c
lib/mpls.h
lib/skiplist.c
lib/vty.c
lib/zclient.c

this should bring lib/ to 0 open issues in coverity
(not counting issues marked as false positive/intentional)

more lib/ coverity fixes

---

bgpd/bgp_vty.c
lib/command.c
lib/command.h
lib/command_parse.y
lib/grammar_sandbox.c
ospf6d/ospf6_asbr.c
pimd/pim_cmd.c
tests/lib/cli/common_cli.c
tests/lib/cli/common_cli.h
tests/lib/cli/test_cli.c
vtysh/vtysh_main.c
zebra/zebra_mpls_vty.c

finally, rip out the old deduplication handling and add it as a separate, independent step
also, includes ambiguous-command finder :)

CLI: independent merge step

---

lib/thread.c
ospfd/ospf_main.c
vtysh/vtysh.c
zebra/zserv.c

Few coverity fixes based on stable/2.0
(Fixed PR based on issue found by Renato in PR 187)

A few fixes for issues found with Coverity (v2 - replace PR 187)

---

bgpd/rfapi/rfapi_vty.c
lib/prefix.c
lib/prefix.h

Hello,
this is a proposal for 2 APIs to convert string mac address to internal representation, and the reverse way.
br

issue #142 / pull request to provide mac address stringification

---

ldpd/adjacency.c
ldpd/hello.c
ldpd/interface.c
ldpd/l2vpn.c
ldpd/lde.c
ldpd/lde.h
ldpd/lde_lib.c
ldpd/ldp_debug.c
ldpd/ldp_vty_conf.c
ldpd/ldpd.c
ldpd/ldpd.h
ldpd/ldpe.c
ldpd/ldpe.h
ldpd/neighbor.c

Pull these changes from master as they are required for Martin's topotest to work. Also, pull one other commit that fixes a segfault when configuring multiple pseudowires.

ldpd: display everything in order on CLI output

---

README
doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
doc/Building_FRR_on_Debian8.md
doc/Building_FRR_on_Fedora24.md
doc/Building_FRR_on_FreeBSD10.md
doc/Building_FRR_on_FreeBSD11.md
doc/Building_FRR_on_FreeBSD9.md
doc/Building_FRR_on_NetBSD6.md
doc/Building_FRR_on_NetBSD7.md
doc/Building_FRR_on_OmniOS.md
doc/Building_FRR_on_OpenBSD6.md
doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

Documentation Update only.
Added instructions on how to build FRR from source for various platforms (the ones used by the CI system).

doc: Add initial set of docs on building FRR on various Distributions

---

ospfd/.gitignore

ospfd: add *.a to .gitignore

---

bgpd/Makefile.am

bgpd: use tabs in Makefile.am

---

bgpd/bgp_evpn_vty.c

Fix the help strings to be correct.

bgpd: Fix help strings for new command

---

zebra/if_netlink.c
zebra/if_netlink.h
zebra/kernel_netlink.c
zebra/kernel_netlink.h
zebra/rt_netlink.c
zebra/rt_netlink.h

This is a rework of the multipath changes for V6 as suggested by Jafar

V6 multipath rework1

---

lib/thread.h

lib: remove unused quagga_clkid

---

doc/cli.md

Needs additions & modifications from @eqvinox prior to merge.
@eqvinox: for your additions, probably easiest for you to submit a PR against [my branch](https://github.com/qlyoung/frr/tree/cli-doc), which will update this pull request.
Alternatively we can just commit this and you can submit separate PR's for your changes.

doc: add CLI implementation documentation

---

bgpd/bgp_debug.c
bgpd/bgp_debug.h
bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
lib/log.c
lib/log.h

Implement draft-idr-bgp-shutdown, take 3

Shutdown take 3

---

isisd/isis_main.c
lib/log.h
ospfd/ospf_main.c
pimd/pim_main.c
pimd/pim_sock.c
watchfrr/watchfrr.c
zebra/main.c
zebra/test_main.c
zebra/zebra_vty.c

assorted bits

---

lib/command.c
lib/vty.c

vty completion memory counting redux

---

pimd/pim_nht.c

The interface api has change and the pim changes used
the old api.

pimd: Fix interface api

---

COMMUNITY.md
doc/git_branches.svg

This fell off my TODO list... had a note to update this from a tech call a month ago or so...

COMMUNITY.md: update CodingStyle & branching

---

bgpd/bgp_vty.c
bgpd/rfapi/bgp_rfapi_cfg.c
isisd/isisd.c
ldpd/Makefile.am
lib/distribute.c
lib/grammar_sandbox.c
lib/keychain.c
lib/ns.c
lib/routemap.c
lib/vrf.c
lib/vty.c
ospf6d/ospf6_top.c
ospfd/ospf_vty.c
ripd/ripd.c
ripngd/ripngd.c
vtysh/extract.pl.in
zebra/interface.c

fixes #125 by removing the entire ignore list
(the grammar sandbox change is unrelated but only 1 line, so i stuffed it in here)

CLI cleanups (remove ignore list)

---

Makefile.am
bgpd/bgpd.c
bgpd/bgpd.h
configure.ac
defaults.h
lib/command.c
lib/version.h.in
ospf6d/ospf6_top.c
ospfd/ospf_vty.c
ospfd/ospfd.c
tests/lib/cli/.gitignore
tests/lib/cli/test_cli.refout.in
vtysh/vtysh_config.c

track version & "defaults" in configs

---

doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
doc/Building_FRR_on_Debian8.md
doc/Building_FRR_on_Fedora24.md
doc/Building_FRR_on_FreeBSD10.md
doc/Building_FRR_on_FreeBSD11.md
doc/Building_FRR_on_FreeBSD9.md
doc/Building_FRR_on_NetBSD6.md
doc/Building_FRR_on_NetBSD7.md
doc/Building_FRR_on_OmniOS.md
doc/Building_FRR_on_OpenBSD6.md
doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

* Added libc-ares
* Added python-dev

doc: Update for the Building_FRR docs to include new requirements

---

doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
redhat/frr.spec.in

Fix some doc issues and Item 2 in #318

Fix a couple of centos related install issues

---

tools/frr-reload.py

Reviewed-by:   Donald Sharp <sharpd@cumulusnetworks.com>

tools: quagga-reload.py fails to change max-paths

---

doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

Signed-off-by: Phil Huang <phil_huang@edge-core.com>

Remove superfluous path and correct groupname

---

bgpd/bgpd.c

with our ASN
Reviewed-by:   Don Slice <dslice@cumulusnetworks.com>

bgpd: removing "allowas-in" for peer-group member still allows AS_PATHS

---

configure.ac
debian/changelog

*: Switchover to 3.1-dev

---

lib/zclient.c
ospfd/ospf_vty.c

Some Issues fixed

---

doc/Building_FRR_on_Debian8.md
doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

1. Fixed not found parameter when add group `frrvty`
2. Append `-p` for sysctl command

Fixed some document typo

---

lib/pqueue.c
lib/pqueue.h

lib: add removal by item to pqueue

---

doc/Building_FRR_on_Debian8.md
doc/Building_FRR_on_Fedora24.md
doc/Building_FRR_on_OpenBSD6.md
doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

Simple Building Doc fixes merged forward from 2.0 and nhrpd additions

Doc fixes from 2.0

---

vtysh/vtysh.c

Problem with DEFUNSH in vtysh, issue #358

---

ldpd/lde.c
ldpd/ldpe.c

ldpd: fix issues detected by Coverity Scan

---

doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md

1.  install init.d related files into system.

Update the docs of ubuntu 12.04/14.04

---

doc/Building_FRR_on_Ubuntu1604.md

Cherry-pick some changes from stable/2.0 so we stay consistent

Stable 2.0 fixes into stable 3.0

---

isisd/isis_mt.c

Fixes broken builds with -werror

isisd: fix uninitialized pointer

---

zebra/redistribute.c

Problem reported by a customer with prefix imported by rdnbrd not being
successfully installed in the quagga rib.  Determined that this was due
to VRR resolving the same arp entry, causing two entries to be installed
in table 10.  When these were imported into the quagga rib, they came in
as two different rib entries from the same table/instance, which is not
permitted and caused them to be deleted.
Added logic to zebra_add_import_table_entry to do the same actions as
rib_add and delete the older rib entry if a new rib entry is received
which matches.
Manual testing successful and automated tests for redistribute neighbor
have the same passes and failures as the base.
Ticket: CM-15926
Reviewed-by: CCR-6130

zebra: fix attempt to install a second rib from imported table entries

---

pimd/pim_cmd.c

Fix: Off by one error, correct index for hold timer

---

doc/Building_FRR_on_Ubuntu1604.md

Fix the build/install instructions for Ubuntu 16.04 and
systemd.

doc: Fix systemd build instructions

---

bgpd/bgp_route.h
bgpd/rfapi/rfapi_monitor.h
bgpd/rfapi/rfapi_rib.h

change `void *` to `struct thread *`

rfapi void * -> struct thread *

---

lib/thread.c

lib: abort if fd >= FD_SETSIZE and using select

---

pimd/pim_assert.c
pimd/pim_cmd.c
pimd/pim_iface.h
pimd/pim_join.c
pimd/pim_register.c

For all pim enabled interfaces and single pim enable interface command.
Clear command to clear protocol counters stats.
'show ip pim interface traffic {WORD} {json}'
'clear ip pim interface traffic'
Testing Done: bringup Pim configuration and form RPT and SPT and check
show ip pim interface traffic command output,
perform clear form of interface traffic command and
verified all counters reset via show form of command.
tor-21# show ip pim interface traffic swp2
Interface       HELLO            JOIN            PRUNE            REGISTER        REGISTER-STOP    ASSERT
Rx/Tx            Rx/Tx           Rx/Tx            Rx/Tx             Rx/Tx           Rx/Tx
---------------------------------------------------------------------------------------------------------------
swp2             22/22 …

pimd: Introduce show command for protocol counters

---

lib/command.c
tools/permutations.c

lib: fix 'list permutations'

---

lib/command.c
tools/permutations.c

lib: fix 'list permutations' (3.0)

---

bgpd/bgp_main.c

wonder what else is missing...

Pick up a couple of patches to master that are needed on 3.0

---

COMMUNITY.md

Give some guidance to people on where they should work for
bug fixese and features.

*: Modify documentation to show people where to work

---

bgpd/bgp_btoa.c
bgpd/bgpd.c
bgpd/rfapi/rfapi_rib.c
isisd/isis_pdu.c
lib/command.c
ospfd/ospf_flood.c
ospfd/ospf_te.c
ripd/ripd.c
ripngd/ripngd.c
tools/permutations.c
zebra/label_manager.c

Coverity fixes

---

configure.ac
vtysh/vtysh.c

*: Allow configure to control VTYSH_PAGER used

---

tools/.gitignore

tools: update .gitignore

---

lib/grammar_sandbox.c

lib: use %p specifier for pointers

---

bgpd/bgp_encap.c

Issue #198 - clean up duplicate command resulting from CLI refactoring

bgpd: Issue #198 - clean up duplicate encap SAFI commands

---

eigrpd/eigrp_const.h
eigrpd/eigrp_dump.c
eigrpd/eigrp_dump.h
eigrpd/eigrp_neighbor.c
eigrpd/eigrp_network.c
eigrpd/eigrp_topology.c
eigrpd/eigrp_update.c
eigrpd/eigrp_vty.c
eigrpd/eigrp_zebra.c
eigrpd/eigrpd.c
eigrpd/eigrpd.h
lib/command.c

Merged in a couple of patches that Renato forwarded to me.  The second one integrating took a decent amount of work so I added myself to the signed-off-by line.
this also fixes #497

Renato eigrp

---

bgpd/bgp_fsm.c
bgpd/bgp_vty.c
bgpd/bgpd.c
ospf6d/ospf6_lsa.c
ospfd/ospf_vty.c

Grab-bag of Commits that we've discovered that are missing from upstream.  Bug fixes so against 2.0

Missed 2.0

---

bgpd/bgp_vty.c
pimd/pim_vty.c
zebra/zebra_vty.c

Handle @rwestphal code changes for static_config consolidation.

Static config2

---

zebra/interface.c
zebra/zebra_rib.c
zebra/zebra_rnh.c

Three small zebra fixes present in cumulus codebase but missing from frr.

Small zebra fixes

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
zebra/redistribute.c
zebra/zebra_mpls_vty.c

A few bugs that I put in quagga that did not make it into frr

Missed bugs

---

bgpd/bgp_encap.c
bgpd/bgp_evpn_vty.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
bgpd/bgp_route.h

3.0 version, should also be merged to master

bgpd: fix config of v6 vpn networks tags 

---

pimd/pim_cmd.c

pimd: Fix crash from cli missinterpertation

---

nhrpd/linux.c

Signed-off-by: Timo Teräs <timo.teras@iki.fi>

nhrpd: configure mgre ipv6 nd for nhrp

---

vtysh/vtysh.c

vtysh: fix autocompletion API misuse

---

nhrpd/nhrp_vty.c

nhrpd: install access-list commands

---

eigrpd/eigrp_interface.c

eigrpd: Fix network statement

---

zebra/zserv.c

zebra: Fix 64 bit number printf issues

---

zebra/zserv.c

Prior to the fix, labels weren't getting installed in zebra nor were the
ifindex values correctly set if labeled-unicast was used in conjunction
with bgp unnumbered.
Ticket: CM-16531
Reviewed-by: CCR-6276

zebra: add bgp unnumbered labeled-unicast to zserv

---

bgpd/bgp_open.c
bgpd/bgp_open.h
eigrpd/eigrp_fsm.c
eigrpd/eigrp_interface.c
eigrpd/eigrp_network.c
eigrpd/eigrp_network.h
eigrpd/eigrp_topology.c
eigrpd/eigrp_update.c
eigrpd/eigrp_zebra.c
isisd/isis_pdu.c
isisd/iso_checksum.c
isisd/iso_checksum.h

May result in alignment errors on certain platforms, such as ARM & SPARC

*: do not take address of packed member

---

zebra/zebra_vty.c

zebra: one "show ip route" to rule them all

---

vtysh/Makefile.am

vtysh: Add back some missing bgp commands

---

configure.ac
lib/thread.c

* make write end nonblocking
* remove `--enable-poll`

poll() fixup

---

bgpd/bgp_route.c

bgpd: resolve IPv6 LL and Global nexthop issue

---

zebra/zebra_mpls.c
zebra/zebra_mpls.h
zebra/zebra_mpls_vty.c
zebra/zebra_vty.c

zebra: more informative error messages & help strings for mpls labels

---

ldpd/lde_lib.c
ldpd/ldp_vty_conf.c
ldpd/ldpd.c
ldpd/ldpd.h

This is for master.. I'll open a separate PR for stable/3.0 later with be0fbdebca3dbb9266a5196d88f504141ea44b0f and a few other fixes.

Ldpd fixes/cleanup

---

ospfd/ospf_vty.c

Fix ospf timers

---

redhat/README.rpm_build.md
redhat/daemons
redhat/frr.init
redhat/frr.logrotate
redhat/frr.spec.in

Fix for merge errors from stable/2.0 RPM package
- Does not (yet) support any of the changes to shared init/config files between debian and rpm. These will be addressed in separate commit
- Adds EIGRPd and NHRPd
(A separate PR for stable/3.0 to bring it at the same level - except EIGRP - will follow).

Rpm merge fix

---

bgpd/bgp_debug.c
bgpd/bgp_route.c
bgpd/bgp_updgrp_packet.c
bgpd/bgp_vty.c
ospf6d/ospf6_area.c
ospfd/ospf_vty.c

Mostly my stuff and a commit from Renato
PRs:
#662 #661 #660 #659 #646 #632

Misc fixes → 3.0

---

zebra/interface.c
zebra/misc_null.c
zebra/zserv.c

Signed-off-by: Alex Couloumbis <alex@ozo.com>

zebra: Fix --disable-rtadv to actually compile

---

bgpd/rfapi/bgp_rfapi_cfg.c

bgpd: Fix missing newline

---

lib/route_types.txt
zebra/rib.h
zebra/zebra_rib.c

zebra: Fix the metaq to be aware of all routing protocols we could see

---

bgpd/bgp_vty.c

bgpd: fix memleak with 'show ip bgp vrf ...'

---

bgpd/bgp_updgrp_packet.c
eigrpd/eigrp_dump.c
eigrpd/eigrp_hello.c
eigrpd/eigrp_interface.c
eigrpd/eigrp_packet.c
eigrpd/eigrp_query.c
zebra/rt_netlink.c
zebra/zebra_vty.c

Fix a bunch of Coverity Issues.

Coverity high

---

zebra/zebra_rib.c

Thinking about nexthops and recursive resolution led me down this path.  I want to start testing this code to see if there are any issues while I think about the next step

Nexthop smushinating

---

isisd/isis_adjacency.c
ospf6d/ospf6_intra.c
ospfd/ospf_spf.c
ripngd/ripngd.c
zebra/zserv.c

#666 
#667 
#668 
#669 
#671 
@mwinter-osr please run your compliance tests again before we merge this
I would like review on all of these, especially the ISIS and zebra fixes.

Fix miscellaneous memory errors

---

lib/routemap.c

lib: "show route-map" is missing from the parser

---

bgpd/rfapi/rfapi_import.c

bgpd: Fix arm warn -> werror issue

---

pimd/pim_nht.c

To Address ICC (intel CC) warning, moving variables
declaration out of switch statement.

pimd: move variable declartion outside of switch

---

zebra/irdp_interface.c
zebra/irdp_main.c

Fix zebra div by zero

---

ldpd/adjacency.c
ldpd/interface.c
ldpd/l2vpn.c
ldpd/lde.c
ldpd/lde_lib.c
ldpd/ldp_vty_conf.c
ldpd/ldpd.c
ldpd/ldpe.c
ldpd/ldpe.h
ldpd/neighbor.c
lib/Makefile.am
lib/ns.c
lib/openbsd-tree.c
lib/openbsd-tree.h
lib/vrf.c
lib/zebra.h
zebra/zebra_rib.c

This PR aims to fix the clang warnings ( #404 ) and at the same time improve the RB tree code used in FRR.
More details about the changes can be found at the commit messages.

RB tree improvement

---

lib/termtable.c

lib: termtable coverity warnings

---

bgpd/bgp_route.c
bgpd/bgp_table.c
bgpd/bgp_table.h

bgpd: Remove unset table.owner

---

lib/json.c

lib: look at the correct token for json

---

ldpd/adjacency.c
ldpd/hello.c

Handling configuration changes from single-stack mode to dual-stack mode
(and vice-versa) is tricky. This patch attempts to solve all issues that
might happen on such circumstances.

ldpd: fix issues with dual-stack adjacencies

---

vtysh/vtysh.c

need 'do' to force ENABLE_NODE

vtysh: fix various show commands

---

isisd/isis_lsp.c
isisd/isis_redist.c
isisd/isis_zebra.c
isisd/isis_zebra.h

This addresses the issues observed in #729

Isis redist fixes

---

lib/routemap.c
ospfd/ospf_routemap.c

🌮 
broken stuff, see commit messages

Fix routemap

---

bgpd/.gitignore
lib/.gitignore

lib, bgpd: fix .gitignore

---

ospfd/ospf_vty.c

Two things:
1) Some advanced 'show ip ospf database'... code
was not working properly.  Fix the cli to handle
this appropriately
2) Consolidate two cli functions into one.
Signed-off-by: Donald Sharp <sharpd@cumulusnetworkscom>

ospfd: Fix 'advanced' type data base show

---

doc/Building_FRR_on_Ubuntu1204.md
doc/Building_FRR_on_Ubuntu1404.md
doc/Building_FRR_on_Ubuntu1604.md

doc: update build docs for ubuntu

---

babeld/babeld.c
bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/rfapi/bgp_rfapi_cfg.c
bgpd/rfapi/rfapi_vty.c
isisd/isis_vty.c
lib/agentx.c
lib/command.c
lib/command_parse.y
lib/plist.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_top.c
ospfd/ospf_vty.c
pimd/pim_cmd.c
ripd/rip_interface.c
vtysh/vtysh.c
zebra/zebra_vty.c

Fix excess docstring

---

bgpd/bgp_main.c
bgpd/bgp_zebra.c
bgpd/bgp_zebra.h

Refactor some code in handling announcement of routes into zebra

Bgp buffer

---

tests/helpers/c/prng.c
tests/helpers/c/prng.h
tests/lib/test_srcdest_table.c

tests: update prng to return better pseudo random numbers

---

lib/nexthop.c
lib/nexthop.h
tests/lib/test_nexthop_iter.c
zebra/redistribute.c
zebra/rib.h
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/zebra_fpm_netlink.c
zebra/zebra_fpm_protobuf.c
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_vty.c

Before, only one level of recursive resolution was supported.
Signed-off-by: ßingen <bingen@voltanet.io>

Allow for more than 1 NH recursion level

---

doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
doc/Building_FRR_on_Fedora24.md
redhat/daemons

Adding missing pimd to redhat daemon config and fixing doc
Fixes issue https://github.com/FRRouting/frr/issues/782 for stable/2.0

Redhat doc fixes for stable/2.0

---

doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
doc/Building_FRR_on_Fedora24.md
redhat/daemons

Adding missing pimd to redhat daemon config and fixing doc
Fixes issue https://github.com/FRRouting/frr/issues/782 for stable/3.0

Redhat doc fixes for stable/3.0

---

doc/Building_FRR_on_CentOS6.md
doc/Building_FRR_on_CentOS7.md
doc/Building_FRR_on_Fedora24.md
redhat/daemons
redhat/frr.init

Adding missing pimd to redhat daemon config
Adding missing babeld to redhat daemon config and init script
Fixing Building Doc 
Fixes issue https://github.com/FRRouting/frr/issues/782 for master branch

Redhat doc fixes for master branch

---

bgpd/bgp_aspath.c
bgpd/bgp_fsm.c
bgpd/bgp_main.c
bgpd/bgp_route.c
lib/command_graph.c
lib/command_match.c
lib/jhash.c
lib/workqueue.c
nhrpd/Makefile.am
nhrpd/nhrp_packet.c
nhrpd/nhrp_peer.c
nhrpd/nhrp_vty.c
ospf6d/ospf6_message.c
ospf6d/ospf6_route.c
ospf6d/ospf6_snmp.c
ospfd/ospf_interface.c
ospfd/ospf_nsm.c
ospfd/ospf_packet.c

(as pointed out by @cfra, GCC 7 is out and has some new warnings)

fix new warnings emitted by GCC 7

---

eigrpd/eigrp_vty.c

eigrpd: remove last vty_outln

---

ospf6d/ospf6_lsdb.c

ospf6d: crash in ospf6_lsdb_show

---

zebra/debug.c

zebra: "debug zebra packet" config display

---

ripd/rip_debug.c
ripngd/ripng_debug.c

Cmd success

---

lib/imsg-buffer.c
lib/imsg.c
lib/imsg.h
lib/openbsd-tree.c
lib/openbsd-tree.h

Fix corrupted RB trees

---

bgpd/bgp_updgrp_packet.c

bgpd: UPDATE may be larger than 4096 if addpath is used

---

bgpd/bgp_vty.c
bgpd/bgpd.c

bgpd: attribute-unchanged issues with peer-groups

---

lib/thread.c
lib/thread.h

lib: flush ready queue before poll() again

---

lib/thread.c

lib: minor style fix

---

configure.ac
lib/zebra.h

This patch addresses build issues on OpenBSD and Android

Portability configurations

---

bgpd/bgp_open.c

bgpd: Fix safi_t confusion wition iana_safi_t

---

nhrpd/nhrp_cache.c
nhrpd/nhrp_main.c
nhrpd/nhrp_route.c
watchfrr/watchfrr.c
zebra/kernel_netlink.c
zebra/rt_netlink.c
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_routemap.c
zebra/zebra_vty.c

Several fixes from my testing of NHRP and kernel routes

Assorted fixes

---

lib/vty.c

Since we were only setting vty->wfd in config_write, vty->fd would
remain 0 and vty_close() wouldn't close vty->wfd.
Clean up the entire fd closing and make it more explicit.  We were even
trying to write to stdin...
[master commit: 10b8a9c]
Reported-by: Jorge Boncompte <jbonor@gmail.com>

[3.0] lib: vty: fix config-write fd leak

---

eigrpd/eigrp_dump.c
eigrpd/eigrp_packet.c
eigrpd/eigrp_update.c

Fix some various EIGRP issues that have been sitting on my back burner.  The third patch `Fix crash and attempt to send data...` apparently fixes some issues for people.  I know that it still has issues, but we stop crashing and apparently fixes some real issues that people are having

Eigrp various

---

pimd/pim_cmd.c

pimd: some pim cli fixes

---

zebra/interface.c
zebra/zebra_static.c
zebra/zebra_static.h
zebra/zebra_vrf.c
zebra/zebra_vrf.h
zebra/zebra_vty.c

[3.0] fixup static routes' ifindexes when interfaces (dis)appear

---

lib/thread.c

lib: fix still reachable linked list in thread.c

---

.gitignore
bgpd/rfapi/.gitignore
tests/.gitignore

*: ignore .dirstamp

---

.dir-locals.el

Sets tab for c-mode.
Alternative to PR #931

Initial take on project emacs variables file and settings. 

---

doc/cli.md
lib/command_graph.c
lib/command_graph.h
lib/command_lex.l
lib/command_match.c
lib/command_parse.y
lib/command_py.c
lib/grammar_sandbox.c
python/clidef.py

lib: add CLI token for 48-bit mac addresses

---

doc/Building_FRR_for_LEDE-OpenWRT.md

build instructions for working stable 3.0 version
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

doc: add LEDE/OpenWRT build instructions

---

ospfd/ospf_vty.c

ospfd: "show ip ospf neighbor" options not passed

---

eigrpd/eigrp_query.c
eigrpd/eigrp_update.c

Fixed issue with eigrp crashing when an external is received by discarding the TLV. Work must be done to handle tlv processing and changes needed to FSM so it understands an external should not be chooses if an internal exist.

Fixed issue with eigrp crashing when an external is received

---

bgpd/bgp_route.c
bgpd/bgp_table.h
bgpd/bgpd.c
bgpd/bgpd.h
bgpd/rfapi/rfapi_import.c
eigrpd/eigrp_packet.c
ldpd/control.h
ldpd/lde.h
ldpd/ldpd.h
ldpd/ldpe.h
lib/freebsd-queue.h
lib/imsg-buffer.c
lib/imsg.c
lib/prefix.c
lib/prefix.h
lib/queue.h
lib/subdir.am
lib/table.c
lib/table.h
lib/workqueue.c
lib/workqueue.h
ospfd/ospf_packet.c
zebra/zebra_rib.c
zebra/zebra_static.c

General optimizations like reduction of function calls and memory allocations for code paths that get called for every prefix with full IPv4 BGP tables.

Optimization

---

ospf6d/ospf6_interface.c

ospf6d: add `no` forms for interface commands

---

Makefile.am
bgpd/bgp_main.c
bgpd/bgp_route.c
common.am
git-reindent-branch.py
lib/command.c
lib/compiler.h
lib/grammar_sandbox.c
lib/libfrr.c
lib/libfrr.h
lib/log.c
lib/memory.c
lib/memory.h
lib/plist.c
lib/plist.h
lib/prefix.c
lib/prefix.h
lib/sigevent.c
lib/subdir.am
lib/vty.h
ospf6d/ospf6_abr.c
ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6d.c
python/clidef.py
python/clippy/__init__.py
tests/isisd/test_fuzz_isis_tlv.c
tests/lib/cli/common_cli.c
zebra/zebra_fpm.c

Fixes: #991
Fixes: #971
Fixes: #543 
Fixes: #453
Fixes: #437 
Fixes: #319

small bits

---

lib/zclient.c
lib/zclient.h
zebra/zserv.c

zebra: Fix compiler warnings

---

eigrpd/eigrp_dump.c
eigrpd/eigrp_fsm.c
eigrpd/eigrp_fsm.h
eigrpd/eigrp_interface.c
eigrpd/eigrp_neighbor.c
eigrpd/eigrp_neighbor.h
eigrpd/eigrp_network.c
eigrpd/eigrp_network.h
eigrpd/eigrp_packet.c
eigrpd/eigrp_packet.h
eigrpd/eigrp_query.c
eigrpd/eigrp_reply.c
eigrpd/eigrp_siaquery.c
eigrpd/eigrp_siareply.c
eigrpd/eigrp_structs.h
eigrpd/eigrp_topology.c
eigrpd/eigrp_topology.h
eigrpd/eigrp_update.c
eigrpd/eigrp_vty.c
eigrpd/eigrp_zebra.c
eigrpd/eigrp_zebra.h

1) Start handling of Split Horizon
2) Cleanup some memory leaks
3) Improve external route comparison( for the future )
4) Improve route handling when we receive a connected route that takes over a INTERNAL
5) Refactor a bunch of code from 'struct prefix_ipv4' to 'struct prefix'

Eigrp split horizon

---

python/clidef.py

Coverity is generating a lot of warnings about unused stuff being
around.  Disabling these bits is most easily done by just putting a few
preprocessor directives into the template.

clippy: disable unneeded autogenerated code

---

ospf6d/ospf6_top.c
ospfd/ospf_vty.c

no ospf6 router-id

---

babeld/kernel.c
bgpd/bgp_zebra.c
lib/nexthop.c
lib/nexthop.h
lib/zclient.c
lib/zclient.h
lib/zebra.h
nhrpd/nhrp_route.c
ospf6d/ospf6_zebra.c
ospfd/ospf_zebra.c
zebra/connected.c
zebra/kernel_socket.c
zebra/kernel_socket.h
zebra/redistribute.c
zebra/rib.h
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/rtread_getmsg.c
zebra/zebra_fpm_netlink.c
zebra/zebra_fpm_protobuf.c
zebra/zebra_rib.c
zebra/zebra_static.c
zebra/zebra_static.h
zebra/zebra_vty.c
zebra/zserv.c

2010 was a good year for patches...

zebra: clean up blackhole support

---

isisd/isis_lsp.c

isisd: keep original TLVs when purging in response to confusion

---

babeld/babel_interface.c
bgpd/bgp_evpn_vty.c
bgpd/bgp_evpn_vty.h
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_vty.c
bgpd/bgp_vty.h
bgpd/bgp_zebra.h
bgpd/bgpd.c
bgpd/bgpd.h
configure.ac
debian/frr.install
doc/Makefile.am
doc/frr-args.8.in
eigrpd/eigrp_vty.c
isisd/isis_circuit.c
lib/libfrr.c
lib/libfrr.h
lib/vty.c
lib/vty.h
nhrpd/nhrp_vty.c
ospf6d/ospf6_interface.c
ospfd/ospf_vty.c
pimd/pim_vty.c
ripd/rip_interface.c
ripngd/ripng_interface.c
vtysh/vtysh.c
vtysh/vtysh.h
vtysh/vtysh_main.c
zebra/interface.c

2010 says hello and sends patches...

"pathspace" options, vtysh-suid-cleanups, "vty_frame()"

---

doc/Makefile.am
doc/bgpd.texi
doc/main.texi
lib/sockunion.h
zebra/connected.c
zebra/connected.h
zebra/if_ioctl.c
zebra/if_ioctl_solaris.c
zebra/if_netlink.c
zebra/interface.c
zebra/interface.h
zebra/ioctl.c
zebra/kernel_socket.c

2010 says hi again and is sending more patches.

zebra: PtP address configuration support

---

pimd/pim_upstream.c
pimd/pim_vty.c
pimd/test_igmpv3_join.c

1) Noticed a bit of a missed patch, fixed
2) vty_frame was not being used properly in pim
3) Cleanup a whitespace issue found in pim

Cleanup some issues in pim

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_private.h
bgpd/bgp_evpn_vty.c
bgpd/bgp_nexthop.c
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_vty.c
bgpd/bgpd.c
lib/command.c
lib/vty.c
lib/zclient.h
ospf6d/ospf6_top.c
vtysh/vtysh_main.c
zebra/connected.c
zebra/if_netlink.c
zebra/interface.c
zebra/kernel_socket.c
zebra/redistribute.c
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/zebra_rib.c
zebra/zebra_static.c
zebra/zebra_vty.c
zebra/zebra_vxlan.c
zebra/zserv.c

Fixes style nits introduced by recent pull requests.

*: fix style

---

isisd/isis_spf.c

isisd: cleanup output of show isis topology

---

bgpd/bgp_clist.c
bgpd/bgp_lcommunity.c
bgpd/bgp_routemap.c
vtysh/vtysh_config.c

Critical fixes for large community support in 3.0-stable

Large community fixes (critical)

---

bgpd/bgp_attr.c
bgpd/bgp_clist.c
bgpd/bgp_lcommunity.c
bgpd/bgp_lcommunity.h
bgpd/bgp_routemap.c

This PR  contains the critical fixes for large community support submitted to 3.0-stable and a few misc cleanups

Large community critical fixes and misc cleanups

---

zebra/rib.h
zebra/rt_netlink.c
zebra/zebra_rib.c
zebra/zebra_vty.c

Fixes issues discussed on the #zebra channel today.

RIB issues

---

bgpd/rfapi/bgp_rfapi_cfg.c

bgpd rfapi: fixup vnc l2_group config

---

isisd/isis_redist.c
lib/prefix.h
zebra/redistribute.c
zebra/redistribute.h

1) Clean up some indentation
2) fix is_default differences across code base
3) Let import tables work with v6 routes.

Zebra import

---

isisd/isis_circuit.c
isisd/isis_circuit.h
isisd/isis_vty.c
lib/ferr.c
lib/ferr.h
lib/subdir.am

This adds extended error reporting + an example of how it's used in isisd.
This PR is for feedback purposes for now, input on the general idea / design appreciated!

"ferr" error reporting extensions

---

eigrpd/eigrp_query.c
eigrpd/eigrp_reply.c
eigrpd/eigrp_routemap.c

I'm not sure how this was missed or why master
is not failing to compile.

eigrp: Fix missing neighbor->nexthop changes?

---

bgpd/bgpd.c
eigrpd/eigrp_packet.c
pimd/pim_instance.c
zebra/rt_netlink.c
zebra/zebra_rib.c

1) Fix for #1061 -> routes from zebra still installed on startup fix to allow deletion of them
2) Add vty_frame for pim vrf ( pim should never create vrf's implicitly )
3) Clean up some eigrp coverity issues
4) Clean up a memory leak in bgp

Grab bag of issues

---

vtysh/vtysh_main.c

vtysh: fix pathspace

---

doc/Building_FRR_on_Ubuntu1604.md

Cherry-picked from merged PR #1126 in stable/3.0

Typos and formatting

---

tools/frr-reload.py

tools: frr-reload.py support for vni under 'address-family l2vpn evpn'

---

lib/thread.c

lib: free thread master name

---

doc/bgpd.texi

Closes #1140
Signed-off-by: Nigel Kukard <nkukard@lbsd.net>

docs: Added large-community documentation

---

bgpd/bgp_attr_evpn.c
bgpd/bgp_clist.c
bgpd/bgp_ecommunity.c
bgpd/bgp_encap_tlv.c
bgpd/bgp_evpn_vty.c
bgpd/bgp_lcommunity.c
bgpd/bgp_rd.c
bgpd/rfapi/rfapi_import.c
lib/skiplist.c
lib/stream.c
lib/stream.h
ospfd/ospf_opaque.h

*: fix be32 reading / 24-bit left shift

---

bgpd/bgp_ecommunity.c
bgpd/bgp_ecommunity.h
bgpd/bgp_evpn_vty.c

bgpd: deduplicate struct definition

---

lib/command.c

lib: Add json support for 'show version' command

---

pimd/pim_ifchannel.c

If you read the extra fine print of the PIM RFC
it asks you to stop the PP Timer and the
Expiry Timer when you are certain S,G RPT states.
This commit puts this into practice and it also
deletes the S,G ifchannel if necessary.
Signed-off-by: Donald Sharp <sharpd@cumulusnetworks.com.

pimd: More S,G RPT prune state missinformation

---

bgpd/bgp_zebra.c

The previous code assumed that all nexthops of an ECMP route were of
the same address-family. This is not always the case.
Reported-by: Don Slice <dslice@cumulusnetworks.com>

bgpd: fix sending of ECMP routes with both v4/v6 nexthops to zebra

---

bgpd/bgp_route.c

Add the ability to display large commnunity json support
Fixes: 1191

bgpd: Add large community json support

---

doc/bgpd.texi

Clarified the use of show bgp ipX instead of show ip bgp.
Moved AS Path regular expressions one level up to BGP regular expressions and added references to it.
Cleaned up a few English language issues.
Cleaned up the bgp show section and clarified a few items which had no definitions.

doc: updates for master, cherry-picked from my 3.0 branch

---

isisd/isis_lsp.c

Standard IS-IS only supports up to 256 fragments per router. Recognize
when the information we want to advertise exceeds 256 fragments and
print a warning in this case instead of overflowing the fragment counter
and overwriting existing LSP fragments.

isisd: Don't corrupt generated LSPs if information exceeds capacity

---

isisd/isis_spf.c
tests/.gitignore
tests/Makefile.am
tests/isisd/test_isis_vertex_queue.c
tests/isisd/test_isis_vertex_queue.py

Speed isisd's SPF up by using some more suitable datastructures and removing ununsed ones.

isisd: spf improvements

---

isisd/isis_lsp.c
isisd/isis_route.c
isisd/isis_spf.c

This pull request addresses some bugs which surfaced recently while testing isisd in various configurations.

Isisd: assorted fixes

---

pimd/pim_cmd.c

When displaying the mroute table, add ability to fill
in all the missing data that for human eyes can be assumed.
This will allow people using grep over the command
can get more information.
```
sharpd@robot ~> sudo vtysh -c "show ip mroute fill"
Source          Group           Proto  Input      Output     TTL  Uptime
*               229.1.1.1       STATIC dum0       enp3s0     1    00:11:07 Default-IP-Routing-Table
*               229.1.1.1       STATIC dum0       virbr0     1    00:01:47 Default-IP-Routing-Table
sharpd@robot ~>
```

pimd: Add 'show ip mroute fill' command

---

tools/frr-reload.py

tools: frr-reload.py should exit(1) if vtysh config mode is locked

---

babeld/babel_main.c
babeld/neighbour.c
bgpd/bgp_route.c
lib/sha256.c
lib/zclient.c
ospfd/ospf_packet.c
ospfd/ospf_vty.c
pimd/pim_nht.c
zebra/zebra_rnh.c

Fix  scan-build/clang warnings.
It does not add, neither remove any features.

Cleanup - scan-build

---

ospfd/ospf_lsa.c

maxage_lsa using prefix structure to store in route_table.
The lsa pointer is 4-8 bytes depending on arch, but prefix member field
would be 1 byte. Use ptr field of prefix structure to store lsa pointer.
Also memset to initialize to avoid crash on ARM platform as same LSA is
referenced from multiple times during shutdown of ospf.

ospfd: Fix maxage_lsa lookup key

---

lib/sha256.c

lib: Fix memset usage

---

isisd/isis_adjacency.c
isisd/isis_circuit.c
isisd/isis_circuit.h
isisd/isis_constants.h
isisd/isis_lsp.c
isisd/isis_lsp_hash.c
isisd/isis_lsp_hash.h
isisd/isis_pdu.c
isisd/subdir.am

isisd: optimize per interface lsp send-queue creation

---

ldpd/address.c
ldpd/interface.c
ldpd/labelmapping.c
ldpd/lde.c
ldpd/lde_lib.c
ldpd/ldpd.c
ldpd/ldpe.c

While here, fix the other SA warnings.

ldpd: sprinkle in some asserts to make scan-build happy

---

bgpd/bgp_filter.c
bgpd/bgp_label.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_monitor.c
eigrpd/eigrp_filter.c
eigrpd/eigrp_packet.c
isisd/isis_te.c
ldpd/address.c
lib/ptm_lib.c
ospf6d/ospf6_abr.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_intra.c
ospf6d/ospf6_lsa.c
ospf6d/ospf6_lsa.h
ospfd/ospf_apiserver.c
ospfd/ospf_dump.c
ripngd/ripngd.c
vtysh/vtysh_main.c
zebra/rt_netlink.c

This pull request voids  #1294 
I do not want to get it squashed because some fixes could be backported and because some specific comments about the analysis should remain.

Fix many clang warning

---

lib/csv.c

Fix csv unit tests.
To be run using,
gcc -o csv csv.c -DTEST_CSV
./csv
Signed-off-by: Vincent Jardin <vincent.jardin@6wind.com>

lib: csv unit tests

---

zebra/redistribute.c

Problem reported when a table entry originated by rdnbrd was moved from one
interface to another on the same switch.  Both would be deleted, leaving
no imported entry in the table.  Modified zebra_add_import_table_entry to
used rib_add_multipath as well as correct the call to delete a duplicate
entry to include the nexthop associated with the route_entry.
Ticket: CM-18154
Reviewed By: CCR-6731
Testing Done: Manual testing successful, deb given to submitter, bgp-smoke
had no new failures

zebra: resolve issue with importing table entries correctly

---

bgpd/bgp_zebra.c

Problem reported with the log displaying error messages if bgpd was
enabled in /etc/frr/daemons but bgp wasn't actually configured.  The
problem was due to operating on interfaces before if_create had been
called (which happens at "router bgp" not at frr starting.)  Moved the
checks for the bgp instance before operating on interfaces.  Manual
testing successful and bgp-smoke completed with no new issues.
Ticket: CM-13504
Reviewed-by: CCR-6738

bgpd: check for bgp instance before processing interfaces

---

ldpd/lde.c
ldpd/ldpe.c
ldpd/packet.c

ldpd: fix heap-use-after-free at exit

---

isisd/isis_pdu.c
lib/command.h
lib/csv.c
ospfd/ospf_network.c
ospfd/ospf_ri.c
ospfd/ospf_te.c
ospfd/ospf_zebra.c
pimd/pim_cmd.c

Fix up a bunch of `HIGH` issues from coverity scan

High stuff

---

ospfd/ospf_lsa.c
ospfd/ospf_vty.c

Add vrf_name in both vtysh and json format of show commands.

ospfd: OSPFv2 VRF, add vrf_name in show command output

---

ospfd/ospfd.c

list_delete_and_null should be used.

ospfd: Fix ships in the night PR's and list_delete

---

configure.ac
doc/install.texi

configure: Have --enable-dev turn on better debugging.

---

lib/workqueue.c

When free'ing the workqueue if you have items
on the workqueue you should free the memory associated
with it.

lib: Free workqueue memory leak on free

---

bgpd/bgp_vty.c

When retrieving information about neighbors or summary in json
add some information about what bestPath particulars we have for
this bgp session.

bgpd: Add ability to display information about bestpath in json

---

COMMUNITY.md

doc: add docs for commit message format

---

bgpd/bgpd.c

If we are configuring a peer in multiple address families
and assigning the peer group valid configuration.  If you
delay the non-automatically address family activation you
will not copy the peer group data into that peer.
Suppose we enter this:
bgp router-id 6.0.0.17
neighbor ISL peer-group
neighbor ISL advertisement-interval 0
neighbor ISL timers connect 5
neighbor ISL timers 3 10
neighbor ISL allowas-in 1
neighbor swp31s0 interface
neighbor swp31s0 peer-group ISL
address-family ipv6 unicast
neighbor ISL allowas-in 1
We've assigned allowas-in to the ISL peer group.  Now suppose
we have a peer start connection to swp31s0.  We startup and
auto copy the v4 peer group information onto the peer.  We
do not copy the v6 peer group information …

bgpd: Fix peer group copying of data for late activation

---

zebra/zebra_fpm.c

As discussed in #1343, this removes the previous limitation of only sending the main unicast table to FPM.

Send all routes to FPM, including VRF and multicast

---

redhat/daemons
redhat/frr.spec.in

RPM Package fixes for stable/2.0

Rpm fix 2.0

---

redhat/README.rpm_build.md
redhat/daemons
redhat/frr.spec.in

RPM Package fixes for stable/3.0

Rpm fix 3.0

---

redhat/README.rpm_build.md
redhat/daemons
redhat/frr.spec.in

Rpm fix master

---

zebra/rt_netlink.c

Problem reported with not deleting LSPs from the zebra kernal mpls table
when a delete occurred in bgp.  Found that we were exiting the delete
process incorrectly due to not being able to derive the route_type from
the best_nhlre on the lsp while deleting. Since this info was only
needed for route installation, removed this early exit in the case of
deleting the lsp.
Ticket: CM-18309
Reviewed By: CCR-6781
Testing Done:  Manual testing looks good.  mpls tests successful

zebra: only pass mpls proto type if doing install

---

bgpd/bgp_main.c

bgpd: cherry-pick -S fix from master

---

bgpd/bgp_route.c

Cleanup the displayed json output to be a bit prettier
to look at.

bgpd: Cleanup some json output in bgp_route.c

---

eigrpd/eigrp_const.h
eigrpd/eigrp_packet.c
eigrpd/eigrp_query.c
eigrpd/eigrp_update.c

I believe this addresses concerns in #1364

Eigrp crashes

---

lib/routemap.c

lib: Fix nexthop reading to work better

---

zebra/if_netlink.c

The linux kernel passes the IFLA_IFALIAS value.  Allow
zebra to read and set the description appropriately.
Currently I don't set the value down into the kernel.

zebra: Allow IFLA_IFALIAS to set ifp->desc

---

bgpd/bgp_attr.c

A crafted BGP UPDATE with a malformed path attribute length field causes
bgpd to dump up to 65535 bytes of application memory and send it as the
data field in a BGP NOTIFY message, which is truncated to 4075 bytes
after accounting for protocol headers. After reading a malformed length
field, a NOTIFY is generated that is supposed to contain the problematic
data, but the malformed length field is inadvertently used to compute
how much data we send.
CVE-2017-15865

bgpd: fix mishandled attribute length

---

redhat/daemons

redhat: Fix redhat startup to actually read in unified config

---

lib/plist.c

When we have a v4 or v6 prefix list, only
apply it via a match when the address families
are the same.
Fixes: #1339

lib: Only apply prefix's to the same family

---

lib/command.c

This is a fix for Issue  #1412

lib: Fix command `copy running-config startup-config` to alias `write file`

---

COMMUNITY.md

Signed-off-by: Mladen Sablic <mladen.sablic@gmail.com>

frr: COMMUNITY.md updated link to to kernel.org

---

isisd/isisd.c

isisd: Add a missing newline to a help string

---

zebra/zebra_rib.c
zebra/zebra_vty.c

Found a couple of issues from code inspection.

Zebra multicast

---

bgpd/bgp_advertise.c
bgpd/bgp_fsm.c
bgpd/bgp_open.c
bgpd/bgp_packet.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
bgpd/bgp_vty.c
bgpd/bgpd.c

Improves consistency and readability.

bgpd: use FOREACH_AFI_SAFI where possible

---

zebra/rt_netlink.c

The v6 linux kernel netlink code doees not have
route replace semantics.  So if we are in that
situation, do a delete/add to get the correct
results.
Fixes: #1461

zebra: V6 does not have route replace semantics

---

bgpd/bgp_vty.c

Fixes a bug whereby all peer-groups would be shown even when a
particular peer-group was specified for display.
Also fixes error message for unknown peer-group name that was never displayed.
Fixes #1378 

bgpd: fix `show bgp peer-group NAME`

---

lib/command.c

[3.0] lib: remove invalid assert

---

bgpd/bgp_rpki.c
bgpd/bgp_vty.c
doc/cli.md
ldpd/subdir.am
lib/plist.c
ospfd/ospf_vty.c
sharpd/sharp_vty.c

*: make clippy usage more consistent

---

babeld/babeld.c
babeld/kernel.c
babeld/kernel.h
bgpd/bgp_routemap.c
bgpd/bgpd.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_rib.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_import_bgp.c
watchfrr/watchfrr.c
zebra/ipforward_proc.c

Cleanup a bunch of SA warnings and issues found

Cleanup a bunch of code

---

ospf6d/ospf6_route.c

Fix sorting of route storage to DB.
Fix two list comparison which allows route with
multiple nexthop to updates.
Ticket:CM-19025
Testing Done:
Configured a topology where ospf6 learn
ecmp route via one neighbor and upon removal
of intra-prefix route from origin, DUT removes
ECMP intra-prefix route from RIB.

ospf6d: Fix multi nexthop route remove

---

lib/frr_zmq.c
lib/frr_zmq.h
tests/lib/test_zmq.c
tests/lib/test_zmq.refout

Add write callback.
Add error callback.
Add frrzmq_check_events() function to check for edge triggered things
that may have happened after a zmq_send() call or so.
Update ZMQ tests.
Signed-off-by: ßingen <bingen@voltanet.io>

lib: Address ZMQ lib TODOs

---

pimd/pim_ifchannel.c

When we receive a S,G rpt prune message for a mroute,
really, absolutely, guarantee the send upstream immediately.

pimd: Really, Actually send S,G rpt prune upstream

---

configure.ac
doc/Makefile.am
doc/install.texi
doc/pimd.texi
doc/routemap.texi
zebra/connected.c
zebra/kernel_socket.c
zebra/rib.h
zebra/rt_netlink.c
zebra/rtread_getmsg.c
zebra/zebra_rib.c
zebra/zebra_vty.c

Can we say orthogonal?  I was stuck on a plane so I worked on the pim documentation that was needed.  Just put it with this stuff

Add Linux Realms and some Pim Documentation

---

configure.ac
isisd/dict.h
lib/md5.c
lib/md5.h
lib/zassert.h
ospfd/OSPF-ALIGNMENT.txt
pkgsrc/README.txt
ripd/ripd.conf.sample
ripngd/ripngd.conf.sample
tests/helpers/c/main.c
tests/lib/test_heavy.c
tests/lib/test_heavy_thread.c
tests/lib/test_privs.c
zebra/ipforward_sysctl.c
zebra/rib.h
zebra/zebra.conf.sample
zebra/zebra_fpm.c
zebra/zebra_rib.c
zebra/zebra_static.c
zebra/zebra_vty.c

1) Store the selected_fib as a pointer off of the rib_dest_t.
2) Cleanup some code associated with KAME

Store selected_fib as a pointer off of rib_dest_t

---

isisd/isis_bpf.c

This PR fixes the following issue: https://github.com/FRRouting/frr/issues/1562
This reverts commit d9e5b009554f99230be1eee62daf098403c3cadf.
`ETH_ALEN` is not equivalent to `ETHER_HDR_LEN`. `ETHER_HDR_LEN` is the definition for the length of the full ethernet header, meanwhile `ETH_ALEN` is just the length of the ethernet address.
Here is the OpenBSD/FreeBSD definition for ETHER_HDR_LEN:
```c
#define ETHER_ADDR_LEN  6       /* Ethernet address length */
#define ETHER_TYPE_LEN  2       /* Ethernet type field length */
#define ETHER_HDR_LEN   ((ETHER_ADDR_LEN * 2) + ETHER_TYPE_LEN)
```
(OpenBSD's definition is at [netinet/if_ether.h](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/netinet/if_ether.h?rev=1.73&content-type=text/x-cvsweb-markup), FreeBSD's is at …

Unbreak ISIS Hellos (FreeBSD)

---

bgpd/bgp_attr.c

Signed-off-by: Lou Berger <lberger@labn.net>

bgpd: minor performance enhancement

---

ldpd/l2vpn.c
ldpd/lde.c
ldpd/ldpd.h
zebra/zebra_pw.c

Cherry-picking two commits from #1500

ldpd: small improvements

---

lib/ringbuf.c
lib/ringbuf.h
lib/subdir.am
tests/Makefile.am
tests/lib/test_ringbuf.c
tests/lib/test_ringbuf.py

Simple ring buffer implementation useful for fixed size FIFO queues.

lib: add ring buffer

---

ospfd/ospf_vty.h

Signed-off-by: lihongguang <lhg803@163.com>

ospfd: return non-zero for configuration failures

---

ospfd/ospf_vty.c

Signed-off-by: lihongguang lhg803@163.com

ospfd: fix [no] area authentication command

---

bgpd/bgp_io.c
bgpd/bgp_io.h
bgpd/bgpd.c
lib/frr_pthread.c
lib/frr_pthread.h

Alternative way to handle the startup issue

More thread yield

---

zebra/label_manager.c

Signed-off-by: ßingen <bingen@voltanet.io>

ldpd: Add privs to label manager

---

ospfd/ospf_vty.c

ospfd: Fix no passive interface command parsing

---

ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_message.c

Add OSPFv3 Protocol incoming/outgoing packets
stats.
r3# show ipv6 ospf6 interface traffic
Interface       HELLO            DB-Desc         LS-Req    LS-Update     LS-Ack
Rx/Tx            Rx/Tx            Rx/Tx    Rx/Tx         Rx/Tx
--------------------------------------------------------------------------------------------
swp1              3/4              2/2             0/2     8/6           3/2
swp2              3/4              2/2             0/1     7/3           2/0
swp3              0/4              0/0             0/0     0/0           0/0

ospf6d: Add protocol stats and show command

---

bgpd/bgp_io.c
bgpd/bgp_io.h
bgpd/bgpd.c
lib/frr_pthread.c
lib/frr_pthread.h

Replace atomic spinlock with condition variable.

improve bgpd thread startup characteristics

---

bgpd/bgp_route.c

BGP "allowas-in" should accept AS paths with "local-as"

---

vtysh/vtysh.c

When printing responses from a client, vtysh searches through every
response it receives twice. Once is to look for the terminating
sequence and the other is to translate `\n` to `\0`, which is used with the
line processing callback capability. However:
* There's no need to search all of the output for the terminator, we can
just check the last 4 bytes.
* In most scenarios we won't have a callback. Therefore we don't need to
process the output and can just dump it.
Together these optimizations have a significant impact on the total
runtime of talkative CLI commands, such as `sh ip bgp json` which runs
roughly 1000% faster when dumping 1,000,000 routes.
Compare:
```
vagrant@frrdev ~> sudo time vtysh -c 'show ip bgp json' > drank5
0.19user 0.17system 0:10.46elapsed 3%CPU (0avgtext+0avgdata …
```

vtysh: optimize printout routine

---

README

* Clarify that FRR implements as well as manages protocols
* Move IS-IS out of "early support"
* Add Babel - friends don't leave friends out of READMEs!
* Add mention of further information

frr: update README

---

lib/thread.c

There are some observed instances where we end up trying to cancel a rw
job based on a file descriptor that we don't have a reference on. The
specific cancel function for rw jobs assumes it's called with a file
descriptor that is valid within pollfds and will cause a segmentation
fault by buffer overrun if this is not the case.
Instead log it and move on. Since the fd does not exist this should
patch over the buggy behavior and provide additional information to help
in finding the root cause.
Fixes #1640 
Reviewed-by: Donald Sharp <sharpd@cumulusnetworks.com>

lib: avoid crash when cancelling invalid rw job

---

redhat/frr.spec.in
zebra/zebra_fpm.c

Build redhat rpm's with FPM.  It's a module so not
a bad idea.

redhat: Build with FPM

---

bgpd/bgp_io.c

bgpd: update last_update whenever obuf sent (consistent with last_write updates)

bgpd: update last_update whenever obuf sent 

---

bgpd/bgp_packet.c

If a BGP message header fails validation we send a BGP NOTIFICATION from
the I/O thread. At this time we clear the output buffer, push a
NOTIFICATION and then call the manual write function for errors. But in
between the push and the write the main thread could have pushed some
other message. Thus we need to hold the lock for the duration of the
function. TOCTTOU.

bgpd: fix race condition causing occasional assert

---

zebra/rt.h
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/zebra_rib.c

This is a continuation of my work to abstract the soutbound api and isolate the install from the setting of appropriate flags.

Southbound pointer

---

lib/zclient.c

lib: Fix encoding of vrf

---

tools/checkpatch.pl
tools/checkpatch.sh

Add shell script and modified checkpatch.pl for use with patch files
targeting FRR.
Fixes #1489 

tools: add style checking scripts

---

lib/keychain.c

added some non-exist commands
Signed-off-by: Dmitrii Turlupov \<dturlupov@factor-rs.ru\>

lib: 'no accept-lifetime' and 'no send-lifetime' for keychain

---

debianpkg/.gitignore

debianpkg: .gitignore += changelog

---

bgpd/bgp_routemap.c
zebra/zebra_vxlan.c

This PR consists of the following:
1. Optimizations in l3vni code flow
2. Policy to filter EVPN routes based on route-type

EVPN Symmetric routing enhancements 2.0

---

ospfd/ospf_routemap.c

Signed-off-by: Dmitrii Turlupov <dturlupov@factor-rs.ru>

ospfd: OSPF support the +/- in set metric <+/-metric>

---

zebra/rt_netlink.c

When a BGP-labeled route is resolved into an LDP-labeled IGP route,
zebra would install it with no labels in the kernel. This patch implements
recursive MPLS labels, i.e. make zebra install all labels from the route's
nexthop chain (the labels from the top-level nexthop being installed in
the top of the MPLS label stack). Multiple recursion levels are supported.

zebra: implement recursive MPLS labels

---

tools/checkpatch.sh

* Send reports to stderr; this allows you to get just the end result by
redirecting stderr
* Don't attempt to copy nonexistent files

tools: improve checkpatch.sh

---

ospfd/ospf_vty.c

show ip ospf [vrf all] interface json and
show ip ospf [vrf all] neighbor json to display
objects in dictionary output rather in array list.
Ticket:CM-19115,CM-19097
show ip ospf vrf vrf1014 interface json 
{
"vrf1014":{
"vrfName":"vrf1014",
"vrfId":119,
**"interfaces"**:{
**"swp51s0.4"**:{
"ifUp":true,
"ifIndex":122,
"mtuBytes":1500,
"bandwidthMbit":10000,
"ifFlags":"<UP,BROADCAST,RUNNING,MULTICAST>",
"ospfEnabled":true,
"ipAddress":"44.4.1.1",
"ipAddressPrefixlen":24,
"area":"0.0.0.1",
"routerId":"6.0.4.7",
"networkType":"POINTOPOINT",
"cost":10,
"transmitDelayMsecs":1000,
"state":"Point-To-Point",
"priority":1,
"mcastMemberOspfAllRouters":true,
"timerMsecs":83,
"timerDeadMsecs":24,
"timerWaitMsecs":24,
"timerRetransmit":200, …

ospfd: fix ospf interface and neighbor json

---

pimd/mtracebis.c
pimd/pim_igmp_mtrace.c

Fix some compiler issues that were not picked up.

pimd: Fix some compiler issues

---

vtysh/vtysh_main.c

vtysh: .history_quagga --> .history_frr

---

pimd/CAVEATS

Added mtrace caveat to CAVEATS.
Signed-off-by: Mladen Sablic <mladen.sablic@gmail.com>

pimd: added mtrace caveat

---

eigrpd/eigrp_zebra.c
lib/zclient.c
lib/zclient.h
sharpd/sharp_zebra.c
zebra/zebra_rib.c
zebra/zserv.c
zebra/zserv.h

I screwed up PR 1751 so pulled this instead.

Route notify owner

---

doc/OSPF-SR.rst
doc/ospfd.texi
ospfd/ospf_ext.c
ospfd/ospf_opaque.c
ospfd/ospf_packet.c
ospfd/ospf_sr.c
ospfd/ospf_sr.h

This pull request corresponds to back port in Dev 4.0 branch of:
- #1729 which add json output to Segment Routing
- #1730  which fix ospfd crash
- #1764 which fix Segment Routing Lan Adjacency TLVs

OSPF Segment Routing fix

---

vtysh/vtysh.c
vtysh/vtysh_config.c

dev/4.0: fix vtysh output init

---

vtysh/vtysh.c
vtysh/vtysh_config.c

vtysh: initialize vty structure correctly for output to terminal

---

bgpd/bgpd.c
lib/netns_linux.c

This fixes https://github.com/FRRouting/frr/issues/1829

Misc BGP VRF fixes

---

bgpd/bgp_vty.c

bgpd: fix update-group show commands

---

bgpd/bgp_vty.c

bgpd: fix update-group show commands [4.0]

---

.gitignore
bgpd/.gitignore
ldpd/.gitignore
lib/.gitignore
ospfd/.gitignore
sharpd/.gitignore
zebra/.gitignore

*: globally ignore clippy-generated source

---

lib/debug.h

Some more work on the debugging header.
* Add `DEBUG*()` macros
This set of macros allows you to write printf-like debugging lines that
automatically check whether a debug is on before printing. This should
eliminate the need for explicit checks in simple cases. For example:
if (SUCH_AND_SUCH_DEBUG_IS_ON) {
zlog_warn(...);
}
Becomes:
DEBUG(warn, such_and_such, ...);
Or, equivalently,
DEBUGE(such_and_such, ...);
The levels passed to DEBUG are expanded into the names of zlog_*
functions, so the same zlog levels are available. There's also a set of
macros that have the level built into them; DEBUGE for errors, DEBUGW
for warnings, etc. Good for brevity.
* Add singular setting macros
Change the 'SET' macros to accept a boolean indicating whether the
provided bits should be set or unset, and …

lib: add convenience debugging macros

---

tools/indent.py
vtysh/vtysh.c

- fix indent.py, restore some unneeded reformats.

more indent.py related changes

---

tools/frr-reload.py

This is the master version of #1823

tools/frr-reload.py: process vnc settings as sub-context

---

zebra/zebra_rib.c
zebra/zserv.c

There were several places where when I am attempting
to debug zebra functionality that I would really
like to have the ability to know what vrf I think
I am operating on.
Add the vrf_id to a bunch of zlog_debug messages
to help figure out issues when they happen.

zebra: Add some additional vrf info to debugs

---

pimd/mtracebis.c

mtracebis has been updated, so it behaves more like the original
mtrace command.
Signed-off-by: Mladen Sablic <mladen.sablic@gmail.com>

pimd: improvments to mtrace

---

debianpkg/README.deb_build.md
debianpkg/backports/ubuntu12.04/debian/rules
debianpkg/backports/ubuntu14.04/debian/rules
debianpkg/rules
redhat/README.rpm_build.md
redhat/frr.spec.in

Changes to allow RPKI enabled FRR packages for master branch
This is similar to #1837, but for master branch

Rpki pkg master

---

zebra/main.c
zebra/redistribute.c
zebra/rib.h
zebra/zebra_ns.c
zebra/zebra_ns.h
zebra/zebra_pbr.c
zebra/zebra_pbr.h
zebra/zebra_rib.c
zebra/zserv.c

Add some code to handle client disconnects as well as zebra restarts for rules and high order tables

Zebra rule

---

doc/user/bgp.rst

Documentation for bgpd vpn-vrf leaking commands of #1913.

doc: bgp vpn-vrf leaking CLI

---

ripd/ripd.c

This commit fixes these three issues:
1) rinfo is used for rip packet sending not tmp_rinfo
2) With RIP_SPLIT_HORIZON and an interface with more than 1 ip addresses
we will not send the routes out an interface that they originate on
3) With RIP_SPLIT_HORIZON_POISONED_REVERSE and an interface with
more than 1 ip address we will not send out ipA with a metric of 16
and ipb with a metric of 1.  Both will be 16 now.
Signed-off-by: lyq140 <34637052+lyq140@users.noreply.github.com>

ripd: considering a interface with 2 or more IP

---

doc/developer/cli.rst
doc/developer/workflow.rst

doc: document code style tools

---

alpine/.gitignore

alpine: add APKBUILD to .gitignore

---

pimd/pim_igmp_mtrace.c

Mtrace router code has been fixed for the case where no PIM
interface exists towards the source and next-hop is returned.
fwd_ttl is set to one, for correct reporting of mcast ttl.
Also, NO_MULTICAST error is returned when there is no PIM.
And prev_hop is set to source, for case when connected to source,
to help termination of hop-by-hop queries.
Dependency of logging on PIM, when sending mtrace packet, has been
removed.
Signed-off-by: Mladen Sablic <mladen.sablic@gmail.com>

pimd: mtrace router code improvments and fixes

---

lib/vrf.h
zebra/interface.c
zebra/zebra_netns_notify.c
zebra/zebra_ns.c

- pbr rules context per ZNS
- notification for netns contexts
- clean code around usage of NS_DEFAULT

Misc fixes netns

---

doc/developer/building-frr-on-alpine.rst

Match the rest of them.
@ajones-rvbd 

doc: change title of Alpine build doc

---

zebra/if_netlink.c

The table id of the vrf is being given to us as part
of the vrf creation netlink callback.  Unfortunately it
was being set in the zvrf *after* the vrf_enable callback.
This didn't used to matter until we started having config data
stored on the side that we needed to act on when the vrf
came up enough to start working.
So when we were storing static routes and installing them
they were being pushed into the default table for non-default
vrf's.
Ticket: CM-19141

zebra: Set table id *before* we enable the vrf

---

lib/command.c
lib/command.h
vtysh/vtysh_config.c

lib: remove SERVICE_NODE

---

lib/command.c
lib/command.h
lib/vty.c
vtysh/vtysh.c

lib: remove MASC_NODE

---

doc/user/ipv6.rst
zebra/rtadv.c
zebra/rtadv.h

This reverts commit 3fec765a8d986664a555c161b814b4bf3332cdf0.
April fools!

Revert "zebra: implement draft-bz-v4goawayflag-00"

---

lib/netns_linux.c

Do not complain about failure to create a namespace if we
do not have any such thing going on.

lib: Namespaces should only complain about failure if we have it

---

doc/manpages/vtysh.rst
vtysh/vtysh.c
vtysh/vtysh.h
vtysh/vtysh_main.c

motivated by #1877 - -  this change by itself does NOT assure any security

vtysh: add -u/--user flag to run commands without enable

---

lib/command.c
lib/command.h

lib: remove IRDP_NODE

---

bgpd/bgp_main.c
doc/user/bgp.rst

Signed-off-by: Kunihiro Ishiguro <ishi@coreswitch.io>

bgpd option '-p 0' means do not listen BGP port.

---

doc/developer/workflow.rst

My goal with this added text is to document the current process (not to change the process). If I have not captured the process accurately, please comment. Thanks!

COMMUNITY.md: document more details of current coding style process

---

zebra/zebra_rib.c
zebra/zebra_static.c
zebra/zebra_static.h
zebra/zebra_vrf.c
zebra/zebra_vty.c

This is a series of commits to address static routes being handled with better with vrf enable/disable and interface up/down events

Static nh vrf

---

zebra/zebra_vxlan.c

zebra: fix style error

---

bgpd/bgp_route.c

bgpd: Fix another aspath %d that should be %u

---

bgpd/rfapi/rfapi_import.c

Thanks to @qlyoung for identifying this SA issue.

bgp/rfapi: fix rfapiNhlAddNodeRoutes SA issue

---

babeld/route.c
bgpd/bgp_mpath.c
bgpd/bgp_packet.c
bgpd/bgp_route.c
bgpd/rfapi/bgp_rfapi_cfg.c
lib/command_lex.l
lib/command_match.c
ospf6d/ospf6_abr.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_intra.c
ospf6d/ospf6_zebra.c
ospfd/ospf_lsa.c
ospfd/ospf_zebra.c

Static analyzer fixes

---

bgpd/bgp_mplsvpn.c

vpn-vrf leak code was not triggering a BGP update or an announce to zebra if a route's labels changed. This changeset corrects that problem.
Thanks to @rwestphal for noticing this issue

bgpd: bugfix vpn-vrf leak: consider route changed if labels change

---

tools/lsan-suppressions.txt

Signed-off-by: Ilya Shipitsin <chipitsine@gmail.com>

more exclusions for clippy tool when running -fsanitize=address

---

zebra/redistribute.c

When we are debugging add a bit of extra information
so we can know what we are redistributing to our peers

zebra: Add some information to redistribute debugs

---

lib/thread.c

lib: fix dynamic stack buffer overflow

---

bgpd/bgp_zebra.c

When sending a bgp route down to zebra for deletion, the
ZEBRA_FLAG_ALLOW_RECURSION and ZEBRA_FLAG_IBGP flags
are not needed in zebra.  So remove the setting
of the api.flags.  If we remove this data from being
passed down we no longer need the peer data structure.
Remove the lookup of the peer data structure and the setting
of the flags as that peer was NULL in some evpn symmetric
routing cases for shutdown of bgp.
Ticket: CM-20720

bgpd: The deletion of a bgp route does not need to send some data

---

bgpd/bgp_attr.c

bgpd: Add some additional attribute information to dump

---

ospf6d/ospf6_asbr.c

Durig ospf6 instance cleanup all border routers
are removed from the db then external LSAs removal
from DB is triggered. During the time, external route
path would not be valid as brouters along with its
rechability have vanished.
For a given external route removal check if no more
paths available simple remove the route from route db.
Testing Done:
Bring up ASBR configuration with ECMP paths to a route.
Bring down the ospf6 instance and validate route is removed
from the DB.

ospf6d: fix ospf6 asbr crash

---

doc/Makefile.am
doc/manpages/conf.py
doc/manpages/index.rst
doc/manpages/sharpd.rst
doc/user/index.rst
doc/user/sharp.rst

doc: Add some documentation for the sharp daemon

---

vtysh/vtysh.c

I introduced a bug with #1940 that caused VTYSH to never write the config if watchfrr was not running. This patch fixes it so that if watchfrr is running, we defer to that (watchfrr will still refuse to write the config if it detects a crashed / disconnected daemon) and if it's not vtysh will write it itself (without crash detection).

vtysh: fix failure to write config w/o watchfrr

---

babeld/babel_main.c
snapcraft/scripts/Makefile
snapcraft/scripts/babeld-service
snapcraft/scripts/eigrpd-service
snapcraft/scripts/pbrd-service
snapcraft/snapcraft.yaml.in

Update to snap package to add new protocol daemons.
- Include small fix in babel to correctly parse `-f` option for config file override

Update SNAP Package to add EIGRP, Babel and PRD

---

bgpd/Makefile.am
bgpd/bgp_debug.c
bgpd/bgp_debug.h
bgpd/bgp_ecommunity.c
bgpd/bgp_ecommunity.h
bgpd/bgp_flowspec_util.c
bgpd/bgp_flowspec_util.h
bgpd/bgp_pbr.c
bgpd/bgp_pbr.h
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_zebra.c
bgpd/bgp_zebra.h
bgpd/bgpd.c
bgpd/bgpd.h
lib/zclient.c
lib/zclient.h
vtysh/Makefile.am

this is the work that consists in handling FS entries and convering it, if possible into policy routing entries, so that ZEBRA will add the new routing rules.

Bgp Flowspec Policy Based Routing

---

isisd/isis_redist.c

Set isis redistribution metric to 0 instead of infinity if it's unspecified.

dev/5.0: isis redist metric

---

isisd/isis_redist.c

isisd: use 0 as default-metric for redistribution

---

doc/user/zebra.rst

As there are subtle differences between VRF-lite and VRF-netns,
some information is given to the operator on what can be/ can not be
done.

doc: add information about zebra VRF configuration

---

ospfd/ospf_interface.c

Currently, interface packet transmit queue is created/deleted as part of 
Interface UP/Down event. This results in a rare condition where port
came up but queue was not created.
The creation of queue occupies only few bytes.
Moving fifo queue creation to interface create would add few bytes of 
fifo creation but at least it guaranteed to be available during
Up/down -->Up event.
Initialize ospf packet fifo queue during ospf interface creation.
Drain queue during interface down event.
Drained and free the queue as part of the interface delete/cleanup.
Testing Done:
Bring up ospfv2 topology with multiple neighbors.
1) Trigger multiple shut/no shut events and validate
all queues are freed.
2) configure/deconfigure router ospf and validate
all ospf instance and interface underneath are freed. …

ospfd: packet fifo init in interface create

---

bgpd/bgp_fsm.c

1) Cleanup error handling to be better
2) Handle no route to peer better when we have a zebra connection.

some small bgp issues

---

doc/developer/building-frr-on-openbsd6.rst

doc: update pkg version for automake on openbsd6

---

README

frr: fix typo in README

---

lib/stream.c
lib/stream.h

`stream_fifo` is used as our standard internal message queue. Message
queues are useful in multithreaded environments. Up until now I have
been doing my own synchronization when using `stream_fifo` in this way;
this patch gets rid of the need for that boilerplate and decreases the
risk of locking mistakes when working with this datastructure.

lib: add mt-safe variants for stream_fifo ops

---

doc/developer/building-frr-on-ubuntu1804.rst

Made some changes to the Ubuntu 18.04 build guide in developer docs based on observed differences while following said guide. Also added some detail that would have been helpful during process.

docdev: Ubuntu 1804 build guide

---

bgpd/bgp_rpki.c

Signed-off-by: Andrey Korolyov <andrey@xdel.ru>

Fix compilation against rtrlib with ssh

---

doc/user/routemap.rst
sharpd/sharp_main.c
sharpd/sharp_vty.c
sharpd/sharp_zebra.c
sharpd/sharp_zebra.h
zebra/redistribute.c
zebra/zebra_rib.c
zebra/zebra_routemap.c
zebra/zebra_routemap.h

Allow zebra route-maps to match on source-instance.

Instance routemap match

---

bgpd/bgp_vty.c

The current implementation does not respect the AFI+SAFI combination of
a peer when executing a non-soft (hard) clear. An example would be the
command `clear bgp ipv4 unicast *`, which will clear all BGP peers, even
those that do not have IPv4-Unicast activated.
This commit fixes that behavior by applying the same rules to both soft
and hard clear commands, so that peers without a matching AFI+SAFI
combination will be no longer modified.
Additionally, this commit adds warning messages to all `clear bgp
[<afi>] [<safi>] <target>` commands when no matching peers with the given
AFI+SAFI combination could be found.
Both existing and new warning messages have been extended to also
mention the AFI+SAFI combination that is missing, which is more helpful
to the user than a generic expression 'No …

bgpd: Respect AFI/SAFI when hard-clearing a peer

---

doc/Makefile.am
tests/Makefile.am

`make distcheck` revealed to me some missing files

Fix missing dist files

---

zebra/zebra_vxlan.c
zebra/zebra_vxlan_private.h

1) Small formating mistake fixed
2) Rename of a variable to give it a slightly better name

zebra: Cleanup some nits from Review Comments

---

zebra/rt_netlink.c

Should help with blackhole routes and route deletion in the stable/4.0 code path.
This should address #2265

Fix 4.0 blackholes

---

bgpd/bgp_main.c
ripd/rip_main.c
ripngd/ripng_main.c

This option is only implemented by 4 daemons:
- BGPD
- RIPD
- RIPNGD
- Zebra
Manpages and [documentation](http://frrouting.readthedocs.io/en/latest/bgp.html#cmdoption-bgpd-r) say that the option causes routes to not be
uninstalled from zebra when the daemon terminates. This is true for RIPD
and RIPNGD in the sense that it prevents them from sending route uninstall
ZAPI messages when they normally would. This is not true for BGPD; in that
daemon it only prevents transmission of Cease / Peer Unconfig NOTIFICATION
messages to peers.
However, when any daemon disconnects from Zebra, all of its routes are
uninstalled from Zebra and the kernel regardless of this option,
rendering it largely vestigial.
It is still useful in Zebra, where it prevents all routes from being
uninstalled when Zebra …

*: remove -r from daemons except zebra

---

redhat/frr.spec.in

Fixes RPKI Package build for master
Adresses issue https://github.com/FRRouting/frr/issues/2234 on master branch

redhat: Fix RPKI RPM build option (Master Branch)

---

redhat/frr.spec.in

Fixes RPKI Package build for dev/5.0
Adresses issue #2234 on dev/5.0 branch

redhat: Fix RPKI RPM build option (dev/5.0) 

---

debianpkg/rules

Allow users to build with WANT_CUMULUS_MODE

debianpkg: Fix typo

---

bgpd/bgp_evpn.c

Some code cleanup and some SA issues found and fixed.

Evpn SA/CI issues found 

---

lib/hash.c
lib/hash.h
lib/linklist.c
lib/linklist.h

* Add `list_sort()`
* Add `list_dup()`
* Add `hash_to_list()`
* Clean and improve doc comments for all hash and linklist functions

linklist sorting + hash table -> linklist

---

lib/memory.c

lib: make allocators work for allocation sizes of 0

---

bgpd/bgp_zebra.c
lib/zclient.c
zebra/label_manager.c
zebra/label_manager.h
zebra/zapi_msg.c

Adopt fixes done to label manager already included in master.
All the commits in this PR are already in master.

Fix label manager dev 5.0

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_abr.h
ospf6d/ospf6_asbr.c

Inter Area Prefix LSA ECMP is not working properly. Two ABRs advertising IAP routes to backbone, not installed with correct cost or if ABR restarted the route is removed
from backbone.
The current implementation ABR was not suppressing IAP update for prefix cost is not better or route is not installed.
The better cost or path route was overwritten with non optimal cost. This caused a loop with nexthops pointing each other at backbone and non-backbone routers.
Consider to only send BEST/installed route's IAP notification at ABRs.
When receiving IAP update from multiple ABRs, preserve multiple advertising routers under the prefix route node.
Upon LSA maxage only remove the advertising route's which is impacted and update route's nexthops and update FIB.
Testing Done:
Top to Bottom is part …

ospf6d: Fix inter area prefix

---

bgpd/bgp_network.c
bgpd/bgpd.c
lib/vrf.c

accept incoming bgp tcp connections within a VRF (Issue #2174)

---

bgpd/bgp_route.c
pbrd/pbr_nht.c
pbrd/pbr_nht.h
pbrd/pbr_vty.c

Fixes for Ubuntu Package build for dev/5.0
This combines PR #2164 and PR #2240 from master for 5.0

PBRd and BGPd ubuntu fix

---

bgpd/bgp_network.c
bgpd/bgpd.c
lib/vrf.c
zebra/redistribute.c

Cherry-pick some fixes that I think should be in 5.0

Couple of cherry-picks of code

---

pimd/pim_nht.c
pimd/pim_rpf.c

pimd: Comment spelling fix

---

pimd/pim_rp.c
pimd/pim_rpf.c

pimd: Fix debug messages

---

bgpd/bgp_evpn_vty.c

bgpd: fix missing docstring

---

bgpd/bgp_evpn.c
ospfd/ospf_flood.c
ospfd/ospf_te.c
ripd/ripd.c
tests/bgpd/test_mpath.c
vtysh/vtysh.c

A grab bag of code cleanup and SA issues from Coverity.

Code Cleanup and SA issues

---

bgpd/bgp_vty.c
doc/user/bgp.rst

Deprecate:
bgp config-type cisco
no bgp multiple-instance
commands

Bgp deprecation

---

doc/developer/cli.rst

doc: document 'show cli graph'

---

bgpd/bgp_route.c

This is a bunch of small commits that cleanup the aggregate-address code in bgp as well fix the issue where we were sending a update for every prefix change associated with a aggregate irrelevant if the aggregate actually changed or not.

Aggregate stuff

---

zebra/rt.h
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/rule_netlink.c
zebra/rule_socket.c
zebra/zebra_mpls.c
zebra/zebra_mpls_netlink.c
zebra/zebra_mpls_null.c
zebra/zebra_mpls_openbsd.c
zebra/zebra_pbr.c
zebra/zebra_pbr.h
zebra/zebra_rib.c

This is the start of working through the code dataplane interactions rework we've been talking about.
Basically try to define a better interface for communication of success/failure/queued for dataplane modifications.  This is the start of the work to allowing the dataplane to be abstracted to be asynchronous.

Fixup sb stuff

---

zebra/zebra_vty.c

At first glance an evident correction, unless I missed something (I was reviewing Coverity issues at [1]).

zebra: resource leak fix (Coverity 1465679)

---

bgpd/bgp_main.c
bgpd/bgp_route.c
bgpd/bgpd.c

Fixes bgp crashes in the topotest, that I was seeing.

Bgp crash fix for topotests

---

bgpd/bgp_vty.c

bgpd: dead code (Coverity 1399246)

---

bgpd/rfapi/bgp_rfapi_cfg.c

bgpd: dead code (Coverity 1399389)

---

tools/start-stop-daemon.c

tools: out-of-bounds access (Coverity 1399290)

---

tools/start-stop-daemon.c

tools: return check (Coverity 1143220)

---

lib/plist.c

lib: out-of-bounds access (Coverity 1457145)

---

vtysh/vtysh_main.c

vtysh: -u fixes

---

bgpd/rfapi/bgp_rfapi_cfg.c

[1] https://scan.coverity.com/projects/freerangerouting-frr>

bgpd: out-of-bounds access (Coverity 1399306)

---

bgpd/rfapi/rfapi.c

bgpd: dead code (Coverity 1399373)

---

babeld/babel_interface.c
babeld/util.c
lib/csv.c
lib/ptm_lib.c
ospfd/ospf_dump.c
ospfd/ospf_interface.c
tests/lib/test_checksum.c
tests/lib/test_graph.c
tests/lib/test_timer_performance.c

String format fixes (Cppcheck 1.72)

babeld, lib, ospfd, tests: fmt fixes (cppcheck)

---

eigrpd/eigrp_update.c
lib/frr_zmq.c
tests/lib/test_srcdest_table.c
vtysh/vtysh.c

At first glance, evident corrections (Cppcheck 1.72)

eigrpd, lib, tests, vtysh: security (cppcheck)

---

bgpd/bgp_routemap.c
lib/routemap.c
lib/routemap.h
pimd/pim_routemap.c
zebra/zebra_routemap.c

In prep for fixing the zebra route-map issue, clean up some code for the eventual work.

Some route-map prep

---

isisd/isis_lsp.c
zebra/zebra_rib.c

Signed-off-by: F. Aragon <paco@voltanet.io>

isisd, zebra: FIXME fixes (grouped)

---

bgpd/bgp_rd.c
bgpd/bgp_routemap.c
bgpd/bgp_vty.c
lib/frrstr.c
lib/frrstr.h
lib/prefix.c
lib/prefix.h
ospfd/ospf_routemap.c
zebra/zebra_routemap.c

This solves a pending FIXME
Signed-off-by: F. Aragon <paco@voltanet.io>

bgpd, lib, ospfd, zebra: all_digit moved to frrstr

---

bgpd/bgp_btoa.c

bgpd: Untrusted argument (Coverity 1399380)

---

ldpd/ldpd.c

At first glance, an evident correction (Cppcheck 1.72)

ldpd: redundant condition (cppcheck)

---

vtysh/vtysh.c

At first glance, evident corrections, but please check vty messages -I put them with good intention, but maybe with not enough global knowledge- (FRR Coverity open issues [1]).

vtysh: return value check (Coverity 1399200)

---

ospfd/ospf_api.c

At first glance, evident corrections (FRR Coverity open issues [1]).

ospfd: OoB access (Coverity 1221445 1221448)

---

zebra/zserv.c

This commit gathers data from the client->obuf_fifo and
puts it all into the buffer for writing.
This will address the fact that the multiple events
created caused the memory of zebra to grow to
unrealistic levels of usage when we are redistributing
data to other protocols.
Recreate Memory:
robot# show memory
Memory statistics for zebra:
System allocator statistics:
Total heap allocated:  1930 MiB
Holding block headers: 16 MiB
Used small blocks:     0 bytes
Used ordinary blocks:  1911 MiB
Free small blocks:     1968 bytes
Free ordinary blocks:  19 MiB
Ordinary blocks:       5210
Small blocks:          58
Holding blocks:        1
New Zebra Memory:
Memory statistics for zebra:
System allocator statistics:
Total heap allocated:  478 MiB
Holding block headers: 16 MiB
Used small blocks:     0 …

zebra: Gather up output data and push in buffer to send

---

isisd/isis_spf.c

isisd: out-of-bounds access (Coverity 1452552)

---

bgpd/bgp_mplsvpn.c

[Speculative fix - NOT TESTED YET]
Issue 2381: interface based routes not marked "up" when they originate
in zebra, redistributed to bgp vrf, then imported to vpn and then
imported by another vrf.
Routes that are redistributed into BGP from zebra should not get
nexthop tracking (the assumption is that the originating protocol
is responsible to export or withdraw the route according to its own
notion of nexthop status).
The vpn-vrf route-leaking code checks the source route sub_type to
decide whether to use nexthop tracking on the resulting leaked route.
A route that is redistributed from zebra into bgp will have
sub_type==BGP_ROUTE_REDISTRIBUTE. If it is leaked to the vpn RIB,
the resulting vpn RIB route will have sub_type==BGP_ROUTE_IMPORTED.
If THAT vpn route is leaked to another vrf, …

bgpd: don't nexthop-track twice-leaked routes that came from zebra

---

lib/sbuf.c

lib: out-of-bounds access (Coverity 1452539)

---

pimd/mtracebis.c

Additional fix over d94023d85c1682ae14def9d50f2474e8e6290e44 (PR #2546)
Removed all pointer arithmetic used for the checks, while keeping same
coverage. I hope this removes the Coverity warning (If this don't fix it, I'll
make Coverity work with a fork and try there as many times as necessary)
Please, excuse the inconvenience.

pimd: untrusted argument (3) (Coverity 1465491)

---

bgpd/rfapi/rfapi_vty.c

bgpd: dead code (Coverity 1399228)

---

bgpd/rfapi/bgp_rfapi_cfg.c

At first glance, an evident correction, but please review it carefully (FRR Coverity open issues [1]).

bgpd: copy-paste error (Coverity 1399219)

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_intra.c
ospf6d/ospf6_proto.c
ospf6d/ospf6_proto.h

At first glance, an evident correction, but please review it carefully (FRR Coverity open issues [1]).

ospf6d: OoB read (Coverity 1221444 1221446)

---

doc/user/bgp.rst
doc/user/conf.py
doc/user/flowspec.rst

Add some information for BGP flowspec.

doc: add flowspec information from user point of view

---

eigrpd/eigrp_hello.c
nhrpd/nhrp_event.c
ospfd/ospf_ri.c
pimd/pim_zebra.c

At first glance, evident corrections (found using PVS-Studio trial version [1]).
[1] https://www.viva64.com/en/m/0036/#ID0EEEAE

eigrpd nhrpd ospfd pimd: fomat fixes (PVS-Studio)

---

bgpd/bgp_rpki.c

If a cache server was added after rpki was started it's tr_socket would
not be initialized. This would lead to a segfault if the rtr manager
ever decides to switch to that socket or if rpki support is stopped.
Signed-off-by: Marcel Röthke <marcel.roethke@haw-hamburg.de>

bgpd: fix rpki segfault (stable/4.0)

---

bgpd/bgp_flowspec_vty.c
bgpd/bgp_route.c
bgpd/bgpd.c
bgpd/rfapi/rfapi.c
bgpd/rfapi/vnc_import_bgp.c
lib/vty.c
lib/workqueue.c
ospfd/ospf_lsa.c
ospfd/ospf_vty.c
pimd/pim_mroute.c
ripngd/ripngd.c

At first glance, evident corrections (found using PVS-Studio trial version [1]).
[1] https://www.viva64.com/en/m/0036/#ID0EEEAE

bgpd lib ospfd pimd ripngd: null chk (PVS-Studio)

---

doc/user/zebra.rst

Add MPLS information to statically handle label from zebra.

doc: add MPLS configuration commands

---

doc/user/bgp.rst
doc/user/conf.py
doc/user/flowspec.rst
doc/user/installation.rst
doc/user/zebra.rst

some misc documentation related to flowspec, bgp and zebra is being put into that branch.
all those commits are inherited from master branch.

Misc bgp zebra doc

---

ospfd/ospf_ase.c
pimd/pim_mroute.c

At first glance, evident corrections (found using PVS-Studio trial version [1]).
[1] https://www.viva64.com/en/m/0036/#ID0EEEAE

ospfd  pimd: null check (PVS-Studio)

---

pimd/mtracebis_netlink.c

fread() function was not used properly.

pimd: standard library usage (PVS-Studio)

---

eigrpd/eigrp_packet.c
lib/filter.c
lib/module.c
lib/vrf.c
pimd/pim_ifchannel.c
pimd/pim_igmp.c
pimd/pim_nht.c
zebra/if_netlink.c
zebra/zebra_ptm.c

At first glance, evident corrections (found using PVS-Studio trial version [1]).
[1] https://www.viva64.com/en/m/0036/#ID0EEEAE

eigrpd lib pimd zebra: dead code (PVS-Studio)

---

pimd/pim_cmd.c
pimd/pim_nht.c
pimd/pim_nht.h
pimd/pim_rp.c
pimd/pim_rpf.c
pimd/pim_zebra.c

Code refactoring and cleanup of pim not switching ecmp paths properly in several situations

More pim neighbor

---

bgpd/bgp_route.c
bgpd/bgp_vty.c

Added localRouterID to "show bgp neighbor json"
Added json O/P to "show bgp [AFI] community <community>"
Signed-off-by: Ameya Dharkar <adharkar@vmware.com>

bgpd: Changes to BGP show json commands

---

isisd/isis_circuit.c

Stable/5.0: Fix issue with p2p interfaces on FreeBSD

---

tools/frr-reload.py

tools: handle exit-vrf as end of context block

---

pimd/pim_zebra.c

When we receive a IGMP report on an interface, do not create upstream
state for that request, unless we are the DR for the incoming interface.
This will prevent a interface on a LAN segment from causing traffic
to flow to itself.

pimd: Do not create upstream state when not DR for igmp request

---

doc/Makefile.am
doc/extra/spelling_wordlist.txt
doc/user/index.rst
doc/user/ldpd.rst

This commit gathers some basic information on how to configure and setup
Ldp, as well as depict some main principles for that protocol.

doc: add Ldp user documentation

---

doc/user/rpki.rst

Previous commit on this file introduced formatting issues.

doc: cleanup rpki.rst

---

doc/user/bgp.rst

* Clean up command stubs
* Document `disable-connected-check`
* Add markup
* Clarify section on autonomous systems
* Rewrap line to 80 characters
* Fix typos
* Fix grammar
Fixes #2713 

doc: misc bgp.rst fixes

---

zebra/zebra_pbr.c

Align zebra pbr code to master code.

zebra: align zebra pbr code to master code.

---

doc/user/rpki.rst

Conflicting commits made close together messed up the formatting.

Fix various rpki.rst errors (again)

---

pimd/pim_nht.c
pimd/pim_zebra.c
pimd/pim_zebra.h

Found a couple of cases where we needed to abstract identical functionality in pim

Pim duplicate

---

bgpd/bgp_debug.c
bgpd/bgp_flowspec_vty.c

bgpd: rsc leak (Coverity 1472226 1472228 1472239)

---

bgpd/bgp_route.c
pimd/pim_rp.c

At first glance, evident corrections (FRR Coverity open issues [1]).

bgpd pimd: return check (Coverity 1472232 1472234)

---

bgpd/bgp_clist.c

Bit of less than ideal memory management here...

bgpd: fix odd memory mgmt in clist strings fn

---

bgpd/bgp_vty.c

Signed-off-by: Ameya Dharkar adharkar@vmware.com

bgpd: Added local router-id to "show bgp neighbor"

---

bgpd/bgp_nht.c

Signed-off-by: vishaldhingra <vdhingra@vmware.com>

peer_delete did not trigger ZEBRA_NEXTHOP_UNREGISTER to ZEBRA

---

tools/frr-reload.py

Problem reported that when a peer-group was added in certain
configurations, it would be rejected because of the order of the
commands put in by nclu. Issued turned out to be how frr-reload.py
was handling the sub-sub-context of the vni under the address-family
and subsequently how it handled the following exit-vni.
Ticket: CM-21996

tools: correct frr-reload.py handling of bgp vni/exit-vni config

---

babeld/babel_main.c
ldpd/ldp_vty_cmds.c
lib/command.h
lib/defun_lex.l
lib/if.c
lib/linklist.c
lib/linklist.h
lib/vrf.c
pbrd/pbr_vty.c
pimd/pim_vty.c
vtysh/Makefile.am
vtysh/extract.pl.in
vtysh/vtysh.c
zebra/zebra_pw.c

These are some minor fixes/improvements taken from the northbound PR and that can be merged separately.

Assorted fixes (pre-northbound)

---

doc/Makefile.am
snapcraft/scripts/Makefile
snapcraft/scripts/staticd-service
snapcraft/snapcraft.yaml.in
vtysh/vtysh_main.c

- Updates to snap package to support staticd

Updates to snap package to support staticd

---

zebra/zebra_vty.c

1. Added json output to "show ip route " command
2. Added tag O/P to "show ip route json" command
Signed-off-by: Ameya Dharkar adharkar@vmware.com

Zebra: Changes to "show ip route" json commands backport to stable/5.0

---

snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/bfdd-service
snapcraft/snapcraft.yaml.in

snapcraft: Add bfdd to snap package

---

bfdd/bfd_packet.c
bfdd/bfdd_vty.c

In response to issue https://github.com/FRRouting/frr/issues/2836 .
This PR tries to fix the alpine compilation and includes a small fix on the show command to display the correct downtime.

bfdd: fix alpine build

---

sharpd/sharp_main.c
staticd/static_main.c

Add ability for sharpd and staticd to ignore access_list cli
for the moment.

sharpd, staticd: Add access_list_init

---

bfdd/bfd.c
bfdd/bfd.h
bfdd/bfd_packet.c
bfdd/bfdd_vty.c
bfdd/control.c
bfdd/ptm_adapter.c
doc/user/bfd.rst
zebra/zebra_ptm.c

Changelog:
* Add `show` command to display session counters;
* Update and complete documentation with missing commands;
* fix coverity scan issues;
* fix a memory leak in the zebra ptm adapter;
* improve log messages;

bfdd: bug fixes and improvements

---

zebra/zebra_vty.c

1. Added json output to "show ip route " command
2. Added tag O/P to "show ip route json" command
Signed-off-by: Ameya Dharkar adharkar@vmware.com

Zebra: Changes to "show ip route" json commands backport to stable/4.0

---

bgpd/bgp_vty.c

bgpd: add json output to bgp route-leak show command

---

isisd/isis_circuit.c
lib/stream.c
lib/stream.h
ospfd/ospf_lsa.c
tests/lib/test_stream.c

Modify stream.c to use one malloc for stream_new. This entails fixing up stream_resize though.

Stream resize

---

bgpd/bgp_rpki.c

This fixes two bugs in the rpki code introduced by the revalidation patch.

bgpd: rpki bugfixes

---

lib/if.c
lib/if.h
pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_pim.c
zebra/zebra_rib.c

zebra: if multiple connecteds, select loopback or vrf if present

---

doc/Makefile.am
doc/developer/library.rst
doc/developer/logging.rst

This roughly outlines when to use which logging function.  It's
certainly something to have to point people to, so they get things nice
and right - and so we get at least somewhat consistent behaviour for the
user.
Signed-off-by: David Lamparter <equinox@diac24.net>

doc/developer: logging guide

---

isisd/isis_bpf.c
lib/ferr.c
zebra/if_ioctl.c
zebra/zebra_vxlan.c

Cleanup some warnings found on bsd systems as they compile.

Bsd warnings

---

lib/vrf.c

Memory sizes of the vrf bit-map was insane for a system
with a moderate number of data on it:
Zebra:
VRF bit-map                   :        601   65536            39391944
Having a full 32bit integer bit space is problematically large,
switch over to a hash to store bit data.  We do not need to waste
so much space.
VRF bit-map                   :         13       8                 312

lib: Convert vrf bit-map to a hash.

---

lib/ferr.c

lib: Use the actual string we want to limit '===' line to

---

doc/developer/workflow.rst

add comment on closing PRs
add comment on PR title and description

workflow additions

---

lib/routemap.c

lib: sort route-maps for display

---

.github/PULL_REQUEST_TEMPLATE.md

Add github pull template as a reminder for new committers to include the
singed-off-by line in commits.
Template inspiration pulled from
help.github.com/articles/creating-a-pull-request-template-for-your-repository/
Signed-off-by: Christoffer <netravnen@gmail.com>

Add github pull-request-template.md

---

eigrpd/eigrp_vty.c

Signed-off-by: Dmitrii Turlupov <dturlupov@factor-rs.ru>

eigrp: opnional metric in 'no redistribute'

---

lib/ferr.c

lib: array index check (Coverity 1473088)

---

ospf6d/ospf6_top.c

ospf6d: Remove deprecated code after 1 year

---

zebra/zebra_rib.c

Debugging inactive nexthops in zebra can be quite difficult
and non-obvious what has gone wrong.  Add detailed rib
debugs for the cases where we decide that a nexthop is
inactive so that we can more easily debug a reason
for the failure.

zebra: Modify nexthop checks to report inactive a bit more

---

sharpd/sharp_vty.c
staticd/static_vty.c

'show debug' was giving Command incomplete, fix.

Static debug

---

bfdd/bfd_packet.c
ldpd/lde.c
lib/command.c
lib/csv.c
lib/imsg-buffer.c
lib/imsg.c
lib/queue.h
lib/skiplist.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_route.c
ospfd/ospf_snmp.c
staticd/static_vty.c
zebra/zebra_fpm_protobuf.c

Should be down to 0 SA warnings with this. :tada:
Let's hope I didn't screw up the `TAILQ_POP_FIRST` macro... CI will tell :)

fix remaining SA warnings

---

bfdd/subdir.am
bgpd/subdir.am
configure.ac
doc/developer/building-frr-for-centos6.rst
doc/manpages/subdir.am
eigrpd/subdir.am
isisd/subdir.am
ldpd/subdir.am
nhrpd/subdir.am
ospf6d/subdir.am
ospfclient/subdir.am
ospfd/subdir.am
pbrd/subdir.am
pimd/subdir.am
redhat/README.rpm_build.md
redhat/frr.spec.in
ripd/subdir.am
ripngd/subdir.am
sharpd/subdir.am
staticd/subdir.am
vtysh/subdir.am
watchfrr/subdir.am
zebra/subdir.am

Can't build manpages without sphinx-build, oops...
Signed-off-by: David Lamparter <equinox@diac24.net>

build: fix not building docs w/o sphinx

---

pimd/pim_cmd.c

[fill here]
[bgpd, build, doc, ripd, ospfd, eigrpd, isisd, etc. etc.]
Always remember to follow proper coding style etc. as
described in the FRRouting Dev Guide.
http://docs.frrouting.org/projects/dev-guide/en/latest/workflow.html

pimd: fix indentation warnings

---

pimd/mtracebis_netlink.c
pimd/pim_ifchannel.c
pimd/pim_pim.c
ripd/rip_interface.c
ripd/ripd.c
ripngd/ripngd.c

Minor fixes for variable shadowing. 
pimd ripd ripngd

pimd ripd ripngd: variable shadowing fixes

---

bgpd/bgp_attr.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
bgpd/bgpd.c
bgpd/rfapi/rfapi.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_import_bgp.c
isisd/isis_pdu.c
isisd/isis_tlvs.c
ospf6d/ospf6_abr.c
ospfd/ospf_flood.c
ospfd/ospf_ia.c
ospfd/ospf_nsm.c
ospfd/ospf_packet.c
ospfd/ospf_zebra.c
ospfd/ospfd.c

Minor fixes for variable shadowing
bgpd isisd ospf6d ospfd

bgpd isisd ospf6d ospfd: variable shadowing fixes

---

bgpd/bgp_vty.c
bgpd/rfapi/bgp_rfapi_cfg.c
bgpd/rfapi/vnc_import_bgp.c
lib/plist.c
lib/termtable.c
lib/vrf.h
lib/zebra.h
ospf6d/ospf6d.h
pbrd/pbr_nht.c
tests/lib/cli/test_commands.c
tests/lib/test_srcdest_table.c
zebra/interface.c

Minor fixes for variable shadowing. This fixes all remaining local variable shadowing cases.
bgpd lib ospf6d pbrd tests zebra

bgpd lib ospf6d pbrd tests zebra: shadowing fixes

---

lib/thread.h
lib/wheel.c
lib/wheel.h
pimd/pim_upstream.c

Allow timer wheel names to see how much time each individual timer wheel is taking up.

Twheel names

---

doc/developer/workflow.rst

Document the deprecation period we've agreed on for CLI commands.
doc

doc: document CLI deprecation period length

---

tools/start-stop-daemon.c

Fix unchecked return value. Coverity issue 1399196.
tools

tools: return check (Coverity 1399196)

---

zebra/if_netlink.c
zebra/interface.c
zebra/interface.h
zebra/rt.h
zebra/rt_netlink.c
zebra/rt_socket.c
zebra/zebra_vxlan.c
zebra/zebra_vxlan.h

A collection of zebra fixes that we've done in the past week internally.

zebra_vxlan fixes

---

bgpd/bgp_io.c
bgpd/bgp_keepalives.c
bgpd/bgpd.c
bgpd/bgpd.h
lib/frr_pthread.c
lib/frr_pthread.h
tests/bgpd/test_aspath.c
tests/bgpd/test_capability.c
tools/checkpatch.pl
zebra/zserv.c

commit titles say it all:
```
lib: remove frr_pthread->id
lib: remove unused frr_pthread_yield()
```

lib: frr_pthread minor simplification

---

bfdd/bfdd_vty.c
zebra/zebra_vxlan.c

Dead code removal (Coverity issues # 1472624 1473199)
bfdd zebra

bfdd zebra: dead code (Coverity 1472624 1473199)

---

configure.ac
tools/frr.in

...so we properly locate config files and daemons whereever the user
decided to put them.
Signed-Off-By: David Lamparter <equinox@diac24.net>

tools/frr: use path settings from ./configure

---

ospfd/ospf_lsa.c

Dead code removal for covering Coverity issue # 1302499
ospfd

ospfd: dead code (Coverity 1302499)

---

bgpd/bgp_route.c

Valgrind reports that temp could be used uninitialized
sometimes.
Signed-off-by: Donald sharp <sharpd@cumulusnetworks.com>

bgpd: prevent uninited variable from being used.

---

doc/user/bgp.rst

Improve documentation on using multiple autonomous systems in bgpd.
Fixes #3008 
Fixes #2201 
Fixes #2969 
doc

Doc bgpd multiple ASes

---

lib/command.c
lib/log.c
lib/log.h
lib/log_int.h

(defaults to disabled, preliminary version for testing)

[6.0] lib: add "log error-code" switch

---

bgpd/bgp_route.c

Fixes a load of stuff related to informational output regarding BGP communities, including dead code and ambiguous CLI commands.
Fixes #3084 
Fixes #2921 
bgpd

fix broken bgp community show cmds

---

bgpd/bgp_nht.c

Testing Done: bgp-smoke completed with no new failures
While testing 5549 support using global addresses, discovered that
ipv6 nexthop tracking thru a route-reflector didn't work.  Since
the next-hop used for remote nexthops resolves to the link-local
of the route-reflector, we need to track it in order to react to
interface down events.  Also tripped over a crash in certain cases
which is also resolved in this fix.
bgpd

bgpd: allow nht registration on ipv6 link-local addresses

---

bgpd/bgp_fsm.c
bgpd/bgp_network.c
bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/bgpd.c

1) Add ability to dump bgp peerhash
2) Track the peerhash a bit better

Bgp peerhash

---

lib/thread.c

This PR backport a memory leak fix from `master`. The affected systems of this bug are basically non Linux glibc users, which allocate memory when using `pthread_mutex_init` (e.g. FreeBSD, AddressSanitizer and maybe others).
This issue was originally found on `master` along with another bug on `thread_add_unused`, however the `5.0` version of the function is simpler and doesn't have the leak.
Commits:
* `lib: refactor thread_execute`: fix `thread_execute` `pthread_mutex` memory leak by standardising the code and removing the only thread API function corner case.
This fix originally was spotted and fixed in this PR: https://github.com/FRRouting/frr/pull/3087
And there is a back port for 6.0 too here: https://github.com/FRRouting/frr/pull/3170
`lib/thread.c`.

5.0: backport memory leak fix

---

tools/frr.in

Use a consistent indent style in the start stop script
tools

tools: reindent frr

---

bgpd/bgp_snmp.c

bgpd: fix missed info->path rename in snmp

---

isisd/isis_lsp.c

Fix `lsp-mtu` command. Command would be ineffective unless specified prior to LSP generation.
Fix crash on age-out of LSP fragments.

Bugfix: IS-IS fragmentation issues

---

bgpd/bgp_vty.c

Signed-off-by: Lakshman Krishnamoorthy lkrishnamoor@vmware.com
Route Server support for evpn address-family
bgpd
Always remember to follow proper coding style etc. as
described in the FRRouting Dev Guide.
http://docs.frrouting.org/projects/dev-guide/en/latest/workflow.html

bgpd: Route Server support for evpn address-family

---

bgpd/bgp_attr.c
bgpd/bgp_attr.h
bgpd/bgp_route.c

Add the ability for an aggregate route to have information about extended and large communities.

Aggregate ecommunity and lcommunity addition

---

Makefile.am
configure.ac
debianpkg/control
debianpkg/frr.dirs
debianpkg/frr.install
debianpkg/rules
vtysh/subdir.am

mostly Debian packaging cleanups, some autoconf stuff.
Refer to individual commits/titles for details...

Debian packaging & generic build stuff

---

bfdd/bfdd_vty.c
bgpd/bgp_damp.c
bgpd/bgp_lcommunity.c
bgpd/bgpd.c
bgpd/rfapi/bgp_rfapi_cfg.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_export_bgp.c
bgpd/rfapi/vnc_zebra.c
lib/routemap.c
ospf6d/ospf6_interface.c
ospfd/ospf_sr.c

This PR contains fixes for some bugs detected by the [CLI fuzzer](https://github.com/rwestphal/frr-cli-fuzzer/). There are still a few other bugs to fix but this is already a first step.
More details in the commit messages.

CLI fuzzer fixes

---

zebra/zebra_rib.c

on some cases, kernel routes are not selected, because the kernel
suppressed it without informing the netlink layer that the route has
been suppressed ( for instance, when an interface goes down, the route
never goes back when interface goes up again). This commit intends to
suppress that entry from zebra.
[fill here]
[bgpd, build, doc, ripd, ospfd, eigrpd, isisd, etc. etc.]
Always remember to follow proper coding style etc. as
described in the FRRouting Dev Guide.
http://docs.frrouting.org/projects/dev-guide/en/latest/workflow.html

zebra: remove kernel routes that are suppressed

---

vtysh/vtysh.c

vtysh: Add some missing daemons to some commands in vtysh

---

staticd/static_vty.c

Missed a cherry-pick somewhere, all of the code for actually displaying the `onlink` attribute of static routes in the config didn't make it into the first PR.
[CI test comment]
[staticd]

Finish onlink stuff

---

.gitignore
Makefile.am
config.version.in
configure.ac
doc/manpages/subdir.am
doc/user/subdir.am
lib/subdir.am
tests/subdir.am
tools/subdir.am
vtysh/subdir.am

Refer to individual commits :)
All of these are `dist` tarball or `clean` target related.

build: potpourri

---

bgpd/rfp-example/rfptest/subdir.am
configure.ac
ospfclient/subdir.am
redhat/frr.spec.in

Another 2 minor patches from build & packaging cleanup - commit titles say it all.

build: SNMP license, rfptest & ospfclient as noinst, redhat spec w/o CONFDATE

---

zebra/zebra_dplane.c

Current clang has an issue with the pointer/target argument
to at least one atomic/intrinsic: a variable with '_Atomic'
generates a compile-time error. Use a cast as a workaround
here to allow use of clang for now.
3259
zebra

zebra: temporary workaround for a clang issue with atomics

---

zebra/zebra_vty.c
zebra/zebra_vxlan.c
zebra/zebra_vxlan.h

Added the json output capability in order to improve troubleshooting
capabilities.
zebra

zebra: add json support to show evpn mac vni <num> mac <mac>

---

isisd/isis_lsp.c

Purged fragments would always be reoriginated by isisd. They
should only be purged once and never be reoriginated.

isisd: Fix issues with purged fragments

---

configure.ac

configure.ac: consistently quote all m4 macros

---

doc/developer/zebra.rst

* Add full version history with header diagrams
* Update field descriptions
* Update overview section
* Update list of protocol commands
doc

doc: update zebra protocol documentation

---

.github/PULL_REQUEST_TEMPLATE.md

Tired of deleting this thing, doubt people read it, and we have checkpatch anyway

.github: remove style reminder from PR template

---

bgpd/bgp_vty.c

https://github.com/FRRouting/frr/issues/3215
bgpd

bgpd: Remove community-list by name without typing full rule

---

doc/developer/workflow.rst

Add in the workflow the possibility to do long term support.

doc: change workflow to support long term maintenance branches

---

lib/distribute.c

ipv6 distribute-list name picked up was not the correct one. the
parameter number is modified accordingly.
Also, the unconfiguration of distribute-list ipv6 was conflicting with
other daemon, thus making impossible the unconfigration. The command has
been split to be specific to ipv6 distribute-list.

lib: distribute-list ipv6 can be (un)configured

---

pimd/pim_ifchannel.c
pimd/pim_zebra.c

add some breadcrumbs in a failure scenario and add a bit of code to back out built state when we discover an error condition.

Pim possible issues

---

configure.ac
lib/command.c
lib/if.c
lib/northbound_cli.c
lib/northbound_cli.h
lib/northbound_confd.c
lib/vty.h
lib/yang.c
lib/yang.h
lib/yang_translator.c
ripd/rip_cli.c
ripd/rip_northbound.c

This PR introduces some changes in northbound API intended to facilitate the process of retrofitting configuration commands to the new northbound model. Most of this work was inspired by some lessons learned with the IS-IS northbound conversion done by Emanuele.
For more details please check the commit messages.
[lib, ripd]

northbound: API improvements + minor fixes

---

bgpd/bgp_vty.c

https://github.com/FRRouting/frr/issues/3215
bgpd

bgpd: Remove extcommunity-list by name without typing full rule

---

staticd/static_vty.c

staticd: fix static analysis warnings

---

configure.ac
tests/lib/cli/common_cli.c
tests/lib/cli/test_cli.refout.in

master version of #3451, please discuss there.

[master] build reproducibility

---

lib/northbound_confd.c
lib/northbound_sysrepo.c

ConfD and Sysrepo implement configuration transactions using a
two-phase commit protocol (prepare + abort/apply). For network-wide
transactions to work, ConfD and Sysrepo move to the second phase of
the commit protocol only after receiving the results of the first
phase from all devices involved in the transaction. If all devices
succeed in the 'prepare' phase, then all of them move to the 'apply'
phase and the transaction is committed. On the other hand, if any
device fails in the 'prepare' phase, all of them move to 'abort'
phase and the transaction is aborted.
The confd and sysrepo plugins were implementing the full
two-phase commit protocol upon receiving a request to validate
the configuration changes and allocate all resources required to
apply them (first phase). The notifications …

lib: fix NETCONF network-wide transactions for confd and sysrepo

---

bgpd/bgp_addpath.c
bgpd/bgp_dump.c
bgpd/bgp_evpn.c
bgpd/bgp_evpn_vty.c
bgpd/bgp_flowspec_vty.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_nexthop.c
bgpd/bgp_nht.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
bgpd/bgp_rpki.c
bgpd/bgp_snmp.c
bgpd/bgp_table.c
bgpd/bgp_table.h
bgpd/bgp_updgrp_adv.c
bgpd/bgp_vpn.c
bgpd/bgp_vty.c
bgpd/bgp_zebra.c
bgpd/bgpd.c
bgpd/rfapi/rfapi.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_export_bgp.c
bgpd/rfapi/vnc_import_bgp.c
bgpd/rfapi/vnc_zebra.c

Continue the abstraction of `struct bgp_node` storing info pointers work that was being done.

Bgp node continued

---

isisd/fabricd.c
isisd/fabricd.h
isisd/isis_circuit.c
isisd/isis_circuit.h
isisd/isis_lsp.c
isisd/isis_lsp.h
isisd/isis_main.c
isisd/isis_pdu.c
isisd/isis_pdu.h
isisd/isis_pdu_counter.c
isisd/isis_pdu_counter.h
isisd/isis_tx_queue.c
isisd/isis_tx_queue.h
isisd/isis_vty_fabricd.c
isisd/isisd.c
isisd/isisd.h
isisd/subdir.am

Merging a few enhancements and optimizations made over isisd and fabricd code. Code has been extensively tested in a scaling setup.
[isisd, fabricd]

Isisd and fabricd enhancements

---

zebra/zebra_rib.c

The set value was only being used as a bool, formalize this
in the call chain.

zebra: Convert nexthop_active functions to use bool

---

lib/zebra.h
zebra/kernel_socket.c

Cleanup the ZEBRA_FLAG_XXX flags in zebra.h and additionally provide some small documentation on what each one is supposed to do

zebra.h ZEBRA_FLAG_XXX cleanup

---

tests/topotests/lib/topotest.py

a couple of fixes for topotests see the individual commits

Topotests fixup

---

bfdd/bfdd_vty.c
bgpd/bgp_damp.c
bgpd/bgp_lcommunity.c
bgpd/bgpd.c
bgpd/rfapi/bgp_rfapi_cfg.c
bgpd/rfapi/rfapi_import.c
bgpd/rfapi/rfapi_vty.c
bgpd/rfapi/vnc_export_bgp.c
bgpd/rfapi/vnc_zebra.c
ospf6d/ospf6_interface.c
ospfd/ospf_sr.c

Backport of #3209 to stable/6.0.
Fixes #3476

[6.0] Cli fuzzer fixes

---

bgpd/bgp_nexthop.c
zebra/zebra_vty.c

those 2 commits add 2 vty commands that permit to dump bgp nexthop imported table for both zebra and bgp

Show import table

---

tools/etc/frr/vtysh.conf
tools/frr.service
tools/frrcommon.sh.in

[master] minor tools/ fixes

---

tools/etc/frr/vtysh.conf
tools/frr.service
tools/frrcommon.sh.in

See commits, just some small bits.

[6.0] minor tools/ fixes

---

doc/user/zebra.rst

doc: add `ip nht resolve-via-default`

---

debian/control
debian/frr.postinst
doc/developer/packaging-debian.rst
tools/frrcommon.sh.in
watchfrr/watchfrr.c

Just some small issues that showed up during testing the new Debian package.  (Will port the entire batch to master in one go with the entire Debian re-packaging.)

6.0 fixes from package testing

---

eigrpd/eigrp_dump.c
eigrpd/eigrp_network.c
eigrpd/eigrp_structs.h
eigrpd/eigrp_vty.c
eigrpd/eigrpd.c

Some commits to cleanup handling of the eigrp router-id command.  Not sure it's 100% yet but it's better than before.

Eigrp router id cleanup

---

isisd/isis_northbound.c

cherry-pick of the `isis network point-to-point` fix from master
N/A
isisd

[dev/7.0] isisd: fix point-to-point network type config

---

doc/user/installation.rst

Fix typos and grammar in doc
[doc]

doc: Fix typos and grammar

---

zebra/zebra_rnh.c
zebra/zebra_rnh.h

A couple of small commits that cleanup some code in zebra_rnh.c

Small cleanup of zebra_rnh.c code

---

bgpd/bgp_flowspec_util.c
bgpd/bgp_flowspec_util.h
bgpd/bgp_nht.c
bgpd/bgp_pbr.c
bgpd/bgp_pbr.h

support for flowspec nexthop tracking.

Flowspec support nh tracking

---

lib/prefix.h
sharpd/sharp_vty.c
sharpd/sharp_zebra.c

1) Add ability to install/remove v6 routes
2) Add ability to subtract! and give me time results in the code.

Sharp v6 and stuff

---

configure.ac
doc/user/installation.rst

add a bit more warning around enable-shell access and add more documentation about configure options to our doc stuff

more doc stuff for configure

---

lib/command.c
lib/vty.c

Please see the commit messages for details.

Fix CLI issue introduced by the northbound + simplifications

---

bgpd/bgp_network.c
lib/vrf.c
lib/vrf.h
lib/zclient.c
staticd/static_vty.c
zebra/zapi_msg.c
zebra/zserv.c

Small code cleanup, please see the commit messages for details.
Edit: the first commit actually fixes an existing bug, which I only realized later (that's why code cleanups are important :)).

Send VRF backend to the client daemons

---

zebra/rt.h
zebra/rt_netlink.c
zebra/rt_netlink.h
zebra/rt_socket.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_mpls.c
zebra/zebra_mpls.h
zebra/zebra_mpls_netlink.c
zebra/zebra_mpls_null.c
zebra/zebra_mpls_openbsd.c
zebra/zebra_rib.c
zebra/zebra_vrf.h

Phase 3 of the async dataplane: move lsp installation and updates to the async dataplane subsystem, and remove the sync code path.
zebra

Async dataplane: support mpls lsps

---

zebra/zapi_msg.c
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_rnh.h
zebra/zebra_routemap.c
zebra/zebra_routemap.h
zebra/zebra_vty.c

zebra: fix the "show ip import-check" command

---

configure.ac

After much discussion we have decided to update the version of master
to 7.1 dev.

*: Convert to new version number

---

Makefile.am
configure.ac
lib/frr_pthread.c

With these changes FRR almost compiles on Mac OS. There are two more issues for which I have patches but they need more work.

A few small build fixes for Mac OS

---

pimd/pim_static.c

Pim static air crash

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn.h
bgpd/bgp_vty.c
bgpd/bgp_zebra.c
include/linux/if_addr.h
include/subdir.am
lib/if.h
lib/zclient.h
zebra/connected.c
zebra/connected.h
zebra/if_ioctl.c
zebra/if_ioctl_solaris.c
zebra/if_netlink.c
zebra/kernel_socket.c
zebra/zebra_vty.c
zebra/zebra_vxlan.c
zebra/zebra_vxlan_private.h

Bunch of EVPN fixes, please see individual bugs for detailed info.

Asundry EVPN fixes

---

configure.ac
doc/developer/building-libyang.rst
doc/user/installation.rst
lib/yang.c
yang/libyang_plugins/subdir.am

Master version of #3663, please comment there.

yang: embed extensions

---

lib/route_types.pl
zebra/rt_socket.c
zebra/zebra_fpm_netlink.c
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_vty.c

1) Moves marking of routes as installed to be owned by the route_entry
2) Marks routes queued for work with a flag so we can `'know' what is going on a bit more
3) Cleans up some issues found in rt_socket.c

Route notification

---

zebra/if_netlink.c

The ifa_flags value in the netlink message was originally a uint8_t
value.  The linux kernel quickly ran out of 8 bits of data to
pass and the IFA_FLAGS value was added to the netlink message to allow
more than 8 bits of data to be passed.  So replace the ifa_flags
with the IFA_FLAGS value if it exists in the interface netlink
message.

zebra: Use the kernel flags from the IFA_FLAGS if it is available

---

include/linux/mroute.h
include/subdir.am

include: Add linux header mroute.h to our build

---

zebra/redistribute.c
zebra/rt_netlink.c
zebra/zebra_rib.c

1) Modify zebra rib debug detail to output the route name instead of a number
2) Modify the nexthop active code to say screw it the kernel is giving me a route, I need to track and trust it.
3) Modify the netlink code to read the onlink flag from the kernel and pass it up.

Zebra Respect my authority

---

bgpd/bgp_aspath.c

bgpd: fix as-path prepend heap uaf

---

lib/route_types.pl
zebra/rt_netlink.c
zebra/zebra_vty.c

1) Clean up some duplicate work in the building of netlink messages to the kernel
2) Cleanup accidental reuse of 'f'

Netlink is serious business

---

doc/user/routemap.rst

doc: fix missing backtick

---

eigrpd/eigrp_dump.c
eigrpd/eigrp_dump.h
eigrpd/eigrp_interface.c
eigrpd/eigrp_topology.c
eigrpd/eigrp_vty.c
eigrpd/eigrp_zebra.c
eigrpd/eigrp_zebra.h
tests/topotests/eigrp-topo1/r1/show_ip_route.json_ref
tests/topotests/eigrp-topo1/r2/show_ip_route.json_ref
tests/topotests/eigrp-topo1/r3/show_ip_route.json_ref
tests/topotests/eigrp-topo1/test_eigrp_topo1.py

Fix a couple of eigrp issues filed over last week.  See individual commits for details

Eigrp metric

---

zebra/zebra_rib.c
zebra/zebra_vty.c

A couple of zebra fixes. see individual commits

Zebra fixes

---

lib/log.c
lib/log.h

cherry-pick to 6.0 of the commit merged in master with #3674

[6.0.3] lib: add hooks for external logging function

---

lib/log.c
lib/log.h

cherry-pick to 7.0 of the commit merged in master with #3674
(as requested in #3742)

[7.0] lib: add hooks for external logging function

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/bgpd-service
snapcraft/scripts/fabricd-service
snapcraft/snapcraft.yaml.in

snap package update for 7.0
- Updated RTRLIB in Snap Package from 0.5.0 to 0.6.3
- Add Libyang 0.16.105 library
- Add FabricD
- Minor fixes

[7.0] Snap Package Update for 7.0

---

vtysh/vtysh.c

vtysh: Fix typo in function name

---

pbrd/pbr_map.c
pbrd/pbr_zebra.c

Add some debugs from events that can happen that will
influence our pbr behavior.

pbrd: Add some missing debugs from external events

---

bgpd/bgp_aspath.c

[6.0] bgpd: fix as-path prepend heap uaf

---

bgpd/bgp_aspath.c

[7.0] bgpd: fix as-path prepend heap uaf

---

tests/topotests/bgp_l3vpn_to_bgp_vrf/customize.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py

Fix setting of TCP l3mdev (was setting UDP)
also add test to see that it is set as expected

topotest: bgp_l3vpn_to_bgp_vrf: fix setting of TCP l3mdev

---

doc/user/sharp.rst
sharpd/sharp_vty.c
sharpd/sharp_zebra.c
sharpd/sharp_zebra.h

Add the ability for sharp to track import-check type nexthops.

Sharp import check

---

lib/privs.c

lib: fix uninitialized value use in privs.c

---

sharpd/Makefile

build: non-recursive sharpd

---

bgpd/bgp_vty.c

increase the range of some graceful timer values from 1-3600 to 1-4095.

Graceful restart range

---

ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6_interface.c
ospf6d/ospf6_main.c
ospf6d/ospf6_network.c
ospf6d/ospf6_network.h

this gathers some ospfv3 fixes related to memory leak when leaving, and some sanity checks.

Ospfv3 misc fixes

---

isisd/isis_lsp.c

[master] isisd: skip over deleted fragments

---

isisd/isis_lsp.c

Since LSP fragments are also on our lspdb dict, lsp_tick() needs to skip
over them after calling lsp_destroy().  Otherwise it ends up accessing
free'd memory.
Fixes: #3533
Signed-off-by: David Lamparter <equinox@diac24.net>

[7.0] isisd: skip over deleted fragments

---

pbrd/pbr_map.c
pbrd/pbr_map.h
pbrd/pbr_vty.c
pbrd/pbr_zebra.c

Couple of bug fixes of pbr found from some testing.

Pbr massacre at 5

---

doc/developer/_static/overrides.css
doc/developer/conf.py
doc/user/_static/overrides.css
doc/user/conf.py
doc/user/vtysh.rst

[master] doc: VTYSH_PAGER docs + new FRR theme

---

doc/developer/_static/overrides.css
doc/developer/conf.py
doc/user/_static/overrides.css
doc/user/conf.py
doc/user/vtysh.rst

[7.0] doc: VTYSH_PAGER docs + new FRR theme

---

doc/developer/_static/overrides.css
doc/developer/conf.py
doc/user/_static/overrides.css
doc/user/conf.py
doc/user/vtysh.rst

[6.0] doc: VTYSH_PAGER docs + new FRR theme

---

lib/command.h
pimd/pim_cmd.c

Add `test pim keepalive-reset A.B.C.D A.B.C.D` command to pim

---

bgpd/bgp_addpath.c
bgpd/bgp_route.c
isisd/isis_cli.c
pbrd/pbr_nht.c
pbrd/pbr_vty.c

More cli fuzzer fizes

---

bgpd/bgp_addpath.c
bgpd/bgp_route.c
isisd/isis_cli.c
pbrd/pbr_nht.c
pbrd/pbr_vty.c

A couple of last-minute fixes for 7.0...

[7.0] More cli fuzzer fixes

---

bgpd/bgp_open.c
bgpd/bgp_open.h

bgpd: capabilty

---

zebra/if_netlink.c

L3VNI keeps reference to svi interface (ifp).
When a netlink change received there is no flag that mac has changed. 
Currently simply overwrite interface's (ifp) hw_addr (MAC) field.
For originating EVPN type-2 and type-5 routes due to VNI MAC change, 
comparison is required to check existing MAC vs. netlink change MAC field.
Testing Done:
Validate EVPN type-5 routes originated upon changing MAC address
of L3VNI's SVI inteface via ip link set cmd.
checked show bgp l2vpn evpn route and rmac field contains new MAC address.
zebra

zebra: advertise evpn route upon l3vni svi mac chg

---

bgpd/bgp_mplsvpn.c
bgpd/bgp_route.h
bgpd/bgp_zebra.c

A couple of small fixes to make 6VPE (L3VPN for IPv6) work again.
This probably needs to go to 7.0 as well, but I'll wait for the review comments first.
[bgpd]

6VPE fixes

---

bgpd/bgp_mplsvpn.c
bgpd/bgp_route.h
bgpd/bgp_zebra.c

[7.0] 6VPE fixes

---

bgpd/bgpd.c

cherry picking from https://github.com/FRRouting/frr/commit/afad5cedf1be827238b376e63b0b93bb555c928e

bgpd: [7.0] Add peer action for PEER_FLAG_IFPEER_V6ONLY flag

---

ripd/rip_cli.c

[7.0] ripd: fix removal of configured passive interfaces

---

include/linux/if_addr.h
include/subdir.am
lib/if.h
zebra/connected.c
zebra/connected.h
zebra/if_ioctl.c
zebra/if_ioctl_solaris.c
zebra/if_netlink.c
zebra/kernel_socket.c
zebra/zebra_rib.c
zebra/zebra_vty.c

Some fixes for 6.0 from master

Connected 6.0

---

pimd/pim_cmd.c
pimd/pim_igmp_mtrace.c
pimd/pim_join.c
pimd/pim_jp_agg.c
pimd/pim_mroute.c
pimd/pim_nht.c
pimd/pim_nht.h
pimd/pim_oil.c
pimd/pim_oil.h
pimd/pim_rp.c
pimd/pim_rp.h
pimd/pim_rpf.c
pimd/pim_rpf.h
pimd/pim_upstream.c
pimd/pim_upstream.h
pimd/pim_zebra.c

[fill here]
[bgpd, build, doc, ripd, ospfd, eigrpd, isisd, etc. etc.]

Rp addition deletion changes

---

tools/etc/frr/daemons

tools: fix two typos in daemons file

---

lib/privs.c

Privs changes are process-wide, and we made a recent attempt to help resolve races (and a deadlock) when we need to use the privs change apis in a multi-threaded process. I think that work didn't quite go far enough: the caller was not guaranteed that the privs had actually been changed. This commit uses the privs struct mutex more strictly, to ensure that the privs are at the level the caller expects when the apis return.
libs

libs: fix race in privs changes

---

doc/manpages/defines.rst

i used the github editor cuz i didnt want to change my local branch
will delete branch after merge

doc: include fabricd in see-also programs

---

doc/developer/building-frr-for-centos6.rst
doc/developer/building-frr-for-centos7.rst
doc/developer/building-frr-for-fedora24.rst
doc/developer/building-frr-for-freebsd10.rst
doc/developer/building-frr-for-freebsd11.rst
doc/developer/building-frr-for-freebsd9.rst
doc/developer/building-frr-for-openwrt.rst
doc/developer/hooks.rst
doc/developer/logging.rst
doc/developer/memtypes.rst
doc/developer/ospf-api.rst
doc/developer/ospf-sr.rst
doc/developer/topotests-snippets.rst
doc/developer/topotests.rst
doc/developer/vtysh.rst
doc/developer/workflow.rst
doc/user/basic.rst
doc/user/bgp.rst
doc/user/flowspec.rst
doc/user/installation.rst
doc/user/ospfd.rst
doc/user/pbr.rst
doc/user/pim.rst
doc/user/sharp.rst
doc/user/zebra.rst

Found with https://github.com/codespell-project/codespell
doc

doc: fix a couple of typos

---

bgpd/bgp_rpki.c

Add command to lookup prefixes in the rpki table
[bgpd]

bgpd: add command to lookup prefixes in the rpki table (stable/7.0)

---

zebra/zebra_vxlan.c

When MAC or IP deleted ensure to cleanup DAD timers.
Signed-off-by: Chirag Shah <chirag@cumulusnetwork.com>
[zebra]

zebra: evpn mac ip dup detect (DAD) timers cleanup

---

doc/developer/building-frr-for-fedora.rst
doc/developer/building-frr-for-fedora24.rst
doc/developer/building-frr-for-ubuntu1404.rst
doc/developer/building-frr-for-ubuntu1604.rst
doc/developer/building-frr-for-ubuntu1804.rst
doc/developer/building.rst
doc/developer/conf.py
doc/developer/include-compile.rst
doc/developer/subdir.am

Update build documentation for:
* Fedora 24+ (tested 24, 28)
* Ubuntu 14.04
* Ubuntu 16.04
* Ubuntu 18.04
More to come

update build docs - Fedora, Ubuntu

---

include/linux/if_addr.h
include/subdir.am
lib/if.h
zebra/connected.c
zebra/connected.h
zebra/if_ioctl.c
zebra/if_ioctl_solaris.c
zebra/if_netlink.c
zebra/kernel_socket.c
zebra/zebra_rib.c
zebra/zebra_vty.c

Some double commits from code in master

Connected 7.0

---

bgpd/bgp_route.c

master version of https://github.com/FRRouting/frr/pull/4036

bgpd: fix show bgp labeled_unicast

---

pimd/pim_ifchannel.c
pimd/pim_mroute.c
pimd/pim_register.c
pimd/pim_rp.c
pimd/pim_rp.h
pimd/pim_upstream.c
pimd/pim_zebra.c
pimd/pim_zlookup.c

See individual commits for what is being done.  Some simple pim cleanups.

Pim cleanup

---

pimd/pim_cmd.c
pimd/pim_igmp_mtrace.c
pimd/pim_mroute.c
pimd/pim_neighbor.c
pimd/pim_nht.c
pimd/pim_nht.h
pimd/pim_rp.c
pimd/pim_rp.h
pimd/pim_rpf.c
pimd/pim_rpf.h

A couple of cleanups to make the pim code better/easier to read

Pim cherrybomb

---

bgpd/rfapi/vnc_debug.c
lib/thread.c
pbrd/pbr_zebra.c
pimd/pim_cmd.c
zebra/kernel_socket.c

Some code cleanup commits
1) remove undebug commands
2) cleanup size printf formaters

some cleanup across multiple daemons

---

doc/developer/ospf-sr.rst

doc: fix typo

---

pimd/pim_ifchannel.c
pimd/pim_upstream.c

See individual commits for description of fixes.

Pim cleanups

---

lib/vrf.c

If `tcp_l3mdev_accept = 0`, then creating a socket for a vrf
for communication is allowed.  On the other hand if it is =1
then the `vrf_socket()` code assumes that we have created
a listen socket in the default vrf.  This is a bad assumption
in that it is perfectly valid to create a bgp instance like this:
```
router bgp 99 vrf BLUE
<configuration>
!
```
But not to create a default bgp instance.  As such when BGP
would call the `vrf_socket` to create the listener for that vrf
the code was dissallowing it.
This code is incorrect behavior.  If we are passing in a interface
to bind the socket to, it is not the correct behavior to just not
bind, especially if the interface passed in is not a vrf name.

lib: Allow bgp to always create a listen socket for the vrf

---

isisd/isis_misc.c
lib/libfrr.c
lib/log.h
lib/log_int.h
lib/northbound.c
lib/northbound_sysrepo.c
lib/yang.c
zebra/zebra_rib.c

A couple of small fixes and improvements in the northbound code.

northbound minor fixes and improvements

---

lib/privs.c
lib/privs.h

Trying out yet-another improvement to privs management: on OSes where privs are process-wide, use a single shared refcount to control privs changes. On OSes where privs apis are per-pthread, use a refcount per-pthread.

lib: serialize privs changes

---

isisd/isis_circuit.h
isisd/isis_cli.c
isisd/isis_lsp.c
isisd/isis_northbound.c
isisd/isis_pdu.c
isisd/isis_te.c
isisd/isis_te.h
isisd/isis_zebra.c
isisd/isisd.c
isisd/isisd.h
yang/frr-isisd.yang

Revert "isisd: Add IS-IS-TE support per Area"

---

bgpd/bgp_filter.c
bgpd/bgp_filter.h
bgpd/bgp_route.c

bgpd: Validate as-path in `show bgp regexp`

---

doc/user/pim.rst
pimd/pim_cmd.c

add a selector to the `show ip mroute ` command, update docs

Mroute show

---

bgpd/bgp_filter.c
bgpd/bgp_route.c

doc: Specify allowed chars in bgp regular expressions

---

bgpd/bgp_filter.c
bgpd/bgp_filter.h
bgpd/bgp_route.c

bgpd: [7.0] Validate as-path in `show bgp regexp`

---

doc/user/pim.rst

The PIM-EVPN doc was not rendering very well on the
website.  So Update documentation to allow it to render
better.

doc: Cleanup output of new PIM-EVPN doc

---

bgpd/bgp_vty.c

Closes https://github.com/FRRouting/frr/issues/1644

bgpd: Make sure `next-hop-self all` backward compatible with force

---

pimd/pim_cmd.c

the json code has not been updated since a variety of new flags have
been added to the code base.  Add those flags in so we can tell
what is going on sometimes.

pimd: Add missing flags to json output

---

bgpd/bgp_vty.c

bgpd: [6.0] Make sure `next-hop-self all` backward compatible with force

---

bgpd/bgp_vty.c

bgpd: [5.0] Make sure `next-hop-self all` backward compatible with force

---

bgpd/bgp_vty.c

bgpd: [7.0] Make sure `next-hop-self all` backward compatible with force

---

vtysh/vtysh.c

The exit of the nexthop-group should know about sharpd

vtysh: Fixup exit nexthop-group to include sharpd

---

bgpd/bgp_route.c

Signed-off-by: Faicker Mo <faicker.mo@ucloud.cn>

bpgd: Add the end of newline of show bgp table json output

---

tests/topotests/lib/topogen.py

Some small changes to improve support for both python 2 and 3.

topotest: fixes to support python3

---

doc/developer/lists.rst
lib/prefix.c
lib/prefix.h
lib/table.c
lib/table.h
lib/typesafe.h
tests/topotests/bgp_rfapi_basic_sanity/scripts/cleanup_all.py
zebra/rib.h
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_rnh.h
zebra/zebra_vrf.c

Revert "Zebra diet"

---

bgpd/bgp_nexthop.c
bgpd/bgp_nexthop.h
bgpd/bgp_route.c
bgpd/bgpd.c
bgpd/bgpd.h
lib/jhash.c
lib/jhash.h

Revert "bgpd: Prevent IPv6 routes received via a ibgp session with own ip as nexthop "

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_mplsvpn.c
lib/vrf.c
ospfd/ospf_packet.c
pbrd/pbr_zebra.c
zebra/zebra_dplane.c
zebra/zebra_rib.c

A bunch of coverity issues that I've gone through and cleaned up.

Coverity stole my sanity

---

lib/frrstr.c
lib/frrstr.h

This is going to replace the unsafe one used in `northbound.c`

lib: add string replace function

---

bgpd/bgp_rpki.c

Add a missing newline to a warning in the rpki module and fix rpki module build without ssh support(#4221).

RPKI fixes/improvements

---

bgpd/bgp_evpn_vty.c

**Issue1**:
The following json cli commands are broken (they dont display anything):
1) `show [ip] bgp l2vpn evpn json`
2) `show [ip] bgp l2vpn evpn all neighbors <IP> routes json`
3) `show [ip] bgp l2vpn evpn rd <RD> json`
4) `show [ip] bgp l2vpn evpn rd <RD> neighbors <IP> routes json`
**RCA1**:  The existing json_object was partially filled. Some fields like "prefix", "prefixLen", etc were not filled in the json_object.
**RCA2**: Code missing to display the constructed json_object. 
**Issue2**:
Column header not displayed for the above evpn cli commands.
Fix: header flagged is set to true
**Output after fix:**
The above commands have been made to follow the existing output style of `show bgp l2vpn evpn routes json`
leaf-1# sh bgp l2vpn evpn json
{
"bgpTableVersion":1, …

bgpd: Fix for evpn json cli output

---

.gitignore

https://github.com/MaskRay/ccls
Ignore the cache dir for this thing

.gitignore: ignore .ccls-cache

---

doc/user/bgp.rst

doc: add doc for bgp maximum-prefix knob

---

doc/developer/lists.rst
lib/prefix.c
lib/prefix.h
lib/table.c
lib/table.h
lib/typesafe.h
zebra/rib.h
zebra/zebra_rib.c
zebra/zebra_rnh.c
zebra/zebra_rnh.h
zebra/zebra_vrf.c

1) Doc update
2) Changes to zebra and table to use new data structures.  Reduces memory for 1 million routes in zebra from 675 - 542mb on my system

Zebra diet

---

bgpd/bgp_route.c
tests/topotests/bgp_ebgp_requires_policy/r1/bgpd.conf
tests/topotests/bgp_ebgp_requires_policy/r1/zebra.conf
tests/topotests/bgp_ebgp_requires_policy/r2/bgpd.conf
tests/topotests/bgp_ebgp_requires_policy/r2/zebra.conf
tests/topotests/bgp_ebgp_requires_policy/r3/bgpd.conf
tests/topotests/bgp_ebgp_requires_policy/r3/zebra.conf
tests/topotests/bgp_ebgp_requires_policy/r4/bgpd.conf
tests/topotests/bgp_ebgp_requires_policy/r4/zebra.conf
tests/topotests/bgp_ebgp_requires_policy/test_bgp_ebgp_requires_policy.py

bgpd: Move inbound policy check outside bgp_input_modifier()

---

zebra/zebra_mpls.c

Try to remove any LSPs associated with a vrf when the vrf is deleted. The vrf code was calling a helpful zebra_mpls api, but that api was basically a no-op for vrfs other than the default.

zebra: remove vrf LSPs when vrf is deleted

---

doc/user/zebra.rst

Add some simple notes about the clis associated with the zebra dataplane.

doc: add cli doc for zebra dplane cli

---

bgpd/bgp_evpn_vty.c

Bug: If there are 2 different prefixes under an rd, the
output of "show bgp l2vpn evpn json" would print only one of the
prefixes.
RCA: prefix info was added to the json_object once per rd. Hence,
prefix and rd were added just once, as the loop iterated over all
the prefixes and paths.
This is related to my earlier commit that went in via PR 4283:
https://github.com/FRRouting/frr/pull/4283
Signed-off-by: Lakshman Krishnamoorthy <lkrishnamoor@vmware.com>

bgpd: evpn json cli bug fix

---

zebra/zebra_mpls.c

7.1 version: Try to remove any LSPs associated with a vrf when the vrf is deleted. The vrf code was calling a helpful zebra_mpls api, but that api was basically a no-op for vrfs other than the default.

zebra: [7.1] remove vrf LSPs when vrf is deleted

---

zebra/zebra_vty.c

"show ip/ipv6 route <prefix> [json]" uses a different parser chain from
"show ip/ipv6 route [json]".
"show ip/ipv6 route <prefix> [json]" CLI does not support "fib" option.
Fix:
Add "fib" option to the above command.
The new command is: "show ip/ipv6 <route/fib> <prefix> [json]"
If "fib" option is specified, we will show only the selected routes
(Similar to "show ip/ipv6 fib")
Signed-off-by: Ameya Dharkar <adharkar@vmware.com>

Zebra: Add "show ip/ipv6 fib <prefix> [json]" CLI

---

doc/developer/topotests.rst
tests/topotests/bgp_l3vpn_to_bgp_vrf/ce1/bgpd.conf
tests/topotests/bgp_l3vpn_to_bgp_vrf/ce2/bgpd.conf
tests/topotests/bgp_l3vpn_to_bgp_vrf/r3/bgpd.conf
tests/topotests/bgp_l3vpn_to_bgp_vrf/r4/bgpd.conf
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_down.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/test_bgp_l3vpn_to_bgp_vrf.py
tests/topotests/lib/ltemplate.py
tests/topotests/lib/topogen.py

change 'num = 50000' at top of topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py for more/less routes
same routes advertise from different CEs so core sees 2xnum.  Tested up to num=100K
Here's sample output that can be found in artefacts/summary.txt or output.log
```
FILE: scripts/scale_up.py
99   ce1    Adding 50000 routes                                      1    0
100  ce2    Adding 50000 routes                                      1    0
101  ce1    RXed last route, 10.0.195.79 +34.75 secs                 1    0
102  ce1    See all sharp routes in BGP +0.86 secs                   1    0
103  ce2    RXed last route, 10.0.195.79 +0.15 secs                  1    0
104  ce2    See all sharp routes in BGP +0.33 secs                   1    0
105  ce3    RXed last route, 10.0.195.79 +0.24 …
```

bgp_l3vpn_to_bgp_vrf: test adding/removing 50K*2CEs VRF routes

---

zebra/rtadv.c
zebra/rtadv.h
zebra/zebra_ns.c
zebra/zebra_router.h
zebra/zebra_vrf.c
zebra/zebra_vrf.h

These 2 commits fundamentally broke bgp unnumbered from working.  Back out and let developer try again.

Revert rtadv changes

---

lib/plist.c

Closes https://github.com/FRRouting/frr/issues/4382

plist: Delete prefix-list by sequence number

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/bgpd-service
snapcraft/scripts/fabricd-service
snapcraft/snapcraft.yaml.in

[7.1] Snap fixes for 7.1

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/bgpd-service
snapcraft/scripts/fabricd-service
snapcraft/snapcraft.yaml.in

Snap Package fixes for master branch
Signed-off-by: Martin Winter mwinter@opensourcerouting.org

Snap fix master

---

isisd/isis_route.c
isisd/isisd.c

isisd: del routes when area is unconfigured

---

lib/linklist.c
lib/linklist.h

lib: const a couple linklist apis

---

lib/plist.c

plist: [7.0] Delete prefix-list by sequence number

---

lib/plist.c

plist: [7.1] Delete prefix-list by sequence number

---

lib/plist.c

plist: [6.0] Delete prefix-list by sequence number

---

bgpd/bgp_zebra.c
zebra/zebra_rib.c

1) Make bgp send down admin distance in all cases
2) rib extra check for ibgp distance in rib_add_multipath

Bgp distance comes closer

---

lib/libfrr.c
lib/northbound.c

gcc 9 has found some new stuff to be fixed

Fix warnings

---

doc/developer/workflow.rst

(and document that ASAN/MSAN/TSAN are mutually exclusive while at it)

doc: add libtool note

---

bgpd/bgp_route.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

A couple of bgp commands have been deprecated for a year, remove them.  See individual commits for work.

Deprecate bgp

---

bgpd/bgp_evpn.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
bgpd/bgp_rpki.c
bgpd/bgp_updgrp_adv.c
eigrpd/eigrp_routemap.c
isisd/isis_routemap.c
lib/routemap.c
lib/routemap.h
ospf6d/ospf6_asbr.c
ospfd/ospf_routemap.c
ospfd/ospf_zebra.c
ripd/rip_routemap.c
ripngd/ripng_routemap.c
zebra/redistribute.c
zebra/zebra_nhg.c
zebra/zebra_rnh.c
zebra/zebra_routemap.c

Reverting commits to take care of compiler errors.
Signed-off-by: Lakshman Krishnamoorthy <lkrishnamoor@vmware.com>

Revert of PR 4078 and PR 4315

---

babeld/message.c
bfdd/bfd_packet.c
bgpd/bgp_mpath.c
bgpd/rfapi/rfapi_import.c
lib/vty.c
nhrpd/vici.c
ripngd/ripng_interface.c

Propose fixes for several SA warnings.

bgpd,babeld,bfdd,lib,ripngd,nhrpd: clean up SA warnings

---

eigrpd/eigrp_routemap.c
eigrpd/eigrp_vty.c

eigrpd: fix invalid command definitions

---

lib/nexthop_group.c
pbrd/pbr_vty.c
sharpd/sharp_vty.c
vtysh/vtysh.c

Allow nexthop-group X tab-complete
Allow pbr-map Y tab-complete

Pbr tab complete

---

bgpd/bgpd.c

Related: https://github.com/FRRouting/frr/issues/4438

bgpd: [5.0] Fix bgp auto-shutdown behavior

---

lib/plist.c

plist: [5.0] Delete prefix-list by sequence number

---

pimd/pim_zlookup.c

When pim is started and has nothing to talk to zebra about
over the zlookup socket and interface events are happening
then the zlookup socket is not being drained.
This eventually leads to a situation where the kernel send buffer
fills up and zebra is unable to write anything down the pipe.
At this time the zapi starts buffering data in `struct buffer`
which of course slowly fills up as pim has nothing to do.
As a bit of a hack allow the zlookup socket to wake up 1 time
a minute and ask for information about the default route
and do nothing with it.  This will cause the socket buffers
to be drained and the system will be happy.
Long term we need to get rid of this synchronous/asynchronous
duality that pim has.  This is on the radar but is not something
that could be fixed in an afternoon …

pimd: Allow zlookup socket to drain

---

lib/plist.c
lib/printf/printf-pos.c
lib/sockopt.c
lib/thread.c
pimd/pim_cmd.c
pimd/pim_mroute.c
sharpd/sharp_vty.c
sharpd/sharp_zebra.c

Various compiler cleanups gleaned from our CI build logs.

More compiler cleanup

---

docker/debian/Dockerfile

Utilizes debian buster and the support libyang from the vendor.

Docker binary image on Debian Buster

---

tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_down.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py

address issue #4515 by doubling the amount of time willing to wait for routes added by sharpd

tests/topotests: bgp_l3vpn_to_bgp_vrf address issue #4515

---

lib/prefix.c
tests/.gitignore
tests/lib/test_prefix2str.c
tests/lib/test_prefix2str.py
tests/subdir.am

eliminate snprintf from AF_INET/AF_INET6 prefix2str, add prefix2str test

---

zebra/kernel_netlink.c
zebra/zserv.c

Update the fuzzing code to compile again.

zebra: Fuzzing code has gotten a bit out of date

---

bgpd/bgp_vty.c
bgpd/bgpd.c
doc/user/bgp.rst

bgpd: List all groups dynamically for commands with peer-group

---

doc/user/setup.rst

Add some instructions and clarity around restarting and reloading FRR.

Document FRR service manipulation

---

pimd/pim_igmpv3.c
pimd/pim_mroute.c
pimd/pim_oil.c
pimd/pim_oil.h
pimd/pim_upstream.c
pimd/pim_zebra.c

Add some additional debugs for helping us debug pim issues

Pim debugs

---

bgpd/bgp_mac.c

Skip evpn routes marked for removed from re-scan list
when an interface is flapped.
Testing Done:
Validated in a scenario where evpn route is marked
for remove as bgp evpn withdrawal is received. Due to
link flap (frr restart of downstream router), the route
was considered for re-add via bgp_update. With this
fix, the remove marked routes are skipped from update.

bgpd: skip evpn remove marked routes from rescan

---

bgpd/bgp_vty.c
bgpd/bgpd.c
doc/user/bgp.rst

bgpd: [6.0] List all groups dynamically for commands with peer-group

---

bgpd/bgp_vty.c
bgpd/bgpd.c
doc/user/bgp.rst

bgpd: [7.0] List all groups dynamically for commands with peer-group

---

README.md

README.md: add VRRP to list of protocols

---

bgpd/bgp_filter.c
bgpd/bgp_route.c

Related: https://github.com/FRRouting/frr/issues/986

doc: [7.0] Specify allowed chars in bgp regular expressions

---

bgpd/bgp_vty.c
bgpd/bgpd.c
doc/user/bgp.rst

bgpd: [7.1] List all groups dynamically for commands with peer-group

---

pimd/pim_ifchannel.c

See individual commits for what is being done.

Pim bug fixes

---

lib/vty.c
pimd/pim_assert.c
pimd/pim_bsm.c
pimd/pim_cmd.c
pimd/pim_iface.c
pimd/pim_ifchannel.c
pimd/pim_mroute.c
pimd/pim_static.c
pimd/pim_upstream.c
pimd/pim_zebra.c

1) Possible thread pointer drop in vty.c
2) Removal of unnecessary NULL checks in pim
3) Ensure upstream creates the channel oil

Some cleanups

---

staticd/static_nht.c
zebra/zebra_rnh.c

See individual commits to know what is going on but issue reported in frog alias.

Nexthop Tracking and Static route fix

---

bgpd/bgp_filter.c
bgpd/bgp_route.c

Closes https://github.com/FRRouting/frr/issues/986

bgpd: [5.0] Validate as-path access-list before continuing regarding invalid

---

bgpd/bgp_nht.c
bgpd/bgp_routemap.c
bgpd/bgp_updgrp.c
bgpd/bgpd.c
eigrpd/eigrp_const.h
fpm/fpm.h
lib/linklist.h
lib/table.h
ospfd/ospf_spf.c
ospfd/ospf_vty.c
pimd/pim_assert.c
pimd/pim_bsm.c
pimd/pim_cmd.c
pimd/pim_iface.c
pimd/pim_ifchannel.c
pimd/pim_macro.c
pimd/pim_register.c
pimd/pim_rpf.c
pimd/pim_upstream.c
pimd/pim_vxlan.c
zebra/interface.h
zebra/irdp.h
zebra/irdp_interface.c
zebra/rib.h
zebra/zebra_fpm.c
zebra/zebra_fpm_netlink.c
zebra/zebra_rib.c

TRUE and FALSE aren't standardized and don't exist on some platforms.
Edit:
Needs to be backported to 7.1 at least, methinks

*: s/TRUE/true/, s/FALSE/false/

---

zebra/redistribute.c
zebra/redistribute.h
zebra/rt_netlink.c
zebra/zebra_rib.c
zebra/zebra_vty.c

The `ip|ipv6 import-table X` command was not properly working anymore.  Fix the code to work properly.

Import table fix

---

bgpd/bgp_clist.c

Closes https://github.com/FRRouting/frr/issues/4626
Closes https://github.com/FRRouting/frr/issues/4627

bgpd: Validate large-community-list against UINT_MAX

---

isisd/isis_misc.c
python/clidef.py

isisd printfrr & clippy fixes

---

bgpd/bgp_dump.c
bgpd/bgp_dump.h
bgpd/bgp_fsm.c
bgpd/bgp_packet.c
bgpd/bgp_packet.h
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h

Just random things that aren't _directly_ BMP related but are needed or useful in some way for it.
Also, 1a1f453 `bgpd: fix last_reset_cause setup` fixes an actual bug :/

bgpd: BMP preparations

---

pimd/pim_cmd.c

pimd: fix some help strings

---

zebra/zebra_vxlan.c

As part of PR 4458, when a client (bgpd) goes down,
zebra cleans up any evpn state including remotely learned
neighs, macs and vteps and uninstall from kernel tables.
Neighs (arps), macs and vteps (HREP entries) were not
removed from kernel tables as the uninstall flag as not set.
Clean up l3vni associated remote neighs, macs and vteps.
Testing Done:
Validated in evpn symmetric routing topology where
remotely learned l2/l3 vnis neigh, macs and remote
vtep (hrep) entries are installed in kernel table,
perform systemctl stop frr.service and validated
all remotely learned entries cleaned up from kernel
tables.

zebra: evpn entries are not cleaned upon frr stop

---

bgpd/bgp_clist.c

bgpd: [7.1] Validate large-community-list against UINT_MAX

---

bgpd/bgp_clist.c

bgpd: [7.0] Validate large-community-list against UINT_MAX

---

bgpd/bgp_clist.c

bgpd: [6.0] Validate large-community-list against UINT_MAX

---

vrrpd/vrrp_packet.c

vrrpd: use protocol number constant

---

doc/developer/topotests-jsontopo.rst
tests/topotests/bgp-basic-functionality-topo1/bgp_basic_functionality.json
tests/topotests/bgp-basic-functionality-topo1/test_bgp_basic_functionality.py
tests/topotests/bgp-path-attributes-topo1/bgp_path_attributes.json
tests/topotests/bgp-path-attributes-topo1/test_bgp_path_attributes.py
tests/topotests/bgp-prefix-list-topo1/prefix_lists.json
tests/topotests/bgp-prefix-list-topo1/test_prefix_lists.py
tests/topotests/example-topojson-test/test_topo_json_multiple_links/example_topojson_multiple_links.json
tests/topotests/example-topojson-test/test_topo_json_multiple_links/test_example_topojson_multiple_links.py
tests/topotests/example-topojson-test/test_topo_json_single_link/example_topojson.json
tests/topotests/example-topojson-test/test_topo_json_single_link/test_example_topojson.py
tests/topotests/example-topojson-test/test_topo_json_single_link_loopback/example_topojson.json
tests/topotests/example-topojson-test/test_topo_json_single_link_loopback/test_example_topojson.py
tests/topotests/lib/bgp.py
tests/topotests/lib/common_config.py
tests/topotests/lib/topojson.py
tests/topotests/pytest.ini

Created this framework  to read data from JSON file to create topology and protocol configuration dynamically.
User has to specify the number of routers, links to each router, interfaces for the routers and protocol configurations for all routers. Creating the configurations dynamically is achieved by using /usr/lib/frr/frr-reload.py utility, which loads it to router.

topotests: Topojson framework

---

bgpd/bgp_routemap.c

Closes https://github.com/FRRouting/frr/issues/1408

bgpd: Show `delete` sub-option for `set [l]comm-list <list> delete`

---

bgpd/bgp_routemap.c

bgpd: [7.1] Show `delete` sub-option for `set [l]comm-list <list> delete`

---

ospfd/ospf_vty.c

Same ospf neighbor can be learnt via multiple interfaces, ospf detail json only displayed
last instance only.
Fix json output format to contain "neighbors" keyword, under which to display all neighbors
for a given vrf.
Fix
show ip ospf neighbor detail json
show ip ospf neighbor detail all json
show ip ospf neighbor <intf name> detail json
Testing Done:
Run the output with JSON lint and the output has passed.
switch1# show ip ospf vrf all neighbor detail json
{
"default":{
"vrfName":"default",
"vrfId":0,
"neighbors":{
"0.0.0.2":[
{
"ifaceAddress":"14.0.0.22",
"areaId":"0.0.0.0",
"ifaceName":"Bridge1.510",
"nbrPriority":1,
"nbrState":"Full",
"stateChangeCounter":6,
"lastPrgrsvChangeMsec":82668,
"routerDesignatedId":"14.0.0.22",
"routerDesignatedBackupId":"14.0.0.21",
"optionsCounter":2, …

ospfd: fix various show ip ospf neighbor json commands

---

vtysh/vtysh_config.c
zebra/interface.c

1) modify zebra interface reading
2) make nexthop-group vtysh show run unique

Various fixes

---

pbrd/pbr_nht.c
zebra/label_manager.c
zebra/zapi_msg.c
zebra/zebra_vxlan.c

1) Guard some debug messages
2) Figure out who is sending us bad data
3) Fix bad data sender

Zebra zapi msgs

---

tests/topotests/lib/lutil.py

This code adds more debugging to help us understand what is going wrong

Add more debugging to ci log files to figure out what is going on.

---

bgpd/bgp_vty.c

Closes https://github.com/FRRouting/frr/issues/4727

bgpd: Add hidden `next-hop-self all` for all address families

---

bgpd/bgp_vty.c

bgpd: [6.0] Add hidden `next-hop-self all` for all address families

---

bgpd/bgp_vty.c

bgpd: [7.0] Add hidden `next-hop-self all` for all address families

---

bgpd/bgp_vty.c

bgpd: [7.1] Add hidden `next-hop-self all` for all address families

---

lib/filter.c

Related: https://github.com/FRRouting/frr/issues/4621
Related: https://github.com/FRRouting/frr/issues/4628

filter: Introduce sequence number for access-list

---

bgpd/bgp_attr.c

Problem reported that when vrf route-leaking between an unnumbered
peer in one vrf to a numbered peer in another vrf, the nexthop
attribute was missing from the update, causing the session to fail.
determined that we needed to expand the  mechanism for verifying if
the route has been learned in the other vrf without an ipv4 nexthop.
Ticket: CM-25610

bgpd: encode implicit next-hop-self in some vrf route leaking scenarios

---

bgpd/bgp_clist.c
bgpd/bgp_routemap.c
tests/topotests/bgp_comm-list_delete/r1/bgpd.conf
tests/topotests/bgp_comm-list_delete/r1/zebra.conf
tests/topotests/bgp_comm-list_delete/r2/bgpd.conf
tests/topotests/bgp_comm-list_delete/r2/zebra.conf
tests/topotests/bgp_comm-list_delete/test_bgp_comm-list_delete.py

Related: https://github.com/FRRouting/frr/issues/4692

 bgpd: Strip `delete` keyword when looking up for communities 

---

zebra/zebra_vxlan.c

Delete an auto MAC with no neighbor associated, when its VNI is down.
In Following sequence stale MAC entry retained in FRR (zebra).
- Local MAC-IP pair
- MAC is deleted in bridge fdb table
- VNI is down, triggers IP (neigh) entries removed from FRR DB.
- MAC retained as AUTO MAC with neigh list count 0.
- When VNI is UP again, stale MAC entry retained in FRR DB.
When the MAC-IP pair moves behind remote VTEP, local VTEP
fails to add remote entry as its MAC is in auto state.
Testing Done:
Validated the sequence with fix and auto MAC is deleted  when VNI is down.
When VNI comes up, the remote MAC-IP is added to FRR (Zebra) and kernel.

zebra: del auto mac when vni is down

---

bgpd/bgp_clist.c

Related: https://github.com/FRRouting/frr/pull/4713

bgpd: [6.0] set comm-list <arg> delete stuff

---

bgpd/bgp_clist.c
tests/topotests/bgp_comm-list_delete/r1/bgpd.conf
tests/topotests/bgp_comm-list_delete/r1/zebra.conf
tests/topotests/bgp_comm-list_delete/r2/bgpd.conf
tests/topotests/bgp_comm-list_delete/r2/zebra.conf
tests/topotests/bgp_comm-list_delete/test_bgp_comm-list_delete.py

Related: https://github.com/FRRouting/frr/pull/4713

bgpd: [7.0] set comm-list <arg> delete stuff

---

ospfd/ospf_flood.c
ospfd/ospf_lsa.c
ospfd/ospf_lsa.h
ospfd/ospf_nsm.c
ospfd/ospf_vty.c
ospfd/ospf_zebra.c
ospfd/ospfd.c
ospfd/ospfd.h

This should fix #4237, and also somewhat clean up the mess that has accumulated on ospfd default-originate.

ospfd: fix & clean up default origination

---

ospfd/ospf_flood.c

[7.1] ospfd: fix default originate always

---

ospfd/ospf_flood.c

[7.0] ospfd: fix default originate always

---

vtysh/vtysh_config.c

Fixes: #4673 
Signed-off-by: Juergen Werner <juergen@opensourcerouting.org>

Replace internal linked-list in vtysh_config with RB-tree

---

doc/developer/library.rst
doc/developer/rcu.rst
doc/developer/subdir.am
lib/frr_pthread.c
lib/frr_pthread.h
lib/frrcu.c
lib/frrcu.h
lib/libfrr.c
lib/log.c
lib/seqlock.c
lib/seqlock.h
lib/sigevent.c
lib/subdir.am
lib/thread.c
tests/lib/test_atomlist.c
tests/lib/test_seqlock.c

This PR is for *preview and comments*.  I haven't fully tested it yet, although it does seem to work.
First target for RCU-ification is the logging code, which will allow removing `loglock`.  I do already have a working hack for it but it needs quite a bit more work.

RCU support
