- pimd/pim_neighbor.c
- pimd/pim_nht.c
> pimd: NH Updates are missing at PIM during boot up

- zebra/zebra_vxlan.c
PR #3745 added EVPN feature to advertise individual SVI-IPs as MAC-IP routes.
Fix a condition in zebra to send MAC and IP pair to bgpd when the feature is enabled.
Testing Done:
Originator VTEP:
TORC11:~# ip -br addr show VxU-1002
VxU-1002         UP             45.0.2.2/24 2001:fee1:0:2::2/64
show bgp l2vpn evpn vni 1004
VNI: 1004 (known to the kernel)
Type: L2
Tenant-Vrf: default
RD: 27.0.0.11:3
Advertise-svi-macip : Yes
Import Route Target:
10:1004
Export Route Target:
10:1004
Remote vtep evpn route output for 45.0.4.2:
BGP routing table entry for 27.0.0.11:3:[2]:[0]:[48]:[00:02:00:00:00:2f]:[32]:[45.0.4.2]
Paths: (2 available, best #1)
Advertised to non peer-group peers:
MSP1(uplink-1) MSP2(uplink-2)
Route [2]:[0]:[48]:[00:02:00:00:00:2f]:[32]:[45.0.4.2] VNI 1004
64435 65546
36.0.0.11 …
> zebra: fix advertise svi ip as macip route

- bgpd/bgp_routemap.c
Say for eg., 256 prefix-list entries are pasted to VTYSH.
This results in BGP processing the events for several minutes.
BGPD starts a timer for 5 seconds when the first dependency configuraion
is received. On timer expiry, BGP process dependent route-maps.
After this processing, BGPD reads the configurations received in the
next 5 seconds and then re-processes the route-maps from the beginning.
This cyclic re-processing consumes time and CPU cycles.
Instead of starting a timer when the first configuration is received,
everytime a configuration is received, the existing timer is reset.
This would mean that all the configurations are read first before the timer
expires. This eliminates the cyclic re-processing.
Signed-off-by: NaveenThanikachalam nthanikachal@vmware.com
> bgpd: Optimizing route-map's processing of dependencies.

- bgpd/bgp_aspath.c
- bgpd/bgp_rpki.c
- bgpd/bgp_vty.c
- lib/libfrr.c
- lib/thread.c
- ospf6d/ospf6_zebra.c
- ospfd/ospf_errors.c
- pbrd/pbrd.conf.sample
- pimd/pim_bsm.c
- pimd/pim_nht.c
- redhat/frr.spec.in
- sharpd/sharpd.conf.sample
- staticd/staticd.conf.sample
- yang/frr-bfdd.yang
- yang/frr-isisd.yang
- zebra/zebra_errors.c
- zebra/zebra_vxlan.c
When you look at our build log for debian packages it is spitting out a decent number of issues.  This addresses some of the found issues.
> debian packaging issues found

- lib/ferr.c
- lib/if.c
- lib/northbound.h
- lib/northbound_cli.c
- lib/prefix.c
- lib/zclient.c
Nothing really important here, but I thought it would be useful to fix these small problems nonetheless.
> Minor assorted fixes

- doc/user/eigrpd.rst
- eigrpd/eigrp_cli.c
- eigrpd/eigrp_filter.c
- eigrpd/eigrp_filter.h
- eigrpd/eigrp_fsm.c
- eigrpd/eigrp_hello.c
- eigrpd/eigrp_interface.c
- eigrpd/eigrp_main.c
- eigrpd/eigrp_neighbor.c
- eigrpd/eigrp_neighbor.h
- eigrpd/eigrp_network.c
- eigrpd/eigrp_network.h
- eigrpd/eigrp_northbound.c
- eigrpd/eigrp_packet.c
- eigrpd/eigrp_structs.h
- eigrpd/eigrp_topology.c
- eigrpd/eigrp_topology.h
- eigrpd/eigrp_update.c
- eigrpd/eigrp_vrf.c
- eigrpd/eigrp_vrf.h
- eigrpd/eigrp_vty.c
- eigrpd/eigrp_zebra.c
- eigrpd/eigrp_zebra.h
- eigrpd/eigrpd.c
- eigrpd/eigrpd.h
- eigrpd/subdir.am
- vtysh/vtysh.c
This PR implements VRF support for EIGRP. It is actually a rebase of @donaldsharp old PR `Vrf conversions` ( #4529 ) on top of the northbound.
> eigrpd: vrf support

- doc/user/pbr.rst
> doc: Update pbr to reflect new mark match command.

- isisd/isis_northbound.c
as part of the 'ip router isis TAG' command we were not validating
the MTU of the interface against the minimum LSP MTU of the area.
This could cause an assertion when the circuit is created in the
APPLY phase.
Fixes issue #4825
> isisd: check MTU when configuring circuit

- doc/user/bgp.rst
> doc: [7.1] Add documentation for `bgp ebgp-requires-policy` command

- doc/user/bgp.rst
> doc: [7.2] Add documentation for `bgp ebgp-requires-policy` command

- doc/user/bgp.rst
> doc: Add documentation for `bgp ebgp-requires-policy` command

- doc/user/ospf_fundamentals.rst
cf. #4929 with correct commit message
> doc: Edgar -> Edsger

- zebra/zebra_nhg.c
If the nexthop is of type `GATEWAY_IFINDEX` then the nexthop
should not resolve to a nexthop that has a different ifindex
from the one given.
Signed-off-by: Stephen Worley <sworley@cumulusnetworks.com>
Fixes this:
```
S>  4.4.4.4/32 [1/0] via 1.1.1.1, dummy99 (recursive), 00:00:03
*                    via 1.1.1.1, dummy1 onlink, 00:00:03
```
> zebra: Don't resolve to diff interface if given

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_routemap.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- tests/topotests/bgp_aggregate-address_route-map/r1/bgpd.conf
- tests/topotests/bgp_aggregate-address_route-map/r1/zebra.conf
- tests/topotests/bgp_aggregate-address_route-map/r2/bgpd.conf
- tests/topotests/bgp_aggregate-address_route-map/r2/zebra.conf
- tests/topotests/bgp_aggregate-address_route-map/test_bgp_aggregate-address_route-map.py
Related: https://github.com/FRRouting/frr/issues/4668
> bgpd: Apply route-map for aggregate-address

- doc/user/zebra.rst
- tests/topotests/all-protocol-startup/r1/ipv4_routes.ref
- tests/topotests/all-protocol-startup/r1/ipv6_routes.ref
- tests/topotests/all-protocol-startup/r1/zebra.conf
> Large admin distance tests and documentation

- staticd/static_routes.c
> staticd: correct update static route when specify nexthop-vrf

- doc/user/ospf_fundamentals.rst
> doc: Djikstra -> Dijkstra

- tests/topotests/bgp_aggregate-address_route-map/test_bgp_aggregate-address_route-map.py
Rewrite some parts to add more visibility what's going on if test fails.
Closes https://github.com/FRRouting/frr/issues/4967
> tests: Improve bgp_aggregate-address_route-map test

- README.md
> README.md: add reference to apt repo

- pbrd/pbr_nht.c
In pbrd we did not care if the nexthop interface nexthop tracking
sent us back did not match the one specified with `nexthop [GATEWAY]
[INTERFACE]`. This happened if the gateway was resolvable via a
different interface and the inteface we specified in the config was
unnumbered (no ipv4 address on it) since the default route gets forced
onlink when it gets into zebra.
This patch adds a check to not install the rule if the interface we got
back was different from the specified.
This patch also reworks the nexthop update path to make it a little more
clear what its doing.
Signed-off-by: Stephen Worley <sworley@cumulusnetworks.com>
> pbrd: Handle GATEWAY_IFINDEX nht conflicts

- isisd/isis_route.c
- isisd/isis_route.h
- isisd/isis_tlvs.c
- isisd/isis_zebra.c
- isisd/isis_zebra.h
- isisd/isisd.h
This PR includes a few commits from #4945 that can be reviewed and merged separately.
> isisd: assorted changes

- lib/frr_pthread.c
so labn ci wont get mad
Fixes #5000 
> lib: clean up frr_pthread structs at exit

- bfdd/bfd.c
- isisd/isis_cli.c
- lib/command.c
- lib/if.c
- lib/libfrr.c
- lib/northbound.c
- lib/northbound.h
- lib/northbound_cli.c
- lib/northbound_confd.c
- lib/northbound_grpc.cpp
- lib/northbound_sysrepo.c
- lib/vty.c
- lib/yang_wrappers.c
- lib/yang_wrappers.h
- ripd/ripd.c
- ripngd/ripngd.c
- yang/libyang_plugins/frr_user_types.c
Please see individual commits for details. None of these commits need to be backported to the stable branches.
> northbound fixes and enhancements

- lib/if.c
Works for one VRF, I haven't tried it with multiple VRFs yet so I'm leaving it in draft for now
> lib: add oper data cbs for ifaces

- isisd/isis_main.c
- isisd/isisd.c
- isisd/isisd.h
- ospf6d/ospf6_top.c
- ospf6d/ospf6_top.h
Write some code that starts the movement of vrf_id into the main data structure for the particular daemon.  More will be coming as there is free time
> Vrf conversions

- doc/user/zebra.rst
Update documentation to reflect on the ground behavior.
> user: Update `ip protocol...` command documentation

- bgpd/bgp_updgrp.c
- bgpd/bgp_updgrp_adv.c
- doc/user/bgp.rst
Update `show bgp update-group` command to be a bit better
> Update groups and coalesce timer

- vtysh/vtysh.c
Please refer to the individual commit messages for more details.
> vtysh: add two commands from the northbound

- bgpd/bgpd.h
- pbrd/pbr_nht.c
1) issue in pbr
2) issue in bgp
> Sa issues found

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
> topotest: bgp_l3vpn_to_bgp_vrf allow for different interface output

- eigrpd/eigrp_network.c
- isisd/isis_te.c
- ospf6d/ospf6_lsdb.c
- ospf6d/ospf6_message.c
- ospf6d/ospf6_neighbor.c
- pimd/pim_zebra.c
Some more SA issues found in Coverity, see individual commit
> More sa stuff this evening

- bfdd/bfdd_vty.c
- doc/user/bfd.rst
- lib/if.c
- lib/nexthop_group.c
- lib/vrf.c
- pbrd/pbr_vty.c
- sharpd/sharp_vty.c
- zebra/interface.c
Cherry-pick of https://github.com/FRRouting/frr/pull/5051
> [7.2] *: fix missing VRF autocompletions

- bgpd/bgp_route.c
> bgpd: Accept no aggregate-address <IP> route-map <RMAP> commands

- zebra/zebra_rib.c
> zebra: if_is_loopback_or_vrf crash if if_lookup_by_index return NULL

- bgpd/bgp_evpn_vty.c
Fixed the following:
1. Print the complete header for 'show bgp l2vpn evpn' command
2. Print the Route Distinguisher header
3. Print all relevant routes in json (some were being skipped)
> bgpd: Fixed 'show bgp l2vpn evpn json' to display all routes

- bgpd/bgp_route.c
> bgpd: [7.2] Accept no aggregate-address <IP> route-map <RMAP> commands

- sharpd/sharp_zebra.c
- zebra/redistribute.c
Fixes ZEBRA_ROUTE_ALL for redistribution deletion events that was accidently dropped.  See individual commits
> ZEBRA_ROUTE_ALL fix

- zebra/redistribute.c
commit ee8a72f315013aecd45bc9c3aaf7ea81b2ca747a
broke the usage of ZEBRA_ROUTE_ALL as a valid redistribution
command.  This commit puts it back in.  LDP uses ZEBRA_ROUTE_ALL
as an option to say it is interested in all REDISTRIBUTION events.
Fixes: #5072
> [7.2]zebra: Fix redistribution deletion for ZEBRA_ROUTE_ALL

- bgpd/bgp_rpki.c
- bgpd/bgp_zebra.c
A couple warnings and SA issues
> Fix some warnings

- docker/debian/Dockerfile
Hi,
This simple MR simplifies the docker image creation using docker's best practices.
Cheers
> Make docker images lighter and with less layers

- lib/command.h
> lib: fix typo

- bfdd/bfdd_vty.c
- ospfd/ospf_vty.c
> *: remove redundant brackets in commands

- doc/developer/workflow.rst
> doc: add style guide for YANG

- Makefile.am
- lib/mlag.c
- lib/mlag.h
- lib/zclient.c
- lib/zclient.h
- mlag/mlag.proto
- mlag/subdir.am
- pimd/pim_cmd.c
- pimd/pim_cmd.h
- pimd/pim_instance.c
- pimd/pim_instance.h
- pimd/pim_main.c
- pimd/pim_mlag.c
- pimd/pim_mlag.h
- pimd/pim_zebra.c
- pimd/pimd.h
- pimd/subdir.am
- zebra/subdir.am
- zebra/zapi_msg.c
- zebra/zebra_mlag.c
- zebra/zebra_mlag.h
- zebra/zebra_mlag_private.c
- zebra/zebra_mlag_private.h
- zebra/zebra_router.h
- zebra/zserv.h
Support for PIM MLAG Functionality:
1) Zebra opens the communication channel with MLAG based on Clients requests.
2) multiple clients can send the register to Zebra at same time.
3) In Rx direction messages are posted to clients from Zebra based on subscriptions during registration.
4) all the messages to/from MLAG are encoded using Protobuf.
5) clients are completely un-aware of this encodes/Decodes.
6) Zebra will take care of encoding the messages in Tx. direction, similarly messages will be posted after protobuf Decode.
7) a New pthread is spawned to process MLAG Messages.
8) this pthread will be closed when there is no MLAG activity
> pimd, lib, Zebra: PIM MLAG Support

- lib/if.c
- lib/if.h
Duplicate of the first two commits in #5132
> [7.2] Fix Interface Infinite Loop Walk

- alpine/APKBUILD.in
> fix alpine 🎿🎿🎿 docker build 🛠️

- doc/user/bgp.rst
> doc: fix read-quanta .. index copy-paste err

- bgpd/bgp_bmp.c
- bgpd/bgp_evpn.c
- bgpd/bgp_flowspec_vty.c
- bgpd/bgp_pbr.c
- bgpd/bgp_route.c
- bgpd/bgp_routemap.c
- bgpd/rfapi/rfapi.c
- bgpd/rfapi/rfapi_import.c
- bgpd/rfapi/rfapi_rib.c
- bgpd/rfapi/rfapi_vty.c
- bgpd/rfapi/vnc_import_bgp.c
- doc/user/bgp.rst
- lib/filter.c
- zebra/zebra_vty.c
Cleanup some SA issues, and a doc fix.  See individual commits
> Sa clean and clean

- isisd/isis_northbound.c
Traffic Engineering parameters are correctly advertised in LSP when
'mpls-te on' CLI command is present in the startup config file.
However, if IS-IS is started without TE enable at startup and
'mpls-te on' command is issued after, TE link parameters are never
announced. The patch correct this issue.
> isisd: Correct missing advertisement of TE parameters

- doc/user/filter.rst
> doc: Update documentation for access-list with sequence numbers

- lib/if.c
- lib/printf/glue.c
- pimd/pim_bsm.c
- pimd/pim_cmd.c
- pimd/pim_rp.c
- zebra/connected.c
Bunch of SA issues fixed see individual commits for details
> Fix it it it it it it

- doc/user/filter.rst
> doc: [7.2] Update documentation for access-list with sequence numbers

- bfdd/bfd.c
- bfdd/bfd_packet.c
- bgpd/bgp_mpath.c
- bgpd/bgp_route.c
- bgpd/bgpd.c
- bgpd/rfapi/rfapi.c
- bgpd/rfapi/rfapi_vty.c
- bgpd/rfapi/vnc_import_bgp.c
> Fix sa or else

- zebra/rt_netlink.c
- zebra/zebra_nhg.c
- zebra/zebra_vxlan.c
> ZEBRA COVERITY STUFF

- README.md
> Add FRR Icon to README

- doc/user/bgp.rst
Fixes https://github.com/FRRouting/frr/issues/2369
> doc: Add redistribute vnc-direct command and fix typo in redistribute vnc

- doc/developer/workflow.rst
As per weekly meeting this is an attempt to document about
how we as a community will work together on development
branches.
> doc: Update documentation to talk about development branches

- tools/tarsource.sh
> tools: generate .changes file required for deb pkg upload

- tests/topotests/ldp-vpls-topo1/r1/zebra.conf
- tests/topotests/ldp-vpls-topo1/r2/zebra.conf
- tests/topotests/ldp-vpls-topo1/r3/zebra.conf
- tests/topotests/ldp-vpls-topo1/test_ldp_vpls_topo1.py
- tests/topotests/lib/topogen.py
Please see the individual commits for details.
Fixes #5239.
> Fix the LDP VPLS topotest

- doc/developer/testing.rst
- doc/developer/topotests-jsontopo.rst
Fixes doc build warnings and makes this new doc actually appear in the built docs
> doc: clean up && index topotest json docs

- tests/topotests/bgp-path-attributes-topo1/bgp_path_attributes.json
- tests/topotests/bgp-path-attributes-topo1/test_bgp_path_attributes.py
- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
1.  Added steps to modify BGP path attributes and verify best path is changed
2.  Modified affected APIs to supported BGP Path attributes modification and verification
> tests: Enhance bgp-path-attributes-topo1 test suite

- vtysh/vtysh_main.c
> vtysh: be helpful and kind to unprivileged users

- tests/topotests/bgp_sender-as-path-loop-detection/r1/bgpd.conf
- tests/topotests/bgp_sender-as-path-loop-detection/r1/zebra.conf
- tests/topotests/bgp_sender-as-path-loop-detection/r2/bgpd.conf
- tests/topotests/bgp_sender-as-path-loop-detection/r2/zebra.conf
- tests/topotests/bgp_sender-as-path-loop-detection/r3/bgpd.conf
- tests/topotests/bgp_sender-as-path-loop-detection/r3/zebra.conf
- tests/topotests/bgp_sender-as-path-loop-detection/test_bgp_sender-as-path-loop-detection.py
Related: https://github.com/FRRouting/frr/pull/5248
> tests: Add a test case for `sender-as-path-loop-detection`

- bgpd/bgp_route.c
- bgpd/bgp_routemap.c
With this code change, we can now filter evpn routes based on RD using the
match statement: "match evpn rd XX"
**Route-map out-filter**
These are all the routes currently being advertised without applying any filter:
```
leaf-1(config-route-map)# do sh bgp l2vpn evpn all neighbors 203.0.113.2 advertised-routes
BGP table version is 0, local router ID is 10.100.0.1
Default local pref 100, local AS 65000
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal
Origin codes: i - IGP, e - EGP, ? - incomplete
Route Distinguisher: 10.100.0.1:3
*> [3]:[0]:[32]:[10.100.0.1]
32768 i
Route Distinguisher: 10.100.0.1:4
*> [2]:[0]:[48]:[00:50:56:b5:d2:fd]
32768 i
*> [2]:[0]:[48]:[00:50:56:b7:61:49]
32768 i
*> …
```
> bgpd: route-map support for evpn RD filter

- pimd/pim_cmd.c
- pimd/pim_rp.c
See indvidiaujl commits but stop pim from crashing.
> Pim crash rp

- zebra/zebra_vxlan.c
In symmetric routing case for evpn (type-2/type-5) routes, nexthop and Router mac fields can change from the originating VTEP.
At the receiving VTEP, bgp path info may points to different nexthop IP (nh1->nh2) and Remote MAC remain the same. When the bgp sync the route with nexthop and RMAC fields.
For the existing RMAC entry update/replace with the new nexthop (VTEP) IP in remote RMAC db in Zebra.
Similarly, bgp path info may points different Router-mac (RMAC1->RMAC2) and the nexthop value remains the same.
In this case, update to the new RMAC value for the existing remote nexthop in the Zebra' nexthop cache db.
> zebra: evpn update remote rmac and nexhop

- pimd/pim_cmd.c
- pimd/pim_rp.c
see individual commits, Double commit of code that went into master
> [7.2] pim crash rp

- ospfd/ospf_api.c
- ospfd/ospf_api.h
- ospfd/ospf_asbr.c
- ospfd/ospf_dump.c
- ospfd/ospf_dump.h
- ospfd/ospf_flood.c
- ospfd/ospf_interface.c
- ospfd/ospf_lsa.c
- ospfd/ospf_nsm.c
- ospfd/ospf_packet.c
- ospfd/ospfd.c
- ospfd/ospfd.h
1) Remove dead code
2) Add/improve debugs to be more vrf aware
3) Remove ip header dump
4) Glom up to 20 read packets in one go.
> Ospf vrf data

- snapcraft/scripts/Makefile
- snapcraft/scripts/vrrpd-service
- snapcraft/snapcraft.yaml.in
Adding the vrrpd daemon to snap package.
> snapcraft: Add vrrpd to the snapcraft package

- snapcraft/scripts/Makefile
- snapcraft/scripts/vrrpd-service
- snapcraft/snapcraft.yaml.in
Adding the vrrpd daemon to snap package.
> snapcraft: Add vrrpd to the snapcraft package [7.2]

- pimd/pim_join.c
- pimd/pim_pim.c
- pimd/pim_rp.c
- pimd/pim_tlv.c
> [7.1] cherrys

- pimd/pim_bsm.c
- pimd/pim_join.c
- pimd/pim_pim.c
- pimd/pim_rp.c
- pimd/pim_tlv.c
- zebra/rtadv.c
- zebra/zebra_router.c
couple of fixes that went in the last day that should be backported
> [7.2] cherrys

- bfdd/bfd.c
Fixes #5308 .
More information on #5390 .
> [7.2] bfdd: fix multiple VRF handling

- eigrpd/eigrp_dump.c
- eigrpd/eigrp_dump.h
Just some minor cleanups of some poorly written code.
> Eigrp cleanup1

- zebra/zebra_routemap.c
- zebra/zserv.c
Fix up column issues in some commands in zebra
> Zebra client summ spacing

- bgpd/bgp_table.c
The function bgp_table_range_lookup attempts to walk down
the table node data structures to find a list of matching
nodes.  We need to guard against the current node from
not matching and not having anything in the child nodes.
Add a bit of code to guard against this.
Traceback that lead me down this path:
Nov 24 12:22:38 frr bgpd[20257]: Received signal 11 at 1574616158 (si_addr 0x2, PC 0x46cdc3); aborting...
Nov 24 12:22:38 frr bgpd[20257]: Backtrace for 11 stack frames:
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_backtrace_sigsafe+0x67) [0x7fd1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_signal+0x113) [0x7fd1ad445db3]1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(+0x70e65) [0x7fd1ad465e65]ad445db3]1ad445957]
Nov 24 12:22:38 frr …
> bgpd: Prevent crash in bgp_table_range_lookup

- bgpd/bgp_table.c
The function bgp_table_range_lookup attempts to walk down
the table node data structures to find a list of matching
nodes.  We need to guard against the current node from
not matching and not having anything in the child nodes.
Add a bit of code to guard against this.
Traceback that lead me down this path:
Nov 24 12:22:38 frr bgpd[20257]: Received signal 11 at 1574616158 (si_addr 0x2, PC 0x46cdc3); aborting...
Nov 24 12:22:38 frr bgpd[20257]: Backtrace for 11 stack frames:
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_backtrace_sigsafe+0x67) [0x7fd1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_signal+0x113) [0x7fd1ad445db3]1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(+0x70e65) [0x7fd1ad465e65]ad445db3]1ad445957]
Nov 24 12:22:38 frr …
> [7.0]bgpd: Prevent crash in bgp_table_range_lookup

- bgpd/bgp_table.c
The function bgp_table_range_lookup attempts to walk down
the table node data structures to find a list of matching
nodes.  We need to guard against the current node from
not matching and not having anything in the child nodes.
Add a bit of code to guard against this.
Traceback that lead me down this path:
Nov 24 12:22:38 frr bgpd[20257]: Received signal 11 at 1574616158 (si_addr 0x2, PC 0x46cdc3); aborting...
Nov 24 12:22:38 frr bgpd[20257]: Backtrace for 11 stack frames:
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_backtrace_sigsafe+0x67) [0x7fd1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(zlog_signal+0x113) [0x7fd1ad445db3]1ad445957]
Nov 24 12:22:38 frr bgpd[20257]: /lib64/libfrr.so.0(+0x70e65) [0x7fd1ad465e65]ad445db3]1ad445957]
Nov 24 12:22:38 frr …
> [7.1]bgpd: Prevent crash in bgp_table_range_lookup

- bfdd/bfd.c
- bfdd/bfd.h
- bfdd/bfdd_vty.c
the #5013 merge was a mess.  Just cleaned it up
Closes https://github.com/FRRouting/frr/pull/5013
> 5013 cleanup merge issues

- bgpd/bgp_vty.c
> [7.2] bgpd: Autocomplete neighbor for clear bgp

- tools/frr.in
> tools: [ [ is not valid test syntax

- lib/zclient.h
- pbrd/pbr_vty.c
- pbrd/pbr_zebra.c
> pbrd: Assorted Fixes

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_evpn.c
- bgpd/bgp_mpath.c
- bgpd/bgp_mplsvpn.c
- bgpd/bgp_route.c
- bgpd/bgp_updgrp_adv.c
- bgpd/bgp_zebra.c
- bgpd/rfapi/vnc_export_bgp.c
- bgpd/rfapi/vnc_import_bgp.c
> bgpd: remove bgp_attr_dup

- pbrd/pbr_map.c
Only remove the interface from the pbr_map after we get
a callback from zapi that every sequence using that interface
has been removed.
Before, if we created a map with multiple sequences and put that on an interface,
then removed it from that interface, it would fail to mark the sequences after
the first one as uninstalled.
This was because we failed to lookup the other ones after we removed
the interface from the pbr_map.
This patch adds a conditional to only delete the interface from the pbr
map if all its sequneces using that interface have been uninstalled.
This patch extends the work done in 38e9ccde2f8edd6946d48c80967027d05e64d73f
Signed-off-by: Stephen Worley <sworley@cumulusnetworks.com>
> pbrd: only remove interface after all seq uninstalled

- doc/user/pim.rst
> doc: document ip mroute static route cmd

- zebra/zebra_nhg.c
- zebra/zebra_rib.c
A couple fixes related to nexthop group code. See individual commits.
> zebra: a couple nhg fixes

- doc/user/nhrpd.rst
> doc: add discussion for a handful of nhrp commands

- doc/manpages/bgpd.rst
- doc/user/overview.rst
Update the `Overview` page of the documentation for the new millennium, in which everyone is aware TCP/IP networks are cosmopolitan ;)
> Doc update overview

- doc/developer/workflow.rst
Update the workflow.rst file to outline new requirement for
features to include automated testing of some sort.
> doc: Update workflow to include new automated testing Requirement

- bgpd/bgp_route.c
- tests/topotests/bgp_ebgp_requires_policy/r5/bgpd.conf
- tests/topotests/bgp_ebgp_requires_policy/r5/zebra.conf
- tests/topotests/bgp_ebgp_requires_policy/r6/bgpd.conf
- tests/topotests/bgp_ebgp_requires_policy/r6/zebra.conf
- tests/topotests/bgp_ebgp_requires_policy/test_bgp_ebgp_requires_policy.py
Closes https://github.com/FRRouting/frr/issues/5565
>  bgpd: Do not apply eBGP policy for iBGP peers 

- zebra/zebra_nhg.c
Do less malloc and free in depends_find(), when looking for a singleton nexthop in the nhg hash.
> zebra: improve efficiency of depends_find()

- lib/vrf.c
- lib/vrf.h
- vrrpd/vrrp.c
- vrrpd/vrrp_zebra.c
exactly what it says on the tin
> VRRP VRF support

- pimd/pim_cmd.c
combine:
``` 
ip mroute INTERFACE A.B.C.D
ip mroute INTERFACE A.B.C.D A.B.C.D
```
into:
```
ip mroute INTERFACE A.B.C.D [A.B.C.D]
```
> pimd: refactor ip mroute cmd

- ripd/rip_zebra.c
- ripngd/ripng_zebra.c
Fix redistribute X/ no redistribute rinse repeat commands.
> Rip redistribute fixes

- doc/developer/building-frr-for-centos8.rst
- doc/developer/building.rst
- doc/developer/packaging-redhat.rst
- redhat/frr.spec.in
Related: https://github.com/FRRouting/frr/issues/5587
> packaging: Add CentOS 8 support

- doc/user/overview.rst
1. Added subsections for BGP, MPLS, ISIS, OSPF etc.
2. Updated RFCs for BGP, MPLS, OSPF.
Signed-off-by: Sri Mohana Singamsetty <msingamsetty@vmware.com>
> doc: Updating FRR supported RFC list

- doc/user/overview.rst
Related: https://github.com/FRRouting/frr/pull/5613
> doc: Add rfc8212 to supported RFCs list

- configure.ac
> configure.ac: add --enable-undefined-sanitizer

- bgpd/bgp_vty.c
> bgpd: fix too much no listen doc string

- zebra/if_netlink.c
- zebra/kernel_netlink.c
> zebra: fix undefined bitshifts in netlink stuff

- bgpd/bgp_vty.c
> bgpd: Time to deprecate bgpTimerUp

- doc/user/pim.rst
The FRR community keeps getting asked about what is supported or not.
Try to clarify in an additional spot what is and what is not supported.
Where people interested in using PIM might have a chance at actually
seeing the notification.
> doc: Clarify what is supported directly in PIM documentation

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
Fixes issue reported in #5643
fix in master by PR #5050
> 7.0: topotest: bgp_l3vpn_to_bgp_vrf allow for different interface output

- bgpd/bgp_route.c
- tests/topotests/bgp_show_ip_bgp_fqdn/test_bgp_show_ip_bgp_fqdn.py
Closes https://github.com/FRRouting/frr/issues/5477
>  bgpd: [7.2] Show `ip` and `fqdn` in json output for `show [ip] bgp <route> json`

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
Fixes issue reported in #5643 
fix in master by PR #5050
> 7.2: bgp_l3vpn_to_bgp_vrf: allow for change in 'ip add show vrf' output format

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
Fixes issue reported in #5643
fix in master by PR #5050
> 7.1: topotest: bgp_l3vpn_to_bgp_vrf allow for different interface output

- lib/ipaddr.h
- lib/yang.c
- vrrpd/subdir.am
- vrrpd/vrrp.c
- vrrpd/vrrp.h
- vrrpd/vrrp_main.c
- vrrpd/vrrp_northbound.c
- vrrpd/vrrp_vty.c
- vrrpd/vrrp_vty.h
- yang/frr-vrrpd.yang
- yang/subdir.am
Converts VRRP to use Northbound API.
Draft at the moment because there are some slight behavior changes in CLI command validation, and autoconfig isn't implemented as a model option.
> VRRP northbound conversion

- debian/frr.logrotate
Signed-off-by: Tim Bray <tim@kooky.org>
> Fix logrotate in debian for bfdd, pbrd and vrrpd.

- doc/developer/building-frr-for-centos6.rst
- doc/developer/building-frr-for-centos7.rst
- doc/developer/building-frr-for-centos8.rst
- doc/developer/building-frr-for-fedora.rst
Closes https://github.com/FRRouting/frr/issues/5660
> doc: Replace wrong paths for centos/fedora source build instructions

- zebra/zapi_msg.c
The only two safi's that are usable for zebra for installation
of routes into the rib are SAFI_UNICAST and SAFI_MULTICAST.
The acceptance of other safi's is causing a memory leak:
```
Direct leak of 56 byte(s) in 1 object(s) allocated from:
#0 0x5332f2 in calloc (/usr/lib/frr/zebra+0x5332f2)
#1 0x7f594adc29db in qcalloc /opt/build/frr/lib/memory.c:110:27
#2 0x686849 in zebra_vrf_get_table_with_table_id /opt/build/frr/zebra/zebra_vrf.c:390:11
#3 0x65a245 in rib_add_multipath /opt/build/frr/zebra/zebra_rib.c:2591:10
#4 0x7211bc in zread_route_add /opt/build/frr/zebra/zapi_msg.c:1616:8
#5 0x73063c in zserv_handle_commands /opt/build/frr/zebra/zapi_msg.c:2682:2
```
Sequence of events:
Upon vrf creation there is a zvrf->table[afi][safi] data structure
that tables are auto created for.  These …
> zebra: Do not accept illegal safi's for route installation

- bgpd/bgp_attr.c
- bgpd/bgp_open.c
- bgpd/bgp_route.c
- lib/if.c
- zebra/if_netlink.c
- zebra/kernel_netlink.c
- zebra/rtadv.c
- zebra/zapi_msg.c
- zebra/zebra_pbr.c
- zebra/zebra_ptm.c
Backport of my recent fixes to 7.2
> Stable 7.2 backport edible arrangement

- configure.ac
- lib/gitversion.pl
- m4/ax_python.m4
commit subject lines say it all
> build: random cleanups

- lib/zclient.c
- tests/topotests/pim-basic/r1/bgpd.conf
- tests/topotests/pim-basic/r1/pimd.conf
- tests/topotests/pim-basic/r1/rp-info.json
- tests/topotests/pim-basic/r1/zebra.conf
- tests/topotests/pim-basic/rp/bgpd.conf
- tests/topotests/pim-basic/rp/pimd.conf
- tests/topotests/pim-basic/rp/upstream.json
- tests/topotests/pim-basic/rp/zebra.conf
- tests/topotests/pim-basic/test_pim.py
> Nexthop encoding

- doc/developer/topotests.rst
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py
- tests/topotests/lib/ltemplate.py
- tests/topotests/lib/lutil.py
recommend compiling sharpd, 
handle when not compiled
log results summary at end of lutil run
> topotest: minor doc, lutil, sharpd not compiled changes

- bfdd/bfd.c
Fixes #5308 for `master`.
More information on #5390 .
Use the interface VRF information instead of relying on the VRF specific
socket information.
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
(cherry picked from commit c05c48621c94582bce6ddb6e3f316f8a010c9bb0)
> bfdd: fix multiple VRF handling

- doc/user/ospf6d.rst
- doc/user/ospfd.rst
Closes https://github.com/FRRouting/frr/issues/1768
> doc: Add documentation about OSPF(6) `set metric [+|-]metric` cmd

- zebra/debug.c
Add show output for 'debug zebra nexthop' debug category - managed to miss that.
> zebra: include zebra nexthop debug in show runn

- doc/user/vtysh.rst
- vtysh/vtysh.c
Add a simple 'copy' cli that reads a file into the current running config.
> vtysh: add a cli that reads a file into running-config

- zebra/zapi_msg.c
- zebra/zebra_nhg.c
- zebra/zebra_nhg_private.h
A couple fixes for stuff found when fuzzing zapi.
> Zebra nhg/nexthop fixes

- bgpd/bgp_fsm.c
- bgpd/bgp_open.c
- bgpd/bgp_route.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
Cleanup some code taht got in recently.  it was poorly formateted.
> Bgp formating

- bgpd/bgp_zebra.c
- doc/developer/zebra.rst
- lib/log.c
- lib/zclient.c
- lib/zclient.h
- zebra/main.c
- zebra/subdir.am
- zebra/zapi_msg.c
- zebra/zebra_gr.c
- zebra/zebra_router.h
- zebra/zserv.c
- zebra/zserv.h
Adding infrastructure support for GR client in Zebra. 
It mainly has client management, Stale route handling,
capability handling.
Signed-off-by: Santosh P K <sapk@vmware.com>
> Zebra: Adding GR infrastructure for clients.

- bgpd/bgp_route.c
- bgpd/bgp_vty.c
- lib/agentx.c
- zebra/zebra_nhg.c
Fix a bunch stuff uncovered by SA
> Coverioty sa stuff

- bgpd/bgp_clist.c
- bgpd/bgp_clist.h
- bgpd/bgp_vty.c
Related: https://github.com/FRRouting/frr/issues/4628
> bgpd: Use sequence numbers for community lists

- lib/netns_linux.c
- scripts/coccinelle/void_no_return.cocci
- zebra/zapi_msg.c
first shot for coccinelle, let's keep useful scripts in the repo?
> zebra, lib: Remove return from void functions

- bgpd/bgp_attr.c
some issues fixes related with distributing flowspec entries. (for instance, if setup as route reflector)
> Flowspec issue redistribute

- zebra/rt_netlink.c
zebra can catch the kernel's route deletion by netlink.
but current FRR can't delete kernel-route on vrf(l3mdev)
when kernel operator delete the route on out-side of FRR.
It looks problem about kernel-route deletion.
This problem is caused around _nexthop_cmp_no_labels(nh1,nh2)
that checks the each nexthop's member 'vrf_id'.
And _nexthop_cmp_no_labels's caller doesn't set the vrf_id
of nexthop structure. This commit fix that case.
Signed-off-by: Hiroki Shirokura <slank.dev@gmail.com>
> [7.2]zebra: fix kernel-route's deletion on vrf

- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/notification_check.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/test_bgp_l3vpn_to_bgp_vrf.py
This exposes issues seen in LabN CI on #5633
> topotest: bgp_l3vpn_to_bgp_vrf - report unexpected BGP notifications

- bgpd/bgp_nexthop.c
Commit identified by Martin that fixes the bgp nexthop issue he found
> [7.3]bgpd: Remove prefix pointer creation

- doc/user/bgp.rst
Closes https://github.com/FRRouting/frr/issues/5777
> doc: Add few words about `bgp disable-ebgp-connected-route-check`

- bgpd/bgp_updgrp_packet.c
This function was heavily indented, reformat to reduce indentation
levels a bit.
> bgpd: Reformat bpacket_reformat_for_peer

- nhrpd/nhrp_vty.c
> nhrpd: allow no nhrp map cmd to match the configured cmd

- bgpd/bgp_nht.c
- bgpd/bgp_rpki.c
> bgpd: Fix up a couple of new SA issues found

- zebra/irdp_packet.c
1) Fix setsockopt to send right data type
2) Fix debug messgeas that should be errors
3) Fix checksum calculation
> Irdp: build and log fixes

- doc/developer/library.rst
- doc/developer/lists.rst
- doc/developer/locking.rst
- doc/developer/logging.rst
- doc/developer/lua.rst
- doc/developer/modules.rst
- doc/developer/static-linking.rst
- doc/developer/subdir.am
Add a couple breadcrumbs to get people up and running
with lua when they are trying to develop for it.
> doc: Add some basic how-to for lua and clean up some found issues

- zebra/zapi_msg.c
> zebra: remove \n in zapi pbr family log msg

- lib/routemap_northbound.c
> lib: do not test before XFREE

- pimd/pim_cmd.c
- pimd/pim_vxlan.c
Fix a couple of SA warnings introduced recently.
> pimd: fix SA reports

- bgpd/bgp_vty.c
Before:
```
Graceful restart informations:
End-of-RIB send: IPv4 Unicast
End-of-RIB received: IPv4 Unicast
Local GR Mode  : Helper*
Remote GR Mode : Helper
R bit          : False
Timers :
Configured Restart Time(sec)  : 120
Received Restart Time(sec)    : 120
IPv4 Unicast :
F bit                 : False
End-of-RIB Received   : Yes
End-of-RIB Send       : Yes
EoRSentAfterUpdate   : Yes
Timers:
Configured Stale Path Time(sec)        : 360
```
After:
```
Graceful restart informations:
End-of-RIB send: IPv4 Unicast
End-of-RIB received: IPv4 Unicast
Local GR Mode: Helper*
Remote GR Mode: Helper
R bit: False
Timers:
Configured Restart Time(sec): 120
Received Restart Time(sec): 120
IPv4 Unicast:
F bit: False
End-of-RIB send: Yes
End-of-RIB send after update: Yes
End-of-RIB received: Yes
Timers: …
```
> bgpd: Format properly `show bgp neighbors` for graceful restart stuff

- tests/topotests/bgp-route-map/test_route_map_topo1.py
- tests/topotests/bgp-route-map/test_route_map_topo2.py
- tests/topotests/lib/bgp.py
… suite
1. Modified scripts to optimize execution time for route-map test suite, added "expected=False" to all expected to be failed verifications.
2. Removed unnecessary print statements from /lib/bgp.py
> tests: Optimizing route-map test cases 

- bfdd/bfdd_vty.c
- bgpd/bgp_aspath.c
- bgpd/bgp_community.c
- bgpd/bgp_ecommunity.c
- bgpd/bgp_lcommunity.c
- lib/hash.h
- lib/routemap.c
- pbrd/pbr_nht.c
- pimd/pim_cmd.c
- pimd/pim_vxlan.c
- zebra/zebra_fpm.c
- zebra/zebra_vxlan.c
It's been a year search and destroy.
> *: change hash_backet to hash_bucket

- bfdd/bfdd_vty.c
- bgpd/bgp_aspath.c
- bgpd/bgp_community.c
- bgpd/bgp_ecommunity.c
- bgpd/bgp_lcommunity.c
- lib/hash.h
- lib/routemap.c
- pbrd/pbr_nht.c
- pimd/pim_cmd.c
- pimd/pim_vxlan.c
- zebra/zebra_fpm.c
- zebra/zebra_vxlan.c
This reverts commit 3895c42a2eb534a70ef25412547e798c1c1ef5a1.
LabN CI update needs to be coordinated before merging this
> Revert "*: change hash_backet to hash_bucket"

- lib/nexthop_group.c
- lib/nexthop_group.h
- pimd/pim_cmd.c
- pimd/pim_vxlan.c
- zebra/redistribute.c
- zebra/rib.h
- zebra/zapi_msg.c
- zebra/zebra_dplane.c
- zebra/zebra_fpm_netlink.c
- zebra/zebra_mpls.c
- zebra/zebra_nhg.c
- zebra/zebra_nhg.h
- zebra/zebra_pw.c
- zebra/zebra_rib.c
- zebra/zebra_rnh.c
- zebra/zebra_snmp.c
- zebra/zebra_vty.c
Embed the nexthop-group, which is just a pointer, in the zebra nexthop-hash-entry object, rather than malloc-ing one.
> zebra,lib: Embed lib nexthop-group in zebra hash entry

- doc/user/overview.rst
> doc: Add notice of rfc-4893 in supported rfc's.

- zebra/zebra_vxlan.c
The existing behavior is when a remote VTEP is deleted,
its associatedneighbor (arp) and MAC entries are removed from
zebra database and do not wait for explicit type-2 route
withdraw from originating VTEP.
Remote type-2 route delete checks if VTEP is present before
removing the entry.
The behavior works fine when all evpn routes points to the
same nexthop as the VTEP IP.
In MLAG topology with advertise-pip, self type-2 and type-5 routes
are advertised with individual VTEP IP as nexthop ip for the route.
When a new VNI is created, it is assigned individual IP as tunnel-ip
then it transition to anycast IP (of the MLAG). During the transition,
type-3 route (VTEP delete) withdraw is sent for the individual IP.
The remote VTEP delete should not trigger to remove evpn routes pointing
to VTEP …
> zebra:remote vtep delete handling

- zebra/zebra_mpls.c
Consolidate some LSP cleanup code into a common free function; I'm planning to add to the lsp struct, and this'll help keep it ... tidy.
> zebra: add a free api for LSPs

- doc/user/rpki.rst
Could be merged only after https://github.com/FRRouting/frr/pull/5848
> doc: Add documentation for `show rpki prefix` and `show rpki as-number`

- ospfd/ospf_ism.c
Optimize display of code a tiny bit so that we can actually
have readable code.
> ospfd: Fix 4 levels of unnecessary indentation

- bgpd/bgp_damp.c
- bgpd/bgp_dump.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- isisd/isis_misc.c
- isisd/isis_vty_fabricd.c
- lib/bfd.c
- lib/keychain.c
- lib/log.c
- ripd/rip_peer.c
- ripd/ripd.c
- ripngd/ripng_peer.c
- ripngd/ripngd.c
- vtysh/vtysh_main.c
- zebra/zebra_vty.c
- zebra/zserv.c
Stop using gmtime() or localtime() - yikes~
> *: use gmtime_r exclusively

- .gitignore
- pimd/pim_mlag.c
- zebra/zebra_nhg.c
Clean up some coverity SA issues
> More more more

- tests/bgpd/test_mpath.c
> tests: fix build with GCC 10

- doc/user/pim.rst
- lib/mlag.c
- lib/mlag.h
- pimd/pim_cmd.c
- pimd/pim_iface.h
- pimd/pim_ifchannel.c
- pimd/pim_macro.c
- pimd/pim_mlag.c
- pimd/pim_mlag.h
- pimd/pim_mroute.c
- pimd/pim_oil.c
- pimd/pim_oil.h
- pimd/pim_upstream.c
- pimd/pim_upstream.h
- pimd/pim_vty.c
- pimd/pim_vxlan.c
- pimd/pim_zpthread.c
- pimd/pimd.c
- pimd/subdir.am
- zebra/zebra_mlag.c
- zebra/zebra_mlag.h
- zebra/zebra_mlag_private.c
1) When comparing upstream -vs- internal it was noted we had missed some code.  This was due to squashing and picking and choosing of data( I hope the lesson has been learned, at least I felt the pain )
2) Internal fixes of mlag issues found had been stacking up slightly.  These have been added too
3) Add some documentation for missing cli commands.
> Upstream merge of missed MLAG code

- zebra/rtadv.c
Memory leak found where ipv6 global prefixes added to the router
advertisement prefix lists were not deleted when the process was
killed.
> zebra: delete ipv6 RA prefix entries when zebra is killed

- pimd/pim_vxlan.c
- pimd/pim_vxlan.h
- pimd/pimd.c
Found some shutdown/cleanup issues where we were not properly cleaning up both memory and a thread.
> Pim shutdown cleanup

- bgpd/bgp_fsm.c
- updating BFD upon update source change
- resetting BFD to init once BGP establishes (after a clear)
> Two bfd fixes

- zebra/zebra_nhg.c
And also remove an assignment without effect while we're here.
> zebra: use modern C function definition

- bgpd/bgp_aspath.c
- bgpd/bgp_debug.c
- lib/if.c
> *: Remove tests for some XFREE-family functions

- bgpd/bgp_aspath.c
- bgpd/bgp_aspath.h
This is only for bgp_aspath.[ch]
> bgpd: Convert type int functions to bool which return 0/1 only

- bgpd/bgp_mplsvpn.c
- bgpd/bgp_network.c
- bgpd/bgp_network.h
- bgpd/bgp_route.c
- bgpd/bgpd.c
- doc/user/bgp.rst
- lib/systemd.c
- pimd/pim_ifchannel.c
- zebra/rt_netlink.c
- zebra/zebra_vxlan.c
- zebra/zebra_vxlan.h
See individual commits for full details
But this is a grab bag of accidently mixed commits that should be upstreamed.
> Missed upstreaming

- zebra/rt_netlink.c
The return type of is_selfroute function is changed from int to bool.
Also remove the redundant invoking of the is_selfroute function in the
calling function netlink_route_change_read_unicast
Fixes: https://github.com/FRRouting/frr/issues/5984
Signed-off-by: Naveen Naidu <naveennaidu479@gmail.com>
> zebra/rt_netlink.c: Clean is_selfroute function

- zebra/zapi_msg.c
> zebra: Distinguish source/destination PBR IP in zlog_warn messages

- doc/user/overview.rst
> doc: Add rfc6608 to supported list

- pimd/pim_cmd.c
S - Sparse Mode
C - indicates there is a member of the group directly connected to the router.
R -set on an (S, G) by the receipt of an (S, G) RP bit prune message.
F -This indicates that this router is a FHR and send register messages to RP to inform RP of this active source
P - OIL list is NULL. That means the router will send a prune.
T - At least one packet received via SPT.
> pimd: add flags in show ip mroute command

- bgpd/bgp_aspath.c
- bgpd/bgp_aspath.h
- bgpd/bgp_attr.c
- bgpd/bgp_packet.c
- bgpd/bgp_route.c
- doc/user/overview.rst
- tests/bgpd/test_aspath.c
- tests/bgpd/test_aspath.py
See individual commits. https://tools.ietf.org/html/rfc7607
>  bgpd: Proscribe the use of AS 0 (zero)

- configure.ac
For some reason the check did not work
> build: really disable pimd on OpenBSD

- configure.ac
> Disable pimd on MacOS

- doc/developer/building-frr-for-archlinux.rst
- doc/developer/building.rst
Signed-off-by: Naveen Naidu <naveennaidu479@gmail.com>
> doc: Add build instructions for Arch Linux

- lib/libfrr.h
- lib/memory.h
- zebra/zserv.h
> treewide: add attribute to functions that do not return

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/ospf6-topo1/test_ospf6_topo1.py
small topotest fixes to make it run on Ubuntu 18.04 with HWE kernel (5.3)
> Topotest fixes for Kernel 5.3 & locale

- doc/user/overview.rst
> doc: Add rfc7606 to BGP supported RFCs list

- lib/mlag.c
- pimd/pim_mroute.c
- pimd/pim_vxlan.c
some more problems uncovered by coverity
> Coverity pim

- doc/user/nhrpd.rst
- nhrpd/nhrp_vty.c
add json support for show nhrp vty commands.
> nhrpd: add json support to show nhrp vty commands

- pimd/pim_cmd.c
> pimd: re-shaping show ip mroute outout

- pimd/pim_iface.c
- pimd/pim_pim.c
- pimd/pim_pim.h
RCA: This was todo item in current code base
Fix: Hello sent with 0 hold time before we update the pim ifp primary address
Signed-off-by: Saravanan K <saravanank@vmware.com>
> pimd: Pim hello should be sent with 0 hold time on address change onold src ip

- lib/nexthop.c
> lib: remove null check before free nh_labels

- configure.ac
- sharpd/sharp_logpump.c
- sharpd/sharp_vty.c
- sharpd/sharp_vty.h
- sharpd/subdir.am
Cooked this up in order to test PR #5451.  Can be merged independently (**not** dependent on 5451.)
> sharpd: add "logpump" to bulk test logging

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/ospf6-topo1/test_ospf6_topo1.py
Same as PR # 6064 for 7.3 branch. Fixes for Topotests on Linux Kernel 5.3
> Topotest fixes

- bgpd/bgp_vty.c
In the past, we always displayed the number of buffered ingress packets
as zero because there was no packet buffering in the input path and
therefore never any queue size to report. They're buffered now so we can
display something meaningful instead of 0.
Also change the inq / outq lookups to be atomic, since they can be
modified elsewhere. These should still compile down to an unfenced word
read but it's good to be explicit.
> bgpd: display ingress packet queue size

- bgpd/bgp_packet.c
> bgpd: Correct two comments typos for bgp_collision_detect()

- doc/developer/workflow.rst
> doc: document JSON conventions

- zebra/rt_netlink.c
> [7.3] zebra: determine src with nexthop objects as well

- zebra/zebra_router.c
> [7.3] zebra: free unhashable (dup) NHEs via ID table cleanup

- bgpd/bgp_vty.c
- ospf6d/ospf6_top.c
- ospfd/ospf_vty.c
> [7.3] bgpd, ospfd, ospf6d: long is not bool :(

- bgpd/bgp_packet.c
- doc/user/overview.rst
- tests/topotests/bgp_as_wide_bgp_identifier/r1/bgpd.conf
- tests/topotests/bgp_as_wide_bgp_identifier/r1/zebra.conf
- tests/topotests/bgp_as_wide_bgp_identifier/r2/bgpd.conf
- tests/topotests/bgp_as_wide_bgp_identifier/r2/zebra.conf
- tests/topotests/bgp_as_wide_bgp_identifier/r3/bgpd.conf
- tests/topotests/bgp_as_wide_bgp_identifier/r3/zebra.conf
- tests/topotests/bgp_as_wide_bgp_identifier/test_bgp_as_wide_bgp_identifier.py
Implement https://tools.ietf.org/html/rfc6286
> bgpd: Add support for Autonomous-System-Wide Unique BGP Identifier

- lib/grammar_sandbox_main.c
- lib/if.c
- lib/libfrr.c
- lib/northbound.c
- lib/northbound.h
- lib/routemap_northbound.c
- lib/yang.c
- lib/yang.h
- lib/yang_translator.c
- tests/bgpd/test_peer_attr.c
- tests/helpers/c/main.c
- tests/lib/cli/common_cli.c
- tests/lib/cli/test_commands.c
- tests/lib/northbound/test_oper_data.c
- tools/gen_northbound_callbacks.c
- tools/gen_yang_deviations.c
Please see the commit messages for details.
> Minor NB improvements

- bgpd/bgp_main.c
- zebra/main.c
> bgpd, zebra: don't compare unsigned < 0

- zebra/zapi_msg.c
- zebra/zebra_nhg.c
- zebra/zebra_nhg_private.h
> [7.3] NHG Backports

- bgpd/bgp_attr.c
> bgpd: Treat-as-withdraw if [el]community length is zero

- lib/nexthop_group.c
Use more limited matching logic so that nexthops within a nexthop-group are unique based only on vrf, gateway, and label stack. Treat configuration of a nexthop that matches an existing nexthop as a replace operation.
Current behavior allows this:
```
mjs-uvm18# conf t
mjs-uvm18(config)# nexthop-group one
mjs-uvm18(config-nh-group)# nexthop 1.1.1.1
mjs-uvm18(config-nh-group)# nexthop 1.1.1.1 weight 1
mjs-uvm18(config-nh-group)# nexthop 1.1.1.1 weight 2
mjs-uvm18(config-nh-group)# nexthop 1.1.1.1 weight 3
mjs-uvm18(config-nh-group)# do sho run
Building configuration...
!
frr version 7.4-dev-WORK
hostname mjs-uvm18
!
nexthop-group one
nexthop 1.1.1.1
nexthop 1.1.1.1 weight 1
nexthop 1.1.1.1 weight 2
nexthop 1.1.1.1 weight 3
!
```
This change …
> lib: support replacement in the nexthop-group cli

- bgpd/bgp_ecommunity.c
> bgpd: clean up SA warning in bgp_ecommunity.c

- zebra/redistribute.c
When default route is requested from client, default
route is sent to client if present. When route gets
deleted then delete is sent to clients.
Signed-off-by: Santosh P K <sapk@vmware.com>
> Zebra: Default route distribute handling.

- tests/topotests/all-protocol-startup/r1/ipv4_routes.ref
- tests/topotests/all-protocol-startup/r1/zebra.conf
Add a couple more tests to static route installation
Do some very very basic work to make sure that they are working
the way we want.
> tests: Add a couple more static route tests

- bgpd/bgp_community.c
- bgpd/bgp_community.h
> bgpd: Use COMMUNITY_SIZE instead of just 4

- configure.ac
- tests/subdir.am
- yang/embedmodel.py
Commit subjects/text say it all.  Just some fixes, for parallel / separate-builddir / git worktree.
> assorted build fixes

- doc/user/bgp.rst
- doc/user/conf.py
- doc/user/subdir.am
- doc/user/wecmp_linkbw.rst
> doc: Documentation for weighted ECMP and link bandwidth

- zebra/zebra_fpm.c
Issue:
For consecutive messages such as
MAC1 -> VTEP1 add
MAC1 -> VTEP2 add
MAC1 -> VTEP1 add
Final state, i.e. (MAC1 -> VTEP1 add) should be sent via FPM.
But, with current code, FPM will send (MAC1 -> VTEP2 add)
RCA:
When FPM receives (MAC1, VTEP1), it stores it in the FPM processing queue and
hash table.
When FPM receives (MAC1, VTEP2), this entry is stored as another node as hash
table key is (mac, vtep and vni)
IF FPM again receives (MAC1, VTEP1), we fetch this node in the hash table
which is already enqueued.
When the FPM queue is processed, we will send FPM message for (MAC1, VTEP1)
first and then for (MAC1, VTEP2)
This sequencing issue happened because the key of the table is (MAC, VTEP, VNI)
Fix:
Change the key of the hash table to (MAC, VNI)
So, every time we receive a new …
> zebra: Address sequencing issue while sending RMAC via FPM

- ospf6d/ospf6_abr.c
Processing loop uncovered when there are multiple ABRs also
acting as ASBRs into the same area in ospf6.  The problem
was that when looking thru the list of Inter-area router
entries, if the current entry being processed matched, it
still merged next-hops and re-initiated the process.  In
this fix, if the route/path matches and the next-hops also
match, there is no need to re-initiate the examine process.
Ticket: CM-28900
> [7.3]ospf6d: stop looping thru same Inter-Area Router LSAs

- ospfd/ospf_packet.c
Fix
- Modulo check on data length not inclusive enough
- Garbage heap read when bounds checking
```
==19733==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6100000089fd at pc 0x0000006ab584 bp 0x7ffe833ea8a0 sp 0x7ffe833ea898
READ of size 1 at 0x6100000089fd thread T0
#0 0x6ab583 in ospf_router_lsa_links_examin /home/qlyoung/projects/frr/ospfd/ospf_packet.c:2622:47
#1 0x6aae8a in ospf_lsa_examin /home/qlyoung/projects/frr/ospfd/ospf_packet.c:2670:9
#2 0x6a9c0e in ospf_lsaseq_examin /home/qlyoung/projects/frr/ospfd/ospf_packet.c:2777:18
#3 0x66dd41 in ospf_packet_examin /home/qlyoung/projects/frr/ospfd/ospf_packet.c:2894:9
#4 0x665dcf in ospf_read_helper /home/qlyoung/projects/frr/ospfd/ospf_packet.c:3036:9
#5 …
```
> ospfd: router LSA link info missing length check

- bgpd/bgp_route.c
- bgpd/bgp_vty.h
- doc/user/bgp.rst
- lib/json.c
- lib/json.h
- add json to show bgp <AFI> <SAFI> statistics
- add vty : show bgp [vrf XXX ] statistics-all
> Bgp stats all

- zebra/zebra_dplane.c
- zebra/zebra_nhg.c
Fix several coverity scan warnings reported recently.
> zebra: fix some coverity SA warnings

- zebra/zserv.c
> zebra: use %u for unsigned when printing counters

- isisd/isis_adjacency.c
- isisd/isis_adjacency.h
- isisd/isis_bfd.c
- isisd/isis_pdu.c
- isisd/isisd.c
- ospf6d/ospf6_flood.c
- ospf6d/ospf6_lsa.c
- ospf6d/ospf6_lsa.h
- ospf6d/ospf6_lsdb.c
- ospf6d/ospf6_message.c
fix up a couple more coverity SA issues found
> More scan more

- lib/bitfield.h
> lib: dont null check bitfield pointer before free

- ldpd/ldp_zebra.c
When the Independent Control mode is in use (the default one),
each LDP speaker allocates labels independently, which can lead to
broken LSPs when the LDP and IGP domains are not congruent.
What we were doing in this case was to drop all packets coming
through a broken LSP, which causes drastic side effects in the
network like loss of IP connectivity between routers.
We can however do a best-effort attempt to avoid packet loss by
popping the top-level label of the incoming packets and forwarding
them normally to their nexthops. This will be enough to guarantee
that labeled IP packets will reach their final destination. The
broken LSPs will still be unsuitable to tunnel labeled traffic, like
VPN packets, but in this case there's nothing we can do about it.
Cisco's IOS does something …
> [7.3] ldpd: don't drop packets coming through a broken LSP

- lib/subdir.am
- yang/frr-pim-rp.yang
- yang/frr-pim.yang
- yang/subdir.am
Defining yang files for pim
Co-authored-by: Sarita Patra saritap@vmware.com
Co-authored-by: Santosh P K sapk@vmware.com
Co-authored-by: vishaldhingra vdhingra@vmware.com
Signed-off-by: Sarita Patra saritap@vmware.com
> yang: Defining yang files for pim

- bgpd/bgp_route.c
- tests/topotests/bgp_show_ip_bgp_fqdn/r2/bgpd.conf
- tests/topotests/bgp_show_ip_bgp_fqdn/r2/zebra.conf
- tests/topotests/bgp_show_ip_bgp_fqdn/r3/bgpd.conf
- tests/topotests/bgp_show_ip_bgp_fqdn/r3/zebra.conf
- tests/topotests/bgp_show_ip_bgp_fqdn/test_bgp_show_ip_bgp_fqdn.py
> bgpd: [7.3] Show hostname in `show [ip] bgp ...` only if nexthop is connected

- bgpd/bgp_route.c
> bgpd: [7.3] Do not discard an UPDATE if the global nexthop is set to ::

- bfdd/bfdd_vty.c
display debugging status of bfd.
> bfdd: display debugging status of bfd

- bgpd/bgp_updgrp_adv.c
- pimd/pim_igmp_mtrace.c
- tests/bgpd/test_mpath.c
> *: triple pack of one-liner WTF fixes

- lib/filter.c
Comments under commit.
Closes https://github.com/FRRouting/frr/issues/6244
> lib: Delete the entire access-list only if there are no more entries

- zebra/zebra_pw.c
zebra: fix zebra pseudowire manager NHT
Intermittently, there is a 30 second delay for a LDP pseudowire to become
operational.
One way to reproduce the issue is: Once PW is up, shutdown link to trigger
a change to the pseudowire's next hop, and then restore link to cause
pseudowire to return to original NH.
Problem Descripton:
The Zebra PW manager installs pseudowires in the data plane when the
following two conditions are met:
1. Pseudowire is labeled via LDP mapping messages
2. A labeled NH route exists to reach the remote pseudowire endpoint
The Zebra PW manager registers a NHT callback when a pseudowire is enabled.
This allows the Zebra PW manager to install or reinstall the pseudowire.
The Zebra PW manager deregisters for the NHT callback when the pseudowire is
disabled.  When LDP …
> zebra: fix zebra pseudowire manager NHT

- zebra/zebra_rib.c
An async route notification can indicate that installation has failed, but the handling code wasn't dealing with that possibility correctly.
> zebra: fix handling of failed route install via notification

- lib/filter.c
> lib: [7.3] Delete the entire access-list only if there are no more entries

- zebra/if_netlink.c
The netlink_vrf_change() function is called both when a VRF device
is created in the Linux kernel and when it is activated. This
commit changes this function to perform the VRF misconfiguration
detection only when the VRF device is created, as doing the check
twice would cause a false positive followed by a hard failure (not
to mention the double check is unnecessary since the VRF table ID
can't change once the device is created).
Fixes #6319.
> zebra: fix detection of VRF misconfiguration

- doc/user/bgp.rst
Closes https://github.com/FRRouting/frr/issues/3446
> doc: Add an example how to filter BGP bogon ASNs

- zebra/rt_netlink.c
Abstract the 5549 ipv4 over ipv6 into a function for easier
code reuse and reading.
Signed-off-by: Stephen Worley <sworley@cumulusnetworks.com>
> zebra: abstract 5549 check into a function

- bgpd/bgp_vty.c
The `bgp bestpath bandwidth` command should not be a legal
command.  Pull out the `no` form to allow this.  Allow
`no bgp bestpath bandwidth` to work as we would expect.
> bgpd: `bgp bestpath bandwidth` should not be a legal command

- zebra/rib.h
- zebra/rtadv.c
- zebra/rtadv.h
- zebra/zebra_dplane.c
- zebra/zebra_fpm.c
- zebra/zebra_fpm_netlink.c
- zebra/zebra_nhg.c
- zebra/zebra_rib.c
- zebra/zebra_rnh.c
- zebra/zebra_rnh.h
- zebra/zebra_router.c
- zebra/zebra_vrf.h
- zebra/zebra_vty.c
first round of removing some unneeded typedefs from the systm
> Typedef i hatez it

- lib/northbound_grpc.cpp
Bit of leftover copypaste code there.
Also cleans up some unnecessary {}
> lib: remove unnecessary rpc request in grpc

- doc/user/overview.rst
Add the VRRP bloc + RFC associated
> overview.rst: add RFC to VRRP

- yang/LICENSE
- yang/frr-bfdd.yang
- yang/frr-eigrpd.yang
- yang/frr-filter.yang
- yang/frr-igmp.yang
- yang/frr-interface.yang
- yang/frr-isisd.yang
- yang/frr-module-translator.yang
- yang/frr-nexthop.yang
- yang/frr-pim-rp.yang
- yang/frr-pim.yang
- yang/frr-ripd.yang
- yang/frr-ripngd.yang
- yang/frr-route-map.yang
- yang/frr-route-types.yang
- yang/frr-routing.yang
- yang/frr-staticd.yang
- yang/frr-test-module.yang
- yang/frr-vrf.yang
- yang/frr-vrrpd.yang
- yang/frr-zebra.yang
Opening this PR upon request of @ahw59 in order to prompt a discussion about this topic on tomorrow's call.
This is a draft PR since we need to gather approval of everyone who wrote a FRR YANG module before it's ready for merge.
> Adopt the BSD-2-Clause license for our YANG modules

- tests/topotests/bgp_gr_functionality_topo1/bgp_gr_topojson_topo1.json
- tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1.py
- tests/topotests/bgp_gr_functionality_topo2/bgp_gr_topojson_topo2.json
- tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2.py
- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
- tests/topotests/lib/topogen.py
- tests/topotests/lib/topotest.py
1. Test suite bgp_gr_functionality_topo1 has 25 test cases, execution time is ~20 Mins
2. Test suite bgp_gr_functionality_topo2 has 17 test cases, execution time is ~21 Mins
3. Framework is enhanced to support BGP-GR config and verifications.
> tests: Add bgp-graceful-restart test suites

- bgpd/bgp_filter.c
- bgpd/bgp_vty.c
- tools/frr-reload.py
Some Double commits from master
> [7.4] DC's

- zebra/zapi_msg.c
- zebra/zebra_nhg.c
When checking if a nexthop is active, if it has been marked as onlink, just check on the presence and status of the nexthop's interface. When handling client request to create a route, if the client says that the nexthop is onlink, trust it; when internally (in zebra) determining that the nexthop is onlink, ensure it is only done in the case of an interface with a /32 IP address which is the case for OSPF unnumbered.
Reviewed-by:   Donald Sharp <sharpd@cumulusnetworks.com>
Reviewed-by:   Stephen Worley <sworley@cumulusnetworks.com>
> zebra: Trust onlink flag for nexthop active resolution

- zebra/rt_netlink.c
Fix a couple of problems with MAC install that originated from a prior code refinement
> Zebra macfdb fixup

- zebra/zebra_nhg.c
When resolving a recursive nexthop, prefer the "outer" label type, if present. If both the recursive and resolving nexthops had labels, we were ending up with the 'inner' type from the recursive nh. I _think_ this is largely a cosmetic change.
> zebra: prefer outer label_type for recursive nexthops

- bfdd/bfd.c
- bfdd/bfd.h
- bfdd/bfdd_nb_config.c
- yang/frr-bfdd.yang
Two small changes:
- Show the correct RFC number for BFD multi hop in YANG model comment.
- Remove duplicated code by moving it to a function.
> bfdd: remove duplicated code and fix comment

- bgpd/bgp_vty.c
Clean up a few lines of cli command installation; remove a duplicate; follow the command grouping pattern better.
Should fix issue #6430
> bgpd: remove duplicate cli command installation

- zebra/rtadv.c
- zebra/zapi_msg.c
1) fix compilation failures when rtadv was disabled by configure
2) Make the code handle rtadv turned off a bit more gracefully
> Fix rtadv stuff

- lib/prefix.c
> lib: Minor update to EVPN type-5 prefix display

- bgpd/bgp_nexthop.c
Display next hop resolution information, whether the "detail" option is
specified or not as it is quite fundamental and only minimally increases
the output.
Introduce option to look at a specific NHT entry, which will also show
the paths associated with that entry.
> bgpd: Enhance BGP NHT show commands

- tests/topotests/bgp-vrf-route-leak-basic/test_bgp-vrf-route-leak-basic.py
Changes:
- Renamed file so it is instantly obvious what it is.
- Use `json_cmp` instead of direct key access.
Recently I stumbled with this topotest failure:
https://ci1.netdef.org/browse/FRR-FRRPULLREQ-TOPOU1604-12381
The error message and the test name were mysterious:
If we go to the test execution logs it shows what test file it is:
```
build	24-May-2020 07:12:53	bgp-vrf-route-leak-basic/test_bgp.py::test_vrf_route_leak 2020-05-24 16:12:53,469 INFO: loading topology: test_bgp
build	24-May-2020 07:12:53	2020-05-24 16:12:53,470 INFO: starting topology: test_bgp
build	24-May-2020 07:12:53	2020-05-24 16:12:53,517 INFO: r1: running version: 7.5-dev-20200524-02-gfc0a7cad0
build	24-May-2020 07:12:53	2020-05-24 16:12:53,518 INFO: r1: waiting for zebra to start (1 seconds)
build	24-May-2020 …
```
> topotest: refactory BGP VRF leak basic test

- doc/user/bgp.rst
Closes https://github.com/FRRouting/frr/issues/6470
> doc: Update BGP show bgp (ext|large-)community-list commands

- doc/developer/workflow.rst
Add some text to the developer doc encouraging use of 'const'
> doc: encourage const in the developer doc

- bgpd/bgp_network.c
- doc/user/snmp.rst
1) fix a doc bug
2) add some clarification where incoming connections are being mapped to to help reduce debugging time.
> More useful debug

- bgpd/bgp_network.c
bgp_accept() gets called over and over again when a VRF device is
deleted out from under a bgp listener socket that is bound to it.
Prevent this by noting the error and cancelling ourselves, allowing the
vrf status code to clean up the mess when it receives word about the
change from Zebra.
> bgpd: avoid spamming bgp_accept() on bad vrf sock

- pimd/pim_mlag.c
- pimd/pim_oil.c
- pimd/pim_upstream.h
some more missed merge and some improved debugging
> Pim missed merge

- bgpd/bgp_io.c
When received packet is processed in bgp_process_reads(), the data
is copied to static buffer and then copied to stream buffer.
The data can be copied directly to stream buffer which will avoid extra memcpy
Signed-off-by: kssoman <somanks@gmail.com>
> bgpd: Avoid extra copy of received data to buffer

- tests/topotests/route-scale/r1/installed.routes.json
- tests/topotests/route-scale/r1/no.routes.json
- tests/topotests/route-scale/r1/sharpd.conf
- tests/topotests/route-scale/r1/zebra.conf
- tests/topotests/route-scale/test_route_scale.py
Add some basic route scale tests to ensure that we can
install a large number of routes.  Also grab some timings
so that we can keep track and see if anything substantially
changes over time.
> tests: Add some scale tests to ensure things work

- bgpd/bgp_updgrp_packet.c
> bgpd: Use constants for nexthop length instead of just numbers

- pimd/pim_mlag.c
This section of code was ported incorrectly and is causing
issues when running against some tests.  Fix the missed
code.
> pimd: Poorly ported code fix

- bgpd/bgp_route.c
If we have something like:
```
ip route 1.1.1.0/24 Null0
!
router bgp 100
neighbor 192.168.0.2 remote-as 200
!
network 1.1.1.0/24
redistribute connected
!
line vty
!
```
1.1.1.0/24 is not advertised due to martian nexthop (0.0.0.0). It starts
working only when we use `redistribute static`.
By checking if it's a BGP static route we able to announce
1.1.1.0/24 with `network 1.1.1.0/24` without redistribute even when
`bgp import-check` is enabled.
Disabling `bgp import-check` works as well, but it's enabled by default
since 7.4.
Related: https://github.com/FRRouting/frr/issues/6552
> bgpd: Do not treat the route as martian for static BGP routes

- bgpd/bgp_route.c
If we have something like:
```
ip route 1.1.1.0/24 Null0
!
router bgp 100
neighbor 192.168.0.2 remote-as 200
!
network 1.1.1.0/24
redistribute connected
!
line vty
!
```
1.1.1.0/24 is not advertised due to martian nexthop (0.0.0.0). It starts
working only when we use `redistribute static`.
By checking if it's a BGP static route we able to announce
1.1.1.0/24 with `network 1.1.1.0/24` without redistribute even when
`bgp import-check` is enabled.
Disabling `bgp import-check` works as well, but it's enabled by default
since 7.4.
> bgpd: [7.4] Do not treat the route as martian for static BGP routes

- tests/topotests/pbr-topo1/test_pbr_topo1.py
This may be expanded in the future as we figure out more things
to gather when the test has gone south.
> tests: the pbr topo1 test is failing gather data to help debug

- tests/topotests/lib/common_config.py
Include vrf name with interface name when topojson framework generates interface configuration. This matches the output of 'show runn', and makes config reset less disruptive. The topojson framework uses a diff generated by frr-reload to reset config to a base state at the beginning of each testcase in a suite. Because the interface names did not match, the diff was removing and then re-adding every ip address on every interface, over and over again.
Also protect debug and log output configuration, so they aren't lost if a developer is trying to debug within a topojson suite.
> tests: in topojson framework, include vrf with interface name

- debian/frr.logrotate
- redhat/frr.logrotate
both redhat and debian control files were missing knowledge of some daemons in the logrotate stuff
> Forgotten daemons

- zebra/zebra_rib.c
Improve and centralize some logic used to a) compare two route_entries, and b) to locate a route_entry that matches a dplane context object that contains the results of a fib update. We were not rigorous enough in checking routes' properties, especially when examining connected routes where we allow multiple route_entries.
Donald and Don S reported problems in a special case where multiple interfaces shared an ip prefix: we were not properly locating route_entries that matched the incoming info from the kernel or from the dataplane module.
> zebra: improve route_entry comparison logic

- doc/developer/building-docker.rst
- doc/developer/building.rst
our docker build docs are nonexistent
> doc: add docker image build instructions

- bgpd/bgp_vty.c
We have a bunch of code in bgp_vty.c that was passing
to peer_af_flag_modify_vty more than 1 flag at a time.
This was causing the underlying routines to get the
flags wrong.  In order to prevent this convert all the
places where we send multiple flags down to this function
to individual flag changes.
> bgpd: peer_af_flag_modify_vty assumes 1 flag at a time

- bgpd/bgp_bmp.c
- bgpd/bgp_bmp.h
Co-authored-by: giacomo270197 <gcasoni@hotmail.it>
Signed-off-by: streambinder <posta@davidepucci.it>
> bgpd: bmp: add support for L2VPN/EVPN routes

- bgpd/bgp_ecommunity.c
- bgpd/bgp_route.c
> bgpd: Return bool type for ecommunity_add_val and subgroup_announce_check

- tests/topotests/lib/topotest.py
Add a few retries during router shutdown before killing a daemon- we've seen some crashes as a result of those aggressive kills.  Also work harder to start only a single instance of daemons, esp. zebra. In all_protocol_startup, I was seeing two zebra start attempts, for example, and the way `remove` was being used wouldn't remove multiple elements if present.
> tests: wait longer when shutting down in topotests

- pbrd/pbr_vty.c
When specifying an interface in a pbr-map `set nexthop ..` command
be a bit more lenient about the interface.
a) If the interface does not exist bail on the command
(this is the same)
b) If the interface exists but is in a different vrf
than specified use the vrf it is actually in.
(this is new behavior)
Ticket: CM-30187
> pbrd: Be a bit more lenient with `set nexthop A.B.C.D <intf>`

- tests/topotests/bgp_recursive_route_ebgp_multi_hop/bgp_recursive_route_ebgp_multi_hop.json
- tests/topotests/bgp_recursive_route_ebgp_multi_hop/test_bgp_recursive_route_ebgp_multi_hop.py
- tests/topotests/lib/bgp.py
1. Added 7 test cases to verify bgp recursive routes and ebgp multi-hop functionality
2. Added framework support to automate these test cases
3. Total execution time is ~5 mins
> tests: Add bgp_recursive_route_ebgp_multi_hop test suite

- zebra/zebra_mpls.c
Check the LSP INSTALLED flag in delete apis, to ensure we enqueue a delete operation for the lfib. Some apis were only checking the nexthop/nhlfe INSTALLED flags, and those could be unset if there's an in-flight dataplane update.
> zebra: check LSP flags when deleting an LSP

- tests/topotests/lib/common_config.py
- tests/topotests/lib/topotest.py
1. It will generate support bundle/sump data on test failures
2. It used /usr/lib/frr/generate_support_bundle.py utility to dump the data
3. It will help in debugging when a test failes.
4. Data will be dumped at following location: /tmp/topotests/<testuiste_name>/<router_name>/support_bundles/<testcase_name>
> tests: Generate support bundle/dump data on tests failures

- doc/user/pim.rst
> pimd: Add some missing mesh-group pim cmds

- lib/frr_pthread.c
Block signals in child/additional pthreads; frr daemons generally expect that only the main thread will handle signals.
> lib: block signals in child pthreads

- lib/if.c
- lib/if.h
- zebra/interface.c
These changes were discussed with @donaldsharp.
Requesting for comments from the community.
> [RFC] zebra: remove vrf parameter from "show interface ..." commands

- zebra/kernel_netlink.c
Yet another netlink cleanup. This time, I split some functions to smaller and more generic ones, as they will be useful for the netlink batching project.
> zebra: netlink cleanup

- bfdd/bfdd_nb_config.c
Add missing profile update hook for detection multiplier change.
> bfdd: update detect multiplier on profile change

- changelog-auto.in
> [7.4] debian: fix changelog

- pimd/pim_mlag.c
- pimd/pim_mlag.h
- pimd/pim_rp.c
- pimd/pimd.c
see individual commits, but pretty obvious.  memory leaks on shutdown
> Pim mem leaks

- pbrd/pbr_map.c
- pbrd/pbr_map.h
- pbrd/pbr_nht.c
A couple pbr fixes, see individual commits.
> pbrd: A couple pbr fixes

- pimd/pim_cmd.c
- zebra/zebra_netns_notify.c
A couple issues turned up when switching to a new compiler.
> Compile issues

- ospfd/ospf_vty.c
> ospfd: remove redundant line continuations

- tools/frr-reload.py
Reported that in certain config changes, a static intended for the
default table would be duplicated into a vrf context.  Determined
that we still weren't keeping or adding the exit-vrf command when
necessary to keep the contexts straight.  Added logic to look for
the failing circumstances and add or remove the delete of the
exit-vrf command as needed.
> tools: fix more frr-reload vrf static errors

- bgpd/bgp_route.c
Check for details in individual commits.
Related: https://github.com/FRRouting/frr/pull/6722
Related: https://github.com/FRRouting/frr/issues/6699
> bgpd: Handle default bgp vrf all for statistics

- bgpd/bgp_flowspec_vty.c
- zebra/zebra_pbr.c
some regressions introduced have to be fixed now
> Flowspec some regression seen

- bgpd/bgp_route.c
> bgpd: [7.4] Handle default bgp vrf all for statistics

- bgpd/bgp_bmp.c
- bgpd/bgp_evpn_vty.c
- bgpd/bgp_main.c
Another round of small coverity code cleanup that has snuck in over the last year
> Coverity code cleanup

- bgpd/bgpd.c
- bgpd/bgpd.h
> bgpd: Remove peer_afc_set()

- bgpd/bgp_route.c
- bgpd/bgp_route.h
- doc/user/bgp.rst
add a new command
`show bgp ipv4 uni neighbor 192.168.161.2 bestpath-routes` which will display for the given peer the list of routes selected by bestpath
> Bestpath routes

- zebra/rt_netlink.c
> [7.4] Zebra macfdb fixup

- zebra/dplane_fpm_nl.c
Summary
------------
Two highlights:
- ~~Make data plane framework use the sequence field in the context~~
- FPM thread race fixes
Most of the work here is to make easier to debug FPM (e.g. new debug log messages telling us when start up route sending finishes), fix a race when using FPM input (currently FPM only discards input messages) and track the end of zebra table walks.
> zebra: FPM fixes

- doc/user/bgp.rst
Related: https://github.com/FRRouting/frr/pull/6793
> doc: Add wide option for show bgp commands

- vtysh/vtysh_config.c
With a config that contains a large number of prefix-lists a 'show run' command
was an expensive operation:
sharpd@eva ~/frr_internal2 ((cl4.1.0))> time vtysh -c "show run" | grep ACTIVE | wc -l
32397
________________________________________________________
Executed in   14.53 secs   fish           external
usr time   14.45 secs  591.00 micros   14.45 secs
sys time    0.03 secs  189.00 micros    0.03 secs
sharpd@eva ~/frr_internal2 ((cl4.1.0))>
Effectively we are keeping a linked list of data to store the configuration.
When we received a new item we would look in the list to see if it already
does, by doing a string search across each element in the list.
Add to the master configuration a hash of items for O(1) lookup.
Keep the list for order so we don't mangle that up.
New time: …
> vtysh: Speed up output of configuration across daemons

- doc/user/pim.rst
> doc: Update doc for `ip pim use-source ..` command

- ldpd/lde_lib.c
When LDP is configured in Order Control mode and we receive a
label withdraw message, we should only resend label withdraws to
peers that are the NH for that fec being withdrawn.  This is a
double commit.   Original fix in master is #6864.
Signed-off-by: Lynne Morrison lynne@voltanet.io
> ldpd: ldp-oc withdraw fix

- lib/yang_wrappers.c
Add more afi safis in conversion to-from string to indentityref.
> lib: yang afi-safi identityref translation

- doc/developer/building-frr-for-openwrt.rst
Frr was added to official OpenWrt repo. No need to use
unofficial sources from Github PR.
Signed-off-by: Pawel Dembicki <p.dembicki@wb.com.pl>
> doc: Update instructions for building for OpenWrt

- bgpd/bgp_snmp.c
Currently, bgpPeerTable only looks the default BGP instance. Most
vendors return all the available peers in this table. This commit
exposes all BGP instances.
The other tables are unchanged as it doesn't make sense to expose
routes from random VRFs into a single table. Vendors are using SNMP
contexts for that but we don't have support for it. Therefore, do
nothing.
Fix #6077
> bgpd: implement bgpPeerTable accross VRFs

- lib/yang.c
- lib/yang.h
- yang/embedmodel.py
BGP Yang is using sub modules and at present FRR is not processing
submodules in embedded framework yang
Signed-off-by: VishalDhingra <vdhingra@vmware.com>
> lib: Add support to load submodules in embedded modules framework

- bgpd/bgp_evpn_vty.c
- lib/routemap_cli.c
Summary
------------
Some doc strings got lost in a merge somewhere, this PR puts them back.
> bgpd,lib: add missing doc strings

- doc/developer/grpc.rst
- doc/developer/index.rst
- doc/developer/subdir.am
- doc/user/grpc.rst
- doc/user/index.rst
- doc/user/subdir.am
Summary
------------
Add some gRPC northbound documentation to let users attempt to use it.
Information Sources
-------------------------
- [Original PR](https://github.com/FRRouting/frr/pull/4082)
- [Ruby Example](https://gist.github.com/rwestphal/6528ebeb8a612711ca3771b843a4eb14)
- [Python Example](https://gist.github.com/rwestphal/4b392347b76743c35d931c9b845f624e)
- [Proto file with all features defintions](https://github.com/FRRouting/frr/blob/master/grpc/frr-northbound.proto)
> doc: initial documentation for gRPC

- doc/user/bgp.rst
> doc: document effect of ebgp-multihop

- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py
- tests/topotests/lib/common_config.py
- zebra/zebra_vty.c
Fix a bug in the recent nb conversion of vni code in zebra
Fix a bug in a recently introduced test
Add some helpful debug information when tests go bad to the new evpn type 5 test
> Test fixups

- lib/thread.c
1) Handle POLLERR
2) Cleanup comment sections as that they were a mess
> Poll error

- lib/filter_nb.c
Summary
------------
Use `args->errmsg` instead of just `zlog_info` for registering the error so the users don't need to check their log files.
Output Example
--------------------
```
frr(config)# ip prefix-list test_pl seq 10 permit 1.2.3.0/24 ge 24
Error description: Invalid prefix range for 1.2.3.0/24: Make sure that mask length < ge <= le
```
And log file:
```
2020/08/13 19:59:02 ZEBRA: [EC 100663331] error processing configuration change: error [validation] event [validate] operation [modify] xpath [/frr-filter:lib/prefix-list[type='ipv4'][name='test_pl']/entry[sequenc
e='10']/ipv4-prefix-length-greater-or-equal]                                                  
2020/08/13 19:59:02 ZEBRA: [EC 100663331] error processing configuration …
```
> lib: show prefix error message on configuration failure

- isisd/isis_adjacency.c
- isisd/isis_adjacency.h
- isisd/isis_circuit.h
- isisd/isis_cli.c
- isisd/isis_lsp.c
- isisd/isis_nb_config.c
- isisd/isis_spf.c
- isisd/isis_sr.c
- isisd/isisd.c
- isisd/isisd.h
- lib/linklist.c
- lib/linklist.h
- tests/topotests/isis-sr-topo1/rt1/isisd.conf
- tests/topotests/isis-sr-topo1/rt2/isisd.conf
- tests/topotests/isis-sr-topo1/rt3/isisd.conf
- tests/topotests/isis-sr-topo1/rt4/isisd.conf
- tests/topotests/isis-sr-topo1/rt5/isisd.conf
- tests/topotests/isis-sr-topo1/rt6/isisd.conf
Assorted isisd bug fixes and enhancements. Please see individual commits for details.
> isisd minor fixes and enhancements

- isisd/fabricd.c
- isisd/isis_adjacency.c
- isisd/isis_bfd.c
- isisd/isis_circuit.c
- isisd/isis_cli.c
- isisd/isis_csm.c
- isisd/isis_dr.c
- isisd/isis_dynhn.c
- isisd/isis_dynhn.h
- isisd/isis_lsp.c
- isisd/isis_lsp.h
- isisd/isis_main.c
- isisd/isis_misc.c
- isisd/isis_misc.h
- isisd/isis_nb_config.c
- isisd/isis_pdu.c
- isisd/isis_redist.c
- isisd/isis_redist.h
- isisd/isis_spf.c
- isisd/isis_sr.c
- isisd/isis_te.c
- isisd/isis_vty_fabricd.c
- isisd/isis_zebra.c
- isisd/isisd.c
- isisd/isisd.h
- tests/isisd/test_isis_lspdb.c
1. Created a structure "isis master".
2. All the changes are related to handle ISIS with different vrf.
3. A new variable added in structure "isis" to store the vrf name.
Signed-off-by: Kaushik <kaushik@niralnetworks.com>
> ISIS VRF: Transformational changes to support different VRFs.

- bgpd/bgp_evpn.c
- bgpd/bgp_packet.c
- bgpd/bgp_updgrp_packet.c
> bgpd: Use sizeof() in bgp_dump_attr()

- tools/frr-reload.py
Add a "--log-level" option to frr-reload to set the maximum message
level to be logged. When the option is not used, the level is set to
info as before.
The existing --debug option is synonymous with --log-level=debug and
these options are therefore mutually exclusive.
Signed-off-by: Duncan Eastoe <duncan.eastoe@att.com>
> tools: frr-reload: more detailed log level control

- bgpd/bgp_route.c
This will check route-maps as well, not only prefix-lists, access-lists, and
filter-lists.
> bgpd: Honor route-maps when forcing maximum-prefix for filtered routes

- doc/user/installation.rst
Make documentation consistent with 0556fc3 changes.
> doc: vrf socket creation logic

- .github/ISSUE_TEMPLATE/bug_report.md
Add lost chapter from issue with bug report
Signed-off-by: Alexey Boldyrev <ne-vlezay80@yandex.ru>
> github: Add lost chapter witch issue template

- doc/user/isisd.rst
- isisd/fabricd.c
- isisd/isis_adjacency.c
- isisd/isis_dynhn.c
- isisd/isis_dynhn.h
- isisd/isis_lsp.c
- isisd/isis_lsp.h
- isisd/isis_main.c
- isisd/isis_misc.c
- isisd/isis_misc.h
- isisd/isis_route.c
- isisd/isis_spf.c
- isisd/isis_spf.h
- isisd/isis_spf_private.h
- isisd/isis_sr.c
- isisd/isis_te.c
- isisd/isisd.c
- isisd/isisd.h
- tests/.gitignore
- tests/isisd/test_common.c
- tests/isisd/test_common.h
- tests/isisd/test_fuzz_isis_tlv.c
- tests/isisd/test_isis_lspdb.c
- tests/isisd/test_isis_spf.c
- tests/isisd/test_isis_spf.in
- tests/isisd/test_isis_spf.py
- tests/isisd/test_isis_spf.refout
- tests/isisd/test_isis_vertex_queue.c
- tests/isisd/test_topologies.c
- tests/subdir.am
This is yet another preliminary PR for the upcoming IS-IS TI-LFA work. Please refer to the individual commits for more details.
> isisd: make the SPF code more modular + reverse SPF + unit tests

- zebra/zebra_dplane.c
- zebra/zebra_rib.c
two commits that clean up some bad behavior from zebra where we ended up in a bad state.
See the commits for an explanation.
> Zebra lies

- lib/zebra.h
- zebra/kernel_netlink.c
- zebra/kernel_netlink.h
- zebra/main.c
This PR modifies netlink fuzzing code to be compatible with the fuzzing infrastructure in the `fuzz` branch.
> zebra: refactor netlink fuzzing

- zebra/kernel_netlink.c
It was wrongly assumed that the kernel is replying in batches when multiple
requests fail. The kernel sends one error message at a time, so we can
simply keep reading data from the socket as long as possible.
Signed-off-by: Jakub Urbańczyk <xthaid@gmail.com>
> zebra: fix netlink batching

- tests/topotests/lib/common_config.py
- tests/topotests/lib/topotest.py
StringIO is one of the pain-points for python2->3. Avoid unnecessary use of StringIO in one place, use version-dependent method in another. Remove a couple of other py2->py3 problems.
> tests: small topotest improvements for python3

- lib/northbound_cli.c
When not using the transactional CLI mode, do not display a
warning when a YANG-modeled commmand doesn't perform any effective
configuration change.
> lib: silence overly verbose CLI warning

- zebra/kernel_netlink.c
Currently, the `--nl-bufsize` option only changes the buffer size of one of the netlink socket that we use in zebra. I propose to use this value in all netlink sockets in zebra, because with the netlink batching we are more likely to hit the default kernel limit.
I also added the `NETLINK_CAP_ACK` option for the dplane netlink socket to reduce the size of responses.
From the Linux manual:
```
NETLINK_CAP_ACK (since Linux 4.2)
The kernel may fail to allocate the necessary room for the
acknowledgment message back to user space.  This option trims
off the payload of the original netlink message.  The netlink
message header is still included, so the user can guess from
the sequence number which message triggered the acknowledg‐
ment.
```
It doesn't affect extended ACKs.
This should fix #7021
> zebra: increase netlink receive buffer size

- eigrpd/eigrp_dump.c
- eigrpd/eigrp_vty.c
bunch of small commits to clean up `vrf all` behavior in eigrp, even if we are not quite ready for it.
> Eigrp fixups

- lib/if.c
- lib/if.h
- lib/nexthop_group.c
- lib/nexthop_group.h
- lib/zclient.c
- pbrd/pbr_map.c
- pbrd/pbr_map.h
- pbrd/pbr_nht.c
- pbrd/pbr_nht.h
- pbrd/pbr_vrf.c
- pbrd/pbr_vty.c
- pbrd/pbr_zebra.c
Bunch of commits that all have to do with networking being yanked out from under FRR/pbr and then putting it all back together again.
See individual commits for what they do
> Pbr vrf is burf

- lib/stream.h
Never implemented, not even sure what I was thinking...
> lib: remove unused stream_get_data api

- bgpd/bgp_mplsvpn.c
NLRI parsing for mpls vpn was missing several length checks that could
easily result in garbage heap reads past the end of nlri->packet.
Convert the whole function to use stream APIs for automatic bounds
checking...
> bgpd: fix mplsvpn nlri garbage heap read

- staticd/static_vty.c
Please see commit messages for details.
> staticd: remove dead code + minor fix

- bgpd/bgp_rpki.c
> bgpd: remove deprecated commands

- bgpd/bgp_clist.c
Problem rerported that if you enter an existing community list
sequence number with new community information, the entire community
list would be deleted.  This commit fixes the replace logic to do
the right thing.
Ticket: CM-30555
> bgpd: correct community-list replace logic

- isisd/isis_route.c
suppress route-event logs that are mostly uninformative, like the fact that a route has not changed, and add more info to the ones that matter, i.e. hints on what changed in a route update. The suppressed logs can be enabled by defining EXTREME_DEBUG to 1, similarly to what is done elsewhere in isisd (e.g. in isis_spf.c)
> isisd: improve route-event logs

- zebra/zebra_vxlan.c
Reverting probing of neigh entry. There is a timing where
probe and remote macip add request comes at the same time resulting
in neigh to remain in local state event though it should be remote.
In mobility case, the host moves to remote VTEP, first MAC only type-2
route is received which triggers a PROBE of neighs (associated to MAC).
PROBE request can go via network port to remote VTEP.
PROBE request picks up local neigh with MAC entry's outgoing port is
remote VTEP tunnel port.
The PROBE reply and MAC-IP (containing IP) almost comes same time at
DUT.
DUT first processes remote macip and installs neigh as remote.
Followed by receives neigh as REACHABLE which marks neigh as LOCAL.
FRR does have BPF filter which does not allow its own netlink request
to receive. Otherwise frr's request to …
> zebra: Revert "zebra: probe local inactive neigh"

- lib/libfrr.c
- lib/libfrr.h
- lib/northbound_sysrepo.c
A couple of fixes to the sysrepo northbound plugin. Please refer to the individual commits for more details.
Fixes #7062
> lib: sysrepo plugin fixes

- bgpd/bgp_evpn.c
bgpd: fix ecom leak handling l3vni update
(cherry picked from commit 84f22ecc05b08d7266605fbd9f6089d6d61e9f03)
> bgpd: fix ecom leak handling l3vni update

- tests/topotests/bgp_route_aggregation/bgp_aggregation.json
- tests/topotests/bgp_route_aggregation/test_bgp_aggregation.py
- tests/topotests/lib/bgp.py
1. Added 2 tests to verify bgp route aggregation using summary-only and
as-set commands
2. Execution time is ~90 sec
> tests: Add bgp_route_aggregation test suite

- ospfd/ospf_zebra.c
1. Fix for duplicating calls of ospf_external_lsa_refresh()
in ospf_distribute_list_update_timer().
2. Added a comment about the scenario and change from PR #6981 
Signed-off-by: Kaushik <kaushik@niralnetworks.com>
> ospfd : Resolving conflict in distribute-list update during MaxAge LSA.

- isisd/isis_ldp_sync.c
- ospfd/ospf_ldp_sync.c
- tests/topotests/ldp-sync-isis-topo1/r1/show_isis_ldp_sync_r1_eth1_shutdown.ref
- tests/topotests/ldp-sync-isis-topo1/r2/show_isis_ldp_sync_r2_eth1_shutdown.ref
- tests/topotests/ldp-sync-isis-topo1/test_ldp_sync_isis_topo1.py
Update the ldp-sync commands to show when an interface is down.
> Fix ldp sync cmds

- zebra/kernel_socket.c
This series of events:
$ sudo ifconfig lo0 add 4.4.4.4/32
$ sudo ifconfig lo0 inet 4.4.4.4/32 delete
would end up leaving the 4.4.4.4/32 address on the interface under
freebsd.
This all boils down to the fact that the interface is not
considered connected yet we have a destination.  If the
destination is the same and we are not connected ignore
it on freebsd.
I am sure there are other fun scenarios that someone
will have to squirrel out.
> zebra: Allow FreeBSD to set and delete addresses from an interface

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/bfd-bgp-cbit-topo3/test_bfd_bgp_cbit_topo3.py
- tests/topotests/bfd-topo1/test_bfd_topo1.py
- tests/topotests/bfd-topo2/test_bfd_topo2.py
- tests/topotests/bfd-vrf-topo1/test_bfd_vrf_topo1.py
- tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
- tests/topotests/bgp_ipv6_rtadv/test_bgp_ipv6_rtadv.py
- tests/topotests/bgp_l3vpn_to_bgp_direct/customize.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/customize.py
- tests/topotests/bgp_multiview_topo1/test_bgp_multiview_topo1.py
- tests/topotests/bgp_rfapi_basic_sanity/customize.py
- tests/topotests/bgp_vrf_lite_ipv6_rtadv/test_bgp_vrf_lite_ipv6_rtadv.py
- tests/topotests/ldp-oc-acl-topo1/test_ldp_oc_acl_topo1.py
- tests/topotests/ldp-oc-topo1/test_ldp_oc_topo1.py
- tests/topotests/ldp-topo1/test_ldp_topo1.py
- tests/topotests/lib/topogen.py
- tests/topotests/lib/topotest.py
- tests/topotests/ospf-topo1-vrf/test_ospf_topo1_vrf.py
- tests/topotests/ospf-topo1/test_ospf_topo1.py
- tests/topotests/pytest.ini
- tests/topotests/rip-topo1/test_rip_topo1.py
- tests/topotests/ripng-topo1/test_ripng_topo1.py
These tests at this point only work for FRR.  Let's cut to the chase
and admit it.
Signed-off-by: Donald Sharp <sharpd@nvidia.com>`
> tests: Our tests are for FRR

- bgpd/bgp_ecommunity.c
- bgpd/bgp_flowspec_vty.c
- bgpd/bgp_zebra.c
- isisd/isis_nb_config.c
- lib/northbound.c
- pimd/pim_igmp.c
- zebra/kernel_netlink.c
code clean up from clang and coverity issues.  Look at individual commits for more data
> Some code cleanup

- bgpd/bgp_route.c
If you are including a network statement of a /32
then the current bgp martian checks will match the /32
together.
Problem:
!
router bgp 3235
neighbor 192.168.161.2 remote-as external
neighbor 192.168.161.131 remote-as external
!
network 10.10.3.11/32
network 192.168.161.0/24
no neighbor 192.168.161.2 activate
neighbor 192.168.161.2 route-map BLUE in
!
eva# show bgp ipv4 uni
BGP table version is 1, local router ID is 10.10.3.11, vrf id 0
Default local pref 100, local AS 3235
Network          Next Hop …
> bgpd: Allow bgp static routes to use /32's

- isisd/isis_adjacency.c
See individual commits for details
> isisd: minor fixes and improvements

- configure.ac
> build: remove redundant commas

- bgpd/bgp_packet.c
bgp->default_keepalive was not considered when setting
peer->v_keepalive, causing the effective keepalive interval to
always be (holdtime/3), even when default_keepalive < (holdtime/3).
This ensures that the default_keepalive is used when it's set and
is < (holdtime/3).
Signed-off-by: Trey Aspelund <taspelund@cumulusnetworks.com>
(cherry picked from commit d8bf8c6128f2e493d473148213bd663a500c7f73)
> bgpd: Use bgp instance's default keepalive interval if < (holdtime/3)

- tests/subdir.am
> tests: skip tests when building without daemon

- isisd/isisd.c
These are only clear commands in FRR available from view node.
> isisd: fix node for clear commands

- tests/topotests/bfd-bgp-cbit-topo3/r1/bgp_ipv6_routes_down.json
- tests/topotests/bfd-bgp-cbit-topo3/r3/bgp_ipv6_routes_down.json
- tests/topotests/bgp-ecmp-topo1/r1/summary.txt
- tests/topotests/bgp-ecmp-topo1/r1/summary20.txt
- tests/topotests/bgp_features/r1/bgp_shutdown_summary.json
- tests/topotests/bgp_features/r1/bgp_summary.json
- tests/topotests/bgp_features/r1/show_bgp.json
- tests/topotests/bgp_features/r2/bgp_shutdown_summary.json
- tests/topotests/bgp_features/r2/bgp_summary.json
- tests/topotests/bgp_features/r2/show_bgp.json
- tests/topotests/bgp_features/r4/bgp_shutdown_summary.json
- tests/topotests/bgp_features/r4/bgp_summary.json
- tests/topotests/bgp_features/r5/bgp_summary.json
- tests/topotests/bgp_flowspec/r1/summary.txt
- tests/topotests/bgp_vrf_lite_ipv6_rtadv/r1/ipv4_routes.json
- tests/topotests/bgp_vrf_lite_ipv6_rtadv/r1/ipv6_routes.json
- tests/topotests/bgp_vrf_lite_ipv6_rtadv/r2/ipv4_routes.json
- tests/topotests/bgp_vrf_lite_ipv6_rtadv/r2/ipv6_routes.json
- tests/topotests/evpn-pim-1/spine/bgp.summ.json
- tests/topotests/isis-topo1-vrf/r1/r1_route.json
- tests/topotests/isis-topo1-vrf/r1/r1_route6.json
- tests/topotests/isis-topo1-vrf/r2/r2_route.json
- tests/topotests/isis-topo1-vrf/r2/r2_route6.json
- tests/topotests/isis-topo1-vrf/r3/r3_route.json
- tests/topotests/isis-topo1-vrf/r4/r4_route.json
- tests/topotests/isis-topo1-vrf/r4/r4_route6.json
- tests/topotests/isis-topo1-vrf/r5/r5_route.json
- tests/topotests/isis-topo1-vrf/r5/r5_route6.json
> tests: don't compare internal vrfId in topotests

- isisd/isis_nb_config.c
> isisd: fix coverity errors in isis ldp-sync commands

- bgpd/bgp_nb_config.c
Fix a couple of new SA warnings in the new bgp northbound.
> bgpd: fix SA warnings in bgp northbound

- ospfd/ospf_flood.c
- ospfd/ospf_packet.h
> ospfd: fix typos

- vtysh/vtysh.c
> vtysh: remove unnecessary include

- bgpd/bgp_evpn_vty.c
> bgpd: hide test commands

- doc/user/pim.rst
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_message.c
- ospf6d/ospf6_network.c
- ospf6d/ospf6_network.h
- ospf6d/ospf6d.c
See individual nothing fancy here
a) pim doc fixes
b) ospfv3 header movements
> Some cleanup from recent commits

- bgpd/bgp_evpn_vty.c
- lib/command.h
Cleanup some of the help strings via static macros.
This is some prep work for another PR coming soon.
> lib,bgpd: EVPN help string cleanup

- isisd/isis_circuit.h
- isisd/isis_csm.c
- isisd/isis_zebra.c
The main purpose of this PR is to fix crash https://github.com/FRRouting/frr/issues/7263, but it also fixes a couple of other issues. Check individual commits for descriptions.
Fixes #7263
> isis crash fix

- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_lsa.c
- ospf6d/ospf6_lsa.h
- ospf6d/ospf6_lsdb.c
- ospf6d/ospf6_lsdb.h
- ospf6d/ospf6_message.c
- ospf6d/ospf6_neighbor.c
- ospf6d/ospf6_snmp.c
- ospf6d/ospf6_spf.c
- tests/ospf6d/test_lsdb.c
- zebra/zebra_evpn_mh.c
- zebra/zebra_evpn_neigh.c
> Cleanup a bunch of new coverity issues

- ospfd/ospf_network.c
- ripngd/ripng_nb_config.c
> 17 coverity

- ospfd/ospf_vty.c
If we enter:
int eth0
ip ospf area 0
ip ospf 10 area 0
!
This will crash ospf.  Prevent this from happening.
OSPF instances:
a) Cannot be mixed with non-instance
b) Are their own process.
Since in multi-instance world ospf instances are their own process,
when an ospf processes receives an instance command we must remove
our config( if present ) and allow the new config to be active
in the new process.  The problem here is that if you have not
done a `router ospf` above the lookup of the ospf pointer will
fail and we will just crash.  Put some code in to prevent a crash
in this case.
> ospfd: Prevent crash if transferring config amongst instances

- tests/topotests/bgp_communities_topo1/bgp_communities_topo2.json
- tests/topotests/bgp_communities_topo1/test_bgp_communities_topo2.py
1.  Adding test to verify that BGP well known communities: no-export, local-AS, 
internet, works fine for eBGP and iBGP peers.
2. Execution time is 90 sec
> tests: Add bgp_communities_topo1 test suite

- ospfclient/ospf_apiclient.c
- ospfd/ospf_gr_helper.c
Try to fix some Coverity SA warnings in ospf GR and ospfclient code.
> ospfd: fix SA warnings in ospfd, ospfclient

- ospfd/ospf_snmp.c
ospfNbrStateChange is generated when the state of neighbor regresses or
it progresses to a terminal state. When transitioning to or from Full
state on non-broadcast multi-access and broadcast networks the trap
should be sent by the designated router. This last condition was not
taken into account when checking for the conditions of generating the
trap.
Fixes volta/volta-stack#1811
Signed-off-by: Babis Chalios <mail@bchalios.io>
> ospfd: fix invocation of ospfTrapNbrStateChange

- vrrpd/vrrp.c
- vrrpd/vrrp_zebra.c
Convert vrrp prefix debugs to use %pFX format
> vrrpd: Convert to using %pFX

- tools/frrcommon.sh.in
chownfrr applies correct owner and group
Signed-off-by: Emanuele Bovisio <emanuele.bovisio@eolo.it>
> tools: use function chownfrr everywhere

- bgpd/bgp_debug.c
- bgpd/bgp_evpn_vty.c
- bgpd/bgp_evpn_vty.h
- bgpd/bgp_routemap.c
- lib/command.h
this is a continuation of #5913 and adds support for (i think) the rest of them.
> lib,bgpd: more evpn route-type numerical command versions

- ospfd/ospf_abr.c
When the ASBR stops announcing a prefix into the NSSA area, the LSA
type 7 is removed from the area. However the ABR is refreshing the
type 5 in its LSDB while removing the Type 7 LSA. Routers outside
the area do not get an update.
With the following topology: r1---r2---r3, with r3 being the ASBR
announcing type 7 LSA:
```
r3 configuration
router ospf
redistribute static
network 10.0.23.0/24 area 1
area 1 nssa
!
```
We stop announcing prefix 3.3.3.3 in the ASBR
```
r3# conf
r3(config)# router ospf
r3(config-router)# no redistribute static
r3(config-router)#
```
r2 (ABR)
```
r2# sh ip os database
NSSA-external Link States (Area 0.0.0.1 [NSSA])
Link ID         ADV Router      Age  Seq#       CkSum  Route
3.3.3.3         33.33.33.33     3600 0x8000002f 0x13be E2 3.3.3.3/32 [0x0]  <-- flushed …
```
> ospfd: flush type 5 when type 7 is removed

- bgpd/bgp_vty.c
set correct information strings for vtysh.
> bgpd: fix information strings for vtysh

- lib/filter.c
- lib/if.c
- lib/nexthop.c
- lib/nexthop_group.c
- lib/sockunion.c
> lib: Convert inet_ntoa to %pI4

- ldpd/address.c
- ldpd/adjacency.c
- ldpd/hello.c
- ldpd/init.c
- ldpd/interface.c
- ldpd/keepalive.c
- ldpd/labelmapping.c
- ldpd/ldp_vty_conf.c
- ldpd/ldp_vty_exec.c
- ldpd/ldp_zebra.c
- ldpd/logmsg.c
- ldpd/neighbor.c
- ldpd/notification.c
- ldpd/packet.c
Replace all use of inet_ntoa; use pI4 or inet_ntop instead.
> ldpd: replace inet_ntoa

- babeld/babel_filter.c
- babeld/babel_interface.c
- isisd/isis_adjacency.c
- isisd/isis_te.c
- isisd/isis_tlvs.c
- ripd/rip_interface.c
- ripd/rip_peer.c
- ripd/rip_zebra.c
- ripd/ripd.c
- staticd/static_vty.c
Replace inet_ntoa, using pI4, pFX, or inet_ntop.
> ripd, staticd, isisd, babeld: replace inet_ntoa

- pimd/mtracebis.c
- pimd/pim_bsm.c
- pimd/pim_cmd.c
- pimd/pim_igmp.c
- pimd/pim_igmp_mtrace.c
- pimd/pim_igmpv3.c
- pimd/pim_nht.c
- pimd/pim_register.c
- pimd/pim_rp.c
- pimd/pim_upstream.c
- pimd/pim_zebra.c
Replace all use of inet_ntoa, using %pI4 or inet_ntoa instead
> pimd: replace inet_ntoa

- pbrd/pbr_zebra.c
- zebra/zebra_mpls.c
- zebra/zebra_rib.c
see individual commits but more inet_ntoa and prefix2str manipulations
> More string

- bfdd/bfdd_cli.c
- ospf6d/ospf6_area.c
- ospf6d/ospf6_area.h
- ospf6d/ospf6_top.c
Just wanting to submit two backports from known to work commits from the 7.5 series used also in VyOS.
Happy to also send a backport PR for 7.4 if this is the right way to go.
> VyOS backports from 7.5 series

- tools/etc/frr/daemons
default staticd=no was missing in daemon file
> tools: add staticd line in daemon config file

- zebra/zebra_evpn_mac.c
- zebra/zebra_evpn_mac.h
- zebra/zebra_evpn_neigh.c
- zebra/zebra_evpn_neigh.h
see individual commits.  Effectively we track uptime like we track route entry uptime.
> Evpn uptime

- zebra/rt_netlink.c
Fix some odd indentation in rt_netlink.c - merge damage, maybe?
> zebra: fix strange indentation

- ospfd/ospf_interface.c
- ospfd/ospf_vty.c
- ospfd/ospfd.c
- ospfd/ospfd.h
Many OSPF fixes, mostly related to "ip ospf area" configuration and processing when interface VRF is changed.
Please, check individual commits for description.
> many ospfd fixes

- doc/user/bgp.rst
Added description and config commands for the various sub-features
introduced as a part of EVPN Multihoming.
> doc: Add documentation for EVPN Multihoming

- bfdd/bfdd_cli.c
- ospf6d/ospf6_area.c
- ospf6d/ospf6_area.h
- ospf6d/ospf6_top.c
This is the extension to https://github.com/FRRouting/frr/pull/7318 where the changes have been backported into 7.3 stable branch.
This PR deals with 7.4 stable.
> VyOS backports from 7.5 series for FRR 7.4

- ospf6d/ospf6_message.c
- ospf6d/ospf6_network.c
- ospf6d/ospf6_network.h
just some small cleanup in ospfv3
> Ospf6 stuff

- isisd/isis_circuit.c
when changing network type from broadcast to p2p, if the interface was also configured as passive, we might end up with the p2p neighbor pointer pointing at some garbage left by the broadcast struct in the union, which would then cause a segfault the first time we would dereference it - for example when building the lsp, or computing the SPF tree.
```
(gdb) bt
#0  0x0000555555579a9c in lsp_build (lsp=0x555555a03b40, area=0x555555a0ff10) at frr/isisd/isis_lsp.c:1114
#1  0x000055555557a516 in lsp_regenerate (area=0x555555a0ff10, level=1) at frr/isisd/isis_lsp.c:1301
#2  0x000055555557aa25 in lsp_refresh (thread=0x7fffffffdf50) at frr/isisd/isis_lsp.c:1381
#3  0x00007ffff7b2622c in thread_call (thread=0x7fffffffdf50) at frr/lib/thread.c:1549
#4  0x00007ffff7ad6df4 in frr_run …
```
> isisd: fix segfault with circuit p2p neighbor

- ospfd/ospfd.c
- zebra/interface.c
- zebra/interface.h
Fix a couple of new SA warnings, clean up a new zebra api a bit.
> ospfd, zebra: Fix SA warnings

- doc/user/snmp.rst
> doc: fix code snippet for net-snmp

- ospfd/ospf_asbr.c
- ospfd/ospf_vty.c
- zebra/zebra_vty.c
> Clang more stuff to cleanup

- doc/user/basic.rst
- doc/user/installation.rst
- doc/user/vrrp.rst
Fixes: https://github.com/FRRouting/frr/issues/5386
Fixes: https://github.com/FRRouting/frr/issues/6928
Fixes: https://github.com/FRRouting/frr/issues/3969
Fixes: https://github.com/FRRouting/frr/issues/7391
> Fix misc doc issues

- bgpd/bgp_debug.c
> bgpd: Correct CLI description for `debug bgp keepalives`

- doc/user/ospf6d.rst
- ospf6d/ospf6_bfd.c
- ospf6d/ospf6_bfd.h
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_neighbor.c
- ospf6d/ospf6_neighbor.h
Modify code to add JSON format output in show command
"show ipv6 ospf6 neighbor" with proper formating
> ospf6d: Json support added for command "show ipv6 ospf6 neighbor [json]"

- doc/developer/building-frr-for-openwrt.rst
- doc/developer/fuzzing.rst
- doc/developer/index.rst
- doc/user/vrrp.rst
document fuzzing and fix a couple unrelated docs warnings
> Doc fuzzing

- changelog-auto.in
> [7.5] build: fix changelog indentation

- bgpd/bgp_attr.c
- bgpd/bgp_attr.h
- bgpd/bgp_debug.c
- bgpd/bgp_ecommunity.c
- bgpd/bgp_ecommunity.h
- bgpd/bgp_evpn.c
- bgpd/bgp_flowspec_vty.c
- bgpd/bgp_mac.c
- bgpd/bgp_pbr.c
- bgpd/bgp_route.c
- bgpd/rfapi/rfapi.c
- bgpd/rfapi/rfapi_import.c
- bgpd/rfapi/rfapi_rib.c
- bgpd/rfapi/rfapi_vty.c
- bgpd/rfapi/vnc_import_bgp.c
Start the process of using set/get accessors to attr->XXX data structures.  Mainly wanted to start getting this in, so that I can work on the attr->extra work in the background( since I'm having `fun` getting it right )
> Attribute setget

- babeld/babel_interface.c
- bfdd/ptm_adapter.c
- bgpd/bgp_addpath.c
- bgpd/bgp_packet.c
- bgpd/bgp_route.c
- bgpd/bgp_zebra.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- isisd/isis_redist.c
- isisd/isis_redist.h
- isisd/isis_spf.c
- isisd/isis_spf.h
- isisd/isisd.c
- lib/zebra.h
- staticd/static_routes.c
- staticd/static_vrf.c
- tests/bgpd/test_mpath.c
See each individual commit but this cleans up memory leaks, uninited data as well as a small bit of refactoring that would even make your grammy proud.
> Cleanup on Aisle 5: Memory leaks, Uninited data and code snarfles

- doc/user/bgp.rst
> doc: fix missing space before list

- doc/user/bgp.rst
> doc: Replace _ to `` when bolding keyword for recently added BGP commands

- doc/user/zebra.rst
- include/linux/rtnetlink.h
- lib/zclient.h
- zebra/connected.c
- zebra/main.c
- zebra/rt_netlink.c
- zebra/zebra_rib.c
- zebra/zebra_router.c
- zebra/zebra_router.h
- zebra/zebra_vty.c
Add `offload_failed` command.  Add abilty to notice kernel notification, Add ability to tell zebra to use asic-offload add some counts to json.
I have not done topotests as that I am not sure how to simulate this
> Asic offload more

- bgpd/bgp_nht.c
- bgpd/bgp_route.c
- bgpd/bgpd.c
> bgpd: Use __func__ instead of hardcoded strings for some functions

- bgpd/bgp_ecommunity.c
- bgpd/bgp_mplsvpn.c
- ospf6d/ospf6_snmp.c
- pimd/pim_cmd.c
see individual commits but some more coverity issues found and fixed
> Memory shenanigans

- doc/user/ospf6d.rst
- ospf6d/ospf6_area.c
- ospf6d/ospf6_area.h
- ospf6d/ospf6_top.c
Modify code to add JSON format output in show command
"show ipv6 ospf6" with proper formating
> ospf6d: Json support added for command "show ipv6 ospf6 [json]"

- changelog-auto.in
- doc/developer/frr-release-procedure.rst
1) Update changelog-auto.in to reflect 7.5 release
2) Update release process.
> Changelog update

- lib/vty.c
> lib: Stop socket from leaking.

- tests/topotests/bgp_ebgp_requires_policy/test_bgp_ebgp_requires_policy.py
> tests: Add more descriptive error messages and increase timeouts

- doc/developer/topotests-jsontopo.rst
> doc: topotest json typo error

- pimd/pim_nb_config.c
> pimd: Fix SA issues found in Coverity Scan

- vtysh/vtysh.c
> vtysh: send quit command to watchfrr

- vtysh/vtysh.c
> [7.5] vtysh: send quit command to watchfrr

- bgpd/bgp_rpki.c
Rework a couple functions to allow the indentation to be a bit
cleaner.
> bgpd: Cleanup rpki indentation

- bgpd/bgp_packet.c
- vtysh/vtysh.c
Just start some cleanup of code under HAVE_CUMULUS
> Datacenter stuff

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/bgp_features/test_bgp_features.py
- tests/topotests/bgp_l3vpn_to_bgp_direct/scripts/add_routes.py
- tests/topotests/bgp_l3vpn_to_bgp_direct/scripts/adjacencies.py
- tests/topotests/bgp_l3vpn_to_bgp_direct/scripts/check_routes.py
- tests/topotests/bgp_l3vpn_to_bgp_direct/scripts/cleanup_all.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/add_routes.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/adjacencies.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_mpls.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/cleanup_all.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/del_bgp_instances.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/notification_check.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_down.py
- tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/scale_up.py
- tests/topotests/bgp_multiview_topo1/test_bgp_multiview_topo1.py
- tests/topotests/bgp_rfapi_basic_sanity/scripts/add_routes.py
- tests/topotests/bgp_rfapi_basic_sanity/scripts/check_close.py
- tests/topotests/bgp_rfapi_basic_sanity/scripts/check_routes.py
- tests/topotests/bgp_rfapi_basic_sanity/scripts/check_timeout.py
- tests/topotests/bgp_rfapi_basic_sanity/scripts/cleanup_all.py
- tests/topotests/isis-tilfa-topo1/test_isis_tilfa_topo1.py
- tests/topotests/lib/bgprib.py
- tests/topotests/lib/lutil.py
some changes around python 2 => python 3 future change.
> Topo python3 preparation

- tests/topotests/bgp_multi_vrf_topo2/bgp_multi_vrf_topo2.json
- tests/topotests/bgp_multi_vrf_topo2/test_bgp_multi_vrf_topo2.py
1. Added 4 test cases for frr/daemon restart(chaos testing)
> tests: Add tests to bgp_multi_vrf_topo2

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/lib/topogen.py
- tests/topotests/lib/topotest.py
Fix Address Sanitizer Issue detection with newer ASAN versions
> tests: Fix Topotest runs with newerversion of Address Sanitizer

- ospfd/ospf_vty.c
- ospfd/ospfd.h
> ospfd: fix a couple of typos

- pimd/pim_cmd.c
- pimd/subdir.am
Fix duplicate block in subdir.am, fix buffer sizes in pim_cmd.c to resolve compilation warnings.
> pimd: fix build and compilation errors

- bfdd/bfdd_cli.c
Summary
---
Fixes #7627 
Replace the unclear error message:
```
% Failed to edit configuration.
YANG error(s):
Schema node not found.
YANG path: /frr-bfdd:bfdd/bfd/sessions/single-hop[dest-addr='192.168.253.6'][interface=''][vrf='default']/minimum-ttl
```
With:
```
frr(config-bfd-peer)# minimum-ttl 250
% Minimum TTL is only available for multi hop sessions.
! or
frr(config-bfd-peer)# echo
% Echo mode is only available for single hop sessions.
frr(config-bfd-peer)# echo-interval 300
% Echo mode is only available for single hop sessions.
```
Reported-by: Trae Santiago
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
> bfdd: session specific command type checks

- doc/developer/memtypes.rst
- lib/memory.c
- lib/memory.h
- vtysh/vtysh.c
- vtysh/vtysh_config.c
* memory leak when interface node config is empty
* incorrect memory statistics
> vtysh memory fixes

- tests/topotests/docker/frr-topotests.sh
This is the opposite of TOPOTEST_AUTOLOAD: Instead of automatically loading
missing modules, TOPOTEST_NOLOAD prevents module loading and supresses
questions about it.
> tests: Add TOPOTEST_NOLOAD to skip module loading question

- ospfd/ospf_vty.c
The following virtual-link configuration was not represented in the
running configuration:
area <area> virtual-link <ip> authentication [null|message-digest]
Signed-off-by: Duncan Eastoe <duncan.eastoe@att.com>
Test virtual-link and interface auth type configuration:
```
for t in "" " null" " message-digest"; do \
echo "Type:$t"
sudo vtysh -c "conf t" -c "interface dp0p1s1" -c "ip ospf authentication$t"; \
sudo vtysh -c "conf t" -c "router ospf" -c "area 1 virtual-link 10.10.10.10 authentication$t"; \
sudo vtysh -c "show run" | grep authentication; \
done
echo Unconfigure
sudo vtysh -c "conf t" -c "interface dp0p1s1" -c "no ip ospf authentication"
sudo vtysh -c "conf t" -c "router ospf" -c "no area 1 virtual-link 10.10.10.10 authentication"
sudo vtysh -c "show run" | grep authentication …
```
> ospfd: vlink auth type not shown in running config

- ospf6d/ospf6_abr.c
- ospf6d/ospf6_abr.h
- ospf6d/ospf6_area.c
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_asbr.h
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_intra.c
- ospf6d/ospf6_main.c
- ospf6d/ospf6_route.c
- ospf6d/ospf6_route.h
- ospf6d/ospf6_spf.c
- ospf6d/ospf6_spf.h
- ospf6d/ospf6_top.c
- ospf6d/ospf6_zebra.c
- ospf6d/ospf6d.c
> ospf6 code cleanup

- bgpd/bgp_vty.c
- tests/topotests/all-protocol-startup/r1/bgpd.conf
- tests/topotests/all-protocol-startup/r1/show_bgp_ipv6_summary.ref
- tests/topotests/all-protocol-startup/r1/show_ip_bgp_summary.ref
- tests/topotests/bgp_multiview_topo1/test_bgp_multiview_topo1.py
introduce in front of each summary line a decription field coming from each peer.
> Show bgp summary desc

- tests/topotests/ospf_basic_functionality/test_ospf_routemaps.py
- tests/topotests/ospf_basic_functionality/test_ospf_single_area.py
Test suite execution time is 75 Secs.
> tests : Adding 3 base ospf testcases.

- doc/developer/building-frr-for-opensuse.rst
- doc/developer/building.rst
- doc/developer/subdir.am
Added new guide for install frr into openSUSE.
It has been tested in openSUSE Tumbleweed in and Raspberry Pi 400.
Signed-off-by: Javier Garcia <rampxxxx@gmail.com>
> doc: add building steps for openSUSE

- vtysh/vtysh_main.c
Add a bit of extra data to `vtysh --help` so that when things are not working we can debug from that.
> Vtysh more useful data

- isisd/isis_spf.c
> isisd: fix SA warning

- tests/topotests/lib/topogen.py
I accidently installed something that is telling me about
unlosed handles in the tests.  Let's clean them up.
<and yes I have no idea wtf I did>
> tests: Close some open handles

- doc/user/zebra.rst
Add doc about RR semantics for Linux Kernel and why it works
the way it does.
> doc: Add some notes about RR semantics and the Linux Kernel

- tests/topotests/lib/bgp.py
1. As per recent changes done in PR #7652, we have modified the auto-rd verification logic
2. Dev PR link: https://github.com/FRRouting/frr/pull/7652
Signed-off-by: kuldeepkash <kashyapk@vmware.com>
> tests: Enhanced auto-rd verification logic for evpn_type5 tests

- lib/hash.h
> lib: update doc comment on hash_cmp

- lib/hash.h
Related: c8aad9c3a4b3e6d6d85fcedaab80cc271015b1f9
> doc: update doc comment on hash_cmp (round 2)

- bgpd/bgp_evpn.c
- bgpd/bgp_evpn_mh.c
- bgpd/bgp_evpn_private.h
- bgpd/bgp_flowspec_vty.c
- bgpd/bgp_nb_config.c
- bgpd/bgp_updgrp_packet.c
- bgpd/bgp_vty.c
- bgpd/rfapi/rfapi_private.h
- eigrpd/eigrp_network.c
- isisd/isis_lsp.c
- ospfd/ospf_ase.c
- ospfd/ospf_lsa.c
- ospfd/ospf_route.c
- ospfd/ospf_snmp.c
- ospfd/ospf_spf.c
- ospfd/ospf_vty.c
- ospfd/ospfd.c
- pimd/pim_cmd.c
- pimd/pim_rp.c
- pimd/pim_static.c
- pimd/pim_vxlan.h
- ripd/ripd.c
- sharpd/sharp_vty.c
- zebra/router-id.c
> *: Replace s_addr check agains 0 with INADDR_ANY

- lib/filter.h
- lib/filter_cli.c
- lib/filter_nb.c
- lib/yang.c
Backport of compatibility/regression fixes for 7.5.
> [7.5] lib: restore previous access/prefix list behaviour

- zebra/zebra_evpn_mh.c
- zebra/zebra_evpn_mh.h
zebra: add support for DF delay timer
zebra: display DF status only for local ESs
> evpn-mh: DF fixes

- tests/topotests/ospf_basic_functionality/test_ospf_authentication.py
- tests/topotests/ospf_basic_functionality/test_ospf_lan.py
- tests/topotests/ospf_basic_functionality/test_ospf_single_area.py
Let's standardize on the internal to frr unicode function.
> tests: unicode to frr_unicode

- bgpd/bgp_conditional_adv.c
- bgpd/bgp_damp.c
- bgpd/bgp_fsm.c
- bgpd/bgp_route.c
- bgpd/bgp_vty.c
fix our usage of bgp_afi_safi_str and some rather not a good way of working
> Die in a fire

- zebra/dplane_fpm_nl.c
Apply @mjstapp's suggestions from https://github.com/FRRouting/frr/pull/7721#pullrequestreview-550086813
I don't believe I've broken any previous assumptions.. :-)
cc @rzalamena
> dplane_fpm_nl optimisations

- lib/routemap.c
see individual commits but prevent a route-map dependency issue from cropping up.
> Route map dependency fix

- pbrd/pbr_nht.c
- zebra/connected.c
- zebra/kernel_socket.c
- zebra/redistribute.c
- zebra/rib.h
- zebra/rt_netlink.c
- zebra/zapi_msg.c
- zebra/zebra_rib.c
see individual commits.  But effectively I made a change in zebra nht to fix pbr but it's causing problems in bgp.  So fix pbr the right way and revert the commit
> Pbr zebra was wrong

- doc/user/bgp.rst
BGP GR command for preserving forwarding state command is
Added to the docs
Signed-off-by: Biswajit Sadhu <biswajit.sadhu@gmail.com>
> doc: Add BGP GR command for preserving forwarding state.

- bgpd/bgp_nb_config.c
- pathd/path_zebra.c
> some coverity fixes

- doc/developer/link-state.rst
- lib/link_state.c
- lib/link_state.h
- lib/subdir.am
Define new models for Link State Database a.k.a TED
and functions to manipulate the new database as well as exchange Link State
information through ZAPI Opaque message.
> Lib: Add Link State Database

- pbrd/pbr_vty.c
- zebra/rule_netlink.c
> pbrd: pbr ipv4/ipv6 match fixes

- tests/topotests/lib/common_config.py
- tests/topotests/lib/pim.py
- tests/topotests/lib/topojson.py
1. Added lib/pim.py for PIM configuration/verification
2. Enhanced lib/common_config.py for common configuration/verification needed for PIM automation
3. Enhanced lib/topojson.py for creating topologies with switches and routers
4. Ran these files through (black) for expected formatting
Signed-off-by: kuldeepkash <kashyapk@vmware.com>
> tests: [topojson]Add/Enhance framework to support PIM automation

- bgpd/bgp_zebra.c
in bgp_zebra_announce we have a bunch of small issues that we can improve.  See individual commits
> Bgp announce

- bgpd/bgpd.c
When adding/removing some peer's flag we need to make sure we FORCE updates
to avoid suppressing critical updates.
Like entering `no neighbor x.x.x.x send-community large` would suppress
updates by default and another side will have stale large communities.
> bgpd: Force BGP updates when triggering reset out

- bgpd/bgp_community.c
Before fix:
```
root@exit1-debian-9:~/frr# /usr/local/bin/vtysh  -c 'c' -c 'route-map test permit 10' -c 'set community 65535:429496723296'
root@exit1-debian-9:~/frr#
root@exit1-debian-9:~/frr# vtysh -c 'c' -c 'bgp community-list standard test permit 65535:4294967296'
root@exit1-debian-9:~/frr#
root@exit1-debian-9:~/frr# /usr/local/bin/vtysh  -c 'c' -c 'route-map test permit 10' -c 'set community 65535'
root@exit1-debian-9:~/frr# /usr/local/bin/vtysh  -c 'c' -c 'route-map test permit 10' -c 'set community 65535:'
% Malformed communities attribute
```
After fix:
```
root@exit1-debian-9:~/frr# /usr/local/bin/vtysh  -c 'c' -c 'route-map test permit 10' -c 'set community 65535:4294967296'
% Malformed communities attribute
root@exit1-debian-9:~/frr# vtysh -c 'c' -c 'bgp community-list standard …
```
> bgpd: Validate community list if they are not malformed

- isisd/isis_nb_config.c
When last area address is removed, resign if we were DR.
This fixes an issue where: when the ISIS area address is changed, ISIS fails to elect a new DR.
> isisd: When last area address is removed, resign if we were DR

- tools/etc/frr/support_bundle_commands.conf
Cleanup some commands in the support bundle.  SEe the individual commits
> Cleanup support bundle

- pimd/pim_ifchannel.c
1. When a node changes from non-DR to DR in the given topology,
the node was receiving both PIM Join as well as IGMP join.
Since it was already receiving PIM Join previously, ifchannel was
already present. Hence when it becomes DR, the IGMP source flag is not
set due to issue in the code. Hence it never creates S,G entry thinking
that it is not DR.
2. When pim join expires, the pim flag is not reset when ifchannel is not
deleted.
Issue: #7752 
> pimd: when node changes from non-DR to DR S,G entry not created

- lib/sockunion.c
- lib/sockunion.h
- nhrpd/README.kernel
- nhrpd/nhrp_cache.c
- nhrpd/nhrp_interface.c
- nhrpd/nhrp_nhs.c
- nhrpd/nhrp_peer.c
- nhrpd/nhrp_route.c
- nhrpd/nhrp_shortcut.c
- nhrpd/nhrpd.h
Multiple fixes for nhrpd to improve DMVPN network operation, and to some crashes.
> nhrpd fixes

- zebra/zebra_vxlan.c
After removal of L3VNI config, the VNI should become an L2VNI if a VxLAN
interface is present for the VNI. This case is not handled in the code.
Changes:
1. After unconfiguring L3VNI, create an L2VNI if VxLAN interface is present
for the VNI.
2. Trigger an update to BGP.
3. Read MAC and ARP entries from kernel.
This PR fixes the issue only for route type-2, 3 and 5. This PR does not address
states regarding route type-1, 4 and multicast group for VxLAN interface.
Signed-off-by: Ameya Dharkar <adharkar@vmware.com>
> zebra: L3VNI to L2VNI conversion is not handled

- bgpd/bgp_nb_config.c
- pathd/path_pcep_cli.c
- tools/frr-reload.py
Assorted minor fixes - see individual commits for details. Let me know if this is not acceptable and you'd rather have me break it into multiple PRs.
> Misc fixes (bgpd, pathd, tools)

- tests/topotests/ospf_basic_functionality/ospf_p2mp.json
- tests/topotests/ospf_basic_functionality/test_ospf_p2mp.py
This test verifies basic  ospf p2mp network types.
> tests: Adding ospf p2mp basic test.

- isisd/isis_spf.c
Currently the transition metric style is redundant because isis will always read both reachability TLVs regardless of the configured
metric style. Correct this by only considering TLVs matching our configuration.
> isisd: ignore routes with incompatible metric style

- ospfd/ospf_vty.c
Description:
Display configured ospf authentication details as part of
"show ip ospf interface" command o/p.
sample o/p:
-----------
dev# 
dev# show ip ospf  interface 
ens256 is up
ifindex 7, MTU 1500 bytes, BW 10000 Mbit <UP,BROADCAST,RUNNING,MULTICAST>
Internet Address 10.1.1.30/24, Broadcast 10.1.1.255, Area 0.0.0.1
MTU mismatch detection: enabled
Router ID 3.3.3.3, Network Type BROADCAST, Cost: 10
Transmit Delay is 1 sec, State Backup, Priority 1
Backup Designated Router (ID) 3.3.3.3, Interface Address 10.1.1.30
Multicast group memberships: OSPFAllRouters OSPFDesignatedRouters
Timer intervals configured, Hello 10s, Dead 40s, Wait 40s, Retransmit 5
Hello due in 7.161s
Neighbor Count is 1, Adjacent neighbor count is 1
Simple password authentication enabled. <======
dev# 
dev# 
dev# …
> ospfd: Adding authentication details to ospf interafce command o/p

- bgpd/bgp_debug.c
- bgpd/bgp_fsm.c
- bgpd/bgp_open.c
- bgpd/bgp_open.h
- bgpd/bgp_packet.c
- bgpd/bgp_packet.h
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_routemap.c
- bgpd/bgp_vty.c
- bgpd/bgpd.c
- bgpd/bgpd.h
- doc/user/bgp.rst
- doc/user/overview.rst
Related: https://github.com/FRRouting/frr/issues/2864
> bgpd: Enhanced Route Refresh capability

- tests/topotests/lib/common_config.py
- tests/topotests/static_routing_with_ebgp/static_routes_topo3_ebgp.json
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo3_ebgp.py
1. Adding api to verify show ip nht command.
2. 5 cases of static routes with admin dist and tag
3. Run time = 89Secs
> tests: Static route cases with admin dist and tag.

- lib/zclient.c
- lib/zclient.h
- zebra/zebra_evpn_mac.c
- zebra/zebra_evpn_mac.h
Add some dumper functions to evpn_mac.c to allow us to have human readable debug for various flags.  See individual commits for explanations.
> Evpn flag dump

- zebra/zebra_fpm.c
Thread zfpm_conn_up_thread_cb can Yield and send RMAC multiple
times to FPM.
Signed-off-by: Kishore Kunal <kishorekunal01@broadcom.com>
> zebra: Scale setup RMAC is send multiple time to fpm

- bgpd/bgpd.c
A bgp neighbor remains in Idle state in the event that the number
of received prefixes exceeds the configured maximum prefix for the
neighbor. The neighbor remains in idle state even after de-configuring
the maximum prefix limit for the neighbor.
The fix is to clear the neighbor overflow state if set, after
de-configuring the neighbor maximum-prefix commnd.
This allows the neighbor to establish without having to perform a
clear operation. It also avoids the misleading neigbor summary
indicating that the neighbor is in prefix overflow state (PfxCt)
when no limit is configured for the neighbor.
Signed-off-by: Dewi Morgan <dewi.morgan@intl.att.com>
> bgpd: clear max prefix overflow on de-config

- tests/topotests/bgp_peer-group/r1/bgpd.conf
- tests/topotests/bgp_peer-group/r1/zebra.conf
- tests/topotests/bgp_peer-group/r2/bgpd.conf
- tests/topotests/bgp_peer-group/r2/zebra.conf
- tests/topotests/bgp_peer-group/r3/bgpd.conf
- tests/topotests/bgp_peer-group/r3/zebra.conf
- tests/topotests/bgp_peer-group/test_bgp_peer-group.py
> tests: Check if peer-group is working in topotests

- zebra/zebra_fpm_netlink.c
Use nl_pid from the netlink socket used for programming the kernel
(netlink_dplane) in netlink route messages sent by the 'fpm' module.
This makes 'fpm' consistent with 'dplane_fpm_nl' which already
behaves this way, and allows FPM server implementations to determine
route origin via nlmsg_pid.
Signed-off-by: Duncan Eastoe <duncan.eastoe@att.com>
> zebra: set nlmsg_pid in netlink msgs sent by 'fpm'

- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
- tests/topotests/bfd-bgp-cbit-topo3/test_bfd_bgp_cbit_topo3.py
- tests/topotests/bfd-isis-topo1/test_bfd_isis_topo1.py
- tests/topotests/bfd-profiles-topo1/test_bfd_profiles_topo1.py
- tests/topotests/bfd-topo1/test_bfd_topo1.py
- tests/topotests/bfd-topo2/test_bfd_topo2.py
- tests/topotests/bfd-vrf-topo1/test_bfd_vrf_topo1.py
- tests/topotests/isis-lfa-topo1/test_isis_lfa_topo1.py
- tests/topotests/isis-rlfa-topo1/test_isis_rlfa_topo1.py
- tests/topotests/isis-sr-te-topo1/test_isis_sr_te_topo1.py
- tests/topotests/isis-sr-topo1/test_isis_sr_topo1.py
- tests/topotests/isis-tilfa-topo1/test_isis_tilfa_topo1.py
- tests/topotests/isis-topo1-vrf/test_isis_topo1_vrf.py
- tests/topotests/isis-topo1/test_isis_topo1.py
- tests/topotests/pbr-topo1/test_pbr_topo1.py
- tests/topotests/pytest.ini
add pytest.mark for 
pbr, isis and bfd
More to come
> More pytest mark

- bgpd/bgp_attr.c
- bgpd/bgp_attr_evpn.c
- bgpd/bgp_ecommunity.c
- bgpd/bgp_ecommunity.h
- bgpd/bgp_evpn.c
- bgpd/bgp_mplsvpn.c
- bgpd/bgp_pbr.c
- bgpd/bgp_updgrp_adv.c
- bgpd/rfapi/rfapi_import.c
- bgpd/rfapi/vnc_export_bgp.c
- lib/northbound_cli.c
- pbrd/pbr_nht.c
- zebra/dplane_fpm_nl.c
See individual commits but just code cleanup in general
> Null stuff

- bfdd/bfd.c
- bfdd/bfd_packet.c
- bfdd/ptm_adapter.c
> Bfd misc fixes 

- pathd/path_pcep_controller.c
- pathd/path_pcep_lib.c
Just to help while debugging in gdb
> pathd: add meaningful names to threads

- lib/command.c
- lib/frrlua.c
Two new coverity issues from inclusion of new lua code.
> lib: Fix up str2prefix usage in lua code

- pimd/pim_jp_agg.c
Memleak: pim_jp_agg_single_upstream_send(), static variable are not
released.
> Fix leak in pim_jp_agg_single_upstream_send()

- ospfd/ospf_lsa.c
> ospfd: cosmetic function names in debug

- doc/developer/topotests.rst
- tests/topotests/lib/snmptest.py
- tests/topotests/lib/topogen.py
- tests/topotests/lib/topotest.py
- tests/topotests/simple-snmp-test/r1/bgpd.conf
- tests/topotests/simple-snmp-test/r1/isisd.conf
- tests/topotests/simple-snmp-test/r1/snmpd.conf
- tests/topotests/simple-snmp-test/r1/zebra.conf
- tests/topotests/simple-snmp-test/test_simple_snmp.py
add SNMP topotest infrastructure and sample test
> Snmp test infra

- tests/topotests/lib/pim.py
- tests/topotests/multicast-pim-sm-topo3/multicast_pim_sm_topo3.json
- tests/topotests/multicast-pim-sm-topo3/multicast_pim_sm_topo4.json
- tests/topotests/multicast-pim-sm-topo3/test_multicast_pim_sm_topo3.py
- tests/topotests/multicast-pim-sm-topo3/test_multicast_pim_sm_topo4.py
1. Added/enhanced framework for multicast-pim-sm automation
2. Added new scenarios to test multicast-pim-sm
Co-author : Vijay Kumar Gupta vijayg@vmware.com
Signed-off-by: kuldeepkash <kashyapk@vmware.com>
> tests: Add new scenarios to test multicast-pim-sm

- tests/topotests/ospf_basic_functionality/ospf_chaos.json
- tests/topotests/ospf_basic_functionality/test_ospf_chaos.py
This script involves Restart ospfd,
restart frr with ospf enabled,
staticd with redistribution inside ospf is enabled
> tests : Adding 3 ospf chaos testcases.

- doc/user/bgp.rst
The RFC 8212 changes keep being questioned.  Update the documentation
a bit more to help the end user figure it out themselves?
At the very least I can just now quote the doc link for this section
when someone asks the question.
> doc: Update bgp doc for more rfc-8212 talk

- tests/topotests/lib/snmptest.py
- tests/topotests/simple-snmp-test/test_simple_snmp.py
Update test_oid_walk to either validate specific oids or
to validate all rows walked.
> tests: update snmp test infastructure api test_oid_walk

- bgpd/bgp_route.c
- tests/topotests/bgp_blackhole_community/r2/bgpd.conf
- tests/topotests/bgp_blackhole_community/r2/zebra.conf
- tests/topotests/bgp_blackhole_community/r4/bgpd.conf
- tests/topotests/bgp_blackhole_community/r4/zebra.conf
- tests/topotests/bgp_blackhole_community/test_bgp_blackhole_community.py
Related: https://github.com/FRRouting/frr/issues/7871
> bgpd: Advertise BLACKHOLE community tagged prefixes to iBGP peers

- tests/topotests/lib/topotest.py
- tests/topotests/simple-snmp-test/test_simple_snmp.py
> tests: update simple_snmp_test to check for memory leaks, router failure

- lib/route_types.pl
- tests/topotests/all-protocol-startup/test_all_protocol_startup.py
Cherry pick of #7933 for dev/7.6.
> [7.6] lib: restore blank line after show route header

- tests/topotests/pytest.ini
tests: temporarily remove isis-lsp-bit-topo1 topotest
> tests: temporarily remove isis-lsp-bit-topo1 topotest

- tests/topotests/lib/snmptest.py
Update snmp topotest api test_oid_walk to validate a subset
of rows in a mib walk.
> tests: update snmp topotest api test_oid_walk

- bgpd/bgp_nexthop.c
- bgpd/bgp_nexthop.h
- bgpd/bgp_nht.c
add human readable flags to the bgp bnc flags
> More flags

- doc/user/setup.rst
Let user know that there are standardized ways to use network namespaces.
> doc: add information about network namespaces

- doc/user/nhrpd.rst
> doc: update the links to nhrp/strongswan patches

- bfdd/bfd_packet.c
- bfdd/ptm_adapter.c
- eigrpd/eigrp_topology.c
- isisd/isis_ldp_sync.c
- lib/log.c
- ospfd/ospf_ldp_sync.c
> bunch of valgrind issues

- ospf6d/ospf6_asbr.c
- zebra/zapi_msg.c
see individual commits but valgrind is finding stuff for us to fix.
> Valgrind cleanups

- doc/developer/topotests.rst
- tests/topotests/multicast-pim-sm-topo1/multicast_pim_sm_topo1.json
- tests/topotests/multicast-pim-sm-topo1/test_multicast_pim_sm_topo1.py
- tests/topotests/multicast-pim-sm-topo2/multicast_pim_sm_topo2.json
- tests/topotests/multicast-pim-sm-topo2/test_multicast_pim_sm_topo2.py
1. Added 10 test cases to verify multicast PIM SM functionality
2. Added framework support to create and verify  multicast PIM SM topology
and configuration
3. Execution time is ~15 mins
> Add multicast-pim-sm-topo1 test suite

- lib/hash.c
- lib/hash.h
- lib/routemap.c
- ospfd/ospf_vty.c
- pimd/pim_cmd.c
- pimd/pim_vxlan.c
- zebra/dplane_fpm_nl.c
- zebra/zebra_fpm.c
- zebra/zebra_vxlan.c
> *: fix all backets

- pimd/pim_ifchannel.c
RCA: There were 2 problems.
1. SGRpt prune expiry didn't create S,G entry with empty oil when no other
interfaces were part of the oil.
2. When restarting the timer with new hold value, comparision was missing and
old timer was not stopping.
Fix:
SGRpt Prune pending expiry will put SG entry with empty oil if no other
interfaces present. If present we will be deleting the inherited oif from oil.
Deleting the oif in that scenario will take care of changing mroute.
When alone interface expires in SGRpt prune pending state, we shall detect by
checking installed flag. if not installed, install mroute.
Signed-off-by: Saravanan K <saravanank@vmware.com>
> pimd: SGRpt prune received during prune didn't override holdtime

- zebra/zserv.c
When displaying `show zebra client summ` when we have instances
running, display the instance number as well.
New Output:
sharpd@eva ~/frr7 (instance_data)> vtysh -c "show zebra client summ"
Name      Connect Time    Last Read  Last Write  IPv4 Routes       IPv6 Routes
--------------------------------------------------------------------------------
ospf[1]       00:00:02     00:00:02    00:00:02       0/0              0/0
ospf[5]       00:00:02     00:00:02    00:00:02       0/0              0/0
sharp         00:00:02     00:00:02    00:00:02       0/0              0/0
static        00:00:02     00:00:02    00:00:02       0/0              0/0
Routes column shows (added+updated)/deleted
> zebra: Display instance id as part of `show zebra client summ`

- doc/user/ospf6d.rst
- ospf6d/ospf6_spf.c
- ospf6d/ospf6_spf.h
- ospf6d/ospf6_top.c
- ospf6d/ospf6_top.h
- ospf6d/ospf6_zebra.c
CLI added:
maximum-paths (1-64)
Added the information in display CLI as well.
Issue: #7961
Signed-Off-by: Mobashshera Rasool <mrasool@vmware.com>
> ospf6d: add CLI to control maximum paths for routes.

- tests/topotests/multicast-pim-static-rp-topo1/multicast_pim_static_rp.json
- tests/topotests/multicast-pim-static-rp-topo1/test_multicast_pim_static_rp.py
1. -  Enhanced the API in common library to support PIM automation
2. -  Enhance API to create multicast topo
3. -  Added PIM lib to create create and verify PIM configurations
4. -  Added 17 testcases to verify multicast static RP functionality
5. -  Execution time ~20min
Co-author :  Kuldeep Kashyap <kashyapk@vmware.com> , Sarita Patra  <saritap@vmware.com>
Signed-off-by: Vijay Kumar Gupta  <vijayg@vmware.com>
> tests: Add multicast-pim-static-rp-topo1 test suite

- pimd/pim_mroute.c
one debug flag check twice, just clean it.
> Fix double check, remove one

- bfdd/ptm_adapter.c
- isisd/isis_bfd.c
- lib/bfd.c
- ospfd/ospf_bfd.c
- pimd/pim_bfd.c
> Some bfd valgrind issues

- doc/user/pbr.rst
- pbrd/pbr_nht.c
- zebra/debug.c
- zebra/debug.h
- zebra/zebra_pbr.c
> zebra,pbrd,doc: PBR more fixes

- doc/user/bgp.rst
> doc: We have to enable nht tracking via default route multihop eBGP

- bgpd/bgp_route.c
> bgpd: Replace typo "Cluser length" => "Cluster length"

- bfdd/bfd.c
BFD key has optional fields "local" and "ifname" which can be empty when
the BFD session is created. In this case, the hash key will be calculated
with these fields filled with zeroes.
Later, when we're looking for the BFD session using the key with fields
"local" and "ifname" populated with actual values, the hash key will be
different. To work around this issue, we're doing multiple hash lookups,
first with full key, then with fields "local" and "ifname" filled with
zeroes.
But there may be another case when the initial key has the actual values
for "local" and "ifname", but the key we're using for lookup has empty
values. This case is covered for IPv4 by using additional hash walk with
bfd_key_lookup_ignore_partial_walker function but is not covered for IPv6.
Instead of introducing …
> bfdd: fix session lookup

- lib/filter_cli.c
CMD_WARNING is replaced by CMD_WARNING_CONFIG_FAILED
Signed-off-by: varasteh <mahdy.varasteh@gmail.com>
> [filter]: change return code for errors

- nhrpd/nhrp_route.c
- nhrpd/nhrp_shortcut.c
2 fixes related to how shortcut entries are installed in the kernel.
> nhrp: fix shortcut routes

- doc/developer/tracing.rst
> doc: document LD_PRELOAD workaround for lttng

- bgpd/bgp_mplsvpn_snmp.c
- bgpd/bgp_snmp.c
- lib/agentx.c
- lib/smux.h
- nhrpd/nhrp_main.c
some new clang stuff from clang-11
> new clang fixes

- bgpd/bgp_route.c
'show bgp ipv[46] vpn neighbors ... advertised-routes' was displaying
empty output due to new command syntax using show_adj_routes() which
assumed each bgp_table was single-tier (not nested).  This fixes that
assumption for safis with a two-tier bgp_table (SAFI_MPLS_VPN,
SAFI_ENCAP, and SAFI_EVPN).
Before:
ub18# show bgp ipv6 vpn neighbors 2001:db8:cafe::2 advertised-routes
ub18#
After:
ub20# show bgp ipv6 vpn neighbors 2001:db8:cafe::1 advertised-routes
BGP table version is 2, local router ID is 100.64.0.222, vrf id 0
Default local pref 100, local AS 1
Network …
> bgpd: fix empty advertised-routes for 2-tier safis

- doc/user/pim.rst
- pimd/pim_cmd.c
Modify code to add JSON format output in show command.
"show ip igmp [vrf NAME] join" and "show ip igmp vrf all join" with proper formatting
> pimd: json support added

- bgpd/bgp_nht.c
When bgp registers for a nexthop that is not reachable due
to the nexthop pointing to a blackhole, bgp is never going
to be able to reach it when attempting to open a connection.
Broken behavior:
```
<show bgp nexthop>
192.168.161.204 valid [IGP metric 0], #paths 0, peer 192.168.161.204
blackhole
Last update: Thu Feb 11 09:46:10 2021
eva# show bgp ipv4 uni summ fail
BGP router identifier 10.10.3.11, local AS number 3235 vrf-id 0
BGP table version 40
RIB entries 78, using 14 KiB of memory
Peers 2, using 54 KiB of memory
Neighbor             EstdCnt DropCnt ResetTime Reason
192.168.161.204            0       0     never Waiting for peer OPEN
```
The log file fills up with this type of message:
```
2021-02-09T18:53:11.653433+00:00 nq-sjc6c-cor-01 bgpd[6548]: can't connect to 24.51.27.241 fd …
```
> bgpd: Blackhole nexthops are not reachable

- ospf6d/ospf6_message.c
Add more details to these logs to help make it easier to determine why
ospf6 adjacency is not coming up.   Also make these logs show up without
having to turn on debug logging, again making it easier to debug the
misconfiguration.
Signed-off-by: Lynne Morrison <lynne@voltaio.net>
> ospf6d: Update logs that indicate why ospf6 adjacency is not coming up.

- bgpd/bgp_mplsvpn_snmp.c
- lib/smux.h
- lib/snmp.c
fix coverity errors in bgp_l3vpn_snmp.c
https://lists.frrouting.org/pipermail/dev/2021-February/002159.html
> MPLSL3VPN snmp coverity fixes

- lib/clippy.c
> lib: use right type for wconv() return val

- doc/developer/tracing.rst
> doc: Instruction how to use Systemtap with FRRouting

- tests/topotests/bgp-aggregator-zero/exabgp.env
- tests/topotests/bgp-aggregator-zero/peer1/exabgp.cfg
- tests/topotests/bgp-aggregator-zero/r1/bgpd.conf
- tests/topotests/bgp-aggregator-zero/r1/zebra.conf
- tests/topotests/bgp-aggregator-zero/test_bgp_aggregator_zero.py
> tests: Test if BGP AGGREGATOR attribute is discarded if ASN comes as 0

- bgpd/bgp_mpath.c
- bgpd/bgp_route.c
- bgpd/bgp_route.h
- bgpd/bgp_routemap.c
- doc/developer/workflow.rst
- isisd/isis_lsp.c
- isisd/isis_lsp.h
- isisd/isis_misc.c
- isisd/isis_vty_fabricd.c
- lib/prefix.c
- lib/prefix.h
- lib/vty.c
- ospf6d/ospf6_abr.c
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_intra.c
- zebra/irdp_interface.c
- zebra/rt_netlink.c
Should be just a couple non-development, non-test occurrences of this
function left now.
Signed-off-by: Quentin Young <qlyoung@qlyoung.net>
> *: remove more sprintf()

- doc/developer/tracing.rst
A bit wrong eventually, sorry.
> doc: Format highlighted syntax properly for Systemtap examples

- doc/developer/tracing.rst
> doc: fix indent depth in tracing doc

- ospf6d/ospf6_lsa.c
When an unknown LSA is in the database and the user issues the
"show ipv6 ospf6 database" command there is a crash.  The code currently
doesn't properly handle display of unknown LSAs.
Signed-off-by Lynne Morrison <lynne@voltaio.net>
> ospf6d: fix display of unknown LSAs in show ipv6 ospf6 database command

- doc/user/isisd.rst
- isisd/isis_lfa.c
- tests/isisd/test_isis_spf.refout
Please see individual commits for details.
Once this is merged I'll backport these fixes to 7.5 as well.
> isisd: TI-LFA fixes

- lib/clippy.c
- lib/defun_lex.l
- lib/northbound_cli.c
Backport several SA fixes to 7.5
> [7.5]lib: Fix SA backports to 7.5

- bgpd/bgp_route.c
If we are filtering a route due to any of the filter reasons
we should not be setting the BGP_NODE_FIB_INSTALL_FIB_PENDING
flag.  This is especially evident with say a loopback that
is covered by a network statement.  When we receive the route
back from our peer we should not be setting the
BGP_NODE_FIB_INSTALL_PENDING flag on it.
> bgpd: Wait for Install should not always set the flag

- zebra/rt_netlink.c
> zebra: don't use kernel nexthops for blackhole routes

- tests/topotests/lib/topogen.py
> tests: don't complain when /tmp/topotests exists

- lib/sigevent.c
- lib/sigevent.h
- lib/thread.c
- lib/thread.h
Double commit of #7045 to fix for signal-handling race in main event loop
> [7.5] lib: fix signal-handling race in main event loop

- doc/developer/building-frr-for-centos7.rst
- doc/developer/packaging-redhat.rst
- redhat/frr.spec.in
Documentation correction for CentOS and RPM changelog date format fix
> [7.5] CentOS Doc Fixes

- pimd/pim_cmd.c
- staticd/static_vty.c
- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
Merging in some old quality-of-life fixups. Fixes a column alignment in pimd, adds a warning in staticd for a certain condition, and satisfies some coverity issues in a certain code path in topotest's `common_config.py` by fixing a bit of unreachable code
> staticd, pimd, tests: small fixups and cov fix

- bfdd/bfdd_cli.c
- bfdd/bfdd_nb_config.c
> bfd cli/nb fixes

- tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1.py
- tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2.py
- tests/topotests/bgp_large_community/test_bgp_large_community_topo_2.py
- tests/topotests/bgp_multi_vrf_topo1/test_bgp_multi_vrf_topo1.py
- tests/topotests/bgp_multi_vrf_topo2/test_bgp_multi_vrf_topo2.py
- tests/topotests/bgp_recursive_route_ebgp_multi_hop/test_bgp_recursive_route_ebgp_multi_hop.py
- tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py
- tests/topotests/multicast-pim-bsm-topo1/test_mcast_pim_bsmp_01.py
- tests/topotests/multicast-pim-bsm-topo2/test_mcast_pim_bsmp_02.py
- tests/topotests/multicast-pim-sm-topo3/test_multicast_pim_sm_topo3.py
- tests/topotests/multicast-pim-sm-topo3/test_multicast_pim_sm_topo4.py
- tests/topotests/multicast-pim-static-rp-topo1/test_multicast_pim_static_rp.py
- tests/topotests/ospf_basic_functionality/test_ospf_chaos.py
- tests/topotests/ospf_basic_functionality/test_ospf_ecmp.py
- tests/topotests/ospf_basic_functionality/test_ospf_ecmp_lan.py
- tests/topotests/ospf_basic_functionality/test_ospf_lan.py
- tests/topotests/ospf_basic_functionality/test_ospf_routemaps.py
- tests/topotests/ospf_basic_functionality/test_ospf_rte_calc.py
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo4_ebgp.py
- tests/topotests/static_routing_with_ibgp/test_static_routes_topo4_ibgp.py
1. Improved error message logging.
2. No functionality changes, added some meaningful error/assert messages.
> tests: Improve error/assert message logging

- doc/user/babeld.rst
Remove a duplicated entry from the babeld doc.
> doc: remove duplicate entry from babeld doc

- bgpd/bgp_attr.c
- bgpd/bgp_evpn.c
- bgpd/bgp_fsm.c
- bgpd/bgp_label.c
- bgpd/bgp_mpath.c
- bgpd/bgp_network.c
- bgpd/bgp_route.c
- bgpd/bgp_updgrp_packet.c
- bgpd/bgp_zebra.c
- nhrpd/netlink_arp.c
- nhrpd/nhrp_cache.c
- nhrpd/nhrp_interface.c
- nhrpd/nhrp_nhs.c
- nhrpd/nhrp_peer.c
- nhrpd/nhrp_route.c
- nhrpd/nhrp_shortcut.c
- nhrpd/nhrp_vc.c
- ospfd/ospf_flood.c
- ospfd/ospf_packet.c
- ospfd/ospf_spf.c
- ripd/ripd.c
- ripngd/ripngd.c
- watchfrr/watchfrr.c
start the work.  See the individual commits
> Start work to switch over to using our now built-in printf functionality

- nhrpd/nhrp_event.c
- tools/nhrpd-event-handler.sh
> nhrp, tools: fix client event handling

- babeld/babeld.c
- babeld/message.c
- babeld/route.c
- bgpd/bgp_zebra.c
- eigrpd/eigrp_packet.c
- eigrpd/eigrp_zebra.c
- lib/vty.c
- lib/zclient.c
- ospf6d/ospf6_message.c
- ospf6d/ospf6_zebra.c
- pimd/pim_igmp_mtrace.c
- pimd/pim_msdp_socket.c
- sharpd/sharp_zebra.c
- zebra/connected.c
- zebra/redistribute.c
- zebra/rt_netlink.c
- zebra/zebra_dplane.c
- zebra/zebra_evpn.c
- zebra/zebra_evpn_mac.c
- zebra/zebra_evpn_neigh.c
- zebra/zebra_evpn_neigh.h
- zebra/zebra_fpm.c
- zebra/zebra_fpm_netlink.c
- zebra/zebra_rib.c
- zebra/zebra_vxlan.c
> more switchover to using our builtin printf functionality

- tools/etc/frr/support_bundle_commands.conf
> zebra support bundle fixes and improvements

- eigrpd/eigrp_cli.c
Fix invalid xpaths.
Fix incorrect usage of operational state when displaying config.
> eigrp cli fixes

- isisd/isis_snmp.c
> isisd: Fix coverity warnings

- zebra/kernel_netlink.c
Backport some cleanups to a couple of log messages and debugs from master to 7.5 - especially to quiet a couple of unprotected debugs.
> [7.5] zebra: backport some netlink cleanups

- ospf6d/ospf6_asbr.c
> ospf6d: Fix coverity errors

- tests/topotests/bgp-snmp-mplsl3vpn/test_bgp_snmp_mplsvpn.py
get ifindices using APIs provided.
> Fix ifindex test

- isisd/isis_lsp.c
no point in scheduling an LSP refresh immediately if we know it is going to be postponed again due to the network still being in its
instability grace period
> isisd: avoid lsp_sched loop when unstable

- pimd/pim_msdp_socket.c
Configuring the sockets used to establish MSDP connections so the
packets are marked as CS6
Signed-off-by: Adriano Marto Reis <adrianomarto@gmail.com>
> pimd: marking MSDP traffic as DSCP CS6

- isisd/isis_lsp.c
> isisd: Fix spelling mistake

- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
1. Enhance verify_bgp_convergence() to solve issue mentioned in #8279
> tests: Fix bgp convergence issue mentioned in #8279

- pathd/path_pcep_cli.c
- pceplib/pcep_msg_messages_encoding.c
- pceplib/pcep_msg_objects_encoding.c
- pceplib/pcep_msg_tlvs.c
- pceplib/pcep_msg_tlvs_encoding.c
- pceplib/pcep_msg_tools.c
- pceplib/pcep_pcc.c
- pceplib/pcep_session_logic.c
- pceplib/pcep_session_logic_loop.c
- pceplib/pcep_session_logic_states.c
- pceplib/pcep_socket_comm_loop.c
- pceplib/test/pcep_msg_messages_test.c
- pceplib/test/pcep_msg_tlvs_test.c
- pceplib/test/pcep_msg_tools_test.c
- pceplib/test/pcep_session_logic_loop_test.c
- pceplib/test/pcep_timers_event_loop_test.c
After the merge of the pceplib pr a list of coverity messages has to be fixed.
> pceplib: Fixing coverity messages.

- bgpd/bgp_vty.c
[no] neighbor <A.B.C.D|X:X::X:X|WORD> send-community
> bgpd: convert send-community to transactional cli

- bgpd/bgp_nht.c
For link-local IPv6 next hops, the next hop tracking is implemented based
on interface status changes. For this purpose, the ifindex is stored in
the NHT. Reset this value if a change in ifindex is noticed, such as for
example after a restart of the networking service.
Also add some additional debug logs.
Signed-off-by: Vivek Venkatraman <vivek@nvidia.com>
Updates: "bgpd: Switch LL nexthop tracking to be interface based"
Ticket: RM 2575386
Testing Done:
1. Manual verification
2. Precommit (#156), evpn-smoke (#155), bgp-smoke (#157), vrl (#158)
-- Precommit is clean, reported failures in evpn-smoke & vrl are resolved
-- some other tests fail in evpn-smoke, bgp-smoke & vrl, appear to be existing
-- or unrelated failures
> bgpd: Reset LLA NHT's interface if there is a change

- doc/user/ospf6d.rst
And delete some trailing whitespace
> doc: remove extraneous .. index:: in ospf6d.rst

- doc/user/bgp.rst
> doc: document proper config for BGP iface peers

- ospf6d/ospf6_lsa.c
When the ospf6 daemon goes down, it originates MAX_AGE
LSAs for all the self-originated LSAs so that it gets
flushed from the neighbor's database. But the link-LSAs
are not getting MAX_AGE.
Set the self-originated link-LSAs age to MAX_AGE and
flood it
> ospf6d: Link LSAs are not getting MAX_AGE in neighbor

- yang/subdir.am
> yang: Allow `make clean` to actually clean up dependant files

- ospfd/ospf_vty.c
> ospfd: fix SA warning

- doc/developer/tracing.rst
- tools/frr.service.in
- tools/frr@.service.in
Signed-off-by: Simon Deziel <simon@sdeziel.info>
> systemd's %n already includes the type suffix (.service)

- ospf6d/ospf6_asbr.c
> ospf6d: fix coverity warning

- bgpd/bgp_nb_config.c
- bgpd/bgp_vty.c
Don't use operational state in CLI.
> bgp cli fixes

- bgpd/bgp_evpn_vty.c
- bgpd/bgp_mplsvpn.c
- bgpd/bgp_route.c
- doc/user/bgp.rst
Reverts FRRouting/frr#8216
This merge resulted in a compile problem
> Revert "bgpd: Add 'rd all' keyword to EVPN/L3VPN show cmds"

- ospfd/ospf_bfd.c
> ospfd: fix building with --disable-bfdd

- bgpd/bgp_rpki.c
> bgpd: fix build warnings

- bfdd/bfd.c
- bfdd/bfd.h
- bfdd/bfdd_cli.c
- bfdd/bfdd_nb_config.c
- vtysh/vtysh.c
A couple of fixes for "no bfd" command (one is a crash).
And a fix for profiles autocompletion.
Fixes https://github.com/FRRouting/frr/issues/8379
> Fix "no bfd" crash

- bgpd/bgp_nb_config.c
Fix missing/incorrect callbacks.
> bgpd: prefix-list and route-map nb fixes

- tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1.py
- tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2.py
- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
Few tests were failing in BGP-GR intermittently. Fixing the failures
> tests: Fix for BGP_GR test failures

- lib/filter.h
- lib/filter_cli.c
- lib/filter_nb.c
> [7.5] access-list and prefix-list fixes

- bgpd/bgp_bfd.c
- lib/bfd.c
> ospfd: fix crash on "show ip ospf neighbor detail"

- bgpd/bgp_mplsvpn.c
> bgpd: Remove dead code regarding prefix_rd allocation

- doc/user/basic.rst
- vtysh/vtysh.c
> vtysh: add "show memory" for a single daemon

- bgpd/bgp_attr.c
> bgpd: Use bool type to check if use32bit ASN

- doc/user/overview.rst
Lame attempt at describing the factors involved in choosing resources
for running FRR
Fixes: #2554
> doc: vaguely describe system requirements

- doc/developer/topotests.rst
> doc: Check for convergence, not sleep for convergence

- doc/user/routemap.rst
- lib/routemap.c
- lib/routemap.h
- lib/routemap_cli.c
- lib/routemap_northbound.c
- vtysh/vtysh_config.c
- yang/frr-route-map.yang
This command was missed in https://github.com/FRRouting/frr/pull/7419.
> lib: convert route-map optimization to NB

- lib/bfd.c
Fixes #8473 : fixing this causes the leak to not show anymore as well.
- Handle badly formatted messages (don't set `ifp` in that case)
- Handle unread messages (e.g. when family is not don't trigger `assert`)
> lib: fix BFD crash on interface removal

- lib/xref.h
The "xref_p" variables are placed in the "xref_array" section
specifically so they're next to each other and we get an array at the
end.  The ASAN redzone that is inserted around global variables is
breaks that since it'd be inserted before and after each of the array
items.  So disable the ASAN redzone for these variables (and only these
variables, nothing else should be affected.)
Signed-off-by: David Lamparter <equinox@diac24.net>
Fixes: #8481
> lib: disable ASAN redzone around xref_p/xref_array

- lib/log_vty.c
- lib/subdir.am
- lib/thread.c
- pathd/subdir.am
- python/vtysh-cmd-check.py
- vtysh/extract.pl.in
- vtysh/vtysh.c
- zebra/subdir.am
I may have forgotten to update `vtysh_scan` when moving things around, particularly on the log commands... oops.  Let's do some spring cleaning on `vtysh_scan`.
(This PR is alternate to / supersedes #8464 )
> fix vtysh_scan SNAFUs

- bgpd/bgp_route.c
> bgpd: Fix clang-format/indentation for show_ip_bgp_large_community_list_cmd

- doc/user/ospfd.rst
> doc: fix ospfd maximum-paths command

- tools/frrcommon.sh.in
> [7.5] Cherry-picking #8309

- tools/frr-reload.py
see individual commits
1) fix the usage of is not
2) cleanup w/ black
> Reload complaining about using `is not`

- yang/frr-zebra.yang
> [7.5] yang: fix zebra module

- isisd/isis_circuit.h
- isisd/isis_csm.c
- isisd/isis_csm.h
see individual commits, some code cleanup and a warn -> debug trade
> Isis circuit warning

- doc/user/Useful_Sysctl_Settings.md
- doc/user/zebra.rst
Add some color to useful sysctl's that are needed for FRR proper operation.
> doc: Start talking about useful sysctl's for proper zebra operation

- doc/user/zebra.rst
> zebra: Add some flavor documentation for ECMP in zebra

- lib/command.c
- lib/command.h
- lib/zlog_targets.c
(These are the first 2 commits from #8457)
Both of these commits should be backported to all stable branches where they apply, I'll open PRs for that when this is merged.  The first one fixes an (unlikely) assert failure, the second one fixes a minor CLI problem that could cause RPKI configs to not load correctly.
> lib: fix zlog assert() & CLI node_exit

- tests/topotests/bgp-default-ipv4-ipv6-unicast/test_bgp-default-ipv4-ipv6-unicast.py
- tests/topotests/bgp-ebgp-common-subnet-nexthop-unchanged/test_bgp-ebgp-common-subnet-nexthop-unchanged.py
> tests: Add pytest bgpd markers for recent BGP tests

- lib/command.c
- lib/command.h
- lib/zlog_targets.c
cf. commit descriptions & #8527 
one assert fix & one fix that can cause RPKI configs to not load correctly
> [7.5] backport #8527

- bgpd/bgp_evpn.c
- bgpd/bgp_zebra.c
- lib/zclient.c
- lib/zclient.h
- pimd/pim_zlookup.c
- zebra/rtadv.c
- zebra/zebra_evpn_mh.c
- zebra/zebra_mroute.c
- zebra/zebra_vxlan.c
various signedness / encoding / decoding issues in zapi cleaned up
> Fix zapi codec badness

- doc/user/bgp.rst
> doc: add evpn discussion of svi and arp cache

- doc/user/bgp.rst
- doc/user/kernel.rst
> doc: remove obsolete Netlink discussion, fix svi cmd doc

- bgpd/bgp_network.c
- bgpd/bgp_packet.c
see individual commits.  But doing some cleanup work in prep for other bgp work going on.
> Peer cleanups

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_msdp.c
- pimd/pim_msdp.h
- pimd/pim_vty.c
Summary
---
I'm reworking some of the PIM code and I've found some issues. Since my original PR #8561 does not have reviewers yet, I'm opening this PR to fix some independent small issues in hope that we can get this merged faster.
Changes:
* Remove some code duplication
* Fix the documentation and improve it
* Show MSDP regular peer configuration in `show running`
> pimd: MSDP trivial fixes

- zebra/connected.c
Currently FRR reads the kernel for interface state and FRR
creates a connected route per address on an interface.  If
you are in a situation where you have multiple addresses
on an interface just create 1 connected route for them:
sharpd@eva:/tmp/topotests$ vtysh -c "show int dummy302"
Interface dummy302 is up, line protocol is up
Link ups:       0    last: (never)
Link downs:     0    last: (never)
vrf: default
index 3279 metric 0 mtu 1500 speed 0
flags: <UP,BROADCAST,RUNNING,NOARP>
Type: Ethernet
HWaddr: aa:4a:ed:95:9f:18
inet 10.4.1.1/24
inet 10.4.1.2/24 secondary
inet 10.4.1.3/24 secondary
inet 10.4.1.4/24 secondary
inet 10.4.1.5/24 secondary
inet6 fe80::a84a:edff:fe95:9f18/64
Interface Type Other
Interface Slave Type None
protodown: off
sharpd@eva:/tmp/topotests$ vtysh -c "show ip …
> zebra: Allow one connected route per network mask on a interface

- ospf6d/ospf6_interface.c
As per the ospfv3 conformance test 24.3
1. SETUP: Configure DIface-0 with priority set to <hprty>.
2. ANVL: Establish full adjacency with DUT for neighbor Rtr-0-A on DIface-0.
3. DUT: Exchange all the <OSPF-DD> packets, during adjacency establish- ment.
4. ANVL: Verify that the received <OSPF-DD> packets contain: • one header of Link-LSA, originated by DUT.
5. ANVL: Send <OSPF-LSR> packet from neighbor Rtr-0-A to DIface-0 con- taining:
One Request Tuple for Link-LSA originated by DUT.
6. ANVL: Listen (for upto 2 * <RxmtInterval> seconds) on DIface-0. DUT: Send <OSPF-LSU> packet.
7. ANVL: Verify that the received <OSPF-LSU> packet contains:
one Link-LSA, originated by DUT, contains: Rtr Pri field set to <hprty>.
When interface priority is changed Link LSAs should be transmitted
with the …
> ospf6d: Send Link LSAs when interface priority is changed

- doc/user/sharp.rst
- sharpd/sharp_vty.c
- sharpd/sharp_zebra.c
- sharpd/sharp_zebra.h
Add the ability for sharpd to watch v4 redistribution events
> sharpd: add v4 redistribute watching

- tests/topotests/bgp-auth/test_bgp_auth.py
Individual tests must not depend on each other. In particular, a test
can't be sure that the previous test config is applied or cleared.
It is definitely not true when a single test is executed, for example:
`test_bgp_auth.py::test_prefix_peer_remove_passwords`.
This commit makes all tests independent of each other. It also adds a
call to check_all_peers_established at the start of "remove_passwords"
tests to make sure that we not only block new peers with an incorrect
password, but also clean the existing peers.
Fixes #8522
> tests: fix bgp-auth topotest

- doc/user/ospf6d.rst
- ospf6d/ospf6_area.c
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_interface.c
- ospf6d/ospf6_main.c
- ospf6d/ospf6_neighbor.c
- ospf6d/ospf6_top.c
- ospf6d/ospf6_top.h
- ospf6d/ospf6d.c
- ospf6d/ospf6d.h
- tests/topotests/ospf6-topo1-vrf/README.md
- tests/topotests/ospf6-topo1-vrf/r1/ip_6_address.nhg.ref
- tests/topotests/ospf6-topo1-vrf/r1/ip_6_address.ref
- tests/topotests/ospf6-topo1-vrf/r1/ospf6d.conf
- tests/topotests/ospf6-topo1-vrf/r1/show_ipv6_vrf_route.ref
- tests/topotests/ospf6-topo1-vrf/r1/zebra.conf
- tests/topotests/ospf6-topo1-vrf/r2/ip_6_address.ref
- tests/topotests/ospf6-topo1-vrf/r2/ospf6d.conf
- tests/topotests/ospf6-topo1-vrf/r2/show_ipv6_vrf_route.ref
- tests/topotests/ospf6-topo1-vrf/r2/zebra.conf
- tests/topotests/ospf6-topo1-vrf/r3/ip_6_address.ref
- tests/topotests/ospf6-topo1-vrf/r3/ospf6d.conf
- tests/topotests/ospf6-topo1-vrf/r3/show_ipv6_vrf_route.ref
- tests/topotests/ospf6-topo1-vrf/r3/zebra.conf
- tests/topotests/ospf6-topo1-vrf/r4/ip_6_address.ref
- tests/topotests/ospf6-topo1-vrf/r4/ospf6d.conf
- tests/topotests/ospf6-topo1-vrf/r4/show_ipv6_vrf_route.ref
- tests/topotests/ospf6-topo1-vrf/r4/zebra.conf
- tests/topotests/ospf6-topo1-vrf/test_ospf6_topo1_vrf.py
- vtysh/vtysh.c
This is a cleanup of https://github.com/FRRouting/frr/pull/7734.
I split a single commit into three:
- actual code for multiple vrf support (just ~100 lines)
- cli update
- topotest
I also fixed a couple of minor issues asked by reviewers of the initial PR.
Finally, there's one more commit authored by me updating the docs (this was missing in the initial PR).
Let's wait for CI to finish and merge this in.
> OSPFv3 VRF support

- doc/user/bgp.rst
maximum 1 argument(s) allowed, 56 supplied.
> doc: Remove trailing whitespaces and fix WARNING: Error in "code-block"

- bgpd/bgp_vty.c
> bgpd: don't return error for GR no-op commands

- zebra/zebra_evpn.c
- zebra/zebra_evpn_mac.c
- zebra/zebra_evpn_neigh.c
- zebra/zebra_mpls.c
- zebra/zebra_vrf.c
- zebra/zebra_vrf.h
- zebra/zebra_vxlan.c
reduce hash size on startup for two situations:
a) per vrf creation
b) per vni creation.
> Hash size reduction

- tests/topotests/multicast-pim-static-rp-topo1/test_multicast_pim_static_rp.py
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo1_ebgp.py
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo2_ebgp.py
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo3_ebgp.py
- tests/topotests/static_routing_with_ebgp/test_static_routes_topo4_ebgp.py
- tests/topotests/static_routing_with_ibgp/test_static_routes_topo1_ibgp.py
- tests/topotests/static_routing_with_ibgp/test_static_routes_topo2_ibgp.py
- tests/topotests/static_routing_with_ibgp/test_static_routes_topo3_ibgp.py
- tests/topotests/static_routing_with_ibgp/test_static_routes_topo4_ibgp.py
Fix pylint errors in three dirs, see commits for details. Also noticed a mis-named test suite that wasn't being run, enabled it.
> tests: fix some pylint errors

- bgpd/bgp_main.c
- isisd/isis_adjacency.h
- isisd/isis_bfd.c
- isisd/isis_bfd.h
- isisd/isis_circuit.c
- isisd/isis_circuit.h
- isisd/isis_cli.c
- isisd/isis_main.c
- isisd/isis_nb_config.c
- isisd/isis_vty_fabricd.c
- isisd/isis_zebra.c
- isisd/isisd.c
- lib/bfd.c
- lib/bfd.h
- ospf6d/ospf6_main.c
- ospfd/ospfd.c
- pimd/pimd.c
- update isisd to use new bfd library
- fix a couple of issues in isis cli related to bfd configuration
- remove old bfd library (isisd was the last daemon using it)
> isisd: rework BFD integration

- lib/command.c
- lib/command.h
- lib/zlog_targets.c
cf. #8527 & commit descriptions
> [7.4] backport #8527

- bgpd/bgp_pbr.c
- bgpd/bgp_zebra.c
- tests/topotests/bgp_flowspec/test_bgp_flowspec_topo.py
see individual commits, but cleanup some code duplication.  I am sure more to come
> Bgp flowspec cleanups

- tests/.gitignore
> tests: fix missing gitignore entry

- bgpd/bgp_route.c
For EVPN routes, there is specific logic in place for path selection
surrounding MAC Mobility.  For pure type-5 routes, if a route is
advertised with a MED, this is ignored since it ultimately falls inside
of the EVPN specific path selection logic, and ultimately selects the
lower IP address.  This change ensure type-5 routes fall into the
normal BGP path selection.
Signed-off-by: Neal Shrader <neal@digitalocean.com>
> bgpd: modify path selection for EVPN type-5 routes

- tests/topotests/lib/common_config.py
- tests/topotests/lib/ospf.py
- tests/topotests/ospf_basic_functionality/test_ospf_rte_calc.py
- tests/topotests/ospf_basic_functionality/test_ospf_single_area.py
Test cases included are ospf cost, 1 ospf mtu.
> tests: adding ospf basic 2 testcases.

- doc/developer/workflow.rst
- doc/user/eigrpd.rst
- doc/user/nhrpd.rst
- doc/user/ospf6d.rst
- doc/user/ospfd.rst
> doc: remove redundant index directives

- isisd/isis_snmp.c
> isisd: fix build warning and simplify code

- ospf6d/ospf6_asbr.c
> ospf6 redistribution fixes

- lib/northbound.c
- pbrd/pbr_nht.c
> fix a couple of coverity warnings

- doc/developer/grpc.rst
Add C++ and Python examples, and add compiling info, and known gRPC
version that works.
Signed-off-by: Christian Hopps <chopps@gmail.com>
> doc: expand documentation on gRPC

- tests/topotests/ospf_sr_topo1/rt1/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt2/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt3/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt4/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt5/ospfd.conf
- tests/topotests/ospf_sr_topo1/rt6/ospfd.conf
Add some basic timer operations to speed up convergence.
> tests: Speedup ospf_sr_topo1 by over 100 seconds

- pimd/pim_igmp.c
- pimd/pim_oil.c
see individual commits for data
> Pim possible crash

- bgpd/bgp_zebra.c
- lib/route_opaque.h
- lib/subdir.am
- tests/topotests/zebra_opaque/r1/bgpd.conf
- tests/topotests/zebra_opaque/r1/zebra.conf
- tests/topotests/zebra_opaque/r2/bgpd.conf
- tests/topotests/zebra_opaque/r2/zebra.conf
- tests/topotests/zebra_opaque/test_zebra_opaque.py
- zebra/zebra_vty.c
Commits have their own descriptions.
> Zebra OPAQUE data from other daemons stuff

- lib/vrf.c
> lib: fix missing newline

- doc/user/ospfd.rst
- doc/user/pathd.rst
> doc: remove "no" commands

- tools/frr-reload.py
All of peers and respective configs are wiped out when
pee-group is removed.
In an attempt to remove peer-group and its associated peers
configs via frr-reload fails if the peer-group is removed first.
To pass the peer-group config removal via frr-reload following steps are taken:
Find the bgp context to which peer-group belongs.
Find the peer-group associated peer(s) and store them in a list.
Remove the peers config lines from the pending list.
Move the peer-group deletion line to end of the pending list so
any remaining peer-group associated config can be removed successfully.
The above steps take 3 iterations over the pending list and scales
linearly.
Testing Done:
Broken:
config:
router bgp 5544
neighbor PG1 peer-group
neighbor PG1 remote-as external
neighbor swp10 interface …
> tools: fix bgp peer-group deconfiguration in frr-reload

- ospf6d/ospf6_interface.c
OSPF6 instance may not exist when processing interface state change.
Do not execute processing steps that require an instance if an area is
not configured for an interface.
> ospf6d: fix possible crashes

- doc/developer/building-libyang.rst
- docker/ubuntu18-ci/Dockerfile
- docker/ubuntu20-ci/Dockerfile
Signed-off-by: Christian Hopps <chopps@gmail.com>
> build: libyangv2 is mainlined, update

- configure.ac
> grpc: improve checks for GRPC C++ requirements

- doc/user/zebra.rst
> doc: fix redundant index once again

- tests/topotests/multicast_pim_sm_topo2/test_multicast_pim_sm_topo2.py
> tests: Fixup some pylint warnings in test_multicast_pim_sm_topo2.py

- lib/compiler.h
> lib: Time to remove CONFDATE block

- tests/topotests/bgp_gshut_topo1/ebgp_gshut_topo1.json
- tests/topotests/bgp_gshut_topo1/ibgp_gshut_topo1.json
- tests/topotests/bgp_gshut_topo1/test_ebgp_gshut_topo1.py
- tests/topotests/bgp_gshut_topo1/test_ibgp_gshut_topo1.py
1. Automated 4 test cases to verify BGP Graceful Shutdown community functionality,
with 2 different topologies.
> tests: Add bgp_gshut_topo1 test suite

- isisd/isis_circuit.c
- isisd/isis_cli.c
- isisd/isis_nb_config.c
> isisd: fix using vrf interface as a loopback

- doc/developer/topotests.rst
> doc: Replace single tick with double tick under developer/topotests.rst

- ospfd/ospfd.c
ospfd: remove ospf passive-interface when delete the whole ospf
When delete the whole ospf: "no route ospf", the passive-interface config of this ospf shall also be removed.
> ospfd: remove ospf interface config: passive-interface

- bgpd/bgp_mplsvpn.c
- pathd/path_pcep_debug.c
- pathd/path_pcep_debug.h
see individual commits but just general clean up from a SA run in coverity
> Sr coverity

- ospf6d/ospf6_message.c
- ospf6d/ospf6_network.c
Cherry-pick the read side fixes from #8725 to dev/8.0
> Backport ospf6 socket non blocking read

- tests/topotests/ospf_basic_functionality/ospf_asbr_summary_topo1.json
- tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_topo1.py
Test suite execution time is ~1 minutes.
Signed-off-by: naveen <nguggarigoud@vmware.com>
> tests : Adding 2 ospf asbr summary testcases.

- lib/zclient.c
- ospf6d/ospf6_lsa.c
- ospfd/ospf_flood.c
- ospfd/ospf_gr_helper.c
- ospfd/ospf_gr_helper.h
- ospfd/ospf_lsa.c
- ospfd/ospf_main.c
- ospfd/ospf_opaque.c
- ospfd/ospf_packet.c
- ospfd/ospf_spf.c
- ospfd/ospf_vty.c
- ospfd/ospfd.c
- zebra/zebra_gr.c
...bringing assorted fixes from #8767 into their own PR so that they can be reviewed and merged earlier.
> ospfd: assorted fixes

- lib/srv6.c
- zebra/zapi_msg.c
- zebra/zebra_srv6.c
Enhance the dtor for srv6 'locators'; also a couple of small cleanups in zebra srv6 code.
> lib,zebra: srv6 cleanup

- ospf6d/ospf6_abr.c
- ospf6d/ospf6_abr.h
- ospf6d/ospf6_area.c
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_intra.c
- ospf6d/ospf6_nssa.c
- ospf6d/ospf6_snmp.c
- ospf6d/ospf6_spf.c
- ospf6d/ospf6_top.c
fix 2 coverity issues, see individual commits
> Ospfv3 coverity

- lib/vrf.c
Always terminate default VRF last during FRR shutdown.
On shutdown we were simply looping over the RB tree and terminating
VRFs from the ROOT. This is not guaranteed to be the default last ever.
Instead switch to RB_SAFE and skip the default VRF till the very end.
> lib: terminate default vrf last

- doc/user/basic.rst
> doc: add a note of domainname

- zebra/zserv.c
see individual commits.  They all center around `show zebra client`
> Zapi message count

- tests/topotests/lib/common_config.py
- tests/topotests/lib/ospf.py
- tests/topotests/ospfv3_basic_functionality/ospfv3_rte_calc.json
- tests/topotests/ospfv3_basic_functionality/ospfv3_single_area.json
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_rte_calc.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
1. Adding  APIs to configure and verify ospfv3.
2. Adding ospfv3 base functionality testcase.
> tests: Adding ospfv3 basic functionality test cases

- lib/northbound_grpc.cpp
Try to correctly stop and cleanup the grpc module's dedicated pthread at shutdown time.
This may fix #8461
> lib: stop grpc pthread at shutdown

- doc/user/basic.rst
add a note document for hostname and domainname for vtysh
fix #1497
> doc: add a note of hostname/domainname for vtysh

- tests/topotests/ospf_basic_functionality/ospf_asbr_summary_type7_lsa.json
- tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_topo1.py
- tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_type7_lsa.py
> tests: Adding ospfv2 summarisation test cases.

- tests/topotests/bgp_route_map/test_route_map_topo1.py
1. There was a false condition, which was causing support bundle to be generated.
Issue is fixed.
> tests: Fix generate support bundle issue for test_route_map_topo1

- pathd/pathd.c
> pathd: coverity msg , frr_weak_random instead rand.

- lib/command.c
> lib: Add some hash name differentiation for Command Hash's

- doc/user/bgp.rst
- doc/user/ospf6d.rst
- doc/user/zebra.rst
> doc: remove unnecessary index directives

- tests/bgpd/test_peer_attr.c
> tests: fix build warning

- bgpd/bgp_flowspec_util.c
- bgpd/bgpd.c
- eigrpd/eigrp_network.c
- lib/prefix.h
- zebra/connected.c
> zebra: fix a couple of coverity warnings

- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_top.c
- ospf6d/ospf6_top.h
- ospf6d/ospf6_zebra.c
> Revert "ospf6d: fix LSAs remain in LSDB with an old router-id value"

- bgpd/bgp_route.c
> bgpd: Unlock bgp_dest for bgp_distance_unset if distance does not match

- bgpd/bgp_fsm.c
- bgpd/bgp_updgrp.c
- bgpd/bgpd.c
Related: https://github.com/FRRouting/frr/issues/8889
> bgpd: Extended message support potential fixes

- ospf6d/ospf6_flood.c
==================
Max aged LSAs are not getting deleted from DB when there are multiple neighbors in a LAN and ack is received late.
LSAs are removed when there is 1 neighbor in full state. I have 2 neighbors in a LAN, a moment later the second neighbors tries to come up. The max age LSA remains in DB forever.
AS Scoped Link State Database
Type LSId           AdvRouter       Age   SeqNum                        Payload
ASE  0.0.0.0        11.11.11.11    3600   80000001                      33::33/128
Rtr-1(config-ospf6)#
Root Cause Analysis:
====================
When the LSA is added to the neighbor's retransmit list, the LSA retrans count
is incremented but it is not checked if the LSA is already present in the
retransmit list leading to the count being incremented …
> ospf6d: Max aged LSAs are not getting deleted from DB

- ospf6d/ospf6_interface.c
> ospf6d: Correct spelling in debug

- bgpd/bgp_updgrp_packet.c
- tests/topotests/bgp_default_route/r2/bgpd.conf
- tests/topotests/bgp_default_route/test_bgp_default-originate.py
Closes https://github.com/FRRouting/frr/issues/9048
> bgpd: Reflect changes to pfxSnt when using default-originate

- tests/topotests/lib/common_config.py
- tools/frr-reload.py
- Remove incorrect requirement for `service integrated-vtysh-config`
when producing a delta.
- Add `--test-reset` option which suppresses non-parseable lines from the
produced delta
> tools: improve frr-reload.py delta file creation

- tests/topotests/evpn_type5_test_topo1/evpn_type5_topo1.json
- tests/topotests/lib/bgp.py
- tests/topotests/lib/common_config.py
The includes topojson library changes for bgp neighbor types.
> tests: Adding lib changes for bgp peer type verification.

- bgpd/bgp_route.c
Closes https://github.com/FRRouting/frr/issues/9054
> bgpd: BGP dampening JSON fixes

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_nb_config.c
- pimd/pim_neighbor.c
- yang/frr-pim.yang
1. Adding BSM status in show command.
2. Made hold interval range to 3.5 times the hello interval.
For more details, please check individual commit messages.
> pimd: Minor fixes for BSM Show CLI and Hold Timer CLI

- zebra/zapi_msg.c
- zebra/zebra_rnh.c
- zebra/zebra_rnh.h
- zebra/zebra_vty.c
Combined backport of PR #8174 and PR #9001 for stable/8.0 as they depend on each other
> Backport of PR 9001 and PR 8174 for 8.0

- zebra/zapi_msg.c
- zebra/zebra_rnh.c
- zebra/zebra_rnh.h
- zebra/zebra_vty.c
> Revert "Backport of PR 9001 and PR 8174 for 8.0"

- doc/user/pim.rst
- pimd/pim_cmd.c
- pimd/pim_nb_config.c
- pimd/pim_neighbor.c
- yang/frr-pim.yang
> Revert "pimd: Minor fixes for BSM Show CLI and Hold Timer CLI (backport #8983)"

- doc/user/pim.rst
- pimd/pim_cmd.c
- tests/topotests/evpn_pim_1/leaf1/pimd.conf
- tests/topotests/evpn_pim_1/leaf2/pimd.conf
- tests/topotests/evpn_pim_1/spine/pimd.conf
- tests/topotests/msdp_mesh_topo1/r1/pimd.conf
- tests/topotests/msdp_mesh_topo1/r2/pimd.conf
- tests/topotests/msdp_mesh_topo1/r3/pimd.conf
- tests/topotests/msdp_topo1/r1/pimd.conf
- tests/topotests/msdp_topo1/r2/pimd.conf
- tests/topotests/msdp_topo1/r3/pimd.conf
- tests/topotests/msdp_topo1/r4/pimd.conf
- tests/topotests/pim_acl/r1/pimd.conf
- tests/topotests/pim_acl/r11/pimd.conf
- tests/topotests/pim_acl/r12/pimd.conf
- tests/topotests/pim_acl/r13/pimd.conf
- tests/topotests/pim_acl/r14/pimd.conf
- tests/topotests/pim_acl/r15/pimd.conf
- tests/topotests/pim_basic/r1/pimd.conf
- tests/topotests/pim_basic/rp/pimd.conf
- tests/topotests/pim_basic_topo2/r2/pimd.conf
- tests/topotests/pim_igmp_vrf/r1/pimd.conf
- tests/topotests/pim_igmp_vrf/r11/pimd.conf
- tests/topotests/pim_igmp_vrf/r12/pimd.conf
- yang/frr-pim.yang
Allow join/prune to go as low as 5 seconds between sends
> Join prune smaller

- tests/topotests/lib/common_config.py
- tests/topotests/lib/ospf.py
- tests/topotests/ospfv3_basic_functionality/ospfv3_ecmp.json
- tests/topotests/ospfv3_basic_functionality/ospfv3_routemaps.json
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_routemaps.py
- tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
> tests:  adding ospfv3 basic cases

- bgpd/bgp_zebra.c
- doc/user/pbr.rst
- lib/pbr.h
- pbrd/pbr_map.h
- pbrd/pbr_vty.c
- pbrd/pbr_zebra.c
- zebra/kernel_netlink.c
- zebra/kernel_netlink.h
- zebra/rule_netlink.c
- zebra/zapi_msg.c
- zebra/zebra_dplane.c
- zebra/zebra_dplane.h
- zebra/zebra_pbr.c
see individual commits but effectively we can now match on the ip protocol being sent in the flow
> add ability to match on proto to pbr

- ospfd/ospf_vty.c
> ospfd: remove gratuitous non-ascii quotation marks

- bgpd/bgp_filter.c
- doc/user/bgp.rst
- doc/user/filter.rst
- doc/user/routemap.rst
- doc/user/zebra.rst
- lib/filter.c
- lib/plist.c
- lib/routemap.c
- zebra/interface.c
- zebra/zebra_evpn_mh.c
- zebra/zebra_evpn_mh.h
- zebra/zebra_ptm.c
- zebra/zebra_ptm.h
Add a "json" option to a few more "show" commands...
Example data:
* `show bgp as-path-access-list`: https://pastebin.com/raw/we5dtzBy
* `show ip access-list `: https://pastebin.com/raw/jtxbMk1c
* `show route-map`: https://pastebin.com/raw/K32HA88p
* `show interface`: https://pastebin.com/raw/A2brGEm6
* `show ip prefix-lis`: https://pastebin.com/raw/8bVZb9wr
> *: can't get enough JSON

- ospfd/ospf_vty.c
This command is currently always treated as an "unset" command, assuming
that active is the default type of the interface. In reality, the default
type of the interface can be changed using "passive-interface default"
command. Both "no" and regular commands can be "set" commands, depending
on the default value. They are treated as an "unset" when there's already
a config of the opposite type.
All this logic is in ospf_passive_interface_update.
Fixes #9240.
> ospfd: fix "no ip ospf passive" command

- nhrpd/nhrp_vty.c
Before:
ip nhrp nhs dynamicnbma 192.168.1.1
After:
ip nhrp nhs dynamic nbma 192.168.1.1
Signed-off-by: Dmitrii Turlupov \<dturlupov@factor-ts.ru\>
> nhrp: fix display of nhs command.

- bgpd/bgp_route.c
When an EVPN prefix flaps too quickly such that the new advertisement
is received prior to the full processing of the prior withdraw, we may
get into a state where the route doesn't get imported properly into
MAC or IP VRFs. Ensure that we do the route import in such cases.
Suggested-by: Sri Mohana Singamsetty <msingamsetty@vmware.com>
Suggested-by: Ameya Dharkar <adharkar@vmware.com>
Signed-off-by: Vivek Venkatraman <vivek@nvidia.com>
> bgpd: Handle quick flaps of an EVPN prefix properly

- doc/user/pathd.rst
- pathd/path_cli.c
- pathd/path_ted.c
> pathd: a couple of cli/doc fixes

- doc/user/bgp.rst
Closes https://github.com/FRRouting/frr/issues/9272
> doc: Specify how aggregate-address works for BGP

- tools/frr-reload.py
tools: add "vni" to oneline list
Add "vni" into oneline list.
Additionally, keep them in order in oneline list.
> tools: add "vni" to oneline list

- lib/zclient.c
- zebra/zebra_mpls.c
> Zebra should continue

- tools/etc/frr/support_bundle_commands.conf
tools: Add ospfv2 and ospfv3 commands in support bundle
> tools: Add ospfv2 and ospfv3 commands in support bundle

- zebra/zapi_msg.c
In the fuzzing code we cut to the chase and call zserv_handle_commands
which bypasses the basic parsing correctness done in zserv_read
duplicate some of this code in the zserv_handle_commands function
so we can throw away blatantly bad packages.
> zebra: Ensure stream meets some level of stringency for fuzzing

- lib/zebra.h
> lib: Switch to zapi fuzzing as higher priority

- doc/user/ospf6d.rst
> a couple of ospf6 doc fixes

- lib/frrstr.c
- lib/frrstr.h
- ospf6d/ospf6_lsa.c
> ospf6d: JSON output for database dump show command

- doc/developer/workflow.rst
- tools/releasedate.py
As discussed in the weekly meeting today, this is what we're trying to work with for the time being.
(Date calculator included as a bonus goodie ;)
> workflow: document release scheduling discussed

- doc/user/zebra.rst
> doc: Replace typo BANDIWDTH to BANDWIDTH

- bgpd/bgp_ecommunity.h
- bgpd/bgp_routemap.c
- bgpd/bgp_routemap_nb_config.c
- lib/routemap.h
- lib/routemap_cli.c
> bgpd: Extended community bandwidth fixes

- bgpd/bgp_routemap.c
> bgpd: Return rmap match if large-community alias found

- bgpd/bgp_rpki.c
See individual commits.  the first one is the important one it should improve performance greatly when processing rpki w/ a bunch of peers
> Rpki processing

- include/linux/rtnetlink.h
> include: Update rtnetlink.h to be correct with upstream kernels

- ospfd/ospfd.c
There are a couple of things that are not initialized if the OSPF router
is created in a non-existent VRF:
- ospf_lsa_maxage_walker
- ospf_lsa_refresh_walker
- ospf_opaque_type11_lsa_init
Rearrange some code to always initialize them and make it easier to find
similar problems in the future.
> ospfd: fix initialization when vrf doesn't exist yet

- tools/etc/frr/support_bundle_commands.conf
> tools: add ospfd support bundle commands

- doc/user/ospf6d.rst
> doc: merge duplicated ospf6d debugging sections

- tests/topotests/ospf_basic_functionality/test_ospf_routemaps.py
> tests: ospf routemap basic test cases 2.

- tests/topotests/lib/common_config.py
- tests/topotests/lib/ospf.py
- tests/topotests/ospf_gr_helper/ospf_gr_helper.json
- tests/topotests/ospf_gr_helper/test_ospf_gr_helper.py
Testing ospf gr helper using scapy tool.
> tests: ospf gr helper topotests with scapy.

- ospf6d/ospf6_abr.c
- ospf6d/ospf6_area.c
- ospf6d/ospf6_area.h
- ospf6d/ospf6_asbr.c
- ospf6d/ospf6_nssa.c
- ospf6d/ospf6_nssa.h
- ospf6d/ospf6_route.c
- ospf6d/ospf6_spf.c
- tests/topotests/ospf6_topo2/r1/ospf6d.conf
- tests/topotests/ospf6_topo2/r2/ospf6d.conf
- tests/topotests/ospf6_topo2/r3/ospf6d.conf
- tests/topotests/ospf6_topo2/r4/ospf6d.conf
- tests/topotests/ospf6_topo2/test_ospf6_topo2.py
A few fixes for bugs I found while implementing some enhancements to ospf6d. Submitting them as a separate PR to facilitate review and backporting.
> ospf6d: NSSA fixes
