FRRouting/frr

isisd/isis_nb_config.c
pathd/path_nb_config.c
pimd/pim_nb_config.c
yang/frr-zebra.yang
zebra/zebra_nb.c
zebra/zebra_nb.h
zebra/zebra_nb_config.c
zebra/zebra_nb_state.c

There are places in the code where function `nb_running_get_entry` is used
with `abort_if_not_found` set to `true` during the config validation stage.
This is incorrect because when used in transactional CLI, the running
entry won't be set until the apply stage, and such usage leads to a crash.
The first commit fixes simple things like moving the usage of `nb_running_get_entry`
to the apply stage, or changing `abort_if_not_found` to `false` where possible.
The second one also fixes the incorrect usage of `nb_running_get_entry` by
making zebra RIBs state-only in the YANG model. The detailed description is in the commit.
This PR fixes https://github.com/FRRouting/frr/issues/8228 at least partially – there should be
no crashes anymore.

Fix aborts when using nb_running_get_entry during validation stage

---

vtysh/vtysh.c

This command is currently useful only for developers.
Let's hide it to not confuse end users by having both
"show runnning-config" and "show configuration running".

vtysh: hide "show configuration running" command

---

ospf6d/ospf6_flood.c

Do not flood unknown LSAs if U-bit is clear.

ospf6d: Do not flood unknown LSAs if U-bit is clear

---

tools/frrcommon.sh.in

Prettier (and shorter) version of #8281 :wink:
> When FRR is starting all daemons (or restarting them all) FRR is reading
in the configuration 1 time for each daemon specified to run. This is
not a big deal if you have a very small configuration. But with large
configurations FRR is taking long enough that watchfrr is not
establishing connection to all the daemons and starting some over.
>
> Modify the code so that vtysh is only read in at the end of a all
sequence. If we are restarting an individual daemon allow the read in of
the whole config.

tools: run `vtysh -b` once for all-startup

---

pimd/pim_cmd.c
pimd/pim_nb_config.c
yang/frr-pim.yang

Issue 1:
PIM neighbor not coming up if hold time is less than hello timer
since hello is sent every 4 sec and hold is 1 sec,
because of this nbr is flapping
Also included display of hold time in CLI 'show ip pim int <intf>' cmd
and json commands.
Issue2:
pimd: in 'no ip pim hello' make "hold time" as optional when undo config
Fix:
Do not allow configuration of hold timer less than hello timer
Also reset the value of hold timer to 3.5 times to hello whenever
only hello is modified so that the relationship holds good.
Make the hold time as optional when undo config.
Signed-off-by: Mobashshera Rasool<mrasool@vmware.com>

pimd: Fix hold time related issues

---

tools/etc/frr/support_bundle_commands.conf

PIM Support Bundle commands are added in support_bundle_commands.conf file.
It will help us in debugging PIM test Failures.

pimd: support bundle commands added

---

isisd/isis_tlvs.c

When you set the isis mtu to 200, isis ends up in a infinite loop
trying to fragment the tlv's.
Specifically ( for me ) the extended reachability function
for packing pack_item_extended_reach requires 11 + ISIS_SUBTLV_MAX_SIZE
room in the packet.  Which is 180 bytes.  At this point we have
174 bytes that we can write into a packet.
I created this by modifying the isis-topo1 topology to all
the isis routers to have a lsp-mtu of 200 and immediately
saw the crash.
Effectively the pack_items_ function had no detection for
when a part of the next bit it was writing into the stream
could not even fit and it would go into an infinite loop
allocating ~800 bytes at a time.  This would cause the
router to run out of memory very very fast and the OOM
detector would kill the process.
Modify the code …

isisd: Prevent OOM crash in isis

---

pceplib/pcep_timers.c

Fix a race in the libpcep timer code; reported by coverity: if we find the thing on the list, remove it immediately.

libs: fix race in pcep lib

---

lib/printf/vfprintf.c
tests/lib/test_table.c

Issue #8315 reported problems with the small local buffer offered to the printfrr extension callbacks - make that buffer a little bigger. Also found an oops in a test, where `%pFX` was being offered to vanilla `printf()` ...

lib: Fix short printfrr buf

---

isisd/isis_snmp.c
ospf6d/ospf6_asbr.c

Fix a  recent coverity warning; also fix an unguarded debug.

isisd,ospf6d : fix some coverity SA warnings

---

ospf6d/ospf6_abr.c

Fixes a regression in test case: anvl-ospfv3-16.14.

ospf6d: fix ospf6_abr_examin_summary to check for a path cost change

---

ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Instead of trying to maintain if_ospf_cli_count, let's directly count
the number of configured interfaces when it is needed. Current approach
sometimes leads to an incorrect counter.
Fixes #8321.

ospfd: fix counting of "ip ospf area" commands

---

ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Instead of trying to maintain if_ospf_cli_count, let's directly count
the number of configured interfaces when it is needed. Current approach
sometimes leads to an incorrect counter.
Fixes #8321.

[7.5] ospfd: fix counting of "ip ospf area" commands

---

lib/filter.h
lib/filter_cli.c
lib/filter_nb.c

Fixes for checking duplicated entries:
* restore incorrectly removed checks for prefix-lists
* take `action` into account when comparing entries – currently we treat `permit SMTH` and `deny SMTH` as same entries

access-list and prefix-list fixes

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
doc/user/bgp.rst

Adds support for 'rd all' matching for EVPN and L3VPN show commands.
Introduces evpn_show_all_routes_macip().

bgpd: Add 'rd all' keyword to EVPN/L3VPN show cmds

---

doc/user/ospfd.rst
ospfd/ospf_spf.c
ospfd/ospf_spf.h
ospfd/ospf_vty.c
ospfd/ospf_zebra.c
ospfd/ospfd.c
ospfd/ospfd.h

Description:
OSPF does not have an option to control the maximum multiple
equal cost paths to reach a destination/route(ECMP).
Currently, it is using the system specific max multiple paths.
But Somtimes, It requires to control the multiple paths from ospf.
This cli helps to configure the max number multiple paths in ospf.

ospfd: Max multipath config support

---

tools/frr-reload.py

tools: frr-reload fixes for deleting vrf static routes
Problems reported that in certain cases, frr-reload.py would
delete vrf static routes inadvertantly due to two different
reasons. First, vrf statics with null0 or Null0 nexthops would
fail the match since rendered as blackholes.  This was already
fixed for non-vrf statics so added for vrf-based.  Second,
frr-reload would fail to match due to different formats for
adding the command. If entered in the old way
"ip route x.x.x.x/x y.y.y.y vrf NAME" and rendered
in the new sway "vrf NAME\nip route x.x.x.x/x y.y.y.y" it would
fail to match do an inadvertant delete.
Second commit is to clean up items found by black formatting tool prior to the application of my fix.

Frr reload vrf static

---

bfdd/bfd.c
bfdd/bfd.h
bfdd/bfdd_cli.c
bfdd/bfdd_nb_config.c
vtysh/vtysh.c

7.5 version of https://github.com/FRRouting/frr/pull/8385

[7.5] Fix "no bfd" crash

---

lib/vrf.c
lib/vrf.h
staticd/static_routes.c
staticd/static_vrf.c
staticd/static_vrf.h
zebra/zebra_nb_config.c
zebra/zebra_vrf.c
zebra/zebra_vrf.h

This is to fix the crash reproduced by the following steps:
* ip link add red type vrf table 1
Creates VRF.
* vtysh -c "conf" -c "vrf red"
Creates VRF NB node and marks VRF as configured.
* ip route 1.1.1.0/24 2.2.2.2 vrf red
* no ip route 1.1.1.0/24 2.2.2.2 vrf red
(or similar l3vni set/unset in zebra)
Marks VRF as NOT configured.
* ip link del red
VRF is deleted, because it is marked as not configured, but NB node
stays.
Subsequent attempt to configure something in the VRF leads to a crash
because of the stale pointer in NB layer.
Fixes #8357.

*: modify VRF_CONFIGURED flag only in VRF NB layer

---

lib/vrf.c
lib/vrf.h
staticd/static_routes.c
staticd/static_vrf.c
staticd/static_vrf.h
zebra/zebra_nb_config.c
zebra/zebra_vrf.c
zebra/zebra_vrf.h

This is to fix the crash reproduced by the following steps:
* ip link add red type vrf table 1
Creates VRF.
* vtysh -c "conf" -c "vrf red"
Creates VRF NB node and marks VRF as configured.
* ip route 1.1.1.0/24 2.2.2.2 vrf red
* no ip route 1.1.1.0/24 2.2.2.2 vrf red
(or similar l3vni set/unset in zebra)
Marks VRF as NOT configured.
* ip link del red
VRF is deleted, because it is marked as not configured, but NB node
stays.
Subsequent attempt to configure something in the VRF leads to a crash
because of the stale pointer in NB layer.
Fixes #8357.

[7.5] *: modify VRF_CONFIGURED flag only in VRF NB layer

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
doc/user/bgp.rst

New and improved PR for the items covered in #8216.
The merge of #8216 caused compile failures in master branch because it introduced a new function (evpn_show_route_rd_all_macip) that called another function (route_vty_out_detail) which was modified by [4027d19b0](https://github.com/FRRouting/frr/commit/4027d19b0814c5b576fb35ca73158e215b2149b8) between successful CI run and merge of #8216.
This PR maintains the original changes but also addresses the route_vty_out_detail signature change.
One new commit is added to fix some new compilation failures when using KEEP_OLD_VPN_COMMANDS.

Add support for 'rd all' in EVPN and L3VPN commands

---

lib/prefix.c
lib/prefix.h
ripngd/ripng_peer.c
ripngd/ripngd.c

Remove the inet6_ntoa() api from lib/prefix.c - it used a static buffer, etc etc. Looks like it was only used in ripng...

lib, ripngd: Remove inet6_ntoa

---

ospfd/ospf_vty.c

ospfd: ignore duplicated "ip ospf area" commands

---

tools/etc/frr/daemons
tools/frrcommon.sh.in

Currently when compiling from source, the frrinit is not able to start pathd because it is missing in some example files. This patch adds pathd to the daemons example file, and adds it to the frrcommon DAEMONS list so frrwatch can start it. 
Signed-off-by: Erik Kooistra <me@erikkooistra.nl>

Added pathd to the init files

---

bgpd/bgp_vty.c
bgpd/bgpd.h
doc/user/bgp.rst
yang/frr-bgp-common.yang

increase the maximum number of neighbors in a bgp group.
Set the maximum value to 50000 instead of 5000.

bgpd: increase the maximum number of neighbors in a listen group

---

nhrpd/nhrp_cache.c
nhrpd/nhrp_interface.c
nhrpd/nhrp_nhs.c
nhrpd/nhrp_packet.c
nhrpd/nhrp_peer.c
nhrpd/nhrp_shortcut.c
nhrpd/nhrp_vty.c
nhrpd/nhrpd.h
nhrpd/zbuf.c
nhrpd/zbuf.h

This series of changes fixes a bunch of errors in handling NAT extensions, causing multiple problems. Especially when inter operating with Cisco routers, the previous code was very broken.
Now NAT handling is tested and working with any combination of:
- FRR as spoke or Hub
- Spoke-Spoke with either FRR or Cisco peer
- The FRR device and/or the other device behind NAT

nhrp: NAT fixes

---

tools/frr-reload.py

In frr-reload.py, avoid issuing a [no] command if we are then issuing the affirmative one. This avoids spurious requests for the default label ranges,
which might fail if something else is using those labels.

tools: do in-place SRGB/SRLB changes

---

zebra/debug.c
zebra/debug.h
zebra/zebra_mpls.c

When certain events occur (interface/connected route changes e.g.) zebra examines LSPs to see if they might have been affected. For LSPs with backup nhlfes, skip this immediate processing and wait for the owning protocol daemon to react. Also added a 'debug mpls detail' control.

zebra: don't process LSPs with backups immediately

---

ospfd/ospf_vty.c

[7.5] ospfd: ignore duplicated "ip ospf area" commands

---

tools/frr-reload.py

Problems reported that in certain cases, frr-reload.py would
delete vrf static routes inadvertantly due to two different
reasons. First, vrf statics with null0 or Null0 nexthops would
fail the match since rendered as blackholes.  This was already
fixed for non-vrf statics so added for vrf-based.  Second,
frr-reload would fail to match due to different formats for
adding the command. If entered in the old way
"ip route x.x.x.x/x y.y.y.y vrf NAME" and rendered
in the new sway "vrf NAME\nip route x.x.x.x/x y.y.y.y" it would
fail to match do an inadvertant delete.
Ticket: 2570270
(cherry picked from commit 00302a580c57fce0bb45d3fd6af9d4408a417ceb)

[7.5] tools: frr-reload fixes for deleting vrf static routes

---

nhrpd/nhrp_nhs.c
nhrpd/nhrp_peer.c

For some reason the usage of tabs in a string snuck in as well
as using a sockunion2str instead of %pSU.  Fix.

nhrpd: Fixup tab usage and sockunion2str usage

---

doc/user/zebra.rst

Add docs for the zebra debug commands (didn't seem to have been included in the zebra doc so far).

docs: add zebra debug docs

---

ospfd/ospf_vty.c

Allow over-write of message-digest-key interface config. Most attributes handle multi-instance by ... ignoring instances, and tolerating repeated config: do the same for md5 auth.
Fixes: #8387 #7943

ospfd: permit over-write of message-digest-key

---

tests/topotests/isis-topo1-vrf/r1/r1_topology.json
tests/topotests/isis-topo1-vrf/r2/r2_topology.json
tests/topotests/isis-topo1-vrf/r3/r3_topology.json
tests/topotests/isis-topo1-vrf/r4/r4_topology.json
tests/topotests/isis-topo1-vrf/r5/r5_topology.json
tests/topotests/isis-topo1-vrf/test_isis_topo1_vrf.py

Now the parse_topology function handles well the vertex type identifier.
Signed-off-by: Emanuele Altomare <emanuele@common-net.org>

topotests: fix 'parse_topology' function in test_isis_topo1_vrf.py

---

lib/nexthop.c

Use the correct number of octets in the comparison of nexthops' label stacks.

[7.5] lib: Fix label-stack comparison for nexthops

---

bgpd/bgp_evpn_mh.c
nhrpd/nhrp_main.c

Clean up a couple of SA warnings in the 7.5 branch.

[7.5] bgpd, nhrpd: fix clang static analysis warnings

---

bgpd/bgp_network.c
bgpd/bgp_zebra.c
tests/topotests/bgp_vrf_ipv6_link_local/r1/bgpd.conf
tests/topotests/bgp_vrf_ipv6_link_local/r1/zebra.conf
tests/topotests/bgp_vrf_ipv6_link_local/r2/bgpd.conf
tests/topotests/bgp_vrf_ipv6_link_local/r2/zebra.conf
tests/topotests/bgp_vrf_ipv6_link_local/test_bgp_vrf_ipv6_ll_func.py

Description:
BGP session not established for ipv6 link local address with vrf config
Problem Description/Summary :
BGP session not established for ipv6 link local address with vrf configyy
1.Configure ipv6 link-local address fe80::1234/64 on dut1 and fe80::4567/64 on dut2
2.Configure BGP neighbors for ipv6 link-local on both dut1 and dut2
3.Verify BGP session is UP over link-local ipv6 address
4.Observed that bgp session not established for ipv6 link local address
Expected Behavior :
BGP session should be established for ipv6 link local address with vrf config
Signed-off-by: sudhanshukumar22 <sudhanshu.kumar@broadcom.com>

bgpd: BGP session not established for ipv6 link local address with vrf config

---

tests/topotests/bgp_evpn_rt5/test_bgp_evpn.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/customize.py
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
tests/topotests/bgp_vrf_lite_ipv6_rtadv/test_bgp_vrf_lite_ipv6_rtadv.py
tests/topotests/isis-topo1-vrf/test_isis_topo1_vrf.py
tests/topotests/lib/common_config.py
tests/topotests/lib/topotest.py

This PR fixes Issue  [#8395](https://github.com/FRRouting/frr/issues/8395) and should also be merged in 7.5 / 7.5.1

tests: fix for l3mdev topotests on kernel 4.19

---

bgpd/bgp_evpn_vty.c

Current behavior has an EVPN_ENABLED check for both standard and 'no'
forms of 'advertise-svi-ip' and 'advertise-default-gw'. This prevents a
user from removing either command from running config if
'advertise-all-vni' is not present.
This commit removes/adjusts the EVPN_ENABLED checks to always allow the
'no' command so config doesn't get stuck.
Before:
```
ub20(config)# router bgp 1
ub20(config-router)# add l2 e  
ub20(config-router-af)# advertise-all-vni 
ub20(config-router-af)# advertise-svi-ip 
ub20(config-router-af)# advertise-default-gw 
ub20(config-router-af)# do sh run
Building configuration... 
!                   
frr version 7.7-dev
hostname ub20
log file /var/log/frr/frr.log …
```

bgpd: always allow no advertise-svi-ip/default-gw

---

pathd/path_pcep.h
pceplib/pcep.h
pceplib/pcep_pcc.c
pceplib/pcep_session_logic.h
pceplib/pcep_socket_comm.h

Use a pcep-specific value for MD5SIG_MAXLEN, using the OS value if present. #8355 reported some issues using the raw OS value when cross-compiling.

lib: use platform-neutral value for TCP MD5 signature len

---

ospfd/ospf_interface.c

Fixes #8423 .
Summary
---
The interface parameters deletion must be called before
`route_table_finish` due to the usage of the route data structures to
search neighbors in the same interface. If the route info is removed
before that we get the following crash:
```
6  0x00007f5c6ed50394 in core_handler at lib/sigevent.c:255
7  <signal handler called>
8  ospf_interface_bfd_apply (ifp=<optimized out>) at ospfd/ospf_bfd.c:130
9  0x000055d4c306d076 in ospf_interface_disable_bfd at ospfd/ospf_bfd.c:159
10 0x000055d4c3071781 in ospf_del_if_params at ospfd/ospf_interface.c:553
11 0x000055d4c3071900 in ospf_if_delete_hook at ospfd/ospf_interface.c:704
12 0x00007f5c6ed17935 in hook_call_if_del at lib/if.c:59
13 if_delete_retain at lib/if.c:290
14 0x00007f5c6ed19bc5 in if_delete at lib/if.c:313
15 …
```

ospfd: fix crash on interface/vrf removal

---

doc/user/bgp.rst

The keepalive, hold, and connect timers were undocumented.
Fixes: #7339

doc: document BGP neighbor timers

---

doc/developer/workflow.rst

Update workflow.rst to state that commit messages consisting solely of
program output, or that otherwise fail to adequately summarize the
changes being made, are unacceptable.

doc: describe acceptable commit messages

---

lib/elf_py.c
pathd/subdir.am
pceplib/pcep_msg_tlvs_encoding.c
pceplib/test/pcep_msg_tlvs_test.c
python/clippy/elf.py

- some ARM 32bit ABIs use DT_REL, which the elf_py code in clippy previously just ignored
- a bug in the python code used the buildhost's pointer size rather than the target's, breaking crosscompile of 32-bit targets on 64-bit hosts
Fixes: #8355

fix xrelfo on ARM(32) & cross-compile

---

lib/filter_cli.c

The correct string representation for "empty" type is an empty string.

[7.5] lib: fix check for duplicated access-list entries

---

bgpd/bgp_vty.c

Calling nb_cli_pending_commit_check only makes sense after nb_cli_apply_changes.

bgpd: fix pending commit check

---

bfdd/bfdd_cli.c

The idea of the "with-defaults" flag is to show the default values for
parameters that were not configured by the user. But bfdd incorrectly
shows the default values for all parameters, including the
user-configured ones.

bfdd: fix nb cli show with defaults

---

doc/user/basic.rst
lib/command.c
vtysh/vtysh.c

Lost ability to handle them in the regex patch

lib, vtysh: re-add support for spaces in 'find'

---

ospfd/ospf_vty.c

When you set OSPF hello-interval for an interface and dead-interval is
not set for this interface, dead-interval will be calculated and set
automatically. "show running-config" will contain an invalid command:
test(config)# interface vpp1
test(config-if)# ip ospf area 0
test(config-if)# ip ospf hello-interval 1
test(config-if)# exit
test(config)#
test(config)# do show running-config
...
interface if1
ip ospf area 0
ip ospf dead-interval minimal hello-multiplier 0
ip ospf hello-interval 1
!
...
It causes frr-reload.py to fail because of this:
line 9: % Unknown command:  ip ospf dead-interval minimal hello-multiplier 0
...
With this change, output "ip ospf dead-interval" only if it has value
configured explicitly.

ospfd: fix output of dead-interval in show running

---

lib/if.c
zebra/if_netlink.c

The first change in this commit is the processing of the VRF termination.
When we terminate the VRF, we should not delete the underlying interfaces,
because there may be pointers to them in the northbound configuration. We
should move them to the default VRF instead.
Because of the first change, the VRF interface itself is also not deleted
when deleting the VRF. It should be handled in netlink_link_change. This
is done by the second change.

lib: fix interface nb stale pointers

---

lib/if.c
zebra/if_netlink.c

The first change in this commit is the processing of the VRF termination.
When we terminate the VRF, we should not delete the underlying interfaces,
because there may be pointers to them in the northbound configuration. We
should move them to the default VRF instead.
Because of the first change, the VRF interface itself is also not deleted
when deleting the VRF. It should be handled in netlink_link_change. This
is done by the second change.

[7.5] lib: fix interface nb stale pointers

---

bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_updgrp_adv.c
bgpd/bgp_vpn.c
doc/user/bgp.rst

The idea is to find out prefixes including specific BGP table version and
above.
I want to look at what new prefixes arrived with a specific BGP table version.
It's kinda useful in some cases like finding out hijacks ad-hoc or so. 
I used this command suddenly last week with Cisco devices and it was handy.

bgpd: Add `show bgp version <version>` command

---

lib/filter.c
lib/filter.h
lib/filter_cli.c
lib/filter_nb.c

```
lib: fix check for duplicated access-list entries
The correct string representation for "empty" type is an empty string.
```
```
lib: fix usage of operational data in CLI
CLI must never use operational data, because this won't work in
transactional mode. Rework search for prefix-list/access-list entries
using only candidate config.
```
```
lib: fix deletion of empty prefix-lists
We delete the prefix-list when its last entry is deleted, but the check
is missed when we delete the description.
```
```
lib: delete empty access-lists
We should delete the access-list when the last entry and remark is
deleted. This is already done for prefix-lists.
```

various acl/plist cli fixes

---

doc/user/nhrpd.rst
doc/user/ospfd.rst
nhrpd/linux.c
nhrpd/netlink.h
nhrpd/nhrp_interface.c
nhrpd/nhrp_multicast.c
nhrpd/nhrp_peer.c
nhrpd/nhrp_vty.c
nhrpd/nhrpd.h
nhrpd/os.h
nhrpd/subdir.am
ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_lsa.c
ospfd/ospf_packet.c
ospfd/ospf_spf.c
ospfd/ospf_vty.c
ospfd/ospfd.c

This pull requests adds nhrp multicast support, and enables the use of OSPF within a DMVPN network.

nhrp, ospf: add nhrp multicast for OSPF DMVPN

---

bgpd/bgp_route.c
bgpd/bgp_route.h
doc/user/bgp.rst
tests/topotests/all-protocol-startup/r1/show_bgp_ipv4-post4.1.ref
tests/topotests/all-protocol-startup/r1/show_bgp_ipv4-post5.0.ref
tests/topotests/all-protocol-startup/r1/show_bgp_ipv4-post6.1.ref
tests/topotests/all-protocol-startup/r1/show_bgp_ipv6-post4.1.ref
tests/topotests/all-protocol-startup/r1/show_bgp_ipv6_post6.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post6.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post6.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post6.1.ref

Just to be more informant, copying from Cisco.
```
exit1-debian-9# sh ip bgp
BGP table version is 4, local router ID is 192.168.100.1, vrf id 0
Default local pref 100, local AS 65534
N*> 10.0.2.0/24      0.0.0.0                  0         32768 ?
N*> 192.168.0.0/24   0.0.0.0                  0         32768 ?
N*> 192.168.10.0/24  0.0.0.0                  0         32768 ?
N*> 192.168.100.1/32 0.0.0.0                  0         32768 ?
Displayed …
```

bgpd: Show RPKI short state in `show bgp <afi> <safi>`

---

bgpd/bgp_route.c
bgpd/bgp_route.h
doc/user/bgp.rst

Print detailed version for JSON output when dumping ALL BGP table with
`show bgp <afi> <safi> json detail`.
This output should be at some sort of identical to show_ip_bgp_route_cmd.
To avoid breaking backward-compatibility for `show bgp json`, adding
'detail' keyword for that.
In long-term it's easier for operators to compare stuff just looking at global
view instead of per-prefix for details.
Before:
```
],"192.168.100.1/32": [
{
"valid":true,
"bestpath":true,
"selectionReason":"First path received",
"pathFrom":"external",
"prefix":"192.168.100.1",
"prefixLen":32,
"network":"192.168.100.1\/32",
"metric":0,
"weight":32768,
"peerId":"(unspec)",
"path":"",
"origin":"incomplete",
"nexthops":[
{
"ip":"0.0.0.0",
"hostname":"exit1-debian-9",
"afi":"ipv4",
"used":true
}
]
}
] }  }
```
After:
``` …
```

bgpd: Add `show bgp json detail` command

---

doc/user/filter.rst
lib/plist.c

Before the transition of prefix-lists to northbound, this setting
controlled whether sequence numbers were displayed in the config.
After the transition, sequence numbers are always displayed in the
configuration, and this command only controls the output of the show
commands, which is not very useful. This command is not even shown in
the config anymore.

lib: remove "ip prefix-list sequence-number" command

---

doc/manpages/vtysh.rst
vtysh/vtysh_main.c

It's sometimes needed to disable logging all FRR commands at all.
Fixes: https://github.com/FRRouting/frr/issues/8400

vtysh: Set history file on demand

---

.travis.yml
doc/developer/building-docker.rst
docker/ubuntu18-ci/Dockerfile
docker/ubuntu18-ci/README.md
docker/ubuntu18-ci/docker-start
docker/ubuntu20-ci/Dockerfile
docker/ubuntu20-ci/README.md
docker/ubuntu20-ci/docker-start

Ubuntu containers can also be used for dev/test - including reproducing issues found in CI
The hope is that this minimalist  / pr0of-of-concept CI usage will be expanded upon. E.g.,  publishing containers on a successful CI run for master, more sophisticated testing, etc....

Enable basic travis CI using new Ubuntu docker containers 

---

nhrpd/linux.c

Ensure we don't try to use an invalid fd in nhrpd; reported by coverity.

nhrpd: fix coverity warning about os_socket()

---

bgpd/bgp_evpn_mh.c

Avoid overrunning the fixed-size array of nexthops in a zapi_nhg.

bgpd: don't overrun fixed zapi array of nexthops

---

lib/filter.c
lib/filter_nb.c

Problems with the current implementation:
* Delete hook is called before the deletion of the access-list from the
master list, which means that daemons processing this hook successfully
find this access-list, store a pointer to it in their structures, and
right after that the access-list is freed. Daemons end up having stale
pointer to the freed structure.
* Route-maps are not notified of the deletion.
This commit fixes both issues.

lib: fix access-list deletion

---

tests/topotests/lib/bgp.py

There are better ways of ensuring that the remote side
has your change instead of sleeping

tests: Do not sleep(5) when verifying bgp communities

---

lib/filter.c
lib/filter_nb.c

Problems with the current implementation:
* Delete hook is called before the deletion of the access-list from the
master list, which means that daemons processing this hook successfully
find this access-list, store a pointer to it in their structures, and
right after that the access-list is freed. Daemons end up having stale
pointer to the freed structure.
* Route-maps are not notified of the deletion.
This commit fixes both issues.

[7.5] lib: fix access-list deletion

---

bgpd/bgp_io.c

Compiler warns about uninitialized value, although in practice it is
unreachable.
Also updates a function comment explaining what that value does.

bgpd: fix uninit value when handling bgp read errs

---

alpine/APKBUILD.in
docker/alpine/Dockerfile

Several issues:
1. `libelf-dev` dependency was not added to `APKBUILD.in` for Alpine packaging
2. Our Alpine base image was using the `latest` tag, which is unstable and not appropriate for us
3. Once `libelf-dev` is added, our FRR Alpine images no longer build because `libelf-dev` hasn't been available in Alpine since 3.9; work around this by adding 3.9 Alpine repository to the 3.13 base image before building FRR
Fixes: #8489

Fix several Alpine build issues related to ELF parsing

---

ospf6d/ospf6_top.c

When oi->area == NULL, it tries to print the
interface's area name, but no area is present.
Print the area name from the command argument instead.

ospf6d: Fix coredump when "no interface IFNAME area <A.B.C.D>" is called

---

lib/sigevent.c
lib/zlog.c

Funny as it may be, calling `abort()` in the `SIGSEGV` handler has the side effect that `abort()` also prints a second backtrace for the resulting `SIGABRT`.  And when it doesn't make it to "funny", it'll be confusing at best :confounded: ...
While at it, also make sure we generate coredumps & avoid printing a bogus "failed to unlinkat() log buffer" error when we never even created one to begin with.
For posterity, this what it looked like before:
```
frr $ tests/lib/test_segv
Received signal 11 at 1618802713 (si_addr 0x0, PC 0x55e6f97121dd); aborting...
zlog_signal+0x18c                  7ff6d0c1a2ad     7ffe50e570d0 /home/equinox/c/frr/lib/.libs/libfrr.so.0 (mapped at 0x7ff6d0b7b000)
core_handler+0xc7                  7ff6d0c55b7a     7ffe50e571f0 …
```

lib: 640k backtraces should be enough for everybody

---

bgpd/bgp_route.c

Absolutetly cosmetic change, but let it be consistent with other checks
for optional attributes.

bgpd: Check for flag existense for community instead of `if not NULL`

---

bgpd/bgp_fsm.c
bgpd/bgp_fsm.h
bgpd/bgp_network.c
bgpd/bgp_nht.c
bgpd/bgp_nht.h

The new LL code in:
8761cd6ddb5437767625f58c8e9cc3ccda7887ab
Introduced the idea of the bgp unnumbered peers using interface up/down
events to track the bgp peers nexthop.  This code was not properly
working when a connection was received from a peer in some circumstances.
Effectively the connection from a peer was immediately skipping state transitions
and FRR was never properly tracking the peers nexthop.  When we receive the
connection attempt, let's track the nexthop now.

bgpd: Address LL peer not NHT when receiving connection attempt

---

ospfd/ospf_abr.c
ospfd/ospf_asbr.c
ospfd/ospf_asbr.h
ospfd/ospf_vty.c
ospfd/ospfd.c
ospfd/ospfd.h

Currently, if NSSA area is configured before redistribution is enabled,
Type-7 LSA's are installed and flooded. But if NSSA area is configured
after redistribution is enabled, Type-7 LSA's are not installed.
With this change, when NSSA area is configured, schedule a task that
scans for external LSA's. If they exist, install Type-7 and flood to
all NSSA Areas.
There already was an attempt to fix this problem in 0f321812f where
`ospf_asbr_nssa_redist_task()` was triggered in `ospf_abr_task_timer()`.
This turns out to be incorrect place for this operation because it's
a one-off operation needed only after "area <ID> nssa" execution. And
`ospf_abr_task_timer()` is a periodic operation. Triggering
`ospf_asbr_nssa_redist_task()` in `ospf_abr_task_timer()` caused a problem
that was fixed in …

ospfd: install Type-7 when NSSA area is configured after redistribution

---

bgpd/bgp_ecommunity.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_nb_config.c
bgpd/bgp_zebra.c
bgpd/bgpd.c
bgpd/bgpd.h
zebra/redistribute.c

Description:
Change is intended for fixing the following issues related to vrf route leaking:
1. FRR doesn't re-install the routes, imported from a tenant VRF,
when bgp instance for source vrf is deleted and re-added again.
When bgp instance is removed and re-added, when import statement is already there,
then route leaking stops between two VRFs.
2. Imported/leak-from routes do not get withdrawn/removed even if the source VRF is deleted.
Deleting and re-adding a tenant vrf, does not refresh the RIB.
3. After FRR restart, routes are not getting redistributed;
when routes added first and then 'redistribute static' cmd is issued.
4. While withdrawal of exported routes is in-progress, routes are marked as being removed and invalid.
In the mean time, if router bgp config is updated, which …

bgpd: vrf route leaking related fixes

---

docker/alpine/Dockerfile
docker/centos-7/Dockerfile
docker/centos-8/Dockerfile
docker/debian/Dockerfile
docker/debian/docker-start
docker/ubuntu18-ci/Dockerfile
docker/ubuntu20-ci/Dockerfile

Specifying watchfrr in Dockerfiles as CMD instead of ENTRYPOINT allows one to easily override the watchfrr command when starting a docker container. This allows simple, manual testing via (e.g.) bash. With ENTRYPOINT only the container will simply explode with an exit code if watchfrr exits.
If you tried to do this before you'd see this from `docker ps`:
```
COMMAND
"/sbin/tini -- /usr/lib/frr/docker-start bash"
```
Which shows that /usr/lib/frr/docker-start (a wrapper around frrinit.sh) tried to start frrinit.sh with the `bash` parameter which clearly won't do anything. Now, one could start a shell session in this container via:
```
docker run --name test --rm -i -t <frr-container> bash
```
The default behavior (`docker run <frr-container>` with no command specified) is not changed.

docker: prefer CMD to ENTRYPOINT for flexibility

---

ospf6d/ospf6_top.c

Issue: When maximum-path is configured in ospf6 view, the
function ospf6_restart_spf deletes the external table as well
which is not required since that stores the redistribute routes.

ospf6d: Do not delete external table when configure max-path

---

pimd/pim_nb_config.c

Fix:
dev(config)# ip pim register-suppress-time 70
dev(config)# do show running-config 
Building configuration...
!
frr version 7.7-dev-MyOwnFRRVersion
hostname dev
log syslog informational
ip pim register-suppress-time 70
ip pim rp keep-alive-timer 185
!
line vty
!
end
dev(config)# no ip pim register-suppress-time 70
dev(config)# do show running-config 
Building configuration...
!
frr version 7.7-dev-MyOwnFRRVersion
hostname dev
log syslog informational
!
line vty
!
end
dev(config)# 

pimd: fix crash pim register-suppress-time command

---

bgpd/bgp_bfd.c
lib/bfd.c
lib/bfd.h
ospfd/ospf_bfd.c

Currently this flag is only helpful in an extremely rare situation when
the BFD session registration was unsuccessful and after that zebra is
restarted. Let's remove this flag to simplify the API. If we ever want
to solve the problem of unsuccessful registration/deregistration, this
can be done using internal flags, without API modification.
Also add the error log to help user understand why the BFD session is
not working.

lib: remove enabled flag for bfd sessions

---

bgpd/bgp_nht.c

the code processing an NHT update was only resetting the BGP_NEXTHOP_VALID flag, so labeled nexthops were considered valid even if there was no nexthop. Reset the flag in response to the update, and also make the `isvalid_nexthop` functions a little more robust by checking the number of nexthops.

bgpd: fix invalid labeled nexthop check

---

tests/topotests/bfd-bgp-cbit-topo3/r1/peers_down.json

This test is completely incorrect on test_bfd_loss_intermediate step.
It shuts down the interface and then "waiting" for the BGP session to
fail. But instead of the actual wait it compares the output of "show bfd
peers" with the "up" state. As it does this comparison right after the
interface shutdown, the BFD session has not yet failed and the comparison
is always successful except very rare cases when the command takes a lot
of time to execute (due to the heavy load on CI system I suppose).

tests: fix bfd-bgp-cbit-topo3 test

---

tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1.py
tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2.py
tests/topotests/bgp_multi_vrf_topo1/test_bgp_multi_vrf_topo1.py
tests/topotests/bgp_multi_vrf_topo2/test_bgp_multi_vrf_topo2.py
tests/topotests/bgp_recursive_route_ebgp_multi_hop/test_bgp_recursive_route_ebgp_multi_hop.py
tests/topotests/lib/common_config.py

This function kills all processes that happen to have the same
name to frr processes and it was only ever used in the setup.
Setup should not be used to kill old runs.  That should be a
separate process.

tests: Remove kill_mininet_router_process

---

ldpd/lde.c
ldpd/ldpe.c
lib/frr_pthread.c
lib/libfrr.c
lib/libfrr.h
lib/northbound_sysrepo.c
pathd/path_pcep.c

Threads created before we fork() for `-d` are running in the parent & will exit with that.  Which is very much not what's needed.
Shuffle around hooks a bit so we have something *after* fork but *before* config load.  Also make the frr_pthread code refuse to create threads before forking.

lib, pathd PCEP: creating threads before forking does _not_ work

---

zebra/zebra_nhg.c
zebra/zebra_nhg.h
zebra/zebra_vty.c

@donaldsharp reported a zebra crash loop during topotest runs. It was caused by graceful restart and retain being turned on while using sharpd to install proto-owned NHGs. We were incorrectly handling the refcnts for proto-owned NHGs we find in the kernel on restart so when we get an update for that ID later, we fail in an assert() we put in to make sure we haven't screwed up the refcnts. 
This PR also includes some QOL patches with including uptime on the NHGs like we do for routes and adding a macro for code read-ability.
The crash:
```
ZEBRA: __assert_fail+0x42                 7f670d43a662     7ffdfc30cf10 /lib/x86_64-linux-gnu/libc.so.6 (mapped at 0x7f670d406000)
ZEBRA: zebra_nhg_proto_add+0x349          55a643e945ca     7ffdfc30cf40 /usr/lib/frr/zebra (mapped at 0x55a643dc0000) …
```

zebra: Proto-NHG Fix Graceful-Restart-Retain Crash Loop

---

bgpd/bgp_fsm.c

If we have a situation where BGP is partially reading in a config
file for a neighbor, *and* the neighbor is coming up *and* we
have a doppelganger.  There exists a race condition when we transfer
the config from the doppelganger to the config peer that we will
overwrite later config because we are copying the config data
from the doppelganger peer( which was captured at the start of initiation
of the peering ).
From what I can tell the peer->af_flags variable is to hold configuration
flags for the local peer.  The doppelganger should never overwrite this.

bgpd: prevent doppelganger overwrite of subsuquently configured cli

---

eigrpd/eigrp_hello.c

Check that incoming TLVS a) don't overrun the incoming packet, b) don't underrun the required size for the type of TLV.
Fixes #8542

eigrpd: validate TLV lengths

---

zebra/zebra_rib.c

Include nexthops' labels in an important debug early in route processing - it's useful to see labels (if they're present).

zebra: include nexthops' label stacks in zebra rib debug

---

ldpd/ldp_vty_conf.c
ldpd/ldp_zebra.c
ldpd/ldpd.h
zebra/redistribute.c

Instead of registering to receive default-VRF information and routes when first connected to zebra, defer the registration until some ldp configuration is entered. This avoids redistributing IPv4/IPv6 routes to ldpd if it's not needed.
Also add a zebra debug event message when calling zebra_redistribute_delete, same as we do for the add case.

ldpd: defer register for info until configured

---

bgpd/bgp_evpn.c
bgpd/bgp_nb_config.c
bgpd/bgpd.c
bgpd/bgpd.h

There are multiple problems:
- commit ef7c53e2 introduced a new return value 2 which broke things,
because a lot of code treats non-zero return as an error,
- there is an incorrect error returned when AS number mismatches.
This commit fixes both.

bgpd: fix bgp_get_vty return values

---

lib/zclient.h
zebra/rib.h
zebra/zapi_msg.c
zebra/zebra_nhg.c
zebra/zebra_nhg.h
zebra/zebra_rib.c

Daemon-sourced nexthop-group changes were being done directly from the zapi message-handlers. Extend the zebra workqueue/meta-queues to allow these NHG changes to be done from the workqueue instead.

lib, zebra: use zebra workqueue for NHG updates

---

configure.ac

The pthread_* checks for extra pthread features really need
PTHREAD_CFLAGS...
---
oops.  this causes bgpd to chug 100% CPU, because pthread_condattr_setclock is no-op'd away, and then it uses a CLOCK_MONOTONIC timestamp against CLOCK_REALTIME ...

build: fix pthread CFLAGS for function checks

---

ospf6d/ospf6_top.c

this command summarises the ospf6 instances along with the router-id and
the vrf_id associated.
this is like what has been done for 'show ip ospf vrfs' command.

ospf6d: add 'show ipv6 ospf6 vrfs' command

---

zebra/zebra_mpls.c
zebra/zebra_nhg.c

A few fixups for processing backups for recursive nexthops, labels in backup nexthops. Also handle TE policy changes in LSP notifications, to align with the LSP result-handling code.

zebra: Misc fixups for backup nexthops

---

bgpd/bgp_filter.c
ldpd/ldp_zebra.c
ldpd/ldpd.h
lib/filter.c
lib/filter.h
lib/plist.c
lib/plist_int.h

A long time ago there was a difference between number-named and string-named
access/prefix-lists. Currently, we always treat the name as a string and
there is no need for a separate list for number-named lists.

*: cleanup number-named access-lists and prefix-lists

---

tests/topotests/lib/topotest.py

The current log prints maximum wait time which is not actually correct,
because it doesn't include the command execution time. We usually have
"failed after X seconds" log with X being far longer than this maximum.
Let's print the maximum number of tries instead.

tests: fix topotest polling log

---

tests/topotests/conftest.py
tests/topotests/lib/pim.py

* provide sane default for `--topology-only`; under some circumstances not using this option provoked a crash
* ~start fixing bad python 2 compat code; there are [correct ways](http://python-future.org/compatible_idioms.html) to handle cross compatibility between Python 2 and 3, using `if version == 2 ...` is typically wrong~
* remove doubly defined function in `lib/pim.py`
* fix format strings with no arguments in `lib/pim.py`
* fix format strings with too many arguments in `lib/pim.py`
* fix use of undefined variable in `lib/pim.py`

Assorted topotests cleanup

---

doc/developer/building-frr-for-openbsd6.rst

Also update info about new packages needed as libcares.

doc: clang in openbsd is the default and update compiler.

---

lib/printfrr.h

FMT_NSTD_BEGIN should be before the first use of "expr".

tests: fix build warning

---

lib/routemap_northbound.c

Description:
This looks broken after NB changes in routemap. When routemap
action modified from permit to deny, it is expected to apply
the new action on the filtered routes before the action in the
routemap data structure has been changed. But currently this is
not handled by the corresponding northbound API.
Issue: #8000

lib: Routemap is not getting applied upon changing the routemap action

---

zebra/debug.c

a) `debug zebra kernel` turns off `debug zebra kernel msgdump....`
this is odd and bad
b) `debug zebra kernel msgdump send` turns off receive and vice versa
this is counter intuitive as well
c) `no zebra kernel msgdump ...` turns off all kernel level debugging
we should only turn off msgdump specific debugs
d) `no debug zebra kernel` turns off all kernel level debugging
we should leave msgdump on.
e) Fix `show run` and show debug output

zebra: msgdump debug strangeness cleanup

---

sharpd/sharp_vty.c

The "remove lsp" command to sharpd was using the wrong list of route protocols - use the ZEBRA list, same as the other sharpd clis. That includes sharpd itself, so you can label and un-label sharpd routes.

sharpd: use correct list of redist protocols in remove lsp

---

ospfd/ospf_asbr.c

Description:
All matching external routes are added to matching external hash table
of aggregate route when aggregation is enabled.
But these external info pointers are not delinked from this hash table
before freeing the corresponding memory  while disabling redistribution.
Addressing these memory issues in this change.
Valgrind issues : 
=73472== Invalid read of size 4
==73472==    at 0x48E87FF: prefix_same (prefix.c:367)
==73472==    by 0x1C5C30: ospf_external_rt_hash_cmp (ospf_asbr.c:371)
==73472==    by 0x48C2319: hash_get (hash.c:157)
==73472==    by 0x1C6BAE: ospf_link_ei_to_aggr (ospf_asbr.c:572)
==73472==    by 0x1C6BAE: ospf_originate_summary_lsa (ospf_asbr.c:602)
==73472==    by 0x1B76D0: ospf_zebra_read_route (ospf_zebra.c:1294)
==73472==    by 0x491DFF8: zclient_read …

ospfd: Fixing few valgrind issues

---

ospfd/ospf_vty.c
tests/topotests/all-protocol-startup/r1/show_ip_ospf_interface.ref

Description:
DR information is missing under "show ip ospf interface [json]".
Added DR infomation to display in "show ip ospf interface".

ospfd: show ip ospf interface displays only BDR info, Added DR info.

---

ospfd/ospf_te.c

This fixes 2 asan errors:
If we only have a TLV_ROUTER_ADDR don't continue after we skipped it.
Fixed length when parsing EXT_TLV_LINK_SIZE.
Signed-off-by: Erik Kooistra <me@erikkooistra.nl>

ospfd: Fixed some ASAN errors

---

doc/user/isisd.rst
isisd/isis_circuit.c
isisd/isis_circuit.h
isisd/isis_cli.c
isisd/isis_csm.c
isisd/isis_ldp_sync.c
isisd/isis_ldp_sync.h
isisd/isis_nb.c
isisd/isis_nb.h
isisd/isis_nb_config.c
isisd/isis_snmp.c
isisd/isis_vty_fabricd.c
isisd/isis_zebra.c
isisd/isisd.c
isisd/isisd.h
tests/isisd/test_isis_spf.c
tests/topotests/isis-snmp/test_isis_snmp.py
tests/topotests/isis-sr-topo1/test_isis_sr_topo1.py
tests/topotests/ldp-sync-isis-topo1/r3/show_isis_ldp_sync.ref
tests/topotests/ldp-sync-isis-topo1/r3/show_isis_ldp_sync_r1_eth1_shutdown.ref
tests/topotests/ldp-sync-isis-topo1/r3/show_isis_ldp_sync_r2_eth1_shutdown.ref
yang/frr-isisd.yang

There are a lot of ISIS fixes in this PR. Main parts are:
1. Fix for circuit SNMP ID generation. Details in commit 58a339f.
2. Allow an arbitrary order of configuration - in particular allow an interface config to be created without an area config. This is necessary for the correct processing of interface moves between VRFs. Details in commit b525ceb.
3. Fix configuration of LDP-sync. The config is per-area but actually controls the whole VRF. Details in 936cdbd. Fixes #8578.
4. Fixes for CLI - it incorrectly uses the operational data instead of NB config nodes. Last 7 commits.

a lot of isis fixes

---

zebra/if_netlink.c
zebra/interface.c
zebra/interface.h

This crash can happen when updating macvlan interfaces status.
The link interface pointer is accessed, and it crashes because that link interface was null.
From FRR point of view, this update of macvlan interfaces is RTM_NEWLINK events.
This is either a new interface or an update of an interface ( eg iface goes up).
ZEBRA discovers interfaces on two ways:
(a)- at zebra startup, discover all interfaces, and once all read, refresh the link interface pointer.
(b)- during zebra life, receive incoming RTM_NEWLINK
There are cases where MACVLAN interfaces created by keepalived daemon may be created before zebra comes alive.
That means that (a) process takes place. That process happens look similar when it comes with vrflte backend.
However, the situation becomes nasty when it has to deal with …

zebra: prevent from crashing if link of macvlan interface not found

---

isisd/isis_lfa.c

When enabling TI-LFA the forward SPF for neighbors adjacent to the
PLR is computed. Later, when computing the PQ spaces, the reverse
SPF trees for those adjacent neighbors affected by the protected
interface are computed.
When node protection is enabled, TI-LFA link protection is run
immediately afterwards to compute repairs in case no
node-protecting backup path exists. In this second run, the
existing code tries to compute the reverse SPF tree for the same
node, without freeing the SPF tree of the prior run.
This patch fixes this by not computing the reverse SPF again, thus
avoiding a memory leak and an unnecessary SPF run.
Signed-off-by: Fredi Raspall <fredi@voltanet.io>

isisd: fix memory leak for non-freed spftrees

---

isisd/isisd.c

When enabling 'debug isis lfa', the option was correctly enabled
but not displayed by 'show debugging' command.
Signed-off-by: Fredi Raspall <fredi@voltanet.io>

isisd: fix show LFA debug in show debugging cmd

---

lib/thread.c

When an operator encounters a situation where the number
of FD's open is greater than what we have been configured
to legitimately handle via uname or the `--limit-fds` command
line, abort with a message that they should be able to
debug and figure out what is going on.
Fixes: #8596

lib: Provide some better error handling for operator

---

doc/user/basic.rst
lib/log_vty.c
lib/zlog.c
lib/zlog.h

The log module buffers outgoing messages by default; add an api to turn that off, and emit messages immediately. This can be useful when debugging, etc. I haven't proposed a cli control here, but that might be useful too?

libs: add api to enable immediate output of zlog

---

doc/user/isisd.rst

This PR aims to add documentation for the default metric-style used for IS-IS.

doc: isis: document default value for metric-style

---

zebra/interface.c

Initially the reading of the speed of an interface happened
upon interface creation and happened until the speed of a link
settled down to a single value.  The speed of an interface
can also change as that a new optic can be inserted that
changes the speed, in which case FRR would see a interface
down (optic removal) and then a interface up (optic insertion).
In this case FRR would not treat this as an event that changed
the speed.  Let's expand the checking a bit more.

zebra: Allow interface up events to read speed

---

configure.ac

Ensure that master is not built with libyang version 2 or greater
since we'll fail.
Fixes: #8524

build: Limit libyang version to under 2.0

---

doc/user/isisd.rst
isisd/isis_circuit.h
isisd/isis_cli.c
isisd/isis_lfa.c
isisd/isis_nb.c
isisd/isis_nb.h
isisd/isis_nb_config.c
yang/frr-isisd.yang

This is a small improvement to the TI-LFA implementation in IS-IS.
When TI-LFA node protection is enabled on an interface (the default is link protection), the current implementation computes node-protecting backups as well as link-protecting backups. The reason for this is that there may be cases where no node-protecting LFAs exist, but link-protecting. The ability to fall back to link protection when node protection is not feasible is something recommended in several normative documentation. However, the current implementation does not allow to disable such a behavior, which may not always be desired since link-protecting repair paths may use the protected node (hence being useless in case of node failure) and always computing link-protecting LFAs incurs additional overhead.
With this …

Pr tilfa link fallback

---

ldpd/lde.c
ldpd/lde.h
ldpd/ldp_vty.h
ldpd/ldp_vty_cmds.c
ldpd/ldp_vty_conf.c
ldpd/ldp_zebra.c
ldpd/ldpd.c
ldpd/ldpd.h

If LDP is miss configured in a setup and the router has LSPs with no remote
label, this code installs the LSP with a pop instruction of the top-level
label so the packet can be forwarded using IP.   This is a best-effort
attempt to deliver labeled IP packets to their final destination instead of
dropping them.    If this config is turned off the code will only install
LSPs that have a valid remote label.

ldpd: make allowing broken-lsps to be installed configurable

---

qpb/subdir.am

The .pb-c.c files pick up our assert() override, but that needs config.h
to be included too, and that needs to go at the very top of the file...
---
Oops :sweat_smile:

build: fix assert() use in .pb-c.c files

---

doc/developer/lists.rst
lib/linklist.c
lib/linklist.h
lib/typerb.h
lib/typesafe.h
pimd/pim_bsm.c
pimd/pim_bsm.h
pimd/pim_cmd.c
pimd/pim_rp.c
tests/lib/test_typelist.h
tests/topotests/Dockerfile

Been asked to look at candidate-rp support, so here's some cleanup before starting on that.
Includes 2 bonus `lib/` bits:
- add `bla_swap_all()` for the TYPESAFE bits to swap the contents of 2 containers
- remove `list_filter_out_nodes` from the old code which is unused after this
Also fix the topotests docker image :disappointed:

lib, pimd: move bsm code to typesafe lists

---

bgpd/bgp_pbr.c

bgpd: Prevent test against uninited data

---

eigrpd/eigrp_packet.c

When receiving a packet, ensure that the AS number is the same.
Fixes: 8515

eigrpd: Test for EIGRP AS number and ensure it's the same

---

ospf6d/ospf6_route.c

The output of "show ipv6 ospf6 route json" was not in the same
format as "show ip ospf route json". Currently ipv6 and ipv4 route
tables as well as ospfv2 have prefix as the key, but the same
is not true for ospfv3.
The structure of the json objects needs to be changed.
Currently the structure present is
```
frr(config-ospf6)# do show ipv6 ospf6 route json
{
"routes":[
{
"destination":"66:ff::\/64",
"isBestRoute":true,
"destinationType":"N",
"pathType":"IA",
"duration":"00:00:06",
"nextHops":[
{
"nextHop":"::",
"interfaceName":"ens256"
}
]
}
]
}
```
It is changed to:
```
frr(config-ospf6)# do show ipv6 ospf6 route json
{
"routes":{
"12::2\/128":{
"isBestRoute":true,
"destinationType":"N",
"pathType":"IA",
"duration":"00:01:22",
"nextHops":[
{
"nextHop":"::",
"interfaceName":"ens192"
}
]
} …
```

ospf6d: Change structure of "show ipv6 ospf6 route json" command

---

zebra/redistribute.c

Current code has an inconsistent behavior with redistribute routes.
Suppose you have a kernel route that is being read w/ a distance
of 255:
eva# show ip route kernel
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
K>* 0.0.0.0/0 [0/100] via 192.168.161.1, enp39s0, 00:06:39
K>* 4.4.4.4/32 [255/8192] via 192.168.161.1, enp39s0, 00:01:26
eva#
If you have redistribution already turned on for kernel routes
you will be notified of the 4.4.4.4/32 route.  If you turn
on kernel route redistribution watching after the 4.4.4.4/32 route
has been read by …

zebra: Allow redistribution for routes selected

---

bgpd/bgp_clist.c

frr(config)# bgp large-community-list expanded com1 permit .*
% Malformed community-list value
The check to validate large-community against UINT_MAX is added for
both standard and expanded community. But however it needs to be
validated only for standard community.
Signed-off-by: Prerana-GB <prerana@vmware.com>

bgpd: BGP large community-list configuration with regex is failing.

---

bgpd/bgp_vty.c

When we are cycling through all peers and looking for
dampening data to dump, do not consider non-configed
peers( dopplegangers ).

bgpd: Do not output peer doppleganger dampened output

---

babeld/babeld.c
doc/user/ripd.rst
doc/user/ripngd.rst
eigrpd/eigrp_main.c
eigrpd/eigrp_routemap.c
lib/distribute.c
lib/distribute.h
ripd/rip_cli.c
ripd/ripd.c
ripngd/ripng_cli.c
ripngd/ripngd.c
vtysh/extract.pl.in

see individual commits.  But effectively FRR's `distribute-list ...` commands are messed up a whole bunch.  Try to sort it out better.

Fix distribute

---

bgpd/bgp_vty.c

vtysh will return an informational message to the user that changing any
graceful-shutdown related parameter either globally or per-neighbor/peer-group
will emit a message. This message is only informational for the user and should
not create a return code of 1 which signals "error"!
This fixes GitHub issue https://github.com/FRRouting/frr/issues/8403

bgpd: changing graceful-restart parameters should not be considered as error

---

bgpd/bgp_evpn.c

When validating a MACIP route's IP address,
bgp_evpn_route_add_l3_ecomm_ok checked for a non link-local v6 address
without checking if the v6 address existed.  Since empty v6 addresses
do not fall into the fe80 range, MAC-Only routes were always passing
this check and getting IP-VRF extended communities (RMAC/IP-VRF RT)
added to the routes.
This commit requires ipaddr_v6 to exist AND fall outside of the
link-local range for IP-VRF ext-comms to be added.
Before:
--------
```
[4:14:32] root@ub18:~                     
[4:14:35] root@ub18:~                                                               
Hello, this is FRRouting (version 7.7-dev). …
```

bgpd: Fix IP-VRF ext-comm check for MACIP routes

---

bgpd/bgp_network.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst
lib/sockopt.c
lib/sockopt.h
tests/topotests/bgp_tcp_mss/r1/bgpd.conf
tests/topotests/bgp_tcp_mss/r1/zebra.conf
tests/topotests/bgp_tcp_mss/r2/bgpd.conf
tests/topotests/bgp_tcp_mss/r2/zebra.conf
tests/topotests/bgp_tcp_mss/test_bgp_tcp_mss.py

=================
In scale setup BGP sessions start flapping.
RCA:
====
In virtualized environment there are multiple places where
MTU need to be set. If there are some places were MTU is not set
properly then there is chances that BGP packets get fragmented,
in scale setup this will lead to BGP session flap.
Fix:
====
A new tcp option is provided as part of this implementation,
which can be configured per neighbor and helps to set the TCP
max segment size. User need to derive the path MTU between the BGP
neighbors and set that value as part of tcp-mss setting.
1. CLI Configuration:
[no] neighbor <A.B.C.D|X:X::X:X|WORD> tcp-mss (1-4096)
2. Running config
frr# show running-config
router bgp 100
neighbor 10.1.1.2 tcp-mss 150       => new entry
neighbor 2000::2 tcp-mss 400 …

bgpd: Support tcp-mss for bgp neighbors

---

bgpd/bgp_pbr.c

Prevent another call path that uses uninited data in
bgp_pbr.c
This was found through more clang sa runs.

bgpd: Another call path with uninited data

---

isisd/isis_snmp.c

fix a number of SA errors thrown up by the newer clang

isisd: fix clang-11 warnings in snmp code

---

lib/filter_cli.c
tools/frr-reload.py

1. When specifying prefix-list with "ge", any "le 32" (for v4) and "le 128" (for v6) instructions are essentially NOP so ignore them.
2. When specifying only an "le" for an existing ip prefix-list qualified with both an "le" and "ge" make sure to remove the "ge" property so it does not stay in the tree.
(1) was previously implemented in frr-reload and I figured its logic is better suited for the daemon itself. This settles a discrepency between what reload was producing and what FRR accepted for the same input.
The below commands are functionally the same so FRR now strips the "le 32" for v4 and "le 128" for v6 as if you never said it at all:
```
ip prefix-list test seq 1 permit 1.1.0.0/16 ge 18 le 32
ip prefix-list test seq 1 permit 1.1.0.0/16 ge 18
```
(2) Fix a bug in "ge" and "le" …

lib: ip prefix-list "le" and "ge" bug squish

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_abr.h
ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6_flood.c
ospf6d/ospf6_intra.c
ospf6d/ospf6d.c

When an "export-list" or "filter-list out" was configured on an area the
filter was not applied to existing database.    The user would either have
to restart the neighboring router in the other area or issue a "clear ipv6
ospf6 interface" to cause the neighbor router to resend it's LSAs.   The
new filter would then be applied to these LSAs and permit or deny summary
LSAs from being added/removed from the database.  The code now applies the
filters to the existing database without user needing to take any action
to clear ospfv3 adjacencies.
The second part of the problem was if a rule changed the updated filter was
not reapplied.  The code has been modified to now process the rule update and
reapply the filter.

ospf6d: Fix when an "export-list" or "filter-list out" is configured

---

ospfd/ospf_vty.c
ospfd/ospf_zebra.c
ospfd/ospf_zebra.h
ospfd/ospfd.c

```
ospfd: deregister vrf from zebra when vrf is disabled
Currently the VRF is deregistered only when it is re-enabled again.
```
```
ospfd: fix redistribution config when vrf doesn't exist
Currently ospfd relies on vrf bitmaps in zclient to check that the
redistribution is configured. This doesn't work when the VRF for OSPF
instance doesn't exist yet, because vrf bitmaps ignore VRF_UNKNOWN id.
Because of this, the following problems occur when the VRF doesn't exist:
- repeated "redistribute smth" command is processed as a first-time
instead of an update
- "no redistribute smth" doesn't work at all
This commit fixes both issues by relying on internal redistribution
config instead of zclient vrf bitmaps.
```

ospf redistribution fixes

---

tools/valgrind.supp

When running valgrind there are some possible memory leaks.
These memory leaks we have absolutely no control over, mark
them as not worthy of being reported.
Finally move the valgrind suppressions file from bgpd/ to tools/
this is because this suppressions file can be used beyond bgpd

tools: Add some more data to ignore for valgrind

---

tests/topotests/bgp-auth/test_bgp_auth.py

There is a rare case where with prefix peers the peer is
completely absent from the json output when checking the
peer state resulting in a python key error. Check key exists
before checking the state.

tests: fix intermittent key error in bgp-auth topotest

---

lib/nexthop.c
lib/nexthop.h
tests/lib/test_nexthop.c
tests/lib/test_nexthop.py
tests/subdir.am

Add a simpler, more limited nexthop comparison function: this compares a few key attributes, such as vrf, gateway, labels. The existing nexthop_cmp() function has evolved to be very thorough and very precise, but we may be missing duplicates. I've also added a unit-test module that exercises the basic comparison api.

lib, tests: add basic nexthop comparison api and unit-test

---

pimd/pim_cmd.c
pimd/pim_nb_config.c
pimd/pim_upstream.c
pimd/pim_upstream.h
pimd/pim_vty.c

Includes a couple of commits to resolve issues with displaying or reacting to particular pimd commands.  It was noted that when vrfs are in use, several commands that were only global in scope would display in every vrf (pim packets, pim join-prune-interval, etc.)  Moved these to only display in the global since that's where they reside.  Additionally while testing found that when the register-suppress-time was modified, the rp_keepalive_time was not adjusted accordingly (even though the rp_keepalive_time is derived from the register-suppress-time.)  Also found a bug that when "no ip pim rp keep-alive-timer" was issued, reset back to "PIM_KEEPALIVE_PERIOD" instead of "PIM_RP_KEEPALIVE_PERIOD" as intended.

Pimd timer fixes

---

tests/topotests/isis-topo1/r1/r1_topology.json
tests/topotests/isis-topo1/r2/r2_topology.json
tests/topotests/isis-topo1/r3/r3_topology.json
tests/topotests/isis-topo1/r4/r4_topology.json
tests/topotests/isis-topo1/r5/r5_topology.json
tests/topotests/isis-topo1/test_isis_topo1.py

parse_topology function doesn't correctly process vertex types with
spaces. Therefore the reference topology files are completely messed up,
we have values in incorrect fields - types in metrics, metrics in
parents, etc.
This commit fixes the parsing function and the reference files.
The same fix was done for isis-topo1-vrf in #8365.

tests: fix isis-topo1 topologies

---

pceplib/test/pcep_msg_messages_test.c
pceplib/test/pcep_msg_objects_test.c
pceplib/test/pcep_msg_tlvs_test.c
pceplib/test/pcep_msg_tools_test.c
pceplib/test/pcep_pcc_api_test.c
pceplib/test/pcep_session_logic_loop_test.c
pceplib/test/pcep_session_logic_states_test.c
pceplib/test/pcep_session_logic_test.c
pceplib/test/pcep_socket_comm_test.c
pceplib/test/pcep_utils_counters_test.c
pceplib/test/pcep_utils_double_linked_list_test.c
pceplib/test/pcep_utils_ordered_list_test.c
pceplib/test/pcep_utils_queue_test.c

Cleaning a list of messages (basically dereference null pointer) that has raised with scan-build.
As they are unit test and those cases are not suppose to happen, asserts has been added.

pceplib. Clean scan-build static analyzer messages.

---

bgpd/bgp_main.c
bgpd/bgp_zebra.c
bgpd/bgpd.c
bgpd/bgpd.h
zebra/redistribute.c

There was a fix some time ago for redistribution in VRF in commit https://github.com/FRRouting/frr/commit/6b2433c63f7fd3027cea8e06ca45f85bd3eea6f2.
Instead of fixing the real issue, this commit just removed a couple of necessary checks from the code.
The real issue is that the BGP instance is not deregistered from zebra when the VRF is deleted. Therefore, when the VRF is readded, the redistribution config is not replayed.
This PR reverts the incorrect "fix" and fixes the real issue in a new commit.

bgpd: fix redistribution in vrf

---

bgpd/bgp_nb_config.c
bgpd/bgp_vty.c
bgpd/bgpd.c

A couple of BGP CLI/NB fixes:
```
bgpd: fix crash when as/type mismatches in config
When we're trying to create the config for already existing router and
the AS number or instance type mismatches, we're returning the
inconsistency error and don't set the NB entry.
Any subsequent command that configures this router will crash because
every command relies on the existence of the NB entry.
Let's store the entry even when there's a mismatch to prevent the crash.
```
```
bgpd: simplify bgp_global_local_as_modify code
No need for complicated code to check instance existence.
```
```
bgpd: forbid modification of bgp instance type
If a user issues the following commands:
router bgp 65000 vrf red
router bgp 65000 view red
bgpd ends up having NB config inconsistent with actual data.
```

bgp cli/nb fixes

---

doc/user/bgp.rst

There are more useful CLI commands coming, thus it's desired to have it's
own section.
Fixes https://github.com/FRRouting/frr/issues/8651

doc: Move BGP community alias under a separate section

---

doc/user/ospf6d.rst
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_intra.c
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6_zebra.c

The code had no limits on addresses configured on an interface running
ospfv3.  The code would crash when more than 100 addresses were added.
This change limits the number of interface address to 100 if mtu is set
to the default value.  If the mtu is set to a jumbo packet size or larger
we will support 200 interface addresses.

ospf6d: Limit the number of interface addresses being supported in ospfv3

---

zebra/if_netlink.c
zebra/kernel_netlink.c
zebra/rt_netlink.c

Cleanup usage of the parse_rtattr code in zebra.
a) in some places we memset tb before and in some places we don't.  This is a crash waiting to happen.  Move memset to inside function to ensure it always happens
b) if_netlink.c had a duplicate function that was a define.  consolidate down to 1.

Parse rtattr

---

bgpd/bgpd.c

Deconfiguring conditional advertisement resulted in all other policy
settings on the peer getting removed due to an excessively large memset.
This also created a desync with the northbound config tree, which caused
its own set of problems...
Fix the memset to just remove the conditional advertisement config.

bgpd: fix deconfig of conditional advertisement

---

lib/privs.c
lib/privs.h

We'll need ZCAP_IPC_LOCK for future work coming down the pike
related to dataplane work being done.

lib: Add ZCAP_IPC_LOCK

---

tests/topotests/bgp_recursive_route_ebgp_multi_hop/test_bgp_recursive_route_ebgp_multi_hop.py

Tests had format for strings with 2 variables but 1 place to put the data.

tests: Fix pylint issues in test_bgp_recursive_route_ebgp_multi_hop.py

---

bgpd/bgp_nht.c
bgpd/bgp_zebra.c
ospfd/ospf_asbr.c
ospfd/ospf_flood.c
ospfd/ospf_gr_helper.c
ospfd/ospf_nsm.c
ospfd/ospf_packet.c
ospfd/ospf_spf.c
pimd/pim_ifchannel.c
zebra/zapi_msg.c
zebra/zebra_evpn_mh.c
zebra/zebra_pbr.c

Some snuck back in.  Search and replace.
ospf6d left alone at the moment because of an active PR.

Use __func__ instead of __PRETTY_FUNCTION__

---

lib/if.h
zebra/connected.c

Track 'down' state of connected addresses with a new flag. We may have multiple addresses on an interface that share a prefix; in those cases, we need to determine when the first address is valid, to install a connected route, and similarly detect when the last address goes 'down', to remove the connected route.
If we have multiple addresses and  `shut` the interface, the code checks the list of connecteds and finds more than one - so it doesn't remove the zebra connected route. The list of connecteds only changes when address are actually added or removed, and the existing code does handle that.
Fixes #8611 
(I think)

lib,zebra: Use a flag to track down status for connected addrs

---

ospf6d/ospf6_flood.c

This should fix the ANVL failure reported in #8567 I added in 4c63a76a63fd02ae2aa73e4e66b04b37b10fdd99 while trying to fix #7030. It passes my manual ANVL-like test performing the steps listed in ANVL-26.13_Failed.txt attached to the bug report. It also passes my topotest for #7030 submitted (but still pending) in #7168.
@Manikandaprab: Could you re-run the real ANVL test with this fix applied, please?
BTW, I still don't understand what commit 76249532faadfb429f46dd94cf6bbc61d78b3f26 was trying to achieve exactly. The code from this commit is still used for the non-self-originated LSA case, but I'm not sure it does anything useful. But at least it doesn't seem to cause harm in typical cases or we would have noticed in the meantime...

Fix #8567 OSPFv3-26.13 ANVL failure

---

bgpd/bgp_vty.c

When only one of the keepalive or hold timers is changed from the
default, bgp won't print the timers command in the config.

bgpd: fix display of timers when only 1 is changed

---

ripd/rip_interface.c
ripngd/ripng_interface.c

RIP schedules a call to `rip_interface_wakeup` in 1 second after
receiving the interface UP event from zebra. The function is called even
if the interface was shut down during this interval.
This is incorrect and also leads to a crash in the following scenario:
```
vtysh -c "conf" -c "router rip vrf red" -c "network enp2s0"
ip link add red type vrf table 1
ip link set enp2s0 vrf red
ip link set enp2s0 down
ip link set enp2s0 up && ip link del red
```

ripd, ripngd: fix interface wakeup after shutdown

---

zebra/zebra_rib.c

Since _rnode_zlog was wrapping zlog(), these messages weren't getting an
unique ID assigned through the xref mechanism.  Replace macro with a
small extension that prints (almost) the same thing.

zebra: replace _rnode_zlog with %pZN ext

---

zebra/zebra_vxlan.c

When clagd is stopped on secondary device, all vxlan interfaces (vnis) are kept in protodown state.
FRR treats protodown vxlan interfaces (vnis) as interface down and sends vni delete to bgpd.
In the event of clagd down, SVIs are flapping as underlying
bridge is going through churn.
When FRR receives SVI up notification do not trigger vni up event to bgpd, if vnis are operationally down.
Testing Done:
Performed CLAG stop/start on secondary device, all vxlan devices remained in protodown along with
this validated the vnis are cleaned up and added back in bgpd.

zebra: evpn check vni oper state in svi up/down event

---

isisd/isis_sr.c

If the n-flag-clear option is set in the configuration of a prefix
segment, clear the flag in the extended ip reachability TLVs.
RFCs 7794 and 8667 are not too strict on the setting / clearing the
N-flag in prefix SIDs. However, if there exists a cmd line option
to clear it, it should be cleared in the TLVs announced, as other
vendors do.
Signed-off-by: Fredi Raspall <fredi@voltanet.io>

isisd: clear the N-flag in ext. reachability TLVs

---

bgpd/bgp_network.c

The priv raise was incorrectly dropped in 97896a9.

bgpd: raise privs for SO_BINDTODEVICE

---

doc/user/pathd.rst
pathd/path_cli.c

From "{}" to "<>" to provide mutual exclusion.

pathd: Fix affinity command to exclude options to match implementation.

---

ospf6d/ospf6_top.c
ospfd/ospfd.c

If the default route redistribution is configured in OSPF router before
the VRF is created, then this is not currently registered in zebra after
the VRF creation.

ospfd, ospf6d: fix "default-information originate" in non-existing vrf

---

pathd/path_cli.c
pathd/path_pcep_pcc.c
pathd/pathd.c

The list of cov issues are:
path_cli.c
ln:354 DEADCODE As adj_src_ipv6_strv is previously check cannot be null and choose else path.
ln:424 DEADCODE same case as before.
ln:531 DEADCODE The fn segment_list_has_prefix return status wasn't captured so "status" is always CMD_SUCCESS.
pathd.c
ln:203: REVERSE_INULL Check of "segment" is done after dereferencing it.
path_pcep_pcc.c 
ln:1275: USE_AFTER_FREE. Access to path->name after pcep_free_path().

pathd: Clean coverity issues after merge pathd link state feature.

---

bgpd/bgp_zebra.c

If there's no default router configured at the moment when bgpd is
connected to zebra, bgpd is not registered as a BFD client.
We should do the registration regardless of the config existence.

bgpd: fix zebra bfd registration

---

ospfd/ospf_ri.c
ospfd/ospf_sr.h

I think this may be the reason for `ospf_sr_topo1` frequent fails.

ospfd: fix SID/Label Sub TLV size

---

tests/topotests/multicast_pim_sm_topo2/test_multicast_pim_sm_topo2.py

Test case test_verify_mroute_when_5_different_receiver_joining_same_sources_p0
is failing intermittently in master. Fixed the issue.
Weekly statistics for the reference:
===== WEEK FROM 2021-05-04 TO 2021-05-11 (108637) FRR-FRR =====
===== TESTS BY FAILURE RATE [rank: name (total, passed, failed, failure rate)] (126) =====
1: bgp_ipv6_rtadv (235, 234, 1,  0.43%)
* test_protocols_convergence (https://ci1.netdef.org/browse/FRR-FRR-4633)
2: bfd-topo3 (359, 358, 1,  0.28%)
* test_wait_bfd_convergence (https://ci1.netdef.org/browse/FRR-FRR-4653)
3: ospf6-topo2 (359, 358, 1,  0.28%)
* test_ospf6_default_route (https://ci1.netdef.org/browse/FRR-FRR-4632)
4: bgp_gr_functionality_topo1 (2246, 2241, 5,  0.22%)
* test_BGP_GR_TC_46_p1 (https://ci1.netdef.org/browse/FRR-FRR-4630)
* …

tests: Fix for multicast_pim_sm test failure

---

bgpd/bgpd.c

Currently, when AS number of an existing BGP neighbor is added in a BGP
confederation, `AS_CONFED_SEQUENCE` segment attribute will be missing in
prefixes advertised to the neighbor. Also, receiving prefixes from the
neighbor will be withdrawn because of "Malformed AS path from A.B.C.D".
neighbor 10.100.200.3 remote-as 123
bgp confederation identifier 65001
bgp confederation peers 123
With this change, update peer's sort after adding or removing its AS
number in a BGP confederation.

bgpd: recalc peer's sort after changing confed peers

---

zebra/connected.c

zebra: fix possible uninitialized value

---

ospfd/ospf_ri.c
ospfd/ospf_te.c

FRR is not using newlines in log messages.  Remove them.

ospfd: New code adds newline to log files

---

isisd/isis_main.c
isisd/isis_nb_config.c
isisd/isis_redist.c
isisd/isis_redist.h
isisd/isis_zebra.c
isisd/isis_zebra.h
isisd/isisd.c
tests/isisd/test_isis_spf.c
tests/topotests/isis_topo1_vrf/r1/r1_route.json
tests/topotests/isis_topo1_vrf/r1/r1_route6.json
tests/topotests/isis_topo1_vrf/r1/r1_topology.json
tests/topotests/isis_topo1_vrf/r2/r2_route.json
tests/topotests/isis_topo1_vrf/r2/r2_route6.json
tests/topotests/isis_topo1_vrf/r2/r2_topology.json
tests/topotests/isis_topo1_vrf/r3/r3_route.json
tests/topotests/isis_topo1_vrf/r3/r3_route6.json
tests/topotests/isis_topo1_vrf/r3/r3_topology.json
tests/topotests/isis_topo1_vrf/r4/r4_route.json
tests/topotests/isis_topo1_vrf/r4/r4_route6.json
tests/topotests/isis_topo1_vrf/r4/r4_topology.json
tests/topotests/isis_topo1_vrf/r5/r5_route.json
tests/topotests/isis_topo1_vrf/r5/r5_route6.json
tests/topotests/isis_topo1_vrf/r5/r5_topology.json

When the redistribution is configured in non-default VRF, isisd should
redistribute routes from this VRF instead of default.
This is an easier implementation of https://github.com/FRRouting/frr/pull/8215.

isisd: fix redistribution in vrf

---

lib/northbound.c

lyd_merge_tree replaces dest siblings with source siblings, not what we
want. Instead lyd_merge_siblings to keep both. Instead lyd_merge_siblings
to keep both.

lib: fix northbound merge code (libyang)

---

bgpd/bgp_nb.c
bgpd/bgp_nb.h
bgpd/bgp_nb_config.c
bgpd/bgp_vty.c
yang/frr-bgp-common-structure.yang

The leaf is called "no-replace-as" in the model but is used reversed in
all the code. Let's rename it to comply with the actual behavior.

bgpd, yang: fix replace-as yang leaf

---

tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py

Too many arguments for format string.

tests: fix bgp_l3vpn_to_bgp_vrf

---

ospfd/ospf_vty.c

Found that in some circumstances, when the "ip ospf area"
command was entered for the default vrf, the wrong ospf
process would be used to check for the presence of a
"network" statement, causing the "ip ospf area" command to
be rejected. This was due to the command using the ospf
instance lookup to find the right ospf process, which can
be in error depending on when the processes were created.

ospfd: "ip ospf area" command can select wrong process

---

yang/frr-bgp.yang
yang/frr-pim-rp.yang
yang/frr-route-types.yang

Summary
---
Fix the command `network` for multicast prefixes in `address-family ipv4 multicast`.
The YANG model was using the pattern for **address** instead of **prefix**.
Example
---
```
router bgp 65000
address-family ipv4 multicast
network 224.0.10.0/24
% Failed to edit configuration.
YANG error(s):
Value "224.0.10.0/24" does not satisfy the constraint "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" (range, length, or pattern).
Value "224.0.10.0/24" does not satisfy the constraint "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" (range, length, or pattern).
YANG path: /frr-bgp:prefix
```

yang: fix BGP multicast prefix specification

---

bgpd/bgp_route.c

They were missed during BGP NB revert.

[8.0] bgpd: fix missing command installations

---

ospf6d/ospf6_asbr.c

Don't `memcpy` a `struct prefix` the memory size varies depending on the original intended type. In this case the original type was (casted away) `struct prefix_ipv6` and we tried to copy `struct prefix` which is bigger.

ospf6d: fix address sanitizer crash

---

yang/frr-bgp-neighbor.yang
yang/frr-bgp-peer-group.yang
yang/frr-bgp.yang

The default for extended-nexthop-capability is true for
unnumbered (interface) neighbors, false for other types. Break the inner
grouping out of the outer neighbor-parameters grouping so that we can
refine the default in that uses case.
Signed-off-by: Christian Hopps <chopps@gmail.com>

bgpd: fix default for extended-nexthop-capability

---

configure.ac

Include -Werror with the listing of compiler flags after the configure script runs.

build: display Werror in configure output, if configured

---

lib/routemap.c

Prior to this commit, updating a prefix-list that is referenced by a
route-map clause will unconditionally delete the root node of that
route-map's prefix-tree (used with route-map optimization).
This is problematic because routes not matching a more specific node
in the tree (i.e. other prefix-list sequences) will not fall-back to
the default node, thus they will not hit any route-map sequences.
This commit ensures that an update to a prefix-list will only delete
the default node while adding the first/only seq to the list.
Example config:
========
ip prefix-list peer475-out-pfxlist seq 45 permit 2.138.0.0/16
ip prefix-list peer475-out-pfxlist seq 50 permit 0.0.0.0/0
!
route-map peer475-out permit 5
match ip address prefix-list peer475-out-pfxlist
Before:
========
ub20# do show route-map …

lib: fix handling of rmap prefix-tree default node

---

pbrd/pbr_nht.c
pbrd/pbr_nht.h

Replace a static lookup array for nexthop-group cache table IDs (`static bool nhg_tableid[65535]` in previous code) with a sparse table representing table IDs allocated to cached nhg entries. This (perfect) hash is keyed by table ID and is filtered through to find the "next unallocated table ID" which PBR will use to install a table in kernel.
The "next unallocated table ID" is pre-computed each time an entry is released from or added to the hash to reduce complexity when only "peeking" to check if a free ID is avaialble (`pbr_nht_has_unallocated_table`).
---
This implementation fixes an OOB core for `A > 65535` given `pbr set table range A B` (see the range of the static array above). Since the hash table is expanded automatically in `lib/hash.c` this is no longer a concern.
Another …

pbrd: implement sparse table lookup for nhg cache

---

ospfd/ospf_interface.c
ospfd/ospf_route.c
ospfd/ospf_route.h

When we get a very quick set of down/up events in ospf, ospf
will run spf *after* both of these events and come to the determination
that there is nothing to send to zebra.
Modify the code such that on an interface down event, mark the routes
as changed so that when ospf is deciding what to do it will automatically
resend the data to zebra.

ospfd: Fix quick interface down up event handling in ospf

---

staticd/static_nb.h
staticd/static_vty.c

When the user adds the route + nexthop pair that already exists with a
different distance, we should replace it instead of adding a new one.
Likewise, when the user wants to delete the route + nexthop pair without
explicitly entering the distance, we should delete the route.
Fixes #8695.

staticd: fix distance processing

---

ospf6d/ospf6_message.c
ospf6d/ospf6_message.h

```
ospf6d: fix invalid "no debug ospf6 message unknown"
The message is always shown in the config, because IS_OSPF6_DEBUG_MESSAGE
works incorrectly when negated because of missing outer brackets.
```
```
ospf6d: fix debug message config write
Fix the following issues:
- if "send" is combined with "recv-hdr", only "send" is shown
- if "recv" is combined with "send-hdr", only "recv" is shown
- if both "send-hdr" and "recv-hdr" are enabled, "; header only" is shown
```

ospf6d: fix debug message issues

---

configure.ac
m4/.gitignore
m4/ax_cxx_compile_stdcxx.m4

Just checking for grpc++ is not enough as older distributions have incompatible versions (e.g., Ubuntu 18.04)

grpc: improve checks for GRPC C++ requirements

---

lib/routemap.c

[7.5] lib: fix handling of rmap prefix-tree default node

---

ospf6d/ospf6_asbr.c

So far, "set tag" was 99% implemented in ospf6d, but registration of the
hook functions was missing, causing "set tag" actions in route maps to be
ignored in ospf6d.
This commit adds the missing hook registration.
Without this bugfix (zebra & ospf6d running):
```
root@d30049169956:~# vtysh 
% Can't open configuration file /etc/frr/vtysh.conf due to 'No such file or directory'.
Hello, this is FRRouting (version 8.1-dev-my-manual-build).
d30049169956# conf t       
d30049169956(config)# route-map FOO permit 10
d30049169956(config-route-map)# set metric 123
d30049169956(config-route-map)# set tag 123
d30049169956(config-route-map)# end
d30049169956# show route-map FOO 
ZEBRA:
route-map: FOO Invoked: 0 Optimization: enabled Processed Change: false …
```

ospf6d: Fix route map "set tag" command

---

lib/routemap.c

[8.0] lib: fix handling of rmap prefix-tree default node

---

bgpd/bgp_evpn_vty.c
bgpd/bgp_vty.c
bgpd/bgp_vty.h
doc/user/bgp.rst
tests/topotests/all_protocol_startup/test_all_protocol_startup.py

Add ability to filter session on show bgp summary by neighbor or
remote AS:
ubuntu# show bgp summary ?
neighbor     Show only the specified neighbor session
remote-as    Show only the specified remote AS session
ubuntu# show bgp summary neighbor ?
A.B.C.D   Neighbor to display information about
WORD      Neighbor on BGP configured interface
X:X::X:X  Neighbor to display information about
ubuntu# show bgp summary remote-as ?
(1-4294967295)  AS number
external        External (eBGP) AS sessions
internal        Internal (iBGP) AS sessions

bgpd: add show bgp summary filter by neighbor or AS

---

zebra/zebra_rnh.c
zebra/zebra_rnh.h
zebra/zebra_vty.c

Optionally hide route changes that only involve backup nexthop activation/deactivation. The goal is to avoid route churn during backup nexthop switchover events, before the resolving routes re-converge. A UI config enables this 'hiding' behavior.
If the new behavior is enabled, zebra will not send nht notifications if a primary nexthop that's part of a tracked route is deactivated in favor of a backup nexthop. zebra will send notifications if the primary or backup nexthops change, or of course if the route for a tracked destination changes.

zebra: hide backup-nexthop activations in nht

---

staticd/static_nb.h
staticd/static_vty.c

When the user adds the route + nexthop pair that already exists with a
different distance, we should replace it instead of adding a new one.
Likewise, when the user wants to delete the route + nexthop pair without
explicitly entering the distance, we should delete the route.
Fixes #8695.

Backport the fix for #8695 to 7.5

---

staticd/static_vty.c

Return a meaningful vtysh value in an error path, if user tries to delete a route that doesn't exist - staticd has always returned SUCCESS in this case.

staticd: return meaningful status in cli error path

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_route.c

Ensure that if allocated route is not added to a table then it is
deleted to avoid leaking memory.
Add a new memory type for route table so that ospf6 routes can be
distinguished in the show memory output in isolation.

ospf6: fix memory leak in ospf6_abr_examin_summary

---

doc/user/zebra.rst
tools/etc/frr/support_bundle_commands.conf
zebra/zebra_vty.c

Description:
This command already added to support_bundle_commands.conf file but not defined.
So, Added this show command("show ip zebra route dump") which dumps all routes
with detailed information including next hops, flags, status ..etc.
This route information will be dump to a file when support bundle generated.
This helps for  better dubugging and added this command as a hidden command.

zebrad: Added a command to dump routes in support bundle

---

pceplib/pcep_session_logic_loop.c

pceplib: fix mixup of global/local variables

---

lib/frr_zmq.c

The frr_zmq wrapper/shim module was using some ... macro magic as it interacted with the task/thread scheduling module. That led to various problems - just use the normal public scheduling apis.

lib: fix use of xrefs in zmq wrapper

---

.gitignore
lib/prefix.h
tools/.gitignore
tools/frr-llvm-cg.c
tools/frr-llvm-debuginfo.cpp
tools/frr-llvm-debuginfo.h
tools/subdir.am

- one small compile fix for clang++ (which doesn't accept `__attribute__((transparent_union))`)
- bunch of `.gitignore`
- `frr-llvm-cg` updates
(No, I won't fix style warnings in `tools/frr-llvm-*` – that tool is provided purely as a no-warranty no-complaints free-bonus thing; I just pushed it out in case it might ever so slightly be useful to someone at some point, if there's any pushback I'll rather just remove it.  "Don't look a gift horse in the mouth.")

lib: LLVM care package

---

isisd/isis_bfd.c
ospf6d/ospf6_bfd.c
pimd/pim_bfd.c

isisd, ospf6d, pimd: set vrf_id when creating bfd sessions

---

ospf6d/ospf6_interface.c

ospf6d: fix using vrf interface as a loopback

---

bgpd/bgp_vty.c
eigrpd/eigrp_cli.c
isisd/isis_cli.c
lib/command.c
lib/if.c
lib/lib_vty.c
lib/northbound.c
lib/northbound.h
lib/northbound_cli.c
lib/northbound_cli.h
lib/vrf.c
lib/vty.c
lib/vty.h
ripd/rip_cli.c
ripngd/ripng_cli.c
tests/bgpd/test_peer_attr.c

The backoff code assumed that yang operations always completed quickly.
It checked for > 100 YANG modeled commands happening in under 1 second
to enable batching. If 100 yang modeled commands always take longer than
1 second batching is never enabled. This is the exact opposite of what
we want to happen since batching speeds the operations up.
Here are the results for libyang2 code, for static routes, without and with batching.
```
| action        |  1K rts |  2K rts | 1K rts | 2K rts | 20k rts |
|               | nobatch | nobatch |  batch |  batch |   batch |
| Add IPv4      |    .881 |    1.28 |   .703 |   1.04 |    8.16 |
| Add Same IPv4 |    28.7 |     113 |   .590 |   .860 |    6.09 |
| Rem 1/2 IPv4  |    .376 |    .442 |   .379 |   .435 |    1.44 |
| Add Same IPv4 |    28.7 | …
```

northbound: KISS always batch yang config, it's faster.

---

pathd/path_cli.c

the config for dynamic candidate paths with bandwidth preferences was using a different order of keywords (`required bandwidth X`) than the corresponding command (`bandwidth X required`). This confuses frr-reload, and possibly users too. Make both use the same order.

pathd: fix render candidate-path bandwidth

---

doc/user/bfd.rst
doc/user/sharp.rst

doc: remove varnames from command descriptions

---

bfdd/bfd.h

There's a padding byte between "mhop" and "peer" fields in this structure.
This structure is sometimes passed by value to functions and used in
assignments. The standard doesn't guarantee that the padding bytes are
copied on assignments. As this structure is used as a hash key, having
this padding byte with unspecified value can lead to unwanted behavior.
Fix the possible issue by making the struct packed.

bfdd: fix bfd key structure

---

lib/frr_zmq.c

Backport #8304 to the dev/8.0 branch

lib: [8.0] fix use of xrefs in zmq wrapper

---

lib/northbound_grpc.cpp

The code that actually calls FRR northbound functions needs to be running in the
master thread. The previous code was running on a GRPC pthread. While fixing
moved to more functional vs OOP to make this easier to see.

lib: fix threading bug in GRPC code

---

doc/user/ospfd.rst
ospfd/ospf_sr.c
ospfd/ospf_sr.h
tests/topotests/ospf_sr_topo1/test_ospf_sr_topo1.py

similarly to what was done for IS-IS in commit 01d43141, combine the SRGB and SRLB commands for OSPF-SR, so that we can replace overlapping ranges in one sweep change.
Also allow the range configuration to be stored before SR is enabled. There is no reason why we should not - in fact that constraint meant that we were always requesting the default label ranges regardless of what we actually wanted to use.

ospfd, doc: combined SRGB/SRLB command

---

lib/vrf.c
zebra/zebra_vrf.h

When the VRF node is exited using "exit" or "quit", there's still a VRF
pointer stored in the vty context. If you try to configure some router
related command, it will be applied to the previous VRF instead of the
default VRF. For example:
```
(config)# vrf test
(config-vrf)# ip router-id 1.1.1.1
(config-vrf)# do show run
...
!
vrf test
ip router-id 1.1.1.1
exit-vrf
!
...
(config-vrf)# exit
(config)# ip router-id 2.2.2.2
(config)# do show run
...
!
vrf test
ip router-id 2.2.2.2
exit-vrf
!
...
```
`vrf-exit` works correctly, because it stores a pointer to the default
VRF into the vty context (but weirdly keeping the VRF_NODE instead of
changing it to CONFIG_NODE).
Instead of relying on the behavior of exit function, always use the
default VRF when in CONFIG_NODE.
Another problem is missing …

zebra: fix config after exit from vrf

---

lib/command.c

Fix the following address sanitizer crash when running the command `find`:
```
ERROR: AddressSanitizer: dynamic-stack-buffer-overflow
WRITE of size 1 at 0x7fff4840fc1d thread T0
0  in print_cmd ../lib/command.c:1541
1  in cmd_find_cmds ../lib/command.c:2364
2  in find ../vtysh/vtysh.c:3732
3  in cmd_execute_command_real ../lib/command.c:995
4  in cmd_execute_command ../lib/command.c:1055
5  in cmd_execute ../lib/command.c:1219
6  in vtysh_execute_func ../vtysh/vtysh.c:486
7  in vtysh_execute ../vtysh/vtysh.c:671
8  in main ../vtysh/vtysh_main.c:721
9  in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
10 in _start (/usr/bin/vtysh+0x21f64d)
```

lib: fix address sanitizer crash on `find`

---

bgpd/bgp_bfd.c
bgpd/bgp_bmp.c
bgpd/bgp_conditional_adv.c
bgpd/bgp_fsm.c
bgpd/bgp_mac.c
bgpd/bgp_network.c
bgpd/bgp_nexthop.c
bgpd/bgp_packet.c
bgpd/bgp_route.c
bgpd/bgp_routemap.c
bgpd/bgp_updgrp.c
bgpd/bgp_vty.c
bgpd/bgp_zebra.c
bgpd/bgpd.c
bgpd/bgpd.h

We are inconsistently using peer_establiahed(peer) with
sometimes using `peer->status == Established`.  Just Convert
over to using the function for consistency.

bgpd: Convert to using peer_established(peer) function

---

tests/topotests/config_timing/r1/staticd.conf
tests/topotests/config_timing/r1/zebra.conf
tests/topotests/config_timing/test_config_timing.py

To start we use 10k static route config. This test goes along with
recent batching changes it will fail w/o them (b/c some operations w/o
batching take 100 times as long).
This test should be added to over time for other large config
items (e.g., acl, policy, etc)

tests: timing large config operations

---

doc/user/ospf_fundamentals.rst
doc/user/ospfd.rst
ospfd/ospf_vty.c
ospfd/ospfd.c

Currently, passive interface flag is configured from the router node
using "passive-interface IFNAME". There are multiple problems with this
command:
- it is not in line with all other interface-related commands - other
parameters are configured from the interface node using "ip ospf"
prefix
- it is not in line with OSPFv3 - passive flag is configured from the
interface node using "ipv6 ospf6 passive" command
- most importantly, it doesn't work correctly when the interface is in
a different VRF - when using VRF-lite, it incorrectly changes the
vrf_id of the interface and it becomes desynced with the actual state;
when using netns, it creates a new fake interface and configures it
instead of configuring the necessary interface
To fix all the problems, this commit adds a new command to the …

ospfd: fix passive interface configuration

---

eigrpd/eigrp_cli.c
isisd/isis_cli.c
lib/command.c
lib/if.c
lib/lib_vty.c
lib/northbound.c
lib/northbound.h
lib/northbound_cli.c
lib/northbound_cli.h
lib/vrf.c
lib/vty.c
lib/vty.h
ripd/rip_cli.c
ripngd/ripng_cli.c

The backoff code assumed that yang operations always completed quickly.
It checked for > 100 YANG modeled commands happening in under 1 second
to enable batching. If 100 yang modeled commands always take longer than
1 second batching is never enabled. This is the exact opposite of what
we want to happen since batching speeds the operations up.
Here are the results for libyang2 code without and with batching.
| action        |  1K rts |  2K rts | 1K rts | 2K rts | 20k rts |
|               | nobatch | nobatch |  batch |  batch |   batch |
| Add IPv4      |    .881 |    1.28 |   .703 |   1.04 |    8.16 |
| Add Same IPv4 |    28.7 |     113 |   .590 |   .860 |    6.09 |
| Rem 1/2 IPv4  |    .376 |    .442 |   .379 |   .435 |    1.44 |
| Add Same IPv4 |    28.7 |     113 |   .576 |   .841 | …

northbound: KISS always batch yang config (file read), it's faster

---

zebra/zebra_mlag.c

When processing bulk messages we need more space to handle more
mroutes.  In this case we are doubling the stream size from
16k -> 32k, which should roughly double the number of mroutes
we can handle in one go.
Additionally.   If we cannot parse the passed message into
the stream to pass up to pimd then gracefully stop processing

zebra: Give extra space and stop processing if we run out of space

---

bgpd/bgp_table.h

static inline functions cannot be probed, let's add USDT.
This will help catching memory leaks regarding lock/unlock in the future,
I believe.
```
global locks;
probe begin
{
ansi_clear_screen();
println("Starting...");
}
probe process("/usr/lib/frr/bgpd").mark("bgp_dest_lock")
{
prefix = @cast($arg1, "bgp_node")->p->u->val;
locks[prefix]++;
printf("---> %s %d (lock count: %d)\n", probefunc(),
prefix, @cast($arg1, "bgp_node")->lock);
}
probe process("/usr/lib/frr/bgpd").mark("bgp_dest_unlock")
{
prefix = @cast($arg1, "bgp_node")->p->u->val;
if (locks[prefix] > 0) {
locks[prefix]--;
}
printf("<--- %s %d (lock count: %d)\n", probefunc(),
prefix, @cast($arg1, "bgp_node")->lock);
}
```
Some outputs:
```
<--- adj_free 94283113939304 (lock count: 2)
<--- adj_free 94283114099240 (lock count: 3) …
```

bgpd: Add tracepoints for bgp_dest_lock_node/bgp_dest_unlock_node

---

ospfd/ospf_asbr.c

To reproduce the issue:
1. Create summary-address: `summary-address 1.1.1.0/24`.
2. Try to delete it with the wrong tag: `no summary-address 1.1.1.0/24 tag 1`.
Each time this command is executed, route_node_lookup is called which
locks route node one more time. As the tag is wrong, the function
return immediately without unlock.
3. Finally delete the summary-address: `no summary-address 1.1.1.0/24`.
The route node won't be deleted.

ospfd: fix memory leaks in summarization

---

doc/user/ospf6d.rst
ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_top.c
tests/topotests/ospf6_topo1_vrf/README.md
tests/topotests/ospf6_topo1_vrf/r1/ospf6d.conf
tests/topotests/ospf6_topo1_vrf/r2/ospf6d.conf
tests/topotests/ospf6_topo1_vrf/r3/ospf6d.conf
tests/topotests/ospf6_topo1_vrf/r4/ospf6d.conf

Currently the interface area is configured from the router node using
"interface IFNAME area ID" command. There are multiple problems with
this command:
- it is not in line with all other interface-related commands - other
parameters are configured from the interface node using "ipv6 ospf6"
prefix
- it is not in line with OSPFv2 - area is configured from the interface
node using "ip ospf area" command
- most importantly, it doesn't work correctly when the interface is in
a different VRF - instead of configuring the interface, it creates a
new fake interface and configuring it instead
To fix all the problems, this commit adds a new command to the interface
configuration node - "ipv6 ospf6 area ID". The purpose of the command is
completely the same, but it works correctly in a multi-VRF …

ospf6d: fix interface area configuration

---

bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_table.h
bgpd/bgpd.c

BGP configuration changes that imply recomputing the BGP route table
(e.g. modifying route-maps, setting bgp graceful-shutdown) might be a
long time process depending on the size of the BGP table and the
route-map numbers and complexity. For example, setups with full
Internet routes take something like one minute to reprocess all the
prefixes when graceful-shutdown is configured. During this time, a
"show bgp commands" request on vtysh results in blocking the shell until
the soft reconfigure table task is over.
This patch splits bgp_soft_reconfig_table task into thread jobs of 25K
prefixes.
Some tests on a full Internet route setup show that after reconfiguring
route-maps or graceful-shutdown, vtysh is not stucked anymore. We are
now able to request commands like "show bgp summary" after …

bgpd: split soft reconfig table task into several jobs to not block vtysh

---

lib/northbound.c

Perform same NULL check for dependent node creation code too.

lib: do not attempt to create default nodes from NULL tree node

---

tests/topotests/lib/bgp.py
tests/topotests/lib/ospf.py
tests/topotests/lib/pim.py

Issue: There was an error reported by Pylint regarding "expected" keyword:
Unexpected keyword argument 'expected' in function call (unexpected-keyword-arg)
Fix: We have defined expected keyword in all topojson APIs.

tests: Fixing common pylint error for topojson

---

ospf6d/ospf6_lsa.c

Added link state ID to JSON output of LSA database CLI show command.
Signed-off-by: David Schweizer <dschweizer@opensourcerouting.org>

ospf6d: Link state ID in LSA database JSON output

---

doc/developer/topotests.rst
tests/topotests/conftest.py
tests/topotests/lib/topogen.py
tests/topotests/lib/topotest.py

Adds `--valgrind-memleaks` to topotests pytest. Runs daemons in valgrind and checks for leaks, failing tests if found.

tests: add valgrind memleaks run options and detection

---

ospfd/ospf_routemap.c

Currently, if the routemap already exists, we delete the pointer to it
when it is updated. We should delete the pointer only if the route-map
is actually deleted.

ospfd: fix routemap update

---

isisd/isis_circuit.c
isisd/isisd.c

```
isisd: fix adding a circuit to the wrong area
When creating a new area, we're adding all circuits in the same VRF to
this area. We should only add circuits configured with the same tag.
```
```
isis: fix double-adding a circuit to the area
isis_circuit_enable can be called for an already enabled circuit. In this
case we would add the circuit to the area multiple times.
```

a couple of isis fixes

---

ospf6d/ospf6_flood.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_intra.c
ospf6d/ospf6_message.c
ospf6d/ospf6_spf.c

The logging in ospf6 is very verbose.  If you turn on logging on a scaled
system you get too many logs.   The problem is that there are some errors
that occur that are hidden behind the debug flags, and to see these errors
we currently need to turn on the debug logging.  This change converts these
error logs to warnings and removes the debug flags.
Signed-off-by Lynne Morrison <lynne@voltanet.io>

ospf6d: move error logs out from behind debug flags

---

isisd/isis_adjacency.c
isisd/isis_dynhn.c
isisd/isis_dynhn.h
isisd/isis_lsp.c
isisd/isis_misc.c
isisd/isis_nb_notifications.c
isisd/isis_snmp.c
isisd/isisd.c
isisd/isisd.h
tests/isisd/test_common.c
tests/isisd/test_isis_spf.c

Currently, the dynamic hostname cache is global. It is incorrect because
neighbors in different VRFs may have the same system ID and different
hostnames.
This also fixes a memory leak - when the instance is deleted, the cache
must be cleaned up and the cleanup thread must be cancelled.
Fixes #8832.
As discussed with @donaldsharp, this PR should replace https://github.com/FRRouting/frr/pull/8834.

isisd: per-instance dynamic hostname cache

---

bgpd/bgp_routemap.c

- vnc_routemap_update is called only for the last bgp instance
- vpn_policy_routemap_event is not called at all
- unguarded debug (there's already a debug inside the called function)
Make the code consistent with the callback code that is used when the
delay timer is enabled.

bgpd: fix routemap update with disabled delay timer

---

docker/alpine/Dockerfile
docker/alpine/docker-start
docker/centos-7/Dockerfile
docker/centos-7/docker-start
docker/centos-8/Dockerfile
docker/centos-8/docker-start
docker/debian/Dockerfile
docker/debian/docker-start

Use `tini` to reap zombies and forward signals to the script. Also start `watchfrr.sh` directly instead of using `sleep 365d` in many of the Docker containers.
To build and test:
```
./docker/centos-8/build.sh
./docker/centos-7/build.sh
docker build ./docker/debian
w@kvm-gentoo .../code/frr $ docker run -it frr:centos-8-b7a223b691 
2021/06/16 02:14:56 WATCHFRR: [T83RR-8SM5G] watchfrr 8.1-dev_git788699264657 starting: vty@0
[...]
w@kvm-gentoo .../code/frr $ docker run -it frr:centos-8-b7a223b691 bash
[root@39cfa2832151 /]# ps 1
PID TTY      STAT   TIME COMMAND
1 pts/0    Ss     0:00 /sbin/tini -- bash
```
I wanted to fix the Alpine build with this PR as there is no LY2 in the Alpine repos but that's proving to be a more-than-trivial task :) it will take more work in the Alpine repository …

docker: use tini as entrypoint unilaterally

---

zebra/zebra_rnh.c
zebra/zebra_srte.c

when sending nexthop information.  We do not need to reset the
last_write_cmd since that is taken care of in the send routine.

zebra: We already store the last command as part of zserv_write

---

lib/compiler.h
lib/table.h

All these functions acquire a route_node lock. Marking them as pure
means that the compiler can optimize the code to not call them multiple
times when it already knows the return value. This is insane.
Fixes #8866
Fixes #8809
Fixes #8595
Fixes #6992

lib: remove pure attribute from functions that modify memory

---

lib/if.c
lib/vty.c
lib/vty.h

This commit fixes the following problem:
- enter the interface node
- move the interface to another VRF
- try to continue configuring the interface
It is not possible to continue configuration because the XPath stored in
the vty doesn't correspond with the actual state of the system anymore.
For example:
```
nfware# conf
nfware(config)# interface enp2s0
<-- move the enp2s0 to a different VRF -->
nfware(config-if)# ip router isis 1
% Failed to get iface dnode in candidate DB
```
To fix the issue, go through all connected vty shells and update the
stored XPath.
Suggested-by: Renato Westphal <renato@opensourcerouting.org>
@rwestphal I added the "Suggested-by" tag mentioning you, as you suggested this idea in …

lib: fix interface configuration after vrf change

---

tools/frr-reload.py

Problem reported that frr-reload.py didn't handle the mac access-list
command correctly, causing reloads to fail.  This fix adds the
support for the command as a single line context.

tools: add mac access-list context to frr-reload.py

---

lib/bitfield.h
lib/memory.c

it is handy to be able to see allocated bitfields in the show
memory output.

lib: add an MTYPE for bitfields

---

ospf6d/ospf6_flood.c

In RFC 2328, seqnumber 0x80000000 is reserved and not used.   If an LSA
is received with this seqnumber, the LSA is now dropped and a debug error
log is printed.

ospf6: Drop LSA with bad seqnumber

---

isisd/isis_circuit.c

Daemons should not output warnings into the running config.

fabricd: fix running config

---

tools/frr-reload.py

One-line fix to make `frr-reload.py` treat `pbr table range ...` lines as being single-line contexts instead of creating a new context.
First create a config file with the following contents:
```
cumulus@cumulus:mgmt:~$ cat frr-1.conf 
nexthop-group GROUP1
nexthop 21.1.1.2 swp2
pbr-map MAP1 seq 10
set nexthop-group GROUP1
match dscp 1
interface swp1
pbr-policy MAP1
```
Then copy this file and add `pbr table range ...` to the top:
```
cumulus@cumulus:mgmt:~$ cat frr-2.conf 
pbr table range 20000 4294966272
!
nexthop-group GROUP1
nexthop 21.1.1.2 swp2
pbr-map MAP1 seq 10
match dscp 1
set nexthop-group GROUP1
interface swp1
pbr-policy MAP1
```
```
./frr-reload.py --test --input frr-1.conf frr-2.conf
[...]
Lines To Delete
===============
no log syslog informational
no nexthop-group GROUP1 …
```

tools: make frr-reload recognize `pbr table range` lines as single-line contexts

---

ospf6d/ospf6_neighbor.c
ospf6d/ospf6_neighbor.h

During the database description exchange process, the slave
releases the last dbdesc packet after router_dead_interval.
This was not implemented in the code.
I have written the function ospf6_neighbor_last_dbdesc_release,
which releases the last dbdesc packet after router_dead_interval.
This change was required as per the conformance test 13.11:
In state Full reception of a Database Description packet from
the master after this interval (RouterDeadInterval) will
generate a SeqNumberMismatch neighbor event.
Test Actions
1.
2. 3.
ANVL: Establish full adjacency with DUT for neighbor Rtr-0-A on DIface-0, with DUT as slave.
ANVL: Wait (for <RouterDeadInterval> seconds).
ANVL: Send <OSPF-DD> packet from neighbor Rtr-0-A to DIface-0 containing:
• •
I-bit field not set
M-bit field not set
MS-bit …

ospf6d: Release last dbdesc packet after router dead interval

---

ospfd/ospf_lsa.c
ospfd/ospf_neighbor.c

Description:
When opaque capability disabled/enabled , all the self-originated lsa will be
flushed and it will make the neighbours to renegotiate.
But here, external lsas are not being re-originated after negotiation.
Fix:
Refresh/re-originate external lsas(Type-5 and Type-7) explicitly after
re-negotiation.

ospfd: External lsa handling in opaque capabilities enable/disable

---

bgpd/bgp_route.c

**To Reproduce**
1. Config BGP instance and network of a non-existent VRF
```
(config)# router bgp 65000 vrf vrf1
(config-router)# network 1.1.1.1/32
```
2. Create the VRF and route
3. The path remains invalid
```
BGP routing table entry for 1.1.1.1/32, version 0
Paths: (1 available, no best path)
Not advertised to any peer
Local
0.0.0.0 (inaccessible) from 0.0.0.0 (1.1.1.1)
Origin IGP, metric 0, weight 32768, invalid, sourced, local
Last update: Thu Jun 17 14:32:11 2021
```
4. The path will become valid after removing and reconfiguring the network.

bgpd: Force process networks on VRF creation

---

doc/user/ospf6d.rst
doc/user/ospfd.rst
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_message.c
ospf6d/ospf6_message.h
ospf6d/ospf6_neighbor.h
ospf6d/ospf6_network.c
ospf6d/ospf6_network.h
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
tests/topotests/ospf6_topo1/test_ospf6_topo1.py
tests/topotests/ospf6_topo1_vrf/test_ospf6_topo1_vrf.py

make socket read non-blocking
rewrite OSPF6 messages to use packet FIFO rather than write directly to socket
queue hello messages to head of FIFO to reduce hello latency
add write-multiplier config (as in OSPFv2) to allow tuning of read/write threads

OSPFv3 socket rework

---

ospf6d/ospf6_neighbor.c

Fix processing of "detail" and "drchoice" arguments.

ospf6d: fix "show ipv6 ospf6 neighbor" command

---

isisd/isisd.c

isisd: fix uninitialized variable when searching for LSP

---

doc/user/basic.rst
lib/compiler.h
lib/log_filter.c
lib/log_vty.c
lib/log_vty.h
lib/zlog.c
lib/zlog.h
lib/zlog_targets.c

#8457 2nd edition.  Doesn't a reboot always help?
This is all the preparatory commits for the upcoming RFC5424 PR which I'll open in a minute.  This is split off because everything here should be ready to go regardless of polishing or adjustments on the RFC5424 bits.

lib: preparations for RFC5424 syslog support

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_mh.c
bgpd/bgp_evpn_vty.c
bgpd/bgp_label.c
bgpd/bgp_snmp.c
bgpd/bgp_updgrp_adv.c
bgpd/bgp_zebra.c

bgp_node_lookup() increases `lock` which is not decreased on return.

bgpd: Make sure we don't miss to unlock for bgp_dest before returning

---

bgpd/bgp_updgrp_adv.c

If you advertise a default route (via default-originate) only if some
prefix is present in the BGP RIB (route-map specified) and this prefix
becomes unavailable, the default route keeps being advertised.
With this change, when we iterate over the BGP RIB to check if we can
advertise the default route, skip unavailable prefixes.
Signed-off-by: Alexander Chernavin <achernavin@netgate.com>
Closes https://github.com/FRRouting/frr/issues/8877

bgpd: [7.3] withdraw default route when route-map has no match

---

bgpd/bgp_updgrp_adv.c
tests/topotests/bgp_default_route_route_map_match_set/r1/bgpd.conf
tests/topotests/bgp_default_route_route_map_match_set/test_bgp_default-originate_route-map_match_set.py
tests/topotests/bgp_default_route_route_map_set/r1/bgpd.conf
tests/topotests/bgp_default_route_route_map_set/test_bgp_default-originate_route-map_set.py

Closes https://github.com/FRRouting/frr/issues/8840

bgpd: Allow aspath prepending for default-originate with route-maps

---

ospf6d/ospf6_interface.c

=================
When show ipv6 ospf6 neighbor is executed each neighbor gets
displayed twice.
frr# show ipv6 ospf6 neighbor
Neighbor ID     Pri    DeadTime    State/IfState         Duration I/F[State]
1.1.1.1           1    00:00:39     Full/DR              00:00:10 ens192[BDR]
1.1.1.1           1    00:00:39     Full/DR              00:00:10 ens192[BDR]
RCA:
====
Since ospf6_interface gets added twice to if_list we see multiple
display output.
Fix:
====
add ospf6_interface to if_list only when newly area gets attached
to the interface. If its already added no need to add it again.
Risk:
=====
Low
Tests Executed:
===============
Have tested the defect scenario.
frr# show ipv6 ospf6 neighbor
Neighbor ID     Pri    DeadTime    State/IfState         Duration I/F[State] …

ospf6d: Show neighbor displays twice for every neighbor.

---

vtysh/vtysh.c

The SR node is hidden by a `--enable-pathd` configuration option.
But the recent commit of SRv6 uses this node as well.  Let's expose
this node and let things work.

vtysh: Expose SR node for non pathd use cases

---

tools/frr-reload.py

2 commits:
a) cleanup frr-reload.py with black formatter
b) When doing a reload and changing the route-map for bgp neighbors, reload is issuing a `no neighbor ... route-map old <in|out>` followed by a `neighbor ... route-map NEW <in|out>`.  This is not good in that it causes churn and we might expose stuff we do not mean to.

Reload with routemaps

---

zebra/rib.h
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_mpls.c
zebra/zebra_mpls.h
zebra/zebra_mpls_openbsd.c
zebra/zebra_pw.c
zebra/zebra_rib.c

Modify the pseudowire reachability logic so that it returns success if there is at least one installed labelled nexthop (primary or backup) for the route resolving the pw destination. The old test required that _all_ nexthops be labelled, and that's not necessary. Also include more info about backups in the pw dataplane contexts.

zebra: Fix pseudowires with backup nexthops

---

Makefile.am
buildtest.sh
configure.ac
doc/developer/building-frr-for-centos6.rst
doc/developer/building-frr-for-centos7.rst
doc/developer/building-frr-for-centos8.rst
doc/developer/building-frr-for-debian8.rst
doc/developer/building-frr-for-debian9.rst
doc/developer/building-frr-for-netbsd6.rst
doc/developer/building-frr-for-netbsd7.rst
doc/developer/include-compile.rst
doc/developer/topotests.rst
doc/user/basic.rst
doc/user/installation.rst
lib/command.c
lib/subdir.am
lib/thread.c
lib/thread.h
lib/vty.c
python/xrelfo.py
vtysh/vtysh.c

- make xrelfo warnings hard failures as requested in #8412 
- ditch some unused things on `configure`
- make the CPU time stuff runtime options & try `CLOCK_THREAD_CPUTIME_ID`

build system housekeeping

---

isisd/isis_nb_config.c

There are some places in the ISIS NB code that require operational data to be available on the validation stage.
This requirement can not be fulfilled when using config batching, which is the default mode for reading configuration.
Change these validations to use configurational data instead.
Fixes #8852.
P.S.
There are actually a lot of other usages of operational data in the ISIS NB code.
This is a fundamental issue but all these validations just silently pass when the operational data is not yet available, so they don't block reading the config and I am not fixing them in this PR.
Some examples:
1. When setting LSP MTU for an instance (`isis_instance_lsp_mtu_modify`) or adding an interface to an area (`lib_interface_isis_create`), we validate that the interface MTU is larger than the …

Fix ISIS config batching

---

bgpd/bgp_updgrp_adv.c

Fix coverity warning CID 1505589: a temp bgp attr is freed while pointing at another attr's aspath.

bgpd: Fix SA warning about freeing an aspath

---

doc/user/ospf6d.rst

Fix issue found late in code review from PR #8727 .
@pushpasis addressing your comments:
1. > Nit: 'od'/'of', 'TYpe'/'Type',
Fixed here.
2. > Should we not have the #defines outside the structure definition?
I don't recall a rule about this and I know a few examples:
- https://github.com/FRRouting/frr/blob/master/lib/if.h#L236
- https://github.com/FRRouting/frr/blob/master/bgpd/bgp_updgrp.h#L248
- https://github.com/FRRouting/frr/blob/master/ospfd/ospf_interface.h#L194
3. > Is there a upper limit to the number of areas we support? If not this could become a performance issue.
> Though in real-world deployments there won't be hundreds of areas on the same ABR :)
In this case I think we should wait it become a problem before trying to solve it, it might need a more specialized / complex …

doc: fix typo in OSPFv3 NSSA

---

isisd/isis_cli.c

isisd: fix extra space in the mpls-te config output

---

doc/user/ospfd.rst

Multiple instances support multiple vrfs is our favorite. But in recent master, it doesn't work, so i do some investigation.
Users including me will be amazed by it.
Multiple instances of ospfd don't support vrf henceforth.

doc: add a note for ospfd instances

---

ospf6d/ospf6_message.c

When OSPFv3 router is configured in both default and non-default VRFs,
every packet destined to a non-default VRF is read twice. This makes it
impossible to establish neighborship because every DbDesc packet is
treated as duplicated and we end up infinitely exchanging DbDescs.
We should drop packets received in the default VRF if an interface we
received it on is bound to another VRF.
Same thing was done for OSPFv2 in 555691e.

ospf6d: fix duplicated packet read

---

doc/user/basic.rst
doc/user/bgp.rst

domainname is a merge conflict: it is duplicated, so delete it.
bgp content is a compille warning and wrongly display, so fix it.

doc: fix some compile warning

---

ospf6d/ospf6_lsa.c

Changed LSA checksum JSON output variable name from "checkSum" to
"checksum" to maintain consistency.
Signed-off-by: David Schweizer <dschweizer@opensourcerouting.org>

ospf6d: consistent checksum JSON output

---

doc/user/ospf6d.rst
lib/routemap.h
ospf6d/ospf6_asbr.c
ospf6d/ospf6_asbr.h
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6d.c
ospf6d/subdir.am

Adding the "clear ipv6 ospf6 command" . It resets
the ospfv3 datastructures and clears the database
as well as route tables. It resets the neighborship
by restarting the interface state machine.
If the user wants to change the router-id, this
command updates the router-id to the latest static
router-id and starts the neighbor formation with
the new router-id.

ospf6d: "clear ipv6 ospf6 process" command

---

isisd/isis_zebra.c
lib/zclient.c
lib/zclient.h
ospfd/ospf_interface.c
ospfd/ospf_zebra.c

Adding defensive code to the interface_link_params zebra callback
to check if the link params changed before taking action.

isisd, ospfd: update interface_link_params callback to check for change

---

doc/user/ipv6.rst
zebra/main.c
zebra/rib.h
zebra/rtadv.c
zebra/rtadv.h
zebra/zebra_router.c
zebra/zebra_router.h
zebra/zebra_vrf.c

Rework RA handling for vrf-lite scenarios.
Before we were using a single FD descriptor for polling
across multiple zvrf's. This would cause us to hit this
assert() in some bgp unnumbered and vrrp configs:
```
/*
* What happens if we have a thread already
* created for this event?
*/
if (thread_array[fd])
assert(!"Thread already scheduled for file descriptor");
```
We were scheduling a thread_read on the same FD for every zvrf.
With vrf-lite, RAs and ARPs are not vrf-bound, so we can just use one
rtadv instance to manage them for all VRFs. We will choose the default
VRF for this.
This patch removes the rtadv_sock altogether for zrouter and moves the
functionality this represented to the default VRF. All RAs will be
handled in the default VRF under vrf-lite configs with only one poll
thread …

zebra: rework RA handling for vrf-lite

---

pimd/pim_cmd.c

We had 3 different string output formats in various places.
Make them all the same.

pimd: make show ip mroute output consistent

---

ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6_zebra.c

This code was not fully completed when adding support for VRFs.

ospf6d: use per-vrf router id instead of one global

---

bgpd/bgp_evpn_vty.c

`oly` is already dereferenced two lines earlier and is always passed to
the function.

bgpd: fix coverity warning

---

bgpd/bgp_zebra.c

There are startup situations where we will attempt to connect to a remote
peer before bgp has received the v6 LL address.  If we do not have this address
we must not allow the connection to come up until we have one available to use
in those situations where we must have a v6 LL address.

bgpd: Ensure v6 LL address is available before establishing peering

---

ospf6d/ospf6_asbr.c
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6_zebra.c

In some situations the ospf6 router-id can change. Currently, LSAs that refers to the old router-id as advertising router remains in LS database.
These fixes reset the ospf area when the router-id modified and forbid zebra to change the router-id of ospf6 when one or more adjagency is Full.

ospf6d: fix LSAs remain in LSDB with an old router-id value

---

ospfd/ospf_vty.c

ospfd: show ip ospf route json does not shown metric and tag
[FRR OSPF] show ip ospf route json does not shown metric and tag.
In function show_ip_ospf_route_external, type 2 cost is not added in json.
Hence it is not displayed.
**Fix:**
1. Add type2cost in the json display
2. Tag was also missing, added that as well
Issue: #8729

ospfd: show ip ospf route json does not shown metric and tag

---

doc/user/pim.rst
pimd/pim_cmd.c
pimd/pim_instance.c
pimd/pim_msdp.c
pimd/pim_msdp.h
pimd/pim_nb.c
pimd/pim_nb.h
pimd/pim_nb_config.c
pimd/pim_vty.c
yang/frr-pim.yang

Small PR to add knobs to control MSDP connection timers per PIM instance.

pimd: allow MSDP timers to be configured

---

tests/topotests/msdp_mesh_topo1/r1/pimd.conf
tests/topotests/msdp_mesh_topo1/r2/pimd.conf
tests/topotests/msdp_mesh_topo1/r3/pimd.conf
tests/topotests/msdp_topo1/r1/pimd.conf
tests/topotests/msdp_topo1/r2/pimd.conf
tests/topotests/msdp_topo1/r3/pimd.conf
tests/topotests/msdp_topo1/r4/pimd.conf

Topotests tweaks to reduce MSDP tests converge time.
- MSDP mesh topo1: made no difference in a few runs locally.
- MSDP topo1: Some runs saved 60 seconds reducing the total run from 120 seconds to 60 seconds, depending on how fast the routers started.

topotests: speed up MSDP convergence speed

---

bgpd/bgp_nht.c

When bgp peers with ipv6 link local addresses, it may receive a
BGP update with next-hop containing both LL and GA information.
By default, nexthop tracking applies to GA, and ignores presence
of LL, when both addresses are present. This is a problem for
resolving GA as next-hop as the next-hop information can be solved
by using the LL address only.
The solution consists in defaulting the nexthop ipv6 choice to LL
when available, and moving back to GA if a route-map is locally
configured at inbound.

bgpd: nht unresolved with global address next-hop

---

tests/topotests/lib/common_config.py
tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py
tools/generate_support_bundle.py
vtysh/vtysh.c
vtysh/vtysh.h
vtysh/vtysh_config.c
vtysh/vtysh_main.c

Speedup (large topo): OLD: ~6 minutes NEW: ~1 second.
- Collect from each node in parallel
- On each node collect each "proc" support in parallel
- For each "proc" only call vtysh once with all commands
Bug fixes:
- output was broken, a dump of python "repr" format of str.
- sub-directory test name was the same internal pytest function name
for any test, and not the actual test name.
Needed timestamp to replace old gather bundle behavior so:
vtysh: add CLI timestamp '-t' flag
Example output:
flk# show version
% 2021/06/29 00:25:01.562
FRRouting 8.1-dev-my-manual-build (flk).

Speedup support bundles, fix bugs, add CLI timestamp

---

zebra/zebra_vty.c

Related: https://github.com/FRRouting/frr/issues/2555

zebra: Do not escape forward slashes for `show ip route json`

---

pathd/path_pcep_config.c
pathd/path_pcep_pcc.c

pathd: If pce ret no-path to PcReq don't retry PcReq nor delegate(1/2)
Based in RFC 5440 @4.2.2 ""...after a no-path , the pcc may decide" and RFC
8231 FRRouting#5.8.3 "... pcc must not set PcReq after path is delegated"
So will not (try) to delegate the path with no-path neither must do
further retries.
pathd: Handle srp_id correctly (2/2)
Based on
RFC 8231 FRRouting#5.8.3 PcUpd
RFC 8181 FRRouting#5.1 Pcinit

pathd : Better RFC complain for two cases, no_path answer and srp_id handle

---

ospf6d/ospf6_message.c

fix some coverity errors in latency warning calculations
correctly protect debugs using the new SEND/SEND_HDR scheme
replace stray inet_ntop  calls in ospf6_write with correct %pI6  formatters

Ospf6 packet debug

---

ospf6d/ospf6_asbr.c

Issue: Crash observed when LSAs are removed from LSDB after max age
when there is no area configured.
(gdb) bt
0  raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
1  0x00007fdb190548bc in core_handler (signo=6, siginfo=0x7ffdd2f5a470, context=<optimized out>) at lib/sigevent.c:262
2  <signal handler called>
3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
4  0x00007fdb185ad921 in __GI_abort () at abort.c:79
5  0x00007fdb1907f199 in _zlog_assert_failed (xref=xref@entry=0x55f30902aa20 <_xref.21999>, extra=extra@entry=0x0) at lib/zlog.c:581
6  0x000055f308dc4f78 in ospf6_asbr_lsa_remove (lsa=0x55f30a7546d0, asbr_entry=0x0) at ospf6d/ospf6_asbr.c:696
7  0x000055f308dd8f0d in ospf6_lsdb_remove (lsa=0x55f30a7546d0, lsdb=lsdb@entry=0x55f30a73d300) at …

ospf6d: Fix crash in ospf6_asbr_lsa_remove at ospf6d/ospf6_asbr.c:696

---

lib/systemd.c

There's nothing that can be done here with an error.  Try to make
Coverity understand that this is intentional.
(I don't know if the `(void)` will actually fix the coverity warning,
but I don't really have a better way to figure it out beyond just
getting this merged and waiting for a result...)

lib: fix coverity unused result warning

---

lib/zclient.c

We are sending up to ZAPI_MESSAGE_OPAQUE_LENGTH but checking
for one less.  We know the data will fit in it to that size.
Also we have asserts on the write to ensure we don't go over
it
Fixes: #8995

lib: Allow ZAPI_MESSAGE_OPAQUE_LENGTH length of data

---

zebra/zebra_evpn_mh.c

zebra was crashing when the command was run on a non-existent VNI.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
root@torm-12:mgmt:~# net show evpn es-evi vni 16777215
VNI 16777215 doesn't exist
root@torm-12:mgmt:~# net show evpn es-evi vni 16777215 detail
VNI 16777215 doesn't exist
root@torm-12:mgmt:~# net show evpn es-evi vni 16777215 json
[
]
root@torm-12:mgmt:~# net show evpn es-evi vni 16777215 detail json
[
]
root@torm-12:mgmt:~#
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Ticket: CM-30232
Signed-off-by: Anuradha Karuppiah <anuradhak@cumulusnetworks.com>
Closes https://github.com/FRRouting/frr/issues/9008

zebra: [7.5] handle "show evpn es-evi" a non-existent VNI

---

ospf6d/ospf6_message.c

Fix: The fix is to call ospf6_write to send the packet immediately to all neighbors
Signed-off-by: kssoman <somanks@gmail.com>

ospf6d : Send LSA update immediately when ospf instance is deleted

---

ospf6d/ospf6_spf.c

This code has been wrong ~ever (according to git history). There are 3
conditional blocks with the added assertion that both the LSA and the
vertex being checked can't both be network LSAs.
The third block is clearly assuming both LSA and vertex are router
LSAs b/c it is accessing the backlink and lsdesc as router lsdesc's also
making sure both are p2p links (which they would have to be to point at
each other).
The programming error here is that (A && B) == False does NOT imply !A,
but the code is written that way.
So we end up in the third block one of LSA or vertex being network LSAs
rather easily (whenever that is the case and the desc isn't the backlink
being sought).
This was caught by ASAN b/c the lsdesc and backlinks are being accessed
(> 4 byte field offsets) as if they were …

ospf6d: fix backlink check

---

doc/user/ospf6d.rst
lib/prefix.h
ospf6d/ospf6_asbr.c
ospf6d/ospf6_zebra.c
ospfd/ospf_asbr.c
ospfd/ospf_flood.c
ospfd/ospf_lsa.c
ospfd/ospf_lsa.h
ospfd/ospf_vty.c
ospfd/ospf_zebra.c

Summary
---
Changes
- Remove some code by removing duplicated functionality: use `is_default_prefix` instead of implementing it again
- Document OSPFv3 debug commands
- Rework default-information configuration show code
I found these while working on OSPFv3 so I want to try to get these merged before my next PR.
Note
----
I tried to use the `transparent union` feature for `is_default_prefix` to accept all kinds of `struct prefix *` but the CI failed on all its variants. You can see all my attempts here:
- https://github.com/opensourcerouting/frr/commit/dc40fc1fd5a5abcbcb7b06ecebf59136d4058dc9
- https://github.com/opensourcerouting/frr/commit/36d4f18514bfc0db94d8d6e6835f052649ae90e0
- https://github.com/opensourcerouting/frr/commit/75b79cc05e0f03dda1eacaad941102c78e320ef0
The analyzer …

doc,lib,ospfd,ospf6d: trivial improvements

---

staticd/static_routes.c

As to the command: 'ip route 1.1.1.1/32 Null0 nexthop-vrf vrf1'                  
The "Null0" interface status should not depend on status of vrf interface.       
If vrf1 is down, this command will display as:                                                                                                                                                        
ip route 1.1.1.1/32 blackhole nexthop-vrf vrf1                                   

staticd: fix bug of Null0 wrongly converted into blackhole in running config

---

bgpd/bgp_route.c

Before returning an error, unlock bgp dest which is locked by
bgp_node_lookup().

bgpd: Don't forget bgp_dest_unlock_node for bgp_static_set()

---

bgpd/bgpd.c

There is no peer_af allocated in `peer_activate`. Trying to delete
the structure just results in an no-op and a error return value.
The error message "couldn't delete af structure for peer" is
unexpected.

bgpd: Do not delete peer_af structure when deactivating peer-group from an address-family.

---

ospf6d/ospf6_interface.c

There's a delay in FreeBSD between issuing a command to leave a
multicast group and an actual leave. If we execute "no router ospf6" and
"router ospf6" fast enough, we can end up in a situation when OS
performs the leave later than it performs the join and the interface
remains without a multicast group.
Instead of counting on a one second delay, we must wait until the
interface actually leaves the group.

ospf6d: fix freebsd mcast group issues

---

bgpd/bgp_fsm.c

Problem: Sometimes the configured Local GR state is not reflected in
show command and peer node. This is causing failures in few of the
BGP-GR topotests.
RCA: This problem is seen when the configuration of local GR state
happens when the BGP session is in OpenSent state and  moves to
Established after the configuration is complete.
When the session gets established, we move the GR state value from stub peer
to the config peer. This will result in overriding the GR state to
previous value.
Fix: The local GR state is modified only through CLI configuration and
does not change during BGP FSM transition. In this case it is not necessary
to transfer the GR state value from stub peer to config peer. This way we
can ensure that always the most recent config value is present in peer …

bgpd: Inconsistency in Local BGP GR state.

---

bgpd/bgp_zebra.c

When setting bgp configuration using peers referencing link local
ipv6 addresses, the bgp should be able to handle incoming bgp
connections, and find out the appropriate interface where the
connection comes from.
ipv6 link local sessions work by using bgp unnumbered interfaces
config, but it does not work if we have a shared media with
multiple potential link local ipv6 addresses on the network.
The fix consists in finding out the appropriate interface, when
the local configuration references a link local ipv6 addresses.
note: this change does not solve the ability for such config to
create an outgoing connection to remote peer (as the link local
ipv6 address config does not indicate which interface to use).

bgpd: associate correct nexthop when using peer link-local

---

bgpd/bgp_evpn.c
tools/coccinelle/hash_compare_null_values_check.cocci

Related: https://github.com/FRRouting/frr/pull/9036

bgpd: Do not check for NULL values for vni_hash_cmp()

---

doc/developer/workflow.rst

This is essentially just a write-up of the conclusions I've been working by.  I think it's valuable to just get this down into our workflow doc to make people aware that usability is an important concern.  Telling users to rebuild FRR to change a `./configure` option is horrible UX.  Restarting FRR to change a command line option is annoying at best and a service interruption at worst.
As said in the `.. note::` at the top of this block, I'm not trying to make these rules, just trying to point out that UX is a factor that should be considered.  It's tempting to take the "easy way out" and make things command line options or build options — less cases to cover, no reconfiguration, etc.  Sometimes it's the only feasible option.  But please at least try reasonably hard :smiley:

workflow: add guidelines for config knobs

---

isisd/isis_lsp.c
isisd/isis_lsp.h
isisd/isis_spf.c
isisd/isisd.c
isisd/isisd.h

There are three commits in this series:
The first and the second fix sending and receiving the attached bit.
Instead of checking for the L2 adjacencies formed by the router that
sends/receives the attached bit, the current code checks whether we
have other L2 routers configured on the devices. This is incorrect – just
imagine how it could work in the simplest case when we have a single ISIS
router configured on the device. I think the initial author of this functionality
got confused by the fact that what is named `isis_area` in the code
is actually an ISIS router.
The third commit fixes the IS type that we set in the LSPs – it represents
a type of router, not a type of circuit. Setting an incorrect IS type in the LSPs
prevents neighbors from correctly processing the attached bit we send. …

isisd: fix setting of the attached bit

---

bgpd/bgp_conditional_adv.c
bgpd/bgp_conditional_adv.h
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst

Adds a knob that sets the time between loc-rib scans for conditional
advertisement.
I chose the range (5-240) because 1 second seems dumb and too easy to
hurt yourself at even moderate scale, 5 seconds you can still hurt
yourself but I could see a use case for it, and 4 minutes should be
enough for anyone (tm)
Supersedes #8825 

bgpd: add knob to config cond-adv scanner period

---

doc/user/bgp.rst

Replaces next-hop-self keyword "all" with "force" to match the CLI.
Also mentions third-party next-hops will be bypassed by next-hop-self.

doc: replace next-hop-self all with force

---

bgpd/bgp_bfd.c

Test the BFD config pointer before trying to free the session as it might not exist.
To Reproduce
---
```sh
vtysh -c 'conf t' -c 'router bgp 65000' \
-c 'neighbor 10.10.10.10 remote-as internal' \
-c 'neighbor 10.10.10.10 bfd' \
-c 'no neighbor 10.10.10.10 bfd' \
-c 'no neighbor 10.10.10.10 bfd'
```

bgpd: fix crash during configuration removal

---

tests/topotests/conftest.py
tests/topotests/docker/frr-topotests.sh
tests/topotests/lib/topogen.py
tests/topotests/lib/topotest.py

TMUX and Screen support when running topotests inside docker. This
allows the gdb, shell and vtysh features to correctly work even when
running the tests inside docker.
Add options:
--asan-abort :: aborts the process on ASAN errors
--strace-daemons :: strace some or all daemons

tests: add triage features: strace, asan-abort, and shells/vtys/gdbs for docker runs too

---

configure.ac

Change option text from `--undefined-sanitizer` to `--enable-undefined-sanitizer`, or else the option is not recognized.
Signed-off-by: Colin Sames <colin.sames@haw-hamburg.de>

configure.ac: fix help text to --enable-undefined-sanitizer

---

ospf6d/ospf6_message.c

Somehow the hello message debugging code slipped outside the debug guard. Lets just remove it.
Acidentally introduced by this commit: https://github.com/FRRouting/frr/commit/3d9680313e663a6f906db9cf87b568cb25b62b9b
**NOTE** this is not present in FRR 8.0.
Sample
---
This PR removes the following unguarded debug messages:
```
2021/07/14 17:52:55 OSPF6: [GNVTE-A64WG]     OSPFv3 Type:1 Len:40 Router-ID:10.254.254.1
2021/07/14 17:52:55 OSPF6: [RA6WJ-XZB2C]     Area-ID:0.0.0.0 Cksum:0 Instance-ID:0
2021/07/14 17:52:55 OSPF6: [K6N0H-3Q3W7]     I/F-Id:3 Priority:1 Option:--|R|-|--|E|V6
2021/07/14 17:52:55 OSPF6: [MFC3G-8KW9N]     HelloInterval:2 DeadInterval:8
2021/07/14 17:52:55 OSPF6: [SMPBA-YB7BT]     DR:10.254.254.1 BDR:0.0.0.0
```

ospf6d: remove extra debug message

---

bgpd/bgp_attr.c
bgpd/bgp_community.c
bgpd/bgp_ecommunity.c
bgpd/bgp_lcommunity.c
bgpd/bgpd.c

the realloc man page:
If ptr is NULL, then the call is equivalent to malloc(size)
This should be sufficient for our needs to not have to have
XMALLOC and XREALLOC

bgpd: XREALLOC handles NULL properly

---

tests/topotests/bgp_conditional_advertisement/r1/bgpd.conf
tests/topotests/bgp_conditional_advertisement/r2/bgpd.conf
tests/topotests/bgp_conditional_advertisement/r3/bgpd.conf

~15min vs. ~1min.
Before:
```
1 passed, 1 skipped in 908.61 seconds
```
After:
```
1 passed, 1 skipped in 82.94 seconds
```

tests: Reduce bgp_conditional_advertisement converge time 10x

---

zebra/zapi_msg.c
zebra/zebra_rnh.c
zebra/zebra_rnh.h

In the reachability code we auto pass back the fully resolved
nexthops.  Modify the ZEBRA_IPV4_NEXTHOP_LOOKUP_MRIB code
to do the exact same thing so that the zclient_lookup_nexthop
code does not need to recursively look for the data that
zebra already has.

pimd: When passing lookup information back pass the fully resolved

---

zebra/zebra_nhg.c

At some point we broke the ifp pointer for nhe->ifp such
that it was pointing to an interface even in groups/recurisve
instances.
Add checks here to make it again so that we only set the ifp
pointer if it is a fully resolved singleton NHE.

zebra: fix ifp pointer for groups/recursives

---

doc/user/bgp.rst

This was apparently missing from our documentation.
Let's add it in.

doc: Document the maximum-paths command for bgp

---

bgpd/bgp_community_alias.c
bgpd/bgp_community_alias.h
bgpd/bgp_route.c
bgpd/bgp_vty.c

Add a bit of code to allow for auto-completion of the community
alias command when attempting to use it for show commands.
example:
eva(config)# bgp community alias 11:22 FOO
eva(config)# end
eva# show bgp ipv4 uni alias
ALIAS_NAME  BGP community alias
FOO

bgpd: Allow for auto-completion of community alias's created

---

bgpd/bgp_route.c

Seems missed grammarly review for the reason "as-path contains our own AS;"

bgpd: Drop unnecessary chars for filtered reason

---

pimd/pim_igmp.c
pimd/pim_igmp.h

1. IGMPv3 packets with invalid TTL should be dropped.
Test Case ID: 4.10
TEST_DESCRIPTION
Every IGMP message described in this document is sent with an IP
Time-to-Live of 1 (Tests that IGMPv3 Membership Report Message
conforms to above statement)
TEST_REFERENCE
NEGATIVE: RFC 3376, IGMP Version 3, s4 p7 Message Formats
Issue: #9070
2. IGMPv3 packets with invalid TOS should be dropped.
Test Case ID: 4.10
TEST_DESCRIPTION
Every IGMP message described in this document is sent with
IP Precedence of Internetwork Control (e.g., Type of Service
0xc0)
(Tests that IGMPv3 Membership Query Message conforms to
above statement)
TEST_REFERENCE
NEGATIVE: RFC 3376, IGMP Version 3, s4 p7 Message Formats
Issue: #9071

pimd: IGMPv3 conformance fixes for invalid TTL and invalid TOS

---

ospfd/ospf_vty.c

Description:
Ospf process crashes upon giving 'clear ip ospf neighbor' with
self routerId. It is asserting if it is a self neighbor in ospf
neighbour kill event processing.
Added a check to validate the provided router-id is self
router-id.
Config:
--------
frr# 
frr# show ip ospf  neighbor 
Neighbor ID     Pri State           Dead Time Address         Interface                        RXmtL RqstL DBsmL
8.8.8.8           1 Full/DR           35.665s 10.1.1.110      ens192:10.1.1.220                    0     0     0
frr# 
frr# 
frr# do show ip ospf  
OSPF Routing Process, Router ID: 10.112.156.220
Supports only single TOS (TOS0) routes
This implementation conforms to RFC2328
RFC1583Compatibility flag is disabled
OpaqueCapability flag is disabled
Initial SPF scheduling delay 0 millisec(s) …

ospfd: ospfd crash while giving 'clear ip ospf neighbor'

---

ospf6d/ospf6_abr.c

In RFC 2328 OSPF Version 2, Section 12.4.3.1 "Originating summary-LSAs
into stub areas" mentions that the stub areas should not import external
routes and instead should generate a 'default summary-LSA' set to
default destination.
> In a stub area, instead of importing external routes
> each area border router originates a "default summary-
> LSA" into the area. The Link State ID for the default
> summary-LSA is set to DefaultDestination, and the metric
> set to the (per-area) configurable parameter
> StubDefaultCost.  Note that StubDefaultCost need not be
> configured identically in all of the stub area's area
> border routers.
**note** OSPFv3 RFC 5340 Section 2.10 "Stub/NSSA Area Support" only mentions that the functionality is mostly the same.

ospf6d: always generate default route for stubs

---

zebra/kernel_socket.c

Notice when a ip address on a bsd interface is considered
an alias, let's mark the connected prefix we generate as
a SECONDARY.

zebra: Mark some bsd interface prefixes as SECONDARY

---

bgpd/bgp_evpn.c
bgpd/bgp_fsm.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_nht.c
bgpd/bgp_nht.h
bgpd/bgp_route.c
tests/topotests/bgp_basic_functionality_topo1/test_bgp_basic_functionality.py

Some BGP updates received by BGP invite local router to
install a route through itself. The system will not do it, and
the route should be considered as not valid at the earliest.
This case is detected on the zebra, and this detection prevents
from trying to install this route to the local system. However,
the nexthop tracking mechanism is called, and acts as if the route
was valid, which is not the case.
By detecting in BGP that use case, we avoid installing the invalid
routes.

bgpd: prevent routes loop through itself

---

pathd/path_pcep_cli.c

Use localtime_r() instead of localtime() in pathd.

pathd: don't use localtime

---

lib/command.c
vtysh/vtysh.c

```
vtysh: fix exit from zebra-only nodes
When exiting from link-params and pseudowire nodes, we were sending exit
command to all VTYSH_INTERFACE daemons. This led to a desynchronized
state in vtysh and daemons other then zebra. We must send exit command
only to zebra.
```
```
lib, zebra: fix exit from link-params node
When exiting from link-params node, we must not decrement xpath_index
because it is not incremented when entering the node.
```
Fixes #317.

vtysh, lib, zebra: fix exit from link-params and pseudowire nodes

---

Makefile.am
bgpd/subdir.am
configure.ac
fpm/subdir.am
grpc/subdir.am
isisd/subdir.am
ldpd/subdir.am
lib/subdir.am
mlag/subdir.am
ospf6d/subdir.am
ospfclient/subdir.am
ospfd/subdir.am
pathd/subdir.am
qpb/subdir.am
ripd/subdir.am
zebra/subdir.am

To quote the commit messages:
> like the other automake variables, setting `xyz_LDFLAGS` causes `AM_LDFLAGS` to be ignored for `xyz`.  For some reason I had in my mind that automake doesn't do this for LDFLAGS, but... it does. (Which is consistent with `_CFLAGS` and co.)
and
> libtool does not understand `-coverage` with a single dash.  Official gcc docs also say `--coverage` rather than `-coverage`.  (clang lists both.)
Fixes: #9034

build: fix LDFLAGS confusion & gcov

---

zebra/if_netlink.c

When port was removed from last access vlan, the linux kernel won't send any vlan info in the netlink message, it might affect that the evpn mh not withdraw EAD-EVI routes.

zebra: trigger remove all access vlans info for access port

---

bgpd/bgp_rpki.c

The rpki sub-node was outputting 2 spaces instead
of 1 space.  Let's fix that to be consistent with
the rest of our code.
Fixes: #2738

bgpd: Fix rpki spacing to be 1 for indentation

---

vtysh/vtysh.c

vtysh was unable to distinguish between end and ena.  The
code can now do so:
sharpd@eva ~/frr5 (master)> sudo vtysh/vtysh -u sharpd
Hello, this is FRRouting (version 8.1-dev).
eva> e
% Ambiguous command: e
eva> en
% Command not allowed: enable
eva> ena
% Command not allowed: enable
eva> enab
% Command not allowed: enable
eva> enabl
% Command not allowed: enable
eva> enable
% Command not allowed: enable
eva> enb
% Unknown command: enb
eva> enc
% Unknown command: enc
eva> end
% Unknown command: end
eva> ene
% Unknown command: ene
eva> quit
Fixes: #2296

vtysh: Handle `en` better when in -u for vtysh

---

zebra/zebra_vxlan.c

Currently 'show evpn rmac vni .. mac .. json' includes fields for
localSequence and remoteSequence, which are misleading since they
aren't applicable to a macs in the IP-VRF mac table (RMAC).
This removes the localSequence + remoteSequence fields from the output.

zebra: Remove MM seq from evpn rmac json output

---

bgpd/bgp_route.c

Before returning an error, unlock bgp dest which is locked by
bgp_node_lookup().

bgpd: [8.0] Don't forget bgp_dest_unlock_node for bgp_static_set()

---

bgpd/bgp_route.c

[8.0] bgpd: Unlock bgp_dest for bgp_distance_unset if distance does not match (backport #8976)

---

vtysh/vtysh.c

Recent change in d1b287e only fixed the problem for 3-letter words.
We were still displaying error for longer words starting with "ena":
```
nfware> enac
% Command not allowed: enable
nfware> enad
% Command not allowed: enable
nfware> enaena
% Command not allowed: enable
```
If we don't allow "enable" command in user mode, why add it at all?

vtysh: another take at "enable" in vtysh user mode

---

bgpd/bgp_route.c
bgpd/bgp_routemap.c

It might be a case when a partial match is hit and this needs to be fixed.

bgpd: Use strcmp comparing BGP alias with an actual entered alias

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_flood.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_intra.c
ospf6d/ospf6_nssa.c
ospf6d/ospf6_route.c
ospf6d/ospf6_route.h

Just the usual batch of small pieces you trip over while working on other things.  Mostly fixes.  Please refer to the individual commits/descriptions.
```
ospf6d: use OSPF6_INTERFACE_LOOPBACK state
The OSPF6_INTERFACE_LOOPBACK interface state wasn't entered anywhere,
even if the interface was OSPF6_IFTYPE_LOOPBACK.  Fix.
```
``` 
ospf6d: don't create Adv-ID:0.0.0.0 LSAs at start
When ospf6d comes up, it gets interface and address state before it
decides on its router ID.  This results in a bunch of LSAs with
advertising router ID 0.0.0.0 in the LSDB.  Not quite right.
There's a whole bunch of paths leading to this, so just drop the LSA in
ospf6_lsa_originate.  The router-ID change causes everything to be
readvertised anyway (... but the delete doesn't catch the 0.0.0.0 stuff
because the …
```

ospf6d: small batch of random fixes/improvements

---

zebra/redistribute.c

Current code was allowing redistribution of kernel routes from
the non-default non vrf tables once FRR was already up and running.
In the case where we add `redistribute kernel` in an upper level
protocol we never consider the non-default vrf or non-vrf tables
so it is never accepted.
In the case where a kernel route is added after `redistribute kernel`
is already in place we were never looking at the fact that the
route was in a non-default non-vrf table.  This code fixes
that issue.
Fixes: #9073
Signed-off-by: Donald Sharp sharpd2nvidia.com>

zebra: Do not allow redistribution for non-vrf tables

---

zebra/zapi_msg.c
zebra/zebra_mpls.c
zebra/zebra_mpls.h
zebra/zebra_vrf.h
zebra/zserv.c

When a vrf label is created by a client and the client disconnects
we should clean up any vrf labels associated with that client.
eva# show mpls table
Inbound Label  Type   Nexthop  Outbound Label
-----------------------------------------------
1000           SHARP  RED      -
eva# exit
sharpd@eva ~/f/zebra (label_destruction)> ps -ef | grep frr
root     4017793       1  0 13:57 ?        00:00:00 /usr/lib/frr/watchfrr -d -F datacenter --log file:/var/log/frr/watchfrr.log --log-level debug zebra bgpd ospfd isisd pimd eigrpd sharpd staticd
frr      4017824       1  0 13:57 ?        00:00:00 /usr/lib/frr/zebra -d -F datacenter --log file:/tmp/zebra.log -r --graceful_restart 60 -A 127.0.0.1 -s 90000000
frr      4017829       1  0 13:57 ?        00:00:00 /usr/lib/frr/bgpd -d -F datacenter -M …

zebra: On client shutdown cleanup any vrf labels associated with it

---

doc/user/ospf6d.rst
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_intra.c
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6_zebra.c

Revert #8622; see comments there.
While the revert doesn't fix this, it backs out code that isn't part of the correct solution.  Also I'd rather crash one router than (possibly) break the network.

ospf6d: revert PR #8622

---

pimd/pim_igmp.c
pimd/pim_igmp.h

This commit is to correct the order in which the fields are
accessed while verifying it. First the fields should be
verified, and if it is valid then access it.

pimd: Validate the fields before accessing it

---

pimd/pim_igmp.c

-1 is true when casted to bool.

pimd: fix incorrect bool returns

---

ospfd/ospf_network.c

Let's be less radical. There's no reason to stop the whole daemon when
there's a socket creation error in a single VRF. The user can always
restart this single VRF to retry to create a socket.

ospfd: don't exit when socket is not created

---

tests/topotests/bgp_basic_functionality_topo1/test_bgp_basic_functionality.py

`format` can't be used per-line when we have a multiline string.
This was recently broken in 3881d05.

tests: fix invalid multiline format

---

bgpd/bgp_vty.c

The bgp ipv6 unicast node should be called `bgp ipv6 unicast`
to make it consistent with other nodes where we list the afi/safi

bgpd: Mark the node as the correct type for bgp ipv6 unicast

---

bgpd/bgp_damp.c

bgp_damp_info_unclaim already calls bgp_reuselist_del. We must not call
it again here.
Fixes #9046.

bgpd: fix double free in dampening code

---

pimd/pim_msdp.c

This leads to a crash when you use "show run" after deleting the group.

pimd: fix missing list remove when deleting mesh group

---

bgpd/bgp_damp.c
bgpd/bgp_damp.h
bgpd/bgp_route.c

This causes a crash using `clear ip bgp dampening <prefix>`.

bgpd: Drop double-pointer for bgp_damp_info_free()

---

ospf6d/ospf6_nssa.c

RCA: When Type-7 LSA is updated, the LSDB is searched, if the
LSA is present in the LSDB then the LSA is updated with next
sequence number and if not then it is originated with the
INITIAL sequence number.
Here while originating Type-7 LSA Process Level LSDB is searched
for instead of area level LSDB.
Fix: Search in the area level LSDB and not in the process level.
Fixes #9099

ospf6d: Type-7 LSA originated with wrong sequence number

---

bgpd/bgp_damp.c

One more crash in dampening code...
When bgp_damp_withdraw is called, if there's already a BDI structure,
bgp_damp_info_claim is called to re-assign the bdi->config in case it
was changed. The problem is that bgp_damp_info_claim actually removes
the BDI from the reuse list of the old config and never adds it to the
reuse list of the new config. We must do this to prevent the crash
because all the code assumes that BDI is always in some list.

bgpd: fix missing list add in dampening

---

bgpd/bgp_updgrp_adv.c
tests/topotests/bgp_default_route_route_map_match_set/r1/bgpd.conf
tests/topotests/bgp_default_route_route_map_match_set/test_bgp_default-originate_route-map_match_set.py
tests/topotests/bgp_default_route_route_map_set/r1/bgpd.conf
tests/topotests/bgp_default_route_route_map_set/test_bgp_default-originate_route-map_set.py

This is a backport combination of #8860 and #8920.
The second one fixes an SA warning introduced by the first one, so they should be merged together, that's why I am not using Mergify.

[8.0] backport 8860 + 8920

---

tests/topotests/simple_snmp_test/test_simple_snmp.py

The test_simple_snmp.py test starts bgp, zebra and snmpd at the
same time.  Then zebra configuration is read in and interface
addresses are applied.  If snmp start slower than zebra
the snmp process can properly get it's ip address to bind to
if it is faster than zebra, it will fail.  Ensure that the
test has addresses before we start daemons.

tests: Set addresses before we use snmpd

---

doc/user/bgp.rst

the code-block was jumbled and not displaying properly.
Reported by: Drew Bloechl

doc: Fix code-block display for example shell commands

---

bgpd/bgp_damp.c
bgpd/bgp_damp.h
bgpd/bgp_route.c

Overall this PR aims to fix multiple memory leaks in the dampening code. All the leaks are regressions in 8.0 and I want this code to be backported even though there are a couple of cleanup-only commits. It is difficult to fix the leaks without doing the cleanup.
Please, check individual commits for descriptions.
The last commit changes the SLIST to a LIST. The dampening code was always using a double-linked list before the rework in 8.0 that introduced all those crashes and memory leaks. As there are frequent removals from the list, using a single-linked list is actually a real performance regression so changing it back to double-linked list should be considered as a fix.

bgpd: fix various memory leaks in dampening

---

zebra/zebra_fpm.c

There exists some rare situations where fpm will attempt
to send a route update with no valid nexthops.  In that
case an assert would be hit.  This is not good for
trying to keep your routing daemons up and running
when we can safely just recover the situation.
Fixes #7588
Signed-off-by: batmancn <batmanustc@gmail.com>
<fixed commit message, and used zlog_err>

zebra: bugfix of error quit of zebra, due to no nexthop ACTIVE

---

bgpd/bgp_damp.c

One more crash in dampening code...
When bgp_damp_withdraw is called, if there's already a BDI structure,
bgp_damp_info_claim is called to re-assign the bdi->config in case it
was changed. The problem is that bgp_damp_info_claim actually removes
the BDI from the reuse list of the old config and never adds it to the
reuse list of the new config. We must do this to prevent the crash
because all the code assumes that BDI is always in some list.

bgpd: [8.0] fix missing list add in dampening

---

tests/topotests/zebra_rib/test_zebra_rib.py

When running this test on a locally loaded system I am seeing the
static route as `queued` still after 1 second.  Let's just blanket
increase the timeout to something longer to give a very loaded system
more time to install the route.
Output on my test system when it was loaded:
INFO     topolog.r1:topogen.py:880 vtysh result:
{
"4.5.1.0/24":[
{
"prefix":"4.5.1.0/24",
"prefixLen":24,
"protocol":"static",
"vrfId":0,
"vrfName":"default",
"selected":true,
"destSelected":true,
"distance":1,
"metric":0,
"queued":true,
"table":254,
"internalStatus":8,
"internalFlags":73,
"internalNextHopNum":1,
"internalNextHopActiveNum":1,
"uptime":"00:00:00",
"nexthops":[
{
"flags":1,
"ip":"192.168.216.3",
"afi":"ipv4",
"interfaceIndex":11,
"interfaceName":"r1-eth6",
"active":true,
"weight":1
}
]
},
I suspect …

tests: Increase timeout for loaded systems

---

tests/topotests/bgp_evpn_mh/test_evpn_mh.py
tests/topotests/lib/scapy_sendpkt.py

tests: add scapy_sendpkt.py util, replace arping use with it

---

doc/user/bgp.rst

Too many colons in a line in the bgp doc source file.

doc: fix bgp user doc colons

---

tests/topotests/bgp_listen_on_multiple_addresses/test_bgp_listen_on_multiple_addresses.py
tests/topotests/lib/topojson.py

- A more general fix for the bgp listener test which requires interfaces be
configured in the kernel when the bgpd daemons are launched.

tests: add early interface config for topojson and fix test

---

lib/frr_zmq.c

When running `make check` against a build that zeromq enabled
the test_zmq unit test was crashing.  The commit:
e08165def1c62beee0e87385e37ea5f12ca0f9b9
Introduced this crash.  Removing the part of the commit
that was causing the crash in the test.  This is mainly
to get `make check` working again for those people using
zeromq in their builds.
Fixes: #9176

lib: prevent crash in make check in some situations

---

bgpd/bgp_routemap.c
doc/developer/scripting.rst
lib/command.c
lib/frrlua.c
lib/frrlua.h
lib/frrscript.c
lib/frrscript.h
tests/lib/script1.lua
tests/lib/test_frrscript.c

- function based hook calls
- almost rewrite of scripting documentation

Function-based Lua hook call

---

lib/vrf.c
zebra/zebra_netns_notify.c

Don't clear VRF's user-configured flag when netns is deleted.
Also avoid leaking wild pointer of VRF in northbound, which can be reproduced by:
1. Add a netns.
```
```
2.  Create northbound VRF config node.
```
(config)# vrf test
```
3. Delete the netns and add one with the same name.
```
```
4. Configure something that accesses the config node entry of the VRF, and zebra crashes.
```
(config)# vrf test
(config-vrf)# vni 100
```

lib, zebra: Preserve user-configured VRF on netns deletion

---

bgpd/bgp_open.c

If we don't advertise any capabilities (dont-capability-negotiate), we
shouldn't set msg size to 65k only if received this capability from another
peer.
Before:
```
~/frr# vtysh -c 'show ip bgp update-group' | grep 'Max packet size'
Max packet size: 65535
```
After:
```
~/frr# vtysh -c 'show ip bgp update-group' | grep 'Max packet size'
Max packet size: 4096
```

bgpd: Set extended msg size only if we advertised and received capability

---

babeld/babel_interface.c
eigrpd/eigrp_cli.c
isisd/isis_circuit.c
lib/if.c
lib/if.h
nhrpd/nhrp_vty.c
ospf6d/ospf6_interface.c
ospfd/ospf_vty.c
pbrd/pbr_vty.c
pimd/pim_cmd.c
ripd/rip_interface.c
ripngd/ripng_interface.c
vrrpd/vrrp_vty.c
zebra/interface.c

The only difference in daemons' interface node definition is the config
write function. No need to define the node in every daemon, just pass
the callback as an argument to a library function and define the node
there.

*: cleanup interface node installation

---

zebra/zebra_dplane.c

Use strlcpy instead of memcpy for safety in dplane rule init api. This was the only place we weren't using strlcpy(); can't see any reason not to.

zebra: use strlcpy in dplane_rule_init

---

bgpd/bgp_fsm.c
bgpd/bgpd.c

Currently, the following sequence of events between peers could
result in erroneous capability reports on the peer
with enabled dont-capability-negotiate option:
- having some of the capabilities advertised to a bgp neighbor,
- then disabling capability negotiation to that neighbor,
- then resetting connection to it,
- and no capabilities are actually sent to the neighbor,
- but "show bgp neighbors" on the host still displays them
as advertised to the neighbor.
There are two possibilities for establishing a new connection
- the established connection was initiated by us with bgp_start(),
- the connection was initiated on the neighbor side and processed by
us via bgp_accept() in bgp_network.c.
The former case results in "show bgp neighbors" displaying only
"received" in capabilities, as …

bgpd: Clear capabilities field when resetting a bgp neighbor

---

bgpd/bgp_damp.c
bgpd/bgp_damp.h

The main reasons:
* bgpd stops responding after 90 seconds when more than 200 entries in reuselist; (SLIST => LIST conversion)
* new crash reported with full feed with bgp_damp_info_free().

bgpd: Revert a couple of BGP dampening related commits

---

doc/user/zebra.rst
zebra/zebra_routemap_nb_config.c

1. This check is absolutely useless. Nothing keeps user from deleting
the address right after this check.
2. This check prevents zebra from correctly reading the user config with
"set src" because of a race with interface startup (see #4249).
3. NO OPERATIONAL DATA USAGE ON VALIDATION STAGE.
Fixes #7319.

zebra: remove checks for src address existence when using "set src"

---

ripd/ripd.c

We were overwriting the last byte of the key when it's exactly 16 bytes.
Fixes #8151.

ripd: fix authentication key length

---

bgpd/bgp_pbr.c
bgpd/bgp_zebra.c

Until now, when bgp flowspec entry action was to redirect to a vrf, a
default route was installed in a specific table. that route was a vrf
route leak one. The process can be simplified, as vrf-lite already
has a table identifier. Actually, because policy routing is used to
redirect traffic to a defined table (with ip rule command), use
the table identifier of the VRF.

bgpd: flowspec redirect vrf uses vrf table instead of allocated table id

---

ospfd/ospf_interface.c
ospfd/ospf_interface.h
ospfd/ospf_vty.c

Description :
ospf hello timer is not getting refelcted upon changing the hello interval. Due to this ospf
waits to send  ospf hello till the old timer got expired, 
scenario:
----------
frr(config-if)# do show ip ospf  interface 
ens192 is up
ifindex 3, MTU 1500 bytes, BW 10000 Mbit <UP,BROADCAST,RUNNING,MULTICAST>
Internet Address 10.1.1.220/24, Broadcast 10.1.1.255, Area 0.0.0.1
MTU mismatch detection: enabled
Router ID 10.112.156.220, Network Type BROADCAST, Cost: 10
Transmit Delay is 1 sec, State Backup, Priority 1
Designated Router (ID) 8.8.8.8 Interface Address 10.1.1.110/24
Backup Designated Router (ID) 10.112.156.220, Interface Address 10.1.1.220
Saved Network-LSA sequence number 0x80000005
Multicast group memberships: OSPFAllRouters OSPFDesignatedRouters
Timer intervals …

ospfd: OSPF hello packets not sent with configured hello timer

---

pimd/pim_ifchannel.c
pimd/pim_rp.c

2 issues are present as mentioned below:
Issue1:
======
pimd: pim_ifchannel_local_membership_add should not inherit if (S,G) rpf unresolved
Problem:
S,G entry has iif = oif in FHR is LHR case.
Setup:-
R11-----R2----R4
R11 :- FHR and LHR
R2 :- RP
R4 :- LHR
Issue :-
1) shut mapped interface in R11
2) wait for 5 min
3) do FRR restart
5) No shut of mapped interface
OIL is added for local interface also where OIL is same as IIF
and duplicate traffic observed on R4 receives in Ixia
RCA:
pim_ifchannel_local_membership_add adds inherited oif from starg when iif for
SG is unavailable.
When  rpf for that SG resolves to this inherited oif from starg, iif is also in oif.
This results in dup traffic.
Fix:
If iif is not available, do not inherit from starg.
Issue 2: Memleak
======
2020-05-05 …

pimd: memory leak fix and issue fix

---

tests/topotests/lib/topotest.py

Pass the topogen 'tgen' object into the startRouterDaemons() method. That object can be used to start a debug cli immediately after starting a daemon, and that can be handy.

tests: make the topogen object available when starting daemons

---

tests/topotests/bgp-evpn-overlay-index-gateway/test_bgp_evpn_overlay_index_gateway.py

Remove a 200 second sleep from bgp-evpn-overlay-index-gateway.
There does not seem to be any evidence that this is needed
and I cannot make the test fail without it.
Fixes: #9035

tests: Remove sleep(200) from bgp-evpn-overlay-index-gateway

---

staticd/static_nb_config.c
staticd/static_nht.c
staticd/static_routes.c
staticd/static_routes.h
staticd/static_zebra.c
staticd/static_zebra.h

Add a couple of back pointers to static route/path/nexthop structures to
simplify the NB code and save ~200 lines.

staticd: simplify the northbound code

---

bgpd/bgp_community.c
bgpd/bgp_ecommunity.c
bgpd/bgp_lcommunity.c
bgpd/bgp_snmp.c
lib/plist.c
ripd/rip_snmp.c

Mostly just retrun => return and misleading comments at all.

bgpd: Fix misleading comments for some parts

---

ospfd/ospf_interface.c

Initialize prefixlen field, and use struct prefix_ipv4
to replace struct prefix.

ospfd: fix coverity warning

---

tests/topotests/bfd_topo2/r2/ospf6d.conf
tests/topotests/bfd_topo2/r4/ospf6d.conf
tests/topotests/bfd_topo2/test_bfd_topo2.py
tests/topotests/msdp_topo1/test_msdp_topo1.py

Summary
---
1. Fix a intermittent failure in MSDP topo1 due to undeterministic traffic route (the test is still testing the MSDP non meshed group peer feature).
2. Many small fixes for bfd_topo2

topotests: small fixes for two tests

---

bgpd/bgp_zebra.c

Previously, when aspath->str was longer than sizeof(api.opaque.data), we
were overwriting the wrong memory.
This problem doesn't exist in master so this PR is targeting only stable/8.0.

[8.0] bgpd: limit the length of opaque data sent to zebra

---

lib/route_opaque.h

```
bgpd: use longer aspath string in opaque data
32 bytes are not enough to carry relatively long AS paths so let's make
the buffer larger.
```
```
bgpd: add protection against too large opaque data structure
BGP opaque data shouldn't be larger than zebra's buffer.
```

BGP opaque data improvements

---

pimd/pim_cmd.c

Some no commands were not accepting values and left us in
a situation where a cut-n-paste of the non-no line would
not be properly accepted.

pimd: Allow more permisive versions of some no commands

---

lib/frrlua.c

Suppress coverity warning on unchecked str2sockunion's return value.

lib: Fix coverity warning of return value

---

bgpd/bgp_mplsvpn.c

In eusure_vrf_tovpn_sid, there is a check to ensure not to select both
SID index and SID auto mode. But, this current check is wrong and not
meaningful.

bgpd: fix typo in ensure_vrf_tovpn_sid

---

bgpd/bgp_attr.c
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_zebra.c

When bgp receives the admin distance from a redistribution statement
let's store that distance for later usage.

bgpd: Store distance received from a redistribute statement

---

lib/frrscript.c

Fix for coverity bug
luaL_dofile returns 0 if success and 1 if failed, so the other switch cases [here](https://github.com/FRRouting/frr/blob/master/lib/frrscript.c#L289-L308) become dead code. The fix is to remove the other switch cases. In case of luaL_dofile error, to retrieve the error value, we can [no longer refer](http://lua-users.org/lists/lua-l/2007-01/msg00566.html) to the return value, so just print the error which should be left on top of the Lua stack (current behaviour).

lib: Fix dead code from lua_dofile

---

zebra/rib.h
zebra/zapi_msg.c
zebra/zebra_rib.c

When receiving a route via zapi, if the route is rejected
there exists a code path where we would not free the corresponding
re created.

zebra: Prevent memory leak if route is rejected early

---

bgpd/bgp_clist.c
bgpd/bgp_community_alias.c
bgpd/bgp_community_alias.h
tests/topotests/bgp_community_alias/r1/bgpd.conf
tests/topotests/bgp_community_alias/test_bgp-community-alias.py

Closes https://github.com/FRRouting/frr/issues/9336

bgpd: Fix bgp routes filtering by [l]community-list

---

bgpd/bgp_io.c
bgpd/bgpd.h

in bgp_io.c upon packet read of some error we are storing
the peer pointer on a thread to call bgp_packet_process_error.
In this case an event is generated that is not guaranteed to be
run immediately.  It could come in *after* the peer data structure
is deleted and as such we now are writing into memory that we
no longer possibly own as a peer data structure.
Modify the code so that the peer can track the thread associated
with the read error and then it can wisely kill that thread
when deleting the peer data structure.

bgpd: bgp_packet_process_error can access peer after deletion

---

ospfd/ospf_interface.h

When declaring functions we must name the variables as part
of our standard.
Signed-of-by: Donald Sharp <sharpd@nvidia.com>

ospfd: Cleanup ospf_interface.h to work with our standards

---

ospf6d/ospf6_asbr.c

For ECMP routes, the metric cost and metric type are compared
even when the asbr entry is not present. This stops the routes
from getting removed when max-age LSAs are received for the
ECMP routes.
For single path routes just after the ECMP case, this check is used
correctly. 

ospf6d: Check the cost only when asbr_present for ECMP routes

---

doc/developer/scripting.rst
lib/frrscript.c
lib/frrscript.h
tests/lib/test_frrscript.c

Previous:
- frrscript_load: push Lua function onto stack
- frrscript_call: calls Lua function
This means frrscript_call only works once since it doesn't push the lua function back onto the stack.
Now:
- frrscript_load: checks Lua function
- this works by pushing the function name from the global table, checking if it is a function, then popping it
- frrscript_call: pushes and calls Lua function (first clear the stack)
Now multiple calls can happen. Consecutive frrscript_calls should still be quite fast, since we aren't reading from the script or compiling the Lua function, its just getting the function from the global table.
See https://github.com/FRRouting/frr/pull/9348/commits/80bfe93670461bfc868c6252e2f15bd44586cd4e for example of consecutive frrscript_call

lib: lua: consecutive script calls

---

redhat/frr.spec.in

Install frr.conf template as a template file, but only install it
as a config file if no per daemon file exists. This will use the
integrated config with new setups, but keeps the per-daemon config
for existing users
Fixes Issue #9295 

redhat: Install frr.conf only if no per daemon config exists

---

zebra/zebra_evpn_mh.c
zebra/zebra_vxlan.c

v4 and v6 host/reference prefixes need to be setup separately for
[RMAC, VTEP] entries as the VTEP is always normalized to a v4 addr.

zebra: use a separate dummy prefix for referencing v6 nexthops

---

bgpd/bgpd.c

When we are starting up under fuzzing we must have the community
alias hash inited on startup.

bgpd: We need to initialize the community alias hash

---

ospfd/ospf_lsa.c

When executing a fuzzing target there exists a code path
where we allocate memory and then drop it immediately
because the fuzzing does not actually schedule threads of
execution.

ospfd: Do not leak memory when fuzzing

---

vtysh/vtysh.c

All these commands are zebra-only. We shouldn't send them to pathd.

vtysh: fix daemon for srv6 commands

---

zebra/rt_netlink.c

Ignore AFs we don't handle in incoming netlink route updates.

zebra: ignore unknown address-family in netlink route msg

---

zebra/zapi_msg.c

Clean up allocated nhgs in error path in zread_nhg_add().

zebra: clean up nhg allocations in error path

---

zebra/zebra_evpn_mh.c

In zebra_evpn_proc_remote_nh if we do not pass in a long
enough stream, the stream reads will fail.  Ensure that
we have enough data.

zebra: Ensure stream is long enough

---

zebra/if_netlink.c

Validate incoming netlink interface name - must be an actual NULL-terminated string.

zebra: interface name must be a valid string

---

staticd/static_nb_config.c
staticd/static_routes.c

If there's no route table in a VRF, it's a hard bug - staticd will crash
on any subsequent action with this route anyway. So let's assert the
existence of a route table instead of returning an unrecoverable error.

staticd: replace NB checks with assert

---

bgpd/bgp_routemap.c

Problem seen where if "set aspath-prepend last-as" configured and
applied outbound, we prepend the peer's asn which causes our self-
originated routes to be denied.

bgpd: Stop prepending peer-as if self-originated and lastas configured

---

doc/user/ospf6d.rst

[8.0] doc: move ospf6 area commands to the appropriate section

---

ospfd/ospf_packet.c

ospfd: Prevent fuzzing mem leak due to event avoidance

---

pimd/pim_bsm.c

When we decide that we do not need a item on the partial_bsrp_list
don't just drop the memory on the floor, free it up.
This was happening when we decided that a pending item has
a hold time of 0.

pimd: Prevent memory leak

---

pathd/path_pcep_cli.c
vtysh/vtysh.c

pce-config, pce and pcc node-entering commands in vtysh include no-form,
which is incorrect. Currently, when user passes a no-form command like
`no pcc`, vtysh enters the node while pathd deletes the node and this
leads to a desynchronization.
Regular and no-form commands should be defined separately to fix this.

vtysh, pathd: fix pcep node-entering commands

---

lib/subdir.am

Fixes #9403
Signed-off-by: John W. O'Brien <john@saltant.com>

Scan lib/resolver.c only when c-ares is installed

---

zebra/kernel_netlink.c

When NHRP registers to zebra to receive link layer events related to
gre interfaces, then it is interested in receiving also RTM_GETNEIGH
messages.
Fixes ("b3b751046495") nhrpd: link layer registration to notifications

zebra: RTM_GETNEIGH messages may be used by nhrp

---

lib/routemap.c

When using "match evpn default-route" rule, match_arg is NULL and strcmp
is not happy with that. There's already a special function named rulecmp
that handles such situations.
Fixes #9384.

bgpd: fix segfault when re-adding "match evpn default-route" rule

---

lib/filter.h
lib/filter_cli.c
lib/filter_nb.c

Currently, when we check the new prefix-list entry for duplication, we
only take filled in fields into account and ignore optional fields.
For example, if we already have `ip prefix-list A 0.0.0.0/0 le 32` and
we try to add `ip prefix-list A 0.0.0.0/0`, it is treated as duplicate.
We should always compare all prefix-list fields when doing the check.
Fixes #9355.

lib: fix prefix-list duplication check

---

yang/frr-filter.yang

The code assumes that these leafs always exist when their complementary
leafs exist. For example, when processing `ipv4-exact-match`, the code
always expects to have access to `ipv4-prefix`. If those leafs are not
provided, code crashes. It doesn't happen when using the CLI because it
always does the right thing, but it can happen when using other
frontends.
Also fix incorrect description for prefix-list sequence leaf.

yang: mark a couple of prefix-list/access-list leafs as mandatory

---

ospf6d/ospf6_asbr.c
ospf6d/ospf6_flood.c

1. Fixed an assert in ASBR summarisation test_ospfv3_type5_summary_tc46_p0 and handled a scenario where LSA was not flushed. 
test_ospfv3_type5_summary_tc46_p0 test case was failing due to the assert. 
2. Fixed removal of Type-7 LSA when Type-5 LSAs are removed.
Check individual comments for more details.

OSPF6d: Fixed assert at ospf6_originate_summary_lsa asbr.c:2849 and flushing of Type-7 LSAs

---

ospfd/ospf_vty.c

There's a new "mpls ldp-sync" command added to the OSPF router node in
FRR 8.0. This change broke the following config:
```
router ospf
!
mpls ldp
discovery hello interval 10
!
```
The config was broken because the "mpls ldp" line is now treated as an
"mpls ldp-sync" line inside the router node. We must explicitly print
"exit" at the end of OSPF router node to fix the issue.
Fixes #9206.

[8.0] ospfd: explicitly exit from the router node

---

ospfd/ospf_flood.c
ospfd/ospf_lsa.c

Fix CI Failure test_ospf_type5_summary_tc45_p0
Summarised LSA is not flushed in OSPFv2 in below scenario:
1. Configure summary-address in ospfv2
2. redistribute static and connected.
3. Check the LSAs are received on neighbor.
4. Now remove all OSPFv2 configs, so neighbor will still have the summarised LSA.
5. Configure router ospf with redistribute static and connected.
6. Check the DB, summarised LSA is present although the configuration is not present.
7. Now configure the summary-address and remove the configuration after sometime.
8. The summarised LSA will be still present.
**RCA:**
When self originated LSA is received from the neighbor and that
LSA is summarised one, the LSA is refreshed but a flag is not set
due to which it was not able to remove it later. …

ospfd: Summarised External LSA is not flushed in one scenario

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/pathd-service
snapcraft/snapcraft.yaml.in

Old snap base (on Ubuntu 16.04) is no longer supported and snap package can't be built anymore because of it.
This updates the core for the snap to be based on 18.04 which is the current recommended version.
Additionally, adds the pathd to the daemons used by snap package

Snap update to 18.04 base

---

snapcraft/README.snap_build.md
snapcraft/README.usage.md
snapcraft/scripts/Makefile
snapcraft/scripts/pathd-service
snapcraft/snapcraft.yaml.in

Old snap base (on Ubuntu 16.04) is no longer supported and snap package can't be built anymore because of it.
This updates the core for the snap to be based on 18.04 which is the current recommended version.
Additionally, adds the pathd to the daemons used by snap package

[8.0] Snap update to 18.04 base

---

doc/user/pim.rst
lib/command.h
pimd/pim_cmd.c
pimd/pim_instance.h
pimd/pim_nb_config.c
pimd/pim_upstream.c
tests/topotests/lib/pim.py
tests/topotests/multicast_pim_sm_topo1/multicast_pim_sm_topo1.json
tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py
tests/topotests/multicast_pim_sm_topo2/multicast_pim_sm_topo2.json
tests/topotests/multicast_pim_sm_topo3/multicast_pim_sm_topo3.json
tests/topotests/multicast_pim_sm_topo3/multicast_pim_sm_topo4.json
tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo3.py
tests/topotests/multicast_pim_static_rp_topo1/multicast_pim_static_rp.json
yang/frr-igmp.yang
yang/frr-pim.yang

While defaults are good picks for "reasonable" guesses, min and max range values really aren't. Operators and experimenters often like to configure "unreasonable" values to stress test, tests boundary conditions and explore innovations.
With that in mind, change all ranges to 1..max (of type).

Improve pim timers

---

doc/user/ospf6d.rst
ospf6d/ospf6_flood.c
ospf6d/ospf6_gr.h
ospf6d/ospf6_gr_helper.c
ospf6d/ospf6_gr_helper.h
ospf6d/ospf6_interface.c
ospf6d/ospf6_interface.h
ospf6d/ospf6_lsa.h
ospf6d/ospf6_message.c
ospf6d/ospf6_neighbor.c
ospf6d/ospf6_neighbor.h
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h
ospf6d/ospf6d.c
ospf6d/ospf6d.h
ospf6d/subdir.am

RFC 5187 specifies the Graceful Restart enhancement to the OSPFv3  routing protocol. This PR implements support for helper functionality alone.
This implementation handles the Grace LSA packet processing , Helper entry , Helper core functionality and helper exit and upon actions.
The following list of commands helps to enable/disable helper functionality.
1. [no] graceful-restart helper-only [A.B.C.D]  :  This config helps to enable /disable helper  support for RESTARTER router 
during  graceful restart . By default, helper support disabled in the router.
2. [no] graceful-restart helper strict-lsa-checking:  By default, strick-lsa-check is enabled in helper role.  If strict-lsa-check 
enabled helper role will be aborted if any topochanges.
3. [no] graceful-restart helper planned-only : …

ospf6d: Support for ospfv3  graceful restart  helper functionality

---

zebra/zapi_msg.c
zebra/zapi_msg.h

For some reason commit #ef524230a6baa decided
to remove enums and switch to uint16_t.  Which
is not the right thing to do.  Put it back

zebra: Fix usage to enum in notify functions

---

tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2.py
tests/topotests/lib/bgp.py

- bugs in the support library function `verify_gr_address_family`
allowed this test to pass depending on ordering of python dictinoary
keys. Fix the bugs, fix the test.

tests: fix broken bgp GR test (non-deterministic)

---

staticd/static_vty.c

Warn when attempting to delete a non-existent static route instead of silently returning. This more closely aligns with what we already do for `no` with VRFs and other commands.
```
arch(config)# no ip route 1.1.1.1/32 blackhole
arch(config)# no vrf blah
% VRF blah does not exist
arch(config)# 
```

staticd: warn on attempted delete of non-existent route

---

tests/topotests/zebra_rib/test_zebra_rib.py

In particular, the fixed 2 second sleep here was not long enough.
Switch to standard run_and_expect polling to make test more robust.

tests: use std polling for results in zebra_rib test

---

bgpd/bgp_evpn.c

when doing BGP over an IGP platform, the expectation is that
the path calculation for a given prefix takes into account the
igpmetric given by IGP.
This is true with prefixes obtained in a given BGP instance where
peering occurs. For instance, ipv4 unicast entries or l2vpn evpn
entries work this way. The igpmetric is obtained through nexthop
tracking, like below:
south-vm# show bgp nexthop
Current BGP nexthop cache:
1.1.1.1 valid [IGP metric 10], #paths 1, peer 1.1.1.1
2.2.2.2 valid [IGP metric 20], #paths 1, peer 2.2.2.2
The igp metric is taken into account when doing best path
selection, and only the entry with lowest igp wins.
[..]
*>i[5]:[0]:[32]:[5.5.5.5]
1.1.1.1                  0    100      0 ?
RT:65400:268435556 ET:8 Rmac:2e:22:6c:67:bb:73
* i                 2.2.2.2 …

bgpd: imported evpn rt5 routes copy igpmetric

---

bgpd/bgp_vty.c

I fixed two configuration issues.
1. `segment-routing srv6` block in `router bgp` block doesn't have `exit`. This causes an issue to load configuration at startup. 
2. `sid vpn export` setting is missing. This causes not to save configuration correctly.

fix some SRv6 configuration isn't saved correctly 

---

vtysh/vtysh.c

Just like `bfd peer`,  we should add "exit" for `bfd profile`
Since no "exit-bfd-profile",  add "exit" for profile during mark process.

vtysh: add "exit" for bfd's profile node

---

zebra/zebra_mpls_vty.c

Maybe with empty nexthop to call zebra_mpls_transit_lsp():
"no mpls lsp (16-1048575)".
So just delete this "gate_str" check.
The check is only for "add" commands, which is already exist.

zebra: fix wrong check of mpls command

---

ospf6d/ospf6_asbr.c

Everytime redistribute CLI is executed, external LSAs are
re-originated. When there is no change in the CLI parameters
the LSAs should not get re-originated.
**Fix:**
Check if the CLI params are same, do not re-originate the LSA.
Fixes: #9445

ospf6d: External LSAs reoriginates on every redistribute CLI

---

snapcraft/snapcraft.yaml.in

snapcraft: add missing dependency

---

tests/topotests/ospf_basic_functionality/test_ospf_single_area.py

- use the standard 'delete' key instead of 'del_action'

tests: fix ospf json config confusion

---

ospfd/ospf_nsm.c

OSPF Peer gets stuck in EXSTART with ARISTA Device.
**Root Cause:**
First peer is form with Arista device in normal area and then
the area type is changed to NSSA. Due to this Type-4 and Type-5
LSAs advertised by Arista router is still present in
the OSPF DB. While DD exchange the Type-5 LSAs are omitted but
the Type-4 LSAs are not omitted due to which Arista device gets
stuck in EXSTART and it keeps moving between EXCHANGE And EXSTART.
**Fix:**
When the area is NSSA, we should not send Type-4 LSAs in DD
exchange packet.

ospfd: NSSA area should not exchange Type-4 LSAs in DD

---

ospf6d/ospf6_gr_helper.c
ospf6d/ospf6_lsdb.h

Two fixes:
- The lsa and lsanext must be unlocked if break out of ALL_LSDB loop. So add it.
- Incidentally correct the comment of ALL_LSDB.

ospf6d: fix lock leak of using ALL_LSDB in GR helper

---

ospf6d/ospf6_gr_helper.c

After i have checked the context of code, i think it needn't return any value.

ospf6d: suppress coverity warning of return value

---

pimd/pim_nb_config.c

IGMP query is sent at irregular intervals
(more than 30 seconds) when "ip igmp query-max-response-time 100"
command is executed multiple times.
**RCA:**
When "ip igmp query-max-response-time 100" is executed, the timers
are reset resulting in the delay of sending the query.
**Fix:**
When there is no change in the config value, we should not reset
the timers.

pimd: IGMPv2 query timer gets delayed in a scenario

---

pimd/pim_igmpv3.c

Problem :
=======
IGMP Report is coming in include mode without any source address, 
When all the groups from Ixia are stopped,
groups still keep refreshing and not getting a timeout.
Fix :
===
If the requested filter mode is INCLUDE *and* the requested
source list is empty, then the entry corresponding to the
requested interface and multicast address is deleted if present.
If no such entry is present, the request is ignored.
When an interface receives the IGMP report without any source, then the group is deleted.

pimd: IGMP groups are not getting timeout

---

bgpd/bgp_ecommunity.h
bgpd/bgp_routemap_nb_config.c
lib/routemap.h
lib/routemap_cli.c

The library code should not depend on a specific daemon's code.

lib: remove the dependency on bgpd code

---

lib/zclient.c
lib/zclient.h
nhrpd/nhrp_route.c
zebra/rt_netlink.c
zebra/zapi_msg.c

nhrp, zebra, lib: pass exact received neighbor state value to nhrp
As NHRP expects some notification of neighboring entries on GRE
interface, when a new interface notification is encountered, the
exact neighbor state flag is found. Previously, the flag passed
to the upper layer was forced to NDM_STATE which is REACHABLE,
as can be seen on below trace:
2021/08/25 10:58:39 NHRP: [QQ0NK-1H449] Netlink: new-neigh 102.1.1.1 dev gre1 lladdr 10.125.0.2 nud 0x2 cache used 1 Type 5
When passing the real value, NHRP received an other value like STALE.
2021/08/25 11:28:44 NHRP: [QQ0NK-1H449] Netlink: new-neigh 102.1.1.1 dev gre1 lladdr 10.125.0.2 nud 0x4 cache used 0 type 5
This flag is important for NHRP, as it permits to monitor the link
layer of NHRP entries.
Fixes: d603c0774eba ("nhrp, zebra, …

Fix nhrp neigh state

---

isisd/isis_lsp.c
tests/isisd/test_isis_lspdb.c

This is used to fix #8755 
It checks sequence number is not null when building LSP missing in received CSNP.

isisd: Fix sending of LSP with null seqno

---

.dir-locals.el

- format with black in emacs
- wrap text at 88 (black)

tests: Update dir-locals

---

doc/user/ospf6d.rst
ospf6d/ospf6_asbr.c
tests/topotests/ospf6_topo2/test_ospf6_topo2.py

Add the "metric" and "metric-type" options to the "redistribute"
command.
This is a small commit since the logic of setting the metric
value and type of external routes was already present due to the
implementation of the "default-information originate" command months
ago. This commit merely extends the "redistribute" command to
leverage that functionality.

ospf6d: extend the "redistribute" command with more options

---

tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_topo1.py

Previously the check did nothing as the input_dict parameter was wrong.

tests: fix ospf ASBR summary test

---

doc/user/bgp.rst

A small problem:
- Correct display of "show bgp summary" in doc.

doc: add a missing field for bgp summary's display

---

tests/topotests/bgp_basic_functionality_topo1/test_bgp_basic_functionality.py
tests/topotests/conftest.py
tests/topotests/lib/bgp.py
tests/topotests/lib/common_config.py
tests/topotests/lib/ospf.py
tests/topotests/lib/pim.py
tests/topotests/lib/topojson.py

Measuring 10-25% speedup for tests that use the common configuration methods (pim tests particularly benefit)
- Load json configs in parallel.
- Reload (reset) routers to new configs in parallel.

tests: configure/reset routers in parallel

---

lib/command.c
vtysh/vtysh.c

Clean up a couple of places to use generic code instead of listing every node we have.

lib, vtysh: make node-processing code more generic 

---

bgpd/bgp_vty.c

Just to be consistent with neighbor_interface_cmd.
Also adding WORD to be optional for negative form.
Closes https://github.com/FRRouting/frr/issues/9510

bgpd: Drop redundand `WORD` for no_neighbor_interface_cmd

---

ospfd/ospf_vty.c

When hello-interval is configured as 5, automatically dead interval becomes
4 times of hello i.e 20 seconds. But user wants the dead interval as
40 seconds and hello as 5 seconds. Therefore user configures it.
Now "ip ospf dead-interval 40" is not shown in "show running-config"
Therefore when user restarts the daemon, the dead interval goes back to
20 seconds and the neighbors are down.
**Fix:**
If user configures dead-interval as 40, show it in show running config.
Fixes: #9401

ospfd: add dead-interval 40 if configured in show running

---

ospfd/ospf_spf.c

ospf_spf_cleanup frees the data so we need to reset the stale pointers.
Fixes #9523.

ospfd: correctly cleanup spf data

---

tests/topotests/lib/bgp.py

- Allow tests to also change the connect timer as they can for the
keep-alive and holddown timers.

tests: log bgp nbr changes, and allow config of connect timer

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst
tests/topotests/bgp_minimum_holdtime/r1/bgpd.conf
tests/topotests/bgp_minimum_holdtime/r1/zebra.conf
tests/topotests/bgp_minimum_holdtime/r2/bgpd.conf
tests/topotests/bgp_minimum_holdtime/r2/zebra.conf
tests/topotests/bgp_minimum_holdtime/test_bgp_minimum_holdtime.py

If a BGP peer makes a connection with a low hold time, it will cause an unpredictable load on our router, so we need to deny session establishment.
This feature is mainly intended to be used in situations where you often connect to routers outside your organization.

bgpd: minimum-holdtime knob to prevent session establishment with BGP peer with low holdtime.

---

doc/user/bgp.rst

doc: Add missing `timers` for connect timer in BGP

---

bgpd/bgp_fsm.c
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst
tests/topotests/bgp_ecmp_topo3/ibgp_ecmp_topo3.json
tests/topotests/bgp_ecmp_topo3/test_ibgp_ecmp_topo3.py

When BGP is notified by RIB that peer address is unreachable then BGP session must be brought
down immediately and not wait for the hold-timer expiry. Today EBGP already behaves this way but
need to change for iBGP.
CLI configuration : [no] bgp fast-convergence
Running config : router bgp 200
bgp fast-convergence           ==> New CLI

bgp: BGP knob for faster convergence of bgp sessions

---

alpine/APKBUILD.in
docker/alpine/Dockerfile
docker/alpine/docker-start
docker/alpine/libyang/10-remove-non-standard-headers.patch
docker/alpine/libyang/11-utest-dont-parse-dlerror.patch
docker/alpine/libyang/APKBUILD

Alpine images have been broken for some time because libyang2 is not
available in Alpine. This patch updates our Dockerfile to build a
libyang2 APK and install it into the image to satisfy FRR's libyang2
dependency.
Unfortunately, libyang2 erroneously includes an internal header from
libc which musl does not provide. FRR's official Docker
images are based on Alpine, which only offers musl libc. Until libyang2
fixes this problem, the libyang2 source that is installed in this image
is a patched version that is compatible with musl libc and not an
official version.

docker: build libyang2 along with FRR [8.0]

---

tools/frrcommon.sh.in

The pathspace folder in `/var/run` needs the `x` permission for the group too
Otherwise vtysh fails when running it with groups frrvty and frr:
$ vtysh -N gateway
% Can't open configuration file /etc/frr/gateway/vtysh.conf due to 'Permission denied'.
vtysh_connect(/var/run/frr/gateway/zebra.vty): stat = Permission denied

tools: fix frr pathspace folder permissions

---

lib/elf_py.c

This fixes some spurious warnings on *BSD, where `elffile_add_dynreloc`
isn't used since `elf_getdata_rawchunk` is not available.

lib/clippy: fix forgotten conditional

---

bgpd/bgp_network.c
bgpd/bgpd.c
lib/vrf.c
lib/vrf.h

2 commits:
a) when using -Z option where we don't communicate with zebra just assume VRF_DEFAULT instead of randomly setting a value.
b) remove unused function
If this is backported I recommend only taking a)

Bgp view not working

---

ospfd/ospf_vty.c

Memory Leak seen at  show_ip_ospf_neighbor_all_common (ospf_vty.c:4635)
**RCA:**
In function show_ip_ospf_neighbor_all_common, one child json object is not
added to the parent child object when there is no nbma neighbor. Hence
the memory leak.
**Fix:**
Add the child object to the parent json object.
Fixes: #9548

ospfd: Memory Leak seen at show_ip_ospf_neighbor_all_common.

---

bgpd/bgp_rpki.c
doc/user/rpki.rst

Add the ability to configure the source address of rpki
connection. Proposed vty command is to add below parameter:
rpki cache <address> source <bindaddr> <port> preference <pref>
rpki cache <address> source <bindaddr> <port> <usernamessh> ...
This works for both tcp and ssh connections. In case the source
address is not available yet, the rpki retry interval will retry
in a defined amount of time.
Rtrlib library is the library in charge of the binding of the
tcp/ssh connection, and applies the getaddrinfo() and bind()
operations to the passed parameter bindaddr to the respective
tcp_config/ssh_config structures.

bgpd: add rpki source address configuration

---

zebra/dplane_fpm_nl.c
zebra/if_netlink.c
zebra/interface.c
zebra/interface.h
zebra/rt_netlink.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_evpn.c
zebra/zebra_evpn.h
zebra/zebra_evpn_mac.c
zebra/zebra_evpn_mac.h
zebra/zebra_evpn_mh.c
zebra/zebra_evpn_mh.h
zebra/zebra_evpn_neigh.c
zebra/zebra_evpn_neigh.h
zebra/zebra_evpn_vxlan.h
zebra/zebra_fpm.c
zebra/zebra_mpls.c
zebra/zebra_mpls.h
zebra/zebra_mpls_openbsd.c
zebra/zebra_nb_config.c
zebra/zebra_nhg.c
zebra/zebra_srte.c
zebra/zebra_srte.h
zebra/zebra_vxlan.c
zebra/zebra_vxlan_private.h

see individual commits.  Nothing fancy here

typedef cleanup to proper usage of `enum X` or `struct X`

---

bgpd/bgp_vty.c

Before:
```
AddPath:
IPv4 Unicast: TX advertised IPv4 Unicast and received
IPv4 Unicast: RX advertised IPv4 Unicast and received
IPv6 Unicast: TX advertised IPv6 Unicast
IPv6 Unicast: RX advertised IPv6 Unicast
```
After:
```
AddPath:
IPv4 Unicast: TX advertised and received
IPv4 Unicast: RX advertised and received
IPv6 Unicast: TX advertised
IPv6 Unicast: RX advertised
```

bgpd: Drop afi/safi duplicate string notation for AddPath capability

---

bgpd/bgp_vty.c

Currently, "vrf default" modifier is not processed correctly and we get
the `% Can't find BGP instance` error.

bgpd: fix "no router bgp X vrf default"

---

bgpd/bgp_fsm.c
bgpd/bgp_network.c
bgpd/bgpd.h

BGP can experience a bunch of errors associated with sockets
being manipulated which would prevent the peer from coming up.
Let's add some additional debug information here so that
our operators can do a bit more for themselves.

bgpd: Add `PEER_DOWN_SOCKET_ERROR` to the list of peer failure modes

---

tests/topotests/bgp_auth/test_bgp_auth.py
tests/topotests/conftest.py
tests/topotests/lib/common_config.py
tests/topotests/lib/topogen.py
tests/topotests/lib/topojson.py
tests/topotests/lib/topotest.py

Refactor the bgp_auth test to create common_config code to allow
non-json based tests to reset routers and load configs in parallel.

tests: refactor parallel reset/load config for non-json

---

bgpd/bgp_fsm.c
bgpd/bgp_network.c

bgp->vrf_id is always VRF_DEFAULT for views. All these special checks
are not necessary.

bgpd: cleanup special checks for views

---

doc/developer/topotests.rst
tests/topotests/lib/topogen.py

Create a pid file for the router created by topotest.
By executing nsenter directly against this pid, developers
can execute commands directly from outside the unet shell.
This allows the developer to use script, tab completion, etc.,
and improves efficiency.
Signed-off-by: Hiroki Shirokura <slank.dev@gmail.com>

topotests: to create pid file of topotest router

---

ospfd/ospf_lsa.c
ospfd/ospf_lsa.h
ospfd/ospf_packet.c

ANVL Test case 25.22, 25.23 and 28.11 are failing due to the following 2 issues.
1. LSAs ACK were not sent when received LSA is having max sequence number
but not max-aged.
2. LSA with INITIAL_SEQUENCE number were not originated
after receiving ACK for max sequence LSA.
For more details, check individual commits.

ospfd: ANVL Test case 25.22, 25.23 and 28.11 fixes

---

ospfd/ospf_packet.c

DUT selecting itself as DR when Restarting Router goes for reload.
**Test Case 7.2**
DUT (GR Helper) receives the Hello packet from the OSPF GR RESTARTER
(ANVL here) with DR and BDR set to 0.0.0.0 and DUT in its hello
neighbor list. DUT triggers the DR and BDR election although it is
in the Helper mode for that neighbor.
When hello packet is received with self router ID in the neighbor list,
there is no check in the code to handle this scenario. Hence the DR/BDR
election happens and it changes the DR although it is helper.
**Fix:**
As per RFC 3623 Section 3.  Operation of Helper Neighbor, below point,
we need to maintain the DR relationship.
Also, if X was the Designated Router on network segment S when the
helping relationship began, Y …

ospfd: GR Conformance fix in Hello packet DR election

---

bgpd/bgp_vty.c

At the begining there was a command to enable floating-point encoding,
but now it's default and can be disabled. Documentation was updated, but
CLI - missed, sorry, fixing.

bgpd: Replace `Enable` to `Disable` for floating-point bw encoding CLI

---

ospfd/ospfd.c

Summary LSA is not originated when router-id is modified or process is reset
When router-id is modified or process is cleared, all the external LSAs are
flushed then LSA is re-originated using ospf_external_lsa_rid_change
When the LSAs are flushed, the aggregate flags are not reset.
**Fix:**
Reset the aggregation flag when the LSAs
are flushed.

ospfd: ASBR Summary LSA is not originated when process is reset

---

doc/user/ospf6d.rst
ospf6d/ospf6_abr.c
ospf6d/ospf6_area.c
ospf6d/ospf6_asbr.c
ospf6d/subdir.am
tests/topotests/ospf6_topo2/test_ospf6_topo2.py

Add a knob to turn an NSSA area into a totally stub area. In this configuration, a Type-3 default summary route is generated by default.
Syntax: `area A.B.C.D nssa no-summary`.
Example:
```
router ospf6
area A.B.C.D nssa no-summary
!
```
Note: different from stub areas, NSSA areas can have Type-7 external routes redistributed in from another routing domain. And among those external routes there might be a default route, which can conflict with the ABR default route if one exists. For this reason, the NSSA RFC specifies that an NSSA ABR should advertise a Type-3 default route **only** when summary routes aren't imported into the NSSA (i.e. totally stub NSSA). _ospfd_ violates that part of the spec since an NSSA ABR announces a Type-3 default route regardless if the "no-summary" option is …

ospf6d: add support for NSSA totally stub areas

---

ospf6d/ospf6_flood.c

When ospf6d comes up, it gets interface and address state before it
decides on its router ID.  This results in a bunch of LSAs with
advertising router ID 0.0.0.0 in the LSDB.  Not quite right.
There's a whole bunch of paths leading to this, so just drop the LSA in
ospf6_lsa_originate.  The router-ID change causes everything to be
readvertised anyway (... but the delete doesn't catch the 0.0.0.0 stuff
because the router-ID is now different.)

[8.0] ospf6d: don't create Adv-ID:0.0.0.0 LSAs at start

---

bgpd/bgp_network.c
bgpd/bgpd.c
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post6.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post6.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post4.1.ref
tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post6.1.ref

It was necessary to update the topotest to reflect that VRF ID is now always 0 for views.
The third commit is not in master because the topotest was updated to use JSON instead of simple vty output.

[8.0] backport bgp view fixes

---

tests/topotests/conftest.py
tests/topotests/lib/micronet.py
tests/topotests/lib/topotest.py

- Fix xterm support to work, previously it mostly didn't, not it should
in all cases (i.e., single or dist mode).
- Catch when the user tries to use various window requiring topotests
features (e.g., --cli-on-error) but isn't running under supported
system (e.g., byobu/tmux/xterm), and fail the run with an explanation.

tests: fix xterm windows for topotests, better errors

---

bgpd/bgp_rpki.c
doc/user/rpki.rst

Currently the source IP parameter must be entered between destination IP
and destination port parameters. This is not obviously understandable
when you read such config so let's move the source parameter to the end
of the command line, after the whole list of destination parameters. We
can do this without any deprecation cycle as the parameter was introduced
just recently and isn't in any public release yet.

bgpd: move rpki source after the server config

---

doc/developer/cli.rst
lib/command.c
lib/command_graph.c
lib/command_graph.h
lib/command_lex.l
lib/command_match.c
lib/command_parse.y
lib/command_py.c
tests/lib/cli/test_cli.c
tests/lib/cli/test_cli.in
tests/lib/cli/test_cli.refout.in
tools/permutations.c

This allows defining a CLI command like this:
`[no] some setting ![VALUE]`
with VALUE being optional for the "no" form, but required for the
positive form.  It's just a `[...]` where the empty branch can only be
taken for commands starting with `no`.

lib: add `![...]` syntax for easy "no" forms

---

ospf6d/ospf6_abr.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_intra.c

The route linked list in ospf6d is ordered in prefix batches which
are associated with a the route node denoting the prefix. So if
you look up the prefix in the tree and start walking the list, if you
find a prefix which differs from the one you are interested in then
you have gone beyond the batch of routes for that prefix.
In some cases the route database linked list is used on a per-prefix
basis. The existing code simply does a continue when the prefix does
not match and continues to walk. This works with small numbers of
routes because the walk continues through unrelated prefix batches and
never finds anything to operate on. However if we have many thousands
of routes these walks become expensive and can cause the SPF thread
(amongst others) to run very long, causing issues with …

ospf6d: break early on route prefix mismatch

---

bgpd/bgp_attr.c
bgpd/bgp_attr.h
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_zebra.c
lib/nexthop.c
lib/nexthop.h
tests/lib/test_nexthop.c
zebra/zapi_msg.c
zebra/zebra_vty.c

Description:
Change is intended for fixing the following issues related to vrf route leaking:
Routes with special nexthops i.e. blackhole/sink routes when imported, 
are not programmed into the FIB and corresponding nexthop is set as 'inactive', 
nexthop interface as 'unknown'.
While importing/leaking routes between VRFs, in case of special nexthop(ipv4/ipv6)
once bgp announces route(s) to zebra, nexthop type is incorrectly set as
NEXTHOP_TYPE_IPV6_IFINDEX/NEXTHOP_TYPE_IFINDEX
i.e. directly connected even though we are not able to resolve through an interface.
This leads to nexthop_active_check marking nexthop !NEXTHOP_FLAG_ACTIVE.
Unable to find the active nexthop(s), route is not programmed into the FIB.
Whenever BGP leaks routes, set the correct nexthop type, so that route gets …

bgpd: VRF-Lite fix nexthop type

---

zebra/zebra_evpn_neigh.c

Problem:
When IP1:M1 (local) moves to IP1:M2 (remote-VTEP) bgpd continues to
advertise IP1:M1. This problem is seen in an EVPN-MH setup.
Fix:
Local path del is sent to bgp if the neigh was {local-active||peer-active}.
So path del needs to be called before the sync flags (including peer-active)
are cleared.
Ticket: #2706744

zebra: Send path del to bgp for local-inactive path

---

bgpd/bgp_vty.c

```
~/frr# vtysh -c 'show run' | grep description
neighbor 192.168.0.2 description test 1 2 3
~/frr# vtysh -c 'show ip bgp summary' | grep -E "Desc|192.168.0.2"
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
192.168.0.2     4          0         0         0        0    0    0    never      Connect        0 test 1 2 3
```
Closes https://github.com/FRRouting/frr/issues/9559

bgpd: Do not strip peer's description by whitespace in `show bgp summary`

---

tests/topotests/bgp_evpn_overlay_index_gateway/host2/zebra.conf

Fixed typo in zebra.conf in host2 of bgp_evpn_overlay_index_gateway in topotests.
Signed-off-by: enigamict <mochienper@gmail.com>

tests: fix typo in zebra.conf

---

tests/topotests/bgp_snmp_mplsl3vpn/test_bgp_snmp_mplsvpn.py

There were some tests where we were turning on mpls on
interface names that don't exist for certain `machines`
in the topology.  Fix.

tests: Fix wrong setting of mpls being turned on

---

.dir-locals.el

Remove the python block from the local emacs settings file .dir-locals.el.

tests: remove python format block from dir-locals

---

tests/topotests/all_protocol_startup/test_all_protocol_startup.py

Fix issue of topotest failures with BGP status Connect or Idle
instead of the expected Active

tests: Fix BGP check in all_protocol_startup

---

tests/topotests/route_scale/scale_test_common.py
tests/topotests/route_scale/test_route_scale1.py
tests/topotests/route_scale/test_route_scale2.py

route_scale run is 500+ seconds.  Break it up into
2 separate tests.  This should reduce run time a slight
bit.

tests: Break up route_scale into 2 separate tests

---

eigrpd/eigrp_northbound.c
lib/vrf.c
lib/vrf.h
zebra/zebra_ptm.c

lib/vrf.c vrf_name_to_id(char *name) returned VRF_DEFAULT on lookup failures, which hid failures from the caller.
This change removes vrf_name_to_id(). It also modifies the few callers to have identical behavior (i.e., lookup failure yields VRF_DEFAULT) in case caller code depends on that behavior.

vrf_name_to_id(): remove and change callers to use vrf_lookup_by_name()

---

zebra/zebra_fpm.c
zebra/zebra_fpm_netlink.c
zebra/zebra_fpm_private.h

Description: Currently IPv4 routes with IPv6 link local next hops are
not properly installed in FPM.
Reason is the netlink decoding truncates the ipv6 LL address to 4 byte
ipv4 address.
Ex : fe80:: is directly converted to ipv4 and it results in 254.128.0.0
as next hop for below routes
show ip route
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
B>* 2.1.0.0/16 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, weight 1,
02:22:26
B>* 5.1.0.0/16 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, weight 1,
02:22:26
B>* 10.1.0.2/32 [200/0] via fe80::268a:7ff:fed0:d40, Ethernet0, …

zebra: Fix IPv4 routes with IPv6 link local next hops install in FPM

---

zebra/zebra_nhg.c

Current implementation doesn't copy nexthop_srv6. This causes unexpected behavior when receiving SID information and nexthop isn't onlink.
For example:
Here is the example of unexpected behaviors. First nexthop of 172.31.2.0/24 has nexthop_srv6 correctly, but Second nexthop doesn't have. so SRv6 encap rule doesn't installed correctly when this route is installed into kernel.
```
r1# show ip route vrf vrf100
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
VRF vrf100:
C>* 172.31.1.0/24 is directly connected, ens2, 01:49:02
B>  172.31.2.0/24 …
```

zebra: copy nexthop_srv6 in nexthop_set_resolved

---

ospf6d/ospf6_lsa.c
ospf6d/ospf6_lsa.h
ospf6d/ospf6_route.c
ospf6d/ospf6_route.h
ospf6d/subdir.am

Debug commad for all lsa types and route types are not present.

ospf6d: Add debug commands for lsa all and route all

---

bgpd/bgp_route.c

EVPN paths are maintained in per-ES list for efficient updates
(es→macip_global_path_list, es→macip_evi_path_list). VNI is also maintained
in path_extra for efficient lookups. This (path_extra) VNI (which is always 0 for
global paths) was being displayed against the path and was mis-interpreted
as the BD.
To avoid that confusion I have removed the display.
Ticket: #2732605

bgpd: remove es_path VNI display from type-2 routes

---

staticd/static_nb.c
staticd/static_nb_config.c
staticd/static_routes.c
staticd/static_routes.h
staticd/static_vrf.c
staticd/static_vty.c
staticd/static_vty.h

The main change is in the title. There are also a couple of auxiliary commits, please, check their descriptions individually.
Closes #8746.

staticd: output config using NB callbacks instead of operational data

---

vtysh/extract.pl.in

When extract.pl dies, it was dieing in a manner that provided
absolutely no useful data as to what went wrong.  Let's add
a tiny bit of debug code.  So we can see what is going wrong.

vtysh: Allow us to gather a bit more data when extract.pl dies

---

ospf6d/ospf6_gr_helper.c

OSPF6_CMD_CHECK_RUNNING doesn't check that ospf6 is not NULL.

ospf6d: fix possible NULL dereference

---

ospf6d/ospf6_area.c
ospf6d/ospf6_asbr.c
ospf6d/ospf6_interface.c
ospf6d/ospf6_neighbor.c
ospf6d/ospf6_route.c
ospf6d/ospf6_top.c
ospf6d/ospf6d.c
ospf6d/ospf6d.h

om6->ospf6 is always initialized at the start of the execution.

ospf6d: cleanup useless checks

---

bgpd/bgp_evpn_vty.c

Currently the route-type-1 output has the Ethernet Tag printed first and
not the ESI.
However the legend has the opposite format. Changing the output would be more disruptive, hence changing the legend. 
For eg:
Current legend:
EVPN type-1 prefix: [1]:[ESI]:[EthTag]:[IPlen]:[VTEP-IP]
*> [1]:[0]:[03:44:38:39:ff:ff:01:00:00:01]:[32]:[192.168.100.2]
192.168.100.2                          0 65002 i
RT:65002:100 ET:8
*> [1]:[0]:[03:44:38:39:ff:ff:01:00:00:01]:[32]:[192.168.100.3]
192.168.100.3                          0 65003 i
RT:65003:100 ET:8
Signed-off-by: Aaron Pereira <aaronpereira88@gmail.com>

bgpd: Update route-type-1 legend to match output

---

doc/user/zebra.rst

Swap out incorrect usage of '^' with proper usage of '-'.

doc: fixup formatting in zebra.rst

---

tests/bgpd/test_mpath.c

Compilation is warning that a memcpy is only copying
the first (sizeof pointer) into memory.  This is not
what we really want.  Although it does beg the question about
why this memcpy is needed( or what it is doing ).  I'm going
to just fix the memcpy and call it a day.

tests: Fix make check builds on some bsd variants

---

pimd/pim_assert.h
pimd/pim_bfd.c
pimd/pim_bsm.c
pimd/pim_cmd.c
pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_ifchannel.h
pimd/pim_igmp.c
pimd/pim_igmp.h
pimd/pim_igmpv3.c
pimd/pim_igmpv3.h
pimd/pim_instance.h
pimd/pim_mroute.h
pimd/pim_nb_config.c
pimd/pim_neighbor.h
pimd/pim_oil.h
pimd/pim_rp.c
pimd/pim_rp.h
pimd/pim_rpf.c
pimd/pim_rpf.h
pimd/pim_upstream.h
pimd/pim_zebra.c
pimd/pim_zlookup.c
pimd/pimd.h

Larger change:  IGMP group/source memberships moved from the IGMP socket (which is per-IPv4-addr on each interface) to the whole interface.  Keeping memberships on the querier is just plain wrong;  multicast happens on the entire link, not on each IPv4 subnet.  (Primarily relevant when you have multiple non-overlapping IPv4 subnets on 1 interface.  There's no way to associate the traffic to a specific subnet.)  Moving this also just cuts 1 unnecessary level of indirection from the picture, making the code a bit simpler.
Smaller changes:
* made the include files a bit less crossdependent (it's still bad, but not as bad as before.)
* refactored IGMP source creation/allocation to be simpler and more flexible (need to add ACLs and limit counts)
This PR is intended to only have functional …

pimd: move IGMP memberships from socket to iface, + some cleanups

---

bgpd/bgp_network.c

Initial commit: 8761cd6ddb5437767625f58c8e9cc3ccda7887ab
introduced the idea of v6 LL using interface up/down events
instead of nexthop resolution to know when a peering should
happen or not.  This above commit left a hole where if the remote
peer connected to this bgp, the bgp code would still believe
the peering is down.   Modify the code to double check and
ensure that we have proper v6 LL resolution flags set.

bgpd: Allow v6 LL peers to work when connected to as well

---

configure.ac
tests/subdir.am

build: Lower the lttng version requirements from 2.12 to 2.10 for easy debian installation
tests: include lttng libs in the bgp tests build

lttng build updates

---

bgpd/bgp_evpn.c

NH tracking is already in use for type-1, type-3 and type-5 routes.
This change extends that tracking to EAD and ESR to eliminate the 9s
delay (BGP holdtimer) with ES/L2-NHG update seen when all the uplinks
are shutdown on a remote EVPN PE.
Ticket: #2682896

bgpd: Extend EVPN next hop tracking to type-1 and type-4 routes

---

.gitignore

Some pcep log output from `make check` is showing up in
git status.  Make git know it's ok to ignore this stuff.

*: Add some missed make check generated files in .gitignore

---

bgpd/bgp_conditional_adv.c
bgpd/bgp_route.c

There are places where we use route-maps using duplicated attributes and
neither intern nor flush them after the usage. If a route-map has set
rules for aspath/communities, they will be allocated and never freed.
We should always flush unneeded duplicated attributes.

bgpd: fix memory leaks when using route-maps

---

tests/topotests/lib/bgp.py

A bunch of tests have this pattern:
a) Install a new prefix into bgp
b) Run this loop:
foreach (router in topology) {
verify_bgp_rib(router)
}
This is to ensure that the prefix is actually disseminated.
The problem with this, of course, is that a wait of 2 seconds
for every item in that loop makes no sense.  As that the initial
router verification of it's bgp rib will wait 2 seconds and
all the remaining bgp routers in the topology will have gotten
the data.  So we end up waiting a bunch of extra time.
Remove the initial_wait time for verify_bgp_rib.  Also
increase the failure wait time to 30 seconds.  This is
to give a bigger window for bgp to send it's data for
our test systems that could be under heavy load.  In the
normal case tests will never hit this.
Signed-off-by: Donald Sharp …

tests: Do not do a initial_timeout of 2 seconds for verify_bgp_rib

---

doc/user/routemap.rst

The set as-path exclude route map command appears to be
entirely undocumented. Mention it in routemap.rst.
Signed-off-by: Lars Seipel <ls@slrz.net>

doc: mention set as-path exclude in routemap.rst

---

ospf6d/ospf6_area.h
ospf6d/ospf6_intra.c

intra_brouter_calc is a int that is being used a bool,
convert to a bool.

ospf6d: Use bool instead of an int

---

doc/user/ospf6d.rst
ospf6d/ospf6_abr.c
ospf6d/ospf6_abr.h
ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6d.c
tests/topotests/ospf6_topo2/test_ospf6_topo2.py

Issue #9535 describes how the export-list/import-list commands work differently on ospfd and ospf6d.
In short:
* On ospfd, "area A.B.C.D export-list" filters which internal routes an ABR exports to other areas. On ospf6d, instead, that command filters which inter-area routes an ABR exports to the configured area (which is quite counter-intuitive). In other words, both commands do the same but in opposite directions.
* On ospfd, "area A.B.C.D import-list" filters which inter-area routes an ABR imports into the configured area. On ospf6d, that command filters which inter-area routes an interior router accepts.
* On both daemons, "area A.B.C.D filter-list prefix NAME <in|out>" works exactly the same as import/export lists, but using prefix-lists instead of ACLs.
The inconsistency on how …

ospf6d: rework filtering commands to be in line with ospfd

---

vtysh/vtysh_config.c

A simple strcmp-based sorting done by `config_add_line_uniq` breaks the
correct advanced sorting of static routes done by staticd. We don't
actually need to check vrf node commands for uniqueness as all commands
are daemon specific, so let's use simple `config_add_line` that doesn't
sort commands.

vtysh: remove sorting of vrf node commands

---

bgpd/bgp_route.c

Yet-another path where the safi needs to be changed to locate the unicast table where LU routes live. There are lots of places where this needs to be done -  this one makes 'show bgp ipv4 labeled-unicast' work.

bgpd: make show bgp labeled-unicast work

---

bgpd/bgp_zebra.c

has_valid_label is only used to check needs to print debug and we can just check the flag in debug print loop.
ref: https://github.com/FRRouting/frr/pull/9638#discussion_r712723319

bgpd: fix mpls nexthop announce in bgp_zebra_announce

---

lib/skiplist.c
lib/skiplist.h
tests/lib/test_skiplist.c
tests/subdir.am

Original per-level counters were implemented using pointers as a dirty hack; this PR reimplements as integers to avoid triggering warnings from analysis tools. Also turns off some debug error-checking of the list functions that could affect performance (10 years in the field would have turned up any issues by now).
Test code added in tests/lib/test_skiplist.c. Currently set to build but not run automatically until I figure out the rules for stdout/stderr/exit codes in the test infrastructure.

lib: skiplist: clean up level counter implementation

---

doc/developer/workflow.rst

I said I'd write some text to put in the workflow doc for this, so here it is.  Triggered by #9646.
My goal here was a "strong recommendation" to go with the new containers, but not a hard requirement.  I just hope any new work starting from here on can go with the new stuff.  I know the new containers aren't "typical" C with their macros, but I've tried my best to make them accessible for all of us.  If there's any shortcomings in their docs we should absolutely fix that.

doc/workflow: prefer typesafe containers

---

doc/user/ospf6d.rst
doc/user/ospfd.rst
ospf6d/ospf6_gr_helper.c
ospfd/ospf_vty.c
tests/topotests/lib/ospf.py
tests/topotests/ospf6_gr_topo1/rt1/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt2/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt3/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt4/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt5/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt6/ospf6d.conf
tests/topotests/ospf6_gr_topo1/rt7/ospf6d.conf
tests/topotests/ospf_gr_helper/test_ospf_gr_helper.py
tests/topotests/ospf_gr_topo1/rt1/ospfd.conf
tests/topotests/ospf_gr_topo1/rt2/ospfd.conf
tests/topotests/ospf_gr_topo1/rt3/ospfd.conf
tests/topotests/ospf_gr_topo1/rt4/ospfd.conf
tests/topotests/ospf_gr_topo1/rt5/ospfd.conf
tests/topotests/ospf_gr_topo1/rt6/ospfd.conf
tests/topotests/ospf_gr_topo1/rt7/ospfd.conf

Considering that both the GR helper mode and restarting mode can be enabled at the same time, the "graceful-restart helper-only" command can be a bit misleading since it implies that only the helper mode is enabled. Rename the command to "graceful-restart helper enable" to clarify what the command does.
In ospfd, start a deprecation cycle of one year before removing the original command. For ospf6d this isn't necessary since the GR helper code didn't see the light of a public release yet.

ospfd, ospf6d: rename the "graceful-restart helper-only" command

---

lib/command.h
vtysh/vtysh.c

After `<daemon_name> is not running` message vtysh does not return error. For example if you disable ospf in `/etc/frr/daemons` and run `vtysh -c configure -c "router ospf"` it prints the message to stderr, but returns 0.
Since it is not possible to do anything daemon related with daemon not running (except some utility commands like `list`, `find`, etc.) I see no reason why it should return 0 and allow you to enter views of daemons that are down. Vtysh can't even properly validate the commands inside those views (let alone save them to config).
I am just not sure which status to use. I chose `CMD_WARNING_CONFIG_FAILED` because I saw it being commonly used in daemons when command fails.
Also the continue was unnecessary because we already checked in line `635` that the `cmd->daemon` …

vtysh: Add error code if daemon is not running

---

bgpd/bgp_route.c

following command: show bgp l2vpn evpn rd all tags
does not append rd contexts one after the other
before:
dut-vm# show bgp l2vpn evpn rd all tags
Network          Next Hop      In tag/Out tag
Route Distinguisher: 65000:999
*> [5]:[0]:[24]:[10.40.1.0]
10.209.36.1     Route Distinguisher: 65000:1000
*> [5]:[0]:[24]:[10.40.1.0]
10.209.36.1
Displayed 2 out of 2 total prefixes
after:
dut-vm# show bgp l2vpn evpn rd all tags
Network          Next Hop      In tag/Out tag
Route Distinguisher: 65000:999
*> [5]:[0]:[24]:[10.40.1.0]
10.209.36.1
Route Distinguisher: 65000:1000
*> [5]:[0]:[24]:[10.40.1.0]
10.209.36.1

bgpd: add carriage return when dumping tags from all evpn rds

---

zebra/if_netlink.c

There were two identical blocks of code run at init time that requested info about AF_BRIDGE - don't see any reason to do that twice, so remove one block.

zebra: stop asking for AF_BRIDGE interface info twice

---

bgpd/bgp_packet.c

the values were swapped by mistake. fix it.

bgpd: swap bgp error value with file descriptor value

---

doc/user/ospf6d.rst
ospf6d/ospf6_area.c
ospf6d/ospf6_area.h
ospf6d/ospf6_asbr.c
ospf6d/ospf6_nssa.c
ospf6d/ospf6_nssa.h
ospf6d/ospf6_spf.c
ospf6d/ospf6_top.h
ospf6d/ospf6_zebra.c
ospf6d/ospf6_zebra.h
tests/topotests/ospf6_topo2/test_ospf6_topo2.py

Add a knob to generate Type-7 default routes on NSSA ABRs/ASBRs.
Syntax: `area A.B.C.D nssa default-information-originate [{metric (0-16777214)|metric-type (1-2)}]`.
Example:
```
router ospf6
area 1 nssa default-information-originate
!
```
This PR also includes a few assorted fixes. Please refer to the individual commits for details.

ospf6d: add a knob to generate Type-7 default routes

---

doc/developer/grpc.rst

The code block after the :: is not displayed correctly without an empty
line in between.

doc: fix code block in grpc docs

---

bgpd/bgp_zebra.c

In current implementation, only last path in mpinfo is treated as seg6 nexthop, but all paths should be treated as seg6 nexthop.
Signed-off-by: Ryoga Saito <ryoga.saito@linecorp.com>

bgpd: fix annouce for multipath SRv6 SID routes

---

ospf6d/ospf6_top.c

ospf6d: Log messages cannot have newlines

---

bgpd/bgp_packet.c
bgpd/bgp_vty.c

The paf data structure is stored based upon an internal
bgp enum.  The code is looking over all AFI/SAFI's and
doing a paf_af_find which then calls afindex to find
the right paf structure.  Let's just loop over the
peer->peer_af_array[] and cut straight to the chase.
Under some loads the paf_af_find was taking up 6%
of the run time.  This removes it entirely.

bgpd: Don't lookup paf structure get straight to the point

---

pimd/pim_cmd.c

This `XFREE()` call is in plainly in the wrong spot.  `rp_all` (the 224.0.0.0/4 entry) isn't supposed to be free'd ever, and the conditional above makes quite clear that it remains in use.
It may be possible to exploit this as a heap corruption bug, maybe even as RCE.  I haven't tried; I randomly noticed this while working on the BSM code.  Luckily this code is only run by the CLI for the clear command, so the surface is very small.

pimd: fix UAF/heap corruption in BSM code

---

pimd/pim_cmd.c
pimd/pim_nb_config.c

Deleting a mesh-group member no longer deletes the mesh-group.
Complete bug description at:
https://github.com/FRRouting/frr/issues/9664
Signed-off-by: Adriano Marto Reis <adrianomarto@gmail.com>

pimd: fixing command "no ip msdp mesh-group member"

---

ldpd/ldpd.c
lib/libfrr.c
lib/module.c
lib/module.h
tests/lib/test_grpc.cpp

frrmod_load() attempts to dlopen() several possible paths
(constructed from its basename argument) until one succeeds.
Each dlopen() attempt may fail for a different reason, and
the important one might not be the last one. Example:
dlopen(a/foo): file not found
dlopen(b/foo): symbol "bar" missing
dlopen(c/foo): file not found
Previous code reported only the most recent error. Now frrmod_load()
describes each dlopen() failure.

frrmod_load(): fix error messages

---

tests/topotests/lib/pim.py

Use correct string comparison syntax in lib/pim.py.

tests: fix string comparison in lib/pim.py

---

bgpd/bgp_trace.h

bgpd: fix build error seen when lttng is enabled
bgp_attr.h was needed to build with lttng enabled 

bgpd: fix build error seen when lttng is enabled

---

bgpd/bgpd.c

When a regular access-list is updated, we should update references to
regular access-lists, not as-path access-lists.
Fixes #9707.

bgpd: fix access-list update callback

---

vtysh/vtysh.c

The current code executes either "exit" or "end" once - so vtysh switches
either to the parent node or straight to the config node. But sometimes,
we need to exit to the grandparent node, which is not the config node.
Another issue is that some nodes are completely missing in this long
checklist, for example, BFD peer and profile nodes.
Instead of doing all this special checking, we should just always exit
the exact number of times we need - it is stored in "tried" variable.
The same change was applied to master in commit https://github.com/FRRouting/frr/commit/af581c003b8707a86448e6c0ba77f576f87fd4ac, but it also includes changes to `vtysh_mark_file` which should not be backported, so I opened this PR manually instead of using Mergify.

[8.0] vtysh: fix node walkup

---

bgpd/bgp_evpn.c
bgpd/bgp_evpn_mh.c
bgpd/bgp_evpn_mh.h
bgpd/bgp_trace.h
tools/frr_babeltrace.py

```
Low overhead bgp-evpn TPs have been added which push data out in a binary
format -
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
root@switch:~# lttng list --userspace |grep "frr_bgp:evpn"
frr_bgp:evpn_mh_nh_rmac_zsend (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
frr_bgp:evpn_mh_nh_zsend (loglevel: TRACE_INFO (6)) (type: tracepoint)
frr_bgp:evpn_mh_nhg_zsend (loglevel: TRACE_INFO (6)) (type: tracepoint)
frr_bgp:evpn_mh_vtep_zsend (loglevel: TRACE_INFO (6)) (type: tracepoint)
frr_bgp:evpn_bum_vtep_zsend (loglevel: TRACE_INFO (6)) (type: tracepoint)
frr_bgp:evpn_mac_ip_zsend (loglevel: TRACE_INFO (6)) (type: tracepoint)
root@switch:~#
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
In addition to the tracepoints a babeltrace …
```

bgpd: initial batch of evpn lttng tracepoints

---

zebra/zebra_vty.c

Add json field nexthop group id to
'show ip route json'.
Testing Done:
```
{
"27.0.0.14\/32":[
{
"prefix":"27.0.0.14\/32",
"protocol":"bgp",
"selected":true,
"destSelected":true,
"distance":20,
"metric":0,
"installed":true,
"table":254,
"internalStatus":16,
"internalFlags":8,
"internalNextHopNum":2,
"internalNextHopActiveNum":2,
"nexthopGroupId":103,     <---- New field
"uptime":"00:04:37",
"nexthops":[
{
"ip":"fe80::202:ff:fe00:11",
"interfaceName":"uplink-1",
....
},
{
"ip":"fe80::202:ff:fe00:1d",
"interfaceName":"uplink-2",
...
}
]
}
]
}
```

zebra: add nhg id to show ip route json

---

ospf6d/ospf6_flood.c
ospf6d/ospf6_nssa.c

The lsa->expire thread is for keeping track of when we
are expecting to expire(remove/delete) a lsa.  There
are situations where we just decide to straight up
delete the lsa, but we are not ensuring that the
lsa is not already setup for expiration.
In that case just stop the expiry thread and
do the deletion.
Additionally there was a case where ospf6d was
just dropping the fact that a thread was already
scheduled for expiration.  In that case we
should just setup the timer again and it will
reset it appropriately.
Fixes: #9721

ospf6d: Ensure expire thread is properly stopped

---

lib/command_graph.h

Signed-off-by: ewlumpkin <ewlumpkin@gmail.com>
Couple small spelling mistakes I found in function comments

lib: fix spelling nits in command.h

---

bgpd/bgp_clist.c

The pointer to large community was not the appropriate one.

bgpd: large community exact match fix

---

ospfd/ospf_gr_helper.c
ospfd/ospf_nsm.c

Description:
As per the RFC 3623 section 3.2,
OSPF nbr shouldn't be deleted even in unsuccessful helper exit.
1. Made the changes to keep neighbour even after exit.
2. Restart the dead timer after expiry in helper. Otherwise, Restarter
will be in FULL state in helper forever until it receives the 'hello'.

ospfd: GR helper functionality change in helper exit

---

zebra/debug_nl.c
zebra/rt_netlink.c

Couple of minor changes to allow us to work w/ nested netlink attributes
1) RTM_NEWNEXTHOP is starting to have to parse nested attributes.  FRR does not have the full ability to do this yet.  But this is a bug in parsing that should just be fixed.
2) RTM_NEWNEIGH with bridges have nested attributes.  Ensure that we can parse them in the debug dumps.

Netlink modifications

---

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py

The check_ping function `_check` function was asserting and being
passed to the topotests.run_and_expect() functionality causing
it to not run the full range of pings if one failed the test.
So effectively it was properly detecting pass / failure but
only allowing for 1 iteration if it was going to fail.
Modify the code to not assert and act like all the other
run_and_expect functionality.

tests: Fix `check_ping` function in test_bgp_srv6l3vpn_to_bgp_vrf.py

---

tests/topotests/isis_topo1/test_isis_topo1.py

the isis_topo1 test has two functions where immediately
after the test ensures that the routes are in isis
tests to see if they are in the rib.  Under system
load I am seeing this test failing because the
routes are still queued.  Modify the zebra check
for the isis routes to look for the proper results
for 10 seconds.

tests: isis_topo1 needs to wait for results under load

---

lib/frrscript.c

The script entries were being stored in a hash lookup with
the script name a pre-defined array of characters.  The hash
lookup is succeeding since it is auto-installed at script
start time irrelevant if there is a handler function.
Modify the code so that if the scriptname is an empty
string "\0" just return a NULL so that zebra does
not attempt to actually load up the script

lib: Return Null when we have an empty string for script name

---

tests/topotests/all_protocol_startup/test_all_protocol_startup.py

the test_nexthop_groups function is failing occassionally
because the test executes 4 in succession sharp install
routes commands.  When I dumped the rib on a failed test
run there were only 2 of the 4 routes in the rib and
the two that were in were the last 2 installed.
The sharp daemon setups a event process where it
installs routes `automatically`.  If the previous
run is not finished entering a new command to install
the routes will mess up the last one from ever happening.
It is assumed that the user doesn't do stupid stuff here.
In this case I am just adding a small sleep between each
installation to just let the test proceed.

tests: All_protocol_startup sporadic failure

---

ospf6d/ospf6_spf.c

in show: 'show ipv6 ospf6' handler command, the reason of SPF
executation is looked up and displayed. At startup, SPF has been
started, but shows no specific reason. Instead of dumping non
initialised string context, reset the string context.

ospf6d: avoid writing dumb ospf6 info at startup

---

zebra/zapi_msg.c
zebra/zebra_dplane.c
zebra/zebra_pbr.h

Fixes related to flowspec information needed in zebra dataplane.

Flowspec dplane missing

---

tests/topotests/ospf_topo1/test_ospf_topo1.py

The test does this:
a) shut link down
b) test for ospf convergence
c) ensure the route is installed
When under a heavily loaded system c) is not guaranteed
to happen quickly.  Give the system 10 extra seconds
to ensure it happens.

tests: test_ospf_topo1.py ensure rib has time to converge

---

bgpd/bgp_open.c
bgpd/bgp_open.h
bgpd/bgp_vty.c
bgpd/bgpd.c
bgpd/bgpd.h
doc/user/bgp.rst

Restart Router mode.
FRRouting (Restarter):
```
bgp long-lived-graceful-restart stale-time 10
bgp graceful-restart restart-time 1
```
Tested with GoBGP (Helper):
```
long-lived-graceful-restart:	advertised and received
Local:
ipv4-unicast, restart time 100000 sec
Remote:
ipv4-unicast, restart time 10 sec, forward flag set
```
Logs:
```
{"Key":"192.168.10.123","Reason":"graceful-restart","State":"BGP_FSM_ESTABLISHED","Topic":"Peer","level":"info","msg":"Peer Down","time":"2021-10-25T17:48:36+03:00"}
{"Key":"192.168.10.123","State":"BGP_FSM_IDLE","Topic":"Peer","level":"warning","msg":"graceful restart timer expired","time":"2021-10-25T17:48:37+03:00"}
{"Family":65537,"Key":"192.168.10.123","Topic":"Peer","level":"info","msg":"start LLGR restart timer (10 sec) for …
```

bgpd: Add Long-lived Graceful Restart capability (restarter)

---

ospfd/ospf_dump.c
ospfd/ospf_dump.h
ospfd/ospf_snmp.c
ospfd/ospf_vty.c

Description:
change -1  :  Adding uptime to the 'show ip ospf neighbor' o/p.
Adding uptime and deadtime in string format for json consumption.
change-2  :  Changed the nbr state format to <nbrsate>/- (ex : FULL/-) to P2pnetworks.

ospfd: Few modifications in "show ip ospf neighbor" o/p.

---

pimd/pim_join.c
pimd/pim_register.c
pimd/pim_zebra.c

Problem :
=======
(*,G) created on transit node where same groups are defined as SSM
At present FRR has SSM checks for IGMP report, but SSM check is missing for PIM join.
Fix :
===
1. When an interface receives the PIM (*,G)join with G as SSM group, then PIMd supposed to discard that join.
There is no need to maintain PIM state for this group.
2. Whenever there is a modification in prefix list for SSM range, then we need to browse the ifchannels (PIM joins)
and groups coming in SSM range with (and *,G) should be removed from ifchannel database and also withdraw those routes
from upstream routers.

pimd: Change in PIM join and mroute

---

bfdd/bfd.c
bfdd/bfd.h
bfdd/bfd_packet.c
bgpd/bgp_nht.c
lib/if.c
lib/if.h
lib/nexthop_group.c
ospf6d/ospf6_route.c
zebra/zebra_l2.c
zebra/zebra_vxlan.c

This function doesn't work correctly with netns VRF backend as the same
index may be used in multiple netns simultaneously.
This PR fixes all the incorrect usages and makes the function internal
to prevent future bugs.
Please, check individual commits for the details.

*: fix usage of if_lookup_by_index_all_vrf

---

tests/topotests/pim_basic/test_pim.py

The test system under load looks for upstream state only
1 time immediately after sending 2 streams of S,G data
flowing.  Give the system some time to process this
and ensure that it actually shows up in a small
amount of time.

tests: pim_basic needs to wait for event to happen under load

---

tests/topotests/ldp_vpls_topo1/r1/show_ip_route_after_link_down.ref
tests/topotests/ldp_vpls_topo1/test_ldp_vpls_topo1.py

The test_ldp_pseudowires_after_link_down test
shuts a link down and was blindly waiting 5 seconds
before just assuming the test system was in a sane
state.  Remove the sleep(5) and actually look for
the changed state for the route 2.2.2.2 that the
psueudowire actually depends on.

tests: Ensure ospf has reconverged before continuing

---

bgpd/bgp_bfd.c
bgpd/bgpd.c
lib/bfd.c
lib/bfd.h

Summary
---
This PR fixes a few BFD BGP integration bugs:
- On some configurations IPv6 address changes didn't correctly propagate
- Follow `ebgp-multihop` for BFD session TTL
How to reproduce:
1. Configure remote eBGP peer
2. Shutdown remote interface to avoid local BGP to connect to it
3. Configure local eBGP peer with `ebgp-multihop N`
4. Start remote interface (`no shutdown`)
The local BGP will create a BFD session with single hop because the TTL configuration never got updated.
- Use `update-source` address for BFD session as well
Same issue as with `ebgp-multihop` but worse: if the BGP peers never connected then the session would not be configured at all. Also this PR makes it explicit that we'll use the `update-source` address for BFD session.

bfdd,bgpd: fix some integration bugs

---

doc/user/bgp.rst

This command is not deprecated.

doc: Drop misleading explanation about `neighbor X interface IFNAME`

---

pceplib/test/pcep_msg_tools_test.c
pceplib/test/pcep_session_logic_loop_test.c

Clean up temp files used by some libpcep unit tests; these were being left around in /tmp after any unit-test run.

tests: clean up temp files in libpcep tests

---

ospf6d/ospf6_interface.c
ospf6d/ospf6_message.c
ospf6d/ospf6_neighbor.c
ospf6d/ospf6_neighbor.h

I am seeing a crash of ospf6d with this stack trace:
OSPF6: Received signal 11 at 1636042827 (si_addr 0x0, PC 0x55efc2d09ec2); aborting...
OSPF6: zlog_signal+0x18c                  7fe20c8ca19a     7ffd08035590 /lib/libfrr.so.0 (mapped at 0x7fe20c819000)
OSPF6: core_handler+0xe3                  7fe20c90805e     7ffd080356b0 /lib/libfrr.so.0 (mapped at 0x7fe20c819000)
OSPF6: funlockfile+0x50                   7fe20c7f8140     7ffd08035800 /lib/x86_64-linux-gnu/libpthread.so.0 (mapped at 0x7fe20c7e4000)
OSPF6:     ---- signal ----
OSPF6: ospf6_neighbor_state_change+0xdc     55efc2d09ec2     7ffd08035d90 /usr/lib/frr/ospf6d (mapped at 0x55efc2c8e000)
OSPF6: exchange_done+0x15c                55efc2d0ab4a     7ffd08035dc0 /usr/lib/frr/ospf6d (mapped at 0x55efc2c8e000)
OSPF6: thread_call+0xc2 …

ospf6d: Prevent use after free

---

pimd/pim_join.c
pimd/pim_register.c

We should not be using inet_ntop. and should be using
the appropriate %pI4 instead.

pimd: remove usage of inet_ntop

---

tests/topotests/all_protocol_startup/test_all_protocol_startup.py

The route replace test was doing this seq of events:
a) Create nhg
b) Install route w/ sharpd
c) Ensure it worked
d) Modify nhg
d) Ensure the update group replace worked
The problem is that the sharp code is doing this:
/* Only send via ID if nhgroup has been successfully installed */
if (nhgid && sharp_nhgroup_id_is_installed(nhgid)) {
SET_FLAG(api.message, ZAPI_MESSAGE_NHG);
api.nhgid = nhgid;
} else {
for (ALL_NEXTHOPS_PTR(nhg, nh)) {
api_nh = &api.nexthops[i];
zapi_nexthop_from_nexthop(api_nh, nh);
i++;
}
api.nexthop_num = i;
}
The created nhg has not been successfully installed( or at least
sharpd has not read the results yet) when it gets the command
to install the routes.  As such it passes down the individual
nexthops instead.  The route replace is never going to work.
Modify the …

tests: Fix route replace test in all_protocol_startup

---

zebra/zapi_msg.c

Currently the NEXTHOP_TYPE_IPV4 and NEXTHOP_TYPE_IPV6 are
not sending up the resolved ifindex for the route.  This
is causing upper level protocols that have something like
this:
route-map FOO permit 10
match interface swp13
!
router ospf
redistribute static
!
ip route 4.5.6.7/32 10.10.10.10
where 10.10.10.10 resolves to interface swp13.  The route-map
will never match in this case.
Since FRR has the resolved nexthop interface, FRR might as
well send it up to be selected on by the upper level protocol
as needed.

zebra: Send up ifindex for redistribution when appropriate

---

lib/vty.c
lib/vty.h

- remove unused `vty_log()` related functions
- convert `vtyvec` & `vtyshvec` to simple DLIST (only used for iteration…)
- convert listeners into a proper `struct vty_serv` and put them in DLISTs too
⇒ 4 `vector_init()` calls gone, 30 remaining.

lib: 🧹🧹🧹 vty code 🧹🧹🧹

---

tests/topotests/bgp_community_change_update/c1/bgpd.conf
tests/topotests/bgp_community_change_update/x1/bgpd.conf

949aaea5 removed debugs from all topotests, but this test relies on the
debug logs so it constantly fails now.

tests: fix bgp_community_change_update

---

bgpd/bgp_route.c

AFI/SAFI is handled in bgp_vty_find_and_parse_afi_safi_bgp() properly for
IPv4, but not for IPv6. Let's have it enabled for IPv6 by default.
Closes https://github.com/FRRouting/frr/issues/9976

bgpd: Set afi by default to AFI_IP6 for `show bgp vrf/view all`

---

zebra/table_manager.c
zebra/zebra_vrf.c

Before 42d4b30e, table_manager_enable was called only once and the hook
was also registered once. After the change, the hook is registered per
each VRF that is created in the system. This is wrong.

zebra: don't register same hook multiple times

---

tests/topotests/bfd_ospf_topo1/test_bfd_ospf_topo1.py

When our CI test system is under high load, expecting bfd to
converge in under 2 seconds is not going to happen.  Modify the test
suites to just ensure that things reconvderge.

tests: bfd_ospf_topo1 expects unreasonable convergence times under load

---

lib/resolver.c
lib/vector.c
lib/vector.h
tests/.gitignore
tests/lib/cli/common_cli.c
tests/lib/cli/common_cli.h
tests/lib/test_resolver.c
tests/subdir.am

(commit message:)
The `struct thread **ref` that the thread code takes is written to and needs to stay valid over the lifetime of a thread.  This does not hold up if thread pointers are directly put in a `vector` since adding items to a `vector` may reallocate the entire array.  The thread code would then write to a now-invalid `ref`, potentially corrupting entirely unrelated data.
This should be extremely rare to trigger in practice since we only use one c-ares channel, which will likely only ever use one fd, so the vector is never resized.  That said, c-ares using only one fd is just plain fragile luck.
Either way, fix this by creating a resolver_fd tracking struct, and clean up the code while we're at it.
(this should be backported to 8.1 & 8.0 at least)
---
Randomly bumped into this …

lib: fix `struct thread **` misuse in c-ares resolver bindings

---

configure.ac
isisd/isis_circuit.c
isisd/isis_lsp.c
isisd/isis_main.c
isisd/isis_pdu.c
isisd/isis_sr.c
isisd/isisd.c
isisd/subdir.am

Hello,
this PR adds fuzz harnesses for isisd and fabricd.
The harnesses send the input received from the fuzzer to `isis_handle_pdu()`.  There is some coverage overlap with `test_fuzz_isis_tlv` which calls TLV functions but I think this harness should achieve wider coverage. It has already found some issues that I haven't managed to easily reproduce with `test_fuzz_isis_tlv`.
I've let the isisd fuzzer run for around a month so far with ASAN and UBSAN. It initially discovered a few dozen issues in router capability TLV parsing and in `unpack_item_ext_subtlvs()`. After that there have been no new crashes but the fuzzer continuously found new paths, so I assume it is working fine. The fixes for those issues are available in PRs #9850 and #9851
I formatted the changes with `clang-format` and …

isisd: add fuzzers for isisd and fabricd

---

pimd/pim_msdp.c

frr-reload fails to recognize wildcard "*" for
member address in frr.conf/runing-config as cli
syntax expects in v4 address format.
Ticket: #2816923
Testing:
Without fix:
```
running config:
ip msdp mesh-group foo1 member *
Frr reoad failure log:
2021-11-02 11:05:04,317  INFO: Loading Config object from vtysh show running
line 5: % Unknown command: ip msdp mesh-group foo1 member *
Traceback (most recent call last):
File "/usr/lib/frr/frr-reload.py", line 1950, in <module>
```
With fix:
--------
running config displays:
```
ip msdp mesh-group foo1 member 0.0.0.0
```

pimd: fix msdp mesh grp with wildcard member addr

---

bgpd/bgp_label.h
bgpd/bgp_route.c
bgpd/bgp_route.h
tests/topotests/lib/bgprib.py

Some work was done a while ago to offer a "show bgp \<afi> \<safi> json detail" cli, but that didn't include some info that is available via the single-prefix cli "show bgp ... \<prefix>". The single-prefix cli uses a different code path that includes the `route_vty_out_detail_header()` function. This tries to add that 'header' call in for the "json detail" form.

bgpd: Add 'show bgp <afi> <safi> json detail' header data

---

bfdd/bfdd_vty.c

show/clear DEFUNs always require either peer label or IP address to be
specified, so if `label` is NULL then `peer_str` is definitely not NULL.
But Coverity doesn't know about that, so it complains about possible
NULL dereference of `peer_str`. This commit should make Coverity happy.

bfdd: fix coverity warnings

---

doc/user/bgp.rst

A little fix for bgp doc, remove redundant chars.

doc: remove redundant chars for bgp

---

zebra/rtadv.c

The rtadv_timer() sends RA packets for all interfaces in all VRFs no matter whether the interface belong or not belong to the current thread's vrf, and when it uses the zvrf's socket (zvrf->rtadv.sock) to send packets for the interface that not belong to the vrf, it would be failed because the socket does not in the same netns as the interface, so the `error 19 (No such device)` would happen.
Issue reported: #9821
Solution:
Skip the interfaces that are no in the same vrf as the current thread's zvrf.

zebra: Fix the RA packets can not sent out

---

pimd/pim_cmd.c
pimd/pim_upstream.c

enum based switches should never use default.  It makes
it very hard to fix and find issues when the enum is
changed.

pimd: Remove default from enum based switch

---

ospf6d/ospf6_gr.h
ospf6d/ospf6_gr_helper.c

Description:
Addressed the following TAINTED_SCALAR issue which can possibly
leads to memory currption.
1. *** CID 1506514:  Insecure data handling  (TAINTED_SddddddCALAR)
/ospf6d/ospf6_gr_helper.c: 1222 in ospf6_grace_lsa_show_info()
2. *** CID 1506513:  Insecure data handling  (TAINTED_SCALAR)
/ospf6d/ospf6_gr_helper.c: 160 in ospf6_extract_grace_lsa_fields()

ospf6d: Addressing few coverity issues.

---

doc/developer/building-frr-for-archlinux.rst
doc/developer/building-frr-for-centos7.rst
doc/developer/building-frr-for-centos8.rst
doc/developer/building-frr-for-debian9.rst
doc/developer/building-frr-for-fedora.rst
doc/developer/building-frr-for-freebsd10.rst
doc/developer/building-frr-for-freebsd11.rst
doc/developer/building-frr-for-opensuse.rst
doc/developer/building-frr-for-ubuntu1804.rst
doc/developer/building-frr-for-ubuntu2004.rst
doc/developer/building-libunwind-note.rst
doc/developer/conf.py
doc/developer/subdir.am
doc/user/basic.rst
lib/atomlist.c
lib/elf_py.c
lib/frrcu.h
lib/log_vty.c
lib/typerb.h
lib/typesafe.c
lib/typesafe.h
lib/xref.c
lib/xref.h
lib/zlog.c
lib/zlog.h

This adds `debug unique-id XXXXX-XXXXX backtrace`, which prints a backtrace whenever the specified log message is printed. It looks like this:
```
areia# debug unique-id ZWE6K-GRWAN backtrace
[…]
2021/11/10 11:09:57.718033 debugging: ZEBRA: [ZWE6K-GRWAN] Not Notifying Owner: kernel about prefix 0.0.0.1/32(254) 3 vrf: 0
2021/11/10 11:09:57.718036 debugging: ZEBRA: | (ZWE6K-GRWAN) message in thread 115524, at route_notify_internal(), zebra/zapi_msg.c:758
2021/11/10 11:09:57.718888 debugging: ZEBRA: | (ZWE6K-GRWAN) route_notify_internal+0xa3               5595a8b73000+000ae37a     7ffcc8d4c920 /home/equinox/c/frr-xref-bt/zebra/.libs/zebra
2021/11/10 11:09:57.719080 debugging: ZEBRA: | (ZWE6K-GRWAN) zsend_route_notify_owner_ctx+0x9c        5595a8b73000+000ae5e6     7ffcc8d4c990 …
```

lib: backtraces for specific log messages

---

zebra/zebra_vxlan.c

Problem:
L2-VNI SVI down followed by L2-VNI's vxlan device
deletion leads to stale entry into L3VNI's
L2-VNI list.
Solution:
When L2-VNI associated SVI is down, default vrf
is the new tenant vrf.
Remove L2-VNI from L3VNI's l2vni list as
L3VNI/VRF is no longer valid in absence of associated
SVI.
When SVI is up re-add L2-VNI into associated VRF's
L3VNI.
The above remove/add from the L3VNI's L2VNI list is
already done when vxlan or L2-VNI is flaped, just need
to handle when SVI is flapped.
Testing Done:
After deleting SVI following by L2-VNI deletion,
L3VNI's L2-VNI list delets the L2-VNI. (no stale entry).
After adding back SVI/L2-VNI, L3VNI list adds back the
L2-VNI and it is associated right tenant VRF.

zebra:  svi down remove evpn l2vni from l3vni list

---

bgpd/bgp_aspath.c
bgpd/bgp_nht.c
bgpd/bgp_updgrp_adv.c
bgpd/bgpd.h
ldpd/hello.c
ldpd/init.c
ldpd/ldpe.h
lib/snmp.c
pathd/path_pcep_controller.c
pimd/pim_msdp_packet.h
pimd/pimd.h
ripngd/ripng_nexthop.c

We had various forms of min/max macros across multiple daemons
all of which duplicated what we have in compiler.h.  Convert
everyone to use the `correct` ones

*: use compiler.h MIN/MAX macros instead of everyone having one

---

zebra/zebra_vrf.c

42d4b30e introduced per-VRF table manager.
Table manager is allocated when the VRF is created, but it is freed when
the VRF is disabled. When this VRF is re-enabled, zebra ends up with
table manager being NULL pointer and it crashes on any dereference.
Table manager should be freed when the VRF is deleted, not when it's
disabled.

zebra: fix disabling table manager

---

lib/if.c
lib/vrf.c
ospfd/ospf_interface.c

Currently, we automatically delete an inactive VRF when its last
interface is deleted. This code introduces a couple of crashes because
of the following problems:
- vrf_delete is called before calling if_del hook, so daemons may try to
dereference an ifp->vrf pointer which is freed
- in if_terminate, we continue to use the VRF in the loop condition
after the last interface is deleted
This check is needed only when the interface is deleted by the user,
because if the interface is deleted by the system, VRF must still exist
in the system. Move the check to appropriate places to fix crashes.

lib: fix vrf deletion when the last interface is deleted

---

isisd/isis_adjacency.c
isisd/isis_adjacency.h
isisd/isis_snmp.c

These variables are only assigned with time() which returns time_t.
This should also fix occasional CI build failures because of comparisons
of signed and unsigned integers.

isisd: use time_t for last update and last flap

---

zebra/zebra_vxlan.c

Bad style introduced in
https://github.com/FRRouting/frr/pull/10006

zebra: use tabs instead of spaces zebra_vxlan.c

---

lib/bfd.c
lib/bfd.h

There are two APIs to control the expected number of hops for a BFD
session – `bfd_sess_set_mininum_ttl` and `bfd_sess_set_hop_count`.
The former is very confusing, as it takes an expected TTL in the
BFD packet which is actually a protocol internal value. The latter is
simple and straightforward – it takes an expected number of hops, which
is always 1 for single-hop and >1 for multi-hop.
As the former API is not used anywhere, just remove it to avoid any
confusion.

lib: remove confusing bfd TTL API

---

bgpd/bgp_bfd.c

When "update-source IFNAME" is used for the neighbor, p->update_source
is set to NULL, so we can't use it as a source address and should use
the address from p->su_local.

bgpd: fix source-address for BFD sessions when using update-source IFNAME

---

zebra/main.c
zebra/zebra_router.c

Free the LSP workqueue later during shutdown, so that zebra has enough time to clean up and uninstall any LSPs.

zebra: free LSP workqueue later during shutdown

---

tools/frr-reload.py

This file uses string literals in place of comments, for some reason. Probably someone misunderstood how [docstrings](https://www.python.org/dev/peps/pep-0257/) work.
Also converts an `if (... or ... or ... or ... or ... or ... or ...)` to a less complicated form. Couldn't resist.

Fix reload comments

---

ospfd/ospf_vty.c

Description:
timerval data structure is being used without initialization.
Using these uninitialized parameters can lead unexpected results
so initializing before using it.

ospfd: fixing few coverity issues in ospf_vty.c

---

ospfd/ospf_te.c

Function ospf_te_parse_te() and ospf_te_delete_te() browse TE TLV but also
subTLV. The loop that parse the subTLV check that cummulative read data doesn't
exceed the total size of the TLV. However, the sum variable that counts the
number of read data was wrongly intialize to 0 instead to 4 (i.e. the initial
TLV Header size that is located at the TOP of subTLV).
This patch adjust accordingly the initial value of the counter.

ospfd: Fix wrong parsing of TE subTLV

---

ospfd/ospf_nsm.c

OSPF_NSM_TIMER_ON must be called regardless of debug configuration.

ospfd: fix code being guarded by debug check

---

tools/valgrind.supp

More memory leaks from libyang that we can just ignore

tools: Add another valgrind suppression for libyang

---

zebra/table_manager.c

During shutdown, when table_manager_disable is called for the default
VRF, its vrf_id is already set to VRF_UNKNOWN, so the expression is true
and the table manager memory is not freed. Change the expression to
compare the VRF name instead of the id. The check in table_manager_enable
is changed for consistency.

zebra: fix memleak on shutdown

---

ospfd/ospf_gr.c

The no-form should use the same arguments as the regular command, hence
replace "period" with "grace-period".

ospfd: fix no-form of "graceful-restart" command

---

isisd/isis_circuit.c
isisd/isis_circuit.h

We don't need to scan through all configured areas to find the circuit
associated with the interface. It is always stored in ifp->info.

fabricd: cleanup interface config output

---

lib/vty.c

Getcwd failed and then chdir(SYSCONFDIR) returns 0. In this condition, It should continue vty_init function instead of entering the if and exist. This will cause zebra failing to start in a non-existent path.
Signed-off-by: Solyn <admin@iloft.xyz>

zebra: fix chdir judgment to avoid starting failed in a non-existent directory

---

zebra/zapi_msg.c
zebra/zebra_dplane.c
zebra/zebra_dplane.h
zebra/zebra_pbr.c

There are 3 dplane_ctx_get_XXX functions for pbr that return true/false.  False is only ever returned because the developer would pass in a null pointer.  Which is useless.  change to an assert to signify the api that we want and don't return true false.

Do not return true/false in dplane_ctx_get_XXX functions

---

tools/frr-reload.py
vtysh/vtysh.c

This was deprecated over a year ago now.  Let's finally
remove it from the system.

tools, vtysh: Remove final vestige of `address-family evpn`

---

vtysh/vtysh.c

I don't know how my original compile didn't fail
or I didn't notice :(

vtysh: Really remove `address-family evpn`

---

lib/ferr.c
lib/filter.c
lib/json.c
lib/json.h
lib/plist.c
lib/routemap.c
lib/vty.c
lib/vty.h

All of this pretty much should've been added years ago:
- `vty_json(vty, json)` - prints `json` to `vty` (with if != NULL) and returns `CMD_SUCCESS` so you can do `return vty_json(vty, json);`
- `json_object_new_stringf("%pFX", prefix)` - call `printfrr` to format args, put result into JSON
- `json_array_string_addf(json, "%pFX", prefix)` - you can guess this one
- `json_object_string_addf(json, "dictkey", "%pFX", prefix)` - you can guess this one too
I haven't done any bulk-replacing on this, that's a separate step that coccinelle can aid with, and should probably happen stepwise after this PR to ease merge conflicts.

lib: make JSON output less painful/boilerplate-y

---

pimd/pim_zebra.c

pimd: use correct VRF when processing interface address add

---

lib/northbound.c

This prevents caller from getting complete validation message.

lib: Do not use sizeof() on `size_t errmsg_len`.

---

zebra/zserv.c

At some scale we eventually run out of room displaying v4/v6 route
totals for `show zebra client summ`:
janelle# show zebra client summ
Name      Connect Time    Last Read  Last Write  IPv4 Routes       IPv6 Routes
--------------------------------------------------------------------------------
bgp           04w0d18h     00:00:19    00:01:2411729127/4052681  2037786/903094
This total over ran the space in just a little over a week of uptime.
Expand to have a bit more room.

zebra: Expand v4/v6 route space

---

pimd/pim_bsm.c
pimd/pim_rp.c

on rp_change, PIM processes all the upstream in a loop and for selected
upstreams PIM has to send join/prune based on the RPF changed.
join and prune packets are not getting aggregated in a single packet.
on pim_rp_change pim_upstream_update() gets called for selected upstreams.
This API calculates to whom it has to send join and to whom it has to
send prune via API pim_zebra_upstream_rpf_changed(). This API peprares
the upstream_switch_list list per interface and inserts the group and
sources.
Now PIM is still in the pim_upstream_update() API context, i.e PIM
is still processing the same upstream. In the last there is a
call to pim_zebra_update_all_interfaces() which processes the
upstream_switch_list list, sends the packets out and clears …

pimd : packet processing optimization on rp change

---

bgpd/bgp_vty.c
lib/command.c
lib/command.h
lib/log_vty.c
lib/routemap.c
lib/routemap.h
ospf6d/ospf6_lsa.c
ospf6d/ospf6_lsa.h
ospf6d/ospf6_neighbor.c
vtysh/vtysh.c
zebra/interface.c

(refer to individual commits for details)
- removes a `vector` use from ospf6d for its LSA handlers (they're constant anyway)
- converts the route-map code from using a `vector` for its set/match items to a hash (which is what's appropriate for the use, i.e. lookup by name)
- replaces hardcoded CLI node numbers in `vty_check_node_for_xpath_decrement()` with a flag in `struct cli_node` for the particular node (so less changes in `lib/` that are really daemon changes)
- make vtysh actually able to configure the per-UID backtraces added in #10025
(25 uses of `vector_init()` remaining…)

lib/vtysh/ospf6d: assorted small bits

---

bgpd/bgp_ecommunity.c

the fix consists in parsing the ext community list ipv6 by taking
account the size of the ecommunity val size.

bgpd: support redirect import more than one route-target ipv6

---

bgpd/bgp_routemap.c
bgpd/bgp_routemap_nb_config.c
doc/user/routemap.rst
lib/routemap_cli.c

For IPv4 matching, we have "match ip next-hop address A.B.C.D".
For IPv6 matching, we have "match ipv6 next-hop X:X::X:X".
To have consistency, let's add "address" keyword to IPv6 commands.
Old commands are preserved as hidden for backward compatibility.

bgpd, lib: fix inconsistency of match ip/ipv6 next-hop commands

---

pimd/pim_ifchannel.c
pimd/pim_upstream.c
pimd/pim_zebra.c
pimd/pim_zebra.h

The ordering of actions is just wrong here, causing us to not remove MFC entries until something else bumps it.
(Free bonus cleanup included.)

pimd: fix stale forwarding entries left around after join goes away

---

lib/link_state.c

Use the _safe iterators when cleaning up the link-state module's vertices, edges, and subnets rbtrees, otherwise we may deref free'd memory.

lib: use _safe iteration during link_state/ted cleanup

---

ospf6d/ospf6_route.c
ospf6d/ospf6_route.h

ospf6d: memcmp cleanup

---

pimd/pim_upstream.c

Mroutes are not recovered after shut/no shut of DUT to RP links
One interface is not added in OIL List in intermediate router,
hence traffic never received at LHR and mroutes not created for (S,G).
```
(Receiver)
eth3
|
R3 ---0--> PIM join------eth0--- R1 ---eth1---------- R2(RP) ----------- R4 (SRC) (10.0.5.1) (226.1.1.1)
|
eth2
|
IGMP join (Receiver)
```
Problem is happening at nodes R3 and R1.
1. R1 has IGMP join and PIM join.
2. mroutes will be like this on R1
(*,g) eth1    pimreg, eth0, eth2
(s,g) eth1    eth0, eth2 
3. Now unicast route for SRC removed from R3 and R1 by interface shut.
4. At this point, mroutes will be removed from kernel.
5. KAT timer is still running.
6. Now make the routing up via interface no shut.
7. R3 sends the …

pimd: STAR inherited Flag not properly set in certain scenarios

---

staticd/static_zebra.c

When the VRF interface is coming up, we don't need to fixup VRF ids - it
was already done in static_vrf_enable when the interface was created.

staticd: remove unnecessary function call

---

ospfd/ospf_ase.c

Description:
When changing the area from normal to NSSA, previous area's
ASBR router's type-5 also calculated and added to routing table along
with Type-7 lsas.
Made a change in route calculation such that it will not consider Type-5
lsas in calculation if it is originated from NSSA ASBR router.
These lsas will be age out at MAX age.
log:
frr(config-router)# do show ip route
T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
f - OpenFabric,
K>* 0.0.0.0/0 [0/0] via 10.112.157.253, ens160, 00:32:47
C>* 10.112.156.0/23 is directly connected, ens160, 00:32:47
S>* …

ospfd: ospf routing table update upon Changing area from normal to nssa

---

ospf6d/ospf6_asbr.c
ospf6d/ospf6_flood.c
ospf6d/ospf6_flood.h
ospf6d/ospf6_top.c
ospf6d/ospf6_top.h

The external_id_table was only ever used to store pointers to data
and was never used for lookup during the course of normal operations.
However it did lead to crashes because somewhere along the way
external routes stored in the external_table never had their
id associated into the external_id_table and we would assert
on the node lookup failing.
Since this code was never used for anything other than
storing data and it was never retrieved for anything useful
let's just remove it from ospf6d.

ospf6d: Remove ospf6->external_id_table

---

tests/topotests/lib/ospf.py
tests/topotests/lib/topojson.py
tests/topotests/ospf_basic_functionality/test_ospf_lan.py
tests/topotests/ospf_dual_stack/test_ospf_dual_stack.json

See individual commits, but the gist of all this started when I had ospf tests failing because the router-id that was being looked for had already been decided by the time the test issued a `router <ospf|ospf6>\nrouter-id A.B.C.D`.  Operationally ospf was not reseting the router id and tests were failing.  
So when we create router config, let's automatically reset the peering so that we don't have to worry about this anymore

Ospf test cleanup

---

pimd/pim_upstream.c

RCA: When upstream transition from Joined to NotJoined due to SGRpt
prune, then only SGRpt prune was sent and SG Prune is missed.
Fix: Send SG Prune towards source as well as SGRpt prune towards RP.
Signed-off-by: Saravanan K <saravanank@vmware.com>

pimd: During Joined -> NotJoined, upstream should send prune nomatter

---

doc/developer/frr-release-procedure.rst

Clarify process for editing changelog and updating the configure.ac
project version, as well as procedure for doing sanity testing prior to
creating the release tag.

doc: update release process

---

tests/topotests/bgp_route_server_client/r1/bgpd.conf
tests/topotests/bgp_route_server_client/r2/bgpd.conf
tests/topotests/bgp_route_server_client/r3/bgpd.conf

The new bgp_route_server_client test is not setting the
timers for peers to be fast enough to have the ability
to converge in under 60 seconds if a packet is dropped/missed
at startup.  Make the test have the ability to converge
under load

tests: Add aggressive timers to the new route server client test

---

pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_ifchannel.c
pimd/pim_ifchannel.h
pimd/pim_igmp.c
pimd/pim_igmp.h

Removing the no caller function declarations and definitions
in pimd directory.

pimd: removing no caller functions

---

ospfd/ospf_asbr.c

When the summary-address is deleted, `ospf_aggr_handle_external_info` is
called for each aggregated route for the cleanup. It needs to find the
corresponding OSPF instance and it does it using the `ei->instance`
which is totally wrong, because it's the instance from which the route
is redistributed, not the local OSPF instance. A pointer to the correct
OSPF instance is already stored in the external_info structure.

ospfd: fix summary-address deletion

---

vtysh/vtysh_config.c

Before:
```
frr version 8.2-dev
hostname frr
rpki
rpki polling_period 20
rpki cache 192.0.2.1 8080 preference 1
service integrated-vtysh-config
!
```
After:
```
frr version 8.2-dev
hostname frr
service integrated-vtysh-config
!
rpki
rpki polling_period 20
rpki cache 192.0.2.1 8080 preference 1
exit
!
```

vtysh: add missing rpki node when showing config

---

ospf6d/ospf6_message.c
tests/topotests/lib/ospf.py
tests/topotests/ospfv3_basic_functionality/ospfv3_nssa.json
tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa.py

RFC 3101 states both E-bit and N-bit need to be checked when receiving a Hello packet.
```
To support the NSSA option an additional check must be made in the function
that handles the receiving of the Hello packet to verify that both the N-bit
and the E-bit found in the Hello packet's option field match the area type and
ExternalRoutingCapability of the area of the receiving interface.
```
This PR adds the check for the N-bit

ospf6d: check N-bit in Hello packet

---

bgpd/bgp_packet.c
bgpd/bgp_packet.h

stream size is never checked anywhere in the code, just convert to void.

bgpd: bgp_packet_set_size int to void

---

zebra/main.c
zebra/zebra_router.c
zebra/zebra_router.h

On startup we create a thread timer event to do a rib sweep
of the system.  On shutdown we never stopped this timer and
as such we have a situation where a thread event could be run
on shutdown after the data for it has been freed.  Here is the
crash I am seeing:
(gdb) bt
(gdb)
Save the thread data in zebra_router and stop the thread so we don't
accidently do work on shutdown we don't mean to.  In this case
it happened in our topotests with some severe system load.
Essentially we happened to kill the zebra daemon just as the
graceful_restart timer popped here.

zebra: Prevent thread usage of data after it being freed

---

tests/topotests/lib/pim.py

Currently under system load tests that use verify_pim_interface_traffic
immediately after a interface down/up event are not giving any time
for pim to receive and process the data from that event.  Give
the test some time to gather this data.

tests: Allow interface statistics to be gathered with some delay

---

pimd/pim_nb_config.c

user config should go ahead no matter it is a query router or not
Signed-off-by: ron <lyq140hf2006@163.com>

pimd: fix igmp user config

---

bgpd/bgp_mpath.c
bgpd/bgp_mplsvpn.c
bgpd/bgp_route.c
bgpd/bgp_route.h
bgpd/bgp_routemap.c
bgpd/bgp_zebra.c
bgpd/bgp_zebra.h
tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py
tests/topotests/bgp_vrf_lite_best_path_test/bgp_vrf_lite_best_path_topo1.json
tests/topotests/bgp_vrf_lite_best_path_test/bgp_vrf_lite_best_path_topo2.json
tests/topotests/bgp_vrf_lite_best_path_test/test_bgp_vrf_lite_best_path_topo1.py
tests/topotests/bgp_vrf_lite_best_path_test/test_bgp_vrf_lite_best_path_topo2.py
tests/topotests/lib/bgp.py

Description:
Incorrect behavior during best path selection for the imported routes.
Imported routes are always treated as eBGP routes.
Change is intended for fixing the issues related to
bgp best path selection for leaked routes:
- FRR does ecmp for the imported routes,
even without any ecmp related config.
If the same prefix is imported from two different VRFs,
then we configure the route with ecmp even without
any ecmp related config.
- Locally imported routes are preferred over imported
eBGP routes.
If there is a local route and eBGP learned route
for the same prefix, if we import both the routes,
imported local route is selected as best path.
- Same route is imported from multiple tenant VRFs,
both imported routes point to the same VRF in nexthop.
- When the same route with same …

bgpd: VRF-Lite fix best path selection

---

bgpd/bgp_bmp.c
lib/resolver.c
lib/resolver.h
nhrpd/nhrp_nhs.c
tests/lib/test_resolver.c

add a parameter to resolver api that is the vrf identifier. this permits
to make resolution self to each vrf. in case vrf netns backend is used,
this is very practical, since resolution can happen on one netns, while
it is not the case in an other one.

lib: resolver per vrf support

---

tests/topotests/lib/topotest.py

Lot's of the GR topotests kill daemons in order to test code
that deals with crashing daemons.  Under heavy system load
it was noticed that a kill command was sent and if told to
wait we would sleep 2 seconds send another kill command and
call it good.  This was causiing issues when subsuquent
json commands would get errors like `lost connection to daemon`
as the daemon finally shut down after some time due to load.
Modify the kill the daemon function to notice that the daemon
was not actually killed and if we need to wait wait some
more time for it too happen

tests: Fix Daemon Killing to actually notice when a deamon dies

---

bgpd/bgp_label.c
bgpd/bgp_route.c

Don't hide the LABELED_UNICAST safi when processing route updates; map it where necessary (to use the UNICAST table for instance). Without this, an 'in' direction route-map configured for the LABELED_UNICAST safi would not be run, because the real safi was being lost.

bgpd: clearer safi handling for BGP-LU route updates

---

pimd/pim_hello.c
pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_neighbor.c
pimd/pim_pim.c
tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py

pim maintains two counters hello tx and hello rx at interface level.
At present pim needs to send the hello message prior to other pim
message as per RFC. This logic is getting derived from the tx hello
counters. Ideally we should not set the tx counters to zero
on the new neighbor addition.
**Fix:**
Let the counters not reset to zero, on neighbor addition since it is statistics for hello.
Use a flag to note down, PIM has to send the hello message.

pimd: hello sent stats counter change and new flag addition to decide hello send

---

lib/if.c
lib/vrf.c
yang/frr-interface.yang
yang/ietf/frr-ietf-translator.json

This is needed for the following two reasons:
1. To be able to remove the northbound HACK in if_update_to_new_vrf. It
is totally wrong to rewrite the configuration datastore when some
operational state changes. It is a hard blocker for storing a
configuration data in a management daemon which knows nothing about
the operational state.
2. To allow changing the VRF of the interface using FRR CLI or any other
frontend in the future. If the VRF is a part of the key, it can't be
changed. If the VRF is a simple leaf, it becomes possible to change
it and thus move the interface between VRFs. For now I mark the leaf
as a "config false" as it's not yet possible to control it from FRR.
But we can't simply remove the VRF from the key, because it is needed to
distinguish interfaces when using netns …

lib, yang: remove vrf from the interface list key

---

pimd/pim_cmd.c
pimd/pim_iface.c
pimd/pim_iface.h
pimd/pim_igmp.c
pimd/pim_igmpv3.c
pimd/pim_mroute.c
pimd/pim_nb_config.c
pimd/pim_vty.c
pimd/pim_zebra.c

Modifying the members of pim_interface which are to be used
for both IPv4 and IPv6 to common names(for both MLD and IGMP).
Issue: #10023
Co-authored-by: Mobashshera Rasool <mrasool@vmware.com>
Co-authored-by: Sarita Patra <saritap@vmware.com>

pimd: Modifying members of pim_interface to accommodate IPv6 changes

---

isisd/isis_cli.c

YANG leaf means "enable" while CLI command is "disable".
So we should use "no" when the leaf is "true", not "false".

isisd: fix running-config for fast-reroute
