FRRouting/frr

vtysh/vtysh_config.c
When both ripd and eigrpd run at the same time, all key configuration in
key chain node is duplicated. This change adds a concept of nested nodes
into vtysh to fix the issue.
Before:
```
key chain test
key 1
key-string 1
exit
key 1
key-string 1
exit
!
```
After:
```
key chain test
key 1
key-string 1
exit
!
```
=> vtysh: fix duplicated output of key chain configuration

pimd/pim_vxlan.c
pim-vxlan uses periodic null registers to bootstrap a new (VTEP, mcast-grp).
These null registers were not being sent if the (S, G) was already present
and in a register-join state.
Ticket: #2848079
=> pimd: handle vxlan sg add/del for upstream entries that are in a reg-join state

tests/topotests/bgp_route_server_client/r1/bgpd.conf, tests/topotests/bgp_route_server_client/r2/bgpd.conf, tests/topotests/bgp_route_server_client/r3/bgpd.conf, tests/topotests/bgp_route_server_client/test_bgp_route_server_client.py
Lower connect timer to 5 seconds as well.
```
FAILED test_bgp_route_server_client.py::test_bgp_route_server_client - AssertionError: Cannot see BGP GUA next hop from r3 in r1
```
```
2021-12-02 14:41:21,115 INFO: topolog.r1: vtysh command => "show bgp 2001:db8:f::3/128 json"
2021-12-02 14:41:21,115 DEBUG: topolog.r1: LinuxNamespace(r1): cmd_status("['/bin/bash', '-c', 'vtysh  -c "show bgp 2001:db8:f::3/128 json" 2>/dev/null']", kwargs: {'encoding': 'utf-8', 'stdout': -1, 'stderr': -2, 'shell': False, 'stdin': None})
2021-12-02 14:41:21,159 INFO: topolog.r1: vtysh result:
{
}
```
At least can't reproduce a failure locally (before managed to catch it).
Ran >2000 times, no failure.
=> tests: Test if BGP session is up additionally for route_server_client setup

tools/frr-reload.py
Remove neighbor <> remote-as <> config line, if the neighbor is part of the peer-group
and peer-group contains remote-as config.
Neighbor part of peer-group can not override
remote-as.
Fix:
Frr-reload needs to remote 'neighbor <> remote-as <>'
from lines_to_add if its already part of peer-group
and peer-group has remote-as config.
Testing Done:
Config snippet:
```
neighbor PEERS peer-group
neighbor PEERS remote-as external
neighbor 10.2.1.2 remote-as external
neighbor 10.2.1.2 peer-group PEERS
```
Before:
```
Frr-reload failure:
line 179: Failure to communicate[13] to bgpd, line:  neighbor 10.2.1.2
remote-as external
% Peer-group member cannot override remote-as of peer-group
```
After:
```
frr-reload apply the config succesfully.
```
=> frr-reload: fix bgp nbr remote-as rendering

bfdd/bfd.c, bfdd/bfd_packet.c
Per RFC 5880 section 6.8.12, the use of a Poll Sequence is not necessary
when the Detect Multiplier is changed. Currently, we update the Detection
Timeout only when a Poll Sequence is terminated, therefore we ignore the
Detect Multiplier change if it's not accompanied with RX/TX timer change.
To fix the problem, we should update the Detection Timeout on every
received packet.
=> bfdd: fix detection timeout update

ospf6d/ospf6_abr.c
In a topology like:
```
r1 ---- 0.0.0.0 ---- r2(ABR) ---- 1.1.1.1 -----r3(ASBR)
```
where r3 is redistributing statics and area 1.1.1.1 is NSSA, the ABR r2 should
not originate type-4 LSA, according to RFC 3101, section 1.3:
"also an NSSA's border routers never originate Type-4 summary-LSAs for the
NSSA's AS boundary routers, since Type-7 AS-external-LSAs are never flooded
beyond the NSSA's border"
``` 
r1# sh ipv6 os database inter-router
Area Scoped Link State Database (Area 0.0.0.0)
Type LSId           AdvRouter       Age   SeqNum                        Payload
IAR  3.3.3.3        2.2.2.2          49 80000001                        3.3.3.3
```
This PR prevents the above LSA of being originated by the ABR r2
Likewise, if r1 is redistributing statics, r2 should not inject a type-4 LSA …
=> ospf6d: do not originate Type-4 lsa when NSSA

tests/topotests/ripng_topo1/r1/ripng_status.ref, tests/topotests/ripng_topo1/r1/ripngd.conf, tests/topotests/ripng_topo1/r2/ripng_status.ref, tests/topotests/ripng_topo1/r2/ripngd.conf, tests/topotests/ripng_topo1/r3/ripng_status.ref, tests/topotests/ripng_topo1/r3/ripngd.conf
Modify the timers uses to send updates/hello's every
1 seconds instead of 5.  Allowing this test to converge
faster under heavy system load.
=> tests: Allow ripng_topo1 to converge a bit faster

tools/frr-reload.py
frr-reload triggers restart of service in case
it fails to parse new config file and conjunction with
running config contains 'router bgp' (default bgp instnace).
When frr-reload fails to parse new config file, it fails
to build newconfig context (empty object).
Instead of bailing out it compares against the running config
context. If the running config contains default bgp instance
it thinks new config is removing default bgp instance so it
triggers frr restart.
Fix is to to bail out reload script when it fails to parse
config file.
Testing Done:
```
router bgp 102 vrf RED
bgp router-id 2.2.2.2
neighbor underlay peer-group
neighbor underlay remote-as <---- Partial config
```
**Before fix:**
```
2021-12-02 02:43:16,987 ERROR: vtysh failed to process new
configuration: vtysh (mark file) …
```
=> tools: exit when reload fails to parse config file

bfdd/bfd.c
When the detection time expires, we put the session down and restart the
timer. As the comment in the code says, it's needed to zero the remote
discriminator after the second expiration.
But the RFC clearly says that this must be done on the first expiration:
```
bfd.RemoteDiscr
The remote discriminator for this BFD session.  This is the
discriminator chosen by the remote system, and is totally opaque
to the local system.  This MUST be initialized to zero.  If a
period of a Detection Time passes without the receipt of a valid,
authenticated BFD packet from the remote system, this variable
MUST be set to zero.
```
And we actually already do it in `ptm_bfd_sess_dn`, so there's no need
to reset the timer and wait for it twice.
=> bfdd: remove unnecessary receive timer restart

zebra/zebra_vty.c
Add optional NHG ID output to `show ip route` dumps. We have
this in json output already as nexthopGroupID but nice
to have the option in a normal dump as well. Not including in main
output for now to avoid breaking screen scrapers.
```
alfred# show ip route vrf all nexthop-group                                                                                                                                                                                                   
Codes: K - kernel route, C - connected, S - static, R - RIP,                                                                                                                                                                                  
O - OSPF, I - IS-IS, B - BGP, E - …
```
=> zebra: add optional NHG ID output to `show ip ro`

doc/developer/frr-release-procedure.rst, tools/release_notes.py
This utility script helps in generating formatted and consistent
change log including:
1- group logs per daemon
2- standarize daemon names (lowercase, end with d)
3- capitalize all log lines
4- no merge commits
caveat: comments are assumed to be in the form. However all commit message are required to be in that format to begin with to be merged.
daemon-name : message
Sample Output:
```
sharpd
Follow the practice on cli design for json output
Install route supports nexthop-seg6 (step3)
Install_routes_helper support zapi_route flags (step1)
snapcraft
Add missing dependency
Add pathd to frr snap daemons
Change base to ubuntu 18.04 and libyang 2.0.7
staticd
Convert typedef to enum
Fix distance processing
Fix late initialization of blackhole type
Output config using nb callbacks instead of …
```
=> tools: add a script to generate a draft release changelog

lib/srv6.c, lib/srv6.h, zebra/zebra_srv6_vty.c
Add the json output to `show-srv6-locator-detail` command.
At almost cases, these fields may be filled by zero but its not bad for future extensibility.
here's a sample output that's generated from `vtysh -c 'sh segment-routing srv6 locator loc1 detail json' | jq` in srv6_locator topotest.
```json
{
"name": "loc1",
"prefix": "2001:db8:1:1::/64",
"blockBitsLength": 40,
"nodeBitsLength": 24,
"functionBitsLength": 0,
"argumentBitsLength": 0,
"algoNum": 0,
"statusUp": true,
"chunks": [
{
"prefix": "2001:db8:1:1::/64",
"blockBitsLength": 0,
"nodeBitsLength": 0,
"functionBitsLength": 0,
"argumentBitsLength": 0,
"keep": 0,
"proto": "system",
"instance": 0,
"sessionId": 0
}
]
}
```
Signed-off-by: Drumato <drumato43@gmail.com>
=> zebra: Add support for json output in srv6 locator detail command

lib/plist.c
BGP ORF Prefix list incorrectly rejected list with a GE or LE to match the actual
prefix.
A prefix list like 
```
ip prefix-list test-orf seq 20 deny 10.0.0.0/8 ge 8 le 24
```
was incorrectly rejected (`/8 ge 8` and `/24 le 24` should be allowed)
=> bgpd: fix BGP ORF Prefix-length matching

pimd/pim_cmd.c, pimd/pim_iface.c, pimd/pim_igmp.c, pimd/pim_igmp.h, pimd/pim_igmp_mtrace.c, pimd/pim_igmp_mtrace.h, pimd/pim_igmpv2.c, pimd/pim_igmpv2.h, pimd/pim_igmpv3.c, pimd/pim_igmpv3.h, pimd/pim_mroute.c, pimd/pim_nb_config.c, pimd/pim_zebra.c, pimd/pim_zebra.h
Modifying the name of structures igmp_source and igmp_group to gm_source and gm_group respectively, which are to be used by both IPv4 and IPv6(for both MLD and IGMP).
Issues:  #10023
Co-authored-by: Mobashshera Rasool <mrasool@vmware.com>
Co-authored-by: Sarita Patra <saritap@vmware.com>
=> pimd: Modifying name of structures to accommodate IPv6 changes.

pimd/pim_cmd.c, pimd/pim_iface.c, pimd/pim_igmp.h, pimd/pim_vty.c
pimd: Modifying struct igmp_join to struct gm_join to accomodate IPv6 changes
Fix:
Modifying name of struct igmp_join to struct gm_join, which is to be used
by both IPv4 and IPv6(for both MLD and IGMP).
Here gm denotes group membership.
Issue:  # #10023 
Co-authored-by: Abhishek N R abnr@vmware.com
Co-authored-by: Sarita Patra saritap@vmware.com
=> pimd: Modifying struct igmp_join to struct gm_join to accomodate IPv6

configure.ac, vtysh/vtysh.c
Drop `--enable-pcep` option and `HAVE_PATHD_PCEP` which does nothing since https://github.com/FRRouting/frr/commit/749714731ee9a59ae39be77e7db3915ce3ad0bd8
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: drop --enable-pcep option and HAVE_PATHD_PCEP 

isisd/isis_adjacency.c
Pointers to the adjacency must be cleared only when the adjacency is
deleted. Otherwise, when the ISIS router is deleted later, the adjacency
is not deleted and a crash happens because of UAF.
Fixes #10209.
=> isisd: fix use after free

pathd/path_ted.c
Signed-off-by: Yamato Sugawara <yamato.sugawara@linecorp.com>
I just fixed one line in pathd/path_ted.c line 450.
=> pathd: fix typo in pathd/path_ted.c

configure.ac
`enable_bmp` doesn't exist, use `enable_bgp_bmp`
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix enable_bmp typo

zebra/zebra_vxlan.c
=> zebra: correct one spell error

bgpd/bgp_fsm.c, bgpd/bgpd.c
Handles that inside the macro.
=> bgpd: No need to test if a thread is running for BGP_TIMER_OFF

ospfd/ospf_abr.c, ospfd/ospf_gr_helper.c, ospfd/ospf_lsa.c, ospfd/ospf_lsa.h, ospfd/ospf_vty.c, tests/topotests/ospf_gr_helper/test_ospf_gr_helper.py, tests/topotests/ospf_gr_topo1/test_ospf_gr_topo1.py
This commit fixes a rather obscure bug that was causing the GR
topotest to fail on a frequent basis.
RFC 3623 specifies that a router acting as a helper to a restarting
neighbor should monitor topology changes and abort the GR procedures
when one is detected, falling back to normal OSPF operation.
ospfd uses the `ospf_lsa_different()` function to detect when the
content of an LSA has changed, which is considered as a topology
change. The problem is that `ospf_lsa_different()` can return true
even when the two LSAs passed as parameters are identical, provided
one LSA has the `OSPF_LSA_RECEIVED` flag set and the other not.
In the context of the ospf_gr_topo1 test, router rt6 performs
a graceful restart and a few seconds later acts as a helper for
router rt7. When it's acting as a helper for …
=> ospfd: fix incorrect detection of topology changes in helper mode

.clang-format
Break after binary operators, rather than before. the current setting seems to trip a lot of us up, so ... let's talk about changing the setting?
=> tools: clang-format break after operators

zebra/rib.h, zebra/zebra_dplane.c, zebra/zebra_rib.c, zebra/zebra_vty.c
In some cases, zebra may install a nexthop-group id that is
different from the id of the nhe struct attached to a
route-entry. This happens for a singleton recursive nexthop,
for example, where the resolving nexthop's id is installed.
The installed value is the most useful value - that corresponds
to information in the kernel on linux/netlink platforms that
support nhgs. Add the installed value to the show route cli
output if it differs, and include both values in the json form.
=> zebra: add installed nexthop-group id value

lib/libfrr.c, lib/libfrr.h, lib/vrf.c
just some small bits for libfrr's "general daemon running" facilities:
- don't free a NULL vrf if we're shutting down before we've completed startup
- make command line bits more fine-grained, particularly to allow future daemons without split-config support (i.e. integrated config only)
=> lib: fix NULL VRF free, shuffle cmdline options

zebra/zebra_evpn_mac.c, zebra/zebra_evpn_neigh.c
zebra: cleanup checking zebra_evpn_mac_add function's return value 
This function is sure to return correct value by "assert", so the
checking its return value should be removed.
=> zebra: cleanup checking zebra_evpn_mac_add function's return value

ospf6d/ospf6_abr.c
ospf6d: clean coverity warning of possible null pointer
Add assert to protect it.
=> ospf6d: clean coverity warning of possible null pointer

tests/topotests/bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py
There still existed chances that best path consideration
has not taken place for both bgp_l3vpn_to_bgp_vrf and
bgp_instance_del_test ( since they both used the same
check_routes.py scripting ).  Add some more checks
to ensure that we have all the data.  Prior to this
change I could see one of these two tests failing
every 2-3 runs on my test system.  I am not seeing
this anymore after ~5 complete test runs.
=> tests: Further fix bgp_l3vpn_to_bgp_vrf

zebra/zebra_ptm.c
bfdd: correct one spelling error of comment
=> bfdd: correct one spelling error of comment

lib/elf_py.c
> ... need to ignore TLS sections, their address is effectively
> meaningless but can overlap other sections we actually need to access.
> 
> Signed-off-by: David Lamparter <equinox@opensourcerouting.org>
> (cherry picked from commit 3942ee1f7bc754dd0dd9ae79f89d0f2635be334f)
This might hopefully fix #10267 
(This is not a mergify backport since this commit came in a PR with a bunch of other commits, cf. #10025 )
=> [8.1] backport lib: fix elf_py TLS section handling

bgpd/bgp_fsm.c, bgpd/bgp_open.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_llgr/r0/bgpd.conf, tests/topotests/bgp_llgr/r0/zebra.conf, tests/topotests/bgp_llgr/r1/bgpd.conf, tests/topotests/bgp_llgr/r1/zebra.conf, tests/topotests/bgp_llgr/r2/bgpd.conf, tests/topotests/bgp_llgr/r2/zebra.conf, tests/topotests/bgp_llgr/r3/bgpd.conf, tests/topotests/bgp_llgr/r3/zebra.conf, tests/topotests/bgp_llgr/test_bgp_llgr.py
Tested between GoBGP and FRR (this commit).
```
┌───────────┐             ┌────────────┐
│           │             │            │
│ GoBGPD    │             │ FRRouting  │
│ (restart) │             │            │
│           │             │            │
└──────┬────┘             └───────┬────┘
│                          │
│                          │
│                          │
│     ┌───────────┐        │
│     │           │        │
│     │           │        │
└─────┤ FRRouting ├────────┘
│ (helper)  │
│           │
└───────────┘
// GoBGPD
% cat /etc/gobgp/config.toml
[global.config]
as = 65002
router-id = "2.2.2.2"
port = 179
[[neighbors]]
[neighbors.config]
peer-as = 65001
neighbor-address = "2a02:abc::123"
[neighbors.graceful-restart.config]
enabled = true
restart-time = 3 …
```
=> bgpd: Implement LLGR helper mode

tests/topotests/nhrp_topo/test_nhrp_topo.py
It fails on 4.19 (Debian 10 CI), so let's go minimum 5.0 for the time being. (It probably needs even newer but I have no idea what exactly.)
=> topotests: require Linux 5.0 for NHRP

doc/developer/topotests.rst
The developer docs weren't clear about some pre-reqs, making a couple of things sound optional that ... aren't.
=> docs: clarify topotest requirements

bgpd/bgp_vty.c, doc/user/bgp.rst, tests/topotests/bgp_llgr/r0/bgpd.conf, tests/topotests/bgp_llgr/r1/bgpd.conf
Using with LLGR, this should be allowed setting GR restart-time timer to 0,
to immediately start LLGR timers.
=> bgpd: Graceful Restart restart-time can be 0

bgpd/bgp_route.c, doc/user/bgp.rst, doc/user/overview.rst
rfc7196 recommends:
In addition, BGP implementations have an internal constant, which we
will call the 'maximum penalty', and the current computed penalty may
not exceed it.
Router Maximum Penalty:  The internal constant for the maximum
penalty value MUST be raised to at least 50,000.
=> bgpd: Increase maximum supress threshold for dampening to 50,000

bgpd/bgp_debug.c, doc/user/snmptrap.rst, tests/topotests/bgp_features/test_bgp_features.py
The following subcodes are defined for the Cease NOTIFICATION
message:
Subcode     Symbolic Name
1        Maximum Number of Prefixes Reached
2        Administrative Shutdown
3        Peer De-configured
4        Administrative Reset
5        Connection Rejected
6        Other Configuration Change
7        Connection Collision Resolution
8        Out of Resources
=> bgpd: Adjust symbolic names for cease notifications according to rfc4486

tools/generate_support_bundle.py
subprocess.check_call needs to be called with shell=True, else it will
interpret the string as a single path to execute instead of a command
with arguments:
Fixes the following error:
```
$ /usr/lib/frr/generate_support_bundle.py
Making backup of /var/log/frr/bgp_support_bundle.log
Traceback (most recent call last):
File "/usr/lib/frr/generate_support_bundle.py", line 89, in <module>
main()
File "/usr/lib/frr/generate_support_bundle.py", line 80, in main
stdout=open_with_backup(ofn),
File "/usr/lib/frr/generate_support_bundle.py", line 32, in open_with_backup
subprocess.check_call("mv {0} {0}.prev".format(path))
File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
retcode = call(*popenargs, **kwargs)
File "/usr/lib/python3.8/subprocess.py", line 340, in call
with …
```
=> tools: fix backing up previous logs in generate_support_bundle.py

docker/alpine/build.sh, docker/alpine/docker-start
Add ability to set your own env for the version of the docker
container alpine image. This is useful for applications like GNS3
who pin a specific version to look for when they boot up. When you build
locally to test your code you can just set the version to 0 so you don't
have to update configs/scripts looking for a specific image version.
Also fix a shebang in docker start for alpine.
=> docker: update alpine build enable set own version

tests/topotests/lib/pim.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py, tests/topotests/multicast_pim_sm_topo2/test_multicast_pim_sm_topo2.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pim_static_rp.py
Under heavy system load, a hello may not be sent ( or it
may be dropped! ).  Give the timeout to be *larger* than
the hello interval so that we don't happen to have any
issues where we are not waiting long enough too.
This hopefully fixes multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py
The test is turning on / off interfaces and not changing the hello interval
which is 30 seconds and only waiting 20 seconds for the tx count to increment.
=> tools: Give longer for interface traffic in pim to work

pimd/pim_rp.c
Just found while code inspection, pim_str.h is included twice.
=> pimd: remove redundant header inclusion

lib/bfd.c
lib: small debug adjustment for bfd
Just use `__func__` to display function name.
=> lib: small debug adjustment for bfd

bgpd/bgp_route.c, tests/topotests/bgp_gr_functionality_topo3/bgp_gr_functionality_topo3.json, tests/topotests/bgp_gr_functionality_topo3/bgp_gr_functionality_topo3.py, tests/topotests/lib/bgp.py
Description:
Change is intended for fixing the issue related to
clearing of stale leaked routes:
- Whenever BGP goes down, 
after bringing down tcp connection and renegotiating capabilities,
once we reestablish connection,
we are not handling clear of VRF leaked route in the bgp_clear_stale_route.
- While bgp is clearing stale routes,
we need to handle withdraw of routes for VRF route-leaking.
Co-authored-by: Kantesh Mundaragi <kmundaragi@vmware.com>
=> bgpd: VRF-Lite fix to clear stale leaked routes

tools/frr-reload.py
Calling get_contexts() can't display as expected, it wrongly displays:
<__main__.Context object at 0x7fdee1d5ad50>
So make it display correct data by add __str__ in Context class.
=> tools: fix wrong get_contexts() of Config class.

ospf6d/ospf6_asbr.c, ospfd/ospf_vty.c
ospfd,ospf6d: fix wrong comparison of routemap name
Comparison of the two pointer is wrong, they have no relevance.
Additionly correct some comment words.
=> ospfd,ospf6d: fix wrong comparison of routemap name

pimd/pim_assert.c, pimd/pim_assert.h, pimd/pim_iface.h, pimd/pim_ifchannel.h, pimd/pim_igmp.h, pimd/pim_jp_agg.h, pimd/pim_macro.c, pimd/pim_macro.h, pimd/pim_neighbor.h, pimd/pim_pim.c, pimd/pim_rpf.h, pimd/pim_str.h, pimd/pim_upstream.h
PIM_ADDR will be controlled at compile time for IPv4 and IPv6.
in_addr and in6_addr will be compiled for the respective daemons.
Added few macros to access some common addresses.
Please refer https://github.com/FRRouting/frr/pull/10194 for the pimv6
compilation stuff.
pim_str.h will be included only for pimv4 compilation.
Issue: #10023 
Co-authored-by: Sarita Patra <saritap@vmware.com>
=> pimd: Data structure changes to accommodate address family for IPv4 and IPv6

bgpd/bgp_attr.c
If soft-reconfiguration is enabled, bgp_adj_in_set will be called from bgp_update and bgp_adj_in_set will call bgp_attr_intern to intern attr pointer. If given attr isn't found in attrhash, hash_get will call bgp_attr_hash_alloc to allocate new attr structure. In bgp_attr_hash_alloc, NULL will be assigned to srv6_vpn field and srv6_l3vpn field in origin attr pointer. attr->srv6_vpn and attr->srv6_l3vpn are interned in bgp_attr_intern, so NULL assignment isn't needed.
And, these fields are used later in bgp_update to set SRv6 information to bgp_path_info. If bgp_attr_hash_alloc assigns NULL to these fields, SRv6 information will be lost and incorrect routes are inserted into the data plane.
bgpd
**Before applying this PR**
Before applying this PR, we can check incorrect output for …
=> SRv6 routes aren't inserted into data plane correctly with soft-reconfiguration

lib/bfd.c, lib/bfd.h
lib: rename one bfd parameter name to reflect real meaning
As to "struct bfd_session_arg", just rename parameter "ttl" to "hops", in order
to  reflect real meaning.
=> lib: rename one bfd parameter name to reflect real meaning

ospf6d/ospf6_interface.c
ospfv3 is showing enabled on loopback interface although
it is not configured in "show ipv6 ospf6 interface json"
Fix: Make the json output similar to the CLI output.
Fixes: #9286
=> ospfv3 is showing enabled on loopback interface although it is not

ospf6d/ospf6_area.c, ospf6d/ospf6_asbr.c, ospf6d/ospf6_interface.c, ospf6d/ospf6_neighbor.c, ospf6d/ospf6_top.c, ospf6d/ospf6d.c, ospf6d/ospf6d.h
ospf ipv4 will give error information, but ospf ipv6 doesn't.
```
% OSPF instance not found
#show ipv6 ospf6  vrf non-exist-vrf route
#
```
Just like ospf ipv4, i have checked all files on ospf6d directory.
So this PR make ospf ipv6 also give error information in the case of non-exist vrfs.
=> ospf6d: add prompt for commands with non-exist vrf

ospf6d/ospf6_abr.c, ospf6d/ospf6_asbr.c, ospf6d/ospf6_nssa.c
Some cleaning mostly in the NSSA part. See individual commits
* 2f2bf3a23 - ospf6d: fix typos
* 034156428 - ospf6d: use \__func__
* 8eaf7c4ec - ospf6d: remove duplicated code
* 0c7006848 - ospf6d: remove double htons
* b80cebb3b - ospf6d: remove duplicated log
=> ospf6d: some cleaning

bgpd/bgp_route.c
The bgp_notify_conditional_adv_scanner function was/is looping
over all peers.  And only matching on the passed in peer,
based upon the subgroup.  As such we do not need to loop
over everything and just cut-to-the chase and just modify
the peer structure.
=> bgpd: Remove unneeded loop over all peers

doc/developer/logging.rst, lib/prefix.c, lib/prefix.h, pimd/.gitignore, pimd/pim6_main.c, pimd/pim_addr.c, pimd/pim_addr.h, pimd/pim_join.c, pimd/pim_mlag.c, pimd/pim_oil.c, pimd/pim_register.c, pimd/pim_str.h, pimd/pimd.c, pimd/pimd.h, pimd/subdir.am, tests/lib/test_printfrr.c
Start some mergeable progress towards `pim6d`
This replaces PR #10194 (unlike that PR, this one is not WIP, compiles, produces sensible output and can actually be merged)
This also partially replaces PRs #10278 / #10192 which I had previously commented/NAKd; at this point it seems a better allocation of my time to just do it rather than try to steer with reviews.
=> pim6d: add skeleton & address structures

bgpd/bgp_route.c
Issue
---
There is a race when an `aggregate-address` with `suppress-map` configured is removed right after a `route-map` removal: the suppressed route never comes back again. This happens because the route-map update timer is scheduled for after the actual aggregation removal.
When the CLI calls the aggregate route removal function the suppressed route will never meet the condition to remove the suppression:
```
void bgp_aggregate_delete(struct bgp *bgp, const struct prefix *p, afi_t afi,
safi_t safi, struct bgp_aggregate *aggregate)
{
//...
if (aggregate->suppress_map_name
&& AGGREGATE_MED_VALID(aggregate)
&& aggr_suppress_map_test(bgp, aggregate, pi)) {
if (aggr_unsuppress_path(aggregate, pi))
match++;
}
//...
}
```
Because the route-map configuration is no longer there.
My proposed …
=> bgpd: fix aggregate route unsuppression bug

pimd/pim_igmpv2.c
Some of the older Cisco device is having IGMPv2 messages longer than 8 octets.
FRR drops these messages and hence forwarding gets impacted.
Also IGMP ANVL conformance test case 5.6 verifies this case.
Fixing the code as per RFC 2236 section 2.5:
Note that IGMP messages may be longer than 8 octets, especially
future backwards-compatible versions of IGMP.  As long as the Type is
one that is recognized, an IGMPv2 implementation MUST ignore anything
past the first 8 octets while processing the packet.  However, the
IGMP checksum is always computed over the whole IP payload, not just
over the first 8 octets.
Fixes: #10331
=> pimd: IGMP messages may be longer than 8 octets

ospf6d/ospf6_asbr.c
When running the `topotest ospf6_topo2`, we see the ABR r2 sending type 5 LSA into
the stub area `0.0.0.1` which are not acknowledged and the ABR keeps trying forever
```
2022/01/07 15:51:57.953 LSUpdate to neighbor 10.254.254.1%r2-eth0
2022/01/07 15:51:57.953 LSUpdate send on r2-eth0
2022/01/07 15:51:57.953     src: fe80::5808:2aff:fe79:bb63
2022/01/07 15:51:57.953     dst: fe80::785f:7aff:feee:82d6
2022/01/07 15:51:57.953     OSPFv3 Type:4 Len:156 Router-ID:10.254.254.2
2022/01/07 15:51:57.953     Area-ID:0.0.0.1 Cksum:0 Instance-ID:0
2022/01/07 15:51:57.953     Number of LSA: 4
2022/01/07 15:51:57.953     [AS-External Id:0.0.0.1 Adv:10.254.254.2]
2022/01/07 15:51:57.953     Age:  198 SeqNum: 0x80000001 Cksum: 3959 Len: 28
2022/01/07 15:51:57.953     [AS-External Id:0.0.0.2 …
```
=> ospf6d: do not send Type-5 into stub area

pimd/pim_cmd.c, pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_igmp.c, pimd/pim_igmpv3.c, pimd/pim_mroute.c, pimd/pim_nb_config.c, pimd/pim_vty.c, pimd/pim_zebra.c
Modifying the members of pim_interface which are to be used
for both IPv4 and IPv6 to common names(for both MLD and IGMP).
Issues: #10023
Co-authored-by: Mobashshera Rasool <mrasool@vmware.com>
Co-authored-by: Sarita Patra <saritap@vmware.com>
=> pimd: rename IGMP members in pim_interface for MLD use

python/clidef.py
Track what conditionals apply when a DEFPY is encountered, and stack them around the autogenerated clippy wrapper.  Otherwise conditional DEFPYs result in undefined function warnings.
=> python: pass conditionals through clippy for DEFPY

bgpd/bgp_table.c, doc/developer/logging.rst, lib/monotime.h, lib/nexthop.c, lib/prefix.c, lib/printf/glue.c, lib/printfrr.h, lib/sockunion.c, lib/srcdest_table.c, lib/strformat.c, lib/thread.c, lib/thread.h, pimd/pim_addr.c, tests/lib/test_printfrr.c, tools/checkpatch.pl
Adds:
- `s` option on `%pI4s`/`%pI6s`/`%pIAs` to print `*` for multicast addrs
- `%pTS` / `%pTV` / `%pTT` for time formatting
- `%pTH` for showing `struct thread *` data
Also fixes some build/meta bits.
=> lib: printfrr shenanigans

doc/user/bgp.rst
Instead of referring to the draft of  IP Prefix Advertisement in
Ethernet VPN let's point to the recently published RFC9136.
Signed-off-by: Marlin Cremers <marlin@cbws.nl>
=> docs(bgp): refer to rfc9136 instead of draft

zebra/rib.h, zebra/zebra_rib.c
Topology:
IXIA-----(ens192)FRR(ens224)------iXIA
Configuration:
1. Create 8 sub-interfaces on ens192 under Default VRF and configure 8
EBGP session between FRR and IXIA.
2. Create 1000 sub-interfaces on ens224 under Default VRF and configure
1000 EBGP session between FRR and IXIA.
3. 2M prefixes distributed from Left side Ixia each with 8 ECMP path.
4. So in total, there are 2M prefixes * 8 ECMP = 16M prefixes entries
in RIB and FIB.
Issue:
Shut ens192 and ens224, this is taking 1hr 15 mins to clean up the routes.
Root Cause:
In the case of route deletion, if the particular route node is having
nht count = 0, we are going to the parent and doing nht evaluation,
which is not needed.
Fix:
If the deleted the route node is having nht count > 0, then do a nht
evaluation on the parent node. …
=> zebra: Fix for route node having no tracking NHT

pimd/pim_cmd.c, pimd/pim_msdp.h, pimd/pim_nb_config.c, pimd/subdir.am
There is no MSDP for IPv6, so drop this code out of pim6d.
=> pim6d: drop off MSDP code

ospfd/ospf_neighbor.c
The capability opaque command can trigger asserts through a rather
round-about mechanism. The command eventually calls
ospf_renegotiate_optional_capabilities, which will call
ospf_flush_self_originated_lsas_now, which has the side effect of
marking the OSPF instance as shutting down. This was causing the
flooding logic to call ospf_write immediately insted of waiting for the
select IO loop every time it was sending a maxage LSA.  This could cause
the list of OSPF interfaces needing to send packets to be drained while
there was a call to ospf_write pending from the IO loop. When the
pending call ran, it would see the empty list of interfaces and assert.
Signed-off-by: Yuan Yuan <yyuanam@amazon.com>
=> ospfd: Fix assert related to capability opaque

bgpd/bgp_route.c
'show bgp ... neighbor [routes|received-routes]' both incorrectly
used a json key of 'advertisedRoutes'.
This corrects the key to be 'receivedRoutes' for commands where
the displayed routes were received, not advertised.
before:
unet> r3 show ip bgp neigh 10.2.30.2 received-routes json | include Routes
"advertisedRoutes":{
after:
ub18# show ip bgp neighbors enp1s0 received-routes json | include Routes
"receivedRoutes":{
ub18# show ip bgp neighbors enp1s0 advertised-routes json | include Routes
"advertisedRoutes":{
=> bgpd: fix advertisedRoutes json key

doc/user/ospfd.rst
doc: adjust small words for ospfd
- using `seconds` in article
- add `no form` for one sentence
=> doc: adjust small words for ospfd

vtysh/vtysh.c
Currently `segment_routing_cmd` is not installed but defined when FRR configured with `--disable-pathd`.
but `SEGMENT_ROUTING_NODE` is used Zebra SRv6 Manager too.
so this patch enables `SEGMENT_ROUTING_NODE` when FRR configured with `--disable-pathd`.
In Cisco's CLI, `SRV6_NODE` is directly installed on `CONFIG_NODE` .  
I'll contribute to make SRv6 Manager to follow Cisco's CLI as another PR after this PR will be merged.
reference: <https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-3/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-73x/m-configure-srv6-usid.html?referring_site=RE&pos=1&page=https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r6-6/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-66x/b-segment-routing-c …
=> enable to transition to `SEGMENT_ROUTING_NODE` when pathd is disabled

pimd/pim_cmd.c, pimd/pim_nb.c, pimd/pim_nb.h, pimd/pim_nb_config.c, yang/frr-pim.yang
frr-pim.yang, created a list of address family under pim
container. For PIMV4 the key is IPV4, where as for PIMV6
the key is IPV6. This is done for PIMV6 development.
This commit will have all the northbound changes to support
IPV4 address family.
Reviewed-by: Mobashshera Rasool mrasool@vmware.com
=> Keeping PIM  under address-family to accomodate IPv6 in future

pimd/pim_cmd.c, pimd/pim_main.c, pimd/pim_nb.c, pimd/pim_nb.h, pimd/pim_nb_config.c, pimd/subdir.am, yang/frr-gmp.yang, yang/subdir.am
Renamed frr-igmp.yang to frr-gmp.yang, igmp to gmp container.
to support IGMP and MLD protocol.
frr-gmp.yang, created a list of address family under gmp
container. For PIMV4 the key is IPV4, where as for PIMV6
the key is IPV6. This is done for PIMV6 development.
This commit will have all the northbound changes to support
IPV4 address family.
Reviewed-by: Mobashshera Rasool <mrasool@vmware.com>
=> pimv: Keeping list of address-family under gmp container

lib/yang.c, zebra/kernel_netlink.c
Removes 2-pack of noisy log messages printed at startup: (both are printed multiple times)
```
2022/01/17 09:47:55 ZEBRA: [HG1WF-2N96F] YANG model "ietf-inet-types@*" "*@*"not embedded, trying external file
2022/01/17 09:47:55 ZEBRA: [VMBPM-Q87BB] Setting netlink socket receive buffer size: 212992 -> 8388608
```
Neither of these is something that should trigger user attention.
=> lib, zebra: make startup less noisy

tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py
The test case test_PIM_hello_tx_rx_p1 is failing randomly because
sometimes the hello packet is received and sometimes not received while getting
the stats data.
When the hello packet is received HelloRx gets incremented to 1 and then
shutdown of the interface is executed which resets the stats to 0
and again when "no shutdown" of the interface is done, the stats get incremented to 1.
The test case checks after "no shutdown" of the interface whether the stats is incremented
but in this case although the stats got incremented the before and after value is same.
Hence the test case failed.
Adding correct expectations in the test case.
=> tests: Fix random failure in test_PIM_hello_tx_rx_p1

bfdd/bfd_packet.c
Just correct one small statistics problem of bfd control packets.
Please refer to commit.
=> bfdd: fix the possibly wrong counter of control packets

pimd/pim_bfd.c, pimd/pim_msdp.c, pimd/pim_vty.c
Removing redundant header inclusion of pim_cmd.h
=> pimd: remove redundant header include

lib/elf_py.c
elf_getdata_rawchunk() already endian-converts; doing it again is, uh,
counterproductive.
Fixes: #10051
[this will need to be backported]
=> lib/clippy: don't endian-convert twice

tests/topotests/isis_topo1_vrf/r1/isisd.conf, tests/topotests/isis_topo1_vrf/r2/isisd.conf, tests/topotests/isis_topo1_vrf/r3/isisd.conf, tests/topotests/isis_topo1_vrf/r4/isisd.conf, tests/topotests/isis_topo1_vrf/r5/isisd.conf
Use vrf keyword for interface, and directly configure isis under
that interface.
=> topotests: isis vrf config changed

pimd/pim_cmd.c, pimd/pim_vty.c
Enable debug commands "debug pim packetdump send" and
"debug pim packetdump receive" in config mode.
Display "debug pim nht rp" in show running config.
=> pimd: debug pim fixes

zebra/zapi_msg.c
Opaque data should be freed together with route entry in case of errors.
=> zebra: fix opaque data memleak

ospfd/ospf_vty.c
`ospf->new_table` is NULL if the OSPF instance has no routes.
=> ospfd: fix crash on "ospf send-extra-data zebra"

redhat/frr.logrotate
s/static/staticd
fixes #10418 
=> redhat: logrotate file has typo for staticd

pimd/pim_cmd.c
`XPATH_MAXLEN` denotes the maximum length of an `XPATH`. It does not make
sense to allocate a buffer intended to contain an `XPATH` with a size
larger than the maximum allowable size of an `XPATH`. Consequently this PR
removes buffers that do this. Prints into these buffers are now checked
for overflow.
This is an alternative to #10394.
=> pimd: fix misuse of xpath buf size constants

pimd/pim6_main.c, pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_main.c
The first commit is cosmetic. The actual fix is in the second commit.
=> pimd: fix interface memleak

ospf6d/ospf6_area.c
This PR will include if the area is NSSA in the output of "show ipv6 ospf"
It also fixes the indentation of `SPF last executed...` string
```
r2# show ipv6 ospf
...
Area 0.0.0.0
Number of Area scoped LSAs is 8
Interface attached to this area: r2-eth1
SPF last executed 20.46717s ago
Area 0.0.0.1[Stub]
Number of Area scoped LSAs is 9
Interface attached to this area: r2-eth0
SPF last executed 20.46911s ago
Area 0.0.0.2[NSSA]                          <----- ***
Number of Area scoped LSAs is 14
Interface attached to this area: r2-eth2
SPF last executed 20.46801s ago
```    
=> ospf6d: show if area is NSSA

bgpd/bgp_conditional_adv.c, bgpd/bgp_route.c, bgpd/bgp_updgrp.c, bgpd/bgp_updgrp.h, bgpd/bgp_updgrp_adv.c, bgpd/bgp_updgrp_packet.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/bgp_maximum_prefix_out/test_bgp_maximum_prefix_out.py
Fixes for the BGP maximum prefix out feature.
Allows the limit to be applied immediately without clearing the neighbor.
=> bgpd: fixes maximum prefix out

lib/ipaddr.h, vrrpd/vrrp_northbound.c
Replace custom implementation or call to ipaddr_isset with a call to
ipaddr_is_zero.
ipaddr_isset is not fully correct, because it's fine to have some
non-zero bytes at the end of the struct in case of IPv4 and the function
doesn't allow that.
=> vrrpd: use ipaddr_is_zero when needed

zebra/zebra_vrf.c
When calling route_table_finish actually call it
on what we mean to.  Additionally ensure that
those tables are nulled out.
=> zebra: Actually delete the table we are looking for

ospf6d/ospf6_abr.c
Fixes #9720. When updating an ECMP inter-area route, we compute
a new route and check whether that already exists. If so, we keep the old
route and only update its nexthops. Previously, we merged the new route's
nexthops into the old one's, but this way, it's impossible to remove
nexthops from the old route, resulting in stale nexthops.
This commit fixes this by first removing all nexthops from the old route and
then copying all nexthops from the new route into it. If the new route has
fewer nexthops, the old one will have as well afterwards.
=> ospf6d: Fix ECMP inter-area route nexthop update

bgpd/bgp_aspath.c, bgpd/bgp_route.c, tests/topotests/bgp_remove_private_as/r1/bgpd.conf, tests/topotests/bgp_remove_private_as/r1/zebra.conf, tests/topotests/bgp_remove_private_as/r2/bgpd.conf, tests/topotests/bgp_remove_private_as/r2/zebra.conf, tests/topotests/bgp_remove_private_as/r3/bgpd.conf, tests/topotests/bgp_remove_private_as/r3/zebra.conf, tests/topotests/bgp_remove_private_as/r4/bgpd.conf, tests/topotests/bgp_remove_private_as/r4/zebra.conf, tests/topotests/bgp_remove_private_as/r5/bgpd.conf, tests/topotests/bgp_remove_private_as/r5/zebra.conf, tests/topotests/bgp_remove_private_as/test_bgp_remove_private_as.py
In situations where remove-private-AS is configured for eBGP peers
residing in a private ASN, the peer's ASN was not being retained
in the AS-Path which can allow loops to occur. This was addressed
in a prior commit but it only addressed cases where the "replace-AS"
keyword was configured.
This commit ensures we retain the peer's ASN when using
"remove-private-AS" for eBGP peers in a private ASN regardless of other
keywords.
Setup:
=========
router bgp 4200000002
neighbor enp1s0 interface v6only remote-as external
neighbor enp6s0 interface v6only remote-as external
!
neighbor enp6s0 remove-private-AS
ub18# show ip bgp sum | include 420000
BGP router identifier 100.64.0.111, local AS number 4200000002 vrf-id 0    <<<<< local asn 4200000002 …
=> bgpd: retain peer asn even with remove-private-AS

zebra/zapi_msg.c
EVPN route add should be queued to preserve the config order.
In particular, against deletion in rib_delete().
=> zebra: Fix EVPN route nexthop config order

ospf6d/ospf6_zebra.c
$ for x in $(seq 1 10000); do vtysh -c 'show ipv6 ospf6 zebra json' >/dev/null; done
Before:
```
$ vtysh -c 'show memory ospf6d' | grep 'Total heap allocated'
Total heap allocated:  26 MiB
```
After:
```
$ vtysh -c 'show memory ospf6d' | grep 'Total heap allocated'
Total heap allocated:  2256 KiB
```
=> ospf6d: Fix memory leak for `show ipv6 ospf6 zebra json`

ospfd/ospf_dump.c
FRR stores the route_tag in network byte order.  Bug filed indicates
that the `show ip ospf route` command shows the correct value.
Every place route_tag is dumped in ospf_vty.c the ntohl function
is used first.
Fixes: #10450
=> ospfd: Convert output to host order from network order for route_tag

zebra/rib.h, zebra/zapi_msg.c, zebra/zapi_msg.h, zebra/zebra_rib.c, zebra/zebra_vty.c
The name 'opaque' is a little general - call the route_entry struct 're_opaque' to make it more specific.
=> zebra: name the route_entry opaque struct more specifically

bgpd/bgp_route.c
=> bgpd: Reuse bgp_path_info_extra_get() for allocating new bgp path info

ospfd/ospf_vty.c
This is PR #10435 applied to OSPFv2. If r1 has a route received from a neighbor with the default administrative distance configured
```   
r1# sh ip route
T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
f - OpenFabric,
O>* 1.1.1.1/32 [110/20] via 10.0.12.2, r1-r2-eth0, weight 1, 00:00:41
```    
If we change the administrative distance
```    
r1(config)# router ospf
r1(config-router)# distance 50
```    
This is not applied as there are no changes in the routing table
```    
r1# sh ip route
O - OSPF, I - …
```
=> ospfd: fix distance not applied

ospf6d/ospf6_top.c, ospf6d/ospf6_top.h
if `r1` has a route received from a neighbor and the same route configured as static, 
the administrative distance will determine  which route to use
```
r1(config)# ipv6 route 1:1::1/128 Null0 70
r1# sh ipv6 route
Codes: K - kernel route, C - connected, S - static, R - RIPng,
O - OSPFv3, I - IS-IS, B - BGP, N - NHRP, T - Table,
v - VNC, V - VNC-Direct, A - Babel, F - PBR,
f - OpenFabric,
S>* 1:1::1/128 [70/0] unreachable (blackhole), weight 1, 00:00:12
O   1:1::1/128 [110/20] via fe80::1833:c9ff:fe7b:3e43, r1-r2-eth0, weight 1, 00:00:49
```    
The static route is selected. If we now change the administrative distance in ospf6, the OSPF route should be selected
```    
r1(config)# …
```
=> ospf6d: fix distance not applied

bgpd/bgp_rpki.c
Before this patch, if the first server crashed or was terminated, RPKI
connection keeps _active_ forever.
With this patch, if we catch connection problem (FATAL), we reset RPKI, to
switch to another available RTR-Server by using configured preference.
=> bgpd: Handle TCP connection errors with connection callbacks for RPKI

ospf6d/ospf6_asbr.c, ospf6d/ospf6_asbr.h, ospf6d/ospf6_top.c, ospf6d/ospf6_top.h, ospfd/ospf_asbr.c, ospfd/ospf_asbr.h, ospfd/ospf_vty.c, ospfd/ospfd.h
Four commits:
- ospfd: fix missing "aggregation timer" in running configuration
- ospfd:  small fixes on ospfd running configuration.
- ospf6d: adjust type of "aggr_delay_interval"
- ospfd: adjust type of "aggr_delay_interval"
=> ospfd: fix missing "aggregation timer" in running configuration

ospfd/ospf_vty.c
Signed-off-by: anlan_cs <vic.lan@pica8.com>
=> [8.2] ospfd: fix missing "aggregation timer" in running configuration

zebra/rib.h, zebra/zebra_rib.c, zebra/zebra_vrf.c
Current code treats all metaqueues as lists of route_node structures.
However, some queues contain other structures that need to be cleaned up
differently. Casting the elements of those queues to struct route_node
and dereferencing them leads to a crash. The crash may be seen when
executing bgp_multi_vrf_topo2.
Fix the code by using the proper list element types.
I'm not 100% sure about the cleanup process, I just do the same thing as `nhg_meta_queue_free`.
Someone with good knowledge of NHG stuff should probably take a deep look into the code.
=> zebra: fix cleanup of meta queues on vrf disable

bgpd/bgp_attr.c, bgpd/bgp_attr_evpn.c, bgpd/bgp_attr_evpn.h, bgpd/bgp_evpn.c
Description:
Replacing memcmp at certain places,
to avoid the coverity issues caused by it.
Co-authored-by: Kantesh Mundargi <kmundaragi@vmware.com>
=> [8.2] bgpd: Fixing memcmp to avoid coverity issue

bgpd/bgp_community_alias.c
buffers are null terminated
fixes #10484 
=> bgpd: strncmp -> strcmp in community hash foo

.clang-format
Port clang-format tweak to 8.1 branch: break after binary operators, rather than before.
=> [8.1] tools: tweak clang format to match master

zebra/rib.h, zebra/zebra_rib.c, zebra/zebra_vrf.c
[Mergify hit a conflict, so back-porting the old-fashioned way?]
Current code treats all metaqueues as lists of route_node structures.
However, some queues contain other structures that need to be cleaned up
differently. Casting the elements of those queues to struct route_node
and dereferencing them leads to a crash. The crash may be seen when
executing bgp_multi_vrf_topo2.
Fix the code by using the proper list element types.
(cherry picked from commit 0ef6eacc95c82014c04f13be3b641ff3983040ca)
=> [8.1] zebra: fix cleanup of meta queues on vrf disable

ospfd/ospf_interface.c
Skip marking routes as changed in ospf_if_down if there's now
new_table present, which might be the case when the instance is
being finished
=> ospfd: Core in ospf_if_down during shutdown.

zebra/kernel_netlink.c
The dataplane pthread only processes a limited set of incoming netlink notifications, but it uses the same set of netlink events as the main pthread. Only register for that limited set of events, reducing duplicate incoming netlink messages.
=> zebra: reduce incoming netlink messages for dplane thread

zebra/interface.c, zebra/interface.h, zebra/rtadv.c
RA packets are pretty chatty and when there is a warning from
a missconfiguration on the network, the log file gets filed
up with warnings.  Modify the code in rtadv.c to only spit
out the warning in these cases at most every 6 hours.
=> zebra: Make Router Advertisement warnings show up once every 6 hours

lib/hash.h, zebra/zebra_nhg.c
I'm seeing this crash in various forms:
Program terminated with signal SIGSEGV, Segmentation fault.
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f418efbc7c0 (LWP 3580253))]
(gdb) bt
(gdb) f 4
267				(*func)(hb, arg);
(gdb) p hb
$1 = (struct hash_bucket *) 0x558cdaafb250
(gdb) p *hb
$2 = {len = 0, next = 0x0, key = 0, data = 0x0}
(gdb)
I've also seen a crash where data is 0x03.
My suspicion is that hash_iterate is calling zebra_nhg_sweep_entry which
does delete the particular entry we are looking at as well as possibly other
entries when the ref count for those entries gets set to 0 as well.
Then we have this loop in hash_iterate.c:
for (i = 0; i < hash->size; i++)
for (hb = hash->index[i]; hb; hb = hbnext) {
/* get pointer to next hash …
=> zebra: Fix improper usage of hash_iterate that caused crashes

zebra/kernel_netlink.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h
Currently when we have a route replace operation for v6 routes
with a new nexthop group the order of kernel installation is this:
a) New nexthop group insertion seq  1
b) Route delete operation seq 3
c) Route insertion operation seq 2
Currently the code in nl_batch_read_resp is attempting
to handle this situation by skipping the delete operation.
*BUT* it is enqueuing the context into the zebra dplane
queue before we read the response.  Since we create the ctx
with an implied success, success is being reported to the
upper level dplane and the zebra rib thinks the route has
been properly handled.
This is showing up in the zebra_seg6_route test code because
the test code is installing a seg6 route w/ sharpd and it
is failing to install because the route's nexthop is rejected:
First …
=> zebra: Fix v6 route replace failure turned into success

tools/release_notes.py
I think we don't care about this in release notes.
bgpd,pimd,isisd,nhrpd: Convert to vty_json() (origin/fix/vty_json)
ospf6d: Fix memory leak for `show ipv6 ospf6 zebra json` (origin/fix/zebra_ospf6d_json_leak)
=> tools: Skip decorating commits with references (branch name, remote)

lib/json.h, ospf6d/ospf6_area.c, ospf6d/ospf6_lsdb.c, ospf6d/ospf6_lsdb.h
The changes implement LSA type counters in the LSA database and add functionality to display those statistics in JSON output of `show area` commands.
Isolated feature of closed WIP PR #8547
=> ospf6d: LSA statistics

pbrd/pbr_map.c, pbrd/pbr_nht.c, pbrd/pbr_nht.h, pbrd/pbr_vty.c
When adding a nhg to a route map, make sure to specify the `family`
of the rm by looking at the contents of the nhg. Installation in the
kernel (for DSCP rules in particular) relies on this being specified in
the netlink message.
Signed-off-by: Wesley Coakley <wcoakley@nvidia.com>
=> pbrd: pbr route maps get addr family of nhgs

pimd/pim_bsm.c, pimd/pim_nht.c
I'm now seeing in my log file:
2022/01/28 11:20:05 PIM: [Q0PZ7-QBBN3] attempting to delete nonexistent NHT BSR entry 0.0.0.0
2022/01/28 11:20:05 PIM: [Q0PZ7-QBBN3] attempting to delete nonexistent NHT BSR entry 0.0.0.0
2022/01/28 11:20:06 PIM: [Q0PZ7-QBBN3] attempting to delete nonexistent NHT BSR entry 0.0.0.0
When I run pimd.  Looking at the code there are 3 places where pim_bsm.c removes the
NHT BSR tracking.  In 2 of them the code ensures that the address is already setup
in 1 place it is not.  Fix.
=> pimd: Only remove bsr NHT if we actually have tracked something

doc/user/pim.rst, pimd/pim_cmd.c
`show ip pim assert` shows S,G ifchannel information even when
there is no information available about the assert process.
Fix the code to not dump non-interesting cases.
Fixes: #10462
=> pimd: Modify `show ip pim assert` to only show interesting bits

ospfd/ospf_asbr.c, ospfd/ospf_lsa.c, ospfd/ospf_lsa.h, tests/topotests/ospf_basic_functionality/test_ospf_rte_calc.py
Description:
This LSID alogithm added as per rcf2328 Appendex-E recommendation.
This applies only for AS-external lsas and summary lsas.
As an example of the algorithm, consider its operation when the
following sequence of events occurs in a single router (Router A).
(1) Router A wants to originate an AS-external-LSA for
[10.0.0.0,255.255.255.0]:
(a) A Link State ID of 10.0.0.0 is used.
(2) Router A then wants to originate an AS-external-LSA for
[10.0.0.0,255.255.0.0]:
(a) The LSA for [10.0.0,0,255.255.255.0] is reoriginated using a
new Link State ID of 10.0.0.255.
(b) A Link State ID of 10.0.0.0 is used for
[10.0.0.0,255.255.0.0].
(3) Router A then wants to originate an AS-external-LSA for
[10.0.0.0,255.0.0.0]:
(a) The LSA for [10.0.0.0,255.255.0.0] is reoriginated using a
new Link State …
=> ospfd: Modifying LSID generation algorithm

babeld/message.c
This patch repairs the checking conditions on length in four functions:
babel_packet_examin, parse_hello_subtlv, parse_ihu_subtlv, and parse_update_subtlv
This patch fixes #10502 and fixes #10503
Signed-off-by: qingkaishi <qingkaishi@gmail.com>
=> babeld: fix the checks for truncated packets

tests/topotests/bgp_community_change_update/test_bgp_community_change_update.py, tests/topotests/bgp_l3vpn_to_bgp_direct/customize.py, tests/topotests/bgp_l3vpn_to_bgp_vrf/customize.py, tests/topotests/bgp_multiview_topo1/test_bgp_multiview_topo1.py, tests/topotests/bgp_rfapi_basic_sanity/customize.py, tests/topotests/ldp_oc_acl_topo1/test_ldp_oc_acl_topo1.py, tests/topotests/ldp_oc_topo1/test_ldp_oc_topo1.py, tests/topotests/ldp_topo1/test_ldp_topo1.py, tests/topotests/ospf6_topo1/test_ospf6_topo1.py, tests/topotests/ospf6_topo1_vrf/test_ospf6_topo1_vrf.py
Add `r` prefix to treat backslashes as literals.
=> tests: fix strings with topologies

doc/developer/workflow.rst
=> doc: the dev tag should come after the new version commit step

tools/frrinit.sh.in
After:
```
root@exit1-debian-11:~# grep ripngd= /etc/frr/daemons
ripngd=no
root@exit1-debian-11:~# pgrep -f ripngd -c
0
root@exit1-debian-11:~# sed -i 's/ripngd=no/ripngd=yes/' /etc/frr/daemons
root@exit1-debian-11:~# /usr/lib/frr/frrinit.sh reload
Stopped watchfrr.
Started watchfrr.
root@exit1-debian-11:~# pgrep -f ripngd -c
2
root@exit1-debian-11:~# grep ripngd= /etc/frr/daemons
ripngd=yes
root@exit1-debian-11:~# sed -i 's/ripngd=yes/ripngd=no/' /etc/frr/daemons
root@exit1-debian-11:~# /usr/lib/frr/frrinit.sh reload
Stopped watchfrr.
Started watchfrr.
Stopped ripngd.
root@exit1-debian-11:~# pgrep -f ripngd -c
0
```
Before:
```
root@exit1-debian-11:~# grep ripngd= /etc/frr/daemons
ripngd=no
root@exit1-debian-11:~# pgrep -f ripngd -c
0
root@exit1-debian-11:~# sed -i …
```
=> tools: Stop disabled daemons when doing reload

bgpd/bgp_evpn_mh.c, vrrpd/vrrp.c, zebra/zebra_evpn_neigh.c
Using memcmp is wrong because struct ipaddr may contain unitialized
padding bytes that should not be compared.
=> *: use ipaddr_cmp instead of memcmp

bgpd/bgp_pbr.c
Using memcmp is wrong because struct nexthop may contain unitialized
padding bytes that should not be compared.
=> bgpd: avoid memcmp comparison of struct nexthop

zebra/connected.c, zebra/kernel_socket.c, zebra/redistribute.c, zebra/rib.h, zebra/rt_netlink.c, zebra/zapi_msg.c, zebra/zebra_rib.c
When using wait for install there exists situations where
zebra will issue several route change operations to the kernel
but end up in a state where we shouldn't be at the end
due to extra data being received.  Example:
a) zebra receives from bgp a route change, installs sends the
route to the kernel.
b) zebra receives a route deletion from bgp, removes the
struct route entry and then sends to the kernel a deletion.
c) zebra receives an asynchronous notification that (a) succeeded
but we treat this as a new route.
This is the ships in the night problem.  In this case if we receive
notification from the kernel about a route that we know nothing
about and we are not in startup and we are doing asic offload
then we can ignore this update.
Ticket: #2563300
Signed-off-by: Donald Sharp …
=> zebra: Fix ships in the night issue

configure.ac, doc/user/basic.rst, doc/user/extlog.rst, doc/user/index.rst, doc/user/subdir.am, lib/command.h, lib/libfrr.c, lib/libfrr.h, lib/log_vty.c, lib/subdir.am, lib/systemd.h, lib/zebra.h, lib/zlog_5424.c, lib/zlog_5424.h, lib/zlog_5424_cli.c, tests/.gitignore, tests/lib/fuzz_zlog.c, tests/lib/fuzz_zlog_inputs.py, tests/lib/subdir.am
This adds RFC5424 syslog support.  I'm still pondering some naming choices (particularly `log extended-syslog EXTLOGNAME` & co.) - this code started out only doing RFC5424 but now also does RFC3164 and systemd-journald, so some of the naming has gotten a bit inappropriate.
NB: the first bunch of commits of this branch are separated out in #8457 and just duplicate here.  Only the "TODO" stuff at the end is the actual RFC5424 bits.
Comments very welcome!  Docs match the current code & doc-based comments on user-facing aspects also welcome :wink: (i.e. no need to read the code at this point, reading the docs & commenting off that is perfectly fine!)
=> lib: RFC5424 syslog support

zebra/kernel_netlink.c, zebra/kernel_netlink.h, zebra/rt_netlink.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h, zebra/zebra_ns.h
Fixes a zebra buffer for netlink message reading not being large enough.  See individual commits
=> Zebra buffering

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_route.c, bgpd/bgp_updgrp_adv.c
bgp_attr_undup does the same thing as bgp_attr_flush – frees the
temporary data that might be allocated when applying a route-map. There
is no need to have two separate functions for that.
=> bgpd: remove bgp_attr_undup

bgpd/bgp_attr_evpn.c, bgpd/rfapi/rfapi_vty.c
They were introduced during recent ecommunity rework in b53e67a3.
CID 1511347 and 1511348.
=> bgpd: fix null pointer dereferences

zebra/zebra_dplane.c
Replace a couple of strdup/free with XSTRDUP/XFREE. (Thanks, Quentin, who noticed these!)
=> zebra: use frr mem apis in dplane

zebra/debug_nl.c, zebra/rt_netlink.h
Adds functions to parse + decode netlink rules.
Adds RTM_NEWRULE + RTM_DELRULE to "debug zebra kernel".
Example output:
```
2022/02/08 17:30:40 ZEBRA: [JAS4D-NCWGP] nlmsghdr [len=80 type=(32) NEWRULE flags=(0x0001) {REQUEST} seq=17 pid=3629048426]
2022/02/08 17:30:40 ZEBRA: [X216X-9DETH]   frh [family=2 (AF_INET) dst_len=32 src_len=32 tos=0 table=0 res1=0 res2=0 action=2 (GOTO) flags=0x0]
2022/02/08 17:30:40 ZEBRA: [KFBSR-XYJV1]     rta [len=5 (payload=1) type=(21) PROTO]
2022/02/08 17:30:40 ZEBRA: [Z4E9C-GD9EP]       11
2022/02/08 17:30:40 ZEBRA: [KFBSR-XYJV1]     rta [len=8 (payload=4) type=(6) PRIORITY]
2022/02/08 17:30:40 ZEBRA: [Z4E9C-GD9EP]       304
2022/02/08 17:30:40 ZEBRA: [KFBSR-XYJV1]     rta [len=11 (payload=7) type=(3) …
```
=> zebra: add netlink debugs for ip rules

lib/thread.c, lib/thread.h
Add a counter to the number of times a thread is starved from
a timer event and add the output to `show thread cpu`
=> lib: Save number of times a thread is starved

lib/keychain.c, lib/keychain.h, ospf6d/ospf6_auth_trailer.c, ospf6d/ospf6_auth_trailer.h, ospf6d/ospf6_message.c
Fixed below coverity issues
________________________________________________________________________________________________________
*** CID 1511366:    (TAINTED_SCALAR)
/ospf6d/ospf6_message.c: 2631 in ospf6_make_lsupdate_list()
2625                          + OSPF6_HEADER_SIZE)
2626                         > ospf6_packet_max(on->ospf6_if)) {
2627                             ospf6_fill_header(on->ospf6_if, (*op)->s,
2628                                               length + OSPF6_HEADER_SIZE);
2629                             (*op)->length = length + OSPF6_HEADER_SIZE;
2630                             ospf6_fill_lsupdate_header((*op)->s, *lsa_cnt);
>>>     CID 1511366:    (TAINTED_SCALAR)
>>>     Passing tainted variable "(*op)->length" to a tainted sink.
2631 …
=> ospf6d: fix coverity issues.

bgpd/bgp_route.c, bgpd/bgpd.c, bgpd/bgpd.h
Add a 6 hour warning to the logging system when
bgp policy is not setup properly.  Operators keep asking
about the missing policy( on upgrade typically ).  Let's
try to give them a bit more of a hint when something is
going wrong as that they are clearly missing the other
various places FRR tells them about it.
=> bgp: Add a 6 hour warning to missing policy

bgpd/bgp_mplsvpn.c
Build warning: 'label' may be used uninitialized in this function bgpd/bgp_mplsvpn.c alloc_new_sid
=> bgpd: uninitialized compiler warning

zebra/kernel_netlink.c, zebra/kernel_socket.c, zebra/rt.h, zebra/zebra_router.c
The recently-added hashtable of nlsock objects needs to be thread-safe: it's accessed from the main and dplane pthreads. Add a mutex for it, use wrapper apis when accessing it. Add a per-OS init/terminate api so we can do init that's not per-vrf or per-namespace.
=> zebra: make netlink object hash threadsafe

pimd/pim_cmd.c
A recent merge caused the below error in compilation, fixing it.
pimd/pim_cmd.c: In function ‘interface_ip_igmp_query_generate_magic’:
pimd/pim_cmd.c:8002:24: error: ‘struct pim_interface’ has no member named ‘version’
igmp_version = pim_ifp->version;
^~
Makefile:12435: recipe for target 'pimd/pimd_pimd-pim_cmd.o' failed
make[1]: *** [pimd/pimd_pimd-pim_cmd.o] Error 1
make[1]: Leaving directory '/root/mobash/FRR/frr'
Makefile:5659: recipe for target 'all' failed
make: *** [all] Error 2
Signed-off-by: Mobashshera Rasool <mrasool@gmail.com>
=> pimd: Fix Compilation issue in PIM

doc/user/ospfd.rst
=> doc: mixing `ip ospf` and `network` commands is not supported

zebra/ioctl.c
Trying to call multiple ioctl calls on ifreq will result in
overwriting ifreq with garbage data. On if_get_flags call,
try to keep the flags field safe from another possible ioctl
call before applying the flags field.
Modified code as per Code Review, done by Donald Sharp.
Signed-off-by: Bijan <bijanebrahimi@riseup.net>
=> zebra: Keep the interface flags safe on multiple ioctl calls

tests/topotests/bgp_route_map/test_route_map_topo1.py
noticed that pylint was complaining about some easily
fixable stuff in test_route_map_topo1.py so let's clean
it up some.
=> tests: Cleanup test_route_map_topo1.py from pylint

ripd/ripd.c
When rip is configured to work on secondary addresses
on an interface, rip was not properly sending out
the packets on secondary addresses because the source of the
packet was never properly being setup and rip would
send the packet out multiple times for the primary address
not once for each address on the interface that is setup to work.
tcpdump + rip debugs output with fix:
2022/02/15 19:59:50 RIP: [ZG173-BHW0K] turn on virbr0
2022/02/15 19:59:51 RIP: [PYB7S-80D89] multicast join at virbr0
2022/02/15 19:59:51 RIP: [GZR24-FCQGG] multicast request on virbr0
2022/02/15 19:59:51 RIP: [JTNCV-XD8S1] rip_send_packet 192.168.122.1 > 224.0.0.9 (virbr0)
2022/02/15 19:59:51 RIP: [VEJY5-67P5X] SEND to  224.0.0.9520
2022/02/15 19:59:51 RIP: [JTNCV-XD8S1] rip_send_packet 73.3.3.8 > 224.0.0.9 …
=> ripd: Fix packet send for non primary addresses

staticd/static_main.c, staticd/static_nb_config.c, staticd/static_routes.h, staticd/static_zebra.c
Restrict the number of nexthops for a route to the compiled-in limit. Be careful with the zapi route struct's array of nexthops too.
Fixes #10601
=> staticd: reject route config with too many nexthops

bgpd/bgp_routemap.c, doc/user/routemap.rst, yang/frr-bgp-route-map.yang
Add evpn mh route type-1 (EAD) to match clause
of route-map.
Ticket: issue#10461
Reviewed By:
Testing Done:
With fix:
```
vtep1(config-route-map)# match evpn route-type
1          EAD (Type-1) route
2          MAC-IP (Type-2) route
3          Multicast (Type-3) route
4          Ethernet Segment (Type-4) route
5          Prefix (Type-5) route
ead        EAD (Type-1) route
macip      MAC-IP (Type-2) route
multicast  Multicast (Type-3) route
prefix     Prefix (Type-5) route
vtep1# show running-config bgpd
....
route-map HOST_ALLOW_1 permit 1
match evpn route-type ead
vtep1# show route-map HOST_ALLOW_1
BGP:
route-map: HOST_ALLOW_1 Invoked: 6 Optimization: disabled Processed Change: false
permit, sequence 1 Invoked 6
Match clauses:
ip address prefix-list LOCAL_HOST_VRF1
evpn route-type ead
``` …
=> bgpd: evpn route-map match ead type-1 route-type

pimd/pim_nb_config.c
224.0.0.0/24 cannot be used by igmp since this is reserved
for routing protocols and other low-level topology discovery or
maintenance protocols.
Fixes: #10614
=> pimd: Do not allow 224.0.0.0/24 range in igmp join

doc/user/isisd.rst, isisd/isis_cli.c
=> isisd: Drop deprecated `segment-routing local-block` command

tests/topotests/lib/common_config.py, tests/topotests/zebra_nht_resolution/r1/zebra.conf, tests/topotests/zebra_nht_resolution/test_verify_nh_resolution.py, zebra/zebra_rnh.c
**Description:**
Change is intended for fixing the NHT resolution logic.
While recursively resolving nexthop, keep looking for a valid/useable route in the rib,
by not stopping at the first/most-specific route in the rib.
Consider the following set of events taking place on R1:
```
R1(config)# ip route 2.2.2.0/24 ens192
R1# sharp watch nexthop 2.2.2.32 connected
R1# show ip nht
2.2.2.32(Connected)
resolved via static
is directly connected, ens192
Client list: sharp(fd 33)
```
- 2.2.2.32 NHT is resolved over the above valid static route.
```
R1# sharp install routes 2.2.2.32 nexthop 2.2.2.32 1
R1# 2.2.2.32(Connected)
resolved via static
is directly connected, ens192
Client list: sharp(fd 33)
```
- .32/32 comes which is going to resolve through itself, but since this is an invalid route,
it …
=> zebra: Nexthop tracking, route resolution recursive lookup

ospfd/ospf_lsa.c
Description:
NULL pointer wrongly passed instead of 'ei' pointer to
ospf_external_lsa_originate() API in opaque capability enable/disable
which always make it to fail in origination.
Corrected it by passing actual ei pointer.
Ref corresponding old  PR : https://github.com/FRRouting/frr/pull/8557
=> ospfd: NULL passed instead of ei pointer in external lsa origination

bgpd/bgp_mplsvpn.c, bgpd/bgp_mplsvpn.h, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_zebra.c, bgpd/bgpd.h
Currently, bgpd announces SRv6 L3VPN routes with transposed SID, but some implementations reject those routes. This patch changes to advertising routes with SRv6 Locator instead of transposed SID. This PR changes the following things:
- change alloc_new_sid to save not only transposed SID but also SRv6 Locator (in 1st patch)
- advertise SRv6 L3VPN routes with SRv6 Locator instead of transposed SID (2nd patch)
- change the treatment of SRv6 SID
- before: transpose SID when bgp_sid_info is created and bgp_sid_info doesn't have transposition_len and transposition_offset
- after: bgp_sid_info has transposition_len and transposition_offset and transpose SID only at bgp_announce_zebra
=> bgpd: Change the format of announcement for SRv6 L3VPN

pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim6_main.c, pimd/pim6_stubs.c, pimd/pim_addr.h, pimd/pim_bfd.c, pimd/pim_bsm.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_static.c, pimd/pim_vty.c, pimd/pim_vty.h, pimd/pimd.c, pimd/subdir.am
This PR adds the below top level CLIs for PIMv6.
Adding the below CLIs for PIMv6 Daemon:
[no] ipv6 pim register-suppress-time (1-65535)
[no] ipv6 pim rp keep-alive-timer [(1-65535)]
[no] ipv6 pim keep-alive-timer (1-65535)
[no] ipv6 pim packet (1-255)
[no] ipv6 pim spt-switchover infinity-and-beyond
[no] ipv6 pim spt-switchover infinity-and-beyond prefix-list WORD
[no] ipv6 pim join-prune interval (1-65535)
Note: The first 4 commits are common in #10393
#10365
#10366 
since we are using the same file. This has been done to ease development.
Signed-off-by: Mobashshera Rasool mrasool@vmware.com
=> pim6d:  Adding PIMv6 Config CLIs for top level

lib/checksum.c, lib/checksum.h, tests/lib/subdir.am, tests/lib/test_checksum.c
Feeding a `struct iovec` into the checksum code is useful to calculate a checksum before doing a `sendmsg()` with the same `iovec`. Otherwise we end up having to copy around the entire thing.  This also "assimilates" the IP pseudoheader bits to a degree, since they can just be put in a iovec.
Also `checksum.h` was missing an include guard, and the unit test is a bit odd.
=> lib: make checksum code take iovec for input 

staticd/static_zebra.c
Zebra sends a nexthop-update message on registeration, which will cause
existing routes to be reconfigured even no changes actually happened.
Don't register the nexthop again if it's already done.
=> staticd: Don't register existing nexthop to zebra

isisd/isis_nb_notifications.c, lib/base64.c, lib/base64.h, lib/subdir.am, lib/yang_wrappers.c, lib/yang_wrappers.h
This pull request fixes #10505. Please refer to #10505 for details.
=> isisd: use base64 to encode the binary data.

doc/developer/topotests.rst
Just to avoid publicly IPv4/IPv6 ranges in topotests/documentation.
=> doc: Enforce using IPv4/IPv6 reserved ranges for documentation

doc/user/zebra.rst
Fix a typo in the zebra doc file that triggers a warning.
=> doc: fix typo in zebra doc

zebra/zebra_nhg.c
When a end operator is doing cross vrf imports in bgp:
router bgp 3239 vrf FOO
address-family ipv4 uni
import vrf BAR
!
and zebra has this configuration:
vrf FOO
ip protocol bgp route-map EVA
!
The current code in zebra_nhg.c was looking up the vrf of the
nexthop and attempting to apply the ip protocol route-map.
For most people the nexthop vrf and the re vrf are one and the
same so they never see a problem.
=> zebra: Use the routes vrf not the nexthop vrf for route-map application

doc/user/zebra.rst, zebra/kernel_socket.c, zebra/zebra_rib.c
See individual commits, but effectively let's get some level of graceful restart functioning in *BSD.  Currently a zebra restart with routes left in the table will cause the routes to stay in the kernel and zebra to not know about them at all after the graceful restart timer pops.
=> Bsd zebra graceful restart cleanup

bgpd/bgp_evpn_vty.c
Just display default vrf name in command.
=> bgpd: fix missing name of default vrf

doc/user/basic.rst, lib/thread.c, tools/etc/frr/support_bundle_commands.conf, vtysh/vtysh.c, zebra/interface.c, zebra/interface.h
See individual commits:
a) Add a `show thread timers` command
b) Add doc
c) Add to support bundle this data gathering
d) Limit interface speed checks to 4 minutes
=> lib, vtysh: Thread timers

doc/user/zebra.rst
Fix a typo in the zebra doc file that generates a warning.
This is the 8.2 backport of #10682
=> [8.2] doc: fix typo in zebra user doc

pimd/pim_bsm.c, pimd/pim_mroute.c, pimd/pim_nht.c, pimd/pim_rp.c, pimd/pim_rpf.c, pimd/pim_rpf.h
We can use PIMADDR_ANY instead of INADDR_NONE to initalize rp->rpf_addr
when there is no rp configured for group_all.
This PR will bring below change in behaviour.
When user will configure rp as 255.255.255.255 pim will accept and create not reachable RP.
Earlier it was rejecting this config as bad address.
=> pimd: replace inaddr_none with PIMADDR_ANY

lib/vty.c, lib/zclient.c, ospfd/ospf_apiserver.c, ospfd/ospf_apiserver.h
See individual commits, but there are 3 cases of enum's called `enum event` in our code base.  Let's rename them to something a bit better named to reduce confusion in the future.
=> lib, ospfd: Enum fixup

bgpd/bgp_route.c
Include the BGP_SHOW_OPT_DETAIL flag in the 'detail' version of the
command.
=> bgpd: fix 'show bgp detail json' output

lib/routemap.c
This issue is applicable to other protocols as well.
When user has configured route-map, even though the prefixes are falling
under the permit rule, the prefixes were denied and were shown
as inactive route in zebra.
Reason being the parameter which is of type enum was passed to the api
route_map_get_index and was typecasted to uint8_t *.
This problem is visible in case of Big Endian systems because we are
accessing the most significant byte.
'match_ret' field is an enum in the caller and so it is of 4 bytes,
the typecasting it to 1 byte and passing it to the api made
the api to put the value in the most significant byte
which was already zero previously. Therefore the actual value
RMAP_NOMATCH which was 1 never gets reset in this case.
Therefore the api always returns 'RMAP_NOMATCH' and …
=> lib: Route-map failed for OSPF routes even for matching prefixes

bgpd/bgp_rpki.c
Bad formatting applied and it worked with small amount of prefixes (lurking).
With full BGP feed and full RPKI table, this causes infinity loop.
=> bgpd: Fix while(read()) for RPKI sync callback

doc/user/zebra.rst
Fix another typo that mis-uses the asterisk character, producing a warning.
=> doc: fix another doc typo

lib/northbound_grpc.cpp
Fix crashes in the grpc module
- Initialize RPC state instance vars to NULL before testing them for NULL.
- Was using a global std::unique_ptr<> and then NULLing it before we were done with the grpc server it was pointing at, the unique_ptr deletes the server when NULLed, which we didn't want.
- fix the shutdown code in general to be thread safe and actually delete the items drained from the queue.
- fix candidate early delete
fixes #9732, fixes #10578, closes #10073
=> critical fixes for grpc

bgpd/bgp_route.c
Commit: ea47320b1d0eeaa56f945fa356da7e4ca7f2b0b2
Modified the bgp_clear_stale_route function to have
better indentation, but in the process changed some
`continue;` statements to `break;` which modified
the looping and caused stale paths to not always be
removed upon an update.
To reproduce:  A ---- B, setup with addpath and GR
One side has a prefix with nhop1 and nhop2, kill one
side and then resend the same prefix with nhop3,
paths nhop1 and 2 become stale and never removed.
Code inspection clearly shows that that `continue`
statements became `break` statements causing the
loop over all paths to stop prematurely.
The fix is to change the break back to continue
statements so the loop can continue instead of
stopping.
=> bgpd: Fix continue/break change from old commit

zebra/zebra_netns_id.c
clang complains `variable 'curr_length' set but not used`.
=> zebra: remove unused variable

pimd/pim6_main.c
1. Removing duplicate if_cmd_init
2. Fix vrf initialisation in Northbound
=> pim6d: Few fixes

pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_addr.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_nb.h
This PR adds the below interface level CLIs for PIMv6.
Adding the below CLIs for PIMv6 Daemon:
[no] ipv6 pim
[no] ipv6 pim drpriority (1-4294967295)
[no] ipv6 pim hello (1-65535) [(1-65535)]
[no] ipv6 pim active-active
[no] ipv6 pim ssm
[no] ipv6 pim sm
[no] ipv6 multicast boundary oil WORD
[no] ipv6 mroute INTERFACE X:X::X:X [X:X::X:X]
=> pimv6 Interface cli implementation 

yang/frr-route-types.yang
The pattern defined for ipv6-multicast-group-prefix is wrong.
This is leading to mismatch for all the valid ipv6 multicast
addresses.
Issue:
areia(config)# ipv6 pim rp 2001:db8::1 ff00::/12
2022/03/07 16:01:20 PIM6: libyang: Invalid union value "ff00::/12" - no matching subtype found. (Schema location /frr-routing:routing/control-plane-protocols/control-plane-protocol/frr-pim:pim/address-family/frr-pim-rp:rp/static-rp/rp-list/group-list-or-prefix-list/group-list/group-list.)
The fix is taken from RFC 8294.
=> yang: Fix the ipv6 multicast pattern in frr-route-types

zebra/interface.c
When an interface goes down, it signals any related NHGs to re-validate themselves. During zebra shutdown, ensure we clean up any installed NHGs.
=> zebra: shutdown doesn't uninstall related NHG

pimd/pim6_stubs.c, pimd/pim_nht.c, pimd/pim_zebra.c, pimd/subdir.am
include NHT code back into compilation for IPv6
not tested at this point, just compiles (and doesn't immediately crash)
=> pim6d: reenable NHT code

zebra/if_netlink.c, zebra/interface.c, zebra/interface.h, zebra/zebra_ptm.c
For  (vxlan but any) interface is configured and UP, in the event of protodown, handle the event to bring the interface down and trigger interface up event when protodown flag is removed.
The couple of fixes found in MLAG scenario where protodown event needs to bring down vni on the primary switch. In absence  evpn routes are advertised incorrectly. 
```
1. 
zebra: handle protodown netlink for vxlan device
Frr need to handle protocol down event for vxlan interface.
In MLAG scenario, one of the pair switch can put vxlan port to protodown state, 
followed by tunnel-ip change from anycast IP to individual IP.
In absence of protodown handling, evpn end up advertising locally learn EVPN (MAC-IP) routes
with individual IP as nexthop.  This leads an issue of overwriting locally learn  entries as …
```
=> zebra: netlink protodown event handling for vxlan device

pimd/pim_br.c, pimd/pim_br.h, pimd/pim_msg.h, pimd/pim_register.c, pimd/pim_register.h
Handle receive of pimv6 register packet
Once the send register flow is handled, will move the pim_register.c to pim_common in subdir.am
=> pim6d: Handle receive of pimv6 register packet

ospf6d/ospf6_gr.c, ospfd/ospf_gr.c
=> ospfd,ospf6d: Add missing newline for `graceful-restart prepare` CLI

lib/libfrr.c, lib/libfrr.h, lib/log_vty.c, lib/zlog.c, lib/zlog_live.c, lib/zlog_live.h, vtysh/vtysh.c
Two important bugfixes:
* [lib: fix log target removal when singlethreaded](https://github.com/FRRouting/frr/commit/d03440cab78605dcc21427127afdf78860d9916b)
* [lib: make live log sockets non-blocking](https://github.com/FRRouting/frr/commit/c9bc69578efbeecfa32fd3f70b2dd7bd6df03b58)
One ancillary bugfix:
* [lib: fix live log fields for crashlog](https://github.com/FRRouting/frr/commit/e69c4a01c1c283c6d55eb2ed2dc8478113e5ac32)
And the remaining commits are "polish"/improvements to the `terminal monitor` feature.
=> lib, vtysh: apply some polish to live-log feature

bgpd/bgp_errors.c, bgpd/bgp_errors.h, bgpd/bgp_zebra.c
When BGP detects that a peering is using a global address but no v6 LL
address has been created for the interface that the global address is
on warn the user that something is amiss and they need to fix it.
=> bgpd: Warn user when an interface has no v6 LL address

zebra/zebra_evpn_neigh.c
In `zebra_evpn_neigh_gw_macip_add()`, it sets `mac->flags` to "ZEBRA_MAC_DEF_GW"
for "advertise-default-gw" mode. But this set is redundant because this "mac"
is already set by `zebra_evpn_mac_gw_macip_add()`.
So remove this redundant assignment.
=> zebra: remove unnecessary assignment

doc/developer/logging.rst, lib/json.c, lib/json.h, lib/prefix.c, pimd/pim_ifchannel.c, pimd/pim_rp.c, pimd/pim_zebra.c, tests/lib/test_printfrr.c
Some random IPv6 mix-ups that showed up when working with the code.
Note: this is on top of / uses / includes PR #10773
=> pim6d: fix a bunch of IPv6 confusion

doc/developer/logging.rst, lib/json.c, lib/json.h, lib/prefix.c, tests/lib/test_printfrr.c
* `json_object_object_addf()` to add an item to a JSON object/dict with a format string key
* `%pFXh` to print a prefix without prefix length
=> lib: more printfrr bits (JSON key, prefix w/o len)

tests/topotests/lib/topotest.py
Do not allow the test system to turn off the logging of commands
Some tests use the reload command that is accidently turning off
the logging.  Just force the tests to ignore it.
=> tests: Make all commands logged

pimd/pim_cmd_common.c
Fixing the below problem:
*** CID 1515041:  Null pointer dereferences  (NULL_RETURNS)
/pimd/pim_cmd_common.c: 592 in pim_process_no_rp_cmd()
586                     vty_out(vty, "%% Unable to find specified RP\n");
587                     return NB_OK;
588             }
589     
590             group_dnode = yang_dnode_get(vty->candidate_config->dnode, group_xpath);
591     
>>>     CID 1515041:  Null pointer dereferences  (NULL_RETURNS)
>>>     Dereferencing a pointer that might be "NULL" "group_dnode" when calling "yang_is_last_list_dnode".
592             if (yang_is_last_list_dnode(group_dnode))
593                     nb_cli_enqueue_change(vty, rp_xpath, NB_OP_DESTROY, NULL);
594             else
595                     nb_cli_enqueue_change(vty, group_list_xpath, NB_OP_DESTROY,
596 …
=> pimd: Fix Null pointer dereference

bgpd/bgp_packet.c, lib/sockunion.c, lib/sockunion.h, pimd/pim_msdp_packet.c
sockopt_cork is a no-op function that was cleaned up
in 2017.  Since then it's still not being used.  At
this point in time there is little point in keeping a
dead function that will not be used because of vagaries
between platforms
=> bgpd, lib, pimd: Remove sockopt_cork

doc/user/pim.rst, pimd/pim_cmd.c, pimd/pim_rp.c, pimd/pim_rp.h, pimd/pim_ssm.h
And filter by group for PIM.
```
exit1-debian-11# show ip pim rp-info
RP address       group/prefix-list   OIF               I am RP    Source   Group-Type
192.168.10.17    238.0.0.0/24        eth2              no         Static   ASM
192.168.10.110   232.0.0.0/24        eth2              no         Static   SSM
exit1-debian-11# show ip pim rp-info 238.0.0.0/24
RP address       group/prefix-list   OIF               I am RP    Source   Group-Type
192.168.10.17    238.0.0.0/24        eth2              no         Static   ASM
exit1-debian-11# show ip pim rp-info 238.0.0.0/24 json
{
"192.168.10.17":[
{
"rpAddress":"192.168.10.17",
"outboundInterface":"eth2",
"iAmRP":false,
"group":"238.0.0.0/24",
"source":"Static",
"groupType":"ASM"
}
]
}
exit1-debian-11#
```
Signed-off-by: Donatas Abraitis …
=> pimd: Show group-type under `show ip pim rp-info`

pimd/pim_cmd.c
Changes correct typo in JSON output for IGMP interface statistics show
command from "leaveV3" to "leaveV2".
Signed-off-by: David Schweizer <dschweizer@opensourcerouting.org>
=> pimd: fix typo in IGMP interface statistics JSON output.

.clang-format, doc/developer/lists.rst, lib/typerb.c, lib/typerb.h, lib/typesafe.h, tests/lib/test_typelist.c, tests/lib/test_typelist.h
As requested by @donaldsharp,  `_last` & `_prev` functions in the typesafe container family. Only `DLIST` and `RBTREE` support these.
Free documentation updates included (limited time offer, only one per customer!)
[do a flip!](https://old.reddit.com/r/futurama/comments/r54u8/do_a_flip/)
=> lib: typesafe container reverse iterators

debian/.gitignore, debian/rules
I was wondering if there's a particular reason `frr@.service` is not included in the Debian package? Guess this would fix it (untested) unless that's intentional.
=> debian: include frr@.service in deb

lib/log_vty.c
Call `zlog_file_rotate` for command file lines as well otherwise on `SIGUSR1` the old descriptor will still be used and no new log file will be created for the rotation.
=> lib: rotate log file supplied by command line

zebra/zebra_evpn_neigh.c, zebra/zebra_vxlan.c
A little bit of cleanup.
Since `assert` is already done, just remove these unnecessary check.
=> zebra: Remove unnecessary check

zebra/dplane_fpm_nl.c
Fix a crash that could happen if the socket closed in the middle of processing a batch of commands.
If the socket is closed during the `while` loop that drains the zebra data plane framework queued items the data structure `socket` field goes to `-1` and inside `fpm_nl_enqueue` the call `thread_add_write(..., fnc->socket, ...);` will `assert()`.
=> zebra: don't enqueue data with FPM socket closed

pimd/pim_cmd.c, pimd/pim_igmp_stats.c, pimd/pim_igmp_stats.h
```
exit1-debian-11# do sh ip igmp statistics
IGMP statistics
Interface               : global
V1 query                : 0
V2 query                : 0
V3 query                : 3
V2 leave                : 0
V1 report               : 0
V2 report               : 0
V3 report               : 18
mtrace response         : 0
mtrace request          : 0
unsupported             : 0
total received messages : 21
joins failed            : 0
joins sent              : 16
general queries sent    : 6
group queries sent      : 3
total groups            : 4
total source groups     : 1
exit1-debian-11# do sh ip igmp statistics json
{
"global":{
"name":"global",
"queryV1":0,
"queryV2":0,
"queryV3":4,
"leaveV2":0,
"reportV1":0,
"reportV2":0,
"reportV3":18,
"mtraceResponse":0,
"mtraceRequest":0, …
```
=> pimd: Show total received messages IGMP stats

zebra/zebra_vxlan.c
Since `zvni_map_to_svi_ns()` is used to find and return one specific interface
based on passed attributes of SVI, so the two parameters `in_param` and `p_ifp`
must not be NULL.
Passing NULL `p_ifp` makes no sense, so the check `if (p_ifp)` is
unnecessary.
So use `assert` to ensure the two parameters, and remove that unnecessary check.
=> zebra: use "assert" instead of unnecessary check

pimd/pim_upstream.c
The pim_upstream data structure has a ref count that is
not properly being incremented/decremented and when an
instance is removed this is causing crashes because timers
are still popping afterwords on data structures that are
now freed.
Since getting the ref count code is extremely hard and
we know that this crash is happening, add a bit of code
to prevent the timers from popping at all when we go
through and free up other data structures that we
are pointing at.
=> pimd: Ensure timers are stopped on instance shutdown

bgpd/bgp_vty.c
Simple prompt issue.
"no router bgp <ASN>" is ok, but "no router bgp" without <ASN> missed "\n".
=> bgpd: add new line for prompt of "no router bgp"

pimd/pim_cmd.c, pimd/pim_iface.h, pimd/pim_igmp.c, pimd/pim_igmp_stats.c, pimd/pim_igmp_stats.h, pimd/pim_pim.c
```
exit1-debian-11# sh ip igmp statistics interface eth2
IGMP statistics
Interface            : eth2
V1 query             : 0
V2 query             : 0
V3 query             : 25
V2 leave             : 0
V1 report            : 0
V2 report            : 0
V3 report            : 34
mtrace response      : 0
mtrace request       : 0
unsupported          : 0
joins failed         : 0
joins sent           : 13
general queries sent : 2
group queries sent   : 24
peak groups          : 9
total groups         : 4
total source groups  : 1
exit1-debian-11# sh ip igmp statistics interface eth2 json
{
"eth2":{
"name":"eth2",
"queryV1":0,
"queryV2":0,
"queryV3":25,
"leaveV2":0,
"reportV1":0,
"reportV2":0,
"reportV3":34,
"mtraceResponse":0,
"mtraceRequest":0,
"unsupported":0,
"peakGroups":9, …
```
=> pimd: Add additional IGMP stats (peak number of groups)

zebra/if_netlink.c
Look up linked interface in the correct netns, otherwise, either a wrong
interface or NULL would be used.
**To Reproduce**
```
```
zebra will crash in `zebra_vxlan_macvlan_up` because `zif->link` is `NULL`.
=> zebra: Lookup linked interface in link netns

zebra/zebra_vxlan.c
Upon 'no advertise-all-vni', cleanup l2vni from its tenant-vrf's l3vni list, instead of passed
zvrf->l3vni which will not be present in case of default instance.
Testing Done:
Before Fix:
```
TORC12(config-router-af)# advertise-all-vni
TORC12(config-router-af)# end
TORC12# show evpn vni 4001
VNI: 4001
Type: L3
Tenant VRF: vrf1
Vxlan-Intf: vni4001
State: Up
Router MAC: 44:38:39:ff:ff:01
L2 VNIs: 134217728 0 1000 1002 <-----
```
After Fix:
```
TORC12# show evpn vni 4001
VNI: 4001
Type: L3
Tenant VRF: vrf1
Vxlan-Intf: vni4001
State: Up
Router MAC: 44:38:39:ff:ff:01
L2 VNIs: 1000 1002
```
=> zebra: evpn disable remove l2vni from l3vni list

tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/frr.conf, tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/ospf-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/ospf-vrf-neno.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r1/zebra-vrf-neno.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/frr.conf, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/ospf-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/ospf-vrf-ray.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r2/zebra-vrf-ray.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r3/frr.conf, tests/topotests/ospf_multi_vrf_bgp_route_leak/r3/ospf-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r3/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r4/frr.conf, tests/topotests/ospf_multi_vrf_bgp_route_leak/r4/ospf-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/r4/zebra-vrf-default.txt, tests/topotests/ospf_multi_vrf_bgp_route_leak/test_ospf_multi_vrf_bgp_route_leak.py
Test ospf running with 3 vrfs: default, neno, ray
Route leaking is setup via bgp between default and neno vrfs
Leaked routes include connected and ospf
Included test:
1- OSPF convergnce
2- zebra/kernel routes
=> tests: add a topotest for ospf, mutli vrf, and route leaking

doc/user/sharp.rst, doc/user/zebra.rst, include/linux/if_link.h, sharpd/sharp_vty.c, sharpd/sharp_zebra.c, sharpd/sharp_zebra.h, tests/topotests/zebra_rib/test_zebra_rib.py, zebra/debug_nl.c, zebra/dplane_fpm_nl.c, zebra/if_netlink.c, zebra/if_netlink.h, zebra/if_socket.c, zebra/interface.c, zebra/interface.h, zebra/kernel_netlink.c, zebra/kernel_socket.c, zebra/rt.h, zebra/rt_netlink.h, zebra/subdir.am, zebra/zapi_msg.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h, zebra/zebra_errors.c, zebra/zebra_errors.h, zebra/zebra_evpn_mh.c, zebra/zebra_evpn_mh.h, zebra/zebra_nhg.c, zebra/zebra_rib.c, zebra/zebra_router.h, zebra/zebra_vty.c
Add support for setting the protodown reason code.
https://github.com/torvalds/linux/commit/829eb208e80d6db95c0201cb8fa00c2f9ad87faf
These patches handle all our netlink code for setting the reason.
For protodown reason we only set `frr` as the reason externally
but internally we have more descriptive reasoning available via
`show interface IFNAME`. The kernel only provides a bitwidth of 32
that all userspace programs have to share so this makes the most sense.
Since this is new functionality, it needs to be added to the dplane
pthread instead. So these patches, also move the protodown setting we
were doing before into the dplane pthread. For this, we abstract it a
bit more to make it a general interface LINK update dplane API. This
API can be expanded to support gernal link …
=> Add Support for Setting Protodown Reason Code

ospfd/ospf_vty.c
before:
```
r1# show ip ospf vrf blue
% OSPF instance not found
r1# show ip ospf vrf default
% OSPF instance not found
r1# show ip ospf
% OSPF instance not found
```
after:
```
r1# show ip ospf vrf blue
% OSPF is not enabled in vrf blue
r1# show ip ospf vrf default
% OSPF is not enabled in vrf default
r1# show ip ospf
% OSPF is not enabled in vrf default
```
=> ospfd: better error messages when not enabled in a vrf

lib/plist.c, lib/plist_int.h
The prefix_master->str data structure was a sorted
list of the prefix names.  Not that big of a deal
other than insertion and deletion is insanely expensive
when you have a large number of unique prefix-lists.
In my test config file that I discovered this,
I have 587 unique prefix lists spread out acros
~26k lines of prefix-lists.  When reading
this config file into FRR the read time goes
from 690 seconds to 650 seconds.
=> lib: Convert prefix_master->str to a RB Tree

tests/topotests/lib/topogen.py
=> topotest: enable pim when detecting `ip pim` using unified config

lib/northbound_grpc.cpp
One uninit warning and one missing lock warning, both were OK but
let's make the tool happy.
=> lib: grpc: fix covevrity warnings

bgpd/bgp_evpn.c, bgpd/bgp_evpn_private.h
`bgp_evpn_import_route_in_vrfs()` is special ( l2vpn ) form of
`install_uninstall_evpn_route() with `AFI_L2VPN` and `SAFI_EVPN` family.
No caller, just remove it.
=> bgpd: remove dead code

zebra/zebra_evpn.c, zebra/zebra_evpn_mac.c, zebra/zebra_evpn_mac.h
Two minor changes:
1) Change `zebra_evpn_mac_gw_macip_add()` 's return type to `void`.
2) Since `zebra_evpn_mac_gw_macip_add()` has already `assert` the returned
`mac`, the check of its return value makes no sense. And keep setting
`mac->flags` inside `zebra_evpn_mac_gw_macip_add()` is more reasonable. So
just move the setting `mac->flags` inside `zebra_evpn_mac_gw_macip_add()`.
=> zebra: minor changes on "zebra_evpn_mac_gw_macip_add" function

zebra/zebra_script.c
Commit: 5d41413833 added 3 new dplane ops:
DPLANE_OP_INTF_INSTALL
DPLANE_OP_INTF_UPDATE
DPLANE_OP_INTF_DELETE
The build system does not build lua so zebra_script.c
was not updated.  Update of course!
=> zebra: Fixup lua with new dplane ops

lib/wheel.c
The wheel data structure is a array of list pointers
but the alloc for it is using the sizeof (struct listnode *)
as the amount to allocate.  Even though the (struct listnode *)
and (struct list *) sizes are the same, let's list the correct
values.
Signed-off-by: ron <lyq140hf2006@163.com>
=> lib: wheel's typo fix

tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py
Currently the test case test_ospfv3_type5_summary_tc46_p0 checks whether the route-calculation for Type-5 is fine or not.
Adding the "show ipv6 ospf6 database as-external json" output in the test script to narrow
down whether it is an LSA origination problem or route calculation problem when the test case fails.
=> tests: Adding database info in the script to ease debug

tests/topotests/lib/micronet_cli.py
1. Handle KeyError
2. logger object is defined in main function and its not not accessible
in other functions so defined it in local functions.
=> tests: Fix topotests crash when KeyError found

zebra/rt_socket.c
When issuing a RTM_DELETE operation and the kernel tells
us that the route is already deleted, let's not complain
about the situation:
2022/03/19 02:40:34 ZEBRA: [EC 100663303] kernel_rtm: 2a10:cc42:1d51::/48: rtm_write() unexpectedly returned -4 for command RTM_DELETE
I can recreate this issue on freebsd by doing this:
a) create a route using sharpd
b) shutdown the nexthop's interface
c) remove the route using sharpd
This would also be true of pretty much any routing protocol's behavior.
Let's just not complain about the situation if a RTM_DELETE
operation is issued and FRR is told that the route does not
exist to delete.
=> zebra: Do not complain if deletion fails

bgpd/bgp_evpn.c
Importing local es routes should be skipped. But the check of it is a bit wrong.
It is ok that local es routes can't be imported, but importing local es will
wrongly enter `uninstall` procedure.
Just adjust this check to make it clear. Immediately return in the case
of importing local es routes.
=> bgpd: fix wrong check on local es routes

bgpd/bgp_evpn_mh.c, zebra/zebra_evpn_mh.c
Two commits:
Since the `RB_INSERT()` is called after not found in RB tree, it MUST be ok and
and return zero. The check of returning value of `RB_INSERT()` is redundant,
just remove them.
=> zebra, bgpd: remove check returning value of RB_INSERT()

doc/user/pim.rst, pimd/pim_cmd.c, pimd/pim_nht.c, pimd/pim_vty.c, pimd/pim_zlookup.c, pimd/pimd.h
PIM Logs are coming at intervals of 1 minute although pim
is not enabled.
Fix:
Added a new option "detail" in the cli:
debug pim nht detail
=> pimd: Added new option "detail" in the "debug pim nht" CLI

zebra/rt_netlink.c
When a operator has a FRR based route installed into the
FIB and a better route comes in from the system.  There
is code in the data plane to schedule the batching
but not to save the context.  In this case if the
operations fails to work properly Zebra will never
know about this.  In this case tell the
=> zebra: Better handle replacing our route by a system route

tools/frrcommon.sh.in
Just suppress false warnings in syslog.
=> tools: suppress unuseful warnings during restarting frr

pimd/pim_cmd.c
source/group information now added for pruned entry
show ip mroute json command displays the source, group info
per oil, so for pruned group since the OIL is empty, it is not
showing.
Fix: Added the above information per source.
=> pimd: add source and group information in mroute json

ospf6d/ospf6_flood.c, ospf6d/ospf6_lsdb.c
Problem:
ospf6d crash is observed when lsack is received from the neighbour for
AS External LSA.
RCA:
The crash is observed in ospf6_decrement_retrans_count while decrementing
retransmit counter for the LSA when lsack is recived. This is because in
ospf6_flood_interace when new LSA is being added to the neighbour's list
the incrementing is happening on the received LSA instead of the already
present LSA in scope DB which is already carrying counters.
when this new LSA replaces the old one, the already present counters are
not copied on the new LSA this creates counter mismatch which results in
a crash when lsack is recevied due to counter going to negative.
Fix:
The fix involves following changes.
1. In ospf6_flood_interace when LSA is being added to retrans list
check if there is alreday …
=> ospf6d: observed crash in ospf6_decrement_retrans_count.

bgpd/bgp_evpn_mh.c
Since the returned value MUST be valid, remove unnecessary checkings.
=> bgpd: remove unnecessary checkings for the returned value

zebra/zebra_evpn_mac.h, zebra/zebra_vxlan.c
Remove host prefix mapping under RMAC instead use list of nexthops to keep track of its existence. 
**Problem**:
In CLAG deployment there might be a situation where CLAG secondary sends individual ip as nexthop
along with anycast mac as RMAC. This combination is updated in zebra's rmac cache.
Upon recovery at clag secondary sends withdrawal of the incorrect rmac and nexthop mapping.
The RMAC entry mapping to nh is not cleaned up properly in the zebra rmac cache.
**Fix**:
Zebra rmac db needs to maintain a list of nexthops.  When a bgp withdrawal for rmac to nexthop mapping 
is received, remove the old nexthop from the rmac's nh list and if the host reference still remains for
the RMAC,fall back to the nexthop one remaining in the list.
At most you expect two nexthops mapped to RMAC (in …
=> zebra: evpn revamp l3vni routermac db 

tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py
Moved the database dump for ospfv3 before ospf route check to ease debugging.
=> tests: Add the show database for ospfv3 before checking for ospf route

pathd/path_cli.c
The order of nai adjacencies ipv6 addresses was wrong.
The src and the destination addresses were swapped.
Change it.
=> pathd: bad order of nai adjacencies for ipv6

bgpd/bgp_bmp.c
Avoid use-after-free and prevent from crashing:
```
(gdb) bt
0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
1  0x00007f2a15c2c30d in core_handler (signo=11, siginfo=0x7fffb915e630, context=<optimized out>) at lib/sigevent.c:261
2  <signal handler called>
3  0x00007f2a156201e4 in bmp_stats (thread=<optimized out>) at bgpd/bgp_bmp.c:1330
4  0x00007f2a15c3d553 in thread_call (thread=thread@entry=0x7fffb915ebf0) at lib/thread.c:2001
5  0x00007f2a15bfa570 in frr_run (master=0x55c43a393ae0) at lib/libfrr.c:1196
6  0x000055c43930627c in main (argc=<optimized out>, argv=<optimized out>) at bgpd/bgp_main.c:519
(gdb)
```
Fixes https://github.com/FRRouting/frr/issues/10856
=> bgpd: Turn off thread when running `no bmp targets X`

zebra/ioctl.c
When running zebra w/ valgrind, it was noticed that there
was a bunch of passing uninitialized data to the kernel:
==38194== Syscall param ioctl(generic) points to uninitialised byte(s)
==38194==    at 0x4CDF88A: ioctl (in /lib/libc.so.7)
==38194==    by 0x49A4031: vrf_ioctl (vrf.c:860)
==38194==    by 0x2AFE29: vrf_if_ioctl (ioctl.c:91)
==38194==    by 0x2AFF39: if_get_mtu (ioctl.c:161)
==38194==    by 0x2B12C3: ifm_read (kernel_socket.c:653)
==38194==    by 0x2A7F76: interface_list (if_sysctl.c:129)
==38194==    by 0x2E9958: zebra_ns_enable (zebra_ns.c:127)
==38194==    by 0x2E9958: zebra_ns_init (zebra_ns.c:214)
==38194==    by 0x2B3F82: main (main.c:401)
==38194==  Address 0x7fc000967 is on thread 1's stack
==38194==  in frame #3, created by if_get_mtu (ioctl.c:155)
==38194== …
=> zebra: Don't send uninited data to kernel on FreeBSD

lib/vty.c
When `terminal monitor` is issued I am seeing this for valgrind on freebsd:
2022/03/24 18:07:45 ZEBRA: [RHJDG-5FNSK][EC 100663304] can't open configuration file [/usr/local/etc/frr/zebra.conf]
==52993== Syscall param sendmsg(sendmsg.msg_control) points to uninitialised byte(s)
==52993==    at 0x4CE268A: _sendmsg (in /lib/libc.so.7)
==52993==    by 0x4B96245: ??? (in /lib/libthr.so.3)
==52993==    by 0x4CDF329: sendmsg (in /lib/libc.so.7)
==52993==    by 0x49A9994: vtysh_do_pass_fd (vty.c:2041)
==52993==    by 0x49A9994: vtysh_flush (vty.c:2070)
==52993==    by 0x499F4CE: thread_call (thread.c:2002)
==52993==    by 0x495D317: frr_run (libfrr.c:1196)
==52993==    by 0x2B4068: main (main.c:471)
==52993==  Address 0x7fc000864 is on thread 1's stack
==52993==  in frame #3, created by …
=> lib: Fix `terminal monitor` uninited memory usage on freebsd

lib/subdir.am
Remove a couple of lex/yacc output files in lib/ during 'distclean' : command_parse.[ch] and command_lex.[ch] were not being removed.
=> build: remove generated lib files during distclean

lib/log.c
When using zlog_backtrace I am seeing this:
==66286== Syscall param write(buf) points to uninitialised byte(s)
==66286==    at 0x4CDF48A: syscall (in /lib/libc.so.7)
==66286==    by 0x4A0D409: ??? (in /usr/local/lib/libunwind.so.8.0.1)
==66286==    by 0x4A0D694: ??? (in /usr/local/lib/libunwind.so.8.0.1)
==66286==    by 0x4A0E2F4: _ULx86_64_step (in /usr/local/lib/libunwind.so.8.0.1)
==66286==    by 0x49662DB: zlog_backtrace (log.c:250)
==66286==    by 0x2AFFA6: if_get_mtu (ioctl.c:163)
==66286==    by 0x2B2D9D: ifan_read (kernel_socket.c:457)
==66286==    by 0x2B2D9D: kernel_read (kernel_socket.c:1406)
==66286==    by 0x499F46E: thread_call (thread.c:2002)
==66286==    by 0x495D2B7: frr_run (libfrr.c:1196)
==66286==    by 0x2B4098: main (main.c:471)
==66286==  Address 0x7fc000000 is on …
=> lib: Prevent uninitialized bytes

zebra/if_netlink.c, zebra/interface.c, zebra/interface.h, zebra/kernel_socket.c, zebra/zebra_netns_notify.c
In the FreeBSD code if you delete the interface
and it has no configuration, the ifp pointer will
be deleted from the system *but* zebra continues
to dereference the just freed pointer.
==58624== Invalid read of size 1
==58624==    at 0x48539F3: strlcpy (in /usr/local/libexec/valgrind/vgpreload_memcheck-amd64-freebsd.so)
==58624==    by 0x2B0565: ifreq_set_name (ioctl.c:48)
==58624==    by 0x2B0565: if_get_flags (ioctl.c:416)
==58624==    by 0x2B2D9E: ifan_read (kernel_socket.c:455)
==58624==    by 0x2B2D9E: kernel_read (kernel_socket.c:1403)
==58624==    by 0x499F46E: thread_call (thread.c:2002)
==58624==    by 0x495D2B7: frr_run (libfrr.c:1196)
==58624==    by 0x2B40B8: main (main.c:471)
==58624==  Address 0x6baa7f0 is 64 bytes inside a block of size 432 free'd
==58624==    at …
=> zebra: Fix use after deletion event in freebsd

bgpd/bgp_route.c
When `all` is specified BGP pointer is always NULL, we need to iterate over
all instances separately.
```
Received signal 11 at 1648199394 (si_addr 0x30, PC 0x562e96597090); aborting...
/usr/local/lib/libfrr.so.0(zlog_backtrace_sigsafe+0x5e) [0x7f378a57ff6e]
/usr/local/lib/libfrr.so.0(zlog_signal+0xe6) [0x7f378a580146]
/usr/local/lib/libfrr.so.0(+0xcd4c2) [0x7f378a5aa4c2]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f378a33e140]
/usr/lib/frr/bgpd(bgp_afi_safi_peer_exists+0) [0x562e96597090]
/usr/lib/frr/bgpd(+0x15c3b8) [0x562e9654a3b8]
```
=> bgpd: Fix crash for `show ip bgp vrf all all neighbors 192.168.0.1 ...`

pimd/pim_ssmpingd.c, pimd/pim_vty.c
PR #10653 forgot to update a bunch of format specifiers.  Fix.
=> pim6d: fix format string mistakes in ssmpingd

zebra/zebra_evpn_mac.c
When `zebra_evpn_mac_svi_add()` adds one found mac by                                                                                   
`zebra_evpn_mac_lookup()` and the found mac is without                           
svi flag, then call `zebra_evpn_mac_svi_add()` to create                         
one appropriate mac, but it will call `zebra_evpn_mac_lookup()`                  
the second time. So lookup twice, the procedure is redundant.                    
Just an optimization for it, make sure only lookup once.                         
Modify `zebra_evpn_mac_gw_macip_add()` to check the `macp`                       
parameter passed by caller, so it can distinguish whether                        
really need lookup or not.
=> zebra: optimization on the mac addition for evpn-mh

lib/monotime.h
These 3 values:
ONE_DAY_SECOND
ONE_WEEK_SECOND
ONE_YEAR_SECOND
Are defined based upon the number of seconds.  Unfortunately doing math
on these values say something like:
days = t->tv_sec / ONE_DAY_SECOND;
Once you go over about a day causes the order of operations to cause the multiplication
to get messed up:
204		if (!t)
(gdb) n
207		w = d = h = m = ms = 0;
(gdb) set t->tv_sec = ONE_DAY_SECOND + 30
(gdb) n
208		memset(buf, 0, size);
(gdb)
210		us = t->tv_usec;
(gdb)
211		if (us >= 1000) {
(gdb)
212			ms = us / 1000;
(gdb)
213			us %= 1000;
(gdb)
217		if (ms >= 1000) {
(gdb)
222		if (t->tv_sec > ONE_WEEK_SECOND) {
(gdb)
227		if (t->tv_sec > ONE_DAY_SECOND) {
(gdb)
228			d = t->tv_sec / ONE_DAY_SECOND;
(gdb) n
229			t->tv_sec -= d * ONE_DAY_SECOND;
(gdb) n
232		if (t->tv_sec >= …
=> lib: Ensure order of operations is expected with SECONDS

babeld/babel_interface.c
When babeld was switched over to the zapi
interface up/down callbacks the interface up
event was not properly put back in.
Fixes: #10893
=> babeld: Rehook up interface up events

bgpd/bgp_evpn_private.h
`is_vni_param_configured()` is used to check whether RD/RT
configured for specific evpn vni.
There seems to be no need for this mixed check. No caller for
about 5 years, just remove it.
=> bgpd: remove dead code for evpn

zebra/kernel_netlink.c
There exists code paths in the linux kernel where a dump command
will be interrupted( I am not sure I understand what this really
means ) and the data sent back from the kernel is wrong or incomplete.
At this point in time I am not 100% certain what should be done, but
let's start noticing that this has happened so we can formulate a plan
or allow the end operator to know bad stuff is a foot at the circle K.
=> zebra: Note when the netlink DUMP command is interrupted

bgpd/bgp_attr.c
When reading the BGP_PREFIX_SID_SRV6_L3_SERVICE_SID_STRUCTURE
it is possible that the length read in the packet is insufficiently
large enough to read a BGP_PREFIX_SID_SRV6_L3_SERVICE_SID_STRUCTURE.
Let's ensure that it is.
Fixes: #10860
=> bgpd: Fix possible insufficient stream data

bgpd/bgp_nht.c, lib/zclient.c, lib/zclient.h, ospf6d/ospf6_zebra.c, pbrd/pbr_zebra.c, pimd/pim_nht.c, sharpd/sharp_zebra.c, staticd/static_nht.c, staticd/static_nht.h, staticd/static_zebra.c, zebra/zapi_msg.c, zebra/zebra_rnh.c, zebra/zebra_rnh.h, zebra/zebra_vty.c
This is a whole bunch of groundwork towards getting NHT on SAFI_MULTICAST (which is currently just straight up b0rked.)
The primary change here is a whole bunch of passing around SAFI values, mostly "short-circuited" out to SAFI_UNICAST. However, since I had to touch staticd's NHT hash, I ended up moving it over to use a typesafe hash.
=> zebra,staticd,*: SAFI_MULTICAST NHT groundwork

bgpd/bgp_route.c
When `all` is specified BGP pointer is always NULL, we need to iterate over
all instances separately.
```
BGP[170822]: Received signal 11 at 1648199394 (si_addr 0x30, PC 0x562e96597090); aborting...
BGP[170822]: /usr/local/lib/libfrr.so.0(zlog_backtrace_sigsafe+0x5e) [0x7f378a57ff6e]
BGP[170822]: /usr/local/lib/libfrr.so.0(zlog_signal+0xe6) [0x7f378a580146]
BGP[170822]: /usr/local/lib/libfrr.so.0(+0xcd4c2) [0x7f378a5aa4c2]
BGP[170822]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f378a33e140]
BGP[170822]: /usr/lib/frr/bgpd(bgp_afi_safi_peer_exists+0) [0x562e96597090]
BGP[170822]: /usr/lib/frr/bgpd(+0x15c3b8) [0x562e9654a3b8]
BGP[170822]: /usr/local/lib/libfrr.so.0(+0x75a9e) [0x7f378a552a9e]
BGP[170822]: /usr/local/lib/libfrr.so.0(cmd_execute_command+0x5d) [0x7f378a552e2d] …
```
=> bgpd: Fix crash for `show ip bgp vrf all all`

vtysh/extract.pl.in
Currently the PIM6d component is getting displayed under
"show ip prefix-list" instead of "show ipv6 prefix-list".
> frr(config)# do sh ip prefix-list 
> ZEBRA: ip prefix-list xyz: 1 entries
>    seq 5 permit any
> OSPF: ip prefix-list xyz: 1 entries
>    seq 5 permit any
> BGP: ip prefix-list xyz: 1 entries
>    seq 5 permit any
> PIM: ip prefix-list xyz: 1 entries
>    seq 5 permit any
> PIM6: ip prefix-list xyz: 1 entries
>    seq 5 permit any
> frr(config)#
> frr(config)# do sh ipv6 prefix-list detail 
> Prefix-list with the last deletion/insertion: abc
> ZEBRA: ipv6 prefix-list abc:
>    count: 1, range entries: 0, sequences: 5 - 5
>    seq 5 permit any (hit count: 0, refcount: 0)
> Prefix-list with the last deletion/insertion: abc
> OSPF6: ipv6 prefix-list abc:
>    count: 1, range …
=> pim6d: Correct the show ip prefix-list display for pim6d

ospf6d/ospf6_nssa.c, tests/topotests/ospf6_topo2/test_ospf6_topo2.py
With the current code, in a topology like this:
```
r1 ---- 0.0.0.0 ---- r2(ABR) ---- 1.1.1.1 -----r3(ASBR)
NSSA
```
where r3 is redistributing statics within the NSSA area, the ABR (r2) is translating type-7 lsa to type-5.
Everytime the function `ospf6_abr_nssa_task()` is executed all translated type-5 are aged out and refreshed for no reason. So for instance having 3 lsas already advertised:
```
r1# sh ipv6 os database
AS Scoped Link State Database
Type LSId           AdvRouter       Age   SeqNum                        Payload
ASE  0.0.0.1        2.2.2.2          39 80000001                     3:3::3/128
ASE  0.0.0.2        2.2.2.2          39 80000001                     4:4::4/128
ASE  0.0.0.3        2.2.2.2          39 80000001                     5:5::5/128
```
Adversting a new …
=> ospf6d: stop refreshing type-5 from NSSA

pimd/pim6_stubs.c, pimd/pim_assert.c, pimd/pim_bsm.c, pimd/pim_iface.c, pimd/pim_join.c, pimd/pim_msg.c, pimd/pim_msg.h, pimd/pim_pim.c, pimd/pim_register.c, pimd/subdir.am
Remaining bits necessary to get PIM packets sent out for IPv6. Manually tested & working.
NB: this PR is on top of PR #10677
=> pim6d: send IPv6 PIM packets

doc/user/basic.rst, lib/northbound.c, lib/northbound_cli.c, vtysh/vtysh.c
We found two problems while working with northbound command to show YANG operational data:
1. It was incorrectly showing configuration (`operational-data` is operation data only!). Not only it was showing configuration data, but it was also displaying invalid configuration.
2. It was incorrectly showing containers which were not created (e.g. presence containers that were never `NB_OP_CREATE`)
I also included a commit to add an option to `operational-data` so it can also display configured if wanted (although that was not the original intention). This is useful for debugging, however the same data could be easily acquired separatedly using gRPC or some other YANG front end.
=> lib: fix and improve yang operational data display

ospfd/ospf_lsa.c
Description:
Default route is not getting flushed from neighbours though originator
triggered flush and deleted LSA from its database. It become as stale
LSA in  neighbours databse forever. This could seen in the following
sequence of configurations with less than a second interval b/w configs.
And this could happen only when originator shouldnt have default route
in its rib so it originates default route only when configure with 'always'
option.
step-1:default-information originate always
step-2:no default-information originate always
step-3:default-information originate
In step-1, default route will be originated to AS.
In step-2, default route will be flushed to AS, but neighbours will be
discarding this update due to minlsainterval condition.
And it is expected that DUT need to keep …
=> ospfd: Default route becomes stale  route in nbrs even after flush from originator

isisd/isis_spf.c
Fixing the crash:
> #0  0x0000560aa80f8e30 in lspdb_const_find (h=<error reading variable: Cannot access memory at address 0x7fff5e95efe8>, item=<error reading variable: Cannot access memory at address 0x7fff5e95efe0>) at ./isisd/isis_lsp.h:64
> #1  0x0000560aa80f8e9d in lspdb_find (h=0x560aaa1ed3b8, item=0x7fff5e95f050) at ./isisd/isis_lsp.h:64
> #2  0x0000560aa80f92f9 in lsp_search (head=0x560aaa1ed3b8, id=0x7fff5e95f200 "") at isisd/isis_lsp.c:100
> #3  0x0000560aa8113d69 in spf_adj_list_parse_tlv (spftree=0x560aaa1f09d0, adj_list=0x560aaa214480, id=0x560aad331a78 "", desig_is_id=0x0, pseudo_metric=0, metric=3, oldmetric=false, subtlvs=0x0) at isisd/isis_spf.c:1330
> #4  0x0000560aa811419d in spf_adj_list_parse_lsp (spftree=0x560aaa1f09d0, adj_list=0x560aaa214480, lsp=0x560aaa1f4e50, …
=> isisd: fix infinite loop when parsing LSPs

bgpd/bgp_ecommunity.c, bgpd/bgp_evpn_vty.c
Small simplification for evpn RT commands, i.e. both per-VRF
and per-VNI - `bgp_evpn_vrf_rt_cmd` and `bgp_evpn_vni_rt_cmd`.
Just extract the duplicated code as a common code, there are
no functional changes.
Additionally correct one comment for `ecommunity_free()`.
=> bgpd: small simplification for evpn RT commands

bgpd/bgp_fsm.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgpd.c, bgpd/bgpd.h
Examples:
```
%ADJCHANGE: neighbor 192.168.0.1(exit1-debian-11) in vrf default Up
192.168.0.1(exit1-debian-11) graceful restart stalepath timer expired
192.168.0.1(exit1-debian-11) sending route-refresh (BoRR) for IPv4/unicast
192.168.0.1(exit1-debian-11) graceful restart timer started for 120 sec
192.168.0.1(exit1-debian-11) graceful restart stalepath timer started for 120 sec
192.168.0.1(exit1-debian-11) graceful restart timer stopped
%MAXPFXEXCEED: No. of IPv4 Unicast prefix received from 192.168.0.1(exit1-debian-11) 9 exceed, limit 1
```
=> bgpd: Print hostname along with IP for most useful debug messages

ospfd/ospf_zebra.c
That commit aim is to fix an invalid behavior when
default-information is activated on ospf router without always option.
Consider an ASBR with:
-one default route coming from ospf,
-and another default route coming from another deaemon (such BGP or static).
When the daemon bgp stops advertising its default route,
-ospf continues to advertise its previous default route (with aging 0),
-this may create default routing loops.
Expected behavior: is to update the removed external default route with
MAXAGING value.
Updating with MAXAGING value will notify the fact the route is currently
invalid. A later removal from ospf external LSA database will be made.
Analysis: all default routes have their type overwritten by a
DEFAULT_ROUTE type. Thus all default routes whatever its origin (ospf,
bgp, …
=> ospfd: fix ospf default route wrongly sent back

bgpd/bgp_vty.c, bgpd/bgp_vty.h, bgpd/bgpd.c, bgpd/bgpd.h
Closes https://github.com/FRRouting/frr/issues/10756
=> bgpd: Add BGP configuration start/end markers

doc/user/zebra.rst, zebra/zebra_srv6_vty.c
This patch series properly fix default value handling of the optional parameter "func-bits" related to SRv6, typo in doc, vty output.
=> zebra: fix doc and default value of "func-bits" for SRv6

m4/.gitignore
The file m4/ax_lua.m4 needs to be a part of distribution, but it is not
inluded in the git repository by default becuase .gitignore file has a
wildcard for all *.m4 files, while individual files that must _not_ be
ignored are listed one by one as exceptions. ax_lua.m4 needs to be added
to this list of exceptions too.
One failure scenario is when you put a snapshot of the source tree in a
new git repository (e.g. the one used for a local CI/CD), this file is
not included in the repository, and subsequently build fails.
This commit adds the exception into m4/.gitignore file
Signed-off-by: Eugene Crosser <crosser@average.org>
=> autoconf: do not .gitignore m4/ax_lua.m4

ospf6d/ospf6_asbr.c
ospf6_routemap_rule_match_interface uses route->ospf6 field for matching
so we must fill the field in our temporary variable.
Fixes #10911.
=> ospf6d: fix crash when applying a route-map on a temporary route

tools/frrcommon.sh.in
If a user enters:
/usr/lib/frr/frrinit.sh start
<modifies daemons file to remove a daemon from being used>
then calls:
/usr/lib/frr/frrinit.sh stop
The daemon(s) that are removed from the file are not stopped.
Apparently in shell scripting naming the variables the same
as the callee does not work as one would think.  Just renaming
the variable to something else solved the problem.
=> tools: Modify all_stop to actually try to stop all daemons

ospfd/ospf_vty.c
Before:
```
$ vtysh -c 'show ip ospf neighbor json' | jq '.neighbors."100.100.200.100"[0].nbrState'
"Full/DR"
$ vtysh -c 'show ip ospf neighbor detail json' | jq '.neighbors."100.100.200.100"[0].nbrState'
"Full"
```
After:
```
$ vtysh -c 'show ip ospf neighbor json' | jq '.neighbors."100.100.200.100"[0].nbrState'
"Full/DR"
$ vtysh -c 'show ip ospf neighbor detail json' | jq '.neighbors."100.100.200.100"[0].nbrState'
"Full/DR"
```
=> ospfd: Show neighbor state in full format (e.g. Full/DR instead of Full)

lib/routemap.h, lib/routemap_cli.c
Before:
```
route-map lua permit 10
exit
```
After:
```
route-map lua permit 10
match script rm
exit
```
=> bgpd: Show `match script SCRIPT` in running config

doc/developer/building-docker.rst, docker/ubi-8/Dockerfile, docker/ubi-8/build.sh, docker/ubi-8/docker-start
- Create frr docker container based in new Red Hat Universal Base
Images.
- This build a docker container based in ubi-8.
- Need to get the devel packages from centos-8 stream repos.
- Centos-8 stream repos added : base, appstream, powertools and epel
Signed-off-by: Javier Garcia <javier.martin.garcia@ibm.com>
=> docker: Adding support for ubi-8 images.

configure.ac
Without `-g` in LDFLAGS we won't get debug info even if it's enabled in CFLAGS.  Since we're controlling debug info through CFLAGS, there's no harm in always having `-g` in LDFLAGS.
---
Not sure how/when this got broken, but anyway this is the reason we're missing proper debug info in a whole bunch of backtraces / bug reports :disappointed:
=> build: stick `-g` into LDFLAGS

isisd/isis_nb_config.c, lib/link_state.c, lib/link_state.h, ospfd/ospf_te.c, pathd/path_ted.c
The commands:
router isis 1
mpls-te on
no mpls-te on
mpls-te on
no mpls-te on
!
Will crash
Valgrind gives us this:
==652336== Invalid read of size 8
==652336==    at 0x49AB25C: typed_rb_min (typerb.c:495)
==652336==    by 0x4943B54: vertices_const_first (link_state.h:424)
==652336==    by 0x493DCE4: vertices_first (link_state.h:424)
==652336==    by 0x493DADC: ls_ted_del_all (link_state.c:1010)
==652336==    by 0x47E77B: isis_instance_mpls_te_destroy (isis_nb_config.c:1871)
==652336==    by 0x495BE20: nb_callback_destroy (northbound.c:1131)
==652336==    by 0x495B5AC: nb_callback_configuration (northbound.c:1356)
==652336==    by 0x4958127: nb_transaction_process (northbound.c:1473)
==652336==    by 0x4958275: nb_candidate_commit_apply (northbound.c:906)
==652336==    by 0x49585B8: …
=> isisd, lib, ospfd, pathd: Null out free'd pointer

zebra/rtadv.c
It's confusing for a user to see 'Tx RA failed' in the logs when
they've enabled RAs (either through interface config or BGP unnumbered)
on an interface that can't send them.  Let's avoid sending RAs on
interfaces that are bridge_slaves or don't have a link-local address,
since they are the two of the most common reasons for RA Tx failures.
=> zebra: don't send RAs w/o LLv6 or on bridge-ports

doc/user/bgp.rst
Correct one word - `EAD-per-ES`, and remove one unuseful `index::` line.
=> doc: two minor changes for evpn-mh

tests/lib/test_grpc.py
it wants yang models installed which will only be there if frr has been
installed before, causing `make check` to fail when run on a system on
which frr has not been installed when GRPC is enabled (--enable-grpc)
=> tests: skip grpc test if frr not installed

pimd/pim_mroute.c, tests/topotests/lib/pim.py
When pimd has this setup:
src ----- rtr ------ receiver
|
rp
And the receiver sends a *,G join to rtr.  When the
src starts sending a S,G, rtr can wait up to one join/prune
interval before sending a S,G rpt prune.  This interval
causes the pimreg device to be in the S,G OIL as that the
RP does not know to prune this leg off.
before:
Timestamp: Thu Mar 31 10:15:18 2022 288767 usec
[MROUTE](10.103.0.5,239.0.0.4)           Iif: rtr-lan_src Oifs: rtr-lan  State: resolved Table: default
Timestamp: Thu Mar 31 10:15:18 2022 288777 usec
[MROUTE](10.103.0.5,239.0.0.4)           Iif: rtr-lan_src Oifs: rtr-lan rtr-lan-1  State: resolved Table: default
Timestamp: Thu Mar 31 10:15:18 2022 288789 usec
[MROUTE](10.103.0.5,239.0.0.4)           Iif: rtr-lan_src Oifs: pimreg rtr-lan rtr-lan-1  State: …
=> pimd: Send immediate join( with possible SG RPT prune bit set

bgpd/bgp_route.c
Flush dummy attr to release objects allocated by route-map.
Similar to #9620.
=> bgpd: Fix memory leak in subgroup_announce_check

pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_ifchannel.c, pimd/pim_igmp.c, pimd/pim_nb_config.c, pimd/pim_pim.c, pimd/pim_vty.c, pimd/pim_vxlan.c
The only function these macros have is to make the code confusing. "PIM_IF_DO_PIM" sounds like it triggers some action, but it doesn't.
Replace with "bool" fields in struct pim_interface.
(Note: PIM_IF_*_IGMP_LISTEN_ALLROUTERS was always set, without any way to unset it.  It is completely removed now and always enabled.)
---
this is a purely mechanical/cleanup change and should have zero functional impact
=> pimd: remove useless PIM_IF_* macros

bgpd/bgp_evpn_mh.c
"no ead-es-route-target export RT":
Since existance is already checked in `bgp_evpn_ead_es_rt_cmd`
with `bgp_evpn_rt_matches_existing()`, there MUST be a deleting
node in evpn's `bgp_mh_info->ead_es_export_rtl` list.
Just modify the check for deleting node to an `assert`.
=> bgpd : use "assert" for one check on evpn-mh

zebra/zebra_vxlan.c
The bounded vrf of `l2vni/zevpn` have wrong relation with the order
in which vxlan interface and svi interface are set.
If set vxlan interface with vlanid first, then set svi interface with
vrf, it is ok that vxlan interface will get correct `vrf` inherited
from svi. But reverse the set sequence (i.e. set svi first, then vxlan),
vxlan interface can't get correct `vrf`, becasue the handling of
`ZEBRA_VXLIF_VLAN_CHANGE` missed inheritting `vrf` by mistake.
```
host# do show  evpn vni 101
VNI: 101
Type: L2
Tenant VRF: vrf1
```
So update `vrf` ("Tenant VRF") of l2vni in `zebra_vxlan_if_update()`.
=> zebra: fix missing vrf change of l2vni on vxlan interface

pimd/pim_vxlan.c, pimd/pim_zebra.c, pimd/pim_zlookup.c
Fixing the below coverity issues.
________________________________________________________________________________________________________
*** CID 1515546:  Null pointer dereferences  (NULL_RETURNS)
/pimd/pim_zlookup.c: 391 in zclient_lookup_read_pipe()
CID 1515546:  Null pointer dereferences  (NULL_RETURNS)
Dereferencing a pointer that might be "NULL" "pim" when calling "zclient_lookup_nexthop_once".
391             zclient_lookup_nexthop_once(pim, nexthop_tab, 10, l);
________________________________________________________________________________________________________
*** CID 1515545:    (NULL_RETURNS)
/pimd/pim_vxlan.c: 902 in pim_vxlan_mlag_update()
CID 1515545:    (NULL_RETURNS)
Dereferencing a pointer that might be "NULL" "pim" when calling "pim_vxlan_set_peerlink_rif".
902 …
=> pimd: Fixing pim coverity issues

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_nb_config.c
Adding the Interface level config CLI for IPV6 MLD
[no] ipv6 mld query-max-response-time,
[no] ipv6 mld last-member-query-interval,
[no] ipv6 mld last-member-query-count,
[no] ipv6 mld watermark-warn
=> pim6d: Adding new MLD Config CLI

pimd/pim_oil.h
pim_channel_oil_change_iif is sitting idly in .h file with no
definition.
The definition was removed but this wasn't. Hence removing it.
=> pimd: Remove pim_channel_oil_change_iif from header file

bgpd/bgp_mplsvpn.c, bgpd/bgp_vty.c, bgpd/bgp_zebra.c
Since additional information such as block_bits_length is needed to generate SIDs properly, the type of elements in srv6_locator_chunks list is extended from `struct prefix_ipv6 *` to `struct srv6_locator_chunk *`. Even in terms of variable name, `struct srv6_locator_chunk *` is appropriate.
=> bgpd: refactor type of srv6_locator_chunks list

lib/prefix.h, pimd/pim_addr.h, pimd/pim_ssm.c
A little bit of cleanup and structure to get information about multicast addresses. Replaces the "is standard SSM" check in pimd. (The other two helpers for scope/nofwd are used in the MLD code.)
=> lib, pimd: small cleanup in multicast addr helpers (SSM & co.)

vtysh/vtysh.c
vtysh_client_execute() expects just a string without a newline; the newline is passed through and ends up in logging output where newlines are not quite wanted.
=> vtysh: remove extraneous newline

pimd/pim_cmd.c
```
frr(config-if)# ip igmp join 232.1.1.1 10.10.10.10
frr(config-if)# do sh ip igmp sources
Interface        Address         Group           Source          Timer Fwd Uptime
ens192           232.1.1.1       10.10.10.10     04:10   N 00:00:10
frr(config-if)#
```
The above output is misaligned and is having Address field which is not
required here.
Fixing it.
Output after fixing it:
```
frr# do sh ip igmp sources 
Interface        Group           Source          Timer Fwd Uptime  
ens192           232.1.1.1       10.10.10.10     03:38   N 00:19:49
frr# 
```
=> pimd: correct the show ip igmp sources output

bgpd/bgp_evpn_mh.c
Correct flag name of `attr.es_flags` - ATTR_ES_L3_NHG_USE.
"bgp_path_info"s (Per "es-vrf") with this flag can use l3nhg.
=> bgpd: correct one flag name on comment for evpn-mh

pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_igmp.c
I should've removed this in #10960.  It's a hazard in terms of forgetting to adjust PRs/other changes that might accidentally still reference the field.
---
Sorry about that :|
=> pimd: remove pim_interface->options

bgpd/bgp_updgrp_adv.c
Description:
Change is intended for fixing the below listed issue related to default-originate:
- When default route is originated using the neighbor default-originate cmd,
MED is not set as part of the update message attribute.
Please check the commit for more details.
Co-authored-by: Abhinay Ramesh <rabhinay@vmware.com>
=> bgpd: Metric not set with default route

bgpd/bgp_evpn_vty.c, bgpd/bgp_vty.c, zebra/zebra_evpn_mh.c
3 changes:
- zebra: adjust the warnings for ESI of evpn-mh
Since there are two kinds of ESI (Type-0 and Type-3),
the warnings should distinguish between the two cases.
- zebra: add whitespace after "%%" for prompt
- bgpd: add whitespace after "%%" for prompt
=> zebra: adjust the warnings for ESI of evpn-mh

bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_mh.h
Remove unnecessary `install_l3nhg` knob because it has already
been controlled by the command: "[no$no] use-es-l3nhg".
=> bgpd: remove unnecessary l3nhg knob for evpn-mh

bgpd/bgp_evpn_vty.c
Currently the warning is wrong:
```
root#show bgp vrf default vni
BGP instance for VRF default not foundACC1(config)#
```
Two changes for "show bgp vrf VRFNAME vni [json]":
- Correct the default VRF check
- Add newline for warning
=> bgpd: fix wrong check for default VRF

watchfrr/watchfrr.c
When watchfrr has noticed issues, send operational state
to systemd so operators issuing `systemd status frr` can
see a more nuanced state of the daemon
=> watchfrr: Send operational state to systemd

bgpd/bgp_evpn_mh.c
Two cosmetic change -
1) Remove unnecessary local variable - `es_vtep` used in one condition.
2) Remove unused variable - `es_cnt`. `proc_cnt` has already taken `es`
into account.
=> bgpd: cosmetic change for evpn-mh

bgpd/bgp_attr.c
Fixes https://github.com/FRRouting/frr/issues/11016
=> bgpd: Pass non-transitive ext-communities between Route Server and RS clients

isisd/isis_circuit.c, isisd/isis_nb_config.c
When lsp-mtu is configured larger than interface mtu and the interface
is brought up, the ISIS code would crash. When other vendors have this
misconfiguration they just continue ISIS running and allow the LSP
packets to be created but not sent. When the misconfiguration is corrected
the LSP packets start being sent. This change creates that same behavior
in FRR.
The startup issue I am hitting is when the isis lsp-mtu is larger that the interfaces mtu.  
We run into this case when we are in the process of changing the mtu on a tunnel.   
I issue a shutdown/no shutdown on the interface, because the tunnel MTU is smaller 
than the lsp-mtu, it is considered an error and calls circuit_if_del.  This deletes 
part of the circuit information, which includes the circuit->ip_addr list.  Later on we …
=> Fix crash in ISIS when mtu mismatch occurs

bgpd/bgp_evpn_mh.c
Fix NULL deference issue in log. And change one word - "vtep",
it should be with lowercase letters like other places.
=> bgpd: fix NULL deference in evpn-mh's log

watchfrr/watchfrr.c
To allow people to know the state of watchfrr from vtysh,
let's add a bit more data to the output.
=> watchfrr: Add some more information to `show watchfrr`

pimd/pim6_cmd.c, pimd/pim_cmd.c
Fix the below spelling
Rendevous --> Rendezvous.
Signed-off-by: Mobashshera Rasool
=> pimd, pim6d: Spelling fixes

bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_mh.h, zebra/zebra_evpn_mh.c
Two commits:
- zebra: simplify one check for evpn-mh
An simplification for one check in
`zebra_evpn_mh_uplink_oper_flags_update()`.
- bgpd: fix a few comments for evpn-mh
Just correct a few comments on Type-1 and Type-4 of evpn-mh.
=> zebra: simplify one check for evpn-mh

bgpd/bgp_attr.c
Backport b17d5444f46c55fb131de4e0ab260bb1bd7df93d to 8.2
=> bgpd: [8.2] Pass non-transitive ext-communities between Route Server and RS clients

bgpd/bgp_nht.c
In some stress testing, we are seeing type-5 evpn routes being
left in a rejected state in zebra.
Sequence of events as I am seeing it:
a) Interface comes up that type5 routes nexthop depends on
b) zebra processes creates the connected and lets bgp know via nht
c) bgp installs the route to zebra
d) zebra processes and sends install to kernel
e) before route is installed, the interface the nexthop points at flaps
f) the route install is rejected, notify zebra
g) the interface comes up
h) zebra gets the notification about the route install rejection
i) zebra processes the down/up and turns it into a single up event
j) BGP never reinstalls the type 5 route
This up event does not translate into a nexthop tracking event
when the events happen quickly enough and/or zebra is extremelyh
busy and …
=> bgpd: Allow type 5 routes to be handled better when link is flapping

ospf6d/ospf6_flood.c
A router has some static routes and redistributes turned on.
"clear ipv6 ospf process" command is applied. Then static routes
are deleted. In 1 in 5 runs, AS-External LSAs are not getting removed
from the neighbors even though it gets removed from its own LSDB.
Because of the clear process command, MAX_AGE LSAs are advertised and
fresh LSAs are installed in the LSDB. When the MAX_LSAs are advertised
back to the same router as part of the flooding process, it gets added
to the LSUpdate list even though it comes inside the MinLSArrival time.
When the static routes get deleted, it removed the LSA from the
LSRetrans list but not from LSUpdate list. The LSAs present in the
LSUpdate list gets advertised when sending LS Updates.
When an old copy of an LSA is more recent than the new LSA, check …
=> ospf6d: Check for MinLSInterval timer when adding to LSUpdate list

isisd/isis_adjacency.c
Add bfd information on show isis neighbor command.
=> isisd: add bfd information on isis neighbor show command

bgpd/bgp_mplsvpn.c
Until now, it has been hard-coded that the position at which the label
is inserted is from the 64th bits. Therefore, when the Locator prefix
was not /64, incorrect SIDs were generated. Also, SIDs are generated
in duplicate on Lines 604 & 613 in bgpd/bgp_mplsvpn.c.
In this patch, the position where the label is inserted is calculated
based on the sum of block_bits_length and node_bits_length (i.e., the
user-specified Locator prefix length). In addition, SID generation is
performed at one location in alloc_new_sid.
Signed-off-by: Nobuhiro MIKI <nmiki@yahoo-corp.jp>
=> bgpd: take SRv6 locator's prefix length into account when generating SIDs

tools/frrinit.sh.in
```
root@spine1-debian-11:~/frr# /usr/lib/frr/frrinit.sh
Usage:
/usr/lib/frr/frrinit.sh (start|stop|restart|force-reload|reload|status)
```
Closes https://github.com/FRRouting/frr/issues/11034
=> tools: Print usage for frrinit.sh when running without arguments

zebra/connected.c
If you are in a situation where you have multiple addresses on an
interface, zebra creates one connected route for them.
The issue is that the rib entry is not created if addresses were
added before the interface was running.
We add the address to a running interface in a typical flow.
Therefore, we handle the route & rib creation within a single ADD event.
In the opposite case, we create the route entries without activating them.
These are considered to be active since ZEBRA_IFC_DOWN is not set.
On the following interface UP, we ignore the same ADDR_ADD as it overlaps
with the already `active` prefixes -> rib is never created.
The minimal reproducible setup:
-----------------------------------------
ip link add name dummy0 type dummy
ip addr flush dev dummy0
ip link set dummy0 down
ip …
=> zebra: set ZEBRA_IFC_DOWN on connected routes for inactive interfaces

vtysh/vtysh.c
A safety check we flushed the data to the storage.
Fixes https://github.com/FRRouting/frr/issues/10234
=> vtysh: Call fflush+fsync before calling fclose() when saving the config

zebra/zebra_nhg.c
Currently if a end user has something like this:
Routing entry for 192.168.212.1/32
Known via "kernel", distance 0, metric 100, best
Last update 00:07:50 ago
* directly connected, ens5
T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
f - OpenFabric,
K>* 0.0.0.0/0 [0/100] via 192.168.212.1, ens5, src 192.168.212.19, 00:00:15
C>* 192.168.212.0/27 is directly connected, ens5, 00:07:50
K>* 192.168.212.1/32 [0/100] is directly connected, ens5, 00:07:50
And FRR does a link flap, it refigures the route and rejects the default
route:
2022/04/09 16:38:20 ZEBRA: [NZNZ4-7P54Y] …
=> zebra: [8.2] Allow system routes to recurse through themselves

zebra/zebra_evpn_mh.h
There are some duplicated `extern`s in this header
file, just remove them.
=> zebra: cleanup duplicated "extern"s for evpn-mh

pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_ifchannel.c, pimd/pim_mroute.c, pimd/pim_oil.h, pimd/pim_tib.c, pimd/pim_upstream.c, pimd/pim_zebra.c
Modified marco name so that it can be reused in mld.
=> pimd: Changing PIM_OIF_FLAG_PROTO_IGMP to PIM_OIF_FLAG_PROTO_GM

debian/frr.logrotate, debian/frr.postinst, redhat/frr.spec.in, tools/frr-reload.py
At the moment we set /var/log/frr permissions to 0750 (frr:frr), but the log
file is 0640 (root:adm) and that doesn't allow adm group to even open the
directory.
Also, when we do "log file /var/log/frr/something", permissions are set to
0640 (frr:frr), but when the logrotate kicks in, we have 0640 (frr:frrvty).
I believe we should have consistent permissions.
Related: https://github.com/FRRouting/frr/issues/10520
Any objections?
=> packaging: A couple of fixes for /var/log/frr

bgpd/bgp_community_alias.c, configure.ac, doc/developer/workflow.rst, isisd/isis_tlvs.c, lib/base64.c, lib/command_py.c, lib/elf_py.c, nhrpd/linux.c, pathd/path_ted.c, zebra/zebra_script.c
This eases incorporating fields from/"subclassing" another struct.
=> build: enable `-fms-extensions`

pimd/pim_assert.c, pimd/pim_upstream.c
This PR addresses two problems in PIM Assert processing
Problem:
PIM assert message is not triggered even after receiving WRONGVIF notification because of Could_assert flag not set. Refer RFC section 4.6.1 of 7761. Only if PIM Assert messages are trigerred, the routers can sense that more than one upstream routers has valid forwarding state and the downstream routers would prune a duplicate path. Even if you receive a WRONGVIF notification, CouldAssert should be true for a router to trigger PIM Assert messages. 
CouldAssert(S,G,I) =
SPTbit(S,G)==TRUE
AND (RPF_interface(S) != I)
AND (I in ( ( joins(*,G) (-) prunes(S,G,rpt) )
(+) ( pim_include(*,G) (-) pim_exclude(S,G) )
(-) lost_assert(*,G)
(+) joins(S,G) (+) pim_include(S,G) ) )
According to the above formula for Could assert, once SPTbit …
=> pimd: assert fixes

lib/plist.c
Recent commit e92508a741e03b8721ccb3424cbebe4d5476e9d changed
the prefix_master->str to a RB tree.  This introduced a condition
whnere on shutdown the prefix list was removed from the master list
and then operated on by passing around a name.  Which was then used
to lookup the prefix list again when we operated on the code.
This change to a RB Tree first deleted the item from the RB tree
first thus introducing this crash
Crash:
(gdb) bt
index=0x556c07d59650, pentry=0x556c07d29380) at lib/routemap.c:2397
arg=0x7ffdbf84bc60) at lib/hash.c:267
event=RMAP_EVENT_PLIST_DELETED) at lib/routemap.c:2489
Grab the first item on the list, clean it and then remove it.
=> lib: Prevent crash after shutdown request

zebra/if_netlink.c, zebra/rt_netlink.c, zebra/rule_netlink.c, zebra/subdir.am, zebra/zebra_trace.c, zebra/zebra_trace.h
Add a series of tracepoints for zebra so that we can gather data about netlink read events from the kernel.  At this point I've instrumented the basic startup netlink functionality so we can see how long it is taking zebra to get up and running with various startup conditions.
=> Zebra trace

isisd/isis_dr.c
debug isis events will also be used to not display isis_dr_resign()
event trace.
=> isisd: isis_dr_resign() trace braced with debug isis events

isisd/isisd.c
In addition to turning on isis bfd debugging traces, the internal
bfd messaging debug is also enabled. Reversely, when isis bfd traces
are off, the internal messaging debug traces are off too.
=> isisd: enable BFD messaging debug when isis bfd is used

tools/frrinit.sh.in
```
root@spine1-debian-11:~/frr# /usr/lib/frr/frrinit.sh
Usage:
/usr/lib/frr/frrinit.sh <start|stop|restart|force-reload|reload|status> [namespace]
/usr/lib/frr/frrinit.sh stop namespace1
```
=> tools: Improve usage example for frrinit.sh

pimd/pim_igmpv3.c
https://github.com/FRRouting/frr/pull/9489/commits/5421bf8f1d5e9f5a6fd8025b0af46503a35ec3bf commit forgot to set the parameter "new" to true when a new source is created, have fixed it.
igmp_get_source_by_addr api is currently setting the parameter
"new" to false always. This is not right. The caller apis are using this field to decide and based on that take actions to create timers, etc.
Its need to be set to true when a new source is created.
=> pimd: Set new to true in igmp_get_source_by_addr api

tools/frrcommon.sh.in
watchfrr and staticd do not require <1024 ports to be running, thus they can
start, but others fail.
We should allow only users with EUID=0 (sudo or root) running frrinit.sh.
Closes https://github.com/FRRouting/frr/issues/11035
=> tools: Allow running frrinit.sh only for EUID=0

lib/command.c
End operator is showing:
!
frr version 8.0.1
hostname test.example.com
domainname
domainname should not be printed in this case at all.  I do not
see any mechanism in current code that this could happen, but
what do I know?  Put some extra stupid insurance in place
to prevent bad config from being generated.
=> lib: Ensure an empty string does not get printed for host/domain

tools/frr-reload.py
1) tools: frr-reload fix bgp nbr delete
When a bgp neighbor removed from associated to peer-group,
the neighbor is fully deleted, subsequent deletion of any
configuration related to the neighbor leads to failure
in frr-reload.
Fix: In frr-reload lines to delete check if any neighbor with
peer-group removal line is present, if so then remove any
further config deletion associated the neighbor needs to removed
from the lines to delete.
Testing Done:
**BEFORE FIX:**
-----------
```
2022-04-08 20:03:32,734  INFO: Executed "router bgp 4200000005  no neighbor swp5 interface peer-group UNDERLAY"
2022-04-08 20:03:32,892  INFO: Failed to execute router bgp 4200000005  no neighbor swp5 password SSSS
2022-04-08 20:03:33,050  INFO: Failed to execute router bgp 4200000005  no neighbor swp5 password …
```
=> tools: frr-reload fix bgp neighbor and bgp instance deletion 

bgpd/bgp_mplsvpn.c
Prior to this fix, the magic number (16) was used regardless of what value
the user specified for func-bits. With this fix, user-specified values are
handled appropriately.
Signed-off-by: Nobuhiro MIKI <nmiki@yahoo-corp.jp>
=> bgpd: take SRv6 func-bits into account when generating SIDs

sharpd/sharp_vty.c
Some recent improvement in GCC triggers 2 new warnings, and they're actual bugs (reading beyond end of prefix_ipv6 by accessing it as prefix, which is larger.)  Luckily it's only in sharpd.
=> build: fix new gcc 11.2 warnings

isisd/isis_lfa.c
That commit aim is to fix an invalid isis access to sptree when
lpd is stopping. isisd is running.
lpd and isisd are running. isis is L1 type configured.
isis_ldp_rlfa_handle_client_close function try to clear
uninitialized spftree.
Expected behavior: isisd not crashing and running.
isis_ldp_rlfa_handle_client_close not trying to clear spftree
that are not initializes due tio the configuration.
Fix: test the configured area's type avoiding to deleted
an unconfigured sptree. function isis_rlfa_handle_client_close
will be aligned on spftree_area_del function
=> isisd: ldp cleaning issue on invalid sptree

bfdd/ptm_adapter.c
With the simple BFD configuration -
(active mode, single hop, without other parameters)
```
!
bfd
peer 11.11.11.11
exit
!
```
The interface with 11.11.11.0/24 is a *virtual* interface,
which can be deleted.
After BFD FSM is created and session is ok, do these things:
1) delete this interface
2) create this interface
3) set same ip address in this interface
Now, everything seems completely restored because all configuration
is same. But bad thing happens, BFD session hang on "down" status -
```
root# show bfd peer 11.11.11.11
BFD Peer:
peer 11.11.11.11 vrf default
ID: 638815827
Remote ID: 0
Active mode
Status: down
Downtime: 3 second(s)
Diagnostics: path down <- caused by destroyed interface
Remote diagnostics: ok
```
With the interface creating, `bfdd_sessions_enable_interface()`
wrongly …
=> bfdd: fix broken FSM in active mode

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.h
Modifying the "mld_group_watermark_cmd" to "ipv6_mld_group_watermark_cmd"
and "igmp_group_watermark_cmd" to "ip_igmp_group_watermark_cmd" for consistency.
and also Removing the duplicate PIM_DECLVAR_CONTEXT macro.
Signed-off-by: Sai Gomathi N <nsaigomathi@vmware.com>
=> pim6d: Modifying the mld group watermark command name

pimd/pim_cmd.c, pimd/pim_vty.c, pimd/pimd.h
The logic for enabling `detailed` versions was supposed to implicitly enable the "normal" debugs, but it got SNAFUd to be the other way around, "normal" enabling `detailed` instead.
Also `debug igmp trace detail` was straight up missing, i.e. no way to set `PIM_DEBUG_IGMP_TRACE_DETAIL`. (And the flag is used in 3 places.)
=> pimd: fix SNAFUs in debug flags

lib/prefix.h, staticd/static_routes.c, staticd/static_zebra.c, staticd/static_zebra.h
- first, a little bit of cleanup
- then combine `update` and `register` functions since they're used in functionally common places anyway
- retry NHT registration if it failed previously
- and fix/initialize NHT for `VRF_DEFAULT` when zebra connection is established
Free bonus content: `prefix_afi()` in lib/prefix.h, shorthand to get `struct prefix *` → `afi_t`
=> staticd: reorg, refactor and improve NHT code

vrrpd/vrrp_vty.c
VRRP as per RFC 5798 'Master Advertisement interval' field refers to the
advertisement interval, we received the last time we got an Advertisement
from a peer who wasn't us, who was in the master state.
This could be clarified by making the field name 'Master Advertisement
interval (rx)',and when we're in the Master state, we put (stale) after the interval.
Signed-off-by: Rajesh Varatharaj <rvaratharaj@nvidia.com>
=> vrrpd: Fix display of 'Master Advertisement interval'

lib/filter_cli.c
If duplicate value is entered, the whole plist/alist just dropped.
Before:
```
$ grep prefix-list /etc/frr/frr.conf
ip prefix-list test seq 5 permit 1.1.1.1/32
ip prefix-list test seq 10 permit 1.1.1.1/32
$ systemctl restart frr
$ vtysh -c 'show run | include prefix-list'
$
```
After:
```
$ grep prefix-list /etc/frr/frr.conf
ip prefix-list test seq 5 permit 1.1.1.1/32
ip prefix-list test seq 10 permit 1.1.1.1/32
$ systemctl restart frr
$ vtysh -c 'show run | include prefix-list'
ip prefix-list test seq 5 permit 1.1.1.1/32
```
Closes https://github.com/FRRouting/frr/issues/11084
=> lib: Ignore duplicate alist/plist entries in CLI

lib/strformat.c
Passing NULL for a `%pTVMs` would result in `(null)Ms`, i.e. the `Ms` flags not eaten up.  Change to eat those up, and print `-` instead for NULL times.
=> lib: format NULL timevals correctly

tests/topotests/lib/pim.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_bsm_topo2/test_mcast_pim_bsmp_02.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_ospf_topo2.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_static_routes_topo1.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_transit_router_topo3.py, tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py, tests/topotests/multicast_pim_sm_topo2/test_multicast_pim_sm_topo2.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo3.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pim_static_rp.py
1. Modified pim APIs name to generic one, same APIs would be used for PIMv4 and PIMv6
verifications
2. Modified all affacted scripts and ran multiple times locally to avoid CI failures
=> tests: [PIMv6] Using generic names for PIM verification APIs

bgpd/bgp_rd.c
`stream_new` in  `str2prefix_rd()` should be called after all
checkings are passed, so the last `if (s)` in this fuction will
make sense.  Additionally remove unnecessary `lret` variable.
=> bgpd: delay "stream_new" in str2prefix_rd()

pimd/pim6_mroute_msg.c, pimd/pim_mroute.c
The ICMP6_FILTER option is always checked by the kernel, so the cost is taken whether or not anything is set there.  Use it instead of taking on additional cost with a BPF program.
---
Also adds a comment to explanation what's going on.
=> pim6d: use ICMP6_FILTER instead of BPF on mroute

tests/lib/test_timer_correctness.c
Someone decided to do malloc testing over make check.
Fixes: #11120
=> tests: Use XCALLOC instead of XMALLOC for threads

bfdd/bfd.h, bfdd/bfd_packet.c, bfdd/bfdd_vty.c
Single-hop bfd configuration:
```
!
bfd
peer 11.11.11.11
exit
!
```
After single-hop bfd session is ok with `up` status,
change(remove, then add different/new *ip* with same
subnet) address on local interface, of course meanwhile
change remote machine's bfd peer ip to this new *ip*.
At this time this bfd session including rnd/rcv
packets and status is completely ok, but the command of
`show bfd peers brief` can't display correct local address,
which should be the new *ip*, but it wrongly displays
last used local address.
Currently single-hop `bs->local_address` is set by using
received packet's destination instead of using `getsockname()`
in `bfd_session_enable()`.
Since set `bfd->local_address.sa_sin.sin_family` to
`AF_UNSPEC` when removing ip address need tranverse many
failed session …
=> bfdd: fix wrong local address of display command

pimd/pim_cmd.c
registerTx printing wrong value in show interface traffic json command
=> pimd: fixing wrong diplay registerTx

babeld/babeld.c, bfdd/bfd.h, bgpd/bgpd.h, ldpd/ldpd.h, lib/if.h, lib/zclient.c, lib/zclient.h, pbrd/pbr_map.c, zebra/zapi_msg.c, zebra/zebra_pw.h
Changes:
- Adjust the FRR interface maximum name length to OS maximum (see `lib/if.h`)
- Use FRR definition to declare all interface name buffers
- Fix some `strncmp` wrong usages
> **NOTE** there is one usage of `IF_NAMESIZE` left in `pimd/mtracebis.c` which was left unchanged on purpose. That file doesn't include any FRR header file.
This PR is a successor for #6840 , but simpler: it only fixes definition usage.
=> *: standardize interface name maximum length

bgpd/bgp_packet.c
Initialize outer/inner bgp_notify structs to zero.
Free bgp_notify.raw_data after use.
=> bgpd: Fix memory leak for bgp_notify_receive()

bgpd/bgp_vty.c, bgpd/bgpd.c
When using `bgp capability extended-nexthop` under peer groups and interface based peering FRR is doing the wrong thing.  This is a variety of fixes to make the behavior better.  See individual commits
=> Bgp capability

bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_mh.h
The "add" parameter of `bgp_evpn_mh_route_update()` makes no sense.
Just remove it to clarify this function, and remove the relevant check
with "add" as well.
=> bgpd: remove one unnecessary parameter for evpn-mh

bgpd/bgp_evpn.c, bgpd/bgp_evpn_vty.c
When `bgp_evpn_new()` is called, the `bgp` parameter MUST be non-NULL,
remove this unnecessary check and remove the NULL check for returned
`struct bgpevpn *`, which should be non-NULL.
And also remove unnecessary check for `import_rt_new()` in the same way.
=> bgpd: remove unnecessary check for evpn

ospf6d/ospf6_auth_trailer.c, zebra/table_manager.c
=> zebra, ospf6d: Do not check if NULL for XCALLOC()

bgpd/bgpd.h
We will hit this soon because uint32_t will be not enough.
Two more flags gonna be added for rfc8538.
=> bgpd: Use uint64_t for bgp->flags

bfdd/bfd_packet.c
After two single-hop sessions (*no local address are configured*) on two
interfaces are UP, remove one address of one interface, both of them
(actually, quite independent sessions) come to be DOWN, not just one.
Consider two boxes: A with `a1` and `a2` adddress on two interfaces,
and B with `b1` and `b2`.
Two sessions are set up and ok: `s1` with <a1,b1> and `s2` with <a2,b2>.
After `a1` of A is removed, there is an unhappy coincidence:
1) On A: `s1` changes local address, and sends <a2,b1> packets with help
of route.
2) On B: correctly dropped <a2,b1> packets.
3) On A: `s1` sends <a2,b1> packets with zero remote descriminator to
initialize this session.
4) On B: wrongly regarded <a2,b1> packets with zero remote descriminator
as part of `s2`. Then `s2` will vibrate.
So the good sessions …
=> bfdd: fix override between sessions

bgpd/bgp_open.c, bgpd/bgp_vty.c, bgpd/bgpd.h, doc/user/bgp.rst
N-bit flag should be exchanged in BGP OPEN messages, not only when the
bgpd is restarted/started.
=> bgpd: Add CLI knob to enable graceful restart for BGP notifications

bgpd/bgp_packet.c, bgpd/bgp_packet.h, bgpd/bgp_vty.c, bgpd/bgpd.h, doc/user/bgp.rst
`clear bgp neighbor` should send Hard Reset and graceful restart should be
activated. Let's make this adjustable.
https://datatracker.ietf.org/doc/html/rfc8538#section-5.1
+-------+------------------------------------+----------------------+
| Value |                Name                |  Suggested Behavior  |
+-------+------------------------------------+----------------------+
|   1   | Maximum Number of Prefixes Reached |      Hard Reset      |
|   2   |      Administrative Shutdown       |      Hard Reset      |
|   3   |         Peer De-configured         |      Hard Reset      |
|   4   |        Administrative Reset        | Provide user control |
|   5   |        Connection Rejected         |    Graceful Cease    |
|   6   |     Other Configuration Change     |    Graceful Cease …
=> bgpd: Send Hard Reset Notification for BGP_NOTIFY_CEASE_ADMIN_RESET

zebra/interface.c
RFC 7471 Section 4.2.7:
It is possible for min delay and max delay to be the same value.
Prior to this change, the code required min < avg < max. This change allows min == avg and avg == max.
test case:
interface eth-rt1
link-params
delay 8000 min 8000 max 8000
Signed-off-by: G. Paul Ziemba <paulz@labn.net>
=> zebra bugfix interface link-param: allow delay min <= avg <= max (was: min<avg<max)

bgpd/bgp_evpn_private.h
In current code, `build_evpn_type2_prefix()` doesn't distinguish ARP
or not according to the `ip` parameter. The `ip` parameter from caller
is always non-NULL.
Be consistent and not confused, just remove the unnecessary check.
=> bgpd: remove unncessary check for evpn

bgpd/bgp_advertise.h, bgpd/bgp_aspath.h, bgpd/bgp_attr.h, bgpd/bgp_clist.h, bgpd/bgp_community.h, bgpd/bgp_damp.h, bgpd/bgp_debug.h, bgpd/bgp_dump.h, bgpd/bgp_mpath.c, bgpd/bgp_mpath.h, bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/bgp_zebra.h, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst
a) Fix #11178 to no longer crash.  There was a conscious decision to not properly handle the non - standard safi's in cleanup or install when this command is issued.  Note this in the documentation
b) Change a uint16_t bit field to a bool since we only had 1 flag
c) A bunch of header cleanup in bgp
=> Fix #11178 and various other cleanup

ospf6d/ospf6_gr_helper.c
ospf6d: suppress coverity warnings of insecure data handling
=> ospf6d: suppress coverity warnings of insecure data handling

bgpd/bgpd.c, doc/user/bgp.rst
The `bgp no-rib` command cycles through all the bgp rib tables
and removes them from zebra.  Modify the code so that FRR notices
that it is attempting to cycle through the safi's that are two level
tables.  In addition these safi's cannot just blindly remove the routes
from the rib as that there are none explicitly.
This code just prevents the crash in bgpd.  It does not properly cycle
through and remove the zebra changes made that are explicit to these afi's.
This should be handled as appropriate by the developers on these safi's when
it becomes important to them.
Fixes: #11178
=> bgpd: [8.2] Prevent crash when issuing various forms of `bgp no-rib`

doc/user/pim.rst, doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_assert.c, pimd/pim_bsm.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_hello.c, pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_join.c, pimd/pim_nb.c, pimd/pim_nb.h, pimd/pim_nb_config.c, pimd/pim_pim.c, pimd/pim_pim.h, pimd/pim_register.c, pimd/pim_vty.c, tests/topotests/lib/pim.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo3.py, yang/frr-pim.yang
Added a new cli command "ip[v6] pim passive" in the interface context,
to disable sending of pim control packets on the interface.
Issue: #5403
=> pimd: introduce ip pim passive command

bgpd/bgp_evpn_vty.c
*** CID 1517751:  Uninitialized variables  (UNINIT)
/bgpd/bgp_evpn_vty.c: 1648 in show_ip_bgp_l2vpn_evpn_rd_neighbor_routes()
1642
1643
1644            if (rd_all)
1645                    return bgp_show_ethernet_vpn(vty, NULL, bgp_show_type_neighbor,
1646                                                 peer, SHOW_DISPLAY_STANDARD, uj);
1647            else
>>>     CID 1517751:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized element of array "prd.val" when calling "bgp_show_ethernet_vpn".
1648                    return bgp_show_ethernet_vpn(vty, &prd, bgp_show_type_neighbor,
1649                                                 peer, SHOW_DISPLAY_STANDARD, uj);
1650     }
1651
1652     DEFUN(show_ip_bgp_l2vpn_evpn_neighbor_advertised_routes,
1653 …
=> bgpd: Initialize prd for show_ip_bgp_l2vpn_evpn_rd_neighbor_routes()

zebra/rt_netlink.c, zebra/zebra_evpn.c, zebra/zebra_evpn_mac.c, zebra/zebra_evpn_mh.c, zebra/zebra_evpn_neigh.c, zebra/zebra_nb_config.c, zebra/zebra_vxlan.c, zebra/zebra_vxlan.h
The global vrf in zebra is always non-NULL. In general, it is bound to
default vrf by `zebra_vrf_init()`, at other times bound to some specific
vrf. Anyway, non-NULL.
So remove all redundant checkings for the returned value of
`zebra_vrf_get_evpn()`.
Additionally, remove the unnecessary check for `zvrf` in
`zebra_vxlan_cleanup_tables()`.
=> zebra: remove unnecessary check for "zevpn_vrf"

bgpd/bgp_rpki.c
Fix the no forms of some rpki commands to take variable
values on the no form.  So that people cut-n-pasting while
adding a no works.
=> bgpd: Fix no form of rpki commands to take values

bgpd/bgp_bmp.c
description:
BMP Per Peer Headers of Route Monitoring messages with UPDATE and
WITHDRAW notificatiosn ( not the sync ones at Initiation) are
all typed as POST POLICY.
fix:
notify Pre policy UPDATES AND WITHDRAWS with  Per Peer Header type set
to PRE POLICY (0)
=> BMP fix invalid bmp POST POLICY flag

zebra/debug_nl.c
Add the ability to give data about the nexthop group type
and encap type so that it is human readable.
=> zebra: Add encap and group type decoding to nexthop dump

bgpd/bgp_network.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst
Allow BGP to control the TOS DSCP value in the tcp header
via a new command at the bgp global level `bgp session-dscp <0-63>`
Signed-off-by: Pavel Shirhov <pavelsh@microsoft.com>
=> bgpd: Allow bgp to control the DSCP session TOS value

ospf6d/ospf6_interface.c, ospf6d/ospf6_message.c
When running `show ipv6 ospf6 interface` the hello timer period
is shown, but there is no indication on how much time is left
on the timer.  Add a clue:
sharpd@eva ~/frr5 (master)> vtysh -c "show ipv6 ospf6 int"
enp39s0 is up, type BROADCAST
Interface ID: 2
Internet Address:
inet : 192.168.119.224/24
inet6: 2603:6080:602:509e:9a14:998:b154:9e9/64
Instance ID 0, Interface MTU 1500 (autodetect: 1500)
MTU mismatch detection: enabled
Area ID 0.0.0.0, Cost 1000
State DR, Transmit Delay 1 sec, Priority 1
Timer intervals configured:
Hello 10(2.652), Dead 40, Retransmit 5
DR: 192.168.122.1 BDR: 0.0.0.0
Number of I/F scoped LSAs is 1
0 Pending LSAs for LSUpdate in Time 00:00:00 [thread off]
0 Pending LSAs for LSAck in Time 00:00:00 [thread off]
Authentication Trailer is disabled
Signed-off-by: …
=> ospf6d: Give time left in hello timer for `show ipv6 ospf6 int`

zebra/main.c, zebra/zebra_vty.c
Add startup message and display netlink buffer size.
Signed-off-by: Loganaden Velvindron <logan@cyberstorm.mu>
=> zebra: Add startup message and display netlink buffer size.

bgpd/bgp_route.c
in bgp_nlri_parse_ip there is a `sanity` check to ensure
that the prefix length as specified by the packet
will fit inside of a `struct prefix` correctly.  The problem
here of course is that this is only v4 / v6 unicast/multicast
parsing and the bytes will never be more than 16, but we are copying
into a part of the struct prefix that is only 16 bytes, but with
this check the length may be up to 47 bytes( but not really possible ).
Limit the size check to at most 16 bytes (since we are only handling
v4 or v6 addresses here )
=> bgpd: Fix coverity SA issue with copying over prefix data

zebra/debug_nl.c, zebra/kernel_netlink.c, zebra/kernel_netlink.h
This parser utility functions are used to send nexthop-group update payload via netlink message.
=> zebra: new netlink parse utility for rta used to send nhg msg

doc/user/isisd.rst
The node keyword does not take 's' at the end.
=> doc: use real wording for the show isis segment-routing node command

tests/topotests/lib/pim.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_ospf_topo2.py
This test is failing intermittently because sometimes igmp
local join is not getting deleted. I did following changes:
1. I did split the joins means trying to delete igmp local joins 
one by one. 
2. Running join delete command only, previously it was run 
along with ip igmp and ip igmp version 2 command.
I tried running tests multiple times and it seems to be working fine with
current changes.
There was an issue found during debugging this test failure,
issue was raised already:
Issue# https://github.com/FRRouting/frr/issues/11105
=> tests: Fix for test_pim_dr_nondr_with_ospf_topo2 test failure

bgpd/bgp_fsm.c, bgpd/bgp_packet.c, bgpd/bgp_packet.h, doc/user/overview.rst
If we receive CEASE Notification or HOLDTIME notification, retain STALE
routes if it's not a CEASE/Hard Reset.
When doing `clear ip bgp PEER`, we can control if this would be CEASE/Hard Reset
or not by using `bgp hard-administrative-reset` knob.
When `bgp graceful-restart notification` is disabled, STALE routes won't be
retained when receiving Notification message.
Co-authored-by: Biswajit Sadhu <biswajit.sadhu@gmail.com>
=> bgpd: Activate Graceful-Restart when receiving CEASE/HOLDTIME notifications

zebra/zebra_vxlan.c
All `vtep`s in dplane should be deleted/uninstalled during vni transition.
=> zebra: fix missing delete vtep during vni transition

bgpd/bgp_errors.c, bgpd/bgp_errors.h, bgpd/bgp_io.c, bgpd/bgp_packet.c, bgpd/bgpd.h
As described by https://www.ietf.org/archive/id/draft-spaghetti-idr-bgp-sendholdtimer-04.html
Since this replicates the HoldTime check on the receiver that is already part of the protocol, I do not believe it necessary to wait for IETF progress on this draft.  It's just replicating an existing element of the protocol at the other side of the session.
---
This supersedes #8530 (it's also the "alternate suggestion" mentioned in https://github.com/FRRouting/frr/pull/8530#issuecomment-824674419)
=> bgpd: implement SendHoldTimer

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Adding the following debug clis for pimv6
[no] debug pimv6
[no] debug pimv6 nht
[no] debug pimv6 nht detail
[no] debug pimv6 events
[no] debug pimv6 packets
[no] debug_pimv6_packetdump_send_cmd
[no] debug_pimv6_packetdump_recv_cmd
[no] debug pimv6 trace
[no] debug pimv6 trace detail
[no] debug pimv6 zebra
=> pim6d: Adding new Debug CLI for pimv6

lib/thread.c, lib/thread.h, ospf6d/ospf6_asbr.c, ospf6d/ospf6_gr.c, ospf6d/ospf6_gr_helper.c, ospf6d/ospf6_interface.c, ospf6d/ospf6_message.c, ospf6d/ospf6_neighbor.c, ospf6d/ospf6_nssa.c, ospf6d/ospf6_spf.c, ospf6d/ospf6_top.c
a) use thread_is_scheduled(), don't set pointer to null in a thread function, trust THREAD_OFF to do the right thing
b) is_default_prefix covers everything already no need to do it again
=> Ospfv3 shenanigans

tests/topotests/bfd_topo1/test_bfd_topo1.py, tests/topotests/bfd_topo2/test_bfd_topo2.py, tests/topotests/lib/common_config.py
Lots of tests call verify_rib that takes a list of routes that
need to be verified in some fashion.  This verify_rib functionality
will try up to 12 seconds before failing the check that zebra
has the route and has installed it.
Unfortunately the verify_rib code was not looking to see if
the route was queued for installation and was then allowing
tests to immediately do subsuquent steps that depended on
that route actually being installed sometimes causing tests
to fail.
Write a bit of additional code that looks at the queued
status and allows the test to wait a bit longer for zebra
to finish processing before allowing the test to move on
to the next bit.
=> tests: Ensure routes are not queued when calling verify_rib

zebra/interface.c, zebra/interface.h, zebra/main.c, zebra/rib.h, zebra/rtadv.c, zebra/rtadv.h, zebra/zebra_l2.h, zebra/zebra_opaque.c, zebra/zebra_vrf.c, zebra/zebra_vrf.h, zebra/zserv.h
Move a few things into places they actually belong, and reduce the number of places we have `#ifdev HAVE_RTADV`.  Just overall code prettification.
... I had actually done this quite a while ago while doing some other random hacking and thought it more useful to not be sitting on it on my disk...
=> zebra: clean up rtadv integration

doc/user/overview.rst
=> doc: Fix FRR/Slack keyword links in overview section

zebra/zebra_evpn_mh.c
Currently, `zif->es_info.esi` is always set even for a few unnecessary
cases in `zebra_evpn_local_es_update()`.
Delay setting `zif->es_info.esi` and remove the annoying rollback
(i.e. unset `zif->es_info.esi`) operation on failure case.
=> zebra: delay setting esi in zebra_evpn_local_es_update()

bgpd/bgp_packet.c
Before:
```
$ vtysh -c 'clear ip bgp 192.168.10.17'
$ vtysh -c 'show bgp neighbor 192.168.10.17 json' | jq '."192.168.10.17".messageStats.notificationsSent'
2
```
After:
```
$ vtysh -c 'clear ip bgp 192.168.10.17'
$ vtysh -c 'show bgp neighbor 192.168.10.17 json' | jq '."192.168.10.17".messageStats.notificationsSent'
1
```
Closes https://github.com/FRRouting/frr/issues/11257
=> bgpd: Don't increment twice notification sent stats counter

bgpd/bgp_rpki.c, doc/user/rpki.rst
```
spine1-debian-11# sh rpki cache-connection
Connected to group 1
rpki tcp cache 192.168.10.17 8283 pref 1 (connected)
rpki tcp cache 192.168.10.17 8282 pref 2
spine1-debian-11# sh rpki cache-connection json
{
"connectedGroup":1,
"connections":[
{
"mode":"tcp",
"host":"192.168.10.17",
"port":"8283",
"preference":1,
"state":"connected"
},
{
"mode":"tcp",
"host":"192.168.10.17",
"port":"8282",
"preference":2,
"state":"disconnected"
}
]
}
```
Related: https://github.com/FRRouting/frr/issues/11139
=> bgpd: Add JSON output for `show rpki cache-connection`

tests/topotests/pbr_topo1/test_pbr_topo1.py
This test is sometimes failing under severe load.  Give some time
for the linux rule installation to actually be registered by the
system before declaring failure.
=> tests: pbr_topo1 sometimes fails under really heavy load

bgpd/bgp_rpki.c
tcp_host->port is a string, ssh_config->port is an integer...
=> bgpd: Put ssh_config->port as integer, not as string in RPKI code

bgpd/bgp_rpki.c, doc/user/rpki.rst
```
spine1-debian-11# sh rpki cache-server json
{
"servers":[
{
"mode":"tcp",
"host":"192.168.10.17",
"port":"8283"
},
{
"mode":"tcp",
"host":"192.168.10.17",
"port":"8282"
}
]
}
spine1-debian-11# sh rpki cache-server
host: 192.168.10.17 port: 8283
host: 192.168.10.17 port: 8282
spine1-debian-11#
```
Related: https://github.com/FRRouting/frr/issues/11139
=> bgpd: Add JSON support for `show rpki cache-server`

docker/alpine/Dockerfile
This has librtr 0.8.0, while 3.13 has 0.7.0.
Related: https://github.com/FRRouting/frr/issues/11269
=> docker: Use Alpine 3.15 for build

bgpd/bgp_rpki.c
This is already handled by a separate command `show rpki cache-server`.
Probably just copy/paste error.
=> bgpd: Drop redundand output under `show rpki prefix-table`

tests/topotests/cspf_topo1/reference/sharp-ted.json
The cspf_topo1 test is comparing the adj-sid value that is
assigned dynamically based upon bring up order.  Under very
large scale this order changes causing the test to fail.
Since the adj-sid is dynamically allocated and appears to
be tested elsewhere, let's remove it from the grab all check.
=> tests: Allow cspf_topo1 to function correctly at scale

.github/workflows/base-branch-label.yml
Faster notice and filter backports by labels per release.
=> github: Add base branch label to every PR to distinguish easily

.github/workflows/base-branch-label.yml
Should solve this:
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```
=> github: Add permissions for labeler action

zebra/zapi_msg.c, zebra/zebra_dplane.c, zebra/zebra_pbr.c, zebra/zebra_pbr.h
The usage of zebra dplane makes the job asyncronous which implies
that a given job will try to add an iptable, while the second job
will not know that its iptable is the same as the former one.
The below exabgp rules stand for two bgp flowspec rules sent to
the bgp device:
flow {
route {match {
source 185.228.172.73/32;
destination 0.0.0.0/0;
source-port >=49156&<=49159;
}then {redirect 213.242.114.113;}}
route {match {
source 185.228.172.73/32;
destination 0.0.0.0/0;
source-port >=49160&<=49163;
}then {redirect 213.242.114.113;}}
}
This rule creates a single iptable, but in fact, the same iptable
name is appended twice. This results in duplicated entries in the
iptables context. This also results in contexts not flushed, when
BGP session or 'flush' operation is performed.
iptables-save: …
=> zebra: avoid pbr iptable added twice when used with flowspec

.github/workflows/base-branch-label.yml
And drop checkout action - not needed.
Due to the dangers inherent to automatic processing of PRs, GitHub’s standard
pull_request workflow trigger by default prevents write permissions and
secrets access to the target repository. However, in some scenarios such
access is needed to properly process the PR.
To this end the pull_request_target workflow trigger was introduced.
=> github: Use pull_request_target as a target

python/makefile.py, tools/frr-llvm-cg.c
Minor fixes to LLVM build tooling / analysis setup.
- use correct CFLAGS to build LLVM bitcode files
- document `makefile.py`
- remove unused variable in callgraph tool
(This should be in the "fixes for release"/stable category.)
=> build: fix some corners for LLVM analysis tools

pimd/pim_igmpv3.c, tools/etc/frr/support_bundle_commands.conf
…interfaces
This should not be merged, trying to gather data.
=> pimd: Disable handling v3 igmp packets on an interface config'ed for v2

bgpd/bgp_nht.c
Commit:
9f002fa5dd34e7d901b501e7d0306027d85b531a
Accidently broke the handling of SR color for nexthops
in BGP.  Put it back
Fixes: #11237
=> bgpd: Fix SR color nexthop processing in BGP

zebra/zebra_vxlan.c
When the kernel was sending an RTM_NEWLINK updating the MAC of a known
SVI, Type-2 routes created by advertise-svi-ip were not getting updated
with the new address.
This adds removal of any old Type-2 routes (with old MAC) and creation
of new Type-2 routes (with new MAC) into RTM_NEWLINK processing.
Fixes: #11174
=> zebra: Update advertise-svi-ip MACIPs w/ new MAC

bgpd/bgp_routemap.c, doc/user/routemap.rst
Allow the end operator to match `match peer <PEERGROUPNAME>`
in a route-map.  If the end operator defines interface
based peers and peer-groups that have names that overlap
the interface based peer will match first.
Fixes: #11316
=> bgpd: Add ability to match `match peer <PEERGROUPNAME>`

tools/frrcommon.sh.in
Since 1686b1d4864384ee508b58418f20970f2dff2587, we try to stop all daemons,
even those which are not (no longer) enabled in /etc/frr/daemons. But we
shouldn't complain about missing PID files for daemons which have never been
started and just silently ignore those.
=> tools: Don't complain about missing PID files when stopping all damons

tools/frrcommon.sh.in
#11315 (just merged) was actually pretty broken. This one really should fix it.
Fix daemon shutdown broken by f0cccaa6bf7dda71d0e1ad1b0406a9b453a84bb3. Now
we still don't complain about missing PID files but actually stop the
running daemons.
The previous fix was broken because it passed a new "--all" option to
daemon_stop which wasn't handled properly (it assumed $1 contains the
daemon name when at that time it acutally contained the "--all" option).
Plus, "--all" wasn't actually necessary, because we already passed
"--reallyall" from all_stop to daemon_stop after the daemon name.
So remove "--all" again and simply check for "--reallyall" in $2. This
should *really* fix #11317.
=> tools: Really fix all daemon shutdown without complaining about PID files

zebra/kernel_netlink.c
Adding error checking condition which was missed in PR-11216.
```
*** CID 1517953:  Error handling issues  (CHECKED_RETURN)
/zebra/kernel_netlink.c: 313 in netlink_socket()
307                     memset(&snl, 0, sizeof(snl));
308                     snl.nl_family = AF_NETLINK;
309                     snl.nl_groups = groups;
310
311     #if defined SOL_NETLINK
312                     if (ext_groups)
>>>     CID 1517953:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "setsockopt(sock, 270, 1, &ext_groups, 8U)" without checking return value. This library function may fail and return an error code.
313                             setsockopt(sock, SOL_NETLINK, NETLINK_ADD_MEMBERSHIP,
314                                        &ext_groups, sizeof(ext_groups));
315     #endif
316
317 …
```
=> zebra: add error check condition to sock option

lib/northbound.c, lib/northbound.h, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_be_adapter.h, mgmtd/mgmt_main.c, mgmtd/subdir.am, staticd/static_nb.c, staticd/static_nb_config.c, staticd/static_zebra.c
Was adding static_nb.c and static_nb_config.c as
a library to mgmt. Had put all the local variables
inside ifdefs. As local validation is not used now,
these changes can be reverted now.
Co-authored-by: Pushpasis Sarkar <pushpasis@gmail.com>
=> mgmtd: Revert changes related to local validation.

pimd/pim_register.c
PIM conformance test case 11.12 sends a register stop msg with
source address as 0. This should trigger a register stop for
all the upstreams. It is not happening as such because we are not
considering 0.0.0.0 source address for starg_handling.
Fixed it.
=> pimd: Handle receive of (*,G) register stop with src addr as 0

pimd/pim_cmd_common.c
The test for setting pimDesignatedRouterLocal was comparing
the result of pim_addr_cmp to non zero to say that the
pim_dr_addr and primary_address are the same.  This is
not correct in that pim_addr_cmp returns 0 for being the
same, so the correct test is !pim_addr_cmp
=> pimd: pim_addr_cmp returns 0 for same not -1 or 1

pimd/pim_cmd.c
the `show ip pim interface [x] traffic` command was deciding
to skip display of interfaces if they happened to be down at
that moment.  This of course does not make a bunch of sense
to limit the output for a interface that may have sent data
in the past.
This fixes this test crash:
rnode = <lib.topogen.TopoRouter object at 0x7fc755be3880>, dut = 'c1', input_dict = {'c1': {'c1-l1-eth2': ['helloTx', 'helloRx']}}, output_dict = {'c1': {}}
def show_pim_intf_traffic(rnode, dut, input_dict, output_dict):
show_pim_intf_traffic_json = run_frr_cmd(
rnode, "show ip pim interface traffic json", isjson=True
)
output_dict[dut] = {}
for intf, data in input_dict[dut].items():
>           interface_json = show_pim_intf_traffic_json[intf]
E           KeyError: 'c1-l1-eth2' …
=> pimd: Show interface traffic even if interface is currently `down`

pimd/pim_oil.c, pimd/pim_oil.h, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_static_routes_topo1.py
The pim_channel_oil_empty() function was setting
the pimreg if it ever existed for NULL comparison
but of course the pimreg device is never pulled back
out again when it was needed to be when the pimreg
is not present.
Commit: a5fa982256b23d53d5b833f75224fb7f96054b9b
broke this.
Fixes: #11368
=> pimd: Fix pim_channel_oil_empty tests

tests/topotests/lib/common_config.py
As of now we are logging only JSON output of CLIs
in topotests(topojson) executions and same o/p is
getting printed twice. CLI logging is already taken 
care by topogen.py inside vtysh_cmd() API.
Enhanced code to show both plain and JSON output
of CLIs and remove duplicate logging.
It will help in reducing execution logs and in
verification, if sometimes there is mis-match
in CLI plain and JSON outputs.
=> tests: [Topojson] Enhance CLI logging

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Moving the common lines of code to pim_cmd_common.c file
=> pimd, pim6d: Moving the reusable code to common api for PIM show CLIs

.github/workflows/stale.yml
=> github: Mark issues with no activity in 180 days as stale

bgpd/bgp_route.c
```
==2209758== 7,791,480 (399,840 direct, 7,391,640 indirect) bytes in 9,996 blocks are definitely lost in loss record 102 of 103
==2209758==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2209758==    by 0x4EE264F: qcalloc (memory.c:116)
==2209758==    by 0x22E62A: lcommunity_new (bgp_lcommunity.c:42)
==2209758==    by 0x22E62A: lcommunity_dup (bgp_lcommunity.c:155)
==2209758==    by 0x26F28F: route_set_lcommunity (bgp_routemap.c:2382)
==2209758==    by 0x4EFF7EF: route_map_apply_ext (routemap.c:2663)
==2209758==    by 0x250B3D: subgroup_announce_check (bgp_route.c:2202)
==2209758==    by 0x27A195: subgroup_announce_table (bgp_updgrp_adv.c:690)
==2209758==    by 0x27A509: subgroup_coalesce_timer (bgp_updgrp_adv.c:332)
==2209758==    by 0x4F1C3FC: …
```
=> bgpd: Fix memory leak when setting [l]community at egress

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_updgrp_adv.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/vnc_export_bgp.c, tests/topotests/bgp_set_local_preference_add_subtract/r2/bgpd.conf, tests/topotests/bgp_set_local_preference_add_subtract/r3/bgpd.conf, tests/topotests/bgp_set_local_preference_add_subtract/test_bgp_set_local-preference_add_subtract.py
When we use network/redistribute local_preference is configured inproperly
when using route-maps something like:
```
network 100.100.100.100/32 route-map rm1
network 100.100.100.200/32 route-map rm2
route-map rm1 permit 10
set local-preference +10
route-map rm2 permit 10
set local-preference -10
```
Before:
```
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.100/32 json' | jq '.paths[].locPrf'
10
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.200/32 json' | jq '.paths[].locPrf'
0
```
After:
```
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.100/32 json' | jq '.paths[].locPrf'
110
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.200/32 json' | jq '.paths[].locPrf'
90
```
Set local-preference as the default …
=> bgpd: Initialize attr->local_pref to the configured default value

bgpd/bgp_attr.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, lib/prefix.h, lib/routemap_northbound.c
Linux kernel allows (FreeBSD/OpenBSD too) using reserved class E IP ranges.
This is a preparation commit that ease the global switch to allow/deny
class E IP ranges in FRR.
https://datatracker.ietf.org/doc/html/draft-chen-ati-adaptive-ipv4-address-space
Related: https://github.com/FRRouting/frr/pull/11283
=> bgpd: Wrap IPV4_CLASS_DE into ipv4_unicast_valid() helper

bgpd/bgp_evpn_vty.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_route.c, bgpd/bgp_vty.c, isisd/isis_cli.c, isisd/isis_redist.c, lib/routemap.c, ospf6d/ospf6_asbr.c, ospfd/ospf_vty.c, ripd/rip_cli.c, ripngd/ripng_cli.c, zebra/zebra_vty.c
For example:
```
donatas-laptop# show bgp ipv4 unicast neighbors 127.0.0.2 advertised-routes route-map ?
RMAP_NAME  Name of the route map
testas2 testas
donatas-laptop(config)# router bgp
donatas-laptop(config-router)# address-family ipv4
donatas-laptop(config-router-af)# redistribute connected route-map ?
RMAP_NAME  Pointer to route-map entries
testas2 testas
donatas-laptop(config-router-af)# network 192.168.0.0/23 route-map ?
RMAP_NAME  Name of the route map
testas2 testas
```
=> *: Use autocomplete for route-maps under commands that require it

pimd/pim_iface.c
mld is enabled on pimreg interface by default. This is fixed now.
https://github.com/FRRouting/frr/issues/11240
=> pim6d: Don't enable mld on pimreg interface by default

tests/topotests/ldp_topo1/r1/show_ip_ospf_neighbor.json, tests/topotests/ldp_topo1/r2/show_ip_ospf_neighbor.json, tests/topotests/ldp_topo1/r3/show_ip_ospf_neighbor.json, tests/topotests/ldp_topo1/r4/show_ip_ospf_neighbor.json, tests/topotests/ldp_topo1/test_ldp_topo1.py
The sporadic failures were happening because, under heavy load,
the r4 router could form an OSPF adjacency with r3 a few seconds
before doing the same with r2. In that interim, LDP could establish
a neighborship with r2 going through r3 (instead of connecting
directly). That would cause all label mappings received from r3
to be ignored since they can't be mapped to the routes' nexthops
received from zebra, causing all sorts of test failures. None of
this is erroneous behavior as LDP simply follows the IGP.
The fix consists of updating the test to ensure all expected OSPF
adjacencies fully converged before proceeding to the LDP checks.
=> tests: fix sporadic failures in the ldp_topo1 topotest

vtysh/vtysh.c
```
donatas-laptop(config)# router bgp 123 vrf ?
VIEWVRFNAME  View/VRF name
default mgmt1 servers2
```
=> vtysh: Add autocomplete for VRFs when using with `router bgp`

pimd/pim_rp.c
The rpf lookup debug was not taking into account the fact that a prefix-list
might be applied and also we might need to make a choice between the two.
So let's give ourselves a bit more data.
=> pimd: Cleanup rpf lookup debug to help us figure out what is going on

doc/user/ldpd.rst, tests/topotests/ldp_vpls_topo1/r1/ldpd.conf, tests/topotests/ldp_vpls_topo1/r2/ldpd.conf, tests/topotests/ldp_vpls_topo1/r3/ldpd.conf
In the last step of this test, r1's link to r2 is shut down but
both routers stay connected through a multi-hop LDP session. That
happens because r1 and r2 have a targeted adjacency created by
the pseudowire.  The test then checks whether the pseudowire is
still up, using an alternate path for nexthop resolution.
Everything's fine except for the fact that LDP GTSM (aka
ttl-security) is enabled by default. This means that messages sent
over a multi-hop session are not delivered. In the case of this
test, it can prevent PW-Status notifications from being delivered,
which in turn can prevent the pseudowire from coming back up.
Fix the test by disabling GTSM so that LDP multi-hop sessions can
work normally. This is in accordance with RFC6720 which mentions
that GTSM should be disabled …
=> tests: fix ldp_vpls_topo1 to work as expected

pimd/pim_oil.c
When pim_upstream_inherited_olist_decide calls the api
pim_channel_add_oif, it can pass PIM_OIF_FLAG_PROTO_GM,
PIM_OIF_FLAG_PROTO_PIM and/or PIM_OIF_FLAG_PROTO_STAR.
Now a consider a case where PIM flag was already set
but STAR flag was not set and this api tries to set
both STAR + PIM and passes the same. The api pim_channel_add_oif
returns since it sees that PIM is already set without
setting the STAR flag.
So basically this will lead to issues in scenarios where for the
same OIF multiple flags(IGMP, PIM, STAR) needs to be set.
Fixing it for all combinations.
=> pimd: Fix the setting of oif_flags in channel oil

tests/topotests/lib/common_config.py, tests/topotests/lib/pim.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_bsm_topo2/test_mcast_pim_bsmp_02.py
Verifying and making sure PIM neighbors are
up before sending BSM packet using Scapy.
Verifying static routes are installed before
proceeding further.
=> tests: Verify PIM neighbors and static routes for BSM tests

pimd/pim_cmd_common.c
PIM_IPV == 4 is removed form function pim_cmd_show_ip_multicast_helper
as pim_zlookup.c is available for pimv6 aswell.
=> pim6d: Removed PIM_IPV == 4 flag

tests/topotests/lib/common_config.py
When you have a static route with multiple different admin
distances there exists a chance that route will have been
installed multiple times due to system load when inserted
at about the same time.  If this is the case then the
verify_rib function can and will select the wrong route
that happens to have a nexthop group that is still installed.
Modify verify_rib to ensure that the route that is going to
be looked at for nexthop correctness is the actual installed
route, not a previous version of it.
=> tests: Fix verify_rib such that it will look at the selected route

bgpd/bgp_debug.c, ospfd/ospf_dump.c, zebra/interface.c, zebra/ioctl.c
See individual commits:
a) bgpd/ospfd -> had extra whitespace when showing `show debugging`.  Just noticed this in passing and added a quick cleanup
b) Make ioctl.c's log messaging a bit better informed.
c) <this is the meat of the matter> On linux do not ask the ioctl for interface updates via if_refresh as that it all comes in through netlink messaging.  This removal reduces some of the duplication of effort being seen on shut/no shut events for interfaces
=> Interface duplication linux

bgpd/bgp_bmp.c, bgpd/bgp_bmp.h, bgpd/bgp_network.c, bgpd/bgp_network.h, doc/user/bmp.rst
With current release, forcin the source ip address when setting up a BMP
connection is not possible.
The need is to add an extra parameter for the following vty command:
router bgp 65500
bmp targets AAA
bmp connect 2.2.2.2 port 666 min-retry 100 max-retry 700
bmp connect 2:2::2:2 port 666 min-retry 100 max-retry 700 [source-interface lo1]
=> bmp: add a interface source to bmp connect command

bgpd/bgp_bmp.c
Commit: 09f267ec95de6d introduced more sockunion2str
usages when FRR should be using %pSU.  This commit
broke the compile when using --enable-dev-build
=> bgpd: Use %pSU instead of sockunion2str

.github/workflows/stale.yml
Set autoclose label after 180 days (no activity) and close (really) two weeks
later.
=> github: Autoclose stale issues/PRs that are stare longer than 180 days

lib/libfrr.c
- The parent of the daemonizing fork reports memleaks for the early
northbound allocations (libyang). If these were real memleaks these
would show up in the child as well; however, ignoring all memleaks in
the parent of the fork is too hard a sale. Instead, spend some CPU
cycles cleaning up the allocations in the parent after the fork and
immeidatley prior to exiting the parent after the daemonizing fork.
=> lib: cleanup red-herring memleaks in parent of daemonizing fork

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_updgrp_adv.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/vnc_export_bgp.c, tests/topotests/bgp_set_local_preference_add_subtract/r2/bgpd.conf, tests/topotests/bgp_set_local_preference_add_subtract/r3/bgpd.conf, tests/topotests/bgp_set_local_preference_add_subtract/test_bgp_set_local-preference_add_subtract.py
When we use network/redistribute local_preference is configured inproperly
when using route-maps something like:
```
network 100.100.100.100/32 route-map rm1
network 100.100.100.200/32 route-map rm2
route-map rm1 permit 10
set local-preference +10
route-map rm2 permit 10
set local-preference -10
```
Before:
```
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.100/32 json' | jq '.paths[].locPrf'
10
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.200/32 json' | jq '.paths[].locPrf'
0
```
After:
```
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.100/32 json' | jq '.paths[].locPrf'
110
root@spine1-debian-11:~# vtysh -c 'show bgp ipv4 unicast 100.100.100.200/32 json' | jq '.paths[].locPrf'
90
```
Set local-preference as the default …
=> bgpd: [8.2] Initialize attr->local_pref to the configured default value

lib/if.c
Using strtol() to compare two strings is a bad idea.
Before the patch, if_cmp_name_func() may confuse foo001 and foo1.
Fixes: 106d2fd572c1 ("2003-08-01 Cougar <cougar@random.ee>")
Signed-off-by: Nicolas Dichtel <nicolas.dichtel@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>
=> lib/if: fix interface name comparison

lib/prefix.h, pimd/pim_register.c, pimd/pim_register.h
Right now, PIMv6 uses link-local addresses for all the communications with the neighbors but
for register packet, it does not work.
So added an api to check if an address is global ipv6 address unicast address or not.
Added an api in pim6d to select a global address from the secondary address list and use
it to send the register msg.
Fixes: #11235
=> lib: pim6d: Use IPv6 global unicast address to send PIMv6 register packet

zebra/zebra_rib.c
Since the calling hook for old fpm is done in `rib_uninstall_kernel()`
inside, this calling place outside should be redundant. Just remove it.
=> zebra: remove redundant calling hook for fpm

doc/user/ospfd.rst, ospfd/ospf_vty.c
Description:
"show ip ospf neighbour [nbrid] [json]" is expected to give brief output
of the specific neighbour. But it gives the detailed output without
the detail keyword.
"show ip ospf neighbour [nbrid] [deatil] [json]" command is failed to
fetch the expected o/p. Corrected it.
Ex o/p:
frr(config-if)# do show ip ospf  neighbor
Neighbor ID     Pri State           Up Time         Dead Time Address         Interface                        RXmtL RqstL DBsmL
8.8.8.8           1 Full/DR         17m03s            31.192s 20.1.1.194      ens192:20.1.1.220                    0     0     0
30.1.1.100        1 Full/DR         56.229s           32.000s 30.1.1.100      ens224:30.1.1.220                    0     0     0
frr(config-if)#
frr(config-if)#
frr(config-if)# do show ip ospf  neighbor …
=> ospfd: Fixing "show ip ospf neighbour <nbrid>" command

bgpd/bgp_zebra.c, lib/nexthop.h, lib/zclient.c, lib/zclient.h, zebra/zapi_msg.c, zebra/zebra_dplane.c, zebra/zebra_fpm_netlink.c, zebra/zebra_rib.c
Multipath route may have mixed nexthops of EVPN and IP unicast. Move
EVPN flag to nexthop to support such cases.
=> lib, zebra, bgpd: Move route EVPN flag to nexthop

zebra/debug_nl.c, zebra/rt_netlink.c
Idea for https://github.com/FRRouting/frr/issues/11451  
We think adding multipath route with a Linux realm (using rt tag mapping) needs a flow attribute per gateway attribute within a multipath rtnl attribute.  
rtnl msg multipath attr dump
```
3400 0900 len 52 RTA_MULTIPATH (9)
1800 0000 len 24
0a00 0000 10: if index
0800 0500 len 8 GATEWAY (5)
0a0a 0a0f 10.10.10.15
0800 0b00 len 8 FLOW (11)
1500 0000 realm 21
1800 0000 len 24
0a00 0000 10: if index
0800 0500 len 8 GATEWAY (5)
0a0a 0a10 10.10.10.16
0800 0b00 len 8 FLOW (11)
1500 0000 realm 21 
```  
Thanks for the help
Signed-off-by: Ricardo <rbarroetavena@anura.com.ar>
=> zebra: rtnetlink: flow attr per gateway attr in multipath updates

doc/user/installation.rst, doc/user/routemap.rst
realms require that the RTA_FLOW attribute be passed down per nexthop when encoding routes.  Make the code work with this.
=> Realm fix nexthop groups

vtysh/vtysh_user.c
Description:
SonarQube detects the following behaviour as a vulanarability.
When authenticating users using PAM, it is strongly recommended to
check the validity of the account (not locked, not expired ...),
otherwise it leads to unauthorized access to resources.
pam_acct_mgmt() should be called for account validity after
calling pam_authenticate().
=> vtysh: Account validity should be verified when authenticating users with PAM

ospf6d/ospf6_zebra.c
It's possible for ospf6 to decide to delete a route after it's removed all of the route's nexthops. It's ok to delete a prefix alone - be a little more forgiving when preparing a route delete.
=> ospf6: permit route delete without nexthops

zebra/zebra_vxlan.c
The two checks have been already checked in `lib_vrf_zebra_l3vni_id_modify()`
as it should be. So remove them from `zebra_vxlan_process_vrf_vni_cmd()`.
And it is improper that the two checks are put after
`zebra_vxlan_handle_vni_transition()`, which will do real things. It is
too later, but luckily they never got there so no bug, just redundant.
UPDATE:
The two checks for l3vni have been already done in
`lib_vrf_zebra_l3vni_id_modify()` as it should be. And it is improper that
the two checks are put after `zebra_vxlan_handle_vni_transition()`, which
will do real things.
My original fix is to remove them. But NB module can't guarantee many changes,
so we'd better keep them in `zebra_vxlan_process_vrf_vni_cmd()` in APPLY stage
for safe.
Just move them in front of …
=> zebra: move the checks for l3vni

pimd/pim_upstream.c
If the upstream is freed in pim_upstream_del, then trying to
call pim_upstream_timers_stop will lead to accessing freed memory.
Fix:
Change the order of the function call.
=> pimd: Avoid accessing freed memory

pimd/pim_cmd_common.c
Fixing the issue https://github.com/FRRouting/frr/issues/11233
Problem:
The command "show ip[v6] mroute" displaying group and source
field for every OIL.
Fix:
Display group and source for the first OIL only. 
=> pim6d: Fixing repeated group source field in show ipv6 mroute

zebra/if_netlink.c, zebra/if_netlink.h, zebra/kernel_netlink.c
'bridge vni add vni <id> dev <vxlan device>'
generates new RTM_NEWTUNNEL and RTM_DELTUNNEL
to add or remove vni to l3vxlan device.
Register new RTNLGRP_TUNNEL group to receive
new netlink notification.
Callback for the new RTM_xxxTUNNEL.
kernel patches:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/
linux.git/commit/?h=v5.18-rc7&id=7b8135f4df98b155b23754b6065c157861e268f1
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/
linux.git/commit/?h=v5.18-rc7&id=f9c4bb0b245cee35ef66f75bf409c9573d934cf9
Ticket:#3073812
Testing Done:
=> zebra: netlink rtm tunnel msg parsing

pimd/pim_instance.c
Fixing below valgrind issues.
==16837== Invalid read of size 8
==16837==    at 0x17971C: pim_neighbor_find (pim_neighbor.c:431)
==16837==    by 0x186439: join_timer_stop (pim_upstream.c:348)
==16837==    by 0x186794: pim_upstream_del (pim_upstream.c:231)
==16837==    by 0x189A66: pim_upstream_terminate (pim_upstream.c:1951)
==16837==    by 0x17111B: pim_instance_terminate (pim_instance.c:54)
==16837==    by 0x17111B: pim_vrf_delete (pim_instance.c:172)
==16837==    by 0x4F1D6C8: vrf_delete (vrf.c:264)
==16837==    by 0x19006F: pim_terminate (pimd.c:160)
==16837==    by 0x1B2E4D: pim_sigterm (pim_signals.c:51)
==16837==    by 0x4F08FA2: frr_sigevent_process (sigevent.c:130)
==16837==    by 0x4F1A2CC: thread_fetch (thread.c:1771)
==16837==    by 0x4ED4F92: frr_run (libfrr.c:1197)
==16837== …
=>  pimd: Fixing invalid memory access

pimd/pim_instance.c
pim_mroute_socket_disable api is present but nowhere called.
This should be called when pim instance is terminated.
Fixed it.
=> pimd: Clean up mroute_socket when pim terminates.

debian/frr.postinst
egrep is deprecated, please see
https://git.savannah.gnu.org/cgit/grep.git/commit/?id=a9515624709865d480e3142fd959bccd1c9372d1
=> frr.postinst: egrep is deprecated

pimd/pim_iface.c
Deletion of pim interface(pim_if_delete) should
do the below things before cleanup.
1. Send a hello message with zero hold time.
2. Delete all the neighbors.
3. Close the pim socket.
This is fixed now.
=> pimd: fix pim interface deletion flow

tools/frrcommon.sh.in
2469a37f reversed the logic of the existence check for
/etc/frr/frr.conf breaking boot config loading, fix it.
=> tools: fix boot config load in watchfrr

isisd/fabricd.c, isisd/isis_bfd.c, isisd/isis_circuit.c, isisd/isis_lsp.c, isisd/isis_pdu.c, isisd/isis_te.c, tests/topotests/bgp_multiview_topo1/test_bgp_multiview_topo1.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py, tests/topotests/ospf6_ecmp_inter_area/test_ospf6_ecmp_inter_area.py, tests/topotests/route_scale/scale_test_common.py, tests/topotests/zebra_seg6local_route/test_zebra_seg6local_route.py
a) Crash in isis because we were not allocating lists to save space and missed at least 1 code path where we didn't allocate first
b) Fix a test not running to completion because a route was still queued and we gave up too early
c) Fix some regex usage issues
=> Crash fix and test fix and some cleanup

zebra/interface.c, zebra/interface.h, zebra/netconf_netlink.c, zebra/zebra_router.h, zebra/zebra_vty.c
see individual commits:
a) mc_forwarding was being sent but not retrieved per interface, fix
b) Pass the afi received and handle v4 and v6 specific versions of the netconf data
c) Add the ability for the netconf dplane to handle the global ALL and DEFAULT values as passed.
=> Netconf work

pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_nb_config.c, pimd/pim_vty.c, pimd/pim_vxlan.c
Modified variable name so that it can be reused in mld.
=> pim6d: Changing igmp_enable to gm_enable.

bgpd/bgp_attr.c, bgpd/bgp_debug.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst
Add the `bgp allow-martian` command under `router bgp X` to allow bgp to receive a NLRI with a nexthop that is a martian address.  Deprecate `debug bgp allow-martian` which is what originally did this
=> Allow martians

pimd/pim_igmp.c
Fixing IGMPv2 ANVL Conformance 3.10
As per RFC 2236 section 3, when the leave message is received at a querier,
it starts sending Query messages for "last Member Query Interval*query count"
During this time there should not be any querier to non-querier
transition and the same router needs to send the remaning queries.
Currently the code is handling this scenario only when leave is receive
for a group and the query is received for the same group.
But we need to handle it irrespective of group since the querier
election is based on interface and not group.
=> pimd: Querier to non-querier transition to be ignored (ANVL Conformance fix)

bgpd/bgp_vty.c
The default keepalive/hold timers are always exposed via this commit:
```
commit 9b1b96233d7204263d409ea6c504b316af9e533f (origin/bgp_timer_always_on)
Author: Trey Aspelund <taspelund@nvidia.com>
Date:   Mon Jun 27 23:20:33 2022 +0000
bgpd: always display keepalive/hold intervals
`show bgp neighbors <peer> [json]` was only displaying the configured
keepalive and holdtime intervals when they differed from the default
values.  Since default config is still config, let's make sure these
values are always displayed.
```
However it mistakenly changed the logic to only display the peer's
timers if the configured value was non-zero.  This updates the logic to
check PEER_FLAG_TIMER to determine if the values were configured,
given 0 is a valid …
=> bgpd: include 0 in configured hold/keepalive

pimd/pim_addr.h, pimd/pim_vty.c
Change the show running commands for pimv4 and pimv6 debug commands
based on the address family.
Signed-off-by: Sai Gomathi N <nsaigomathi@vmware.com>
=> pimd,pim6d: Change the show running commands based on address family

pimd/pim_tlv.c
As per RFC 4601 section 4.9.4, For Register-Stops,
the Mask Len field contains full address length * 8
(e.g. 32 for IPv4 native encoding) (e.g. 128 for IPv6),
if the message is sent for a single group
The issue is seen after #10356, so fixed now.
=> pimd: Register stop message sent with mask 32

zebra/kernel_socket.c
Fixes #11513 .
This is a slightly modified version of Hiroki Sato's version:
https://github.com/hrs-allbsd/frr/commit/9ca79c941fd84322199994a2aed267b23d39c86a
Handle the `ENOBUFS` on a OS basis since it could have been implemented
differently (OpenBSD for an example uses `RTM_DESYNC`).
=> zebra: handle FreeBSD routing socket ENOBUFS

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_igmp.c, pimd/pim_instance.h, pimd/pim_vty.c
Implementing the todo parts of watermark-warn CLI for IPv6 MLD
This command can be use to warn the user
when more than the desired limit of groups gets configured.
Signed-off-by: Sai Gomathi N <nsaigomathi@vmware.com>
=> pim6d: Fix the todo items in ipv6 watermark limit CLI

zebra/zebra_rib.c
New output example:
2022-07-03 09:40:29.310 [DEBG] zebra: [JF0K0-DVHWH] rib_meta_queue_add: (0:254):4.5.6.8/32: queued rn 0x55937f586ee0 into sub-queue Kernel Routes
2022-07-03 09:40:29.321 [DEBG] zebra: [HH6N2-PDCJS] default(0:254):4.5.6.8/32 rn 0x55937f586ee0 dequeued from sub-queue Kernel Routes
Let's make it a bit more human readable.
=> zebra: Add a subqueue2str function to give more useful data in debugs

zebra/kernel_netlink.c
some minor changes around the SOL_NETLINK sockopt call to make it a bit better for the end operator to understand what is going on when failure cases happen
=> Setsockopt changes

bfdd/bfd.c, bfdd/bfd.h, bfdd/bfd_packet.c, bfdd/bfdd_cli.c, tests/topotests/bfd_vrf_topo1/r1/bfdd.conf, tests/topotests/bfd_vrf_topo1/r1/peers.json, tests/topotests/bfd_vrf_topo1/r2/bfdd.conf, tests/topotests/bfd_vrf_topo1/r2/peers.json, tests/topotests/bfd_vrf_topo1/r3/bfdd.conf
Modify the existing BFD Echo code to send an Echo message that will
be looped in the peers forwarding plane.   The existing Echo code
only works with other FRR implementations because the Echo packet
must go up to BFD to be turned around and forwarded back to the
local router.    The new BFD Echo code sets the src/dst IP of the
packet to be the local router's IP and sets the dest MAC to be the
peers MAC address.    The peer receives the packet and because it
is not it's IP address it forwards it back to the local router.
Signed-off-by: Lynne Morrison <lynne.morrison@ibm.com>
=> bfdd: add IPv4 BFD Echo support that loops pkts in forwarding plane

pimd/pim_oil.h
Removing the extern declaration of pim_channel_oil_list since
its not required anymore.
=> pimd: Remove unused extern pim_channel_oil_list

tests/topotests/bgp_conditional_advertisement/test_bgp_conditional_advertisement.py
The bgp_conditional_advertisement topotest runs all the test cases in
the same function. It is not easy to debug it because the pytest
"--pause" argument does not make breaks between test cases.
Dispatch the test-cases into functions to benefit from the "--pause"
feature.
=> topostest: bgp_conditional_advertisement cleanup

ospfd/ospf_bfd.c, tests/topotests/bfd_profiles_topo1/r1/ospfd.conf
Before this patch we can enable 'ip ospf bfd' via '[no] ip ospf bfd profile ...' commads.
After patch '[no] ip ospf bfd profile ...' actual only if 'ip ospf bfd' is set.
=> ospfd: set/unset bfd profile

tests/topotests/lib/common_config.py
Issue was reported by Donald, we were hitting
with key not found error and execution was
stopped, which is fixed by this PR.
=> tests: Fix for multicast_pim_bsm_topo1 key error

lib/typesafe.h
There's a nagging SA warning, at least with the scan-build version we use in the FRR CI.
=> lib: fix SA warning in typesafe code

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Problems Identified:
show ip pim nexthop cli didn't have json extension and
show ipv6 pim nexthop cli didn't have json extension
Fixes: #9307
Description:
show ip pim nexthop command shows the nexthops that are being used.
Added json support for the commands.
Signed-off-by: nsaigomathi <nsaigomathi@vmware.com>
=> pimd: json support for nexthop

pimd/pim6_cmd.c, pimd/pim_nb_config.c
Fixing the ipv6 pim drpriority issues.
Issue 1 : 
Fixes: https://github.com/FRRouting/frr/issues/11503
R2(config)# interface ens192.4001
R2(config-if)# ipv6 pim drpriority 200
Error description: Pim not enabled on this interface
Issue 2:
no ipv6 pim drpriority command is not showing.
=> pim6d: Fix [no] ipv6 pim drpriority command

lib/resolver.c
resolver_resolve should check hostname is null or not.
if ares_gethostbyname() get a null hostname string, it will access a null pointer and crash.
**test result:**
**trace code**
=> lib: check hostname in resolver_resolve

tests/topotests/bgp_default_originate/test_bgp_default_originate_topo1_3.py
this commit containes 2 testcases that covers
1. Default originate behaviour on restarting the BGP daemon and FRR router
2. Default Originate behaviour on shut /no-shutting the interface
Signed-off-by: ARShreenidhi <rshreenidhi@vmware.com>
=> tests : bgp default originate test cases

pimd/pim_bsm.c, pimd/pim_cmd_common.c, pimd/pim_iface.c, pimd/pim_ifchannel.c, pimd/pim_join.c, pimd/pim_jp_agg.c, pimd/pim_msg.c, pimd/pim_neighbor.c, pimd/pim_nht.c, pimd/pim_nht.h, pimd/pim_register.c, pimd/pim_rp.c, pimd/pim_rpf.c, pimd/pim_rpf.h, pimd/pim_tib.c, pimd/pim_upstream.c, pimd/pim_upstream.h, pimd/pim_vxlan.c, pimd/pim_zebra.c
Modifying below structures from struct prefix to pim_addr
Modify "struct prefix rpf_addr" to "pim_addr rpf_addr".
Modify "struct pim_rpf rpf" in "struct pim_nexthop_cache".
Modify "struct pim_rpf rp" in "struct rp_info".
Modify "struct pim_rpf rpf" in "struct pim_upstream".
=> pim6d: modify pim_rpf from struct prefix to pim_addr

bgpd/bgp_bmp.c
When using `no router bgp` we MUST free the memory for the listeners too.
Replicate with:
```
router bgp 100
bmp targets server1
bmp listener 0.0.0.0 port 65535
no router bgp
router bgp 100
bmp targets server1
bmp listener 0.0.0.0 port 65535
no router bgp
router bgp 100
bmp targets server1
bmp listener 0.0.0.0 port 65535
no router bgp
```
Before:
```
Type                          : Current#   Size       Total     Max#  MaxBytes
BMP targets                   :        0    240           0        1       248
BMP targets name              :        0      8           0        1        24
BMP listener                  :       12    152        1824       12      1824
BMP instance state            :        0     88           0        1        88
```
After:
```
Type                          : …
```
=> bgpd: Free memory for BMP listeners when deleting BGP instance

zebra/debug_nl.c, zebra/rt_netlink.c
- fix #11533 by properly ignoring irrelevant notifications
- fix header type in RTM_GETROUTE
- drop unneeded IIF/OIF attributes
- set src/dst len correctly
- make table ID hack IPv4 specific
- add debug decodes for RTA_EXPIRES and RTA_MFC_STATS
=> zebra: fix various multicast routing netlink API bits

pimd/pim6_cmd.c, pimd/pim_cmd.c
The code is mismatching with the display. So fixing this.
frr# clear ip 
mroute       IP multicast routing table
=> pimd, pim6d: Fix description for clear ip[v6] mroute command

bgpd/bgp_evpn.c
`attr.rmac` is not set in debug as expected for its wrong place in code.
Just move the debug process (`bgp_debug_zebra(NULL)`) after possible `rmac`
value is set.
=> bgpd: fix missing rmac value in debug

bgpd/bgp_updgrp.c
The GCC extended printf format checking plugin runs into some GCC shortcomings regarding casts on printf function parameters.  While this can be fixed with a small GCC patch, patching GCC is "nontrivial" to say the least.  Luckily, it happens that this is /almost/ not an issue for the FRR source base.
Since we fix SA "misunderstandings" too, let's just fix places where the format checking plugin runs into this limitation to keep things working extra smoothly.
(It's not a huge effort either, these two spots in bgpd are the only places that trigger the plugin limitation, and it's been "clean" before that for more than a year if my memory is right.)
---
To build with the plugin, run `make -C tools/gcc-plugins CXX=g++-$GCCVER` **before** `./configure` (it will autodetect the plugin). …
=> bgpd: work around GCC/plugin shortcomings

doc/user/pimv6.rst, pimd/pim6_cmd.c
This is needed for ANVL between testruns, and already in IPv4 too.
=> pim6d: add `clear ipv6 pim bsr-data`

babeld/message.c
We installed the route only if the type was SUBTLV_MANDATORY.
Fixes https://github.com/FRRouting/frr/issues/11555
=> babeld: Install route to RIB if parse_update_subtlv() is false

pimd/pim_str.h
Removing double inclusion of pim_addr.h from pim_str.h file.
=> pimd: removal double inclusion of pim_addr.h

bgpd/bgp_packet.c
==175785== 0 bytes in 1 blocks are definitely lost in loss record 1 of 88
==175785==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==175785==    by 0x492EB8E: qcalloc (in /usr/local/lib/libfrr.so.0.0.0)
==175785==    by 0x269823: bgp_notify_decapsulate_hard_reset (in /usr/lib/frr/bgpd)
==175785==    by 0x26C85D: bgp_notify_receive (in /usr/lib/frr/bgpd)
==175785==    by 0x26E94E: bgp_process_packet (in /usr/lib/frr/bgpd)
==175785==    by 0x4985349: thread_call (in /usr/local/lib/libfrr.so.0.0.0)
==175785==    by 0x491D521: frr_run (in /usr/local/lib/libfrr.so.0.0.0)
==175785==    by 0x1EBEE8: main (in /usr/lib/frr/bgpd)
==175785==
=> bgpd: Free ->raw_data from Hard Notification message after we use it

configure.ac, debian/rules, doc/developer/packaging-debian.rst, pimd/subdir.am, redhat/frr.spec.in
By default pim6d will be disabled on all the systems.
Use --enable-pim6d flag in configure option for running pim6d daemon.
=> pim6d: Enable/disable pim6d daemons on different platforms based on flags

zebra/zebra_evpn_neigh.c
The assignment of neigh flags on ES peers is set twice. Just clean it.
=> zebra: remove redundant flags assignment

pimd/pim_rp.c
~~I would like to discuss on this before moving further. Have raised it temporarily to ease the discussion.~~
~~Either~~
1. We can fix both PIMv4 and PIMv6 by only matching the configured RP address with the interface address and not the prefix-length since it does not matter
**OR**
~~2. Make this fix only specific to PIMv6 as done in this PR.~~
The API pim_rp_check_interface_addrs checks if the RP address matches
with the primary address then it returns true.
In case of PIMv4 this condition is true, therefore the router becomes RP.
But in case of PIMv6, this condition does not pass because primary address
for PIMv6 is link-local address.
Also PIMv4 allows secondary addresses to be used as RP
if it is a host route in case primary does not match.
This behaviour is same for PIMv6.
Fixing it …
=> pimd,pim6d: Set RP to true if the address matches, ignore prefix-length

lib/prefix.h, pimd/pim_str.h
Longest possible length of a IPV6 (S,G) string is 94 bytes
INET6_ADDRSTRLEN * 2 = 46 * 2
(,) = 1
NULL Character at end = 1
=> pim6d: Longest possible length of a (S,G) string is 96 bytes

pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
In several places, we are getting the vrf structure using vrf_lookup_by_name().
Again we are passing vrf->vrf_id to pim_get_pim_instance() to get the pim_instance. 
The API pim_get_pim_instance() again get the VRF structure using vrf_lookup_by_id(). This is avoided in this PR.
=> pimd: Avoid unnecessary vrf lookup

pimd/pim_nht.c, pimd/pim_upstream.c
pimd: During prune pending, behave as NOINFO state
Fixed ANVL Conformance PIM-SM 16.3 test case.
When (S,G,rpt) prune is received, we were installing
the mroute immediately with none as OIF.
This leads to dropping the (S,G) traffic during prune
pending time as well.
Also we should not install the mroute if there is no
change in the rpf update.
These 2 things lead to the failure of the test case.
Fixed it by blocking the installation in this scenario.
When prune pending timer pops, it will take care of
installing the mroute with  none as OIF.
Fixes: https://github.com/FRRouting/frr/issues/11535
=> pimd: During prune pending, behave as NOINFO state (conformance issue)

tests/topotests/bgp_default_route_route_map_match_set/r1/zebra.conf
Remove an extra dot on an IP in r1 zebra config for topotest bgp_default_route_route_map_match_set
=> topotests: Remove typo (extra dot on the IP)

zebra/zebra_neigh.c
=> zebra: free neighbor state before exit to avoid memleaks

tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_bsm_topo2/test_mcast_pim_bsmp_02.py
API to verify static route was checking whether
router is installed with expected nexthop. In
this particular scenario we has same route as
Connected and Static both. In heavy loaded
system static routes was taking time to get
installed and API was doing the verification
on Connected route instead Static route that
is why nexthop verification was failing and so 
was the test. Enhanced scripts to check for
static routes only.
Issue: https://github.com/FRRouting/frr/issues/11563
=> tests: Fix multicast_pim_bsm_topo2 static route issue

bgpd/bgp_community_alias.c
==361630== 24,780 (96 direct, 24,684 indirect) bytes in 3 blocks are definitely lost in loss record 94 of 97
==361630==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==361630==    by 0x492EB8E: qcalloc (in /usr/local/lib/libfrr.so.0.0.0)
==361630==    by 0x490BB12: hash_get (in /usr/local/lib/libfrr.so.0.0.0)
==361630==    by 0x1FD3CC: bgp_ca_alias_insert (in /usr/lib/frr/bgpd)
==361630==    by 0x2CF8E5: bgp_community_alias_magic (in /usr/lib/frr/bgpd)
==361630==    by 0x2C980B: bgp_community_alias (in /usr/lib/frr/bgpd)
==361630==    by 0x48E3556: cmd_execute_command_real (in /usr/local/lib/libfrr.so.0.0.0)
==361630==    by 0x48E384B: cmd_execute_command_strict (in /usr/local/lib/libfrr.so.0.0.0)
==361630==    by 0x48E3D41: …
=> bgpd: Fix memory leak for community alias

ospfd/ospf_spf.c
Covers case where a node is connected to a peer via two interfaces/networks, and one adjacency is not FULL (and the other one is)
=> ospfd: free unreachable router LSA node so that it is not left unreachable

bgpd/bgp_community.c
Do not forget to cleanup after we are done:
==395247== 8,268 (32 direct, 8,236 indirect) bytes in 1 blocks are definitely lost in loss record 199 of 205
==395247==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==395247==    by 0x492EB8E: qcalloc (in /usr/local/lib/libfrr.so.0.0.0)
==395247==    by 0x490BB12: hash_get (in /usr/local/lib/libfrr.so.0.0.0)
==395247==    by 0x1FBF63: community_intern (in /usr/lib/frr/bgpd)
==395247==    by 0x1FC0C5: community_parse (in /usr/lib/frr/bgpd)
==395247==    by 0x1F0B66: bgp_attr_community (in /usr/lib/frr/bgpd)
==395247==    by 0x1F4185: bgp_attr_parse (in /usr/lib/frr/bgpd)
==395247==    by 0x26BC29: bgp_update_receive (in /usr/lib/frr/bgpd)
==395247==    by 0x26E887: bgp_process_packet (in …
=> bgpd: Fix memory leak for community stuff

bgpd/bgp_attr.c
According to RFC9234:
An UPDATE message with a malformed OTC Attribute SHALL be handled
using the approach of "treat-as-withdraw".
=> bgpd: OTC attribute should be treated as withdrawal

bgpd/bgp_bmp.c, doc/user/bmp.rst
Support for BMP L3VPN monitoring messages through SAFI_MPLS_VPN address
family
=> bmp add L3VPN support

pimd/pim_zebra.h
Removing the api pim_scan_individual_oil from .h since there is
no definition of it.
=> pimd: Remove the api from .h file since there is no definition of it

alpine/APKBUILD.in, docker/alpine/Dockerfile, docker/alpine/libyang/APKBUILD
We were using a locally built copy of libyang because it wasn't present in Alpine's repos for a while, but someone added it back in May, so we can use that again.
=> Update Alpine packaging foo + change docker images back over to Alpine-provided libyang

ldpd/adjacency.c
LDPD crashes when hold time is configured to 65535:
(gdb) bt
0  0x00007f8c3fc224bb in raise () from /lib64/libpthread.so.0
1  0x00007f8c4138a3dd in core_handler () from /lib64/libfrr.so.0
2  <signal handler called>
3  0x00007f8c3fc1ccc0 in pthread_mutex_lock () from /lib64/libpthread.so.0
4  0x00007f8c4139914b in thread_timer_remain_msec () from /lib64/libfrr.so.0
5  0x00007f8c41399209 in thread_timer_remain_second () from /lib64/libfrr.so.0
6  0x000000000040eb19 in adj_to_ctl ()
7  0x0000000000427b38 in ldpe_nbr_ctl ()
8  0x000000000042fd68 in control_dispatch_imsg ()
9  0x00007f8c4139a628 in thread_call () from /lib64/libfrr.so.0
10 0x00000000004265fc in ldpe ()
11 0x000000000040a68f in main ()
=> ldpd: Check if the thread is scheduled before calling for remained time

zebra/rt_netlink.c
Closes https://github.com/FRRouting/frr/issues/11624
=> zebra: Avoid buffer overflow using netlink_parse_rtattr_nested()

zebra/zebra_mpls.c
Closes https://github.com/FRRouting/frr/issues/11574
=> zebra: Cleanup the memory from the hash for MPLS stuff

pimd/pim_iface.c
The clear was happening only for PIMv4. Removed the PIMv4
check.
Fixes: #11628
=> pim6d: clear interface stats on interface shutdown

bgpd/bgp_vty.c
currently "show bgp summary" and "sho bgp summary wide" commands
provide a description string until a whitespace is occuring this
respectively with size limits of 20 and 60 chars
now theses two commands are providing strings with all
characters until the last witespace before size limit
=> bgp:change in showing neighbor description

bgpd/bgp_vty.c
Just fix the description because it's wrong.
=> bgpd: Show extended communities memory consumption

doc/developer/rcu.rst
On line 16 of this file following sentence has a typo.
> * once done, the updated copy is swapped in in a single
Remove unused "in" from document.
Signed-off-by: alireza <alirezaarzehgar82@gmail.com>
=> doc: Remove extra "in" from document

bgpd/bgpd.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_ap.c, bgpd/rfapi/rfapi_encap_tlv.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/vnc_export_bgp.c, bgpd/rfapi/vnc_export_table.c, lib/agentx.c, tests/topotests/bgp_snmp_mplsl3vpn/test_bgp_snmp_mplsvpn.py, zebra/rtadv.c
a) bgp_snmp_mplsl3vpn sometimes fails because the system is not necessarily up.  Give it some time to get there.
b) Cleanup commit to remove redundant code in setting the thread pointer to null( it already is )
c) bgp listener data is being leaked on shutdown
d) rfapi codes are asserting on memory failure to allocate( this is redundant )
e) Add a bit more information to operator when rtadv fails to properly create a socket.
=> Bunch of stuff found during testing.

tests/topotests/bgp_default_originate/bgp_default_originate_2links.json, tests/topotests/bgp_default_originate/test_bgp_default_originate_2links.py
test script covers
1. Default originate behaviour using  'network <x.x.x.x>' command
2. Default originate behaviour using aggregate summary command
Signed-off-by: ARShreenidhi <rshreenidhi@vmware.com>
=> tests: bgp default orignate behaviour on network commands

ospfd/ospf_lsa.c
The index about slots should be displayed as `slot`. Additionally, adjust format.
=> ospfd: correct one debug info for lsa

vtysh/vtysh.c
If we have `end` at the end of the frr.conf, then we never execute
XFRR_end_configuration command, and start/end markers do not work.
This leads to for example waiting BGP configuration parsing thread to hang,
and the peers are in shutdown state until the timer expires.
=> vtysh: Ignore `end` when parsing frr.conf

isisd/isis_cli.c
The php value is defined in yang but not properly set.
Fixes: 8f6c893629 ("isisd: add segment-routing CLI commands")
=> isisd: fix prefix-sid last-hop-behavior

bgpd/bgp_fsm.c, bgpd/bgp_io.c, bgpd/bgp_keepalives.c, bgpd/bgp_packet.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/vnc_zebra.c, doc/developer/locking.rst, lib/ferr.c, lib/frr_pthread.c, lib/hash.c, lib/log_filter.c, lib/privs.c, lib/stream.c, lib/thread.c, lib/zlog_targets.c, zebra/zebra_opaque.c, zebra/zebra_rib.c, zebra/zserv.c
convert:
frr_with_mutex(..)
to:
frr_with_mutex (..)
To make all our code agree with what clang-format is going to produce
=> *: frr_with_mutex change to follow our standard

bgpd/bgp_filter.c
=> bgpd: Call a hook when as-path filter is replaced

pathd/path_zebra.c, pathd/path_zebra.h, pathd/pathd.c
This handler code is used to stop zebra related contexts.
=> pathd: add a zebra stop handler

tests/topotests/bgp_default_route_route_map_match/r1/zebra.conf
Drop the static route for the r1 zebra config
=> topotests: Drop static route

bgpd/bgp_evpn.c, bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c
FRR should create a bnc per peer.  Not have
one's that write over others.  Currently when
FRR has multiple Interface based peering, BGP wa
creating a single BNC.  This is insufficient in that
we were accidently overwriting the one LL with other
data.  This causes issues when there are multiple and
there is weird starting issues with those interfaces
that you are peering over.
=> bgpd: LL peers need bnc's per peer

bgpd/bgp_filter.c
Before:
```
$ vtysh -c 'sh memory bgpd | include Temporary'; echo ; for x in $(seq 1 1000); do vtysh -c 'conf' -c 'bgp as-path access-list belekas permit wrong' >/dev/null; done; vtysh -c 'sh memory bgpd | include Temporary'
Temporary memory              :       19 variable       504       22       656
Temporary memory              :     1019 variable     24504     1023     24656
```
After:
```
$ vtysh -c 'sh memory bgpd | include Temporary'; echo ; for x in $(seq 1 1000); do vtysh -c 'conf' -c 'bgp as-path access-list belekas permit wrong' >/dev/null; done; vtysh -c 'sh memory bgpd | include Temporary'
Temporary memory              :       19 variable       504       22       656
Temporary memory              :       19 variable       504       24       680
```
Signed-off-by: Donatas …
=> bgpd: Free memory for as-path filter if regexp is wrong

bgpd/bgp_advertise.c, bgpd/bgp_advertise.h, bgpd/bgp_updgrp.c, bgpd/bgp_updgrp_adv.c
=> bgpd: Cleanup subgroup hash when we delete/merge a subgroup

bgpd/bgp_vty.c
commit: a486300b2679ff80a13d800ed76e1236edfcaa2b
introduced newlines in zlog_XX messaging.  Not allowed.
=> bgpd: Remove newlines from zlog, they are not allowed

pimd/mtracebis_netlink.c
Coverity is complaining that buf has not been initialized.
It has and coverity appears to be confused so let's help it
find the initialization.
=> pimd: Fix a couple coverity issues with mtracebis_netlink.c

tests/topotests/lib/common_config.py, tests/topotests/lib/pim.py, tests/topotests/lib/topogen.py, tests/topotests/lib/topojson.py, tests/topotests/lib/topotest.py, tests/topotests/multicast_pim_static_rp_topo1/multicast_pimv6_static_rp.json, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pimv6_static_rp.py
Enhanced few exsiting PIM APIs to support both
IPv4 and IPv6 configuration. Added few new APIs
for PIMv6. Tested all existing tests with new
API changes.
=> tests: [PIMv6] Added APIs for multicast PIMv6 config

bgpd/bgp_zebra.c
In commit: d70a31a3ef2b60d978b336d5cc9ee5e1ec079dfc
the Zapi ZEBRA_RULE_ADD message was modified but
the bgp version was not updated appropriately and
when zebra received the message it did not properly
read it.
=> bgpd: Fixup pbr rule changes that were missed

tools/gcc-plugins/frr-format.c, tools/gcc-plugins/gcc-common.h
check_function_arguments_recurse() has received a new function argument in GCC 12.  Fill it in and add a compatibility wrapper.
=> tools/gcc-plugins: make GCC 12 compatible

bgpd/bgp_bmp.c
bgp_node_lookup increments lock, we should decrement it after use.
=> bgpd: Unlock bgp_node after bgp_node_lookup

bgpd/bgp_vty.c
When using bgp_vty_afi_from_str it can
return AFI_MAX( but in practice never will with
our cli ).  In bgp_default_afi_safi_cmd the code
directly references:
bgp->default_afi[afi][safi] = TRUE;
and if afi is AFI_MAX FRRR would be accessing
memory where it should not be.
Let's just provide some assurances for coverity
that this never happens.
=> bgpd: Ensure we are not using AFI_MAX

isisd/isis_adjacency.c
adj->global_ipv6_addrs was not being freed on deletion
of the adjacency.
=> isisd: Prevent leak of global_ipv6_addrs

pimd/pim_nht.c
Topology:
R1(LHR) ---- R2 ----R4(FHR)
---- R3 ----
R2 = RP
Steps to reproduce:
1. R1(LHR) sends IGMP join, R4(FHR) sends multicast traffic.
Verify traffic is flowing from FHR to LHR.
2. Restart R1(LHR).
3. Below sequence of events are happening after FRR restart in R1(LHR).
4. R1(LHR) Register RP address to Zebra.
5. R1(LHR) Receive update from Zebra that R2(RP) is reachable via R3.
6. R1(LHR) Receive IGMP join for group 225.1.1.1, will create pim upstream
and (*,G) mroute with IIF towards R3.
7. R1(LHR) Receive update from Zebra that RP is reachable via R2(RP).
8. R1(LHR) Update the PIM upstream IIF, but not updating the (*,G) IIF
even there is RPF change.
9. R1(LHR) receives IGMP join for group 225.1.1.2, will create (*,G) with
IIF towards R2(RP), both upstream and (,G) created with IIF …
=> pimd: Update mroute IIF based on Nexthop received from Zebra

bgpd/bgp_vty.c
=> bgpd: Safi can be SAFI_MAX which would allow a write beyond alloced

doc/developer/topotests.rst
Updated /doc/topotests.rst with socat details,
which is needed to run PIMv6 tests. Socat tool
is used to send PIMv6 join and traffic.
=> doc: Update /doc/topotests.rst documentation

bgpd/bgp_bmp.c
fixes the recent support bmp monitor of VPNv4 afi/safi 
the bmp updates messages (MP_REACH_NLRI) are never sent for VPNv4 and bmp withdraws (MP_UNREACH_NRLI) are sent instead
this is caused by bgp_node_lookup which fails to find VPNv4 bgp_node in the rib which resulsts in NULL path info attributes passed to bmp_monitor
using bgp_afi_node_lookup instead of bgp_node_lookup in the case of vpn solves the problem
=> bgpd: fixed bmp vpnv4 monitoring sending withdraws instead of updates

lib/sockopt.c, lib/subdir.am
The format message checks done by clippy/xrelfo were still guarded
behind `--enable-dev-build`.  They've been clean and reliable, so it's
time to enable them unconditionally.
Fixes: #11680
=> build: unconditionally enable format checks

lib/link_state.c, lib/link_state.h
In CSPF topo test, valgrind detects uninitialized bytes when exporting TE
Opaque information through ZEBRA. This is due to C pragma compilation directive
`__attribute__(aligned(8))` in `struct ls_node_id` in `link_state.h`. Valgrind
consideris that struct ls_node_id nid = {} doesn't initialized the padding
bytes introduced by gcc.
This patch simply removes the C pragma compilation directive and also takes
opportunity to remove the transmission of remote node id for vertices and
subnets which is not known. Indeed, remote node id is only pertinent for
edges.
=> lib: Correct valgrind errors

ospf6d/ospf6_intra.c
For both router and network LSAs, combine the two conditions and process lsa
prefix uniformly.
=> ospf6d: combine two conditions for lsa prefix

qpb/qpb.h
`struct prefix` is a superset of `struct prefix_ipv4` and
`struct prefix_ipv6`.  Let's let coverity figure it out
=> qpb: Tell coverity the actual size we are copying

zebra/zebra_vxlan.c
The test case is with `redirect-off` in evpn multi-homing environment:
```
evpn mh redirect-off
```
After the environment is setup, do the following steps:
1) Let one member of ES learn one mac:
```
2e:52:bb:bb:2f:46 dev ae1 vlan 100 master bridge0 static
```
Now everything is ok and the mac can be synced to other ES peers.
2) Shutdown bond1. At this time, zebra will get three netlink messages,
not one as current code expected. Like:
```
e4:f0:04:89:b6:46 dev vxlan10030 vlan 30 master bridge0 static <-A
e4:f0:04:89:b6:46 dev vxlan10030 nhid 536870913 self extern_learn <-B
e4:f0:04:89:b6:46 dev vxlan10030 vlan 30 self <-C
```
With A), zebra will wrongly remove this mac again:
```
ZEBRA: dpAdd remote MAC e4:f0:04:89:b6:46 VID 30
ZEBRA: Add/update remote MAC e4:f0:04:89:b6:46 intf …
```
=> zebra: fix bond down for evpn-mh

bgpd/bgp_evpn_vty.c
bgpd was crashing every time `show bgp l2vpn evpn route rd` was issued
with an RD that didn't match "all".  This was introduced by 9b01d289883
which changed how argv_find() is handled in various vtysh commands, but
the new changes forgot a "!".  So let's re-add the "!".
Before:
```
ub20# show bgp l2vpn evpn route rd 399672:100
vtysh: error reading from bgpd: Resource temporarily unavailable (11)Warning: closing connection to bgpd because of an I/O error!
ub20#
ub20# show bgp l2vpn evpn route rd 399672:100 mac 11:11:11:11:11:11
vtysh: error reading from bgpd: Resource temporarily unavailable (11)Warning: closing connection to bgpd because of an I/O error!
ub20#
```
After:
```
ub20# show bgp l2vpn evpn route rd 399672:100
ub20#
ub20# show bgp l2vpn evpn route rd 399672:100 mac …
```
=> bgpd: fix show bgp l2vpn evpn route rd crashes

bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgp_route.h
Just drop the test and convert to void.
=> bgpd: bgp_best_path_select_defer never returns negative

lib/sockunion.c, pimd/pim_cmd_common.c, pimd/pim_instance.c, pimd/pim_instance.h, pimd/pim_register.c, pimd/pim_sock.c, pimd/pim_sock.h
The problem here is when the same node is FHR as well as RP,
then the node keeps on sending the register packet.
Register-stop is not sent as well.
This problem has occurred because the RP is the same node
and there is no socket created on loopback interface, so the
packet is never sent out and never received back on the same
node, so register recv could not be processed on the node and
hence no register-stop is sent.
Since register packets are unicast packets, its better to handle
the send of register packet via a separate register socket.
This fixes the problem mentioned above as well.
Fixes: #11331
=> pimd, pim6d: Send register msg via reg socket, solve FHR/RP same node issue

doc/user/ripd.rst
Current wording _implies_ `neighbor` updates are sent unicast; this makes it explicit.
Aside: what is the "Below is very simple RIP configuration" (lines 131-140) doing here?
=> doc/user/ripd: clarify unicast behaviour

bgpd/bgp_evpn_vty.c
Changed BUM flooding output in 'show bgp l2vpn evpn vni' from 'Head-end replication' to 'Enabled'
Signed-off-by: Pooja Doijode <pdoijode@nvidia.com>
=> bgpd: addition of vxlanFlooding field in show output

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
clear ipv6 pim [vrf NAME] interface traffic
=> pim6d: Implementing "clear ipv6 pim interface traffic" command.

bfdd/bfd_packet.c
When an interface does not have a mac address, don't
try to retrieve the mac address ( for it to just fail ).
Example interface:
sharpd@eva [2]> ip link show tun100
21: tun100@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/ipip 192.168.119.224 peer 192.168.119.120
Let's just notice that there is a NOARP flag and abort the call.
Fixes: #11733
=> bfdd: Some interfaces don't have mac addresses

bgpd/bgp_evpn.c, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_zebra.c
RFC 4760 states we SHOULD ignore the NEXT_HOP attribute for BGP Update
messages carrying only MP_REACH_NLRI attributes. Thus we should use the
Network Address of Next Hop field of the MP_REACH_NLRI as the nexthop.
Instead of always looking for BGP_ATTR_NEXT_HOP, this commit ensures:
1) we set mp_nexthop_len to BGP_ATTR_NHLEN_IPV4 for v4 bgp_static routes
2) we check mp_nexthop_len when choosing the nexthop to use for nht
3) we check mp_nexthop_len when choosing the nexthop to send to zebra
4) we check mp_nexthop_len when picking the nexthop to shown by vtysh
Reported-by: Binon Gorbutt <binon@aervivo.com>
=> bgpd: ignore NEXT_HOP for MP_REACH_NLRI

pimd/pim6_main.c
Debug pimv6 cli's are implemented.
Therefore removing this.
=> pim6d: Removing the temporary enabled debugs.

lib/termtable.h
there is no definition of ttable_cell_del(), thus remove its declaration.
Signed-off-by: Weiguo Li <liwg06@foxmail.com>
=> lib: Remove invalid function declaration

staticd/static_nb_config.c
There exists some nexthop attributes that are not the unique
part of the nexthop and if you change the static route
with those values then the route is not being updated
in zebra with the new values:
Example of brokenness:
eva# conf
eva(config)# ip route 1.2.3.9/32 192.168.119.1 enp39s0 label 16020
eva(config)# do show ip route 1.2.3.9
Routing entry for 1.2.3.9/32
Known via "static", distance 1, metric 0, best
Last update 00:00:05 ago
* 192.168.119.1, via enp39s0, label 16020, weight 1
eva(config)# ip route 1.2.3.9/32 192.168.119.1 enp39s0 label 16040
eva(config)# do show ip route 1.2.3.9
Routing entry for 1.2.3.9/32
Known via "static", distance 1, metric 0, best
Last update 00:00:12 ago
* 192.168.119.1, via enp39s0, label 16020, weight 1
Fixed behavior:
eva# conf
eva(config)# ip route …
=> staticd: When changing the underlying nh ensure it is reinstalled

bfdd/bfd.c, bfdd/bfd.h, bfdd/bfd_packet.c, bfdd/bfdd_vty.c, doc/user/bfd.rst
Add a send time into the BFD Echo packet.  When the BFD Echo
packet is received back store time it took in usec.   When
user issues a show bfd peer(s) command calculate and display
minimum, average, and max time it took for the BFD Echo packet
to be looped back.
Signed-off-by: Lynne Morrison <lynne.morrison@ibm.com>
=> BFDD: Add RTT to BFD IPV4 Echo packet processing

zebra/interface.c
When moving an interface between vrf's we do not need
to install the connected routes multiple times.
eva# show ip route vrf all
T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
F - PBR, f - OpenFabric,
VRF BLUE:
C>* 4.5.6.7/32 is directly connected, dummy7, 00:00:10
VRF default:
K>* 0.0.0.0/0 [0/100] via 192.168.119.1, enp39s0, 00:00:10
C>* 192.168.119.0/24 is directly connected, enp39s0, 00:00:10
eva# exit
sharpd@eva ~/f/t/topotests (multiple_connected_installs)> sudo ip link add GREEN type vrf table 11000
sharpd@eva ~/f/t/topotests (multiple_connected_installs)> …
=> zebra: Don't install connected routes multiple times into FRR

bgpd/bgp_conditional_adv.c, bgpd/bgp_route.c, bgpd/bgp_updgrp.c
A couple of fixes for bgp conditional advertisement, mostly authored by Quentin:
- The new outbound filter to apply conditional advertisement policy was not working properly due to complications with update groups. The two routemaps were properly copied into the update group peer filter but not the conditional advertisement state. If the adv state changes, that will change the update_group's hash, so ensure that the peer/update_group/subgroup relationships are updated.
- If we have conditional advertisement enabled, and conditionally withdrew some prefixes, and then we do a 'clear bgp', those routes were getting advertised again, and then withdrawn the next time the conditional advertisement scanner executed. When we go to advertise check the prefix against the conditional advertisement …
=> bgpd: conditional adv fixes

zebra/zebra_pw.c
I am seeing the zebra_pw_install_retry timer thread crashing
on shutdown
The shutdown of the timer is only in an
if () {
...
} else if
Let's just always shut it down.
=> zebra: Fix crash in shutdown w/ pw thread still running

bgpd/bgpd.c, bgpd/bgpd.h
The output is not checked, we can have void instead.
=> bgpd: Convert some int functions to void

redhat/frr.spec.in
=> redhat: Drop --enable-systemd from build specification

ospf6d/ospf6_interface.c
After all needed interfaces ( for example: interface "a1", vrf "vrf1", and
"a1" is binded to "vrf1" ) are ready/created, then restart/start frr. zebra
at startup will call `netlink_interface()` to process all interfaces and notify
all clients, but its calling `get_iflink_speed()` maybe fails for unexpected
order of the coming interfaces: when processing "a1", "vrf1" maybe is unknown
at that time. `if_zebra_speed_update()` timer is introduced to deal with this
order problem.
Currently only ospfd and ospf6d deal with this speed change to recalculated
route cost. ospfd can deal with this change, but ospf6d will wrongly missed it.
Since both `ipv6 ospf6 cost COST` and `auto-cost reference-bandwidth COST` are
not set, cost of this ospf6d interface should be calculated with interface
speed, but …
=> ospf6d: fix missing cost change

ospf6d/ospf6_interface.c, tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
=> ospf6d: Remove ospf6Enabled from JSON output

ospf6d/ospf6_message.c, ospfd/ospf_flood.c, ospfd/ospf_interface.c, ospfd/ospf_interface.h, ospfd/ospf_nsm.c, ospfd/ospf_packet.c, ospfd/ospf_sr.c, ospfd/ospf_vty.c
a) Clean up ospf_write to be a bit more permissive in sending of data to our peers. 
b) Cleanup indentation
c) When a neighbor goes down, look at any other neighbors on that same interface and if none of them are in a state where packets could be sent, cleanup the oi->obuf queue
d) Just some refactoring
=> Ospf packet helper

zebra/zebra_vxlan.c
These moved mac addresses are actually in active status during moving
phase, just correct comment.
=> zebra: correct one comment for evpn-mh

zebra/if_netlink.c
`get_iflink_speed()` uses ioctl to get speed, not ip address. Additionally
adjust format for another one comment line.
=> zebra: correct one comment about ethtool ioctl

doc/user/bgp.rst
It's an invalid command, probably copy/paste error.
=> doc: Drop `deny` rules from BGP community-list example

include/linux/pkt_cls.h, zebra/debug_nl.c, zebra/dplane_fpm_nl.c, zebra/interface.c, zebra/kernel_netlink.c, zebra/kernel_socket.c, zebra/rt.h, zebra/subdir.am, zebra/tc_netlink.c, zebra/tc_netlink.h, zebra/tc_socket.c, zebra/zebra_dplane.c, zebra/zebra_dplane.h, zebra/zebra_nhg.c, zebra/zebra_rib.c
This PR is supposed to add traffic control netlink APIs, contexts, and its main handling parts to zebra.
=> zebra: add basic traffic control API

pimd/pim_sock.c
The socket created for pimv6 was created using AF_INET for PIMV6
too.
Since the api pim_reg_sock is common to both PIMv4 and PIMv6,
need to use PIM_AF instead of AF_INET.
Fixes: #11815
=> pim6d: Register message getting dropped in source node, mroute stuck in RegJ

zebra/zebra_script.c
Add TC handlers in script code and move non-handled
code together.
=> zebra: add TC handlers in script code

zebra/tc_netlink.c, zebra/zebra_dplane.c
zebra: fix deadcodes in tc dplane & netlink
=> zebra: fix deadcodes in tc dplane & netlink

tools/frrcommon.sh.in
When stopping the FRR daemons, stop zebra last, after trying to stop the other daemons.
=> tools: stop zebra daemon last

pimd/pim6_mld.c, pimd/pim_addr.h, pimd/pim_iface.c, pimd/pim_nb_config.c, pimd/pim_vty.c
=> pim6d: Completing "ipv6 mld" config command.

zebra/kernel_socket.c, zebra/redistribute.c, zebra/rib.h, zebra/rt_netlink.c, zebra/zapi_msg.c, zebra/zebra_mpls.c, zebra/zebra_mpls.h, zebra/zebra_rib.c
Reworking of how routes and labels are handled for processing in FRR.
Effectively route add/deletion and label processing from upper level protocols have been added to the metaQ for serialization.  I have done this for 2 reasons:
a) There is a bug when you do this:
sharpd@eva ~/frr (metaq_processing)> sudo ip nexthop add id 5052 via 192.168.119.44 dev enp39s0 ; sudo ip route add 10.0.0.9 nhid 5052
sharpd@eva ~/frr (metaq_processing)> vtysh -c "show ip route 10.0.0.9"
Routing entry for 0.0.0.0/0
Known via "kernel", distance 0, metric 100, best
Last update 00:00:26 ago
* 192.168.119.1, via enp39s0
sharpd@eva ~/frr (metaq_processing)> ip route show 10.0.0.8
10.0.0.8 nhid 5051 via 192.168.119.44 dev enp39s0 
In order to fix this route processing needs to happen after nexthop group processing( …
=> Metaq processing

zebra/zebra_dplane.c
zebra: trim unused tc dplane result values
=> zebra: trim unused tc dplane result values

debian/control
FRR only needs lua library (package libluaX.Y-dev) to be compiled and
linked, but its `configure` script makes use of lua interpreter to
perform its checks. Therefore, `luaX.Y` package is a requisite
build-dependency for debian packaging.
This commit adds the debian package with the lua interpreter to the
build dependencies.
Closes: #11834
Signed-off-by: Eugene Crosser <crosser@average.org>
=> debian: add lua _binary_ to build dependencies

tests/topotests/conftest.py, tests/topotests/lib/topogen.py
Also print runtime directory for topotests if the error occurs.
=> tests: Log as error if some of the daemons are missing

ospf6d/ospf6_abr.c
Fix issue #11839.
When the user defines a range in an area other than the backbone area, the
summary route will be announced to the backbone area as an inter-area LSA.
However, if the prefix defined in the range is the same prefix as a connected
route in that area, the LSA won't be announced to the backbone area.
This is because when ospf6d is originating the summary route for the
intra-area route, it finds the range configured by the user and tries to
suppress the route by deleting the existing summary route, which happens to be
the one created by the range.
Although the range definition is not necessary in this case, it should not
fail this use case. So let's just keep the summary route there if it is
created from the user defined range.
=> ospf6d: Don't remove summary route if it is a range

nhrpd/nhrp_interface.c
1. Run frr:
interface enp0s8
ip address 193.168.1.2/24
exit
!
interface gre1
ip address 10.8.1.2/32
ip nhrp network-id 1
ip nhrp nhs dynamic nbma 193.168.1.1
tunnel source enp0s8
exit
Log:
NHS: Register 10.8.1.2 -> 10.8.1.2 (timeout 2)
Send Registration-Request(3) 10.8.1.2 -> 10.8.1.2
Recv Registration-Reply(4) 10.8.1.1 -> 10.8.1.2
2. Create VRF and move enp0s8 to VRF
ip link set enp0s8 master vrf1
Before patch:
NHS: Waiting link for 193.168.1.1
After patch:
NHS: Register 10.8.1.2 -> 10.8.1.2 (timeout 2)
=> nhrpd: Use nhrp_interface_update_nbma when source vrf was changed

ospfd/ospf_vty.c
Description:
Per neighbor GR enabled information is  missing from json
output in "show ip ospf gr helper details json" command.
Example config:
frr(config-router)# graceful-restart helper enable 2.2.2.2
frr(config-router)#
frr(config-router)# do show ip ospf  graceful-restart helper  detail
OSPF Router with ID (10.112.156.220)
Graceful restart helper support disabled.
Strict LSA check is enabled.
Helper supported for Planned and Unplanned Restarts.
Supported Graceful restart interval: 1800(in seconds).
Enable Router list:
2.2.2.2,
frr(config-router)# do show ip ospf  graceful-restart helper  detail json
{
"routerId":"10.112.156.220",
"helperSupport":"Disabled",
"strictLsaCheck":"Enabled",
"restartSupoort":"Planned and Unplanned Restarts",
"supportedGracePeriod":1800, …
=> ospfd: Adding per neighbour json details to GR helper detail command

gdb/lib.txt
Add a macro to walk all memory allocations in a core file.
load the file in gdb:
source /path/to/frr/gdb/lib.txt
mg_walk mg_first
(gdb) mq_walk mg_first
showing active allocations in memory group libfrr
memstats: BFD info:0
memstats: Buffer:5
memstats: Buffer data:0
memstats: Host config:6
memstats: Completion item:0
memstats: Command Tokens:2585
memstats: Command Token Text:1951
memstats: Command Token Help:1951
memstats: Command Argument:0
memstats: Command Argument Name:575
memstats: Command Match Stack:0
memstats: Lexer token (temporary):0
memstats: Path Computation Algorithms:0
memstats: Distribute ctx:0
memstats: Distribute list:0
memstats: Dist-list ifname:0
memstats: Dist-list name:0
memstats: error information:0
memstats: Access List:0
memstats: Access List Str:0
memstats: Access …
=> gdb: Add a macro to walk memory allocations

doc/user/pimv6.rst, pimd/pim6_mld.c, pimd/pim_cmd.c, pimd/pim_igmp.c, pimd/pim_instance.h
This CLI displays the MLD group information.
Modified the igmp_group_count of struct pim_instance to gm_group_count
to be used for both IGMP and MLD.
=> pim6d: Implementing "show ipv6 mld groups" CLI

pimd/pim_addr.h, pimd/pim_sock.c
IPv4 and IPv6 behaves a little bit differently with the socket
options.
IPPROTO_RAW socket option is only for IPv4.
Therefore the register packet was not properly getting encapculated
for PIMv6 and was working fine for PIMv4.
So have used IPPROTO_PIM for PIMv6.
Fixes: #11846
=> pim6d: mroute stuck in register state, multicast traffic getting drops

bgpd/bgp_vty.c, bgpd/bgp_zebra.c, lib/zclient.c, sharpd/sharp_vty.c, zebra/zebra_srv6.c
Running `srv6_locator`, `zebra_seg6local_route`, `bgp_srv6l3vpn_to_bgp_vrf` and `bgp_srv6l3vpn_to_bgp_vrf2` topotests with `--valgrind-memleaks` gives many memory leak errors (reported below).
This patch fixes several memory leaks related to the SRv6 implementation. Details of the memory leaks and how they were fixed are provided in the commit messages.
```
==270435== 96 bytes in 6 blocks are definitely lost in loss record 112 of 207
==270435==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==270435==    by 0x48F34A3: qcalloc (memory.c:116)
==270435==    by 0x236740: ensure_vrf_tovpn_sid (bgp_mplsvpn.c:611)
==270435==    by 0x23AE2F: vpn_leak_postchange (bgp_mplsvpn.h:252)
==270435==    by 0x23AE2F: vpn_leak_postchange (bgp_mplsvpn.h:227) …
```
=> *: Fix several memory leaks in SRv6 implementation

pimd/pim_cmd_common.c
2022-08-18 04:57:32,376 - ERROR: Found memory leak in daemon pimd
2022-08-18 04:57:32,377 - ERROR: ==12100== 18,978 (144 direct, 18,834 indirect) bytes in 2 blocks are definitely lost in loss record 45 of 45
2022-08-18 04:57:32,377 - ERROR: ==12100==    at 0x4C31FAC: calloc (vg_replace_malloc.c:762)
2022-08-18 04:57:32,377 - ERROR: ==12100==    by 0x532F51F: json_object_new_object (in /lib/x86_64-linux-gnu/libjson-c.so.3.0.1)
2022-08-18 04:57:32,377 - ERROR: ==12100==    by 0x128B5C: pim_show_interfaces (pim_cmd_common.c:3395)
2022-08-18 04:57:32,377 - ERROR: ==12100==    by 0x15A86B: show_ip_pim_interface_magic (pim_cmd.c:3127)
2022-08-18 04:57:32,377 - ERROR: ==12100==    by 0x15A86B: show_ip_pim_interface (pim_cmd_clippy.c:324)
2022-08-18 04:57:32,377 - ERROR: ==12100==    by …
=> pimd, pim6d: deleting the memory malloced for json.

ospfd/ospf_lsa.c
Description:
ospf process is crashing when  the current router acts
as GR helper and it received a new lsa.
Here, ospf_lsa_different() is being called without checking
'old' pointer. It is asserted in ospf_lsa_different() api
if the 'old' pointer is NULL.
corrected this by validaing old pointer before calling
ospf_lsa_different() api.
back tarce:
Program terminated with signal SIGABRT, Aborted.
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[Current thread is 1 (Thread 0x6b84348827c0 (LWP 3155))]
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
1  0x00006b8433aa4801 in __GI_abort () at abort.c:79
2  0x00006b8433a9439a in __assert_fail_base (fmt=0x6b8433c1b7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", …
=> ospfd: crash when router acts as GR helper upon a topo change

configure.ac
main is not a function found in libreadline, its better to check for a
function thats provided by it.
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> configure: Check for readline() function instead of main

zebra/zebra_vxlan.c
zebra can change l2vni's tenant vrf with new `vid`, and then notify bgpd
to change also. But this notification is wrongly missed, so bgpd knows
nothing about it. It affects evpn routes, which are related to tenant vrf.
Need to notify bgpd of the `vid` change.
Changes l2vni 100 of vxlan's `vid` so as to change its svi interface from
default to vrf1, then check bgp's vni status.
Before: (Ignored irrelevent columns)
```
host#show bgp l2vpn evpn vni
VNI      Type RD                    Tenant VRF
* 100      L2   66.66.66.66:2         default <- No change
```
After:(Ignored irrelevent columns)
```
host#show bgp l2vpn evpn vni
VNI      Type RD                   Tenant VRF
* 100      L2   66.66.66.66:2        vrf1 <- Updated
```
=> zebra: fix missing tenant vrf change notification

lib/thread.c
A couple of pointers in do_thread_cancel() were only inited at the start of the function; make sure they're inited during each iteration of the loop.
=> lib: ensure locals are inited to NULL

pimd/pim_neighbor.c, pimd/pim_neighbor.h
pim_neighbor_find_prefix function is no more used. Removing it.
=> pimd: Removal of unused function pim_neighbor_find_prefix

pimd/pim6_mld.c, pimd/pim_iface.c, pimd/pim_igmp.c, pimd/pim_igmpv2.c, pimd/pim_igmpv3.c, pimd/pim_mroute.c, pimd/pim_vty.c, pimd/pimd.h
Changing the below macros to common 
PIM_DEBUG_IGMP_EVENTS to PIM_DEBUG_GM_EVENTS
PIM_DEBUG_IGMP_PACKETS to PIM_DEBUG_GM_PACKETS
so that it can be used for both IGMP and MLD debugs.
Issue: #11895
=> pimd, pim6d: Changing IGMP to GM in debug macros

isisd/isis_circuit.c, isisd/isis_nb_config.c, isisd/isis_sr.c, isisd/isis_te.c, isisd/isis_te.h, isisd/isis_tlvs.c, isisd/isis_tlvs.h, isisd/isisd.c
Running most of isisd tests with --valgrind-memleaks give many memory errors.
This is due to the way isisd is stopped: performing a "no router isis XXX"
through CLI solves most of them. Indeed, `isis_finish()` doesn't call
`isis_area_destroy()` leaving many allocated memory not freed.
This patch adds call to appropriate delete functions or XFREE() when necessary
to properly free all allocated memory before terminating isisd.
=> isisd: Correct Valgrind errors

ospfd/ospf_lsa.c, ospfd/ospf_lsa.h, ospfd/ospf_vty.c, ospfd/ospfd.c, ospfd/ospfd.h
Description:
Added hidden clis that will allow you to reset the default timers
for LSA refresh and LSA maxage remove delay, these will help in testing
LSA refresh scenarios in upcoming OSPFv2 Flood reduction feature(rfc4136).
IETF Link : https://datatracker.ietf.org/doc/html/rfc4136
Signed-off-by: Manoj Naragund  <mnaragund@vmware.com>
=> ospfd: Added clis to change default timers for LSA refresh and maxage remove delay.

ospfd/ospf_spf.c
It is not possible to build ospf_spf.c file with --disable-ospfapi because
ospf_apiserver.c has SUPPORT_OSPF_API around all function definitions and
that results in an undefined reference to the ospf_apiserver_notify_reachable
function error while building.
Signed-off-by: Michal Ruprich <mruprich@redhat.com>
=> ospfd: Adding SUPPORT_OSPF_API define in ospf_spf.c

lib/zlog.c
Replace all of the path name with macro, only the two places.
=> lib: replace one path with macro

zebra/zebra_vrf.c
When using namespace VRF backend, and frr.conf contains:
vrf test
netns /run/netns/test
exit-vrf
FRR fails to start:
line 11: Failure to communicate[13] to zebra, line:  netns /run/netns/test
Fix this by returning CMD_WARNING rather than CMD_WARNING_CONFIG_FAILED when the same netns path is configured.
=> zebra: Reconfiguring netns for vrf is not a failure

tests/topotests/conftest.py
`--collect-only` does not run any tests, so bypass env checks for it.
---
`python3 -m pytest --collect-only` is useful to get a list of all the tests.
=> topotests: ignore env for pytest --collect-only

bgpd/bgp_keepalives.c
If logging to files is enabled, the RCU sweeper background pthread is responsible for closing old files' fds after log-rotation. Pthreads that don't run in the libfrr event loop, like the bgp keepalive pthread, are holding their per-pthread rcu lock, preventing that rcu pthread from closing old files. Don't hold the rcu lock in the bgp keepalive pthread: it blocks the rcu pthread and prevents log-file deletion.
=> bgpd: release rcu lock in bgp keepalive pthread

pimd/pim6_mld.c
Added Robustness value, Query interval, Query response timer
and Last member query interval field in json output.
Issue: https://github.com/FRRouting/frr/issues/11891
=> pim6d: Adding additional details for "show ipv6 mld interface [ifname] json" command.

zebra/kernel_netlink.c
To resolve link dependencies of unordered interfaces, the commit                                                                                                             
`520ebf72b27c2462ce8b0dc5a1d4cb83956df69c` has separated assignment of                                                                                                       
`zif->link_ifindex` and `zif->link` from `netlink_interface()` during startup.                                                                                               
The fixup stage of `zebra_if_update_all_links()` goes into the last of                                                                                                       
`interface_lookup_netlink()`, it can't be executed in the case of error in …
=> zebra: fix broken evpn

bgpd/bgp_labelpool.c, bgpd/bgp_labelpool.h, bgpd/subdir.am, lib/bitfield.h, tests/topotests/bgp_lu_topo1/R1/labelpool.summ.json, tests/topotests/bgp_lu_topo2/R1/labelpool.summ.json
For issue #11825
- double the size of each new chunk request from zebra
- use bitfields to track label allocations in a chunk
- When allocating:
- skip chunks with no free labels
- search biggest chunks first
- start search in chunk where last search ended
- Improve API documentation in comments (bgp_lp_get() and callback)
- Tweak formatting of "show bgp labelpool chunks"
- Add test features (compiled conditionally on BGP_LABELPOOL_ENABLE_TESTS)
=> bgpd: improve labelpool performance at scale

bgpd/bgp_io.c, bgpd/bgp_packet.c, bgpd/bgp_packet.h
The "bgp_notify_" apis in bgp_packet.c generate a notification to a peer, usually during error handling. The io pthread wants to send notifications in a couple of cases during early received-packet validation - but the existing api interacts with the peer struct itself, and that's not safe across the two pthreads.
Add a new api for use by the io pthread, and adjust the main notify api so that it can avoid touching the peer struct.
Fixes: #11698
=> bgpd: avoid notify race between io and main pthreads

pimd/pim6_mld.c, pimd/pim_igmp.c, pimd/pim_igmpv2.c, pimd/pim_igmpv3.c, pimd/pim_nb_config.c, pimd/pim_tib.c, pimd/pim_vty.c, pimd/pimd.h
Changed PIM_DEBUG_IGMP_TRACE to PIM_DEBUG_GM_TRACE and PIM_DEBUG_IGMP_TRACE_DETAIL to PIM_DEBUG_GM_TRACE_DETAIL. Hence, these macros can be used for both v6 and v4.
Issue: #11895
Co-authored-by: Sai Gomathi N <nsaigomathi@vmware.com>
=> pimd, pim6d: Changing IGMP to GM in debug macros.

pimd/pim_iface.c
In function pim_if_delete, pim_ifp->bfd_config.profile needs to be freed.
=> pimd: Fix memleak in bfd profile

lib/plist.c
When bulk deleting prefix lists on shutdown the code was calling plist_delete, which removed the item
from the master->str list, and then popping the next item on the list and just dropping it on the floor. The pop is not needed.
=> lib: Fix skip of every other plist deletion

pimd/pim_nb_config.c
When there is update in the configuration of last_member_query_interval
and last_member_query_count, call gm_ifp_update().
This will update cur_query_intv_trig and cur_lmqc of gm_ifp structure.
Issue: #11901
=> pim6d: Update last_member_query_interval and last_member_query_count

pimd/pim6_mld.c
CID 1519843 (#2 of 2): Uninitialized scalar variable (UNINIT)
43. uninit_use_in_call: Using uninitialized value pkt_src->sin6_addr when calling gm_rx_process
=> pim6d: Fixing coverity issues for pim6_mld.c

bgpd/bgp_packet.c, bgpd/bgpd.h
See the BGP message sequence:
R1                  R2
|      updates      |
|------------------>|
|                   |
|  refresh request  |
x<------------------|
|                   |
|   updates cont.   |
|------------------>|
|                   |
|    end-of-rib     |
|------------------>|
|                   |
When R1 and R2 establish BGP session, R1 begins to send initial updates. If R2 sends a route-refresh request before EoR, it's silently ignored by R1, and routes received earlier have no chance to be processed again.
RFC7313 says, "for a BGP speaker that supports the BGP Graceful Restart, it MUST NOT send a BoRR for an <AFI, SAFI> to a neighbor before it sends the EoR for the <AFI, SAFI> to the neighbor." But it doesn't forbid route-refresh request to be sent before receiving …
=> bgpd: Handle route-refresh request received before EoR

pimd/pim_iface.c
After restart pim dr address was zero due to which pim (*,G) join could not get propagated towards RP.
While trying to find primary address ll_highest will be zero initially, since we have not received address from zebra yet.
So we can get the best address at this point and use it as primary address whenever ll_highest is zero.
Fixes: #11925
=> pim6d: (*,G) mroutes not learnt after pim6d daemon restart

pimd/pim_iface.c, pimd/pim_igmp.h, pimd/pim_vty.c, pimd/pimd.h
Changing
IGMP_DEFAULT_ROBUSTNESS_VARIABLE to GM_DEFAULT_ROBUSTNESS_VARIABLE,
IGMP_GENERAL_QUERY_INTERVAL to GM_GENERAL_QUERY_INTERVAL,
IGMP_QUERY_MAX_RESPONSE_TIME_DSEC to GM_QUERY_MAX_RESPONSE_TIME_DSEC and
IGMP_SPECIFIC_QUERY_MAX_RESPONSE_TIME_DSEC to GM_SPECIFIC_QUERY_MAX_RESPONSE_TIME_DSEC
to accomodate both igmp and mld.
=> pimd, pim6d: Changing IGMP to GM in few macro's.

pathd/path_ted.c
Fix the 'no mpls-te on' command.
=> pathd: 'no mpls-te on' command was not working

isisd/isis_nb_config.c, isisd/isisd.c, isisd/isisd.h
==2623619==
==2623619== 6 bytes in 1 blocks are definitely lost in loss record 3 of 75
==2623619==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==2623619==    by 0x4B55E4A: strdup (strdup.c:42)
==2623619==    by 0x493C992: qstrdup (memory.c:128)
==2623619==    by 0x1A9212: isis_instance_fast_reroute_level_1_remote_lfa_prefix_list_modify (isis_nb_config.c:1599)
==2623619==    by 0x494837C: nb_callback_modify (northbound.c:1083)
==2623619==    by 0x4948C6E: nb_callback_configuration (northbound.c:1352)
==2623619==    by 0x494919D: nb_transaction_process (northbound.c:1473)
==2623619==    by 0x4947DA9: nb_candidate_commit_apply (northbound.c:906)
==2623619==    by 0x4947EBA: nb_candidate_commit (northbound.c:938)
==2623619==    by 0x494EB9E: nb_cli_classic_commit (northbound_cli.c:64) …
=> isisd: Fix memory leak on shutdown with prefix lists

pimd/pim6_mld.c
Issue:
frr# show ipv6 mld 
interface   All VRFs
Fix:
frr# show ipv6 mld
interface   MLD interface information
Keeping "show ipv6 mld interface" cmd similar as "show ip igmp interface" cmd.
=> pim6d: "show ipv6 mld interface" command

bgpd/bgp_debug.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_vty.c, bgpd/bgp_nexthop.c, bgpd/bgp_nht.c, bgpd/bgp_rd.c, bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/rfapi/bgp_rfapi_cfg.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c, bgpd/rfapi/rfapi_vty.h, lib/prefix.h
Convert a bunch of prefix_rd2str() for json/vty stuff.
=> bgpd: Use %pRD for prefix_rd2str()

bgpd/bgp_ecommunity.c, bgpd/bgp_fsm.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_packet.c, bgpd/bgpd.c
1) In ecommunity_del_val(), ecommunity was not being freed
when the last value in the ecommunity was being deleted.
2) Memory allocated when 'import vrf route maps <>' is configured,
wasn't being deleted when the entire bgp config was deleted through 'no router bgp'.
3) When router id is changed through config, new RD is auto generated.
However new export RT was being assigned without freeing
the older RT from VRF.
Signed-off-by: Samanvitha B Bhargav <bsmanvitha@vmware.com>
=> bgpd: multiple memory leak issue fixes

doc/user/vtysh.rst
Docs were recommending both integrated and non-integrated config in different sections.  Remove the recommendation for non-integrated config from vtysh.rst.
=> doc: Align docs to recommend integrated config

ospfd/ospf_vty.c
=> ospfd: Remove deprecated command `graceful-restart helper-only`

pimd/pim6_mld.c
=> pim6d: Adding last member query count field in "show ipv6 mld interface [ifname] json" command.

pathd/path_ted.c
This commit is dedicated to fix some issues in path_ted_query_type_f
function. Issues are related to IPv6 implementation.
-key is not based on the pertinent part of IPv6 address.
-test on memcmp return value is mismatch.
-wrong flag value tested (ipv4 against ipv6).
-return adj_sid was the wrong one.
Signed-off-by: Francois Dumontet francois.dumontet@6wind.com
=>  pathd: nai adjacency fix query type f for IPV6

bgpd/bgp_route.c
Before:
```
2022/09/26 10:13:35.261 BGP: [QCZ1W-VKS36] 192.168.0.1(r0) sending REFRESH_REQ for afi/safi: IPv4/unicast
2022/09/26 10:13:35.262 BGP: [VF3QY-FP1PP] 192.168.0.1: route-refresh for IPv4/unicast, marking prefix 172.16.1.1/32 as stale
2022/09/26 10:13:35.262 BGP: [VF3QY-FP1PP] 192.168.0.1: route-refresh for IPv4/unicast, marking prefix 192.168.0.0/24 as stale
2022/09/26 10:13:35.262 BGP: [SDZS7-XVC4W] 192.168.0.1(r0) rcvd route-refresh (BoRR) for IPv4/unicast, triggering timer for 360 seconds
2022/09/26 10:13:35.362 BGP: [Y6XKR-PF89P] 192.168.0.1(r0) rcvd route-refresh (EoRR) for IPv4/unicast, stopping BoRR timer
```
=> bgpd: Print hostname for peer as well when marking as stale for route-refresh

vtysh/vtysh_config.c
vtysh was not properly handling the `service cputime-XXX` commands in output when multiple daemons are running.
=> Cputime stats

vtysh/vtysh_config.c
Before:
```
donatas-pc# sh run | include allow-reserved-ranges
allow-reserved-ranges
allow-reserved-ranges
allow-reserved-ranges
allow-reserved-ranges
allow-reserved-ranges
allow-reserved-ranges
donatas-pc#
```
=> vtysh: Show allow-reserved-ranges once in config

lib/mgmt_fe_client.c, lib/mgmt_fe_client.h, lib/vty.c
Description:
Have observed an inavalid memory access during the following scenario.
when "write memory" command issued, it will create a vty pointer and
collect all configurations , write to a file and then close the vty
pointer.
Here when vty pointer created, mgmt session is created by updating the mgmtd
session with vty pointer and send the session request to mgmtd fe_adapter.
Session_id details will be updated to the session structure once ack received
from frontend adapter.
As part of vty_close, the correspodning mgmt session should be destroyed before
cleaning up the client pointer.i.e here vty.
Here, before even receiving the ack from adapter, this vty_close called and vty freeed.
Anyhow, session is not be distroyed because it is relayed on session_id which
is expected to be updated …
=> mgmtd: Fixing invalid memory writes

pimd/pim6_main.c, pimd/pimd.h
Proof:
eva# conf
eva(config)# no service integrated-vtysh-config
eva(config)# end
eva# wr mem
Note: this version of vtysh never writes vtysh.conf Building Configuration...
Configuration saved to /etc/frr/zebra.conf
Configuration saved to /etc/frr/ripd.conf
Configuration saved to /etc/frr/ripngd.conf
Configuration saved to /etc/frr/ospfd.conf
Configuration saved to /etc/frr/ospf6d.conf
Configuration saved to /etc/frr/bgpd.conf
Configuration saved to /etc/frr/isisd.conf
Configuration saved to /etc/frr/pimd.conf
Configuration saved to /etc/frr/nhrpd.conf
Configuration saved to /etc/frr/eigrpd.conf
Configuration saved to /etc/frr/babeld.conf
Configuration saved to /etc/frr/sharpd.conf
Configuration saved to /etc/frr/fabricd.conf
Configuration saved to /etc/frr/pbrd.conf
Configuration saved to …
=> pimd: Allow v6 to do non-integrated configuration

bgpd/bgp_vty.c
Noticed a typo in the definition of
show_ip_bgp_neighbors_graceful_restart function.
Signed-off-by: Michal Ruprich <mruprich@redhat.com>
=> bgpd: show ip bgp neighbors graceful-restart typo

isisd/fabricd.c
When fabricd is configured to use an interface and there will be no peers out that interface, the log file is filling up with:
Oct 04 10:50:03 host2 fabricd[1444769]: [HHXDJ-1DA93] ISIS-Adj (1): Threeway state change Initializing to Up Oct 04 10:50:03 host2 fabricd[1444769]: [R18GA-MS9R7] OpenFabric: Started initial synchronization with 1111.1111.1111 on enp1s0f1np1 Oct 04 10:50:06 host2 fabricd[1444769]: [HHXDJ-1DA93] ISIS-Adj (1): Threeway state change Up to Initializing Oct 04 10:50:07 host2 fabricd[1444769]: [NT6J7-1RYRF] OpenFabric: Initial synchronization on enp1s0f1np1 timed out! Oct 04 10:50:07 host2 fabricd[1444769]: [R18GA-MS9R7] OpenFabric: Started initial synchronization with 3333.3333.3333 on enp1s0f0np0 Oct 04 10:50:08 host2 fabricd[1444769]: [HHXDJ-1DA93] ISIS-Adj (1): …
=> fabricd:  Turn off excessive logging when peering will not come up

zebra/rtadv.c
Couple commits here to improve our logging of RAs.
1) When we detect a mismatch in local/received values, include those values in the log
2) Exclude Retrans Timer inconsistencies from system logging if one of the values is 0 per RFC 4861
=> RA logging improvements

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_addr.h, pimd/pim_vty.c
Adding the following debug clis for mld
[no] debug mld
[no] debug mld events
[no] debug mld packets
[no] debug mld trace
[no] debug mld trace detail
Issue: #11895
=> pim6d: Adding new Debug CLI for MLD

pimd/pim_hello.c, pimd/pim_tlv.c, pimd/pim_tlv.h
Fixed as per rfc7761 section 4.3.1.
"""
Sending Hello Messages
The Address List option advertises all the secondary addresses associated with the source interface of the router originating the message.  The option MUST be included in all Hello messages if there are secondary addresses associated with the source interface and MAY be omitted if no secondary addresses exist.
"""
Issue: #12015
=> pimd, pim6d: send secondary address in PIM hello packet

bgpd/bgp_zebra.c, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ebgp_unnumbered_nbr.py
When primary global v6 unicast address is configured on an
unnumbered interface, BGP does not re-advertise updates out
with the new global v6 address as the nexthop
Signed-off-by: Pdoijode <pdoijode@nvidia.com>
=> bgpd: BGP does not update next-hop when global V6 address is configured

bgpd/bgpd.c, tests/topotests/bgp_gr_restart_retain_routes/r1/bgpd.conf, tests/topotests/bgp_gr_restart_retain_routes/r1/zebra.conf, tests/topotests/bgp_gr_restart_retain_routes/r2/bgpd.conf, tests/topotests/bgp_gr_restart_retain_routes/r2/zebra.conf, tests/topotests/bgp_gr_restart_retain_routes/test_bgp_gr_restart_retain_routes.py
Fixes https://github.com/FRRouting/frr/issues/12030
=> bgpd: Do not send Deconfig/Shutdown message when restarting

lib/typesafe.h, tests/lib/test_typelist.h
_add function in hash list is not supporting some same hash value case. if we add instance of structure tye a and b different but with same hash value. the _add a, add b, add a sequence lead to have the same object twice in list.
the aim of that fix is to avoid such situation, coding the _add function in a similar manner than the _find one
=> lib: hash list add function fix

tests/topotests/bgp_gr_restart_retain_routes/r2/zebra.conf
The bgp_gr_restart_retain_routes test is looking for specific output that does not include the routes nexthop id:
def _bgp_check_kernel_retained_routes():
output = (
r2.cmd("ip route show 172.16.255.1/32 proto bgp dev r2-eth0")
.replace("\n", "")
.rstrip()
)
expected = "172.16.255.1 via 192.168.255.1 metric 20"
diff = topotest.get_textdiff(
output, expected, "Actual IP Routing Table", "Expected IP RoutingTable"
)
if diff:
return False
return True
While the output includes nexthop group id's now:
root@r2:# ip route show 172.16.255.1 proto bgp dev r2-eth0 172.16.255.1 nhid 8 via 192.168.255.1 metric 20
Let's just mark r2 as not to use nexthop groups for installation and this test issue will go away.
=> tests: nhid is interfering with pattern match

bgpd/bgp_route.c
There is code that sets the pi based upon matching it against the same peer.  In this code the type and sub-type are also compared to the passed in type and sub-type.  Let's just use type and sub-type as that if we have a pi we know type and sub-type are already correct.  This should also make the first iteration work correctly when the pi has not been created yet when we call the martian_update function.bgpd: Remove unnecessary check for pi and setting type and sub-type
There is code that sets the pi based upon matching it against the same peer.  In this code the type and sub-type are also compared to the passed in type and sub-type.  Let's just use type and sub-type as that if we have a pi we know type and sub-type are already correct.  This should also make the first iteration work …
=> bgpd: Remove unnecessary check for pi and setting type and sub-type

bgpd/bgp_vty.c
This PR replaces `inet_ntop` with the formatter `%pI6` when printing the SRv6 VPN SIDs.
=> bgpd: Use `%pI6` to print the SRv6 VPN SIDs

bgpd/bgp_packet.c, isisd/isis_tlvs.c, ospfclient/ospf_apiclient.c
backport #11656 fixing up the %pBP thingie.
=> Some memory backport 8.2

bgpd/bgp_route.c
Before patch:
frr# show bgp large-community 1:1:1 exact-match
% Large-community malformed
After patch:
frr# show bgp large-community 1:1:1 exact-match
=> bgpd: fix display bgp large-community exact-match

bgpd/bgp_vty.c
When an SRv6 locator is unset, all the SRv6 SIDs allocated from the locator are removed. Before freeing the memory allocated for an SRv6 SID, we check if the pointer to the SID is `NULL`.
However, checking for `NULL` before freeing memory is useless.
This PR aims to improve the code's readability by removing the useless `NULL` checks.
=> bgpd: Don't check for `NULL` when removing SRv6 SIDs

bgpd/bgp_rpki.c
With this fix, make `no match rpki` in a route-map actually remove the node in the candidate configuration instead of creating it.
Signed-off-by: Alexander Chernavin <achernavin@netgate.com>
=> bgpd: fix "no match rpki" in route-map

pimd/pim_cmd.c
RpAddress is showing wrong value in
"show ipv6 pim bsm-database" cli. This is fixed now.
Issue: #12089
=> pim6d: Fix RpAddress in "show ipv6 pim bsm-database"
