FRRouting/frr

babeld/babel_main.c, bfdd/bfdd.c, bgpd/bgp_main.c, eigrpd/eigrp_main.c, isisd/isis_main.c, ldpd/ldpd.c, lib/libfrr.c, nhrpd/nhrp_main.c, ospf6d/ospf6_main.c, ospfd/ospf_main.c, pathd/path_main.c, pbrd/pbr_main.c, pimd/pim_main.c, ripd/rip_main.c, ripngd/ripng_main.c, sharpd/sharp_main.c, staticd/static_main.c, vrrpd/vrrp_main.c, zebra/main.c
=> *: Drop `break` after using frr_help_exit() in switch/case

tests/topotests/lib/bgp.py
=> tests: add global BGP json config for [re]connect timer

tests/topotests/bgp_auth/R1/bgpd.conf, tests/topotests/bgp_auth/R1/bgpd_multi_vrf.conf, tests/topotests/bgp_auth/R1/bgpd_vrf.conf, tests/topotests/bgp_auth/R1/ospfd.conf, tests/topotests/bgp_auth/R1/ospfd_multi_vrf.conf, tests/topotests/bgp_auth/R1/ospfd_vrf.conf, tests/topotests/bgp_auth/R2/bgpd.conf, tests/topotests/bgp_auth/R2/bgpd_multi_vrf.conf, tests/topotests/bgp_auth/R2/bgpd_multi_vrf_prefix.conf, tests/topotests/bgp_auth/R2/bgpd_prefix.conf, tests/topotests/bgp_auth/R2/bgpd_vrf.conf, tests/topotests/bgp_auth/R2/bgpd_vrf_prefix.conf, tests/topotests/bgp_auth/R2/ospfd.conf, tests/topotests/bgp_auth/R2/ospfd_multi_vrf.conf, tests/topotests/bgp_auth/R2/ospfd_vrf.conf, tests/topotests/bgp_auth/R3/bgpd.conf, tests/topotests/bgp_auth/R3/bgpd_multi_vrf.conf, tests/topotests/bgp_auth/R3/bgpd_multi_vrf_prefix.conf, tests/topotests/bgp_auth/R3/bgpd_prefix.conf, tests/topotests/bgp_auth/R3/bgpd_vrf.conf, tests/topotests/bgp_auth/R3/bgpd_vrf_prefix.conf, tests/topotests/bgp_auth/R3/ospfd.conf, tests/topotests/bgp_auth/R3/ospfd_multi_vrf.conf, tests/topotests/bgp_auth/R3/ospfd_vrf.conf, tests/topotests/bgp_auth/test_bgp_auth.py
- Reduce OSPF timers to 1 and 4
- Reduce BGP connect timer to 5
- Apply configs in parallel as single file
- Remove the switches as all links are p2p, perhaps this will help with
reliability?
=> tests: speed up bgp_auth test (24m -> 12m)

ospf6d/ospf6_gr_helper.c, ospf6d/ospf6_message.c
Two small fixes for the GR helper code.
=> ospf6d: minor GR fixes

debian/control
=> debian: update list of protos in pkg desc

ripd/ripd.c
Signed-off-by: Schylar Utley <schylarutley@hotmail.com>
=> ripd: Fix spelling errors

tests/topotests/lib/common_config.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py
=> Remove add kernel route usage

doc/developer/topotests-jsontopo.rst, tests/topotests/example_test/test_example.py, tests/topotests/example_test/test_template_json.json, tests/topotests/example_test/test_template_json.py
Utilizes new pytest fixtures to completely factor out setup and teardown
functionality. Supply the JSON config and write your tests.
"The best topotest template yet!"
=> tests: new improved simple JSON template w/ doc update

tests/topotests/lib/micronet_compat.py
=> tests: deal with parallel exit of process we are reaping

zebra/router-id.c, zebra/zapi_msg.c
a) When an upper level protocol requests the router-id, don't respond if we don't know it yet
b) When we hand set a router-id, only send an update if it actually changes from what it currently is.
=> Router id optimizations

bgpd/bgp_evpn_vty.c, ospfd/ospf_vty.c
Implement proper usage of the JSON_C_TO_STRING_NOSLASHESCAPE json functionality, also clean up some memory allocation patterns that were/are awful
=> Slash escape

doc/developer/topotests.rst, tests/topotests/example_test/r1/zebra.conf, tests/topotests/example_test/r2/zebra.conf, tests/topotests/example_test/test_template.py
- Update the template and documentation to use newer pytest fixutres for
setup and teardown, as well as skipping tests when the suite fails.
=> tests: update the test template and doc

isisd/isis_snmp.c, pathd/path_cli.c, tests/zebra/test_lm_plugin.c
see individual commits for what is going on.
=> Strict prototypes

ospf6d/ospf6_area.h, ospf6d/ospf6_interface.h, ospf6d/ospf6_intra.h, ospf6d/ospf6_lsa.h, ospf6d/ospf6_neighbor.h, ospf6d/ospf6_nssa.h, ospf6d/ospf6_route.h, ospf6d/ospf6_zebra.h
=> ospf6d: Cleanup headers to our standard

bgpd/bgp_updgrp_adv.c, lib/routemap.c, lib/routemap.h, tests/topotests/bgp_default_route_route_map_match_set/test_bgp_default-originate_route-map_match_set.py
Fixes https://github.com/FRRouting/frr/issues/9584
=> BGP default-originate with route-map fixes

tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py
1. Optimized test: test_clear_pim_neighbors_and_mroute_p0 run time by clearing
mroute and verifying mroutes separately. Execution time is reduced from almots 10 mins
to ~220 sec.
=> tests: Optimize test_multicast_pim_sm_topo1.py execution time

doc/developer/cli.rst
Document coding steps required to add a new CLI node to a daemon.
=> doc/developer: how to add a CLI node

lib/command_match.c
=> lib: fix segfault on question mark on empty line

doc/developer/logging.rst, lib/nexthop.c, tests/lib/test_printfrr.c
Added some nexthop formats:
%pNHcg - gateway IP address only
%pNHci - nexthop interface name only
=> printfrr %pNHcg, %pNHci

lib/northbound_cli.c
Instead of sorting each command one-by-one using listnode_add_sort, add
them to the list without sorting and then sort the list only once.
=> lib: significantly improve nb cli command sorting

zebra/zebra_fpm.c
=> zebra: Fix ignored return value from inet_pton

zebra/if_netlink.c, zebra/zebra_l2.c, zebra/zebra_l2.h, zebra/zebra_vxlan.c, zebra/zebra_vxlan.h
Those 3 commits solve 3 issues seen when handling vxlan interfaces after BGP configuration has been loaded.
This solves consistencies observed between RIB and linux contexts
=> Vxlan evpn updates

ospf6d/ospf6_intra.c, ospf6d/ospf6_message.c, ospf6d/ospf6_spf.c, pimd/pim_msdp.c, tools/valgrind.supp
=> Bunch of valgrind issues found

doc/developer/topotests.rst
=> doc: add sudo environment setup info for topotests

bgpd/bgp_evpn.c
The BGP configuration for BGP EVPN RT5 setup consists in mainly
2 bgp instances (eventually one is enough) and L3VNI config.
When L3VNI is configured before BGP instances, and BGP route
targets are auto derived as per rfc8365, then, the obtained
route targets are wrong. For instance, the following can be
obtained:
```
=> show bgp vrf cust1 vni
BGP VRF: cust1
Local-Ip: 10.209.36.1
L3-VNI: 1000
Rmac: da:85:42:ba:2a:e9
VNI Filter: none
L2-VNI List:
Export-RTs:
RT:12757:1000
Import-RTs:
RT:12757:1000
RD: 65000:1000
```
whereas the derived route targets should be the below
ones:
```
=> show bgp vrf cust1 vni
BGP VRF: cust1
Local-Ip: 10.209.36.1
L3-VNI: 1000
Rmac: 72:f3:af:a0:98:80
VNI Filter: none
L2-VNI List:
Export-RTs:
RT:12757:268436456
Import-RTs:
RT:12757:268436456
RD: 65000:1000
``` …
=> bgpd: update auto route target for l3vni appropriately

docker/ubuntu20-ci/Dockerfile
=> docker: remove grpc from Travis CI

doc/user/bgp.rst
=> doc: fix range for bgp expanded community list

doc/user/ospfd.rst
=> doc: fix debugging-ospf label

doc/user/ospfd.rst
=> doc: fix ospf distribute-list command and description

isisd/isisd.h
=> isisd: remove unused function declaration

zebra/if_netlink.c, zebra/kernel_netlink.c, zebra/kernel_netlink.h, zebra/rt_netlink.c, zebra/rule_netlink.c
two things:
a) we were not passing in that we were in startup in some situations
b) use a bool to indicate startup
=> Interface startup

doc/user/zebra.rst
=> doc: Add documentation about use_oif_addrs_only

lib/vrf.c, zebra/zebra_netns_notify.c
=> a couple of crash fixes after recent interface/vrf rework

doc/user/zebra.rst
=> doc: Cosmetic minor changes for zebra.rst

doc/user/rpki.rst
Closes https://github.com/FRRouting/frr/issues/9927
=> doc: We must install rpki packages to enable RPKI support

bgpd/bgpd.c, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post4.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1-post6.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post4.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2-post6.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_2.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post4.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3-post6.1.ref, tests/topotests/bgp_multiview_topo1/r1/show_ip_bgp_view_3.ref
Fixes https://github.com/FRRouting/frr/issues/9976
=> bgpd: [7.5] Do not randomly generate a vrf id for -Z

isisd/isis_circuit.c, isisd/isis_circuit.h, isisd/isis_cli.c, isisd/isis_events.c, isisd/isis_ldp_sync.c, isisd/isis_nb_config.c, isisd/isisd.c, tests/topotests/isis_topo1_vrf/r3/r3_topology.json
=> various isisd northbound fixes

zebra/zebra_ptm.c
=> zebra: fix build with --enable-bfdd=no

babeld/babeld.c, bgpd/bgp_routemap.c, bgpd/bgp_vty.c, eigrpd/eigrp_routemap.c, isisd/isis_cli.c, ldpd/ldp_vty_cmds.c, lib/filter.c, lib/filter_cli.c, lib/routemap_cli.c, ospf6d/ospf6_area.c, ospfd/ospf_vty.c, ripd/rip_cli.c, ripngd/ripng_cli.c
=> lib: Add autocomplete for access-lists

zebra/zebra_netns_notify.c
We don't receive interface down/delete notifications from kernel when a
netns is deleted. Therefore we have to manually replicate the necessary
actions, otherwise interfaces are kept in the system with stale pointers
to the deleted netns.
=> zebra: fix netns deletion

doc/developer/process-architecture.rst
There was a historical blurb at the top of the process architecture
document that in several instances caused some confusion regarding
whether or not FRR supports multithreading. Remove this paragraph and
replace it with a summary of the page contents.
=> doc: update & clarify language in process arch doc

tests/topotests/bgp_tcp_mss/bgp_vrf_tcp_mss.json, tests/topotests/bgp_tcp_mss/test_bgp_vrf_tcp_mss.py, tests/topotests/lib/bgp.py
Signed-off-by: ARShreenidhi <rshreenidhi@vmware.com>
Testcase to verify TCP-MSS with VRF functionality
=> tests: testcase to configure and verity tcp mss with vrf

lib/bfd.c, lib/zclient.c, lib/zclient.h
=> lib: rename bfd function to reflect real functionality

lib/if.c, lib/if.h, pimd/pim_bsm.c, pimd/pim_bsm.h, pimd/pim_cmd.c, pimd/pim_igmp.c, pimd/pim_igmp_mtrace.c, pimd/pim_nht.c, pimd/pim_nht.h, pimd/pim_register.c, pimd/pim_rp.c, pimd/pim_rpf.c, pimd/pim_time.c, pimd/pim_upstream.c, pimd/pim_vxlan.c, ripd/rip_snmp.c, staticd/static_routes.c, staticd/static_zebra.c, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py
PIM NHT got random stuff bolted on to the side after it was initially added, specifically BSR NHT is very hacky.  Rework to make it less so.
c071e2e additionally fixes a bug I randomly ran into while cleaning this up.
=> pimd: make PIM NHT less weird

bgpd/bgp_evpn_mh.c, bgpd/bgp_evpn_vty.c, bgpd/bgp_route.c, bgpd/bgp_vpn.c, bgpd/bgp_vty.c, ldpd/ldp_vty_exec.c, lib/nexthop_group.c, ospf6d/ospf6_intra.c, ospf6d/ospf6_top.c, ospfd/ospf_sr.c, ospfd/ospf_vty.c, pimd/pim_cmd.c, pimd/pim_rp.c, tools/coccinelle/json_object_string_addf.cocci, zebra/interface.c, zebra/zebra_evpn.c, zebra/zebra_evpn_mac.c, zebra/zebra_evpn_mh.c, zebra/zebra_evpn_neigh.c, zebra/zebra_mpls.c, zebra/zebra_vty.c, zebra/zebra_vxlan.c
Basically automatic changes from Coccinelle.
=> *: inet_ntop for JSON output

isisd/isis_sr.c, ospfd/ospf_dump.c, ospfd/ospf_ext.c, ospfd/ospf_sr.c, ospfd/ospf_sr.h
minor fixes to the ospfd SR implementation (plus a minor one for isisd) that were rotting in an old PR branch.
See individual commits for a description of the changes.
=> ospfd, isisd: minor SR fixes

redhat/frr.spec.in
Fixes issue #10082
Signed-off-by: Karel Van Hecke <25814162+karelvanhecke@users.noreply.github.com>
=> redhat: check if frr.conf already exists

bgpd/bgp_route.c, tests/topotests/bgp_route_server_client/r1/bgpd.conf, tests/topotests/bgp_route_server_client/r1/zebra.conf, tests/topotests/bgp_route_server_client/r2/bgpd.conf, tests/topotests/bgp_route_server_client/r2/zebra.conf, tests/topotests/bgp_route_server_client/r3/bgpd.conf, tests/topotests/bgp_route_server_client/r3/zebra.conf, tests/topotests/bgp_route_server_client/test_bgp_route_server_client.py
Related: https://github.com/FRRouting/frr/issues/10056
=> bgpd: Do not send LLA for route-server-client peers

bgpd/bgp_routemap.c, doc/user/routemap.rst, lib/routemap.c, lib/routemap.h, lib/routemap_cli.c, lib/routemap_northbound.c, tests/topotests/bgp_route_map_match_ipv6_nexthop_access_list/r1/bgpd.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop_access_list/r1/zebra.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop_access_list/r2/bgpd.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop_access_list/r2/zebra.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop_access_list/test_bgp_route_map_match_ipv6_nexthop_access_list.py, yang/frr-route-map.yang
Related: https://github.com/FRRouting/frr/issues/10011
=> bgpd: match ipv6 next-hop

lib/routemap_cli.c, vtysh/vtysh.c
```
exit1-debian-11(config)# route-map ?
RMAP_NAME  Route map tag
belekas testas
```
=> lib: Use autocomplete for `route-map <name> <action> <seq>`

bgpd/bgp_open.c
```
OPEN has (no message found) capability (71), length 14
```
=> bgpd: Add missing LLGR capability handling stuff

bgpd/bgp_damp.c, bgpd/bgp_route.c, doc/user/bgp.rst
This is mostly a small refactoring to allow more show commands to have access to the "json" option for free. Please see individual commits for details.
=> bgpd: add "json" option to a few more show commands

tests/topotests/isis_topo1_vrf/test_isis_topo1_vrf.py
During repeated runs I am seeing this test fail to run successfully.
Upon inspecting the output:
{
"prefix":"10.0.10.0/24",
"prefixLen":24,
"protocol":"isis",
"vrfId":6,
"vrfName":"r1-cust1",
"selected":true,
"destSelected":true,
"distance":115,
"metric":10,
"queued":true,
We can see that the route is still queued.  Under heavy system
load and not ensuring that isis has time to send the route to
zebra and for zebra to install the route, this test can fail.
=> tests: Fix isis_topo1_vrf to wait a tiny bit for zebra route install

configure.ac, lib/northbound_confd.c, yang/confd/confd.frr-ripd.yang, yang/confd/confd.frr-ripngd.yang, yang/frr-bgp-bmp.yang, yang/frr-bgp-common-structure.yang, yang/frr-bgp-neighbor.yang, yang/frr-bgp-peer-group.yang, yang/frr-routing.yang, yang/subdir.am
See https://github.com/FRRouting/frr/issues/9111
=> fix broken northbound confd

bgpd/bgp_bmp.c
```
home-spine1.donatas.net(config-bgp-bmp)# ipv6 access-list ?
ACCESSLIST_NAME  Access list name
test4 test6
```
=> bgpd: Add autocomplete for access-list under BMP node

doc/user/routemap.rst
=> doc: add missing route-map match command

lib/routemap_cli.c
Just a small cleanup to unify the code and remove duplication.
=> lib: routemap config output cleanup

bgpd/bgp_bmp.c
Fixes https://github.com/FRRouting/frr/issues/9933
=> bgpd: Handle Delete status when peers flapping for BMP

pceplib/pcep_msg_objects.h, pceplib/pcep_msg_tools.c, pceplib/pcep_pcc.c, pceplib/pcep_session_logic.c, pceplib/test/pcep_msg_messages_test.c, pceplib/test/pcep_msg_tools_test.c, pceplib/test/pcep_session_logic_loop_test.c
run clang-format
run clang-format
run clang-format
run clang-format
run clang-format
=> pceplib: fix style issues

doc/user/pathd.rst
=> doc: fix undefined label warning

pimd/pim_cmd.c, pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_igmp.c, pimd/pim_igmpv3.c, pimd/pim_mroute.c, pimd/pim_nb_config.c, pimd/pim_vty.c, pimd/pim_zebra.c
=> Revert "pimd: Modifying members of pim_interface to accommodate IPv6 changes"

doc/user/bgp.rst
=> doc: Add `default-originate route-map WORD` for bgpd

doc/user/ldpd.rst
=> doc: fix typo in ldpd docs

bgpd/bgp_route.c, bgpd/bgpd.c
=> bgpd: Drop `if 0` blocks

bgpd/bgp_community.c
=> bgpd: Fix typo in bgp_aggr_community_hash_alloc()

doc/user/installation.rst
doc: minor grammar correction
Need one empty line.
=> doc: minor grammar correction

tools/generate_support_bundle.py
The generate_support_bundle.py script needs some
reformating to meet our standards
=> tools: Run formatter over generate_support_bundle.py

tests/topotests/nhrp_topo/test_nhrp_topo.py
=> Nhrp topo queries

bgpd/bgp_debug.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/overview.rst, tests/topotests/bgp_features/test_bgp_features.py
=> bgpd: Extended BGP Administrative Shutdown Communication

tools/frr-reload.py
tools: cleanup convertion of "Null0":
1) convert from "null0" to "Null0"
2) convert into "blackhole"
No use, cleanup them. Any question, thx!
=> tools: cleanup convertion of "Null0"

bfdd/bfdd_vty.c, pimd/pim_oil.c
Just a couple of whitespace issues I noticed during code inspection
=> Various stuff

ospfd/ospf_vty.c
ospfd: correct one word of the output message
=> ospfd: correct one word of the output message

bgpd/bgpd.c
```
*** CID 1510738:  Null pointer dereferences  (FORWARD_NULL)
/bgpd/bgp_vty.c: 4243 in bgp_shutdown_msg_magic()
4237            if (msgstr && strlen(msgstr) > BGP_ADMIN_SHUTDOWN_MSG_LEN) {
4238                    vty_out(vty, "%% Shutdown message size exceeded %d\n",
4239                            BGP_ADMIN_SHUTDOWN_MSG_LEN);
4240                    return CMD_WARNING_CONFIG_FAILED;
4241            }
4242
>>>     CID 1510738:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "msgstr" to "bgp_shutdown_enable", which dereferences it.
4243            bgp_shutdown_enable(bgp, msgstr);
4244            XFREE(MTYPE_TMP, msgstr);
4245
4246            return CMD_SUCCESS;
4247     }
4248
```
```
*** CID 1510737:  Null pointer dereferences  (REVERSE_INULL)
/bgpd/bgpd.c: 4344 …
```
=> bgpd: Make sure we are playing with non-NULL for bgp shutdown message

lib/bfd.c
Small fix for error case. Please check commit for details.
=> lib: fix the right value is returned for fail cases

bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h
It's hard to read sometimes or even add something more.
=> bgpd: Reduce nesting for bgp_show_peer()

doc/developer/workflow.rst
Remove some remains from the times when patches were accepted via email.
=> doc: cleanup submitting patches and enhancements

isisd/isis_nb_config.c, isisd/isis_snmp.c
see individual commits. Recent PR introduced some problems.
=> Isis fixes

bgpd/bgp_fsm.c, bgpd/bgpd.h, tests/topotests/bgp_llgr/r0/bgpd.conf, tests/topotests/bgp_llgr/r1/bgpd.conf, tests/topotests/bgp_llgr/r2/bgpd.conf, tests/topotests/bgp_llgr/r2/zebra.conf, tests/topotests/bgp_llgr/r3/bgpd.conf, tests/topotests/bgp_llgr/r4/bgpd.conf, tests/topotests/bgp_llgr/r4/zebra.conf, tests/topotests/bgp_llgr/test_bgp_llgr.py
Fixes https://github.com/FRRouting/frr/issues/10310
=> bgpd: Graceful-restart / LLGR with dynamic peers

ospfd/ospf_lsa.c, ospfd/ospf_vty.c, tests/topotests/ospf_instance_redistribute/r1/ospf_default_information.json, tests/topotests/ospf_instance_redistribute/r1/ospf_instance_lsa.json, tests/topotests/ospf_instance_redistribute/r1/ospf_instance_lsa2.json, tests/topotests/ospf_instance_redistribute/r1/ospfd-3.conf, tests/topotests/ospf_instance_redistribute/r1/sharp_installed.json, tests/topotests/ospf_instance_redistribute/r1/zebra.conf, tests/topotests/ospf_instance_redistribute/test_ospf_instance_redistribute.py, zebra/redistribute.c, zebra/redistribute.h, zebra/rib.h, zebra/zapi_msg.c, zebra/zapi_msg.h, zebra/zebra_rib.c
There are some issues with OSPF instance redistribution.  Let's fix those up.  See individual commits for what is going on.
=> OSPF Redistribution

zebra/if_netlink.c
VRF deletion code must be called after the corresponding interface
deletion code.
=> zebra: fix vrf deletion

bgpd/bgp_attr_evpn.c, bgpd/bgp_attr_evpn.h, bgpd/bgp_evpn.c, bgpd/bgp_route.c, lib/ipaddr.h
=> BGP EVPN overlay index fixes and improvements

isisd/isis_cli.c
=> isisd: remove deprecated command

bgpd/bgp_network.c, bgpd/bgp_network.h, bgpd/bgp_vty.c
Closes https://github.com/FRRouting/frr/issues/10153
=> bgpd: Relax peer to be on the same host

ospf6d/ospf6_zebra.c
=> ospf6d: [8.1] Fix memory leak for show ipv6 ospf6 zebra json

staticd/static_routes.c, staticd/static_vty.c
Cleanup, just remove duplication.
=> staticd: small cleanup

bgpd/bgp_attr.c, bgpd/bgp_attr_evpn.c, bgpd/bgp_attr_evpn.h, bgpd/bgp_evpn.c, bgpd/bgp_vty.c, bgpd/bgp_zebra.c
Description:
Change is intended for fixing some of the coverity issues.
Co-authored-by: Kantesh Mundaragi <kmundaragi@vmware.com>
=> bgpd: Addressing few coverity issues

tests/topotests/ospf6_ecmp_inter_area/r1/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r1/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r2/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r2/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r3/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r3/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r4/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r4/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r5/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r5/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r6/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r6/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r7/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r7/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r8/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r8/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/r9/ospf6d.conf, tests/topotests/ospf6_ecmp_inter_area/r9/zebra.conf, tests/topotests/ospf6_ecmp_inter_area/test_ospf6_ecmp_inter_area.py
Used to reproduce #9720 and may also serve as a regression test in the
future.
=> tests: Topotest for checking ECMP inter-area nexthop handling

bfdd/bfd_packet.c, bfdd/bfdd_nb_config.c, doc/user/bfd.rst, yang/frr-bfdd.yang
=> bfdd,doc,yang: a few minor commits for bfdd

bfdd/bfd.c
The bfdd with passive mode was stuck in INIT status, can’t recovery even the path between them is ok.
=> bfdd: fix broken FSM in passive mode

doc/user/pim.rst
While going through the doc, found some commands are missing in the doc.
Also correcting few mistakes.
=> doc: Correcting the documentation for pimd

doc/user/ospfd.rst
Minor fix for doc.
Please refer to commit log.
=> doc: complete area id for ospf's "range" command

debian/changelog, redhat/frr.spec.in
=> debian, redhat: updating changelog for new release

bgpd/bgp_route.c, doc/user/zebra.rst, lib/command.c, lib/command.h, zebra/rt_netlink.c, zebra/rtadv.c, zebra/rtadv.h, zebra/zebra_router.h, zebra/zebra_vty.c
Add new data to `show zebra`:
```
sharpd@eva ~/f/isisd (master)> vtysh -c "show zebra"
OS              Linux(5.10.0-11-amd64)   
v4 Forwarding   On                       
v6 Forwarding   On                       
MPLS            On                       
EVPN            Off                      
VRF             l3mdev Available         
ASIC offload    Unavaliable              
RA              Compiled in              
RFC 5549        BGP is not using         
Kernel NHG      Unavailable              
Route      Route      Neighbor   LSP        LSP
VRF                         Installs   Removals    Updates   Installs   Removals
VRFA                               0          0          0          0          0
default                            0          0          0          0          0 …
```
=> More zebra show

babeld/message.c
babeld: fix #10487 by adding a check on packet length
=> babeld: add a check for truncated packets

doc/developer/workflow.rst, tools/releasedate.py
What we should do when creating stabilization branch from the master.
=> doc: Add a commands snippet to workflow about what to do in RC1 phase

pimd/pim_igmp.c
As per RFC 2236 section 3, when the leave message is received at a querier,
it starts sending Query messages for "last Member Query Interval*query count"
During this time there should not be any querier to non-querier
transition and the same router needs to send the remaning queries.
Fixes: #10422
=> pimd: Querier to non-querier transistion to be ignored in a case

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_attr_evpn.c, bgpd/bgp_debug.c, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_flowspec.c, bgpd/bgp_flowspec_vty.c, bgpd/bgp_mpath.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_pbr.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c, bgpd/rfapi/vnc_export_bgp.c, bgpd/rfapi/vnc_import_bgp.c
This is an extra work before moving attr->ecommunity to attra_extra struct.
=> bgpd: Use bgp_attr_[sg]et_ecommunity for struct ecommunity

bgpd/bgp_attr.c, bgpd/bgp_attr.h
=> bgpd: Move attr->pmsi_tnl_type to attr->extra->pmsi_tnl_type

doc/developer/workflow.rst
Some release management updates
=> doc: Update workflow.rst for release management

bgpd/bgp_route.c, bgpd/rfapi/vnc_export_bgp.c
=> bgpd: fix a couple of memleaks

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_debug.c, bgpd/bgp_evpn_vty.c, bgpd/bgp_lcommunity.c, bgpd/bgp_mpath.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_zebra.c
=> bgpd: Use get/set helpers for attr->lcommunity

doc/developer/workflow.rst
=> doc: An example how we do RC tagging for stabilization branch

doc/user/ospfd.rst
=> doc: add "cost" to ospfd "range" command

bgpd/bgp_aspath.c, bgpd/bgp_attr.c, tests/bgpd/test_aspath.c
It's not always guarded, just check inside.
=> bgpd: Check for NULL inside aspath_unintern()

pimd/pim_iface.c
=> pimd: remove redundant code

ripd/ripd.c
Cleaup the indentation levels in ripd.c
=> ripd: Cleanup ripd.c indentation levels and comments

pimd/pim_ifchannel.c, pimd/pim_nht.c
=> pimd: cosmetic change

pimd/pim_iface.c
=> pimd: fix unused variable

bgpd/bgp_evpn_vty.c, bgpd/bgp_rpki.c, bgpd/bgp_vty.c, lib/command.c, ospfd/ospf_vty.c, pbrd/pbr_vty.c, sharpd/sharp_vty.c, zebra/zebra_vty.c
Minor change for output of `vty_out`.
=> *: Add necessary new line for output of vty_out()

pimd/pim_ifchannel.c, pimd/pim_upstream.c, pimd/pim_upstream.h
=> pim6d: Handling pim_upstream for IPV6

configure.ac, doc/user/vtysh.rst, lib/subdir.am, lib/vty.c, lib/vty.h, lib/zlog.c, lib/zlog.h, lib/zlog_live.c, lib/zlog_live.h, python/clidef.py, vtysh/subdir.am, vtysh/vtysh.c, vtysh/vtysh.h, vtysh/vtysh_main.c
This is RFC5424 syslog (previously in #8458 as draft), and `vtysh` live log display on top of that (because it shares some code.)
Documentation updates included, not much else to say here…
https://www.youtube.com/watch?v=8psFQCEgA18
=> lib & vtysh: RFC5424 syslog + vtysh live log display

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_community.c, bgpd/bgp_debug.c, bgpd/bgp_evpn_vty.c, bgpd/bgp_fsm.c, bgpd/bgp_mpath.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_zebra.c, bgpd/rfapi/rfapi_vty.c
=> bgpd: Reuse get/set helpers for attr->community

tests/topotests/lib/topogen.py, tests/topotests/lib/topotest.py
This PR adds support for configuring topotest routers using a single file.
instead of:
```
router.load_config(
TopoRouter.RD_ZEBRA, os.path.join(CWD, "{}/zebra.conf".format(rname))
)
router.load_config(
TopoRouter.RD_OSPF, os.path.join(CWD, "{}/ospfd.conf".format(rname))
)
router.load_config(
TopoRouter.RD_BGP, os.path.join(CWD, "{}/bgpd.conf".format(rname))
)
```
```
router.load_frr_config(
os.path.join(CWD, "{}/frr.conf".format(rname)),
[TopoRouter.RD_ZEBRA, TopoRouter.RD_OSPF, TopoRouter.RD_BGP]
)
```
or just:
```
router.load_frr_config(os.path.join(CWD, "{}/frr.conf".format(rname)))
```
In this latter case, the daemons list will be inferred from frr.conf file.
=> topotests: add support for frr.conf as a unified config

pimd/pim_nht.c, pimd/pim_zlookup.c
Handling pim nexthop tracking for IPV6
=> nexthop tracking changes for pimv6

pimd/pim_nht.c, pimd/pim_rpf.c
=> pim6d: Handling nexthop for PIMV6

vtysh/vtysh.c
Just some small bits that snuck through. One false positive.
=> vtysh: fix coverity issues in live-log code

doc/user/zebra.rst, zebra/kernel_socket.c, zebra/zebra_rib.c
backport https://github.com/FRRouting/frr/pull/10672
=> zebra: [8.2] Bsd zebra graceful restart cleanup

zebra/zebra_evpn.c
=> zebra: Delay the usage of one variable

pimd/pim6_cmd.c, pimd/pim6_stubs.c, pimd/pim_bsm.c, pimd/pim_bsm.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_nb_config.c, pimd/pim_rp.c, pimd/pim_rp.h, pimd/pim_rpf.c, pimd/pim_util.c, pimd/pim_util.h, pimd/subdir.am
Implementing the static RP feature for PIMv6.
Check commits for more details.
~~Please ignore the first 4 commits since it is common to other PRs raised. Once those are merged, will remove it from this PR.~~
Document updation is done in #10480 
Signed-off-by: Mobashshera Rasool [mrasool@vmware.com](mailto:mrasool@vmware.com)
=> pim6d: Static RP feature

zebra/zebra_evpn_mac.c
zebra crash is seen during shutdown (frr restart).
During shutdown, remote neigh and remote mac clean up
is triggered first, followed by per vni all neigh
(including local) and macs cleanup is triggered.
The crash occurs when a remote mac is cleaned up first
and its reference is remained in local neigh.
When local neigh attempt removes itself from its associated
mac's neigh_list it triggers inaccessible memory crash.
The fix is during mac deletion if its neigh_list is non-empty
then retain the MAC in AUTO state.
This can arise when MAC and neigh duo are in different state
(remote/local). Otherwise, the order of cleanup operation
is neighs followed by macs.
The auto mac will be cleaned up when per vni all neighs and macs
are cleaned up.
Testing Done:
Configure evpn symmetric config where …
=> zebra: fix crash in evpn neigh cleanup all

doc/user/isisd.rst, isisd/isis_adjacency.c, isisd/isis_adjacency.h, isisd/isis_circuit.c, isisd/isis_circuit.h, isisd/isis_lsp.c, isisd/isis_lsp.h, isisd/isis_pdu.c, isisd/isis_spf.c, isisd/isis_spf.h, isisd/isis_tlvs.c, isisd/isis_tlvs.h, isisd/isisd.c, isisd/isisd.h, tests/isisd/test_fuzz_isis_tlv.c, tests/isisd/test_isis_spf.c, tests/topotests/isis_topo1/test_isis_topo1.py
Adding json output for isis show commands : summary, interfaces, neighbor and database.
=> Feat isis json show cmds

doc/user/index.rst, doc/user/pimv6.rst, doc/user/subdir.am
This PR is raised to add the documentation for MLD and PIMv6.
=> doc: Add the document for PIMv6

vrrpd/Makefile
Looks like the bones were put in place but they
were slightly malformed.  Fix.
=> vrrpd: Allow it to be built in directory

doc/developer/frr-release-procedure.rst
=> doc: Add a couple of handy commands to get some info for release notes

pimd/pim_cmd.c, pimd/pim_igmp_stats.c, pimd/pim_igmp_stats.h
=> pimd: Add IGMP total groups and total source groups to statistics

bgpd/bgp_nht.c, lib/zclient.c, lib/zclient.h, ospf6d/ospf6_zebra.c, pbrd/pbr_zebra.c, pimd/pim_nht.c, sharpd/sharp_zebra.c, staticd/static_zebra.c, zebra/rib.h, zebra/zebra_rnh.c, zebra/zebra_srte.c
See individual commits, but the gist is that nexthop tracking was not working w/ import_check needs and LPM.
=> Bgp zebra nht

bgpd/bgp_nht.c
=> bgpd: Remove dead code for [un]register_zebra_rnh

pimd/pim_cmd.c, pimd/pim_igmp.c, pimd/pim_pim.c, pimd/pim_sock.c, pimd/pim_sock.h, pimd/pim_ssmpingd.c
Socket code changes done to make the socket code IPv6 aware.
Signed-off-by: Balaji Gurudoss <G_Balaji1@dell.com>
=> pim6d: PIMv6 socket related changes

lib/routemap.c
If a operator issues a series of route-map deletions and
then re-adds, *and* this triggers the hash table to realloc
to grow to a larger size, then subsuquent route-map operations
will be against a corrupted hash table.
Why?
Effectively the route-map code was inserting each
route-map <NAME> into a hash for storage.  Upon
deletion there is this concept of delayed processing
so the routemap code sets a bit `to-be-processed`
and marks the route-map for deletion.  This is
1 entry in the hash table.  Then if the operator
recreates the hash, FRR would add another hash
entry.  If another deletion happens then there
now are 2 deletion entries that are indistinguishable
from a hash perspective.
FRR stores the deleted name of the route-map so that
any delayed processing can lookup the name and only …
=> lib: Fix corruption when routemap delete/add sequence happens

zebra/zebra_vty.c
see individual commits but add more data to `show zebra`
=> zebra: Multipath output

pimd/pim_igmpv2.c, pimd/pim_igmpv3.c
==================
(rcv1)-----A----B---C
v3 enabled with src 90.0.0.1
|
(rcv2)--
v3 enable with src none
rcv1 sends the packet in INCLUDE mode, rcv2 sends the IGMP report
in exclude mode. As per the state machine the group structure was
getting added and deleted. As group gets deleted the mroute for 90.0.0.1
and recreated back.
This effects the end to end trafiic.
Fix:
====
As per RFC 4604.
drop the exclude mode, IGMP reports, if destnation group is
SSM based.
EXCLUDE
mode does not apply to SSM addresses, and an SSM-aware router will
ignore MODE_IS_EXCLUDE and CHANGE_TO_EXCLUDE_MODE requests in the SSM
range.
Signed-off-by: Vishal Dhingra <rac.vishaldhingra@gmail.com>
=> pimd : Handling of Exclude mode IGMPv3 report messages for SSM aware group.

lib/wheel.c
Signed-off-by: ron <lyq140hf2006@163.com>
=> lib: not thread off when schedule

pimd/pim_instance.h, pimd/pim_nb_config.c, pimd/pim_ssmpingd.c, pimd/pim_ssmpingd.h, pimd/pim_vty.c
Changes done in pim_ssmpingd to support IPv6 addresses
Signed-off-by: Balaji Gurudoss <G_Balaji1@dell.com>
=> pim6d: pim_ssmpingd changes to support PIMv6

vtysh/extract.pl.in
=> pim6d: Enable protocol as VTYSH_PIM6D for pim6_cmd.c

tests/topotests/lib/common_config.py, tests/topotests/lib/ospf.py, tests/topotests/lib/topotest.py, tests/topotests/ospfv3_basic_functionality/ospfv3_asbr_summary_type7_lsa.json, tests/topotests/ospfv3_basic_functionality/ospfv3_dual_stack.json, tests/topotests/ospfv3_basic_functionality/ospfv3_ecmp_lan.json, tests/topotests/ospfv3_basic_functionality/ospfv3_lan.json, tests/topotests/ospfv3_basic_functionality/ospfv3_nssa2.json, tests/topotests/ospfv3_basic_functionality/ospfv3_rte_calc.json, tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp_lan.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa2.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_routemaps.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_rte_calc.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
Covers basic test case like route map, rte calc.
=> tests: adding ospfv3 base cases.

lib/northbound_sysrepo.c
Signed-off-by: Fabio Antonini <f.antonini@tiesse.com>
Changes required to adapt some sysrepo API calla to the newer version 2.0.41.
=> support to sysrepo-2.0.41

tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py
Automated EVPN-GR scenario to verify Graceful-restart functionality for EVPN address-family.
=> tests: Adding EVPN-GR scenario to evpn_type5 suite

pimd/pim_igmpv2.c, pimd/pim_mroute.c
This is a fixup of #10156 as that it was an old PR that I don't think was going to be updated, but I think we need this code
=> Pim igmp query

tests/topotests/bgp_vrf_dynamic_route_leak_topo3/bgp_vrf_dynamic_route_leak_topo3.json, tests/topotests/bgp_vrf_dynamic_route_leak_topo3/test_bgp_vrf_dynamic_route_leak_topo3.py, tests/topotests/bgp_vrf_dynamic_route_leak_topo4/bgp_vrf_dynamic_route_leak_topo4.json, tests/topotests/bgp_vrf_dynamic_route_leak_topo4/test_bgp_vrf_dynamic_route_leak_topo4.py, tests/topotests/lib/bgp.py, tests/topotests/lib/common_config.py
1. Added new topology and tests to verify bgp_vrf_dynamic_route_leak functionality
=> tests: Adding new tests to bgp_vrf_dynamic_route_leak suite

pimd/pim_igmpv2.c, pimd/pim_mroute.c
Backporting https://github.com/FRRouting/frr/pull/10809
=> pimd: [8.2] Pim igmp query backport

pimd/pim_igmp.c
Modifying the code as per RFC 4604 section 2.2.1
EXCLUDE mode does not apply to SSM addresses, and an SSM-aware router
will ignore MODE_IS_EXCLUDE and CHANGE_TO_EXCLUDE_MODE requests in
the SSM range.
Issue is observed when a group in exclude mode was in ASM range
as per the prefix-list and then prefix-list is modified to make
it fall under SSM range. The (*,G) entry remains there.
So when the group moves to ssm range and it is exclude mode,
delete the group from the IGMP table.
=> pimd: correct prefix-list ssm range update for exclude mode

isisd/isis_circuit.c, isisd/isis_pfpacket.c, isisd/isis_spf.c
=> isisd: add guard debug when compiling with EXTREME_DEBUG

pimd/pim_bsm.c, pimd/pim_bsm.h, pimd/pim_nht.c, pimd/pim_nht.h, pimd/pim_pim.c, pimd/pim_pim.h
This PR handles the receiving of PIMv6 packet.
=> pim6d: Handling of receiving of PIMv6 packets

bgpd/bgp_bmp.c
```
spine1-debian-11(config-router)# bmp targets ?
BMPTARGETS  Name of the BMP target group
ok test1
```
=> bgpd: Add autocomplete for BMP targets

pimd/pim6_cmd.c, pimd/pim_iface.c, pimd/pim_nb_config.c
Adding new mld CLI's for v6.
ipv6 mld join
ipv6 mld
ipv6 mld version
ipv6 mld query-interval
Signed-off-by: Abhishek N R abnr@vmware.com
=> pim6d: Adding new mld CLI's for v6

ospfd/ospf_sr.c
Handle configuration inconsistencies when configuring SRLB
=> Ospf srlb config

bgpd/bgp_script.c, lib/frrscript.c
Closes https://github.com/FRRouting/frr/issues/10914
=> bgpd: Fix Lua route-map crash

doc/developer/logging.rst
Group together and extend docs on daemon-specific printfrr formats.
=> doc/developer: daemon-specific printfrr formats

docker/centos-8/Dockerfile
- Need to adapt repos to new centos-8 stream.
Signed-off-by: Javier Garcia <javier.martin.garcia@ibm.com>
=> docker: Centos-8 dockerfile fix.

isisd/isis_bfd.c, isisd/isisd.c
=> Isis misc fixes

tests/lib/test_frrlua.c
=> tests: Fix uninitialized usage of variables in tests

doc/user/bgp.rst
Add type-0 ESI support for this cli:
`[no$no] evpn mh es-id [(1-16777215)$es_lid | NAME$esi_str]`
=> doc: add mh type-0 ESI support

bgpd/bgp_rpki.c
Replacing: https://github.com/FRRouting/frr/pull/10957
=> bgpd: RPKI memory leak

watchfrr/watchfrr.c
clean up some typedef's that FRR should not have
=> Enum watchfrr

lib/routemap_cli.c
=> lib: Remove deprecated routemap_optimization_cmd

bgpd/bgp_clist.c, bgpd/bgp_community.c, bgpd/bgp_community.h, bgpd/bgp_debug.c, bgpd/bgp_lcommunity.c, bgpd/bgp_lcommunity.h, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_vty.c
Closes https://github.com/FRRouting/frr/issues/10998
=> bgpd: Allow setting BGP [large]community in route-maps

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h, pimd/pim_ssmpingd.c, pimd/pim_vty.c
pim6d: Addition of ipv6 ssmpingd config commands
Signed-off-by: Balaji Gurudoss <G_Balaji1@dell.com>
=> pim6d: Addition of ipv6 ssmpingd config commands

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_mpath.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/vnc_export_bgp.c
=> bgpd: Reuse bgp_attr_set_[el]community() for setting attribute flags

bgpd/bgp_clist.c, bgpd/bgp_community.c, bgpd/bgp_community.h, bgpd/bgp_debug.c, bgpd/bgp_lcommunity.c, bgpd/bgp_lcommunity.h, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_vty.c
=> bgpd: [8.2] Allow setting BGP [large]community in route-maps

doc/user/zebra.rst
=> doc: Add `show ip nht..` documentation

debian/frr.logrotate, debian/frr.preinst, redhat/frr.logrotate, tools/etc/rsyslog.d/45-frr.conf
=> packaging: Add pathd to logrotate

.github/ISSUE_TEMPLATE/bug_report.md
=> github: Use checkboxes for issue templates

tests/topotests/lib/common_config.py, tests/topotests/multicast_pim_dr_nondr_test/pim_dr_nondr_with_ospf_topo2.json, tests/topotests/multicast_pim_dr_nondr_test/pim_dr_nondr_with_static_routes_topo1.json, tests/topotests/multicast_pim_dr_nondr_test/pim_dr_nondr_with_transit_router_topo3.json, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_ospf_topo2.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_static_routes_topo1.py, tests/topotests/multicast_pim_dr_nondr_test/test_pim_dr_nondr_with_transit_router_topo3.py
1. Added/enhanced framework for multicast-pim-dr_nondr automation
2. Added 16 test cases to test/verify multicast_pim_dr_nondr scenarios
Signed-off-by: kuldeepkash <kashyapk@vmware.com>
=> tests: Add multicast_pim_dr_nondr_test suite

bgpd/bgp_nht.c
Fix: 06e4e90132ad23815c6f288dd7e6be334f5ab233
Modified BGP to pay more attention the prefix returned from
zebra to ensure that a LPM wasn't accidently causing BGP
import checks to think it had a match when it did not.
This unfortunately removed the check to handle the route
removal.
This sequence of config and events would leave BGP in a bad state:
ip route 100.100.100.0/24 Null0
router bgp 32932
bgp network import-check
address-family ipv4 uni
network 100.100.100.0/24
Then if you removed the static route the import check would
still think the route existed:
donatas-pc(config)# ip route 100.100.100.0/24 Null0
donatas-pc(config)# do sh ip bgp import-check-table
Current BGP import check cache:
100.100.100.0 valid [IGP metric 0], #paths 1
blackhole
Last update: Sat Apr 23 22:51:34 2022 …
=> bgpd: Fix import check removal

bgpd/bgp_route.c
=> bgpd: Drop inet_ntop for route_vty_out_overlay()

bgpd/bgp_route.c
The logic to unlock dest if iteration completed without iterating the entire node was flawed. Specifically, if iteration terminated due to `gr_deferred == 0` then the node would not get unlocked.
This change takes into account the fact that dest will be NULL only in the case when the entire table was iterated and all nodes were already unlocked. In any other case, it needs to be unlocked.
Signed-off-by: Carl Baldwin <carl@ecbaldwin.net>
=> bgpd: ensure that the node gets unlocked in all cases

bgpd/bgp_attr.c, bgpd/bgp_bmp.c, bgpd/bgp_open.c, bgpd/bgp_packet.c, tests/bgpd/test_aspath.c, tests/bgpd/test_capability.c, tests/bgpd/test_ecommunity.c, tests/bgpd/test_mp_attr.c, tests/bgpd/test_packet.c
see individual commits but just some new issues found by examining the build output in the CI system.
=> Werror error error

doc/developer/logging.rst, lib/prefix.c, lib/prefix.h
cf. commits / commit titles.
Also compiler errors from odd platforms in 3… 2… 1…
=> lib: `struct prefix` spring cleaning

bgpd/bgp_route.c
=> bgpd: fix size of esi_buf

pimd/pim6_stubs.c, pimd/pim_register.c, pimd/subdir.am
Register and Null register send handling
Signed-off-by: plsaranya<Saranya_panjarathina@dell.com>
=> pim6d: Register message send handling

configure.ac, lib/mgmt.proto, lib/mgmt_be_client.c, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_fe_adapter.h, mgmtd/mgmt_txn.c
=> mgmtd: fix remote validation code, use by default

isisd/isis_te.c, isisd/isis_tlvs.h, pceplib/pcep_msg_objects.c, pceplib/pcep_msg_objects_encoding.c, pceplib/pcep_socket_comm_loop.c, pceplib/test/pcep_session_logic_states_test.c, tests/bgpd/test_aspath.c, tests/topotests/lib/micronet.py
a) Fix some spelling mistakes
b) A read past end of string
c) weird double declerations of structures
d) direct copy of a prefix into a wrong type
=> valgrind issues and general cleanup

bgpd/bgp_nexthop.c, bgpd/rfapi/rfapi_rib.c, isisd/isis_spf.c, ospf6d/ospf6_top.c, ospfd/ospf_ldp_sync.c, ospfd/ospf_vty.c, pceplib/pcep_msg_tlvs_encoding.c, ripngd/ripngd.c, tests/lib/test_srcdest_table.c, zebra/zebra_nb_state.c, zebra/zebra_vxlan.c
=> *: Avoid casting to the same type as on the left

bgpd/bgp_evpn_mh.c, zebra/zebra_evpn_mh.h
Correct one debug log in evpn-mh.
BTW, correct one misspelled word in comment.
=> bgpd,zebra: correct one debug log for evpn-mh

babeld/message.c, bfdd/bfdd.c, bgpd/bgp_attr.c
=> Some more Coverity issues solved

doc/user/bgp.rst
After https://github.com/FRRouting/frr/pull/11183
=> doc: Add some more documentation about Notification support for GR

lib/linklist.c
Add one check in `list_sort()`:
Immediatly return if no any items in this list.
=> lib: add one check in "list_sort()"

bgpd/bgp_debug.c, bgpd/bgp_debug.h, bgpd/bgp_updgrp.c
Make it a bit easier to debug how FRR puts peers into different nexthop groups
=> Update group debugging

zebra/ioctl.c, zebra/rib.h, zebra/zebra_rib.c
=> Remove some unused functions in zebra

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_main.c, pimd/pim6_mld.c, pimd/pim6_mld.h, pimd/pim6_mld_protocol.h, pimd/pim_iface.c, pimd/pim_iface.h, pimd/pim_instance.c, pimd/pim_instance.h, pimd/pim_nb_config.c, pimd/pim_vty.c, pimd/subdir.am, yang/frr-gmp.yang
~WORK IN PROGRESS: MLD code~
~still a bunch of TODOs left~
Does 90%, ready to merge.
=> pim6d: MLD code

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Adding the below clear ipv6 pim commands
clear ipv6 pim statistics
clear ipv6 mroute
clear ipv6 pim oil
clear ipv6 mroute count
=> pimv6: Adding clear ipv6 pim CLIs

bgpd/bgp_route.c
Fixes https://github.com/FRRouting/frr/issues/11209
=> bgpd: Show a correct local AS for the advertised/bestpath routes

bgpd/bgp_fsm.c, zebra/kernel_netlink.c
a) Fix bug with v6 LL handling in bgp
b) Fix newline that got in from a recent commit
=> Bgp zebra stuff

bgpd/bgp_packet.c
=> bgpd: fix oopsie with SendHoldTime==0

docker/centos-7/Dockerfile, docker/centos-8/Dockerfile, docker/ubi-8/Dockerfile
Related: https://github.com/FRRouting/frr/issues/11269
=> docker: CentOS/UBI adoptions for librtr 0.8.0

debian/changelog, redhat/frr.spec.in
=> debian, redhat: update changelog for new release

tests/topotests/bgp_gr_notification/r1/bgpd.conf, tests/topotests/bgp_gr_notification/r1/zebra.conf, tests/topotests/bgp_gr_notification/r2/bgpd.conf, tests/topotests/bgp_gr_notification/r2/zebra.conf, tests/topotests/bgp_gr_notification/test_bgp_gr_notification.py
Related: https://github.com/FRRouting/frr/issues/5282
=> tests: Add Notification support for Graceful-Restart tests

bgpd/bgp_rpki.c, doc/user/rpki.rst
Related: https://github.com/FRRouting/frr/issues/11139
After 2022.06.07.
=> bgpd: Add JSON output for `show rpki prefix` and other show commands

tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ebgp_unnumbered_nbr.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_bsm_topo2/test_mcast_pim_bsmp_02.py, tests/topotests/static_routing_with_ebgp/test_static_routes_topo3_ebgp.py, tests/topotests/static_routing_with_ibgp/test_static_routes_topo3_ibgp.py
If at first you succeed try try again.
No I mean if it works the first time no need to do
the same command again.
=> tests: Remove duplicated work

ospf6d/ospf6_message.c
OSPFv3 packets can be fragmented and up to 64k long, regardless of interface MTU.  Trying to size these buffers to MTU is just plain wrong. To not make this a super intrusive change during the 8.3 release freeze, just code this into ospf6_iobuf_size().
Since the buffer is now always 64k, don't waste time zeroing the entire thing in receive;  instead just zero kind of a "sled" of 128 bytes after the buffer as a security precaution.
Fixes: #11298
---
@dmrzzz could you confirm this fixes the issue?
=> ospf6d: fix rx/tx buffer sizes

redhat/frr.spec.in
=> redhat: fix merge conflict resolution

.github/workflows/base-branch-label.yml
=> github: [8.2] Add base branch label to every PR to distinguish easily

lib/workqueue.c, lib/workqueue.h, ospfd/ospf_zebra.c, ospfd/ospfd.h
grab bag o' cleanup.  See the individual 3 commits.
=> Lib zebra cleanup

.github/workflows/base-branch-label.yml
=> github: [8.1] Add base branch label to every PR to distinguish easily

babeld/message.c, babeld/message.h
see individual commits, just bringing FRR up to rfc compliance to interact with new versions of babel
=> Babel updates

bgpd/bgp_route.c, bgpd/bgpd.h
Fix random warnings from CodeQL.
=> bgpd: Minor warning fixes

configure.ac, lib/northbound_sysrepo.c
Seems we supported here old versions of sysrepo only.
=> lib: sysrepo compilation issues

pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Moving reusable code to common api for few of the show CLIs.
See individual commits for details.
=> pimd, pim6d: Moving reusable code to common api for show CLI's.

bgpd/bgp_mplsvpn.c, tests/topotests/bgp_vrf_leaking_rt_change_route_maps/r1/bgpd.conf, tests/topotests/bgp_vrf_leaking_rt_change_route_maps/r1/zebra.conf, tests/topotests/bgp_vrf_leaking_rt_change_route_maps/test_bgp_vrf_leaking_rt_change_route_maps.py
Fixes https://github.com/FRRouting/frr/issues/11215
Fixes https://github.com/FRRouting/frr/issues/10800
=> bgpd: Fix VRF leaking when import/export RT list changed with route-maps

mgmtd/mgmt_db.c, mgmtd/mgmt_db.h
=> mgmtd: Change the startup file location.

pimd/pim_addr.h, pimd/pim_iface.c
Fixing the issue https://github.com/FRRouting/frr/issues/11234
=> pim6d: creating pim6reg

lib/nexthop.c, lib/nexthop.h, zebra/zebra_nhg.c, zebra/zebra_nhg.h
Add the ability for zebra to have a printfrr %pNG for nhe's.  Makes debug output a bit easier to follow
=> Zebra nhg debug

bgpd/bgp_vty.c, lib/sockunion.c
see individual commits but
1) Actually give information for failed state in json output
2) Add some extra error messages when FRR fails to gather socket data in an unexpected way.
=> Add some extra data for when things might be going wrong

eigrpd/eigrp_vty.c, lib/command.c, lib/vty.c, nhrpd/zbuf.c, ospf6d/ospf6_interface.c, python/tiabwarfo.py, zebra/zebra_netns_id.c
bunch of code problems found during a long ago lgtm scan
=> Lgtm fixes

bgpd/bgp_route.c
When using json output for `show bgp statistics json` gather the
number of prefixes of each prefix Length.
Signed-off-by: Antonio Quartulli <a@unstable.cc>
This PR is a follow up of https://github.com/FRRouting/frr/pull/8342 - @donaldsharp suggested to pick this patch up and apply the missing changes:
* use IPV6_MAX_BITLEN instead of IPV6_MAX_PREFIXLEN
* populate element in the json array only if the prefix count is non-zero
=> bgpd: Allow statistics gathering to give more data about prefix Lengths

bgpd/bgp_bfd.c
=> bgpd: Replace zlog_info -> zlog_debug under BGP_DEBUG()

tests/topotests/lib/pim.py, tests/topotests/multicast_pim_uplink_topo1/multicast_pim_uplink_topo1.json, tests/topotests/multicast_pim_uplink_topo1/test_multicast_pim_uplink_topo1.py
Added framework support to create and verify multicast PIM multi-uplink
topology and configuration. Added 9 test cases to verify multicast PIM 
uplink(8 uplink) functionality.
=> tests: Add multicast-pim-multi-uplink test suite 

ospfclient/README
=> ospfclient: fix help url

bgpd/bgp_attr.c
=> bgpd: Drop duplicate label assignment

bgpd/bgp_bmp.c, bgpd/bgp_network.c, bgpd/bgp_route.c, bgpd/bgp_vty.c, lib/nexthop_group.c, nhrpd/nhrp_nhs.c, nhrpd/nhrp_peer.c, nhrpd/nhrp_shortcut.c, nhrpd/nhrp_vty.c
=> *: Replace sockunion2str => %pSU

bgpd/bgp_rpki.c, doc/user/rpki.rst
Fixes https://github.com/FRRouting/frr/issues/7978
=> bgpd: RPKI fixes

bgpd/rfapi/vnc_zebra.c, isisd/isis_bfd.c, isisd/isis_snmp.c, ospf6d/ospf6_auth_trailer.c, pimd/pim6_mld.c, pimd/pim_instance.h, pimd/pim_nht.c, pimd/pim_rpf.c, pimd/pim_zebra.c, pimd/pim_zlookup.c, pimd/pimd.c
=> Random stuff right

zebra/rtadv.c
When a interface is configured with this:
int eva
ipv6 nd ra-interval 5
no ipv6 nd suppress-ra
!
And then subsuquently the interface is created and brought up, FRR
would both error on joining the RA multicast address and never
properly work in this state.
Delay the startup of the join and start of the Router Advertisements
until after the ifindex has actually been found.
=> zebra: Fix rtadv startup when config read in is before interface up

bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h
=> bgpd: Use uin64_t for peer->flags

bgpd/bgp_open.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/bgp_roles_capability/r1/bgpd.conf, tests/topotests/bgp_roles_capability/r1/zebra.conf, tests/topotests/bgp_roles_capability/r2/bgpd.conf, tests/topotests/bgp_roles_capability/r3/bgpd.conf, tests/topotests/bgp_roles_capability/r4/bgpd.conf, tests/topotests/bgp_roles_capability/r5/bgpd.conf, tests/topotests/bgp_roles_capability/r6/bgpd.conf, tests/topotests/bgp_roles_capability/r6/zebra.conf, tests/topotests/bgp_roles_capability/test_bgp_roles_capability.py
=> bgpd: Make sure peer-groups/unnumbered work too with BGP role

lib/privs.c
Staticd when run tells privs.c that it does not need any
priviledges.  The lib/privs.c code was not downgrading
any and all permissions it may have been given at startup.
Since we don't need any let's actually tell the system that
FRR does not need the capabilities anymore in the case
where a daemon does not ask for any cap's.
=> lib: Allow downgrade of all caps when none are specified

zebra/main.c, zebra/rt_netlink.c, zebra/zebra_rib.c, zebra/zebra_router.c, zebra/zebra_router.h, zebra/zebra_vty.c
Some minor stuff run across while thinking about other problems :)
a) Add more cases to proto2zebra
b) move allow_delete into zrouter where it belongs
c) Notice an error condition( since we are testing for it) end operator would want to know that a route is dropped.
=> Zebra odds and ends

zebra/ioctl.c
Fixes #11499 .
This PR is a backport of #10547 (dependency) and #10864.
=> [8.2] Fix FreeBSD interface configuration

bfdd/bfd_packet.c
Fix some new coverity scan issues found in `bfdd`.
=> bfdd: fix coverity scan issues

tools/etc/rsyslog.d/45-frr.conf
Closes https://github.com/FRRouting/frr/issues/11546
=> tools: Add missing bfdd to logrotate config

lib/filter_nb.c, zebra/zebra_nhg.c, zebra/zebra_vty.c
see individual commits all found via running valgrind
=> Valgrind issues

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
=> pim6d: Implementing "clear ipv6 pim interfaces" command.

bfdd/bfd_packet.c
Signed-off-by: Lynne Morrison <lynne.morrison@ibm.com>
=> BFDD: Cleanup warning

bgpd/bgp_packet.c, isisd/isis_tlvs.c, ospfclient/ospf_apiclient.c
=> Some memory

bgpd/bgp_zebra.c, tests/topotests/bgp_default_originate/test_bgp_default_originate_topo1_1.py, tests/topotests/bgp_default_originate/test_bgp_default_originate_topo1_2.py, tests/topotests/bgp_default_originate/test_bgp_default_originate_topo1_3.py, tests/topotests/bgp_default_originate/test_default_orginate_vrf.py, tests/topotests/bgp_default_originate/test_default_originate_conditional_routemap.py, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ebgp_ibgp_nbr.py, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ebgp_nbr.py, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ebgp_unnumbered_nbr.py, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ibgp_nbr.py, tests/topotests/bgp_ipv4_over_ipv6/test_rfc5549_ibgp_unnumbered_nbr.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper1.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper2.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper3.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py, zebra/zebra_mpls.c
Some more valgrind issues found and fixed
=> Valgrind me

bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h
Closes https://github.com/FRRouting/frr/issues/11676
=> bgpd: Allow setting custom port for unnumbered sessions

ospf6d/ospf6_gr_helper.c
corrected the gramatical error for debug string
Signed-off-by:sri-mohan1 <sri.mohan@samsung.com>
=> ospf6d: corrected the debug string

tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pimv6_static_rp.py
Updated topology for static rp suite as per testcase.
=> tests: [PIMv6] Updated topology for static rp suite

bgpd/bgp_updgrp_adv.c, ospfd/ospf_lsa.c
a) cleanup indentation some in a file in bgp
b) Fix a coverity issue
=> two things

ospfclient/ospf_apiclient.c
=> ospfclient: condition optimization

pimd/pim_iface.c
Combine all the if conditions in api pim_if_addr_add_all to
reduce nested loops.
=> pimd: Simply the code a bit, reduce code complexity

a.py, bgpd/bgp_aspath.c, bgpd/bgp_aspath.h, bgpd/bgp_route.c, tests/topotests/bgp_as_override/r1/bgpd.conf, tests/topotests/bgp_as_override/r1/zebra.conf, tests/topotests/bgp_as_override/r2/bgpd.conf, tests/topotests/bgp_as_override/r2/zebra.conf, tests/topotests/bgp_as_override/r3/bgpd.conf, tests/topotests/bgp_as_override/r3/zebra.conf, tests/topotests/bgp_as_override/r4/bgpd.conf, tests/topotests/bgp_as_override/r4/zebra.conf, tests/topotests/bgp_as_override/test_bgp_as_override.py
Closes https://github.com/FRRouting/frr/issues/11677
=> bgpd: Override ASN without checking if an entire as-path is from a single ASN

bgpd/bgp_zebra.c, lib/sockopt.c, ospfd/ospf_abr.c, ospfd/ospf_flood.c, zebra/if_ioctl.c
see individual commits but clean up some warnings that will soon become errors
=> Cleanup for dev builds

pimd/pim_cmd_common.c
Using termtable for show ip | ipv6 pim interface
for dynamic space alignments.
Issue: #11246
=> pimd, pim6d: Using ttable for displaying purpose

pimd/pim_static.c
Allow the same group/source route to be configured on more than one interface.
Currently FRR doesn't allow adding the same mroute on different input interfaces.
Current behavior, if we have the following config:
```
interface eth1
ip mroute eth0 239.0.0.1
interface eth2
ip mroute eth0 239.0.0.1
```
Only one multicast route will be installed with an input interface of the last
interface configured.
Signed-off-by: Nathan Bahr <nbahr@atcorp.com>
=> pimd: fix static mroute to also take into account the input interface

pimd/pim6_mld.c, pimd/pim6_mld.h, pimd/pim_cmd_common.c
=> pim6d: fix clear ipv6 mroute

zebra/zebra_mpls.c, zebra/zebra_nhg.c, zebra/zebra_nhg.h, zebra/zebra_router.c, zebra/zebra_router.h
See individual commits but fixes memory leaks and use after free's on shutdown
=> NHGs Various Fixes

doc/user/zebra.rst, tests/topotests/bgp_l3vpn_to_bgp_direct/customize.py, tests/topotests/bgp_l3vpn_to_bgp_direct/r1/zebra.conf, tests/topotests/bgp_l3vpn_to_bgp_direct/r2/zebra.conf, tests/topotests/bgp_l3vpn_to_bgp_direct/r3/zebra.conf, tests/topotests/bgp_l3vpn_to_bgp_direct/r4/zebra.conf, zebra/if_socket.c, zebra/interface.c, zebra/interface.h, zebra/kernel_netlink.c, zebra/kernel_socket.c, zebra/netconf_netlink.c, zebra/netconf_netlink.h, zebra/rt.h, zebra/zebra_dplane.c, zebra/zebra_dplane.h, zebra/zebra_mpls.c, zebra/zebra_mpls.h, zebra/zebra_nhg.c
Allow the operator to turn on mpls on interfaces from FRR itself.  
See individual commits for work.
=> Mpls turns on

vtysh/vtysh_main.c
Don't know if this is the correct way to fix this, but it works.
=> vtysh: Handle SIGTSTP (C-z) without exiting the vty shell

pimd/pim_cmd_common.c
Using ttable for displaying "show ip/ipv6 multicast count" command output.
=> pimd, pim6d: Using ttable for displaying output of show multicast command

pimd/pim_cmd_common.c
Using ttable for displaying "show ip/ipv6 mroute count" command output.
=> pimd, pim6d: Using ttable for displaying output of show mroute count command

ospfd/ospf_abr.c
Debug string for ospf is corrected
=> ospfd: debug string corrected

bgpd/bgp_evpn_vty.c, lib/link_state.c, nhrpd/nhrp_peer.c, pathd/path_pcep_pcc.c, pbrd/pbr_vty.c, pimd/pim_cmd.c, pimd/pim_ifchannel.c, pimd/pim_upstream.c, watchfrr/watchfrr.c, zebra/zebra_dplane.c
Some coverity fixes from the update
=> Aug coverity update

doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_addr.h, pimd/pim_vty.c
pim6d: Add debug mroute6 commands 
=> pim6d: Add debug mroute6 commands 

pimd/pim_cmd_common.c
Using ttable for displaying 
"show ip/ipv6 pim rpf"
"show ip/ipv6 pim secondary"
"show ip/ipv6 pim upstream"
"show ip/ipv6 pim upstream-join-desired"
"show ip/ipv6 pim upstream-rpf"
commands output.
=> pimd, pim6d: Using ttable for displaying show ip/ipv6 pim CLI's output

pimd/pim_rp.c
Using ttable for displaying "show ip/ipv6 pim rp-info"  command output.
=> pimd, pim6d: Using ttable for displaying "show ip/ipv6 pim rp-info"  command output.

pimd/pim_cmd_common.c
=> pimd, pim6d: Removing unused parameter

ospfd/ospf_abr.c
these changes are done for improving the code maintainability
=> ospfd: changes to improve code maintainability

ospfd/ospf_apiserver.c
=> ospfd: changes for code maintainability

tests/topotests/bgp_default_originate/test_bgp_default_originate_2links.py
Signed-off-by: ARShreenidhi <rshreenidhi@vmware.com>
=> tests : bgp-default-originate ecmp scenerio is added

bgpd/bgp_clist.c, tests/topotests/bgp_clist/r1/bgpd.conf, tests/topotests/bgp_clist/r1/zebra.conf, tests/topotests/bgp_clist/r2/bgpd.conf, tests/topotests/bgp_clist/r2/zebra.conf, tests/topotests/bgp_clist/test_bgp_clist.py
Closes https://github.com/FRRouting/frr/issues/11806
=> bgpd: Fix community-list handling

babeld/kernel.c, babeld/kernel.h, bgpd/bgp_advertise.c, bgpd/bgp_damp.c, bgpd/bgp_dump.c, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_fsm.c, bgpd/bgp_io.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_nexthop.c, bgpd/bgp_nht.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgp_snmp.c, bgpd/bgp_updgrp.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, bgpd/rfapi/bgp_rfapi_cfg.c, bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_import.c, bgpd/rfapi/rfapi_private.h, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c, pimd/mtracebis_netlink.c, ripd/ripd.c, zebra/zserv.c, zebra/zserv.h
1 and 2) Convert all of bgp to just use monotime() instead of this weird function indirection
3) Intentionally show to coverity that we are downcasting on purpose.  Let's see if the issue goes away
=> Time 32 bits

bgpd/bgp_evpn.c, bgpd/bgp_evpn_vty.c, bgpd/bgp_labelpool.c, bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/11850
=> bgpd: Do not print new line for EVPN CLI outputs if it's a JSON

pimd/pim_cmd_common.c
Using ttable for displaying 
show ip|ipv6 pim channel
show ip|ipv6 pim jp-agg 
Issue: #11246
=> pimd, pim6d: Using ttable for displaying show CLIs

doc/user/pimv6.rst, pimd/pim6_mld.c, pimd/pim6_mld.h, pimd/pim_nb_config.c, pimd/pim_vty.c
=> pim6d: Completing mld config commands.

isisd/isis_adjacency.c, isisd/isis_bpf.c, isisd/isis_circuit.c, isisd/isis_dlpi.c, isisd/isis_dr.c
=> isisd: changes for code maintainability

zebra/zebra_vxlan.c
`show evpn vni detail` doesn't reflect any change in vni transition.
Need to add processing in command of `[no] vni (1-16777215)`.
With the config:
```
!
vni 66
!
vrf vrf1
vni 88
exit-vrf
!
```
Before:
```
(config-vrf)# no vni 88
(config-vrf)# do show evpn vni detail
VNI: 66
Type: L3
Tenant VRF: default
L2 VNIs: <- Empty
```
After:
```
(config-vrf)# no vni 88
(config-vrf)# do show evpn vni detail
VNI: 66
Type: L3
Tenant VRF: default
L2 VNIs: 88 <-
```
=> zebra: fix missing vni transition

tests/topotests/bgp_distance_change/bgp_admin_dist.json, tests/topotests/bgp_distance_change/bgp_admin_dist_vrf.json, tests/topotests/bgp_distance_change/test_bgp_admin_dist.py, tests/topotests/bgp_distance_change/test_bgp_admin_dist_vrf.py, tests/topotests/lib/bgp.py, tests/topotests/lib/common_config.py
This has bgp admin topotest automation suit.
=> tests: adding bgp admin distance topotests.

bgpd/bgp_btoa.c, bgpd/bgp_dump.c, bgpd/bgp_fsm.c
=> bgpd: changes for code maintainability

ripd/ripd.c
=> ripd: changes for code maintainability

bfdd/bfd.c, bfdd/bfd_packet.c
=> bfd: changes for code maintainability

eigrpd/eigrp_network.c, eigrpd/eigrp_packet.c, eigrpd/eigrpd.c
=> eigrpd: changes for code maintainability

tests/topotests/bgp_remove_private_as/test_bgp_remove_private_as.py
Do not fail at the first shot.
=> tests: Validate the routes using polling for bgp_remove_private_as

pimd/pim6_mld.c
Root Cause:
"clear ipv6 mroute" was not deleting the subscribers of gm_if structure.
Fix:
The command "clear ipv6 mroute" deletes grp_pends, gsq_pends, sgs, subscribers, expires of gm_if data structure.
Issue: #11724
=> pim6d: fix clear ipv6 mroute crash

zebra/if_ioctl.c, zebra/if_netlink.c, zebra/if_sysctl.c
=> zebra: changes for code maintainability

pimd/pim_cmd_common.c
Using ttable for displaying
"show ip/ipv6 pim join"
"show ip/ipv6 pim neighbor"
"show ip/ipv6 pim local-membership"
commands output.
Fixes: https://github.com/FRRouting/frr/issues/11246
=> pimd, pim6d: Using ttable for displaying show command outputs

bgpd/bgp_attr.c, tools/coccinelle/route_map_apply.cocci
=> bgpd: Use route_map_result_t for route_map_apply() as return type

bgpd/bgp_evpn_vty.c
=> bgpd: Free ecommunity before returning on warning/error

pimd/pim_cmd_common.c
Using ttable for displaying "show ip/ipv6 pim state" command output.
=> pimd, pim6d: Using ttable for displaying "show ip/ipv6 pim state" command output.

docker/alpine/Dockerfile, docker/alpine/build.sh
Closes https://github.com/FRRouting/frr/issues/11973
=> docker: Keep and copy .apk files after they are built

doc/user/bgp.rst
=> doc: Add `neighbor PEER extended-optional-parameters` command

pimd/pim_igmp.c
When more than 2 routers are present in LAN and the querier goes down, the other routers will wait for other querier present timer to expire to elect a new querier.
This issue will be seen when the router having next lower ip address expires the other querier present timer first and it starts sending the query message. Now on the other non-querier routers it will receive this query and reset its other querier present timer but the querier is still the old one and since it is lowest ip, it never gets updated to the newly elected querier.
Reset the other querier timer only if query is received from the previously elected querier or a better new querier This will make sure that non-querier elects the new querier whose ip address is higher than the old querier
when the old querier goes down …
=> pimd: IGMP Querier election is not correct in LAN scenario

debian/changelog, redhat/frr.spec.in
=> debian, redhat: Update changelog for new release (8.5)

zebra/if_netlink.c
When zebra requests tunnel data it is sending a RTM_GETTUNNEL per interface that is a VXLAN tunnel.  If the kernel that is being used does not support the particular request type then zebra will get a error message per tunnel request back.  Unfortunately netlink_parse_info *stops* reading on the first error message. Therefor one kernels that are returning an error message let's gather all of those errors.  This will allow things like route reads to actually work properly
Fixes: #12056
=> zebra: Allow tunneldump data to work properly on non-supported kernels

bgpd/bgp_nexthop.c
- for a given IP nexthop, dump all NH entries, including colored entries, or entries with an ifindex.
- when a given IP nexthop is requested, the path is displayed. For better readibility, remove the carriage return between 'Last update' and 'Paths', because ctime() function already performs carriage return.
=> bgpd: improve 'show bgp nexthop' command

doc/user/ospfd.rst, ospfd/ospf_dump.c
Signed-off-by: Madhuri Kuruganti <maduri111@gmail.com>
=> ospfd: fix for some of ospf debug commands config lost after reboot

tests/topotests/bgp_basic_functionality_topo1/test_bgp_basic_functionality.py, tests/topotests/bgp_communities_topo1/test_bgp_communities.py, tests/topotests/bgp_communities_topo1/test_bgp_communities_topo2.py, tests/topotests/bgp_ecmp_topo2/test_ebgp_ecmp_topo2.py, tests/topotests/bgp_ecmp_topo2/test_ibgp_ecmp_topo2.py, tests/topotests/bgp_ecmp_topo3/test_ibgp_ecmp_topo3.py, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-1.py, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-2.py, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-3.py, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-4.py, tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2-1.py, tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2-2.py, tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2-3.py, tests/topotests/bgp_gr_functionality_topo2/test_bgp_gr_functionality_topo2-4.py, tests/topotests/bgp_gr_functionality_topo3/bgp_gr_functionality_topo3.py, tests/topotests/bgp_gshut_topo1/test_ebgp_gshut_topo1.py, tests/topotests/bgp_gshut_topo1/test_ibgp_gshut_topo1.py, tests/topotests/bgp_prefix_list_topo1/test_prefix_lists.py, tests/topotests/bgp_route_map/test_route_map_topo1.py, tests/topotests/bgp_route_map/test_route_map_topo2.py
Updating topojson script's assert messages,
which will help in better debugging, when
test will fail.
=> tests: [topojson]Update assert messages for better debugging

tools/frr-reload.py
Closes https://github.com/FRRouting/frr/issues/12088
=> tools: Handle sequence numbers for BGP community (large/ext) in frr-reload.py

bgpd/bgp_community.h, bgpd/bgp_mplsvpn.c, bgpd/bgp_mplsvpn.h, bgpd/bgp_nht.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_table.h, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_accept_own/ce1/bgpd.conf, tests/topotests/bgp_accept_own/ce1/zebra.conf, tests/topotests/bgp_accept_own/ce2/bgpd.conf, tests/topotests/bgp_accept_own/ce2/zebra.conf, tests/topotests/bgp_accept_own/pe1/bgpd.conf, tests/topotests/bgp_accept_own/pe1/ldpd.conf, tests/topotests/bgp_accept_own/pe1/ospfd.conf, tests/topotests/bgp_accept_own/pe1/zebra.conf, tests/topotests/bgp_accept_own/rr1/bgpd.conf, tests/topotests/bgp_accept_own/rr1/ldpd.conf, tests/topotests/bgp_accept_own/rr1/ospfd.conf, tests/topotests/bgp_accept_own/rr1/zebra.conf, tests/topotests/bgp_accept_own/test_bgp_accept_own.py
=> bgpd: Implement ACCEPT_OWN extended community

ospfd/ospf_interface.c
When forming a neighbor relationship on an interface, ospf is currently evaluating unnumbered as highest priority, without any consideration for if you have /32's and non /32's on the interface.  Effectively if I have something like this:
int foo0
ip address 192.168.119.1/24
!
router ospf
network 0.0.0.0/0 area 0
!
ospf will form a neighbor on foo0 if it exists.  Now suppose someone does this:
int foo0
ip address 192.168.120.1/32
This will create the unnumbered interface on foo0 and the peering will come down immediately.
The problem here is that the original designers of the unnumbered code for ospf didn't envision end operators mixing and matching addresses on an interface like this ( for perfectly legitimate reasons I might add ).
So if ospf has both numbered and unnumbered let's match …
=> ospfd: Allow unnumbered and numbered addresses to co-exist better

watchfrr/watchfrr.c
Closes https://github.com/FRRouting/frr/issues/12049
=> watchfrr: Delay restart_kill if still reading configuration

doc/user/pim.rst, doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim6_cmd.h, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_cmd_common.h
Implemented the below CLIs for PIMV6 BSM.
[no] ipv6 pim bsm
[no] ipv6 pim unicast-bsm
show ipv6 pim bsr [vrf NAME] [json$json]
show ipv6 pim bsm-database [vrf NAME] [json$json]
show ipv6 pim bsrp-info [vrf NAME] [json$json]
debug pimv6 bsm
=> pim6d:  BSM CLIs implementation 

isisd/isisd.c, ldpd/neighbor.c, ospf6d/ospf6_route.c, pathd/path_ted.c, pceplib/pcep_msg_messages.c, pceplib/pcep_msg_messages_encoding.c, pceplib/pcep_pcc.c, pceplib/pcep_pcc_api.c, pceplib/pcep_session_logic.c, pceplib/pcep_socket_comm.c, pceplib/pcep_timers.c, pceplib/pcep_utils_double_linked_list.c, pceplib/pcep_utils_logging.c, pceplib/pcep_utils_memory.c, pceplib/pcep_utils_queue.c, pimd/pim_vty.c
upgraded to clang-16 on a vm and saw some compile issues that need to be cleaned up So let's do that
=> Clang 16 robots

zebra/zebra_fpm.c
Signed-off-by: Spoorthi K <spk@redhat.com>
=> zebra: Remove duplicate update of msg_type

bgpd/rfapi/rfapi.c, lib/agentx.c, vtysh/vtysh_config.c
see individual commits but fixes a couple minor things
=> Various and sundry

tools/frr.in, tools/frrinit.sh.in
Closes https://github.com/FRRouting/frr/issues/12163
=> tools: Honor sysdir, confdir, bindir for frr-reload.py from "frr" wrapper

bgpd/bgp_nht.c, doc/user/index.rst, doc/user/nexthop_groups.rst, doc/user/pbr.rst, doc/user/subdir.am, lib/linklist.c, lib/nexthop_group.c, lib/nexthop_group.h, lib/zclient.c, lib/zclient.h, pbrd/pbr_main.c, pbrd/pbr_nht.c, pbrd/pbr_nht.h, sharpd/sharp_nht.c, sharpd/sharp_zebra.c, tests/topotests/all_protocol_startup/r1/ospf6d.conf, tests/topotests/all_protocol_startup/r1/ospfd.conf, tests/topotests/all_protocol_startup/r1/show_ip_ospf_interface.ref, tests/topotests/all_protocol_startup/test_all_protocol_startup.py, vtysh/vtysh_config.c, zebra/rt_netlink.c, zebra/zapi_msg.c, zebra/zebra_nhg.c, zebra/zebra_nhg.h, zebra/zebra_vty.c
```
nexthop-group B
resilient buckets 32 idle_timer 100 unbalanced_timer 500
nexthop 192.168.100.33 enp7s0
exit
```
vtysh -c "show nexthop-group rib sharp" 
```
ID: 185483869 (sharp)
RefCnt: 1
Uptime: 00:50:26
VRF: default
Valid, Installed
Depends: (335)
via 192.168.100.33, enp7s0 (vrf default), weight 1
Buckets: 32 Idle Timer: 100 Unbalanced Timer: 500 Unbalanced time: 0
sharpd@robot:~/frr$ ip nexthop show id 185483869
id 185483869 group 335 type resilient buckets 32 idle_timer 1000 unbalanced_timer 5000 unbalanced_time 0 proto sharp 
sharpd@robot:~/frr$ 
```
=> Resilience

alpine/APKBUILD.in, bgpd/bgp_regex.h, bgpd/bgp_routemap.c, configure.ac, doc/user/installation.rst, docker/alpine/Dockerfile, lib/frrstr.c, lib/frrstr.h, lib/vty.c, lib/vty.h
Related: https://github.com/FRRouting/frr/issues/12162
=> docker: Use PCRE2 for Alpine

doc/user/pathd.rst, lib/ipaddr.h, pathd/path_cli.c, pathd/path_ted.c, pathd/path_ted.h, pathd/pathd.c, pathd/pathd.h
Add some debug guards to current pathd traces.
=> Pathd debug

bgpd/bgp_route.c
This commit addresses an issue that happens when using bgp peering with a rr client, with a received prefix which is the local ip address of the bgp session.
When using bgp ipv4 unicast session, the local prefix is received by a peer, and finds out that the proposed prefix and its next-hop are the same. To avoid a route loop locally, no nexthop entry is referenced for that prefix, and the route will not be selected.
When the received peer is a route reflector, the prefix has to be selected, even if the route can not be installed locally.
Fixes: ("fb8ae704615c") bgpd: prevent routes loop through itself
=> bgpd: authorise to select bgp self peer prefix on rr case

bgpd/bgp_fsm.c, bgpd/bgp_keepalives.c, bgpd/bgp_network.c, bgpd/bgp_route.c
Some internal commits that should be upstreamed
=> Bgp debugs upstream

staticd/static_nb_config.c
Closes https://github.com/FRRouting/frr/issues/12218
=> staticd: Fix crash for an existing route with color

staticd/static_vty.c
Simplify all DEFUNs by moving all logic to the northbound translation function and transforming all function parameters into a single structure.
---
The goal of this PR is to simplify the code to make it easier to accommodate new parameters: before this every time a new parameter was added all callers of this function had to be modified. If new commands were added the DEFUNs had to replicate the logic scattered over other DEFUNs.
With this PR adding the BFD static route monitoring command variants should require less code changes in the CLI side.
=> staticd: improve CLI/northbound translation code

bgpd/bgp_mpath.c, ospf6d/ospf6_abr.c, ospf6d/ospf6_route.c, ospf6d/ospf6_route.h, ospfd/ospf_ism.c, ospfd/ospf_network.c
See individual commits but a small grab bag of cleanup and fixes
=> Misc and then some

bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_peer_graceful_shutdown/r1/bgpd.conf, tests/topotests/bgp_peer_graceful_shutdown/r1/zebra.conf, tests/topotests/bgp_peer_graceful_shutdown/r2/bgpd.conf, tests/topotests/bgp_peer_graceful_shutdown/r2/zebra.conf, tests/topotests/bgp_peer_graceful_shutdown/r3/bgpd.conf, tests/topotests/bgp_peer_graceful_shutdown/r3/zebra.conf, tests/topotests/bgp_peer_graceful_shutdown/test_bgp_peer_graceful_shutdown.py
Closes https://github.com/FRRouting/frr/issues/6246
=> bgpd: Implement graceful-shutdown command per neighbor

bgpd/bgp_packet.c, bgpd/bgp_snmp_bgp4v2.c
Related: https://github.com/FRRouting/frr/issues/6486
=> bgpd: Implement SNMP BGP4V2-MIB (bgp4V2PeerErrorsTable)

pimd/pim_cmd_common.c
Using ttable for displaying "show ip/ipv6 pim nexthop" command output
Issue: #12270
=> pimd, pim6d: Using ttable for displaying "show ip/ipv6 pim nexthop" command output

doc/user/bgp.rst, tests/topotests/bgp_comm_list_match/r1/bgpd.conf, tests/topotests/bgp_comm_list_match/r1/zebra.conf, tests/topotests/bgp_comm_list_match/r2/bgpd.conf, tests/topotests/bgp_comm_list_match/r2/zebra.conf, tests/topotests/bgp_comm_list_match/test_bgp_comm_list_match.py
Closes https://github.com/FRRouting/frr/issues/12422
=> doc: Fix BGP community-list misleading example

bgpd/bgp_keepalives.c, ospf6d/ospf6_lsa.c, ospfclient/ospf_apiclient.c, ospfclient/subdir.am, ospfd/ospf_apiserver.c, ospfd/ospf_apiserver.h, ospfd/ospf_snmp.c, ospfd/subdir.am
see individual commits
a) Remove some more MTYPE_TMP
b) Cleanup ospfapiclient to notdirectly include .c files
=> More mtype tmp

ldpd/ldpe.c, vtysh/vtysh_config.c, zebra/zebra_ns.c
fix some use after free's found w/ valgrind
=> General use

doc/user/basic.rst, vtysh/vtysh.c
Add motd commad.
Displays motd when requested by the user.
=> Add motd command

bgpd/bgp_aspath.c, bgpd/bgp_aspath.h, bgpd/bgp_route.c, bgpd/bgp_vty.c, bgpd/bgpd.c, tests/topotests/bgp_confed1/r1/bgp_ipv4_unicast.json, tests/topotests/bgp_confed1/r1/bgp_summary.json, tests/topotests/bgp_confed1/r1/bgpd.conf, tests/topotests/bgp_confed1/r1/zebra.conf, tests/topotests/bgp_confed1/r2/bgp_ipv4_unicast.json, tests/topotests/bgp_confed1/r2/bgp_summary.json, tests/topotests/bgp_confed1/r2/bgpd.conf, tests/topotests/bgp_confed1/r2/isisd.conf, tests/topotests/bgp_confed1/r2/zebra.conf, tests/topotests/bgp_confed1/r3/bgp_ipv4_unicast.json, tests/topotests/bgp_confed1/r3/bgp_summary.json, tests/topotests/bgp_confed1/r3/bgpd.conf, tests/topotests/bgp_confed1/r3/isisd.conf, tests/topotests/bgp_confed1/r3/zebra.conf, tests/topotests/bgp_confed1/r4/bgp_ipv4_unicast.json, tests/topotests/bgp_confed1/r4/bgp_summary.json, tests/topotests/bgp_confed1/r4/bgpd.conf, tests/topotests/bgp_confed1/r4/zebra.conf, tests/topotests/bgp_confed1/test_bgp_confed1.py
currently the following configuration
dut:
!
interface ntfp2
ip router isis 1
!
router bgp 200
bgp confederation identifier 300
bgp confederation peers 300
neighbor 192.168.1.1 remote-as 100
neighbor 192.168.2.2 remote-as 300
!
neighbor 192.168.2.2 default-originate
!
router isis 1
net 49.0001.0002.0002.0002.00
redistribute ipv4 connected level-2
!
end
router:
!
interface ntfp2
ip router isis 1
isis circuit-type level-2-only
!
router bgp 300
bgp confederation identifier 300
bgp confederation peers 200
neighbor 192.168.2.1 remote-as 200
neighbor 192.168.3.2 remote-as 400
!
network 3.3.3.0/24
!
router isis 1
is-type …
=> bgp:  fix case where confederation id same as member-as

bgpd/bgp_addpath.c, bgpd/bgp_open.c, bgpd/bgp_route.c, bgpd/bgp_updgrp.c, bgpd/bgp_updgrp.h, tests/topotests/bgp_labeled_unicast_addpath/r1/bgpd.conf, tests/topotests/bgp_labeled_unicast_addpath/r1/zebra.conf, tests/topotests/bgp_labeled_unicast_addpath/r2/bgpd.conf, tests/topotests/bgp_labeled_unicast_addpath/r2/zebra.conf, tests/topotests/bgp_labeled_unicast_addpath/r3/bgpd.conf, tests/topotests/bgp_labeled_unicast_addpath/r3/zebra.conf, tests/topotests/bgp_labeled_unicast_addpath/r4/bgpd.conf, tests/topotests/bgp_labeled_unicast_addpath/r4/zebra.conf, tests/topotests/bgp_labeled_unicast_addpath/test_bgp_labeled_unicast_addpath.py
Closes https://github.com/FRRouting/frr/issues/5373
=> bgpd: Labeled unicast fixes for addpath capability

pimd/pim_msdp_packet.c
I found these problems while testing against a bad behaving MSDP peer.
1. MSDP crashes if the peer sends a TLV with an unexpectedly big payload. Follow the RFC recommended behavior.
2. Fix a crash on the packet debugger while parsing a bad packet.
=> pimd: two MSDP packet handling fixes

bgpd/bgp_route.c
```
Direct leak of 112 byte(s) in 1 object(s) allocated from:
0 0x7feb66337a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
1 0x7feb660cbcc3 in qcalloc lib/memory.c:116
2 0x55cc3cba02d1 in info_make bgpd/bgp_route.c:3831
3 0x55cc3cbab4f1 in bgp_update bgpd/bgp_route.c:4733
4 0x55cc3cbb0620 in bgp_nlri_parse_ip bgpd/bgp_route.c:6111
5 0x55cc3cb79473 in bgp_update_receive bgpd/bgp_packet.c:2020
6 0x55cc3cb7c34a in bgp_process_packet bgpd/bgp_packet.c:2929
7 0x7feb6610ecc5 in thread_call lib/thread.c:2006
8 0x7feb660bfb77 in frr_run lib/libfrr.c:1198
9 0x55cc3cb17232 in main bgpd/bgp_main.c:520
10 0x7feb65ae5082 in __libc_start_main ../csu/libc-start.c:308
SUMMARY: AddressSanitizer: 112 byte(s) leaked in 1 allocation(s).
```
Signed-off-by: Donatas …
=> bgpd: Free memory allocated by info_make() when hitting maximum-prefix

doc/user/zebra.rst
=> doc: Clarify asic offload documentation in zebra

lib/privs.c
Fixes #12480 .
Don't let `zprivs_caps_init` allocate resources without checking if there were other caps previously allocated.
This fixes a memory leak that happens on daemons that `fork()` and reuse the `<daemon>_di` (see `ldpd`/`lde`/`ldpe` code).
=> lib: fix capability double resource allocation

ospfd/ospf_spf.c
Fixes #12479 .
Fix the following problems:
- Always free vertex next hops on `vertex_parent_free`
- Signalize failure on `ospf_spf_add_parent` when parent already exists so the caller has the chance to `free()` any allocated resources.
- Don't reuse vertex next hops without the reference count logic in `ospf_nexthop_calculation`. Instead allocate a new copy so it can be `free()`d later without complications
=> ospfd: fix memory leak on SPF calculation

bgpd/bgp_snmp_bgp4v2.c, bgpd/bgp_snmp_bgp4v2.h
Closes https://github.com/FRRouting/frr/issues/6486
=> bgpd: SNMP continued work on IPv6

doc/accords/cli-colors
This is pretty much a writeup of the discussion we had on the FRR weekly call about an hour ago.  I added a bunch of detail but hopefully it still represents the overall consensus.
=> accords: CLI coloring

doc/user/zebra.rst, zebra/zebra_vty.c
Added JSON support for show nexthop-group rib
command.
JSON output:
```
{
"8":{
"type":"zebra",
"refCount":4,
"uptime":"00:00:45",
"vrf":"default",
"valid":true,
"installed":true,
"interfaceIndex":3,
"nexthops":[
{
"flags":3,
"fib":true,
"directlyConnected":true,
"interfaceIndex":3,
"interfaceName":"eth0",
"vrf":"default",
"active":true
}
]
},
"10":{
"type":"zebra",
"refCount":3,
"uptime":"00:00:46",
"vrf":"default",
"valid":true,
"installed":true,
"interfaceIndex":3,
"nexthops":[
{
"flags":3,
"fib":true,
"ip":"2001::2",
"afi":"ipv6",
"interfaceIndex":3,
"interfaceName":"eth0",
"vrf":"default",
"active":true,
"weight":1
}
]
},
"2":{
"type":"zebra",
"refCount":2,
"uptime":"00:00:47",
"vrf":"default",
"valid":true,
"installed":true,
"interfaceIndex":1,
"nexthops":[
{
"flags":3,
"fib":true, …
```
=> zebra: JSON support for show nexthop-group rib

doc/user/zebra.rst, zebra/zebra_routemap.c
Changes:
JSON support added for below commands,
- show ip nht route-map vrf all json
- show ip nht route-map vrf <name> json
- show ipv6 nht route-map vrf all json
- show ipv6 nht route-map vrf <name> json
- show ipv6 nht route-map json
- show ip nht route-map json
Testing Done: Unit testing completed.
tor-1# show ip nht route-map vrf default json
```
{
"afi":"ipv4",
"vrfs":{
"default":{
"protocols":{
"system":"none",
"kernel":"none",
"connected":"connected-policy",
"static":"none",
"rip":"none",
"ripng":"none",
"ospf":"none",
"ospf6":"none",
"isis":"none",
"bgp":"bgp-policy",
"pim":"none",
"eigrp":"none",
"nhrp":"none",
"hsls":"none",
"olsr":"none",
"table":"none",
"ldp":"none",
"vnc":"none",
"vnc-direct":"none",
"vnc-rn":"none",
"bgp-direct":"none",
"bgp-direct-to-nve-groups":"none", …
```
=> zebra: show ip nht route-map vrf json support

ospf6d/ospf6_neighbor.c
master and slave.
=================
Memory leak backtraces
2022-11-23 01:51:10,525 - ERROR: ==842== 1,100 (1,000 direct, 100 indirect) bytes in 5 blocks are definitely lost in loss record 29 of 31
2022-11-23 01:51:10,525 - ERROR: ==842==    at 0x4C31FAC: calloc (vg_replace_malloc.c:762)
2022-11-23 01:51:10,525 - ERROR: ==842==    by 0x4E8A1BF: qcalloc (memory.c:111)
2022-11-23 01:51:10,525 - ERROR: ==842==    by 0x13555A: ospf6_lsa_alloc (ospf6_lsa.c:723)
2022-11-23 01:51:10,525 - ERROR: ==842==    by 0x1355F3: ospf6_lsa_create_headeronly (ospf6_lsa.c:756)
2022-11-23 01:51:10,525 - ERROR: ==842==    by 0x135702: ospf6_lsa_copy (ospf6_lsa.c:790)
2022-11-23 01:51:10,525 - ERROR: ==842==    by 0x13B64B: ospf6_dbdesc_recv_slave (ospf6_message.c:976)
2022-11-23 01:51:10,525 …
=> ospf6d: Fixing memory leak in ospf6_lsa_create_headeronly for both

ospfd/ospf_vty.c
a) if show_function happened to be NULL we would leak json memory b) json_lsa_type was being allocated but only used in the default case, leaking memory c) json output would sometimes produce text output and that is incorrect
=> ospfd: Fix some json mem leaks and some issues

zebra/dplane_fpm_nl.c, zebra/rt_netlink.c, zebra/rt_netlink.h
As the title says. Please see the commit message for more details.
=> fpm: Send NH message to FPM even if the local kernel doesn't support it

doc/developer/cli.rst, doc/developer/workflow.rst
=> doc: add guidance for CLI cmds that output JSON

doc/developer/subdir.am, doc/user/subdir.am, lib/elf_py.c, lib/xref.h, zebra/zserv.c, zebra/zserv.h
Fix a bunch of small issues that crept up while updating the Debian mainline packages.
=> *: various build fixes

doc/user/bgp.rst
Builds are complaining about this issue.
=> doc: Ensure that the underline length is correct

tests/topotests/lib/lutil.py
This change alters the behavior of existing test code. The
default mode (before any call to luSetWaitType()) is now
"strict".
The historical behavior of luCommand(op="wait) is to ignore
failures to match the specified regexp in the specified time.
In those cases, no result was logged and no error was signaled.
This change introduces a new "strict" mode for luCommand(op="wait):
in "strict" wait mode, each invocation of luCommand(op="wait)
generates an explicit, logged failure result when it fails to match
the specified regexp in the specified time. These failures signal
an error for the test.
Calling luSetWaitType("nostrict") restores the historical behavior.
Calling luSetWaitType("strict") (re)enables the new strict behavior.
Individual calls to luCommand() may also specify …
=> topotests/lib/lutil.py: luSetWaitType("strict"|"nostrict")

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_path_attribute_discard/exabgp.env, tests/topotests/bgp_path_attribute_discard/peer1/exabgp.cfg, tests/topotests/bgp_path_attribute_discard/r1/bgpd.conf, tests/topotests/bgp_path_attribute_discard/r1/zebra.conf, tests/topotests/bgp_path_attribute_discard/test_bgp_path_attribute_discard.py
Closes https://github.com/FRRouting/frr/issues/12592
=> bgpd: Add `neighbor path-attribute discard` command

bgpd/bgp_mplsvpn.c, lib/if.c, lib/if.h, tests/topotests/bgp_accept_own/pe1/bgpd.conf, tests/topotests/bgp_accept_own/pe1/zebra.conf, tests/topotests/bgp_accept_own/test_bgp_accept_own.py
Closes https://github.com/FRRouting/frr/issues/12630
Talked in Slack, it fixes the described problem.
=> bgpd: Allow importing local routes with accept-own mechanism

tests/topotests/lib/micronet.py
- required for old OSs like centos 7
- fixes #11924
=> tests: replace -a (all) with individual flags for nsenter

zebra/zebra_netns_notify.c
Do extra inotify data structure checks and copy the file name to a stack buffer making sure it is null byte terminated.
Found by Coverity Scan (CID 1465494)
---
Checks explanation following the inotify(7) man page:
> The  name field is present only when an event is returned for a file inside a watched directory; it identifies
> the filename within the watched directory.  This filename is null-terminated, and  may  include  further  null
> bytes ('\0') to align subsequent reads to a suitable address boundary.
The `if (event->len == 0)` check makes sure we always process events with names (even if empty).
> The  len  field  counts  all  of the bytes in name, including the null bytes; the length of each inotify_event
> structure is thus sizeof(struct inotify_event)+len.
The null byte is …
=> zebra: make sure string is null terminated

tests/topotests/evpn_type5_test_topo1/test_evpn_type5_chaos_topo1.py, tests/topotests/evpn_type5_test_topo1/test_evpn_type5_topo1.py, tests/topotests/lib/pim.py, tests/topotests/multicast_pim_bsm_topo1/test_mcast_pim_bsmp_01.py, tests/topotests/multicast_pim_bsm_topo2/test_mcast_pim_bsmp_02.py, tests/topotests/multicast_pim_sm_topo1/test_multicast_pim_sm_topo1.py, tests/topotests/multicast_pim_sm_topo2/test_multicast_pim_sm_topo2.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo3.py, tests/topotests/multicast_pim_sm_topo3/test_multicast_pim_sm_topo4.py, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pim_static_rp.py, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pim_static_rp1.py, tests/topotests/multicast_pim_static_rp_topo1/test_multicast_pim_static_rp2.py
Few assert/error messages are updated for test
scripts for better debugging.
=> tests: [topojson] Update assert/error messages

bgpd/bgp_route.c, bgpd/bgp_routemap.c
Some extra modifications necessary after https://github.com/FRRouting/frr/pull/12664 has been merged.
=> Vpnv6 encode plus

lib/filter_cli.c
When setting rule for access-list ( and prefix-list ) without sequence, it
will automatically get a sequence by `acl_get_seq()`, and return
`CMD_SUCCESS` for command even this sequence value is wrong.
In this scene, `CMD_WARNING_CONFIG_FAILED` should be returned with a
warning.
So, add the check in `acl_get_seq()` and move `nb_cli_enqueue_change()`
after the check of wrong sequence.
Both `plist_remove_if_empty()` and `acl_remove_if_empty()` should ignore
this check, there is no change on them.
Before:
```
anlan(config)# access-list aa seq 4294967295 deny 6.6.6.6/32
anlan(config)# access-list aa deny 6.6.6.7/32  <- Return CMD_SUCCESS
YANG error(s):
Value "4294967300" is out of uint32's min/max bounds.
Value "4294967300" is out of uint32's min/max bounds.
Value "4294967300" is out of …
```
=> lib: fix wrong returned value for filter

lib/wheel.c, lib/wheel.h, zebra/zebra_rib.c
see individual commits, code inspection shows that we have some stuff that is never used.
=> remove dead code

bgpd/bgp_evpn.c, bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h
Couple commits reducing unnecessary churn + cleaning up some martian handling code.
=> BGP Martian Tunnel-IP Improvements

tests/topotests/zebra_rib/test_zebra_rib.py
The test was sometimes failing around the sleep(4) for waiting for the routes to be installed.  Instead of blindly sleeping let's check to see that the routes are actually there in zebra and then continue on.
=> tests: zebra_rib remove a sleep

bgpd/bgp_io.c
BGP was modified in a0b937de428e14e869b8541f0b7810113d619c2e to grab the peer->io_mtx before validating the header to ensure that the input Queue was not being modified by anyone else at that moment in time.  Unfortunately validate_header can detect a problem and attempt to relock the mutex, which deadlocks.  This deadlock in the bgp_io pthread is the lone deadlock at first, eventually though bgp attempts to write another packet to the peer( say when the it's time to send the next packet ) and the main pthread of bgpd becomes deadlocked and then the whole bgpd process is stuck at that point in time leaving us dead in the water.
The point of locking the mutex earlier was to ensure that the input Queue wasn't being modified by anyone else, (Say reading off it ) as that we wanted to ensure …
=> bgpd: Don't try to recursively hold peer io mutex

babeld/babel_filter.c
The first argument of `access_list_lookup` and `prefix_list_lookup` should be `AFI_` constants instead of `AF_` constants.
Signed-off-by: Yuxiang Zhu <vfreex@gmail.com>
=> babeld: Fix filtering against all interfaces

tools/frr.vim
Let's make these unique IDs actually a bit useful.
https://aurora.nox.tf/tmp/gotoxref.webm
=> tools: add `GotoXref` vim script

tools/etc/rsyslog.d/45-frr.conf
=> tools: Fix missing pbrd in rsyslog.d 45-frr.conf file

pbrd/pbr_vty.c
Ticket: 2699411
Signed-off-by: Wesley Coakley <wcoakley@nvidia.com>
=> pbrd: fix large tableids displayed as negative

lib/yang_translator.c
Closes https://github.com/FRRouting/frr/issues/12775
=> lib: Release memory of YANG translation module on error

bgpd/bgp_updgrp_adv.c, tests/topotests/bgp_default_originate_withdraw/r1/bgpd.conf, tests/topotests/bgp_default_originate_withdraw/r1/zebra.conf, tests/topotests/bgp_default_originate_withdraw/r2/bgpd.conf, tests/topotests/bgp_default_originate_withdraw/r2/zebra.conf, tests/topotests/bgp_default_originate_withdraw/r3/bgpd.conf, tests/topotests/bgp_default_originate_withdraw/r3/zebra.conf, tests/topotests/bgp_default_originate_withdraw/test_bgp_default_originate_withdraw.py
Closes https://github.com/FRRouting/frr/issues/12749
=> bgpd: Intern default-originate attributes to avoid use-after-free

babeld/babel_interface.c
=> babeld: changes for code maintainability

doc/user/eigrpd.rst, doc/user/pim.rst, doc/user/pimv6.rst, doc/user/ripd.rst
Correct the pid path for daemons, and remove one useless line in "ripd.rst" .
=> doc: correct the pid path for daemons

bgpd/bgp_route.c, zebra/if_netlink.c
See individual but upstream some commits.
=> some missed upstream commits

pimd/pim_zpthread.c, zebra/zebra_l2_bridge_if.c
=> Coverity evpn

ldpd/address.c
=> ldpd: changes for code maintainability

doc/user/ripd.rst, doc/user/ripngd.rst
Correct ripd&ripngd doc based on code.
=> doc: cosmetic changes for ripd

bgpd/bgp_attr.c, bgpd/bgp_routemap.c
Two minor changes about vpnv6 encoding scheme.
no impact on behaviour, just recoding.
=> Vpnv6 nexthop encoding

bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_flowspec.c, bgpd/bgp_label.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/rfapi/vnc_export_bgp.c
=> bgpd: Drop struct attr from bgp_withdraw()

bgpd/rfapi/rfapi_import.c
An rfapi timer callback is responsible for the memory in a context object, even in special-case exit paths. Always free that object.
Fixes: #12847
=> bgpd: free rfapi callback object always

tests/topotests/bgp_gr_restart_retain_routes/test_bgp_gr_restart_retain_routes.py
Depending on ip_route and kernel, the output might include a nhid which causes the test to fail with a strict text output check. Change to json output to avoid the issue
=> tests: Change bgp_gr_retained_routes to use json output of "ip route"

bgpd/bgp_route.c, tests/topotests/bgp_vpnv4_ebgp/r1/bgp_ipv4_routes.json, tests/topotests/bgp_vpnv4_ebgp/r1/bgpd.conf, tests/topotests/bgp_vpnv4_ebgp/r1/ipv4_routes.json, tests/topotests/bgp_vpnv4_ebgp/r1/zebra.conf, tests/topotests/bgp_vpnv4_ebgp/r2/zebra.conf, tests/topotests/bgp_vpnv4_ebgp/r3/bgp_ipv4_routes.json, tests/topotests/bgp_vpnv4_ebgp/r3/bgpd.conf, tests/topotests/bgp_vpnv4_ebgp/r3/zebra.conf, tests/topotests/bgp_vpnv4_ebgp/test_bgp_vpnv4_ebgp.py
The selection reason value was wrong for imported VPN prefixes.
Fix it and add a topotest
=> Vpnv4 ecmp

bgpd/rfapi/rfapi_import.c
Fix for rfapi memory leaks identified in #12478 
Closes https://github.com/FRRouting/frr/issues/12478
=> bgpd/rfapi: memleak: clean CE tables at exit

bgpd/bgp_vty.c
Keep the common code for command: "show ip bgp summary [wide]".
=> bgpd: Simplify the code for show command

bgpd/bgp_nht.c, tests/topotests/bgp_ipv6_ll_peering/r1/bgpd.conf, tests/topotests/bgp_ipv6_ll_peering/r1/zebra.conf, tests/topotests/bgp_ipv6_ll_peering/r2/bgpd.conf, tests/topotests/bgp_ipv6_ll_peering/r2/zebra.conf, tests/topotests/bgp_ipv6_ll_peering/test_bgp_ipv6_ll_peering.py
Closes https://github.com/FRRouting/frr/issues/12860
=> bgpd: Check if the peer is configured as interface when checking NHT

ospf6d/ospf6_abr.c, ospf6d/ospf6_flood.c, ospf6d/ospf6_gr.c, ospf6d/ospf6_interface.c, ospf6d/ospf6_lsdb.c, ospf6d/ospf6_lsdb.h, ospfd/ospf_packet.c
A few fixes to make OSPF GR a bit more graceful :)
=> OSPF Graceful Restart fixes

tests/topotests/lib/pim.py, tests/topotests/multicast_pim6_sm_topo1/multicast_pim6_sm_topo1.json, tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm1.py, tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm2.py
1. Automated new scenarios to multicast pim6
SM test suite. Added 10 test cases to verify
multicast PIM6-SM functionality.
2. Enhanced or added new libraries to support
multicast pimv6 automation
Co-Authored-by: Vijay Kumar Gupta <vijayg@vmware.com>
=> tests: [PIMv6] Adding multicast pim6 SM testsuite

ospf6d/ospf6_flood.c, ospf6d/ospf6_gr_helper.c, ospf6d/ospf6_message.c, ospf6d/ospf6_neighbor.c, ospfd/ospf_nsm.c, ospfd/ospf_packet.c
A couple of patches to upstream for OSPF, OSPFv3 logging.
=> ospfd, ospfd6: Add more logging

lib/filter_cli.c, lib/filter_nb.c, tests/topotests/bgp_prefix_list_any/r1/bgpd.conf, tests/topotests/bgp_prefix_list_any/r1/zebra.conf, tests/topotests/bgp_prefix_list_any/r2/bgpd.conf, tests/topotests/bgp_prefix_list_any/r2/zebra.conf, tests/topotests/bgp_prefix_list_any/test_bgp_prefix_list_any.py
Closes https://github.com/FRRouting/frr/issues/13007
=> lib: Adjust only any flag for prefix-list entries if destroying

ospfd/ospf_spf.c, ospfd/ospf_ti_lfa.c
see individual commits but this cleans up 2 easy memory leaks with ospf_ti_lfa.c
=> Ospf ti lfa leaks

doc/user/ospfd.rst, ospfd/ospf_vty.c
Summary of the changes:
* Code cleanup
* Add "detail" option
* Fix inconsistency in the JSON output
Please refer to the individual commits for details.
=> ospfd: Improve the "show ip ospf database" command

bgpd/bgp_route.c
Some debugs were especially hard to figure out in bgp_route.c
a) If using a %p pointer to print the bgp_path_info this is pretty useless.  Print where it came from instead b) Use A.B.C.D/M(VRFNAME) when outputing the prefix
Just basically give more useful information.
=> bgpd: Add vrf name and peer name to some bgp debugs

zebra/dplane_fpm_nl.c, zebra/redistribute.c, zebra/router-id.c, zebra/zapi_msg.c, zebra/zebra_evpn_mac.c, zebra/zebra_mpls.c, zebra/zebra_mpls_vty.c, zebra/zebra_pw.c, zebra/zebra_rib.c, zebra/zebra_rnh.c, zebra/zebra_vty.c
Let's make this as consistent as is possible.
=> zebra: Use zebra_vrf_lookup_by_id when we can

bgpd/bgpd.c, tests/topotests/bgp_route_map_delay_timer/r1/bgpd.conf, tests/topotests/bgp_route_map_delay_timer/r1/zebra.conf, tests/topotests/bgp_route_map_delay_timer/r2/bgpd.conf, tests/topotests/bgp_route_map_delay_timer/r2/zebra.conf, tests/topotests/bgp_route_map_delay_timer/test_bgp_route_map_delay_timer.py
Closes https://github.com/FRRouting/frr/issues/13125
=> bgpd: Do not announce routes immediatelly on prefix/distribute/filter changes

tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_topo1.py, tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_type7_lsa.py, tests/topotests/ospf_basic_functionality/test_ospf_authentication.py, tests/topotests/ospf_basic_functionality/test_ospf_chaos.py, tests/topotests/ospf_basic_functionality/test_ospf_ecmp.py, tests/topotests/ospf_basic_functionality/test_ospf_ecmp_lan.py, tests/topotests/ospf_basic_functionality/test_ospf_lan.py, tests/topotests/ospf_basic_functionality/test_ospf_nssa.py, tests/topotests/ospf_basic_functionality/test_ospf_routemaps.py, tests/topotests/ospf_basic_functionality/test_ospf_rte_calc.py, tests/topotests/ospf_basic_functionality/test_ospf_single_area.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper1.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper2.py, tests/topotests/ospf_gr_helper/test_ospf_gr_helper3.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_authentication.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_ecmp_lan.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_nssa2.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_routemaps.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_rte_calc.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_single_area.py
Few assert/error messages are updated for test
scripts for better debugging.
=> tests: [topojson] Update assert/error messages for ospf scripts

tests/topotests/bgp_labeled_unicast_addpath/test_bgp_labeled_unicast_addpath.py
Closes https://github.com/FRRouting/frr/issues/13130
=> tests: Check received routes count for labeled-unicast with addpath

mgmtd/mgmt_vty.c
The changes involve adding show debuggin command for MGMTd which resolves command incomplete issue.
Fixes #13154
=> mgmtd: Fix for issue 13154.

babeld/babeld.c, babeld/babeld.h, babeld/util.h, bgpd/bgp_routemap.c, lib/compiler.h, lib/routemap.c, nhrpd/debug.h, ospfd/ospf_routemap.c, zebra/zebra_routemap.c
a) Add unlikely/likely macros in zebra.h
b) Add some additional debugs to routemap.c
c) Make DEBUG_ROUTEMAP_DETAIL unlikely
d) cleanup some code that is not needed
=> Unlikely routemap

alpine/APKBUILD.in
protobuf-c-compiler
protobuf-c-dev
=> docker: Install missing dependencies for Alpine build

lib/cspf.c, lib/cspf.h, sharpd/sharp_vty.c
=> [WIP] sharpd: fix leak

ripd/ripd.c
=> ripd: Cosmetic changes for ripd

lib/if_rmap.c, lib/if_rmap.h, lib/subdir.am, ripd/rip_nb.c, ripd/rip_nb.h, ripd/rip_nb_config.c, ripngd/ripng_nb.c, ripngd/ripng_nb.h, ripngd/ripng_nb_config.c, yang/frr-if-rmap.yang, yang/frr-ripd.yang, yang/frr-ripngd.yang, yang/subdir.am
Good example of using a YANG grouping mapping to shared library code.
Also fixes  memleak.
=> Convert if_rmap to use YANG northbound

bgpd/bgp_route.c
Closes https://github.com/FRRouting/frr/issues/13267
=> bgpd: Fix crash for `show bgp ... neighbor received-routes detail|PREFIX

isisd/isis_affinitymap.c, isisd/isis_flex_algo.c, isisd/isis_spf.c, isisd/isisd.c
Fix some coverity scanner issues and an issue with a JSON output
=> isisd: fixes for Flex-Algo

lib/elf_py.c, zebra/zebra_dplane.c
see different commits just some more coverity clean up
=> coverity phase #392356

bgpd/bgp_evpn_vty.c, bgpd/bgp_mplsvpn_snmp.c, bgpd/bgp_route.c
See individual commits but just some coverity stuff that has snuck through a bit.
=> Bgp before light

doc/developer/topotests.rst, tests/topotests/bgp_gr_functionality_topo1/test_bgp_gr_functionality_topo1-3.py, tests/topotests/conftest.py, tests/topotests/lib/micronet_compat.py, tests/topotests/lib/topogen.py, tests/topotests/lib/topotest.py, tests/topotests/munet/cli.py, tests/topotests/munet/mutini.py
Also remove sleep hack for `--gdb-daemons` launched daemons, adding proper launch detection (or lack thereof!)
=> Add --pcap, --logd, --pause-at-end options to topotest

tests/topotests/munet/base.py
Fixes bad fixed path use and rootcmd functionality to run things in the root namespace (all but pid at least).
=> tests: import munet version 0.12.16

lib/vty.c, mgmtd/mgmt_ds.c, mgmtd/mgmt_txn.c
Cleanup all zlog_err() that were meant for debug only.
Signed-off-by: Pushpasis Sarkar <pushpasis@gmail.com>
=> mgmtd, lib: Cleanup zlog_err()

isisd/isis_flex_algo.c, isisd/isis_spf.c, isisd/isisd.c, lib/flex_algo.c, lib/flex_algo.h
Free flex-algorithm database memory when an IS-IS area is destroyed.
=> isisd, lib: fix flex-algo memory leak

mgmtd/mgmt.h, mgmtd/mgmt_ds.h, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_history.c, mgmtd/mgmt_history.h
=> mgmtd: simplify commit id to just be a timeval string

zebra/zebra_dplane.c
1) Clean up some mistakes about how memory can fail to allocate in the dplane
2) Clean up some possible memory leaks inside of a dplane function
=> Dplane memory leak

ripd/ripd.c
=> ripd: fix another memtype mismatch

bgpd/bgp_attr.c, tests/topotests/bgp_aigp/r2/bgpd.conf, tests/topotests/bgp_aigp/r3/bgpd.conf, tests/topotests/bgp_aigp/r4/bgpd.conf, tests/topotests/bgp_aigp/r5/bgpd.conf, tests/topotests/bgp_aigp/r6/bgpd.conf, tests/topotests/bgp_aigp/r7/bgpd.conf, tests/topotests/bgp_aigp/test_bgp_aigp.py
Closes https://github.com/FRRouting/frr/issues/13469
=> bgpd: AIGP should be non-transitive

zebra/zebra_rib.c
There are two issues being addressed:
a) The ZEBRA_ON_RIB_PROCESS_HOOK_CALL script point was creating a fs pointer per dplane ctx in
rib_process_dplane_results().
b) The fs pointer was not being deleted and directly leaked.
For (a) Move the creation of the fs to outside
the do while loop.
For (b) At function end ensure that the pointer
is actually deleted.
=> zebra: Reduce creation and fix memory leak of frrscripting pointers

tests/topotests/lib/topojson.py, tests/topotests/ospf_basic_functionality/test_ospf_asbr_summary_topo1.py, tests/topotests/ospfv3_basic_functionality/test_ospfv3_asbr_summary_topo1.py
See individual commits, but hopefully fix the router-id not being changed and our tests failing issue we are seeing.
=> Clear up clear command

tests/topotests/bgp_disable_addpath_rx/r1/bgpd.conf, tests/topotests/bgp_disable_addpath_rx/r2/bgpd.conf, tests/topotests/bgp_disable_addpath_rx/r3/bgpd.conf, tests/topotests/bgp_disable_addpath_rx/r4/bgpd.conf
Was incorrectly setting BGP timers.
=> tests: Fix timers command for bgp_disable_addpath_rx test

doc/user/ripngd.rst, ripngd/ripng_cli.c, ripngd/ripng_main.c, ripngd/ripng_nb_config.c, ripngd/ripng_zebra.c, ripngd/ripngd.c, ripngd/ripngd.h, tests/topotests/ripng_allow_ecmp/r1/frr.conf, tests/topotests/ripng_allow_ecmp/r2/frr.conf, tests/topotests/ripng_allow_ecmp/r3/frr.conf, tests/topotests/ripng_allow_ecmp/r4/frr.conf, tests/topotests/ripng_allow_ecmp/r5/frr.conf, tests/topotests/ripng_allow_ecmp/test_ripng_allow_ecmp.py, yang/frr-ripngd.yang
Adopted version of https://github.com/FRRouting/frr/pull/13430
=> ripng: Implement allow-ecmp X command

doc/developer/link-state.rst
RFC7572 does not mention BGP-LS. I believe it's RFC7752.
=> doc: fix typo RFC7572 to RFC7752

tests/topotests/lib/topogen.py, tests/topotests/lib/topotest.py
Additionally, some cleanup in the config code, including new warning for missing configuration files when user is expecting them.
=> tests: cleanup unified config and config arg

tests/topotests/ospfapi/test_ospf_clientapi.py
fixes #13584
The test had the ospf client injecting multiple opaque LSAs on 5s pace, but the test itself verified and advanced on an LSA in the middle of that sequence and not the last one. Then the test reset the ospf client and originating router. If a later injected LSA managed to get in to the router and flooded prior to the client/router reset then the opaque data or sequence number could differ from the expected value.
=> tests: ospfapi: fix non-determinism in test

tests/topotests/lib/topotest.py
Use the non deprecated format.
=> tests: Convert to using logger.warning

bgpd/bgp_clist.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_vty.c, eigrpd/eigrp_update.c, zebra/zebra_mlag.c, zebra/zserv.c
See the individual commits but this is just a bunch of code cleanup from running coverity
=> Bunch of code cleanup from Coverity

lib/mgmt_be_client.c, lib/mgmt_be_client.h, staticd/static_main.c
Code is no longer using a global FE "client context", and instead creates client objects, rename the structure and it's uses to reflect this.
Remove an obfuscating abstraction layer whose existence was entirely based on using a uintptr_t rather than a pointer to an declared-only struct.
Remove unsupported API code.
=> lib: mgmtd: remove backend abstraction layer and other cleanup

doc/user/bgp.rst
Looks like people don't find what does it mean (Policy) at first shot, let's try giving more hints here.
=> doc: Document RFC8212 under `Displaying BGP Information` section

lib/vty.c
=> lib: close config files after reading (coverity)

tests/topotests/bgp_always_compare_med/bgp_always_compare_med_topo1.json, tests/topotests/bgp_always_compare_med/test_bgp_always_compare_med_topo1.py, tests/topotests/lib/bgp.py
1. Automated 5 different scenarios to verify BGP always compare med functionality.
2. Added/enhanced bgp.py to support config/un config bgp always compare med related configurations.
=> tests: Adding bgp_always_compare_med testuite

tests/topotests/lib/mcast-tester.py, tests/topotests/lib/pim.py, tests/topotests/multicast_mld_join_topo1/test_multicast_mld_local_join.py, tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm1.py, tests/topotests/multicast_pim6_sm_topo1/test_multicast_pim6_sm2.py, tests/topotests/multicast_pim6_static_rp_topo1/test_multicast_pim6_static_rp1.py, tests/topotests/multicast_pim6_static_rp_topo1/test_multicast_pim6_static_rp2.py
These pim6 tests were seemingly copied from 2 year old - since fixed - buggy pim topotests/infra. So repeat all the same fixes again...
=> tests: fixing pim6 topotest bugs

doc/developer/process-architecture.rst
Refer to the latest code, modify the description of event system.
=> doc: Adjust event system

bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c
Reverts FRRouting/frr#13509 
This breaks a test
=> Revert "bgpd: upon if up event, evaluate bnc with matching nexthop"

doc/developer/process-architecture.rst
Refer to the latest code, modified the description of pthread.
=> doc: Adjust pthread description

tests/topotests/rip_topo1/test_rip_topo1.py, tests/topotests/ripng_topo1/test_ripng_topo1.py
Closes https://github.com/FRRouting/frr/issues/13718
=> tests: Convert rip/ripng tests using run_and_expect

bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgp_vty.h
Closes https://github.com/FRRouting/frr/issues/13778
=> GCC13 nits

tests/topotests/bgp_local_as_dotplus_private_remove/test_bgp_local_as_dotplus_private_remove.py
This test has several issues:
A) The convergence function is spamming the show neighbor command until success, if the neighbor never comes up the test will never finish. This adds unnecessary load to an already loaded test system.  Use run_and_expect to properly wait for the neighbor relationship to come up.
B) The convergence function should not sleep for 1 second *After* the neighbor is established
C) The _bgp_as_path() function fails if the prefix has not been received yet. This looking for the prefix data should be within a run_and_expect() functionality. Else a loaded test system will fail in this function because while we may be in an established state, prefixes might not yet have been exchanged and there is no point in failing the test without giving the system some time to …
=> topotests: structural issues in bgp_local_as_dotplus_private_remove

isisd/isis_tlvs.c
Fixes a crash associated with attempting to read beyond the end of the stream when parsing ASLA Sub-TLV.
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7830859 in __GI_abort () at abort.c:79
#2  0x00007ffff7d51321 in _zlog_assert_failed (xref=xref@entry=0x7ffff7e306c0 <_xref.19624>, extra=extra@entry=0x0) at lib/zlog.c:667
#3  0x00007ffff7ca802c in stream_getc (s=0x55555593d2a0) at lib/stream.c:353
#4  0x00005555556421eb in unpack_item_ext_subtlv_asla (mtid=<optimized out>, exts=<optimized out>, indent=<optimized out>, log=<optimized out>, s=<optimized out>, …
```
=> isisd: Fix read beyond end of stream of ASLA Sub-TLV parsing

bgpd/bgp_labelpool.c, bgpd/bgp_labelpool.h, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/bgp_lu_topo1/R1/labelpool.summ.json, tests/topotests/bgp_lu_topo1/R2/labelpool.summ.json, tests/topotests/bgp_lu_topo2/R1/labelpool.summ.json, tests/topotests/bgp_lu_topo2/R2/labelpool.summ.json, zebra/zserv.c
Related: https://github.com/FRRouting/frr/issues/13753
=> bgpd: Use synchronous way to get labels from Zebra

ripngd/ripng_interface.c, ripngd/ripng_offset.c
=> ripngd: changes for code maintainability

bgpd/bgp_vty.c
Add an error log message when the config-end notification is not received for 10 minutes. This bgpd change was moved to a separate commit as per a review comment on the ospf6d change.
=> bgpd: Add config-end timeout error log message.

lib/command.c, lib/mgmt.proto, lib/mgmt_fe_client.c, lib/mgmt_fe_client.h, lib/mgmt_msg.c, lib/mgmt_msg.h, lib/northbound_cli.c, lib/vty.c, lib/vty.h, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_be_adapter.h, mgmtd/mgmt_ds.c, mgmtd/mgmt_ds.h, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_history.c, mgmtd/mgmt_txn.c, mgmtd/mgmt_txn.h, tests/lib/test_grpc.cpp, vtysh/vtysh.c, vtysh/vtysh_config.c
This is a backport of #13795 for dev/9.0 branch, direct cherry-pick no conflicts.
=> [9.0] mgmt lock simplification - backport #13795

tests/topotests/multicast_pim_uplink_topo2/multicast_pim_uplink_topo2.json, tests/topotests/multicast_pim_uplink_topo2/test_multicast_pim_uplink_topo2.py, tests/topotests/multicast_pim_uplink_topo3/multicast_pim_uplink_topo3.json, tests/topotests/multicast_pim_uplink_topo3/test_multicast_pim_uplink_topo3.py
Automated 8 new test cases to verify multicast PIM uplink(8 uplink) functionality.
=> tests: Add multicast-pim-multi-uplink test suite

doc/user/ripngd.rst, ripngd/ripng_routemap.c, tests/topotests/ripng_route_map/r1/frr.conf, tests/topotests/ripng_route_map/r2/frr.conf, tests/topotests/ripng_route_map/r3/frr.conf, tests/topotests/ripng_route_map/test_ripng_route_map.py
Closes https://github.com/FRRouting/frr/issues/8141
=> ripng: match ipv6 address [prefix-list] CMDs

zebra/zserv.c
Closes https://github.com/FRRouting/frr/issues/13858
=> zebra: Free Zebra client resources

tests/topotests/bgp_vpnv4_asbr/test_bgp_vpnv4_asbr.py
=> tests: Fix broken check_ping run_and_expect semantics

bgpd/bgp_ecommunity.c
Reformat and align to be readable.
=> bgpd: Fix comment for ecommunity_ecom2str()

zebra/zebra_rib.c
Just more details what's going on when deleting a route.
=> zebra: Dump route details when deleting a route

tests/topotests/bgp_vpnv4_asbr/test_bgp_vpnv4_asbr.py
Ensure in the test that MPLS entries are installed before declaring the test fails.
=> topotests: bgp_vpnv4_asbr, wait that mpls entry is installed

tools/frr-reload.py
When no ip pim is performed subsequent pim related configs under the interface also implicitly deleted.
When doing this via frr-reload requires to remove any explicit no ip pim <blah> lines so delete list.
Testing Done:
running-config:
```
interface lo
ip pim
ip pim use-source 6.0.0.1
exit
```
frr.conf:
```
remove two pim config lines.
interface lo
exit
```
Before fix:
```
2023-06-29 23:44:26,062  INFO: Failed to execute interface lo  no ip pim use-source 6.0.0.1 2023-06-29 23:44:26,142  INFO: Failed to execute interface lo  no ip pim use-source 2023-06-29 23:44:26,221  INFO: Executed "interface lo  no ip pim"
```
After fix:
Only no ip pim executed and rest of the other lines removed from delete list.
```
2023-06-30 01:07:32,618  INFO: Executed "interface lo  no ip pim"
```
Signed-off-by: …
=> tools: fix pim interface config deletion

bgpd/bgp_open.c, bgpd/bgp_open.h, bgpd/bgp_packet.c, bgpd/bgp_routemap.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h
https://www.rfc-editor.org/rfc/rfc8810.html
=> bgpd: rfc8810 deprecations 

bgpd/rfapi/rfapi_import.c
Closes https://github.com/FRRouting/frr/issues/13966
=> bgpd: rfapi memleak: clean CE tables at exit

bgpd/bgp_vty.c, lib/asn.h
=> bgpd: Show neighbors software version if description is not set

lib/command.c, lib/command.h, lib/command_graph.c, lib/command_graph.h, lib/command_match.c, lib/command_py.c, lib/grammar_sandbox.c, python/clippy/__init__.py, python/xrelfo.py, tools/permutations.c
Backport to stable/8.4.
Closes https://github.com/FRRouting/frr/issues/13944
=> lib: make cmd_element->attr a bitmask & clarify

bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, tests/topotests/bgp_flowspec/peer1/exabgp.cfg, tests/topotests/bgp_flowspec/test_bgp_flowspec_topo.py, tests/topotests/bgp_l3vpn_to_bgp_vrf/r1/bgpd.conf, tests/topotests/bgp_l3vpn_to_bgp_vrf/r2/bgpd.conf, tests/topotests/bgp_l3vpn_to_bgp_vrf/r4/bgpd.conf, tests/topotests/bgp_vpnv4_per_nexthop_label/test_bgp_vpnv4_per_nexthop_label.py, tests/topotests/conftest.py, tests/topotests/isis_tilfa_topo1/rt1/isisd.conf, tests/topotests/isis_tilfa_topo1/rt1/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt2/isisd.conf, tests/topotests/isis_tilfa_topo1/rt2/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt3/isisd.conf, tests/topotests/isis_tilfa_topo1/rt3/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt4/isisd.conf, tests/topotests/isis_tilfa_topo1/rt4/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt5/isisd.conf, tests/topotests/isis_tilfa_topo1/rt5/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt6/isisd.conf, tests/topotests/isis_tilfa_topo1/rt6/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/test_isis_tilfa_topo1.py, tests/topotests/lib/topotest.py, tests/topotests/zebra_rib/test_zebra_rib.py, zebra/kernel_netlink.c
Fixes a couple of issues to make topotests stricter
=> Tests need to be stricter

doc/developer/building-docker.rst
=> doc: fix the error path.

bgpd/bgp_route.c, bgpd/bgp_updgrp_adv.c
Closes https://github.com/FRRouting/frr/issues/13987
=> bgpd: Memory leaks in communities (backport)

bgpd/rfapi/rfapi.c, bgpd/rfapi/rfapi_rib.c, bgpd/rfapi/rfapi_vty.c
Closes https://github.com/FRRouting/frr/issues/13989
=> bgpd: rfapi memleak fixes

tests/topotests/lib/topotest.py
Old behavior was to print a gobbledy non-decoded "bytes" string, new behavior decodes into text strings and adds some functionality. New info:
- threads
- registers
- succinct backtrace
- full backtrace starting from first relevant function (skips all the assert/abort/core_handler frames)
- disassemble of the relevant function if it was a non-assert/non-abort core (e.g., SIGSEGV).
=> tests: fix/improve the printing of backtrace from cores

tests/topotests/babel_topo1/test_babel_topo1.py
Retry fetching route table for a little while until we get correct answer
=> tests: test_babel_topo1: tolerate slow results

tools/etc/frr/support_bundle_commands.conf, zebra/zebra_nhg.c, zebra/zebra_rib.c
See individual commits, tl;dr -> bgp_default_originate tests frequently fail because a route was not being installed.
=> Zebra same route

doc/user/ospfd.rst, ospfd/ospf_route.c, ospfd/ospf_route.h, ospfd/ospf_vty.c
Allows to user easily distinguish route items by router that originates it.
The output format, by example as following:
```
============ OSPF network routing table ============
N T  10.0.0.0/24           [23] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.0.5
N    10.0.30.0/24          [24] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.0.5
N    10.0.50.1/32          [13] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.8.255.33
N    10.0.50.3/32          [23] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.0.1
N    10.0.50.7/32          [23] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.0.1
N T  10.0.60.0/30          [24] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.0.5
N    10.0.253.0/24         [34] area: 0.0.0.0
via 192.168.124.67, eth7
adv 10.0.60.2
bsp-debianrt-exp1# show ip …
```
=> ospfd: Show advertise router in 'show ip ospf route' command

tests/topotests/bgp_bmp/r1/bgpd.conf, tests/topotests/bgp_bmp/r1/zebra.conf, tests/topotests/bgp_bmp/r2/bgpd.conf, tests/topotests/bgp_bmp/r2/zebra.conf, tests/topotests/bgp_bmp/test_bgp_bmp.py, tests/topotests/lib/bmp_collector/bgp/open/__init__.py, tests/topotests/lib/bmp_collector/bgp/update/__init__.py, tests/topotests/lib/bmp_collector/bgp/update/af.py, tests/topotests/lib/bmp_collector/bgp/update/nlri.py, tests/topotests/lib/bmp_collector/bgp/update/path_attributes.py, tests/topotests/lib/bmp_collector/bgp/update/rd.py, tests/topotests/lib/bmp_collector/bmp.py, tests/topotests/lib/bmp_collector/bmpserver, tests/topotests/lib/topogen.py
The test consists of the following:
- test the bmp **monitoring** [**pre-policy**/**post-policy**] **IPv4**/**IPv6** unicast.
- ~~**pmacct** as a bmp server (version **1.7.6**)~~
- pmacct is not used anymore, a basic bmp collector has been added to the topotests.
- platform **ubuntu 22.04**.
Below an example of the bmp logging file resulted from the present basic bmp test.
~~[logs.txt](https://github.com/FRRouting/frr/files/10922748/logs.txt)~~
[bmp_logs.txt](https://github.com/FRRouting/frr/files/11407825/bmp_logs.txt)
=> Add basic bgp bmp test

bgpd/bgp_nexthop.c, bgpd/bgp_nexthop.h, bgpd/bgp_nht.c
let us give a chance to look at what happens with that patch !
https://github.com/FRRouting/frr/pull/13745
=> Bgp nht other if cases 2

pimd/pim_iface.c
Assume that `pim_ifp` has two ip (v4) addresses, one is primary, the other is secondary. After remove primary ip, the secondary ip doesn't be promoted, so `pim_ifp->primary_address` will wrongly be set to "0.0.0.0", it leads to `pim_sock_delete(ifp)` on this interface.
Add the promotion for primary address.
Fixes #13590
=> pimd: Fix missing promotion for primary address

doc/user/isisd.rst, isisd/isis_cli.c, isisd/isis_nb.c, isisd/isis_nb.h, isisd/isis_nb_config.c, isisd/isis_redist.c, isisd/isis_redist.h, isisd/isis_zebra.c, isisd/isis_zebra.h, isisd/isisd.c, isisd/isisd.h, tests/topotests/isis_topo1/r3/r3_route.json, tests/topotests/isis_topo1/r4/r4_route.json, tests/topotests/isis_topo1/r5/isisd.conf, tests/topotests/isis_topo1/r5/r5_route.json, tests/topotests/isis_topo1/r5/zebra.conf, yang/frr-isisd.yang, zebra/redistribute.c
The redistribute table yang model is incomplete in isis.
The functionality is also buggy.
Let us fix it.
=> Redistribute isis table

isisd/isis_sr.c, isisd/isis_sr.h, isisd/isis_zebra.c, tests/topotests/isis_tilfa_topo1/rt1/isisd.conf, tests/topotests/isis_tilfa_topo1/rt1/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt2/isisd.conf, tests/topotests/isis_tilfa_topo1/rt2/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt3/isisd.conf, tests/topotests/isis_tilfa_topo1/rt3/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt4/isisd.conf, tests/topotests/isis_tilfa_topo1/rt4/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt5/isisd.conf, tests/topotests/isis_tilfa_topo1/rt5/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/rt6/isisd.conf, tests/topotests/isis_tilfa_topo1/rt6/step1/show_yang_interface_isis_adjacencies.ref, tests/topotests/isis_tilfa_topo1/test_isis_tilfa_topo1.py
A few fixes to make this topotest more stable. Thanks @donaldsharp for all the help!
Fixes #14043
=> tests: improve stability of the IS-IS TI-LFA topotest

bgpd/bgpd.c
When 'no neighbor .. update-source' is issued for a regular peer, that peer is always reset.  This is unnecessary if the peer is a member of a peer-group and it inherits an identical update-source, so let's skip the reset/Notification for that condition.
Config:
------------
router bgp 1
neighbor PG peer-group
neighbor PG remote-as internal
neighbor PG update-source 100.64.0.3
neighbor 192.168.122.99 peer-group PG
neighbor 192.168.122.99 update-source 100.64.0.3
Before:
------------
ub20-2(config-router)# do show ip bgp sum | include .99
192.168.122.99  4          1         3         4        0    0    0 00:00:43            0        0 N/A
ub20-2(config-router)# no neighbor 192.168.122.99 update-source
ub20-2(config-router)# do show ip bgp sum | include .99
192.168.122.99  4          1 …
=> bgpd: skip reset when removing dup update-source

tests/topotests/bgp_addpath_best_selected/r2/bgpd.conf, tests/topotests/bgp_addpath_best_selected/test_bgp_addpath_best_selected.py
Test everything else only after we have an initial good state.
=> tests: Improve bgp_addpath_best_selected topotest

tests/topotests/bgp_srv6l3vpn_over_ipv6/test_bgp_srv6l3vpn_over_ipv6.py, tests/topotests/bgp_srv6l3vpn_sid/test_bgp_srv6l3vpn_sid.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf2/test_bgp_srv6l3vpn_to_bgp_vrf2.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py, tests/topotests/bgp_vpnv4_asbr/test_bgp_vpnv4_asbr.py, tests/topotests/lib/checkping.py
=> tests: amalgamate check_ping

doc/user/zebra.rst, tests/topotests/static_routing_mpls/r1/zebra.conf, tests/topotests/static_routing_mpls/r2/zebra.conf, tests/topotests/static_routing_mpls/test_static_routing_mpls.py, yang/frr-zebra.yang, zebra/interface.c, zebra/zebra_nb.c, zebra/zebra_nb.h, zebra/zebra_nb_config.c
Convert MPLS command to yang NB API.
Use enable|disable keywords instead of "[no] mpls".
=> Mpls yang enable disable

pbrd/pbr_vty.c, pbrd/pbr_zebra.c
Fix coverity-reported issues in pbrd
=> pbrd: address coverity issues reported 230815

ospf6d/ospf6_auth_trailer.c, ospf6d/ospf6_auth_trailer.h
Please see individual commits for details.
=> OSPFv3 authentication trailer interop

bgpd/bgp_attr.c
Relax this handling (RFC 7606) only for eBGP peers.
More details: https://datatracker.ietf.org/doc/html/rfc7606#section-4
There are two error cases in which the Total Attribute Length value can be in conflict with the enclosed path attributes, which themselves carry length values:
* In the first case, the length of the last encountered path
attribute would cause the Total Attribute Length to be exceeded
when parsing the enclosed path attributes.
* In the second case, fewer than three octets remain (or fewer than
four octets, if the Attribute Flags field has the Extended Length
bit set) when beginning to parse the attribute.  That is, this
case exists if there remains unconsumed data in the path
attributes but yet insufficient data to encode a single minimum-
sized path attribute. <<<< …
=> bgpd: Treat-as-withdraw attribute if remaining data is not enough

bgpd/bgp_fsm.c
first two commits are just making things nicer and cleaning up code a bit.  third commit fixes a use after free.
=> Bgp fsm problemos

bgpd/bgp_fsm.c
It was noticed that occassionally peering failed in a testbed upon investigation it was found that the peer was not in the peer hash and we saw these failure messages:
Aug 25 21:31:15 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: %NOTIFICATION: sent to neighbor 2001:cafe:1ead:4::4 4/0 (Hold Timer Expired) 0 bytes
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 100663299] Can't get remote address and port: Transport endpoint is not connected
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 100663299] %bgp_getsockname() failed for  peer 2001:cafe:1ead:4::4 fd 27 (from_peer fd -1)
Aug 25 21:31:22 doca-hbn-service-bf3-s06-1-ipmi bgpd[3048]: [EC 33554464] %Neighbor failed in xfer_conn
root@doca-hbn-service-bf3-s06-1-ipmi:/var/log/hbn/frr# vtysh -c 'show bgp …
=> bgpd: Add peers back to peer hash when peer_xfer_conn fails

ospfd/ospfd.c
Addressed a memory leak in OSPF by fixing the improper deallocation of area range nodes when removed from the table. Introducing a new function, `ospf_range_table_node_destroy` for proper node cleanup, resolved the issue.
```
Direct leak of 56 byte(s) in 2 object(s) allocated from:
#0 0x7faf661d1d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7faf65bce1e9 in qcalloc lib/memory.c:105
#2 0x55a66e0b61cd in ospf_area_range_new ospfd/ospf_abr.c:43
#3 0x55a66e0b61cd in ospf_area_range_set ospfd/ospf_abr.c:195
#4 0x55a66e07f2eb in ospf_area_range ospfd/ospf_vty.c:631
#5 0x7faf65b51548 in cmd_execute_command_real lib/command.c:993
#6 0x7faf65b51f79 in cmd_execute_command_strict lib/command.c:1102
#7 0x7faf65b51fd8 in …
```
=> ospfd: fix area range memory leak

zebra/rule_netlink.c
We've recently extended the features available through the iprules/pbr cli and zapi messaging, and most of those extensions can't be used in netlink/linux. Only attempt to install in netlink iprules that include supported actions; ignore requests with actions that aren't supported by netlink.
=> zebra: ignore iprule requests for unsupported actions

bgpd/bgp_route.c, bgpd/bgp_route.h, lib/prefix.h
=> Evpn bgp bestpath debug issues

bgpd/bgp_attr.c
Before this path we used session reset method, which is discouraged by rfc7606.
Handle this as rfc requires.
Signed-off-by: Christian Breunig <christian@breunig.cc>
(cherry picked from commit bcb6b58d9530173df41d3a3cbc4c600ee0b4b186)
Fixes https://github.com/FRRouting/frr/issues/14289
Backport of https://github.com/FRRouting/frr/pull/14290
=> bgpd: Use treat-as-withdraw for tunnel encapsulation attribute (backport for 7.5)

tools/etc/frr/support_bundle_commands.conf
Description : 
Addition of support bundle commands for mgmtd daemon.
=> mgmtd: support bundle commands for mgmt.

bgpd/bgp_advertise.c, bgpd/bgp_advertise.h, bgpd/bgp_evpn.c, bgpd/bgp_evpn_mh.c, bgpd/bgp_label.c, bgpd/bgp_mplsvpn.c, bgpd/bgp_nexthop.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_table.c, bgpd/bgp_table.h
Bunch of coverity issues came in with the break up of the bgp_node and bgp_dest.  Let's clean them up
=> Bgp coverity cleanup early sept

zebra/interface.c
=> zebra: fix link update for veth interfaces

pathd/path_pcep_cli.c
Add the possibility to de-configure PCE options. Actually the no command will reset the options to the default values. When a PCE option is modified reset the PCC peer session to take into account the change occured.
=> pathd: add no command for pce/pce-config options

lib/elf_py.c, lib/event.c, lib/ipaddr.h, lib/northbound.c, lib/prefix.c, lib/printf/printfcommon.h, lib/sha256.c, lib/vty.c, lib/zlog_5424.c
Probably missed one or two but this should take care of the majority of Coverity nits in `lib/`.
=> lib: fix a bunch of coverity nits

doc/user/vtysh.rst
Related: https://github.com/FRRouting/frr/issues/14444
=> doc: domainname MUST be manually written to vtysh.conf also

doc/user/ospfd.rst, doc/user/pbr.rst
Closes https://github.com/FRRouting/frr/issues/14477
=> Some recent documentation adjustments

doc/user/mgmtd.rst
=> doc: reference the correct MGMTd show command

bgpd/bgp_attr.c, bgpd/bgp_linkstate_tlv.c, bgpd/bgp_linkstate_tlv.h
fix link state coverity scan issues
=> bgpd: fix link state coverity scan issues

tests/topotests/all_protocol_startup/test_all_protocol_startup.py
Don't hard-code a sharpd nhg id: those values aren't stable if the daemons/protos/route-types change. Use json show output to find the id in the 'resilient' nhg test case in the all_protocol_startup suite.
=> tests: locate nhg id from json output in all_proto_startup

zebra/zebra_pbr.c
Include a zclient value in the hash and tree key computations for iprules in zebra: clients may collide without this.
=> zebra: add zclient to iprules key

ospfd/ospfd.c
Issue: https://github.com/FRRouting/frr/issues/14004
Following the information shared by Corneyy https://github.com/FRRouting/frr/issues/14004#issuecomment-1651307025, the following codepath https://github.com/FRRouting/frr/blob/11d19d1279c77691628b025b51bcb2eb13fd87c7/ospfd/ospfd.c#L1269C13-L1269C13 would be causing the problem.
The problem was happening because the ospf->oiflist has this behaviour, each interface was removed and added at the end of the list in each ospf_network_run_subnet call, generation an infinite loop.
As a solution, a copy of the list was generated and we interacted with a fixed list.
=> vtysh freezed on ospf 'no network' command when there are multiple networks and interfaces

bgpd/bgp_attr.c, bgpd/bgp_route.c, bgpd/bgp_updgrp.c, bgpd/bgp_vty.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_oad/r1/frr.conf, tests/topotests/bgp_oad/r2/frr.conf, tests/topotests/bgp_oad/r3/frr.conf, tests/topotests/bgp_oad/test_bgp_oad.py
More details: https://datatracker.ietf.org/doc/html/draft-uttaro-idr-bgp-oad
=> bgpd: Implement EBGP-OAD peering type

tests/topotests/bgp_unique_rid/test_bgp_unique_rid.py
This is test when ospf and bgp router ids are same.
=> tests: Adding a bgp router id chaos test case.

ospf6d/ospf6_interface.c
Closes https://github.com/FRRouting/frr/issues/14777
=> ospf6d: Let the user override interface cost for a loopback

lib/event.c, lib/frrevent.h
Attempt to allow different FD's be handled in a round-robin fashion
=> Event io smoothing

doc/developer/.readthedocs.yaml, doc/developer/requirements.txt, doc/user/.readthedocs.yaml, doc/user/requirements.txt
=> doc: restore frr docs theme

staticd/static_vty.c
Debug commands should be installed in staticd, not in mgmtd.
=> staticd: fix debug commands

bgpd/bgp_bmp.c
bmp bgp asn & router_id coverity fix
=> bgpd: bmp bgp asn & router_id coverity fix

doc/developer/.readthedocs.yaml, doc/user/.readthedocs.yaml
=> doc: fix docs path to requirements.txt

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_packet.c
This is an manually backport of pull request https://github.com/FRRouting/frr/pull/14716
=> bgpd: A couple more bgpd crash fixes for malformed packets (backport #14716)

tests/topotests/munet/base.py, tests/topotests/munet/cli.py, tests/topotests/munet/mutest/userapi.py, tests/topotests/munet/native.py, tests/topotests/munet/testing/fixtures.py, tests/topotests/munet/testing/hooks.py, tests/topotests/munet/watchlog.py
- Import 0.13.10 which adds watched logs feature, among others.
=> tests: import munet 0.13.10

bgpd/bgp_bmp.c, lib/resolver.c, lib/resolver.h, nhrpd/nhrp_main.c, nhrpd/nhrp_vc.c
See individual commits just a few more memory leaks on shutdown
=> More frr memory leaks on shutdown

lib/northbound_oper.c, tests/topotests/mgmt_oper/simple-results/result-intf-eth0-name.json, tests/topotests/mgmt_oper/simple-results/result-intf-eth0-vrf.json, tests/topotests/mgmt_oper/simple-results/result-intf-name.json, tests/topotests/mgmt_oper/test_simple.py
- fix key leaf queries
- fix specific list entry with non-key leaf top element
=> lib: fix specific entry queries

zebra/interface.c
Closes https://github.com/FRRouting/frr/issues/15050
=> zebra: Push all configured IP addresses when the interface comes up

lib/agentx.c
The maximum number of file descriptors in an fd set is limited by FD_SETSIZE. This limitation is important because the libc macros FD_SET(), FD_CLR() and FD_ISSET() will invoke a sigabort if the size of the fd set given to them is above FD_SETSIZE.
We ran into such a sigabort with bgpd because snmp can return an fd set of size higher than FD_SETSIZE when calling snmp_select_info(). An unfortunate FD_ISSET() call later causes the following abort:
Received signal 6 at 1701115534 (si_addr 0xb94, PC 0x7ff289a16a7c); aborting... /lib/x86_64-linux-gnu/libfrr.so.0(zlog_backtrace_sigsafe+0xb3) [0x7ff289d62bba] /lib/x86_64-linux-gnu/libfrr.so.0(zlog_signal+0x1b4) [0x7ff289d62a1f] /lib/x86_64-linux-gnu/libfrr.so.0(+0x102860) [0x7ff289da4860] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) …
=> lib snmp: use snmp's large fd sets for agentx

doc/developer/mgmtd-dev.rst, doc/developer/northbound/retrofitting-configuration-commands.rst, mgmtd/mgmt_be_adapter.c
Also change `be_client_xpaths` to `be_client_config_xpaths` referred in the doc to make much clearer it's use (since there's a separate `be_client_oper_xpaths`.
=> doc: mgmtd: update mgmtd conversion doc to be current.

doc/user/bgp.rst
Mention the limitations of this type of peering
in bgp.
=> doc: Update bgp unnumbered documentation

zebra/interface.c, zebra/zebra_nhg.c
Cleanup the code a bit.  See the two commits.  Nothing fancy here.
=> Zebra touchups

bgpd/rfapi/bgp_rfapi_cfg.c, pceplib/test/pcep_msg_messages_test.c, pceplib/test/pcep_msg_tlvs_test.c
a) Removal of strdup from rfapi code
b) Fix of some new coverity issues.
=> Some fixes

zebra/zebra_nhg.c
I was doing some nhg debugging in zebra and noticed some debugs that were extraordinarly chatty for no reason.  Let's consolidate and cleanup to make things easier to understand in the logs.
=> Nhg debugs

doc/user/routemap.rst
Closes https://github.com/FRRouting/frr/issues/15318
=> doc: Fix the documentation for route-map continue statement

doc/developer/topotests.rst, docker/ubuntu-ci/Dockerfile, tests/lib/subdir.am
- update the reference ubuntu dockerfiles
- fix the grpc test to pass again
=> update doc with new more strict protobuf requirements 

bgpd/bgp_bmp.c, tests/topotests/bgp_bmp/r1/bgpd.conf, tests/topotests/bgp_bmp/r1/zebra.conf, tests/topotests/bgp_bmp/r2/bgpd.conf, tests/topotests/bgp_bmp/test_bgp_bmp.py, tests/topotests/lib/bmp_collector/bmp.py, tests/topotests/lib/bmp_collector/bmpserver, tests/topotests/lib/topogen.py
When using BMP, export the labels if any
Add a topotest for that
=> bgpd: export labels into BMP

bgpd/bgp_route.c
=> Bgp best selection cleanup

doc/user/basic.rst
Closes: https://github.com/FRRouting/frr/issues/15465
=> doc: Fix one spelling `dissallowed` to `disallowed`

tests/topotests/mgmt_oper/simple-results/result-intf-eth0-exact.json, tests/topotests/mgmt_oper/simple-results/result-intf-eth0-with-config.json, yang/frr-zebra.yang, zebra/zebra_nb.c, zebra/zebra_nb.h, zebra/zebra_nb_state.c
- add interface's bond to oper state
- implement zif-type oper state leaf
=> zebra: oper data additions

mgmtd/mgmt_txn.c
Make the wording clearer about what's going on.
=> mgmtd: change error message

ospf6d/ospf6_neighbor.c
add localIfaceAdress field in show ipv6 ospf6 neighbor detail json command.
=> ospf6d: add localLinkLocalAddress field

bgpd/bgp_route.c
A route and its nexthop might belong to different VRFs. Therefore, we need both the bgp and bgp_nexthop pointers.
Fixes: 8d51fafdcbef3dcf06df796e4f9b83d2bbd5edc2 ("bgpd: Drop bgp_static_update_safi() function")
=> bgpd: Check the route and the nexthop appropriately when validating NH

bgpd/bgp_routemap.c
Closes https://github.com/FRRouting/frr/issues/15527
=> bgpd: Update default-originate route-map actual map structure

doc/user/isisd.rst
Correct isis commands based on code.
=> doc: fix some commands for isis

debian/changelog, redhat/frr.spec.in
regular release house keeping.
=> debian, redhat: updating changelog for 10.0 release

doc/user/isisd.rst
Correct one command based on code.
=> doc: fix one command for isis

doc/user/bgp.rst
Fixed one bgp comamnd based on code.
=> doc: fix one bgp command

tests/topotests/bgp_asdot_regex/r1/show_bgp_ipv4.json, tests/topotests/bgp_asdot_regex/r2/show_bgp_ipv4.json, tests/topotests/bgp_srv6l3vpn_sid/r1/vpnv6_rib.json, tests/topotests/bgp_srv6l3vpn_sid/r2/vpnv6_rib.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r1/vpnv6_rib.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r2/vpnv6_rib.json, tests/topotests/evpn_pim_1/spine/bgp.summ.json
BGP table version is variable. Don't check it.
=> topotests: do not check table version

lib/stream.h, zebra/zebra_evpn.c, zebra/zebra_evpn_mac.c, zebra/zebra_evpn_mh.c, zebra/zserv.c
=> Zebra fix io display and shorten evpn zapi packet sizes

bgpd/bgp_vty.c, bgpd/bgpd.c
Please refer to the two commit logs.
=> bgpd: adjust checking return value for commands

bgpd/bgp_vty.c, tests/topotests/bgp_evpn_maximum_prefix/c1/frr.conf, tests/topotests/bgp_evpn_maximum_prefix/c2/frr.conf, tests/topotests/bgp_evpn_maximum_prefix/r1/frr.conf, tests/topotests/bgp_evpn_maximum_prefix/r2/frr.conf, tests/topotests/bgp_evpn_maximum_prefix/test_bgp_evpn_maximum_prefix.py
Closes https://github.com/FRRouting/frr/issues/15720
=> bgpd: Allow using maximum-prefix for EVPN

bgpd/bgp_open.c
RFC5492 says:
This document defines a new Error Subcode, Unsupported Capability.
The value of this Subcode is 7.  The Data field in the NOTIFICATION
message MUST list the set of capabilities that causes the speaker to
send the message.  Each such capability is encoded in the same way as
it would be encoded in the OPEN message.
=> bgpd: Include capabilities when sending NOTIFICATION(7)

bgpd/bgp_vty.c
The 'table-direct' redistribute command is available for ipv4 unicast but not for ipv6 unicast.
Add the command to ipv6 unicast as well.
Fixes: b6367f8460 ("bgpd: add redistribute table-direct support")
=> bgpd: add redistribute table-direct command for ipv6-unicast

bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/15806
=> bgpd: Inherit some peer flags from the peer-group

bgpd/bgp_snmp_bgp4.c, ospfd/ospf_snmp.c
The previous code was correct even if the coverity scanner was                                       
complaining.                                                                                         
Fixes: https://github.com/FRRouting/frr/issues/15680
=> bgpd, ospfd: fix non increasing SNMP OID

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_ecommunity.c, bgpd/bgp_ecommunity.h, bgpd/bgp_mpath.c, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_routemap_nb_config.c, bgpd/bgp_vty.c, bgpd/bgp_zebra.c, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, lib/routemap_cli.c, lib/zclient.c, lib/zclient.h, tests/topotests/bgp_extended_link_bandwidth/r1/frr.conf, tests/topotests/bgp_extended_link_bandwidth/r2/frr.conf, tests/topotests/bgp_extended_link_bandwidth/test_bgp_extended_link_bandwidth.py, tests/topotests/bgp_link_bw_ip/r2/bgp-route-3.json, tests/topotests/bgp_link_bw_ip/r5/bgpd.conf, yang/frr-bgp-route-map.yang, zebra/zapi_msg.c
Closes https://github.com/FRRouting/frr/issues/15575
=> bgpd: Implement extended link-bandwidth

doc/user/isisd.rst
Remove a few obsoleted isis commands based on code.  And correct one example.
=> doc: clean up a few commands for isis

bgpd/bgp_vty.h, lib/resolver.c, ospf6d/ospf6_intra.c
FreeBSD 13 complains about a bunch of things. Pick up the fixes necessary to make the build work.
=> 8.4: cherry-pick build fixes

bgpd/bgp_attr.c, bgpd/bgp_attr.h, bgpd/bgp_packet.c, ospfd/ospf_te.c
CVE-2023-47234, CVE-2023-47235, and CVE-2024-27913
=> 8.4: backport #15431 and #14716

bgpd/bgp_fsm.c, bgpd/bgpd.c
Closes https://github.com/FRRouting/frr/issues/15880
=> bgpd: Apply NOOP when doing negative commands for GR operations

doc/user/pim.rst, doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_ifchannel.c, pimd/pim_register.c, pimd/pim_upstream.c, pimd/pim_upstream.h, yang/frr-pim.yang
cf. #15969, just the first 3 commits with fixes separately
=> pimd: fixes split off from #15969

mgmtd/mgmt_be_adapter.c
- also add missing rpc client accounting bug in same diagnostic command.
=> mgmtd: add missing diagnostic show cmd output (notify maps)

doc/user/pim.rst, doc/user/pimv6.rst, pimd/pim6_cmd.c, pimd/pim_cmd.c, pimd/pim_ifchannel.c, pimd/pim_register.c, pimd/pim_upstream.c, pimd/pim_upstream.h, yang/frr-pim.yang
=> pimd: fixes split off from #15969 (backport #15975)

doc/user/ripngd.rst, doc/user/routemap.rst, lib/routemap_cli.c, tests/topotests/bgp_route_map_match_tag_untagged/r1/frr.conf, tests/topotests/bgp_route_map_match_tag_untagged/test_bgp_route_map_match_tag_untagged.py, yang/frr-route-map.yang
Closes https://github.com/FRRouting/frr/issues/15852
=> lib: Allow doing match/set tag untagged

tests/topotests/grpc_basic/test_basic_grpc.py, tests/topotests/lib/grpc-query.py
- Add separate get, get-config, get-state operations to query command, as well as switching default output to JSON.
- Add an `--xml` to change the output format.
- move printss to logging.debug so output is a machine parseable result.
=> tests: improve the grpc query client and topotest

doc/user/zebra.rst
See individual commits, clean up documentation a tiny bit
=> Show ip route summary

isisd/isis_spf.c, isisd/isis_sr.c
Fix a crash with "show isis route algorithm X"
Fix display of "show isis" commands
=> isisd: fix show isis algorithm

bgpd/bgp_ecommunity.c
Not yet released, but we should definitely get this in before releasing 10.1.
=> bgpd: Make sure we have enough data to handle extended link bandwidth

bgpd/bgp_packet.c
Closes https://github.com/FRRouting/frr/issues/16126
=> bgpd: Send End-of-RIB not only if Graceful Restart capability is received

zebra/dplane_fpm_nl.c
The FPM dataplane plugin does a length check for incoming messages, but it tests against the top-level netlink message header size. That isn't included in the netlink message length encoding. In the case of the ROUTE message, validate incoming message length against correct (struct rtmsg) len, not top-level netlink message header size.
=> zebra: fix incoming FPM message length validation

doc/developer/mgmtd-dev.rst, doc/user/mgmtd.rst, mgmtd/mgmt_be_adapter.c
doc: add some text on native message API and notif xpath array
=> mgmtd: add empty notif xpath map for completeness

doc/user/ldpd.rst
Correct one ldp command based on code.
=> doc: fix one ldp neighbor command

lib/zclient.c, tests/topotests/bgp_weighted_ecmp_recursive/r1/frr.conf, tests/topotests/bgp_weighted_ecmp_recursive/r2/frr.conf, tests/topotests/bgp_weighted_ecmp_recursive/r3/frr.conf, tests/topotests/bgp_weighted_ecmp_recursive/r4/frr.conf, tests/topotests/bgp_weighted_ecmp_recursive/r5/frr.conf, tests/topotests/bgp_weighted_ecmp_recursive/test_bgp_weighted_ecmp_recursive.py, zebra/zebra_nhg.c
Closes https://github.com/FRRouting/frr/issues/16235
=> zebra: Set the weight for non-recursive next-hop

yang/frr-zebra.yang
=> yang: Added default value to leaf

doc/user/pim.rst, doc/user/pimv6.rst
Complete a few pim commands in documents.
=> doc: adjust some commands for pim/pimv6 bsr

yang/frr-bfdd.yang
Fixed warnings at frr-bfdd yang file
=> yang: Fixed pyang warnings at frr-bfdd yang file

tests/topotests/msdp_topo2/r1/bgpd.conf, tests/topotests/msdp_topo2/r1/pimd.conf, tests/topotests/msdp_topo2/r1/zebra.conf, tests/topotests/msdp_topo2/r2/bgpd.conf, tests/topotests/msdp_topo2/r2/pimd.conf, tests/topotests/msdp_topo2/r2/zebra.conf, tests/topotests/msdp_topo2/r3/bgpd.conf, tests/topotests/msdp_topo2/r3/pimd.conf, tests/topotests/msdp_topo2/r3/zebra.conf, tests/topotests/msdp_topo2/r4/bgpd.conf, tests/topotests/msdp_topo2/r4/pimd.conf, tests/topotests/msdp_topo2/r4/zebra.conf, tests/topotests/msdp_topo2/r5/bgpd.conf, tests/topotests/msdp_topo2/r5/pimd.conf, tests/topotests/msdp_topo2/r5/zebra.conf, tests/topotests/msdp_topo2/test_msdp_topo2.py
Adding a MSDP test with multiple possible routes.
=> tests: Test MSDP RPF

tests/topotests/bfd_bgp_cbit_topo3/r1/bgpd.conf, tests/topotests/bfd_bgp_cbit_topo3/r3/bgpd.conf, tests/topotests/bgp_prefix_list_any/r1/bgpd.conf, tests/topotests/bgp_prefix_list_any/r2/bgpd.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop/r1/bgpd.conf, tests/topotests/bgp_route_map_match_ipv6_nexthop/r2/bgpd.conf, tests/topotests/route_scale/scale_test_common.py
See individual commits.  Just some changes to make the tests flow smoother
=> Test timing fixes

babeld/babel_interface.c, babeld/babel_interface.h, babeld/babel_main.c, babeld/babeld.c, babeld/babeld.h, pbrd/pbr_vrf.c
=> More memory leaks on shutdown

bgpd/bgp_evpn.c
Fix a duplicated test clause - cut-and-paste mistake, maybe?
=> bgpd: fix duplicated test clause

tools/frr-reload.py
fix usage of regex string without proper escaping
=> tools: fix invalid escape on regex string

bgpd/bgp_zebra.c
Fixes: https://github.com/FRRouting/frr/issues/16747
=> bgpd: Retry connecting to label manager if failed

ospfd/ospf_packet.c
When an ospf interface is not in the backbone area, but it receives a packet from the backbone, no logs are generated for this mismatch. However, the opposite scenario does generate logs. Add a log for this case.
=> ospfd: logging behavior for area id mismatches

ospfd/ospf_zebra.c
This file had a bunch of debugs that were operating on specific vrf's but not telling you which vrf this was happening in.  Add code to allow operator debugging to understand what vrf is being worked on.
=> ospfd: Add vrf name to debug functions in ospf_zebra.c

tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py
Remove duplicate check_ping import
=> tests: Remove duplicate `check_ping` import

tests/topotests/zebra_seg6local_route/r1/routes.json, tests/topotests/zebra_seg6local_route/test_zebra_seg6local_route.py
Add new testcases to verify SRv6 End.DX6, End.DT4 and End.DT6 behaviors.
=> tests: Add more SRv6 testcases

pimd/pim_iface.c
In `pim_if_addr_add()`, some code inside `PIM_IPV == 4` ( the case of `igmp->mtrace_only` ) wrongly accepts ipv6 address.
So, clearly add IPV4 check.
=> pimd: fix missing IPV4 check

bgpd/bgp_main.c, doc/user/bgp.rst
Related: https://github.com/FRRouting/frr/issues/16969
=> bgpd: Actually make ` --v6-with-v4-nexthops` it work

bfdd/bfdd_cli.c, lib/bfd.h
Continue the work of b70835d690 ("bfdd: add no variants to interval configurations")
=> bfdd: add no variants to all configurations

bgpd/bgp_bmp.c
Export labels to pre-policy BMP
=> bgpd: export labels to pre-policy bmp

doc/user/bgp.rst, tests/topotests/bgp_as_override/test_bgp_as_override.py
=> doc: clarify bgp as-override

tests/topotests/lib/common_check.py
For some reason this was missing.
=> tests: iproute2_check_path_selection call the actual command

bgpd/bgp_fsm.c, bgpd/bgp_io.c, ldpd/ldpe.c, lib/defun_lex.l, lib/netns_linux.c, lib/ptm_lib.c, lib/zclient.h, lib/zlog_5424_cli.c, pimd/pim6_mld.c, pimd/pim_autorp.c, pimd/pim_bsr_rpdb.c, vtysh/vtysh.c, zebra/ipforward_proc.c, zebra/zebra_dplane.c, zebra/zebra_nb_state.c, zebra/zebra_netns_id.c, zebra/zebra_netns_notify.c
```
scan-build: Analysis run complete.
scan-build: Removing directory '/tmp/scan-build-2024-10-16-130506-210976-1' because it contains no reports.
scan-build: No bugs found.
```
Refer to individual commits for details.
Haven't checked random weird build configurations so there might still be an issue or two on different platforms and/or build options.
=> *: fix clang-19 SA

doc/user/evpn.rst
=> docs: Update evpn.rst

lib/frrscript.c, lib/frrscript.h, zebra/zebra_vty.c
Closes https://github.com/FRRouting/frr/issues/17161
=> lib, zebra: Keep `zebra on-rib-process script` in frr.conf

sharpd/sharp_vty.c, sharpd/sharp_zebra.c, sharpd/sharp_zebra.h, zebra/dplane_fpm_nl.c, zebra/rt_netlink.c, zebra/rt_socket.c, zebra/zebra_rib.c
mergifyio failed to backport https://github.com/FRRouting/frr/pull/17279 to dev/10.2 because there was a commit that removed a srcdest_XXX call that was not needed that happen to be in a hunk that these series of patches also modified.  That commit is not a bug fix per say so it did not get backported.  This just fixes that problem, I will close #17279
=> Mrib nht wonky (backport #17254)

bgpd/bgp_clist.c, bgpd/bgp_clist.h
Closes https://github.com/FRRouting/frr/issues/17233
=> bgpd: Treat numbered community-list only if it's in a range 1-500

bgpd/bgp_fsm.c, bgpd/bgp_route.c, tests/topotests/bgp_addpath_graceful_restart/r1/frr.conf, tests/topotests/bgp_addpath_graceful_restart/r2/frr.conf, tests/topotests/bgp_addpath_graceful_restart/r3/frr.conf, tests/topotests/bgp_addpath_graceful_restart/test_bgp_addpath_graceful_restart.py, tests/topotests/bgp_addpath_llgr/r1/frr.conf, tests/topotests/bgp_addpath_llgr/r2/frr.conf, tests/topotests/bgp_addpath_llgr/r3/frr.conf, tests/topotests/bgp_addpath_llgr/test_bgp_addpath_llgr.py
Closes https://github.com/FRRouting/frr/issues/17372
=> bgpd: Clear stale routes with multiple paths

bgpd/bgp_route.c
Some very very minor optimizations for bgp_withdraw and bgp_update
=> Bgp withdraw and unlikely

bgpd/bgp_bfd.c
Closes https://github.com/FRRouting/frr/issues/17337
=> bgpd: Reset BGP session only if it was a real BFD DOWN event

doc/developer/topotests.rst, tests/topotests/Dockerfile, tests/topotests/docker/README.md, tests/topotests/docker/frr-topotests.sh, tests/topotests/docker/inner/compile_frr.sh, tests/topotests/docker/inner/entrypoint.sh
Fixes below foobar:
```
make topotests-build
make topotests
```
Closes https://github.com/FRRouting/frr/issues/17499
=> Fix docker image for topotests

tests/topotests/bgp_max_med_on_startup/r1/bgpd.conf, tests/topotests/bgp_max_med_on_startup/test_bgp_max_med_on_startup.py, tests/topotests/ospfapi/test_ospf_clientapi.py
see individual commits but some minor tweaking to fix the occassional error we are seeing
=> two test cleanups

zebra/zebra_vxlan.c, zebra/zebra_vxlan_if.c
Fix up couple of style issues missed in
PR 17483
=> zebra: EVPN fix code style in vlan vni map debugs

lib/zclient.c
Currently the zapi reconnection is once every 10 seconds for the first 3 times and then once every 60 seconds from then on out.  We are seeing interesting behavior under loaded systems where zebra is just slow to come up and daemons are spending a long time waiting to connect.  Let's just make things a bit more aggressive.
Change the code to attempt to reconnect once every second for 30 seconds and then change to once every 5 seconds from then on out.
This should help with non-integrated configuration on system startup.
=> lib: Speed up reconnection attempts for zapi

bgpd/bgp_zebra.c, bgpd/bgpd.h, tests/topotests/bfd_profiles_topo1/r2/bgpd.conf, tests/topotests/bfd_profiles_topo1/r3/bgpd.conf, tests/topotests/bfd_profiles_topo1/r4/bgpd.conf
=> Bfd shared network

zebra/zebra_rib.c
=> zebra: use macro for one check

bgpd/bgp_mplsvpn.c, tests/topotests/bgp_vpnv4_import_allowas_in/r1/frr.conf, tests/topotests/bgp_vpnv4_import_allowas_in/r2/frr.conf, tests/topotests/bgp_vpnv4_import_allowas_in/test_bgp_vpnv4_import_allowas_in.py
Closes https://github.com/FRRouting/frr/issues/17607
=> bgpd: Import allowed routes with self AS if desired

zebra/zebra_nhg.c
Upon if_down, we don't reset the valid flag for dependents and unset the INSTALLED flag.
So when its time for the NHG to be deleted (routes dereferenced), zebra deletes it since refcnt goes to 0, but stale NHG remains in kernel.
Ticket :#4200788
=> zebra: Fix resetting valid flags for NHG dependents

tests/topotests/mgmt_oper/oper.py, tests/topotests/mgmt_oper/test_oper.py
Test for presence of IPv6 kernel routes too.
=> tests: improve test reliability

lib/mgmt_be_client.c, lib/mgmt_be_client.h, lib/mgmt_msg_native.h, tests/topotests/lib/fe_client.py
Add support for adds deletes and patch to support datastore notifications.
=> New YANG notify msg fmt

bgpd/bgp_debug.c, bgpd/bgp_debug.h, bgpd/bgp_route.c, doc/user/bgp.rst
Add a new debug command:
debug bgp aggregate [prefix <A.B.C.D/M|X:X::X:X/M>]
=> bgpd: add a debug command for route aggregation

lib/if.c
=> lib: remove interface dead code

lib/plist.c
=> bgpd: fix crash in displaying json orf prefix-list

zebra/zebra_nhg.c
During route processing in zebra, Zebra will create a nexthop group that matches the nexthops passed down from the routing protocol.  Then Zebra will look to see if it can re-use a nhe from a previous version of the route entry( say a interface goes down ).  If Zebra decides to re-use an nhe it was just dropping the route entry created.  Which led to nexthop group's that had a refcount of 0 and in some cases these nexthop groups were installed into the kernel.
Add a bit of code to see if the returned entry is not being used and it has no reference count and if so, properly dispose of it.
=> zebra: Fix leaked nhe

tests/topotests/bgp_srv6_sid_reachability/test_bgp_srv6_sid_reachability.py, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf3/test_bgp_srv6l3vpn_to_bgp_vrf3.py
Some issues I found while running tests at home.
=> 2 test fixes

zebra/zebra_nhg.c
See individual commits.  Just some more nexthop group bugs
=> Active routes are active

bgpd/bgp_packet.c, bgpd/bgp_packet.h, bgpd/bgp_vty.c, bgpd/bgpd.c, tests/topotests/bgp_dynamic_capability/r1/frr.conf, tests/topotests/bgp_dynamic_capability/r2/frr.conf, tests/topotests/bgp_dynamic_capability/test_bgp_dynamic_capability_enhe.py
This was missed and asked in Slack that it would be useful. 
=> frrbot skipped intentional.
=> bgpd: Handle ENHE capability via dynamic capability

lib/mgmt_be_client.c, lib/northbound.c, lib/northbound.h, lib/northbound_notif.c, lib/yang.c, lib/yang.h, mgmtd/mgmt_be_adapter.c, mgmtd/mgmt_fe_adapter.c, mgmtd/mgmt_testc.c, tests/topotests/mgmt_notif/test_ds_notify.py, tests/topotests/mgmt_notif/test_notif.py
- also improve error handling and remove a cleanup memleak
=> Handle datastore notifications correctly in backend clients (daemons)

tests/topotests/bgp_rpki_topo1/r2/bgp_rpki_valid.json
Remove table version check in bgp rpki topo1.
Fixes: 5f50b98f8e ("tests: add bgp rpki topo1 rpkiValidationState")
=> tests: remove table version check in bgp rpki topo1

bgpd/bgp_updgrp.c, tests/topotests/bgp_peer_solo/r1/frr.conf, tests/topotests/bgp_peer_solo/r2/frr.conf, tests/topotests/bgp_peer_solo/test_bgp_peer_solo.py
A topotest supporting suggested change: https://github.com/FRRouting/frr/pull/17910
=> bgpd: Fix bgp peer solo option

bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgp_packet.c, bgpd/bgpd.h, zebra/kernel_netlink.c
2 deadlock fixes backport to 10.1
=> Backport 17229 some to 10 1

bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgp_packet.c, bgpd/bgpd.h, zebra/kernel_netlink.c
see individual commits but backport 2 mutex issues
=> Backport 17229 some to 10 2

bgpd/bgp_fsm.c, bgpd/bgp_network.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_ipv6_ll_peering/r1/bgpd.conf, tests/topotests/bgp_ipv6_ll_peering/r1/zebra.conf, tests/topotests/bgp_ipv6_ll_peering/r3/bgpd.conf, tests/topotests/bgp_ipv6_ll_peering/r3/zebra.conf, tests/topotests/bgp_ipv6_ll_peering/test_bgp_ipv6_ll_peering.py
Closes https://github.com/FRRouting/frr/issues/17955
=> bgpd: Do not start BGP session if BGP identifier is not set

bgpd/bgp_route.c, tests/topotests/bgp_oad/r3/frr.conf, tests/topotests/bgp_oad/test_bgp_oad.py
Revert https://github.com/FRRouting/frr/pull/18012, it was mistakenly merged with conflicts.
=> Fix 10.0 branch

doc/developer/sbfd.rst, doc/user/sbfd.rst
=> doc: fix sbfd.rst doc warnings

babeld/babeld.c
Improve code clarity and maintainability
=> babeld: Improve code clarity and maintainability

pbrd/pbr_zebra.c, zebra/zapi_msg.c
See individual commits.  Was trying to debug some stuff that had tableids and found it was `fun`
=> Vrf tableid debugs

bgpd/bgp_bfd.c, bgpd/bgp_nexthop.c, bgpd/bgp_zebra.c
Closes https://github.com/FRRouting/frr/issues/17860
=> bgp/bfd backports for stable/10.0

bgpd/bgp_route.c
Factorize bgp_table_cleanup(). Cosmetic change. It will help adding AFI / SAFI in the future.
=> bgpd: factorize bgp_table_cleanup()

bgpd/bgpd.c, tests/topotests/bgp_l3vpn_hidden/ce1/frr.conf, tests/topotests/bgp_l3vpn_hidden/ce1/show_bgp_ipv4_unicast.json, tests/topotests/bgp_l3vpn_hidden/ce1/show_bgp_ipv4_unicast_step1.json, tests/topotests/bgp_l3vpn_hidden/ce1/show_bgp_ipv6_unicast.json, tests/topotests/bgp_l3vpn_hidden/ce1/show_bgp_ipv6_unicast_step1.json, tests/topotests/bgp_l3vpn_hidden/ce1/show_bgp_summary.json, tests/topotests/bgp_l3vpn_hidden/pe1/frr.conf, tests/topotests/bgp_l3vpn_hidden/pe1/show_bgp_ipv4_vpn.json, tests/topotests/bgp_l3vpn_hidden/pe1/show_bgp_ipv6_vpn.json, tests/topotests/bgp_l3vpn_hidden/pe1/show_bgp_summary.json, tests/topotests/bgp_l3vpn_hidden/rr1/frr.conf, tests/topotests/bgp_l3vpn_hidden/rr1/show_bgp_ipv4_vpn.json, tests/topotests/bgp_l3vpn_hidden/rr1/show_bgp_ipv6_vpn.json, tests/topotests/bgp_l3vpn_hidden/rr1/show_bgp_summary.json, tests/topotests/bgp_l3vpn_hidden/test_bgp_l3vpn_hidden.py, tests/topotests/bgp_vrf_route_leak_basic/r1/bgpd.conf, tests/topotests/bgp_vrf_route_leak_basic/test_bgp-vrf-route-leak-basic.py
backport of https://github.com/FRRouting/frr/pull/18119
=> bgpd: fix default instance when leaving the hidden state (backport 10.3)

bgpd/bgpd.c
=> Revert "bgpd: release manual vpn label on instance deletion (backport #18121)"

yang/frr-route-types.yang
Corrected Pyang errors or warnings at frr-route-types.yang file
=> yang: Corrected Pyang errors or warnings

lib/northbound_oper.c, tests/lib/northbound/test_oper_data.in, tests/lib/northbound/test_oper_data.refout
Add additional unit-test cases to cover the found issues
=> Fix oper-state queries that involve choice/case nodes

yang/frr-affinity-map.yang
Imported modules are not in use
=> yang: Imported modules are not in use

pimd/pim6_mld.c
When receiving MLD messages, prefer pktinfo over msghdr.msg_name for determining the source interface. The latter is just the VRF master interface in case of VRF and we need the true interface the packet was received on instead.
=> pimd: Fix PIM6 MLD VRF support (use recvmsg() pktinfo)

bgpd/bgp_keepalives.c
This reverts commit 23bdaba147517abb4a70d03166ad74f759888d46.
=> Revert "bgpd: Make keepalive pthread be connection based."

doc/developer/building.rst, doc/developer/index.rst, doc/developer/lists.rst, doc/user/protocols.rst
Cleanup some doc issues I noticed as well as add some typesafe conversion stuff
=> Documentation typesafe

zebra/interface.c, zebra/zebra_vxlan_if.c
=> Clean up some code and bad assumptions in zebra

yang/frr-bgp-common.yang
Fixed pyang errors at frr-bgp-common.yang
=> yang: Fixed pyang errors at frr-bgp-common.yang

zebra/fpm_listener.c
The fpm_listener didn't have the ability to specify the output file location at all.  Modify the code to accept this.
=> zebra: add ability to specify output file with fpm_listener

bgpd/bgp_fsm.c, bgpd/bgp_network.c, bgpd/bgp_nexthop.c, bgpd/bgp_zebra.c, bgpd/bgpd.c, bgpd/bgpd.h
Closes https://github.com/FRRouting/frr/issues/18408
=> bgpd: Print the real reason why the peer is not accepted (incoming)

tests/topotests/lib/pim.py
Corrected input dict at pim.py
=> tests: Corrected input dict at pim.py

tests/topotests/zebra_operational_data/test_zebra_operational.py, yang/frr-zebra.yang, zebra/zebra_nb.c, zebra/zebra_nb.h, zebra/zebra_nb_state.c
=> More yang state

tests/topotests/all_protocol_startup/test_all_protocol_startup.py, zebra/zebra_nhg.c
Trigger:
Imagine a route utilizing an NHG with six nexthops (Intf swp1-swp6). If interfaces swp1-swp4 flaps, the NHG remains the same but now only references two nexthops (swp5-6) instead of all six. This behavior occurs due to how NHGs with recursive nexthops are managed within Zebra.
In the scenario below, NHG 370 has all six nexthops installed in the kernel. However, Zebra maintains a list of recursive NHGs that NHG 370 references i.e., Depends: (371), (372), (373) which are not directly installed in the kernel.
- When an interface comes up, its nexthop and corresponding dependents are installed.
- These dependents (counterparts to 371-373) are non-recursive and are installed as well.
- However, when attempting to install the recursive ones in zebra_nhg_install_kernel(), they resolve …
=> zebra: Fix reinstalling nexthops in NHGs upon interface flaps

zebra/fpm_listener.c
See individual commits:
a) Add a timestamp to output so we can watch time move around
b) Add ability to cause all routes to be offload failed
=> Fpm listener reject

zebra/main.c, zebra/redistribute.c, zebra/router-id.c, zebra/zapi_msg.c, zebra/zebra_gr.c, zebra/zebra_mlag.c, zebra/zebra_ptm.c, zebra/zebra_ptm_redistribute.c, zebra/zebra_router.h, zebra/zebra_srv6.c, zebra/zebra_srv6_vty.c, zebra/zebra_vrf.c, zebra/zserv.c, zebra/zserv.h
Convert over to a typesafe list for the client list and stale client list
=> Typesafe zclient

tests/topotests/lib/common_check.py
Catch specific exceptions and handle them accordingly
=> tests: Catch specific exceptions

yang/frr-eigrpd.yang
Code inline with RFC 8407 rules
Corrected pyang errors and warnings.
=> yang: Code inline with RFC 8407 rules

lib/filter_cli.c
Closes https://github.com/FRRouting/frr/issues/18493
=> lib: Return duplicate prefix-list entry test

bgpd/bgp_route.c
Fix a possible use-after-free in the recent bgp batch clearing code, CID 1639091. Capture the "last" prefix we've processed, instead of deref'ing a bgp dest struct.
=> bgpd: fix SA warning in bgp clearing code

tests/topotests/lib/exa-receive.py
Handling potential errors gracefully at exa-receive.py
=> tests: Handling potential errors gracefully

eigrpd/eigrp_dump.c, eigrpd/eigrp_filter.c, eigrpd/eigrp_fsm.c, eigrpd/eigrp_hello.c, eigrpd/eigrp_interface.c, eigrpd/eigrp_interface.h, eigrpd/eigrp_main.c, eigrpd/eigrp_neighbor.c, eigrpd/eigrp_neighbor.h, eigrpd/eigrp_network.c, eigrpd/eigrp_network.h, eigrpd/eigrp_northbound.c, eigrpd/eigrp_packet.c, eigrpd/eigrp_query.c, eigrpd/eigrp_reply.c, eigrpd/eigrp_routemap.c, eigrpd/eigrp_structs.h, eigrpd/eigrp_topology.c, eigrpd/eigrp_update.c, eigrpd/eigrp_vty.c, eigrpd/eigrp_zebra.c, eigrpd/eigrp_zebra.h, eigrpd/eigrpd.c, eigrpd/eigrpd.h, lib/if.c, lib/if.h
See individual commits, but convert some data types to typesafe and cleanup memory issues being seen on shutdown.
=> Eigrp typesafe

tests/topotests/lib/send_bsr_packet.py
Fix potential issues at send_bsr_packet.py
=> tests: Fix potential issues at send_bsr_packet.py

bgpd/bgp_fsm.c, bgpd/bgp_io.c, bgpd/bgp_io.h, bgpd/bgp_main.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/high_ecmp/r1/frr.conf, tests/topotests/high_ecmp/r1/frr_ipv4_bgp.conf, tests/topotests/high_ecmp/r1/frr_ipv6_bgp.conf, tests/topotests/high_ecmp/r1/frr_unnumbered_bgp.conf, tests/topotests/high_ecmp/r2/frr.conf, tests/topotests/high_ecmp/r2/frr_ipv4_bgp.conf, tests/topotests/high_ecmp/r2/frr_ipv6_bgp.conf, tests/topotests/high_ecmp/r2/frr_unnumbered_bgp.conf, zebra/rib.h, zebra/zebra_rib.c, zebra/zserv.c
The first 7 commits are another PR.  No way I could test this without those changes..  In look at the last 3 commits to see what is going on.  Once the other PR goes in I'll rebase/force push
=> Bgp packet reads conversion to a FIFO

yang/frr-zebra.yang
Corrected pyang warnings or errors in frr-zebra.yang
=> yang: Corrected pyang errors in frr-zebra.yang

tests/topotests/all_protocol_startup/test_all_protocol_startup.py
Fix resource leaks in test_all_protocol_startup.py
=> tests: Resource leaks in test_all_protocol_startup

staticd/static_zebra.c, tests/topotests/static_srv6_sids/test_static_srv6_sids.py
Currently, when the locator block and sid block differs, staticd would still go ahead and request zebra to allocate the SID which it does if there is atleast one match (from any locators).
Only when staticd tries to install the route, it sees that the locator block and sid block are different and avoids installing the route.
Fix:
Check if the locator block and sid block match before even requesting Zebra to allocate one.
=> staticd: Avoid requesting SRv6 sid from zebra when loc and sid block dont match

babeld/babeld.c, babeld/babeld.h
Add checking for port == 6696.
=> babeld: check valid babel port

yang/frr-bfdd.yang
Corrected pyang errors in frr-bfdd.yang
=> yang: Pyang errors in frr-bfdd.yang

tools/generate_support_bundle.py
Adding a `-N` pathspace option to the generate_support_bundle.py to support FRR running in a 
non-default namespace with a prefix on the config/socket options.
The same pathspace will be prepended to the output log files (if specified)
```
usage: generate_support_bundle.py [-h] [-c CONFIG] [-l LOG_DIR] [-N PATHSPACE]
optional arguments:
-h, --help            show this help message and exit
-c CONFIG, --config CONFIG
input config
-l LOG_DIR, --log-dir LOG_DIR
directory for logfiles
-N PATHSPACE, --pathspace PATHSPACE
Insert prefix into config & socket paths
```
=> tools: Add pathspace option to generate_support_bundle

tests/topotests/lib/mcast-tester.py
Fix potential issues in mcast-tester.py
=> tests: Fix potential issues in mcast-tester.py

isisd/isis_tlvs.c
> ==713776==ERROR: LeakSanitizer: detected memory leaks
>
> Direct leak of 120 byte(s) in 1 object(s) allocated from:
>     #0 0x7fdfcbeb4a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
>     #1 0x7fdfcb86f8dd in qcalloc lib/memory.c:105
>     #2 0x55ce707739b6 in isis_tlvs_find_alloc_asla isisd/isis_tlvs.c:8500
>     #3 0x55ce7072fae0 in isis_link_params_update_asla isisd/isis_te.c:191
>     #4 0x55ce70733881 in isis_link_params_update isisd/isis_te.c:499
>     #5 0x55ce70693f2a in isis_circuit_up isisd/isis_circuit.c:776
>     #6 0x55ce7069a120 in isis_csm_state_change isisd/isis_csm.c:135
>     #7 0x55ce7068dd80 in isis_circuit_enable isisd/isis_circuit.c:79
>     #8 0x55ce70699346 in isis_ifp_create isisd/isis_circuit.c:1618
>     #9 …
=> isisd: fix asla memory leak

bgpd/bgp_rpki.c, tests/topotests/bgp_rpki_topo1/test_bgp_rpki_topo1.py
1) Fix a crash found by issuing a `rpki stop` and then checking the cache connection
2) Add some tests for rpki to give a bit more code coverage as found by gcov results
=> Rpki testing and bug fix

bgpd/bgp_pbr.c
=> bgpd: fix pbr memory leaks

isisd/isis_cli.c, pathd/path_cli.c, pimd/pim_cmd.c
Add yang attr to isisd northbound commands
Add yang attr to pathd northbound commands
Add yang attr to pimd northbound commands
=> fix yang commands that don't have yang attr

yang/frr-pathd.yang
Corrected pyang warnings and errors in frr-pathd.yang
=> yang: Corrected pyang errors in frr-pathd.yang

tests/topotests/lib/common_config.py
Address pending changes from PR:18574
=> tests: Resource leak in common_config.py

lib/darr.c, lib/darr.h, lib/mgmt_be_client.c, lib/northbound_notif.c, mgmtd/mgmt_fe_adapter.c, tests/lib/test_darr.c
Improvements:
- Sort the array of selectors and eliminate duplicates
- Validate selectors are valid xpaths
- darr: add binary search macros for arrays of strings
=> Improve notification selectors (sort, eliminate dups)

tests/topotests/lib/lutil.py
Shadowing the built-in function in lutil.py
=> tests: Shadowing the built-in function

doc/user/basic.rst
Try to document the sub-node `line vty` and
what it can do.  Call out the distinction
between vtysh and VTY.
=> doc: line vty was not documented

yang/frr-interface.yang
Fix pyang warnings and errors in frr-interface.yang
=> yang: Fix pyang errors in frr-interface.yang

tests/topotests/lib/topotest.py
Ensure proper handling of resource allocation
=> tests: Proper handling of resource allocation

tests/topotests/lib/bgp.py
Fix Unidiomatic-typecheck in bgp.py
=> tests: Unidiomatic-typecheck in bgp.py

yang/frr-ospfd.yang
Fix pyang errors or warnings in frr-ospfd.yang
=> yang: Fix pyang errors in frr-ospfd.yang

ospf6d/ospf6_main.c, ospfd/ospf_main.c, ripd/rip_main.c, zebra/label_manager.c, zebra/label_manager.h
See individual commits but another round of removing dead code.
=> Remove dead code found

tests/topotests/lib/pim.py
Correct unidiomatic-typecheck in pim.py
=> yang: Correct unidiomatic-typecheck in pim.py

lib/nexthop_group.c, lib/nexthop_group.h, tests/topotests/bgp_weighted_ecmp_recursive/test_bgp_weighted_ecmp_recursive.py, zebra/zebra_vty.c
Show the nexthops count in an NHG
=> zebra: show nexthops count in nexthop-group command

isisd/isis_misc.c, isisd/isis_misc.h
See individual commits but remove dead functions and cleanup the isis_misc.h header
=> Remove unused functions as well as cleanup a header file

eigrpd/eigrp_hello.c
A comment was wrong.  Make it right.
=> eigrpd: Clean up comment to reflect reality

bfdd/bfdd_vty.c
=> bfdd: Adding my discriminator id in show bfd peers counters json

mgmtd/mgmt_fe_adapter.c
The older protobuf session create path didn't set the notify_format value. Set it to the default value in this case.
=> mgmtd: need to set default notify_format for protobuf message too

tests/topotests/lib/pim.py
Fix unreachable code in pim.py
=> tests: Fix unreachable code in pim.py

bgpd/bgp_vty.c, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, bgpd/bgpd.c, bgpd/bgpd.h, doc/user/bgp.rst, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r1/frr.conf, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r1/vrf10_rib_h_encaps_reduced.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r1/vrf20_rib_h_encaps_reduced.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r2/frr.conf, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r2/vrf10_rib.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/r2/vrf20_rib.json, tests/topotests/bgp_srv6l3vpn_to_bgp_vrf/test_bgp_srv6l3vpn_to_bgp_vrf.py
Add a BGP option so that BGP uses the H_Encaps reduced option instead of the default H_Encaps option.
=> Bgp encaps reduced

bgpd/bgp_main.c, bgpd/bgp_vty.c, isisd/isis_main.c, lib/libfrr.h, lib/link_state.c, mgmtd/mgmt_main.c, mgmtd/mgmt_testc.c, zebra/zserv.h
See individual patches, 2 clang-19 cleanups and 1 removal of dead and buried commands.
=> Clang-19 cleanup and removal of scheduled functionality

bgpd/bgp_aspath.c, bgpd/bgp_clist.c, bgpd/bgp_clist.h, bgpd/bgp_filter.c, bgpd/bgp_filter.h, bgpd/bgp_regex.c, bgpd/bgp_regex.h, bgpd/bgp_route.c, bgpd/bgp_routemap.c, bgpd/bgp_vty.c, configure.ac, lib/command.c, lib/event.c, lib/frr_pthread.h, lib/frregex_real.h, lib/frrevent.h, lib/frrstr.c, lib/frrstr.h, lib/memory.c, lib/memory.h, lib/subdir.am, lib/vty.c, lib/vty.h, lib/xref.h
Commit subjects really say it all; hardwiring unnecessary checks and moving things around so they don't affect things in our headers.
=> *: oh no, `config.h` is mobilizing its forces! - 3 of ∞

bgpd/bgp_packet.c, tests/topotests/bgp_mrai_suppress_duplicate/r1/frr.conf, tests/topotests/bgp_mrai_suppress_duplicate/r2/frr.conf, tests/topotests/bgp_mrai_suppress_duplicate/test_bgp_mrai_suppress_duplicate.py
Closes https://github.com/FRRouting/frr/issues/18098
=> bgpd: Force adj-rib-out updates if MRAI is kicked in

tests/topotests/fpm_testing_topo1/test_fpm_topo1.py, zebra/fpm_listener.c
Alllow fpm_listener to dump it's idea of what the nhg's look like too
=> zebra: add ability to dump fpm listener nhg

zebra/zebra_rib.c
If you have a kernel route that would normally be considered as connected, allow it to exist in non vrf table-ids as well as the non-default table.
Fixes: #18952
=> zebra: Allow routes that could be considered connected to exist

zebra/zebra_srv6_vty.c
Currently, `show running-config` displays the `formats`, `format usid-f3216` and `format uncompressed` nodes even if the user does not change any config parameter under those nodes.
This commit cleans up the output of `show running-config` by hiding those nodes when the config under them is the default config.
Example:
```
router# configure
router(config)# segment-routing
router(config-sr)# srv6
router(config-srv6)# locators
router(config-locators)# locator MAIN
router(config-locator)# prefix fcbb:bb01:1::/48
```
Before:
```
router# show running-config
...
srv6
locators
locator MAIN
prefix fcbb:bb01:1::/48
exit
!
exit
!
formats
format usid-f3216
exit
!
format uncompressed-f4024
exit
!
exit
!
exit
!
exit
!
end
```
After:
```
router# show running-config
... …
```
=> zebra: Cleanup SRv6 output of `show running-config`

lib/northbound.c, zebra/zebra_srv6_vty.c
=> Fix some coverity issues

bgpd/bgp_aspath.c, tests/topotests/bgp_set_aspath_replace/test_bgp_set_aspath_replace.py
fix: https://github.com/FRRouting/frr/issues/18990
=> bgpd:fix as-path replace issue with bgp as-path access-list

bgpd/bgp_vty.c, bgpd/bgpd.c, doc/user/bgp.rst, tests/topotests/bgp_local_asn/test_bgp_local_asn_agg.py, tests/topotests/bgp_local_asn_dot/test_bgp_local_asn_dot_agg.py, tests/topotests/bgp_reject_as_sets/r2/bgpd.conf, tests/topotests/lib/bgp.py
<< As a side note: Bird also switched this by default >>
=> bgpd: Reject AS_SET by default

tests/topotests/bgp_peergroup_gshut/test_bgp_peergroup_gshut.py
The test_peer_group_graceful_shutdown_session_stability function was intermittently failing due to premature session flap checks. Stability has been improved by ensuring the BGP session is fully established before verifying the behavior during gshut enable/disable transitions.
=> bgpd: [TOPOTEST] stabilize bgp_peergroup_gshut test case

tests/topotests/nhrp_redundancy/test_nhrp_redundancy.py
See the individual commits, but ping was setup to fail no matter what if any packets are dropped, under heavy system test load, the kernel will drop packets.
=> Nhrp redundancy ping

lib/routemap_cli.c
Fixes: https://github.com/FRRouting/frr/issues/19102
=> lib: Fix `no on-match goto NUM` command

tests/topotests/zebra_operational_data/test_zebra_operational.py
Tests are frequently failing on the zebra_operational_data test.  Modify the code such that it gives up to 30 seconds for the state to transition.
=> tests: Allow time for change of state to propagate

bgpd/bgp_zebra.c, tests/topotests/bgp_wcmp_zebra_link_bandwidth/r1/frr.conf, tests/topotests/bgp_wcmp_zebra_link_bandwidth/r2/frr.conf, tests/topotests/bgp_wcmp_zebra_link_bandwidth/r3/frr.conf, tests/topotests/bgp_wcmp_zebra_link_bandwidth/test_bgp_wcmp_zebra_link_bandwidth.py
Closes https://github.com/FRRouting/frr/issues/19161
=> bgpd: Extract link bandwidth value from extcommunity before using for WCMP

ospfd/ospf_flood.c
ERROR: AddressSanitizer: heap-use-after-free on address 0x60c0001ca478 at pc 0x562dc173c5b9 bp 0x7ffe07f7a260 sp 0x7ffe07f7a258
READ of size 4 at 0x60c0001ca478 thread T0
0 0x562dc173c5b8 in ospf_lsa_lock ospfd/ospf_lsa.c:269
1 0x562dc17242ec in ospf_flood_delayed_lsa_ack ospfd/ospf_flood.c:139
2 0x562dc17242ec in ospf_flood ospfd/ospf_flood.c:553
3 0x562dc1771bba in ospf_ls_upd ospfd/ospf_packet.c:1959
4 0x562dc1771bba in ospf_read_helper ospfd/ospf_packet.c:2926
5 0x562dc1771bba in ospf_read ospfd/ospf_packet.c:2957
6 0x7f615e0dba5f in event_call lib/event.c:2005
7 0x7f615e001781 in frr_run lib/libfrr.c:1252
8 0x562dc170b171 in main ospfd/ospf_main.c:307
9 0x7f615da2c249 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
10 0x7f615da2c304 in __libc_start_main_impl …
=> ospfd: Use after free cleanup of lsa

doc/user/ospf6d.rst, doc/user/ripd.rst, doc/user/ripngd.rst
Found some missing commands in documentation.
=> Doc some missing commands

tools/etc/frr/support_bundle_commands.conf
Add some more data to the support bundles created
=> Support bundle more commands

tests/topotests/bgp_rr_ibgp/test_bgp_rr_ibgp_topo1.py
This test failed locally for me because the looked for route was in a queued state.  Modify the test to ensure that at least tor2 comes up, with a 30 second timeout.  Also modify the test to wait up to 30 seconds to see if the routes are in the rib at all.
=> tests: Fix bgp_rr_ibgp tests

bgpd/bgp_evpn.c, bgpd/bgp_evpn.h, bgpd/bgp_evpn_private.h, bgpd/bgp_evpn_vty.c, bgpd/bgp_zebra.c, bgpd/bgp_zebra.h, doc/user/bgp.rst, lib/vxlan.h, tests/topotests/bgp_evpn_flooding_per_vni/r1/frr.conf, tests/topotests/bgp_evpn_flooding_per_vni/r1/setup.sh, tests/topotests/bgp_evpn_flooding_per_vni/r2/frr.conf, tests/topotests/bgp_evpn_flooding_per_vni/r2/setup.sh, tests/topotests/bgp_evpn_flooding_per_vni/test_bgp_evpn_flooding_per_vni.py, zebra/zebra_evpn.c, zebra/zebra_evpn.h, zebra/zebra_vxlan.c
Closes https://github.com/FRRouting/frr/issues/16154
Thanks @toreanderson for testing this.
=> bgpd: Handle BUM traffic per-VNI

pimd/pim_autorp.c, tests/topotests/pim_autorp/test_pim_autorp.py
=> Fix pim autorp problems

babeld/babel_zebra.c, bgpd/bgp_vty.c, isisd/isis_redist.c, lib/log.c, lib/log.h, lib/route_types.pl, ospf6d/ospf6_asbr.c, ospfd/ospf_vty.c, sharpd/sharp_vty.c, zebra/zebra_nb_state.c, zebra/zebra_vty.c
=> Fix some new coverity issues

lib/prefix.c, lib/prefix.h, tests/topotests/zebra_reserved_ranges/r1/frr.conf, tests/topotests/zebra_reserved_ranges/test_zebra_reserved_ranges.py, zebra/connected.c
Closes https://github.com/FRRouting/frr/issues/19513
=> zebra: Allow assigning any IPv4 addresses on interfaces

bgpd/bgp_debug.c, bgpd/bgp_debug.h, bgpd/bgp_fsm.c, bgpd/bgp_fsm.h, bgpd/bgp_open.c, bgpd/bgp_packet.c, bgpd/bgp_route.c, bgpd/bgp_route.h, bgpd/bgp_vty.c, bgpd/bgp_vty.h, bgpd/bgpd.c, bgpd/bgpd.h, tests/topotests/lib/bgp.py, tests/topotests/lib/common_config.py
Re-opening https://github.com/FRRouting/frr/pull/16343
=> Further enhancements for GR 

bgpd/bgp_mplsvpn.c, bgpd/bgp_route.c, tests/topotests/bgp_srv6l3vpn_sid/test_bgp_srv6l3vpn_sid.py
See individual commits.
Only formatting changes.
=> SRv6/MPLS Coexistence in L3VPN / formatting fixes

isisd/fabricd.c, isisd/isis_pdu.c, ospf6d/ospf6_spf.c, ospfd/ospf_spf.c, pbrd/pbr_zebra.c, pimd/pim_cmd.c, pimd/pim_cmd_common.c, pimd/pim_iface.c, pimd/pim_igmpv3.c, pimd/pim_mroute.c, watchfrr/watchfrr.c
Add explicit int types to some arithmetic expressions where int overflow was possible.
Fixes: #19588
=> Fix int long issues

lib/if.c, lib/vrf.c, lib/vrf.h, lib/zclient.c, zebra/zapi_msg.c
See individual commits but this is just some cleanup .
=> Improve handling of vrf backend type

ospfd/ospf_spf.c, ospfd/ospf_spf.h, ospfd/ospf_ti_lfa.c
=> Revert "ospfd: On cleanup, actually free vertexes"

tests/topotests/lib/common_config.py, tests/topotests/mgmt_oper/oper.py
Corrected unidiomatic-typecheck
=> tests: Corrected unidiomatic-typecheck
